### ISSUE TITLE
[CI] org.elasticsearch.xpack.esql.qa.single_node.EsqlSpecIT failing

### ISSUE THREAD

**Issue by pxsalehi** [elastic/elasticsearch#100081]
There's been a lot of failure for this suite in the past few days, e.g.: https://gradle-enterprise.elastic.co/s/ho4zlyo4xtu4g/tests/overview?outcome=failed

Failure history: https://gradle-enterprise.elastic.co/scans/tests?search.buildOutcome=failure&search.timeZoneId=Europe/Berlin&tests.container=org.elasticsearch.xpack.esql.qa.single_node.EsqlSpecIT

**Comment by luigidellaquila** [comment]
This issue was due to a spike of failures all related to memory management (unreleased circuit breakers)

<img width="832" alt="Screenshot 2023-10-17 alle 10 05 01" src="https://github.com/elastic/elasticsearch/assets/459289/2ce91746-2bb1-4ca3-9210-a640a047c544">

These problems were fixed with a series of PRs (see meta-issue https://github.com/elastic/elasticsearch/issues/99826) and that kind of failure does not seem to happen anymore. In last 10 days EsqlSpecIT failed only once, but with a completely different way (it seems to be a cluster failure, probably as a consequence of other failures).
