### ISSUE TITLE
Improve node exclusioin performance (enhancement)

### ISSUE THREAD

**Issue by linker-c** [elastic/elasticsearch#100037]
### Description

When we add a node to the exclusion list, the intend is often to removing that node.
It seems a waste of time moving/recover backup shards on that node at this point.
Would it be possible to:

1. switch any primary shard located on this excluded node immediately.  Making one of the backup shard in other node the primary.
2. drop all backup shards on this excluded node.  (new backup shards should be created somewhere else immediately).
3. recover any primary shards still exist on the excluded node.

The idea is to clear data on this excluded node ASAP.  This will shorten the node replacement cycle, which in term improves the overall cluster's maintainability.

**Comment by DaveCTurner** [comment]
> new backup shards should be created somewhere else immediately

The problem with this proposal is that this cannot happen _immediately_ - creating new shard copies takes a significant amount of time and effort. If you really would prefer to drop all the shards on a node without waiting for those shards to recover elsewhere first, then you can do that by simply shutting down the node and letting Elasticsearch recover the data elsewhere later.

**Comment by linker-c** [comment]
True, but moving backup shards also take time.  My thinking is that it's almost equivalent.  I understand the one main (and important) difference is that index won't have backup shard.  I also know we can drop backup manually, but it'll be too tedious to figure out which indices are in that node, etc.  Maybe a flag we can configure dynamically at run time?

**Comment by DaveCTurner** [comment]
> True, but moving backup shards also takes time. My thinking is that they are almost equivalent.

I think they are completely equivalent. It's the same process.

> Maybe a flag we can configure dynamically at run time?

I don't think we need a flag for this. If you don't want to wait for a node to completely vacate before shutting it down then that's fine, just shut it down without waiting. It puts your data at risk for a while because some shard copies will become unassigned, but that's what you seem to want.

**Comment by linker-c** [comment]
It's the difficulty in managing such approach I am hoping to simplify.  I just wish to have a way to drop data from this excluded node ASAP.  Moving backup shards keep the copy in the node until it's moved.  Plus it takes up a slot in recovery task, which is wasteful imo.  This is where the time can be more efficiently used.  Imagine I have 100+ shards on that node, to manually drop backup requires me to get a list of indices on that node first, then change settings on them (assuming the cluster doesn't move new index into that excluded node.  This is another issue I am having...).  It's too complicated, hence this request.
If ES can automatically just assign primary shards out of the node and drop all backups, it'll take much shorter time to clean out the node to be replaced.

Thanks.

**Comment by DaveCTurner** [comment]
I am still not understanding your objection to just shutting down the node without waiting for any shard movements.

**Comment by linker-c** [comment]
Sorry.  Missed that part.  
More potential cascading issues.  Not all primary shards are moved out of the nodes.  So the recovery is more complicated.  If there's a way to immediately switch primary shards away from the excluded node, then it's an option I would try.

**Comment by DaveCTurner** [comment]
Stopping the node while it holds primary shards will immediately promote replicas on other nodes to primary.

I'm going to close this issue because we're having trouble determining whether there's any action needed by the Elasticsearch team or whether it's more of a user question and surrounding discussion. We'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. If the discussion on the forum gives rise to a more precise description of the problem you're looking to solve, with some specific actions for the ES team, then we can bring them back here. But for now, I hope you don't mind that I close this.
