### ISSUE TITLE
[ES|QL] Inconsistent unknown column message with suggestion

### ISSUE THREAD

**Issue by dej611** [elastic/elasticsearch#100137]
**Describe the feature:**

Given an index with a `bytes` field, if I submit the following ESQL query:

```
from my-index | keep bytess
```

I receive the error message: `Unknown column [bytess]`.
But If I perform a `keep` operation before, then the same error comes back enriched with column suggestion:

```
from my-index | keep bytes | keep bytess
```

I receive the error message: `Unknown column [bytess], did you mean [bytes]`?

**Comment by astefan** [comment]
@dej611 this is the expected behavior following this change https://github.com/elastic/elasticsearch/pull/98987.

In other words, to be as performant as possible when issuing a `field_caps` call (which can be very heavy in large clusters/indices), we only ask for the fields that we can extract from the query. Such a drawback, like the one you very well identified, is a consequence of the performance gain we get instead of having the most helpful and correct error message.

Given this explanation, which I hope is satisfactory, I will go ahead and close this report.
