### ISSUE TITLE
Add min_doc_count support to range aggregations

### ISSUE THREAD

**Issue by halilim** [elastic/elasticsearch#10027]
Currently, range aggregations doesn't have `min_doc_count` support AFAIK. As a temporary solution client-side filtering could be used but being able to filter out empty buckets from range aggregations (and from other aggregations if possible) would be neater.

**Comment by jpountz** [comment]
This is something we started discussing on https://github.com/elastic/elasticsearch/issues/8110. The issue has been closed since it probably had too much scope, but essentially we are thinking/working on adding the ability to do more stuff at reduce time (when all shard responses get merged) and filtering of the reduced buckets could certainly be done this way. Hopefully this would also allow to have a single way to filter buckets instead of having to implement it for every aggregation.

**Comment by clintongormley** [comment]
@colings86 any thoughts about this?

**Comment by colings86** [comment]
With the addition of the bucket selector pipeline aggregation in 2.0 you can now filter buckets of any aggregation type at reduce time for minimum doc count or any other criteria

**Comment by clintongormley** [comment]
thanks @colings86 - closing
