### ISSUE TITLE
Add an `index_filter` option to the _search_shards API

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#100431]
### Description

It's becoming more and more common to select which indices should be queried not through the index pattern, but via filters, and rely on the `can_match` phase to efficiently skip these shards.

We should add an `index_filter` option to the `_search_shards` API to allow callers to skip shards that have no chance of matching the query.

See #99740 which gives a bit more context about the why, in the context of the `_pit` API.

**Comment by dnhatn** [comment]
I think we have stopped adding enhancements to the search_shards API because we have switched to a new transport-only search_shards API that accepts [queries](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/action/search/SearchShardsRequest.java#L34) and performs the can_match phase.

**Comment by javanna** [comment]
Indeed, we have recently introduced a new transport level search shards API that incorporates the can match phase. We are not planning on enhancing the legacy cluster search shards API, unless scenarios emerge that make it necessary.
