### ISSUE TITLE
[Feature] Reciprocal decay

### ISSUE THREAD

**Issue by synhershko** [elastic/elasticsearch#10048]
Support for a reciprocal decay function will be highly useful for one use-case I'm helping with:

(1/x)^c where c is a constant and x is the parameter to the decay function (datetime field etc).

/cc @brwe

**Comment by brwe** [comment]
What would the score be as c approaches 0? We added exp, gauss and linear because like this we can at least make sure the score is between 0 and 1 always. What is your usecase?
I cannot promise there will be any resources soon to implement this but it should be really easy to implement it as a plugin like so: https://github.com/elastic/elasticsearch/blob/master/src/test/java/org/elasticsearch/search/functionscore/FunctionScorePluginTests.java

**Comment by ofir-reich** [comment]
You mean where x approaches 0. It would be best to add a constant b, so that it's (x+b)^c, or (abs(x)+b)^c to handle negative cases.
But to be more exact, what we need is a minus logarithmic decay:
Score = -log( abs(x)+b ),
where x is the difference between the query term and the document.
Our use case is for time decay. We want the time difference between documents to affect the result in this way, so that more recent documents are given a higher score. The reason we can't use any of the other decay functions is that we use a probabilistic interpretation for the IDF and we want it to be consistent all through our search to get the exact results we want. We've found that the probability that a document is relevant to our query decays as a power law: probability ~ 1/(delta_t+b) .
Since IDF is (close to) the log of a probability of a random document to match the query, we take the exponent of the IDF (the resulting score). We want to add to the probability the power law decay, but since scores are additive and we take an exponent of the result in the end, we want a log( abs(delta_t)+b) function for the score so that when we take the exponent to obtain the probability it would become 1/(delta_t+b).
I hope this was clear. I'm open to other clarifications if needed.
Thank you!

p.s. notice that in the probabilistic interpretation, a decay function of 1/(x+b)^c for the score would correspond, when taking the exponent, to an exponential decay in probability, which also might be useful for many use-cases. It doesn't make much sense to decay the score itself as en exponent.

**Comment by brwe** [comment]
I think I understand the usecase but I am not convinced that this is a very common one so I am leaning against adding this scoring function to core. 
What keeps you from implementing this in a script (potentially native) or as a plugin to decay functions?

**Comment by synhershko** [comment]
Maintenance, mostly. We could do that, but the internal APIs are not stable and aren't going to be for a while. I've been maintaining various plugins for over 2 years now.

We think this could be very useful for many others as well, hence this proposals. We do hope it will make it in, and will gladly provide a complete PR for it.

**Comment by clintongormley** [comment]
The maths was above me, but it looks like this could be implemented easily with a (very fast) `expression` script, no? Plus the `weight` parameter allows for tuning between functions.

Any reason to keep this open?

**Comment by nik9000** [comment]
> Any reason to keep this open?

I think expression scripts are likely to be good for this. The API there is pretty stable.

If we think the shape of the decay is useful it might be worth adding. If I'm reading it right they are talking about something like `1 + log(b) - log( a * abs(now - doc['time']) +b )`

This creates something that starts at 0 and decays quickly at first but more and more slowly as time goes on. And, if my very very very rusty calculus doesn't fail me, it will eventually become negative so we'd want to clamp it at 0.

**Comment by dakrone** [comment]
This is possible with the new Painless scripting language, so I am closing this since it's been almost a year.
