### ISSUE TITLE
Deleted index comes back

### ISSUE THREAD

**Issue by masaruh** [elastic/elasticsearch#10054]
Reproduction:

1. Create two nodes cluster, node1 and node2 (both are master eligible)
2. Create an index
3. Stop node2
4. Delete the index
5. Stop node1
6. Start node1 and node2
7. Deleted index comes back

**Comment by markwalkom** [comment]
This is 1.4.4 according to @masaruh

**Comment by masaruh** [comment]
Forgot to mention it's not dangling index.

It can be reproduced by:
1. Create three nodes cluster, node1 and node2 are master eligible and node3 is data only node.
2. Create index
3. Stop node2
4. Delete the index
5. Stop node1 and node3
6. Start node1, node2 and node3
7. Deleted index comes back

It looks old cluster state on node2 is imported on restart during `LocalGateway.performStateRecovery`.
It looks indices found in any `nodeState` are getting recovered. I wonder if it should recover only indices in `electedGlobalState`.

**Comment by brwe** [comment]
This is actually expected behavior. When a master eligible node joins a cluster then all information is has about indices from it's last cluster state are imported as well. This is a safety measure to make sure that a master with an empty cluster state (for example because the data folder of a master eligible node was deleted and it becomes master after full cluster restart) does not cause all indices to be deleted. We are even changing that now to work in a similar way for data only nodes, see https://github.com/elastic/elasticsearch/issues/8823

**Comment by masaruh** [comment]
Thanks @brwe. Makes sense.

**Comment by bleskes** [comment]
A common failure here is people forgetting to configure min_master_nodes or recover_after, do a full cluster restart (or what ever) while adding new nodes to the cluster. If one of the new nodes gets elected as master before the older nodes join, it will not wait for them and iniitialize an empty cluster state (thinking it’s alone in a fresh cluster). We need this protection to make sure that we don’t delete all data once the old nodes join.
