### ISSUE TITLE
Scripting Issues generating compound _id from fields

### ISSUE THREAD

**Issue by nithyanv** [elastic/elasticsearch#10064]
Hi,

I am trying to generating compound _id from _source fields.

curl -XPUT http://localhost:9200/_template/my_tplt -d '{
"template" : "my*",
"order":    1,
"settings" : {
"index.cache.field.type" : "soft",
"index.refresh_interval" : "5s",
"index.store.compress.stored" : true,
"mapping.allow_type_wrapper": true
},
"mappings" : {
"_default_" : {
"_all" : {"enabled" : false},
"_timestamp" : {"enabled" : true,"path" : "my_time","format" : "YYYY-MM-dd HH:mm:ss"},
"_ttl" : { "enabled" : true, "default" : "30d"},
"transform" : {
"script_file" : "gen_id"
},
"properties" : {
"my_time": {
"type": "date",
"format": "YYYY-MM-dd HH:mm:ss"
},
"my_roll" : {"type": "string", "index" : "not_analyzed" },
"my_name" : {"type": "string", "index" : "not_analyzed" },
"my_address":{"type":"string","index" : "not_analyzed" },
"my_message" : {"type": "string", "index" : "not_analyzed"}
}
}
}
}
'

File gen_id.groovy in \elastic_home\config\scripts\ 
contains the following line
ctx._source['_id']=ctx._source['my_roll']+ctx._source['my_name'];

input file contains 
{"index":{"_index":"my_index","_type":"test"}}
{"my_time":"2015-03-10 17:04:45","my_name":"nithya","my_roll":"A0001","my_address":"somewhere here","my_message":"This is me"}

But I get the following 
errorMapperParsingException[Provided id [AUwKuP4ndtjQr1ZnsG_U] does not match the content one [A0001nithya] 

I have tried with 
File gen_id.groovy updated with this line
ctx._source['my_message']=ctx._source['my_roll']+ctx._source['my_name'];

But even my_message does not insert with new value my_message value. 

What am I missing here?

**Comment by javanna** [comment]
I think this question would be better answered in the mailing list. That said, you cannot change the `_id` of a document through a script. I suppose that AUwKuP4ndtjQr1ZnsG_U is the auto generated id for your document, since you didn't specify one in the url, and A0001nithya the result of the script. 
Not sure about the last bit on the my_message field, maybe you can share some more details on the mailing list around it, that sounds like it should work.

In general, and especially if you want to modify your ids, I would pre-process your documents before sending them to elasticsearch to be honest, so that they have the right id from the beginning.
