### ISSUE TITLE
Date format using seconds since epoch

### ISSUE THREAD

**Issue by cameronevans** [elastic/elasticsearch#10072]
We currently use seconds since epoch to store dates in Elasticsearch. However, this is interpreted as milliseconds since epoch and stores them internally as such. 

Example: 10/Feb/2015:17:54:07 in seconds (1423590847) becomes 01/17/1970 11:26:30

Unfortunately this issue means that we have to use date histogram facets instead of aggregations in order to use the "factor" field to convert it accordingly (discussed in #6490). 

Possible solutions would be: mention that Unix time in seconds isn't a supported date format in the documentation or allow the Unix seconds format to be specified in the mapping.

**Comment by jpountz** [comment]
I agree an option on date fields to interpret numbers as seconds since epoch instead of milliseconds would make sense.

**Comment by jpountz** [comment]
Dates would still be stored as milliseconds since Epoch internally, which should be fine since Lucene doc values have gcd compression exactly for this use-case: it would figure out that all values share a common divisor and use it for compression.

**Comment by saffroy** [comment]
Thanks @jpountz for working on this!
One question regarding your commit c7115f8: with 'numeric_resolution' set to 'seconds', will it parse a double (or string) value of 42.001 into 42001 ms or 42000 ms?

**Comment by jpountz** [comment]
I just checked: it would be parsed as 42000ms.

**Comment by jpountz** [comment]
Unfortunately, the abstraction we are using right now (`java.util.concurrent.TimeUnit`) cannot deal with fractions so making it parse as 42001 would require some work. I suggest that we merge the `numeric_resolution` change first and then open a new issue if better handling of double values is desirable?

**Comment by saffroy** [comment]
I support your suggestion of opening a new issue on top of the above change, though for me it's mostly a convenience issue, ie. not really a big deal.

In my case, the annoyance was that I thought it would work without an extra step (seconds since epoch seemed like a common format to me, much more than milliseconds since epoch), until I found that I had to explicitly tell Logstash to convert from seconds+fraction of a second since epoch (luckily Logstash makes it easy, once you know that you need it).
