### ISSUE TITLE
Switching from Facets to Aggregations problems in Elastic Search

### ISSUE THREAD

**Issue by parasb** [elastic/elasticsearch#10081]
We were using facets in elastic search. But since they are deprecated now, We are trying to use aggregations now. The code snippet for both the approaches are 

https://gist.github.com/parasb/751baf0fca2a7682a8d1

Refering the code snippet for facets,  we pass 2 IMEIs in should array of facet 0, it returns the result corresponding to those IMEIs in facet 0 & we pass 1 IMEI in should array of facet 1, it returns the result corresponding to that IMEI in facet 1. So, we get the aggregated results of those multiple fquery search in the corresponding facet.

But while using aggregation, we pass all the IMEIs in the should array and get the response as per IMEI. I need to aggregate multiple IMEIs in multiple buckets. for eg: 2 IMEI in one bucket and another 1 IMEI in different bucket (similar to 2 IMEIs in 0 facet & 1 IMEI in first facet).

Does Elastic Search aggregation provide a way to do this?

**Comment by jpountz** [comment]
Sorry but I'm not sure to understand the issue here. That said, maybe the answer to your question is in our facets to aggregations migration guide? http://www.elastic.co/guide/en/elasticsearch/reference/current/search-facets-migrating-to-aggs.html#_facet_filters

Closing the issue as it sounds to me like a question rather than a bug.
