### ISSUE TITLE
ESQL: Grok command ignores escaping for \"

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#101017]
### Description

Command "grok process.command_line "\"%{DATA:drive}:\\%{DATA:path}\"%{SPACE}%{GREEDYDATA:args}" returns an error stating "unmatched close parenthesis".
Looks like the \" escaping is not considered.
![image](https://github.com/elastic/elasticsearch/assets/76245/5764c68e-7e4c-4cbc-bc89-6c5647eae5e2)
![image](https://github.com/elastic/elasticsearch/assets/76245/08c958ec-fa13-4b3a-9a05-44e5610cb64b)

**Comment by luigidellaquila** [comment]
I think the problem here is due to missing escaping in the query.

I tested the following:

mapping:
```
{
    "mappings": {
        "properties": {
            "x": {
                "type": "keyword"
            }
        }
    }
}
```

bulk data:
```
{"index": {"_index":"test"}}
{"x" : "\"c:\\\\foo\\bar.exe\" baz"}
```

query:
```
{
    "query": "from test | grok x \"\\\"%{DATA:drive}:\\\\\\\\\\\\\\\\%{DATA:path}\\\"%{SPACE}%{GREEDYDATA:args}\""
}
```

and it seems to work just fine:
```
{
    "columns": [
        {
            "name": "x",
            "type": "keyword"
        },
        {
            "name": "drive",
            "type": "keyword"
        },
        {
            "name": "path",
            "type": "keyword"
        },
        {
            "name": "args",
            "type": "keyword"
        }
    ],
    "values": [
        [
            "\"c:\\\\foo\\bar.exe\" baz",
            "c",
            "foo\\bar.exe",
            "baz"
        ]
    ]
}
```

I think the problem here is just that multiple string quoting + regex is hard. I'll try to explain what happens during the various steps of the parsing:

original query payload:
```
                                                16 backslash characters
"query": "from test | grok x \"\\\"%{DATA:drive}:\\\\\\\\\\\\\\\\%{DATA:path}\\\"%{SPACE}%{GREEDYDATA:args}\" | keep x, drive, path, args"
```

unquoted query:
```
                              8 backslash characters
from test | grok x "\"%{DATA:drive}:\\\\\\\\%{DATA:path}\"%{SPACE}%{GREEDYDATA:args}" | keep x, drive, path, args
```

unquoted grok expression
```
               4 backslash characters
"%{DATA:drive}:\\\\%{DATA:path}"%{SPACE}%{GREEDYDATA:args}
```

since it's a regex, backslashes are quoted, ie. each `\\` here matches a single `\` in the input string.


Another example that seems to work fine, this time with triple quotes in Kibana, that make the query a bit more readable:
```
POST _esql 
{
      "query": """
      row x = "\"c:\\\\foo.exe\" bar"
      | grok x "\"%{DATA:drive}:\\\\\\\\%{DATA:path}\"%{SPACE}%{GREEDYDATA:args}" 
      | keep x, drive, path, args
      """

}
```

See that the escaping of the `\\` is different from the one that makes the query fail.
