### ISSUE TITLE
Change upgrade docs to avoid rolling upgrades

### ISSUE THREAD

**Issue by seang-es** [elastic/elasticsearch#10118]
Rolling upgrades are causing problems with data corruption in some cases.  Updating documentation to recommend full cluster stops during upgrades.

Also adding recommendation to halt writes/flush data before restarting to reduce recovery time.

**Comment by kadaan** [comment]
While I understand your reasoning for removing the recommendation, this will require an outage to upgrade ES, which for many use cases will not be acceptable.  Being able to upgrade a live system and in a backwards compatible way (and being able to roll back the changes if needed) should be a core principle for all distributed systems.  Without that ability, customers will be much more reticent to upgrade.

**Comment by allenmchan** [comment]
If elasticsearch needs a full down to be upgraded, that means that the logstash ecosystem would screech to a halt as well. I sure hope this recommendation is just temporary and ES devs are working hard to make upgrades possible without full cluster down.

**Comment by nik9000** [comment]
> If elasticsearch needs a full down to be upgraded, that means that the logstash ecosystem would screech to a halt as well. I sure hope this recommendation is just temporary and ES devs are working hard to make upgrades possible without full cluster down.

+1

This is pretty nightmarish for those of us with site search powered by Elasticsearch.  We do plan to build a second cluster in a backup data center that we could fail over to.  But that is many months away.

This is also pretty different than the story that I heard at Elasticon regarding sealed indexes making rolling restarts faster and simpler.  We were planning on doing them _more_ often with support from that one day.

Is the trouble writes during the restart?  Merges?

Not supporting rolling restart would have caused us not to select Elasticsearch.

**Comment by s1monw** [comment]
I think this PR needs some clarification. IMO the relevant versions that are risky to upgrade are 1.3.x and 1.4.x where a lot of checksum problems were uncovered. We had false positives on old lucene 3.x segments as well as truncation issues due to the way recoveries worked. In the upcoming release (planned for next week) of Elasticsearch `1.5.0` all known issues related to this are resolved and it's safe to do a rolling upgrade. I think this PR should specify the risky version rather than making a general statement.

I also would love the users to not get paranoid about this, we have not even had a review cycle on this PR. We operate very open here and obviously don't want to hold this information back from anybody but there is no reason for get worried that this won't get resolved. I can assure you we spend almost all our time these days on infrastructure and stability that's also a reason why `1.5.0` doesn't have that many user-facing features. There will likely be a `1.6.0` release with https://github.com/elastic/elasticsearch/issues/10032 to improve this situation dramatically. So stay tuned we are working on all ends.

> Being able to upgrade a live system and in a backwards compatible way (and being able to roll back the changes if needed) should be a core principle for all distributed systems. 

you can downgrade unless you have written to the new cluster. I personally don't know a lot of systems that are forwards compatible to be honest :)

**Comment by clintongormley** [comment]
No longer relevant
