### ISSUE TITLE
add time zone setting for relative date math for date range aggregation 

### ISSUE THREAD

**Issue by csezheng** [elastic/elasticsearch#10130]
Hi, 

The following issue has been resolved for the range filter/query.
https://github.com/elastic/elasticsearch/issues/3729

Is it possible to add something similar to date range aggregation? The default date is UTC time by default, but we need to use now in PST time zone. 
```php
{
    "aggs": {
        "range": {
            "date_range": {
                "field": "date",
                "format": "YYYY-MM-dd HH:mm:ss",
                "ranges": [
                    { "to": "now-1d/d" }, 
                    { "from": "now-1d/d" } 
                ]
            }
        }
    }
}
```

**Comment by wkoot** [comment]
Ran into the same issue, would be nice if `time_zone` is indeed picked up.
I'm currently using the following workaround in python, as per your example:
```
from datetime import datetime
timezone_offset = "+%iH" % round(float((datetime.now() - datetime.utcnow()).seconds) / 60 / 60)

query = {
    "aggs": {
        "range": {
            "date_range": {
                "field": "date",
                "format": "YYYY-MM-dd HH:mm:ss",
                "ranges": [
                    { "to": "now-1d/d" + timezone_offset }, 
                    { "from": "now-1d/d" + timezone_offset } 
                ]
            }
        }
    }
}
```

**Comment by mj1856** [comment]
Keep in mind that offsets can change within a single time zone, due to daylight saving time, and other various anomalies.  See "Time Zone != Offset" in [the timezone tag wiki on StackOverflow](http://stackoverflow.com/tags/timezone/info).

For an aggregation to be meaningful in a specific time zone, such as US Pacific Time, the time zone itself would have to be understood by ElasticSearch.  This would probably be best expressed as an IANA/Olson time zone identifier, such as `"America/Los_Angeles"`.   This would also mean that an ElasticSearch cluster would have to have a process for receiving regular updates to the IANA tzdb, which can happen about a dozen times per year or so.

@wkoot - In your example, the `timezone_offset` field is calculated based on the *current* difference between the local time zone and UTC.  There's no guarantee that that offset is the correct one for any of the dates covered by the to/from values of the query.
