### ISSUE TITLE
"minimum_should_match" does not work with "cutoff_frequency"

### ISSUE THREAD

**Issue by szou-cp** [elastic/elasticsearch#10150]
total documents: 20675074

term, document count, divided by total documents
![image](https://cloud.githubusercontent.com/assets/8093917/6722281/616744d2-cd94-11e4-87b0-d4a81de4e1d9.png)

Elasticsearch 1.4.1

Query 1
---

```json
{
  "from" : 1,
  "size" : 10,
  "query" : {
    "multi_match" : {
      "query" : "cat and mouse",
      "fields" : [ "tag", "tag.stemmed", "anothertag" ],
      "type" : "most_fields",
      "minimum_should_match" : "100%",
      "cutoff_frequency" : 0.0002
    }
  }
}
```
return me 3316 documents, I expected 3312 documents.

Query 2
---

```json
{
  "from" : 1,
  "size" : 10,
  "query" : {
    "multi_match" : {
      "query" : "cat and mouse",
      "fields" : [ "tag", "tag.stemmed", "anothertag" ],
      "type" : "most_fields",
      "minimum_should_match" : "100%",
      "cutoff_frequency" : 0.002
    }
  }
}
```
return me 100270 documents, I expected less than 3312 documents.

Query 3
---

```json
{
  "from" : 1,
  "size" : 10,
  "query" : {
    "multi_match" : {
      "query" : "cat and mouse",
      "fields" : [ "tag", "tag.stemmed", "anothertag" ],
      "type" : "most_fields",
      "minimum_should_match" : "100%",
      "cutoff_frequency" : 0.005
    }
  }
}
```
return me 100279 documents, I expected less than 3312 documents.

Query 4
---

```java
{

  "from" : 1,
  "size" : 10,
  "query" : {
    "multi_match" : {
      "query" : "cat and mouse",
      "fields" : [ "tag", "tag.stemmed", "anothertag" ],
      "type" : "most_fields",
      "operator": "or"
    }
  }
}
```
100279 is the total document returns by this query

__I guess somehow "cutoff_frequency" will make "minimum_should_match" not used.__

**Comment by micpalmia** [comment]
I'm also noticing a weird behavior of `cutoff_frequency` with `multi_match` queries.

**Comment by MaineC** [comment]
This looks related to #10154 - @micpalmia do you only see weird behaviour in multi-match queries or also in plain match queries?

**Comment by clintongormley** [comment]
Hi @szou-cp 

Let's reduce the complexity of your example by (1) reducing the number of fields involved (because we don't know what is happening in those other fields), (2) reducing the number of shards involved (because the cutoff frequency is per shard, not per index, see https://www.elastic.co/guide/en/elasticsearch/guide/current/relevance-is-broken.html) and (3) working with a finite set of docs with known term overlaps:

    DELETE t
    
    PUT t 
    {
      "settings": {
        "number_of_shards": 1
      }
    }
    
    POST t/t/_bulk
    {"index":{}}
    { "text": "cat and mouse"}
    {"index":{}}
    { "text": "cat and dog"}
    {"index":{}}
    { "text": "dog and mouse"}
    {"index":{}}
    { "text": "dog and mouse"}
    {"index":{}}
    { "text": "dog and mouse"}
    
    GET t/_search
    {
      "query": {
        "match": {
          "text": {
            "query": "cat and mouse",
            "minimum_should_match": "100%",
            "cutoff_frequency": 0.60
          }
        }
      }
    }

By playing with `cutoff_frequency` you can see that its behaviour works exactly as expected (except that `mouse` seems to move from high frequency to low frequency at a cutoff of 0.6, instead of at 0.8 (which is what I'd expect)

Add `?explain'  to the search request to get more detailed info about how the query executes.

This just leaves me with the question of why the cutoff frequency doesn't seem to be exact, unless you can show something else which appears to be incorrect?

**Comment by clintongormley** [comment]
No more info. Closing

**Comment by sevab** [comment]
Despite using just one shard and having enough data for testing (700 documents) I also experience a similar issue where `minimum_should_match` is ignored whenever `cutoff_frequency` is present and has a value of less than 1 in a `multi_match` query.

The following search query matches 4 documents despite each of them containing only one of three low frequency words from the query in their `"title.analyzed"` field (only word `dictionary` matches for each of them). With `"minimum_should_match"` set to `75%` I'd expect all four documents to be filtered-out, but even setting it to 100% doesn't filter them out.

```javascript
// matches 4 results
{
 "query": {
    "multi_match": {
      "query":  "dictionary of human geography",
      // `title.analyzed` here is a `standard` field stripped of `_english_` stopwords; `another_field` is just a standard field
      "fields": [ "title.analyzed", "another_field"],
      "cutoff_frequency": 0.01,
      "minimum_should_match": "75%"
    }
  }
}
```

However, removing `cutoff_frequency` (or setting it to 1) returns the desired 0 results, but I'd like to keep the `cutoff_frequency` for stripping frequent words from the standard `another_field`:
```javascript
// matches 0 results
{
 "query": {
    "multi_match": {
      "query":  "dictionary of human geography",
      "fields": [ "title.analyzed", "another_field"],
      "minimum_should_match": "75%"
    }
  }
}
```


The issue doesn't occur when I use a simple `match` instead of `multi_match` to query against one of the fields:
```javascript
// matches 0 results
{
 "query": {
    "match": {
      "title.analyzed": {
        "query":  "dictionary of human geography",
        "cutoff_frequency": 0.01,
        "minimum_should_match": "75%" 
      }
    }
  }
}
```

However, I'd like to continue using `multi_match` while taking advantage of both `cutoff_frequency` and `minimum_should_match` parameters.


Looking at [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html) for `multi_match`, both `cutoff_frequency` and `minimum_should_match` should be supported.
