### ISSUE TITLE
Cluster API feature request: Node Startup

### ISSUE THREAD

**Issue by jzinner** [elastic/elasticsearch#10177]
We have Node Shutdown API points. http://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-shutdown.html

But to instrument the Rolling Restart discussed at the bottom of the page^^ -- I need a Node Start API as well.

Please consider writing a Node Start API  -- this will make cluster management possible from the Cluster API 

Cheers,

**Comment by clintongormley** [comment]
How could we call node-start when the node is not running?

There used to be a restart API (briefly), but it was removed because it was problematic.  I'm not sure what the problem was, but it was big enough that the feature wasn't reliable, and it wouldn't help with upgrades anyhow.

I don't believe that this can be provided as part of Elasticsearch itself.
