### ISSUE TITLE
Elasticsearch does not refresh AWS Web Identity Token file when changed on disk

### ISSUE THREAD

**Issue by pebrc** [elastic/elasticsearch#101828]
### Elasticsearch Version

8.x

### Java Version

_bundled_

### OS Version

Kubernetes 

### Problem Description

**Observed**
We have ECK users reporting that S3 repository setups that rely on AWS IAM roles for service accounts (IRSA) stop working after a while and only a restart of the affected Pods restores functionality. 

https://github.com/elastic/cloud-on-k8s/issues/7208

The users are following this documentation on the ECK side https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-snapshots.html#k8s-iam-service-accounts which configures a `CustomWebIdentityTokenCredentialsProvider` based on information from the two environment variables `AWS_WEB_IDENTITY_TOKEN_FILE` (and `AWS_ROLE_ARN`) 

My hunch is that Elasticsearch is not watching the file pointed to by `AWS_WEB_IDENTITY_TOKEN_FILE` and does not [refresh](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/STSAssumeRoleWithWebIdentitySessionCredentialsProvider.html#refresh--) the credentials when the token changes on disk after the configured expiration time. This would be consistent with the users reporting that a restart of the Pods solves the problem. 

**Expected** 
I think it would be reasonable to expect that Elasticsearch reloads the credentials when the token changes on disk without user intervention. 

### Steps to Reproduce

https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-snapshots.html#k8s-iam-service-accounts

with a short ` expirationSeconds: 300` or something along those lines. 
Then wait for token refresh. (Disclaimer: I have not tried it yet myself just relaying user reports here)

**Comment by arteam** [comment]
ES indeed doesn't watch for changes in the token file, but nevertheless the changes in the web Identity token file should be automatically picked up when a role session expires (the default duration is an hour). When the session expires, `STSAssumeRoleWithWebIdentitySessionCredentialsProvider` should [re-read](https://github.com/aws/aws-sdk-java/blob/abae667a5c4027c685a26b0d717af137e64c100d/aws-java-sdk-sts/src/main/java/com/amazonaws/auth/STSAssumeRoleWithWebIdentitySessionCredentialsProvider.java#L146) the file and use the new token for establishing a new session.

I wonder if there's some duration mismatch, so when the old token expires, but the AWS SDK still consider the session from valid and only invalidates it after a restart.

In the meantime, I also looked at `S3Service` and we don't refresh the credentials when the S3 repository is reloaded with new settings. We should do that so at least users don't need to restart the pod.

I will look further at the issue, because I assumed that the token update workflow should work transparently with the AWS SDK.

**Comment by stdmje** [comment]
Any news on this? @arteam This is a major problem IMHO

**Comment by celalsahin** [comment]
Hello! Is there any progress here? We are also struck by the same problem

**Comment by devagunay** [comment]
Is there any update related to this issue?

**Comment by michellebeard** [comment]
Which version(s) of Elasticsearch will have this change? Will it be backported?

**Comment by ywangd** [comment]
8.13 which just got [released](https://www.elastic.co/blog/whats-new-elastic-search-8-13-0). 
No I don't think it will be backported.

**Comment by michellebeard** [comment]
Thanks! I couldn't find it in the release notes.

**Comment by jackchi** [comment]
Yesterday I upgraded from ES 8.8.1 to 8.15.0 and we experienced the same issue with token not getting refreshed by ElasticSearch. 

**POST /_snapshot/my-repo/_verify?pretty=true**

```json

{
  "error": {
    "root_cause": [
      {
        "type": "repository_verification_exception",
        "reason": "[my-repo] path  is not accessible on master node"
      }
    ],
    "type": "repository_verification_exception",
    "reason": "[my-repo] path  is not accessible on master node",
    "caused_by": {
      "type": "i_o_exception",
      "reason": "Unable to upload object [tests-u7JQMsD-QrWRscI0Vv0EuA/master.dat] using a single upload",
      "caused_by": {
        "type": "amazon_client_exception",
        "reason": "amazon_client_exception: java.lang.IllegalStateException: Connection pool shut down",
        "caused_by": {
          "type": "illegal_state_exception",
          "reason": "Connection pool shut down"
        }
      }
    }
  },
  "status": 500
}
```

I am following the ECK instructions for IRSA https://www.elastic.co/guide/en/elasticsearch/reference/current/repository-s3.html#iam-kubernetes-service-accounts

I see the token files are new on the projected volume mounts:

```sh
~/config/repository-s3$ ls -lah                                 
total 4.0K
drwxrwsrwt  3 root elasticsearch  100 Oct 16 14:34 .
drwxrwsrwx 10 root elasticsearch 4.0K Oct 15 19:22 ..
drwxr-sr-x  2 root elasticsearch   60 Oct 16 14:34 ..2024_10_16_14_34_53.3014348955
lrwxrwxrwx  1 root elasticsearch   32 Oct 16 14:34 ..data -> ..2024_10_16_14_34_53.3014348955
lrwxrwxrwx  1 root elasticsearch   34 Oct 15 19:21 aws-web-identity-token-file -> ..data/aws-web-identity-token-file
```
Are there any other reports of this issue?

**Comment by BenjaminWalkerBond** [comment]
I too am experiencing exactly this issue. We have a deployment set up with IRSA. I followed the same documentation you did. The roles work until the token expires, and then elastic search does not get the updated token. I know this because it falls back on the EC2 instance role to authenticate with AWS, and from similar logs to yours. 

We have 8Gi of memory specified. Do you have a workaround at the moment?

**Comment by celalsahin** [comment]
Same here using 8.16.1 - this was resolved - a regression with a recent change maybe?

**Comment by levanlongktmt** [comment]
I got the same problem with 8.17.0, do anyone found way to workaround?
