### ISSUE TITLE
Documentation includes incorrect scary warning

### ISSUE THREAD

**Issue by masseyke** [elastic/elasticsearch#101851]
Our [index module documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#index-modules) includes the scary warning `Changing static or dynamic index settings on a closed index could result in incorrect settings that are impossible to rectify without deleting and recreating the index.` That might have been true 8 years ago when it was added in https://github.com/elastic/elasticsearch/commit/f123a53d7258349a171e47a35f4581899d8fa776, but it no longer seems to be true. We should remove the warning because it causes confusion.

**Comment by DaveCTurner** [comment]
I've suggested this as a topic for today's fix-it meeting agenda.

**Comment by DaveCTurner** [comment]
We discussed this today. Lee helpfully remembered the context for this comment was that changing `index.data_path` on a closed index will make it impossible to assign the shards when it is reopened. Possibly there were some other settings which could change how the data was represented on disk but these no longer exist. All this pre-dates the concept of `Setting.Property#Final` settings, and as far as we can tell you could recover things by reverting the setting change, no need to recreate the index. We decided that we should consider it a bug if we encounter any settings that are not `Final` but which are harmful if changed on a closed index. We also think we should fix such bugs rather than simply documenting them in an overly-broad warning as we do today, so we believe we should remove this warning. I'll start the process of making `index.data_path` final.
