### ISSUE TITLE
"Unknown analyzer type [language]" when creating an index with a default language analyzer

### ISSUE THREAD

**Issue by LionelVallet** [elastic/elasticsearch#101917]
### Elasticsearch Version

8.11.0

### Java Version

_bundled_

### OS Version

Debian 12

### Problem Description

When I create an index with a language analyzer specified, Elasticsearch throws a bad request error :

``` json
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Unknown analyzer type [language] for [default]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "Unknown analyzer type [language] for [default]"
  },
  "status": 400
}
```

### Steps to Reproduce

``` json
{
  "settings": {
    "analysis": {
      "analyzer": {
        "default": {
          "language": "french",
          "type": "language"
        }
      }
    }
  }
}
```

**Comment by cbuescher** [comment]
I think this is a misunderstanding in the [usage of language analyzers](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-lang-analyzer.html#german-analyzer). In your example you are trying to define a new custom analyzer named "default", but the type "language" doesn't exist. There however is a "french" analyzer that you can use in your field mappings without declaring it explicitly in the analysis settings. Please take another look at the docs and reais any remaining questions in our support forums over at [discuss.elastic.co](https://discuss.elastic.co/). We prefer to use Github issues only for bug reports and feature requests, which is why I will close this question.
