### ISSUE TITLE
connectOnNetworkDisconnect doesn't have retry

### ISSUE THREAD

**Issue by danielli90** [elastic/elasticsearch#10206]
connectOnNetworkDisconnect by default is turned off. When enabled, because it does an immediate reconnect without a wait, it most likely fail to reconnect to a node that has a transient network connectivity issues.

Proposed fix: introduce two new settings - (1) connectOnNetworkDisconnect Retry; (2) connectOnNetworkDisconnect Interval.

https://github.com/elastic/elasticsearch/blob/master/src/main/java/org/elasticsearch/discovery/zen/fd/NodesFaultDetection.java
Source code - 

        if (connectOnNetworkDisconnect) {
            NodeFD fd = new NodeFD(node);
            try {
                transportService.connectToNode(node);
                nodesFD.put(node, fd);
                // we use schedule with a 0 time value to run the pinger on the pool as it will run on later
                threadPool.schedule(TimeValue.timeValueMillis(0), ThreadPool.Names.SAME, fd);
            } catch (Exception e) {
                logger.trace("[node  ] [{}] transport disconnected (with verified connect)", node);
                // clean up if needed, just to be safe..
                nodesFD.remove(node, fd);
                notifyNodeFailure(node, "transport disconnected (with verified connect)");
            }
        } else {
            logger.trace("[node  ] [{}] transport disconnected", node);
            notifyNodeFailure(node, "transport disconnected");
        }

thx
Daniel

**Comment by bleskes** [comment]
@danielli90 this is tricky. If the node is not connected, it will not get cluster state updates from the master. Originally we had this reconnect to deal with environments that sometimes close connections but the network weren't down. However, it turned out to be an issue in the cases where a network issue causes timeouts, in which case we just waited on the timeout to fire and the transport to disconnect and then we retried and waited for another timeout period, during which the node will not get any updates. This is why we changed it.

As a side note - if this happens, the node will ping for and rejoin the master, making sure it has the latest cluster state.

I'm wondering - why did you need this? I assume something didn't work well for you.

**Comment by clintongormley** [comment]
No more feedback. Closing
