### ISSUE TITLE
Excessive fixed_bit_set_memory_in_bytes causing GC thrashing

### ISSUE THREAD

**Issue by drewdahlke** [elastic/elasticsearch#10224]
We're running ES 1.4.4 on a 4 node c3.2xlarge EC2 cluster, configured for 8GB heaps. Sometimes nodes start GC thrashing b/c it's not freeing up enough memory. For example:

```
[2015-03-23 17:25:53,342][INFO ][monitor.jvm              ] [Ocelot] [gc][old][212973][1077] duration [6.1s], collections [1]/[6.4s], total [6.1s]/[1.8h], memory [7.2gb]->[7.2gb]/[7.3gb], all_pools {[young] [38mb]->[188mb]/[0b]}{[survivor] [0b]->[0b]/[0b]}{[old] [7.1gb]->[7gb]/[7.3gb]}
[2015-03-23 17:25:59,627][INFO ][monitor.jvm              ] [Ocelot] [gc][old][212974][1078] duration [6.1s], collections [1]/[6.2s], total [6.1s]/[1.8h], memory [7.2gb]->[7.1gb]/[7.3gb], all_pools {[young] [188mb]->[70mb]/[0b]}{[survivor] [0b]->[0b]/[0b]}{[old] [7gb]->[7gb]/[7.3gb]}
```

It's all old gen. We switched from concurrent mark sweep to G1, but that didn't help. Looking at node stats while this is going on

curl http://localhost:9200/_nodes/Ocelot/stats

```
"segments": {
          "count": 6015,
          "memory_in_bytes": 909820630,  =  0.84734 GB
          "index_writer_memory_in_bytes": 0,
          "index_writer_max_memory_in_bytes": 1504223232,  = 1.40092 GB
          "version_map_memory_in_bytes": 0,
          "fixed_bit_set_memory_in_bytes": 2779968664    = 2.58905 GB
        },
```

I noticed that fixed_bit_set_memory_in_bytes is taking up quite a large chunk of our 8GB heap and that by design it never evicts
https://github.com/elastic/elasticsearch/pull/7037

We use nested documents heavily. I was wondering if there's a way to control this memory usage, if this is a bug, or if we simply need more memory/nodes to cover this memory overhead.

**Comment by martijnvg** [comment]
@drewdahlke The nested feature heavily leans on in-memory bitsets. Essentially each parent nested field needs an in-memory bitset. In the case all the nested fields are in the root level, only one bitset needs to be in memory, but once you have multiple levels of nested fields more bitsets need to be loaded in memory and this can become expensive. In your case do you have multiple levels of nested fields?

Are you using nested sorting? Unfortunately at the moment this is quite memory in-efficient. It has been fixed in 2.0: #9199

In the case that you don't use all of your nested fields you may want to disable eager loading by setting `index.load_fixed_bitset_filters_eagerly` to false in your elasticsearch.yml file.

If you have many documents marked as deleted it may make sense to prune those documents by running an optimize. (this can also be found in node stats under docs/deleted) This can reduce the space these in-memory bitsets need.

Other than that you can always increase the maximum heap space a node is allowed to use or add more nodes.

**Comment by drewdahlke** [comment]
Hey, thanks for getting back to me. Our doc structure only nests one layer deep right now, but we are sorting on a nested date field. It's good to know there's an improvement for that in a future release. I've got include_in_parent set to false on the nested docs. Our docs get updated typically 8-10 times but are never deleted.

We're on 1.4.4 and it looks like in 1.4.1 the eager loading of bitsets was disabled by default so we should be good there. However, I have a question about that. Is it holding onto 1 bitset per field or one bitset per field per term filter value ever used while querying with _cache=true? 

Also is there a way to see a breakdown on field name to bit set overhead? It would be handy to see which fields have the most overhead.

**Comment by drewdahlke** [comment]
Scratch what I said about 1.4.4 defaulting to false. I must have missread https://github.com/elastic/elasticsearch/issues/8394 because setting index.load_fixed_bitset_filters_eagerly=false seems to have done the trick. fixed_bit_set_memory_in_bytes shrunk 2 orders of magnitude from that. Sweet!

**Comment by martijnvg** [comment]
> However, I have a question about that. Is it holding onto 1 bitset per field or one bitset per field per term filter value ever used while querying with _cache=true?

The bitset cache caches on a per nested field basis.

> Also is there a way to see a breakdown on field name to bit set overhead?

No, at the moment that isn't possible

If a document get deleted then under the hood the Lucene document(s) get marked as deleted and are re-added. So perhaps it does make sense to prune deleted docs at some point.

In 1.4.4 only the bitset for parent level nested field are eagerly loaded, in your case that is only one bitset, so that should be fine. The nested sorting also causes the nested fields used in the nested sorting to be cached, so that adds up.

**Comment by martijnvg** [comment]
One note about the disabling the eager loading is that unfortunately will not prevent jvm heap issues. If a search request gets executed that does need the bitsets, it will load it and you may run into the same issues.

**Comment by drewdahlke** [comment]
Makes sense. Any chance we could make this a feature request to persist those bitsets on disk and LRU cache them in memory rotated by a configurable max memory cap? As is with time series data (we have 1 index per day of data) old data, less frequently queried, has the same bitset memory cost as the hot recent data and it'd be nice to get some control over that.

**Comment by holm** [comment]
We have been trying to upgrade to 1.4 from 1.2, but are currently unable to because the we run out of heap, even with more than 50% additional heap being made available. Based on testing it seems this is the issue that is causing the increased memory usage. 

We use nested documents for sorting. Is there any chance the fix in 2.0 will be backported or are there any other ways to get around this issue?

**Comment by martijnvg** [comment]
@holm sorry to hear that nested sorting is preventing you from upgrading... We decided not to backport the nested sorting fix into 1.x, because of a change in Lucene 5 (2.0 will use this Lucene version) on which the fix relies on. Basically documents are guaranteed to always score in order in Lucene 5, in Lucene 4 this isn't always to case and the nested sorting fix relies on that. 

@drewdahlke The reason that these bitsets are on the jvm heap space is because the nested query, nested sorting etc. require random access to it.

**Comment by jpountz** [comment]
I don't think we should try to backport this change, this would be dangerous. I would rather recommend increasing the heap size or adding more nodes to the cluster until we have a better solution for this issue (ie. 2.0).

But even on 2.0, nested documents will still be a heavy feature since we will still require a full bit set for each nested field. In general, `nested` should not be considered an improved version of `object` but rather a useful feature that comes with a non-negligible cost. This needs to be taken into account when designing mappings. Also, `nested` docs don't only increase memory usage, they also make the index sparser, which in-turn hurts compression of the index on disk and increase memory usage of all data-structures that key by doc ID (such as fielddata).

@holm As a side note, I see that you have 6015 segments on a single node, which is quite large for a single node. Do you know how many shards this maps to (I would guess around 120 since it is common for shards to have about 50 segments)? Maybe you could save memory by having fewer shards, eg. by allocating fewer shards per index, merging read-only indices to a single segment per shard, or having eg. weekly indices instead of daily if you have time-based data.

**Comment by drewdahlke** [comment]
Keeping the bitsets on heap makes total sense. It's my impression from https://github.com/elastic/elasticsearch/pull/7037 that bitsets moved from being in field cache with an LRU eviction policy to something separate & non-evicting in 1.4.0. 

Breaking the bitsets out from field cache is a huge improvement b/c bitsets & field data are different enough that giving them different eviction policies makes a lot of sense. However, omitting the eviction policy all-together on bitsets seems atypical for the project. I'd like to see a cap similar to indices.fielddata.cache.size but for those bitsets. For us a slow query here and there trumps OOMs or the expense of growing the cluster to compensate. 

Sans you all adding a cap we're looking at either having to fork ES 1.4.4 to add a cap or downgrading to 1.3.x to keep our ec2 costs down. 

@jpountz Merging old shards down to a single segment is a great idea; putting it on my list. The bitsets have my attention right now b/c upgrading from 1.1.x to 1.4.x with no other changes immediately started costing us more money to host b/c we have to have so much more heap available.

**Comment by cdmicacc** [comment]
We are in the same situation -- the memory used by the bitsets grows until the entire heap is consumed (we have 12 nodes, currently, each with a 32GB heap).  

By chance, we discovered that issuing POST https://localhost:9200/index/_cache/clear will clear the bitset cache (but there is no corresponding explicit parameter to clear them).  Without some form of cache expiry (LRU or otherwise), we're either going to have to periodically flush all the caches across the cluster, or downgrade back to 1.3.

**Comment by martijnvg** [comment]
One note to @jpountz's note about memory usage for nested docs: Nested documents requires a full bit set for each nested field that is a parent of another nested field. This applies for both 2.0 and 1.x (the nested sorting is just an exception here).

**Comment by holm** [comment]
We use the nested document feature to associate a personal "score" for each user to a document. We then use the score for the active user when sorting the results. For most documents only very few users will have a score, so the length of the nested documents are quite short. 

I think having an eviction policy for the bitsets sounds like a good idea. Barring that, I would love to know if there are other ways to solve the scoring, outside a nested sorting. I guess a function score could work also, although less direct.

**Comment by schlosna** [comment]
I am experiencing bloat of the fixed bit set caches which has led to OutOfMemoryErrors on our data nodes and ES cluster instability. We make heavy use of nested documents to provide access controls for parent documents, and our queries include filters for these nested documents.

Similar to @drewdahlke, we may have to fork ES if we cannot bound the `FixedBitSetFilterCache` so I am beginning to look into implementing size and/or time bounding for the `FixedBitSetFilterCache`, and wanted to gauge community interest in a possible PR and get feedback on what might be an acceptable implementation. I am planning on an implementation similar to `IndicesFieldDataCache`. I am also interested in thoughts around if the `FixedBitSetFilterCache` should participate in the existing circuit breakers (i.e. indices.breaker.total.limit per
https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-fielddata.html#circuit-breaker), and possibly add `indices.breaker.filter.limit` and `indices.breaker.filter.overhead`.

**Comment by jepettoruti** [comment]
Is there any official word of when this will be fixed? Is it for ES 2.x or would it come in some previous release?
@schlosna I don't think we have the resources to help with the development of a fork, but happy to test it.

**Comment by jpountz** [comment]
Making this cache bounded is a bit trappy because then even very simple queries that match few documents might need to scan the entire index to load these bit sets that we use for nested queries/sorting.

Like @martijnvg said, this situation will improve a lot in 2.0 thanks to #9199. However I don't think we can do anything in 1.x.

**Comment by drewdahlke** [comment]
@jpountz If I recall doc values were added b/c un-inverting the index into field data cache on demand was expensive. It sounds like building the bitsets on demand are in the same boat, so wouldn't it make sense to persist them to disk as well? Putting a bounded cache on something disk backed would make it less trappy and allow people to take the performance hit on indexing/merging rather than heap usage at query time. 

I could see defaulting it to unbounded (prioritizing query performance), but providing a bounded option for people who need more control over heap usage. 

@schlosna If you end up forking before an official fix comes out, I could spare some cycles for code review/testing.

**Comment by jpountz** [comment]
@drewdahlke Totally agreed, we shouldn't have to load all this information about the nested structure in memory. It should reside on disk and we should read from there directly.
