### ISSUE TITLE
using query string query to check if field exists

### ISSUE THREAD

**Issue by sweetest** [elastic/elasticsearch#10232]
"query":{"query_string" : {
        "default_field" : "body",
        "query" : "UserID:*"
        }
    }

I thought query above will return items which includes UserID field, but I got an unexpected result that it does not return logs with UserID=-.

I can do this by exists filter, but I think query string query above should return what I expected.

I'm trying to fix this locally and want to ask your opinion about this.

mapping on this field is string:analyzed.

**Comment by javanna** [comment]
Hi @sweetest,
I think this type of question could be asked in the mailing list instead, unless you found a bug or you have a feature request.

This does not seem like a bug to me, what you describe is the expected behaviour of the `query_string` query. I believe your field ended up empty after text analysis, that would be why you don't get that specific document back by doing `UserID:*`. Have a look at how fields get analyzed using the analyze api.
