### ISSUE TITLE
ESQL: add `text` type support to all functions accepting `keyword`

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#102552]
### Description

Currently, some functions accepting the `keyword` type accept `text` too. We should extend `text` function support to all functions.

**Comment by kyle-mallah** [comment]
Hi, I'm interested in contributing to this issue, if that aligns with current priorities.

Based on my understanding, this issue involves adding text type support to all functions that currently only accept keyword types. This could impact memory and execution time because text fields, due to tokenization, can result in more buckets and involve more data compared to keyword fields.

From my review, addressing this issue will require substantial effort:

1. **Performance considerations:** Each function, especially aggregations, needs case-by-case consideration for potential impacts on memory and execution times. It's also crucial to evaluate both downstream and upstream effects, such as decisions made by the query planner/optimizer.

2. **Code consistency & design**: Despite the case-by-case nature of this issue, we need to ensure the changes maintain design/implementation consistency across the production and test codebases.

3. **Risk of regressions**: Implementing changes across all functions at once could increase regression risks.

I propose considering a phased approach to extend this functionality incrementally to address the three points above.

Would this be a viable strategy and align with the current roadmap? If there is already a roadmap for these changes or discussions elsewhere, I’d greatly appreciate direction on where to start.

I am ready to begin by reviewing the anticipated challenges within each function, as well as the upstream/downstream impacts.

Thank you!

**Comment by bpintea** [comment]
Thanks for your interest @kyle-mallah. I believe we'd added `text` support to all remaining functions and this issue remained dangling. (Once can verify the functions in `EsqlFunctionRegistry` class and check their `resolveType()` for a `isString()` call, which checks on the two types.) Will close now, but if you spot any uncovered implementation feel free to just open a PR.
