### ISSUE TITLE
Proposal to include support for IBM Power/Z platform in Elasticsearch

### ISSUE THREAD

**Issue by bhavanisn** [elastic/elasticsearch#102597]
### Description

Currently ES does not compile on Power/Z platform as there is no platform support
Power platform is very popular and well known for its performance, reliability and scalability. It is used in wide variety of applications and systems. It would be beneficial for Elasticsearch to extend its compatibility to cater to broader range of users.

Rationale:
1. Open source availability and support: Communities like [adoptium.net](http://adoptium.net/) is a working group which distributes TCK certified runtimes technology for Java ecosystem. This provides free distribution of OpenJDK for Power platform 
2. Diversity: Supporting Power platform would provide users with more choice of deployment infrastructure allowing them to select platform that best suits their needs.
3. Growing User Base: Power architecture is very well known, robust, evolved over years and widely used. So by extending Elasticsearch support to this platform would attract new users and promotes more diverse and vibrant Elasticsearch community.

Prototype Implementation on Power (ppc64le):

[ppc64le_patch.txt](https://github.com/elastic/elasticsearch/files/13460412/ppc64le_patch.txt)

Let know about your opinion on this.

**Comment by DaveCTurner** [comment]
Adding support for additional processor architectures is not something we [undertake lightly](https://github.com/elastic/elasticsearch/issues/54930#issuecomment-610690848) since it entails a good deal of ongoing effort in testing and maintenance. Today we cannot justify that effort, we only know of a small minority of users wanting to run Elasticsearch on Power/Z. The costs still enormously outweigh the benefits so we will not be adding Power/Z support.

We monitor the situation on an ongoing basis; if we start to see compelling reasons to add support for additional processor architectures then we will reconsider.
