### ISSUE TITLE
Plugin manager should handle path `elastic/plugin/version` for installing plugins

### ISSUE THREAD

**Issue by brwe** [elastic/elasticsearch#10254]
The repository was renamed from `elasticsearch` to `elastic` but for installing plugins from this repository the path still needs to be `elasticsearch/plugin/version`. This is confusing.

**Comment by uboness** [comment]
we should keep the installation path `elasticsearch/...` as these are elasticsearch plugins

**Comment by brwe** [comment]
could we support both?

**Comment by bleskes** [comment]
+1 to support both as it is confusing. We promote the notion of the first part being a github user as well, which refers to the source of the plugin (same goes for maven), not the fact that is an ES plugin:

```
bin/plugin --install github_user/repo
```

so you could read `elasticsearch/marvel/latest` as get the marvel plugin, supplied by elasticsearch (the org/company) and I want the latest version. In this interpretation people can totally expect elastic to work. Bonus points for being shorter...

**Comment by uboness** [comment]
I'd say this is an attempt to put patches on a broken functionality to begin with... IMO we need to drop this "magic" support for github repo and maven... we can still support them but that can come with an additional explicit arg (e.g. `--github` and `--maven`)... for the rest all downloads should go to our downloads service (or the url defined by the `--url` arg)

**Comment by rjernst** [comment]
+1 to what @uboness said.

**Comment by tlrx** [comment]
I don't think we need the support for 'elastic' but I like the github and maven support. I think most users don't know if a community plugin is available on github or maven or something else. 

Here's what I've done in #9998: 

I updated the plugin manager to add a notion of [plugins repository](https://github.com/elastic/elasticsearch/pull/9998/files#diff-196560d7540091985eaa960c6472daafR27). Each repository can have multiple URL patterns (the defaults are [here](https://github.com/elastic/elasticsearch/pull/9998/files#diff-9030409020becbc44b2a241180305d0fR528)). An URL pattern is used to convert the user input like `elasticsearch/marvel/latest', 'elastic/marvel' or 'marvel' into a final URL that will be tested. If the URL works, the plugin is downloaded and installed. Otherwise it will try the next pattern. When all patterns are tested and failed, it can try another plugins repo or fails the install.

Because URL patterns are tested in order and plugins repositories can be chained, and because default URL patterns for our download service are:
```
http://download.elasticsearch.org/[organisation]/[name]/[name]-[version].zip
http://download.elasticsearch.org/[organisation]/elasticsearch-[name]/elasticsearch-[name]-[version].zip
http://download.elasticsearch.org/elasticsearch/[name]/[name]-latest.zip
```

the following commands will work:
```
bin/plugin install marvel                                          (match the 3rd pattern)
bin/plugin install elasticsearch/marvel/latest          (match the 1st pattern)
bin/plugin install elastic/marvel/latest                     (match the 3rd pattern)
```

There are default plugins repositories defined for sonatype, github and maven. A fixed URL or an URL pattern can explicitly be defined with the --url option. 

Another nice thing I'd like to add once the PR is merged is the ability for users to define their own plugins repository in configuration like bintray, jcenter or a shared filesystem (with a pattern like file:///path/to/my/plugins/[name]-[version].zip). It could help a lot with deployments where there's no external access.

**Comment by bleskes** [comment]
@tlrx sounds great. if these all work:

```
bin/plugin install marvel                       
bin/plugin install elasticsearch/marvel/latest
bin/plugin install elastic/marvel/latest  
```

I'm happy :)

**Comment by tlrx** [comment]
@bleskes if you're happy, I'm happy. :)

**Comment by brwe** [comment]
@tlrx I agree, once #9998 is merged this issue can be closed as far as I am concerned

**Comment by brwe** [comment]
#9998 was merged
