### ISSUE TITLE
Concurrent recoveries setting applies only to target nodes

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#10267]
Test case is to use shard allocation filtering to exclude a single node (node2) from the cluster:

Concurrent recoveries set to 1, “target” nodes are throttled because only 1 shard is initializing on each node due to relocation from node 2.  But this does not seem to apply to the “source” node (node2) where it is relocating 3 at a time.

![image](https://cloud.githubusercontent.com/assets/7216393/6834867/16835a86-d2f4-11e4-978b-8b0dab7118e4.png)

Compare this to concurrent recoveries set to 2 (default), “target” nodes have up to 2 shards relocating to each node (consistent with the concurrent recoveries setting).  Which equates to 6 concurrent relocations from node 2 occurring. 

![image](https://cloud.githubusercontent.com/assets/7216393/6834874/21052bb0-d2f4-11e4-98fb-dddcff20e248.png)

Have the impression that concurrent recoveries apply to both source and target nodes.  Is there a way to control the concurrent recoveries for the source node?  Or is this is a special case (for exclusions) where the idea is to get the shards off the node to be decommissioned as fast as possible so we are only applying concurrent recoveries to the “target” nodes and not the source ?

**Comment by bleskes** [comment]
> Have the impression that concurrent recoveries apply to both source and target nodes

The `cluster.routing.allocation.node_concurrent_recoveries` settings concerns initializng shards, which implicitly mean target nodes. 

For the source node we have the `indices.recovery.concurrent_streams` which control how many concurrent out going file copy requests we can have. That effectively throttles recoveries on the source.  

Was this causing any issue?

**Comment by ppf2** [comment]
Thanks @bleskes .  Tried `indices.recovery.concurrent_streams` but it does not appear to have an effect.  The following are the settings:

```
{
   "persistent": {
      "indices": {
         "recovery": {
            "concurrent_streams": "1"
         }
      },
      "cluster": {
         "routing": {
            "allocation": {
               "cluster_concurrent_rebalance": "2",
               "node_concurrent_recoveries": "2"
            }
         }
      }
   },
   "transient": {}
}
```

And the source is still showing 6 out going file copy requests.

![image](https://cloud.githubusercontent.com/assets/7216393/6857863/0b920fea-d3c7-11e4-89d0-75f1dfe44a9e.png)

For a ~100 node cluster with a node getting excluded, this is causing many out going file copy requests from the source node.

**Comment by bleskes** [comment]
@ppf2  yeah. I agree it's confusing. `indices.recovery.concurrent_streams` doesn't limit the number of source recoveries that can go on but rather how big the pull of out going requests they can have. The default of 3 means that all the recoveries copying files of a node can only have 3 "inflight" requests *together*. We also have a separate pool (and setting) for very small files to make sure those are not blocked by 3 large files. I'm wondering if we can just make do with the same concurrent recoveries as we do for the target side.

**Comment by clintongormley** [comment]
@bleskes anything to do here?

**Comment by bleskes** [comment]
yeah, I think this is still an open confusion. There were some extra discussion https://github.com/elastic/elasticsearch/issues/15161#issuecomment-161227518 and  https://github.com/elastic/elasticsearch/issues/15161#issuecomment-161755836 

The gist of the concern is that we need to find a way not to throttle recovery of replicas (from the primary)  for new indices. The reason is that two long ongoing relocations doesn't throttle getting to green when creating new indices (who's shard are small/empty so they don't matter).

**Comment by DaveCTurner** [comment]
This is an interesting idea but since its opening we have not seen enough feedback that it is something we should pursue. We prefer to close this issue as a clear indication that we are not going to work on this at this time. We are always open to reconsidering this in the future based on compelling feedback; despite this issue being closed please feel free to leave feedback (including +1s).
