### ISSUE TITLE
geoShapeQuery relation error?

### ISSUE THREAD

**Issue by gucasbrg** [elastic/elasticsearch#10271]
// Import Spatial4J shapes
import com.spatial4j.core.context.SpatialContext;
import com.spatial4j.core.shape.Shape;
import com.spatial4j.core.shape.impl.RectangleImpl;

// Also import ShapeRelation
import org.elasticsearch.common.geo.ShapeRelation;// Shape within another
QueryBuilder qb = geoShapeQuery(
        "location",                                     
        new RectangleImpl(0,10,0,10,SpatialContext.GEO) 
    )
    .relation(ShapeRelation.WITHIN);       

I find  relation function is not implement in geoShapeQuery ,but It's suggested with link: http://www.elastic.co/guide/en/elasticsearch/client/java-api/current/query-dsl-queries.html

**Comment by clintongormley** [comment]
@nknize any ideas?

**Comment by nknize** [comment]
I'm not sure why the docs have an example like this.  This is describing how to use a FilterBuilder not a QueryBuilder.  Here's the example using the FilterBuilder:

```java
FilterBuilder fb = geoShapeFilter("location", 
                                   ShapeBuilder.newEnvelope().topLeft(0,10).bottomRight(10,0), 
                                   ShapeRelation.WITHIN)
```
At the moment GeoShapeQueryBuilder does not accept a relation (everything boils down to ```CONTAINS``` || ```WITHIN``` || ```INTERSECTS```). This is primarily due to spatial query complexities in Lucene that haven't been cleaned up until recently. For the time being, to achieve more complex queries you can ```match_all``` and set a post filter, or you can combine a ```geoShapeQuery``` and post filter using the ```geoShapeFilter```.  

There are a few low hanging fruit issues and optimizations here that I need to write up.

**Comment by clintongormley** [comment]
@nknize can this be closed now?

**Comment by nknize** [comment]
++. Closing as non-issue
