### ISSUE TITLE
Aggregations: formatted string values are always returned in 1.5

### ISSUE THREAD

**Issue by gmarz** [elastic/elasticsearch#10284]
In ES 1.5, many aggregations now return a formatted `<foo>_as_string` version of the return values by default, even without specifying a `format` in the request, or regardless of the field type.

For instance:

```json
"aggregations": {
      "my_stats": {
         "count": 54,
         "min": 10148,
         "max": 19602,
         "avg": 15151.611111111111,
         "sum": 818187,
         "min_as_string": "10148.0",
         "max_as_string": "19602.0",
         "avg_as_string": "15151.611111111111",
         "sum_as_string": "818187.0"
      }
   }
```

Aggregations where I've observed this:

`as_string` always present:
- min
- max
- sum
- avg
- stats
- extended_stats
- value_count
- percentiles
- percentiles_ranks
- cardinality

`as_string` only present if the field is a date, regardless if `format` is specified or not:
- terms
- histogram
- date_histogram

Does it ever make sense to return a formatted version of a numeric field?  For dates, should we only return a formatted version if `format` is specified in the request?

**Comment by clintongormley** [comment]
@colings86 was this from one of your changes?

**Comment by colings86** [comment]
@clintongormley yes, I think it might be due to https://github.com/elastic/elasticsearch/pull/9032. I'll assign it to myself and hopefully get a fix soon

@gmarz formatting numeric results can be useful to do things such as padding and rounding when required. The `format` parameter should work on terms, and histogram when the field is numeric. I will look into that as well as fixing this issue so the `as_string` field is only present in the result when `format` is specified (or the field is a date).
