### ISSUE TITLE
Completion Suggester incorrect sorting by weight

### ISSUE THREAD

**Issue by ravlio** [elastic/elasticsearch#10406]
```
"version" : {
    "number" : "1.4.4",
    "lucene_version" : "4.10.3"
  }
```

I have about **20m** database of keywords such as:
"**car**" (weight is 100)
"**buy car**" (weight is 50) 
"**buy used car**" (weight is 10)
...
each keyword having weight equal popularity. Initial mapping is:

```
PUT /suggestions/search/_mapping
{
  "search": {
            "properties": {
               "suggest": {
                  "type": "completion",
                  "analyzer": "standard"
               }
            }
         }
}
```

And indexing is simple:

```
PUT /suggestions/search/1
{
   "name": "car"
   "suggest": {
      "input": "car",
      "weight": 100
   }
}
```
So, considering the above list, when I type "car" I will only get "**car**" query. It worked fine as long as I did not want to look up words in middle of phrase. The solution I have found is split keyword to words and add them ti suggestion input as array:

```
PUT /suggestions/search/1
{
   "name": "buy used car"
   "suggest": {
      "input": ["buy", "used", "car"],
      "weight": "10"
   }
}
```

Now when I type "car" I can find all of three keywords correctly sorted by weight. The solution was very rapid, much faster then any other elasticsearch autocompletion features. But then there was a big problem.

When I reached 200k different keywords related to "car" (indexing arrays like [best, car, buy], [car, rental], [used,car,sale], etc...), I have problem with sorting by weight. When I make query:

```
GET /suggestions/_suggest
{
   "text" : "car",
   "completion": {
      "field": "suggest"
   }
}
```
The results are sorted in wrong order. The weight (imagine that top keyword "car" has 200k weight and bottom is 1) is shifted randomly and first result has a weight of 100-180k instead of 200k.

You can reproduce this by creating index in loop (pseudo-code):

```
for ($i=1;$i<200000;$i++)
{

   PUT /suggestions/search/$i
   {
      "name": "$i"
      "suggest": {
         "input": ["test", "$i"], // $i as second word is needed otherwise results will be merged
         "weight": $i
      }
   }

}
```

Then try to search "test" and you can see something like this:

```
{
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   },
   "suggest": [
      {
         "text": "test",
         "offset": 0,
         "length": 4,
         "options": [
            {
               "text": "179992",
               "score": 179992
            },
            {
               "text": "179940",
               "score": 179940
            },
            {
               "text": "179868",
               "score": 179868
            },
            {
               "text": "179820",
               "score": 179820
            },
            {
               "text": "179696",
               "score": 179696
            }
         ]
      }
   ]
}
```

As you can see, first result is 179992, not 200000. Of course the top weight is 200k and index contains 200k elements. What could be the problem? This is feature of FST working or just a bug?

**Comment by areek** [comment]
Thanks for the detailed report, @ravlio!
Currently, there is a hard limit of at most 256 duplicated analyzed form per (lucene) segment, after which the suggestion entries are ignored. It seems like you have hit that limit.
In this case, the analyzed form of "car" must have exceeded that limit in some segments and hence you see missing suggestions. 
A work-around might be to use multiple surface forms to represent "car", s.t. none of the surface forms hit this limit. 
This is a known issue, we are working towards removing this limitation.

**Comment by ravlio** [comment]
Finally, I have found a trick to solve problem with limitations. Simply we append each input word with set of random characters (5 chars length is enough to for getting unique words). Another hint is to make first character of appending numeric. 

So the indexing now looks like:
```
"suggest": {
         "input": ["best card to buy", "best1dricj", "car1vjtiw", "buy1clskq"], // "to" is a stopword and omitted
         "output" : "best car to buy", // output is required to get whole phrase in results instead of searchable words 
         "weight": 123
      }
```

The "**1**" digit prevents cases when word and random string form other words. For example, in some case  we can get randomly word "**cardhsqoe**" which besides "**car**" will be also searched by "**card**" giving inaccurate results. Maybe is is possible to more unique character like "**#**", need to try.

This solution words perfectly in 20m index.

**Comment by emsipl** [comment]
Hi. How is the work going regarding this suggestion limit? In the meantime is it possible to change it somehow in my ES configuration? I also have this problem, but @ravlio's solution doesn't work for me, because I want each individual name to pop up in suggestion results only once. The case I'm having is:

over 1k documents with input "**car**", different weight for each document, max weight: 800
over 1k with input "**card**", different weight for each document, max weight: 1000
over 1k with input "**carpet**", different weight for each document, max weight: 700

When I search for "**car**" I expect to get 3 suggestions in following order: **card**, **car**, **carpet**. But now the order is: **car**, **carpet**, **card** (seems like the first 256 "card" documents searched were only the ones with low weight values, and after 256 entries ES just stopped looking). I cannot add random string to every single document, because I can end up having results like: 

```
card [input:card1abc,weight:1000]
card [input:card1xyz,weight:900]
car [input:car1def,weight:800]
carpet [input:carpet1qwe,weight:700] 
```

which is not acceptable (I use it for autocomplete and I don't want to suggest the same word twice). Obvious fix would be to prepare my data so each document would have the weight equal to max weight of all documents with the same name (i.e. all **car** documents would have the weight 800, all **card** documents would be weighted with 1000, etc.), but it would be very costly (performance-wise) for me to prepare the data this way. 

Do you have any suggestions or can you tell the ETA for removing the 256 duplicated entries limitation?

**Comment by trompx** [comment]
Hello,

ES version: 5.2

Thanks a lot for the solution @ravlio. Unfortunatly, it is not fully working in my case. I have less data so I don't really know what may be the bug.

I have 15 strings composed of multiple words : `word1 word2 word3 word4 ...`
word1 is common to all of those 15 strings.
I index as input all permutation of those words (I have between 30-1000 inputs for each indexed documents).
```
"suggest": {
         "input": ["word1", "word2", "word3", "word4", "word1 word2", "word1 word3" and so on...],
         "output" : "word1 word2 word3 word4",
         "weight": 1000
}
```
Searching for word1 was only returning 2 strings.

I tried adding a random string at the end of each input:
```
"suggest": {
         "input": ["word1$rnd1", "word2$rnd2", "word3$rnd3", "word4$rnd4", "word1 word2$rnd5", "word1 word3$rnd6" and so on...],
         "output" : "word1 word2 word3 word4",
         "weight": 1000
}
```
Now I get more results, but only 5 out of 15.

Did you find a better solution?

@areek Did you come up with something to remove that limitation?

Thank you
