### ISSUE TITLE
Document the `deprecated` flag for templates

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#104052]
### Description

We currently support this flag, but haven't documented it. We should add this to the public documentation.

**Comment by felixbarny** [comment]
Turns out I actually did document this flag in #101148. I just looked at the wrong version ([8.11](https://www.elastic.co/guide/en/elasticsearch/reference/8.11/indices-component-template.html#put-component-template-api-request-body) (current) instead of [8.12](https://www.elastic.co/guide/en/elasticsearch/reference/8.12/indices-component-template.html#put-component-template-api-request-body) (master)).
