### ISSUE TITLE
BulkRequest with listener waiting for response fails assertion 'Expected current thread [...] to not be a transport thread'

### ISSUE THREAD

**Issue by nmunro-cvt** [elastic/elasticsearch#10402]
Starting with 1.5.0, creating a bulk request then calling **bulkRequest.execute().addListener(...)** results in
> java.lang.AssertionError: Expected current thread [...] to not be a transport thread. Reason: 

full stack trace : https://gist.github.com/nmunro-cvt/ea14d625629692ef2773

Started happening in 1.5.0, same code works fine pre-1.5.0.

Noticed some new assertions were introduced in 1.5.0
> https://github.com/elastic/elasticsearch/blob/master/src/main/java/org/elasticsearch/common/util/concurrent/BaseFuture.java#L117

However, I don't see what I need to do differently to pass the assertions.

Simplified example to reproduce error: https://gist.github.com/nmunro-cvt/0be42236e9abf4359a44

**Comment by clintongormley** [comment]
@jpountz any ideas what should be changed here?

**Comment by jpountz** [comment]
It looks to me like an actual bug that we only find about now thanks to #9164. The transport thread waits for the action to be executed so that it can run the listeners, but my understanding is that we should never wait in transport threads?

@bleskes @s1monw Since you helped reviewing on #9164 could you have a look at this issue and confirm/infirm this is a real bug?

**Comment by clintongormley** [comment]
@bleskes assigning to you

**Comment by bleskes** [comment]
this should be fixed now with https://github.com/elastic/elasticsearch/pull/10573 . @nmunro-cvt thx for reporting!
