### ISSUE TITLE
elasticsearch number matching does not working

### ISSUE THREAD

**Issue by bairaginath** [elastic/elasticsearch#10416]
elasticsearch does not work with exactly matching with number. if i wanted to search price=53.it retrieve all prices of 53,531,5394,............so on ........

**Comment by javanna** [comment]
Hi @bairaginath may I ask you to move your question to our [mailing list](https://groups.google.com/forum/?fromgroups=#!forum/elasticsearch) please? Please describe your problem thoroughly there and you'll get help for sure. We use github issues for bugs and feature requests, if it turns out that you found a bug you can still open a new issue including a complete recreation for it. Thanks!
