### ISSUE TITLE
Write alias resolution doesn't work with TSDS with lookahead.

### ISSUE THREAD

**Issue by gmarouli** [elastic/elasticsearch#104189]
### Elasticsearch Version

main

### Java Version

_bundled_

### OS Version

n/a

### Expected behaviour

As a user when I use a write alias pointing to a TSDS data stream I expect indexing will be directed to the correct index. 

### Current behaviour

When we try to index a document to TSDS via the write alias right after a rollover and for the duration of the lookahead, the write alias resolves to the latest index, which is in most cases not the correct one until the lookahead time passes.

### Steps to Reproduce

1. Create a TSDS template
```
PUT _index_template/my-tsds-test
{
  "index_patterns": ["my-tsds-test-*"],
  "data_stream": { },
  "template": {
    "settings": {
      "index.mode": "time_series",
      "index.routing_path": [ "name" ],
      "index.look_ahead_time": "30m"
    },
    "mappings": {
      "properties": {
        "name": {
          "type": "keyword",
          "time_series_dimension": true
        },
        "@timestamp": {
          "type": "date",
          "format": "strict_date_optional_time"
        }
      }
    }
  }
}
```

2. Index documents with the current timestamp 
```
PUT my-tsds-test-index/_bulk
{ "create":{ } }
{ "@timestamp": "2024.01.10T09:23:00.000Z", "name": "HAL-000001" }
{ "create":{ } }
{ "@timestamp": "2024.01.10T09:23:00.000Z", "name": "SYKENET-000001" }
```

3. Perform a rollover, during which a new index is added `-000002` but documents with the current timestamp should still go to the `-000001` because of the lookahead time.
```
POST my-tsds-test-index/_rollover
```
4. Try to write documents using write alias
```
PUT my-tsds-test-index-write-alias/_bulk
{ "create":{ } }
{ "@timestamp": "2024.01.10T09:24:00.000Z", "name": "HAL-000002" }
{ "create":{ } }
{ "@timestamp": "2024.01.10T09:24:00.000Z", "name": "SYKENET-000002" }

#Response:
{
  "errors": true,
  "took": 2,
  "items": [
    {
      "create": {
        "_index": ".ds-my-tsds-test-index-2024.01.10-000002",
        "_id": null,
        "status": 400,
        "error": {
          "type": "document_parsing_exception",
          "reason": "[1:66] failed to parse: time series index @timestamp value [2024.01.10T09:24:00Z] must be larger than 2024.01.10T09:54:00Z",
        "caused_by": {
          "type": "illegal_argument_exception",
          "reason": "time series index @timestamp value [2024.01.10T09:24:00Z] must be larger than 2024.01.10T09:54:00Z"
        }
      }
    }
  },
  {
    "create": {
      "_index": ".ds-my-tsds-test-index-2024.01.10-000002",
     "_id": null,
     "status": 400,
     "error": {
       "type": "document_parsing_exception",
       "reason": "[1:70] failed to parse: time series index @timestamp value [2024.01.10T09:24:00Z] must be larger than 2024.01.10T09:54:00Z",
       "caused_by": {
         "type": "illegal_argument_exception",
         "reason": "time series index @timestamp value [2024.01.10T09:24:00Z] must be larger than 2024.01.10T09:54:00Z"
          }
        }
      }
    }
  ]
}
```

**Comment by limotova** [comment]
Hi,
I took a look into this and I think the source of the issue is when TransportBulkAction goes to [process the request](https://github.com/elastic/elasticsearch/blob/149f4a1376819fc01107fcbe5ed9ad5278051bf3/server/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java#L680). The concrete write index is determined by `ia` (by calling `ia.getWriteIndex(...)`). 
When you run the request via the data stream name, `ia` is a DataStream and if the DataStream is a time series data stream specifically it uses the timestamp to [calculate](https://github.com/elastic/elasticsearch/blob/149f4a1376819fc01107fcbe5ed9ad5278051bf3/server/src/main/java/org/elasticsearch/cluster/metadata/DataStream.java#L1115) the correct index . 
But when you run the request via the alias, `ia` is an Alias and it just uses whatever [index](https://github.com/elastic/elasticsearch/blob/149f4a1376819fc01107fcbe5ed9ad5278051bf3/server/src/main/java/org/elasticsearch/cluster/metadata/IndexAbstraction.java#L254) is in its `writeIndex` field. For aliases to data streams, the `writeIndex` is the latest backing index.

To fix this I think the Alias class probably needs some way of knowing that it's a time series data stream, or perhaps a reference to the DataStream itself. 
From what I can tell the `referenceIndices` field in Alias contains all of the backing indices, so it might just be a matter of adding an extra `isTimeSeries` boolean and doing the timestamp logic on `referenceIndices`.

**Comment by limotova** [comment]
Yes I think it should be possible to give the alias access to the data stream and use only the `dataStreamAlias` boolean.
I made a draft PR https://github.com/elastic/elasticsearch/pull/104440, just wanted to make sure this matches what you were thinking of before I add tests. I believe it fixes the issue though
It fetches the current write index (the latest backing index), gets its parent data stream, and then delegates `getWriteIndex(...)` to the parent data stream.

**Comment by gmarouli** [comment]
@limotova yes, that's exactly what I had in mind, I do not know off the top of my head if this is the most efficient way to retrieve the data stream (it might well be) but the idea is what I was thinking too.

**Comment by limotova** [comment]
Great, let me clean it up and add some tests then, I'll open a non-draft PR in a bit

**Comment by limotova** [comment]
I updated the PR..!
