### ISSUE TITLE
[CI] discovery-gce tests failing on 7.17 with FIPS enabled

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#104174]
I'm able to reliably reproduce this failure by running `./gradlew :plugins:discovery-gce:qa:gce:yamlRestTest -Dtests.fips.enabled=true`.

https://gradle-enterprise.elastic.co/s/ytywzcmb7umy6

```
* What went wrong:
Execution failed for task ':plugins:discovery-gce:qa:gce:yamlRestTest'.
> `cluster{:plugins:discovery-gce:qa:gce:yamlRestTest}` failed to wait for cluster health yellow after 40 SECONDS
    IO error while waiting cluster
    503 Service Unavailable
```

**Comment by mark-vieira** [comment]
@jakelandis Is it possible #104086 is related here?

**Comment by jakelandis** [comment]
Indeed it is related. I reverted `93af6465bba7a7398e4eb766ee554f842cdd1153` locally and the test passes. I will fix this or revert this tomorrow. If this causes issues in the 24 hours feel free to push the revert. 

Full error:
> » [2024-01-09T17:23:11,738][WARN ][o.e.c.g.GceInstancesServiceImpl] [yamlRestTest-1] unable to resolve project from metadata server for GCE discovery service
»  java.io.IOException: parseAlgParameters failed: PBE AlgorithmParameters not available
»       at sun.security.pkcs12.PKCS12KeyStore.parseAlgParameters(PKCS12KeyStore.java:855) ~[?:?]
»       at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2113) ~[?:?]
»       at sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:221) ~[?:?]
»       at java.security.KeyStore.load(KeyStore.java:1473) ~[?:?]
»       at com.google.api.client.util.SecurityUtils.loadKeyStore(SecurityUtils.java:80) ~[google-http-client-1.41.1.jar:1.41.1]
»       at com.google.api.client.googleapis.GoogleUtils.getCertificateTrustStore(GoogleUtils.java:86) ~[google-api-client-1.33.1.jar:1.33.1]
»       at com.google.api.client.googleapis.javanet.GoogleNetHttpTransport.newTrustedTransport(GoogleNetHttpTransport.java:87) ~[google-api-client-1.33.1.jar:1.33.1]
»       at com.google.api.client.googleapis.javanet.GoogleNetHttpTransport.newTrustedTransport(GoogleNetHttpTransport.java:58) ~[google-api-client-1.33.1.jar:1.33.1]
»       at org.elasticsearch.cloud.gce.GceInstancesServiceImpl.getGceHttpTransport(GceInstancesServiceImpl.java:176) ~[discovery-gce-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»       at org.elasticsearch.cloud.gce.GceInstancesServiceImpl.getAppEngineValueFromMetadataServer(GceInstancesServiceImpl.java:157) ~[discovery-gce-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»       at org.elasticsearch.cloud.gce.GceInstancesServiceImpl.resolveProject(GceInstancesServiceImpl.java:130) [discovery-gce-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»       at org.elasticsearch.cloud.gce.GceInstancesServiceImpl.<init>(GceInstancesServiceImpl.java:119) [discovery-gce-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»       at org.elasticsearch.plugin.discovery.gce.GceDiscoveryPlugin.createGceInstancesService(GceDiscoveryPlugin.java:74) [discovery-gce-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»       at org.elasticsearch.plugin.discovery.gce.GceDiscoveryPlugin.lambda$getSeedHostProviders$1(GceDiscoveryPlugin.java:80) [discovery-gce-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»       at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) [?:?]
»       at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) [?:?]
»       at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) [?:?]
»       at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) [?:?]
»       at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) [?:?]
»       at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) [?:?]
»       at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:?]
»       at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) [?:?]
»       at org.elasticsearch.discovery.DiscoveryModule.<init>(DiscoveryModule.java:157) [elasticsearch-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»       at org.elasticsearch.node.Node.<init>(Node.java:886) [elasticsearch-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»       at org.elasticsearch.node.Node.<init>(Node.java:309) [elasticsearch-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»       at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:234) [elasticsearch-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»       at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:234) [elasticsearch-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»       at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:434) [elasticsearch-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»       at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:169) [elasticsearch-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»       at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:160) [elasticsearch-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»       at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:77) [elasticsearch-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»       at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112) [elasticsearch-cli-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»       at org.elasticsearch.cli.Command.main(Command.java:77) [elasticsearch-cli-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»       at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:125) [elasticsearch-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»       at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80) [elasticsearch-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»  Caused by: java.security.NoSuchAlgorithmException: PBE AlgorithmParameters not available
»       at sun.security.jca.GetInstance.getInstance(GetInstance.java:159) ~[?:?]
»       at java.security.Security.getImpl(Security.java:676) ~[?:?]
»       at java.security.AlgorithmParameters.getInstance(AlgorithmParameters.java:157) ~[?:?]
»       at sun.security.pkcs12.PKCS12KeyStore.parseAlgParameters(PKCS12KeyStore.java:849) ~[?:?]
»       ... 34 more

**Comment by jakelandis** [comment]
https://github.com/elastic/elasticsearch/pull/104179 raised to fix the issue. Artem ran into the same issue in main and already fixed there, so that PR is just the necessary backport.

**Comment by jakelandis** [comment]
fixed by https://github.com/elastic/elasticsearch/pull/104179
