### ISSUE TITLE
Logger warning using Elasticsearch Java API

### ISSUE THREAD

**Issue by Ghost93** [elastic/elasticsearch#10421]
Hi,

We have a java application that indexes documents to an elasticsearch setup.
The application uses log4j2 as its' logging library.

At startup, when _Client_ is initialized, the following warning messages occur:

`log4j:WARN No appenders could be found for logger (org.elasticsearch.plugins).`
`log4j:WARN Please initialize the log4j system properly.`
`log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.`

The easy solution would be to hold log4j.properties file but I try to avoid this, since I already use log4j2.properties I would prefer to "bridge" over elastic's log4j logs to my log4j2.

I tried creating a logger at my log4j2 configuration named `org.elasticseach.plugins` but it didn't help.

Googling this problem found [this stackoverflow question](http://stackoverflow.com/questions/24543787/logger-warning-using-elasticsearch-java-api) that was posted a year ago and was not answered.
I email the guy asked the question and he said in the end they didn't solve it, just left it.

Anyone got an idea?

Thanks.

**Comment by snowwolf007cn** [comment]
Oops, I have the same problem

**Comment by jmcomets** [comment]
+1, same problem here. This is really cluttering my logs/nerves.

**Comment by rubenve** [comment]
+1 I'm the Stackoverflow guy. :)

**Comment by Ghost93** [comment]
@clintongormley 
any news on this issue?

**Comment by oubenali** [comment]
Has anyone found a solution ? I received the same warnings

**Comment by jmoney8080** [comment]
Do you use the slf4j-apis with the log4j2 bindings or do you use the log4j2 apis directly?  

The "future proof" way of doing this is use the slf4j-apis with an slf4j implementation of the apis(in this case log4j2). Then, you can use the log4j12-over-slf4j library that routes all log4j to slf4j which should then proxy to log4j2 in your case. 

That "should" work. It's how I migrated everything to logback a year ago in some of my projects and I encountered similar errors. I assume the same process would work for log4j2(just have not tried it yet) as this problem is exactly why slf4j came into existence in the first place.

**Comment by Ghost93** [comment]
@jmoney8080 could you please provide a detailed sample?
Thanks!

**Comment by jmoney8080** [comment]
https://github.com/jmoney8080/slf4j-example

you can download that repo and run mvn clean -U package and it should compile and show the logging.  There is a README explaining the setup.

Basically, 
1) log4j is ONLY a log4j project
2) log4j2 is ONLY a log4j project
3) slf4j-log4j2 depends on (1) and (2) but uses slf4j with log4j implementation.  It then delegates all log4j classes to slf4j so that logging from all three classes continues to work.

**Comment by jasontedor** [comment]
Closing in favor of #17697.
