### ISSUE TITLE
Require units be specified for time configuration

### ISSUE THREAD

**Issue by nemonster** [elastic/elasticsearch#10466]
Default units for attributes such as discovery.zen.ping_timeout are milliseconds, but the documentation often uses values in seconds when describing defaults.  Unless you specify the units when modifying one of these values, for instance using 30 vs. 30s you will wind up with 30 milliseconds, which was not intended.  Requiring a valid time unit when setting one of these should be required.  Alternatively, documentation could be expanded to flag this as a possible opportunity for misconfiguration.  Especially in areas where an incorrect setting is likely to result in instability such as discovery.zen.ping_timeout.

**Comment by clintongormley** [comment]
Related to #7633

**Comment by ppf2** [comment]
It sounds like there are backwards compatibility concerns around requiring a time units.  Have we considered implementing smarter defaults when whole numbers are detected for settings in the meantime?  For example, there are settings out there that can be dangerous when mistakenly set to whole numbers (and we have seen this happen in production environments), things like zen discovery and fault detection timeouts, refresh and flush intervals, etc..  Instead of defaulting everything to milliseconds when whole numbers are detected, perhaps we can selectively default to milliseconds only for settings that makes sense?  For example, if refresh interval is set to a whole number and is <1000, ignore the setting and use the system default value (eg, 1s)  and write a warning to the log file indicating that we are falling back to the system default as a safety measure, etc..

**Comment by jpountz** [comment]
Fixed via https://github.com/elastic/elasticsearch/pull/11437
