### ISSUE TITLE
Expose fine-grained metadata_read and metadata_write blocks settings

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#10498]
The update indices settings api currently allows to add blocks to indices as follows:

`index.blocks.read` => block data reads
`index.blocks.write` => block data writes
`index.blocks.metadata` => block metadata reads and writes

We also have the `index.blocks.read_only` shortcut that allows to block data writes and metadata operations. As soon as #9203 is in the latter will only block data writes and metadata writes, meaning that metadata reads will be possible against a read_only index.

It might be beneficial to expose as setting the distinction between metadata read and write blocks made possible with #9203, as we do with data. The idea would be to deprecate the `index.blocks.metadata` and add `index.blocks.metadata_read` and `index.blocks.metadata_write`.

Opening this up for discussion.

**Comment by tlrx** [comment]
+1

**Comment by clintongormley** [comment]
+1

**Comment by clintongormley** [comment]
Also, change `read_only` to be a shortcut for setting `write: false` and `metadata_write: false` so that these settings don't interfere with each other

**Comment by mstruve** [comment]
+1 Would love the ability to prevent metadata writes to protect our indexes and their settings while still allowing doc read/writes.

**Comment by ywelsch** [comment]
@javanna what's the status on this? Do you still think this is something we should do?

**Comment by javanna** [comment]
@ywelsch potentially, probably good to look into it and revive the discussion around it to see if it's something that is still interesting.

**Comment by tlrx** [comment]
We talked about this today and we agreed on not implementing this change for now. Since it's been opened this issue gained little traction and we'd like to dedicate our time to implement changes we find more valuable to users.

As a possible workaround, Elasticsearch's security (free starting versions 6.8.0 and 7.1.0) can be used to configure more fine grained access controls in order to prevent index settings updates while allowing indexing docs.
