### ISSUE TITLE
ES|QL: Bug in filtering of null values on multivalued

### ISSUE THREAD

**Issue by xeraa** [elastic/elasticsearch#104995]
### Elasticsearch Version

8.12.0

### Java Version

_bundled_

### OS Version

Elastic Cloud

### Problem Description

Adding a singlevalue and a multivalue field returns null — this is expected. When wanting to exclude the row from the final result set, I tried to do this with `WHERE sum IS NOT NULL`. This does not exclude the row from the result.

Surprisingly, the opposite condition excludes it (`WHERE sum IS NULL`). It feels like this is the wrong way around?

### Steps to Reproduce

Query:

```
POST _query?format=txt
{
  "query": """
    ROW a = 5, b = [ 1, 2 ]
    | EVAL a - 3, b + 2, sum = a + b
    | LIMIT 1
    | WHERE sum IS NOT NULL
  """
}
```

**Comment by luigidellaquila** [comment]
Most likely the problem is in [OptimizerRules$FoldNull](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/optimizer/OptimizerRules.java#L1673) and in [Expressions.nullable()](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/expression/Expressions.java#L83).
These are QL components, and since SQL/EQL have a slightly different behavior regarding multi-values, they could not fit ESQL needs completely.

We can adopt a precautionary approach and disable that rule completely, or we could override `nullable()` method for all the ESQL operators. For sure we'll have to do it for arithmetic operators and for binary comparisons (the same bug happens if we replace `a + b` with `a == b`)

**Comment by luigidellaquila** [comment]
The problem seems to be more extended: `nullable()` is used by other rules and components like `BinaryComparisonSimplification`, `InferIsNotNull`, `PropagateNullable`

And it's not limited to binary operators, but it also extends to functions, eg. the following has the same problem:

```
ROW a = "foo", b = [ "bar", "baz" ]| EVAL c = concat(a, b)| LIMIT 1 |  WHERE c IS NOT NULL
```
