### ISSUE TITLE
Add IMDSv2 support to `repository-s3` plugin

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#105135]
Today we support [IMDSv2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html) in the `discovery-ec2` plugin (see https://github.com/elastic/elasticsearch/pull/84410) but `repository-s3` still only supports IMDSv1. Should we add IMDSv2 support to `repository-s3`?

**Comment by ATecha** [comment]
I'm running into this at work, where we're required to use IMDSv2.
I'm glad I found the recent post by strophy; I've been pulling my hair out on this as well.
I'd also like this info be added to the documentation (that only v1 is currently supported), to save others from the frustration, at least while v2 support is being added.

**Comment by benriou** [comment]
We are also interested in IMDSv2 support for the repository-s3 plugin.

The only machines that still make unauthenticated calls to IMDS are Elasticsearch hosts due to a lack of IMDSv2 support.

**Comment by ParinithaNagaraja** [comment]
Any updates on when repository-s3 will support IMDSv2 ? Is there a timeline for this?. 
Does anyone know of a technical representative who we can contact?

**Comment by fabianocosta** [comment]
We also need it here. Any updates?

**Comment by alanwds** [comment]
I spend some time trying to understand the reason why backup (and any other operations related to S3) fail in one of our clusters. Unfortunately, we are using a old version of ES (6.3) and repository-s3 plugin (6.3.2). The response is quit confuse:

```curl -H 'Content-Type: application/json' "http://localhost:9200/_cat/snapshots/my_repo?v&s=id"
{
  "error": {
    "root_cause": [
      {
        "type": "amazon_service_exception",
        "reason": "Unauthorized (Service: null; Status Code: 401; Error Code: null; Request ID: null)"
      }
    ],
    "type": "amazon_service_exception",
    "reason": "Unauthorized (Service: null; Status Code: 401; Error Code: null; Request ID: null)"
  },
  "status": 500
}```

The log is also limited

```
[WARN ][r.suppressed             ] path: /_cat/snapshots/my_repo, params: {s=id, v=, repository=my_repo}
com.amazonaws.AmazonServiceException: Unauthorized (Service: null; Status Code: 401; Error Code: null; Request ID: null)
	at com.amazonaws.internal.EC2CredentialsUtils.handleErrorResponse(EC2CredentialsUtils.java:156) ~[?:?]

```

I hope that this can be usefull for anyone facing this "issue".

**Comment by vespatest** [comment]
Hi there,

After some detailed debugging into repository-s3 it seems it uses S3Service from AWS for authentication and it seems there are no elastic search customizations there. In our case AWS SDK (aws-java-sdk-core) was old (1.11.294) and it was NOT supporting IMDSv2. 
Minimal versions of all SDKs supporting IMDSv2 can be found here:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html#use-a-supported-sdk-version-for-imdsv2
So once we updated the version of AWS SDK to a newer one the support for IMDSv2 comes out of the box!
In fact recent versions of ElasticSearch use recent versions of AWS SDK and therefore the IMDSv2 should be supported without any extra effort from Elastic Search people.
More on that for older version of ElasticSearch is still should be possible to use newer version of AWS SDK because it is backward compatible (in most cases!)

I hope this helps!

Regards,
JV

**Comment by k4kratik** [comment]
any updates on this ?

**Comment by harikishore-nuk** [comment]
is IMDSv2 support for "repository-s3" avaialble now?

**Comment by DaveCTurner** [comment]
Yes, see https://github.com/elastic/elasticsearch/pull/117748
