### ISSUE TITLE
Better highlighting fragment support for fields with list/array values

### ISSUE THREAD

**Issue by pulquero** [elastic/elasticsearch#10528]
If I have a document like {"prop":["a...", "b..", "c...", ...]} and perform highlighting with max_fragments=n it is entirely possible for all those fragments to come from just the first list entry. It would be helpful if there was some setting/option to set the max fragment size per list entry.

Even better would be if the json response contained some indication of which list entry each fragment came from.

**Comment by clintongormley** [comment]
Hi @pulquero 

An array of terms in Elasticsearch is indexed just like an analyzed string field, eg the text `The quick brown fox`, would get indexed in the same way as an array `[the, quick, brown, fox]`.

What you're asking for wouldn't make sense in the context of analyzed strings, as far as I understand. Realistically, I don't think there is any generic setting that we can support here.  Sorry.

**Comment by pulquero** [comment]
That is not strictly true, because if I set num_fragments to 0, I get a fragment array the same length as my string field array. e.g. if I use highlight tags the following happens:

[the, quick, brown, fox] -> [<B>the</B>, <B>quick</B>, <B>brown</B>, <B>fox</B>].[the quick brown fox] -> [<B>the</B> <B>quick</B> <B>brown</B> <B>fox</B>].

So my current work-around is to have num_fragments=0, then post-process each fragment array element by splitting it on the highlight tags, and restricting it to say the first 2 highlights. Essentially, I'm looking for some setting to do that.



     On Monday, 13 April 2015, 10:50, Clinton Gormley <notifications@github.com> wrote:
   

 Hi @pulquero An array of terms in Elasticsearch is indexed just like an analyzed string field, eg the text The quick brown fox, would get indexed in the same way as an array [the, quick, brown, fox].What you're asking for wouldn't make sense in the context of analyzed strings, as far as I understand. Realistically, I don't think there is any generic setting that we can support here. Sorry.—

**Comment by nik9000** [comment]
> It would be helpful if there was some setting/option to set the max fragment size per list entry.

Do you mean to say "it would be helpful if there was some option to set the maximum number of fragments per list entry"? As in "I only want one fragment per list entry but I want the top five fragments."  That wouldn't be inconceivable to implement using the [experimental highlighter](https://github.com/wikimedia/search-highlighter) but against the three built into Elasticsearch it'd be harder.  Partly it'd just be harder because you'd have to do it three times.  And partly harder because all but the plain highlighter don't load the field value in the order that you'd need it.

Upshot: if you want it you'll have to implement it yourself.  If you implement it against the experimental highlighter I linked above I'll code review it.

I figure its worth me saying this: I'm not part of the Elasticearch team. I just maintain the experimental highlighter.
