### ISSUE TITLE
Change default suggestion mode to `popular`

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#10537]
The default suggest mode for Term and Phrase suggester is `missing`.  This can be problematic since typos in the index will prevent any suggestions will come back.  It's fine if you want that behavior, but as a default, it is a little user-unfriendly.  

`popular` would probably make a better default, since it will (usually) provide good suggestions despite the presence of typos in the index. 

Missing can also introduce strange artifacts due to shard-local information.  The nature of "suggest only if missing from the index" makes the shard-local abnormalities more apparent than the relative weighting of `popular`.

**Comment by clintongormley** [comment]
+1

**Comment by edudar** [comment]
On the other hand, `popular` brings up suggestions for correctly spelled terms simply because the other word is more 'popular'. In my case, it was `kia -> ia`, `tesla -> tells`, `oath -> with`, etc. So I have to make various moves with multiple suggeters to make things OK, cause we have typos in the index (UGC) and `missing` does not work properly...

**Comment by jimczi** [comment]
cc @elastic/es-search-aggs

**Comment by polyfractal** [comment]
We chatted about this in the search meeting. There are pros and cons to each, and the "correct" choice really depends on what the user is looking for.  So it doesn't make sense to move to a different default that has a different set of trade offs.

Seeing as there's only been one +1 and one -1 in three years, we're going to close and leave the default as `missing`. :)
