### ISSUE TITLE
Need a API to get exists script languages list of ES cluster.

### ISSUE THREAD

**Issue by chenryn** [elastic/elasticsearch#10548]
https://github.com/elastic/kibana/pull/3558

Then we can select the language from the list in Kibana settings.

**Comment by rashidkpc** [comment]
@clintongormley with painless coming about soon it would be really helpful to get this.

**Comment by clintongormley** [comment]
Once https://github.com/elastic/elasticsearch/issues/17114 is in, running the following command will provide the necessary info:

    GET _cluster/settings?include_defaults&filter_path=**.script.engine.*.inline

**Comment by colings86** [comment]
So I guess the tricky bit here is ensuring the returned list of script languages is consistent between different nodes. Because script languages are registered in plugins and plugins are installed on individual nodes you could end up in the situation where a node reports a script language is available but when the script is run on a different node (because a shard involved in the request is on a different node) it fails because that node doesn't have that script language available.

Would we be ok with having the API just return the list of script languages available on the node that was sent the request? What if the node that is sent the request is a master node or a client node, do we still ask for its list of installed languages? Should we forward the request to a random data node and get it's list of installed languages?

**Comment by clintongormley** [comment]
Closed by #17114
