### ISSUE TITLE
Artificial term vectors are generated only for stored fields

### ISSUE THREAD

**Issue by salvatore-campagna** [elastic/elasticsearch#105649]
### Elasticsearch Version

8.14 and above

### Java Version

_bundled_

### OS Version

All

### Problem Description

As a result of making the [`_ignored` field not stored ](https://github.com/elastic/elasticsearch/pull/101373)and having just doc values we are missing generation of term vectors for it. `TermVectorsService#addGeneratedTermVectors` indeed, generates term vectors only for stored fields. Since `_ignored` is no longer a stored field term vectors are not generated anymore. We need to fix that and we might have two ways to do that:
1. add term vectors generation logic for non-stored fields, generating term vectors for fields having just doc values  (more in general using `ValueFetcher` whatever the field type is, which would use stored fields or doc values depending on what is configured in the mapper as a `ValueFetcher`)
2. we might add generation of term vectors at indexing time and later on relying on fetching term vectors for the `_ignored` field rather then generating them "on-the-fly"

### Steps to Reproduce

Just run the test after [PR](https://github.com/elastic/elasticsearch/pull/101373) is merged.

**Comment by javanna** [comment]
> we might add generation of term vectors at indexing time and later on relying on fetching term vectors for the _ignored field rather then generating them "on-the-fly"

I don't think this is an option, as it would dramatically increase size on disk for the field.


> add term vectors generation logic for non-stored fields generating term vectors for fields having just doc values (more in general using ValueFetcher whatever the field type is, which would use stored fields or doc values depending on what is configured in the mapper as a ValueFetcher

Agreed. I want to point out that this issue is not only for `_ignored`, and I even wonder what the usecase is for retrieving term vectors for the `_ignored` field. Fields that are excluded from `_source` have the same issue, as well as fields that are indexed but not stored in the index nor in `_source.` I think that `TermVectorsService` is quite outdated, it does not support runtime fields and does not go through value fetchers to retrieve field values, and I wonder if it is worthwhile to expand its functionalities. I am not sure how widely used this API is, especially the on-the-fly generation of term vectors.

**Comment by salvatore-campagna** [comment]
I agree that option 1 is the way to go...e definitely option 2 would increase disk size.

**Comment by javanna** [comment]
I would close this as won't fix. We don't plan to improve the term vectors API further at the moment, and it only allows retrieval of stored fields currently.
