### ISSUE TITLE
TransportClient timeout Bug

### ISSUE THREAD

**Issue by polgl** [elastic/elasticsearch#10561]
Hi,

After an OOM in one of multiple client nodes (data=false, master=false),
the java client (Transport client) can not connect to the other nodes that are still running.

The java client does not see that the node is down and still sends requests.

**Comment by clintongormley** [comment]
Hi @polgl 

The problem is that a node that has OOM'ed still carries on running, so it is not actually down (unless you're saying that it as killed by the OOM killer?)

Essentially, there are only two things to do here:

* monitor for OOMs and kill a node that has one
* avoid OOMs (ie figure out why it occurred and avoid it in the future)
