### ISSUE TITLE
Publish desired balance after assigning new shards

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#105832]
Today we always run the desired balance computation until it converges or is superseded by a new cluster state. If we create some new shards, they start out unassigned, and will wait for the desired balance computation to complete before they can be assigned. This could be quite some time to wait. Should we instead notice that we assigned some unassigned shards during the computation and, if so, publish the intervening state for reconcililation to start while the computation continues?

**Comment by idegtiarenko** [comment]
David and I discussed this issue and decided to close it for now as such publishing desired balance quickly after assigning new shards could lead to a hotspot on a new empty node.

This issue was addressing the situation when desired balance computation could be slow (such as when computing initial assignment in unbalanced cluster) however such situations are rare.
