### ISSUE TITLE
Include pool and queue sizes in default cat thread_pool output

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#10600]
Currently, the cat thread_pool api returns the following thread pool metrics by default for the bulk, index and search pools:

```
.active
.queue
.rejected
```

It will be helpful to also return the .size and .queueSize values.

**Comment by clintongormley** [comment]
@ppf2 I'm not sure it makes sense to return those values by default, because they are config options which don't change.  The point of the cat API is to return the numbers which DO change and need monitoring.

Instead, I would propose a different feature: to support wildcards in header names, so you can do:

    GET _cat/thread_pool?v&h=bulk.*

What do you think=

**Comment by ppf2** [comment]
I like the idea of supporting wildcard :+1:

**Comment by clintongormley** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/issues/10811
