### ISSUE TITLE
Unbounded threadpools in Netty

### ISSUE THREAD

**Issue by dernasherbrezon** [elastic/elasticsearch#10616]
There are unbounded thread pools exist in NettyTransport (https://github.com/elastic/elasticsearch/blob/1032429d31efce215a8c9abfe4a41830d821da72/src/main/java/org/elasticsearch/transport/netty/NettyTransport.java#L312)

I would expect them configured the same way index/search/&etc threadpools. Could create pull request if needed

This is related to #5152

**Comment by clintongormley** [comment]
@spinscale what do you think?

**Comment by spinscale** [comment]
those unbounded thread pools should go away with netty 4, as you can configure the worker count in there. Even though we can change to the configuration parameters to look like regular thread pools, there is no possibility for  resizing IIRC, because it is configured on startup due to the `NioEventLoopGroup` class of netty (4).

**Comment by dakrone** [comment]
We are on Netty 4 now for 5.0 and this is no longer an issue as the transport does not create its own threadpools
