### ISSUE TITLE
marvel.agent.exporter: error connecting to [[0:0:0:0:0:0:0:0]:9200] [No route to host]

### ISSUE THREAD

**Issue by minfrin** [elastic/elasticsearch#10650]
On a default install of elasticsearch v1.4.4-1 from RPM, the elasticsearch.log reports that the marvel.agent.exporter complains as follows, and marvel doesn't work (queries to marvel return {}):

[2015-04-17 00:00:31,853][ERROR][marvel.agent.exporter    ] [Osiris] could not connect to any configured elasticsearch instances: [[0:0:0:0:0:0:0:0]:9200]
[2015-04-17 00:00:32,982][ERROR][marvel.agent.exporter    ] [Osiris] error connecting to [[0:0:0:0:0:0:0:0]:9200] [No route to host]

Setting network.bind_host to the external IP address is our case worked around the problem.

It appears that marvel is trying to using the bind address to bind to, instead of a valid IP address obtained through discovery. When the bind address is 0.0.0.0 the attempt fails.

**Comment by bleskes** [comment]
Marvel is shipping data over http to configurable list of targets (fallback on error). This is so to support the recommended setup where the monitoring data is sent to another cluster, to be available in case of trouble. By default, and for easy of first use, we ship data locally by pick up on the address of the local node. Since the traffic is going from the node to itself, we choose to pick on what ES calls the binding host and not the published IP (which what ES tells to other nodes to use when connecting to it). If not configured, ES will pick up the any local address, IPv4 or IPv6 depending on defaults. In your ES bound to `[0:0:0:0:0:0:0:0]:9200` but it doesn't route correctly. To work this, you can either configure marvel to use an explicit IP, or tell ES to bind ES to a specific ip via `network.bind_host` in your elasticsearch.yml file. There are also some special reserved "hosts", see http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html#modules-network . 

Let me know if this works for you.

**Comment by clintongormley** [comment]
Closing as Marvel 2 has been released
