### ISSUE TITLE
org.elasticsearch.xpack.esql.heap_attack.HeapAttackIT.testFetchTooManyMvLongs Lucen Snapshot Failure

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#106683]
### CI Link

N/A

### Repro line

 ./gradlew ':test:external-modules:test-esql-heap-attack:javaRestTest' --tests "org.elasticsearch.xpack.esql.heap_attack.HeapAttackIT.testFetchTooManyMvLongs" -Dtests.seed=F1F12175C991F463 -Dtests.locale=mt-MT -Dtests.timezone=Asia/Jerusalem -Druntime.java=22

### Does it reproduce?

Yes

### Applicable branches

lucene_snapshot

### Failure excerpt

This only fails on the Lucene Snapshot branch. It didn't fail with the same seed on main. Also, I tried pulling in the latest main to ensure we didn't miss a commit, and it still failed. 

Something funky with the new lucene snapshot and this test maybe?

```
org.elasticsearch.xpack.esql.heap_attack.HeapAttackIT > testFetchTooManyMvLongs FAILED
    java.lang.AssertionError:
    Expected: <0>
         but: was <1>
        at __randomizedtesting.SeedInfo.seed([F1F12175C991F463:BA3FFB02B463516E]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at org.elasticsearch.test.ESTestCase.assertThat(ESTestCase.java:2147)
        at org.elasticsearch.xpack.esql.heap_attack.HeapAttackIT.assertWriteResponse(HeapAttackIT.java:558)
        at org.elasticsearch.xpack.esql.heap_attack.HeapAttackIT.initIndex(HeapAttackIT.java:546)
        at org.elasticsearch.xpack.esql.heap_attack.HeapAttackIT.initMvLongsIndex(HeapAttackIT.java:517)
        at org.elasticsearch.xpack.esql.heap_attack.HeapAttackIT.testFetchTooManyMvLongs(HeapAttackIT.java:406)
```

**Comment by nik9000** [comment]
@dnhatn may be interested in this one.

**Comment by benwtrent** [comment]
Ah yeah, i should have adjusted the test label to `low-risk`. 

Looking at `CHANGES.txt` for Lucene 9.11, nothing immediately stands out to me as a big enough optimization to keep this from tripping.

**Comment by dnhatn** [comment]
@benwtrent This test has a large number of documents to trigger the impact of a new concurrent merges that you recently introduced in Lucene in https://github.com/apache/lucene/pull/13190 (cool changes!).

The issue lies in the PerFieldDocValuesFormat and PerFieldPostingsFormat, which mutate and reset the fieldInfos of the mergeState while executing its merge. Consequently, other ongoing merges may fail to see some fieldInfos.

https://github.com/apache/lucene/blob/e2788336d49c56050b3cea5944008bcffe35dcb1/lucene/core/src/java/org/apache/lucene/codecs/perfield/PerFieldDocValuesFormat.java#L150-L158

https://github.com/apache/lucene/blob/04f335ad79cae019d1a552e41e0029d061d8e3d9/lucene/core/src/java/org/apache/lucene/codecs/perfield/PerFieldPostingsFormat.java#L196-L214

Previously, this wasn't an issue because merge sub-tasks executed sequentially. We need to address these two usages. I will work on the fix, but if you prefer, feel free to proceed.

**Comment by dnhatn** [comment]
I've opened https://github.com/apache/lucene/pull/13208/ in Lucene, which should fix this issue.
