### ISSUE TITLE
Start failed on Windows 10: no tools.jar in bundled jdk

### ISSUE THREAD

**Issue by liuweibing7** [elastic/elasticsearch#106854]
### Elasticsearch Version

8.13.0

### Java Version

_bundled_

### OS Version

Windows 10

### Problem Description

![image](https://github.com/elastic/elasticsearch/assets/96558678/24230e9d-1f1c-4ff0-83ca-a100fec282e8)

I have my own jdk and JAVA_HOME before, when I first start elasticsearch, it failed, so I delete my own JAVA_HOME, the ES_JAVA_HOME must be used. But, when I restarted, it still failed, cause there is no tools.jar in the  jdk/lib directory. Should I add a tools.jar to the jdk/lib directory, or this is a bug ?

### Steps to Reproduce

1. download elasticsearch elasticsearch-8.13.0-windows-x86_64.zip
2. unzip to elasticsearch-8.13.0
3. cd to elasticsearch-8.13.0/bin and click the boot file elasticsearch.bat
4. boot failed and the cmd exited

**Comment by rjernst** [comment]
Thanks very much for your interest in Elasticsearch.

The exception is truncated (you need to look at the entire log file referenced). It's not clear what might be trying to look at tools.jar. However, tools.jar has been gone from Java for many years. Elasticsearch does not rely on it. Therefore this issue is likely environmental.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this issue.
