### ISSUE TITLE
ES|QL LOCATE function

### ISSUE THREAD

**Issue by tteofili** [elastic/elasticsearch#106818]
Java calls this `indexOf`

**Comment by nik9000** [comment]
PostgreSQL seems to call this function `POSITION`. MS SQL Server seems to call it `CHAR_INDEX`. I love standards.

**Comment by tteofili** [comment]
note that there's a slight difference between PostgreSQL's `POSITION` (it finds the first occurrence of a _substring_ in the target `String`) vs MS SQL_SERVER's `CHAR_INDEX` (it finds the first occurrence of a _character_ in the target `String`).

I'm not entirely sure which one we're looking to have.

**Comment by nik9000** [comment]
I want substring. Though I think `CHARINDEX` (sorry, no `_`. standards) does find the substring too: https://learn.microsoft.com/en-us/sql/t-sql/functions/charindex-transact-sql?view=sql-server-ver16#a-returning-the-starting-position-of-an-expression

My *wild* guess is that they called it `CHARINDEX` because they use the word `INDEX` for something else important. Maybe just the concept of indexes. I dunno. I reference MSSQL's docs because they are usually very good.

Oh no! Oracle calls it INSTR: https://docs.oracle.com/cd/B13789_01/server.101/b10759/functions058.htm . Or INSTR2 or INSTRC. But that proliferation is because of character sets. We don't have those - we are utf-8 only.

I can't find the docs for it in splunk. This is fun! It's like a scavenger hunt.

We can make aliases if we want. I forget exactly how, but it's not super hard. But for now I'd just call it `LOCATE` because it's the first name you mentioned. We don't have namespaces on these functions so I don't want to use up all the good names.

**Comment by tteofili** [comment]
thanks a lot @nik9000 , I'll go with substring 👍

**Comment by tteofili** [comment]
one concern regarding the function semantics, it seems that all MS's `CHARINDEX`, PostgreSQL's `POSITION`, Oracle's `INSTR` return `0` when the substring is not found; of course this is different than java's `indexOf` which returns `-1` in that case.
clearly in the programming context, positions are 0-based whereas positions start from 1 in the DB context.

**Comment by nik9000** [comment]
I think we use 1-based positions for strings. Which is upsetting to me, but I think we did it to line up with all the other DBs. I think. So long as we line up with `SUBSTRING` we're doing the right thing.

We shouldn't deviate from what the DBs do, but I wonder why `POSITION` on unmatched data doesn't produce `null`. The `null` would propagate when you combine `SUBSTRING` and `POSITION` in ways that I think folks want.
