### ISSUE TITLE
Doc improvement for "xpack.security.enabled"

### ISSUE THREAD

**Issue by zachsa** [elastic/elasticsearch#107040]
### Description

The documentation for `xpack.security.enabled` is unclear - to me that meant username / password, but didn't necessarily mean TLS.

I spent quite a lot of time trying to figure out why my instances in a docker swarm environment were still serving http at port 9200 transport and http ssl enabled, as I wanted an environment with no username/password, but with transport and connections still via HTTPS / TLS. The logs explicitly mention switching ssl contexts and reference my generated certs - no real indication as to why port 9200 was serving http instead of https. 

I can see that xpack.security.enabled has to be true otherwise TLS is not possible.

**Comment by jaswanth-2273** [comment]
How can I disable xpack.security.enabled in a Kubernetes environment? I am unable to run Elasticsearch version 8.13.x or 8.14.x in Kubernetes without credentials.

Is this supported? If yes, could you provide information on how to achieve this?

**Comment by leemthompo** [comment]
@jaswanth-2273 you might try the [Elastic Discuss forum](https://discuss.elastic.co) for a detailed Kubernets specific answer to your question. In brief, you'll need to update the Elasticsearch configuration to set `xpack.security.enabled: false`. However, remember you should _never_ disable security features for production environments.

**Comment by zachsa** [comment]
@leemthompo - no they are not. My intention was to incrementally improve the deployment one aspect at a time. These docs would not have decreased my frustration as they still don't say that TLS is required when using security.enabled.

> Never run an Elasticsearch cluster without security enabled. This principle cannot be overstated. Running Elasticsearch without security leaves your cluster exposed to anyone who can send network traffic to Elasticsearch, permitting these individuals to download, modify, or delete any data in your cluster. [Start the Elastic Stack with security enabled](https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-stack-security.html) or [manually configure security](https://www.elastic.co/guide/en/elasticsearch/reference/current/manually-configure-security.html) to prevent unauthorized access to your clusters and ensure that internode communication is secure.

I would say that actually comes across as patronizing

**Comment by jaswanth-2273** [comment]
@leemthompo  
I want to update the flag to false (i.e., xpack.security.enabled: false). How do I override this through Helm? I have tried updating the values in the ConfigMap and even in the environment values, but it does not work.

**Comment by leemthompo** [comment]
@zachsa thanks for response and understand frustrations, because lot of things come under the umbrella of `xpack.security` that aren't immediately obvious in the doc. Per your feedback, I'm going to update that doc to clarify that it must be enabled so you can use any Elasticsearch authentication, authorization and audit features.

**Comment by leemthompo** [comment]
@jaswanth-2273 again I'd encourage you to ask on Discuss because this is not the best forum for your question. One final link I can provide which might be helpful is the [Elastic Cloud Kubernetes documentation](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-installing-eck.html) because installation via Helm charts is obsolete. :)

**Comment by zachsa** [comment]
@jaswanth-2273 - thinking about why I found those docs offputting.. I would prefer it if the docs really just described how Elasticsearch works

**Comment by leemthompo** [comment]
@zachsa I've gotten feedback from more knowledgable teammates.
 
Per your original question to have TLS without authn/authz, you could enable security (and TLS) and then configure [anonymous access](https://www.elastic.co/guide/en/elasticsearch/reference/current/anonymous-access.html) with a `superuser` role.

Otherwise, the docs feedback is well received, thanks.
