### ISSUE TITLE
overshoot watermarks during relocation in multi-disk scenario

### ISSUE THREAD

**Issue by conicl** [elastic/elasticsearch#107488]
### Elasticsearch Version

latest

### Installed Plugins

none

### Java Version

_bundled_

### OS Version

Darwin Kernel Version 23.1.0

### Problem Description

During the shard allocation, the `DiskThresholdDecider` takes into account the size of shards being relocating when calculating the disk occupancy of a specific disk on a node. This work is done by collecting statistics of each shard, including store size and shard paths, through the `ClusterInfoService` on metadata changed.

However, the collection process is performed through the `TransportIndicesStatsAction`, which by default does not include shards relocating. As a result, the paths of all shards relocation we get from  `ClusterInfo` are empty. According to the current calculation logic, if the path is empty, it will be directly added to the occupancy of the target disk. 
```
            // if we don't yet know the actual path of the incoming shard then conservatively assume it's going to the path with the least
            // free space
            if (actualPath == null || actualPath.equals(dataPath)) {
                totalSize += getExpectedShardSize(routing, 0L, clusterInfo, null, metadata, routingTable);
            }
```

In scenarios where multiple disks are configured on a single node, this leads to the usage of multiple disks being counted on a single disk. When the disk reaches a high watermark, shards cannot be recovered.

### Steps to Reproduce

1. Create a node with 3 data disks .
2. Write some data to ensure that the usage of each disk is above 50%.
3. Add an additional node which has same disk configuration, and exclude all data from being allocated to the initially started node by setting `cluster.routing.allocation.exclude`.
4. During the relocation process, when creating an index, will observe that shards cannot be allocated due to the high disk watermark.

**Comment by DaveCTurner** [comment]
I think this is the behaviour I'd expect, although it should resolve in time since eventually there will be no relocating shards and thus the disk usage calculation will be correct.

The use of [multiple data paths was deprecated almost 3 years ago](https://www.elastic.co/guide/en/elasticsearch/reference/current/important-settings.html#_multiple_data_paths). We don't think it's the right way to run Elasticsearch, and although it is not yet forbidden I'm sorry to say that we're also not going to invest our limited time in fixing issues to which it relates. If you find any issues like this when running with the recommended configuration of a single data path then please open a separate issue about them, but for now I'm going to close this.
