### ISSUE TITLE
Deprecation of facets

### ISSUE THREAD

**Issue by SaSa1983** [elastic/elasticsearch#10769]
According to your documentation facets are deprecated and users are encouraged to switch to aggregations.

But aggregations only deliver approx. counts (in contrast to facets, which's counts are exact)

I'd suggest to keep "facets" but still encourage users to switch to aggreagations and only suggest use of facets where exact count are relevant

**Comment by jpountz** [comment]
> But aggregations only deliver approx. counts (in contrast to facets, which's counts are exact)

Are you talking about the `terms` facet/aggregation? In that case they work essentially the same way. The aggregation is actually even better since it has better heuristics to request more terms at the shard level which tends to improve accuracy. Also aggregations report on an error bound since 1.4.

I'm wondering that the confusion might come from the fact that this limitation is documented for aggs for not faceets?

**Comment by clintongormley** [comment]
Yep, this looks like a misunderstanding to me.  Feel free to reopen if this is not the case.
