### ISSUE TITLE
Store large integers list per document and match (intersection) with input integers list.

### ISSUE THREAD

**Issue by prshant70** [elastic/elasticsearch#107746]
### Description

A few days back, I was seeking an efficient method to store nearly 50,000 location IDs (6-digit) per document in ElasticSearch and enable querying of these documents based on matching indexed locations with provided input location IDs. The document should appear in the result set if its stored location IDs include any of the input locations. As I couldn’t find a suitable out of the box solution for this, I wrote a custom ElasticSearch plugin that usages RoaringBitmap implementation to solve this problem. The plugin code is available here - https://github.com/tata1mg/fastmatch-elasticsearch-plugin

In my preliminary testing of the plugin, it demonstrated strong performance in query speed and storage efficiency. The plugin efficiently handles the storage and matching of large integer lists and is versatile for various applications; I'm using it for checking product availability. I think others with similar needs could benefit from this plugin. Could you please advise me on how to make the plugin code part of the ElasticSearch codebase and make it accessible through ElasticSearch artifacts?

**Comment by prshant70** [comment]
Hello

Reminder!

Any help here would be really appriciated.

**Comment by rjernst** [comment]
Thanks for your interest in Elasticsearch!

It's great to hear you are interested in making your plugin available for others to use. Although we do welcome contributions to Elasticsearch itself, accepting new plugins has an ongoing maintenance cost, so we do not normally take them in. However, you can make your plugin available via maven, and then garner feedback on https://discuss.elastic.co from fellow Elasticsearch users. I recommend you take a look at the docs for [writing a plugin](https://www.elastic.co/guide/en/elasticsearch/plugins/current/creating-classic-plugins.html).

 Since the plugin would not exist within the Elasticsearch codebase, I hope you don't mind I close this issue.
