### ISSUE TITLE
Log template management requests at INFO level

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#10795]
It will be helpful to move template management task entries (create, delete, update, etc..) from DEBUG to INFO level:

```
[2015-04-24 12:21:19,747][DEBUG][cluster.service          ] [Stiletto] processing [create-index-template [ls_template2], cause [api]]: execute
[2015-04-24 12:21:19,748][DEBUG][cluster.service          ] [Stiletto] cluster state updated, version [12], source [create-index-template [ls_template2], cause [api]]
```

**Comment by clintongormley** [comment]
Or possibly provide a different context for logging, eg `cluster.service.template`?

**Comment by ppf2** [comment]
Sounds like a good idea to create a new context and write some useful INFO level messages to this new logger. thx

**Comment by javanna** [comment]
We discussed this during fixit-friday, we shouldn't go and change the log level for those existing lines, because they get logged for every single cluster state updates, which would make logs way too big at INFO level. But we can add additional log lines specifically to the create/remove index template code though if needed e.g. `MetaDataIndexTemplateService` similar to what `MetaDataCreateIndexService` does when an index gets created. We should do that for both `removeTemplates` & `putTemplate` methods. I think this is reasonable and wouldn't cause problems at INFO level, assuming that index templates don't get changed all the time.

**Comment by jasontedor** [comment]
I opened #29027.
