### ISSUE TITLE
What is the significance of the assertion for `line.size` in `/sys/fs/cgroup/cpu/../cpu.stat`?

### ISSUE THREAD

**Issue by mingshisaveme** [elastic/elasticsearch#107983]
Why do we need to assert `line.size`? Can this line of code be safely removed? On some systems, the value of `line.size` is 6, and enabling the JVM `-ea` parameter during testing leads to startup failures.
https://github.com/elastic/elasticsearch/blob/585fae304213c79f8978d4654444a8ba9e184e14/server/src/main/java/org/elasticsearch/monitor/os/OsProbe.java#L481

For example: 

```
cat user-59756.slice/cpu.stat
```

```
nr_periods 0
nr_throttled 0
throttled_time 0
wait_sum 78240156074   // The extra entry "wait_sum"
nr_bursts 0
burst_time 0
```

**Comment by DaveCTurner** [comment]
It's there just as a simple check that we're running in an environment that looks at least a little bit like the ones on which we test. Folks do try and run these things on weird unsupported Linux-like OSs sometimes and if the format of this data is too different from what we expect then other things will go wrong.

However in this case you're right, the regular Linux kernel can, in some configurations, yield an extra `wait_sum` line here:

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/kernel/sched/core.c?id=57865f397001f592817eea513251705d45d000af#n11113

I think we shouldn't simply remove this assertion. Instead I'd rather we strengthened it to say that the file format is roughly what we expect here, but to tolerate extra values added in future kernel versions since this seems not to be considered a breaking change to the kernel.

**Comment by mingshisaveme** [comment]
Thank you very much for your explanation.  can we simply modify it to:

```
assert lines != null && (lines.size() == 3 || lines.size() == 5 || lines.size() == 6);
```

and then submit a PR like it.
