### ISSUE TITLE
Term matching on empty string behaves differently when case_insensitive==true

### ISSUE THREAD

**Issue by demjened** [elastic/elasticsearch#108968]
### Elasticsearch Version

8.15.0

### Java Version

_bundled_

### OS Version

Elastic Cloud

### Problem Description

Context in [Discuss forum post](https://discuss.elastic.co/t/term-query-with-empty-string-and-case-insensitive-setting-become-invalid/359961). 

The `term` query on a keyword field with an empty value ("") behaves differently depending on the `case_insensitive` flag:
- If `case_insensitive==false` (default), the query matches on "",
- If `case_insensitive==true`, the query does not match on "".

We should make this consistent.

### Steps to Reproduce

Tested on an Elastic Cloud deployment with version 8.15.0-SNAPSHOT.

```
PUT term-match-test
{
  "mappings": {
    "properties": {
      "text": {
        "type": "keyword"
      }
    }
  }
}
```

```
PUT term-match-test/_doc/1
{
  "text": ""
}
```

Case sensitive search returns 1 hit:
```
POST term-match-test/_search
{
  "query": {
    "term": {
      "text": {
        "value": ""
      }
    }
  }
}
```

Case insensitive search returns 0 hits:
```
POST term-match-test/_search
{
  "query": {
    "term": {
      "text": {
        "value": "",
        "case_insensitive": true
      }
    }
  }
}
```

**Comment by benwtrent** [comment]
This is because to search case insensitively, we build a regex automaton over the codepoints, making them case insensitive chars. 

Since the number of codepoints here is `0`, we build a completely empty automaton and thus match nothing. 

I am not 100% sure the best way forward on this. Two thoughts are:

 - Correct how we create the automaton to handle the case when the string is empty
 - Have a special case for the insensitive query that first checks for the term to be an empty string and just return a regular terms query (seems safer).
