### ISSUE TITLE
Remove `GeoShapeFieldMapper`

### ISSUE THREAD

**Issue by lkts** [elastic/elasticsearch#108979]
### Description

`GeoShapeFieldMapper` is not used and superseeded by `GeoShapeWithDocValuesFieldMapper`. 

One issue with removing it is usage in https://github.com/elastic/elasticsearch/blob/4878509bb06a61dafa8306c378ccbb66656e67e7/x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/mapper/GeoShapeWithDocValuesFieldMapper.java#L107 which is a potential breaking change.

**Comment by martijnvg** [comment]
This class is no longer used, previously this class was used when using the open source distribution, but that no longer exists. The `GeoShapeWithDocValuesFieldMapper` class is used now. 

This class be removed, but we have to double check what happens when someone has the `org.elasticsearch.index.mapper.GeoShapeFieldMapper` configured in their log4j config. If that causes issues, then we should register this logger using `DeprecationLogger.getLogger(String)` method for the rare cases someone has this setup.
