### ISSUE TITLE
Replica shard corrupted

### ISSUE THREAD

**Issue by niv0** [elastic/elasticsearch#10903]
We have an cluster with two data nodes and one non-data nodes. Our index 'location' has 5 shards and 1 replica. 

When we try to get a document

```json
GET location/mapping/31307093
```

Once we get an answer with a document
```json
{
   "_index": "location.b",
   "_type": "mapping",
   "_id": "31307093",
   "_version": 1,
   "found": true,
   "_source": {
      "MAPPINGTYP": "A",
      "LOKATIONSID_NEU": "31330483",
      "LETZTEAENDERUNG": "2015-04-28-02.05.25.547042"
   }
}
```

But next query gives us
```json
{
   "_index": "location.b",
   "_type": "mapping",
   "_id": "31307093",
   "found": false
}
```

It seems that replica shard is corrupted?  Is there any way to check if any other document is corrupted? I guess shutting down one node, deleting the files and starting it again would help, but this doesn't solve the real problem. Would the upgrade to elasticsearch 1.5.x bring any improvement in that area?

We use elasticsearch 1.4.4 with jdk1.8.0_40 running on Red Hat Enterprise Linux Server release 6.6 running on VMware vSphere.

Kind regs
Vladimir Nisevic

**Comment by clintongormley** [comment]
Hi @niv0 

Yes it looks like the replica is out of sync with the primary.  You can confirm which copy of the shard holds the document by adding `?preference=_primary` to the GET request.

Assuming it is the replica, then you can get your replicas back in sync by setting the number of replicas to zero, then back to 1:

    POST location.b/_settings 
    { "number_of_replicas": 0 }

I agree that this doesn't solve the original problem.  You may have experienced a bug that has already been fixed in 1.5, but could possibly be something else.  Do you use the delete-by-query or bulk APIs?  Are you aware of any issues you had with nodes falling over?

**Comment by javadevmtl** [comment]
Curious can their not be a way to check if primaries and shards match in size after a merge or after documents have been committed to the replica or something?

**Comment by clintongormley** [comment]
@javadevmtl Presumably indexing is underway, and refreshes happen at different times on the primary and replica, so no, there isn't really a way to do this without pausing indexing.

**Comment by niv0** [comment]
Hi @clintongormley, thank you for your support.

We do not really use here either delete-by-query nor bulk APIs'. We had no fail over node issues in that time period.

We will try with upgrade to ES 1.5.x and see if issue still occurs.

Would close this issue at this point of time.
