### ISSUE TITLE
async ESQL and _search: add search_id, is_running and is_complete to response headers

### ISSUE THREAD

**Issue by ppisljar** [elastic/elasticsearch#109576]
### Description

In order to be able to use cbor response format in kibana and avoid decoding the body on kibana server, we would need search_id, is_running and is_complete to be returned as part of response headers (on top of returning them in body as today)

**Comment by nik9000** [comment]
@ppisljar and I discussed and alternative, which is always sending `wait_for_completion=0` and then using *that* to get the id. That felt less good to me because it throws out the wait-for-completion behavior. And I'm not entirely sure that it'd work - I think we can sometimes return with the results immediately from `wait_for_completion=0`. It just feels better to do the headers.

**Comment by nik9000** [comment]
I've tagged this as `search/search` and `esql` because we probably want to do this in both places.

**Comment by nik9000** [comment]
*Technically* I think all you need is `is_completed`. If it's false you can parse and get the search id. If it's true you can stream. But if we're going to add the rest I think.

**Comment by nik9000** [comment]
All I see in the responses is ```
            builder.field("id", id);
            builder.field("is_running", isRunning);
            builder.field("is_partial", isPartial);
```

Is there an `is_completed` you have that you can reference? Or are you looking for `is_running`?

**Comment by thomasneirynck** [comment]
Adding some more context here around the relevance of this issue for Kibana.

Kibana-server introduces overhead when querying Elasticsearch. This is due to how the implementation in the `data`-plugin. This plugin is used by many applications (notably Discover, Lens, Maps, ...) to fetch data from Elasticsearch. The overhead falls in two buckets.
1) a batching layer (`bsearch`) that collates requests from the browser into a single one i(https://github.com/elastic/kibana/issues/166206). This was introduced as a work-around for the http1-connection limit in browsers. It collates the ES-responses into a single response (see (2)). Apart from having to collate the responses, the custom batching also introduces more latency.
2) unnecessary encoding/decoding and custom compression. ES-requests are decoded and re-encoded on kibana-server before sending it to kibana-browser.

------

(1) can be addressed by moving to http2. This would mainly be an architecture improvement, with some marginal performance benefits.
(2) when (1) is completed, any unneccessary decoding/encoding can be removed as well. This will result in faster delivery of data to kibana-browser and reduce the memory footprint in kibana-server.

(2) is blocked by this issue here (https://github.com/elastic/elasticsearch/issues/109576). There are a few use-cases in polling for async-responses where some of metadata is needed from theES-response body. Can this be moved to a header (exact properties TBD).

---------------------

Running kibana by default in http2 and removing `bsearch` (1) is an incompatible change as it removes the `bsearch` component and may potentially degrade on-prem users running http1. To motivate this move, and the additional admin-requirements of using SSL, we would also like to introduce the performance benefit of (2) at the same time.

---------

wrt cbor and streaming. Removing any decoding requirements from kibana-server, will allow longer-term improvements like using a more efficient data-format (cbor), or even faster delivery (stream results). However, these are longer-term improvements and not the most critical from a short-term perspective.

**Comment by swallez** [comment]
Regarding "use cbor response format in kibana": starting with 8.15, [ES|QL results can be output as Apache Arrow dataframes](https://www.elastic.co/guide/en/elasticsearch/reference/current/esql-rest.html#esql-rest-format) which are generally of the same size or smaller than cbor encoding and can be used with no decoding/deserialization.

This was added in https://github.com/elastic/elasticsearch/pull/109873

**Comment by ivancea** [comment]
Just merged the last PR adding headers.
Now both the `/_query` and `/_async_search[/status]` also have these headers in the response:
- `X-Elasticsearch-Async-Is-Running`: Either `?0` or `?1`, depending on if the query is still running or not
- `X-Elasticsearch-Async-Id`: The ID of the query. If the query was instantly ran and the other header is `?1`, this header may be absent

**Comment by thomasneirynck** [comment]
thx @swallez - wrt https://github.com/elastic/elasticsearch/issues/109576#issuecomment-2298226469

We have done some investigation in arrow and we noticed that the client-side support in Javascript is quite poor right now, and any gains in filesize, Kibana loses in parsing/reading of the format (https://github.com/elastic/kibana/pull/183909).

So there is no immediate plans to use arrow as transfer format for Kibana.

**Comment by swallez** [comment]
Thanks for the feedback @thomasneirynck. I'll look at that PR to understand if/how we can avoid any form of parsing, which is an essential part of the benefits of Arrow beyond network payload size.

**Comment by thomasneirynck** [comment]
I should clarify we mainly looked at it from a dashboard/charting perspective.

> if/how we can avoid any form of parsing

Much has to do with how Lens and elastic/charts require their data to be laid out a specific way before data is drawn as a chart. Different models (e.g. loading arrow-buffers straight on GPU) could avoid all this, but there are not actionable in the short term.

**Comment by swallez** [comment]
I did some investigation an posted the results here https://github.com/elastic/kibana/issues/175695#issuecomment-2382859377
