### ISSUE TITLE
copy_to does not work with multi fields

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#10996]
This previously worked, but was broken with document parser refactoring in #10802. We could fix this in a simple way, by handling multi fields in the doc parsing as well (so the multi field can be checked for a copyTo). 

However, the mapper attachment plugin currently relies on the ability to generate the values for multifields separately (not just copying the original value). My current thought is the mapper attachment should basically attach these values to the parser context, so that when multi fields are handled in the doc parser, it finds the value there for whatever subfields are present.

**Comment by konradkonrad** [comment]
Is this related to #8483 or would your proposal tackle that specific problem, too?

**Comment by rjernst** [comment]
@konradkonrad I do not think this is related. This bug was introduced in a very recent refactoring, only on master, and only happens when copy_to is used *within* a multi field (which it doesn't look like that user does).

**Comment by clintongormley** [comment]
@rjernst I'm not sure that it ever makes sense to use `copy_to` in a multi-field sub-field?  It can be used on the main field only, to the same effect.  There is similar confusion with using `include_in_all` on sub-fields.  Users think that the tokens from the sub-fields end up being added to `_all`, when really it is just the string value of the main field which is passed to `_all`.

**Comment by rjernst** [comment]
@clintongormley Great! Then I will find a way to restrict multi fields to `copy_to` cannot be specified. I've created #11053 to track that.

**Comment by ppanero** [comment]
Hello @rjernst  @clintongormley @konradkonrad 

First of all please spare my life for commenting on an anciently dead issue. I have an issue with this and suggesters. Due to the nature of a federated datamodel, the are three fields:

``_data`` where the searchable data goes
``_suggest`` where the desired data for "search-as-you-type" is copied to
``_didyoumean`` where the desired data for "did-you-mean" is copied to

The second one uses an ``edge n-gram`` and the last one a ``phrase`` analyzers (pretty much standard configuration in both analyzers). Now lets go to the case:

1- Let's say I have a field "title" inside ``_data``, and it is as follows:

```
"_data": {
          "type": "object",
          "properties": {
              "title": {
                  "type": "text",
                  "analyzer": "english",
                  "fields": {
                       "exact_match": {
                       "type": "keyword",
                       "copy_to": [
                            "suggest",
                            "didyoumean"
                       ]
                 }
               }
            }
          }
        },
```

Obviously it doesn't work since ``copy_to`` is in the inner keyword field.

2- I try to get the suggested value for the ``phrase`` one, but it will only return **1** word suggestions (even with **max_errors** set to >1) because the ``text`` terms are copied one by one splitted by space (as ``text`` does by default).
3- Sadly its not an option to refactor and put ``exact_match`` as outer field and text as inner because that ends up in plenty of undesired issues with full-text search.

Is there any solution that you expert eyes see?

Thank a million, and again sorry for bringing a zombie from the dead.

Cheers!
