### ISSUE TITLE
[ES|QL][Named parameters] Not sending the params in a query with named parameters results in blocking all future _query requests

### ISSUE THREAD

**Issue by stratoula** [elastic/elasticsearch#110028]
### Elasticsearch Version

8.15

### Java Version

_bundled_

### OS Version

Darwin Kernel Version 22.6.0

### Problem Description

Using named parameters in the query and not sending the params results in breaking my _query api.

### Steps to Reproduce

Run this without sending the params:

```
POST /_query/async?drop_null_columns
{
  "query": "ROW x = ?name1, y = ?name1"
}
```
It will fail, which is expected!

Then run this:

```
POST /_query/async?drop_null_columns
{
  "query": "ROW x =1"
}
```

It fails and now all my _query requests are blocked, all error out,  I have to restart my cluster.

**Comment by ChrisHegarty** [comment]
This is not specific to async.

The issue is with the sharing of the stateful static `QueryParams.EMPTY` in `EsqlQueryRequest`. It means that parser errors from request1 are seen by request2, and all subsequent requests.

Initialising an instance field to the static `QueryParams.EMPTY` is an anti-pattern for stateful objects.
