### ISSUE TITLE
Remove libsigar

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#11034]
Supposedly ES works if its not available, hence, its unnecessary.

Having uunecessary JNI dependencies is too much.

**Comment by s1monw** [comment]
+1 in general

**Comment by dakrone** [comment]
+1

**Comment by kimchy** [comment]
the fact that it works without mainly comes for the cases where there isn't an OS sigar supports, or its running embedded and someone doesn't wish to distribute sigar.

My main concern with sigar is that the project has stagnated. There hasn't been a new release since 1.6.4 which happened a few years ago... .

It has been very handy to use. Single API call to get the status on 100 node cluster. Many monitoring tools (bigdesk, ElasticHQ, ...) for ES rely on it (since its part of the API), and the ones I have found handy are basic ones, just with an opportunity to see the state across the cluster easily. I've mainly used cpu (os and process), swap usage, and in extreme cases network and fs statistics.

**Comment by lukas-vlcek** [comment]
Do I understand this correctly that you are considering dropping REST APIs (cluster, admin...) that expose info based on Sigar lib? This would be unfortunate IMO. Not because I am Bigdesk maintainer but because getting this info directly from ES is extremely valuable feature. It is one of the reasons why we are using ES in our team.

**Comment by s1monw** [comment]
> Do I understand this correctly that you are considering dropping REST APIs (cluster, admin...) that expose info based on Sigar lib? This would be unfortunate IMO. Not because I am Bigdesk maintainer but because getting this info directly from ES is extremely valuable feature. It is one of the reasons why we are using ES in our team.

this is about removing the native library not the stats it's providing. We can in the meanwhile get several of them from other sources. We might not be able to provide a 1 to 1 replacement but a native lib that is basically unmaintained for more than half a decade is not really an option.

**Comment by tlrx** [comment]
I'm closing this one: sigar has been removed in #12010 and the REST APIs have been updated to expose stats & information that can be collected through JMX management beans (see #12043, #12049, #12053). Network Stats has been removed because there's no simple replacement (see #12054).
