### ISSUE TITLE
Confirm: possible to model openinghours using Geo Polygon Filter?

### ISSUE THREAD

**Issue by gebrits** [elastic/elasticsearch#11054]
Some years ago I had a conversation on the Solr userlist to use Solr geo-functionality for modelling POI openinghours. This got some nice debate going with endresult being: it's possible with some hacking. A couple of years later (2013) it was possible out of the box with [solr](http://lucene.472066.n3.nabble.com/Modeling-openinghours-using-multipoints-td4025336.html) 

Partially based on that Chris Hostetter (a.k.a. Hossman) did the following [presentation](https://people.apache.org/~hossman/spatial-for-non-spatial-meetup-20130117/) in 2013, which nicely outlines several usecases (all sharing a temporal component) using geo-polygon intersections, etc.  

Question: 
1. are all these geo polygon intersection/overlap related queries possible with Elasticsearch as well? Geo Polygon Filter seems the way go to, but like to know the support for the above. 
2. Is there a way to define x/y instead of lat/long for ease-of-use? I.e.: getting the geo part out of geo-spatial?

**Comment by imotov** [comment]
@gebrits I think this would be a great topic for a conversation on [elasticsearch user list](https://groups.google.com/forum/?fromgroups#%21forum/elasticsearch) or our new [discussion forums](http://discuss.elastic.co) since we are using github issues to keep track of bugs and feature requests. I just want to mention that while using geo polygons for filtering working hours is undeniably awesome, you might want to also consider simpler solutions such as using [nested documents](http://stackoverflow.com/a/7118625/783043).
