### ISSUE TITLE
Validate snapshot via dry-run restore

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#11083]
I know we do verification during the snapshot process (#7159), but if a snapshot is kept in a repo for an extended period (eg months/years) then it'd be nice to know we could periodically verify there has been no FS/other corruption that may cause restoration problems.

Therefore it'd be awesome if we had a dry-run/verification restore flag that verified the snapshots but obviously doesn't restore anything.

**Comment by clintongormley** [comment]
@imotov what do you think about this?

**Comment by imotov** [comment]
I really like the idea. I think it will nicely complement #9183. I wouldn't make it a restore option though because this will imply that we verify that snapshot has compatible settings, metadata, etc., which is much more difficult to test in dry run. Instead, I would make it a separate snapshot-level `verify` command and maybe add an option to repository-level `verify` command to check checksum for all files in the repository.

**Comment by mellieA** [comment]
Did this functionality ever make it to any release? I have another request for this enhancement.

**Comment by imotov** [comment]
@mellieA no, it wasn't implemented yet.

**Comment by mellieA** [comment]
I've been thinking about this, could we also print a list of associated files (verbose option) that restoring the snapshot is dependent on?

**Comment by ywelsch** [comment]
I talked with @tlrx about this: We think that this feature is targeting an archiving solution, and less useful for how snapshot/restore is used right now. We have no immediate plans to work on this, which is why I'm closing this issue.
@mellieA can you elaborate on the use cases where you would like to have list of associated files?

**Comment by maxkalashnikov** [comment]
Although the initial description was for archiving, this is not at all limited to that. The assumption that, just because a snapshot was written successfully, means it can be read back successfully (even immediately) is deeply flawed, especially in the face of network filesystems.

Then imagine what happens if that filesystem get replicated somewhere for, e.g., business continuity purposes. Did the replication completely sync all the files needed by any given snapshot? 

It may be possible to use a semaphor file to determine  if such a sync were wholly successful, but the use case for this feature is determining which snapshot(s) can still be used in the absence of such success.
