### ISSUE TITLE
[CI Failure] org.elasticsearch.common.jna.NativesTests.testMlockall

### ISSUE THREAD

**Issue by gmarz** [elastic/elasticsearch#11096]
Fails on *nix because the actual mlockall call fails:

```
[2015-05-11 17:35:41,417][INFO ][test                     ] Test testTryMlockall(org.elasticsearch.common.jna.NativesTests) started
[2015-05-11 17:35:41,450][WARN ][common.jna               ] Unable to lock JVM memory (ENOMEM). This can result in part of the JVM being swapped out. Increase RLIMIT_MEMLOCK (ulimit).
[2015-05-11 17:35:41,453][ERROR][test                     ] FAILURE  : testTryMlockall(org.elasticsearch.common.jna.NativesTests)
```

http://build-us-00.elastic.co/job/es_core_master_regression/2093/testReport/junit/org.elasticsearch.common.jna/NativesTests/testMlockall/

I modified the test to only assertTrue for Windows for now, but we should be able to test this on *nix as well.

**Comment by rmuir** [comment]
Should we really assert this? Before adding the windows impl, we only checked that it was FALSE on unsupported platforms. Otherwise all build infrastructure and developers machines would need to be configured correctly, so that mlockall works.

if we REALLY REALLY want to check that mlockall succeeded, I think we need to do a lot more. At the least, we need assume(tests.maven) because people aren't going to configure their IDEs correctly. Sigar tests currently use this for example, because IDEs generally will not have the right configuration. We could also add a tests.mlockall sysprop, that controls the boolean we pass to SecurityBootstrap (https://github.com/elastic/elasticsearch/blob/master/src/test/java/org/elasticsearch/test/SecurityBootstrap.java#L47). 

It could default to false (so developers machines don't test it), and we could set it to true for jenkins jobs where we know it should be working. Even in that properly configured case I'm suspicious, because the machine could just be busy and not have enough memory available. 

So I'm worried that asserting mlockall success will only cause annoying test failures.

**Comment by gmarz** [comment]
I've gone ahead and removed the assert.  Let's maybe keep this issue open until we have the above setup in place to test it properly?

**Comment by clintongormley** [comment]
@rmuir 8 months later, do you think we still need to do anything here, or can I close the issue?
