### ISSUE TITLE
Improve request structure for scripts and templates

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#11091]
Created from the discussion at https://github.com/elastic/elasticsearch/pull/8393#issuecomment-96388815

The ScriptParameterParser added in 1.5 was an effort to make the parsing of scripts in Elasticsearch consistent but did not go far enough. The way scripts are defined in requests is still not one consistent method across the codebase. We want scripts to be defined in an object containing the script, params, lang, and type. This will be defined in the request in the following way:

Inline Scripts:
```json
...
"script": {
    "inline": "doc[foo] + 1",
    "lang": "groovy",
    "params": {
        ...
    }
}
...
```

File Scripts:
```json
...
"script": {
    "file": "my_file_script",
    "lang": "groovy",
    "params": {
        ...
    }
}
...
```

Index Scripts:
```json
...
"script": {
    "id": "my_indexed_script",
    "lang": "groovy",
    "params": {
        ...
    }
}
...
```

Inline scripts can also be specified using the following short form, but the language will be the default language and the params will be empty:

```json
...
"script": "doc[foo] + 1"
...
```

We should have similar constructs for templates. Also, the script and template classes should be available in the Java API and should be able to parse and render (build) themselves in XContent as well as being able to be serialized between nodes.

**Comment by nik9000** [comment]
Can you deprecate rather than remove the
{
  "script": " name/body",
  "lang": " whatever"
}
style?

Or maybe offer the new style in 1.6 if you are dropping the old in 2.0?

Created from the discussion at #8393 (comment)
<https://github.com/elastic/elasticsearch/pull/8393#issuecomment-96388815>

The ScriptParameterParser added in 1.5 was an effort to make the parsing of
scripts in Elasticsearch consistent but did not go far enough. The way
scripts are defined in requests is still not one consistent method across
the codebase. We want scripts to be defined in an object containing the
script, params, lang, and type. This will be defined in the request in the
following way:

Inline Scripts:

..."script": {
    "inline": "doc[foo] + 1",
    "lang": "groovy",
    "params": {
        ...
    }
}
...

File Scripts:

..."script": {
    "file": "my_file_script",
    "lang": "groovy",
    "params": {
        ...
    }
}
...

Index Scripts:

..."script": {
    "id": "my_indexed_script",
    "lang": "groovy",
    "params": {
        ...
    }
}
...

Inline scripts can also be specified using the following short form, but
the language will be the default language and the params will be empty:

..."script": "doc[foo] + 1"
...

We should have similar constructs for templates. Also, the script and
template classes should be available in the Java API and should be able to
parse and render (build) themselves in XContent as well as being able to be
serialized between nodes.

—
Reply to this email directly or view it on GitHub
<https://github.com/elastic/elasticsearch/issues/11091>.

**Comment by colings86** [comment]
@nik9000 yes, it is the intention to support both the current format and the new format in 1.6. Sorry, I should have mentioned that in the issue.

**Comment by nik9000** [comment]
Thanks!

**Comment by colings86** [comment]
Backporting the changes to 1.6 proved far too complex to have the confidence in the change, so the plan is now to merge this to 2.0 only and support the old API in the REST layer so that stuff thats stored like transforms and templates continue to work, but to remove support for the old script API in the Java API and the wire format. When the old script API is used through the REST layer it will log a deprecation warning to the new deprecation logger
