### ISSUE TITLE
Encryption of snapshot

### ISSUE THREAD

**Issue by pwli** [elastic/elasticsearch#11128]
Is it possible to encrypt snapshots before it leaves the node ?
So that data is encrypted in flight ? May be a config variable to
set up password for encryption and decryption ?

**Comment by clintongormley** [comment]
@imotov @jaymode what do you think?

**Comment by pandujar** [comment]
+1

**Comment by yarmand** [comment]
+1

**Comment by clintongormley** [comment]
@imotov @jaymode thoughts?

**Comment by yarmand** [comment]
We needed encryption for our Azure snapshots.
As some backends have encryption directly as a server side option, I implemented encryption directly in the Azure plugin.
For reference, here is the [Pull Request for this implementation against elasticsearch 1.7](https://github.com/elastic/elasticsearch-cloud-azure/pull/112).
When we update to 2.1 I will port this and will submit a PR in this repository.

**Comment by pmazeris** [comment]
+1

We're using the **repositiry-gcs** elasticsearch plugin to push to encrypted / acl'ed gcr.io buckets in GKE/Google. Having data already encrypted during transit time would be perfect. 

@yarmand, what would be a reasonable ETA for this addtion? Thks

**Comment by tlrx** [comment]
We talked about this today with @ywelsch and it seems that all cloud based storage providers supported for snapshot/restore (Amazon S3/Azure Storage/Google Cloud Storage) now provide server side encryption and secured transfers over the network using HTTPS. We don't have immediate plan to add our own encryption system in elasticsearch so I'm going to close this issue. Please feel free to comment or +1 here if you want to add your point of view.

**Comment by geekpete** [comment]
It'd be great just to use a pgp/gpg public key (loaded when adding/updating the repository as a parameter) to create snapshots and encrypt files before sending.
Then to restore/decrypt files have the associated private key loaded in order to decrypt the files as they're retrieved.
You'd need to have logic to know which encrypted objects are already present on the remote end to do incremental, but this would just be stored as part of the metadata identifying which objects represent which source files in order to be skipped if they already exist.

**Comment by jkakavas** [comment]
We discussed this today in our weekly meeting. Client side encryption for snapshots is something that we want to do and we plan to tackle in the near future. Two main points that came out of the discussion are that

* We will not implement the encryption ourselves, but rather depend on the implementation that the SDK of the providers offer. S3 (there is a community PR up for this - #30513 ) and Azure offer this
* We will optimally defer the implementation of client side encryption for snapshots for after we have a satisfactory solution for key management and password protection of the elasticsearch keystore.

**Comment by albertzaharovits** [comment]
We have discussed this in today's distributed team meeting.

I have steered the discussion away from using the SDK for encryption compared to doing the encryption with the JCE API. The heavy lifting of this feature is the key management. It matters less whether we pass this key to a SDK API or the JCE API it is more important where we get the key from and how we can rotate/disable them. The scope of the key is also important, whether the key is used for a snapshot or for a repository. Symmetric key vs Asymmetric key is another topic.

Changing the key is especially difficult. The snapshot implementation would have to be modified if we were to allow for keys to change for each snapshot operation. This is because the "index" file would have to be unencrypted (contrasting with the other files) for a new snapshot with another key to be incremental; and restoring would require all the keys.

Using a fixed key per repository (which cannot be changed for the lifetime of the repository) is a better alternative. The snapshot format will not have to change.  However, keys have to be periodically changed (rotated) - a requirement by policies. Changing keys requires decrypting with the old key and re-encrypting with the new key. This however requires new code to avoid the heavy handed approach of restoring using the old key and then snapshotting to a new repository using the new key. Curiously there is [no support](https://github.com/aws/aws-cli/issues/1686) for rotating keys in the AWS cmd line utility. Thinking about implementing this rotation mechanism got as wondering about the use cases here, to evaluate the tradeoffs: Who really uses this feature (when there is TLS + server side encryption)? Do they store the keys of the disk or have a vault-like service? How do they go about rotating them? Do they really want the data leaving their on premise cluster (even if encrypted)?

So, the main open question is: In a model with one immutable key per repository, how do we rotate keys?

**Comment by albertzaharovits** [comment]
And another question: Is having the encryption key on the data nodes be suitable for the users of "client side encryption". Or they have some other "vault" like service to manage keys?

**Comment by albertzaharovits** [comment]
We have discussed this in today's security team meeting. We have again focused on the key management topic. For the moment we are undecided whether to use SDK or JCE support to do the encryption (it depends on other decisions).

We have though about it under the assumption that a repository has a fixed key. Key rotation should ideally be handled outside of elasticsearch because this rotation mechanism is independent of the snapshot format (this is to be generic, specific only for the storage type).

All the data nodes (participating in the snapshot) have to have the same key. This is a requirement
for other features that we work on (e.g. hashing processor).

Azure and AWS employ [envelope encryption](https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#enveloping) for easy key rotation, however they don't provide client cmd line utility to do this rotation, as these CLIs tools don't have client side encryption support https://github.com/aws/aws-cli/issues/1686 . The only way to do key rotation is by using their respective "key vault" services: ["KMS" (Key Management Service)](https://docs.aws.amazon.com/kms/latest/developerguide/rotate-keys.html). This made us wonder if key management on the client application (client from the cloud provider's perspective, ES nodes, to be clear) is truly a feature requested by the kind of customers that are asking for this type of encryption in the first place (the option of TLS + server side encryption is broadly available and accessible). It might be that many are interested primarily in abiding to standards and norms  and these standards preclude non audited key management services (like the one we would like to develop).

We are torn between:
* satisfying the ultra suspicious not wanting the encryption keys to ever leave the local network
* satisfying the ultra religious wanting to abide to standards even if the improvement over TLS + server side encryption is marginal.
* or both ...

CC @joshbressers

**Comment by original-brownbear** [comment]
Closing this as a duplicate of https://github.com/elastic/elasticsearch/issues/41910 where this will be implemented in some form eventually.
