### ISSUE TITLE
First query is slow

### ISSUE THREAD

**Issue by lmqwudi** [elastic/elasticsearch#11140]
while I use es to search something, I find it behave much slower in first query.can sb tell me why?

**Comment by markwalkom** [comment]
That is because during the first query Elasticsearch pulls data into cache, so that subsequent queries are faster.
You can use [Warmers](http://www.elastic.co/guide/en/elasticsearch/reference/current/indices-warmers.html) to help with this, but be careful of using them too much.

Also please join us in #elasticsearch on Freenode or at https://discuss.elastic.co/ for troubleshooting help, we reserve Github for confirmed bugs and feature requests :)
