### ISSUE TITLE
ESQL: Align documentation and the return type for datetime/date type

### ISSUE THREAD

**Issue by qn895** [elastic/elasticsearch#111650]
### Description

It would be good to align the types mentioned in the documentation to what we are returning in the ES|QL reponses. Either updating the documentation to use `date` instead of `datetime` or change the return type of the response to `datetime` . Currently, the documentation uses a mix of both which is a bit confusing.

For example, let's say for following documentation of [date_diff](https://www.elastic.co/guide/en/elasticsearch/reference/current/esql-functions-operators.html#esql-date_diff) that uses  to_datetime, we are mixing datetime (supported type table above) and :date (table below).

![image](https://github.com/user-attachments/assets/6717484f-4758-4a7e-ab26-758590d00822)

![image](https://github.com/user-attachments/assets/7f096f58-ecb3-4780-a1a8-a87eed4e0e10)

Supported field types also mention `date`

<img width="592" alt="image" src="https://github.com/user-attachments/assets/8738f6a1-dcad-4042-8a68-cb1be7ea9c00">

Additionally, it would be good to clarify what `date_period` and `time_duration` are and some examples in the ES|QL documentation.

**Comment by bpintea** [comment]
> Additionally, it would be good to clarify what date_period and time_duration are and some examples in the ES|QL documentation.

They're covered [here](https://www.elastic.co/guide/en/elasticsearch/reference/master/esql-syntax.html#esql-timespan-literals), but not individually split.

**Comment by bpintea** [comment]
> Either updating the documentation to use date instead of datetime or change the return type of the response to datetime .

"date" is the type Elasticsearch [uses](https://www.elastic.co/guide/en/elasticsearch/reference/current/date.html), even though it's actually a datetime (internally).
QL has been using `DATETIME` for it, because SQL does have support for just `DATE` (which is just that, date).

We've been outputting the types ES has, but yes, we could look into considering taking the split stance (and return "datetime", since that's what the values always look like anyways).
