### ISSUE TITLE
Cluster not indexing new documents when in "yellow" state.

### ISSUE THREAD

**Issue by rsomcio** [elastic/elasticsearch#11173]
I restarted a node in my cluster but new documents are not indexing.  I thought "yellow' state meant that unassigned replicas are getting initialized but the cluster is still fully functional.  Is this a bug?

+=== debug

$ curl -XGET 'es.internal.company.com:9200/_cluster/health?pretty'
{
  "cluster_name" : "es_cluster_a",
  "status" : "yellow",
  "timed_out" : false,
  "number_of_nodes" : 9,
  "number_of_data_nodes" : 6,
  "active_primary_shards" : 1265,
  "active_shards" : 3041,
  "relocating_shards" : 0,
  "initializing_shards" : 12,
  "unassigned_shards" : 725,
  "number_of_pending_tasks" : 0
}

curl -XGET 'es.internal.company.com:9200/_cat/indices?pretty'|sort -k 3n

yellow open web-logs-2015.05.11              8 2 577100361   0 697.3gb  346.7gb
yellow open web-logs-2015.05.12              8 1 737742512   0 640.3gb  496.3gb
yellow open web-logs-2015.05.13              8 1 632722103   0 557.6gb  402.5gb
yellow open web-logs-2015.05.14              8 2 240925903   0 309.3gb  148.5gb
yellow open web-logs-2015.05.15              8 2         0   0    920b     920b

**Comment by imotov** [comment]
@rsomcio `yellow` means that all primary shards have started but it doesn't mean that you have enough shards to achieve default [write consistency](http://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#index-consistency) for all indices if you have more than one replica per index. Your assumption is only correct if indices in the cluster have no more then 1 replica. It looks like in your case at least some of the indices have 2 replicas or more. For such indices a primary shard and at least one other replica have to be available to perform index operation with default level of write consistency. The `yellow` health status doesn't guarantee that. This issue is discussed in details in #4755. So, I am going to close this one as a duplicate. Please feel free to reopen it if my assessment of the issue was incorrect and you think that you have a different issue.
