### ISSUE TITLE
`Engine#getSparseVectorValueCount` seems rather expensive

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#111715]
I was looking at the hot threads for a large-ish node and observed that all the `management` threads were at 100% executing `Engine#getSparseVectorValueCount`. This was added in https://github.com/elastic/elasticsearch/pull/108793. I think this is going to be a problem, it looks like maybe we should add some caching or other optimizations here.

**Comment by jimczi** [comment]
@DaveCTurner can you share the hot thread output? From a quick look at the code it might be because we go through [all the fields in the mapping on every leaves](https://github.com/elastic/elasticsearch/pull/108793/files#diff-f8501346ff87c692cce80010afb9362e72d7f4d1550d29fefef71fff05922ac4R315) to find sparse vector field. A quick fix should be to go through the mapping only once and then go on the leaves but only if the mapping has one or more sparse vector field.

**Comment by jimczi** [comment]
I opened https://github.com/elastic/elasticsearch/pull/111729, the way these stats are implemented impacts deployments that don't even use dense/sparse vectors so it's problematic. Thanks for reporting @DaveCTurner!
