### ISSUE TITLE
Limit duration on scan&scroll

### ISSUE THREAD

**Issue by seang-es** [elastic/elasticsearch#11238]
Scan and scroll could be made safer by limiting the amount of time the scan window remains open.  If it's open too long, it can lead to extra segments failing to merge and will consume resources on the system.  A maximum limit to the duration could help keep scan and scroll from breaking the cluster if used improperly.

**Comment by jpountz** [comment]
+1

**Comment by nik9000** [comment]
More playing devil's advocate than anything, but why isn't the timeout that you have to put on each request enough to do that? Because you could theoretically drag the request out a long long time?

Also when I use scan/scroll for mapping updates and on some indexes that process can take the better part of a day. How long do we have to get for these requests to get scary?

**Comment by clintongormley** [comment]
I'm not sure how we could enforce a maximum duration without breaking scroll requests.

**Comment by rjernst** [comment]
@clintongormley I think we could do this by first allowing a new parameter to add this total duration limit on the scroll, and then at a later time making some value the default for the limit instead of infinity?

**Comment by clintongormley** [comment]
This sounds like a policy for admins rather than for users.  I'm wondering if a better approach would be the task management API #6914.  Admins would be able to check for long running jobs which have exceeded their permitted lifespan and to kill them via an API.  They could also choose not to kill them, as opposed to realising too late that they have started an important scan/scroll job without extending the default lifespan.

**Comment by rjernst** [comment]
Task management seems to me more for background tasks. Isn't all we are talking about an extra setting on the initial request that limits the total time allowed to refresh the scroll? Having to do an extra check for ```jobs which have exceeded their permitted lifespan and to kill them via an API``` seems rather cumbersome.

**Comment by clintongormley** [comment]
@rjernst As a user, why would you start a scan/scroll job and then abort it before it is finished? You'd just need to start it again.  This is why I think that this functionality is more for the admin who wants to force their users to obey certain policies (but may well want to exempt their own long running jobs from such policies).

**Comment by adrianosimoes** [comment]
I noticed this is a old issue. Is this issue still relevant?

**Comment by clintongormley** [comment]
Yes it is, and in fact we discussed this again just the other day.  We should add a soft limit which prevents setting the `scroll` time to more than (eg) 5 minutes.

**Comment by colings86** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/issues/23268
