### ISSUE TITLE
[ES|QL] Return correct correct message when a union type field is provided to to_dateperiod or to_timeduration

### ISSUE THREAD

**Issue by fang-xing-esql** [elastic/elasticsearch#112668]
`To_DatePeriod` and `To_TimeDuration` only take constants as input, when a union type field is provided to them, the correct error message doesn't return.

Here are the steps to reproduce it:

```
curl -u elastic:password -H "Content-Type: application/json" "127.0.0.1:9200/test1" -XPUT -d '{
  "mappings": {                                                                                                         
        "properties": {
            "x": {       
                "type": "keyword"
            }
        }
  }
}'
curl -u elastic:password -H "Content-Type: application/json" "127.0.0.1:9200/test2" -XPUT -d '{
  "mappings": {
        "properties": {
            "x": {
                "type": "text"   
            }
        }
  }
}'
curl -u elastic:password -H "Content-Type: application/json" "127.0.0.1:9200/_query?format=txt" -d '{
    "query": "from test* | eval y = now() + to_dateperiod(x)"}
'

"verification_exception","reason":"Found 1 problem\nline 1:45: Cannot use field [x] due to ambiguities being mapped as [2] incompatible types: [keyword] in [test1], [text] in [test2]"}]
```

`To_DatePeriod` has an unresolved child, `Analyzer`'s `Verifier` errors out. However, the real/expected error that the function only takes foldable inputs are not returned, because the check to foldable is deferred to `LogicalPlanOptimizer`, which is after `Analyzer`. The correct error message is returned for the other field/data types, this is found for union type field only.

**Comment by alex-spies** [comment]
I left a [comment](https://github.com/elastic/elasticsearch/pull/109193#discussion_r1749990480) with suggestions on where to do the validation, which also would improve general error messages for union types.

**Comment by craigtaverner** [comment]
> I left a https://github.com/elastic/elasticsearch/pull/109193#discussion_r1749990480 with suggestions on where to do the validation, which also would improve general error messages for union types.

I added a reply to that comment:

> I agree that the solution should be in the Analyzer.ResolveUnionTypes, and also think it could be related to another idea we have, which is to support union-types for more functions than just convert functions. Currently we assume that all convert functions support union-types and no other functions do. But this discussion clarifies that there exist convert functions that do not. So what about creating an interface for functions that support union-types, make sure all but these foldable functions use that, and this opens up the option to add union-types to other functions too?

**Comment by bpintea** [comment]
I guess there are two error messages here, both valid.

> the real/expected error that the function only takes foldable inputs

Is that true, though? The fact that `x` is referred to outside of a conversion is also a problem. I'm not sure we'd want "auto-union" for this function. If you'd write `... | eval ... to_dateperiod(x::keyword)`, you'd get to the second problem (and its expected message).

**Comment by bpintea** [comment]
> make sure all but these foldable functions use that

What type would the union types be cast to? I guess we'd need to extract the called function argument's type. 
But generally there might be an idea in auto-union-ing, since some conflicts (like text-keyword, byte-...-long) are just a nuisance (and probably frequent).

**Comment by alex-spies** [comment]
@bpintea :
> Is that true, though? The fact that x is referred to outside of a conversion is also a problem. I'm not sure we'd want "auto-union" for this function. If you'd write ... | eval ... to_dateperiod(x::keyword), you'd get to the second problem (and its expected message).

But `to_dateperiod` _is_ a conversion. It'd be totally reasonable to expect that this conversion can take both `keyword` and `text` fields, and thus also field mapped to both.

But the specialty here is that `to_dateperiod` and `to_timeduration` only take literals and constants. No matter what we'd do about the types, the expression `to_dateperiod(x)` will always be wrong - so the error message is not helpful and masks the real problem.

**Comment by alex-spies** [comment]
@craigtaverner: 
> I agree that the solution should be in the Analyzer.ResolveUnionTypes, and also think it could be related to another idea we have, which is to support union-types for more functions than just convert functions. Currently we assume that all convert functions support union-types and no other functions do. But this discussion clarifies that there exist convert functions that do not. So what about creating an interface for functions that support union-types, make sure all but these foldable functions use that, and this opens up the option to add union-types to other functions too?

++ on the interface for functions that can take multi-typed fields. However, since currently these are exactly the type conversions sans `to_dateperiod` and `to_timeduration`, maybe we can implement this abstraction when/if we start having more such functions?

**Comment by bpintea** [comment]
@alex-spies 

> No matter what we'd do about the types, the expression to_dateperiod(x) will always be wrong

I'm just wondering if we have an established priorities list of failures: `FROM employees | EVAL birth_date + TO_DATEPERIOD(birth_date + 1 YEAR)` also fails on verification, also on TO_DATEPERIOD's input type.

Even with the [proposed fixed](https://github.com/elastic/elasticsearch/pull/114934), something like `from test* | eval y = now() + to_dateperiod(concat(x, "1 year"))` will still fail with the same error message you're trying to address. I'm just not convinced the fix should be in union types.

**Comment by fang-xing-esql** [comment]
> Even with the [proposed fixed](https://github.com/elastic/elasticsearch/pull/114934), something like `from test* | eval y = now() + to_dateperiod(concat(x, "1 year"))` will still fail with the same error message you're trying to address. I'm just not convinced the fix should be in union types.

Thanks for the discussions @bpintea @alex-spies ! I realized that our `VerificationException` becomes a bit complicated when new things are added, the water becomes a little too deep. To_DatePeriod and To_TimeDuration exposed inconsistent error messages on constant function arguments, and Bogdan's example exposes potential inconsistent error messages on field arguments, it doesn't look completely wrong to me 🤔, although more consistent is better. They are not show stoppers, but I'm sure we can do something to make it more consistent, I'm not sure the best option yet, need more time to think through it. 

```
from types | eval y = concat(integer, "1 year")
1:24: argument of [concat(integer, "1 year")] must be [string], found value [integer] type [integer]

from test* | eval y = concat(multi_typed, "1 year")
1:30: Cannot use field [multi_typed] due to ambiguities being mapped as [2] incompatible types: [ip] in [test1, test2, test3] and [2] other indices, [keyword] in [test6]
```

**Comment by alex-spies** [comment]
I agree @bpintea and @fang-xing-esql , there's a more general issue/complication at play here.

```
from test* | eval y = now() + to_dateperiod(concat(x, "1 year"))
```
I think this is a very nice example, thanks @bpintea .

I was trying to think of a way to solve this without adding special casing to union types' resolution. But I don't think it's really possible, and after some consideration I think that putting the special casing right into union types' resolution is actually correct.

To produce the error message "don't use a field" instead of "mapping conflict" in `to_dateperiod(concat(x, "1 year"))`, we'd have to run the optimizer and fold stuff. Or at least traverse the expression and determine that we depend on a field. But we don't run the optimizer on queries that have unresolved fields and it'd probably be hard to make that work properly.

And adding something special just to determine if the expression itself depends on a field is also insufficient. We have the same problem with `EVAL other_name = x | EVAL y = now() + to_dateperiod(other_name)`. The most useful error message really is "don't use a field in `to_dateperiod`", but we'll let the user know about the mapping conflict, instead. But determining that "don't use a field" is the right error message requires propagating foldables as an optimization.

In contrast, for `from test* | eval y = now() + to_dateperiod(x)`, we actually can provide a good error message. And union type resolution deals exactly with converter functions applied to multi-typed fields, that's its job. So I think union type resolution should create good error messages when sticking a field into a converter function makes no sense, like here. Actually, I think we should go further and make useful error messages when a mapping conflict has types that the converter function can't even take in the first place. And this is determined exactly in the spot where https://github.com/elastic/elasticsearch/pull/114934 deals with `to_dateperiod` and `to_timeduration`.

Maybe we could also make an argument that we should have appropriate error messages at least when we stick something nonsensical directly into a function - even though changing the expression 1 or several nesting levels higher than that would actually be required to make it work?

**Comment by bpintea** [comment]
> I was trying to think of a way to solve this without adding special casing to union types' resolution. But I don't think it's really possible, and after some consideration I think that putting the special casing right into union types' resolution is actually correct.

Yes, after more thought, I think that's correct, indeed. It just feels like such a verification step that we put in the analyser, and more to it, only to prioritise a certain message over what is in the end a failure, but I guess since that's how union types work, we'll have to adapt.
