### ISSUE TITLE
docbug: rolling restarts

### ISSUE THREAD

**Issue by faxm0dem** [elastic/elasticsearch#11278]
There's several places in the reference documentation which duplicate the *rolling restart* procedure:

* [setup-upgrade](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html)
* [_rolling_restarts](https://www.elastic.co/guide/en/elasticsearch/guide/current/_rolling_restarts.html)
* [cluster-nodes-shutdown](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-shutdown.html)

The latter is wrong, as it fails to mention the allocation needs to be re-enabled after every node restart.

## Proposed change:

Remove duplicates (especially the wrong ones), and reference the one true procedure from all other places

**Comment by clintongormley** [comment]
Hi @faxm0dem 

Thanks for pointing this out. I've left the docs in the Definitive Guide, because that's for a published book and I think it is OK to duplicate it there.  However, the shutdown API has been removed in master, so I've added a deprecation notice to the 1.x branch, and just deleted the rolling restart docs from that page in 1.x (62c5361ad8d09a043d4ad800c142362045c135fd)  and 1.5 (a8c46d68a863e4be33f1d2aba24843f7940dcaf2)
