### ISSUE TITLE
[DOCS] Update 'Scalability and resilience' documentation with updated content

### ISSUE THREAD

**Issue by kosabogi** [elastic/elasticsearch#112999]
### Description

The scalability section of the [Elasticsearch guide](https://www.elastic.co/guide/en/elasticsearch/reference/8.16/scalability.html) needs to be updated with the content provided in this [Google document](https://docs.google.com/document/d/1F9SamrQCTZnPt8_1bQpx2zOUk8AWsYPIVXRpQGMydkY/edit#heading=h.dlm29rqz3td1).

**Comment by leemthompo** [comment]
@kosabogi because the [basics page](https://www.elastic.co/guide/en/elasticsearch/reference/master/elasticsearch-intro.html) is now live, you're free to start working on porting @shainaraskas's draft to the [scalability section](https://github.com/elastic/elasticsearch/blob/main/docs/reference/intro.asciidoc?plain=1#L381C1-L382C24). :)

**Comment by kosabogi** [comment]
Related PR: https://github.com/elastic/elasticsearch/pull/113679
