### ISSUE TITLE
ESQL: Inconsistent quoting in identifiers

### ISSUE THREAD

**Issue by alex-spies** [elastic/elasticsearch#113028]
In the grammar, [qualifiedName](https://github.com/elastic/elasticsearch/blob/f7880ae85f0be9f9a8c89c5415ce406c293a09db/x-pack/plugin/esql/src/main/antlr/EsqlBaseParser.g4#L170) and [qualifiedNamePattern](https://github.com/elastic/elasticsearch/blob/f7880ae85f0be9f9a8c89c5415ce406c293a09db/x-pack/plugin/esql/src/main/antlr/EsqlBaseParser.g4#L173) allow dot-separated names and quotes, but the quoting is more restrictive on `qualifiedName`.

In the following examples, consider that `KEEP` and `DROP` and most other commands use `qualifiedNamePattern`, while `EVAL` and `MV_EXPAND` and, generally, expressions use `qualifiedName`

```
ROW foo.bar = 1 | KEEP foo.`b`a`r` // OK

ROW foo.bar = 1 | KEEP `foo.`b*`a`r // OK

ROW foo.bar = 1 | EVAL x = 1 + foo.`b`a`r` // parsing exception

ROW foo.bar = 1 | EVAL x = 1 + `foo.bar` // OK

ROW foo.bar = 1 | EVAL x = 1 + `foo`.`bar` // OK
```

**Comment by ivancea** [comment]
I've just learnt that the syntax
```
`a`b`c`
```
exists for patterns, to be able to escape wildcards, like in:
```
`logs_`*`_abc`
```

So I wonder if it would be better to propagate that _weird_ syntax to all identifiers, or to restrict the pattern syntax in some way to only allow to mix wildcards with the quotes (Which would be a breaking change, probably with edge cases too).

Just dumping this here for now

**Comment by costin** [comment]
A better example is `` `field prefix`*`s u f f i x` `` - both the suffix and prefix name contain spaces and need to be escaped with backticks. Yet we want to match what's inside of them.
This is not the case with normal qualifiers since they don't contain a pattern so allowing mixed quoted and unquoted text adds no value - simply escape everything or don't. There's no special * character.

My point is, this is by designed. We could have aligned the two but it would complicate the declaration without any benefit.

**Comment by alex-spies** [comment]
Thanks for the clarification @costin . Since this is by design and there's no reason to make the quoting more flexible in places that _do not use wildcards_, I'll close this as this is not a bug in the first place.
