### ISSUE TITLE
Exception occured when accessing elastic search

### ISSUE THREAD

**Issue by aimdev** [elastic/elasticsearch#11340]
While accessing a dataset thats been working for a week or so, this morning this occurred.
Error: Request to Elasticsearch failed: {"error":"ReduceSearchPhaseException[Failed to execute phase [query], [reduce] ]; nested: ClassCastException[java.lang.Long cannot be cast to org.apache.lucene.util.BytesRef]; "}
KbnError@http://elastic.sec.lan:5601/index.js?_b=6004:39225:30
RequestFailure@http://elastic.sec.lan:5601/index.js?_b=6004:39262:18
http://elastic.sec.lan:5601/index.js?_b=6004:42993:56
try@http://elastic.sec.lan:5601/index.js?_b=6004:46233:31
http://elastic.sec.lan:5601/index.js?_b=6004:46211:27
map@[native code]
map@http://elastic.sec.lan:5601/index.js?_b=6004:46210:33
callResponseHandlers@http://elastic.sec.lan:5601/index.js?_b=6004:42965:25
http://elastic.sec.lan:5601/index.js?_b=6004:43083:36
wrappedCallback@http://elastic.sec.lan:5601/index.js?_b=6004:20888:81
wrappedCallback@http://elastic.sec.lan:5601/index.js?_b=6004:20888:81
http://elastic.sec.lan:5601/index.js?_b=6004:20974:34
$eval@http://elastic.sec.lan:5601/index.js?_b=6004:22017:28
$digest@http://elastic.sec.lan:5601/index.js?_b=6004:21829:36
$apply@http://elastic.sec.lan:5601/index.js?_b=6004:22121:31
done@http://elastic.sec.lan:5601/index.js?_b=6004:17656:51
completeRequest@http://elastic.sec.lan:5601/index.js?_b=6004:17870:15
onreadystatechange@http://elastic.sec.lan:5601/index.js?_b=6004:17809:26

**Comment by markwalkom** [comment]
What version of ES?

**Comment by aimdev** [comment]
Hi
Version: 1.5.2, Build: 62ff986/2015-04-27T09:21:06Z, JVM: 1.8.0_45
Aimee

**Comment by clintongormley** [comment]
Hi @aimdev 

It sounds like you have run into a known mapping bug. Either:

* you have two fields with the same name with different mappings in different types in the same index (#8871), or
* you are using dynamic mapping and two shards have ended up mapping the same field as different data types (https://github.com/elastic/elasticsearch/issues/8688).  when one shard gets moved to a different node it applies the data type as specified on the master, which can clash with the data type stored on disk

Both of these issues will be fixed in 2.0 (see #8870).  For now, the only solution for now is to (fix your mappings in the first case, then) to reindex your data.

**Comment by nidgupta** [comment]
I also faced the same issue of dynamic mapping ended up with different data types on 2 shards. we are not yet on 2.0, so as work around I snapshotted and restored the index, all good now.
