### ISSUE TITLE
app-misc/elasticsearch-8.15+ is not working on system without libsystemd

### ISSUE THREAD

**Issue by j4Hu** [elastic/elasticsearch#113666]
### Elasticsearch Version

8.15

### Java Version

openjdk version "21.0.3" 2024-04-16 LTS

### OS Version

gentoo linux 6.9.12 with openrc without systemd

### Problem Description

on linux distribution without systemd (with openrc) and systemd libraries (libsystemd), elasticsearch will not start, because bootstrap checks uses only libsystemd and fails.

even with native access lib turned off, bootstrap checks fails:
ES_JAVA_OPTS="$ES_JAVA_OPTS -Dorg.elasticsearch.nativeaccess.enableVectorLibrary=false"

limits are set ok, and versions before 8.15 are working ok. 

/etc/conf.d/elasticsearch:
MAX_OPEN_FILES=65536
MAX_LOCKED_MEMORY=unlimited
MAX_THREADS=4096

### Steps to Reproduce

- install version 8.15+ (8.15, 8.15.1, 8.15.2)
- start service
- service is stopped after failed bootstrap checks

### Logs (if relevant)

[2024-09-27T09:48:16,694][WARN ][o.e.n.NativeAccess       ] host] Unable to load native provider. Native methods will be disabled.
java.lang.UnsatisfiedLinkError: Could not find libsystemd in java.library.path: /usr/share/elasticsearch/lib/platform/linux-x64:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
at org.elasticsearch.nativeaccess.jdk.JdkSystemdLibrary.<clinit>(JdkSystemdLibrary.java:43) ~[elasticsearch-native-8.15.1.jar:?]
at org.elasticsearch.nativeaccess.lib.NativeLibraryProvider.getLibrary(NativeLibraryProvider.java:58) ~[elasticsearch-native-8.15.1.jar:?]
at org.elasticsearch.nativeaccess.LinuxNativeAccess.<init>(LinuxNativeAccess.java:20) ~[elasticsearch-native-8.15.1.jar:?]
at org.elasticsearch.nativeaccess.NativeAccessHolder.<clinit>(NativeAccessHolder.java:28) ~[elasticsearch-native-8.15.1.jar:?]
at org.elasticsearch.nativeaccess.NativeAccess.instance(NativeAccess.java:22) ~[elasticsearch-native-8.15.1.jar:?]
at org.elasticsearch.bootstrap.Elasticsearch.initializeNatives(Elasticsearch.java:285) ~[elasticsearch-8.15.1.jar:?]
at org.elasticsearch.bootstrap.Elasticsearch.initPhase2(Elasticsearch.java:170) ~[elasticsearch-8.15.1.jar:?]
at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:75) ~[elasticsearch-8.15.1.jar:?]
[2024-09-27T09:48:16,753][WARN ][o.e.n.NativeAccess       ] host] Cannot check if running as root because native access is not available

    
[2024-09-27T09:46:04,056][INFO ][o.e.b.BootstrapChecks    ] host] bound or publishing to a non-loopback address, enforcing bootstrap checks
[2024-09-27T09:46:04,062][WARN ][o.e.n.NativeAccess       ] host] Cannot get process limits because native access is not available
[2024-09-27T09:46:04,063][WARN ][o.e.n.NativeAccess       ] host] Cannot get process limits because native access is not available
[2024-09-27T09:46:04,064][WARN ][o.e.n.NativeAccess       ] host] Cannot get process limits because native access is not available
[2024-09-27T09:46:04,064][WARN ][o.e.n.NativeAccess       ] host] Cannot get process limits because native access is not available
[2024-09-27T09:46:04,066][WARN ][o.e.n.NativeAccess       ] host] Cannot get process limits because native access is not available
[2024-09-27T09:46:04,066][WARN ][o.e.n.NativeAccess       ] host] Cannot get process limits because native access is not available
[2024-09-27T09:46:04,079][ERROR][o.e.b.Elasticsearch      ] host] node validation exception
[2] bootstrap checks failed. You must address the points described in the following [2] lines before starting Elasticsearch. For more information see [https://www.elastic.co/guide/en/elasticsearch/reference/8.15/bootstrap-check
s.html]
bootstrap check failure [1] of [2]: max size virtual memory [-1] for user [elasticsearch] is too low, increase to [unlimited]; for more information see [https://www.elastic.co/guide/en/elasticsearch/reference/8.15/max-size-virt
ual-memory-check.html]
bootstrap check failure [2] of [2]: max file size [-1] for user [elasticsearch] is too low, increase to [unlimited]; for more information see [https://www.elastic.co/guide/en/elasticsearch/reference/8.15/_max_file_size_check.ht
ml]
[2024-09-27T09:46:04,095][INFO ][o.e.n.Node               ] host] stopping ...
[2024-09-27T09:46:04,148][INFO ][o.e.n.Node               ] host] stopped
[2024-09-27T09:46:04,149][INFO ][o.e.n.Node               ] host] closing ...
[2024-09-27T09:46:04,182][INFO ][o.e.n.Node               ] host] closed

**Comment by rjernst** [comment]
Thanks very much for your interest in Elasticsearch.

This issue seems to be a report of Elasticsearch not working on an unsupported platform. Specifically, Elasticsearch does not support Gentoo linux, nor any systems that do not have systemd.

We choose to support particular platforms with care. We test the platform on our CI with our full suite of tests, we create platform specific tests, and our team ensures that every Elasticsearch release works correctly on that platform. Additionally we need to spend time investigating failures on that platform, and making sure performance is acceptable, etc.

Because of the above we generally will not make changes targeting an untested and unsupported platform because we cannot guarantee that the change works, and will continue to work in future releases and we aren't prepared to have code in the repository that we cannot maintain, because it's not tested. It would be a very bad experience for our users if Elasticsearch suddenly stopped working on a particular platform after an upgrade.

Given the above, I hope you don't mind I close this issue.

**Comment by j4Hu** [comment]
Thank you for your prompt response and for explaining the reasons behind the compatibility decisions. I appreciate your commitment to maintaining high-quality software and ensuring that your users have a positive experience.

I understand that Elasticsearch does not officially support Gentoo Linux and **from version 8.15+ systems without systemd**, but I wanted to bring to your attention a point regarding the documentation and the recent changes in the requirements for Elasticsearch 8.15+.

I kindly request that you consider **providing a clear changelog entry or documentation update that explicitly states the requirement for systemd starting from version 8.15+**. This would help users like myself better understand the system requirements and plan accordingly.

Your documentation does not mentions these requirements (systemd), looks like all linux should work.   versions <8.14 works for years.
https://www.elastic.co/guide/en/elasticsearch/reference/current/targz.html


Additionally, I would like to **suggest that you consider turning off, or other change in the bootstrap checks** when running Elasticsearch with ES_JAVA_OPTS="$ES_JAVA_OPTS **-Dorg.elasticsearch.nativeaccess.enableVectorLibrary=false**". As i understand this option, means that ES should not load libsystemd.

This would allow users who are aware of the potential issues to work around them and use the software on unsupported platforms if they wish to do so.

Thank you again for your time and consideration. 


PS: The decision to hard require libsystemd for the simple "ulimit -a" check does have security implications. See libsystemd + XZ hack

**Comment by Kangie** [comment]
@rjernst 

How do you square this with https://github.com/elastic/elasticsearch/commit/0f176e1779b2869f8cb2b788aae5509bbbcf3725 where you dropped your requirement for libsystemd a few months ago?

In light of the commit above this reeks of a bug, not an "unsupported configuration"

**Comment by rjernst** [comment]
The commit you referenced was about removing the need to link to libsystemd, not about avoiding systemd altogether. We still talk to systemd, but directly over the socket systemd provides. Note that the change you referenced is not yet released, it will be in 8.16. I suspect it will help you since we then only talk to systemd if the NOTIFY_SOCKET env var is present. But because you are running on an unsupported system (gentoo linux), if there are further changes necessary to get running, we will not be able to make them in Elasticsearch.

**Comment by Kangie** [comment]
@rjernst 

>  because you are running on an unsupported system (gentoo linux)

What systems count as "supported" in the eyes of elasticsearch? Is there some matrix that I'm unaware of? You ship a Java application.

Gentoo systems certainly _can_ include systemd, but nowhere in your documentation does it mention that this is a requirement.

I'll consider dropping the downstream package entirely (or my maintainership of it) if we can't reasonably expect to raise _legitimate issues_ with our upstream and have them be taken seriously.

**Comment by j4Hu** [comment]
> The commit you referenced was about removing the need to link to libsystemd, not about avoiding systemd altogether. We still talk to systemd, but directly over the socket systemd provides. Note that the change you referenced is not yet released,

optionally comunication/dependency , if it is present is definitely ok. it is restoring old behavior.
linux systemd should not be hard requirement for multi platform java application by design.

> it will be in 8.16. I suspect it will help you since we then only talk to systemd if the NOTIFY_SOCKET env var is present. 

great, this will be very helpful, looking forward to try 8.16+ and let you know

> But because you are running on an unsupported system (gentoo linux), if there are further changes necessary to get running, we will not be able to make them in Elasticsearch.

i understand, but it seems like any linux platform was supported, and is by documentation. 
there is no reason to not support, if you bundle all requirements (bundled java). 

(you can also bundle systemd :D)

i am very happy that in newer version, after commit merge, old behavior will be back again. tnx

**Comment by rjernst** [comment]
> What systems count as "supported" in the eyes of elasticsearch? Is there some matrix that I'm unaware of?

Yes, the [support matrix](https://www.elastic.co/support/matrix) defines which OS/distributions are supported with each version of Elasticsearch. These are the specific systems we test on. For anything outside of that we won't make changes _specific to that system_. 

> You ship a Java application.

A Java application which has some small amount of native code. It's tangential to this case, but we do have eg a native vector library that is platform specific. The point is Elasticsearch is not a _pure_ Java application. We have limited resources, so we choose a limited set of platforms to test on. We've had cases before where a change is necessary to support a platform, like a tweak to how we interact with the system, we've made it, but then inadvertently break it again. Instead of playing a game of whack-a-mole, we take a harder stance on not making changes targeted at unsupported platforms.

Again, I don't _think_ it will matter in this case, the requirement for libsystemd should be gone. But I explained the above to clearly set expectations for any future problems.
