### ISSUE TITLE
deb package postrm script

### ISSUE THREAD

**Issue by p53** [elastic/elasticsearch#11373]
Hi,

i have /var/lib/elasticsearch on separate filesystem, i found that in your postrm scripts you are removing this directory, apparently if it is mountpoint and filesystem is mounted, script won't be able to remove it, thus removing will fail

elasticsearch version: 1.5.2

**Comment by tlrx** [comment]
@p53 thanks for reporting. Note that this repository is removed only if it's empty. Did the uninstall fail because of this?

**Comment by p53** [comment]
Hi i removed all things from /var/lib/elasticsearch and yes now package was removed. But those things which were in /var/lib/elasticsearch were there by default, so it seems unconsistent, to install package by one operation and to uninstall you need beside uninstall operation also remove files which were not created by me, but by package manually

**Comment by tlrx** [comment]
@p53 thanks for your response. The folder is created by the package installation but it remains empty until elasticsearch is started. Once elasticsearch is started we should not removed this folder because important data can reside in it.

I'll update the script to not fail when deleting this folder. In worst case an empty folder won't be deleted.
