### ISSUE TITLE
Better support for async indexing

### ISSUE THREAD

**Issue by nickminutello** [elastic/elasticsearch#11394]
I am indexing from a message stream where I can get bursts of about 1m messages in about 10sec.
Elastic (embedded, 1 node, 5 shards at the moment) wont keep up with this.

To maximise throughput, I would like to be able to index these asynchronously (ie, call IndexRequestBuilder.execute() with no .actionGet() ).
If I do, however, within a few seconds, the indexing threadpool queue gets overrun and I get EsRejectedExecutionException errors.

What I would like to be able to do is specify on the request that the call blocks until it is queued rather than giving me an EsRejectedExecutionException - ie slowing the client down rather than rejecting the requests.

At the moment, I run the indexing requests through a ThreadPoolExecutor with a fixed capacity queue and a CallerRunsPolicy - so that when the queue reaches capacity. It would be nice if I didnt need this additional threadpool, and instead I could lean directly on Elastic's threadpool.

(BTW, I can optimise further by batching index requests - but I doubt it would eliminate the problem - and also its not completely trivial because I frequently end up with multiple updates to the same document in the one batch - which then fails)

I am presently using the Java API, but I guess this is applicable to all interfaces.

**Comment by clintongormley** [comment]
hi @nickminutello 

(not a java dev but...)

What you're asking for is back pressure, which is best implemented by indexing synchronously with multiple threads (it sounds like what you're doing today).  In fact, we're deprecating async indexing because it complicates other features that we're introducing (https://github.com/elastic/elasticsearch/pull/10642)

If Elasticsearch has to queue these requests up, it ends up consuming memory. That's the last thing you want to do on your server.  I think what you're doing already is correct.

(repeat: not a java dev and apologies if i'm missing something)

**Comment by nik9000** [comment]
> In fact, we're deprecating async indexing because it complicates other features that we're introducing (#10642)

I just skimmed it but that looks like async replication not async indexing on the client, right?

> What you're asking for is back pressure

@nickminutello didn't ask for backpressure, but it'd be useful in this situation. If the inserting application could signal to the queueing application that it needs to slow down and maybe discard some data points, that'd be back pressure. Its really useful in the kind of real time systems I don't work on any more!

I think this is the crux of the request:
> the call blocks until it is queued rather than giving me an EsRejectedExecutionException
Which makes sense to me. java.util.concurrent doesn't have a caller blocks policy, annoyingly. So that is a pain.

**Comment by nickminutello** [comment]
@nik9000 I presumed the caller blocking was a form of back-pressure.
But yes, some way of pushing back and making the async indexing client wait.

It doesnt have to even block, per se, it could just execute the request synchronously - which has the desired effect of pushing back on the client.

@clintongormley I understand what you mean by memory consumption - blocking the caller implies keeping the request in memory, however that memory consumption would be proportional to the number of indexing client threads, so in most cases, that will be naturally bounded.

It just seems a bit of a shame to have another level of threadpool on the client to achieve asynchronicity - when elastic natively handles 90% of the problem - async indexing, with bounded queue, etc but only 1 policy for dealing with queue over-capacity.
If the indexing client code is quite simple (which in my case it is) then adding thread-pooling, etc is a big delta in complexity.

**Comment by clintongormley** [comment]
We've removed async indexing in order to be able to support synced flushes, so I'm going to close this ticket.
