### ISSUE TITLE
query string does not take field analyzer into account

### ISSUE THREAD

**Issue by MarneusCalgarXP** [elastic/elasticsearch#11411]
I define a mapping with a simple text field, with two analyzers:
* index_analyzer : a ngram indexer, with stop words and whitespace tokenizer
* index_searcher : a analyzer, with the same elision, stop words, and same tokenizer, but without ngram

I index the french text **"part de reve"**
* "de" is a word that belongs to stop words
* the ngram indexes all ngram tokens from words "part" and "reve".

When I search (using query string) the string **"part de reve"** (using AND operator), the query returns nothing.
I have to search **"part reve"** (without "de") to retrieve my data ==> the stop word is not removed from query.

Here is the whole example:

*    DELETE test

*    PUT test
```javascript
{
  "analysis" : {
    "analyzer" : {
      "ngram_indexer" : {
        "tokenizer" : "whitespace",
        "char_filter" : ["my_mapping"],
        "filter" : [
          "stop_francais",
          "substring"
        ]
      },
      "ngram_searcher" : {
        "tokenizer" : "whitespace",
        "char_filter" : ["my_mapping"],
        "filter" : [
          "stop_francais"
        ]
      }
    },
    "filter" : {
      "stop_francais": {
        "stopwords": [
          "_french_", "a"
        ],
        "type": "stop" ,
        "remove_trailing": false
      },
      "substring" : {
        "type" : "nGram",
        "min_gram" : 1,
        "max_gram"  : 40
      }
    },
    "char_filter" : {
      "my_mapping" : {
        "type" : "mapping",
        "mappings" : ["&=>et", "+=>plus", "-=>\\u0020"]
      }
    }
  }
}
```

* PUT test/test/_mapping
```javascript
{
  "test": {
    "properties": {
      "name": {
        "type": "string",
        "index": "analyzed",
        "search_analyzer": "ngram_searcher",
        "index_analyzer": "ngram_indexer"
      }
    }
  }
}
```

* PUT test/test/1
```javascript
{
  "id": 1,
  "name" : "part de reve"
}
```

* GET test/test/_search
```javascript
{
  "from": 0,
  "size": 10,
  "query": {
    "query_string": {
      "query": "part de reve",
      "default_field": "name",
      "default_operator": "and"
    }
  }
}
```

==> it does not return the inserted record.
(use "part reve" as query string and it returns the inserted record)

**Comment by clintongormley** [comment]
Hi @MarneusCalgarXP 

The problem is a result of the combination of the `query_string` query with the `remove_trailing` option in the stop filter.  Because the `query_string` query supports its own mini-language, it parses the query string by consuming each token separately.

The result is that `part`, `de`, and `reve` are each passed to the analyzer separately, so the stopwords filter sees `de` as the last token in the stream, and doesn't remove it because you've set `remove_trailing` to false. This is the same problem that exists when using multi-word synonyms with the query string query... it never recognises them as synonyms.

If you use the `match` query instead, then it will analyze your query string as you expect.

One thing that surprises me is that the `simple_query_string` behaves in the same way, including `de` in the list of tokens to search for.  As far as I know, this query is supposed to consume as much continuous text as possible.  @dakrone @jdconrad any ideas here?

(Btw, @MarneusCalgarXP:  you really don't want to use min/max ngrams 1..40 - your index will simply blow up.  This is not the same as using edge_ngrams. With ngrams you probably want a range more like 2..4 max.)

**Comment by jdconrad** [comment]
simple_query_string gets passed into Lucene's SimpleQueryParser.  SimpleQueryParser will, by default, tokenize on whitespace.  Each token is then passed into the field's analyzer as @clintongormley mentioned.  Whitespace tokenization can be turned off in SimpleQueryParser, in which case the entirety of the string would be passed to the analyzer.  How the analyzer actually handles it depends on which analyzer is being used.  For this single case, I believe you would get the behavior you're looking for if whitespace tokenization is turned off.

**Comment by clintongormley** [comment]
thanks @jdconrad - i'm wondering if we should turn whitespace tokenization off by default?

**Comment by jdconrad** [comment]
I don't know enough about the typical analyzers to know if that solution would work well.  Unexpected behavior may result from something like the following:
x | y
where "x " and " y" end up becoming terms that get passed in.

**Comment by clintongormley** [comment]
ah right, in the case of keyword tokenizers... i see what you mean.  

Pants!

**Comment by MarneusCalgarXP** [comment]
OK, I tested, it seems to work with a match query.
Thank you all for explanations !
