### ISSUE TITLE
Internal error when indexing,[all instances of a given field name must have the same term vectors settings 

### ISSUE THREAD

**Issue by blablatruc** [elastic/elasticsearch#11413]
Hi, 

We have discovered this problem while trying to upgrade from es version 1.2.3 to the latest version. 1.5.2. The same problem occurs in the version 1.3.0 and any version after that one.

To reproduce the problem execute: 

curl -XPUT 'http://localhost:9200/test/' -d '
 {
   "mappings": {
     "test": {
       "_source": {
         "enabled": false
       },
       "properties": {
         "subject": {
           "type": "multi_field",
           "fields": {
             "subject": {
               "type": "string",
               "term_vector": "with_positions_offsets"
             },
             "subject_english_stemmer": {
               "type": "string",
               "term_vector": "with_positions_offsets"
             }
           }
         }
       }
     }
   }
 }'

The error appears when starting to index the field:
 curl -XPUT 'http://localhost:9200/test/test/1' -d '
 {
 "subject":"this is test subject",
  "subject.subject_english_stemmer": "this is test subject"
}'
 
{"error":"IllegalArgumentException[all instances of a given field name must have the same term vectors settings (storeTermVectors changed for field=\"subject.subject_english_stemmer\")]","status":500}

It seems that the problem has started when es was updated to lucence 4.9.0:
https://lucene.apache.org/core/4_9_0/changes/Changes.html#v4.9.0.bug_fixes

So what is the workaround in this case? We can not change the mapping because we have a lot of indices and data.

**Comment by clintongormley** [comment]
Hi @blablatruc 

i'm afraid that the only solution is to reindex your data.  Fields with the same name in different types in the same index are backed by the same Lucene field internally.  Having inconsistent data written to the same Lucene field can result in corruption.

In 2.0 we're getting a lot stricter about this limitation because too many people have suffered the consequences (see #8870).  I'm sorry that I can't give you an easier fix, but it is the correct way to progress.
