### ISSUE TITLE
Index Corrupted when upgrading from Java7u67 to Java7u80

### ISSUE THREAD

**Issue by marcelog** [elastic/elasticsearch#11439]
Hi guys,

I decided to open an issue here to see if this might be an issue that is affecting more people or just us. Everything is described here: [https://discuss.elastic.co/t/how-safe-is-java7-update-80-with-es-1-4-x/1380](https://discuss.elastic.co/t/how-safe-is-java7-update-80-with-es-1-4-x/1380) but I'll reproduce the text anyway for your convenience.

I'm planning on upgrading from Java7 u67 to u80, due to the fix for the upcoming leap second.

Today just tried shutting down all the nodes (3 in total, 2 with data, 1 just to route searches) and upgrading one of the data nodes to JRE7u80 (this was the only online node, just to be safe). It came up with index corrupted errors (note that everything was working flawlessly until the upgrade):

> {"message":"[elastic2-west02] [index_2015_05_v1][3] sending failed shard for [index_2015_05_v1][3], node[Yx684lX3SC6uoD_yT0d5Tw], [P], s[INITIALIZING], indexUUID [UqUZW7iXTqez4M5nReZH1Q], reason [Failed to start shard, message [IndexShardGatewayRecoveryException[[index_2015_05_v1][3] failed to fetch index version after copying it over]; nested: CorruptIndexException[[index_2015_05_v1][3] Preexisting corrupted index [corrupted_UXeWPgF7Qn61i2_qi9gkJw] caused by: CorruptIndexException[Invalid fieldsStream maxPointer (file truncated?): maxPointer=102522365, length=40370176]\norg.apache.lucene.index.CorruptIndexException: Invalid fieldsStream maxPointer (file truncated?): maxPointer=102522365, length=40370176\n\tat org.apache.lucene.codecs.compressing.CompressingStoredFieldsReader.(CompressingStoredFieldsReader.java:135)\n\tat org.apache.lucene.codecs.compressing.CompressingStoredFieldsFormat.fieldsReader(CompressingStoredFieldsFormat.java:113)\n\tat org.apache.lucene.index.SegmentCoreReaders.(SegmentCoreReaders.java:133)\n\tat org.apache.lucene.index.SegmentReader.(SegmentReader.java:108)\n\tat org.apache.lucene.index.ReadersAndUpdates.getReader(ReadersAndUpdates.java:145)\n\tat org.apache.lucene.index.ReadersAndUpdates.getReadOnlyClone(ReadersAndUpdates.java:239)\n\tat org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:104)\n\tat org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:422)\n\tat org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:112)\n\tat org.apache.lucene.search.SearcherManager.(SearcherManager.java:89)\n\tat org.elasticsearch.index.engine.internal.InternalEngine.buildSearchManager(InternalEngine.java:1569)\n\tat org.elasticsearch.index.engine.internal.InternalEngine.start(InternalEngine.java:313)\n\tat org.elasticsearch.index.shard.service.InternalIndexShard.postRecovery(InternalIndexShard.java:710)\n\tat org.elasticsearch.index.gateway.local.LocalIndexShardGateway.recover(LocalIndexShardGateway.java:223)\n\tat org.elasticsearch.index.gateway.IndexShardGatewayService$1.run(IndexShardGatewayService.java:132)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\n\tat java.lang.Thread.run(Unknown Source)\n]; ]]","@version":"1","@timestamp":"2015-05-31T11:57:31.887Z","type":"elasticsearch","host":"x.x.x.x:56107","path":"cluster.action.shard","priority":"WARN","logger_name":"cluster.action.shard","thread":"elasticsearch[elastic2-west02][generic][T#2]","class":"?","file":"?:?","method":"?"}

This is ES 1.4.4 (a couple of months ago we upgraded from 1.3.2 to 1.4.4 without issues) with JRE7u67 (the cluster has been running on this java version since the beginning). The node was upgraded to JRE7u80 and started up isolated from the cluster (all the nodes were down for this test), running on Amazon Linux 3.14.42-31.38.amzn1.x86_64

When we noticed the errors, we shut down the upgraded node and rollbacked the jre upgrade, renamed the data directory (just to have evidence and recreate the data dir from scratch) started the other nodes that were untouched and then the problematic one. Everything went back to JRE7u67, the shards were reallocated successfuly (from the copies in the other data node) and the cluster is now all green and happy... but, without the latest java update.

Anyone with any thoughts/comments?

Thanks!

**Comment by rmuir** [comment]
I am not sure it is related to your JVM upgrade. 1.5 has a number of fixes for file truncation issues, I think that is the root problem, and you just got unlucky in a way that seems to correlate with 7u80.

By the way, if you are concerned about it, why not use 7u79 instead? Its significantly less scary
(http://www.oracle.com/technetwork/java/javase/2col/7u79-bugfixes-2494165.html) versus looking at the list of changes for 7u80 (http://www.oracle.com/technetwork/java/javase/2col/7u80-bugfixes-2494167.html). Basically just timezone and security fixes.

**Comment by marcelog** [comment]
Thanks for your reply. We didn't notice that the leap second addition was available in 7u79, nice catch! 

In any case, if I understand correctly: you mean that the files are really corrupted in disk and we didn't notice during all these months? What can trigger this behavior? Sounds scary :)

But really, we didn't have any issues and we do a daily snapshot for all indices, daily queries for the whole month of data (1 index per month), and a lot of writes during each day. And not so long ago we restarted the cluster with the upgrade to 1.4.4 and some operating system updates (a few days later after that), and we never had any errors in the logs (we monitor the cluster with a marvel cluster but also we log the messages to a logstash installation that aggregate all the logs for us).

What would you guys recommend to handle this particular situation and avoid the risk of losing data with a java or ES upgrade? How can we be sure that our current index files are ok or not?

Thanks guys!

**Comment by rmuir** [comment]
> In any case, if I understand correctly: you mean that the files are really corrupted in disk and we didn't notice during all these months? What can trigger this behavior? Sounds scary :)

You can get an idea how things can happen by reviewing the 1.5 release notes (https://www.elastic.co/blog/elasticsearch-1-5-0-released). To me the most important change is that files are transferred in an atomic way on recovery (temp files, then renamed at the end). So if stuff goes wrong, you dont have the chance of a half-baked file sitting there. But there are really a ton of fixes to this kind of stuff there.

I honestly doubt you had corrupted data "all along". That is because the check in question was added in ES 1.2.x (https://issues.apache.org/jira/browse/LUCENE-5617), so the check was happening before you upgraded, too. So I think it likely happened before/after the upgrade? Things are getting shut down, Shards are shuffling around or whatever, stuff gets chatty, more chance for stuff to wrong or have an incomplete file with the old code.

> What would you guys recommend to handle this particular situation and avoid the risk of losing data with a java or ES upgrade? How can we be sure that our current index files are ok or not?

My first recommendation is to use the latest elasticsearch version. Really, a lot of folks here have spent a lot of time on preventing these issues: this kind of stuff has matured a lot and will continue to get better in forthcoming releases. So IMO, if you are worried about safety of your data, prioritize it first by using the latest version, and maybe invite some additional risk of bugs or whatever in features, but its a good tradeoff.

As far as checking the index files: you can always explicitly do full checks with the lucene CheckIndex tool (see https://www.found.no/foundation/dive-into-elasticsearch-storage/#fixing-problematic-shards for some instructions, but please please don't ever use the badly-named *fix* option). So if you want to manually do a check, that is your best option currently. Its also possible for ES to check on startup (`index.shard.check_on_startup`) but this is really slow and resource-hungry.

Going forward its really something you shouldnt need to do: files are fully checked continuously whenever they are "in motion" (e.g. network recovery, merge for indexes being changed, etc). We also have a fair amount of checks happening just on startup, like the one you hit here, which was extended to all files in the index in ES 1.4+. Finally coming in 2.0 there will also be a "reasonable" option `index.shard.check_on_startup=checksum` designed for situations like yours (https://github.com/elastic/elasticsearch/pull/9183), where maybe you want an explicit full check on startup to know your data is ok, after upgrades etc :)

Having an option for an immediate check... its been thrown around before: maybe its a good idea, maybe not. I do have concerns it could could be a trap like `optimize`, leading people to run it across the entire index after every operation or other stuff like that.

**Comment by marcelog** [comment]
That is an amazing reply really, it clarified a lot and I highly appreciate it :) A few final questions then:

1.- Got it. We will try to upgrade to 1.5.2 (latest so far). But just to clarify  this case (and as a final conclusion): you think that this error might just happened while shutting down the node (and not before), and that there is a chance that repeating the process will yield a successful result?

2.- Just out of curiosity: [https://www.elastic.co/guide/en/elasticsearch/hadoop/current/requirements.html] still recommends 7u55. Do you recommend a jvm upgrade to 7u79 or sticking to 7u67 (in our case) is a safer bet? 

3.- Are snapshots stored in a way that can be trusted and safe from corruption? (hardware issues aside). I'm asking this to know if there might be a chance of snapshooting an already corrupted index (i.e: corrupted lucene files), and if there is a chance of losing data in scenarios like this, when using a snapshot to restore data that might have been snapshooted with older ES versions (i.e: older lucene versions).

Thanks again for your time and all the hard work!

**Comment by rmuir** [comment]
> 1.- Got it. We will try to upgrade to 1.5.2 (latest so far). But just to clarify this case (and as a final conclusion): you think that this error might just happened while shutting down the node (and not before), and that there is a chance that repeating the process will yield a successful result?

That is my best guess as to what happened, its the simplest explanation. As far as the chance of it happening, its not clear to me how likely it is, you know if you just got unlucky, but it can happen, which is why folks worked to fix it for 1.5. I definitely think if things are "not moving" when you shut down, you could have probably been just fine and not hit it, so you can at least get lucky.

> 2.- Just out of curiosity: [https://www.elastic.co/guide/en/elasticsearch/hadoop/current/requirements.html] still recommends 7u55. Do you recommend a jvm upgrade to 7u79 or sticking to 7u67 (in our case) is a safer bet?

I don't know any hadoop-specifics of JDK versions (cc @costin). The recommendations page does say "or higher". I think the motivation there was just to avoid index corruption bugs that can happen in versions before 7u55, so 7u79 should be fine.

> 3.- Are snapshots stored in a way that can be trusted and safe from corruption? (hardware issues aside). I'm asking this to know if there might be a chance of snapshooting an already corrupted index (i.e: corrupted lucene files), and if there is a chance of losing data in scenarios like this, when using a snapshot to restore data that might have been snapshooted with older ES versions (i.e: older lucene versions)

Its a good question. See https://github.com/elastic/elasticsearch/issues/5593 where this feature was added for elasticsearch 1.4

**Comment by costin** [comment]
> Just out of curiosity: [https://www.elastic.co/guide/en/elasticsearch/hadoop/current/requirements.html] still recommends 7u55

That's because the documentation belongs to the es-hadoop 2.0.2 and at the time, that was the latest safe JDK version. Hence why it also states 'or higher' - as time goes buy, new releases are published.
The beta documentation has a slightly different [wording](https://www.elastic.co/guide/en/elasticsearch/hadoop/2.1.Beta/requirements.html) pointing to the Elasticsearch [Matrix](https://www.elastic.co/subscriptions/matrix).

Note that most Hadoop distros use JDK 6 or old JDK 7 versions.

Hope this helps,

**Comment by marcelog** [comment]
Thanks guys, will close this one then, and will try to schedule an update to the latest 1.5.x (1.4.4 has been working amazingly well for us, but due to this "episode" we'd like to  avoid any kind of possible "bad luck", as suggested) and only then bump up the java version to 7u79.

I really appreciate all the insights, and useful links to resources :)

Best!

**Comment by marcelog** [comment]
Just wanted to report that we upgraded (not in a rolling upgrade, but shutting down the cluster) to ES 1.5.2 and Java 7u80 and everything went smoothly. Thanks again for your time and help.

Cheers.

**Comment by clintongormley** [comment]
thanks for letting us know @marcelog
