### ISSUE TITLE
Search optimization - Highlighter causes many query rewrites

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#11442]
A user reported very slow performance here https://github.com/elastic/elasticsearch/pull/10391#issuecomment-105466848

The issue is that the query being highlighted does not have its rewritten form cached and consequently is rewritten for every doc x field being highlighted.

**Comment by markharwood** [comment]
A quick attempt to fix this was to cache the query when rewritten for search purposes and share it across all calls to the plain highlighter. This was a massive speed-up for the fuzzy queries in the example https://github.com/elastic/elasticsearch/pull/10391#issuecomment-105466848 but caused our unit tests to fail.
The WeightedSpanTermExtractor used for highlighting requires detailed knowledge of the query on a per-document basis and performs it's own detailed unpacking of the original un-rewritten query to achieve its goals. With my intended change, the unit tests showed that a PrefixQuery that is rewritten for search execution does not highlight correctly because as part of that translation it loses the information in the original query required by WeightedSpanTermExtractor.

It is possible there is an ugly trade-off to be made here between accuracy of highlighter results and the performance costs of rewrites. The solution may not be a simple one but I will dig deeper.

**Comment by javanna** [comment]
Postings highlighter would be a great fix here as it doesn't require rewriting the query and pulls the automata out of the prefix query, I'd give it a try.

**Comment by markharwood** [comment]
Postings Highlighter is demonstrably faster but requires a re-index for many users.
I was wondering about having a "fast-mode" for the plain highlighter that feeds it the re-written query used for search. It is significantly faster for the issue reported (100ms vs 30 seconds) and produces identical results for the fuzzy multi-match in question. What it loses is the ability to highlight certain other types of query (Prefix being one example). I'm not sure how many others there are at this stage.

**Comment by rmuir** [comment]
The other highlighters are definitively broken here.

doing any kind of rewrite at all, against the index, just to highlight a few docs, thats just wrong.

**Comment by markharwood** [comment]
The plain highlighter continuously rewrites against a MemoryIndex from what I can see (but dives off to the main index to look up term doc freqs for weightings used when selecting "best" matches)

**Comment by rmuir** [comment]
> What it loses is the ability to highlight certain other types of query (Prefix being one example).

why not just use the same technique postings highlighter uses for all multitermqueries? IMO the only reasonable way to do it. It has the same runtime whether or not the query rewrites to 100 terms or 100 million terms.  Hint: it does not have anything to do with postings in the offsets!

**Comment by rmuir** [comment]
Why look up docfreqs? PH uses a "constant score" for multitermqueries. It really does not matter. someone highlighting wildcards does not care about ranking for the most part. Same reason they use  constant score execution in lucene for the actual query, too

and sorry, just for the record here. postings highlighter isnt any faster because there is some magic about postings in the offsets. maybe this has some nice locality, but IMO things are faster because it does not do dumb things.

doing dumb things to me includes:
* rewrite()ing against the entire index
* looking up docfreqs against the entire index
* making big datastructures in RAM
* using term vectors

**Comment by rmuir** [comment]
The fast vector impl is the worst. it actually has a Terms/TermsEnum per-document, but rewrites against the whole index anyway... sorry, to me this stuff is hopeless

**Comment by markharwood** [comment]
>Why look up docfreqs?

I'm hazy on this but "plain" highlighter is all based around rewriting the query against a MemoryIndex containing the doc to be highlighted. The "getBestTextFragments" method is a summarizer and has to be aware of the quality of the words found in various fragments of what could be a long field so has to come up with an IDF value using the main index as a source of stats

**Comment by rmuir** [comment]
Using docfreq is definitely broken. Its unrelated to anything at play here.

If you are ranking fragments (lets call them sentences for simplicity), then those sentences are your documents, and each document is your corpus. And you want the top-N sentences... so the measure you need is the number of sentences in the document that match that word.

This is not something thats easy to compute: because sentences usually arent split at index-time, but you can use approximations based on totalTermFreq instead (total # of occurrences in all sentences). This is the "freq" from the postings list in the postingshighlighter impl.

You don't need docfreq across the entire index: totally irrelevant.

**Comment by markharwood** [comment]
It's a question of certainty and related to doc length - if I searched for `totalTermFreq measure` in your last comment I'd only have 4 sentence/documents in my comment/corpus and a docFreq of 1 for both `totalTermFreq` and `measure` but using the full index of all comments would give me more stats/certainty about the relative importance of those 2 terms.
A quality/performance trade-off that depends on the type of content you are dealing with.

It's certainly true to say that the summariser capabilities designed for large fields are fairly pointless to run in scenarios such as the original problem where the fields are very small.

**Comment by rmuir** [comment]
The thing you are missing is, the corpus has "changed", you are just highlighting one document, with the goal to return the top-N sentences/snippets. the other documents at this point are not really comparable (and lots of people have data where docs vary wildly from each other).

Using the other corpus is not just bad, its also slow. So since the corpus is just one doc, use statistics for that one doc.

So yeah, I definitely think postingshighlighter ranks better too. At least it has the basic components for each sentence (term frequency, term importance, length normalization), and just tries to reuse stuff from IR we already know works and not do anything "sheisty" or "creative" like transfer statistics from other documents, that at best are "comparable corpora".

And the ranking is easy to tune to what you want (e.g. ignore length normalization completely, ignore term frequencies completely, or reasonable things in between, etc) with classic BM25 parameters.

**Comment by rmuir** [comment]
also, just being practical, i dont think highlighting selection for "foo fighters" for document A should ever change, because of what happens to other docs (sharding different, merging, adding other docs, whatever). This is confusing to the user.

**Comment by markharwood** [comment]
I do get what you mean - I'm just sceptical about basing any statistical judgements based purely on the tiny amounts of evidence that are available in short docs.

> This is confusing to the user.

Not if you consider we are fundamentally answering the question "why did this doc rank so high?". From a quality perspective, the selections should be as close as possible to representing "what the search engine saw as interesting" in each document. Somewhere in the querying process we have the IDF that was an ingredient in this ranking and so it would be useful if we could retain that. Using an alternative doc-local fragment-ranking system that is light on evidence/stats and deviates from the value judgements that place each doc in a certain position in the rankings is likely to be more misleading.

**Comment by nik9000** [comment]
I have lots of opinions on this but I'm on mobile and tired.

Its worth pointing out that the Experimental highlighter pulls out the
automata for some queries (prefix, fuzzy, Wildcard) but falls back to
rewriting when it doesn't know what to do with the query. Its far from
perfect but it doesn't  put a dent in our performance. It might be a useful
"quick" fix for the mentioned problem because it doesn't need a reindex.
Just a restart to install it.

I totally filed an issue years ago about wildcard query being slow with the
plain highlighter.

Nik

**Comment by markharwood** [comment]
@nik9000 for the record, the experimental highlighter was fast on the example problem and produced equivalent results. I see it has a bundle of useful options to play with too. Very interesting!

**Comment by markharwood** [comment]
Closing this - the rewrite operation is an integral part of the design of the plain highlighter (or at least the WeightedSpanTermExtractor that is used to implement "best fragment" decisions). While suitable for some use cases it is inappropriate for use cases where many small fields are being highlighted in large numbers of documents.
The Experimental highlighter plugin Nik linked to looks very promising.

**Comment by jeantil** [comment]
@nik9000 just out of curiosity, is the "experimental" highlighter now considered `production ready` ?

thanks

**Comment by nik9000** [comment]
It's been in production at WMF, my old job for over a year now. It's
serving millions of diverse requests a day without any problem. But its not
an elastic supported plugin. I keep bringing it up because I wrote it. I'm
sorry to make things complicated!

I honestly don't know what the future holds for the plugin.

**Comment by jeantil** [comment]
@nik9000 thanks for your answer I'll have a look again :)
