### ISSUE TITLE
TransportClient issues with nested calls

### ISSUE THREAD

**Issue by frstie** [elastic/elasticsearch#11467]
This is a similar issue to #10766 but we've attached a test case that demonstrates it happening.

In our case we are running a search in ES and then caching the results of the search back into ES. As in the referenced case we are indexing the cached result in the ActionListener for the search results.

We've put together a very simple test case to replicate this. It's fine for a single run, but increasing the number of runs results in problems.

Under ES 1.4.5 with 10 parallel runs it seems to just hang altogether in most cases. Under ES 1.5.2 the test completes in about 40 secs but we have one or more "transport stopped" exceptions being thrown in the failure handler. In each case ES is running as a vanilla install on the same machine as the tests are running.

https://gist.github.com/frstie/75c04d85d93fff8a0738

We're not sure whether these results are expected - would be great to hear any suggestions or feedback!

**Comment by clintongormley** [comment]
Related to #10766, #10704, #10644 

@spinscale any thoughts here?

**Comment by spinscale** [comment]
@frstie can you retry running the same test, but ensure that the you do not use the calling thread for the listener by changing your search request builder call to

```java
SearchRequestBuilder searchRequest = internalCluster().transportClient().prepareSearch().setListenerThreaded(true);
```

**Comment by frstie** [comment]
Hi @spinscale  - adding that in sorts out the problem nicely. Still get a handful of "transport stopped" exceptions when ~ 50 concurrent requests but that's probably just a capacity issue.

Thinking about it this makes sense in our case, particularly since we are using vertx and want to make sure there is minimum blocking on the calling thread.

Are there any cases when we explicitly _wouldn't_ want to use setListenerThreaded() since it seems to me that it would be a sensible default for our use cases?

**Comment by frstie** [comment]
I (and my colleague) also read it the wrong way around when reading the javadoc about setListenerThreaded() - I think we assumed it would be using a different thread by default and setting the property would have the opposite effect.

**Comment by spinscale** [comment]
Just a word of warning: Setting this property means, that the action listener is run in the `listener` threadpool. By default this threadpool is `fixed` and does not have a queue, see [threadpool docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-threadpool.html). The assumption is still that your task is kinda lightweight, so you shouldnt block in that threadpool either (which is simple in your example as you wait for the future instead of applying another listener).

Elasticsearch 2.0 will solve this by indeed changing the default for the transportclient to do the right thing, see https://github.com/elastic/elasticsearch/pull/10940

**Comment by frstie** [comment]
Thanks. That all makes sense. Hopefully this will help other people with the same issue. Feel free to close the case if you like.

**Comment by clintongormley** [comment]
thanks @frstie, closing
