### ISSUE TITLE
rename TokenFilters to Transformers

### ISSUE THREAD

**Issue by mehulkar** [elastic/elasticsearch#11462]
Or anything else. This is a larger discussion (if there's a more appropriate place to have it, I'm happy to start it there). 

TokenFilters don't convey anything to me and they sound too similar to Tokenizers. And they don't filter search results (which is what I'm thinking of when I think filtering). 

From what I understand, TokenFilters are used to _transform_ tokens. So Transformer sounds like a better name.

**Comment by rmuir** [comment]
I dont think Transformers is a compelling enough name to go thru the process of renaming TokenFilters. They have had this name for over 15 years! This is definitely the first time i've ever heard anyone complain about the name. Despite growing up in the 1980's, "Transformers" makes me think of shitty movies.

**Comment by clintongormley** [comment]
I've got to agree with @rmuir here.  Tokenizers convert strings into a stream of tokens.  Each token filter is then applied to the token stream in turn, adding, removing, or changing tokens in the stream.

There is an overlap between tokenizers and token filters (eg ngram tokenizer vs ngram token filter), so giving them completely different names would impede understanding instead of helping it. 

The token filters name also fits nicely with the character filters name (they filter characters before tokenizing).

Nobody understands the analysis process until they read through the documentation to understand what happens in each part of the process, so I'm comfortable with keeping the current names and just relying on the explanations that we provide.
