### ISSUE TITLE
ESQL: STATS BY expression not working with expression from EVAL

### ISSUE THREAD

**Issue by alex-spies** [elastic/elasticsearch#114714]
`FROM employees | eval x = [1,2,3], y = 5 + 6 | stats by y + 1` or `FROM employees | eval x = [1,2,3], y = 5 + 6 | stats by yy = y + 1` currently return 0 rows, even though using expressions in the `by` clause works fine if they use only fields that are present in the index. Using `by` clauses composed from both index fields and eval fields seems to work, too, like `FROM test | eval x = [1,2,3], y = 5 + 6 | stats by yy = y + a`.

**Comment by alex-spies** [comment]
I think the problem may be in either `SkipQueryOnEmptyMappings` or in `PropagateEmptyRelation`; that's from the optimizer passes:

```
Query: FROM test | eval x = [1,2,3], y = 5 + 6 | stats by y + 1

[2024-10-14T14:49:39,880][INFO ][o.e.x.e.o.LogicalPlanOptimizer] [runTask-0] Rule logical.SkipQueryOnEmptyMappings applied
Limit[1000[INTEGER]]                                                = Limit[1000[INTEGER]]
\_Aggregate[STANDARD,[y + 1{r}#41],[y + 1{r}#41]]                   = \_Aggregate[STANDARD,[y + 1{r}#41],[y + 1{r}#41]]
  \_Eval[[y{r}#39 + 1[INTEGER] AS y + 1]]                           =   \_Eval[[y{r}#39 + 1[INTEGER] AS y + 1]]
    \_Eval[[[1, 2, 3][INTEGER] AS x, 5[INTEGER] + 6[INTEGER] AS y]] =     \_Eval[[[1, 2, 3][INTEGER] AS x, 5[INTEGER] + 6[INTEGER] AS y]]
      \_EsRelation[test][<no-fields>{r$}#10]                        !       \_LocalRelation[[<no-fields>{r$}#10],EMPTY]
                                                                   
[2024-10-14T14:49:39,880][INFO ][o.e.x.e.o.LogicalPlanOptimizer] [runTask-0] Rule logical.CombineEvals applied
Limit[1000[INTEGER]]                                                = Limit[1000[INTEGER]]
\_Aggregate[STANDARD,[y + 1{r}#41],[y + 1{r}#41]]                   = \_Aggregate[STANDARD,[y + 1{r}#41],[y + 1{r}#41]]
  \_Eval[[y{r}#39 + 1[INTEGER] AS y + 1]]                           !   \_Eval[[[1, 2, 3][INTEGER] AS x, 5[INTEGER] + 6[INTEGER] AS y, y{r}#39 + 1[INTEGER] AS y + 1]]
    \_Eval[[[1, 2, 3][INTEGER] AS x, 5[INTEGER] + 6[INTEGER] AS y]] !     \_LocalRelation[[<no-fields>{r$}#10],EMPTY]
      \_LocalRelation[[<no-fields>{r$}#10],EMPTY]                   ! 
                                                                   
[2024-10-14T14:49:39,880][INFO ][o.e.x.e.o.LogicalPlanOptimizer] [runTask-0] Rule logical.PropagateEmptyRelation applied
Limit[1000[INTEGER]]                                                                             = Limit[1000[INTEGER]]
\_Aggregate[STANDARD,[y + 1{r}#41],[y + 1{r}#41]]                                                = \_Aggregate[STANDARD,[y + 1{r}#41],[y + 1{r}#41]]
  \_Eval[[[1, 2, 3][INTEGER] AS x, 5[INTEGER] + 6[INTEGER] AS y, y{r}#39 + 1[INTEGER] AS y + 1]] !   \_LocalRelation[[<no-fields>{r$}#10, x{r}#37, y{r}#39, y + 1{r}#41],EMPTY]
    \_LocalRelation[[<no-fields>{r$}#10],EMPTY]                                                  ! 
                                                                                                
[2024-10-14T14:49:39,880][INFO ][o.e.x.e.o.LogicalPlanOptimizer] [runTask-0] Rule logical.PropagateEmptyRelation applied
Limit[1000[INTEGER]]                                                         = Limit[1000[INTEGER]]
\_Aggregate[STANDARD,[y + 1{r}#41],[y + 1{r}#41]]                            ! \_LocalRelation[[y + 1{r}#41],EMPTY]
  \_LocalRelation[[<no-fields>{r$}#10, x{r}#37, y{r}#39, y + 1{r}#41],EMPTY] ! 
```
We seem to end up with an empty local relation - but we should have 1 row instead.

**Comment by luigidellaquila** [comment]
At a first look, the problem seems to be at a lower level, in the IndexResolver. 
In a query with `STATS by y` the EsIndex has one concrete index, while in a query with `STATS by y + 1` the EsIndex has no concrete indices, so `SkipQueryOnEmptyMappings` replaces it with a `LocalRelation`.

Digging a bit deeper, I see that the real difference is in `Aggregate.computeReferences()`: 
- for `STATS by y` it only returns `y`as an UnresolvedAttribute
- for `STATS by y + 1` it returns `y`, but also `y + 1`, the implicit - artificial aggregate of the STATS (that internally looks like `STATS y + 1 by y + 1`). 

In the first case, `y` gets removed later, and to make things work we add `_index` field to make the field_caps work.
In the second case, `y` gets removed, but not `y + 1`, so we don't add `_index`, but since `y + 1` does't match any fields in the schema, `field_caps` returns an empty list of indices.

A simple solution (and IMHO correct) could be to remove these implicit aggregates from `Aggregate.computeReferences()`
cc @alex-spies @astefan

**Comment by ivancea** [comment]
Reopening, as the bug still occurs when there's a command using the grouping attribute alias after the aggregation.
Like:
```
FROM test
| EVAL y = \"a\"
| STATS COUNT() BY x=y
| SORT x
```
This will return no rows.

Remove the alias, and it will work, like:
```
FROM test
| EVAL y = \"a\"
| STATS COUNT() BY y
| SORT y
```
