### ISSUE TITLE
Failure when adding the 'date' filter on logstash

### ISSUE THREAD

**Issue by refaelos** [elastic/elasticsearch#11492]
Hey,

What i'm doing is loading TONS of events from S3 into ES (100s of millions) at once using logstash.

The problem is that when I add the filter:
```
  date {
    match => [ "server_time", "UNIX" ]
  }
```
Logstash fails with multiple warnings:
```
{:timestamp=>"2015-06-03T19:59:30.118000+0000", :message=>"retrying failed action with response code: 429", :level=>:warn}
```
And then with errors:
```
{:timestamp=>"2015-06-03T20:02:31.123900+0000", :message=>"too many attempts at sending event. dropping: 2015-05-19T12:10:57.722Z %{host} ...}
```

When I remove the 'date' filter, it works great BUT I only get one index created (for today). I want to have multiple indices for the events' dates.

I found out that when I reduce the 'flush_size' of logstash things work fine but getting data into ES like this is extremely slow.

Another thing I found later is that when I set the following config to elasticsearch:

```
threadpool.search.type: fixed
threadpool.search.size: 20
threadpool.search.queue_size: 100

threadpool.bulk.type: fixed
threadpool.bulk.size: 60
threadpool.bulk.queue_size: 500

threadpool.index.type: fixed
threadpool.index.size: 20
threadpool.index.queue_size: 100

indices.memory.index_buffer_size: 30%
indices.memory.min_shard_index_buffer_size: 12mb
indices.memory.min_index_buffer_size: 96mb


indices.fielddata.cache.size: 15%
indices.fielddata.cache.expire: 6h
indices.cache.filter.size: 15%
indices.cache.filter.expire: 6h

index.refresh_interval: 30s
index.translog.flush_threshold_ops: 50000
```
I can raise the bulk size to 1000 and everything works but the machine gets stuck and things are REALLY slow.

Any help will be greatly appreciated ... :pray:

**Comment by clintongormley** [comment]
HI @refaelos 

I'm afraid I don't really understand what you're doing - other than mentioning the date filter, I have no idea what data you're sending to Elasticsearch, what your expected outcome is, or even what hardware you're running this on.  Really this feels like a logstash configuration issue, rather than a problem with Elasticsearch. 

I'd ask on the forums instead: https://discuss.elastic.co/c/logstash or https://discuss.elastic.co/c/elasticsearch

One thing for sure: you don't want to be setting the bulk threads this high - that's just going to put a lot of extra load on the system.  Setting thread pool config is a very expert option, you can easily break things if you set them incorrectly.

**Comment by refaelos** [comment]
Thanks man!

I'll put the question on the forum and explain some more about the infrastructure and the data.

**Comment by refaelos** [comment]
Posted it there: https://discuss.elastic.co/t/one-vs-multiple-indices-on-es-using-lss-date-filter

Will be great if you can help.
