### ISSUE TITLE
ES|QL: Alias collisions in STATS

### ISSUE THREAD

**Issue by luigidellaquila** [elastic/elasticsearch#114970]
```
row x = 1, y = 2 | stats y = max(x) by y
```

In this case, STATS cannot return both the aggregate `y = max(x)` and the grouping `y`, because they have the same alias.

Surprisingly, it returns the grouping:

```
       y       
---------------
2              
```

Not sure if a query like this should be invalid, but if it's valid, the aggregate is probably more relevant.

I'm labeling it as a bug, but I'm not completely sure.

**Comment by luigidellaquila** [comment]
Same for 

```
row x = 1, `max(x)` = 2 | stats max(x) by `max(x)`
```

```
    max(x)     
---------------
2              
```

**Comment by alex-spies** [comment]
Hm, I agree that the behavior can be unexpected, but I don't know if this can be improved. I don't think it's a bug in the implementation.

Currently, we just go left-to-right over all expressions in the `STATS` and duplicate names get shadowed by expressions further to the right.

```
row x = 1, y = 2 | stats y = max(x) by y
```
It's reasonable to assume that this will return 2 columns, and in this case it's not even ambiguous what they should be: `by y` can only refer to the `y` defined in the `row` command.

But we cannot have 2 columns with the same name in the output of the command, so we can return either the `y = max(x)` or the `y` from `by y`.

```
row x = 1, `max(x)` = 2 | stats max(x) by `max(x)`
```
This has the same problem.

Since shadowing doesn't really add value to the `STATS` command, it'd be reasonable to consider such queries simply invalid. But we can't fail them now as this would be breaking bwc.

We can send a warning though as users probably didn't want to write such a query in the first place.
