### ISSUE TITLE
[Bug] SameShardAllocationDecider does not correctly determine hosts

### ISSUE THREAD

**Issue by umairmufti** [elastic/elasticsearch#11490]
The SameShardAllocationDecider attempts to prevent multiple instances of the same shard from being allocated to the same node. Nodes are identified by their IPs and hostnames. If _either_ the IPs match _or_ the hostnames match, the nodes are determined to be the same. 

The current logic is incorrect. At a minimum, _both_ hostnames _and_ IPs should match. Consider when ES is running inside of Docker and containers on different physical hosts receive the same IP address.

**Comment by jpountz** [comment]
If you are reporting this issue, I assume that you already set `cluster.routing.allocation.same_shard.host` to `true`, otherwise elasticsearch does not try to avoid allocating shards twice on the same node.

Then it's true that elasticsearch checks for either the same IP or host. If you want to have something better, I would recommend on setting attributes on each container and then using forced awareness to force elasticsearch to not allocate twice the same shard on containers that are hosted on the same machine. https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-cluster.html#forced-awareness

**Comment by clintongormley** [comment]
@jpountz Docker creates a private subnet, so two docker instances running on different hardware can indeed have the same IP address.  So the question for me is: would this change break the same_shard behaviour in other scenarios, eg with VMs?  I think it probably would as VMs on the same machine may well have different IPs.

**Comment by umairmufti** [comment]
The proposed change is to bring the code in accordance with the documentation. Specifically, the documentation states that hostname _and_ IP address are checked to determine the host.
 
Moreover, the following cases exist:
1. Nodes running on the same host with different IP addresses and different hostnames
2. Nodes running on the same host with different IP addresses but same hostnames
3. Nodes running on the same host with same IP addresses but different hostnames
4. Nodes running on the same host with same IP addresses and same hostnames
5. Nodes running on the different hosts with different IP addresses and different hostnames
6. Nodes running on the different hosts with different IP addresses but same hostnames
7. Nodes running on the different hosts with same IP addresses but different hostnames
8. Nodes running on the different hosts with same IP addresses and same hostnames

Checking against only IP _or_ hostname produces a false negative in case 1; and, false positives in cases 6, 7, and 8.
Checking against both IP _and_ hostname produces a false negative in case 1; and, a false positive in case 8.
 
The cost of the false positives is to prevent shards from being relocated, thereby increasing the risk of data loss. In our case, it was exactly case 7 that caused all of our shards to end up on a single host as all 5 nodes were assigned the same IP (but different hostnames) by Docker.

**Comment by umairmufti** [comment]
Any update on this issue?

**Comment by dakrone** [comment]
>  So the question for me is: would this change break the same_shard behaviour
>  in other scenarios, eg with VMs? I think it probably would as VMs on the same
>  machine may well have different IPs.

Wouldn't VMs have different host names though, so I don't think changing this
would break anything? (ie, VMs have different host names and different IPs, so a
user would still have to use allocation awareness for it)

@clintongormley I think we should make this change or at least make it configurable, do you have a preference?

**Comment by ywelsch** [comment]
@dakrone Requiring matching IPs **and** matching hostnames breaks other use cases. For example running multiple Elasticsearch instances on one host but binding each of them to a different network interface.

Maybe we can generalize `SameShardAllocationDecider` to make the conditions on which it checks "sameness" configurable (potentially allowing custom node attributes). What do you think?

**Comment by dakrone** [comment]
@ywelsch yeah, I think generalizing the conditions and potentially making them configurable (I don't think we should use custom node attributes, we already have an allocation decider for that) would be a good idea.

**Comment by javanna** [comment]
@ywelsch @dakrone does anything need further discussion here? Or shall we label adoptme?

**Comment by ywelsch** [comment]
@javanna I've changed the labels

**Comment by DaveCTurner** [comment]
This is an interesting idea, but since its opening we have not seen enough feedback that it is something we should work on. We prefer to close this issue as a clear indication that we are not going to work on this at this time. We are always open to reconsidering this in the future based on compelling feedback; despite this issue being closed please feel free to leave feedback (including +1s).
