### ISSUE TITLE
Boolean settings parsing should not be lenient

### ISSUE THREAD

**Issue by mikemccand** [elastic/elasticsearch#11503]
Spinoff from #11437.

Today, most boolean settings in Elasticsearch are parsed leniently
using `Booleans.parseBoolean`, which interprets `0`, `no`, `off` and `false`
as `false`, else `true` for any random strings like `NO` or `OFF` or `foobar`, etc.

I think this is dangerous: if the user has a typo for false, or maybe
thinks "disabled" would also mean false, they silently get true.

I think we should parse boolean settings strictly, maybe using this
awesome project: https://github.com/rmuir/booleanparser so that the
user gets a clear exception stating that the value is not recognized.

Unfortunately this is a biggish project ... I think we'd need to take
a similar approach to #11437, where for back compat if we see
un-parseable boolean settings from persisted places (cluster, index
settings), we dynamically map them to true and log a warning.

**Comment by rjernst** [comment]
+1 to being strict. Could we limit to only true/false like booleanparser (i'm all for using it!), and do "backcompat" based on index created version?

**Comment by clintongormley** [comment]
There are languages, such as Perl, which don't have boolean values.  This is the reason that boolean parsing in Elasticsearch is lenient.

I think it is OK to be lenient (as in have multiple ways of expressing true and false) but then to throw an exception if an unrecognised value is provided, eg:

* False: `false`, `0`, `"false"`, `"0"` 
* True: `true`, `"true"", `1`, `"1"`

I believe that `no`, `yes`, `on`, `off`, etc are supported because of the YAML spec: http://yaml.org/type/bool.html

**Comment by clintongormley** [comment]
To be clear, my comment applies to values passed through the REST API, as opposed to settings in a config file

**Comment by rmuir** [comment]
Finally an issue worth discussing :)

I think we should have so-called "strict" boolean parsing, because we can assume what we are doing is actually important. When things aren't important e.g. `do you want another beer?`, then lenient parsing of booleans is just fine: you can default to `true` and nothing will go wrong!

So the context is critical: here we are talking about situations such as parameter configuration for a distributed system that might hold terabytes of data, and input parameters to APIs that might be connected to even larger systems doing god knows what.

This is just the assumption you must make with code: in general computers are used for important things these days, so that's why I think everyone should use boolean parsing that doesn't suck. 

Let's just make this clear and unambiguous to prevent problems: it's easy!

> Today, most boolean settings in Elasticsearch are parsed leniently
> using Booleans.parseBoolean, which interprets 0, no, off and false
> as false, else true for any random strings like NO or OFF or foobar, etc.

Terrible

> I think this is dangerous: if the user has a typo for false, or maybe
> thinks "disabled" would also mean false, they silently get true.

Its dangerous for a ton of other reasons too, for example its inconsistent with java's equally crappy `Boolean.parseBoolean` which instead maps unknown values to `false`. This is just asking for bugs.

> There are languages, such as Perl, which don't have boolean values. This is the reason that boolean parsing in Elasticsearch is lenient.

Perl has the worst boolean semantics on the planet:

    The number 0, the strings '0' and '', the empty list "()", and "undef"
    are all false in a boolean context. All other values are true.
    Negation of a true value by "!" or "not" returns a special false
    value. When evaluated as a string it is treated as '', but as a 
    number, it is treated as 0.

Somehow they managed to actually make it worse than C. 

This doesn't mean we should map all non-zero numbers to `true`, or do other crazy things because of language X or Y or Z. Seriously, why can't we just supply simple unambiguous interfaces and let the Perl language client deal with making it "perl-like" on the client-side? That's its job.

Trying to do this stuff server-side just begs for complexity and bugs. Which numbers are acceptable? Maybe we should apply unicode normalization so that full-width numbers work? What about ideographic numbers? We can bring in ICU to parse chinese numbers. Some writing systems might not have a concept of zero, what to do there? 

Screw that. In most cases we expect these configuration values to be important, and the API to be used as an important interface for the application. Communication here should be clear, simple, and unambiguous. We can do this, and just transcend the language problem the same way we'd solve this in the physical world. What is the best way there? Something like this works surprisingly well:

    Nod your head for `yes`, shake for `no`, anything else and I'll punch you in the face.

We can translate that directly into java code, by parsing "true" to `true` and "false" to `false`, with anything else as an exception. In Java, its important declare a checked exception like `ParseException` too, so that you inform the caller of the "rules", and so that the flow of their code is forced to deal with the exceptional case. I generally hate checked exceptions like anyone else, but when used sparingly as a tool to prevent bugs, they do have their place.

> I believe that no, yes, on, off, etc are supported because of the YAML spec: http://yaml.org/type/bool.html

This doesn't mean we have to allow them. There are other things in the YAML spec we may not allow too. This isn't inconsistent, its the same as YAML only allowing certain whitespace characters, despite requiring a Unicode text encoding. They don't have to allow all Unicode whitespace just because Unicode defines whitespace in a certain way.

If we think the boolean settings being parsed are all unimportant, then by all means, stick with a crappy lenient parser. Otherwise we should really fix this everywhere.

**Comment by uboness** [comment]
@rmuir I love your boolean parser, a piece of art... and love the copyrights on it too. I'm cool with stricter parsing, but only if we keep `42` to represent `maybe`!

+1 for `"true"` & `"false"`

**Comment by dadoonet** [comment]
Hahaha! I'd love to see in our code base:

```java
if (str.equals("42")) {
  return randomBoolean();
}
```

Like an easter egg...

Totally +1 to either reject any unknown form and never fall back to `true`.
`true` and `false` makes sense to me.

In that case, may the upgrade plugin should try to detect "old settings" and warn the user to change their values? I guess it's hard to build that as this plugin does not read for example `elasticsearch.yml` file?
Also, how to know that users have been using in their data `something` which is translated to `true`?
So what would happen if someone tries to reindex the same doc again (eg. update it by script)?

**Comment by saurajeet** [comment]
thanks @jpountz for taking time to find the right place for the issue i filed. 
+1 for "true" or "false" in stricter parsing.

**Comment by rjernst** [comment]
I started a branch here:
https://github.com/rjernst/elasticsearch/tree/booleans_are_simple

But there are many tests that need to be fixed. Anyone feel free to pick it up and base future work on.

**Comment by clintongormley** [comment]
Fixed in 5.0 with the great settings rewrite
