### ISSUE TITLE
Improve exception message when failing to parse an out-of-range number

### ISSUE THREAD

**Issue by SoniaSanzV** [elastic/elasticsearch#115080]
## Summary
When some user tries to create a remote cluster and enters a number of node connections that is too large, the request fails but the information that is returned to the user is not too helpful. 

### Expected result
The server side returns an error message that is explanatory and specifies that the number of node connections is larger than supported. 

### Actual result
The actual message only says that the request failed but it doesn't explain why.
![Image](https://github.com/user-attachments/assets/864eeb2b-88a4-414c-82af-513c7df17c39)

**Comment by DaveCTurner** [comment]
I think this is a general problem with numeric settings, rather than anything specific to remote clusters. While it's certainly true that `2147483648` cannot be parsed as an `Integer`, from the user's point of view this is conceptually quite different from failing to parse something `not_even_numeric`.
