### ISSUE TITLE
for fields with numeric type 'byte', elasticsearch accepts values greater than 127 and indexes them wrongly

### ISSUE THREAD

**Issue by passing** [elastic/elasticsearch#11513]
using elasticsearch 1.5.2 I can index values greater than 127 for a byte field without getting any error. The values just overflow internally and the resulting numbers can be searched for.
e.g. indexing 250 ends up as -6
indexing 260 ends up as 4

```
curl -XPUT localhost:9200/test -d '
{
    "mappings" : {
        "foo" : {
            "properties" : {
                "field1" : { "type" : "byte" }
            }
        }
    }
}'

curl -XPUT localhost:9200/test/foo/one -d '
{
  "field1" : 127
}'

curl -XPUT localhost:9200/test/foo/two -d '
{
  "field1" : 250
}'

curl -XPUT localhost:9200/test/foo/three -d '
{
  "field1" : 260
}'
```

now searching like this...
```
curl -XGET localhost:9200/test/_search?search_type=count -d '
{
    "aggs" : {
        "values" : {
            "terms" : { "field" : "field1" }
        }
    }
}'
```

returns the following resultset
```
{
   "took": 3,
   "timed_out": false,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   },
   "hits": {
      "total": 3,
      "max_score": 0,
      "hits": []
   },
   "aggregations": {
      "values": {
         "doc_count_error_upper_bound": 0,
         "sum_other_doc_count": 0,
         "buckets": [
            {
               "key": -6,
               "doc_count": 1
            },
            {
               "key": 4,
               "doc_count": 1
            },
            {
               "key": 127,
               "doc_count": 1
            }
         ]
      }
   }
}
```

trying the same with a 'short' number, you get an error message for document 'two'
```
curl -XPUT localhost:9200/test -d '
{
    "mappings" : {
        "foo" : {
            "properties" : {
                "field1" : { "type" : "short" }
            }
        }
    }
}'


curl -XPUT localhost:9200/test/foo/one -d '
{
  "field1" : 31000
}'

curl -XPUT localhost:9200/test/foo/two -d '
{
  "field1" : 33000
}'
```

```
{
   "error": "RemoteTransportException[[dev-test-mon-es-02][inet[/192.168.110.83:9300]][indices:data/write/index]]; nested: MapperParsingException[failed to parse [field1]]; nested: JsonParseException[Numeric value (33000) out of range of Java short\n at [Source: UNKNOWN; line: 2, column: 19]]; ",
   "status": 400
}
```

**Comment by clintongormley** [comment]
Even with  `coerce:false`, the out-of-range byte value doesn't fail, and the short shouldn't fail with `coerce:true`, but does...

**Comment by szroland** [comment]
Fields mapped as byte actually get read as short and then cast to byte. E.g. if you map the field as byte and send in the 33000 value, you get the same error (e.g. out of range for **short**), e.g.:

	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.shortValue(AbstractXContentParser.java:108)
	at org.elasticsearch.index.mapper.core.ByteFieldMapper.innerParseCreateField(ByteFieldMapper.java:289)

For consistency, `AbstractXContentParser.byteValue()` method could be created that ultimately could call `JsonParser.getByteValue()`, which does include byte range check, assuming this behavior of the range check in the parser is desired. However, this is why coerce has no effect.

Coerce works converting String values, but not for down-casting numeric values for short/byte fields, since the range check is in JsonParser in the latter case, e.g. `ensureNumberConversion()` is too late, the parser will have thrown the exception by then if the incoming value is numeric.

JsonParser only checks range for short and byte (e.g. not for int). So an approach could be to always parse the value as int and then cast down for short/byte fields. `ensureNumberConversion()` would then ensure range enforcement as needed. I think this approach would be more consistent overall than relying on `JsonParser.getShortValue()`/`JsonParser.getByteValue()` for short/byte, and `ensureNumberConversion()` for int/float range check.

If you agree, I can implement this.

Coerce documentations also doesn't explicitly mention the behavior of casting down, it only mentions truncating fractions, which is not exactly the same thing, strictly speaking. Maybe it should be spelled out that not only will your 10.2 be converted to 10, but also 266 will become 10 for byte fields.

Another consistency issue is that even if coerce is set and String values are accepted, fractions cause `NumberFormatException`, so while `330.12` and `"330"` are accepted, `"330.12"` is not. JsonParser explicitly checks for the `.` to decide between `long` and `double`, the same approach could be used here as well.

**Comment by jpountz** [comment]
@szroland +1 this proposal makes sense to me.

> If you agree, I can implement this.

Feel free to ping me when you have a PR ready.

**Comment by szroland** [comment]
Looking at this a bit more I think we might want to be just a little bit careful, and make sure the semantics of coerce is fully intended. Bytes are problematic, because they are read as shorts and then casted to byte. So to illustrate the issue, let me use a short field, and the value 32768, which is `Short.MAX_VALUE` + 1, e.g. fits only into an int.

Current behavior:

Input | Output (coerce=true) | Output (coerce=false)
-------|----------------------------|-----------------------------
42|42|42
42.12|42|IllegalArgumentException
"42"|42|IllegalArgumentException
"42.12" |NumberFormatException|IllegalArgumentException
32768| JsonParseException | JsonParseException
32768.12 | JsonParseException | JsonParseException 
"32768"| NumberFormatException | IllegalArgumentException
"32768.12"|NumberFormatException |IllegalArgumentException
true | JsonParseException | JsonParseException
"true" | NumberFormatException | IllegalArgumentException

The issue is that 42.12 is accepted, but "42.12" is not, even though coerce also supposed to mean to accept the number as a string.
Other issue is that overflow is sometimes an IllegalArgumentException, which can be ignored using ignore_malformed, sometimes it is JsonParseException, which can not be ignored.
With bytes, there is also the automatic cast, which results in even the integer of the number changing (e.g. from 266 to 10).

So one possible behavior is that the integer part must be in range, but when `coerce` is true the number can have a fractional part which is cut off and/or it can also be input as string.

Input | Output (coerce=true) | Output (coerce=false)
-------|----------------------------|-----------------------------
42|42|42
42.12|42|IllegalArgumentException
"42"|42|IllegalArgumentException
"42.12" |**42**|IllegalArgumentException
32768| **IllegalArgumentException** | **IllegalArgumentException**
32768.12 | **IllegalArgumentException** | **IllegalArgumentException** 
"32768"| NumberFormatException | IllegalArgumentException
"32768.12"|NumberFormatException |IllegalArgumentException
true | **IllegalArgumentException** | **IllegalArgumentException**
"true" | NumberFormatException | IllegalArgumentException

The alternative is to allow the implicit casting of out-of-range values when coerce is true, not only for bytes but for other types as well, but that can be a little bit confusing e.g. turning into negative value in this case.

Input | Output (coerce=true) | Output (coerce=false)
-------|----------------------------|-----------------------------
42|42|42
42.12|42|IllegalArgumentException
"42"|42|IllegalArgumentException
"42.12" |**42**|IllegalArgumentException
32768| :boom: **-32768** | **IllegalArgumentException**
32768.12 | :boom: **-32768** | **IllegalArgumentException** 
"32768"| :boom: **-32768**| IllegalArgumentException
"32768.12"| :boom: **-32768**|IllegalArgumentException
true | **IllegalArgumentException** | **IllegalArgumentException**
"true" | NumberFormatException | IllegalArgumentException

Reading back I'm getting mixed signals on this casting aspect of coerce from @passing and @clintongormley.

**Comment by anujgandharv** [comment]
When is it planned to be fixed? We have a use case where we need this functionality.

**Comment by martinhynar** [comment]
It seems that not only byte allows decimals, I see the same behavior with short, integer, and long too.
With this mapping

```
{ "mappings": {
    "example": {
      "properties": {
        "number_long": { "type": "long", "coerce": true },
        "number_integer": { "type": "integer", "coerce": true },
        "number_short":  { "type": "short", "coerce": true }}}}}
```

and document

```
{ "number_long": 42.5,
  "number_integer": 42.5,
  "number_short": 42.5 }
```

I am getting values that are not integers. `_search?fields=number_long,number_integer,number_short,_source`

```
"hits": [{
        "_index": "test-integers",
        "_type": "example",
        "_id": "1",
        "_score": 1,
        "_source": {
          "number_long": 42.5,
          "number_integer": 42.5,
          "number_short": 42.5 },
        "fields": {
          "number_long": [ 42.5 ],
          "number_integer": [ 42.5 ],
          "number_short": [ 42.5 ]}}]
```

Behavior is same on 1.7.4 and 2.2.0.

@szroland How you managed to get 42 from 42.12 with coercion enabled?

**Comment by jpountz** [comment]
@martinhynar those values are retrieved from the `_source`, which elasticsearch does not modify. So if the source contains 42.5 for a field value, trying to read this value from the source will always return 42.5 regardless of the mappings.

**Comment by martinhynar** [comment]
@jpountz Thanks for explanation.
I updated my example locally by adding `"store":true` to all fields and now the values returned by search are all 42. I did not realized that store is false by default and therefore values are extracted from `_source`.
