### ISSUE TITLE
dutch analyzer does not work for words shorter than 4 characters

### ISSUE THREAD

**Issue by a-witkowski** [elastic/elasticsearch#115167]
### Elasticsearch Version

8.12.1, 8.15.3

### Java Version

_bundled_

### OS Version

Windows 11 24H2, OS build: 26100.2033

### Problem Description

dutch analyzer does not work for words shorter than 4 characters

### Steps to Reproduce

Run request:
```
POST https://localhost:9200/_analyze HTTP/1.1
content-type: application/json

{
    "analyzer": "dutch",
    "text": "Wat is een workflow-eigenschap"
}
```

Actual result:
```
HTTP/1.1 200 OK
X-elastic-product: Elasticsearch
content-type: application/json
content-length: 190

{
  "tokens": [
    {
      "token": "workflow",
      "start_offset": 11,
      "end_offset": 19,
      "type": "<ALPHANUM>",
      "position": 3
    },
    {
      "token": "eigenschap",
      "start_offset": 20,
      "end_offset": 30,
      "type": "<ALPHANUM>",
      "position": 4
    }
  ]
}
```

Expected result:
```
HTTP/1.1 200 OK
X-elastic-product: Elasticsearch
content-type: application/json
content-length: 353

{
  "tokens": [
    {
      "token": "wat",
      "start_offset": 0,
      "end_offset": 3,
      "type": "<ALPHANUM>",
      "position": 0
    },
    {
      "token": "een",
      "start_offset": 7,
      "end_offset": 10,
      "type": "<ALPHANUM>",
      "position": 2
    },
    {
      "token": "workflow",
      "start_offset": 11,
      "end_offset": 19,
      "type": "<ALPHANUM>",
      "position": 3
    },
    {
      "token": "eigenschap",
      "start_offset": 20,
      "end_offset": 30,
      "type": "<ALPHANUM>",
      "position": 4
    }
  ]
}
```

**Comment by benwtrent** [comment]
@a-witkowski this is because those are considered `stop-words` by our dutch analyzer. 

It has nothing to do with their character length. 

I don't know why you would want to search over fairly irrelevant words like `wat` `is` or `een` as they will likely exist in many documents and provide very little information.

If you want to really remove the stop words (I do not suggest this). You can use a custom analyzer: https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-custom-analyzer.html

For example, here is the dutch analyzer as a custom analyzer: https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-lang-analyzer.html#dutch-analyzer
