### ISSUE TITLE
Core: Rename caches

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#11569]
With the merge of queries and filters, it would make sense to rename our caches:
 - filter cache -> query cache
 - shard query cache -> shard request cache

I also have hopes that the latter renaming will help remove confusion that the request cache is short-lived since it is invalidated on every refresh.

**Comment by s1monw** [comment]
++

**Comment by jpountz** [comment]
One challenge here is that the new setting for the size of the query cache would be `index.cache.query.size` while it is also the old setting for the request cache size. So we need somehow to be able to differenciate the two.

**Comment by s1monw** [comment]
> One challenge here is that the new setting for the size of the query cache would be index.cache.query.size while it is also the old setting for the request cache size. So we need somehow to be able to differentiate the two.

yeah we can't really... we can go to `index.shard.query.cache.size` maybe?

**Comment by clintongormley** [comment]
And `node.cache.query.size` given that it is node level?

**Comment by bleskes** [comment]
we typically prefix the node level index related settings with `indices`. I like the cache prefix as well.

How about `indices.cache.shard_requests.*` (using adrien’s naming of `shard request cache`)?

**Comment by jpountz** [comment]
@bleskes That works for me, but the issue here is not the new name of the request cache, but the new name of the query cache (formerly known as filter cache) so that it would be different from the previous name of the request cache.

**Comment by bleskes** [comment]
@jpountz yeah, I got confused. The important part for me was to point out the usage of "indices." as node level settings which related to indices. 

As far as the name collision goes - I wonder how many people use the current query cache (i.e. shard requests caching) and thus how bad it would be to make a breaking change and change the semantics of that settings.

Another alternative, which I'm on the fence about but think it's worth mentioning, is using the word segments in the name  - as the queries are cached on a segment level. So that will be `indices.cache.segment.query` & `indices.cache.shard.requests`  .

**Comment by jpountz** [comment]
If there are no objections, I will try to implement Boaz's last proposal.

**Comment by s1monw** [comment]
> If there are no objections, I will try to implement Boaz's last proposal.

++
