### ISSUE TITLE
Minor Code Performance Improvement

### ISSUE THREAD

**Issue by mosbat** [elastic/elasticsearch#115969]
Hi guys, I inspected the code and thought it might be helpful to make the code more efficient. Feel free to give me your feedback on my PR; I'm open to feedback/ideas for sure.

Thank you!

https://github.com/elastic/elasticsearch/pull/115968

**Comment by thecoop** [comment]
Hi @mosbat,

Thanks for your interest in Elasticsearch. As in the linked PR, we do not accept wide-ranging small improvements in this manner. This is also not a specific bug or feature we need to keep track of. As such, I'll close this issue.

**Comment by mosbat** [comment]
> Hi [@mosbat](https://github.com/mosbat),
> 
> Thanks for your interest in Elasticsearch. As in the linked PR, we do not accept wide-ranging small improvements in this manner. This is also not a specific bug or feature we need to keep track of. As such, I'll close this issue.

so I get that performance improvement is not in scope?

**Comment by thecoop** [comment]
We are of course always looking for performance improvements, but they need to be isolated specific changes that cause a measurable difference in performance using [rally](https://github.com/elastic/rally). Furthermore, this issue is not specifically actionable or closeable with one identifiable change.
