### ISSUE TITLE
'elasticsearch' user and group id's should be consistent across multiple nodes

### ISSUE THREAD

**Issue by seang-es** [elastic/elasticsearch#11609]
For filesystem snapshots, if the 'elasticsearch' group and user have differing id numbers between nodes in the system, snapshots will not work.  The master will create subdirectories for each index, but the permissions will reflect ownership by the 'elasticsearch' user on the master.  If the master's elasticsearch user does not match the elasticsearch user id on another node, that node will not be able to write to those directories.

When we create the 'elasticsearch' user and group at installation time, it would be helpful to have a consistent id number.  I don't know if the best solution is to pick an arbitrary high user ID number (9200?) and try to use it by default, or just to document that it needs to be set the same across all nodes.

**Comment by Xylakant** [comment]
I'd consider a fixed user/group ID a bug. For example we assign ranges for user accounts depending on whether it's a "system" account or a "real user" account and 9200 would fall smack into our "real user" account range and probably conflict. I know of more organizations that use a similar scheme, so whatever value you choose you'll step on somebodies toe.

**Comment by clintongormley** [comment]
Let's opt for documenting it

**Comment by gogularaja** [comment]
Hi All,

I am facing an issue while taking elasticsearch snapshot in cluster. I found it is because of different permission of elasticsearch user in one of my node.

I have 2 servers. Configured as cluster
server1: 10.0.0.0
server2: 10.0.0.1

I have changed the userid & groupid of elasticsearch user in server2. So that to keep it same across all the nodes.
But after changing it, i am unable to start the elasticsearch service in server2. Also log file is also not getting updated.


Please guide me in solving this issue..


Thanks,
Gogul

**Comment by rjernst** [comment]
This has been open for almost 3 years with no other reports of similar issues. I'm going to close this as the filesystem snapshots seem to be used far less than cloud based snapshots, and for those that do use snapshots they seem to have not had similar problems. If someone does run into this issue again, we would happily accept a docs change for filesystem snapshot/restore docs.

**Comment by ropetin** [comment]
FYI, this is still an on-going issue.  I have just run into it with 6.2.2 about 30 minutes ago.  Filesystem snapshots are still a supported feature, correct?  So unless anyone fixed the root issue (they haven't) the problem will still be there.   I can't fix the code, but I can fix the documentation maybe.  Which documentation are you referring to when you mention accepting changes?

**Comment by GoodMirek** [comment]
I have solved this issue by creating the elasticsearch user and group prior installation of elasticsearch, thus setting it to a fixed value throughout all the nodes. If Ansible is used for provisioning, ansible-elasticsearch role is capable of doing it automatically.

**Comment by tegansnyder** [comment]
I also ran into this issue. I installed ES on six nodes a few months back, then replaced three of them with new nodes a few weeks ago. Since then ES hasn't been able to write to the NFS for snapshotting. It looks like the only way to fix this is to make sure the uid and gid are the same across all nodes. This looks like a chore because i will need to find a non-used uid and gid that will work across all nodes then do the:

```sh
# make sure uid doesn't exist
id -nu NEW_UID
# make sure new guid doesn't exist
getent group NEW_GUID
# this command will take forever to complete (just tried it on 9TB and took like an hour)
/bin/chown --changes --silent --no-dereference --recursive --from=OLD_UID:OLD_GUID NEW_UID:NEW_GUID /
# then ensure chown'd directories elasticsearch:elasticsearch
```

**Comment by hellosputnik** [comment]
What about adding a [bootstrap check](https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html) that ensures the elasticsearch UID and GID are consistent (or at least a warning when there is inconsistency)?

**Comment by Plop** [comment]
> This has been open for almost 3 years with no other reports of similar issues. I'm going to close this as the filesystem snapshots seem to be used far less than cloud based snapshots, and for those that do use snapshots they seem to have not had similar problems. If someone does run into this issue again, we would happily accept a docs change for filesystem snapshot/restore docs.

I'm still running into this issue. Please make some changes.

**Comment by GoodMirek** [comment]
> > This has been open for almost 3 years with no other reports of similar issues. I'm going to close this as the filesystem snapshots seem to be used far less than cloud based snapshots, and for those that do use snapshots they seem to have not had similar problems. If someone does run into this issue again, we would happily accept a docs change for filesystem snapshot/restore docs.
> 
> I'm still running into this issue. Please make some changes.

Me too and probably also other people. We all solve it in house, as apparently nobody fixed that in Elasticsearch.

**Comment by tocy1** [comment]
For Anyone that comes across this problem, I solved this by running  the following commands on the nodes that had permission issues
id elasticsearch# To Know your elasticsearch gid and uid 
service elasticsearch stop
usermod -u <NEW UID> elasticsearch
groupmod -g <NEW GID> elasticsearch
find / -user <OLD UID> -exec chown -h <NEW UID> {} \;
find / -group <OLD GID> -exec chgrp -h <NEW GID> {} \;
service elasticsearch start

**Comment by cen1** [comment]
> For Anyone that comes across this problem, I solved this by running the following commands on the nodes that had permission issues id elasticsearch# To Know your elasticsearch gid and uid service elasticsearch stop usermod -u NEWUID elasticsearch groupmod -g NEWGID elasticsearch find / -user OLDUID -exec chown -h NEWUID {} ; find / -group OLDGID -exec chgrp -h NEWGID {} ; service elasticsearch start

Hadd to add a backslash in my case:

```
find / -user OLDUID -exec chown -h NEWUID {} \;
find / -group OLDGID -exec chgrp -h NEWGID {} \;
```

**Comment by DaveCTurner** [comment]
Folks, thanks for all your interest and comments on this topic. Our recommendations in this area are [included in the docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/snapshots-filesystem-repository.html#_troubleshooting_a_shared_file_system_repository) (emphasis mine):

> **TIP**: Many NFS implementations match accounts across nodes using their numeric user IDs (UIDs) and group IDs (GIDs) rather than their names. It is possible for Elasticsearch to run under an account with the same name (often elasticsearch) on each node, but for these accounts to have different numeric user or group IDs. If your shared file system uses NFS then ensure that every node is running with the same numeric UID and GID, or else **update your NFS configuration to account for the variance in numeric IDs across nodes**.

Note the last bit, which seems to be the source of all the confusion above: if you don't have full control over numeric UIDs and GIDs, configure your NFS setup to match users by name rather than by numeric ID. It simply isn't true that Elasticsearch requires identical numeric UIDs and GIDs across all nodes. The details of how exactly to set up your NFS system to do this vary greatly by implementation so we can't reasonably describe them all in the Elasticsearch manual: you'll need to look at your NFS system docs for further information.

If you need more help, we'd like to direct you to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.
