### ISSUE TITLE
Log cluster health state (green/yellow/red) change

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#11657]
If we go from one state to another we should explicitly log this.

If not at info/warn, even though that'd be *super dooper handy*, at least at trace/debug.

**Comment by clintongormley** [comment]
We do already, as DEBUG:

    [2015-06-15 11:13:16,339][DEBUG][cluster.service          ] [Gladiator] set local cluster state to version 10

**Comment by bleskes** [comment]
few more handy tips: 

debug logging also gives you the reason for the change - we try to give it good names. He it says it got a new cluster state from the master.

```
1> [2015-06-14 04:51:45,068][DEBUG][cluster.service          ] [node_t1] processing [zen-disco-receive(from master [[node_t0][UUL8MVMFT1iz_2G5po6Haw][hotel][local[node_0]]{enable_custom_paths=true, mode=local}])]: execute
 
```

if you set the logging level of `cluster.service` to `TRACE`  you will get the complete cluster state with every change. Note though that it can be huge and so use with care.

**Comment by markwalkom** [comment]
Sorry, by state I meant green/yellow/red :)

**Comment by danielmitterdorfer** [comment]
I've looked into this and thought how it could be implemented. The problem is that currently the cluster health status is calculated on a variety of parameters (see `ClusterHealthResponse`). The cluster health status is only evaluated when a cluster health REST request is handled. So this calculation is triggered by some user action but not based on an event from within ES itself currently.

So we have basically two problems to solve:

1. Where do we calculate the cluster health status?
2. How to recognize cluster state changes in general?

Regarding (1), I can think of different approaches:

* We could precalculate the cluster health status and put it into `ClusterState`. However, I am not really convinced that this a good solution as it increases the size of `ClusterState` further.
* We could factor out the common logic and recalculate it every time it's needed (i.e. on state change and when handling the before-mentioned REST request).

Regarding (2) I think we'd need to implement a `ClusterStateListener` which logs the message.

Apart from that, the old cluster health status could be kept around to suppress logging when the cluster health status did not change.

What do think @clintongormley, @bleskes?

**Comment by bleskes** [comment]
I'm +1 on have a generic method to calculate the cluster status (it is fairly encapsulated in ClusterHealthResponse ). Note that status change only happens after specific events. Going from green to yellow to red happens on shard failures and nodes leaving the cluster. Going from red to yellow to green happens on shard started event. We can just do the calculation there and do some logging there (including the reason / what have changed).

**Comment by danielmitterdorfer** [comment]
Thanks for your thoughts. I'll give it a shot and ping you.

**Comment by nik9000** [comment]
> We can just do the calculation there and do some logging there (including the reason / what have changed).

I wonder if we could go so far as to _always_ log something at those events and raise the log level if the cluster state changed. Something like
```java
public static void logClusterStateChangeEvent(String eventMessage) {
  ClusterState oldState = fetchOldState();
  ClusterState newSate = calculateNewState();
  if (oldState != newState) {
    logger.info("{} and cluster state changed from {} to {}", eventMessage, oldState, newState);
  } else {
    logger.debug("{} and cluster state stayed {}", eventMessage, oldState);
  }
}
```

That way if you switched to DEBUG level logging you'd see this stream of events and it'd be really obvious which one might impact the cluster state. I kinda figure we already have logging at these events so it'd be a matter of hunting them down.

**Comment by bleskes** [comment]
@nik9000 I think we can defiantly do better but watch out with logging cluster states. They can be *huge*.

**Comment by nik9000** [comment]
> @nik9000 I think we can defiantly do better but watch out with logging cluster states. They can be huge.

Oh I didn't mean the whole thing! I just meant the health. Yeah. I know full well that they can take up megabytes of text.....

**Comment by nik9000** [comment]
> Oh I didn't mean the whole thing! I just meant the health. Yeah. I know full well that they can take up megabytes of text.....

And I've fixed the comment so it looks like what I meant the first time around.
