### ISSUE TITLE
Unexpected Behavior with ICU Collation Keyword Sorting

### ISSUE THREAD

**Issue by wka24** [elastic/elasticsearch#116763]
Hello,

I am experiencing unexpected behavior with the sorting order of documents in Elasticsearch using the icu_collation_keyword field type. 
Here are the details:

**Steps to Reproduce:**

Create the Index with Mappings:
PUT /test-index
{
"mappings": {
"properties": {
"id422": {
"type": "text",
"fields": {
"collated": {
"type": "icu_collation_keyword",
"strength": "tertiary",
"case_level": true
}
}
}
}
}
}

Index the Documents:

POST /test-index/_doc/1
{
"id422": "0a11"
}

POST /test-index/_doc/2
{
"id422": "0A11"
}

POST /test-index/_doc/3
{
"id422": "0b11"
}

POST /test-index/_doc/4
{
"id422": "0B11"
}

POST /test-index/_doc/5
{
"id422": "0c11"
}

POST /test-index/_doc/6
{
"id422": "0C11"
}

Search and Sort:
GET /test-index/_search
{
"sort": [
{
"id422.collated": {
"order": "asc"
}
}
],
"_source": ["id422"]
}

Expected Sort Order:
0A11
0B11
0C11
0a11
0b11
0c11
Actual Sort Order:
The response includes unexpected characters in the sort field, and the order does not match the expected case-sensitive sorting.

Response:
Sort order
0a11
0A11
0b11
0B11
0c11
0C11

The sort fields of the response contain unexpected cryptic characters like:
"sort": [
"""কՅ‡ࡀ

Additional Information:
Elasticsearch version: 8.15.3
Kibana version: 8.15.3
ICU Analysis plugin version: 8.15.3
Any insights or suggestions on how to resolve this issue would be greatly appreciated.

Thank you!

**Comment by john-wagster** [comment]
@wka24 the ICU spec is pretty complex.  I myself struggle with it.  For the docs you have in your example:

```
0a11
0a11
0a11
0a11
```

**Comment by john-wagster** [comment]
@wka24 the ICU spec is pretty complex. I myself struggle with it. For the documents you are indexing you have in your example:

```
0a11
0A11
0b11
0B11
0c11
0C11
```

These will be sorted by default following DUCET collation, which is documented for ES here on the [icu_collation_keyword](https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-icu-collation-keyword-field.html). 
 
DUCET though can be difficult to know what the sort order is supposed to be intuitively. 

I use this [utility](https://icu4c-demos.unicode.org/icu-bin/collation.html) to check the sort ordering, which matches what you get above in your reported results: 

```
0a11
0A11
0b11
0B11
0c11
0C11
```

However, if you want to get a sort order of:

```
0A11
0B11
0C11
0a11
0b11
0c11
```

You can provide custom ICU style rules to the icu plugin; these rules also work on the icu utility I mentioned above so you can easily verify their behavior.  Here's what that looks like when creating your index:  
 
```
{
  "mappings": {
    "properties": {
      "id422": {
        "type": "text",
        "fields": {
          "collated": {
            "type": "icu_collation_keyword",
            "strength": "tertiary",
            "case_level": true,
            "rules": "& Z <* a-z"
          }
        }
      }
    }
  }
}'
```

That `rules` parameter will cause the expected sort ordering. 

As far as the output of the sort field is concerned this is a sequence of unicode bytes that are primarily useful for databases to easily sort on that collation ordering.  Your tool of choice is outputting the actual unicode characters themselves but this isn't particularly meaningful.  You can read more about this here if you are curious: [sort keys](https://unicode-org.github.io/icu/userguide/collation/api.html#getsortkey)

So for example when I use the above rules with the set of inputs you provided I get the following output with unicode escapes printed instead of actual characters (because a lot of these are essentially control characters for collation I believe).  You can kind of see how they are sequential though.  You have to be careful too as there's no guarantee that these sort keys are stable from version to version of the ICU so you might for instance get different sort key characters out of that utility I mentioned above.

```
{
    "took": 6,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 6,
            "relation": "eq"
        },
        "max_score": null,
        "hits": [
            {
                "_index": "test",
                "_id": "2",
                "_score": null,
                "_source": {
                    "id422": "0A11"
                },
                "sort": [
                    "\u0995\u0545\u2021\u001d\u7900\u0717\u380c\u0000\u0000"
                ]
            },
            {
                "_index": "test",
                "_id": "4",
                "_score": null,
                "_source": {
                    "id422": "0B11"
                },
                "sort": [
                    "\u0996\u0545\u2021\u001d\u7900\u0717\u380c\u0000\u0000"
                ]
            },
            {
                "_index": "test",
                "_id": "6",
                "_score": null,
                "_source": {
                    "id422": "0C11"
                },
                "sort": [
                    "\u0997\u0545\u2021\u001d\u7900\u0717\u380c\u0000\u0000"
                ]
            },
            {
                "_index": "test",
                "_id": "1",
                "_score": null,
                "_source": {
                    "id422": "0a11"
                },
                "sort": [
                    "\u09ae\u4085\u22a0\u1080\u0808\u2000\u0001"
                ]
            },
            {
                "_index": "test",
                "_id": "3",
                "_score": null,
                "_source": {
                    "id422": "0b11"
                },
                "sort": [
                    "\u09ae\u40c5\u22a0\u1080\u0808\u2000\u0001"
                ]
            },
            {
                "_index": "test",
                "_id": "5",
                "_score": null,
                "_source": {
                    "id422": "0c11"
                },
                "sort": [
                    "\u09ae\u4105\u22a0\u1080\u0808\u2000\u0001"
                ]
            }
        ]
    }
}
```

Happy to discuss further if you have a specific use case with the sort keys or are having trouble with the icu spec.  Just let me know some more details of your use-case.  

Otherwise I'll probably close this ticket over the next couple of days as the sort order aligns with the icu spec.

**Comment by wka24** [comment]
Hello,

Thank you for the detailed response and suggestions.

I've tried several rule suggestions from AI tools, but unfortunately, they didn't yield the desired results. I'm currently using GitHub Copilot and ChatGPT for guidance.

The page you mentioned on the icu_collation_keyword provides information on how to achieve case-sensitive sorting by adjusting the strength and case_level parameters. However, the sort order resulting from these settings does not appear to be truly case-sensitive. Both Copilot and ChatGPT suggest that the results should align with the example provided, but that doesn't seem to be the case in practice.

I’m unsure why the ICU4C demos page interprets the sort order as "case-sensitive." I've experimented with different settings, but it always seems to compare case-insensitively first, and only then apply case sensitivity and other criteria in a secondary step.

Either the ICU documentation is unclear, or the test page does not fully adhere to the specifications. I don’t plan to dive deeper into the ICU spec at the moment, as it wouldn’t resolve my current issue.

The workaround using the provided rules is effective, which is great and addresses my current needs.

Right now, my main task is to replace the existing OpenText search engine in our product with Elasticsearch. As we roll out the solution across different countries and for clients with specific sorting requirements, additional use cases may arise. Currently, I'm in the implementation phase and conducting early internal tests.

**Comment by john-wagster** [comment]
Yep I think your interpretation is correct.  I've found that the case-sensitive parameters do work but they get applied potentially in an order that's not what you were hoping for such as: 

```
A
a
B
b
C
c
```

So essentially reversing the order of the original input instead of what you want.  

The ICU spec is complicated to say the least.

Feel free to reply back if you need any more help or run into difficulty.  Those rules themselves can get pretty confusing.  Happy to help out. 

I'll leave the issue open for a few more days just in case you do wind up needing anything.
