### ISSUE TITLE
NPE with AbstractNioSelector

### ISSUE THREAD

**Issue by ayashjorden** [elastic/elasticsearch#11706]
Hi all,
Got lots of NullPointerException with the following StackTrace:
```
[2015-06-16 19:01:45,017][WARN ][netty.channel.socket.nio.AbstractNioSelector] Unexpected exception in the selector loop.
java.lang.NullPointerException
        at sun.nio.ch.EPollArrayWrapper.isEventsHighKilled(EPollArrayWrapper.java:174)
        at sun.nio.ch.EPollArrayWrapper.setUpdateEvents(EPollArrayWrapper.java:190)
        at sun.nio.ch.EPollArrayWrapper.add(EPollArrayWrapper.java:239)
        at sun.nio.ch.EPollSelectorImpl.implRegister(EPollSelectorImpl.java:164)
        at sun.nio.ch.SelectorImpl.register(SelectorImpl.java:133)
        at java.nio.channels.spi.AbstractSelectableChannel.register(AbstractSelectableChannel.java:209)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker$RegisterTask.run(NioWorker.java:151)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

The cluster consists of a data node (8 cors 126GB ram, 32GB heap) and SearchLoadBalancer(master/data = false).

What can cause this ?

**Comment by clintongormley** [comment]
@spinscale any ideas?

**Comment by ayashjorden** [comment]
@clintongormley @spinscale any update on this ticket?
What additional information can I provide to start investigation?

These exceptions happen to us almost every day.

Thanks,
Yarden

**Comment by spinscale** [comment]
I need to take a closer look at this. Can you provide some more generic information:

* elasticsearch version
* java version
* Any special usage pattern? Do you open a lot of new connections? What load is happening on that system?
* Can you run netstat to check the number of open tcp connections?
* Do you know if this is happening with HTTP or the transport protocol? (If you dont use HTTP, we can rule it out)
* What is the impact of that exception in your system/cluster? Are connections broken after that? Is elasticsearch unresponsive?

**Comment by ayashjorden** [comment]
Please see the requested data below:
1. ES cluster consists of two nodes, data/master node (listed below) and a Search-Load-Balancer (data/master=false) which a collocated Kibana 4(nodeJS) is connected to.
  * ```json
{
  "status" : 200,
  "name" : "es01",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.5.2",
    "build_hash" : "62ff9868b4c8a0c45860bebb259e21980778ab1c",
    "build_timestamp" : "2015-04-27T09:21:06Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}```
2. java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-1~deb8u1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

3. logstash 1.5.0 with updated elasticsearch output plugin 0.2.7 . I know there's a bottle neck due to ES machine CPU (2x4cors with hyper-threading)
4. ```sudo netstat -tupn|grep -F c.d|wc -l``` results in 168, outside high traffic hours.
5.Logstash 1.5.0 is using the transport protocol, not HTTP.
6. I don't know the impact on my cluster as the only thing I see are these errors in the logs.

Hope this information will be helpful,
Yarden

**Comment by szroland** [comment]
Interesting that the `EPollArrayWrapper.isEventsHighKilled` method got introduced to fix file descriptor registration hitting a NullPointer exception, e.g. http://hg.openjdk.java.net/icedtea/jdk7/jdk/rev/9af467c489cc, you still seem to be hitting (another) NullPointer in that area. Maybe there is an issue with how it determines the number of max open file descriptors (e.g. `IOUtil.fdLimit()` call), but in practice the issue looks to be triggered by an FD value larger than 65535 (or whatever you have set `sun.nio.ch.maxUpdateArraySize` to, if you happen to have customized it). Overall this feels to be a JDK issue to me.

As a workaround, I'd recommend trying either one of these:
* Try setting ulimit to 65535 maximum. Based on the error, you likely have it set higher
* If you must keep it at a value higher than that, you could try set the JVM property `sun.nio.ch.maxUpdateArraySize` to a bit higher than whatever you specified as ulimit
* Try upgrade to a newer version of OpenJDK if you can
* You could try using a recent version of the Oracle JVM distribution, maybe even java 8

**Comment by spinscale** [comment]
@szroland very interesting. Out of curiosity: how did you make the connection between the above revision and this problem? Cant spot the missing link

Thanks a lot for helping!

**Comment by szroland** [comment]
I was just looking at the JDK source, `EPollArrayWrapper` in particular, just out of interest, what can be throwing that NullPointer. On the changelog: http://hg.openjdk.java.net/jdk8/jdk8/jdk/log/687fd7c7986d/src/solaris/classes/sun/nio/ch/EPollArrayWrapper.java I saw a ref to a NullPointer, so first I thought it was that issue exactly. But on the contrary, this change seems to be already included in the version of jvm used (e.g. the `isEventsHighKilled` method). I just referenced it to show JDK issues are not unheard of in this area, and that one in particular was another NullPointer in this same class.

Note that I couldn't actually point to the root cause problem, because the `EPollArrayWrapper` code, and how it handles the `eventsLow` and `eventsHigh` structures seems consistent to me, and still the NullPointer seems to be because the eventsHigh map was not created, but a large FD did come through. The only thing I can think of is `IOUtil.fdLimit()` (a native method, so I didn't check how it worked) reporting a lower value than what FDs can actually occur in the given setup. To work around that, you can either limit FDs in linux manually, use that jvm flag to override the size of the `eventsLow` structure, so that it is always sufficiently large, or upgrade and hope someone spotted the root cause and fixed it.

Admittedly, there is a chance of the version of  `EPollArrayWrapper` in the particular JDK build not being fully consistent with the source I was looking at, which could result in my analysis not being 100% correct. I couldn't actually find the particular revision of EPollArrayWrapper that is exactly in that build. But still, the likelyhood of that is small I believe, since the code is still the same at the head revision of jdk8, http://hg.openjdk.java.net/jdk8/jdk8/jdk/log/687fd7c7986d/src/solaris/classes/sun/nio/ch/EPollArrayWrapper.java. I still recommended the upgrade, as I suspect the issue might be with the fdLimits() call, not with `EPollArrayWrapper`itself. 

I haven't tried actually reproducing this, although now that we know the jdk and elastic version, we could try doing that as well.

**Comment by spinscale** [comment]
@ayashjorden have you tried any of the above suggestions? Eager to get some feedback here!

**Comment by ayashjorden** [comment]
Hi @spinscale,
Sorry for the delayed response.

Lowering file descriptors is too risky for us because the (currently) single data node will (again) go into a 'too many open file' blitz.

JVM maxUpdateArraySize and Java8 options will be in focus next week.

I'll post an informative feedback once I'll have it.

Thanks,
Yarden

**Comment by ayashjorden** [comment]
Hi All,
We resolved the issue by addressing ES limit configuration issues as described at #12404 .

Thanks for all the help,
Yarden
