### ISSUE TITLE
copy_to and geo_point

### ISSUE THREAD

**Issue by jimmyjones2** [elastic/elasticsearch#11715]
I can't seem to get it to work with 1.6.0:
```bash
curl -XPUT localhost:9200/geo
curl -XPUT localhost:9200/geo/geo/_mapping -d '
{
  "geo" : {
    "properties" : {
      "location" : {
        "type" : "geo_point",
        "copy_to" : "other_location"
      },
      "other_location" : {
        "type" : "geo_point"
      }
    }
  }
}'
curl -XPOST localhost:9200/geo/geo -d '{ "location" : [-71, 41] }'
curl -XGET localhost:9200/geo/geo/_search?type=count -d '
{
  "size" : 0,
  "query" : { "match_all" : {} },
  "aggs": {
    "geo": {
      "geohash_grid" : { "field" : "other_location" , "precision" : 2 }
    }
  }
}'
```
Get no results when agg on other_location field, but works with location field.

**Comment by clintongormley** [comment]
@nknize do geo-points support the `copy_to` parameter? If the answer is no, then would it be feasible (and useful) to add support for them? If not, we should probably throw an exception if `copy_to` is specified.

@jimmyjones2 what was your reason for wanting to use `copy_to` with a geo-point?

**Comment by jimmyjones2** [comment]
I've got some records with multiple geo-point fields and would like to be able to search them all at once and plot them all on a map in Kibana

**Comment by nknize** [comment]
@clintongormley @jimmyjones2  copyTo is not supported with ```geo_point``` field. It's feasible but I don't know that its needed (especially in 2.0 with a change to GeoPointField default indexing). It should make this use-case feasible/simple with named queries. I think it might be doable with named filters (i'm helping give training so I'll revisit when I have some time to tinker).

**Comment by clintongormley** [comment]
thanks @nknize - i'll assign to you then

**Comment by FindKim** [comment]
I am also running into this issue. Would it be possible to `copy_to` separate `lat` and `lon` values into `other_location.lat` and `other_location.lon`, respectively?

**Comment by michielhn** [comment]
@nknize can you elaborate how this would look like in the future? I am practically looking for the same solution w/o having to redefine the log output from our applications.

**Comment by blabno** [comment]
I use `position` field in many types, but I need `geohash_prefix:true` only in one type, so I wanted to use `copy_to` to `userPosition` field that has `geohash_prefix` enabled , but it does not work. Right now I have to add `userPosition` to the indexed document itself, which is not too nice.

In general when I get a new requirement and have to change mapping for `position` field (which I can't because other types use it differently) then I have to add new field to the document.

**Comment by clintongormley** [comment]
@blabno the indexing for geo points has changed completely in 2.2/2.3, you can't enable or disable geohashes any more. With the new index format, I can't see the benefit of copying geo-point fields to another field any more, so I'm going to close this

**Comment by blabno** [comment]
@clintongormley is `geohash_prefix` always set to `true` then? I assume that if we index parent geohashes then the index grows. Now what if in 10 documents we have `position` field of `geo_point` type, but we want to have `geohash_prefix:true` only for one document?
Just do not tell me that I have to give the field different name, because that would be really stupid requirement to change data model, because of technology limitation.

**Comment by clintongormley** [comment]
@blabno apparently i'm mistaken, the geohash prefix parameter hasn't been removed: https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-point.html#geo-point-params

That said, I don't understand why you would index the same geopoint in multiple ways.  That is really wasteful.  Choose the highest precision that you need and apply that to a single field.

**Comment by blabno** [comment]
@clintongormley I would love to index `position` property in `user` entity in one way only, unfortunately ES forces me to use the same mapping for the same field across all document types and I use `position` property across a lot of other document types. So now I would have to change mapping for all other document types, just to get support for `geohash_prefix` in just one document.
