### ISSUE TITLE
Allow to execute REST tests in plugins again

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#11721]
The `ElasticsearchRestTestCase` has changed in 2.0 and now throws an error when executing REST tests in a maven plugin project which depends on `elasticsearch-2.0.0-SNAPSHOT-tests.jar`:

```java
$ cd plugins/delete-by-query
$ mvn clean test -Dtests.filter="@rest"

Suite: org.elasticsearch.plugin.deletebyquery.test.rest.DeleteByQueryRestTests
ERROR   0.03s J3 | DeleteByQueryRestTests.initializationError <<<
   > Throwable #1: java.nio.file.NoSuchFileException: delete_by_query
   > 	at org.elasticsearch.test.rest.support.FileUtils.resolveFile(FileUtils.java:99)
   > 	at org.elasticsearch.test.rest.support.FileUtils.findYamlSuites(FileUtils.java:86)
   > 	at org.elasticsearch.test.rest.ElasticsearchRestTestCase.collectTestCandidates(ElasticsearchRestTestCase.java:189)
   > 	at org.elasticsearch.test.rest.ElasticsearchRestTestCase.createParameters(ElasticsearchRestTestCase.java:174)
   > 	at org.elasticsearch.plugin.deletebyquery.test.rest.DeleteByQueryRestTests.parameters(DeleteByQueryRestTests.java:45)
   > 	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
Completed [4/4] on J3 in 0.04s, 1 test, 1 error <<< FAILURES!
```

When executed with `mvn clean test` command, it seems that plugin specific REST tests (declared in POM file using `<tests.rest.suite/>` tag) are resolved using a `ZipFileSystem` instance corresponding to the `elasticsearch-2.0.0-SNAPSHOT-tests.jar`.

When executed in an IDE, tests are resolved using the classpath and it works.

File resolution are a bit cryptic in `ElasticsearchRestTestCase` and `FileUtils` so I'll be happy if someone can point me in the right direction to make this works.

**Comment by rmuir** [comment]
I don't think its a bug, i think these tests are overengineered?

The zipfilesystem stuff is the best way I could make it work given what some of the other plugins wanted to do here.

In order to simplify this test the parameterization really has to go. that is what adds a significant majority of complexity to this stuff because things must happen in clinit. 

Please, no more parameterized tests, ever!

**Comment by javanna** [comment]
I'd leave the parameterized discussion out of this issue, we can certainly discuss that but I'd do it separately. 

The problem here is that plugins need to be able to run their own REST tests, pointing to them via -Dtests.rest.suite and -Dtests.rest.spec. That is not possible anymore, given that if `ElasticsearchRestTestCase` comes from within a jar, REST tests and spec can only be taken from that specific jar. Only the usecase where a plugin needs to run REST tests coming from elasticsearch core is handled right now; a plugin cannot run its own tests, unless I am missing a way to do it. We need to add back this feature to the REST test infra, it doesn't need to be able to run tests from any file system location as it used to be though (way too much!).

**Comment by rmuir** [comment]
The parameterized discussion is definitely involved here. Besides being completely useless, parameterized tests just make things complicated, because nothing can happen except in clinit (so no subclassing). Just have a look around and look at what is subclassing this rest test stuff and why.

There is too much going on. Down with parameterized tests! I need to create some kind of github plugin like the CLA-checker that makes the whole PR go completely red if it contains any.
