### ISSUE TITLE
Use only Jackson in favor of XContent?

### ISSUE THREAD

**Issue by mtraynham** [elastic/elasticsearch#11895]
I've been using the Java API recently to dynamically generate different types of index mappings for particular use cases and indices.  I found myself implementing POJO's that simulate what XContent parses and using Jackson to produce JSON for the ElasticSearchClient.

I see that XContent uses parts of Jackson under the covers, but I'm a little lost on why most of the endpoints don't just parse POJO objects that may be shared with the Java API.  Not to mention, it seems like some of the other data formats that Jackson has would be useful, such as Avro.

*Edited this after some more investigation.

**Comment by pickypg** [comment]
Not for or against this, but I wanted to [link to the Avro page](https://github.com/FasterXML/jackson-dataformat-avro#schema-not-optional). One key takeaway that does make it less attractive for me:

> Avro is strongly Schema-based, and all use requires an Avro Schema. Since there is little metadata in encoded in Avro data, it is not possible to know anything about structure of data without Schema.

This makes it inherently harder to implement than the rest of the formats that we do support.

**Comment by mtraynham** [comment]
@pickypg That is very good point! Somewhat of a pitfall to Avro.  For RPC, both parties must know the schema to understand the transmitted Avro data; unlike file based serialization that stores a copy of the schema at the top.  Although, an Avro schema is somewhat similar to an ElasticSearch index mapping and it might be possible to infer that schema (or store it on the index mapping).  I only bring it up because you could get a lot more over wire in less time.

This kind of diverges from my curiosity though, which was more about why XContent responses are built using array/object/field builders and not just POJO's that could be shared through the Java API, like with index mappings and field types.

**Comment by spinscale** [comment]
one of the reasons, that we do not use POJOs, is that this would require serialization/deserialization up front and possibly create big objects in memory. This would not be GC friendly.

For example, take an elasticsearch query. Instead of having to pass the pojo to the different query parser (one for a filtered query, one for a geo shape query, etc.. one for each type), we can just pass the xcontent parser and read through it step by step.

As you already mentioned, the `XContent` stuff is just a small layer on top of JSON to simplify the handling of streaming data. Due to this, it is not really easy to create POJOs out of this at this layer and you need to do that in your client code.

As you can see in our `pom.xml` dependencies, we already use the `jackson-dataformat-smile`, `jackson-dataformat-yaml` and `jackson-dataformat-cbor` libraries. Because of the `xContent` abstraction it is really easy for us to support different formats and also extract the format being used in the data sent to elasticsearch (one of the reasons why we can index data in YAML format as well as read JSON configuration files). You may be able to extend the xcontentparsers to also support avro without the need to bind to a POJO by using the `jackson-dataformat-avro` library...

I will close this ticket though, as we will not change our approach here. Hope this helps.

**Comment by mtraynham** [comment]
@spinscale Hey thanks for addressing me.  I do understand the benefits of the streaming aspect and the gains that may be had with query parsing/responses.  In terms of fairly static endpoints that don't receive requests very often, and the schema may be somewhat small and addressable (specifically index mappings), it just seems a bit overkill.  The Java API does have fluid interfaces for handling these types of requests, but it simply builds XContent behind the scenes.  In my case, we load a mapping and add/remove fields as we see fit.  So I found myself implementing POJO's to simulate what XContent would generate.  I couldn't find a good way to read a static index mapping from disk, nor an easy way to modify the fields that were on that mapping using XContent.
