### ISSUE TITLE
Can't create keystore.tmp with a read only filesystem

### ISSUE THREAD

**Issue by rmannibucau** [elastic/elasticsearch#119341]
### Elasticsearch Version

8.x

### Java Version

_bundled_

### OS Version

ubuntu 24.10

### Problem Description

bootstrap keystore uses a temp file next to the original keystore

the issue is that it means a readonly filesystem can't be used within kubernetes (or more generally but it pops up quickly with k8s)

fix is to use tmp dir in https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/common/settings/KeyStoreWrapper.java#L443 (`java.io.tmpdir` actually)

### Steps to Reproduce

set config dir readonly and start es

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

Specifically:

> fix is to use tmp dir

That's not going to help, we have to be able to overwrite the actual keystore a few lines lower down:

https://github.com/elastic/elasticsearch/blob/8efd08b019b9160f5e703520c6ce3b6a9f92cfbd/server/src/main/java/org/elasticsearch/common/settings/KeyStoreWrapper.java#L520

Instead, the fix is not to try and write to the keystore in an environment where that is not permitted. Prepare the keystore in advance elsewhere first.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by rmannibucau** [comment]
> There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question

Well there is no actual question which can be solved on a forum, the bug is in the code (this is why i opened it there).
Agree there can be multiple fixes but current workaround to overwrite config/ folder and copy java.options, elasticsearch.yml and log4j2.properties is not satisfying even if it works.

What I didn't note which can lead to another better fix is that I don't enable https, only http so the keystore shouldn't even be checked and even less be written so ServerCli is likely over preconfiguring the env.

Also KeyStoreLoader could check it is readonly or not (https://github.com/elastic/elasticsearch/blob/main/distribution/tools/server-cli/src/main/java/org/elasticsearch/server/cli/KeyStoreLoader.java#L42) before trying and assume it is preconfigured if readonly - ultimately it means just implementing the related todo (https://github.com/elastic/elasticsearch/blob/8efd08b019b9160f5e703520c6ce3b6a9f92cfbd/distribution/tools/server-cli/src/main/java/org/elasticsearch/server/cli/ServerCli.java#L279).

There are a ton of working fixes for this bug but default behavior is likely wrong from an user perspective so it should likely stay an open bug.
