### ISSUE TITLE
Filtered terms aggregation no more works from 1.5 version

### ISSUE THREAD

**Issue by Matrooskin** [elastic/elasticsearch#11959]
After upgrading ES from 1.4 to 1.5 some issue appears with terms aggregation.
On ES 1.4 this code is working perfect, beginning from 1.5 it returns empty buckets.

https://gist.github.com/Matrooskin/5c0bf81157038c6c3b6f

**Comment by clintongormley** [comment]
Hi @Matrooskin 

The problem is that you have a type name `nestedDocs` which is the same as a field name `objNestedDocs.nestedDocs`.  This ambiguity is causing the problem.  

We have fixed this in 2.0 with #8872.  In the meantime, all I can suggest to you is to change either the type or the field name to remove the ambiguity

**Comment by Matrooskin** [comment]
Thank you for quick response. I will do that change.
