### ISSUE TITLE
FSTs via completion suggester consuming all the heap

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#11967]
ES 1.6.0 with an index with 5 completion fields.  The heap usage on nodes hit 98%.  The heap itself is showing mostly segment readers with FSTs in them loaded via searches:

![image](https://cloud.githubusercontent.com/assets/7216393/8445344/b5e05680-1f50-11e5-83e6-aaa5a9c80509.png)

Currently, all FSTs for a field are loaded into the heap when the field is requested via search.  This makes me wonder if there's potentially a protection mechanism we can put in place to prevent the FSTs from consuming all of the heap.  Some kind of a cap and/or a way to evict them would be nice.

**Comment by clintongormley** [comment]
FSTs need to be in memory to work. We can't really evict them. It would also be difficult to add a circuit breaker to prevent loading the FST, because throwing an exception while loading the FST would make the entire segment unusable.

I don't think there is any way around this issue: you need to monitor the amount of memory used with the completion stats and plan around it.

Closing as won't fix
