### ISSUE TITLE
Add option to show aliases in _cat/indices

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#11984]
We already have `_cat/aliases` and it reports the indices associated with it. However, `_cat/indices` shows a lot of index-specific detail that would also benefit from showing any aliases associated with it.

This wouldn't necessarily need to be a default feature, but it would help to extend the flexibility of the single call so that one can associate things like store size with an alias in a single call. My big fear is that multiple aliases can exist, so this could really bloat the output if used in such cases.

**Comment by clintongormley** [comment]
Hi @pickypg 

I don't think we should add this.

The problem is that multiple aliases would clash with the tabular output of cat. (See https://github.com/elastic/elasticsearch/pull/11791 for a similar issue that we're in the process of fixing). 

You can already use aliases with the indices stats API, which solves the problem by using structured output. Alternatively, you can use:

    GET _cat/indices/{alias_name}

which will give you the data you're after for all of the associated indices.  I think that this already serves the purpose.
