### ISSUE TITLE
after DELETE old snapshot,can't resotre snapshot

### ISSUE THREAD

**Issue by JasonBian** [elastic/elasticsearch#12012]
we do a backup for the elasticsearch everyday(there will create a snapshot everyday),where I delete the old snapshots,only leave the latest 7 snapshots on the hdfs.then I execute the restore the snapshot, I found that we can't restore the snapshot
[Failed to start shard, message [IndexShardGatewayRecoveryException[[userindex][6] failed recovery]; nested: IndexShardRestoreFailedException[[userindex][6] restore failed]; nested: IndexShardRestoreFailedException[[userindex][6] failed to restore snapshot [snapshot_20150624]]; nested: IndexShardRestoreFailedException[[userindex][6] Failed to fetch index version after copying it over]; nested: CorruptIndexException[codec mismatch: actual codec=Lucene46SegmentInfo vs expected codec=segments (resource: BufferedChecksumIndexInput(MMapIndexInput(path="/es/elasticsearch-1.2.2/data/elasticsearch-kt/nodes/0/indices/userindex/6/index/segments_4bol")))]; ]]

**Comment by clintongormley** [comment]
HI @JasonBian 

It looks like you have a corrupt file in your snapshot.  I suggest:

* reindexing your `userindex` to a new index (just in case)
* try to optimize the `userindex` (to rewrite any bad segments)
* make a fresh snapshot
* try to restore it... hopefully this will work

A number of corruption problems have been fixed in recent versions. You should upgrade as soon as possible.
