### ISSUE TITLE
Nested geo_* type with doc values and include_in_parent fails with multiple values

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#12056]
If you create a `nested` `geo_*` type and you attempt to use both `include_in_parent` and `doc_values`, then you cannot index multiple values. If you remove either setting, then it works.

```
PUT /test
{
  "mappings": {
    "type": {
      "properties": {
        "location": {
          "type": "nested",
          "include_in_parent": true, 
          "properties": {
            "point": {
              "type": "geo_point",
              "doc_values": true
            }
          }
        }
      }
    }
  }
}

# Works
PUT /test/type/1
{
  "location" : {
    "point" : [0, 0]
  }
}

# Fails
PUT /test/type/2
{
  "location" : [
    {
      "point" : [0, 0]
    },
    {
      "point" : [1, 1]
    }
  ]
}
```

The first attempt works as expected, but the second attempt fails with an odd exception.

```json
{
   "error": "IllegalArgumentException[DocValuesField \"location.point\" appears more than once in this document (only one value is allowed per field)]",
   "status": 500
}
```

This is related to https://github.com/elastic/elasticsearch/issues/10653#issuecomment-94097576, which notes that `include_in_parent` is ignored for `geo_*` types, but it does not suggest that it will fail upon trying to make use of it. This behavior should probably be explicitly blocked. Note: changing `geo_point` to some type that does work with `include_in_parent`, such as `long`, does work.

**Comment by rjernst** [comment]
For `geo_point`:
BinaryDocValues only supports a single value. Multiple values must be encoded within the binary value returned. This works when changing to eg `long` because then the field is using SortedNumericDocValues, which supports multiple values. However, `geo_point` has code (which at a glance looks correct to me) which handles multiple values when encoding. So this seems like a bug. Maybe @nknize has ideas here on what could be going wrong.

For `geo_shape`:
As mentioned in the referenced comment, the way the custom token producer for shapes works only allows a single pass, but `include_in_parent` works by simply copying the reference to the token producer, and the second iteration (for the parent) silently fails. I agree we should simply disallow this with an error message until it can be fixed. I'll put up a PR.

**Comment by pickypg** [comment]
Just to add for @nknize, it does work with multiple values _without_ `include_in_parent`.

**Comment by nknize** [comment]
This worked for me in 2.x. @pickypg can you confirm? @clintongormley Would you like me to diff with 1.7.x and backport a patch?

**Comment by pickypg** [comment]
@nknize Confirmed that this appears to work in 2.0.0-beta1.

**Comment by clintongormley** [comment]
@nknize Thanks, but I think we're good with 2.0.  Closing

**Comment by vixriihi** [comment]
I'm facing this same issue with v7.11.2
