### ISSUE TITLE
Improve error handling of ClassCastException

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#12135]
Example in 1.6:

```
POST cast/type/1
{
  "ip_str":"0.0.0.0"
}
PUT cast2
{
  "mappings": {
    "type":{
      "properties": {
        "ip_str":{
          "type":"ip"
        }
      }
    }
  }
}
POST cast2/type/1
{
  "ip_str":"0.0.0.0"
}

GET cast/_mapping
GET cast2/_mapping

GET cast,cast2/_search?search_type=count
{
  "aggs": {
    "NAME": {
      "terms": {
        "field": "ip_str",
        "size": 10
      }
    }
  }
}
```

Returns:

```
{
   "error": "ReduceSearchPhaseException[Failed to execute phase [query], [reduce] ]; nested: ClassCastException[org.elasticsearch.search.aggregations.bucket.terms.LongTerms$Bucket cannot be cast to org.elasticsearch.search.aggregations.bucket.terms.StringTerms$Bucket]; ",
   "status": 503
}
```

Above is a simplified example.  Would be nice to improve the error handling above, eg. tell the user that cast index's type mapping has ip_str defined as a string while cast2 index' type mapping has ip_str defined as an ip type and they will have to reindex to address the type mismatch, etc..

**Comment by ashishnerkar1** [comment]
Hi All, I am new to ElasticSearch & want to start contributing to this project. I am interested in working on this issue. Can someone point me to appropriate resources & steps to start working on this issue.

**Comment by clintongormley** [comment]
@ashishnerkar1 read https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md

**Comment by HarishAtGitHub** [comment]
sorry for the unnecessary noise due to my commit in other repo (when trying to reproduce the issue)...

**Comment by xuzha** [comment]
Look like we resolved this already. 

{
   "error": {
      "root_cause": [],
      "type": "reduce_search_phase_exception",
      "reason": "[reduce] ",
      "phase": "query",
      "grouped": true,
      "failed_shards": [],
      "caused_by": {
         "type": "class_cast_exception",
         "reason": "org.elasticsearch.search.aggregations.bucket.terms.LongTerms$Bucket cannot be cast to org.elasticsearch.search.aggregations.bucket.terms.StringTerms$Bucket"
      }
   },
   "status": 503
}

**Comment by clintongormley** [comment]
@xuzha would still be nice to mention the actual field name

**Comment by HarishAtGitHub** [comment]
@clintongormley , I was not able to exactly do what you asked for but I made the exception little more understandable .
Is the following ok ?
```javascript
{  
   "error":{  
      "root_cause":[  

      ],
      "type":"reduce_search_phase_exception",
      "reason":"[reduce] ",
      "phase":"query",
      "grouped":true,
      "failed_shards":[  

      ],
      "caused_by":{  
            "type":"bucket_type_mis_match_exception",
            "reason":"Bucket types are Incompatible",
             "caused_by":{  
                      "type":"incomparable_exception",
                       "reason":"The Buckets cannot be compared as one is of type LongTerms and the other is of type StringTerms",
                                  "caused_by":{  
                                              "type":"class_cast_exception",
                                                "reason": "org.elasticsearch.search.aggregations.bucket.terms.LongTerms$Bucket cannot be cast to org.elasticsearch.search.aggregations.bucket.terms.StringTerms$Bucket"
            }
         }
      }
   },
   "status":503
}
```

I introduced two exceptions IncomparableException.java and BucketTypeMisMatchException.java,
so as to better understand exceptions instead of just throwing class Cast exception which can be anything.  I threw IncomparableException in StringTerms.java where the comparison takes place and failed.
and caught the exception at InternalTerms at line : ordered.insertWithOverflow(b); which caused the comparision.

I wanted to achieve the goal "mention the actual field name" goal  but I don't know where to get actual field name from as the exception happens in InternalTerms level at which level I don't know how to find the field name.May be I am missing something. 

I will debug further to achieve "mention the actual field name" goal ..

Before that can you tell me if the new error message makes it a little bit more readable and understanding ? . I made the exceptions in such a way that at least people who have read the internal reading from https://www.elastic.co/guide/en/elasticsearch/reference/1.6/search-aggregations-bucket-terms-aggregation.html can understand.

Please correct me if I am wrong .

[I found that even https://github.com/elastic/elasticsearch/issues/12675 is connected to this as per the basic of the issue .]

**Comment by clintongormley** [comment]
@HarishAtGitHub that sounds like progress!  One thing to mention is that we have reduced the number of exceptions in master, so we wouldn't  be keen on adding new ones.  I'm guessing you're developing against 1.7?  Rather target master.  If you want to open a PR to get some feedback about what you've done so far, feel free.  May save some development time.

**Comment by HarishAtGitHub** [comment]
I am working on my [fork](https://github.com/HarishAtGitHub/elasticsearch) which is just 62 commits behind actual master . 
and my build says elasticsearch-2.0.0-beta1-SNAPSHOT . so I think it is almost new ...
yes I saw many exceptions like [here](https://gist.github.com/HarishAtGitHub/ae7fc8a69563964e2b97) , but I found nothing suited my requirement , so went on with a new one .
may be I am wrong, I will revisit.

I will clean up my small work and will open a PR by tomorrow ..

**Comment by HarishAtGitHub** [comment]
@clintongormley as per your suggestion . I have made a pull request https://github.com/elastic/elasticsearch/pull/12821 with a detailed commit log, explaining why I did it like this .

this is just PATCH-1 . this will be extended so that other terms can also handle the exceptions on comparing the same way ...

Please let me know if the approach is ok, so that I can continue.
