### ISSUE TITLE
Symlink support on windows

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#12170]
We currently support symlinks with SecurityManager, and have tests. However, the symlink test always fails on windows. While the permission for the link is correctly setup, on windows, permission is not automatically granted for the target of the link.

We could possibly solve this by explicitly adding permission for the target, whenever we add a link to the policy.

**Comment by clintongormley** [comment]
@rjernst do you know if this has been resolved?

**Comment by rjernst** [comment]
AFAIK, this has not been fixed. We still have an "assume not windows" in the test `EvilSecurityTests.testSymlinkPermissions()`.

**Comment by rmuir** [comment]
Er, but that was placed here by you for this issue. 

keep in mind that "symlinks" on windows are really a different thing than unix ones. If you have an issue with how filepermission works for the windows case there, I strongly suggest opening an openjdk issue. We can't work around it here, it needs to be fixed in the right place.

**Comment by rjernst** [comment]
> Er, but that was placed here by you for this issue.

Yes, I simply created this issue after investigating a build failure on windows. I have no problem with closing saying this is an issue with java+windows.  We should probably document this limitation, although I'm not sure where/if we currently document what "symlink support" we have.

**Comment by rmuir** [comment]
Was there actually a build system running with permissions to create the links? FYI that is probably indicative of a bigger problem: it means it was running code as administrator.

See thats the thing with symlinks on windows, they work differently, and you need special permissions that ordinary users dont have. Definitely more of an esoteric thing...

**Comment by ayanovsk** [comment]
Was running ./gradlew check after ./gradlew assemble per instructions about setting up.
It was running for almost 2 hours, then it failed and did not finish run, I guess because of this issue (see below).
Maybe I should not have been running this ./gradlew check; did not expect it being so long;
frankly, do not understand much, was just following initial instructions on setup and check.
Would it do it this way on anyone using Windows ?
------
ERROR   0.01s J0 | EvilSecurityTests.testDuplicateDataPaths <<< FAILURES!
   > Throwable #1: java.nio.file.FileSystemException: C:\install_folder\elasticsearch\elasticsearch\qa\evil-tests\build\testrun\test\J0\temp\org.elasticsearch.bootstrap.EvilSecurityTests_17891422E1881457-001\tempDir-009\link: A required privilege is not held by the client.
   >    at __randomizedtesting.SeedInfo.seed([17891422E1881457:7567B21FC9BF5BBE]:0)


> Task :qa:evil-tests:test FAILED
Tests with failures:
  - org.elasticsearch.bootstrap.EvilSecurityTests.testDuplicateDataPaths

JUnit4 test failed, ant output was:
   [junit4] <JUnit4> says hallo! Master seed: 17891422E1881457
 

BUILD FAILED in 1h 41m 57s
2685 actionable tasks: 2176 executed, 509 up-to-date
------
