### ISSUE TITLE
Fix time sensitive percolator queries

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#12179]
Percolator queries are parsed to a Lucene query at percolator query creation time. It matter what fields are in the mapping at percolator creation time. This is why ES requires fields to exist in the mapping when a percolator query is added. 

However some percolator queries are even more sensitive to when they are parsed:
* If a range query contains `now`.
* If a field in some queries contain wildcards. (depending of what the fields are resolved at percolator query parse time)

For the first case there is a workaround, but there is an issue with it (#12122), so we can do better.

With the query refactoring, queries are going to be parsed on the coordination node and the transformed in an intermediate format that gets send to nodes actually executing the queries. On these nodes this intermediate format is transformed into a Lucene query.

The percolator could for some queries that are time sensitive store the intermediate format instead of the Lucene query. When the a percolator evaluates a query in an intermediate format it just transforms it into a Lucene query before percolating a document.

**Comment by rjernst** [comment]
Does this late binding mean errors (missing fields) would not be surfaced until documents are percolated?

**Comment by martijnvg** [comment]
yes, the errors would be known when documents are percolated, but because the the percolator queries haven't been parsed into their final form, it should be possible to add the missing field to the mapping.

**Comment by jpountz** [comment]
Is it something we can move forward with now that query refactoring landed?

**Comment by javanna** [comment]
> Is it something we can move forward with now that query refactoring landed?

yes now that we have the infra for parsing into our own intermediate objects, we can look into migrating the percolator to actually make use of it.

**Comment by javanna** [comment]
I chatted with @martijnvg about this. Using our own intermediate query objects would make it possible to only parse the json of percolator queries at index time (`QueryParser#fromXContent`) and delay the rest to the percolation time e.g. mappings, wildcards and now resolution (`QueryBuilder#toQuery`). This would allow us to potentially remove the need for strict field resolution in the percolator, similarly to what we did for aliases when we moved parsing to search time rather index time.

On the other hand, #13646 relies on calling `Query#extractTerms` in lucene so that we can index the terms extracted out of each query, and that requires calling `QueryBuilder#toQuery` at index time, which also requires again strict field resolution. It seems like these two are conflicting changes and #13646 is much more important as it brings bigger benefits, so maybe we should simply close this issue.
