### ISSUE TITLE
Record applied _templates when creating indices

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#12220]
It'd be nice if we have a meta field (optional?) that stored what _templates were applied when creating an index.

It's simple enough to figure this out when there are a few templates and indices, but becomes difficult if there are multiple ordered templates.

**Comment by clintongormley** [comment]
We already log this information https://github.com/elastic/elasticsearch/pull/8646 - i definitely don't think we should store it.  Not least of all because templates can be changed, and so the stored value may have nothing to do with the old value.

If you need to debug this, then it is easy to just create a new index with the current template settings and see what comes out in the logs.
