### ISSUE TITLE
Invalid root_cause for mustache_exception

### ISSUE THREAD

**Issue by spalger** [elastic/elasticsearch#12292]
In the JavaScript tests I'm trying to validate the error output when specifying an invalid mustache template, and while the correct error is produced, it is not sent in the API response as the root cause.

@colings86 mentioned this is likely a bug in the exception XContent rendering. (whatever that means :smile_cat:)

Here is a trace of the request:
```
  -> POST http://localhost:9406/_render/template
  {
    "inline": "{ \"query\": { \"match\": { \"text\": \"{{{my_value}}\" } }, \"size\": {{my_size}} }",
    "params": {
      "my_value": "bar",
      "my_size": 100
    }
  }
  <- 500
  {
    "error": {
      "root_cause": [
        {
          "type": "script_exception",
          "reason": "Failed to compile inline script [{ \"query\": { \"match\": { \"text\": \"{{{my_value}}\" } }, \"size\": {{my_size}} }] using lang [mustache]"
        }
      ],
      "type": "script_exception",
      "reason": "Failed to compile inline script [{ \"query\": { \"match\": { \"text\": \"{{{my_value}}\" } }, \"size\": {{my_size}} }] using lang [mustache]",
      "caused_by": {
        "type": "mustache_exception",
        "reason": "Improperly closed variable in query-template:1"
      }
    },
    "status": 500
  }
```

And the test that produced it: https://github.com/elastic/elasticsearch/blob/d4b94a9be2f0f519083c79c61dc9b6bbe67b7387/rest-api-spec/src/main/resources/rest-api-spec/test/template/30_render_search_template.yaml#L52-L55

**Comment by colings86** [comment]
From talking to @clintongormley and @kimchy, the `root_cause` is actually correct here as it is supposed to stop at the `script_exception` since the `mustache_exception` is a implementation detail. The problem here is that there is a difference in implementation between the exception checking on the Java client REST tests and the JS REST tests (and possibly other clients too). The Java client REST tests implementation presumably gets an Exception object (rather than a JSON representation) and will check the messages for all causes (maybe @javanna can confirm that?) whereas the JS Client REST tests implementation checks the rendered JSON and looks only at the `root_cause.reason` field. So the question is which implementation to change. Should the Java implementation only check the root cause as defined by the ExceptionsHelper? or should the JS implementation (and other clients potentially) be changed to check all `reason` fields under `error`?

**Comment by colings86** [comment]
Looking at [DoSection](https://github.com/elastic/elasticsearch/blob/4c981ff4bfc250080d521af105b5e8589c9fc517/core/src/test/java/org/elasticsearch/test/rest/section/DoSection.java#L105) it looks like we take the string value of the `error` object in the JSON response and try to match it to the regex.

**Comment by clintongormley** [comment]
@spalger Shouldn't you just be including the rest of the structured data in the exception object that youc reate? and rendering it as part of stringification?

**Comment by spalger** [comment]
Yeah @clintongormley, I'm going to revamp the exception message a bit to include the related issue information so that the test will pass and the errors will be more informative. Thanks all :)
