### ISSUE TITLE
`mvn package` doesn't handle dirty workspace correctly

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#12320]
Follow-up from #12307.

If I check out an older commit, clean and compile the workspace, then check out a newer commit and run `mvn package`, the workspace is not completely clean.

Here's a reproduction:

```bash
git checkout c2c8956
mvn clean compile test-compile
git checkout pr/12307
mvn package -Drun -DskipTests
```

And then running the ES server will fail.

It looks like this is a known issue with Maven: https://cwiki.apache.org/confluence/display/MAVEN/Incremental+Builds but nevertheless, this issue can track any progress here.

**Comment by rmuir** [comment]
Note that also the `maven-shade-plugin` in many cases "replaces" the generated jar artifact and also has similar problems. @jaymode and I spent a good amount of time just the last few days tracking down issues with that in another project. 

The hack used there is only evil in that it will make things slow (https://github.com/elastic/securemock/commit/181f732ea082c67dc559edb9f1c7b7338c19c50c). But maybe its not so bad, packaging is mostly not slow because of compilation, its because of rpm/deb/shading which we are looking at moving out to separate modules in other issues.

**Comment by clintongormley** [comment]
Closing as we've moved to gradle
