### ISSUE TITLE
When a query_string contains stop words and the default_operator is "AND" no results are returned

### ISSUE THREAD

**Issue by jdchmiel** [elastic/elasticsearch#12347]
I would expect stop words to be ignored for an "AND" search?

**Comment by clintongormley** [comment]
It is really helpful if you provide an example of what you're doing.  Without an example I have to guess what the problem is. Stopwords are ignored:

    PUT t
    {
      "mappings": {
        "t": {
          "properties": {
            "text": {
              "type": "string", 
              "analyzer": "english"
            }
          }
        }
      }
    }
    
    PUT t/t/1
    {
      "text": "black and white"
    }
    
    PUT t/t/2
    {
      "text": "black white"
    }
    
    GET t/_search
    {
      "query": {
        "query_string": {
          "default_field": "text",
          "default_operator": "AND", 
          "query": "black and white"
        }
      }
    }

Returns:

      "hits": [
         {
            "_index": "t",
            "_type": "t",
            "_id": "2",
            "_score": 0.2712221,
            "_source": {
               "text": "black white"
            }
         },
         {
            "_index": "t",
            "_type": "t",
            "_id": "1",
            "_score": 0.2712221,
            "_source": {
               "text": "black and white"
            }
         }
      ]


I'm guessing that you aren't specifying the field that uses the analyzer with the stopwords, and instead you're querying the `_all` field, which uses the `standard` analyzer (not stopwords)

**Comment by jdchmiel** [comment]
Ahh you are exactly correct. I was specifying the field, but not specifying the analyzer. When I set it to "snowball" (with a coworkers help) it all acted as expected.
