### ISSUE TITLE
Empty and/orFilter inside hasParent filter causes NULLPointerException

### ISSUE THREAD

**Issue by santanusinha** [elastic/elasticsearch#12383]
In my application, a bunch of filters are generated on the fly from client side requests. As a result there might be situations where there can be empty and filter list. This is causing a NPE in elasticsearch.

I have provided a detailed test case and the output log [here](https://gist.github.com/santanusinha/45c5bcbf6afb6c67eb63)

**Comment by clintongormley** [comment]
@javanna one for the list

**Comment by javanna** [comment]
I would expect this to be fixed in master after the query refactoring changes. That said it is hard to test given that queries and filters got merged. Also and and or queries have been removed. Anyways we did find different cases where queries would convert to null and that could cause NPEs which we have lots of tests for at the moment. Closing.
