### ISSUE TITLE
Installation from package repository on Debian fails to pickup limits config

### ISSUE THREAD

**Issue by ayashjorden** [elastic/elasticsearch#12404]
Hi,
I've ran into an issue with ES not picking up limits configuration when installing using apt-get.

System descrtiption:
Debian8 with openJDK:
```
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-1~deb8u1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
```

I've configured /etc/deafult/elasticsearch to support mlock.all and increased the nofile for the ES user, but even doing so, when cURL-ed ```es:9200/_nodes/process?pretty```, I got mlock.all false and max_file_descriptors=65K (where I set it to 262144).

After digging throughout the system and with the community, I scanned again ```/etc/default/elasticsearch``` and found a pointer to ```/usr/lib/systemd/system/elasticsearch.service```.

After modifying ```LimitNOFILE=262144``` and ```LimitMEMLOCK=infinity``` and restarting ES, mlock.all was true and max_file_descriptors was set to 262144.

Is this the way it intended to be used? if so, should be documented more explicitly on ES site.
If not, what should be done (ontop of [this](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/setup-service.html)) in order to enable mlock.all and increase the max_file_descriptors ?

I'll be happy to provide additional info if needed.

Thanks,
Yarden

**Comment by clintongormley** [comment]
Yeah I think you're not the first person to run into this issue.  We should definitely document it more explicitly.  I wonder if we should actually change the comments in `config/elasticsearch.yml` in the RPM/deb to point users to the right file.

**Comment by ayashjorden** [comment]
Hi Clinton,
I'm not the systemd expert, but if not to much of a bother for you, can you elaborate about the relationship between */etc/elasticsearch/elasticsearch.yml* <=> */etc/default/elasticsearch* <=> */usr/lib/systemd/system/elasticsearch.service*, that would be awesome.

The thing that I'm missing is whether should I've edit only *elasticsearch.service* or */etc/default/elasticsearch* or both?

Thanks,
Yarden

**Comment by clintongormley** [comment]
the settings in elasticsearch.service are passed as custom settings (not sure if in an env variable or on the command line) but they override what is set in the config file

**Comment by ayashjorden** [comment]
Thanks

**Comment by tlrx** [comment]
> I'm not the systemd expert, but if not to much of a bother for you, can you elaborate about the relationship between /etc/elasticsearch/elasticsearch.yml <=> /etc/default/elasticsearch <=> /usr/lib/systemd/system/elasticsearch.service, that would be awesome.

Systemd uses the file `/usr/lib/systemd/system/elasticsearch.service` to manage the elasticsearch service. Every custom setting like `LimitNOFILE=262144` must be defined directly in this file.

The executable to launch as a service by Systemd is indicated in the `ExecStart` setting. This setting is special compared to other settings because it is one of those that accept environment variables (ex: `-Des.default.config=$CONF_FILE`). We cannot do things like `LimitNOFILE=$BLA`.

The environment variables that can be used when starting/stopping the service are defined which `Environment` settings. We defined default values in the `elasticsearch.service` file but it is possible to override the default values in the file '/etc/default/elasticsearch' (that's the role of the `EnvironmentFile' setting).

The environment variables indicate useful paths to elasticsearch, like where to load the the configuration file `elasticsearch.yml`.

Finally, Systemd uses /usr/lib/systemd/system/elasticsearch.service
to start the service, then potentially overrides some paths using /etc/default/elasticsearch, then start elasticsearch which loads /etc/elasticsearch/elasticsearch.yml.

**Comment by ayashjorden** [comment]
@tlrx , thanks for the detailed explanation.
So, my question now is: why the configuration in ```/etc/default/elasticsearch``` didn't kick in when started ES service on my hosts? **only** when I modified ```/usr/lib/systemd/system/elasticsearch.service``` file, the settings in it worked.

**Comment by clintongormley** [comment]
We should:

* update docs to explain process
* add comment to config file pointing to elasticsearch.service, etc
* add comments above config elements overwritten by other files, pointing to those files

**Comment by abraxxa** [comment]
This is **really** annoying as you have to edit /usr/lib/systemd/system/elasticsearch.service on every `apt update` to uncomment LimitMEMLOCK=infinity which makes automating cluster updates hard because a manual edit is required!
Furthermore the last line `# Built for Distribution: Deb-2.3.2 (deb)` also changes with every version and is displayed in the diff.
I'm wondering why `LimitMEMLOCK=infinity` isn't the default which would also circumvent the problem.
Having two different debian packages, one for systemd and one for SysV might be helpful as well.

**Comment by jasontedor** [comment]
@abraxxa You do not have to edit `elasticsearch.service` on every update. Instead, create a directory `/usr/lib/systemd/elasticsearch.service.d/memlock.conf` with the contents

```
[Service]
LimitMEMLOCK=infinity
```

and set the correct permissions. These are called drop-in units and `man systemd.unit` covers them:


> `There are two methods of overriding vendor settings in unit files: copying the unit file from /lib/systemd/system to /etc/systemd/system and modifying the chosen settings. Alternatively, one can create a directory named unit.d/ within /etc/systemd/system and place a drop-in file name.conf there that only changes the specific settings one is interested in. Note that multiple such drop-in files are read if present.`

> `The advantage of the first method is that one easily overrides the complete unit, the vendor unit is not parsed at all anymore. It has the disadvantage that improvements to the unit file by the vendor are not automatically incorporated on updates.`

> `The advantage of the second method is that one only overrides the settings one specifically wants, where updates to the unit by the vendor automatically apply. This has the disadvantage that some future updates by the vendor might be incompatible with the local changes.`

Please note that this is only a subset of the content of that man page (this is from `systemd` 225).

With the above solution, you no longer need to edit the unit file.

> I'm wondering why `LimitMEMLOCK=infinity` isn't the default which would also circumvent the problem.

Because locking memory requires special permissions and should be a deliberate choice made by system operators.

**Comment by abraxxa** [comment]
@jasontedor thanks for the great info! Can this be added to the package docs?
The Debian 8 manpage for systemd.unit seems to be too old to contain any infos about drop-in unit but the online version at https://www.freedesktop.org/software/systemd/man/systemd.unit.html does.

**Comment by clintongormley** [comment]
@abraxxa this has been added to the documentation here: https://www.elastic.co/guide/en/elasticsearch/reference/master/setting-system-settings.html#systemd

**Comment by abraxxa** [comment]
Thanks Clinton!
