### ISSUE TITLE
bug with list indexing in groovy scripts

### ISSUE THREAD

**Issue by mwiebusch78** [elastic/elasticsearch#12426]
There seems to be a problem with list indexing in Groovy scripts in elasticsearch 1.7.0. I have the following document in my database:

    {
        "name": "Test",
        "numbers": [20, 15, 10, 5]
    }

I use function_score to boost on a specific element of "numbers" field:

    POST _search
    {
        "query" : {
            "function_score" : {
                 "query" : {"match" : { "name" : "Test"}},
                 "script_score" : {"script" : "doc['numbers'].get(0)"},
                 "boost_mode" : "replace"
            }
        }
    }

This returns

    "hits": {
      "total": 1,
      "max_score": 5,
      "hits": [
         {
            "_index": "myindex",
            "_type": "mytitle",
            "_id": "AU67v7GsYH4LIlLusnu1",
            "_score": 5,
            "_source": {
               "name": "Test",
               "numbers": [
                  20,
                  15,
                  10,
                  5
               ]
            }
         }
      ]
    }

The score ends up being the last element of the list. get(1) gives me the next-to-last element, and get(-1) the first element. I assume that's not the inteded behaviour?

**Comment by jasontedor** [comment]
@mwiebusch78 This is due to the way that [multi-value fields are indexed](https://www.elastic.co/guide/en/elasticsearch/guide/current/complex-core-fields.html#_multivalue_fields). In particular, the ordering of the elements is not available at search time.

My recommendation would be to at index time extract the first value of the `numbers` field into another field. This will make the first value available at scoring time.
