### ISSUE TITLE
Combine YUM Repo into one

### ISSUE THREAD

**Issue by dhollinger** [elastic/elasticsearch#12493]
Currently for every "minor release" version change, a new YUM repo is created. For those of us using Enterprise Linux (RHEL, CentOS, Oracle Linux), that means we have to add a new repository for every minor release change.

Could we get a consolidated YUM repository for ElasticSearch RPMs?

**Comment by EagleDelta2** [comment]
Might be a good idea to discuss the same thing for Debian/Ubuntu repositories as well.

**Comment by clintongormley** [comment]
@electrical you set it up this way in the beginning.  What was the reasoning back then?

**Comment by electrical** [comment]
A bit of history around this.
We started building the repo's when we were still at 0.90.x and 1.x was coming close.
Since there was so much stuff that would break with upgrading to 1.x from 0.90.x we wanted to avoid users accidentally doing an upgrade and getting 1.x install and breaking everything.
Because of this we decided on separate repo's to avoid accidental breakage.

We continued with this since there was always a chance that if you would upgrade from 1.0.x to 1.3.x for example things could break as well ( java serialization and other things )

Our main concern was ensuring users experience by avoid accidental breakage.

I do agree its not easiest to manage solution but the safest we could think of.
Nobody wants their cluster to break because a sysadmin decides to do an apt-get upgrade :-)

**Comment by dakrone** [comment]
> Nobody wants their cluster to break because a sysadmin decides to do an apt-get upgrade :-)

At the same time, a lot of admins expect that doing an `apt-get upgrade` will give them the latest version of ES with security fixes and all that. I would suggest that it would be better to err on the side of upgrading than leaving an old (insecure) version out there because an admin didn't add a new repo?

**Comment by clintongormley** [comment]
But perhaps we should keep using separate repos for major version upgrades?

**Comment by dakrone** [comment]
> But perhaps we should keep using separate repos for major version upgrades?

+1 to repos for 1.x, 2.x, and 3.x

**Comment by EagleDelta2** [comment]
@dakrone Same thing on the RHEL side of things, we expect to be able to get the latest updates from a single repo. Especially on the RHEL side where tools like Satellite and Spacewalk are used, we end up combining all the Elasticsearch Repos into a single channel (spacewalk) anyway and good admin practices would be testing the upgrades before pushing to production anyway.

It should never be the vendor's job to enforce Enterprise IT Admin Best Practices.

**Comment by dakrone** [comment]
@EagleDelta2 RHEL and debian do this by separating the packages by name, for example, the "maven" package and the "maven2" (old version) package so that they are separated, so the vendor does do this.

**Comment by EagleDelta2** [comment]
@dakrone For major release updates, yeah.

I'm more concerned with minor releases having different repos. I.E. pulling a new repo after two updates because the minor release changed.... or pulling several new repos because we want to test every version from 1.4.2 (our version) up to latest.

**Comment by dakrone** [comment]
@EagleDelta2 I agree for the major updates, I think there should be a 1.x and 2.x repo, because 2.0.0 would break a lot of things if people do a `dnf update` or `apt-get upgrade` and suddenly jumped from 1.7.1 to 2.0.0, but I do agree someone should be able to have a single repo to upgrade from 1.5.0 to 1.7.1. Admins can specifically pin a version if they don't want it to be upgraded.

**Comment by clintongormley** [comment]
This is now part of our release process - we use the same repo for minor versions, and a new repo for major versions

**Comment by clintongormley** [comment]
Apparently some more tweaks are required - reopening
