### ISSUE TITLE
Should we specify JVM versions in docs or link to support matrix?

### ISSUE THREAD

**Issue by joshuar** [elastic/elasticsearch#12499]
In our reference documentation, we currently specify what JVM versions are supported on the setup page:

https://www.elastic.co/guide/en/elasticsearch/reference/current/setup.html

This is just duplicating the information in our support matrix here:

https://www.elastic.co/subscriptions/matrix

Are we worried about the reference and support matrix getting out of sync?  Shouldn't we just refer users to the support matrix?

**Comment by eskibars** [comment]
+1 to linking rather than duplicating with the potential to get out of sync.  It's just one less thing to forget about.

**Comment by palecur** [comment]
Agreeing pretty hard with @eskibars here.

**Comment by ppf2** [comment]
Currently, this is causing confusion, esp. around OpenJDK 8 support.  

The reason why Oracle JVM 1.8 appears in the [matrix](https://www.elastic.co/support/matrix#show_jvm) but not Iced Tea OpenJDK 8 is because we haven't run enough tests against OpenJDK 8 at this time.  While Iced Tea OpenJDK 8 may work fine (and many users are using it), it is not currently considered an officially supported Java version.

The way the documentation is written today (https://www.elastic.co/guide/en/elasticsearch/reference/2.3/setup.html#jvm-version) can be a bit misleading.

>Elasticsearch is built using Java, and requires at least Java 7 in order to run. Only Oracle’s Java and the OpenJDK are supported. The same JVM version should be used on all Elasticsearch nodes and clients.
>We recommend installing the Java 8 update 20 or later, or Java 7 update 55 or later. Previous versions of Java 7 are known to have bugs that can cause index corruption and data loss. Elasticsearch will refuse to start if a known-bad version of Java is used. 

So let's update the documentation to cross reference the https://www.elastic.co/support/matrix#show_jvm instead :)

**Comment by debadair** [comment]
The docs link to the support matrix as of 5.0: https://www.elastic.co/guide/en/elasticsearch/reference/5.0/setup.html#supported-platforms
