### ISSUE TITLE
Make startTime part of ActionRequest

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#12512]
At the moment the _search api ensure that the current time (useful for scripts with now etc.) is consistent across all shards where the search request executed. This is because all the search related transport action extend from `AbstractAsyncAction`, which records the startTime of an request. 

What I think would be better if startTime becomes part of the ActionRequest (or an immediate abstract subclass) itself and for shard level related request classes we would then need another base class. So that enforcing that current time will evaluate constantly in all apis.

**Comment by andyb-elastic** [comment]
It looks like the timekeeping mechanism mentioned here has changed - `TransportSearchAction` now creates a `SearchTimeProvider` [when beginning search execution](https://github.com/elastic/elasticsearch/blob/f8830b7b43e51935134817269dcebe4766338ace/server/src/main/java/org/elasticsearch/action/search/TransportSearchAction.java#L180).

Since there hasn't been activity here I'll close this issue - let me know if I'm misunderstanding and this is still something we want to do
