### ISSUE TITLE
question regarding _msearch?

### ISSUE THREAD

**Issue by lokeshhctm** [elastic/elasticsearch#12612]
I am using msearch API.
I used it to send 20 request and response of each request have time taken like 200ms - 500ms but total Multi request is taking 5 seconds.
I am wondering if elastic search msearch API internally run requests sequentially.
Or it is in parallel, is there some limit of maximum it runs in one batch. If it runs in batch, can we change the batch size?

**Comment by xuzha** [comment]
Hi @lokeshhctm 

Please ask questions like these on the forum instead: https://discuss.elastic.co/, many ES users would be more helpful. 

ElasticSearch will issue the 20 async search requests. So I will say ES exec these search in parallel. There is no batch. 

In addition, it might make sense not to put many requests in one multi search request, because the slowest of these queries will determine the total response time of your request and slow down all others. And also, the performance dependence on lots of factors, such as query complexity and network IO.

**Comment by spinscale** [comment]
You might issue too much requests, so that the thread pools on your system (scaled by the number of CPUs) are running those requests sequentially instead of parallel. Check your thread pool stats/infos. See https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-thread-pool.html, https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-threadpool.html

Closing in order to continue this discussion in the forum.
