### ISSUE TITLE
BytesStreamsTests.testAccessAfterClose is ignored

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#12620]
This test has @Ignore with this comment:

```
// we ignore this test for now since all existing callers of BytesStreamOutput happily
// call bytes() after close().
```

**Comment by xuzha** [comment]
I think we could remove this test. 

>
```
hhoffstaette added a note on Mar 4, 2014
@kimchy explicitly wanted close() a no-op because many callers still call close() prematurely and then something else.
>```

If close () is a no-op, then why we need this test. If the requirement changed now, we should change close() method.

**Comment by rjernst** [comment]
We should fix any code that is calling `bytes()` after `close()`. This sounds very broken and error prone!

**Comment by jpountz** [comment]
While I agree with Ryan, I looked into making this change in order to remove the AwaitsFix and this was problematic when the stream is wrapped with a `DeflaterOutputStream`. The `DEFLATE` format has an end marker that `DeflaterOutputStream` writes either when you cann `finish()` or `close()`. Since `finish()` is specific to this `OutputStream` implementation, it is not practical. So now imagine you want to generate compressed bytes (which is something we often do in Elasticsearch):

```java
try (BytesStreamOutput out = new BytesStreamOutput();
        OutputStream compressedOutput = CompressorFactory.COMPRESSOR.streamOutput(out)) {
    data.writeTo(compressedOutput);
    compressedOutput.flush();
    BytesReference compressedBytes = out.bytes();
}
```

This does not work because the end marker has not been written yet when we call `out.bytes()`. And if we move the last line outside of the `try`block, then `out.bytes()` is called after `out` is closed which is what we want to prevent.

As a consequence I'd like to close this bug as a won't fix. Please suggest if you have ideas to work around that problem.

**Comment by rjernst** [comment]
Thanks for the analysis @jpountz. I agree with you after further thought. This is similar to ByteArrayOutputStream, in that you can get access to the byte array after the stream after or before the stream as been closed. Closing only means you can no longer write to the stream.  I opened #26392 to remove the test.
