### ISSUE TITLE
elasticsearch hangs when execute query on analyzed filed  

### ISSUE THREAD

**Issue by shorman88** [elastic/elasticsearch#12669]
Hi,

I have kibana and elasticsearch installed to analyse the webservers logs.

When i try to get the average request time for 5 or 10 request_urls the elasticsearch hanged and i have to restart the cluster.
![visualize](https://cloud.githubusercontent.com/assets/7731747/9084466/a549befe-3b7c-11e5-8604-1f1ed5ebde8b.png)

Am i doing something wrong?

Note that by choosing .raw field i get results.

Thanks

**Comment by colings86** [comment]
Please use https://discuss.elastic.co for question on using Elasticsearch.Those forums are specifically set up for questions whereas this list is reserved for bug reports and new feature requests.

If you look at your Elasticsearch server logs you will probably find out of memory errors which correlate with the times you performed these searches. Analyzed fields tends to be very high cardinality and lead to heavy memory pressure (including the JVM running out of available heap) due to this high cardinality. This is why a warning is shown in the Kibana UI when you select an analyzed field to use as part of an aggregation
