### ISSUE TITLE
Remove mapping source transform scripts

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#12674]
The ability to transform the `_source` field before indexing (while storing the original `_source`) is confusing and error prone.  Most of what you can do with it can already be done with `copy_to`.  It also makes it difficult to know where a field value has come from, which means it can't support highlighting.

I think this is not widely used at all and should be removed in 2.0 (while continuing to support indices which already use it for 2.x releases)

**Comment by nik9000** [comment]
> Most of what you can do with it can already be done with copy_to

Originally transforms were written because I needed conditional ```copy_to```. Like "only documents with namespace == 0 need to copy their text field to the suggest field". We never ended up using it and since its been written people have used it for lots of somewhat unexpected things. Its lots of power.

So I think we have two options:
1. Remove it
2. Move it to a plugin
3. Leave it there and put more big signs on it about how it shouldn't be done

We should also talk about implementing conditional ```copy_to``` again. Its less powerful but its maybe less error prone.

One thing I should mention is that there is a parameter, ```_source_transform``` that you should be able to stick on get and search requests that will re-run the transform on load. Its meant for debugging but it works.

I'm partial to moving source transform to a plugin and no implementing conditional copy_to.

**Comment by clintongormley** [comment]
> I'm partial to moving source transform to a plugin and not implementing conditional copy_to.

sounds good to me

**Comment by pickypg** [comment]
> I'm partial to moving source transform to a plugin and no implementing conditional copy_to.

Sounds great to me too. People miss big signs because they frequently get on the road after them.

**Comment by nik9000** [comment]
Moved to 2.1. I'll totally pick this up early next week but there is 0 chance it'll make it into 2.0.

**Comment by nik9000** [comment]
Now that I'm looking at source transforms it looks half finished. There is support in the Java api to transform on load. But there isn't support in the REST api for it. It'd be so much less confusing if that were possible. Not that it'd be well loved, but less confusing.

**Comment by nik9000** [comment]
I suspect when I first wrote transform I just didn't think about the rest API for that.

**Comment by nik9000** [comment]
Just changed issue to remove rather than break into a plugin because:
1. Its hard to break into a plugin in satisfactory ways. I made an effort and it was just making the problem worse. See #13164.
2. So far as I know no one is really using this in the way it was intended to be used. People are using it as a simple transformation pipeline but its really really really not for that and that causes all kinds of confusion. Logstash is a much better fit. See that abandoned pull request I mentioned above for more. And for me describing what transforms are "really" for.

**Comment by adichad** [comment]
@rjernst confirms over at #13657 that transformed have not been removed in 2.x and will only be deprecated.

request to reinstate the related documentation for example at

https://www.elastic.co/guide/en/elasticsearch/reference/1.7/mapping-transform.html
https://www.elastic.co/guide/en/elasticsearch/reference/1.7/_get_transformed.html

to also work at

https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-transform.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/_get_transformed.html

and maintain deprecation warnings there?
