### ISSUE TITLE
Chown data/logs when installing deb/rpm packages

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#12688]
Issue from https://github.com/elastic/elasticsearch/issues/10671#issuecomment-127457647

If you remove a package then it removes the elasticsearch user/group.  Installing it again will create a new user/group with different IDs, which means that the data and logs directories will no longer be owned by the correct user.

Should we do a chown when installing the package?

**Comment by jeffwidman** [comment]
I was bit by this myself and couldn't figure it out until I ran across @imsaar's helpful post (big thank you!)

It's tough because occasionally the admin wanted it that way, and will be surprised by the `chown`. But something should be done. 

I'd bet that 95% of admins don't customize things (and I don't think it's smart to customize ownership of something like this is you're an admin--change the path instead to non-default directory), so I'd vote for the install routine to `chown` the folders. If you want to be extra cautious, maybe as part of the install routing print a message saying that this was done and the admin needs to redo any customizations if they were done.

**Comment by jasontedor** [comment]
The config directory in `/etc/elasticsearch` needs to be recursively `chown`'ed as well. I have a fix and a test case for this, but I'll keep it in my pocket until #17152 is in.
