### ISSUE TITLE
[Test] Add random write/read errors on azure repository

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#12699]
_From @dadoonet on February 27, 2015 22:32_

As we have in AWS plugin with elasticsearch/elasticsearch-cloud-aws#95, we should add random write and read errors while doing snapshot and restore so we can better handle issues and retry.

_Copied from original issue: elastic/elasticsearch-cloud-azure#76_

**Comment by dadoonet** [comment]
Related to #51

**Comment by tlrx** [comment]
This issue is opened for some time now and has no updates. While we think it's still good to have more testing cases we consider that this is very low priority and we should focus on other issues or add more integration tests. I'm going to close this issue, but feel free to comment and add your opinion.
