### ISSUE TITLE
filter_path does not walk into _source

### ISSUE THREAD

**Issue by peterlimayo** [elastic/elasticsearch#12705]
GET api with filter_path does not allow a dot path into the _source.
Instead of 

.../_search?filter_path=hits.hits._source.address

I need to enter

.../_search?filter_path=hits.hits._source&_source=address

Why doesn't it allow you to specify a path into _source ?

**Comment by tlrx** [comment]
@peterlimayo that's a limitation of the response filtering feature and it is related to the way elasticsearch internally returns the `_source` of documents.

The documentation may help you (see https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#_response_filtering):

> Note that elasticsearch sometimes returns directly the raw value of a field, like the _source field. If you want to filter _source fields, you should consider combining the already existing _source parameter (see Get API for more details) with the filter_path parameter like this:
curl -XGET 'localhost:9200/_search?pretty&filter_path=hits.hits._source&_source=title'

I'm closing the issue since this is not a real bug, feel free to reopen if needed.
