### ISSUE TITLE
Elasticsearch ubuntu init script doesn't prevent to start 2 elasticsearch

### ISSUE THREAD

**Issue by rvrignaud** [elastic/elasticsearch#12716]
On ubuntu 14.04 for Elasticsearch 1.7.0 debian package,
If we start twice elasticsearch very shortly, the pidofproc function doesn't return the PID of the first elasticsearch.
So 2 elasticsearch can be started at the same time. In my case this causes an OOM trigger. 

How to reproduce:

```
# service elasticsearch stop
# service elasticsearch start; service elasticsearch start; 
```

**Comment by clintongormley** [comment]
Hi @rvrignaud 

As a workaround, you can set this in your elasticsearch.yml:

    node.max_local_storage_nodes: 1

**Comment by rvrignaud** [comment]
Hey @clintongormley,
I already have max_local_storage_nodes set to 1 but that doesn't prevent the second java process to start and to allocate memory (XMS and XMX setted to the same value).

**Comment by electrical** [comment]
With the rpm init script we place a lockfile before starting ES and remove it afterwards.
If someone would try a second startup it would find the lockfile and abort directly.
It should be a fairly easy fix to implement this in the ubuntu/debian init script as well.
Since more things are moving to systemd this will not pose an issue later.

**Comment by jordansissel** [comment]
I think the problem here is these two lines of the init script:

* [start-stop-daemon is given `-b` flag](https://github.com/elastic/elasticsearch/blob/master/distribution/deb/src/main/packaging/init.d/elasticsearch#L140
)
* [elasticsearch is given -d flag](https://github.com/elastic/elasticsearch/blob/master/distribution/deb/src/main/packaging/init.d/elasticsearch#L82)

Given the above, I think Elasticsearch is backgrounding itself (`elasticsearch -d`) and `start-stop-daemon` is also forking, so I *think* start-stop-daemon is tracking the pid of the parent Elasticsearch process which immediately dies after Elasticsearch daemonizes.

My suggestion is that one of the two things are changed:
* Don't give `-b` to start-stop-daemon
* or, don't give `-d` to elasticsearch.

**Comment by jordansissel** [comment]
I think this is a dup of https://github.com/elastic/elasticsearch/issues/8796

**Comment by dakrone** [comment]
We now default `node.max_local_storage_nodes` to 1, so closing this.

**Comment by rvrignaud** [comment]
@dakrone as replied here https://github.com/elastic/elasticsearch/issues/12716#issuecomment-128681997 `node.max_local_storage_nodes` set to 1 does not fix the problem. IMHO this should be kept open.

**Comment by dakrone** [comment]
@rvrignaud ahh I see, my apologies! I think this is related to the daemonization that we do and would have to be fixed there then, I'm re-opening this. Thanks for catching this!

**Comment by rjernst** [comment]
I think this was actually fixed by https://github.com/elastic/elasticsearch/commit/5413efc570dfed0db26ede2cc0ef6ab737417748 since we no longer double daemonize.
