### ISSUE TITLE
Node in slow GC without obvious load

### ISSUE THREAD

**Issue by niu-lin** [elastic/elasticsearch#12725]
We have a cluster with 10 nodes which used to work very well. Recently, the cluster become unstable, after some debugging, we found that JVM can go into an unstable state some times without obvious load.
JVM heap usage will go up very quickly and trigger heavy GC and then go back again. This process continuous until at a certain time, the node completely hang up and causing shard rebalancing. However, sometimes, the node can "go back alive" for some seconds causing another round of shard rebalancing. Shard rebalancing continuous  until either bring the whole cluster unresponsive or calm down if one or two nodes triggers JVM OOM.
During the time, no obvious high workload, no slow query logged, only lots of lots slow GC logs.

Below are some screenshots from bigdesk. I'm not sure what I should paste him for experts, please just let me know if you want any additional information.
 
![image](https://cloud.githubusercontent.com/assets/12907027/9135896/8fedfdee-3d44-11e5-8f54-096872a8ad2d.png)
![image](https://cloud.githubusercontent.com/assets/12907027/9135906/a28e0016-3d44-11e5-8639-079931421205.png)
![image](https://cloud.githubusercontent.com/assets/12907027/9135909/ac9331e4-3d44-11e5-93ae-e179ffff1c02.png)

**Comment by clintongormley** [comment]
Hi @niu-lin 

This is a common problem and usually has to do with setting up swap correctly (https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration.html#setup-configuration-memory) but could be due to other factors (eg hardcoding paramters into scripts, so scripts are recompiled frequently).

I suggest that you start by asking in the forum, and open a new issue if you think you've found a bug.  https://discuss.elastic.co/

thanks

**Comment by niu-lin** [comment]
Hi @clintongormley 
Thank you for your response. I believe this has nothing to do with swap because we have disabled swapping and I verified the JVM does not use any swap space by looking at /proc/pid/status.
And for scripts, I'm not quite understand what do you mean by "hardcoding parameters". 
Anyway, I'll move to the forum. Thank you for advice.
Lin
