### ISSUE TITLE
designate master node through cluster api

### ISSUE THREAD

**Issue by charlesmims** [elastic/elasticsearch#12778]
Feature request:
I would like the ability to be able to manually designate a master node for a cluster.

Use case:
I want to have a dedicated master for performance reasons, but I don't want to keep 2 additional dedicated masters as wasted resources waiting for a disaster to happen.
The solution I would like to use is to have a single dedicated master, and make the data notes master-eligible so that one of them can take over if the master fails.  Then, when the master rejoins the cluster, I need a way to make it the master again.  The only way I can think of doing this now is setting each of the data nodes to be non-master-eligible, and restarting the data node that became master when the master node died.  This is suboptimal.

**Comment by clintongormley** [comment]
Hi @charlesmims 

I think this change would be a mistake.  Master nodes, like data nodes, should all be of similar quality, otherwise if one "better" master node fails, then another "worse" master node tries to take over, you could end up just crashing your cluster regardless.

Dedicated master nodes make sense once your cluster is big enough.  They can use cheaper, smaller hardware than the data nodes.  Alternatively, you can also run two instances of elasticsearch on each box: one as dedicated data, and one as dedicated master, with a much smaller heap.

**Comment by charlesmims** [comment]
I disagree with this assessment.  For situations where data nodes are huge beefy boxes, adding the duty of temporarily being master in addition to being a data node shouldn't cause instability unless the data node is already running close to its limits.  At any rate there are countless design decisions like this that elasticsearch admins need to account for already.  I'm probably not the only admin would wants a way to have a dedicated master and be able to survive failure of that master without dedicated backup masters and without having to restart a node to get the cluster back to the original master.

How is running two instances on one machine, one as a dedicated master and one as dedicated data preferable to allowing a data node to temporarily take over as master in the event that a master node goes down?  If you're suggesting that it should be done this way because you would implement it with enough memory set aside for a master instance and reduced memory for the data instance, this isn't any better than having dedicated backup master machines.

The guys in elasticsearch irc chat seemed to think this would be a good feature, can we put it to a vote or something rather than just closing it?

**Comment by charlesmims** [comment]
Another benefit of being able to specify a master is eliminating downtime while a new master is elected, when doing rolling restarts to upgrade, for example.

**Comment by bleskes** [comment]
> How is running two instances on one machine, one as a dedicated master and one as dedicated data preferable to allowing a data node to temporarily take over as master in the event that a master node goes down? 

While it's true that the master and data nodes share the risk of server failures, using two separate processes protects the master from any data/search related pressure (mostly memory and GC). We try to keep things as simple as possible because as you say, there is a lot an admin needs to worry about it. We feel this is a simpler and less error prone solution.

> Another benefit of being able to specify a master is eliminating downtime while a new master is elected, when doing rolling restarts to upgrade, for example.

I a fully agree that a clean master step down API will be handy to have a planned master shutdown go without any service hick up. It's own are radar but at the moment, there are other things higher up on the list - for example, shorten the 3s master election so if a master goes down (planned or not) a new master will be more quickly elected.

**Comment by charlesmims** [comment]
Another use-case for this feature:
Upgrading masters and rolling restarts could be less harrowing than shutting down the current master and hoping master election works.
