### ISSUE TITLE
Show more details of closed indices in _cat/indices

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#12847]
From [this forum post](https://discuss.elastic.co/t/size-of-closed-index/27302).

While we let users know an index is closed using `_cat/indices`, it'd be handy if we could show them things like the number of shards, docs and store size.

**Comment by clintongormley** [comment]
I don't think it is feasible. The only way to get this information is to open the index. About the only thing we could change is to include the primary and replica settings for closed indices (because those come from the cluster state). However, there is no guarantee that they reflect what is on the disk.  You could delete the closed index and add another with the same name and different settings, and we would be none the wiser until trying to open the index.

I think I've just convinced myself that we shouldn't change this.

**Comment by markwalkom** [comment]
There's no chance we can keep some sort of data in cluster state on this?
I think it'd be very useful, even if not just for _cat.

**Comment by bleskes** [comment]
a side note for whoever ends up here looking for info (the feature is still good imho) - a current alternative is to use the [shard stores](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-shards-stores.html)

**Comment by seang-es** [comment]
_shard_stores does not seem to return data for closed indices

**Comment by bleskes** [comment]
shard stores should give you insight into closed indices if the ignore unavailable is set to false. I think that given the lack of interest for this feature and the possible workaround, I'm going to close this as won't fix.
