### ISSUE TITLE
Remove URL from PluginManager

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#12896]
We should be using `URI` instead.

It'd be great to eventually get `new URL(...)` in the forbidden APIs also.

**Comment by rjernst** [comment]
+1

**Comment by rjernst** [comment]
The plugin manager was completely rewritten since creating this issue. It still uses `new URL`, but only in the case that a URL is passed in (in which case the plugin id is not a builtin plugin or a maven identifier).  We need URL because we need to open a connection; URI only has information about the URI, but you still need to call toURL() to get something that can open a connection.

**Comment by dakrone** [comment]
+1, thanks for closing this Ryan
