### ISSUE TITLE
-Des.network.host=_eth0_ binds to ipv6 link-local address

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#12915]
Try this on two linux machines:

bin/elasticsearch -Des.network.host=_eth0_

You will see that it binds to a link-local ipv6 address: 

[2015-08-15 22:59:25,266][INFO ][org.elasticsearch.http   ] [Timberius] bound_address {inet[/fe80:0:0:0:f66d:4ff:fe90:ce0c%2:9200]}, publish_address {inet[/fe80:0:0:0:f66d:4ff:fe90:ce0c%eth0:9200]}

Nodes do get multicast packets from each other, but the address isn't going to work, because its link-local:

[2015-08-15 23:00:19,016][WARN ][org.elasticsearch.discovery.zen.ping.multicast] [Shamrock] failed to connect to requesting node [Bloodstorm][RVsIyNniTq6LYEQmTPRCEA][mac2][inet[/fe80:0:0:0:3e15:c2ff:fee5:d26c%4:9300]]
ConnectTransportException[[Bloodstorm][inet[/fe80:0:0:0:3e15:c2ff:fee5:d26c%4:9300]] connect_timeout[30s]]; nested: SocketException[Network is unreachable];

This makes it tricky to get things working since most machines are dual-stack and we are picking an address that won't go anywhere. Of course you can do -Des.network.host=_eth0:ipv4_ to workaround it.

**Comment by dakrone** [comment]
Confirmed this locally, when I do `bin/elasticsearch -Des.network.host=_wlp3s0_` it binds to the link-local IPv6 address (`bound_address {inet[/fe80:0:0:0:8638:35ff:fe5e:93ce%2:9300]}`) even though this is not a loopback interface. Interestingly enough, it sends multicast **from** the IPv4 address for the `wlp3s0` interface, see:

```
» sudo tcpdump -n -s0 -A -i wlp3s0 udp port 54328                                                                                                                                                            
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on wlp3s0, link-type EN10MB (Ethernet), capture size 262144 bytes
11:21:58.375184 IP 192.168.0.4.54328 > 224.2.2.4.54328: UDP, length 116
E....}@...E-.........8.8.|...   ....z.....elasticsearch Protector.3oLX8kvNSb2wMCxlijXI_Q.Xanadu.domain.192.168.0.4.............85..^........$V...z
```

Since this affects 2.0, what do you think about defaulting `ES_USE_IPV4` to true for the 2.0.0 beta/ga (which fixes this issue for me) and addressing IPv6 fully going forward? I'm concerned about some things:

- People don't think about IPv6 much with firewalls yet, so if they bind to `eth0` and only protect IPv4, they could be in a bad situation (we should carefully test and document using IPv6 with ES)
- Connectivity problems due to a lack of testing coverage since every OS under the sun seems to do IPv6/multicast slightly different (as well as DNS issues with IPv6 also...)
- IPv6 with privacy extensions enabled causing development problems (haven't tested to see how it would affect this yet)
- Current lack of our test coverage for IPv6

I think we could address the last one through the Vagrant testing that @nik9000 has been working on. We should make sure each machine has both the v4 and v6 stacks and we can bind/discover things correctly.

Thoughts?

**Comment by nik9000** [comment]
We could absolutely add more tests around this with vagrant. Spin up a
couple of machines with a private network and have more bats tests. I don't
know if we can do osx vms though.

**Comment by dakrone** [comment]
We should also test IPv6-**only** machines to ensure we have no hard requirement on IPv4-specific behavior.

**Comment by jasontedor** [comment]
We can technically do OS X VMs but we can't legally do OS X VMs until we provision some Mac hardware for our CI infrastructure and run OS X as the host OS. Tests utilizing these VMs could only run on this hardware. 

From the [OS X 10.10 EULA](http://images.apple.com/legal/sla/docs/OSX1010.pdf):

>B. Mac App Store License. If you obtained a license for the Apple Software from the Mac App Store, then subject to the terms and conditions of this License and as permitted by the Mac App Store Usage Rules set forth in the App Store Terms and Conditions (http://www.apple.com/legal/internet-services/ itunes/ww/) (“Usage Rules”), you are granted a limited, non-transferable, non-exclusive license:

> [...]

>(iii) to install, use and run up to two (2) additional copies or instances of the Apple Software within virtual operating system environments on each Mac Computer you own or control that is already running the Apple Software, for purposes of: (a) software development; (b) testing during software development; (c) using OS X Server; or (d) personal, non-commercial use.

**Comment by nik9000** [comment]
It looks like there are a couple of OSX boxes in vagrant atlas too. So that
should be possible.

Nik

**Comment by rmuir** [comment]
> Since this affects 2.0, what do you think about defaulting ES_USE_IPV4 to true for the 2.0.0 beta/ga (which fixes this issue for me) and addressing IPv6 fully going forward?

One problem with that i simple stuff like `localhost` isn't going to work. Stuff like curl is simply not going to care. When I played with this issue, i ended out with all kinds of interesting situations: advertising 127.0.0.1 on ethernet multicast, advertising ipv6 over ipv4, etc. 

I think it was buggy all along but hidden by the fact that things were binding to all interfaces or whatever before?
