### ISSUE TITLE
1.7 and 2.0 missing snapshot rpm packages

### ISSUE THREAD

**Issue by electrical** [elastic/elasticsearch#12984]
1.7 and 2.0 branches are missing the rpm snapshot packages.

**Comment by s1monw** [comment]
can you provide example URLs for this please? It's not clear which misses what, thanks

**Comment by electrical** [comment]
https://s3-eu-west-1.amazonaws.com/build.eu-west-1.elastic.co/origin/1.7/nightly/JDK7/elasticsearch-latest-SNAPSHOT.deb exists for example for the 1.7 branch but there is no rpm equivalent.
For 2.0 branch

https://s3-eu-west-1.amazonaws.com/build-eu.elasticsearch.org/origin/2.0/nightly/JDK7/elasticsearch-latest-SNAPSHOT.noarch.rpm is empty because there rpm is not generated and the symlink we create in jenkins generates an empty file then.

**Comment by dadoonet** [comment]
It's a bug. Maven profiles are executed first then inner properties are evaluated.

We defined:

```xml
    <properties>
                <packaging.rpm.rpmbuild>/usr/bin/rpmbuild</packaging.rpm.rpmbuild>
    </properties>
```

And 

```xml
    <profiles>
        <profile>
            <id>rpm</id>
            <activation>
                <file>
                    <!-- Folks having /usr/bin/rpmbuild available will be able to build the rpm module -->
                    <exists>${packaging.rpm.rpmbuild}</exists>
                </file>
            </activation>
            <modules>
                <module>rpm</module>
            </modules>
        </profile>
    </profiles>
```

When the `profile` part is evaluated, `packaging.rpm.rpmbuild` has not been set yet.
So we end up to evaluate `<exists></exists>`.

That's why this profile is never executed, and the rpm module is not added to the reactor.

I'll come with a fix.

In the meantime, running `mvn deploy -Dpackaging.rpm.rpmbuild=/usr/bin/rpmbuild` might solve the issue.
