### ISSUE TITLE
Log slow queries as json, not binary.

### ISSUE THREAD

**Issue by vvcephei** [elastic/elasticsearch#12992]
In the Java client, you can compose the query either by adding String source chunks or by using another builder, like the Aggregation builder and adding the aggregation to the query. There is a quirk, though: if you use a builder, the only way to contribute it to the query is to first turn it into a byte[]. When you do this, the query ultimately gets logged as half-json, half-binary-string in the slow query log.

That isn't a *problem*, per se, but it's annoying when you're trying to analyze the logs.

I have no opinion about how the query objects are stored in memory, but it would be nice if the slow query log (and full query log if #9172 comes to pass) would log a human readable query.

**Comment by nik9000** [comment]
This seems like a fair request to me.

**Comment by colings86** [comment]
This is fixed by https://github.com/elastic/elasticsearch/pull/13752 in the master branch. The search source is now stored as an object instead of as bytes and so SearchSlowLog will now print the json search request in the slow log rather than the binary bytes. 

Note that until https://github.com/elastic/elasticsearch/issues/10217 is fully complete there will still be some elements of the search request (e.g. sort parameters) which will be rendered as binary bytes since until these are refactored they are still stored in the Search request as bytes.

Closing in favour of the mentioned PRs/issues
