### ISSUE TITLE
On disk replicas not used after node restart if hit low disk watermark

### ISSUE THREAD

**Issue by jimmyjones2** [elastic/elasticsearch#13047]
Today I needed to restart a node in my Elasticsearch 1.7.1 cluster for a firmware update. It's used with time based indices. The disks are over 85% full, but they won't fill for a while so was planning on adding more storage next week. However when I restarted the node, it wouldn't serve any shards as the disk was over the 85% threshold, yet the shards were already on disk and all but the latest time based index was exactly the same as the primary elsewhere in the cluster.

It's not a major issue, just forced me to sort out my disk space situation before being able to restart any other nodes, and it might have been a pain to recover the data if the disk crashed on another node.

```
[node2] low disk watermark [85%] exceeded on [xxxxxx][node3] free: 50.2gb[12.4%], replicas will not be assigned to this node
```

**Comment by clintongormley** [comment]
The problem here is that, while a replica may exist, we have no idea whether the replica is the same as the primary or not (unless the replica is sync flushed).  So we may end up having to copy over the whole primary (while still keeping the replica around just in case) which could push you over the limit.

I think what should happen here is

* existing primaries should be recovered automatically
* sync-flushed replicas should be recovered automatically
* once the index is green, unused shard copies should be deleted (which is what happens now)

It is still possible to get into a deadlock situation, eg:

* two nodes, 1 replica, both nodes over the low watermark
* the primary recovers automatically
* the replica is not sync-flushed, but the node is over the low watermark and so the shard will not recover

In this case, the low watermark can be changed dynamically (and temporarily) to allow recovery.

**Comment by DaveCTurner** [comment]
@ywelsch and I discussed this and concluded that although we could see some ways to improve this situation in 6.x (e.g. nondestructively perform a seq#-based recovery of the existing shard copy rather than making a whole new one) on balance we prefer to close this to indicate that it's not something we foresee working on in the near future. Further feedback, including +1s, is welcome.
