### ISSUE TITLE
Provide case insensitive option for mapping char_filter

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#13045]
mapping char_filter is currently case-sensitive, can be helpful to provide a configurable option for it to perform the replace action in a case-insensitive manner.

https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-mapping-charfilter.html?q=char%20filter

**Comment by rmuir** [comment]
What is the use case? The only purpose of a charfilter is to "hack" the text before the tokenizer, and most tokenizers don't care about case.

**Comment by ppf2** [comment]
Thanks for the feedback, sounds like this is not what the mapping char_filter is intended for so I will close this one out :)  For this particular use case, the end user is trying to use a keyword tokenizer and have some of the terms have synonyms (which doesn't work with keyword), so they are using char_filter as an alternate option.  Workaround here can be to do a -> z, A-> z in the char_filter, or add another char_filter that lowercase everything first.

**Comment by tomfotherby** [comment]
My use case for wanting a case-insensitive mapping `char_filter` is that I have a custom tokeniser which splits on many characters including the forwardslash. However I have some domain-specific words, for example `i/o` that I want to keep as one. So I have a mapping char_filter to do `'i/o => i_fs_o'` and then a `pattern_replace` filter to put it back again (`'pattern'     => '(.*)_fs_(.*)','replacement' => '$1/$2',`).  The problem is that I need to specify every case variate of i/o in the mapping ('I/o','I/O', etc). Since I have 50 or so such keywords, the variations of case bloat the mapping considerably.

**Comment by clintongormley** [comment]
@tomfotherby Use the [pattern-replace character filter](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/analysis-pattern-replace-charfilter.html) instead
