### ISSUE TITLE
terms facet gives wrong count with n_shards > 1

### ISSUE THREAD

**Issue by jmchambers** [elastic/elasticsearch#1305]
I'm working with nested documents and have noticed that my faceted search interface is giving the wrong counts when I have more than one shard. To be more specific, I'm working with RDF triples (entity > attribute > value) and I'm nesting the attributes (called predicates in my example):

    {
      "_id" : "512a2c022f0b4e3daa341e6c8bcf6c2f",
      "url": "http://dbpedia.org/resource/Alan_Shepard",
      "predicates": [
        {
          "type": "type",
          "string_value": ["thing", "person", "astronaut"]
        }, {
          "type": "label",
          "string_value": ["Alan Shepard"]
        }, {
          "type": "time in space",
          "float_value": [216.950]
        },
        ... lots more
      ]
    }

I've created a shell script (https://gist.github.com/1196986) that recreates the problem with a fresh index. The created data set has these totals:

* thing (30)
* creative work (20)
* video game (10)
* tv show (10)
* people (10)

With only __one shard__ the following query gives the correct counts no matter what the size parameter is set to:

    {
      "size": 0,
      "query": {
        "match_all": {}
      },
      "facets": {
        "type_counts": {
          "terms": {
            "field": "string_value",
            "size": 5
          },
          "nested": "predicates",
          "facet_filter": {
            "term": {
              "type": "type"
            }
          }
        }
      }
    }

However, with __more than one shard__ the size parameter affects the accuracy of the counts. If it is equal to or greater than the number of terms returned by the facet query (5 in this case) then it works fine. However, the terms at the bottom of the list start to display low counts as you reduce the size parameter:

With "size" : 4
* thing (30)
* creative work (20)
* video game (10)
* __tv show (9)__

With "size" : 3
* thing (30)
* __creative work (15)__
* __video game (9)__

With "size" : 2
* thing (30)
* __creative work (15)__

So it looks like the sub-totals from some of the shards aren't being included for some reason. BTW I'm on ubuntu and the problem seems to affect all versions of ES I've tried (17.0, 17.1 and 17.6). Any ideas...?

P.S. absolutely loving ES - it's made my life a lot easier :)

**Comment by lloy0076** [comment]
Is this issue likely to be "fixed" given that it appears facets, en masse, are deprecated?

**Comment by clintongormley** [comment]
@lloy0076 it definitely won't be fixed in facets.  However, the same problem exists in aggregations, due the to nature of distributed systems.  We'll leave this issue open as a reminder - at some stage we hope to provide a slower but more accurate version.

**Comment by jodok** [comment]
Yes, if you use the "scatter/gather" pattern you naturally hit the limits of a two-phase approach. When building [Crate.IO](https://crate.io)* (a SQL Database using Elasticsearch, https://github.com/crate/crate) we decided to extend it to support a distributed map/reduce algorithm to provide accurate [aggregations] (https://crate.io/docs/stable/sql/aggregation.html).
**(disclaimer: i'm one of the Crate guys)*

**Comment by otisg** [comment]
@jodok Because @clintongormley used words "slower" and "more accurate" in "we hope to provide a slower but more accurate version", can you comment on the performance and accuracy of your implementation?  Specifically, @clintongormley is implying numbers will be closer to the truth, but not necessarily 100% accurate, and I'm wondering if in case of CrateIO they are always 100% accurate?  And, of course, I'm wondering if you've compared performance of CrateIO approach vs. ES approach (at scale)?  Thanks.

**Comment by jodok** [comment]
@otisg the performance of "normal" queries that don't need the 2-phase map/reduce approach is the same. but when it comes to exact aggregations - they need one more cluster roundtrip. instead of 1. collect data (all shards), 2. merge result (one node) - an additional step is added: 1. collect (all shards), 2. reshuffle data (to multiple nodes) and do aggregation, 3. merge (one node). this requires one more network roundrip in the cluster, but usually this is even less than a ms. this method scales horizontally, performance heavily depends on cardinality and the size of the result set. happy to help running tests on sampledata on a demo cluster.

**Comment by otisg** [comment]
@clintongormley @kimchy couldn't ES "borrow" the the approach/idea that Crate or Solr(Cloud) use?  Both give 100% accurate counts.

**Comment by ppf2** [comment]
Facets have been deprecated for a while now and have been removed from master/2.0 (https://github.com/elastic/elasticsearch/pull/7337) with aggregations being the replacement.  Time to close this ticket?

**Comment by clintongormley** [comment]
Agreed

**Comment by thanodnl** [comment]
I think it is worth to keep open this ticket as the aggregations framework suffers from the same issue with terms aggregates on more than 1 shard.

**Comment by clintongormley** [comment]
I've opened https://github.com/elastic/elasticsearch/issues/12316 instead
