### ISSUE TITLE
Can't use complex params with lang=expression scripts?

### ISSUE THREAD

**Issue by tko** [elastic/elasticsearch#13071]
I'm trying to port the following simple inline function_score / script_score script from groovy to expression to avoid the need for dynamic scripting with potential security holes:
```
{ "script": "indirect_score.get(doc['somefield'].value, 0.0)",
  "lang": "groovy",
  "params": {
    "indirect_score": {
      "hello": 1,
      "world": 2
    }
  }
}
```

However when ported to expression:
```
{ "script": "indirect_score[doc['somefield'].value] || 0.0",
  "lang": "expression",
  "params": {
    "indirect_score": {
      "hello": 1,
      "world": 2
    }
  }
}
```
I get a surprising
```
ExpressionScriptCompilationException[Unknown variable [indirect_score] in expression];
```
error whever I try to access the map, even with hardcoded `indirect_score['hello']` script. Primitive params seem to recognized just fine however, but are not flexible enough for the indirect lookup we need.

Does this mean dicts/maps or other complex variables can not be used as expression params, or what am I doing wrong?

**Comment by clintongormley** [comment]
Hi @tko 

This is a limitation of the expressions language, which is very fast, but very limited.  You can save your groovy scripts as script files instead.

**Comment by tko** [comment]
Yeah, I was trying to avoid having to change to our deployment process as well. Oh well.

FWIW without knowing anything about the internals it's rather surprising that dictionary-like access sometimes works (`doc['field']`) and other times doesnt (`someparam['field']`) -- it seems like all the pieces should be there, though I can easily imagine many reasons they haven't been wired up equally.

**Comment by rjernst** [comment]
What you are trying to do is a hash lookup, which is slow when doing per document.  In this case, I assume your "somefield" field is a string? `doc` is setup as a special variable which binds to field accessors at compile time, so that looking up for each doc is like saying "lookup this field number in docvalues/fielddata". But your example is trying to get the value of a string field (already something slow not supported in expressions) and use that to do a lookup in a map.

It might be possible for us to tweak the inputs and language to allow array params of numbers and indirect lookups based on number field values, but there is already ongoing work to expand the capabilities of scripts with #13084.

**Comment by tko** [comment]
Strings, yes, though could just as easily be numbers.

I just meant that syntactically the `doc` access looks _very much_ like hash lookup which (to someone with zero knowledge of expressions limitations) rather implies that hash lookup is supported in general. I may very well have missed the relevant documentation and made too many assumptions, but now that I know it simply won't work I'm good and can stop banging my head on the keyboard.
