### ISSUE TITLE
IP fields cause mapping conflicts

### ISSUE THREAD

**Issue by spalger** [elastic/elasticsearch#13112]
While using the 2.0 branch, @jbudz and I are noticing that `_default_` mappings always cause unresolvable type conflicts.

This is the mapping we are testing with:
```curl
curl -XPOST localhost:9200/logstash-2015.08.25 -d '{
  "mappings":{
    "_default_": {
      "properties":{
        "ip":{
          "type":"ip"
        }
      }
    }
  }
}'
```

And the documents that we are sending:
```
curl -XPOST localhost:9200/_bulk -d '{"index":{"_index":"logstash-2015.08.25","_type":"apache"}}
{"index":"logstash-2015.08.25","ip":"192.168.1.1"}
{"index":{"_index":"logstash-2015.08.25","_type":"nginx"}}
{"index":"logstash-2015.08.25","ip":"192.168.1.1"}
'
```

But the bulk fails with `"Mapper for [ip] conflicts with existing mapping in other types:\n[mapper [ip] is used by multiple types. Set update_all_types to true to update [search_analyzer] across all types.]"`. 

Since we are using `_default_` as the type, it seems like `update_all_types` should not be needed, since we are not actually creating the types until the documents are indexed.

**Comment by clintongormley** [comment]
@rjernst could you take a look please

**Comment by clintongormley** [comment]
Actually, this isn't about default mappings, it is a problem with fields of type `ip`.  This request will replicate the same problem:

    PUT my_index
    {
      "mappings": {
        "one": {
          "properties": {
            "field": {
              "type": "ip"
            }
          }
        },
        "two": {
          "properties": {
            "field": {
              "type": "ip"
            }
          }
        }
      }
    }

**Comment by rjernst** [comment]
@clintongormley Yes, it affects ip field type. The problem is how the search analyzer for ip fields is setup. For other numeric fields, it sets up an index analyzer for the numeric precision, and a search analyzer for the "max" value, and generally has constants for each possible precision. However, ip fields create these (even the "max" on for search analyzer) on the fly every time. This exposed a bug in our comparison of search analyzer when checking compatibility: we are looking at reference equality, instead of the name of the analyzer.

When I found the bug, I realized we had a hole in the unit tests (it was something I was relying on existing mappings tests for, but that was obviously insufficient!). I have a fix ready, and have been working on an improved base test which will exhaustively test compatibility checks for every property, for every field type.
