### ISSUE TITLE
no inFilter alternative in 2.0

### ISSUE THREAD

**Issue by brackxm** [elastic/elasticsearch#13145]
It is strange that QueryBuilders.inQuery() is removed in 2.0.
The documentation states that filters from FilterBuilders are available in QueryBuilders.
However that is not the case for FilterBuilders.inFilter().
Apparently QueryBuilders.inQuery() has been removed as it was deprecated. However FilterBuilders.inFilter() was not deprecated.
Code using FilterBuilders.inFilter() but not QueryBuilders.inQuery() never noticed the (then unrelated) deprecation in 1.x and is left without an alternative in 2.0

**Comment by nik9000** [comment]
Bleh. Sorry about that. it looks like `inFilter` and was just an alias for `termsFilters` and `inQuery` was just an alias for `termsQuery`. So in 2.0 there is just `termsQuery` and you should just use it if you want that "in any of these terms" behavior.

I'm going to close this because this bug report should be enough of a trail for people to follow to successfully migrate. If it isn't I'll add a note to https://www.elastic.co/guide/en/elasticsearch/reference/master/_query_dsl_changes.html

**Comment by nickminutello** [comment]
Perhaps everyone has moved to 2.x - so there isn't much demand anymore - but I did notice this gem of info was missing from https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_java_api_changes.html

**Comment by martin-g** [comment]
One feature that seems to be missing is that `InFilter` had a method `execution("and|or")` but this is not possible with `termsQuery()`.

**Comment by nik9000** [comment]
I hadn't noticed that! If you want AND then I think the normal way to get that now is with a `bool` query with many `term` queries in the `must` clause.

It is interesting to know that the optimizations that the `terms` query does for OR aren't all that useful if you don't have a fair number of terms. So if you have less than 16 terms it is rewritten internally into a `bool` query with many `term` queries in the `should` clause.
