### ISSUE TITLE
Percolator - Utilise Replicas to parallelise percolations on _mpercolate

### ISSUE THREAD

**Issue by gingerwizard** [elastic/elasticsearch#13177]
Percolator currently does not utilise replicas fully on an mpercolate request.  Documents are batched and sent to 1 candidate within a replica group.  This ticket proposes increasing use of replicas within a single request for greater parallel execution.  Given Percolator is largely CPU bound (provided there is sufficient memory for queries) this should increase throughput and reduce total execution time for the request.

For example, consider sending 10 documents in a request where queries have been indexed into two shards A1 and B2.  Both have replica shards A2 and B2.  Currently, assuming no routing, all 10 documents will either be sent to (A1 or A2) AND (B1 or B2).  Given execution on each shard is sequential, performance will be as fast as the slowest shard to respond.  Each shard has to percolate 10 documents.

The enhancement would split the 10 documents.  In this case 5 documents would be sent to each of the shards A1,A2,B1,B2.  This may not double throughput and changes the CPU load profile across nodes, introducing contention considerations.  However, it may be worth exploring.

**Comment by gingerwizard** [comment]
@martijnvg suggested this was worth consideration
@polyfractal may have some interesting thoughts re this especially regards the relationship between latency and throughput.

**Comment by clintongormley** [comment]
Not sure this would be effective in production scenarios.  Typically, you'll be doing multiple mpercolate requests.  Each mpercolate request would end up on a single shard, but because you're running multiple requests, you already have parallelization (without the added cost of fanning out). If all you're doing is one mpercolate request, then probably latency isn't as important.

It's the same as running a search on a single shard: it has to hit every segment in the shard, which it does serially.  You could search the segments in parallel which could speed up the results if you only ever run one query at a time, but in practice you run lots of queries simultaneously.

**Comment by gingerwizard** [comment]
MPercolate currently just acts a network optimisation.  The most common application seems to be to buffer N documents and send them off for percolation in one go.  This is particularly applicable when users are percolating prior to indexing.  Its unlikely they are running multiple percolate requests in parallel therefore, and hence not utilising the full capacity of their cluster with respect to CPU. 

If the advice is simply to send N smaller mpercolate requests in parallel i'm fine with that if we think it will achieve the same effect. I imagine you would need to set N to the number of replicas you have.

**Comment by martijnvg** [comment]
I think adding this optimisation at some point does make sense (not high priority). Instead of parallelising   the mpercolate request up to `primary_shard` times, a mpercolate request can be parallelised `primary_shard * num_replica` times. Multiple mpercolate requests can be send at the same time, but this is something that we can solve nicely on the ES side and then clients don't have to worry about dividing their mpercolate requests evenly.

**Comment by martijnvg** [comment]
Closing this issue as the mpercolate api in 5.0 is deprecated and redirects to msearch api. The msearch api does utilise shard copies better than mpercolate api did.
