### ISSUE TITLE
fielddata_fields for _all doesn't display all the terms

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#13178]
Tested in 1.7.1.
For the following test

```
PUT /test_qs
{
  "mappings": {
    "test_type": {
      "properties": {
        "text1": {
          "type": "string"
        },
        "text2": {
          "type": "string"
        },
        "text3": {
          "type": "string"
        }
      }
    }
  }
}

POST /test_qs/test_type/_bulk
{"index":{}}
{"text1":"abc","text2":"def","text3":"ghi"}

GET /test_qs/test_type/_search
{
  "fielddata_fields": ["_all"]
}
```

the result is

```
            "fields": {
               "_all": "abc"
            }
```

where it should have been actually `"_all": ["abc", "def", "ghi"]`.

**Comment by clintongormley** [comment]
The background to this bug: meta-fields typically contain a single value only, while other fields may contain zero or more values. So meta-fields are special cased to return just the first value (and in 2.0, to return their values at the "top" level, instead of within the `fields` element).

`_all` is an exception to this rule and should probably be treated as an ordinary field.  really, returning fielddata for the `_all` field is a really bad idea, fine for testing, but will blow up your heap in production.

**Comment by clintongormley** [comment]
Had a chat to @nik9000 about highlighting and the `_all` field.  I think we should leave things as they are for now, and revisit this once we have a better story around highlighting.

**Comment by javanna** [comment]
Support for the `_all` field has been removed, closing.
