### ISSUE TITLE
Don't allow users to modify merge settings

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#13185]
this is extremely expert and even experts don't touch it. I really wonder if we should allow this at all and if so should we rather provide some kind of optimized profile for `[THROUGHPUT, SEARCH_PERFORMANCE, READ_ONLY]' or something like this?

**Comment by nik9000** [comment]
I like the idea of an optimized profile! I think its much much less trappy. Especially if you can transition from one to the other and the "right things" happen.

**Comment by bleskes** [comment]
+1

**Comment by polyfractal** [comment]
+1

I can count on one hand the number of clusters helped by merge settings tweaks.  In contrast, you see clusters obliterated by even relatively small merge tweaks all the time.

**Comment by clintongormley** [comment]
+1

**Comment by mikemccand** [comment]
+1

At a minimum we should stop documenting these settings; I think we should do that today for 2.0.

This fits well with other recent simplifications (removing `SerialMergeScheduler`, merge policy control (always use the default `tiered`).

Optimized profiles is a great idea but I think there are challenges.  E.g. increasing `index.merge.policy.segments_per_tier` and/or decreasing `index.merge.policy.max_merge_size` should give better indexing throughput, since it tolerates more segments in the index, but it risks exhausting file handles if the node stores many shards and the risk is very dependent on how large the shard turns out to be and whether compound file format was disabled.

Also, when users change from one profile to another (e.g. THROUGHPUT to SEARCH_PERFORMANCE) suddenly on large shards there could a long running high merging cost for the shard to "catch up" to the new settings.

**Comment by jasontedor** [comment]
We have stopped documenting these settings in #13199. I think these can remain, however, as expert settings. Closing.
