### ISSUE TITLE
Avoid write outage when deploying to master node

### ISSUE THREAD

**Issue by laundrei** [elastic/elasticsearch#13346]
Whenever I do a rolling deployment there is a small spike in write errors when deploying to the current master node.  I get this error message:
Could not complete the operation due to- blocked by: [SERVICE_UNAVAILABLE/2/no master]

I'm guessing this means that some writes are timing out while waiting for a new master to be elected.  Is there anyway to force a master node election before brining down the current master node to avoid this?  Currently I call _all/_flush/synced and _cluster/nodes/_local/_shutdown before bringing down a node.

**Comment by bleskes** [comment]
since 1.4, master election takes 3 seconds. During that time nodes will only serve reads but writes will stall, waiting for the election to complete. We could relatively easy add an API to force a new master election but that will still take 3s and the old master is likely to re-elected. We could, in theory, introduce a clean master hand-off to another node but this is tricky and I think that are other places we can improve and have more impact (for example, ideas to reduce the 3s duration). 

All that said, I wonder why you see the no master block. All write api should wait for 1 minute before timing out and other operations that require a master should timeout only after 30s. Both of which are much longer than the time it takes to elect a new master.

**Comment by nik9000** [comment]
> All that said, I wonder why you see the no master block. All write api should wait for 1 minute before timing out and other operations that require a master should timeout only after 30s. Both of which are much longer than the time it takes to elect a new master.

Do you mean [this](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#timeout)?

**Comment by laundrei** [comment]
So my cluster consists of 3 dedicated master nodes and 30 data nodes.  When doing rolling deployments I deploy to the master nodes first and then the data node.  I only see that error when deploying to the master nodes.  

I didn't realize that master election is only supposed to take 3 seconds, perhaps it is taking longer than usual for some reason.  Btw I am using elastic search 1.7.1.  Also I am not specifying a timeout in the write requests to elastic search but my HTTP client will wait 30 seconds before timing out.  I'll look through the log files to see if I can figure out how long master election is taking.

**Comment by bleskes** [comment]
@nik9000 yeah, I meant that for indexing requests.

@laundrei thank you for the extra info. let me know how long the election takes or if you find anything of interest in the logs.

**Comment by clintongormley** [comment]
No more feedback. Closing
