### ISSUE TITLE
Top level parent child inner_hits doesn't use correct mapping

### ISSUE THREAD

**Issue by masaruh** [elastic/elasticsearch#13449]
If type is specified, it uses parent's mapping for inner hits:
```
DELETE test

PUT test
{
  "mappings": {
    "parent": {},
    "child": {
      "_parent": {
        "type": "parent"
      }
    }
  }
}

POST test/parent/1
{"name": "parent1"}

POST test/child/1?parent=1
{"name": "child1", "num": 1}

# Without type
# This works.
GET test/_search
{
  "query": {
    "has_child": {
      "type": "child",
      "query": {
        "match_all": {}
      },
      "inner_hits": {
        "sort":"num"
      }
    }
  }
}

# With type
# This gets parse failure saying "No mapping found for [num] in order to sort on"
GET test/parent/_search
{
  "query": {
    "has_child": {
      "type": "child",
      "query": {
        "match_all": {}
      },
      "inner_hits": {
        "sort":"num"
      }
    }
  }
}
```

Looks like it's because `SubSearchContext` uses `type` for main query while parsing sub search.

Note, this happens in 1.7.1 but not 2.x thanks to great mapping refactoring.

**Comment by martijnvg** [comment]
@masaruh correct, this has fixed by the great mapping refactoring, because it is a mapping issue that manifest here because has_child and has_parent queries operate between types, but the search api scoped the mapping view down to a single type. This makes this query fail. Without the mapping refactoring this issue can't fixed properly, so two things can be done. Upgrade to 2.0 once it is released or don't use types in the url when using the has_child query.  Filtering by type can also be done in the query dsl instead.

There was another similar issue open for this too, but I can't find it at the moment, but also that one has been fixed by the mapping refactoring. I'm closing this issue and because it has been fixed in 2.0 and it can't really be fixed in 1.x.
