### ISSUE TITLE
Get function score query results as fields

### ISSUE THREAD

**Issue by mausch** [elastic/elasticsearch#13469]
[I asked about this a couple of weeks ago in the forum](https://discuss.elastic.co/t/get-function-score-value-as-fields/28129) and didn't get any answers, so it seems that this is not implemented at the moment, therefore this is a feature request.

Basically, I need to return several function score query results as fields. Parsing the explanation tree is not really an option as it's cumbersome, error-prone, and slow (explanations bloat up the response quite a bit).

There is `script_fields` but it doesn't seem like it's possible to call arbitrary function score queries (e.g. a decay function).

To give an example, I'd like to run something like this:

``` json
{
  "script_fields": {
    "pepe": {
      "random_score": {
        "seed": 123
      }
    }
  }
}
```

where [`random_score`](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#function-random) could be any function score query.

or alternatively being able to run any arbitrary function score as part of a script:

``` json
{
  "script_fields": {
    "pepe": {
      "script": "function_queries.random_score(123)"
    }
  }
}
```

**Comment by mickdelaney** [comment]
+1

**Comment by nik9000** [comment]
@brwe, do you have a sense of how hard this would be?

**Comment by brwe** [comment]
I did not take a close look yet but don't think it would be super hard. However, I wonder what your use case is? What do you need the function results for?

**Comment by mickdelaney** [comment]
Use the scores in the application individually, rather than relying on a single score. Or parsing the explanation (which is huge obviously). 

Does that make sense ??

**Comment by nik9000** [comment]
> Use the scores in the application individually, rather than relying on a single score. Or parsing the explanation (which is huge obviously).
> 
> Does that make sense ??

Some sense, yeah. The trouble with using the scores individually is that the result ordering and cutoff will still be based on the overall score. But I see how you could flavor the individual results. Like put a little "closest!" marker or the one with the highest geographic score or something. The thing is that you might not get the actual "closest" result back because it might score lower for other reasons. Then again that could be fine for your use case.

You can work around not having this by implementing the function score as a script. Everything but random score should be pretty doable.

**Comment by mausch** [comment]
> You can work around not having this by implementing the function score as a script. Everything but random score should be pretty doable.

Yep, but that wouldn't give us access to built-in functions (e.g. a [decay function](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#function-decay)). We'd have to avoid all these nice built-in functions and reimplement them as scripts instead (which is slower, clunkier, etc). That's why I also suggested being able to access built-in functions from scripts as an alternative.

The main use case for this is to expose individual score components to the end user. At the moment if you have a complex scoring mechanism with lots of functions, the end user doesn't understand why results rank the way the rank. Sometimes this is ok or the user shouldn't have to care (e.g. Google) but otherwise it's useful to aid the user in making a decision on each result. Combining scores from different functions is sometimes highly personal and you can't have a one-size-fits-all overall score so the user has to be able to see into the otherwise black box.

Another use case we're considering is automating the relevance tuning to some degree.

Lastly it would be really useful for business analytics, to understand how users behave, then mine that data, analyse it, etc.

**Comment by nik9000** [comment]
> Yep, but that wouldn't give us access to built-in functions (e.g. a decay function). We'd have to avoid all these nice built-in functions and reimplement them as scripts instead (which is slower, clunkier, etc). That's why I also suggested being able to access built-in functions from scripts as an alternative.

Actually what I meant was that you could absolutely reimplement the decay functions as scripts. If you used expression scripts they should perform quite well. On par with the native functions. But implementing them is a pain so this is really just a workaround. [Here](https://en.wikipedia.org/wiki/Special:Search/prefer-recent:.5,10_stuff?cirrusDumpQuery) is an example reimplementing one of the functions to add more features, in this case it does exponential decay but only to 50% of the score.

I think I understand your use case. Would it be fair to sum it up as an easier to parse and smaller explain output?

**Comment by mausch** [comment]
> I think I understand your use case. Would it be fair to sum it up as an easier to parse and smaller explain output?

Technically, yes. The simplest way really is to be able to expose this as pseudo-fields, just like [Solr has been doing for quite some time now](http://wiki.apache.org/solr/CommonQueryParameters#functions).

**Comment by nik9000** [comment]
I think I'm sold. I had a voice conversation with @brwe and @colings86 about this and we came to the conclusion that:
1. This is reasonably easy to do.
2. It would have been useful for @brwe to have had in the past - in particular when building presentations about how the scores are built.
3. Its totally possible to build this and misinterpret the results.
4. In many many cases you don't want to return these results to the user. For example if you want to show a user the result that is closest to them you would want the distance from their location without any exponential decay applied. In those cases this would be trappy.
5. Its possible that users may think that these values are cached between the search and fetch phase. They wouldn't be. It'd be more trouble than its worth.

So I think this is worth doing but we'll have to make sure there is a big warning. I hate those but its wroth it I think.

I'm marking this as low hanging fruit because it should be reasonably simple but I don't know how its ranked relative to other things. So its probably a good thing for a new contributor to pick up.

Ping @clintongormley to check all this - he'll have opinions that might differ from mine and he gets to make the final call.

**Comment by nik9000** [comment]
I should point out that this might be useful to build [radar charts](https://en.wikipedia.org/wiki/Radar_chart) describing search scores. Which are pretty.

**Comment by clintongormley** [comment]
Is perhaps a simpler alternative just to provide convenience functions that implement gauss/exp/linear decay for use in scripts? Then this could be done easily with script fields.

I'd be interested to see how the above suggestions would be exposed at the API level

**Comment by clintongormley** [comment]
Thinking about this issue some more...

The original request (to store the results of scripts in the function score to return them with each hit) won't work.  We'd have to cache these results on each shard during the search phase to later be returned with fetch phase, or pass back all of these results to the coordinating node during the search phase.  Horribly complicated, lots of overhead.

The alternative is to rerun these scripts during the fetch phase for just the documents being fetched.  This wouldn't be possible without rerunning the query itself, as these scripts can have access to the `_score`, which depends on the sub-clause of the query where the script is executed. Plus, think that these scripts may be executed within a highly nested set of bool clauses, or within a nested or has_child query - what would be the structure for returning these values?  The overhead of rerunning the query and returning this big structure would be high, and it is already implemented as the explain API.

The last alternative is to calculate values as script fields, which you can do today (although you don't have access to the `_score`, or the context of nested queries etc).  While less flexible, this is more efficient because you don't rerun the query, you don't cache results on the shard, and you just have a simple list of keys and values, rather than the massive structure required to support something like explain.

All of the convenience functions in function score are documented and can be reimplemented pretty easily in raw scripts.  I am not in favour of adding the full JSON support that we have in function score for script_fields. The only thing I would consider doing is providing predefined functions (eg gauss_decay) in a script language which package up the calculations.

Perhaps that is something we can look at doing with the new scripting language that we are adding (https://github.com/elastic/elasticsearch/issues/13084).  @jdconrad what's your take on doing this?

**Comment by mausch** [comment]
Thanks for the analysis @clintongormley . 

I agree that caching the results from the function query would be complicated to implement (though from the point of view of the client it would be the best option). It would also probably require adding a name to each function query that the client wants to fetch as a pseudo-field.

I don't mind the performance hit of re-running the function query as a pseudo-field (this is what Solr does). In terms of Elasticsearch this means making the function query available in a `script_field`. As you say it would be quite easy to make the built-in functions available in scripts.

However from the point of view of the client code, this would mean having to generate both the JSON for a function query, e.g.:

```json
"linear": {
  "some_field": {
    "scale": "10",
    "offset": "11",
    "origin": "12"
  }
}
```

and for the target scripting language, e.g. in Groovy this could be something like:

```groovy
linear('some_field', [scale: 10, offset: 11, origin: 12])
```

That's why I suggested to support JSON in `script_fields`, because it would be the exact same JSON for `function_score` and for `script_fields`. Plus, JSON is much easier to generate than Groovy.

I think it would be perfect if we could access any function query (including any custom function registered from a plugin) like this.

**Comment by jdconrad** [comment]
Closing this as function_score_query is going to be changed significantly.
