### ISSUE TITLE
Allow connection to GCE instances from outside GCE platform

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#13461]
_From @dadoonet on January 28, 2014 21:17_

Until now, we can only connect and discover nodes when running inside GCE platform.
It means no authentification or credentials are required.

We want to be able to support as well node detection from outside GCE platform. Which means probably that users will need to open 9300 port in GCE firewall.

_Copied from original issue: elastic/elasticsearch-cloud-gce#10_

**Comment by DaveCTurner** [comment]
The reasons I can think of for wanting this are:

- Forming a cluster whose nodes are partly within GCE and partly outside.
- (Relatedly) starting a remote coordinating-only node for use with the transport client.
- Using a tribe node to connect to clusters that are both within GCE and outside.

The first sounds like a bad idea, and the others are being phased out (respectively by the REST client and CCS).

Closing this because of the above reasons (and lack of recent activity) but please reopen with more information if this is still something we want to work on.
