### ISSUE TITLE
ElasticSearch windows service doesn't respect the memory heap max size

### ISSUE THREAD

**Issue by TheFireCookie** [elastic/elasticsearch#13509]
Hello everyone,

We are having some issues with running ElasticSearch on Windows.

So our setup is as follow:

4 workstations with Elastic search started on it.

Specs:
Workstation:
OS: Windows 7 Professional 64 bits
CPU: Core i7 3770
Memory: 8.00 GB

ElasticSearch configuration:
Version: 1.5.2
http.compression: true
Java initial memory pool: 256 MB
Java maximum memory pool: 5358 MB
Thread stack size: 256 KB

Windows configuration:
Virtual memory size: 12058 MB

So everything was fine on each station until today where one of the station have its elasticsearch memory working set at: 6505 MB

So for info, here is the 4 machines ES memory working set:
Station 1: 6505 MB
Station 2: 5772 MB
Station 3: 5855 MB
Station 4: 5841 MB

Kopf plugin give me this informations:
Station 1:
Heap used: 3.89GB
Max: 5.17GB

Station 2:
Heap used: 3.70GB
Max: 5.17GB

Station 3:
Heap used: 2.63GB
Max: 5.17GB

Station 4:
Heap used: 3.53GB
Max: 5.17GB

The station 2 is the master node.

For the documents & index & shards we have:
11 indexes
25.374.590 docs
110 shards

So the question is why the station one take 6505 MB of memory?

And while we are at it, bonus question:

We actually have 11 indexes, one per document type. Is this useful or not? And bonus question 2:
Is 110 shards on 4 stations madness?

Thank you all!

If you need more informations, you can ask me!

**Comment by jpountz** [comment]
I suspect your tool is measuring virtual memory usage, which might account for some files stored in disk given that elasticsearch uses mmap.

> We actually have 11 indexes, one per document type. Is this useful or not? And bonus question 2:
Is 110 shards on 4 stations madness?

Having indices with one single type instead of different types on the same index makes sense. 110 shards on 4 machines starts to be a lot however, depending on the size of your shards. If they are already large (several GB) then this might be fine, but if they are small you should probably consider reducing the number of shards.

Please use [the forums](http://discuss.elastic.co) for questions in the future. These issues are for bugs and feature requests.
