### ISSUE TITLE
OS/ProcessProbe need to not use setAccessible

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#13527]
I don't know why they do it this way, but it causes grief.

Current code does this which will fail on java 9:
```
OperatingSystemMXBean osMxBean = ManagementFactory.getOperatingSystemMXBean();
Method getTotalPhysicalMemorySize = osMxBean.getClass().getMethod("getTotalPhysicalMemorySize");
getTotalPhysicalMemorySize.setAccessible(true);
System.out.println(getTotalPhysicalMemorySize.invoke(osMxBean));
```

Instead, do it like this:
```
OperatingSystemMXBean osMxBean = ManagementFactory.getOperatingSystemMXBean();
Class c = Class.forName("com.sun.management.OperatingSystemMXBean");
Method getTotalPhysicalMemorySize = c.getMethod("getTotalPhysicalMemorySize");
System.out.println(getTotalPhysicalMemorySize.invoke(osMxBean));
```

I would maybe also add a class.cast for simplicity and better errors/debugging too.

Separately, we need to ban setAccessible completely.

**Comment by rmuir** [comment]
And we also just revert af2df9aef67462adba9146a28e464043ee7ae122 as part of this too. I will take care of this one.

**Comment by uschindler** [comment]
Copypasted from hangouts:

you dont need al that:
https://docs.oracle.com/javase/8/docs/jre/api/management/extension/com/sun/management/OperatingSystemMXBean.html
this one is officially documented in the JDK javadocs
the problem may only be suppressforbidden, because it detects the class name as "sun."
its part of compact3
as you see it also has annotation @Exported
you can get the bean by passing the interface name to the managmentfactory
   public static <T extends PlatformManagedObject> T getPlatformMXBean(Class<T> mxbeanInterface)
you may add @SuppressForbidden
i know this is a bit controversal... ☺
IBM J9 may not implement this, because its not required to have the bean
but the interface should be there if they are compatible
you also have that one officially documented: https://docs.oracle.com/javase/8/docs/jre/api/management/extension/com/sun/management/UnixOperatingSystemMXBean.html

**Comment by uschindler** [comment]
In any case, why do you need the Class#forName() in your code. Removing the setAccessible should be fine, or what happens?

**Comment by rmuir** [comment]
> In any case, why do you need the Class#forName() in your code. Removing the setAccessible should be fine, or what happens?

it fails, even with java 8. you have to get the correct method. Sorry Uwe, it may be officially doc'ed as an extension but we should not rely on that, for jvm support everywhere. There is a simple way to do it, and its what i listed above. I will fix the code.

**Comment by rmuir** [comment]
And yes you see it here (https://docs.oracle.com/javase/7/docs/jre/api/management/extension/com/sun/management/package-summary.html) but if you try IBM:

```
Exception in thread "main" java.lang.ClassNotFoundException: com.sun.management.OperatingSystemMXBean
	at java.lang.Class.forName(Class.java:139)
	at test2.main(test2.java:8)
```

This is why we will do it the correct way!

**Comment by uschindler** [comment]
> it fails, even with java 8. you have to get the correct method

it fails also on Java 8, because it is an interface... So you have to reflect the interface and then call the method on the interface.
