### ISSUE TITLE
Both AWS EC2 discovery and S3 plugins do not support credentials file

### ISSUE THREAD

**Issue by robertsmarty** [elastic/elasticsearch#13555]
Both AWS EC2 discovery and S3 plugins do not support credentials file.

Plugins currently support ...

            credentials = new AWSCredentialsProviderChain(
                    new EnvironmentVariableCredentialsProvider(),
                    new SystemPropertiesCredentialsProvider(),
                    new InstanceProfileCredentialsProvider()
            ); 

These plugins should use the DefaultAWSCredentialsProviderChain which supports environment, system, instance and credentials file!

http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html

This would simplify code and support more credentials options.

My company (16000+ seats) currently requires this as we use SSO + AWS STS to update credential files.

Thanks!

**Comment by dadoonet** [comment]
I might be wrong but I think that the security manager won't allow execution of things like access to file `~/.aws/credentials`. @rmuir Am I right?

**Comment by rmuir** [comment]
Thats right.

**Comment by robertsmarty** [comment]
Why would the AWS Java SDK provide a function to utilise the ~/.aws/credentials file if it can't be accessed? Sorry, doesn't make sense to me.

**Comment by rmuir** [comment]
Currently I have several concerns:

* If we allow ourselves access to read the file, then any code can read the file, and if there is a security vulnerability the compromise can escalate to other parts of AWS.
* Current management of the existing options is not yet secure: we are working on tooling, the removal of `setAccessible` so that we have easy intuitive ways to improve the security: e.g. keep it only in a private field.
* The AWS sdk was clearly never used in a secure environment, for example it requires this permission for jackson-databind serialization of its InternalConfig representation, because it has wrong access modifiers to classes and members, and no way to bypass this. This makes the above more challenging.
* The existing mechanism for passing this information around (`Settings`) is not secure: credentials are kept around in memory, passed too to many places, held in `java.lang.String`. We need a new mechanism that is a one-time handoff to the target plugin and then erases itself.

So I think we need to walk before we can run, that is all.

**Comment by robertsmarty** [comment]
Thanks for the detail!
