### ISSUE TITLE
Add Fixed-Point Numeric data type

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#13625]
Fixed-point numerics allow the user to specific the number of significant digits they are interested in.  E.g. a user may only care about two sig-figs (`5.01`, `123.19`, etc). instead of the full 6-9 sig-figs in 32bit floats.

Fixed-point numerics can be "layered" on top of our existing support for Longs without too much hassle.  Additional information would need to be saved, such as the number of bits for the fractional component, and the base/sign if it is configurable.  Input/output formatting would also need to know how to convert into the appropriate representation.

But most of the "guts" should work seamlessly.  Ranges are unaffected, aggregations convert everything to Double anyway, etc

Fixed-point has two notable advantages:

- Most important to me, since fixed-points are basically Longs in disguise, they can leverage the compression tricks used in doc values to drastically decrease their on-disk footprint.  In contrast, floats/doubles are stored at their full size since there is no way to encode fp in a random-access format without introducing error

  Many "pure metrics" will only care about a few sig-figs (do you really care if your CPU usage is 53.0000001% vs 53.00%) but the space savings will definitely be appreciated

- As a more expert-level feature, if the user knows their dynamic range, they can obtain better precision for their use-case.  E.g. if your range is 0-1 exclusive, a fixed-point can be more precise than floating because you can dedicate all 32 bits to the fractional component instead of only 24bits in the float

**Comment by nik9000** [comment]
Neat!

**Comment by jpountz** [comment]
+1

**Comment by felixbarny** [comment]
+1

**Comment by kimchy** [comment]
huge +1

**Comment by tsg** [comment]
You might have noticed a few 👍 s from the Beats team :-). That's because in Topbeat/Metricbeat we have percentage values which we currently represent as a float between 0 and 1 as well as other floats for which we don't need great precision. 

We considered storing them as integers and then use UI logic to transform them in floats, but decided for this (or the half-precision floats) to be implemented, as it would obviously be better for everyone.

**Comment by kimchy** [comment]
btw, this could potentially be completely hidden from the user as an implementation detail? The user can configure precision in the double/float mapping and we do the magic behind the scenes?

**Comment by polyfractal** [comment]
@tsg @kimchy If you and/or the Metricbeat team can skim through #15939 and see what you think of the discussion, that'd be helpful.  The PR was stalled because concern was raised if a software half-float would be better.  I didn't feel comfortable pushing forward with the PR until a comparison could be made, but I'm not sure I can implement a half-float either (and haven't had the time to sit down and learn the needed bit twiddling).

There were questions around the API too: specify number of digits, number of bits, etc.

(You can ignore the code comments, I didn't work on them until the bigger issues were resolved).

> btw, this could potentially be completely hidden from the user as an implementation detail? The user can configure precision in the double/float mapping and we do the magic behind the scenes?

Hiding it as an implementation detail could be doable, need to think about that.  Floating and fixed have very different edge-cases at their extremes which may be confusing to the user.  E.g. fixed points are precise until they overflow at the edge of their range, floats instead become more increasingly more erroneous.

But no one understand floating error anyway, so maybe it's moot :)

**Comment by jpountz** [comment]
> Floating and fixed have very different edge-cases at their extremes which may be confusing to the user.

+1, I don't think we can mix both under the same type without introducing confusion.

> We considered storing them as integers and then use UI logic to transform them in floats, but decided to wait for this (or the half-precision floats) to be implemented, as it would obviously be better for everyone.

I have mixed feelings about this. We could implement it in elasticsearch, but on the other hand I have the feeling it would be more flexible/efficient/easy to do it from client side. For instance imagine we want to store percentages with a precision of 1%: the client would just have to multiply values by 100 at index time and index them as longs (or ints) rather than floats. And then it would also divide values by 100 when reading the _source or the result of histogram, min, max, terms, percentiles, ... aggregations. I think it is great that elasticsearch would be working directly on the "compressed" representation. If we want to do the same thing from within elasticsearch, first we have to figure out the right API to expose such numbers (which proved a bit tricky on the PR), and then either we need to add a multiplication on every doc values read, or we try to add the optimization to not decode every value but this is quite error-prone as we can optimize eg. histogram aggregations to divide post aggregation, but if the field is fed to the scripting API we still need to decode every value. So I'm afraid it would not be easy to expose in a generic way.

(Also, for the record, even if better than regular floats, I think half floats would still be a poor option to index percentages.)

**Comment by tsg** [comment]
The reason I don't like too much doing that in the client is that while we could easily do the conversion to int in Beats, we don't know how the user consumes the data, it might be via the Kibana discover tab or even directly via the Elasticsearch API. So we'd have to somehow communicate that those values should be divided by 100 or whatever.

If it's not possible to do it in a clean way in Elasticsearch, or it doesn't look like it will be done anytime soon, we might reconsider and choose to do that.

> (Also, for the record, even if better than regular floats, I think half floats would still be a poor option to index percentages.)

That's true for half-floats but not for the fixed points, right?

An alternate idea that @polyfractal mentioned was to implement compression for floats, rather than do things like fixed-points/half-floats. If that is possible, it sounds to me like a good idea since it would benefit more use cases.

**Comment by polyfractal** [comment]
> An alternate idea that @polyfractal mentioned was to implement compression for floats, rather than do things like fixed-points/half-floats. If that is possible, it sounds to me like a good idea since it would benefit more use cases.

I actually pinged @jpountz about this particular last night.  He said the compression scheme (separately encode mantissa and exponent as longs, recombine on reads) won't be possible using the current Doc Values setup.  Multi-valued fields are returned in sorted order, so you'd be unable to re-assemble the correct matching pairs of mantissa/exponent.

But, there are apparently thoughts about adding an iterator scheme to DV, which might allow that style of compression in the future.

Other lossless compression schemes that I know about for floats are all based on the previous value(s) which means they can't be used for random access :(

**Comment by dakrone** [comment]
@polyfractal do we have this now with the `scaled_float` type, since it potentially allows you to do something like this?

**Comment by polyfractal** [comment]
Oh, yeah, this was closed by @jpountz in https://github.com/elastic/elasticsearch/pull/19264 :)
