### ISSUE TITLE
GceDiscoveryTests is flakey

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#13623]
These tests seem to always fail on windows:
http://build-us-00.elastic.co/job/es_core_master_window-2008/2236/
http://build-us-00.elastic.co/job/es_core_master_window-2008/2237/
http://build-us-00.elastic.co/job/es_core_master_window-2012/1754/
http://build-us-00.elastic.co/job/es_core_master_window-2012/1753/

**Comment by rjernst** [comment]
Adding the awaitsfix to these tests caused the build to fail because these are the *only* unit tests for the plugin. I've disabled unit tests altogether in the gce plugin. They need to be re-enabled in the pom once these are fixed.

**Comment by rmuir** [comment]
The issue is, we have to support elasticsearch in too many ways:

* starting up from bin/elasticsearch (integ tests use this way too)
* running unit tests (which are not realistic)
* running from IDEs.

We can't easily work around the problems with GCE and AWS jars for the latter 2, its just too much fucking work. I waste like 2x as much time on that stuff as actually solving real problems.

**Comment by rmuir** [comment]
The issue is, this plugin has security problems and we cannot simulate it in unit tests on windows machines where jar files are spread across multiple drive letters. 

We should not make this stuff more complicated just for these unit tests. We should spend the effort fixing real problems instead, like the problems in the GCE code.

The same issue may happen with AWS plugins, too.
