### ISSUE TITLE
Date Math Not Working for GET

### ISSUE THREAD

**Issue by sirdavidhuang** [elastic/elasticsearch#13665]
I try to get a document using date math, but Elasticsearch returns a error.

Version: Elasticsearch 2.0.0-beta2

Put Document

$ curl -XPUT 'localhost:9200/logstash-2015.09.19/animals/1' -d '{"name":"puppy"}'
{"_index":"logstash-2015.09.19","_type":"animals","_id":"1","_version":1,"_shards":{"total":2,"successful":1,"failed":0},"created":true}

Get Document

$ curl -XGET 'localhost:9200/logstash-2015.09.19/animals/1'
{"_index":"logstash-2015.09.19","_type":"animals","_id":"1","_version":1,"found":true,"_source":{"name":"puppy"}}

Get Document with Date Math

$ curl -XGET 'localhost:9200/`<logstash-{now/d}`>/animals/1'
No handler found for uri `[/<logstash-now/d>/animals/1]` and method [GET]

**Comment by dadoonet** [comment]
It's not supposed to work AFAIK. Did you see that somewhere in docs?
You should do that on the client side.

May be using an alias would help you?

**Comment by sirdavidhuang** [comment]
This page includes the date math information.
https://www.elastic.co/guide/en/elasticsearch/reference/master/date-math-index-names.html

Example from page.
curl -XGET 'localhost:9200/<logstash-{now/d-2d}>/_search' {
  "query" : {
    ...
  }
}

I try this curl command and get a error.
curl -XGET 'localhost:9200/<logstash-{now/d}>/_search' -d '{
  "query" : {
    "match" : {}
  }
}'

{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"<logstash-now","index":"<logstash-now"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"<logstash-now","index":"<logstash-now"},"status":404}

There is also this pull request.

Add date math support in index names #12209
https://github.com/elastic/elasticsearch/pull/12209

**Comment by dadoonet** [comment]
Great. I missed that !

**Comment by martijnvg** [comment]
Thanks for reporting @sirdavidhuang, this is indeed a bug. The issue here is that the index name is cut of at the date rounding (`/)` and only `<logstash-{now` ends up being received as index name.

**Comment by javanna** [comment]
Hi @sirdavidhuang we had initially treated this as a bug and fixed it, but afterwards we found out that the fix introduced a regression (#14177), which made us take a step back. Any slash that should not be used as a path separator in a uri should be properly escaped, and it is wrong to try and make distinctions between the different slashes on the server side depending on what surrounds them, that heuristic is not going to fly (in fact it didn't :) )

We are going to revert the initial fix then, the solution to this problem is to escape the '/' in the url like this: `curl -XGET 'localhost:9200/<logstash-{now%2Fd}>/animals/1'`. That is going to work and didn't require any fix in the first place.

**Comment by chenryn** [comment]
escape the '/' don't work for me:

![image](https://cloud.githubusercontent.com/assets/1219655/12576503/24f6ab3e-c44f-11e5-92d5-ec2b08405ce5.png)
