### ISSUE TITLE
Proposal: Elasticsearch doctest

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#13739]
Elasticsearch has lots examples sitting in asciidoc but doesn't have a mechanism for making sure that they work. I propose it grow some way to test these either by running them against a cluster or by comparing them to the rest-api-specs.

**Comment by dadoonet** [comment]
++ IMO we should extract the documentation from existing tests.

That's why I opened https://github.com/elastic/docs/issues/4 to make Java documentation always consistent.

See an example here of what I can imagine for a Java Client doc: https://github.com/elastic/elasticsearch/blob/master/qa/smoke-test-client/src/test/java/org/elasticsearch/smoketest/SmokeTestClientIT.java#L39

**Comment by nik9000** [comment]
> See an example here of what I can imagine for a Java Client doc: https://github.com/elastic/elasticsearch/blob/master/qa/smoke-test-client/src/test/java/org/elasticsearch/smoketest/SmokeTestClientIT.java#L39

Oh that is cool! I like that.

I was thinking of the other way around - running the json docs that we have through something to make sure they work.

**Comment by danielmitterdorfer** [comment]
@nik9000 Isn't this covered by #18075 (i.e. can we close this ticket?)?

**Comment by clintongormley** [comment]
Closed by #18075

**Comment by nik9000** [comment]
Man, I've been talking about this for a while now. I just keep forgetting all the tickets I've made.
