### ISSUE TITLE
Shard rebalancing too aggressive when adding new nodes

### ISSUE THREAD

**Issue by avleen** [elastic/elasticsearch#13771]
Cluster:
 * 3 dedicated masters
 * 2 client nodes
 * 65 data nodes, each running 2 instances of ES
 * ES version 1.5.2, but tests on a smaller 1.7 cluster seem to behave the same way
 * Shard balancing based on disk usage
 * 64 indices, 1757 primary shards, 1757 replica shards (3514 shards total)

Upon adding a new node to the cluster, the expectation is that this node will get populated quickly.
In reality, we end up with shards rebalancing across the entire cluster.

Example:
I added `logdb41` to the cluster today, and the result was primary shards getting relocated and replicas being rebuilt everywhere, and very few going to the new node at any one time:
```
index               shard time   type       stage source_host          target_host
logstash-2015.08.29 26    268206 relocation index logdb74              logdb52
logstash-2015.08.23 36    268138 replica    index logdb70              logdb74
logstash-2015.08.23 15    268340 replica    index logdb26              logdb38
logstash-2015.08.25 15    267976 replica    index logdb39              logdb26
logstash-2015.08.25 28    268094 replica    index logdb32              logdb27
logstash-2015.09.08 6     245140 replica    index logdb48              logdb41
logstash-2015.08.25 12    268262 relocation index logdb40              logdb65
logstash-2015.09.19 25    264782 relocation index logdb65              logdb41
```

Does the rebalancing algorithm try to get disk usage as even as possible across the entire cluster?
Or does it allow some amount of variance between nodes?
It feels like the cluster is coming up with a new map of where all the shards should end up, but instead of initially putting as many shards as possible on the new node, it's prioiritising the rebalancing some other way.
This seems less efficient in terms of production operations. Do all these shards really need to move?

Thanks!

**Comment by dakrone** [comment]
> Does the rebalancing algorithm try to get disk usage as even as possible across the entire cluster?

No, disk is actually not a factor in the "weight" of a node+shard combination. The only thing disk is used for is a "yes/no" for whether the shard can be allocated based on the watermarks.

> It feels like the cluster is coming up with a new map of where all the shards should end up, but instead of initially putting as many shards as possible on the new node, it's prioiritising the rebalancing some other way.

This is likely because the `BalancedShardsAllocator` has determined a new, better, weight for other nodes since new nodes have been added. Basically, it tries to give weight to a node for a shard given the following criteria:

- _index balance_ meaning that the shards for a particular index are distributed more evenly (instead of clustered around a small number of nodes)
- _shard balance_ meaning that the number of shards is roughly equivalent across all the nodes (when possible with regard to the allocation deciders)

The `index` factor defaults to 0.55 and the `shard` factor defaults to 0.45 (for their relative importance).

However, in your case, since you want the rebalancing to not be as aggressive, you could consider the `cluster.routing.allocation.balance.threshold` setting (defaults to 1.0f), which means that the weight for the evaluated node must be above this for a relocation to be performed. If you raise it, relocations will occur less frequently at the potential cost of a more unbalanced (with regard to the two weights I mentioned above) cluster.

**Comment by clintongormley** [comment]
No further feedback. Closing
