### ISSUE TITLE
Provide a way to disable allocation awareness for specific indices

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#13780]
Details on the use case is documented in https://github.com/elastic/elasticsearch/issues/12431.  Providing an option to disable allocation awareness at the index level will help address such use case.

**Comment by DaveCTurner** [comment]
This is an interesting idea, but since its opening we have not seen enough feedback that it is something we should work on. We prefer to close this issue as a clear indication that we are not going to work on this at this time. We are always open to reconsidering this in the future based on compelling feedback; despite this issue being closed please feel free to leave feedback (including +1s).

**Comment by jdcrown** [comment]
This is typically a problem with multiple availability zones and auto balancing evenness when an index has "auto_expand_replicas: 0-n" set such as the case with .security. 

So if i am using a single autoscaling group in AWS that has multiple availability zones, AWS does not guarantee evenness, it's mainly based on availability.  This can wreak havoc on the .security index in this case.

**Comment by DaveCTurner** [comment]
From the [AWS docs](https://docs.aws.amazon.com/autoscaling/ec2/userguide/auto-scaling-benefits.html):

> Amazon EC2 Auto Scaling attempts to distribute instances evenly between the Availability Zones that are enabled for your Auto Scaling group.

Although there's no _guarantee_ of evenness, an uneven distribution across AZs represents a failure state that should be resolved in due course.

Additionally, since 6.5.0 the `.security-*` indices default to `auto_expand_replicas: 0-1` (cf. https://github.com/elastic/elasticsearch/pull/33131). If you have two or more AZs and have allocation awareness enabled then this ensures that there's no more than one copy in each AZ, which should be sufficient (cf. discussion in https://github.com/elastic/elasticsearch/issues/29712). If you are asking for more replicas (i.e. `auto_expand_replicas: 0-n` where `n≥2`) and struggling to get them all allocated then I suspect you're setting `n` too high.
