### ISSUE TITLE
Integration tests for running ES with plugins could be collapsed into running with a single ES startup

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#13826]
Currently for each module in the ES repo we install the plugin, start up ES, wait for it to start, and then execute the tests. Instead of doing this N times for each module, we could probably execute the tests against the running ES that has all of the plugins installed, reducing the amount of times we have to start ES externally and wait for it to be available.

**Comment by nik9000** [comment]
+1

Its not the "maven way" but it could save a ton of time.

**Comment by rmuir** [comment]
-1

This would be nearly impossible to debug.

**Comment by dakrone** [comment]
@rmuir shouldn't we test that our install multiple of our plugins don't interfere with each other?

**Comment by rmuir** [comment]
Integration tests need to be as simple as possible so that they can be debugged. Its like the golden rule, otherwise they will cause time to be wasted.

Its obvious that this has not been understood, if you look at the ones in `elasticsearch/core`, but that does not mean we have to keep doing things this way, and spread that bad behavior into the plugins world.

**Comment by nik9000** [comment]
> Integration tests need to be as simple as possible so that they can be debugged. Its like the golden rule, otherwise they will cause time to be wasted.

I don't 100% agree with this but my quibble isn't relevant. In this case the proposal is only to sacrifice cleanliness of tests for speed. I think in this case I think its a tradeoff worth making. I also agree with you that in other cases the integration tests have gotten too complicated and should be simplified.

**Comment by dadoonet** [comment]
I'm +1. I always thought that Integration tests are about "integration".
So how all the stuff we are building integrates with each other.

I think it's part of the qa basically.

On the other hand, I agree with Robert on the fact that as a plugin developer I prefer to detect super quickly that my plugin simply does not start anymore.

This is a tradeoff I believe.

**Comment by rmuir** [comment]
> I don't 100% agree with this but my quibble isn't relevant. In this case the proposal is only to sacrifice cleanliness of tests for speed. I think in this case I think its a tradeoff worth making. I also agree with you that in other cases the integration tests have gotten too complicated and should be simplified.

I do not think this is the right tradeoff at all. Plugins integration tests are very fast, and don't need optimizing. Its the distribution and core integration tests that are dog slow.

**Comment by rmuir** [comment]
> On the other hand, I agree with Robert on the fact that as a plugin developer I prefer to detect super quickly that my plugin simply does not start anymore.

Please consider other situations like when we do lucene upgrades, we need to be able to debug this stuff, and not have 87 plugins failing at once.

**Comment by rmuir** [comment]
> I'm +1. I always thought that Integration tests are about "integration".
> So how all the stuff we are building integrates with each other.
> 
> I think it's part of the qa basically.

If you want to test that, then improve the qa/smoke-test-plugins test. But individual units/modules need to be tested first, with contained test cases, so that you never have to debug a crazy complex configuration with multiple plugins unless *its actually an integration problem across them*

That is how tests work, it is the same reason why unit tests are valuable.

**Comment by jpountz** [comment]
Maybe the issue that is surfacing here is that elasticsearch startup is too slow and we should try to understand why and fix it.

**Comment by rjernst** [comment]
This is a bad idea. We are not gaining any time back when the time to debug problems is more than the "time saved" in builds. Tests should be isolated.

**Comment by dadoonet** [comment]
@jpountz hot reload of plugins ? :)

**Comment by rmuir** [comment]
This issue is optimizing the wrong thing. I have the feeling this happens often not just around tests, but with code too. 

Look at the simplest plugin:
```
[INFO] Plugin: Example site ............................... SUCCESS [  9.293 s]
```

On the other hand:
```
[INFO] Elasticsearch: Core ................................ SUCCESS [08:17 min]
```

In fact I think server startup is something like 2s out of that 9.293s,  but still the fact remains, this server startup in plugin builds is not the slow part of the build.

**Comment by rmuir** [comment]
The difference is even more pronounced on my mac laptop, which I only got a little over a year ago:
```
[INFO] Plugin: Example site ............................... SUCCESS [ 12.014 s]
[INFO] Elasticsearch: Core ................................ SUCCESS [25:29 min]
```

**Comment by javanna** [comment]
I would love to have faster tests too, but I agree that going back to a shared cluster isn't the right solution... and if we want to test that different plugins don't interfere with each other we should have specific tests for that, but in general each plugin should have isolated and easy to debug tests.

**Comment by dakrone** [comment]
Okay, I can understand the reasoning to have plugins isolated for easier debuggingi.
