### ISSUE TITLE
Rip the grooviness out of 'messy tests' in groovy plugin

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#13837]
These these tests belong in core, and were just moved temporarily.

We should clean them up one by one...

**Comment by rmuir** [comment]
See https://github.com/elastic/elasticsearch/pull/13834 for more information. The referred package-info is https://github.com/rmuir/elasticsearch/blob/groovy_factor_out/plugins/lang-groovy/src/test/java/org/elasticsearch/messy/tests/package-info.java

**Comment by tlrx** [comment]
Many messy tests have been cleaned recently in #19280, #19302, #19336 and #19621. Most of the tests have been moved back in their original places and converted back again into integration tests while the dependency on Groovy has been replaced by mocked scripts. It's not perfect since some tests would have benefit to be changed into unit or simplier tests but I think that's still a good move.
