### ISSUE TITLE
Determine if the index has been modified

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#13830]
Today, it is difficult to determine if any index has been updated (e.g., in _mostly_ read only scenarios where the answer becomes more interesting). If you have a simple, outside cache, then it would be ideal to know when an index has been modified without jumping through hoops to figure it out.

Conceptually, this could be as simple as a _shard_ metadata field that indicates when the last document was _modified_ (created, updated, or deleted). I do not think that it is worth modifying the cluster state by adding it at the index level (less of a hassle with cluster state diffs, but still quite noisy).

This could live as a secondary API next to `_field_stats` (`_index_stats` or just an addition to the `<index>/_stats`) as a way to show how many _actual_ modified documents exist, how many deleted documents exist (preferably as an absolute number, rather than somewhat relative like `_version`, but actual deletions will most likely be harder to track), and document count. Some of this is available in other ways (e.g., deleted docs), but there's no simple way to know that "indexA has these stats relative to its documents" and there's no way to know "those stats last changed at time `X`".

**Comment by clintongormley** [comment]
It's got to be persisted somewhere.  Data needs to be part of the cluster/index state in order to be persisted.  So now we need to write this to disk every time  document is indexed.

Elasticsearch already has a bunch of caching built in.  Most of the time you can just run your queries/aggs and rely on Elasticsearch to do the caching for you.  In the small number of cases where you want external caching, you could use a simple max agg on a timestamp field to check whether the external cache should be purged.  Enable result caching on the max agg and even that check becomes very light.

I think existing functionality is a better answer than adding an index timestamp.

**Comment by clintongormley** [comment]
It just occurred to me that this could be implemented in a much simpler lighter way: most recent refresh time.  Each index (or shard) could just record the time of the most recent refresh of a new segment.  This value need not be persistent, just held in memory.

**Comment by jasontedor** [comment]
Today this can be solved client side by storing the last sequence number and then polling the shard level stats for the current number; if it is higher, there must have been a change. Closing.
