### ISSUE TITLE
How to take snapshot of a index type instead of all types in the indexes?

### ISSUE THREAD

**Issue by lokeshhctm** [elastic/elasticsearch#13832]
We have 2 different types in the index but we don't need to take backup of whole index including all types but to one specific type only. How can we do this?

**Comment by jpountz** [comment]
Snapshots can only work at the index level, not type. If you want finer granularity you need to index your documents in different indices instead of types. In the future please use [the forums](http://discuss.elastic.co) to ask questions, we try to only use github issues for confirmed bugs and feature requests.
