### ISSUE TITLE
Cannot easily specify multiple number values for match query

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#13849]
[Match query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query.html) allows only one value to be passed. If multiple values are required for the match then one can aggregate them into a sentence which is going to be analyzed.
However if the field the match queries against is a _number_, it is not possible to pass in multiple values:

```json
"match" : { "participants" : "1" }
```
works however

```json
"match" : { "participants" : "1 2" }
```
doesn't and will throw a `NumberFormatException`. Using an array (as `terms` query allows) is also not supported.

```json
"match" : { "participants" : [1 2] }
```

The workaround is to break down the query into `bool` manually.

**Comment by costin** [comment]
@dakrone was kind enough to try it out and replicate the issue.

**Comment by jpountz** [comment]
Wouldn't it be easier to build a `terms` query instead of a `match` if you already know which terms you would like to query?

**Comment by costin** [comment]
Should work but I would argue it's still a workaround. Just like `in` is a synonym for `terms`, ES could automatically translate the query from `match` to `terms`. The user doesn't always know the values passed are numbers or that the target field is numeric hence why applying the workaround would require additional calls and effort.

**Comment by clintongormley** [comment]
@costin i don't think we should support this.  The semantics for the `terms` query is simple: include any document which contains at least one of the listed terms.  

The `match` query is a very different story.  We've got min should match, fuzziness, cutoff frequencies, tf/idf, phrases and positions, what happens if each entry in the array generates multiple terms? how do we combine the scores from each entry, and how do we combine the scores from the terms from each entry. should we use bool, dis_max, blended?  etc etc etc

We provide the tools for you to specify the logic you require explicitly yourself, eg:

    {
      "query": {
        "bool": {
          "should": [
            {
              "match": {
                "participants": "1"
              }
            },
            {
              "match": {
                "participants": "2"
              }
            }
          ]
        }
      }
    }

or (depending on your needs) perhaps:

    {
      "query": {
        "constant_score": {
          "filter": {
            "bool": {
              "should": [
                {
                  "match": {
                    "participants": "1"
                  }
                },
                {
                  "match": {
                    "participants": "2"
                  }
                }
              ]
            }
          }
        }
      }
    }

I don't think we should further complicate an already complicated query when there is a perfectly usable alternative.
