### ISSUE TITLE
ES_HOME is set to null in windows service

### ISSUE THREAD

**Issue by bittusarkar** [elastic/elasticsearch#13877]
I'm running a single instance of Elasticsearch 1.7.1 on Windows 10. I use some custom Elasticsearch plugins which need to read the value of `ES_HOME` environment variable. I use `System.getenv("ES_HOME")` to read it. I've not set the value of `ES_HOME` environment variable on this machine. When I start Elasticsearch by executing `elasticsearch.bat`, the value of `ES_HOME` is correctly read. But when I install Elasticsearch service and start it using `service.bat install` and `service.bat start`, the value of `ES_HOME` is `null`. If I set `ES_HOME` environment variable on my machine, then there is no problem at all but I want to minimize the dependency on environment variables as much as possible.

This looks like a bug to me as there is discrepancy in behaviour between two launching machanisms. Thoughts?

**Comment by clintongormley** [comment]
@Mpdreamz could you take a look at this please?

**Comment by bittusarkar** [comment]
@Mpdreamz were you able to make any progress on this?

**Comment by bittusarkar** [comment]
Pinging again

**Comment by gmarz** [comment]
@bittusarkar ES_HOME isn't set globally, so the service won't pick up on it since it's ran separately in it's own process.  Even if we set it globally (which is probably a bad idea) you're still relying on environment variables- the only difference being local vs global.

What if you try `System.getProperty("es.path.home")` instead?

**Comment by bittusarkar** [comment]
Awesome! `System.getProperty("es.path.home")` works for me.
