### ISSUE TITLE
Copy a snapshot to another repository

### ISSUE THREAD

**Issue by grantr** [elastic/elasticsearch#13913]
I have a repository with 4-hour snapshots going back 8 months. Most of those I'd like to delete, but 10 are useful and should be kept. I have to delete ~1500 snapshots. At 30 minutes each, that will take about 25 days.

If there were a way to copy snapshots between repositories, this would be a much faster operation: copy those 10 snapshots, delete the old repository.

Any plans to support this? I think it would reduce the pain of cleaning up large repositories substantially.

**Comment by clintongormley** [comment]
Related to #12587?

**Comment by imotov** [comment]
@clintongormley in #12587 we added support for bulk delete operations within snapshot. Basically deleting multiple snapshot files in one request to S3 or azure. I think what @grantr needs is to have an ability to delete multiple snapshots at the same time.

**Comment by clintongormley** [comment]
thanks @imotov - closing

**Comment by kerrick-lyft** [comment]
This feature would be useful for me. We have separate repositories for staging and production environments, and we'd like to be able to copy a snapshot to the production repository after creating and validating it in staging.

**Comment by MorrieAtElastic** [comment]
The "nyc_restaurants" index in the Example demos in github is built by copying a tar'd snapshot directory onto a customer's server and then defining a repository and snapshot using that data and then restoring the index. See https://github.com/elastic/examples/blob/master/Exploring%20Public%20Datasets/nyc_restaurants/README.md#option-1-load-data-by-restoring-index-snapshot.

So I find myself confused that this particular enhancement request is outstanding when not only is copying snapshots possible, but the method is being used by Elasticsearch itself in publicly available demos. 

Since I am now hoping to use this method to help a customer who has no other way of moving a large amount of indexes between 2 clusters, I would appreciate knowing:  how the method used in the nyc_restaurants setup differs from what is being requested in this enhancement? And is what is being done in the nyc_restaurants demo supported? 

btw: has this enhancement been scheduled for implementation?

**Comment by MorrieAtElastic** [comment]
OK: it has been explained to me that what this enhancement is requesting is the ability to selectively identify a few snapshots within a repository and copy only them. What is being done in the nyc_restaurants example demo is that the entire repository is being moved. 

Incidentally, I think the enhancement request has value and I would like to see it implemented.
