### ISSUE TITLE
Lets talk about switching bin/elasticsearch to bash

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#14002]
Right now `bin/elasticsearch` uses `sh`. Would it offend anyone terribly if `bin/elasticsearch` ran in `bash` instead? It'd buy nicer syntax for defaults and sweet, sweet arrays. Arrays would make it much easier to dynamically build command line arguments and not have issues with spaces.

**Comment by nik9000** [comment]
@spinscale @tlrx have opinions? @brwe? I'm not sure who else to ask....

**Comment by KevinCathcart** [comment]
Question from a drive-by commenter:
What about the Solaris/SmartOS? Do they install bash by default these days?  I know that Solaris did not historically install it by default, but I've not worked with even remotely recent versions, so that may have changed.

**Comment by markwalkom** [comment]
I'm a +1 on this.

@KevinCathcart  "technically" we don't support Solaris/SmartOS, but it's probably worth keeping it in mind none the less.

**Comment by KevinCathcart** [comment]
@markwalkom: Right. Misread the support matrix because my job's websense
filter blocks portions of the site, so not everything will display right.
(I would like to strangle the idiot IT person who thought putting the CDN
category in the blocked list was a good idea.)

**Comment by brwe** [comment]
+1 from me too but only speaking as a developer. I don't know the reason why it is `sh` now but assume it is because of what @KevinCathcart said.

**Comment by spinscale** [comment]
@nik9000 are arrays a bash 4 feature? If so, do all the OS's have bash4 installed by default?

I also agree that the support matrix should not be the only systems ES runs on, as long as we dont die from maintenance hell. The argument for easily parsing spaces is intriguing though... we still do fail in the plugin manager here, right?

**Comment by tlrx** [comment]
I think using `sh` + POSIX compliant scripts help a lot when it comes to install elasticsearch on various operating systems where bash is not installed by default (I have Solaris and FreeBSD in mind).

Since these scripts do not contain a lot of code and logic, I think we can stick to `sh` if it helps non-bash users to use elasticsearch.

**Comment by clintongormley** [comment]
Discussed in FixItFriday: there are a number of users on Solaris/SmartOs, who would need to install bash before using Elasticsearch.  Given that we've shifted command line parsing to Java, do we need the nicer features in bash still?

Consensus in the discussion was to keep on with `sh`, but I'll leave this issue open for a while to garner more opinions.

**Comment by jasontedor** [comment]
I think that we should revisit this. Defaulting to `/bin/sh` is very difficult to support because `/bin/sh` means different things on OS that we support. For example, on late Centos it means `bash`, but on some Ubuntu it means `dash`. I don't think that the lack of `bash` on *unsupported* OS should play *strongly* into our decision making.

> Given that we've shifted command line parsing to Java, do we need the nicer features in bash still?

Yes, I ran into issues on Ubuntu in #17675 after adding a very simple conditional that is fine in `bash` but not `dash`.

> Consensus in the discussion was to keep on with `sh`

This does not make sense to me since `sh` does not mean the same thing across OS, so it means we supporting everything.
