### ISSUE TITLE
Allocation not complete when only 1 of 2 awareness attributes is set to forced

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#14011]
This test uses a similar setup as 14010 (also using ES 1.7.2), the only difference is that for this use case, only 1 of the attributes (updateDomain) is set to be forced, the other attribute (faultDomain) is not set to be forced.

With this configuration, you will see from the video that the first issue I ran into is 14010 where I have to prod it by forcing a cluster reroute in order for it to complete its allocation.  Except that even after prodding, one of the shard is not at the right place.  If I use a manual reroute command to move it, it actually gets moved successfully and does not violate any routing rules.  Given that it does not violate any routing rules, it seems like there is another bug here where it is not moving the shard to the right place automatically as part of awareness.

Repro video:
https://drive.google.com/file/d/0B1rxJ0dAZbQvd3p5Y3F0QzItMWs/view?usp=sharing

Node setup:
https://docs.google.com/document/d/1ktYSzaZh_FlhloSextzCNh3HYYS0OEE8wPU4jhHGPTo/edit?usp=sharing

**Comment by clintongormley** [comment]
Also see #14010

**Comment by ywelsch** [comment]
The issue here is that the AwarenessAllocationDecider uses the total number of shards (which is 1 primary + 2 replicas = 3) as basis to calculate balancedness in faultDomain. However, one of the replicas cannot be allocated due to forced awareness in updateDomain. But this unassigned replica is still used as basis to calculate balancedness in faultDomain.

I'm not sure what we could change here. Any thoughts @bleskes @dakrone?

**Comment by bleskes** [comment]
agreed this will be hard to solve. Basically we need to capture the idea that the third copy can not be assigned under the current setup and this shouldn't be taken into account when balancing on the allocation awareness attribute. My only idea here is to separate allocation deciders into "hard" and "soft" group. The hard one should be run first and should mark any shard copy that is "not assignable" as such. The soft group can the ignore those shards when making decisions. It will require more thoughts and review of current deciders to see how they fit. 

Note: #8178 is another example the result of mixing allocation awareness with a hard rule.

**Comment by DaveCTurner** [comment]
This is an interesting idea, but since its opening we have not seen enough feedback that it is something we should work on. We prefer to close this issue as a clear indication that we are not going to work on this at this time. We are always open to reconsidering this in the future based on compelling feedback; despite this issue being closed please feel free to leave feedback (including +1s).
