### ISSUE TITLE
Improve circuit breaking on aggregations

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#14046]
Unfortunately circuit breaking on aggregations only catches a small subset of out-of-memory errors. I was talking with @dakrone recently who had the interesting idea to also count how many aggregators we create and use it for circuit-breaking. I think it would be a good heuristic to avoid out-of-memory errors in the deeply-nested aggregation case that we often see.

**Comment by dakrone** [comment]
When I discussed this with @jpountz we talked about potentially adding this to the constructor of `AggregatorBase` to increment when it is created (since we can get the breaker from the aggregation context) and decrement it in the `close` method, which I think is a neat idea to try.

Part of this would be determining the "weight" of a single `AggregatorBase`, then we could have a separate `BucketBreaker` where the `overhead` could be tuned for specific use cases (as a mulitplier of the class size).

Thoughts and heap dumps welcome :)

**Comment by dakrone** [comment]
If anyone is curious about this, I'm working on a branch with it here: https://github.com/elastic/elasticsearch/compare/master...dakrone:bucket-circuit-breaker

**Comment by dakrone** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/19394

**Comment by haizaar** [comment]
Will this circuit breaker prevent me from running aggregation that returns zillion buckets? Like generating histogram on file size metrics with step of 5, which can easily result in trillion buckets.

**Comment by dakrone** [comment]
@haizaar that's the intention, yes
