### ISSUE TITLE
Cluster concurrent rebalance ignored on node allocation exclusion

### ISSUE THREAD

**Issue by lb425** [elastic/elasticsearch#14057]
The setting cluster.routing.allocation.cluster_concurrent_rebalance appears to be ignored when moving shard off a node that has been excluded from allocation with the setting cluster.routing.allocation.exclude._ip .

ES Version: 1.7.2

Repeatedly experienced with the following steps:
set cluster.routing.allocation.cluster_concurrent_rebalance to 1
exclude node from allocation with cluster.routing.allocation.exclude._ip

This results in 80 shards rebalancing at a time until all shards are removed from the excluded node.

**Comment by clintongormley** [comment]
Investigation required

**Comment by ywelsch** [comment]
I can confirm the issue. The root cause is that rebalancing constraints are not taken into consideration when shards that can no longer remain on a node need to be moved. AFAICS, it affects the following options:

- cluster.routing.allocation.cluster_concurrent_rebalance
- cluster.routing.allocation.allow_rebalance
- cluster.routing.rebalance.enable
- index.routing.rebalance.enable
- rebalance_only_when_active
