### ISSUE TITLE
Trouble sorting by "bucket_script" in 2.0.0-rc1

### ISSUE THREAD

**Issue by bkj** [elastic/elasticsearch#14101]
I'm running into some trouble trying to sort by a `bucket_script` aggregation. Attached is an example that illustrates the difficulty.

If we add these fake documents:

```
curl -XPUT http://localhost:9200/test/test/1 -d '
{
    "ind" : 1,
    "my_field" : 1
}
'

curl -XPUT http://localhost:9200/test/test/2 -d '
{
    "ind" : 1,
    "my_field" : 50
}
'

curl -XPUT http://localhost:9200/test/test/2 -d '
{
    "ind" : 2,
    "my_field" : 99
}
'
```

This works:

```
curl -XPOST http://localhost:9200/test/_search -d '{
    "aggs" : {
        "test" : {
            "terms" : {
                "field" : "ind",
                "order" : {
                    "var1.value" : "asc"
                }
            },
            "aggs" : {
                "var1" : {"sum" : {"field" : "my_field"}},
                "var2" : {"sum" : {"field" : "my_field"}},
                "bs"   : {
                    "bucket_script" : {
                        "script" : "var1 + var2",
                        "buckets_path" : {
                            "var1" : "var1",
                            "var2" : "var2"
                        }
                    }
                }
            }
        }
    }
}'
```

but this doesn't:

```
curl -XPOST http://localhost:9200/test/_search -d '{
    "aggs" : {
        "test" : {
            "terms" : {
                "field" : "ind",
                "order" : {
                    "bs.value" : "asc"
                }
            },
            "aggs" : {
                "var1" : {"sum" : {"field" : "my_field"}},
                "var2" : {"sum" : {"field" : "my_field"}},
                "bs"   : {
                    "bucket_script" : {
                        "script" : "var1 + var2",
                        "buckets_path" : {
                            "var1" : "var1",
                            "var2" : "var2"
                        }
                    }
                }
            }
        }
    }
}'
```

Is such an ordering possible at the moment?  Am I just using the wrong syntax? If this is not possible, are there any plans to make it possible in the future?

Thanks!
Ben

**Comment by clintongormley** [comment]
@colings86 could you comment on this please?

**Comment by colings86** [comment]
In order to be able to use an aggregation for sorting the terms aggregation it must currently be a numeric metric aggregation. Pipeline Aggregations are a different family of aggregations than the Metric Aggregations and cannot be used for sorting. You couldn't sort using a Pipeline aggregation because they are only executed in the reduce phase on the coordinating node and so you do not have the information on the shard in order to be able to sort the shards buckets to pick the top N to send to the coordinating node.

**Comment by bkj** [comment]
Thanks for the answer -- that's sortof what I was guessing.  Do you think it's possible to order the results by using something else?  Like the `scripted_metric` aggregation that allows user defined `map`, `combine`, and `reduce` scripts?

**Comment by colings86** [comment]
Copied from a similar conversation on the Discuss forums here: https://discuss.elastic.co/t/ordering-terms-aggregation-based-on-pipeline-metric/31839/2

The Scripted Metric Aggregation is part of the Metric Aggregation family but is not a Numeric Metric Aggregation since it returns an arbitrary object. However, there is an issue open in the Elasticsearch repo to add the ability to sort by an attribute of the Scripted Metric Aggregation: https://github.com/elastic/elasticsearch/issues/8486

**Comment by clintongormley** [comment]
Closing in favour of #8486
