### ISSUE TITLE
Max doc frequency percentage in More Like This query

### ISSUE THREAD

**Issue by maxcom** [elastic/elasticsearch#14114]
More Like This Query has max_doc_freq settings that can be used to remove high-frequency words from search. It is not a frequency but an absolute value. The problem that actual value for index depends on number of documents in the index - larger indexes requires larger values to filter out domain specific stop words. 

I found that XMoreLikeThis actually has `setMaxDocFreqPct(int maxPercentage)` method that recalculates percentage to actual number of documents in index.

However, this method is not available to client. I would be great if you add it to java client and HTTP API.

**Comment by amirhmd** [comment]
hi guys,

is this one still available?

**Comment by talevy** [comment]
This feature request is an interesting idea but since its opening we have not seen enough feedback that it is a feature we should pursue. We prefer to close this issue as a clear indication that we are not going to work on this at this time. We are always open to reconsidering this in the future based on compelling feedback; despite this issue being closed please feel free to leave feedback on the proposal (including +1s).
