### ISSUE TITLE
DateFieldMapper fails storing JSON-LD when property name contains `Date`?

### ISSUE THREAD

**Issue by jhberges** [elastic/elasticsearch#14152]
Storing the following fragment as part of a document cause `DateFieldMapper` to throw `IllegalArgumentException` with default setup.
Workaround is to disable "smart mapping" of date/time.

    ...
    "ccdm:publicationEndDateTime" : {
      "@type" : "xml:dateTime",
      "@value" : "2015-01-02T11:45:00Z"
    },
    "ccdm:publicationStartDateTime" : {
      "@type" : "xml:dateTime",
      "@value" : "2015-01-02T11:30:00Z"
    },
    ...

Fails at
https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/index/mapper/core/DateFieldMapper.java#L515 

The mapper will fail on the `@type` attribute.
A bit annoying, but auto-indexing of this field (or these documents) aren't crucial for our use, but perhaps such failures during automagic should be avoided?

Best regards, Jan-Helge

**Comment by clintongormley** [comment]
Indexing just the values that you provided work just fine.  The `@value` field is added as type date.  The problem comes when you try to index a value that isn't a valid date later on.

We can't tell if you intended these values to be indexed or not, so we're not going to silently swallow this exception.  However, you can add a dynamic mapping rule which maps any `@value` field as type:string, or `enabled:false` or whatever you need.
