### ISSUE TITLE
Bool query: apply minimumShouldMatch when explicitly set regardless of existing clauses

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#14167]
We internally adjust the minimum should match value depending on how many optional clauses we have. That works well in many cases, but we end up overriding an explicitly set value for instance if we have less optional clauses than the current value (see https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/common/lucene/search/Queries.java#L175). Let's say for example that we have no optional clauses and minimum should match is set to 1, we internally adjust it to 0 right before executing the query. I was discussing this today with @jpountz and this behaviour seemed odd, which is why I am opening this issue for discussion.

**Comment by jpountz** [comment]
I think we should remove this leniency.

**Comment by jimferenczi** [comment]
#15571 fixed the min should match when the number of optional clauses is smaller than the provided value. For instance you have 2 optional clauses and min should match is set to 3, in such case the query will now return 0 result. Regarding your example, min should match is ignored when there is no optional clauses so I don't think that #15571 changed anything here. I don't fully understand what you mean by "this behaviour seemed odd". What is the expected behaviour ? Should we translate the non optional clauses into optional ones and take the min should match into account ?

**Comment by javanna** [comment]
I see what you mean @jimferenczi  I think my example wasn't that representative, I had missed that with no optional clauses minimum should match gets ignored, which makes sense to me. What I cared about was that we don't override the explicitly set minimum should match depending on the number of optional clauses, otherwise could return results while it really shouldn't. I am happy, you fixed this, closing this issue.
