### ISSUE TITLE
Reject children documents that don't have a parent

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#14218]
Some of our search code assumes that all children documents have a parent, yet we don't enforce this at index time. This assumption looks sane to me (otherwise why would you put a document in a child type at all?) so we should fix our indexing to reject child documents that don't have a parent?

See https://discuss.elastic.co/t/elasticsearch-2-0-bool-query-with-inner-hits-and-parent-query/31706 for more background.

**Comment by dadoonet** [comment]
Just wondering what would happen if you have indexed a parent, some children and then you delete the parent...

I did not test it but I guess the DELETE operation will be successful, so what will happen to the search parts you mentioned earlier?

**Comment by jpountz** [comment]
I agree this can be an issue as well, but a different one? It is different to not have a value for the `_parent` field and to have a value that points to a document that does not exist.

**Comment by bevans88** [comment]
In a very simple Use Case that somewhat mirrors my current applications use of Parent/Child functionality:

- 'Book' Type that is a Child of 'Author' Type.
- 'Book' may, or may not have an Author. For instance we may have a 'Book' that we don't know the   author of .

 If it is enforced that all Child documents must have a Parent set then this becomes invalid.

As far as I'm aware having Child documents with no Parent set has also caused no problems with 'standard' search queries, with the current problem only arising due to the use of them in the recent Inner Hits functionality.

At the moment ElasticSearch actually allows for searching on Child documents that don't have a Parent set:
```
  "query": {
    "bool": {
      "must_not": [
        {
          "has_parent": {
            "parent_type": "Author",
            "query": {
              "match_all": {}
            }
          }
        }
      ]
    }
  }
```
Also, wouldn't the following cause problems (In the same way deleting a Parent would I assume):

- Index Child document with Parent that has not yet been indexed. 
- Run search on child documents.

**Comment by clintongormley** [comment]
This puts a burden on users to index parents then children in that order.  If you are (eg) taking a dump from a database then you may get documents in some random order.  This would also mean doing a real-time check for the existence of a parent any time we index a child doc.  Costly, no? 

Also the point of deleting parent docs without also deleting child docs is a valid one.  Either we have to special case the deletion of parent docs to first delete children, or we have to guard against the case where a child doc may not have parents.  

The above is making me lean towards ensuring that we can always handle the case where corresponding parents don't exist.

**Comment by clintongormley** [comment]
I think I may have misunderstood this - it's not about the existence of the parent document, but about whether the child has a parent specified...  in which case I agree, we should enforce this.

> If it is enforced that all Child documents must have a Parent set then this becomes invalid.

In your example, you can simply have an UnknownAuthor parent document.

**Comment by jpountz** [comment]
> I think I may have misunderstood this - it's not about the existence of the parent document, but about whether the child has a parent specified... in which case I agree, we should enforce this.

Exactly, this is what I meant.

**Comment by martijnvg** [comment]
@clintongormley @jpountz the index time check is insufficient. We only check if a routing value has been specified. When the parent id is specified at index we also set the routing value, so that passes the check. If no parent id is specified we fail, but if only a routing value is specified (like was reported in the forum) then we don't fail while we should.

**Comment by mayya-sharipova** [comment]
Closing this issue, as in 6.x we already don't allow to index child docs  where `parent` field  is not specified:
```
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "failed to parse"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "failed to parse",
    "caused_by": {
      "type": "illegal_argument_exception",
      "reason": "[parent] is missing for join field [jf]"
    }
  },
  "status": 400
}
```

We still don't enforce that `parent` should be valid and existing, but it is a different issue.

**Comment by jaddison** [comment]
> We still don't enforce that parent should be valid and existing, but it is a different issue.

I think if this is ever 'fixed', it will break valid scenarios (like one I have). I hope it is never considered something to fix. 🙏🏼
