### ISSUE TITLE
rpm uses non-portable `--system` flag to `useradd`

### ISSUE THREAD

**Issue by OrangeDog** [elastic/elasticsearch#14211]
If it used the equivalent `-r` flag instead then it would work on older systems, in particular el5.
Otherwise, the `useradd` fails but the install continues, resulting in a broken installation where everything is owned by root.

**Comment by girirajsharma** [comment]
Makes sense to me. `--system` flag wasn't introduced in CentOS prior to CentOS 6.0 [http://www.freebsd.org/cgi/man.cgi?query=useradd&apropos=0&sektion=8&manpath=CentOS+6.0&arch=default&format=html]
Although, these days almost all linux distributions have the support of both the flags.
May be I can fix this if the use of flag `r` instead of `system` is preferred.

**Comment by jordansissel** [comment]
This was fixed by https://github.com/elastic/elasticsearch/pull/14596
