### ISSUE TITLE
Terms query ignores minimum_should_match when used in must_not clauses

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#14223]
A `terms` query inside a `bool` query's `must` clause will respect the `minimum_should_match` setting, however, when the same terms clause is embedded inside a `must_not` clause the setting is silently ignored.

[Example GIST with a graph-walking scenario ](https://gist.github.com/markharwood/44aadd21cde319234f90)

The bug is because internally the must_not clauses are rewritten to filters and therefore do not execute the usual `minimum_should_match` query logic, in the interests of performance.

@jpountz  suggested throwing an error if the user passes a `miniumum_should_match` setting in a  `terms` query used as part of a must_not clause.
Internally this makes sense for performance and code maintenance reasons but does come at a cost for end users. This would mean inconsistency in the syntax (must vs must_not behaviour of `terms`) and the work-around is verbose (use a bool `should` with array of individual `term` queries followed by minimum_should_match).

**Comment by jpountz** [comment]
This inconsistency comes from 1.x where the terms query would generate a bool query and the terms filter would generate a terms filter. Now that we merged both, we have to accept the `minimum_should_match` parameter in all cases and I think the bug is that we don't fail when `min_should_match` is set while we are in a `filter` context.

`minimum_should_match` is currently deprecated so that we can make the `terms` query always generate a Lucene TermsQuery instead of a BooleanQuery when used in a query context, which I think is important for the predictability of the query DSL. Otherwise, queries would have very different performance characteristics when used as a filter or a query, would fail when there are more than 1024 clauses when used as a query and not a filter, etc. This will help remove the inconsistency as well when `minimum_should_match` is finally removed.

I agree the bool syntax is a bit verbose, but I don't think that the terms query should be the solution. Maybe we can find ways to simplify the bool syntax when all sub queries are term queries.

**Comment by clintongormley** [comment]
Min should match hasn't been documented in the terms query since 2.0.  Let's deprecate it now and remove it in 3.0

**Comment by mayya-sharipova** [comment]
Closing, as "minimum_should_match" has been removed from terms query in: https://github.com/elastic/elasticsearch/commit/d7cd5ce60d0589562ff8f64c88e7c989c155a7ac
