### ISSUE TITLE
Security Manager breaks JConsole and VisualVM

### ISSUE THREAD

**Issue by otisg** [elastic/elasticsearch#14268]
Hi,

Short version: with security manager enabled one cannot connect to ES with JConsole or VisualVM - permission denied.  I'm assuming this is not a known issue because it seems like a pretty significant problem.

See https://discuss.elastic.co/t/security-policy-in-2-0-breaks-jconsole-and-visualvm/32861

**Comment by rmuir** [comment]
Looks like JConsole/VisualVM are the broken ones, not the other way around.

`attempt to add a Permission to a readonly Permissions object` in that stack indicates bugs in their code, not ours. See javadocs for Policy: 

`Applications are discouraged from calling this method since this operation may not be supported by all policy implementations. Applications should solely rely on the implies method to perform policy checks. `

They are getting this value because we don't implement `getPermissions(CodeSource)/getPermission(ProtectionDomain)` nor should we since its not necessary. And they are not checking the result value for whatever it is they are doing to see if its http://docs.oracle.com/javase/8/docs/api/java/security/Policy.html#UNSUPPORTED_EMPTY_COLLECTION for optional methods.

**Comment by s1monw** [comment]
> Looks like JConsole/VisualVM are the broken ones, not the other way around.

I agree with this observation we can't and shouldn't do anything on our side to compensate for problems like these in 3rd party applications. It's just not maintainable and sacrificing security for problems like this is not an option given all the history along those lines. I really think this should be communicated to the folks that maintain these apps. @otisg do you wanna help here communicating this? you seem to be a user of this and I guess you can push them a bit?

**Comment by rmuir** [comment]
There is already a bug report for it: https://bugs.openjdk.java.net/browse/JDK-8014008

**Comment by samcday** [comment]
We were using JMX + Datadog JMX integration to get heap + gc stats for Elasticsearch into Datadog. Is there any workaround or are we 100% screwed here? :)

**Comment by rmuir** [comment]
You gotta at least do your part and use the latest version of elastisearch: #14274
