### ISSUE TITLE
Remove threadpool type cached setting from documentation?

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#14294]
We don't recommend changing the size of the thread pools, and certainly not recommend setting them to unbounded.  Seems like documenting the configuration to modify our thread pools to [cached](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-threadpool.html#_literal_cache_literal) without sufficient warnings will do more harm than good.

**Comment by jasontedor** [comment]
I think that we should go further than merely removing it from the documentation, but actually forbidding any thread pool other than the generic thread pool of being of type "cached". The generic thread pool should remain as "cached" because operations that are submitted to this thread pool can not block nor be rejected; we remain very careful about which operations are submitted to this thread pool. I've opened #14336 to address.

**Comment by bleskes** [comment]
I wonder if we should allow to configure the cache types at all these days. Might be the simplest to just remove the option and fix the defaults we have now.

**Comment by jasontedor** [comment]
I've added the [discuss label](https://github.com/elastic/elasticsearch/labels/discuss) to open up if we want to take this further than merely banning the `cached` thread pool type and actually banning changing any thread pool type.

**Comment by jpountz** [comment]
+1 to not allow to configure threadpool types at all

**Comment by s1monw** [comment]
+1

**Comment by jasontedor** [comment]
I've closed #14336 in favor of #14367 which takes the original pull request further by forbidding the changing of the thread pool type for any thread pool.
