### ISSUE TITLE
usage quota on every data path

### ISSUE THREAD

**Issue by yiguolei** [elastic/elasticsearch#14299]
Currently, cluster.routing.allocation.disk.watermark.low and cluster.routing.allocation.disk.watermark.high , these two parameters control the disk allocation. But both of them calculate the usage and free space of the whole disk not the specified path. It works only when there is only one elasticsearch instance running on the disk and it will not work when there are two or more instances running on the same disk. Does elasticsearch have a setting to control the data path usage or path disk quota? If we have this setting, then we can deploy two or more elasticsearch instances using same disks.

**Comment by clintongormley** [comment]
@yiguolei I don't understand why would you want to run two instances on the same disks?  You're splitting the I/O between two instances.  

Also, a path doesn't have a max amount of space.  Only the disk has that.

**Comment by simpleopen** [comment]
Hi, @clintongormley ,

Tentatively,  I think I have a user case of @yiguolei 's proposal. The feature of disk usage quota per data path can help prevent a single point of issue from causing all-cluster data loss incident. Do you think we can maybe revisit this discussion, and get your feedbacks?

We have a self-hosted Elasticsearch cluster, accepting log feeds from multiple sources. Due to a Logstash configuration error, one feeding source suddenly went crazy by sending a huge amount of data within a short period. We have a very big disk buffer, but it was still eaten up. All the nodes got a disk full, and the cluster’s functionality came into a halt. It took some time to fix the problem, and incoming data is lost during the gap.

Feels like, a single point of issue should not fail the entire cluster, and we want to look into possibly restricting total disk usage of indices from each source.

On our cluster, each source creates one index per day, with naming pattern source_name-YYYY-MM-DD, and we can get total disk usage per source by command “du -chs /indices/source_name-* | grep total”.
Tentatively thinking, maybe we can have a watchdog script to check it, and close or delete the indices that exceed the quota. I am wondering if there is any existing tool for it?

I am also wondering how Elasticsearch Cloud handles disk usage issue, assuming there are also multiple clients on their shared host. Is it deploying one virtual machine for each client or something similar?

Feedbacks and pointers will be highly appreciated.
