### ISSUE TITLE
Optimize query parsing based on how a query will be used

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#14335]
Today if you ask the `terms` query parser to generate a query, it will create a `TermsQuery`. However a `DocValuesTermsQuery` would match exactly the same documents, and would perform worse when used for iterating over matches, but better when used to check whether some documents match. We could make the parser a bit smarter and sometimes generate a `DocValuesTermsQuery` instead of a `TermsQuery`.

I think there are at least two use-cases when using a `DocValuesTermsQuery` instead of a `TermsQuery` would be an easy win:
- excluded clauses (`must_not` in a `bool`)
- in `filter`/`filters` aggregation

I used `TermsQuery` as an example, but it applies more generally to all multi-term queries that can also be executed via doc values such as ranges.

Ideally this would be a Lucene feature, but I'm not sure how this could work given that Lucene doesn't have a schema. So I think elasticsearch is the right place to put it?

**Comment by rmuir** [comment]
I'm concerned about this optimization because i think it can easily open a can of worms where things start to look like they used to.

I also think it only really applies for more rare / abuse type cases: its *extraordinarily* risky and in the worst case acts like a DBMS full table scan.

So, I don't think we should do it.

**Comment by polyfractal** [comment]
At least for the aggregation `filter` case, can we just default to `DocValuesTermsQuery` on the Elasticsearch side?  It seems like the agg filter will always satisfy the case of "just matching" instead of iterating?

I've been running into a lot of slow aggs due to `filter` agg buckets lately.  Rewriting it is usually non-trivial (have to move some filters to the query, convert some to `terms` aggs and then exclude terms you aren't interested in, etc).

I don't really know enough Adrien's suggestion to comment intelligently, but it's a noticeable performance problem for aggs anyhow.  If aggs could be a bit smarter it'd be a nice win for users.

**Comment by jpountz** [comment]
I'm a bit torn here. I certainly agree with Robert that I don't want to get back to the previous situation where we were trying to do too much on top of Lucene and often ended up making worse decisions than the ones that Lucene would have made by itself. Given that the new query improvements (improved cost API, two-phase iteration, etc.) only landed into the hands of our users two weeks ago, I suggest that we wait for a couple months before reevaluating this issue so that we have better perspective.

**Comment by polyfractal** [comment]
Works for me, I certainly don't know enough about how all the components fit together to have a well-educated opinion.  :)

**Comment by colings86** [comment]
Closing as this is no longer relevant

**Comment by jpountz** [comment]
Superseded by https://issues.apache.org/jira/browse/LUCENE-7055
