### ISSUE TITLE
+ in delimiter not working

### ISSUE THREAD

**Issue by bigterminal** [elastic/elasticsearch#14344]
Trying to index and find the token "c++" in text. 
In settings I've tried escaping the +, using unicode, and doing a double ++. Its still returning everything that has a "C" in it as a matching results, as if the + was not considered an alphanum.

See my settings below: 

    settings: {
      analysis: {
        filter: {
          symbol_filter: {
            type: "word_delimiter",
            type_table: ["# => ALPHANUM", "@ => ALPHANUM", "/ => ALPHANUM", "$ => ALPHANUM", "& => ALPHANUM", "+ => ALPHANUM", "- => ALPHANUM"]
          }
        },
        analyzer: {
          symbol_analyzer: {
            type: "custom",
            tokenizer: "standard",
            filter: ["lowercase", "symbol_filter"]
          }
        }
      }
    }

**Comment by cbuescher** [comment]
Hi @bigterminal, 
Filters, like the `word_delimiter` in your example, are working on a stream of tokens from the tokenizer. Since you are using the standard tokenizer, this will already remove most punctuation, including the `+` character. The whitespace tokenizer should help. Please ask questions about usage in the forums at https://discuss.elastic.co/ in the future.
