### ISSUE TITLE
Can't start ES after upgrading from 1.7.1 to 2.0

### ISSUE THREAD

**Issue by futurekill** [elastic/elasticsearch#14359]
I'm getting the following in our test cluster when I try to start up:

`Exception in thread "main" java.lang.IllegalStateException: unable to upgrade the mappings for the index [dev-note-index], reason: [Field name [listing.requestAmount] cannot contain '.']`

Any ideas?

**Comment by futurekill** [comment]
I upgraded using the ES yum repo...here's what's installed now:

Name        : elasticsearch
Version     : 2.0.0
Release     : 1
Architecture: noarch
Install Date: Thu 29 Oct 2015 05:08:13 PM UTC
Group       : Application/Internet
Size        : 31905528
License     : (c) 2009
Signature   : RSA/SHA1, Thu 22 Oct 2015 08:41:40 AM UTC, Key ID d27d666cd88e42b4
Source RPM  : elasticsearch-2.0.0-1.src.rpm
Build Date  : Thu 22 Oct 2015 08:41:37 AM UTC
Build Host  : vagrant-ubuntu-trusty-64
Relocations : /usr
Packager    : Elasticsearch
Summary     : Distribution: RPM

**Comment by clintongormley** [comment]
It's in the breaking changes docs: https://www.elastic.co/guide/en/elasticsearch/reference/current/_mapping_changes.html#_field_names_may_not_contain_dots

We recommend using the migration plugin to detect these issues before upgrading: https://github.com/elastic/elasticsearch-migration/

**Comment by aanm** [comment]
@clintongormley But why? Is it difficult to solve that? I mean, if elasticsearch is a document oriented database why can't save json documents since json supports dots in field names?

**Comment by rjernst** [comment]
@aanm Json does not support dots in field names (at least not so far as not using quotes); using a dot implies the part before the dot is an object. The problem with this in elasticsearch is ambiguity, and indeterminism. When a user passes say "foo.bar" as a field name, should that be an object field "foo", with a "bar" field, or a single field "foo.bar"? What happens when a field "foo.bar" exists at the same time an object field "foo" with a subfield "bar" exists? These are the problems that led to removing dot as a valid character in field names.

**Comment by aanm** [comment]
@rjernst Thanks for the reply. Exactly! It supports as far I use quotes, which I do. I think, if a user says 'foo.bar' it's wrong and should cause an exception but if the user says '"foo.bar"' (see the double quote) elastic should consider a single field "foo.bar".
> What happens when a field "foo.bar" exists at the same time an object field "foo" with a subfield "bar" exists?
Nothing, they are different things ' "foo.bar" ' is a field.

**Comment by rjernst** [comment]
>> What happens when a field "foo.bar" exists at the same time an object field "foo" with a subfield "bar" exists?

> Nothing, they are different things ' "foo.bar" ' is a field.

But now you have two fields, with the same path. Remember that fields in 2.0 must be specified using their full path. The field "foo.bar" has the same path as that with object field "foo" and sub field "bar".

**Comment by diranged** [comment]
Hey guys this is a pretty amazingly painful change. We have 30 days worth of indexed data from our Flume pipeline ... and you guessed it, all 30 indexes have a `flume.syslog.status` field ([FLUME-2838](https://issues.apache.org/jira/browse/FLUME-2838)).

We're going to get around this temporarily by actually striping this header out with our custom ElasticSearch Sink ... but even that is going to delay our upgrade to ES 2.0 by 30 days whlie we wait for our indexes to roll over.

Is there any way that this change can be made optional rather than a completely blocking change?

**Comment by rjernst** [comment]
> Is there any way that this change can be made optional rather than a completely blocking change?

@diranged Sorry, it cannot. The major improvements to mappings in 2.0 were to eliminate the possibility of ambiguity in fields. That cannot be made optional as the inner workings of mappings now depend on that uniqueness.

**Comment by diranged** [comment]
@rjernst and without dumping and re-indexing ~9 billion events, we can't *change* the field name of previously indexed data.. right?

**Comment by s1monw** [comment]
> Is there any way that this change can be made optional rather than a completely blocking change?

this can't be done differently. You guys ran into a long standing bug that we fixed. Waiting 30 days is not the end of the world. Changes like this must be done at some point, if you make it lenient you just end up with more trouble. If you wait 30 days you will be able to go to 2.1 even which might be even more stable.

**Comment by rjernst** [comment]
@diranged Yes, you will need to reindex.

**Comment by aanm** [comment]
> But now you have two fields, with the same path. Remember that fields in 2.0 must be specified using their full path. The field "foo.bar" has the same path as that with object field "foo" and sub field "bar".

@rjernst Okay, can provide me a path example?

**Comment by rjernst** [comment]
@aanm "path" is the term used for the full canonical name for a field. This includes any object fields it is part of, from the root of the mappings. "foo.bar" is the path (ie the full canonical name) for an object field called "foo", with a subfield "bar".

**Comment by aanm** [comment]
@rjernst Okay "foo.bar" is not supported, how about "foo\.bar"?

**Comment by rjernst** [comment]
Escaping is not supported at this time. I won't see it will never be supported, but it is sufficiently complicated enough with all the places we access/use field names that it would be a largish change IMO.
