### ISSUE TITLE
Forwardport BWC test fixes to gradle branches

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#14406]
Once gradle has stabilized on master we'll need to forward port https://github.com/elastic/elasticsearch/pull/13477 to those branches. Normally forwardporting/backporting doesn't merit its own issue but in this case we'll be committing to the maven branches long before we'll be able to commit to the gradle branches.

**Comment by nik9000** [comment]
To make this clear:
Even though 3.0.0 doesn't have to be wire compatible with any released projects we can forward port this to master and only create the "current" tests. These tests validate the BWC tests by running them against the current version.

**Comment by brwe** [comment]
Discussed with @rjernst and @nik9000 and we decided that best would be to first figure out how many of these actually need the infrastructure with the ExternalNodeService etc. because alternatively we might also just spin up a mixed version cluster and run the rest tests against that. It might even give us more coverage. Some test explicitly test rolling upgrade though. I'll make a list and then we can discuss further.

**Comment by brwe** [comment]
I looked at all bwc tests and asked around what they actually test etc and here is a summary:

We can replace most of the tests with REST tests although we would lose a little bit of randomness. However, there are some things that cannot be testes with REST tests alone:

- transport clients that connect to mixed version clusters (see TransportClientBackwardsCompatibilityIT.testSniffMode)
- rolling upgrades, see BasicBackwardsCompatibilityIT.testIndexRollingUpgrade/testIndexUpgradeSingleNode
- full cluster restarts and expected behavior afterwards, see RecoveryBackwardsCompatibilityIT.testReusePeerRecovery

These tests attempt to simulate real world behavior but the question is how successful this is. For example, with the current setup we cannot install plugins. Also, while we simulate some things these tests don't actually stress the cluster much. For example, we have a test that indexes, upgrades a node, indexes, upgrades a node and so forth but none that indexes while nodes are upgraded. 
It seems wrong to to have these kind of tests in our current setup and we should rather have a dedicated way to simulate an actual cluster and check things like indexing while we upgrade, recovery, etc. As to how this should look like I do not know yet.



In any case, while I believe we would profit from a separation of stress tests and just mixed version cluster tests it will be a lot of work and we might also decide to postpone this and simply port the current mechanism to master (which will be much less work). 

Below is a list with all test and what I think we should do with them. 

Let me know what you think!

Detailed list of all current bwc tests and what I think should be done with them:

The following tests can be replaced by REST tests:
-----------

BasicBackwardsCompatibilityIT:
    public void testExternalVersion() throws Exception {
    public void testInternalVersion() throws Exception {
    public void testIndexAndSearch() throws Exception {
    public void testNoRecoveryFromNewNodes() throws ExecutionException, InterruptedException {
    public void testUnsupportedFeatures() throws IOException {
    public void testExistsFilter() throws IOException, ExecutionException, InterruptedException {
    public void testDeleteRoutingRequired() throws ExecutionException, InterruptedException, IOException {
    public void testIndexGetAndDelete() throws ExecutionException, InterruptedException {
    public void testUpdate() {
    public void testAnalyze() {
    public void testExplain() {
    public void testGetTermVector() throws IOException {
    public void testIndicesStats() {
    public void testMultiGet() throws ExecutionException, InterruptedException {
    public void testScroll() throws ExecutionException, InterruptedException {
    public void testSimpleFunctionScoreParsingWorks() throws IOException, ExecutionException, InterruptedException {

ClusterStateBackwardsCompatIT:
    public void testClusterState() throws Exception {
    public void testClusterStateWithBlocks() {


GetIndexBackwardsCompatibilityIT:
    public void testGetAliases() throws Exception {
    public void testGetMappings() throws Exception {
    public void testGetSettings() throws Exception {
    public void testGetWarmers() throws Exception {

NodesStatsBasicBackwardsCompatIT:
    public void testNodeStatsSetIndices() throws Exception {
    public void testNodeStatsSetRandom() throws Exception {


SignificantTermsBackwardCompatibilityIT:
    public void testAggregateAndCheckFromSeveralShards() throws IOException, ExecutionException, InterruptedException {


These will be tricky to have as REST tests but the [repository hdfs plugin](https://github.com/elastic/elasticsearch/tree/master/plugins/repository-hdfs/src/test/resources/rest-api-spec/test/hdfs_repository) has some snapshot/restore REST tests already that we can make use of:

SnapshotBackwardsCompatibilityIT
public void testBasicWorkflow() {
public void testSnapshotMoreThanOnce() throws Exception {


 


We need a dedicated test that connects clients to a mixed version cluster to replace 
-----------

TransportClientBackwardsCompatibilityIT:
    public void testSniffMode() throws ExecutionException, InterruptedException {
UnicastBackwardsCompatibilityIT:
    public void testUnicastDiscovery() {





We need dedicated stresstests for:
-----------

UpgradeIT:
    public void testUpgrade() throws Exception {

RecoveryBackwardsCompatibilityIT
    public void testReusePeerRecovery() throws Exception {

BasicBackwardsCompatibilityIT:
    public void testIndexUpgradeSingleNode() throws Exception {
    public void testIndexRollingUpgrade() throws Exception {
    public void testRecoverFromPreviousVersion() throws ExecutionException, InterruptedException {

For the latter we should also add a regular Integration tests that indexes while a whole index with replicas is moved around.

I am unsure what to do with this one:
-----------

BasicAnalysisBackwardCompatibilityIT:
public void testAnalyzerTokensAfterUpgrade() throws IOException, ExecutionException, InterruptedException {

**Comment by javanna** [comment]
I think we can get rid of `UnicastBackwardsCompatibilityIT`, it was meant to test unicast discovery when we didn't use it by default. If we create a mixed cluster we will use unicast which gets then tested indirectly. Other way around, not sure if we need to write some bw comp test for multicast at this point.

`TransportClientBackwardsCompatibilityIT` could be part of some different test infra for the java api (which would need more tests if we care). This specific test is about sniff mode, as we don't test sniffing elsewhere. If we move to a REST test infrastructure, we would also need a test for transport client without sniff, which is now tested indirectly by any of our bw comp tests as we use it to connect to the external cluster.

**Comment by clintongormley** [comment]
Comment copied from #18065:

> The 2.x branch has a bunch of backwards compatibility tests and we need to examine each one and decide if we need to port it to the master branch (and then 5.x branch, if we've cut such a branch before doing this issue.)

> Many of them just want to run features against a mixed version cluster. We should get good enough coverage for those by running all the REST tests. Right now we run the core REST tests. I think all we have to do is run all the plugin REST tests for those tests.

> Others assert that things work during a rolling restart. Those are going to be harder to port.

**Comment by rjernst** [comment]
I'm closing this as our backwards compatibility testing has been improved considerably since switching to gradle, and forward porting any changes from this old issue would be very difficult and probably not add much of any additional coverage.
