### ISSUE TITLE
Inner hits not returning deep fields values

### ISSUE THREAD

**Issue by albanm** [elastic/elasticsearch#14475]
Hello,

I try to fetch inner hits with specific fields. Everything works fine when the fields are at the root of the nested document, but it doesn't when the field has a composed key with some dots.

I have this with ElasticSearch 1.7.2.

Here is a simple script to illustrate the problem:

```shell
printf "Delete index:\n\n"
curl -XDELETE localhost:9200/test

printf "\n\nPrepare mappings with some nested object:\n\n"
curl -XPUT localhost:9200/test -d '{
  "mappings": {
    "article": {
      "properties": {
        "comments": {
          "type": "nested"
        }
      }
    }
  }
}'

printf "\n\nInsert an article with nested comment:\n\n"
curl -XPUT localhost:9200/test/article/1 -d '{
  "title": "Inner hits fields bug",
  "comments": [{
    "user": {
      "id": "albanm"
    },
    "content": "What is going on ?"
  }]
}'

printf "\n\nFlush index:\n\n"
curl -XPOST 'http://localhost:9200/test/_flush'

printf "\n\nSearch articles with nested comments in inner hits. In inner hits results the field 'content' IS PRESENT but 'user.id' IS NOT:\n\n"
curl -XPOST localhost:9200/test/article/_search -d '{
  "query": {
    "nested": {
      "path": "comments",
      "query": {
        "match_all": {}
      },
      "inner_hits": {
        "fields": ["content", "user.id"]
      }
    }
  }
}'

printf "\n\n"

```

**Comment by albanm** [comment]
FYI storing the individual field doesn't seem to change anything.

**Comment by clintongormley** [comment]
There is a discrepancy between how paths are specified for `fields` and `_source`:

`fields` can only return stored fields as inner hits:

    PUT /test
    {
      "mappings": {
        "article": {
          "properties": {
            "comments": {
              "type": "nested",
              "properties": {
                "content": {
                  "type": "string",
                  "store": true
                },
                "user": {
                  "properties": {
                    "id": {
                      "type": "string",
                      "store": true
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    
    
    PUT /test/article/1
    {
      "title": "Inner hits fields bug",
      "comments": [
        {
          "user": {
            "id": "albanm"
          },
          "content": "What is going on ?"
        }
      ]
    }
    
The full path must be specified for stored fields:

    POST /test/article/_search
    {
      "query": {
        "nested": {
          "path": "comments",
          "query": {
            "match_all": {}
          },
          "inner_hits": {
            "fields": [
              "comments.user.id",
              "comments.content"
            ]
          }
        }
      }
    }
    
But `_source` prepends the path of the nested field:

    POST /test/article/_search
    {
      "query": {
        "nested": {
          "path": "comments",
          "query": {
            "match_all": {}
          },
          "inner_hits": {
            "_source": [
              "user.id",
              "content"
            ]
          }
        }
      }
    }
    
@martijnvg looks like a bug to me?

**Comment by martijnvg** [comment]
@clintongormley @albanm The reason why there is a discrepancy between `fields` and `_source` is just because the two are differently implemented. The `fields` requires the field to exist in the mapping and therefor the full path needs to be provided, whereas `_source` doesn't require that and just retrieves the relevant bits from the _source (map of maps).

This discrepancy is noticeable when using inner hits, because the actual source of an inner hit is different than the source of a top level hit. (the _source of the inner hit is a subset of the _source of a top level hit)
So I'm not sure if this is a bug, because the _source is actually just different in the cases.

Another thing is that the `_source` allows to include/exclude also properties that are unmapped. (in cases where object field is configured to be disabled), so that is also a reason that this feature is differently implemented.

**Comment by albanm** [comment]
The behavior that I noticed is still a bug I think. Let's forget _source, and just look at my initial example. The field "content" was successfully extracted from _source and returned without being stored nor prefixed by "comments.", while "user.id" was not.

By the way I switched to using _source filtering as I now see that my problem is with a deprecated functionality:

["This functionality has been replaced by the source filtering parameter."](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/search-request-fields.html).

**Comment by clintongormley** [comment]
> The behavior that I noticed is still a bug I think. Let's forget _source, and just look at my initial example. The field "content" was successfully extracted from _source and returned without being stored nor prefixed by "comments.", while "user.id" was not.

It's a bit more complicated than that :)  Before 2.0, you could reference fields either with just the name, or with the full path.  `content` was actually being retrieved from the source field, and could be found because you used the short name.  `user.id` however is neither the short name nor the full path.

**Comment by albanm** [comment]
Ok, thanks for the explanations !
