### ISSUE TITLE
Elasticsearch publishes an address/port combination to which it isn't bound

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#14503]
It looks like you can convince Elasticsearch to publish an address/port combination to which it isn't bound. I'm not 100% sure the cause but it produces fun output like:
```
[2015-11-03 16:48:37,979][INFO ][transport                ] [external_0] publish_address {127.0.0.1:9400}, bound_addresses {[::1]:9400}, {127.0.0.1:9402}
```

I checked for a few minutes and didn't see the place where elasticsearch makes sure that its bound both ipv4 and ipv6 under the same port. So maybe it doesnt?

**Comment by nik9000** [comment]
Found in 2.2.0. I'm not sure how far back it goes nor how important it is.

**Comment by rmuir** [comment]
the whole point of having a publish address is to lie about what you are bound to. Its a really expert option like that, you do it if you are behind static NAT or something and have that firewall mapping you via a different ip/port.

personally, i'm not sure its needed at all really, if some code is reworked (e.g. i talk to you on the address you talked to me on). but in any case, this is intentional that its not checked.

but i do think its critical that its adjusted in the documentation, almost nobody should be using this parameter unless they are an expert.

**Comment by rmuir** [comment]
I spoke with @nik9000 about this on always on: there are competing problems. One is that automatic publish address selection is just address section, does not select the port number: which could happen if someone binds to [::1]:9200 and 127.0.0.1:9201 (something running on the last one). So in this case, things are simply wrong.

The other is that publish can be manually specified for expert cases, so we have to be careful. Nik is going to look into fixing the code.

Additionally, going along the path of "publish host is pretty confusing for most", more ideas:
* moving bind.host/publish.host to an expert setting of the docs:  "network.host" is preferred.
* remove warnings about publish host autoselection (in 2.x/master only right now), as we don't want to encourage people specifying it.

**Comment by bleskes** [comment]
FYI we have a related build failure: https://github.com/elastic/elasticsearch/issues/14513
