### ISSUE TITLE
RareClusterStateIT#testDelayedMappingPropagationOnPrimary test failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#14513]
build url: http://build-us-00.elastic.co/job/es_core_master_strong/5442/

The following reproduce line made the test fail once locally:

```
gradle :core:integTest -Dtests.seed=AA231B6B048C00 -Dtests.class=org.elasticsearch.indices.state.RareClusterStateIT -Dtests.method="testDelayedMappingPropagationOnPrimary" -Des.logger.level=DEBUG -Dtests.security.manager=true -Dtests.nightly=false -Dtests.heap.size=1024m -Dtests.jvm.argline="-server -XX:+UseSerialGC -XX:-UseCompressedOops -XX:+AggressiveOpts" -Dtests.locale=ar_YE -Dtests.timezone=Brazil/West
```

But now I can make it fail again...

This test also failed yesterday: http://build-us-00.elastic.co/job/es_core_master_small/5436/
Before that I can't find any other failures.

**Comment by bleskes** [comment]
I briefly looked at this and can add some pointers to where the problem lies. Basically the publish address is combination of a host of the ipv4 bound address and the port of ipv6 :

```
1> [2015-11-03 05:25:45,601][INFO ][org.elasticsearch.test.transport] [node_t0] publish_address {127.0.0.1:9400}, bound_addresses {[::1]:9400}, {127.0.0.1:9401}
```

The result publish address is actually the address another node is bound to, which causes confusion :)

Somewhere in `NettyTransport#bindServerBootstrap(java.lang.String, java.net.InetAddress, org.elasticsearch.common.settings.Settings)` things go wrong..

**Comment by bleskes** [comment]
it seems we are already tracking this here: https://github.com/elastic/elasticsearch/issues/14503
