### ISSUE TITLE
Multiple Types for @timestamp field

### ISSUE THREAD

**Issue by DKribl** [elastic/elasticsearch#14520]
Hey,

Since I updated Elasticsearch to 2.0, I get following Error:
```
failed to execute bulk item (index) index {[logstash-2015.11.04](...)java.lang.IllegalArgumentException: Mapper for [@timestamp] conflicts with existing mapping in other types:
[mapper [@timestamp] is used by multiple types. Set update_all_types to true to update [format] across all types.]
```

Hope you can help me guys!
Greetings

**Comment by jordansissel** [comment]
@DKribl Logstash, by default, will set the `@timestamp` field to be a date. Based on your error, this looks like an expected failure that is _new_ to Elasticsearch 2.0 because in 2.0, ES will enforce more safety controls on conflicting mappings.

This may be easiest to resolve on discuss.elastic.co since I think this is a configuration problem (the way Logstash may be configured? or whatever you have writing into Elasticsearch).

**Comment by DKribl** [comment]
Hey,

thanks for the quick response. Unfortunately the errors increased massively after updateing, so I wasn't able to use my ELK stack anymore. Had to downgrade to 1.7. I will now use a clean ELK Stack to collect new data! This issue can be closed now, thanks :+1:  :-)
