### ISSUE TITLE
mGET API doesn't have an option to not return metadata fields

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#14556]
In the GET API you can specify the URL as `/{index}/{type}/{id}/_source` and it will return only the _source in the response (i.e. will not return the metadata fields such as _id and _type). This is done by the RestGetSourceAction and is only available in the REST API (AFAIK).

This option does not seem to be available on the mGET API. You cannot set /_source on the request to exclude the metadata fields from the responses. You also cannot specify this on each get individually.

I wonder if we should add this? I can't think of a concrete use case for this but it is an inconsistency between the GET and mGET APIs. Marking this issue as 'Discuss' to see if there is any usecases which this would be useful

**Comment by s1monw** [comment]
We discussed this today and we all agreed that we don't like the inconsistency. On the one hand this is a nice usecase for response filtering (https://github.com/elastic/elasticsearch/pull/14390) but it would still have `_source : {}` in the response. On the other hand having dedicated REST handlers is not nice either so I wonder if we can implement this as a general feature on GET and push the real rendering in to `GetResponse#toXContent()` and pass a boolean via the `Params` if we only want the source or skip metadata? We can then also deprecate the `/_source` Url and just use a param instead.

**Comment by dakrone** [comment]
This feature request is an interesting idea but since its opening we have
not seen enough feedback that it is a feature we should pursue. We prefer
to close this issue as a clear indication that we are not going to work on
this at this time. We are always open to reconsidering this in the future
based on compelling feedback; despite this issue being closed please feel
free to leave feedback on the proposal (including +1s).
