### ISSUE TITLE
Percentiles aggregation: method parsing issues

### ISSUE THREAD

**Issue by gmarz** [elastic/elasticsearch#14691]
Currently, although tdigest is the default method, `compression` can only be set if it's wrapped in a `tdigest` object:

```
{
    "aggs" : {
        "load_time_outlier" : {
            "percentiles" : {
                "field" : "load_time",
                "tdigest": {
                    "compression": 200
                }
            }
        }
    }
}
```

Otherwise, the following exception is thrown: `Unexpected token VALUE_NUMBER in [load_time_outlier].`

The [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/search-aggregations-metrics-percentile-aggregation.html#search-aggregations-metrics-percentile-aggregation-compression) however states that it can be set at the root agg level:

```
{
    "aggs" : {
        "load_time_outlier" : {
            "percentiles" : {
                "field" : "load_time",
                "compression" : 200 
            }
        }
    }
}
```

On a similar note, the hdr histogram can only be provided as an object as well:

```
{
    "aggs" : {
        "load_time_outlier" : {
            "percentiles" : {
                "field" : "load_time",
                "hdr": {
                    "number_of_significant_value_digits" : 3
                }
            }
        }
    }
}
```

but the documentation states that it can be specified as so:

```
{
    "aggs" : {
        "load_time_outlier" : {
            "percentiles" : {
                "field" : "load_time",
                "percents" : [95, 99, 99.9],
                "method" : "hdr", 
                "number_of_significant_value_digits" : 3 
            }
        }
    }
}
```

I think the objects make sense, since there are options that only pertain to certain methods, but I think `compression` should still be allowed at the root level if a method isn't specified, since tdigest is taken by default.

**Comment by clintongormley** [comment]
@colings86 could you take a look please?

**Comment by colings86** [comment]
To me this is a documentation bug. It looks like the documentation didn't get updated form the previous incarnation of the settings (which were never released).

I think we should only allow the object definition and not allow `compression` on the root level. This makes the parsing easier in code and makes it easier to explain the syntax to users. If you are just using the defaults then you don't need to specify anything and you get tdigest with compression set to 100. If you want to change the settings then you must define the method as well as the settings so it is explicit. Otherwise we could end up with situations where a user specifies compression at the root level and hdr as the method and doesn't realise why this doesn't work.

**Comment by gmarz** [comment]
@colings86 Agreed, that makes sense.

A bit of nit pick though, but probably worth nothing: the null checks [here](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/search/aggregations/metrics/percentiles/AbstractPercentilesParser.java#L151) and [here](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/search/aggregations/metrics/percentiles/AbstractPercentilesParser.java#L160) aren't necessary as these will get caught in the parsing loop above.

**Comment by polyfractal** [comment]
@elastic/es-search-aggs

**Comment by jtibshirani** [comment]
It looks like the documentation was updated in https://github.com/elastic/elasticsearch/commit/3f344d3154f29d8c873d8002570d65b4e2bdb0ee, so closing this out.
