### ISSUE TITLE
ES 2.0.0 does not accept timestamp path and mapping. 

### ISSUE THREAD

**Issue by nithyanv** [elastic/elasticsearch#14715]
Hi,

The following template mapping 

>curl -XPUT http://localhost:9200/_template/service_01 -d '{
>"template" : "service*",
>"order":    1,
>"settings" : {
>"index.cache.field.type" : "soft",
>"index.refresh_interval" : "5s",
>"index.store.compress.stored" : true,
>"mapping.allow_type_wrapper": true
>},
>"mappings" : {
>"_default_" : {
>"_all" : {"enabled" : false},
>"_timestamp" : {"enabled" : true,"path" : "0STARTTIMESTAMP","format" : "YYYY/MM/dd HH:mm:ss"},
>"properties" : {
>"0STARTTIMESTAMP": {
>"type": "date",
>"format": "YYYY/MM/dd HH:mm:ss"
>},
>"STOPTIMESTAMP": {
>"type": "date",
>"format": "YYYY/MM/dd HH:mm:ss"
>}
>}
>}
>}
>}'

Works great in ES 1.4.4. For the below data. 
>{"index":{"_index":"service_sapstats","_type":"mytype"}}
>{"0STARTTIMESTAMP":"2015/02/13 13:00:00","*STOPTIMESTAMP":"2015/02/13 13:15:00","data":"somedata"}

But in ES 2.0.0 it throws the below exceptions. 

>{"index":{"_index":"service_sapstats","_type":"SAM","_id":null,"status":400,"error":{"type":"mapper_parsing_exception","reason":"mapping [_default_]","caused_by":{"type":"mapper_parsing_exception","reason":"Mapping definition for [_timestamp] has unsupported parameters:  [path : 0STARTTIMESTAMP]"}}

in ES 2.0.0

**Comment by rjernst** [comment]
These features were explicitly removed from 2.0. See #8143 and #6677.

**Comment by rjernst** [comment]
@nithyanv You can create your own `date` type field (which already supports timestamps).

**Comment by lam-juice** [comment]
the _timestamp field is useful for more than just ttl - for instance, if ES is used as a timeseries storage, if you want to know how long your pipeline takes to deliver the message, it can be calculated as (_timestamp - @timestamp) (provided that @timestamp is obtained from the parsed event time).

with a self-created date field, such information is lost, because if a pipeline delay happens after adding the date field, the delay will not get captured by _timestamp - @timestamp.

**Comment by l15k4** [comment]
@rjernst hey, do you know whether I have to re-index everything because of that : https://discuss.elastic.co/t/upgrade-from-1-7-x-to-2-2-0--timestamp-mapping-issue/41894

The reindexing would took 47 hours, so I'm kinda screwed...
