### ISSUE TITLE
elasticsearch init script not starting on ubuntu 11.04

### ISSUE THREAD

**Issue by titotp** [elastic/elasticsearch#14724]
When i tried to start the elastic search using init script its not working. However it works fine when i manually run from bin/elasticsearch
ES Version 1.7

**Comment by jasontedor** [comment]
Would you be able to provide any additional details about the nature of how it's not working? Are there any error or log messages that you can share?

**Comment by titotp** [comment]
unfortunately the logs are not creating. I followed the ansible playbook 
https://github.com/Traackr/ansible-elasticsearch

There is no error message when it starts. Its starts ok, But when i check the status it shows stopped

http://pastebin.com/uQh8cTTh

**Comment by nik9000** [comment]
So 11.04 isn't an officially supported version - 12.04, 14.04 are. And we test on 15.04 too because why not. Most of that testing is in 2.0 onwards and not so much 1.x. That being said I imagine it ought to work.

The first thing I do when I get into a situation like this is to run `bin/elasticsearch` as the `elasticsearch` user just to see if Java starts. If you don't get any log at all this is typically caused by something super early.

Another thing you can do is temporarily hack the init script to not run elasticsearch daemonized. If you do that it won't close stdout and you can read the logs.

It'd be nice to do this all automatically but its just hard in init.d land. In systemd its simpler _but_ we haven't done it because not everyone uses systemd.

**Comment by titotp** [comment]
yes i am using 14.04 and it works fine when i run manually
bin/elasticsearch

**Comment by nik9000** [comment]
> yes i am using 14.04 and it works fine when i run manually bin/elasticsearch

Do you mean that 14.04 works fine when you run `bin/elasticsearch` or that 11.04 works fine when you run `bin/elasticsearch`?

**Comment by titotp** [comment]
14.04 is the version i am using and it works fine with bin/elasticsearch. However it is not working with init script.

**Comment by nik9000** [comment]
Oh! In that case I imagine its some kind of invalid configuration. Can you try (temporarily) removing `-d` from the `start-stop-daemon` line? That should foreground elasticsearch and it should spit out _something_ when you run it.

**Comment by titotp** [comment]
Thanks Nick for helping out. I tried removing the -d from init script and its still same.

PID_FILE="$PID_DIR/$NAME.pid"
DAEMON=$ES_HOME/bin/elasticsearch
DAEMON_OPTS="-p $PID_FILE --default.config=$CONF_FILE --default.path.home=$ES_HOME --default.path.logs=$LOG_DIR --default.path.data=$DATA_DIR --default.path.work=$WORK_DIR --default.path.conf=$CONF_DIR"
DAEMON_OPTS="$DAEMON_OPTS -Des.max-open-files=true"

root@ip-10-1-5-141:/var/run/elasticsearch# /etc/init.d/elasticsearch status
 * elasticsearch is not running
root@ip-10-1-5-141:/var/run/elasticsearch# /etc/init.d/elasticsearch stop
 * Stopping Elasticsearch Server
   ...done.
root@ip-10-1-5-141:/var/run/elasticsearch# /etc/init.d/elasticsearch start
 * Starting Elasticsearch Server
root@ip-10-1-5-141:/var/run/elasticsearch#

**Comment by titotp** [comment]
Init script - http://pastebin.com/nVHnSiAE

**Comment by nik9000** [comment]
Can you try deleting this line from your init script:
```
DAEMON_OPTS="$DAEMON_OPTS -Des.max-open-files=true"
```

That is the only difference I can see between it and the one that comes with 1.7.3. The trouble with lines like the one above is that they break anything with a space in it.

Its very strange that you don't get output from elasticsearch without the `-d`. Its been a while since I tried it. Maybe `start-stop-daemon` is eating it.  Can you try echoing the command that Elasticsearch would run from `bin/elasticsearch` and running it yourself as the right user?

I hate these sorts of issues and I'm really sorry about them.

**Comment by titotp** [comment]
start-stop-daemon --start -b --user elasticsearch -c elasticsearch --pidfile /var/run/elasticsearch.pid --exec /usr/share/elasticsearch/bin/elasticsearch -- -d -p /var/run/elasticsearch.pid -Des.default.config=/etc/elasticsearch/elasticsearch.yml -Des.default.path.home=/usr/share/elasticsearch -Des.default.path.logs=/var/log/elasticsearch -Des.default.path.data=/var/lib/elasticsearch -Des.default.path.work=/tmp/elasticsearch -Des.default.path.conf=/etc/elasticsearch

This works fine when i run it from cli. Not from init script

**Comment by titotp** [comment]
@nik9000 figured out the issue. It was some stupid mistake on my side. I have set the elasticsearch_heap_size: 2g on a t2.micro instance that has only 1GB. I reduced that to 1GB  and its working fine.
Thanks for all the help.
