### ISSUE TITLE
LinkedHashMap order is not preserved by StreamOutput.java

### ISSUE THREAD

**Issue by bczifra** [elastic/elasticsearch#14743]
LinkedHashMap order is not preserved by org.elasticsearch.common.io.stream.StreamOutput.java.  This is because the LinkedHashMap is cast to a Map, and then it's entry set is iterated on, rather than iterating on the LinkedHashMap itself.  

The relevant code fragment from StreamOutput.java:379-92:
        } else if (value instanceof Map) {
            if (value instanceof LinkedHashMap) {
                writeByte((byte) 9);
            } else {
                writeByte((byte) 10);
            }
            @SuppressWarnings("unchecked")
            Map<String, Object> map = (Map<String, Object>) value;
            writeVInt(map.size());
            for (Map.Entry<String, Object> entry : map.entrySet()) {
                writeString(entry.getKey());
                writeGenericValue(entry.getValue());
            }
        }

I discovered this in the course of writing a plugin and trying to return a LinkedHashMap from the run() method of AbstractExecutableScript.

**Comment by jasontedor** [comment]
> This is because the LinkedHashMap is cast to a Map, and then it's entry set is iterated on, rather than iterating on the LinkedHashMap itself.

The `Map#entrySet` method is abstract and is [implemented on `LinkedHashMap`](https://docs.oracle.com/javase/8/docs/api/java/util/LinkedHashMap.html#entrySet--). Because of virtual method dispatch, the cast doesn't matter and the implementation of `entrySet` on `LinkedHashMap` will be the one that is invoked at runtime. It is this method that gives the iteration order while iterating, and that is the order that the entries will be written to the stream. I wrote a test in #14743 that shows that this order is preserved by the serialization, and it is preserved whether or not the iteration order is insertion order or access order.

Can you explain what led to you thinking that the iteration order is not preserved by serialization. Do you have a reproducible test case that you can share?
