### ISSUE TITLE
Potential issue when testing plugins using ElasticsearchIntegrationTest?

### ISSUE THREAD

**Issue by jaranflaath** [elastic/elasticsearch#14824]
Hi,

I've come across a potential issue when writing an integration test for one of our plugins using the ElasticsearchIntegrationTest class. This is in version 1.7.3.

When a plugin tries to make a request to Elasticsearch, it will receive an error due to the assert in org.elasticsearch.transport.Transports which is checking if the current thread is a transport thread.

I have created a github repo which demonstrates the issue: https://github.com/jaranflaath/es-plugin-integrationtest

Running the PluginTest will reproduce the situation.

I am not certain if this is an issue in Elasticsearch, or an issue with the way we try to test our plugin, so any input is welcome.

Thanks!

**Comment by jaranflaath** [comment]
After some more digging and discussions on Freenode, I have now found a solution and provided an example in the "solution" branch in the example repository: https://github.com/jaranflaath/es-plugin-integrationtest/tree/solution

However, I would love some feedback on what is the proper way to do this.

**Comment by jasontedor** [comment]
> it will receive an error due to the assert in org.elasticsearch.transport.Transports which is checking if the current thread is a transport thread

This is by design. In your [code](https://github.com/jaranflaath/es-plugin-integrationtest/commit/89b755fcff38b4756dfba0b4d439e9ab8d5bce3c#diff-f70cd741ee6d7246193213cc8db54748R31), you're sending a request on the thread that is handling your client request on the endpoint `/cluster_status`. The handling of that request happens on a network thread, and by sending another request on that thread you'd be blocking a network thread until a response comes back. Blocking network threads is bad and we go to great lengths to prevent it.

Your solution "works" because you got the [request off of the network thread](https://github.com/jaranflaath/es-plugin-integrationtest/blob/b85452b121b1e0086abcf26071e3c904a374e8b4/src/main/java/ske/skatt/elasticsearch/PluginRestEndpoint.java#L34), but it still has the problem that it is surreptitiously [blocking](https://github.com/jaranflaath/es-plugin-integrationtest/blob/b85452b121b1e0086abcf26071e3c904a374e8b4/src/main/java/ske/skatt/elasticsearch/PluginRestEndpoint.java#L46) the network thread.

The preferred way to handle situations like this is to attach a listener to the request. You'll want to do something like this:

```java
@Override
    public void handleRequest(final RestRequest request, final RestChannel channel, Client client) {
        client.admin().cluster().prepareHealth().execute(new RestBuilderListener<ClusterHealthResponse>(channel) {
            @Override
            public RestResponse buildResponse(ClusterHealthResponse clusterIndexHealths, XContentBuilder xContentBuilder) throws Exception {
                return new BytesRestResponse(OK, clusterIndexHealths.getStatus().name());
            }
        });
    }
```

This gets your request off of the network thread and does not block the network thread waiting for a response to that request.

**Comment by jaranflaath** [comment]
Thanks a lot for your feedback and suggested solution. Will give it a try :)
