### ISSUE TITLE
ES 2.0 update caused problems with date properties by adding epoch_millis

### ISSUE THREAD

**Issue by zdeseb** [elastic/elasticsearch#14878]
ES 2.0 upgrade added to all date type property mappings format epoch_millis. Unfortunately this was added at the beginning of the format parameter so it is used for conversion to string.

**For example when I have had following index:**
```javascript
PUT test
{
  "mappings": {
    "item":
    {
      "properties": {
        "Value":
        {
          "type": "date",
          "format": "dateOptionalTime"
        }
      }
    }
  }
}
```
and the aggregations returns
```javascript
{
   "Value": {
    "value": 1447993360390,
    "value_as_string": "2015-11-20T04:22:40.390Z"
  }
}
```

**After upgrade I have following:**
```javascript
PUT test
{
  "mappings": {
    "item":
    {
      "properties": {
        "Value":
        {
          "type": "date",
          "format": "epoch_millis||dateOptionalTime"
        }
      }
    }
  }
}
```

and the aggregations returns
```javascript
{
   "Value": {
    "value": 1447993360390,
    "value_as_string": "1447993360390"
  }
}
```

**I think epoch_millis should be added (if it is necessary - why?) at the end of format value, not at the beginning or this info should be in breaking changes for ES 2.0 version !!!**

**Comment by clintongormley** [comment]
Ah, this is an unfortunate side effect of making `epoch_millis` explicit.  For upgraded indices, it was added as the first format because that reflects how values were parsed in 1.x.  For new indices, it is added as the second format (and so will do what you expect).

If you reindex your data, things will work as before.  Alternatively, specify the `format` parameter in your aggregation as a workaround.
