### ISSUE TITLE
Why data nodes disk usage goes up, even if no additional data is added

### ISSUE THREAD

**Issue by satapsa** [elastic/elasticsearch#14891]
I have a 4 node cluster.
PN1   - 59% disk usage    -- Master and data
SN1   - 61% disk usage    - data
DN1  -  95% disk usage    -- data
DN2  -  49%                      -- data

I noted one of the node - DN1 had 87% disk usage and hitting the low disk watermark  and I was not able recovere shard. I deleted some old indices and restarted the Elastic search.

Now disk usage is 90% and high watermark is 90%.

Why the disk usage goes up in Elastic search even if no extra data is added ?

Why disk usage are different on different nodes ?

**Comment by nik9000** [comment]
These are better questions for the forums because its not clear at all that you have a bug in a released version of elasticsearch. If I had to guess its because Elasticsearch is moving files around to balance the cluster. Depending on your version it could be doing some silly things like moving files to a machine that doesn't have enough disk space for them. You can check (cat recovery)[https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-recovery.html] to see what is moving around right now.


> Why disk usage are different on different nodes ?

Elasticsearch balances the total number of shards and doesn't balance the total disk usage across nodes. It uses hard limits on disk usage to push shards off of nodes that go over the limits but that is all it does with shard size.

**Comment by gorefbitim** [comment]
I know it's a while, but had the same problem - disk space went down with almost no new data. Finally I used the following command:
$ curl -XGET 'localhost:9200/_cat/indices?v'

To find the about 180mb is chewed up by X-Pack monitoring service per day, but it's only for the last 7 days. 

Have you find other related interesting stuff ?
