### ISSUE TITLE
Use a java agent to disable ObjectInputStream for the entire JVM

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#14939]
We've banned `ObjectInputStream` and friends but they might still be used by libraries. Maybe we can plug that hole with [NotSoSerial](https://github.com/kantega/notsoserial)?

**Comment by rmuir** [comment]
I don't think we should do this, I think its by far too risky. Changing bootclasspath to modify the behavior of the jvm (either directly or with agent)? no thanks. Looking at their code, I don't think its gonna work under java 9/jigsaw, I think the licensing situation here is still ambiguous, etc.

I also think this agent is an incomplete, risky, knee-jerk reaction to a specific vulnerability. Instead, I think we should just continue to tighten things up in general. For the specific concerns of third party code, e.g. we can start auditing third party libraries that we bring in with forbidden apis (https://github.com/policeman-tools/forbidden-apis/issues/38) to treat them more like our own code. Yes, we can in fact "know what that code is doing" :)

Overall, we can continue to lock things down to bring more reliability and security: e.g. do some real code cleanups to address some of the TODOs and exceptions we have in the security policy. This helps both our own code and third party code.

As far as JDK code, yes its kind of a special case, but I think addressing it by replacing classes in the JDK is the wrong technique. If we distrust the JVM, then we should sandbox it better, and the right guy to do that is the operating system. Today this is minimal (only dropping ability to execute), because its a black and white thing. This is a tradeoff to keep in mind. So if we want to expand e.g. system call filtering to do more, or if we want OS packaging to bring in its own JDK that we apparmor or whatever, we have to think about the implications: we can't have plugins declaring exceptions and stuff like we can at the java level.

**Comment by rmuir** [comment]
Also, forgot to mention, containing the JVM at the OS level doesn't have to be complex. Even stuff like tidying up filesystem permissions in our packaging can be a great improvement there.
