### ISSUE TITLE
Would you append "preference" that is like search request option on ForceMergeRequest?

### ISSUE THREAD

**Issue by HowookJeong** [elastic/elasticsearch#14958]
I think, ForceMergeRequest can be performed into each shards.
If this idea is right, I hope that you implement this option on ForceMergeRequest.

This is just my opinion, you don't need to think seriously.

Thanks.

**Comment by clintongormley** [comment]
What is the use case?

**Comment by HowookJeong** [comment]
I usually use a force merge or _optimize because I have many kind of heavy requests which are index, delete and update by using bulk.
These operation create many segment files and deleted docs.
It is inefficient to storage and getting slower.
Also, This operation use a lot of system resources.
If the operation can request to shard level, I could save system resources and our cluster will be stable.

I think, the idea is very useful.
So, I hope you'll consider try again.

Thanks.

**Comment by clintongormley** [comment]
Force merge is a heavy operation any way you look at it.  You should not run it on an index that is still being modified. Instead, you should leave segment maintenance up to the background merge process, which (in recent versions) will throttle indexing if merges are not keeping up. 

Also, it should be run on your "cold storage" nodes, not your hot nodes, so that it doesn't interfere with other processes.

i don't think that preference will help your situation.
