### ISSUE TITLE
Support for number fields in more_like_this queries

### ISSUE THREAD

**Issue by johnament** [elastic/elasticsearch#14965]
more_like_this only supports string field types.  Lets suppose that I have a field "creator", which is the numerical ID of whoever created some document.  I should be able to run a more_like_this on the creator field to find other records this person has created.

**Comment by davidklebanoff** [comment]
I believe this may be possible if creator has a field type of "keyword" and then form your query like:

```json
{
    "query": {
        "more_like_this" : {
            "fields" : ["creator"],
            "like": [
              {
                  "_index": "foo",
                  "_type": "bar",
                  "_id": "123"
              }
          ],
            "min_term_freq" : 1,
            "max_doc_feq" : 1,
            "minimum_should_match" : 1
        }
    }
}
```

**Comment by cbuescher** [comment]
cc @elastic/es-search-aggs

**Comment by jimczi** [comment]
We discussed this internally and we think that there is simple workaround which is to use a `keyword` field instead of a numeric field. Technically it would be equivalent in terms of matching and this field would be compatible with the `more_like_this` query. It is also possible to use the `term_vectors` API to build a custom boolean query using the same logic than the `mlt` query. `keyword` fields should be used for exact matching,  for this reason we are going to close this issue.
