### ISSUE TITLE
Unallocated shards because of "index.auto_expand_replicas":"0-all" and "cluster.routing.allocation.same_shard.host": true

### ISSUE THREAD

**Issue by slovit** [elastic/elasticsearch#14979]
Setting both options `"index.auto_expand_replicas":"0-all"` and `"cluster.routing.allocation.same_shard.host": true` causes unallocated shards in a cluster. 

E.g. in a cluster with 5 physical hosts and 10 Elasticsearch instances (2 instances/host) the settings cause 5 unallocated shards per an index.

Is this the correct behavior?
Thanks!

P.S. Tested on Elasticsearch-1.4.4

**Comment by ywelsch** [comment]
This is the expected behavior. `auto_expand_replicas` expands the number of replicas based on the number of available **nodes** (which are Elasticsearch instances, not physical hosts). It does not take any other allocation constraints into account. Please use https://discuss.elastic.co for future questions of this kind.

**Comment by clintongormley** [comment]
Duplicate of https://github.com/elastic/elasticsearch/issues/2869
