### ISSUE TITLE
Bulk update with doc reindexes document

### ISSUE THREAD

**Issue by yoitsro** [elastic/elasticsearch#15053]
When running a bulk request with update actions, even if `doc` is sent in the source, the document is replaced with the update source, instead of being merged. Tested on ES 2.0.0.

Create the document
```
POST my_index/my_type/1
{
  "field1": "value1"
}
```

Update the document without bulk
```
POST my_index/my_type/1/_update
{
  "doc": {
    "field2": "value2"
  }
}
```

Document is now:
```
{
  "field1": "value1",
  "field2": "value2"
}
```

Bulk update the document
```
$ cat requests
{ "update" : { "_index" : "my_index", "_type" : "my_type", "_id" : "1" } }
{ "doc": { "field1" : "aNewValue" } }
$ curl -s -XPOST localhost:9200/_bulk --data-binary "@requests"; echo
{"took":7,"errors":false,"items":[{"create":{"_index":"my_index","_type":"my_type","_id":"1","_version":3, "status":200}}]}
```

Fetch the document
```
GET my_index/my_type/1
```

Output
```
{
  "field1": "aNewValue"
}
```

**Comment by clintongormley** [comment]
@yoitsro this is a known issue when running with Shield enabled, because of field level security.  2.0.1 and 2.1.0 have been released with field level security disabled by default (making the bulk updates work correctly) and disabling bulk updates if FLS is enabled.  You should upgrade your cluster.

We're working on a fix that will allow FLS to work with bulk updates in the future.

**Comment by yoitsro** [comment]
@clintongormley Our cluster is running 2.1.0 on Found, and this is where I initially noticed the problem. Is there anything else I might be missing and why this doesn't work on Found?
