### ISSUE TITLE
default gradle build to --debug --stacktrace

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#15091]
The gradle build in master "hides" too much, yet it is not stabilized (e.g. integ tests dont work on windows).

We should default to full output (verbose as possible) until everything is working. This idea of super-succinct output is not good until everything is stabilized: it just discourages anyone from fixing problems because they cannot see what is wrong.

**Comment by clintongormley** [comment]
@rjernst can this be closed yet?

**Comment by rjernst** [comment]
In CI, we run gradle clean --stacktrace as a first step to the build, so that we catch any configuration errors with the stacktrace. Execution is different, since gradle uses exceptions to signal build failure, but does not distinguish unknown exceptions from a normal build failure. If there was a way to default both stacktrace and debug, it would be extremely noisy, so from that alone I dont think we would want this, but there is also the fact there is simply no way to enable these by default.
