### ISSUE TITLE
[Ingest] Add the ability to create multiple documents from one ingest document.

### ISSUE THREAD

**Issue by jimferenczi** [elastic/elasticsearch#15112]
Could be useful to add the ability to create multiple documents from a single ingest document. Denormalization for instance would be a good candidate though we would need something to create unique ids for the extra documents.
Example:
```
 public Cursor<IngestDocument> execute(IngestDocument ingestDocument) throws Exception;
```

**Comment by martijnvg** [comment]
Based on what rules should a document be split? Also this is going to be tricky when it comes to represent these additional documents back in the response, because ingest intercepts requests. Index response can only hold the response of one document and with bulk if the order of the responses don't match with the order of the request items that the bulk response becomes useless.

**Comment by clintongormley** [comment]
Given the reasons pointed out by @martijnvg, this sounds like something better handled client side.  Closing
