### ISSUE TITLE
`indices.recovery.file_chunk_size` got lost in #13840

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#15161]
The setting `indices.recovery.file_chunk_size` got lost in  https://github.com/elastic/elasticsearch/pull/13840 - I found out while reviewing some settings and their defaults. the `512kb` default for this one caught my attention and I was surprised we are using such a rather big buffer to send across the network. From my perspective we should use an 8kb for writing most of the time which we now do by accident (we use `Streams#copy(InputStream in, OutputStream out)` which uses a 8k buffer. I wonder why we have these low level settings and if we:

 1. bring it back / make it adjustable at all
 2. drop more super low level settings in `RecoverySettings`

there are a couple of settings that are questinable:
 * `indices.recovery.compress` - lets either compress or not but why make this adjustable?
 * `indices.recovery.concurrent_streams` / `indices.recovery.concurrent_small_file_streams` why do we have this and why can't this come from some ThreadPool instead. I also wonder if the small / large differentiation is worth the trouble?
 * `index.shard.recovery.translog_size` / `index.shard.recovery.translog_ops` I think we can drop both and just hide sending behind a stream and just keep on writing to the stream and flush when necessary (8kb) or just use 8kb as a fixed size?
 

I might be wrong with the 8kb since this is really an RPC rather than a stream but I wonder if we can find a good default we can just go with instead of having these expert settings. I would be ok with moving some of these settings to system properties to signal how expert they are but the amount of timeouts and things here is really not maintainable.

**Comment by dakrone** [comment]
> `indices.recovery.concurrent_streams` / `indices.recovery.concurrent_small_file_streams` why do we have this and why can't this come from some ThreadPool instead. I also wonder if the small / large differentiation is worth the trouble?

It was [originally added](https://github.com/elastic/elasticsearch/pull/3584) because large relocations can block things like the recovery of newly created indices, so you end up waiting a long time before the newly created index is available.

**Comment by s1monw** [comment]
> It was originally added because large relocations can block things like the recovery of newly created indices, so you end up waiting a long time before the newly created index is available.

for stuff like this I think we should just use the coordinating thread and do it sequentially instead of in-parallel. But thanks for the pointer @dakrone !!

**Comment by jpountz** [comment]
I'm not familiar enough with the recovery process to comment but I'm all for having fewer low-level settings. If we don't fully trust some components, we can have an escape hatch using system properties like you suggested.

**Comment by bleskes** [comment]
> indices.recovery.compress 

+1 on removing ^^ never heard about a case where it was used.

> indices.recovery.concurrent_streams / indices.recovery.concurrent_small_file_streams

What Lee said re that we need a solution to let new indices get to green quickly, even if a big file is being copied. Doesn't have to this solution as Simon said.

Also, these setting protect a node holding many primaries from being overloaded by outbound recoveries. I think this is simpler to implement on the master with a decision allocator (like we do for target relocation). The was an e-mail thread about this where @kimchy thought at the time that this will be complicated (the thread at the time was about the tension between max_bytes_per_sec and these settings).

> index.shard.recovery.translog_size / index.shard.recovery.translog_ops I think we can drop both and just hide sending behind a stream and just keep on writing to the stream and flush when necessary (8kb) or just use 8kb as a fixed size?

We already read ops from the translog one by one, so writing to a blocking output stream will easy to implement here.

> I would be ok with moving some of these settings to system properties to signal how expert they are

+1 to simplify and remove escape hatches which we haven't used for a while. Even better if we can simplify the mechanics to have one setting do more (like the 8k buffer which holds for many transmissions). One note about system properties - our current settings are dynamically updatable so in case of trouble you can tweak them without going down. system properties aren't. As these settings are relevant for all nodes of the cluster, having them updatable from code means they can be changed in one command rather than a full cluster restart.  To me this is a case by case basis judgment call. 

If we move to system properties, we need some kind of mechanism to report they were used and changed. Right now asking for the elasticsearch.yml file + cluster settings gives you a complete picture. In general we are moving towards using more and more cluster settings and less the yml file. I'm worried moving to system properties will go agains this.

**Comment by s1monw** [comment]
@kimchy can you tell us where the `512kb` came from vs. `8k` buffer.

**Comment by kimchy** [comment]
- compress: I agree that we can remove this setting, I don't think someone really sets it. My suggestion is actually not to have it on when transferring segments (they are already compressed), but still do compression on translog entries as those tend to be highly compressed json documents.

- Regarding concurrent streams, I agree that if we can make better decision when allocating a shard, for example, prefer new indices to allocate almost ignoring deciders that throttle, will help. We will still need to somehow prioritize "the streams" of segments, though in that case, a single recovery thread would be enough. I do think that it is still good to have concurrent streams for beefy shard recovery as it will speed it up compared to single thread streaming data.

- To do blocking streaming, we would simulate it over evented networking, deciding when to "flush". We should have higher than 8k buffer to flush, as network buffers can transfer in one go much more, and the 8k one we do in Lucene for files doesn't apply in this case (copy to native direct buffer). I am +1 on removing the setting, since 512k is a good default and I doubt someone would want to change it. Note that higher flush buffer starts to hurt you when doing evented networking.

- Regarding translog size, I agree that we can remove this setting as well, and just flush based on bytw size, and use the same flush size we decide to use for segments here as well (512k).

**Comment by s1monw** [comment]
> Regarding concurrent streams, I agree that if we can make better decision when allocating a shard, for example, prefer new indices to allocate almost ignoring deciders that throttle, will help. We will still need to somehow prioritize "the streams" of segments, though in that case, a single recovery thread would be enough. I do think that it is still good to have concurrent streams for beefy shard recovery as it will speed it up compared to single thread streaming data.

@kimchy I think we should just use the recovery thread itself to send such small files. That way it's simplified and we can rely on throttling to not overload the node. The recovery thread is blocking anyway and sending small files should be very very quick anyhow.

**Comment by kimchy** [comment]
@s1monw right, we might still want to then not throttle recoveries for freshly created indices? otherwise they might backlog?

**Comment by s1monw** [comment]
> @s1monw right, we might still want to then not throttle recoveries for freshly created indices? otherwise they might backlog?

I don't see that really but that has to be a sep change since all our tests will fail on that one I tried it

**Comment by clintongormley** [comment]
@s1monw is this issue closed by https://github.com/elastic/elasticsearch/pull/15235 or is there more to do?

**Comment by s1monw** [comment]
@clintongormley you are right I missed that... closing
