### ISSUE TITLE
[Feature Request] "_highlight" API for indices

### ISSUE THREAD

**Issue by aeryaguzov** [elastic/elasticsearch#15367]
Indices already have an *_analyze* API from which we can see how analyzers work.  

We need the "same" API to highlight sample text with a query according to index settings (same thing is already implemented in [sphinx] (http://sphinxsearch.com/docs/current.html#sphinxql-call-snippets) ).

This can be useful when we do not need to store text in document, but need to highlight some text.   

For now, if we want to highlight sample text, we have to index "tmp" text, highlight it, and then delete it.

**Comment by aeryaguzov** [comment]
As I understand there is no way to highlight childs in parent/child query (https://github.com/elastic/elasticsearch/issues/1764), so this API can be a workaround to highlight childs after search

**Comment by clintongormley** [comment]
Hi @aeryaguzov 

The analyze API works because it is a process which happens before data is indexed.  Highlighters require indexed terms for query matching and for term statistics.  So in the end, you have to index the text.

For parent/child, you can now highlight the child documents using inner_hits:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-inner-hits.html#parent-child-inner-hits

**Comment by nik9000** [comment]
> So in the end, you have to index the text.

Its a bit more complex than that. 2/3 of the highlighters require indexed text. The plain highlighter always reanalyzes on the fly, last I checked. It'd _technically_ be possible to implement "here is some text and a query please highlight it" for all highlighters using a MemoryIndex. Its probably overkill though.
