### ISSUE TITLE
Deleting a document from a non-existing index creates the index

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#15425]
Using the default settings, if a delete request is issued for a single document against a non-existing index, Elasticsearch will create the index. Steps to reproduce:

```
DELETE /foo
```

```
DELETE /foo/bar/1
```

Then:

```
GET /foo
```

responds with HTTP 200 OK and response body

```
{
  "foo" : {
    "aliases" : { },
    "mappings" : { },
    "settings" : {
      "index" : {
        "creation_date" : "1450124918393",
        "number_of_shards" : "5",
        "number_of_replicas" : "1",
        "uuid" : "Ny3PruSCTIG5TlYecU0_XA",
        "version" : {
          "created" : "3000099"
        }
      }
    },
    "warmers" : { }
  }
}
```

showing that it created the index.

**Comment by niemyjski** [comment]
+1 this just cost me a day of work.

**Comment by bleskes** [comment]
Carrying the discussion over from #21926 

> I think we should have a dedicated setting for this which defaults to false.

I would prefer to make deletes with an external version auto create indices rather than have a settings that controls a deletes in general. It seems that's the only use case that needs it so we can have it contained.

**Comment by s1monw** [comment]
++ @bleskes

**Comment by nikkelj** [comment]
+1, I was using an index management scheme that was open loop deleting potentially existent indices based on time range.  This then creates thousands of ghost indices that cannot be deleted, and completely kills the cluster performance.  Poor behaviour.

**Comment by olcbean** [comment]
Hey guys, as this appears to be still an issue in master, I would like to give it a try iff nobody else is working on it.

As the discussion was held over time in multiple threads, let me sum up what the expected behavior should be : 
* if an external version is used : create the index ( the same behavior as of now )
* otherwise : throw an `index_not_found`
(the change should not introduce an additional `IndexOption`)
