### ISSUE TITLE
Keyed response: document explicitly for all aggs that support it

### ISSUE THREAD

**Issue by nellicus** [elastic/elasticsearch#15484]
In docs the possibility of using keyed responses is mentioned here and there

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-range-aggregation.html#_keyed_response
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-histogram-aggregation.html#_response_format

by running a quick test on percentile aggs

```
GET my-index/_search
{
  "size": 0,
  "aggs": {

    "percentiles": {
      "percentiles": {
        "keyed":false,
        "field": "a_numeric_field",
        "percents": [
          1,
          5,
          25,
          50,
          75,
          95,
          99
        ]
      }
    }
  }
}
```

it is observable that `keyed` is also enforced in there 

```
{
  "took": 47,
  "timed_out": false,
  "_shards": {
    "total": 15,
    "successful": 15,
    "failed": 0
  },
  "hits": {
    "total": 133952,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "percentiles": {
      "values": [
        {
          "key": 1,
          "value": -122.41699999999999
        },
        {
          "key": 5,
          "value": -122.05740000000003
        },
        {
          "key": 25,
          "value": -122.0574
        },
        {
          "key": 50,
          "value": -122.0574
        },
        {
          "key": 75,
          "value": -78.34338576181548
        },
        {
          "key": 95,
          "value": 2.17410000000001
        },
        {
          "key": 99,
          "value": 12.649400000000016
        }
      ]
    }
  }
}
```

however no mention of keyed is made in https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-percentile-aggregation.html?q=percentiles#search-aggregations-metrics-percentile-aggregation

unless I'm missing something, is there an opportunity to have this documented clearly, perhaps just mentioning for each bucket agg if this is supported or not, not to make this a massive task?

CC @clintongormley @colings86 @markharwood @martijnvg @debadair @palecur

**Comment by colings86** [comment]
It is a bug that we don't have this documented for Percentiles but I am not keen in having a section for keyed response in the documentation listed which aggregation support it and which don't since a vast majority of them don't support it. 

I also am inclined to think its a bit of a useless feature anyway. In range and percentile aggregations you know ask for specific buckets and so I would think you would always want to get the buckets by key (implying `keyed: true`) rather than iterating through them. For the few cases where you would want to iterate through them, most (probably all) languages allow you to iterate through maps anyway. In the histogram aggregation you actually don't know what buckets are going to be returned so getting a bucket by key doesn't make too much sense to me (if you wanted a specific bucket surely you would have used the range aggregation?) so I would say that `keyed: false` is probably the only viable option here too.

This is just my opinion though.

**Comment by uboness** [comment]
@colings86 I don't share your opinion here. I think there are two things to take into account here:

- There should be a consistent response structure across all aggs. This enables more generic tools to build UIs on top of the aggs and treat all the aggs the same when parsing the response. IMO, Having an array of buckets as a default structure is a good choice for that.

- sometimes you do know what you're looking for and you use the aggs to get a few specific aggs. In those cases you want to have random access to them instead of writing boilerplate code that iterates over an array to find those aggs.

This is where the current support comes from - default to arrays, but you can customize the response to be keyed instead (and along with that, customize the keys for every bucket).

**Comment by clintongormley** [comment]
I'm of the opinion that we should remove the keyed response for three reasons:

* you lose order
* you produce key names that potentially look like paths eg `99.9` and can't be indexed into elasticsearch and won't work with path syntax
* converting an array into a map is a one liner on the application side

@rashidkpc does kibana use keyed responses?

**Comment by rashidkpc** [comment]
@clintongormley yes it does. If you choose to remove them please file a ticket on the kibana repo.

**Comment by clintongormley** [comment]
@rashidkpc may I ask what for? ie would it be annoying to kibana to have keyed responses removed, or are you on board with this?

**Comment by rashidkpc** [comment]
I'm fine with it, we can change how we handle the agg. I'd much rather have things be consistent.

**Comment by uboness** [comment]
if everyone is onboard for removing keyed responses, I'm +1 as well. will certainly clean up some code. Hopefully not many will complain about it... lets see how it goes.

**Comment by javanna** [comment]
I wasn't aware that we planned on removing keyed responses, and I recently got in #23758 that documented it where it was undocumented.

@clintongormley if we still plan on removing keyed responses do we want to create a new issue or relabel this one?

**Comment by clintongormley** [comment]
@colings86 what do you think?

**Comment by colings86** [comment]
The documentation for this is fixed in https://github.com/elastic/elasticsearch/pull/23758. There is stil;l a discussion to be had about whether we should have the `keyed` option but I have created a new issue to discuss this: https://github.com/elastic/elasticsearch/issues/24611
