### ISSUE TITLE
CentOS 6.5 can't start elasticsearch 2.1 with root. And no permission run as non-root. Why?   

### ISSUE THREAD

**Issue by rentianhua** [elastic/elasticsearch#15497]
bin/elasticsearch
Exception in thread "main" java.lang.RuntimeException: don't run elasticsearch as root.
    at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:93)
    at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:144)
    at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.

**Comment by jpountz** [comment]
elasticsearch doesn't allow to be run as root so that if your elasticsearch instance ever gets compromised, an attacker would have limited permissions.

**Comment by spinscale** [comment]
in case you installed the RPM: If you run as non-root, make sure you run as the elasticsearch user, otherwise you will have permission problems when starting up - the easiest way is to use the service/systemctl tools to start/stop elasticsearch, as those use all the things configured in the package.

If you want to run as your own user, make sure you configure the data/log directories to directories you can write into.

If you cannot run elasticsearch as a package with the default user, please reopen this issue and provide more details, so we can reproduce the issue. Thanks!

**Comment by rentianhua** [comment]
thanks all of your comments :+1:

**Comment by bobbyc8** [comment]
sudo systemctl start elasticsearch.service
