### ISSUE TITLE
Recovery loop never ends or comes back shortly 

### ISSUE THREAD

**Issue by konste** [elastic/elasticsearch#15499]
I have a small two machines cluster and starting with ES 2.1 it got barely usable. One of the two machines (random) falls out of the cluster, then rejoins, runs many hours of recovery, then goes green for just a little and then scenario repeats with one machine or another. I suspected overload and gradually reduced the load, but it does not seem relevant. It pretty much feels like 2.1 issue. 

A few symptoms, which may be relevant or may be not:
1.	A lot of these: failed to create shard, failure ElasticsearchException[failed to create shard]; nested: LockObtainFailedException[Can't lock shard […][4], timed out after 5000ms]; I was looking for a way to increase this 5000ms timeout, but for the life of me could not find how;
2.	Lots of these: BroadcastShardOperationFailedException[operation indices:monitor/stats failed]; nested: IllegalIndexShardStateException[CurrentState[RECOVERING] operations only allowed when shard state is one of [POST_RECOVERY, STARTED, RELOCATED]];
3.	 It is not Out of Memory – I had it in the past and now pretty sure it is not the case;
4.	Some of these: RemoteTransportException[[Acorn6][10.150.0.111:9300][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [25] files with total size of [45gb]]; nested: ReceiveTimeoutTransportException[[Acorn5][10.150.0.110:9300][internal:index/shard/recovery/prepare_translog] request_id [32655383] timed out after [900386ms]];

Any troubleshooting tips? 
Thank you!
Konstantin

**Comment by bleskes** [comment]
The trick is indeed finding out why the nodes are falling of the cluster. Here is a bit of help answering your questions (I'm going to close this for now - feel free to reopen or continue discussing on discuss.elastic.co ).

1) When we create a shard on a folder we acquire a lock to make sure the folder is not used by a background process (like a recovery). This is to protect against overriding folders in the case of quick index deletion and creation (among others). We give this a best effort of 5s which is more then enough for things to unravel things. The assumption is that if this fails we better try another node (and if that fails come back to this node). This is indeed not configurable. 
2) The BroadcastShardOperation is too verbose. These errors are correct and expected. This was fixed with #14950 . You can ignore those.
3) OK :)
4) This indicate that a recovery doesn't have any activity for more then 15 minutes and therefore the recovery is cancelled. This is probably the source of your problems. The question is why does it time out. I would check the logs for network issues or engine related things.
