### ISSUE TITLE
BulkRequest estimated size in bytes does not include script param size

### ISSUE THREAD

**Issue by rrphotosoft** [elastic/elasticsearch#15589]
HI,
When executing an update as follows:

```
            final ArrayList<Integer> test_list = new ArrayList<Integer>();
    Random r = new Random();
    for(int i=0; i < 50000; i++){
        test_list.add(r.nextInt(3000));
    }
    Collections.sort(test_list);
            //ElasticClientHolder is a singleton that holds the transport client.
    BulkRequestBuilder brb = new BulkRequestBuilder(ElaticClientHolder.getInstance());

    UpdateRequest ureq = new UpdateRequest("test_index", "test_type", "test");
    ureq.script("update_test_script", ScriptType.FILE,new HashMap<String,Object>(){{
        put("test_list",test_list);
    }});
    ureq.scriptedUpsert(true);
            ureq.upsert(new HashMap<String,Object>());

    brb.add(ureq);

           System.out.println(brb.request().estimatedSizeInBytes());
```

=> this returns 34

If instead we simply add the  following:

```
          ureq.upsert(new HashMap<String,Object>(){{
            put("test_list",test_list);
         }});

        System.out.println(brb.request().estimatedSizeInBytes());
```

=> this returns something like 231511

The script params aren't being included in the size calculation, Is this intentional and if yes, how do we determine the size of the bulk request while using script_params.

Thanks, 
Bux

**Comment by clintongormley** [comment]
@danielmitterdorfer any ideas?

**Comment by danielmitterdorfer** [comment]
The reason is straightforward: The [size calculation for scripts](https://github.com/elastic/elasticsearch/blob/ace1b33c3c5ddcd933045cb88c04475799fa96ea/core/src/main/java/org/elasticsearch/action/bulk/BulkRequest.java#L163) in `BulkRequest` does only take into account the script size (i.e. the actual source code of the script) but not its parameters. That's why in the first case, only 34 is returned.

The second case does something different: Internally, we create a new update request and treat the provided `Map` as its source. The source of a request is always considered in total in the size calculation. That's why we get a size of 231511 in this case.

We *could* do something similar in the script case but this will add some overhead as we'd have to prematurely have to serialize it, just to determine the size.

**Comment by martijnvg** [comment]
Closing... determining the size in bytes for script params requires extra overhead that determining the size of a normal index request has not.
