### ISSUE TITLE
Add GitHub.CHEATSHEET to the project

### ISSUE THREAD

**Issue by martinstuga** [elastic/elasticsearch#15662]
Many people have some challenges when using Git/GitHub to contribute to the project.

It would be nice to have a GitHub.CHEATSHEET similar to GRADLE.CHEATSHEET.

**Comment by nik9000** [comment]
If you make one I'll review it. It might make more sense to put it CONTRIBUTING.md because folks having github problems may have not yet forked the code.

When I started contributing a few years ago I followed whatever tutorial I could find online about making PRs and it seemed to work fine. No none of the project owners said I was doing it wrong. So maybe something like this isn't needed? The advantage of the gradle cheetsheet is that maven is **so** common you can talk about the gradle commands using the shared language of maven so its terse.

**Comment by martinstuga** [comment]
@nik9000 Unfortunately I'm not the right person to do that because I'm still having some difficulties using GitHub with a forked project.

Yeah, I completely agree with you about put it in CONTRIBUTING.md (at least the basic commands).

**Comment by clintongormley** [comment]
Hmmm github has extensive good documentation https://help.github.com/

Not sure it makes sense to duplicate this?

**Comment by martinstuga** [comment]
My idea is to provide a step-by-step that includes stuff like update our remote repository from the upstream and so on.

**Comment by javanna** [comment]
Are there specific issues with the way we use github as a project? In that case we should document things better, otherwise I wonder if it makes sense for every single project on github to include (the same?) instructions about using github.

**Comment by clintongormley** [comment]
Agreed - I think the github docs are sufficient here.  Closing
