### ISSUE TITLE
Extend the Avg Aggregation to support weighted average

### ISSUE THREAD

**Issue by lquerel** [elastic/elasticsearch#15731]
The current Avg Aggretation only supports the simple form of average (ie: sum(values) / num of values). In order to support weighted average (ie: sum( value \* weight) / sum (weight)) in an efficient way, I suggest the following changes in the API.

**First implementation without modification of the existing API**
The script property in the avg object can return a number of a list of numbers. My proposal is to also support a map containing 2 fixed properties: value and weight (or values and weights if multiple values) (. For example:

``` javascript
{"avg" : { "script" : "[value: doc['latency'].value, weight: doc['transaction'].value]" }}
```

I prototyped this solution with only 2 modifications. A first modification in the ScriptDoubleValues class to take into account this map. A second modification in the AvgAggregator class to apply the right formula accordingly to the context.

**Second implementation requiring minor modifications of the existing API (more efficient because no script)**
We can add a new property 'weight' to define the field to use in the document.

``` javascript
{ "avg" : { "field" : "latency",  "weight" : "transaction"} } 
```

I didn't prototype this solution because I'm still not sure which DoubleValues implementation to use to get efficiently the value and the weight. If you have some advices don't hesitate.

A third option is to use scripted metrics but until now it's not possible to sort the result of scripted metrics so that doesn't work for me. I created a pull request to add this support but I'm still waiting approval. But anyway a solution based on scripted metrics will be less efficient. 

This proposal should be easy to implement and I'm pretty sure that many users will be happy with this extended version of the avg aggregation.

**Comment by jpountz** [comment]
Actually this is typically the kind of use-case for which the `avg` aggregation supports scripts. Any reason why you're not happy with scripts?

**Comment by lquerel** [comment]
The weighted average is equals to sum(value-i * weight-i) / sum(weight-i). Value and Weight are dynamic values extracted from a set of documents. Currently the script only returns the value for each document so I don't see any mathematical way to compute easily a weighted average without the weight for each document knowing that currently the result of the script is summed and divided at the end by the number of values (and not the sum of weights).

**Comment by lquerel** [comment]
I sent a pull request with the implementation of the first approach based on the script attribute.

https://github.com/elastic/elasticsearch/pull/15781

**Comment by jpountz** [comment]
> The weighted average is equals to sum(value-i * weight-i) / sum(weight-i). Value and Weight are dynamic values extracted from a set of documents. Currently the script only returns the value for each document so I don't see any mathematical way to compute easily a weighted average without the weight for each document knowing that currently the result of the script is summed and divided at the end by the number of values (and not the sum of weights).

Right, this involves some client-side logic, something like (not tested):

```
{
  "aggs": {
    "weighted_sum": {
      "sum": {
        "script": {
          "inline": "doc['value'].value * doc['weight'].value"
        }
      }
    },
    "sum_of_weights": {
      "sum": {
        "field": "weight"
        }
      }
    }
  }
}
```
And then you would need to divide the `weighted_sum` value by `sum_of_weights`. I can understand that this is less convenient that that eg you can't use it with kibana so I'm open to discussing adding a way to do weighted averages easily. But I would like to make sure there is enough demand for it before (so that the feature is worth maintaining) and have a discussion about what to do if either the source of values or weights is missing in a document or multi-valued. If we can't come with a nice API then I'd rather not implement the feature. I'll mark this issue as `discuss` so that others chime in.

**Comment by lquerel** [comment]
Thank for your response.

With this approach, how can you order the result of the weighted average? With my proposal it's done directly by the coordinator node with the following query.

```
{
  "aggs": {
    "myAggr": {
      "terms": {
        "field": "dimension",
        "order": { "weightedAgv": "desc"}
      },  
      "aggs": {
          "weightedAvg": {"avg" : { "script" : "[value: doc['latency'].value, weight: doc['transaction'].value]" }}
       }
    }
}
```

Except if I'm wrong, but with your approach I need to sort client side and means potentially loading a lot of data. Right ? 
IMO it's a second good reason (with kibana) to support this feature natively. I will be very happy to help if needed. 

Multi-valued values/weights are implemented in my pull request has follow:

** Standard average **
```
{ "avg" : { "script" : "doc['latency'].value" }} } 
```

By default the weight is equals to 1.

** Weighted average (single-valued) **
```
{ "avg" : { "script" : "[value: doc['latency'].value, weight: doc['transaction'].value]" }}} 
```

** Weighted average (multi-valued) **
```
{ "avg" : { "script" : "[values: doc['latency'].value, weights: doc['transaction'].value]" }}} 
```

Weights is optional, if not provided then by default weight=1 for each value.
If weights.size() < values.size() then by default weight=1 for each value without corresponding weight.
Otherwise we use the corresponding weight.

General remark: when the weight field is missing in the original doc then by default weight=1.

**Comment by elephantum** [comment]
+1 for any reasonable solution. Weighted average is a common case in any business-related dashboard.

**Comment by jpountz** [comment]
Thinking about it a bit more: the only reason to not do it on client side is to be able to order by sub aggregation. However sorting by sub aggregation has the drawback of making counts very inaccurate, I am actually more thinking of deprecating the ability to sort by sub aggregations and by asending count because of that. So I don't think we should add a weighted average aggregation (or add weighting support to the avg agg) just to be able to sort by it.

> If weights.size() < values.size() then by default weight=1 for each value without corresponding weight.

This won't work since elasticsearch does not maintain the order of values in fielddata: they always come in ascending order. So if your original document has `{value: [5, 1], weight: [2,3]}`, we will actually use a weight of 2 for 1 and 3 for 5.

**Comment by jpountz** [comment]
We just discussed it in Fixit Friday. We like the feature but would like to verify that there is traction for this feature before implementating it. Also we need to figure out a clear API, especially about what happens with multi-valued fields or missing values.

**Comment by lquerel** [comment]
Good news.

Proposal: add a new aggregation to compute weighted average.
 
{ 
	"weigthed-avg" : { 
		"field-value" : string,      [mandatory]
		"field-weight": string,     [mandatory]
		"missing-value": int,      [optional, default 0]
		"missing-weight": int     [optional, default 1]
	} 
}

The management of multi-values fields was already described before in this thread.
 
Weighted average computed as: sum(field-value[i] * field-weight[i]) / sum(field-weight[i])

**Comment by kylevarisco** [comment]
I'd love to see this in ElasticSearch.  In our business (commodity trading/marketing/logistics), weighted averages are the main metric that we use - weighted average sales prices, weighted average transport costs, etc.  I think this would be a very useful addition - currently we are having to calculate sums in Elastic, and then pull those results to a middle tier where the weighted averages are calculated.

**Comment by smartlocating** [comment]
@lquerel @jpountz what is your current recommendation for getting a single-value weighted average?

**Comment by hilalgur** [comment]
Hi,
I have same problem. I want to weighted average on ES-5.0.0. I did something:
```
GET titubb56k/ihale/_search 
{
  "aggs": {
    "myAggr": {
      "terms": {
        "field": "UrunNo",
        "order": { "weightedAvg": "desc"}
      },  
      "aggs": {
          "weightedAvg": { "avg" : { "script" : "[values: doc['BirimFiyat'].value, weights: doc['Adet'].value]" }}
       }    }  }  }
```
and I have error:

```
{
  "error": {
    "root_cause": [
      {
        "type": "parsing_exception",
        "reason": "Unexpected token VALUE_STRING [script] in [weightedAvg].",
        "line": 9,
        "col": 49
      }
    ],
    "type": "parsing_exception",
    "reason": "Unexpected token VALUE_STRING [script] in [weightedAvg].",
    "line": 9,
    "col": 49
  },
  "status": 400
}
```
What is the problem? Or weighted average is possible on ES-5.0.0

**Comment by hilalgur** [comment]
I did,
```

POST ortalama/avg/_search
{
  "size": 3,
    "query": {
    "term": {
      "IdareKodu":  "4"
      }
    },

  "aggs": {
    "gunluk_satis": {
      "terms": {
        "field": "IdareKodu"
      },
      "aggs": {
        "pay": {
          "sum": {
            "script": {
              "lang": "expression",
              "inline": "doc['BirimFiyat'] * doc['Adet']"
            }
          }
        },
       
        "payda": {
          "sum": {
            "script": {
              "lang": "expression",
              "inline": "doc['Adet']"
            }
          }
        },
        "sonuc": {
                    "bucket_script": {
                        "buckets_path": {
                          "Pay": "pay",
                          "Payda": "payda"
                        },
                        "script": "params.Pay / params.Payda"
                    }
                }
      }
    }
  }
}

That worked
```

**Comment by lquerel** [comment]
@jpountz what is the conclusion?

**Comment by mandarincreative** [comment]
Any update on a native-ish weighted Average?

**Comment by darrencruse** [comment]
Just a note that I'm disappointed this hasn't made it in - I'm working for an agriculture company and it's common to do calculations that are weighted by the area of farmers fields.

i.e. the search is matching attributes in the indexed documents (representing fields) to select a subset of all possible fields, and the field documents have other values to average, along with the area of each field.  So the goal is to do averages on the values weighting them more for bigger fields and less for smaller fields, with different searches used for the selection (might be region of the country, type of crop being grown etc. etc).

(giving the detail JIC there's still a thought this isn't a common need - maybe I'm biased because of my problem but I think this really *is* a common need, and also hoping feedback if people think this can be done client side - I've racked my brain about this and I don't see how it can be?) 

Anyway I'd gotten a little excited that I'd landed on the "bucket_script" solution like @hilalgur showed above.

Then disappointed again when it seems there no way to get a Kibana visualization to use a query that needs a "bucket_script" (seems it only supports plain "script" and it seems to *have* to generate the ES query itself it doesn't seem possible to completely tell it the ES query you want it to use AFAICT).

atm I'm thinking we might have to ditch Kibana and go with doing charts ourself atop the ES queries which use "bucket_script".   Seems ashame though Kibana seems pretty nice in a lot of ways otherwise.

**Comment by jdimeo** [comment]
I'm interested from the perspective of downsampling old documents. If, for example, I'm dropping 99 out of 100 documents > 1 year old, 9 out of 10 > 6 months old, and all documents < 6 months old, I would love it if I could configure aggregations (including but not limited to average) to appropriately weight the old documents x100 or x10 so that I can re-create the original counts with some margin of error/approximation.

**Comment by jpountz** [comment]
I think it's becoming obvious that there is traction for this feature, so let's give it a try? Let's just make sure that the documentation is clear as to how the weight is computed in case of missing values or multiple values.

**Comment by jpountz** [comment]
As far as I'm concerned, I'd like it to be a new aggregation rather than adding options to the `avg` aggregation, as well as clearly separating options that applies to values from those that apply to the weight, eg.

```
{
  "weighted_average": {
    "weight": {
      "field": "w",
      "mode": "min",
      "missing": 1
    },
    "values": {
      "field": "poularity"
    }
  }
}
```

**Comment by cicisoso** [comment]
any plan updated about weighted average?  @jpountz  will you put this feature in next release?

**Comment by jpountz** [comment]
> any plan updated about weighted average?

It's currently labelled as an `adoptme` meaning it is waiting for someone to pick it up.

> will you put this feature in next release?

Probably not.

**Comment by rsmything** [comment]
Anyone can help to calculate weighted mean based on the count of each value as the weight

**Comment by viranch** [comment]
I'm also interested in downsampling my documents like @jdimeo but need weighted average.

@jdimeo were you able to build a work around? I'm thinking of writing a middleware that will calculate weighted average from counts stored with the downsampled documents.

**Comment by rsmything** [comment]
Please help to make right aggregation

> 
Invalid pipeline aggregation named [weighted_mean] of type [bucket_script]. Only sibling pipeline aggregations are allowed at the top level


```
{
  "size": 0,
  "aggs": {
    "overall": {
      "terms": {
        "field": "days",
      },
      "aggs": {
        "summary": {
          "sum": {
            "script": {
              lang: "expression",
              inline: "doc['days'] * _score"
            }
          }
        }
      }
    },
    "total": {
      sum_bucket: {
        "buckets_path": "overall>summary"
      }
    },
    "count": {
      value_count: {
        "script": {
          "source": "doc['days'].value"
        }
      }
    },
    "weighted_mean": {
      "bucket_script": {
        "buckets_path": {
          "Total": "total",
          "Count": "count"
        },
        "script": "params.Total / params.Count"
      }
    }
  }
}
```

**Comment by jdimeo** [comment]
@viranch no workaround, sorry- we're just not implementing downsampling for now

**Comment by colings86** [comment]
@elastic/es-search-aggs

**Comment by lquerel** [comment]
Happy to see that you finally integrated this feature.
