### ISSUE TITLE
Adding Multiple Types

### ISSUE THREAD

**Issue by chirag2528** [elastic/elasticsearch#15773]
Is there any way to add values in a column which a comprises of Double and Long Values and Retrieve them back Using Spark Java ESRDD.

Also I don't want Elastic Search to Upper cast a long value to double and type cast double to long ?
I have tried using ignore_malformed because first value can be double value or a long value.

**Comment by rjernst** [comment]
Questions like these are better asked on http://discuss.elastic.co. Github is reserved for bug reports and feature requests.

Fields in elasticsearch must be a single data type.  You can store longs in a double field, or vice versa, but you will lose precision in the process.  It sounds like you are using dynamic mappings, which is why you care about the "first value". Instead, you can explicitly set your mappings, and the values in your documents will (by default) be coerced to that type (ie passing a long value, but with field mapped as double).
