### ISSUE TITLE
It would be useful to have a way to ignore broken transaction log on index recovery

### ISSUE THREAD

**Issue by haizaar** [elastic/elasticsearch#15779]
This is a spin off the problem discussed here: https://discuss.elastic.co/t/cannot-recover-index-because-of-missing-tanslog-files/38336

I have an index with broken transaction log data. The data itself in the index appears to be fine as reported by Lucene tool. However ES 2.1.1 refuses to bring the index up because of broken translog. 

Since the actual index data is there, I think there should be a way (a tool?) to instruct ES to disregard the transaction log file and to start over.

**Comment by bleskes** [comment]
@haizaar to be clear - throwing away the transaction log means a likely data loss. In your case it's pretty much guaranteed (because of the translog generation your lucene index points at). I'm fine with having a way to allow users to confirm this loss and open the lucene index but we need to be clear about the implications. 

Also note that usually another shard will be used to recover the primary.  This request is about having a way to recover where all copies have been lost or have corruptions, in the specific case that one of those corruptions is in the translog.

**Comment by haizaar** [comment]
Yes, I fully understand the implications. However if you ever get to this situation (no replicas and no adequate backups) I prefer to have a choice between full data loss (like it is now) and partial data loss. And I much prefer the partial one.

I hope I read you right.

**Comment by bleskes** [comment]
> I hope I read you right.

You do :)

**Comment by s1monw** [comment]
> I have an index with broken transaction log data. The data itself in the index appears to be fine as reported by Lucene tool. However ES 2.1.1 refuses to bring the index up because of broken translog.

I am curious, you have yet another broken t-log? What's the problem this time?

**Comment by haizaar** [comment]
No. I opened this bug as a spin off from original discussion we had before.

**Comment by dakrone** [comment]
Coming back to this after working with someone who had a corrupt (though empty) translog and wanted to keep the data in the shard as it was the only copy (a single primary, no replica). I think we should either have a way to ignore a corrupted translog (with a ton of warnings and all that) or a tool that can put an empty translog in place so a shard can recover. Otherwise, it's frustrating in the case of accidental translog corruption or truncation to lose the entire shard's worth of data.

**Comment by clintongormley** [comment]
Agreed - we need a command line tool to perform expert operations such as this.

**Comment by dnhatn** [comment]
Implemented in https://github.com/elastic/elasticsearch/pull/19342.
