### ISSUE TITLE
ES 2.1.1 bloats log files if particular index has a broken transaction log

### ISSUE THREAD

**Issue by haizaar** [elastic/elasticsearch#15780]
This is a spin off the problem discussed here: https://discuss.elastic.co/t/cannot-recover-index-because-of-missing-tanslog-files/38336.

If ES 2.1.1 encounters broken transaction log during index recovery - as listed in the above discussion, it starts quite rapidly to fill up the log files - at about 10GB/hour rate. This can fill up the disk space and cause for additional instability. f

I think logging strategy for such errors should be less aggressive and utilize [Truncated Exponential Backoff](https://github.com/elastic/elasticsearch/issues/15779) approach.

**Comment by bleskes** [comment]
@haizaar did you have any replicas or was this the single shard copy available?

**Comment by haizaar** [comment]
I had one replica (it's `.kibana` index with default settings).

**Comment by bleskes** [comment]
@haizaar thanks. Was that replica assigned and active? I think you mentioned a single node?  If you've had another replica it would have taken over. Sadly if the master has no other options it just keeps trying and that spams the log. Agreed we should do better.

**Comment by haizaar** [comment]
It was a single node scenario. The replica was not assigned and did not take over for some reason.

**Comment by surry** [comment]
We saw something similar with log files growing huge when we hit the maximum number of documents for an index. We had a 20 GB log for one day that was filled with indexing exceptions related to that limit because we kept trying to index new documents. Thankfully this was at the end of the month and a new index was created a few days later.

I wouldn't say that's an Elasticsearch issue, but I thought it might fall into the same bucket as the fix hinted at above.

**Comment by DaveCTurner** [comment]
Closing for a handful of reasons:

- A one-node cluster is not a resilient setup. This specific problem seems fixable, but fixing resilience problems that only occur in one-node clusters is generally a long way down the priority list. Use >1 node where you need resilience.

- Backoff of _logging_ is a bad idea - when analysing log files it's important to be able to reason about what the system was doing based on messages that aren't there as well as the ones that are, and suppressing log messages breaks that.

- The [linked discuss issue](https://discuss.elastic.co/t/cannot-recover-index-because-of-missing-tanslog-files/38336) reached a workaround.

- There's been no further activity here for a couple of years.
