### ISSUE TITLE
Phrase query on field mapped as long does not filter results

### ISSUE THREAD

**Issue by BigFunger** [elastic/elasticsearch#15807]
This issue was raised by a user in irc. They were trying to filter on a field in kibana with no success. Upon digging a bit deeper we found that his field was mapped as a long. When I tried to create a filter in kibana on that field, none of the results were filtered out. Kibana creates filters on long fields as phrase queries.

To see the issue input these commands into sense.

```
DELETE /xamox

POST /xamox
{
  "mappings": {
    "test": {
      "properties": {
        "long_field": {
          "type": "long"
        },
        "double_field": {
          "type": "double"
        }
      }
    }
  }
}

POST /xamox/test
{
  "long_field": 0.253388538525881,
  "double_field": 0.253388538525881
}

POST /xamox/test
{
  "long_field": 0.640691024131749,
  "double_field": 0.640691024131749
}

POST /xamox/test
{
  "long_field": 0.0878632360473135,
  "double_field": 0.0878632360473135
}

#basic query
GET /xamox/test/_search

#phrase query on long
POST /xamox/test/_search
{
  "query": {
    "match": {
      "long_field": {
        "query":0.640691024131749,
        "type":"phrase"
      }
    }
  }
}

#phrase query on double
POST /xamox/test/_search
{
  "query": {
    "match": {
      "double_field": {
        "query":0.640691024131749,
        "type":"phrase"
      }
    }
  }
}
```

**Comment by jimferenczi** [comment]
The phrase type is not the problem here. It works as expected, the problem is the coercion that is done on long mappings by default. This means that if your input contains a floating point it will be truncated to a long. As a result all the "long_field" in your example documents are all indexed under the same term: 0. This is why your query on long_field returns all the documents, it is internally translated into:
````
"match": {
   "long_field": {
      "query":0,
      "type":"phrase"
  }
} 
````
The solution for your problem would be to change the mapping to use double instead of long.
