### ISSUE TITLE
Elasticsearch 2.1.1 doesn't automatically start on Ubuntu 16.04

### ISSUE THREAD

**Issue by ThomasdOtreppe** [elastic/elasticsearch#15800]
I have been testing 16.04 with Logstash, Kibana and ElasticSearch and so far, Logstash and Kibana (I'm using the init.d file from Kibana 4.1.1) start just fine with the init.d file at boot time.

But ElasticSearch doesn't start at boot time and it doesn't even run the file at boot. However, if I login on the system and manually start it using 'service elasticsearch start', it works just fine.

I tested the exact same scenario with 14.04 and it works just fine and starts at boot. So, there is something Ubuntu 16.04 doesn't like in the init.d file.

Download URL for Ubuntu 16.04:
- http://cdimage.ubuntu.com/ubuntu-server/daily/

**Comment by nik9000** [comment]
Do the instructions in at the [repository](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-repositories.html) page for making it start automatically work for you? The Elasticearch deb doesn't register itself to start on boot intentionally even though that is the normal thing for debs to do because we think that behavior is creepy in a distributed system.

**Comment by ThomasdOtreppe** [comment]
I was doing the `update-rc.d elasticsearch defaults 95 10` that has been working forever until 16.04 that switched to systemd. The systemctl command worked perfectly.

Sorry about that.

**Comment by gsouf** [comment]
Hi @nik9000  
The link you sent is not working anymore, would you like to update it please?

**Comment by regularmike** [comment]
This fixed it for me:

`sudo systemctl enable elasticsearch.service`

**Comment by FlorinMarina** [comment]
sudo /bin/systemctl daemon-reload
sudo /bin/systemctl enable elasticsearch.service
sudo /bin/systemctl start elasticsearch.service
