### ISSUE TITLE
memory leak in BitsetFilterCache

### ISSUE THREAD

**Issue by jamesjin** [elastic/elasticsearch#15820]
When we have many indices and part of them contains nested type, we can find that the heap is cost by BitsetFilterCache very quickly. It can be reproduced on ES2.1 under the default setting. Here is the steps:

1. create two indices "index1" and "index2"
2. add type "tweet" with nested type "comments" to "index1"
3. add a new tweet doc to "index1"
4. wait until it finishes the refresh
5. dump the heap, you can find that the "loadedFilters" field of BitsetFilterCache of "index2" contains the query result of "index1".

And the root cause is:

BitSetProducerWarmer does not check the index name in the method BitSetProducerWarmer#warmNewReaders. And IndicesWarmer notifies every BitSetProducerWarmer even the indexShard does not belong to the index of the BitSetProducerWarmer

**Comment by jpountz** [comment]
This is a very good observation, I could reproduce it.

**Comment by ycombinator** [comment]
Hi @jamesjin, thanks for reporting this issue! I work in Developer Relations at Elastic. I understand it must've taken you a significant bit of time to reproduce it and figure out the root cause. Thank you for doing that. As a token of our appreciation, we'd like to send you a small thank you gift. Could you send us a quick "hello" email us at developerrelations [at] elastic.co and we'll figure out how best to get you the gift there? Thanks again!
