### ISSUE TITLE
add update-by-query job id metadata

### ISSUE THREAD

**Issue by djschny** [elastic/elasticsearch#15839]
This request is to add (by default preferably) the ability to add/update a field on a document that is a unique ID associated with the reindex job being run. This has the following use cases for example:

1. As a reindex job is running, you can track it's progress simply by writing a filtered query to see how many documents have that ID on it.
2. If some documents were not updated due to conflicts (since it is my understanding we are not retrying on conflict), this will allow a person to determine these documents and take appropriate manual or other action post reindex job completion.
3. If the reindex job failed half way through (due to whatever reason), one would be able to know how far it got, what documents to run over again for the rerun, etc.
4. Later on when task management is in place, automatic rerunning of the job can continue on another node and we would know what set of documents to resume on.

In lieu of this being available, one could accomplish this by script but of course it would be manual up to each person to do. However I believe this is something good to have on by default as it helps promote best practices. One could also disable it when calling a reindex API. Some configurable options that come to mind:

* `job_id_stamping` - defaults to `true` and controls whether the above described behavior happens
* `job_id_field` - specify the name of the field to use to store the job id in. defaults to something like `reindex_job_id`
* `job_id_value` - specify the value to place in the `job_id_field` of a document when it is updated. Defaults to something unique like a uuid, task id, or datetime stamp.

While this may not make it in the first iteration, this is important metadata to have and making sure we think about scenarios like this as we continue to iterate on the tool is important.

**Comment by clintongormley** [comment]
(This discussion is really about update-by-query rather than reindex - title updated to reflect that)

While the job_id approach might work for some use cases, I think that it is too blunt a tool and ignores the fact that multiple update-by-query requests could be run in parallel on the same index.  Instead, I think the scripted approach (in combination with filters) is the correct one.

Update scripts should be written to take parallel changes into account, eg:

    if (ctx._source.name == 'Jon') {
        ctx._source.name = 'John'
    }

This can be rerun with a filter on name == 'Jon', but the logic depends entirely on how the application should behave.  Providing just one rigid way of doing this would be insufficient and, I think, confusing.

> As a reindex job is running, you can track it's progress simply by writing a filtered query to see how many documents have that ID on it.

Status can already be tracked via task mgmt.
