### ISSUE TITLE
Be able to specify translog path in elasticsearch.yml

### ISSUE THREAD

**Issue by sherry-ger** [elastic/elasticsearch#15970]
It would be nice to be able to place translog on a different filesystem from the Elasticsearch data files.  So  upon restart of a node, replaying translog and writing data files won't hit the same disk.

**Comment by clintongormley** [comment]
I don't like this idea for a few reasons.  The first is that we're now managing two directory trees which may or may not overlap, so you have to be extra careful when creating them, cleaning them up or moving them around.  The chance of introducing bugs here is high.

The second is that we have just moved away from splitting shards across multiple paths to ensuring that a single shard is contained entirely on a single disk.  The reason for this was to avoid the loss of one path corrupting all of your shards.  If users have a separate path just for translogs then we're back to the same situation.

My feeling is: if your disks aren't keeping up, then get SSDs or add more hardware.

**Comment by clintongormley** [comment]
Discussed this in FixItFriday - @s1monw pointed out two important issues:

* An entire shard needs to belong to a single path so that it if any part fails, the whole shard fails.
* When nodes are shut down, they flush to disk, meaning that there is no translog to replay on startup.  Only in case of disastrous shutdown do translogs need to be replayed.  Introducing the complexity of multiple paths for this outlier is not worth it.

Closing
