### ISSUE TITLE
Nodes info and stats output do not show tribe node clients

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#16105]
/_cat/nodes?v run against the tribe node shows the following:

```
host      ip        heap.percent ram.percent load node.role master name                   
127.0.0.1 127.0.0.1                               c         x      tribe_cluster_node1/t2 
127.0.0.1 127.0.0.1                               c         x      tribe_cluster_node1/t1 
127.0.0.1 127.0.0.1                               c         x      tribe_cluster_node1    
127.0.0.1 127.0.0.1            5         100 2.69 d         x      cluster2_node1         
127.0.0.1 127.0.0.1            5         100 2.69 d         x      cluster1_node1  
```

You will see 1 node for each downstream cluster (there are 2 downstream clusters here each with a single node), the tribe node itself, and its corresponding tribe node clients that joined both clusters.

But if you hit the `_nodes` or `_nodes/stats` api against the tribe node, you will see that it only returns cluster1_node1, cluster2_node1 and tribe_cluster_node1 in the output.  The 2 tribe node clients are missing from the output (unlike the `_cat/nodes` output).

**Comment by clintongormley** [comment]
Related to https://github.com/elastic/elasticsearch/issues/16815

**Comment by javanna** [comment]
This doesn't necessarily have to do with tribe nodes, as Clint pointed out above, it's more to do with client nodes. 

`_cat/nodes` reads first from the local cluster state, which is why you see there all the nodes. Note that if you run the same call on any other node in the cluster apart from the tribe node, you'll see the same nodes apart from the tribe node itself, as that one doesn't really join the cluster.

On the other hand nodes info and stats actually connect to all nodes in the cluster to gather information, and a client node cannot at the moment cannot to another client node as explained in #16815. Closing in favour of #16815.
