### ISSUE TITLE
Index buffer - clarify min and max settings relative to size

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#16115]
[Here](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/indexing-buffer.html) it's not immediately clear how min and max relate when we also have size. @javanna was nice enough to check and mentioned;
> the min and max are taken into account only when index_buffer_size is a percentage.  In that case the min and max may override index_buffer_size depending on how much memory is available

Thanks to this thread [here](https://discuss.elastic.co/t/index-buffer-size-vs-max-index-buffer-size/39586) for prompting the question.

**Comment by javanna** [comment]
See https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/indices/IndexingMemoryController.java#L101 .

**Comment by s1monw** [comment]
@mikemccand is this still relevant?

**Comment by mikemccand** [comment]
It is still relevant, even in master, because those settings determine the size of the total indexing buffer for the node.  Only the per-shard min and max settings were removed in master from #14121.

Are there specific suggestions on improving the docs?  (They do already state that they only take effect when `index_buffer_size` is a percentage already...).

**Comment by clintongormley** [comment]
Honestly I think the docs are pretty clear.  @markwalkom if you can think of a way of making this clearer, feel free to send a PR but otherwise I'm going to close this

**Comment by markwalkom** [comment]
There ya are mate! :D

**Comment by clintongormley** [comment]
Closing
