### ISSUE TITLE
port fix for windows command line options to master

### ISSUE THREAD

**Issue by brwe** [elastic/elasticsearch#16129]
This pr https://github.com/elastic/elasticsearch/pull/15320
cannot be easily ported to master because we need to translate mvn/ant to gradle which might take me a little so I open an issue here.

**Comment by rjernst** [comment]
I don't think the change will be that difficult, but I would also wait until I've finished refactoring ES into a fixture. Part of that is to use ProcessBuilder instead of ant exec, at which point we will no longer use the pidfiles for correct test execution, and the command line qa test you have here can set the options and check the pid file itself.

**Comment by brwe** [comment]
> I would also wait until I've finished refactoring ES into a fixture

ok

**Comment by clintongormley** [comment]
@rjernst does this still need doing?

**Comment by jasontedor** [comment]
> does this still need doing?

The fix has been done in master in e32da555aa56b20f914610282392f51c2d12b8ac by @ywelsch after the command-line parsing refactoring in #17088 but the tests have not been forward-ported.

**Comment by clintongormley** [comment]
@brwe would you be able to port the tests to master please?

**Comment by brwe** [comment]
ok

**Comment by brwe** [comment]
We discussed it in #18437 and came to the conclusion that might make more sense to invest in bats tests for windows (https://github.com/elastic/elasticsearch/issues/18475) instead of having this one test in gradle or the likes.

**Comment by brwe** [comment]
superseded by #18475
