### ISSUE TITLE
"/etc/init.d/elasticsearch stop" takes 86400 seconds in RHEL6.x.

### ISSUE THREAD

**Issue by yfujita** [elastic/elasticsearch#16140]
This is same problem with #15520.

Cause of this problem is that behavior of killproc is different between RHEL 6 and 7. 

Line 129 of /etc/init.d/elasticsearch:
```
killproc -p $pidfile -d 86400 $prog
```

In RHEL 6, killproc execute "sleep $delay" if target process does not stop within 1sec. So, "/etc/init.d/elasticsearch stop" often takes 86400 seconds, even if elasticsearch is stopped.

**Comment by jasontedor** [comment]
Duplicates #15520.

**Comment by marevol** [comment]
@jasontedor I think that this problem is to use killproc in /etc/init.d/elasticsearch.
For RHEL 6, elasticsearch waits 86400 sec(24h) even if a process of elasticsearch is stopped.
For RHEL 7, elasticsearch is stopped if the process is stopped within 24h.
This behavior  for _RHEL 6_ annoys us in our production environment.
I think it's better not to remove/replace killproc in elasticsearch's init script.
