### ISSUE TITLE
Improve level logic in cluster stats api

### ISSUE THREAD

**Issue by augusto-altman** [elastic/elasticsearch#16266]
Currently the _ClusterHealthRequest_ class (and therefore _ClusterHealthRequestBuilder_) does not support the [**level** request parameter](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-health.html#request-params).

Each time the cluster health is requested using the Java API

``` java
//cluster health at shard level is retrieved
client.admin().cluster().prepareHealth().execute().actionGet();
```

The cluster health is retrieved at _shard_ level. (Tested on version 2.0.0)

This improvement would be very nice for saving memory on cases where the amount of indices/shards is too high and the user only needs the general cluster health. Also it's currently not following the REST API defaults (its default level is _cluster_)

**Comment by clintongormley** [comment]
The stats have to be collected at the shard level anyway, in order to summarise it at the index and cluster level.  Really the only change would be to not populate the maps in the response.  This may be worth doing for a small saving when sending the response to the client.

Note: changing the default level to `cluster` for the java api would be a breaking change.

**Comment by martijnvg** [comment]
The `level` parameter logic should be moved from `ClusterHealthResponse#toXContent(...)` method to `ClusterStateHealth` constructor so that we would never serialize indices level stats during node to node serialization. Also `ClusterHealthRequest` should get a getter/setter for the level logic.

> Note: changing the default level to cluster for the java api would be a breaking change.

Currently this is the default.

Note that in the rest client the `level` parameter can be specified as an additional parameter.

**Comment by javanna** [comment]
I wonder if this is still relevant given that the transport client is deprecated. This is one of those situations where we filter the output on the REST layer but given that the transport client doesn't go through REST, some flags are not available and the output comes back unfiltered. This is similar e.g. in get aliases API and others, but the high-level REST client behaves like the other clients as it parses back the REST response. Maybe we can close this as won't fix?

**Comment by martijnvg** [comment]
So in the low level client one can pass down custom query string parameters, but I didn't see how this is possible in the high level rest client. As the `level` parameter is not part of `ClusterHealthRequest` class. This is the main reason why I left it open.

**Comment by javanna** [comment]
@martijnvg  for all the flags that are only supported by the REST layer but not by our requests, once we add support for the API to the high-level REST client, we are forced to add support for the missing flag to the request, although it will only be read by the high-level REST client.

**Comment by javanna** [comment]
As part of prioritizing the work for #27205 we have decided to leave adding support for cluster stats API for later. Making the level parameter supported in the high-level client is something that will be part of adding support for cluster stats once we want to add it, it does not need a specific issue. Also, we are not going to change this in the current transport client, so I am going to close this issue.
