### ISSUE TITLE
Improve documentation on snapshot restore using URL (read-only) repository

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#16280]
A few documentation improvement suggestions based on user experience in the field:
- Will be nice to add a cross reference to setting up [read only url repository](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/modules-snapshots.html#_read_only_url_repository) from the [restore](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/modules-snapshots.html#_restore) section of the guide.
- Providing an example (eg. for file protocol) will be nice.

```
PUT /_snapshot/my_restore_repo
{
  "type": "url",
  "settings": {
    "url": "file:///nfs/path"
  }
}
```
- When setting up a read-only repository, only setting up repositories.url.allowed_urls is sufficient.  The statements below suggests that path.repo is also required.

> "URL Repository supports the following protocols: "http", "https", "ftp", "file" and "jar". URL repositories with http:, https:, and ftp: URLs has to be whitelisted by specifying allowed URLs in the repositories.url.allowed_urls setting. "
> "URL repositories with file: URLs can only point to locations registered in the path.repo setting similar to shared file system repository."

**Comment by frederikbosch** [comment]
I dont get the purpose of this method at all. Could someone dxplain it?

**Comment by clintongormley** [comment]
@frederikbosch you can make snapshots available to the public (or privately to others) via a read-only URL repository.

**Comment by frederikbosch** [comment]
@clintongormley Alright, but how is that achieved? Is the data pushed to some other location?

**Comment by frederikbosch** [comment]
My case is that I want to push the backup directly (without hitting the local fs) to another location (over HTTPS over FTPS/SFTP). And I thought that this backup type might be useful. For me S3, HDFS and Azure are not an option.

**Comment by clintongormley** [comment]
@frederikbosch no, it's read only.  it's for making read only copies available to others, not for making the snapshots yourself. we don't have an http only writable repository

**Comment by frederikbosch** [comment]
@clintongormley Thanks for your answers! That is really helpful.

**Comment by BaranOrnarli** [comment]
@clintongormley is there no way to transfer a local zipped folder (generated via _snapshot "fs") to ES Master node, then distribute it across the ES cluster without "shared drives"? I was looking for a way to simply point to a "local filesystem repo" and have the Master ES node distribute it into the cluster or _snapshot-restore it by reading the local filesystem (read-only). The "Type: 'fs'" ES-repo requires a COPY of the folder in EACH datanode/masternode which is really difficult with one folder/zip that is gigantic.

**Comment by wchrisdean** [comment]
To grok on what my research process has been on this so far, and what ongoing authoring looks like:

1. Reffing https://github.com/elastic/elasticsearch/issues/40663 - guide needs to link the actual reference material
2. Create separate reference doc for snapshot + restore REST API, which needs to live in the API section (there currently is none).
3. Rework current article to be more of a step-by-step how-to for creating the backup instead of just API documentation. Use https://www.elastic.co/guide/en/elasticsearch/guide/2.x/backing-up-your-cluster.html Definitive guide info as a boilerplate
4. Get review on versioning. Def-guide material is outdated (from 2.x), and while the format is good, the substance likely is not.

Work is ongoing but continuing.

**Comment by wchrisdean** [comment]
Additional reference material from outside source - https://qbox.io/blog/elasticsearch-data-snapshots-restore-tutorial
If we want to include the actual bash administration information as part of this tutorial, this would be a good source reference for authoring.

**Comment by debadair** [comment]
[docs issue triage]

**Comment by wchrisdean** [comment]
@colings86 
I. Intro 
  a. what is a snapshot
  b. why do you need to do this instead of simply copying the directories. Elevate that to actual content instead of breaking it into a warning note.
  c. Snapshot methods and automation
    i. REST API (linking to new API page)
    ii. SLM
  d. Version compatibility (anchor to section V)
  
II. Repositories
  A. Local Repository
    i. Registering a Repository
      a. deleting/unregistering a repository (currently in the snapshots section)
    ii. Creating a repository
    iii. Managing a Repository
    iv. Shared File system
      a. Mounting how-to
      b. settings
  B. Remote Repository
    i. advantages vs. local Repositories
    ii. Plugins for working with s3, azure, gcs, Hadoop

III. Snapshots 
  A. Create a Snapshot
    i. Basic example
    ii. Advanced example with specific settings
    iii. Snapshot default settings
  B. Managing snapshots
    i. snapshot state info
    ii. Snapshot status information (move from current Restore section)
    iii. retrieve a snapshot
    iv. delete a snapshot (refer to unregistering repository)
    v. monitor a snapshot (move from current Restore section)

IV. Restore
  A. Restore a snapshot
    i. Link to REST API docs on managing Restores
    ii. default restore settings and how to change
    iii. Restoring cross-cluster
    
V. Version compatibility
(content staying mostly the same with structural changes)
  A. move this from the intro, does not need to be at the topline of the doc, but should still be scannable.
  B. language itself can stay intact, a few minor tweaks needed
  C. Engineering review of version compability needed to ensure this is still accurate
  D. Move this to a chart format so its more easily scannable

First step for this is to break out the API documentation to the REST section so that we have a linkable asset before the rewrite. Notes
-Much of the content itself, where accurate, will remain the same. It will simply be an update in the way the content is laid out and presented, with it being more of a front-to-back guide on setting up the repo, creating the snapshot, then restoring said snapshot
