### ISSUE TITLE
CONF_FILE setting is no longer supported. elasticsearch.yml must be placed in the config directory and cannot be renamed.

### ISSUE THREAD

**Issue by luluprat** [elastic/elasticsearch#16306]
i try to upgrade from a centos 
1.5 to 2.1
i can't start elasticsearch 
CONF_FILE setting is no longer supported. elasticsearch.yml must be placed in the config directory and cannot be renamed.

**Comment by dadoonet** [comment]
Yes it's part of the breaking changes. See https://github.com/elastic/elasticsearch/pull/13772

**Comment by luluprat** [comment]
but wath i have to do so to get elasticsearch work ?

**Comment by dadoonet** [comment]
If you need help, you can describe all the steps you made to upgrade to 2.1 on discuss.elastic.co

We can help you there.

Check that you updated all scripts (like bin/elasticsearch...) as well.

**Comment by ekovacs** [comment]
same happend to me. 

Problem:
i did not want to do anything else but install the 2.2.1 version through yum. no other magic, only a simple `yum install ./elasticsearch-2.2.1.rpm`. then starting it gave me the blues `CONF_FILE setting is no longer supported. elasticsearch.yml must be placed in the config directory and cannot be renamed.`

The solution: 
`/etc/sysconfig/elasticsearch` had the `CONF_FILE=/etc/elasticsearch/elasticsearch.yml` line it it, that the rpm install process didn't update. after a couple hours of searching where the hell did i define this environment variable i tripped upon that location. after commenting out that line, the elasticsearch service started. 

@dadoonet Please update the rpm/deb install process so it patches that file so that the service would start without a problem after the upgrade. if not, then please update your documentation to clearly state this possible problem and this solution.

**Comment by dadoonet** [comment]
Thanks @ekovacs. @spinscale WDYT? Should we open an issue?

**Comment by clintongormley** [comment]
@ekovacs Presumably your `/etc/sysconfig/elasticsearch` file was not replaced because it had been edited locally.  You should have had a `.rpm` version (or similar) alongside it.  This is how RPM works.  We can't override your local edits.
