### ISSUE TITLE
mapper is used by multiple types

### ISSUE THREAD

**Issue by sandesh2014** [elastic/elasticsearch#16350]
Have Upgraded ES From 1.7 to ES 2.1. While Indexing, facing the issue mentioned below. Any help would be highly appreciated:

mapper [field] is used by multiple types. Set update_all_types to true to update [format] across all types.]]
[5813]: index [index_name], type [index_type], id [13344701], message [java.lang.IllegalArgumentException: Mapper for [field] conflicts with existing mapping in other types

**Comment by sandesh2014** [comment]
Can anyone from elastic team help out regarding this issue. Do let me know if this is a bug or something else is wrong.

**Comment by rjernst** [comment]
It is hard to give a better explanation of what is happening without seeing the mappings. However, this is expected behavior with 2.0+ when you try to have a field with the same name, but different data types, in two different document types.

Please join us on https://discuss.elastic.co for questions like these.
