### ISSUE TITLE
"query" around "match" causes ConstantQuery and ignores boost

### ISSUE THREAD

**Issue by asldevi** [elastic/elasticsearch#16401]
I'm running on ES 2.1.1.

The following query
```
GET /.../.../_search?explain=true
{
"fields": [], 
"query": { 
    "bool": {
        "should": [
            {"match": {
                "primary_skills":{
                    "query": "communication skills",
                    "boost": 3
            }}}
        ]
    }}}
```
works as expected.

But the same query, with an extra (redundant) `query` around `match` simply causes `ConstantScore` query and doesn't take the boost into account.

```
GET /.../.../_search?explain=true
{
    "fields": [], 
    "query": { 
        "bool": {
            "should": [
                {"query": {"match": {
                    "primary_skills":{
                        "query": "communication skills",
                        "boost": 3
                }}}}
    ]
   }}}
```

shows 
```
"description": "ConstantScore((primary_skills:communication primary_skills:skills)^3.0), product of:",
                           "details": [
                              {
                                 "value": 1,
                                 "description": "boost",
                                 "details": []
                              },
``` 
in the `explain` output.

**Comment by clintongormley** [comment]
That's because the `query` element is a remnant from 1.x, where it was the query filter (see https://www.elastic.co/guide/en/elasticsearch/reference/1.7/query-dsl-query-filter.html)  (ie it allowed you to use a query in filter context).

Queries and filters are now the same thing so the `query` filter has no purpose - it has been left there for bwc reasons, and is removed in 3.0.
