### ISSUE TITLE
Conditional update

### ISSUE THREAD

**Issue by rnagappan** [elastic/elasticsearch#16439]
Is there support for updating a document only if some condition is true? I don't mean versioning. For example if the document in ES is missing some field and I have a possibly newer version of that document with the field present can I tell ES only to update it if the one in the store is missing that field? 

Due to stringent operational speed requirements I really don't want to query for the existing document to compare it to.

**Comment by jasontedor** [comment]
> Is there support for updating a document only if some condition is true?

Please see [partial updates to documents[[(https://www.elastic.co/guide/en/elasticsearch/guide/current/partial-updates.htm](https://www.elastic.co/guide/en/elasticsearch/guide/current/partial-updates.html) and the potential use of  scripting on updates.

> Due to stringent operational speed requirements I really don't want to query for the existing document to compare it to.

Maybe I'm misunderstanding your requirements, but you can just get the document by ID rather than querying. That will be fast.

For future reference, questions like this are best asked on the [Elastic Discourse forums](https://discuss.elastic.co). GitHub is reserved for bug reports and feature requests.

**Comment by rnagappan** [comment]
Thanks for the reply. I thought I was making a feature request!

**Comment by clintongormley** [comment]
@rnagappan that's what scripted updates can be used for

**Comment by rnagappan** [comment]
What I want to do is something like this

http://stackoverflow.com/questions/31599068/using-a-script-to-conditionally-update-a-document-in-elasticsearch

But checking for a field value rather than version. So my code would be something like:

`if (myField != null) do update else cancel operation`

I can see a similar example on the page provided above for delete, but is an equivalent test for update?

**Comment by clintongormley** [comment]
set `ctx.op = "none"`

**Comment by rnagappan** [comment]
Thanks. So I'm guessing that from this page

https://www.elastic.co/guide/en/elasticsearch/guide/current/partial-updates.html

The query would be written as


    POST /website/blog/1/_update
    {
       "script" : "ctx.op = ctx._source.views == count ? 'update' : 'none'",
        "params" : {
            "count": 1
        }
    }
