### ISSUE TITLE
Elasticsearch picks wrong data type

### ISSUE THREAD

**Issue by kavitakanojiya** [elastic/elasticsearch#16468]
I have added new boolean column into one of my tables. Now, I didnt reindexed the whole table/records because I dont use this column to search records, but we chose to reindex for future use maybe.

But elasticsearch index picks up this column with datatype as 'long'. Will you please shed some light why elasticsearch picks this wrong datatype ?

Some docs/pointers will be helpful. Very helpful. This happened to me twice.

**Comment by dadoonet** [comment]
Please join us on discuss.elastic.co. We will provide better help there.

You probably did not define your mapping and your inject process sent to elasticsearch a number like `"foo": 1` instead of `"foo": true`.
As you seem to be importing from a database, you should give details about all what you are doing on discuss so we will have a better picture of what is happening.

Closing as not an issue.
