### ISSUE TITLE
top_hits and sub-aggregations

### ISSUE THREAD

**Issue by bsideup** [elastic/elasticsearch#16537]
Hi!

Why top_hits doesn't allow to have sub-aggregations?

I.e. I want to calculate a median of last N hits in each category

**Comment by martijnvg** [comment]
because the `top_hits` agg is a metric aggregations and metric aggs can't
have sub aggs.
How would you determine what last N hit would be the median? On what field
are you going to sort? Maybe instead use the `percentile` agg?

On 9 February 2016 at 16:01, Sergei Egorov <notifications@github.com> wrote:

> Hi!
>
> Why top_hits doesn't allow to have sub-aggregations?
>
> I.e. I want to calculate a median of last N hits in each category
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/elasticsearch/issues/16537>.
>



-- 
Met vriendelijke groet,

Martijn van Groningen

**Comment by bsideup** [comment]
@martijnvg I use "sort" from top_hits for such decisions. 

Also, I need to calculate median of exactly last N hits in each category, I can't calculate median (aka 50th percentile) of all hits :(

**Comment by clintongormley** [comment]
This sounds like you will need to postprocess your results on the client.  As @martijnvg says, metric aggs can't support sub-aggs.
