### ISSUE TITLE
Not greedy behaviour of "must_not" for array field of terms

### ISSUE THREAD

**Issue by orangeudav** [elastic/elasticsearch#16534]
For example, i have two records with 'name' field:
{_id: 1, name: ['aaa', 'bbb']}
{_id: 2,  name: ['aaa']}
When i execute search query like this
`{must_not: [{term: { name: 'bbb' }}]} `
i get only 2. How can i get [1, 2] (not exclude 1 because it contain not only 'aaa') as result without addition efforts? Do ES have some flag to change greedy of must_not?

**Comment by rjernst** [comment]
Please use http://discuss.elastic.co for questions like this. Github is used for bug reports and feature requests.

I don't know why you think this has anything to do with "greedy". In doc 1, `aaa` and `bbb` are separate terms. The must not query you use finds the `bbb` term and excludes that document. It sounds like you are looking for something to say "must not have only this term". There is no direct support for that type of query that I know of. But you should also think about how useful this query is, since must nots do not contribute to scoring.
