### ISSUE TITLE
Node not marked as client unless node.client: true

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#16565]
From a cluster running ES 2.1.1 (or ES 1.x) with 8 nodes, two of which were client nodes:

```http
GET _cluster/stats
```

produces:

```json
"nodes": {
  "count": {
    "total": 8,
    "master_only": 2,
    "data_only": 4,
    "master_data": 0,
    "client": 0
  }
  ...
}
```

These nodes were set to being client nodes implicitly by using

```yaml
node.master: false
node.data: false
```

It appears that the node.client count is only tripped when using `node.client: true`, but it should be `node.client || (node.master || node.data || node.ingest) == false`. This should be done at the source where ever we do that check initially. The annoying thing is that it kind of prevents other types of nodes from being dynamically added without "lying" if we change that check.

**Comment by javanna** [comment]
interesting point. It raises additional questions though, especially with the node ingest addition.

At the moment, when `node.client` is set to true a node cannot become master nor can hold data. Yet we would need to double check what the precedence is if one specifies also `node.data` or `node.master`... When it comes to `node.ingest`, the assumption is that client nodes can do ingestion, so `node.client` set to `false` doesn't turn ingestion off at the moment, you need to set `node.ingest` to `false` too. I tend to find the `node.client` setting confusing and hard to handle internally at this point, maybe we could keep the setting but make it a shortcut to what it needs to be internally?

**Comment by pickypg** [comment]
> I tend to find the `node.client` setting confusing and hard to handle internally at this point, maybe we could keep the setting but make it a shortcut to what it needs to be internally?

I completely agree and I love the idea.

**Comment by javanna** [comment]
We discussed this during FixItFriday. We reached consensus that the `node.client` setting adds confusion and should be removed in favour of being explicit and say `node.master: false` and `node.data: false`. Being explicit would also make things less confusing around the `node.ingest` setting that was recently added (whether a client node does ingestion or not).

We don't really need to keep `node.client` around as a shortcut as we now validate settings and we can fail at startup from the next major version on if anybody uses the `node.client` setting. We need to be careful with node attributes as they don't have their own namespace as part of settings, so we should be careful that if somebody specifies `node.client` we fail and we don't treat it as a node attribute (or take the chance to give node attributes their namespace).

Last bit is we need to update documentation and code to make sure that client nodes are not mentioned anywhere. This will have an impact on the rest output of some apis like cluster stats, as `client` should not be used there anymore.

**Comment by jtharpla** [comment]
Wouldn't node.master: false and node.data: false still result in an implicit client node? Seems like that that should still be included in the documentation, along with possible use cases where one might want such client nodes.  Or is there an intention to move away from the concept of client nodes altogether? (in other words is this more than a config change, but actually a shift in what architectures are recommended/supported?)

**Comment by pickypg** [comment]
@jtharpla 

> Wouldn't node.master: false and node.data: false still result in an implicit client node?

Yes. This is currently true and it will be true afterward.

> Seems like that that should still be included in the documentation

I agree, but thankfully we recently [rewrote the node module in our documentation](https://www.elastic.co/guide/en/elasticsearch/reference/2.2/modules-node.html). This actually avoids using `node.client` for pretty much the reason of this ticket -- it's confusing.

> Or is there an intention to move away from the concept of client nodes altogether?

No, we're keeping the idea around. Node clients serve a good and reasonable purpose for large clusters.

**Comment by javanna** [comment]
I am working on this, and made good progress, but we need to figure out how to update the cluster stats api output. We currently have `master_only`, `data_only`, `master_data` and `client`. Ingest nodes should be taken into account too, but then the combinations become more than just current 4 that we have. There can potentially be `master_ingest`, `data_ingest`, `master_data_ingest` & `ingest_only` nodes in addition to the ones listed above. We could expose all of the different combinations, or do we only want to report the most common ones (e.g. master_ingest and data_ingest shouldn't get that popular)?

I would also rename `client` to `coordinating_only` to try and clarify what those nodes do.

**Comment by pickypg** [comment]
I don't like not reporting them. Perhaps we can use an `EnumSet`, though I don't necessarily want to pass that over the wire? However, doing that (or equivalent!) should be much simpler than trying to pass around all of the various checks.

**Comment by javanna** [comment]
Let's try and decide what we want to return from the REST layer first. @pickypg I take it that you would be ok with having 8 different node type combinations returned rather than the current 4?

**Comment by pickypg** [comment]
@javanna I would. I think it makes it a lot easier to debug, if necessary. It sucks though because suddenly we're left with `2^n` combinations (where `n` is fortunately just `3` for now), but I'd rather than that semi-arbitrarily hiding some.

I expect some small scale instances to use `data_ingest` for example.

**Comment by pickypg** [comment]
Maybe we can flip the REST layer around, similar to the Java layer. If the response is just an array of the node types that it _is_, then all of the combinations can be determined by the client. Then we can avoid the combinatorial nightmare (and empty implies `coordinating_only`).

**Comment by javanna** [comment]
ok let's see what @clintongormley thinks about the proposed changes api-wise.

**Comment by clintongormley** [comment]
The `_cluster/stats` API provides a summary (the details can be checked in the nodes-info API), so I think the right thing to do here is to report how many nodes there are in each role, eg:

    "total": 8,
    "master": 3,
    "data": 5,
    "ingest": 2,
    ....

I don't think we should return combinations like `master_data` as those will just explode as we add more roles.  The only weird one is "how many nodes are there that act only as clients" (because all nodes can act as clients).  Perhaps this can be represented with `client_only`

> I tend to find the node.client setting confusing and hard to handle internally at this point, maybe we could keep the setting but make it a shortcut to what it needs to be internally?

I agree - easier than setting 3, 4, ... N other default roles to false.

> We need to be careful with node attributes as they don't have their own namespace as part of settings, so we should be careful that if somebody specifies node.client we fail and we don't treat it as a node attribute (or take the chance to give node attributes their namespace).

Node attributes should really be moved into their own namespace so that we can be strict about settings, otherwise we're just guessing.

**Comment by javanna** [comment]
On keeping `node.client` as a shortcut, I thought more about it and it may make things even more confusing, cause then people will have a setting in their configuration that is not in their final settings. And still people will keep on wondering "does client:true mean ingest:false or not?", note that at the moment a node client is an ingest node unless `node.ingest` is set to `false`, which is right or wrong depending on how you ask :) Being explicit seems the best way to remove ambiguity. I think the best way to go is to reject `node.client` with an error at startup. Would you agree @clintongormley ?

On the combinations, I follow your reasoning, but I am afraid that `master_only`, `ingest_only`, `data_only` and `coordinating_only` (I would get rid of the client terminology) may come in handy to have a quick overview, otherwise the summary may become less useful, especially with many nodes and multiple roles. Shall we maybe have these 4 plus the totals as you mentioned? Just throwing it out there, not sure it's a great idea though.

**Comment by rjernst** [comment]
> Node attributes should really be moved into their own namespace so that we can be strict about settings, otherwise we're just guessing.

I agree that node attributes should have their own namespace, but I also think that continuing to have confusing settings/semantics for node roles, instead of renaming/changing semantics, only hurts users. the argument I have heard supporting a need for keeping the old names is always "but there are so many users/articles out there that know/use this name". My counter argument is as users continue to grow, new users should not be forced into confusion by antiquated naming. We should always strive to rename things when appropriate to help the new users, and at the same time find ways to help old users migrate (eg forcing functions like failing on startup with old names, with helpful error messages).

I remember two discussions before about node "roles" that I will summarize here.  The first is having a single `node.roles` setting, which is an array of the allowed roles on a node.  For example, having `node.roles: ["master_eligible", "data", "coordinating"]`. This would make it very clear, in a single setting, all the roles the node can play in the cluster. The other idea was about being explicit with the combinations that are allowed. For example, `node.type: "master_data_coordinating"`. The problem with this was the explosion of combinations as new node types are added, but I included it here for completeness.

**Comment by javanna** [comment]
No need to discuss the node attributes problem here, everybody agrees, we will address it in a followup PR, my comment was to remember that we have to take those into account if we want to remove node.client or client will become a node attribute which is bad.

I think we should make baby steps and get rid of `node.client` that is confusing, especially since we have ingest nodes too. I would love to move forward solving the problem reported here, as I said I have an upcoming PR and the main issue was what to do with cluster stats api, which @clintongormley replied to. We can reason about renaming etc. later I think. PR coming tomorrow :)
