### ISSUE TITLE
No documentation on what stopwords are in each set

### ISSUE THREAD

**Issue by soaxelbrooke** [elastic/elasticsearch#16561]
For instance, there is no documentation of what words are in the `_english_` stop words set.

**Comment by clintongormley** [comment]
Yeah, I've tried to put together a list before, but they're quite difficult to round up in Lucene.

**Comment by hjc1710** [comment]
I can certainly confirm that these are quite hard to round up. We had a client demand the list for all stop words we were using for every language configured. [Here](https://gist.github.com/hjc1710/6f0aa01bb436249ab3c6) is a quick description on what it took for me to find, and prove, that the list of stop words that ES is using come from `org.apache.lucene.analysis.snowball` and where to find the files. As you can see, it wasn't fun.

Maybe this is something I can take if I have some free time? Seems like a great beginner ticket and I have experience doing this already!

**Comment by clintongormley** [comment]
@hjc1710 please do - would be great to have this info in the docs

**Comment by ppf2** [comment]
https://github.com/apache/lucene-solr/tree/master/lucene/analysis/common/src/resources/org/apache/lucene/analysis/snowball

**Comment by debadair** [comment]
We should link to the Lucene docs.

**Comment by jrodewig** [comment]
[docs issue triage]

leaving open as this is still relevant.

**Comment by ScottieL** [comment]
Hi, I am a beginner who is looking to contribute. This issue seems fairly straightforward. From what I have looked at so far, it seems like the stop words are coming from a combination of different sources such as lucene snowball and the IR Multilingual Resources at UniNE.


 [french](https://github.com/apache/lucene-solr/blob/2e1a470c90e9293a42160280c5c39afb33bb5db0/lucene/analysis/common/src/java/org/apache/lucene/analysis/fr/FrenchAnalyzer.java#L82)

[arabic](https://github.com/apache/lucene-solr/blob/2e1a470c90e9293a42160280c5c39afb33bb5db0/lucene/analysis/common/src/java/org/apache/lucene/analysis/ar/ArabicAnalyzer.java#L57)
 

I can go ahead and look through all the languages and start compiling a list of words. I have uploaded an example of the arabic stopwords. I cannot obtain a translation for them, but can work towards it. I figured getting a list of all the language's stopwords would be a better first step. Hopefully I am on the right track. Please review the attached file and let me know if this format would satisfy documentation efforts.

[arabic_stop.txt](https://github.com/elastic/elasticsearch/files/3703862/arabic_stop.txt)

**Comment by jrodewig** [comment]
@ScottieL  Thanks for offering to contribute. Please feel free to open a PR.

As @debadair previously mentioned, I believe that linking to the stop word source will be sufficient. I don't think we need to translate them or necessarily include them verbatim in the Elasticsearch docs.

This will let us point users to the stopwords without getting out of sync.
