### ISSUE TITLE
Restore should check disk availability

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#16564]
Currently, restoring from a snapshot can lead to running out of disk space because it does not check the amount of available space on nodes before executing.

We should check for available disk space before attempting to restore.

**Comment by BlureX** [comment]
Hi there, I'm new to this project and would like to try fix this issue.

**Comment by ywelsch** [comment]
This feature request is interesting but since its opening we have not seen enough feedback that it is a feature we should pursue. We prefer to close this issue as a clear indication that we are not going to work on this at this time. We are always open to reconsidering this in the future based on compelling feedback; despite this issue being closed please feel free to leave feedback on the proposal (including +1s).
