### ISSUE TITLE
Potential NullPointerException in class org.elasticsearch.action.index.IndexRequest

### ISSUE THREAD

**Issue by simonbrandhof** [elastic/elasticsearch#16596]
The [line 649](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/action/index/IndexRequest.java#L649) is:
```
timestamp = MappingMetaData.Timestamp.parseStringTimestamp(defaultTimestamp, mappingMd.timestamp().dateTimeFormatter(), getVersion(metaData, concreteIndex));
```
Here the variable mappingMd can be `null`, so `mappingMd.timestamp()` can raise a NPE.
I don't know in which context this case can occur, but still there's a potential bug here.

Regards

**Comment by jasontedor** [comment]
First, I think that you meant to refer to [line 629](https://github.com/elastic/elasticsearch/blob/cca611171c53254b74f2da7239e05177fec92b1d/core/src/main/java/org/elasticsearch/action/index/IndexRequest.java#L629).

More importantly, there's no issue here but it's not straightforward why. Here's the relevant block of code.

```java
617  String defaultTimestamp = TimestampFieldMapper.Defaults.DEFAULT_TIMESTAMP;
618  if (mappingMd != null && mappingMd.timestamp() != null) {
619    // If we explicitly ask to reject null timestamp
620    if (mappingMd.timestamp().ignoreMissing() != null && mappingMd.timestamp().ignoreMissing() == false) {
621      throw new TimestampParsingException("timestamp is required by mapping");
622    }
623    defaultTimestamp = mappingMd.timestamp().defaultTimestamp();
624  }
625
626  if (defaultTimestamp.equals(TimestampFieldMapper.Defaults.DEFAULT_TIMESTAMP)) {
627    timestamp = Long.toString(System.currentTimeMillis());
628  } else {
629    timestamp = MappingMetaData.Timestamp.parseStringTimestamp(defaultTimestamp, mappingMd.timestamp().dateTimeFormatter(), getVersion(metaData, concreteIndex));
630  }
```

The else block can only be hit if `defaultTimestamp` is not equal to `TimestampFieldMapper.Default.DEFAULT_TIMESTAMP`. But on [line 617](https://github.com/elastic/elasticsearch/blob/cca611171c53254b74f2da7239e05177fec92b1d/core/src/main/java/org/elasticsearch/action/index/IndexRequest.java#L617) it is initialized to have that value. That value is changed from the default on [line 623](https://github.com/elastic/elasticsearch/blob/cca611171c53254b74f2da7239e05177fec92b1d/core/src/main/java/org/elasticsearch/action/index/IndexRequest.java#L623), but that only occurs if `mappingMd != null` (from the condition on [line 618](https://github.com/elastic/elasticsearch/blob/cca611171c53254b74f2da7239e05177fec92b1d/core/src/main/java/org/elasticsearch/action/index/IndexRequest.java#L618)). Thus, if the `else` block in question is hit, it is guaranteed that `mappingMd` is not null. However, it's possible that `mappingMd.timestamp().defaultTimestamp()` is equal to `TimestampFieldMapper.Defaults.DEFAULT_TIMESTAMP` and that's why the code is written this way.

I'll push a commit that has an assert that `mappingMd` is not null here, and that should keep your IDE or static analysis tool from complaining. :)
