### ISSUE TITLE
Performing derivatives on arbitrary aggregations. 

### ISSUE THREAD

**Issue by kennycason** [elastic/elasticsearch#16593]
I was looking into implementing the derivative pipeline into our aggregations. 
For example, we may return a sum aggregation of numeric type (post likes) that has been segmented previously by a string type (channel, fb/twitter/etc). Also specifically in our case they were bucketed under a date_range aggregation.

I noticed that derivatives could only be provided if parent aggregation was a histogram or a date histogram. Is there any plan or desire to support derivatives (and other pipeline metrics for the general case of numeric aggregations? I'm guessing there would also be some work around the gap policy.

I also noticed an issue with parsing the bucket path when i have an aggregation with a name containing a "." (like I have below), I was able to fix that by just renaming to "_"

sample query where i'd like to have derivatives for:
`"sum":{  "field":"post.likes_count" }`
the request:

``` json
{  
   "aggregations":{  
      "date_range_buckets":{  
         "date_range":{  
            "field":"post.creation_date",
            "ranges":[  
               {  
                  "from":"2015-12-15T00:00:00.000Z",
                  "to":"2015-12-21T00:00:00.000Z"
               },
               {  
                  "from":"2015-12-21T00:00:00.000Z",
                  "to":"2016-01-01T00:00:00.000Z"
               }
            ]
         },
         "aggregations":{  
              "channel":{  
                   "terms":{  
                      "field":"internal.channel"
                   },
                   "aggregations":{  
                      "post_likes_count":{  
                         "sum":{  
                            "field":"post.likes_count"
                         }
                      }
                   }
               }
         }
      }
   },
   "size": 0
}
```

Thanks, let me know if i'm just missing something obvious. :)

**Comment by polyfractal** [comment]
Hmm, do you just want the "total" derivative of the summed `like_count` between the two different ranges?  Or do you want to see the derivative between each term in the ranges?

The first is doable by using a `sum_bucket` agg to accumulate all the `like_count` for a single range, then a derivative over that sum:

```json
{
   "aggregations": {
      "date_range_buckets": {
         "date_histogram": {
            "field": "creation_date",
            "interval": "day"
         },
         "aggregations": {
            "channel": {
               "terms": {
                  "field": "channel"
               },
               "aggregations": {
                  "post_likes_count": {
                     "sum": {
                        "field": "likes_count"
                     }
                  }
               }
            },
            "sum_of_likes": {
               "sum_bucket": {
                  "buckets_path": "channel>post_likes_count.value"
               }
            },
            "deriv": {
               "derivative": {
                  "buckets_path": "sum_of_likes"
               }
            }
         }
      }
   },
   "size": 0
}
```

The second option is not currently possible...the pipeline aggs don't really play nicely with terms aggs at the moment.  We dont have any syntax to "path" into a specific term, and the aggs don't know how to "link up" matching terms between different ranges. 

We've definitely talked about this type of functionality before.  Unsure where we left off, it might be pending some refactoring.  @colings86 thoughts?

**Comment by kennycason** [comment]
I admittedly probably made the example more complicated by adding in multiple date ranges. :) Thanks for the response!

When you said "the pipeline aggs don't really play nicely with terms aggs at the moment." - That was the primary point of interest for me, the ability to do pipeline metrics on any aggregation (or at least terms aggs) and not just on the histogram aggregations. 

As it stands now, I am building a generic metrics pipeline that functions on an Elasticsearch response for our api. i.e. given an Elasticsearch response, and a list of fields & desired metrics (derivative/avg/etc), apply it to the response before returning to user. Fortunately the calculations aren't super complex but I found my code getting a bit more complex when I started trying to implement my own "gap policy" before applying my own pipeline.

**Comment by yaauie** [comment]
`date_range` aggregation shares a property with `date_histogram` aggs, which may make them suitable for derivative aggregations, specifically that the ordering of the buckets is meaningful (so long as one doesn't completely encompass another), therefore the pipeline has enough information to provide the derivative. Given a `date_range` agg, it would be very useful to apply derivative in order to support period-over-period comparisons for arbitrary periods (as opposed to the set of pre-defined periods that `date_range` aggs make possible).

**Comment by kennycason** [comment]
@yaauie that's a good point on the ordering and something that makes our case a bit different is that we have nested term aggregations, then for each of the buckets we perform sub aggregations like sum/average, or just use count. those are all numerical values that we then use to sort our buckets THEN we manually apply the derivative pipeline.

**Comment by polyfractal** [comment]
Revisiting this ticket, it seems there are two related issues here:

1. Allow "pathing" through terms aggregations, either by providing some kind of syntax to specify a term (`foo>bar['my_term']>the_sum.value`), or by adding logic so the pipeline aggs know how to "link" up values between terms aggs (`foo>bar>the_sum.value` and it knows to grab the different `the_sum` values from each term)
2. Extend derivatives and related aggs to work with Ranges, since they provide some semblance of ordering

The second point seems like an easy win.  The first point (which is the meat of the request in this issue) is a lot more difficult, because there are a lot of funky edge-cases to handle (what happens if some values are missing in different term partitions?  How do you handle multi-nested terms? etc etc)

**Comment by polyfractal** [comment]
We chatted about this in our Search meeting.

1. We don't see this functionality being implemented any time soon, because it is very complicated to deal with all the edge-cases and in some cases it isn't clear how they would be handled.  We may implement it at some point in the future, but not in the near-term.
2. Extending pipeline aggs to work with Ranges (date and regular) is something that we should talk more about.  There are also interesting edge-cases there too (how to deal with gaps, etc) but it seems a more tractable problem.  I'll open a dedicated issue to discuss this feature request.

Going to close this ticket for now.  Just because we're closing doesn't mean we won't implement the functionality in the future... we just want to signal it's not something we're working on now.  Thanks!
