### ISSUE TITLE
Evaluate the replacement of the scroll API with search_after

### ISSUE THREAD

**Issue by jimferenczi** [elastic/elasticsearch#16631]
The scroll API is widely used for a lot of use cases (Map/Reduce, reindex, delete by query, ...). 
The performance is great but there are some limitations that IMO are difficult to handle: 
* The scroll API is using a `snapshot` of the index, if the scroll takes a long time a lot of resources are consumed (and kept) just for the scroll.

* The scroll is always bounded to one replica per shard, this means that there is no way to spread the load among the available replicas for one shard. 

Now that we added the support for `search_after` (https://github.com/elastic/elasticsearch/issues/8192) we could evaluate the cost of using this feature instead of the scroll. 
There is no context attached to a `search_after` request, this means that we can use the newest searcher on each sub-query but also that each sub-query could run on any available replicas. 
The downside of this approach is the need to use a tiebreaker for the sort (the scroll API is using the internal Lucene docid for this). The best tiebreaker we could think of is the _uid because we are sure that it has a unique value per document. Though the cost of sorting on _uid is big (see https://github.com/elastic/elasticsearch/issues/11887).
IMO I don't think that we should use docvalues but  rather rely on the fielddata because it can be used lazily (we pay the cost of having the _uid in fieldata but only when there is a scroll request running and we can easily remove it when we are done).

**Comment by nik9000** [comment]
> The scroll API is using a snapshot of the index, if the scroll takes a long time a lot of resources are consumed (and kept) just for the scroll.

Losing the "snapshot" behavior in reindex would certainly be a change. It'd be really nice not to have to worry about the snapshot disappearing out from under you though.

**Comment by bleskes** [comment]
There are some more things to consider here:

 - currently we guarantee a point in time snapshot, which also means we never return the same document twice. For arbitrary sort orders, you can even drop a document. That's something we can stop supporting, but at I don't see how we can do it without using lucene's snapshots. 

- the biggest user of the scroll API is the scan search type - there we by design have no order but the one on disk. If we change our merge policies to honor some ordering we could change that, but for now I would expect a big penalty hit to the scan search if we sort as well.

**Comment by javanna** [comment]
Another aspect is in terms of usability, the snapshot makes sure that no changes will be returned in case indexing is happening while scrolling. Even sorting by `_uid` depending on the id of documents and where are with the scroll, new documents might be returned or not. Maybe that turns out not to be a big deal, but seems like a big change at first glance.

**Comment by jimferenczi** [comment]
> the biggest user of the scroll API is the scan search type - there we by design have no order but the one on disk. If we change our merge policies to honor some ordering we could change that, but for now I would expect a big penalty hit to the scan search if we sort as well.

Yes and it's amplified now that the scroll is using a MinDocQuery and terminateAfter when sorting on Lucene docids only:
https://github.com/elastic/elasticsearch/pull/12983
So yeah speed matters and `search_after` is not ready for this kind of speed. I ran some tests and the difference can be huge. 
I completely missed the MinDocQuery thing which is brilliant and hard to beat.
I'll close it until we find a way to achieve the same speed without snapshot ;).
