### ISSUE TITLE
Took time for index requests ?

### ISSUE THREAD

**Issue by rdigiorgio** [elastic/elasticsearch#16641]
As of now, and AFAIK, the only way to know if a query exceeded a certain time threshold to process is enabling slow logs. Why does IndexResponse simply not include a took time ? 

We are sending indexing bulk requests to our cluster for real-time analytics and we would just want to know, if a bulk was slow to process, which one of the queries it included took a long time to execute immediately in our application, as it slows down our entire bulk request.

**Comment by nik9000** [comment]
> Why does IndexResponse simply not include a took time ?

I think it'd be safe to just add it. I'm marking this as something that should be easy for a new contributor because my gut says it should be.

**Comment by rdigiorgio** [comment]
By the way, it also involves updating BulkItemResponse, which should also include the took time.

**Comment by jasontedor** [comment]
> I'm marking this as something that should be easy for a new contributor because my gut says it should be.

@nik9000 Something to keep in mind is that the hard part here is going to be writing tests.

**Comment by dakrone** [comment]
This feature request is an interesting idea but since its opening we have
not seen enough feedback that it is a feature we should pursue. We prefer
to close this issue as a clear indication that we are not going to work on
this at this time. We are always open to reconsidering this in the future
based on compelling feedback; despite this issue being closed please feel
free to leave feedback on the proposal (including +1s).

**Comment by itaydvir** [comment]
+1 (please add Took time for IndexResponse)
