### ISSUE TITLE
Indexed scripts should be stored in cluster state

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#16651]
Indexed scripts are now stored in a dedicated index. Moving indexed scripts to the cluster state will make the indexed script logic much simpler. We already have dedicated indexed script APIs in place so this shouldn't be too difficult.

When developing this we should think about bwc too, we can the first time we start ES after a full cluster restart decide to copy the scripts from the dedicated index into the cluster state, if we see there is a script index, but no scripts are in the cluster state.

Also we should then maybe rename indexed scripts, to stored scripts or something like that.

**Comment by rjernst** [comment]
+1

**Comment by uboness** [comment]
+1 as well...

this will also be a great opportunity to differentiate between scripts & template (today we treat templates as scripts, while they are two different beasts... specially with template needing a context of escaping)

> When developing this we should think about bwc too, we can the first time we start ES after a full cluster restart decide to copy the scripts from the dedicated index into the cluster state, if we see there is a script index, but no scripts are in the cluster state.

would be great if we do this for 3.0 and instead of having this migration done automatically, I think it's better to provide a tool that will do that as part of the 2.x->3.0 migration path.

> Also we should then maybe rename indexed scripts, to stored scripts or something like that.

+1

**Comment by clintongormley** [comment]
Related to #14837 
Related to #13729

**Comment by martijnvg** [comment]
> I think it's better to provide a tool that will do that as part of the 2.x->3.0 migration path.

+1 this is much simpler to develop and maintain.
