### ISSUE TITLE
TransportNodesAction: Getting stats from all nodes via client node does not work

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#16815]
So, I am not sure if this is a feature or a bug, but we may want to discuss this. if you try to get node stats from a client node and other client nodes are part of the cluster, then the stats will only contain stats from this client node and all master and data nodes.

The reason for this is in `TransportNodesAction`, where we check, if the code where this is executed on is a client node as well as the receiving node, see [here](https://github.com/elastic/elasticsearch/blob/99a7d8e41f4a0dfa14f64d9b9d080626c558c5e3/core/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java#L161-L165)

I understand that this is intentional in the TransportNodesAction, but there might be actions, where we actually want to allow this (clearing caches i.e.)

**Comment by javanna** [comment]
thanks for opening this @spinscale I had the same on my list to open. I stumbled upon it while working on #16565, cluster stats node counts are off due to this depending on which node the request hit, in case you have client nodes in your cluster.  Also related to #3617 and most likely affects other apis too.

Note also that this will happen only if `node.client` is set to true, not in case `node.master` and `node.data` are both set to false, which I am fixing as part of my upcoming PR for #16565...so while removing the `node.client` setting the question is: should the `shouldConnectTo` method be adapted or go away?

**Comment by bleskes** [comment]
>  should the shouldConnectTo method be adapted or go away?

Imo this check stems from seeing Client nodes as a client and expecting many of them (possibly hundreds ). This meant that not connecting them will save something significant. It was OK to do because for all *data* related requests we will never send something from one client node to another. The downside is of course that things like Nodes  Stats and nodes info do not report them.  Since we are moving away from client nodes  we should just keep things simple and connect every node to every node.

**Comment by clintongormley** [comment]
Related to https://github.com/elastic/elasticsearch/issues/16105

**Comment by javanna** [comment]
Did some digging around this, this seems to affect the following apis:
- nodes info (missing client nodes)
- nodes stats (missing client nodes)
- nodes hot threads (missing client nodes)
- cluster stats apis (nodes count off, both total and client count)

The issue manifests if you have two or more clients nodes in your cluster and you call any of the above api hitting directly one of the clients nodes. When the client node acts as a coordinating node it cannot connect to other clients nodes hence the other client nodes are skipped.

**Comment by javanna** [comment]
Closed via #16898.
