### ISSUE TITLE
Use `mmapfs` by default

### ISSUE THREAD

**Issue by mikemccand** [elastic/elasticsearch#16983]
ES today has a default directory implementation which switches based on file extension, only using `mmapfs` for files that Lucene does heavy random access on (terms dict, doc values) and `niofs` otherwise.

But unfortunately, for compound files (`.cfs`), which I suspect are often the majority of segments, especially for  large shards, it still uses `niofs`, hurting performance when we do random access on the sub-files within those.

ES used to have issues with segment explosion, which I think contributed to wanting to reduce the mmap count, but we've fixed those, and cfs is now enabled by default, so I think the performance hit of using the inferior `niofs` on compound file segments is the wrong tradeoff.

We could alternatively keep the current "switching" directory, but for `.cfs` extension use `mmapfs`.

**Comment by uschindler** [comment]
Strong +1 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

This hybrid one is horrible, sorry. It is just caused by some rare customers misusing their cluster. In addition, it goes back to the time when Lucene showed the crazy OOM when mapping failed (which is/was a Java bug). We fixed this so mmap failed now throws an IOException as you would expect.

**Comment by bleskes** [comment]
I'm wondering if something has changed since we last evaluated and explicitly decided to not put cfs files under mmap - see discussion on https://github.com/elastic/elasticsearch/pull/6636

**Comment by mikemccand** [comment]
I think way back then we had problems with "segment explosion" (e.g. index throttling was only just added when that issue was created, there were settings to turn off merging, etc.).

We also didn't use Lucene's defaults for CFS, I think, so a shard could have lots of small files.

Shards today should have fewer segments, should be more often CFS, and shouldn't run up against the "too many memory maps" very easily.
