### ISSUE TITLE
Improve performance when retrieving only IDs

### ISSUE THREAD

**Issue by sledgebox** [elastic/elasticsearch#16996]
It would be nice if there were an API that would optimize for retrieving all IDs(only) of search results. It may be nice for a lot of reasons, but here's a good example. It would allow users to scroll to the bottom of a huge list (assuming the IDs have been cached after the original call) like in this example.
http://demos.telerik.com/kendo-ui/grid/virtualization-remote-data

Also, it would hopefully not go through the scroll API and could be just one constant download streamed to the requester. 

Another thing, can there be support for a non-json response type, something that can deserialize as fast as a DB reader?

**Comment by clintongormley** [comment]
@sledgebox returning all the results (ids or otherwise) in a single request where "all" is a large number is very costly in a distributed system, so we won't provide an API to do that.  

I don't really understand your use case, but I think you may find the new [search_after](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-request-search-after.html) functionality useful (coming in 5.0)

As far as returning just the IDs, try this:

    GET _search?_source==false&filter_path=hits.hits._id

> Another thing, can there be support for a non-json response type, something that can deserialize as fast as a DB reader?

We won't be providing another response encoding.  Perhaps you need to look for a faster JSON library, or try out the CBOR encoding instead.

**Comment by sledgebox** [comment]
Search_after does look useful. Is it not shorthand for something that could be done with query logic? When does 5.0 release? Can you point me to a roadmap?

I don't understand why returning all results is very costly. Can you provide a link explaining? Is it more costly than scrolling all? 

Thanks, so much.
