### ISSUE TITLE
Running exec command from an ES 2.2 plugin

### ISSUE THREAD

**Issue by steccami** [elastic/elasticsearch#17052]
Hi all,
I'm trying to execute this line of code from an ES 2.2 plugin. 

Process p = Runtime.getRuntime().exec("java -jar test.jar");

but I keep getting this error: 

java.io.IOException: Cannot run program "java": error=13, Permission denied
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
        at java.lang.Runtime.exec(Runtime.java:617)
        at java.lang.Runtime.exec(Runtime.java:450)
        at java.lang.Runtime.exec(Runtime.java:347)
...
Caused by: java.io.IOException: error=13, Permission denied
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:187)
        at java.lang.ProcessImpl.start(ProcessImpl.java:130)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)

I added this line 
 permission java.security.AllPermission;
to the java.policy file but it does not work. 

I'm running ES 2.2 on the following JVM:

java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

I also tried the following code: 

AccessController.doPrivileged() 

as suggested here (https://www.elastic.co/guide/en/elasticsearch/plugins/current/plugin-authors.html) but still nothing.

Thanks in advance for your help.

Regards

**Comment by nik9000** [comment]
This is caused by seccomp/seatbelt. Forking is not allowed from Elasticsearch for security reasons. This is another layer on top of java security provided by the OS and we don't have a way to shut it off. Well, the version you are working with might. There was a -D parameter you could use to disable it iirc but we've removed it and I don't remember if it is in 2.2.

If you really really really really must run an external process you are going to need to communicate with some process outside of Elasticsearch that hasn't dropped its forking permissions.

**Comment by steccami** [comment]
Ok, tnx a lot! 
BTW I've already implemented a workaround based on REST APIs ;-)

Cheers
