### ISSUE TITLE
Context and headers are not copied when registering percolator queries

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#17071]
This comes from a user report on [discuss](https://discuss.elastic.co/t/shield-authorization-exception-percolation-and-indexed-shapes/43928).

When registering a percolator query (by indexing a document with type `.percolator`) that uses a query with indexed values, the headers and context are not carried over to the request used to get the indexed values. One example of this is a geo shape query that uses an indexed shape. Looking at the `GeoShapeQueryParser`, the code expects that it can get the context and headers from the `SearchContext`, but there is no `SearchContext` when the query is being parsed by the `PercolatorQueriesRegistry`.

I've confirmed the behavior on `2.x` and confirmed that the behavior is fixed in master by #15776, but this change is not something we should try to backport.

**Comment by martijnvg** [comment]
The bigger problem here is when the the document in the shape index changes. There is no mechanism that updates the percolator query. I think this is problematic. It is even more problematic in master as there upon indexing the percolator extracts query metadata from the query and stores that with query, so that at percolate time the percolator can be smart about what queries need to be evaluated. So in master the query would really need to be reindexed.

The percolator should not accept queries that fetch data via a get request. That not only applies for the `qeo_shape` query, but also for `terms` and `template` queries. These queries should only be allowed in the percolator if the data (terms, shapes and scripts) are defined inline.

**Comment by clintongormley** [comment]
@s1monw was working on a change to inline these items when indexing the percolator query, so eg a reference to an indexed geoshape would be expanded into the full geoshape at query index time.  Not sure where he got to with it.

**Comment by martijnvg** [comment]
@clintongormley I think what @s1monw meant with, is that instead of caching Lucene queries we cache our own query builders, which at query time are then rewritten to Lucene queries. In case of the `geo_shape` query this would mean that we fetch the shape at query time instead of index time. This would fix the problem in ES < 5.0, however from 5.0 we also during indexing store the query terms for certain percolator queries to speed up execution and in order for this to happen the percolator needs to be rewritten to a Lucene query at index time. This isn't necessarily a problem for the `geo_shape` query since the query terms extract logic hasn't been implemented (yet), but it is a problem for the `terms` query.

I think there are two options here:
* Never do the extract query terms optimisation if a percolator query needs to fetch additional data via a get request.
* The percolator should disallow queries that have been set to execute a get call to fetch terms, shapes etc.

Maybe we should go with option 1, it kind of nice to support these kind of queries in the percolator. For this I do need to update the percolator refactor PR (#16349), since I kind of assumed option 2.

**Comment by clintongormley** [comment]
@martijnvg Having percolator queries that do lookups of data like terms or geoshapes is misleading, as it leads the user to assume that changing the indexed terms/geoshape will automatically update the percolator, which isn't the case.  Plus percolator instantiation can fail if the index holding the remote data isn't available.

I'd go for one of two options:

* Disallow lookup clauses in percolator queries
* Do the lookup at index time and replace the index/type/id with the inlined data

The only thing against the second option is that we don't change the `_source` anywhere else (other than the update API and now the ingest API), so it might be surprising.  Probably OK though.

**Comment by s1monw** [comment]
in order to do the lookup at index time we have to either modify the source or store the rewritten query in a secondary field that we use to parse the query after we indexed it. Today we are using the soruce which is the original query. I think we can easily add a stored field that holds the rewritten one and that way we can also easily upgrade the once indexed before 5.x?

**Comment by martijnvg** [comment]
@s1monw How would that work with the terms we extract in the `PercolatorFieldMapper` and use that to not evaluate percolator queries at search time? 

Also if the remote document changes, then how would the percolator query be updated?

**Comment by s1monw** [comment]
@martijnvg here is some pseudo-code for `PercolatorFieldMapper`

```Java

@Override
    public Mapper parse(ParseContext context) throws IOException {
        QueryBuilder queryBuilder = PercolatorQueriesRegistry.parseQueryBuilder(queryShardContext);
        queryBuilder = QueryBuilder.rewrite(queryBuilder, queryShardContext); // fetch the shape etc.
        byte[] queryAsBytes =  queryBuilder.toXContent();
        context.doc.addField("query_field", queryAsBytes)
        Query luceneQuery = queryBuilder.toQuery()
        ExtractQueryTermsService.extractQueryTerms(luceneQuery, context);
        return null;
    }
```

Ideally we would apply this to the source, parse, rewrite, regenerate source and only do it once!

**Comment by s1monw** [comment]
With ingest we could maybe do that?

**Comment by martijnvg** [comment]
@s1monw This is an Interesting approach! But I still don't understand how we would deal with updates in the remote document. (for example the document that holds the shape for `geo_shape` query)

> Ideally we would apply this to the source, parse, rewrite, regenerate source and only do it once!

You mean on the coordination node? If we did this there then it would mean we would need to load IndexService on the fly. (in cases a node doesn't have any shard for that index)

> With ingest we could maybe do that?

If we do this then instead of ingest I prefer to have a dedicated put query api. The reason that we then don't have to parse the entire source to a map of maps. Instead we can stream parse the query bit out of it and add back as a top level field in the source.

**Comment by s1monw** [comment]
> This is an Interesting approach! But I still don't understand how we would deal with updates in the remote document. (for example the document that holds the shape for geo_shape query)

that's not supported - that's the entire point. We have to resolve it once the request comes in, rewrite the source and forward that source to the replicas. Anything else is just not supported.

**Comment by s1monw** [comment]
> If we do this then instead of ingest I prefer to have a dedicated put query api. The reason that we then don't have to parse the entire source to a map of maps. Instead we can stream parse the query bit out of it and add back as a top level field in the source.

what are you concerned about here? if ingest is not capable of doing this why would be release it at all?

**Comment by martijnvg** [comment]
> that's not supported - that's the entire point. We have to resolve it once the request comes in, rewrite the source and forward that source to the replicas. Anything else is just not supported.

Ok, I thought that this behaviour was expected, which I know we can't do. That is why my reaction was to just not support these queries... (this what happens now in #16349, see [second commit](https://github.com/elastic/elasticsearch/pull/16349/commits/34b0b65c91a32369f3cbc696f084534c5cdb4f86))

> what are you concerned about here? if ingest is not capable of doing this why would be release it at all?

I think ingest is capable of doing this, it is just that this whole map of maps conversion is't needed in the context of indexing a percolator query (but from a general ingest use case it does). I think we should make ingest a bit smarter, if we know a pipeline only adds top level fields then ingest doesn't need to do this map of maps conversion and simply appends its data to the binary source. There likely more optimisations that we can do, but just thinking out loud here.

But it does mean that ingest would need to create shard contexts on demand for indices that are not available on the local node.

I'll start with making the suggested change to the PercolatorFieldMapper in #16349, so that we already store queries in this format. As a followup issue we can then see how we can move this to ingest.

**Comment by s1monw** [comment]
> But it does mean that ingest would need to create shard contexts on demand for indices that are not available on the local node

no all you need is `QueryParseContext` and `QueryRewriteContext` you don't need the index locally.

**Comment by martijnvg** [comment]
> no, all you need is QueryParseContext and QueryRewriteContext you don't need the index locally.

ah wait, so you meant that only the rewrite should happen in ingest? I somehow thought that you also meant that the query extraction should happen in ingest.

**Comment by s1monw** [comment]
> ah wait, so you meant that only the rewrite should happen in ingest? I somehow thought that you also meant that the query extraction should happen in ingest.

yeah I was thinking about a dedicated ingest processor that also does the rewrite?

**Comment by martijnvg** [comment]
> yeah I was thinking about a dedicated ingest processor that also does the rewrite?

+1 for an ingest processor that does a query builder rewrite. 

In order to get the 'do query rewrite once' optimisation, creating a pipeline is then required, but that is something that can be documented.

**Comment by martijnvg** [comment]
The bug has been fixed and the potential follow up work that can be done has been described in #29053.
