### ISSUE TITLE
jq as response filter

### ISSUE THREAD

**Issue by kimchy** [elastic/elasticsearch#17115]
Just came across https://github.com/eiiches/jackson-jq, which is an implementation of jq (https://stedolan.github.io/jq/) using Jackson. I don't know about the quality of the implementation itself (looks like it has the "spec" tests embedded), but if it is good, it might be a good option for us to expose in a similar manner to filter path.

**Comment by kimchy** [comment]
looked at it a bit more, it seem like this requires full tree model representation of the output before it gets filtered, which is different compared to the "stream" filtering we do in filter path, so it will have memory implications.

**Comment by rashidkpc** [comment]
This would be amazing. Certainly has abuse implications, eg, using _search with a huge size to do aggregations, but would allow for some fantastic work arounds for less agreeable response structures. 

I'd love to have it, we might just need a sane limit on how big of an object could be loaded in the jq pipe.

**Comment by clintongormley** [comment]
We talked about this in Fix It Friday and some concerns were raised.

Elasticsearch is designed to return small representations of your data. Using something like jq may well lead to abuse of this by hiding the size/complexity of the response behind the jq layer, which can have a performance and memory impact.

We already have response filtering which is efficient and simple.  jq has a syntax which means potentially dealing with syntax errors (which probably means a different response from the one the user expects)

This processing can obviously be done client side.  Is the resistance to doing this on the client because of network bandwidth?  If so, perhaps the answer is to enable HTTP compression by default instead (something which we are going to investigate https://github.com/elastic/elasticsearch/issues/7309)

**Comment by kimchy** [comment]
I agree, this can be dangerous..., specifically with the amount of potential processing/memory it will require. Maybe we can have some examples of where this can be handy to begin with captured in this issue.

**Comment by TheFrozenFire** [comment]
I've been looking for exactly this sort of feature. My organization does a lot of data reporting right out of ES. Right now, I'm having to maintain external tooling which queries ES and then runs the response through jq to produce the report format I need (such as converting to CSV).

I would envision this being implemented as an addition script type like mustache, groovy, and painless. One could specify a jq filter script inline, indexed, or from a file. The jq filter could be passed as a response filter, which would be executed by the coordinating node to process the response body accordingly.

I think that such functionality would come with the explicit instruction that when used, the response body becomes unpredictable and possibly non-JSON. As I don't use ES extensively, I admittedly don't know what the further-reaching implications of this would be. But, I don't see it as much different than having a load balancer in front of the coordinating nodes, and that balancer possibly returning unexpected output to HTTP requests.

**Comment by nik9000** [comment]
I don't think we're likely to work on this in the near future. Maybe never, given the whole tree processing thing. I love jq and it'd be super fun to have an implementation of it available but I don't think it is worth it and I know it isn't worth it at this time.
