### ISSUE TITLE
Transient and/or persistent threadpool index queue size configuration is not taken into account when updating them using the cluster update API.

### ISSUE THREAD

**Issue by petitout** [elastic/elasticsearch#17124]
**Elasticsearch version**: 1.7.5

**JVM version**: 1.8.0_66

**OS version**: CentOS Linux release 7.1.1503
Linux localhost 3.10.0-229.20.1.el7.x86_64

**Description of the problem including expected versus actual behavior**:

I've the following error when trying to delete a huge amount of documents :

```
....
"myIndexName": {
        "_shards": {
            "total": 1,
            "successful": 0,
            "failed": 1,
            "failures": [
                {
                    "index": "myIndexName",
                    "shard": 0,
                    "reason": "EsRejectedExecutionException[rejected execution (queue capacity 100) on org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase$1@4d215e4]"
                }
            ]
        }
    }
....
```

I know what this error means so I tried to execute the following command to resolve the issue :

```
curl -XPUT localhost:9200/_cluster/settings -d '{"transient" : {"threadpool.index.queue_size":500}, "persistent": {"threadpool.index.queue_size":500} }'
```

and I got the following response :
```
{"acknowledged":true,"persistent":{"threadpool":{"index":{"queue_size":"500"}}},"transient":{"threadpool":{"index":{"queue_size":"500"}}}}
```

But unfortunately when trying to delete again the documents, I still get the exact same error.

Then I manually updated elasticsearch.yml to add the following line :

```
...
threadpool.index.queue_size: 500
...
```

I restarted elasticsearch and the delete query was working fine.

**Steps to reproduce**:
 1. manage to get a "EsRejectedExecutionException" error when indexing or deleting documents (you may do it by voluntarily set a very small threadpool.index.queue_size value in the configuration file)
 2. Update this threadpool.index.queue_size using the cluster update api :
```
curl -XPUT localhost:9200/_cluster/settings -d '{"transient" : {"threadpool.index.queue_size":500}, "persistent": {"threadpool.index.queue_size":500} }'
```
 3. try to index or delete the documents again

**Provide logs (if relevant)**:
No error in logs only this logs appear when executing the cluster update query :
```
[2016-03-15 15:09:52,234][DEBUG][cluster.service          ] [Living Monolith] processing [cluster_update_settings]: execute
[2016-03-15 15:09:52,240][DEBUG][cluster.service          ] [Living Monolith] cluster state updated, version [343], source [cluster_update_settings]
[2016-03-15 15:09:52,240][DEBUG][cluster.service          ] [Living Monolith] publishing cluster state version 343
[2016-03-15 15:09:52,240][DEBUG][cluster.service          ] [Living Monolith] set local cluster state to version 343
[2016-03-15 15:09:52,250][DEBUG][river.cluster            ] [Living Monolith] processing [reroute_rivers_node_changed]: execute
[2016-03-15 15:09:52,250][DEBUG][river.cluster            ] [Living Monolith] processing [reroute_rivers_node_changed]: no change in cluster_state
[2016-03-15 15:09:52,253][DEBUG][cluster.service          ] [Living Monolith] processing [cluster_update_settings]: took 19ms done applying updated cluster_state (version: 343)
[2016-03-15 15:09:52,254][DEBUG][cluster.service          ] [Living Monolith] processing [reroute_after_cluster_update_settings]: execute
[2016-03-15 15:09:52,256][DEBUG][cluster.service          ] [Living Monolith] processing [reroute_after_cluster_update_settings]: took 2ms no change in cluster_state
```

**Comment by jasontedor** [comment]
There are unit tests in place that verify that modifying these settings works as expected, and I am unable to reproduce. Against a fresh 1.7.5 node:

```bash
19:30:20 [jason:~] $ curl -XGET localhost:9200/
{
  "status" : 200,
  "name" : "Crimson Dynamo V",
  "cluster_name" : "elasticsearch_jason",
  "version" : {
    "number" : "1.7.5",
    "build_hash" : "00f95f4ffca6de89d68b7ccaf80d148f1f70e4d4",
    "build_timestamp" : "2016-02-02T09:55:30Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
19:30:33 [jason:~] $ curl -XGET localhost:9200/_cat/thread_pool?h=index.queueSize
200
19:30:37 [jason:~] $ curl -XPUT localhost:9200/_cluster/settings?pretty=1 -d '{"transient" : {"threadpool.index.queue_size":500}, "persistent": {"threadpool.index.queue_size":500} }'
{
  "acknowledged" : true,
  "persistent" : {
    "threadpool" : {
      "index" : {
        "queue_size" : "500"
      }
    }
  },
  "transient" : {
    "threadpool" : {
      "index" : {
        "queue_size" : "500"
      }
    }
  }
}
19:30:40 [jason:~] $ curl -XGET localhost:9200/_cat/thread_pool?h=index.queueSize
500
```

Plus I see the logging statement:
```
[2016-03-15 19:30:37,222][DEBUG][threadpool               ] [Husk] creating thread_pool [index], type [fixed], size [8], queue_size [500]
```

which only happens if the thread pool is actually recreated to reflect the new queue size.

Do you possibly have other settings set here such as `threadpool.index.capacity` or `threadpool.index.queue`? It's crazy that we supported all of these, but either of those would override `thread pool.index.queue_size`.

Starting from a fresh 1.7.5 node again:

```bash
19:50:48 [jason:~] 7 $ curl -XGET localhost:9200/_cat/thread_pool?h=index.queueSize
200
19:51:08 [jason:~] $ curl -XPUT localhost:9200/_cluster/settings?pretty=1 -d '{"transient" : {"threadpool.index.capacity":500}, "persistent": {"threadpool.index.capacity":500} }'
{
  "acknowledged" : true,
  "persistent" : {
    "threadpool" : {
      "index" : {
        "capacity" : "500"
      }
    }
  },
  "transient" : {
    "threadpool" : {
      "index" : {
        "capacity" : "500"
      }
    }
  }
}
19:51:12 [jason:~] $ curl -XGET localhost:9200/_cat/thread_pool?h=index.queueSize
500
19:51:15 [jason:~] $ curl -XPUT localhost:9200/_cluster/settings?pretty=1 -d '{"transient" : {"threadpool.index.queue_size":200}, "persistent": {"threadpool.index.queue_size":200} }'
{
  "acknowledged" : true,
  "persistent" : {
    "threadpool" : {
      "index" : {
        "queue_size" : "200"
      }
    }
  },
  "transient" : {
    "threadpool" : {
      "index" : {
        "queue_size" : "200"
      }
    }
  }
}
19:51:37 [jason:~] $ curl -XGET localhost:9200/_cat/thread_pool?h=index.queueSize
500
```

showing that the `queue_size` setting has no effect after `capacity` is set. I note further that my logs match yours in this case:

```
[2016-03-15 19:51:37,497][DEBUG][cluster.service          ] [Aries] processing [cluster_update_settings]: execute
[2016-03-15 19:51:37,497][DEBUG][cluster.service          ] [Aries] cluster state updated, version [4], source [cluster_update_settings]
[2016-03-15 19:51:37,497][DEBUG][cluster.service          ] [Aries] publishing cluster state version 4
[2016-03-15 19:51:37,497][DEBUG][cluster.service          ] [Aries] set local cluster state to version 4
[2016-03-15 19:51:37,498][DEBUG][river.cluster            ] [Aries] processing [reroute_rivers_node_changed]: execute
[2016-03-15 19:51:37,498][DEBUG][river.cluster            ] [Aries] processing [reroute_rivers_node_changed]: no change in cluster_state
[2016-03-15 19:51:37,499][DEBUG][cluster.service          ] [Aries] processing [cluster_update_settings]: took 2ms done applying updated cluster_state (version: 4)
[2016-03-15 19:51:37,499][DEBUG][cluster.service          ] [Aries] processing [reroute_after_cluster_update_settings]: execute
[2016-03-15 19:51:37,499][DEBUG][cluster.service          ] [Aries] processing [reroute_after_cluster_update_settings]: took 0s no change in cluster_state
```

I will point to examples like this every time that there is an attempt at arguing that we should support more than one way to do something.

**Comment by petitout** [comment]
With all due respect, you didn't prove that there was no issue.

I also have the same behavior than you : elasticsearch seems to acknowledge the setup and is returning the updated configuration using the GET query (curl -XPUT localhost:9200/_cluster/settings?pretty=1)

but that doesn't mean that behind the hood it actually takes the configuration into account.

please retest with the steps I've provided (it fails EVERY time) :

1 - recreate the context to get the "EsRejectedExecutionException" with a voluntarily too small value for the queue_size
2- update the queue_size with the cluster API
3- try again the request that previously got the "EsRejectedExecutionException"


If this is the way you manage issues, next time I will not waste my time opening one.

**Comment by jasontedor** [comment]
> With all due respect, you didn't prove that there was no issue.

@petitout With the information that you provided, I am not able to reproduce the issue that you report, and after spending an hour studying the relevant code, I provided a plausible explanation for the behavior that you're seeing, including most importantly the fact that the cluster state is updated but without logging that the thread pool is recreated. I also added the [feedback_needed](https://github.com/elastic/elasticsearch/labels/feedback_needed) to indicate that there's a possibility that new information could alter the assessment provided here so far.

> but that doesn't mean that behind the hood it actually takes the configuration into account.

The [*only*](https://github.com/elastic/elasticsearch/blob/v1.7.5/src/main/java/org/elasticsearch/threadpool/ThreadPool.java#L379) way that the new queue size is updated in the the APIs (`_cat/thread_pool` and `_cluster/settings`) is if the thread pool is actually recreated. In the relevant code here, for a fixed thread pool, either the a new executor holder is [created](https://github.com/elastic/elasticsearch/blob/v1.7.5/src/main/java/org/elasticsearch/threadpool/ThreadPool.java#L365) with updated info but *without* changing the queue size, or a new executor holder is [created](https://github.com/elastic/elasticsearch/blob/v1.7.5/src/main/java/org/elasticsearch/threadpool/ThreadPool.java#L380) with updated info, a new queue size, *and* a new executor. Since you're saying that the API is outputting a *new* queue size, it is in fact the case that the queue is correctly updated.

> please retest with the steps I've provided (it fails EVERY time) :

Please provide a complete shell script the reproduces what you claim. Again, I tried and it did not reproduce for me.

> If this is the way you manage issues, next time I will not waste my time opening one.

I am genuinely trying to help you and I'm very sorry that you feel otherwise.

**Comment by petitout** [comment]
@jasontedor, I started with a fresh installation on another virtual machine and I couldn't reproduce the problem.......
I'm truly sorry for the inconvenience

**Comment by jasontedor** [comment]
> I'm truly sorry for the inconvenience

@petitout No worries!
