### ISSUE TITLE
Allow create index with alias instead of index name

### ISSUE THREAD

**Issue by xmudall** [elastic/elasticsearch#17137]
**Describe the feature**:
It is a feature request.
Creating index by alias instead of index name is really useful sometimes.
Consider this case, I have a service writing log data into ES and create a new index per month. If I use dynamic template to create index, the index name will be exactly same as the one I used to write data. Therefore, I have to use index name to write data other than an alias. It's conflict with official recommendation and i can't perform a reindex if need.
This problem will be solved if there exists an api like:
-PUT /_template/example
{
    "template": "test-*-write",
    "template_pattern": "{index}-write"
    "order": 1,
    "aliases": {
      "{index}-write": {},
      "{index}-read"; {},
    }
}

**Comment by clintongormley** [comment]
Hi @xmudall 

>  It's conflict with official recommendation and i can't perform a reindex if need.

The mostly-append logging use case is different from the single index read/write use case, where it makes sense to write to an alias.  With logging, you typically generate the index name from the timestamp of the log message, so yes, you do index directly into the index for that month, rather than into an alias.

Aliases with logging make sense for read requests, where you want to query the latest index, or the most recent three months etc. 

That said, we have an idea for a more flexible append-only work flow.  We'll be opening an issue to discuss this feature in the near future.

**Comment by xmudall** [comment]
Hi @clintongormley 
I agree with your opinion on logging. I just used logging case as an example for easy understand. Actually, I've a mail server provides full text searching on mails for users. I split mails by time slot (e.g. per month) to reduce resource usage especially memory (little fielddata, cache, etc.) . I use dynamic template to create index for every time slot. I hope all write/read operation is based on alias so that i can do a zero-downtime reindex if needed. That's why i have this problem.
Could you please give me any suggestions how to achieve the requirement without an alias based template? Thanks a lot.

**Comment by xmudall** [comment]
Hi @clintongormley 
Are you there?
