### ISSUE TITLE
It's not easy being green

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#17152]
The QA Vagrant tests are vital for ensuring the correctness of the Elasticsearch distributions. These tests do not currently pass and should be brought to green.

Relates #16854

**Comment by elasticdog** [comment]
See #16854 and https://github.com/elastic/infra/issues/145 where work is progressing on this issue. We discussed this during the engineering all-hands, and we want to switch over to the VirtualBox images managed by the infra team, as we should be able to duplicate them exactly in LXC-form in order to run the tests on AWS (nested virtual machines do not work on EC2, so vanilla virtual box won't work).
