### ISSUE TITLE
Support for pluggable/custom QueryCachingPolicy 

### ISSUE THREAD

**Issue by Vineeth-Mohan** [elastic/elasticsearch#17161]
It would be great if we can define our own QueryCachingPolicy implementation and ask Elasticsearch to use it rather than the default one. This will give us the flexibility to write our own caching policy.
So once we make this implementation and ship it as a plugin , the following configuration in the elasticsearch.yml file should chose our QueryCachingPolicy class rather than the default one.

index.query_caching_policy: MyCustomQueryCachingPolicy

**Comment by jpountz** [comment]
May I ask what you are missing from the default one? Maybe we could just improve it?

**Comment by Vineeth-Mohan** [comment]
@jpountz  - I know this is being debated on another issue. But i badly want the ability to decide if the filter needs to be cached or not cached with me itself. Depending on my client ( Free or paid ) , his usage , the volume of data he is going to search etc , we make decision for enabling caching or not on the set of keywords ( Kept in another document and looked up using terms lookup filter ) he is going to search. 

You can think this for situations like , when a client logs in , before he makes any search , we plan to cache his filter so that when he search the performance is good. When he logs out , we remove the filter too.  Similarly we have other use cases too. 

Hence kindly make expose QueryCachingPolicy via a flag or configuration or something , or provide the pluggability so that we can do it ourself.

**Comment by clintongormley** [comment]
> we plan to cache his filter so that when he search the performance is good.

@Vineeth-Mohan and what does his filter look like?  Is it a simple term query on customer ID?

**Comment by jpountz** [comment]
> Depending on my client ( Free or paid ) [...] we make decision for enabling caching or not on the set of keywords

I don't think this would be a good idea: if free customers are hammering the cluster, then paid customers will have a better experience if caching is enabled for the free customers since their queries will use less CPU/IO. From that perspective it is better to just cache the filters that are used most often.

> when a client logs in , before he makes any search , we plan to cache his filter so that when he search the performance is good

This filter is likely a term filter and term filters barely need any caching: they are already plenty fast thanks to the way inverted indices work.

The reason why I am cautious about exposing such internals of Elasticsearch is that the filter cache is not a regular cache. Regular caches trade memory for latency and throughput, they can barely make any harm if they are configured correctly. On the contrary, elasticsearch's filter cache can severely hurt latency and throughput if it is too aggressive: the inverted index encodes skip lists than can be used to efficiently skip over documents that do not match. If caching is too aggressive then many queries will have to read entire postings lists and load them into memory while the query maybe only needed to know about 10 matching docs.

**Comment by Vineeth-Mohan** [comment]
@clintongormley  - Well the main filter is  a terms lookup on 100,000 terms. So i have a field called ids and for each user , he is interested in 100,000 ids alone and those documents alone should be shown to him. I have used a term lookup query to achieve this. This is applied to 12 billion records.

**Comment by Vineeth-Mohan** [comment]
@jpountz - I am using a terms lookup filter of 100,000 terms against a 9 billion record indices per customer. The free client has his own set of keywords and the paid customer has his own set of keywords. And as the cache i make is one cache per the entire 100,000 terms for a client , it cant be reused for another client.  The main reason being , even if 1 keyword is different , the cache key would be different and we cant reuse the filter cache there. 

I saw the issue where you have planned to make the terms lookup query expensive , but then when i checked the code , expensive queries need 2 execution for caching. Is there some solution to make this query to get cached in the first go itself.
