### ISSUE TITLE
Ingest Attachment - OCR support for images

### ISSUE THREAD

**Issue by miguelxpn** [elastic/elasticsearch#17221]
Hello,

the ingest attachment plugin uses Tika for content extraction, Tika supports OCR by default if Tesseract OCR is installed.

I took a look at the Ingest Attachment code to see how hard it would be to add Tika's OCR functionalities to it and I found that I would need to add a new parser (org.apache.tika.parser.ocr.TesseractOCRParser) and the appropriate security policies. 

I forked the code and did that to see if it would work, the way Tika calls Tesseract is by forking a new process, so Elasticsearch's default seccomp config makes it fail. After disabling seccomp it works. 

Would you guys be willing to accept a pull request to add that in? The changes in the code are small, the only problem is that to work seccomp will have to be disabled in the Ingest Node if the user wants OCR.

**Comment by clintongormley** [comment]
Hi @miguelxpn 

Thanks for taking a look at this.  I can't speak for everybody but I think it likely that we would be very much against disabling seccomp ("optional security isn't security at all").  I think the right way to approach this would be to have a separate OCR service that the ingest plugin can talk to.  That way, Elasticsearch doesn't have to allow forking and it restricts the possibility of exploits to just the OCR service.

**Comment by talevy** [comment]
@miguelxpn, the way we are using Tika right now, this is not possible.

Closing since this is not possible with Tika, but could theoretically be done by spawning a process within a separate Tesseract Ingest Plugin.

**Comment by synapticiel** [comment]
Hi @miguelxpn 
What are exactly the appropriate security policies you added to make it possible to call tesseract ?
From a custom code, i'm able to run Tika with Tesseract, but non from ingest-attachment code
I did all possible config, but always getting this error when running Unit Tests 

`Caused by: org.apache.tika.exception.TikaException: Tesseract is not available. Please set the OCR_STRATEGY to NO_OCR or configure Tesseract correctly`
