### ISSUE TITLE
Add Template parameter to hide indices

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#17247]
It comes up that you want to _not_ include certain index's in global templates, such as meant-to-be hidden indices.

Currently, the [Multiple Index syntax](https://www.elastic.co/guide/en/elasticsearch/reference/2.2/multi-index.html) is the way that we support things like `+test*,-test3` to exclude matching indices, but templates do not support it. However, this may be unnecessarily complicated for templates because the above strategy is meant for fancy logic that can be needed for things like snapshotting and restoring.

A simple solution for this, rather than implementing Multiple Index syntax, may be to add an extra parameter:

``` json
{
  "template" : "*",
  "hide_template" : ".*"
}
```

From there, anything that matches `template`, but also matches `hide_template` (name is debatable), will _not_ have the template applied. We could even default `hide_template` to `.*` so that it excludes anything with a `.`-prefix by default.

As a note, Multiple Index syntax does provide a more consistent approach and also a more flexible one. However, it would not stop users from shooting themselves in the foot because they would have to manually exclude `.`-prefixed indices. I kind of actually want a mix of the two: multiple index without the add/remove stuff so that you can comma delimit multiple patterns for each parameter, thus allowing us to hide `.`-prefix by default.

**Workaround**

For anyone coming here because they ran into colliding templates, the workaround is pretty simple: do not apply _mapping_ changes in global templates where global means `"template" : "*"`. The downside is that it may mean that you end up repeating the template for multiple indices as a result.

**Comment by clintongormley** [comment]
Continuing discussion from https://github.com/elastic/elasticsearch/pull/17300#issuecomment-200954297

I've just read the issue in more detail and realised that my suggestion of adding a parameter to `ignore_indices` to the create index API would not help here, as this problem exists for autocreated indices like kibana and marvel.

As far as I can tell, there are three options:

1. The option proposed in this issue ie adding an `exclude_templates` parameter which defaults to `.*`
2. Changing `*` universally to ignore indices beginning with `.`
3. Making the Kibana template fully explicit, so that nothing can be overridden

The third option would work today, but it does imply a maintenance burden on Kibana.  The second option I'm concerned about because it touches so many APIs and has the disconcerting effect of making indices disappear, eg:

    PUT .my_index
    { "settings": .... }

    GET */_settings

returns

    {}

It'd also mean that request like `GET _cat/indices` would not return hidden indices by default, unless you write it as `GET _cat/indices/*,.*`.  I'm not sure if this change is worth it, just to deal with this case.

I'm leaning towards the first option but am open to further suggestions.

**Comment by pickypg** [comment]
I think the first option has the most unintended consequences and it's the least likely to impact any existing functionality anywhere. The third option also does not quite solve it without going over-the-top explicit and it's a wack-a-mole strategy because it will always have to catchup with any new feature. For example, imagine a simplified set of templates:

```http
PUT /_template/global
{
  "template" : "*",
  "mappings" : {
    "_default_" : {
      "_source" : { "enabled" : false }
    }
  }
}

PUT /_template/kibana
{
  "template" : ".kibana",
  "mappings" : {
    "my_type" : {
      "properties" : {
        "all_fields_mapped" : { "type" : "keyword" }
      }
    }
  }
}
```

Unless they also supplied the `_source` as being enabled explicitly, then the global template would still break things.

**Comment by epixa** [comment]
I like the first option as well.  I think it's appropriate that the way to "fix" the problem is to configure the template that created it to begin with, and the logical default would be one that doesn't interfere with how the core products of the stack operate.

Kibana does need to move to an explicit mapping sooner rather than later, but I agree with @pickypg on this.  If moving to an explicit mapping addresses this issue for the moment, given how global templates can be used, I think that's basically just a coincidence rather than a reliable permanent solution.

**Comment by epixa** [comment]
So what needs to happen in order to gather consensus around a solution and then to make it happen? This is blocking a support escalation, so it'd be great to at least keep the ball moving.

**Comment by pickypg** [comment]
Just waiting on @clintongormley to decide if he's comfortable with this solution.

**Comment by clintongormley** [comment]
We'll discuss this in FixItFriday tomorrow

**Comment by colings86** [comment]
Discussed in FixItFriday and we agreed that the first option would be the best way forward on this. We also agreed that we preferred the option to be called `exclude_template` rather than `hide_template`

**Comment by epixa** [comment]
Awesome!

**Comment by pickypg** [comment]
PR in #17300

**Comment by pickypg** [comment]
This is now defunct with the desire to avoid template inheritance. Closing.
