### ISSUE TITLE
Es goes insane when doing bulk-upsert with index from template where index-name has ":" in it

### ISSUE THREAD

**Issue by ddorian** [elastic/elasticsearch#17242]
**Elasticsearch version**:2.2
**JVM version**:
**OS version**:Windows 7 64bit
**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Do a scripted bulk-upsert on an index that doesn't exist that gets created from a tempalte "monthly_stats:*"
 2. Do bulk-upsert (i only did 3 objects where each incremented 1 field, so request IS small)
 3. Es goes insane (writes GBs of logs and takes 80% cpu)

**Provide logs (if relevant)**:
http://pastebin.com/u0qeqNWw

**Note that the problem goes away after I replace in index-name ":" to "_".**

**Comment by jasontedor** [comment]
Unfortunately the index name leaks into the folder name, and the `:` character is invalid for filenames on Windows. From `WindowsPathParser` in the JDK:

```java
    // Reserved characters for window path name                                                                                                                                                                                         
    private static final String reservedChars = "<>:\"|?*";
    private static final boolean isInvalidPathChar(char ch) {
        return ch < '\u0020' || reservedChars.indexOf(ch) != -1;
    }
```

In master this is fixed by #16442 where we no longer use the index name to derive the folder name but instead use the index UUID (separating name from identity). We can't retroactively forbid `:` in index names because they are okay on non-Windows.

For now, you can workaround this by changing the `:` to another character, as you already pointed out.
