### ISSUE TITLE
Sort on single field as a list produces parse error

### ISSUE THREAD

**Issue by HonzaKral** [elastic/elasticsearch#17257]
**Elasticsearch version**: `5.0.0` (3ed4ff0)

**JVM version**: OpenJDK 64-Bit Server VM (build 25.74-b02, mixed mode)

**OS version**: Linux 4.1.20-1-lts

**Description of the problem including expected versus actual behavior**:  When sorting on a single field and passing it in a list you get: `Failed to derive xcontent` error

**Steps to reproduce**:
 1. `curl -X PUT localhost:9200/i/t/42 -d '{"number": 123}`'
 2. `curl localhost:9200/_search -d '{"sort": ["number"]}'`

**Comment by colings86** [comment]
This is due to a bug in the work-around for sorting which was put in so we could parse the search request on the coordinating node but defer things that had not yet been refactored (e.g. sort) until we got to the shard. The parsing code stores each element of the sort in a list in the request on the coordinating node and then tries to read each element as JSON on the shard. Which doesn't work if the element is a string instead of JSON.

The sort refactoring is almost complete (see #17205) so I this can be closed when that PR is merged. @cbuescher is adding a test to that PR to test this problem and ensure it works in the refactored sort code.

**Comment by cbuescher** [comment]
Added test for parsing this kind of syntax (e319985) and just tried this manually on #17205, this should be fixed once that PR is in.

**Comment by HonzaKral** [comment]
Thanks @cbuescher!

In the mean time, if anybody finds this, I added a work around to my tests - just do `{"sort": "number"}` instead.
