### ISSUE TITLE
Remove legacy geo_point type

### ISSUE THREAD

**Issue by nknize** [elastic/elasticsearch#17349]
GeoPointV2 off loaded the majority of the `geo_point` functionality to lucene but supported backcompat w/ 1.x and 2.x. ES 6.0 will completely remove legacy `geo_point` type support in favor of better performing `GeoPointField` and `LatLonPoint` in Lucene 6+.

**Comment by rmuir** [comment]
for the `LatLonPoint` I definitely think we should wait until Lucene 6.1.

its still in the sandbox now because it has sandiness, but it already improves a lot for 6.1. In 6.1 its "index format changes" in that it uses docvalues and encodes slightly differently into the BKD. In 6.1 it uses two-phase iterator for all operations (this is currently very important for performance, the 6.0 version would have performance regressions to users.) Also it gets an efficient sort comparator that does not need to do kagillions of haversin comparisons. But, it still has some known bugs around corner cases and other sandiness, so there is still work to do. I think we can get it cleaned up for 6.1

**Comment by nknize** [comment]
closing in favor of #16749
