### ISSUE TITLE
Inner_hits aggregation

### ISSUE THREAD

**Issue by a-lustin-parc** [elastic/elasticsearch#17376]
Please, make it possible to aggregate inner_hits. Not all nested objects, but only those that come under the condition of query

**Comment by Vineeth-Mohan** [comment]
@a-lustin-parc  - Is it on all the matched children documents or matched documents per hit ?

**Comment by clintongormley** [comment]
@a-lustin-parc inner hits performs a further search request for every result.  This can already be heavy, adding aggregations would be too much. Rather, run a multi-search with an entry for each hit and calculate the aggregations in there.

**Comment by junchih** [comment]
hi @clintongormley , I'm just new to ES. just don't get it why you say "inner hits performs a further search request for every result", since the asker was asking the `inner_hits` on nested objects.

as I understand, there seems could be only one search request to fetch all related documents and hidden documents for each nested objects. am I right? is there any topic or article could answer my confusing?

**Comment by dinamic** [comment]
@clintongormley could you clarify how making multiple searches makes it possible to aggregate based on data in `inner_hits`? I don't understand it.
