### ISSUE TITLE
indexing stats now contain indexing ops from recovery 

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#17412]
this is a followup from #17406 where we now use the same code path for indexing even the document is a recovery operation from disk or remote. This influences the stats which are NOW correct but this depends on the semantics we want to have from them. I open this issue to discuss this and make it a blocker such that we won't forget

**Comment by clintongormley** [comment]
From a user's point of view, the fact that the recovery process makes use of indexing is an implementation detail.  This number reflects "active" indexing requests, and the more interesting number is the rate of change, rather than the absolute number.  So i'd make the stats work in the same way are before #17406
