### ISSUE TITLE
Change upgrade API to reindex-in-place

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#17446]
The upgrade API in its current form will not help users to migrate indices created in Elasticsearch 1.x to 5.x.

The upgrade API rewrites an index in the latest Lucene format, but it still retains the original data structures that were used when the index was first created. For instance:
- Doc-values on numeric fields used to use BinaryDocValues, but now use dedicated NumericDocValues.
- The parent-child feature has been completely rewritten to use a new data structure.
- Geo-point fields now require doc values and the Lucene index where, previously, they relied on in-memory calculations.

We should change the upgrade API to reindex-in-place, that is:
- Create `.my_index`using the mapping and settings from `my_index`
- Reindex the data in `my_index` to `.my_index`
- Atomically delete `my_index` and rename `.my_index` to `my_index`

This would work only on a read-only index (at least for now).  It depends on:
- [ ] The ability to rename an index #17426 
- [ ] The ability to retrieve a reindex job's status after completion #16911

**Comment by dakrone** [comment]
I think since it has been 2 years and we haven't done this, we can close it.

This feature request is an interesting idea but since its opening we have
not seen enough feedback that it is a feature we should pursue. We prefer
to close this issue as a clear indication that we are not going to work on
this at this time. We are always open to reconsidering this in the future
based on compelling feedback; despite this issue being closed please feel
free to leave feedback on the proposal (including +1s).
