### ISSUE TITLE
elasticsearch-plugin doesn't quote the java path

### ISSUE THREAD

**Issue by skearns64** [elastic/elasticsearch#17495]
**Description of the problem including expected versus actual behavior**: bin/elasticsearch-plugin doesn't quote the Java path in the same way that bin/elasticsearch does, which can cause problems when installing plugins and your JAVA_HOME has a space in it. 

Elasticsearch-plugin: https://github.com/elastic/elasticsearch/blob/master/distribution/src/main/resources/bin/elasticsearch-plugin#L70

vs

https://github.com/elastic/elasticsearch/blob/master/distribution/src/main/resources/bin/elasticsearch#L98

I admit this isn't likely to cause problems in the real world, because it should only be problematic when there are spaces in the JAVA_HOME path (bad idea!), but if it happens, you end up with `bin/elasticsearch` working, while `bin/elasticsearch-plugin` does not.

**Comment by jasontedor** [comment]
The quotes in the `elasticsearch` script are not part of the value of `JAVA` after the assignment. Thus, the line you point to in the `elasticsearch-plugin` script is not the problem.

The problem here is the use of `eval` when invoking java using `JAVA`. While `$JAVA` is quoted there, evaluation of the parameters causes those quotes to be removed (this is normal shell behavior)! Note that the `elasticsearch` script uses `exec` instead, hence the difference.

A simple solution is to use single quotes or escaped quotes around `"$JAVA"` (as other arguments here already do). Note that changing to use `exec` is a much bigger change because of the quoting of arguments that is done earlier in the script.

I opened #17496.

**Comment by jasontedor** [comment]
Closed by #17496.
