### ISSUE TITLE
Slow shard allocation in Elastic 2.3

### ISSUE THREAD

**Issue by pradeepg-telsiz** [elastic/elasticsearch#17526]
Hi Team,

Recently I updated my elastic from 2.2.0 to 2.3.0. When I start elastic 2.3, It is taking almost 5 to 8 min to turn all index from RED to YELLOW status. If I use same data and start elastic 2.2, it is approximately taking  30 seconds. 

**Elasticsearch version**:

**JVM version**:

**OS version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by bleskes** [comment]
Thanks for reporting. Can you tell us the exact upgrade procedure you followed and the size of your cluster?

**Comment by pradeepg-telsiz** [comment]
I have 11 index, total size adding up to 12GB. 

Below are the steps that I followed
1. Stop elasticsearch 2.2
2. Downloaded ES 2.3 and updated configurations to match with ES2.2
3. Start ES 2.3 
Takes minimum 5 to 7 min to get all index to YELLOW state. 
4. Revert back ES 2.3 to 2.2
5. Start ES 2.2 
Takes less than 40-40 sec to get all index to YELLOW state.

**Comment by bleskes** [comment]
Sounds strange. Can you share your config? is there anything of note in the master logs? If you prefer you can send them to my first name at elastic.co

**Comment by pradeepg-telsiz** [comment]
Sent you configurations in mail. Did you get it?

**Comment by bleskes** [comment]
Yes. Didn’t have time to look at it yet. Will do asap. Thanks!

**Comment by pradeepg-telsiz** [comment]
Any update on this?

**Comment by bleskes** [comment]
I looked at the logs and there is concrete I can take out of it. I do see a lot of node restarts (which are probably planned). I also some cluster state publishing that is slower than it should (see messages with `cluster state update task `). 

Can you repeat the experiment with logging set to DEBUG? Also, I'm not sure but it seems like you are indexing/searching while the cluster is recovering. If so, it will be better stop it while doing the experiment because it pollutes the logs..

**Comment by clintongormley** [comment]
@pradeepg-telsiz any further info?

**Comment by pradeepg-telsiz** [comment]
No improvement. Living with the same state and recovering each index manually. Where can I send the log? Can you please share email id?

**Comment by bleskes** [comment]
@pradeepg-telsiz same as before - my first name at elastic.co . Thx.

**Comment by pradeepg-telsiz** [comment]
Sent mail with logs. Please let me know if you need any more information.

**Comment by bleskes** [comment]
@pradeepg-telsiz thanks for the logs. I can see that some shards can not be assigned because they miss enough shard copies (you have 1 primary, 2 replicas which means that you need at least 2 copies to be found before a primary can be assigned, sadly only 1 is found - do you know why?). Once the shard is forcefully assigned via the API it recovers locally on node1 as you said. The node 2 is assigned a replica and it recovers from node1 and it looks it does so very quickly. Then there is nothing for a long time until node3 starts its recovery. It'ss hard to say why exactly as the logs you sent are only partially set to debug and I miss things. For example node3.txt has debug logs from some components (`discovery.zen.publish`) but not others (`cluster.service`). Can you check what's going on and resend with a complete log?

**Comment by colings86** [comment]
@bleskes is this still an issue? could this be closed?

**Comment by bleskes** [comment]
I think we can close it... it's been a long while. Thanks for the ping @colings86 !
