### ISSUE TITLE
Support wait_for_completion=<time_value>

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch#17545]
It would be super handy if we can supply a `time` value for `wait_for_completion` e.g `2m`

Right now the `reindex` and `update_by_query` are blocking by default and unbounded but most of the clients all have request timeouts. 

It would be awesome if we could specify a time unit after which a `task` property with a task id will be returned just as if we'd specified `wait_for_completion=false` from the get go.

This way clients won't recieve a timed out exception but a 200 that they can act on.
- indices upgrade
- task list
- snapshot_create
- snapshot_restore

Also expose a `wait_for_completion`

**Comment by jimferenczi** [comment]
We discussed this in Fix-It Friday. First of all we agreed that if a timeout occurs we should never return a 200.
Regarding the wait_for_completion for reindex and update_by_query, we also agreed that wait_for_completion should always be false. This kind of operation can take hours or days so the reindex/update_by_query should answer right away and the TaskManager should be used to wait for the completion of the task (with a poll strategy ?).

**Comment by nik9000** [comment]
> First of all we agreed that if a timeout occurs we should never return a 200.

Timeout occurs where? Like if we supported `wait_for_completion=1m` we should return some non-200 code with the task id after a minute? Sure!

> wait_for_completion should always be false

This is a pretty big reversal from the discussion during reindex's implementation. I wanted wait_for_completion to default to false. @clintongormley and @imotov wanted it to default to true. They argued that it'd be more consistent with the rest of the API - `wait_for_completion` is only supported in some places. Where it is supported you can set it to false and get immediate returns with a task id. But by default those APIs work just like every other API. That argument won me over.

There are plenty of cases where reindex and update_by_query make sense defaulting to false. If you are only modifying tens of thousands of documents, for instance. Or if you don't have a proxy between you and the server - like if you are running on localhost. I think that'll be pretty common actually.

Right now `wait_for_completion=false` is the only way to get the final result. Since it isn't stored anywhere. This is certainly a defect that we'll have to fix soon, but it is a consideration. So we can't "always" make it false.

**Comment by nik9000** [comment]
> Like if we supported wait_for_completion=1m we should return some non-200 code with the task id after a minute? Sure!

202 looks like the code we should use any time we return a task id and the task is still processing, regardless of if we support some timeout on waiting for completion. It fits super well.

**Comment by jimferenczi** [comment]
> This is a pretty big reversal from the discussion during reindex's implementation

Doesn't have to be ;) We discussed about long running tasks in general where wait_for_completion should/must always be set to false. That's all.

> Timeout occurs where? Like if we supported wait_for_completion=1m we should return some non-200 code with the task id after a minute? Sure!

yep exactly.

> There are plenty of cases where reindex and update_by_query make sense defaulting to false. If you are only modifying tens of thousands of documents, for instance. Or if you don't have a proxy between you and the server - like if you are running on localhost. I think that'll be pretty common actually.

I guess you mean defaulting to true ?
Yes for playground stuff it's simpler that way but it's not recommended ;) ?
 

> Right now wait_for_completion=false is the only way to get the final result. Since it isn't stored anywhere. This is certainly a defect that we'll have to fix soon, but it is a consideration. So we can't "always" make it false.

wait_for_completion=true ? 
So if the sender does not wait for completion and checks the task manager afterward it would be impossible to determine if the task was successful or not ?

**Comment by nik9000** [comment]
> long running tasks in general where wait_for_completion should/must always be set to false

That is certainly different from how we'd talked about before. I can see the merit in defaulting long running tasks to false to "teach users what they'll need to do at scale" but I also see the merit in the argument that we should just be consistent and always wait unless asked to do otherwise.

I'm totally against taking away the option for people to set `wait_for_completion=true` if they want it.

> playground stuff

I dunno. You can crank through a couple hundred thousand documents in well under the time most things would timeout. That is a fairly big playground. And if you don't have a proxy between you and Elasticsearch you can wait as long as you'd like. I think that is pretty common for this kind of thing.

> So if the sender does not wait for completion and checks the task manager afterward it would be impossible to determine if the task was successful or not ?

All you know is "the task is gone" there is an open issue for it but I don't have it handy. We'll be doing *something* to persist the results after completion. Probably also something to persist the results while it is running in case the node drops out.

**Comment by bleskes** [comment]
> I'm totally against taking away the option for people to set wait_for_completion=true if they want it.

+1 on keeping the option to wait. We assume too much about what people will do with this API. Remember that update by query can be used with great success on 10 docs as well.  This API doesn't add any complexity on our side.

Re the default  - I think we need to think about the inexperienced users first. Trying out the API for the first time, it's very confusing if it just "comes back". To me, waiting first and then looking at docs to see you don't have to wait is better learning curve. 


+1 on returning 202 on timeout.

**Comment by jimferenczi** [comment]
> I also see the merit in the argument that we should just be consistent and always wait unless asked to do otherwise.
> I'm totally against taking away the option for people to set wait_for_completion=true if they want it.

I am not arguing against the default. I agree that the default should be true but for some use cases we should advise the user to manually set it to 'false'. Though maybe not now if the "the task is gone" issue is not resolved ;)

**Comment by nik9000** [comment]
> for some use cases we should advise the user to manually set it to 'false'.

We should certainly have stronger language around that in the docs!

**Comment by bleskes** [comment]
We discussed it FixItFriday. General sentiment is that we don't really follow the suggested use case. If we add a limit to the `wait_for_completion` in the sense of time and return a valid response for that case, a client will implement code to deal with it an go into async mode. In that case, we don't fully understand why a client couldn't make an async call (`wait_for_completion=false`) and using the same code to monitor the task for as long as it wished to. I'm closing this for now, if people feel strongly it should be reconsidered, feel free to reopen and explain.
