### ISSUE TITLE
Eclipse gradle build ElasticSearch problem (Not found JAVA_HOME)

### ISSUE THREAD

**Issue by chilly** [elastic/elasticsearch#17554]
In my console, echo $JAVA_HOME is correct path.
I changed 
buildSrc/src/main/groovy/org/elasticsearch/gradle/BuildPlugin.groovy

eclipse can not set JAVA_HOME, like intellij. but the following code only judge intellij. is it a bug?

+                   if (System.getProperty("idea.active") != null) {
+                       // intellij doesn't set JAVA_HOME, so we use the jdk gradle was run with
+                   } else {
+                       throw new GradleException('JAVA_HOME must be set to build Elasticsearch')
+                   }

**Comment by nik9000** [comment]
I use Eclipse but I don't use the Eclipse gradle plugin. I think that is how most folks who do Elasticsearch development with Eclipse do it. The docs (CONTRIBUTING.md I think) talk about how to do project generation for Eclipse. Sadly, it is too much work to support both the Eclipse gradle plugin and the gradle eclipse plugin. So we went with the gradle eclipse plugin.

I'm going to close this because I don't think it is a bug. This is just "how it is done" but I'm happy to reopen if you disagree or think we need more docs somewhere. If you were interested in contributing and want to hack on the docs then please do. You are in a better position to do that than I am because I've been doing Elasticsearch development with Eclipse for years and have internalized a lot of my workflow to the point where I'm liable to skip things in the documentation because it has become muscle memory.
