### ISSUE TITLE
Remove ordering support on `histogram` aggregations

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#17587]
I propose that we always return histograms sorted by ascending bucket. I suspect that ordering is very rarely used on histograms, and even it it were needed, it would be easy to either do it on client side since histograms always return all buckets, or to use a terms aggregation instead.

**Comment by jpountz** [comment]
We discussed it in FixitFriday and agreed to remove this feature.

**Comment by colings86** [comment]
This will need to be removed in 6.0 and deprecated in 5.x

**Comment by colings86** [comment]
@elastic/es-search-aggs

**Comment by polyfractal** [comment]
@jpountz we chatted about this today, and were inclined to close/won't-fix because it'd be a relatively big change, probably breaking to some users, and we weren't sure if there was a compelling advantage other than simplifying code.  But we weren't sure if part of the context was missing... do you recall if there was a specific reason to remove ordering on histo other than simplicity?

Also, relates https://github.com/elastic/elasticsearch/issues/17588

**Comment by nik9000** [comment]
Using the logic from https://github.com/elastic/elasticsearch/issues/17587#issuecomment-689677769, I'm going to close this.
