### ISSUE TITLE
Swapping when mlockall is set to true

### ISSUE THREAD

**Issue by jdelgad** [elastic/elasticsearch#17605]
**Elasticsearch version**: 1.5.2

**JVM version**: 1.8u60

**OS version**: CentOS 7.1

**Description of the problem including expected versus actual behavior**: Appears to be related to https://github.com/elastic/elasticsearch/issues/7504. 

On a 128GB server with 24 cores using a hard disk drive in a 5 node cluster.

Running `sudo fgrep Swap /proc/PID/status` reports `VmSwap:	    1980 kB`

**Steps to reproduce**:
 1. systemd service file configured `LimitNOFILE=65535`
 2. systemd service file configured `LimitMEMLOCK=infinity`
 3. Configured to use non-standard tmp directory due to 'nonexec' using `-Djna.tmpdir`

**Provide logs (if relevant)**:

Attached. They are a bit sanitized, but should be good.
[nodes_stats.txt](https://github.com/elastic/elasticsearch/files/209319/nodes_stats.txt)
[nodes.txt](https://github.com/elastic/elasticsearch/files/209320/nodes.txt)

**Comment by jasontedor** [comment]
When Elasticsearch locks memory using `mlockall`, it locks with the flag `MCL_CURRENT`. This means that only pages that are currently mapped into the address space will be locked, and future pages that are mapped will not be locked. This means that any pages that are not mapped into the address space are eligible for swapping, and thus having `mlockall` enabled and successfully executed is not inconsistent with seeing pages swapped by the virtual memory subsystem.

There are a few circumstances under which Elasticsearch will map additional pages:
 - if min heap size (`Xms`) and max heap size (`Xmx`) are not equal to each other, then the heap size can change from its size at startup to its steady-state size as Elasticsearch executes requests
 - if using a collector that releases memory back to the operating system (the serial collector and the garbage first collector both do this but note that we recommend *not* using either of these collectors with Elasticsearch and their use with Elasticsearch is unsupported)
 - if index files are mapped into memory via `mmap`

It's this last case that likely hits everyone because we recommend setting `Xms` equal to `Xmx` (and you get this for free if you use `ES_HEAP_SIZE` to set the heap size), and we recommend *not* using either of the collectors that release memory back to the operating system.

You see, `mlockall` is really just a last resort for minimizing swapping. It's not completely effective for reducing swapping.

If you want to disable swapping, then disable swapping using `swapoff -a`. If for some reason this is not an option for you, then minimize swapping by setting the kernel parameter `vm.swappiness` to `1` (using `sysctl`). The absolute last resort is `mlockall` because at least this prevents the JVM itself (meaning the code, data and stack of the JVM) and parts of the heap from being swapped out.

You might be wondering why we do not also lock memory with the flag `MCL_FUTURE`? This would lock memory mapped pages into physical memory but that's horrific because most users's data size exceeds their physical memory size. Further, it completely negates the amazing job the operating system does at managing memory mapped pages.
