### ISSUE TITLE
Infer heap size at startup

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#17686]
Today we rely on the user to set the JVM heap size. But we also have very strong heap size recommendations (stay below zero-based compressed oops, less than half the physical RAM) and we can use these recommendations to start Elasticsearch with a recommended heap size. The heap will still be configurable and if it is configured we will not use our ergonomics to size the heap.

**Comment by clintongormley** [comment]
How do we avoid killing the user's laptop by taking half their RAM?  What happens when the user starts three instances to try things out?  Relying on `localhost` to indicate production mode isn't sufficient here.

**Comment by clintongormley** [comment]
While we're on it, the change in https://github.com/elastic/elasticsearch/pull/17675 which removes `ES_HEAP_SIZE` I think is dangerous.  Way back in the past, before we had `ES_HEAP_SIZE`, users would set min/max to different values all the time.  It was a real problem, and the reason that `ES_HEAP_SIZE` was added.  

Instead of sizing the heap automatically, I'd much prefer:

* to have one setting for min/max
* to complain in production mode if that setting is not set

**Comment by jasontedor** [comment]
We have decided to not go this route, opting instead for the defaults added in #18311 and otherwise requiring manual configuration for now.
