### ISSUE TITLE
Mapper.TypeParser instances can't deal with @Inject

### ISSUE THREAD

**Issue by cadu-goncalves** [elastic/elasticsearch#17754]
**Elasticsearch version**:  >= 2.2.0

**JVM version**: 1.8

**OS version**: Windows 7

**Description of the problem including expected versus actual behavior**:
The current way to register custom type mappers is from _org.elasticsearch.indices.IndicesModule#registerMapper_, which receives instances of   _org.elasticsearch.index.mapper.Mapper.TypeParser_. 

The spot to handle Guice binding context for DI (register implementations, bindings, etc..) is inside _org.elasticsearch.common.inject.Module#config_.

The plugin bootstrap sequence first register the mappers calling onModule method related with IndicesModule, and them builds the DI context calling the module config method. 

How instances passed to _registerMapper_ will be able to solve @Inject bindings, if they can only be constructed by hand and can't be bound to the DI context as Singletons for example?
 
**Steps to reproduce**:
Does not apply.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by nik9000** [comment]
Everything you register must be constructed by hand. Guice is **slowly** getting squashed out of Elasticsearch because it made it very hard to tell what was used where. It is being replaced by the deliberate "this depends on this" kind of behavior that you get from building things by hand.

If there is a thing that you need a reference to in a plugin and you can't get it then we can address that issue but the general direction that the code is going isn't an issue per say.
