### ISSUE TITLE
Cluster names should be restricted to ASCII

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#17810]
We no longer use index names for dir/filenames for various reasons, one of which is that unicode and filesystems often don't play well together.

Similarly, we should restrict the cluster name to ASCII only, as the cluster name is used as a directory name.  This is a breaking change, but possibly all that is required is to change the cluster name and rename the directory.  Not sure about snapshots?

**Comment by rmuir** [comment]
+1

**Comment by s1monw** [comment]
+100 make this a blocker

**Comment by clintongormley** [comment]
We could use the cluster UUID instead of the cluster name same as we do for indices now.  We should also provide a command line tool to allow renaming clusters and indices.

**Comment by s1monw** [comment]
yeah I mean that is the ultimate solution just don't use it anywhere outside of the system.

**Comment by bleskes** [comment]
we discussed it some more and I think I summarize things with:

1) One option is to limit cluster names to be pure ascii. Down side here is the BWC breakage (people who's cluster names are non-ascii, will need to re-configure and change folder names). The up side is the simplicity and the transparency - a common mistake in training is to start ES twice, one normally and one with a non-default cluster name). Looking at the data folder immediately shows what's wrong and what people should do.
2) Another solution is to use the cluster_uuid as a top level folder name. This would mean people are free to choose whatever they want as a cluster name. The down side is that it produces a chicken-and-egg issues:
   - in order to use the right data folder, a new node needs to first join the cluster to get it's uuid. This means we can't persist anything /create folders before we join. 
   - Existing nodes can scan their data folders to find one that has the right cluster name internally in it's _state file. This adds complexity and ambiguity 
       - what happens if we find two matching folders? (we can probably not start, but then the user needs to choose, meaning they need tooling to see which one is goog).
       - what happens if a node joins the cluster after having written stuff/read stuff to it's data folder (for example, we plan to write some persistent node id in there, which is needed on join), only to discover that the cluster has another uuid than the folder used locally.
 
Personally, I see the reason to have an "opaque" identifier for a cluster, but I'm not sure it's worth the complexity.

**Comment by clintongormley** [comment]
Discussed in FixItFriday - there's no need to have the cluster name as a directory at all.  If you want multiple clusters in the same mount point, then just change the `path.data`.

On startup, we should check the data path for any folder other than `nodes`. If any exists, then we should fail hard and tell the user to either: (1) move the `cluster/nodes` up to the top level or (2) change the `path.data` setting.

**Comment by clintongormley** [comment]
The data path can also be set as `path.data = /path/to/data/${cluster.name}`

**Comment by dakrone** [comment]
We'll also need to check for the (extremely rare) case where someone has named their cluster "nodes" and act accordingly.

**Comment by Chealer** [comment]
For the sequel to this episode, see ticket #32661. In short, instances with data left at the old path will fail to start when upgraded to 6.7+.
