### ISSUE TITLE
No appenders could be found for logger (common) printed out

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#17819]
If I turn off my wi-fi connection and run elasticsearch, tried with 1.7, 2.3 and 5.0 and it is always the same, the process prints out the following to start with:

```
log4j:WARN No appenders could be found for logger (common).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

The `logging.yml` is the default one. After that everything looks ok, usual logging etc.. I guess this is due to the order of initialization of our logging, we may be ok with this initial warning but maybe there is something that we want to do about it.

**Comment by jasontedor** [comment]
This one is fun. The trouble starts in the innocuous looking [line 199 `Bootstrap.java`](https://github.com/elastic/elasticsearch/blob/6941966b1654106ed9249cd01c32bfa2e06b452f/core/src/main/java/org/elasticsearch/bootstrap/Bootstrap.java#L199):

```java
199:        if (Strings.hasLength(pidFile)) {
```

This triggers class initialization for `Strings` which causes the field `TIME_UUID_GENERATOR` to be initialized on [line 64](https://github.com/elastic/elasticsearch/blob/6941966b1654106ed9249cd01c32bfa2e06b452f/core/src/main/java/org/elasticsearch/common/Strings.java#L64):

```java
64:    private static final UUIDGenerator TIME_UUID_GENERATOR = new TimeBasedUUIDGenerator();
```

This in turn triggers class initialization for `TimeBasedUUIDGenerator` which causes the field `secureMungedAddressed` to be initialized on [line 38](https://github.com/elastic/elasticsearch/blob/6941966b1654106ed9249cd01c32bfa2e06b452f/core/src/main/java/org/elasticsearch/common/TimeBasedUUIDGenerator.java#L38):

```java
38:   private static final byte[] secureMungedAddress = MacAddressProvider.getSecureMungedAddress();
```

Now the coup de grâce. The method [`MacAddressProvider#getSecureMungedAddress`](https://github.com/elastic/elasticsearch/blob/6941966b1654106ed9249cd01c32bfa2e06b452f/core/src/main/java/org/elasticsearch/common/MacAddressProvider.java#L64) tries to get a secure MAC address for use in generating the time-based UUIDs. If all the network interfaces are disabled, then there is no MAC address to use so the check on [line 73] passes:

```java
73:        if (!isValidAddress(address)) {
```

which leads to the fatal logging statement on [line 74](https://github.com/elastic/elasticsearch/blob/6941966b1654106ed9249cd01c32bfa2e06b452f/core/src/main/java/org/elasticsearch/common/MacAddressProvider.java#L74):

```java
74:            logger.warn("Unable to get a valid mac address, will use a dummy address");
```

This line being fatal because it's invoked *before* logging has been initialized.

Two lessons:
1. `static` is evil, don't do `static`
2. logging in static methods using a statically-initialized static logger (instead of an instance of `logger` from an `AbstractComponent`) is prone to this problem

I opened #17837

**Comment by javanna** [comment]
> This one is fun.

Sounds like it, thanks a lot for digging and fixing @jasontedor
