### ISSUE TITLE
Missing privileges in shield documentation

### ISSUE THREAD

**Issue by janbernhardt** [elastic/elasticsearch#17855]
On Kibana shield integration page the following privilege is mentioned 'view_index_metadata'
https://www.elastic.co/guide/en/shield/2.3/kibana.html

However within the shield documentation this privilege is not mentioned
https://www.elastic.co/guide/en/shield/current/shield-privileges.html

In the past there were also a much more fine grained privileges like these
indices:admin/mappings/fields/get
indices:admin/validate/query
indices:admin/get

But I could not find any documentation about this in the current version.
Has the privilege management changed in 2.3?

**Comment by eskibars** [comment]
Hey @janbernhardt .  For community support of Shield, we use our [discuss forums](https://discuss.elastic.co/c/shield) rather than the ES/Kibana github repos.  (Commercial support comes directly through our support team for our paying customers).  I'm going to close this issue here, but feel free to open this or other topics on discuss if my below answer isn't satisfactory.

For this particular issue, there does appear to be a documentation gap in the Shield privileges documentation.  The fine-grained privileges you listed often caused confusion and warranted a re-evaluation.   I've let the team know about the documentation gap, so thanks for reporting this!
