### ISSUE TITLE
Tribe node doesn't return HTTP address via Nodes Info or Cat Nodes APIs

### ISSUE THREAD

**Issue by radu-gheorghe** [elastic/elasticsearch#17905]
**Elasticsearch version**:
1.7.5, 2.3.1, 5.0.0alpha1

**JVM version**:
```
$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

**OS version**:
OSX 10.11.1

**Description of the problem including expected versus actual behavior**:
Basically, I can't figure out a way to get the HTTP address of a tribe node via the APIs. Nodes info gives only the transport address:
```
      "name" : "tribe1/t1",
      "transport_address" : "127.0.0.1:9303",
      "host" : "127.0.0.1",
      "ip" : "127.0.0.1",
      "version" : "5.0.0-alpha1",
      "build_hash" : "7d4ed5b",
      "roles" : [ ]
```
by comparison, a "normal" node has the HTTP address as well:
```
      "name" : "logs1",
      "transport_address" : "127.0.0.1:9301",
      "host" : "127.0.0.1",
      "ip" : "127.0.0.1",
      "version" : "5.0.0-alpha1",
      "build_hash" : "7d4ed5b",
      "http_address" : "127.0.0.1:9201"
...
```
Also, in 5.0.0alpha1, the _cat nodes API doesn't return the HTTP address, even when requested specifically:
```
$ curl localhost:9200/_cat/nodes?h=name,http_address
users1    127.0.0.1:9200
tribe1/t2 -
```

**Steps to reproduce**:
 1. Start one node in one cluster, with a config like:
```
node.name: logs1
cluster.name: logs
```
 2. Then a second node in one cluster:
```
node.name: users1
cluster.name: users
```
 3. Finally a tribe node:
```
node.name: tribe1
tribe.t1.cluster.name: logs
tribe.t2.cluster.name: users
# http.port: 9250  # behavior seems the same whether port is explicitly specified or not
```
4. Call the Cat Nodes and Nodes Info APIs, looking for the HTTP address

**Comment by s1monw** [comment]
I think this looks more like a bug, we need to investigate this further... removing discuss label. @tlrx will take a look

**Comment by tlrx** [comment]
Thanks for reporting @radu-gheorghe. Maybe I'm missing something but I just tested this and everything looks fine to me. Note that HTTP address has been added to the _cat/nodes API since 5.0.0-alpha1 (#16770).

Here's my test on 5.0.0-alpha1:

**Start node-0 in cluster-0 (port 9600)**
```
bin/elasticsearch -E es.cluster.name=cluster-0 -E es.node.name=node-0 -E es.http.port=9600 -E es.transport.tcp.port=9601
```

_cat/nodes ouput looks ok:
```
curl -XGET 'http://localhost:9600/_cat/nodes?pretty&v&h=id,name,ip,port,http'            
id   name     ip        port http
_ha0 node-0   127.0.0.1 9601 127.0.0.1:9600
```

**Start node-1 in cluster-1 (port 9700)**
```
bin/elasticsearch -E es.cluster.name=cluster-1 -E es.node.name=node-1 -E es.http.port=9700 -E es.transport.tcp.port=9701
```

_cat/nodes ouput looks ok:
```
curl -XGET 'http://localhost:9700/_cat/nodes?pretty&v&h=id,name,ip,port,http'
id   name     ip        port http
X9cI node-1   127.0.0.1 9701 127.0.0.1:9700
```

**Start tribe node on default port range**
```
bin/elasticsearch -E es.cluster.name=cluster-tribe -E es.node.name=tribe -E es.tribe.c0.cluster.name=cluster-0 -E es.tribe.c0.discovery.zen.ping.unicast.hosts="127.0.0.1:9601" -E es.tribe.c1.cluster.name=cluster-1 -E es.tribe.c1.discovery.zen.ping.unicast.hosts="127.0.0.1:9701"
```

When requesting _cat/nodes on the tribe node, it correctly reports the tribe node, the tribe client nodes (tribe/c0 & tribe/c1) and the node-0 and node-1 too with their respective HTTP addresses:
```
curl -XGET 'http://localhost:9200/_cat/nodes?pretty&v&h=id,name,ip,port,http'
id   name     ip        port http
X9cI node-1   127.0.0.1 9701 127.0.0.1:9700
g1k3 tribe/c0 127.0.0.1 9301 -
_ha0 node-0   127.0.0.1 9601 127.0.0.1:9600
ci5d tribe/c1 127.0.0.1 9302 -
T2-k tribe    127.0.0.1 9300 127.0.0.1:9200
```

Same thing with the Nodes Info API on the tribe node:
```
curl -XGET 'http://localhost:9200/_nodes?pretty&filter_path=nodes.*.http*,nodes.*.version'
{
  "nodes" : {
    "_ha0UOorR66vazp-BUw3kg" : {
      "version" : "5.0.0-alpha1",
      "http_address" : "127.0.0.1:9600",
      "http" : {
        "bound_address" : [ "[::1]:9600", "127.0.0.1:9600" ],
        "publish_address" : "127.0.0.1:9600",
        "max_content_length_in_bytes" : 104857600
      }
    },
    "g1k3oBYERDu5Mu4chi1L4w" : {
      "version" : "5.0.0-alpha1"
    },
    "T2-knUQnT32eaFXH8_gJ-A" : {
      "version" : "5.0.0-alpha1",
      "http_address" : "127.0.0.1:9200",
      "http" : {
        "bound_address" : [ "[::1]:9200", "127.0.0.1:9200" ],
        "publish_address" : "127.0.0.1:9200",
        "max_content_length_in_bytes" : 104857600
      }
    },
    "X9cI2S3PRByVHtuZ88W06w" : {
      "version" : "5.0.0-alpha1",
      "http_address" : "127.0.0.1:9700",
      "http" : {
        "bound_address" : [ "[::1]:9700", "127.0.0.1:9700" ],
        "publish_address" : "127.0.0.1:9700",
        "max_content_length_in_bytes" : 104857600
      }
    },
    "ci5dgIniQfSx99yheSb03g" : {
      "version" : "5.0.0-alpha1"
    }
  }
}
```

In the previous output there are no HTTP addresses for tribe clients nodes like tribe/c0 because they are client nodes connected to the remote cluster and don't expose any HTTP service. This is how tribe nodes work: it instantiates a single node (named **tribe** in my example) that starts multiple tribe nodes, each of them is a client node connected to a remote cluster (tribe/c0 and tribe/c1).

When queried directly, the nodes of the remote clusters (node-0 and node-1 in my example) will only report the tribe client nodes connected to their respective cluster (tribe/c0 and tribe/c1). These nodes don't really know about the node called __tribe__ that expose a global view of multiple clusters.

On 2.3.5 or 1.7.5, the Nodes Info API provides the HTTP address (just be sure to hit the tribe node):
```
curl -XGET 'http://localhost:9200/_nodes/_local?pretty&filter_path=nodes.*.http_address,nodes.*.name,nodes.*.version'

{
  "nodes" : {
    "tDk2qwCOQzqbROzMgpy8VQ" : {
      "name" : "tribe",
      "version" : "2.3.1",
      "http_address" : "127.0.0.1:9200"
    }
  }
}
```

I hope it helps. I'm closing this issue but feel free to reopen if needed!
