### ISSUE TITLE
Translog configurable path

### ISSUE THREAD

**Issue by prog8** [elastic/elasticsearch#18015]
I am dealing with problem with high ingestion rate of very small documents. Currently I store indices in EBS (EC2). I was considering changing location of translog to faster (local) storage with low access latency and more IOPS. I realized it is not possible now. Though i found TranslogConfig class in source code. Moreover there is path already, just waiting to get new functionality :)

The only limitation is that TranslogConfig's path depends only on *shardPath().resolveTranslog()*​

`new TranslogConfig(shardId, shardPath().resolveTranslog(), indexSettings, bigArrays);`

What if translog path is configurable with prefix? This would make it possible to store translog in local directories.

PS. I am sure that translog is reducing the ingestion throughput. CPU wait time varies from 15% to 20%. When I change translog strategy to async it dropped to 6%.

**Comment by jasontedor** [comment]
I do not think this should be configurable. A translog is intimately tied to its shard. If it were configurable, a simple misconfiguration could cause an abundance of chaos (let alone the chaos from users that might try to park their translog on a RAM disk).

I also doubt that this is even the right solution to your problem, but I think that you should open a post on the [Elastic discourse forums](https://discuss.elastic.co) for a broader discussion since Elastic reserves GitHub for bug reports and feature requests.
