### ISSUE TITLE
Reindex API allow op_type delete

### ISSUE THREAD

**Issue by jrots** [elastic/elasticsearch#18043]
Would be nice if we the reindex api also should support delete as op_type, 
think it uses the bulk api internally so would only require a few adjustments.. 
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"opType [delete] not allowed, either [index] or [create] are allowed"}],"type":"illegal_argument_exception","reason":"opType [delete] not allowed, either [index] or [create] are allowed"},"status":400}

Now I still need to use the npm package elasticdump for these kind of operations, 
if delete was also present I could remove this dependency

**Comment by nik9000** [comment]
> bulk api internally so would only require a few adjustments

The whole `op_type` thing is an attempt to mimic the `_update` API. This is still certainly possible. Some folks brought it up when I started work on the `_reindex` API and I said "I'll do it after index and create are done" and I never did.

I'm busy doing other stuff and will probably try and work on "reindex from a remote cluster" before I pick this up, but I'll get it eventually. On the other hand, if anyone is excited about it and wants to work on it I'd be happy to review a PR and/or help anyone get started on reindex's code.

**Comment by nik9000** [comment]
Depending on how it is done, this might be the same thing as #16883. Or, rather, it might make sense to close both issues with the same PR because they are so similar.

**Comment by tlrx** [comment]
I gave this a look and I think we should remove the current delete-by-query plugin and reimplement the delete-by-query feature using the reindex infrastructure. We could benefit of throttling, maybe scripting too, and the response format will be similar to reindex and update-by-query. I think it's a matter of creating few classes and mutualize/move around some code. 

I don't really know why we chose to implement reindex/update-by-query as a module (because of script usage?) but I think it make sense to have everything at the same place... update-by-query and delete-by-query share the same trade-offs in term of conflict resolution. I'll be happy to do it anyway :)

**Comment by nik9000** [comment]
> why we chose to implement reindex/update-by-query as a module

I implemented it as a plugin at first because I wasn't sure how long it was going to take. I grew to love it being a plugin because:

1. I can be sure that nothing depends on it. It is a "dead end" as far as code goes. That makes it easier to reason about.
2. When you change only it you can usually just run a small-ish number of tests. This is kind of a result of point 1 but it still lovely.
3. It serves as an example of how you can add fairly extensive functionality in a plugin. You can point people at it and say "plugins can make whole new actions and stuff!" This is a bit of a cheat because I changed core to make writing the plugin easier, but it is still nice!

So when it came time to "merge" it to core I just made it into a module so it was shipped with core by default and still super self contained.

I think if you wanted to move delete-by-query to reindex's infrastructure you'd just implement it in the reindex module. It really isn't conceptually any different from reindex.



BTW, I'd be really excited if `_delete_by_query` just ended up being the same thing as `_update_by_query` with `op_type` set to delete. Reindex could reuse that! It'd be cool! I think.
