### ISSUE TITLE
Groovy scripting - possible memory leak

### ISSUE THREAD

**Issue by PeteyPabPro** [elastic/elasticsearch#18079]
**Elasticsearch version**: 2.3.1

**JVM version**: openjdk version "1.8.0_71-debug"
OpenJDK Runtime Environment (build 1.8.0_71-debug-b15)
OpenJDK 64-Bit Server VM (build 25.71-b15-debug, mixed mode)

**OS version**: CentOS 6.7, kernel: 2.6.32-573.18.1.el6.x86_64

**Description of the problem including expected versus actual behavior**:  I'm using the Java client and a couple of dynamic Groovy scripts to update certain fields and nested objects in my documents. As can be seen by my [node stats](https://gist.github.com/anonymous/5e5a47a3f5476f61e2b30464bd96ccf7), almost all of my largish heap is being used up, even though I'm not using any field_data (the index itself is only around 7g, but 12g of heap is being used). I did a heap dump and a leak suspects analysis that seems to point to a memory leak involving Groovy classes: 
![screen shot 2016-05-01 at 1 58 25 pm](https://cloud.githubusercontent.com/assets/9867183/14943466/389e444a-0fa8-11e6-8de5-f7bb2dacc7e4.png)

**Steps to reproduce**: Unclear if can be easily reproduced in different context
 

**Provide logs (if relevant)**: Node stats and leak suspects screenshot above

**Comment by PeteyPabPro** [comment]
Some more details about how I'm using Groovy scripting can be found on the Stack Overflow [question](http://stackoverflow.com/questions/36918850/elasticsearch-using-a-lot-of-memory-gc-thrashing) I asked about this.

**Comment by ywelsch** [comment]
This is a tricky one.

In Groovy 2.4.0, a memory leak was fixed (https://issues.apache.org/jira/browse/GROOVY-6704) by using `java.lang.ClassValue`s. Later, it was discovered that this fix introduced another leak caused by a JVM bug (https://bugs.openjdk.java.net/browse/JDK-8136353). From Groovy 2.4.5 on (we use 2.4.6 in Elasticsearch), the decision to use classvalues was reversed (https://issues.apache.org/jira/browse/GROOVY-7591). This reintroduced the old memory leak (which I guess is the one you're seeing here). You can rerevert back to the 2.4.0 - 2.4.4 groovy behavior by setting the system property `-Dgroovy.use.classvalue=true`. Note that this reintroduces the other leak. This essentially means: pick your poison. A test that I used to verify this bug report did not run into OOM issues when using `-Dgroovy.use.classvalue=true`, but that might not hold for your scripts.

I would suggest that you use native scripts written in Java (https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting.html#native-java-scripts).

**Comment by PeteyPabPro** [comment]
1) Thanks, I'll try the system property first and see how that goes. I can add that to ES_JAVA_OPTS, correct?

 2) Dynamic scripting is a bit more suitable for our workflow - do you think using something like Javascript instead of Groovy would be a reasonable course of action if there is still a leak after setting the system property?

**Comment by nik9000** [comment]
> 2) Dynamic scripting is a bit more suitable for our workflow - do you think using something like Javascript instead of Groovy would be a reasonable course of action if there is still a leak after setting the system property?

This is why lang-painless is a thing. It is still very much "incubating" but it is going to the answer in the future I think. If you can live with groovy being, well, groovy until 5.0 the best thing to do is to wait for 5.0 try and port stuff to lang-painless as part of your "migrate to 5.0" process and file issues when you hit things it can't do. Well, that is the best thing for *us* and I think it'd be a good choice for you too, but I'm biased.

**Comment by PeteyPabPro** [comment]
@nik9000 Definitely looking forward to 5.0, and will certainly move over to lang-painless! But unfortunately the leak is problematic in the meantime...

@ywelsch I ran it with `-Dgroovy.use.classvalue=true`, and another leak did pop up. Does this one seem to be the ClassValue one you mentioned?
![leak suspects 2](https://cloud.githubusercontent.com/assets/9867183/14991772/103b75c4-1131-11e6-81bb-dc64f18cb887.png)

**Comment by clintongormley** [comment]
Not much more that we can do here other than make Painless better, or wait for Groovy to fix this.
