### ISSUE TITLE
rpm -U deletes elasticsearch.yml

### ISSUE THREAD

**Issue by Martin-Logan** [elastic/elasticsearch#18158]
**Elasticsearch version**:
5.0 Alpha 2
**JVM version**:
openjdk version "1.8.0_91"
**OS version**:
Centos 7
**Description of the problem including expected versus actual behavior**:
inplace upgrade using 64bit rpm (e.g. rpm -U elasticsearch-5.0.0-alpha2.rpm) overwrites the elasticsearch.yml file . Expect it to create an rpmnew file. 
**Steps to reproduce**:
 1.install alpha 1
 2.edit elasticsearch.yml
 3.upgrade with rpm -U elasticsearch-5.0.0-alpha2.rpm

**Provide logs (if relevant)**:

**Comment by jasontedor** [comment]
This is the expected behavior in your circumstance. When `rpm -U` is invoked, there are different scenarios. The scenarios come from there being three possible config files: the original config file distributed with alpha1, your config file with edits, and the config file that is distributed with alpha2. In this situation, you have alpha1 = x, your config = y and it turns out that alpha2 = z (there was a change to the shipped config file between alpha1 and alpha2). In this case, rpm assumes that z must be used with the new package (it can not safely assume that either x or y are safe to use with the new package). That is why it will not produce an `rpmnew` here.

**Comment by Martin-Logan** [comment]
Would it not be better then to produce an rpmold rather than entirely lose the configuration?

**Comment by jasontedor** [comment]
> Would it not be better then to produce an rpmold rather than entirely lose the configuration?

It should have produced an `rpmsave`. Are you saying that it did not? If not, that is a bug that we should fix.

**Comment by Martin-Logan** [comment]
It indeed did not

**Comment by jasontedor** [comment]
> It indeed did not

Yes, I just reproduced this as well. I will investigate. Thanks for reporting.

**Comment by jasontedor** [comment]
@Martin-Logan I've marked you as eligible for the [Pioneer Program](https://www.elastic.co/blog/elastic-pioneer-program) and opened #18188.
