### ISSUE TITLE
Make _source transformations great again

### ISSUE THREAD

**Issue by ddorian** [elastic/elasticsearch#18179]
There are ALOT of cases where I have a custom _id, that is not just a random/unique value but a combination of different values, that I also want to index, but don't want to store again in the _source.

Example _id: "project_id:user_id:thing_id:action:timestamp" and I would need to index all of these values separately, meaning storing them again as separate fields in the _source.

Currently this is not a problem if I don't store _source. Is there any alternative to transformations ?

Thank You

**Comment by clintongormley** [comment]
Those values need to be in the `_source` in order to be indexed, but you can disable storing the `_source`.  Of course, that prevents you from reindexing your document easily (although you could use a script to generate these fields from the `_id` field during reindexing).  but `_source`  transform isn't coming back.
