### ISSUE TITLE
Add support for deprecated REST endpoints to the REST specs

### ISSUE THREAD

**Issue by uboness** [elastic/elasticsearch#18238]
today the REST Specs support `path` (the main endpoint) and `paths` (all variation of possible endpoints). Would be nice to also support `deprecated_paths`. This will enable testing them as long as they're still supported. Also, by isolating these, auto-generated client can skip these paths when generating their code.

**Comment by nik9000** [comment]
Relates to https://github.com/elastic/elasticsearch/issues/17512. At least, it relates a little bit.

**Comment by javanna** [comment]
We now always return deprecation warnings as headers, it is up to clients to act on them e.g. log them or even throw an error. We have been testing since then deprecations from both unit tests and yaml tests: we assert by default that no deprecated functionality is used, and we declare exceptions in case we want to test the deprecations themselves, to verify that they are properly raised. 

I am not sure about the auto-generated clients aspect. They could skip deprecated paths if they were declared separately in the spec. But then we would force users to migrate as soon as something gets deprecated, which is one major version before Elasticsearch actually removes the endpoint.

**Comment by javanna** [comment]
The users migration point that I made applies to cases where endpoints are removed after being deprecated, where I think clients should still expose them although deprecated, but then the whole endpoint is deprecated, not just one of its paths.

When it comes to renaming endpoints though, we usually remove from the spec the deprecated path, which becomes untested although it is still exposed in core, so there is no ambiguity and auo-generated clients know which path to pick. This would be improved by adding a `deprecated_paths` section.

**Comment by javanna** [comment]
@elastic/es-clients what do you think?

**Comment by Mpdreamz** [comment]
++ to a deprecated_paths section, I think clients should still generate the code for them but clients could then automatically mark them as obsolete. 

The .NET code generator can patch the spec where needed and with 5.4 there was one endpoint removed (exist alias) that we had to write a patch file for. 

Ideally it would be a map of endpoint/deprecation reason

**Comment by nik9000** [comment]
@Mpdreamz and @javanna, it's been almost a year since the last comment. Is this still an important thing? I'm going to close this for now because we seem to have done ok without it for a while but if you think it is important please reopen it.
