### ISSUE TITLE
AggregatorBuilder vs. AggregationBuilder in the Java API

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#18367]
With the query refactoring, AggregationBuilder was renamed to AggregatorBuilder. While I get the intention since these objects do not create aggregations directly but rather aggregators, this is a bit confusing from the perspective of the Java API since aggregators are completely internal to elasticsearch.

We should either finish this renaming and also rename AggregationBuilders to AggregatorBuilders and fix the documentation of the Java API (which still uses AggregationBuilder), or rename it (and all sub classes) back to AggregationBuilder.

I have a slight preference for option 2 since I think it makes the Java API nicer.

**Comment by jpountz** [comment]
cc @colings86

**Comment by colings86** [comment]
I'm kind of +0 for both options in that I have no strong opinion either way but I would like us to keep AggregatorFactory the same name (rather than renaming it to AggregationFactory) since this is an internal class and we have factory objects on the Aggregation side of things for some aggregations (e.g. histogram) and I think renaming the AggregatorFactory would lead to confusion.

**Comment by jpountz** [comment]
> I would like us to keep AggregatorFactory the same name (rather than renaming it to AggregationFactory) since this is an internal class

+1
