### ISSUE TITLE
Unassigned shards after complete cluster failure (All nodes down)

### ISSUE THREAD

**Issue by vineet01** [elastic/elasticsearch#18393]
ES version 2.3.1 

I have a 3 node cluster, all 3 nodes are master-eligible and data nodes. I have tested cases when any one node is down, or any two nodes are down. Everything works perfectly fine and single node which is up is able to serve requests and shows yellow cluster health status which is expected. 

However when i bring all nodes down and start only one node, cluster status stays "red" and shard allocation never happens (tried also with cluster.routing.allocation.enable: all) , however if i start any one of other two nodes it gets back to normal, i get this in logs :-

org.elasticsearch.cluster.block.ClusterBlockException: blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];

17 May 2016 14:37:24,778 DEBUG  gateway:82 - [myhostname.com] [my-index][1] found 1 allocations of [my-index][1], node[null], [P], v[0], s[UNASSIGNED], unassigned_info[[reason=CLUSTER_RECOVERED], at[2016-05-17T09:07:08.627Z]], highest version: [186]

17 May 2016 14:37:24,778 DEBUG  gateway:89 - [myhostname.com] [my-index][1]: not allocating, number_of_allocated_shards_found [1]

I am using unicast for node discovery, and 2 replicas.

index.number_of_replicas: 2

Not sure if its the expected behavior.

**Comment by ywelsch** [comment]
Please ask questions like these on http://discuss.elastic.co

`index.number_of_replicas: 2` means that you have 3 copies of the data, i.e., each node has a copy. If you start only a single node, ES does not assign this shard as it wants to prevent allocating a stale shard copy. It therefore requires a quorum (2 copies) of the data to be available before deciding which one is the most recent one. This can be influenced by the setting `index.recovery.initial_shards` (see https://www.elastic.co/guide/en/elasticsearch/reference/2.3/index-modules.html#dynamic-index-settings ). Setting this to "1" will start recovery if only one copy is available but is dangerous as it can make a stale shard copy primary, leading to data loss.

Note: we have improved this in v5.0.0 with allocation ids #14739, so that we don't need a quorum of copies anymore to ensure allocating a non-stale copy.

**Comment by vineet01** [comment]
https://discuss.elastic.co/t/is-the-index-recovery-initial-shards-honored-for-distributed-writes-deletes-in-a-cluster-as-well/50211
