### ISSUE TITLE
Multiple Clauses in Span Near Query

### ISSUE THREAD

**Issue by cashel1** [elastic/elasticsearch#18478]
Elasticsearch 5.0 Alpha2

JVM version 1.8.0_91

OS Version Windows 7

Multiple clause addition in a 'span near query' produces an  java.lang.IndexOutOfBoundsException: Index: 3, Size: 1
The 'span or query' does not produce the problem.  

**Steps to reproduce**:
 SpanNearQueryBuilder qb = QueryBuilders.spanNearQuery(spanTermQuery("name","jack"), 1F);
 qb.clauses().add(1F, spanTermQuery("name", "jill"));
				
 qb = QueryBuilders.spanOrQuery(spanTermQuery("name", "jack"));
 qb.clauses().add(spanTermQuery(atb.getName(), termVal));

**Comment by clintongormley** [comment]
@cbuescher could you take a look at this please?

**Comment by cbuescher** [comment]
@cashel1 thanks for reporting, the problem seems to be that you are trying to add a new clause directly to the current list of clauses at a specific index (using javas List#add(int index, E element). This syntax will produce IndexOutOfBoundsException if you are trying to add element outside of the current lists length. Instead you should add new clauses using `SpanNearQueryBuilder clause(SpanQueryBuilder clause)`.

As a side note, I couldn't reproduce with your code snippet above, this doesn't seem to be using the Java-API since those wouldn't accept floats (`1F`) as argument for slop and list index. Are you using another client by any chance?

As far as I can see this is not a bug in ES but rather wrong usage of the API. We should not allow adding directly to the clauses list obtained by `SpanNearQueryBuilder#clauses()` but rather make that one a read-only unmodifiable list. Also we should probably add documentation and rename `clause(SpanQueryBuilder clause)` to `addClause(SpanQueryBuilder clause)` to avoid future confusions like this.

**Comment by cashel1** [comment]
Thanks, on the slop, this was a lazy attempt on my part to eliminate the variable from the post.
