### ISSUE TITLE
RestController.dispatchRequest should not stash threadcontext

### ISSUE THREAD

**Issue by salyh** [elastic/elasticsearch#18482]
In https://github.com/elastic/elasticsearch/blob/v5.0.0-alpha2/core/src/main/java/org/elasticsearch/rest/RestController.java#L165   RestController.dispatchRequest stashes the current threadcontext during resthandler execution. This makes it IMHO impossible to access transient context values from a RestHandler.

**Comment by s1monw** [comment]
you want to access the transient context from the caller of the RestHandler? I don't really understand why since the caller is the netty worker thread and nothing sits on top of this. It the beginning of the request so I think it has to stash to make sure everything is cleaned up afterwards?

**Comment by salyh** [comment]
I have a plugin which defines has a own ``HttpServerAdapter`` implementation and i try to pass through some transient parameters to the rest controller. In ES 2.x this worked and i wonder why the stash does not happen in ``HttpServer``?

**Comment by s1monw** [comment]
Well that is the place where we copy over relevant headers from the http request which is nothing by default. I think what we should do is to copy headers form the context rather than the request and filter them with the `relevantHeaders` set. That way you can pass in whatever you want but you have to register that header via `RestController#registerRelevantHeaders`? What do you think? Wanna open a PR for this?

**Comment by salyh** [comment]
Will prepare a PR

**Comment by s1monw** [comment]
@salyh note that #22636 will remove the infrastructure you are using. it would be great to get more feedback what you are doing to make sure  we have the right extension points.

**Comment by s1monw** [comment]
#22636 removed `HttpServerAdapter` this issue is obsolet
