### ISSUE TITLE
Support custom value coercion for boolean field mappings

### ISSUE THREAD

**Issue by marshall007** [elastic/elasticsearch#18535]
Similar to how you are able to specify the [`format`](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html) for parsing date types, I would like to see support for custom true/false values for the boolean field mapping.

Currently `false`, `"false"`, `"off"`, `"no"`, `"0"`, `""`, `0`, and `0.0` are all treated as falsey out of the box, but things like `"No"` and `"Off"` are not. The ability to customize this behavior would be really handy.

The actual mapping might look something like this:

```json
{
  "type": "boolean",
  "false_values": [ false, "No" ]
}
```

**Comment by s1monw** [comment]
this is a parsing feature and nothing we do per field or per index. I am also on the fence here since I think we should rather go into the other direction and only accept `true` or `false` and  nothing else going forward. I am still putting a discuss lable on it and we will discuss how we move forward

**Comment by rjernst** [comment]
I don't think this should be customizable, in the same way we should not have custom formatting for numbers (for example, trying to parse numbers from text like "ten"). The fact that we currently allow many different values for false, and "not false" is true is something we have been slowly working towards removing. We should allow true, or false, and fail otherwise.

**Comment by marshall007** [comment]
@s1monw @rjernst thanks for the feedback and that totally makes sense. Just to provide a bit of background on this: in refactoring our logic for replicating into ES, I started to prefer doing as little transformation on the documents as possible prior to indexing. Since the `_source` then remains largely untouched, it's easier to reason about and compare documents coming from the search API with those fetched directly from the database.

The `transform` API, which was deprecated in 2.0.0, worked really well for this use-case despite being a bit clunky and hard to test. I totally get why that API was deprecated, but I was hoping we might see it eventually replaced with more discrete/structured transformations like what I was proposing here.

**Comment by rjernst** [comment]
@marshall007 You can use the `ingest` node feature which is coming in 5.0. See https://www.elastic.co/guide/en/elasticsearch/reference/master/ingest.html
