### ISSUE TITLE
Use Classloader Isolation for Integration Tests

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#18540]
Non-constant, static fields are the bane of testing.

With that out of the way, it seems like it might be worthwhile to introduce classloader isolation for our integration test nodes, so that they cannot share _any_ state, whether it's by accident or not. It's a simple statement with _a lot_ of potential ramifications.

/cc @jaymode

**Comment by rjernst** [comment]
While this would be fantastic, I do not think it is possible. We would need the entire class hiearchy to be loaded in separate loaders, including the tests. I'm going to close this issue as this is beyond just a complicated issue, and it is definitely something nobody is working on (or thought about working on in the 2 years since it was opened).
