### ISSUE TITLE
bin/elasticsearch script fails when grep color is on

### ISSUE THREAD

**Issue by JnBrymn-EB** [elastic/elasticsearch#18644]
This line breaks for me https://github.com/elastic/elasticsearch/blob/master/distribution/src/main/resources/bin/elasticsearch#L88

because I have `grep` globally configured to highlight matches. This means that the first match `-Xms256m` is actually sent to Java as `<weird_encoded_-_char>Xmx256m` and Java tries to run that as a class - and fails.

I can fix this by temporarily changing my grep settings, but it did cost me an hour or so tracking down what was happening. Therefore - for other users like me - you might want to modify the script: `grep color=never` should do the trick.

Also I see that there is a mix of `grep` and `egrep` in the script.

/cc @jasontedor

**Comment by jasontedor** [comment]
I assume that you're doing this with `GREP_OPTIONS=--color=always` instead of via an alias? I'm assuming this because we bash does not expand aliases by default in scripts, and we do not `shopt -s expand_aliases`.  In general, the use of global `--color=always` is going to lead to trouble; this is not the first time that I've seen it break something. In fact, the use of `GREP_OPTIONS` is discouraged and deprecated and will be remove in a future version of `grep` exactly because it causes problems for otherwise portable scripts. A slightly better choice is `--color=auto` because then the coloring is only applied when the output is going directly to a terminal.

> I can fix this by temporarily changing my grep settings, but it did cost me an hour or so tracking down what was happening.

I think that `bash -x ./bin/elasticsearch` would have helped quickly here. It does help to have seen this problem before though, sorry.

> Therefore - for other users like me - you might want to modify the script: `grep color=never` should do the trick.

This requires GNU `grep`. Maybe this is something that we should require, but it is not something that we require today; note that [POSIX `grep` does not support `--color`](http://pubs.opengroup.org/onlinepubs/9699919799/) and thus adding it to our script is not a decision to be made lightly.

> Also I see that there is a mix of grep and egrep in the script.

This is a consequence of needing extended regular expressions in some places, and some `grep`s (non POSIX-compliant `grep`s on OS that we do *not* support so I'm in favor of removing) do not support `grep -E`.

In general, I'm inclined to recommend that you to change something on your end. As I mentioned, I've seen other scripts break because of global `grep` options of `--color=always`.

**Comment by JnBrymn-EB** [comment]
Fair 'nuf. Close this ticket if you'd like. Perhaps I'm in the minority;
I'll change my grep to just use an alias.

-John

**Comment by jasontedor** [comment]
Thanks for understanding @JnBrymn-EB. :smile:
