### ISSUE TITLE
add native sql support

### ISSUE THREAD

**Issue by yehosef** [elastic/elasticsearch#18642]
There are many use cases where SQL access to elasticsearch is desired.  There are a few possibilities currently possible:

https://github.com/NLPchina/elasticsearch-sql
which is a plugin that gives some sql abilities and

https://crate.io/a/sql-for-elasticsearch/
which is really a sql database built on top of elasticsearch (it doesn't give you sql access to existing elasticsearch data - you have to use crate completely.)

It seems that Solr has sql support:
https://cwiki.apache.org/confluence/display/solr/Parallel+SQL+Interface
so it seems it should be possible to add to elasticsearch also.

The advantages of this being integrated over a plugin might be performance and just "out of the box" support which would make elasticseach more appealing for business use cases, especially if they are using sql-based graphing/reporting solutions (eg, tableau, periscope)

**Comment by evanv** [comment]
It's interesting to note that one of the bigger drivers of Spark adoption has been their SQL syntax support on the DataFrame API (they're expanding SQL support in 2 actually because of that, eg, https://databricks.com/blog/2016/05/11/apache-spark-2-0-technical-preview-easier-faster-and-smarter.html).

Just throwing that out there... actually have mixed feelings about this, personally. ES's DSL is far richer than SQL or SQL plus a few more commands. But then again, exposing SQL-like queries probably would drive adoption quite a bit and those non-ES users that adopt it probably would get more comfortable with the ES DSL if they had a SQL-like bridge to help them start using it.

**Comment by yehosef** [comment]
It's also valuable for tooling that supports sql like tableau - and it makes it easier for things like apache Drill to use elasticsearch in that stack.

**Comment by ajaybhatnagar** [comment]
It will be good to have sql like interface as it helps migrating/adopting from RDBMS setups with lower training/adoptions needs of the organizations.

**Comment by costin** [comment]
Elasticsearch SQL has been officially released in 6.3:
https://www.elastic.co/products/x-pack/elasticsearch-sql
