### ISSUE TITLE
Performance of Postings Highlighter has regressed significantly in ES 2.1.1 from ES 1.7.1

### ISSUE THREAD

**Issue by bittusarkar** [elastic/elasticsearch#18665]
**Elasticsearch version**: 2.1.1

**JVM version**: 1.8.0_72

**OS version**: Windows 10

**Description of the problem including expected versus actual behavior**:
I indexed around 40K documents in a single shard, zero replica index with `_source` enabled. Each document has around 40 to 50 fields. There is only one mapping that I'm using for all documents. It has around 500 fields. I execute a `multi_match` query that matches only 38 documents and mostly the same field. The effective number of fields that get searched on through this `multi_match` query is around 400. This is the same setup I used for both Elasticsearch 1.7.1 and Elasticsearch 2.1.1 and below are the average search times under different scenarios:

```
                                | Elasticsearch 1.7.1 | Elasticsearch 2.1.1
============================================================================
No highlighter                  |               40 ms |               35 ms
Plain highlighter               |              140 ms |             1000 ms
Postings highlighter            |               80 ms |             3000 ms
```

The timings in the table above are fairly consistent even when the same queries are fired back to back multiple times. As you can see, if I disable highlighting all together, they both perform equally well but `postings` highlighter performs significantly worse in the new version. Interestingly, `plain` highlighter performs better than `postings` highlighter in ES 2.1.1. I also tried Elasticsearch 2.3.3 but had similar experience as Elasticsearch 2.1.1. This is a major blocker for us to move to Elasticsearch 2.x.

Is this a know issue? Let me know if you need more information and I'd be happy to help.

**Comment by clintongormley** [comment]
@bittusarkar could you upload a small recreation showing what you're doing? I can't think of anything that has changed here, except maybe the extraction of query terms.

**Comment by bittusarkar** [comment]
@clintongormley Let me work on creating the repro. It might take some time. In the meanwhile, let me add some information I missed earlier. I profiled Elasticsearch 2.1.1 by running a single query and almost 77% of inherent time was spent in `org.apache.lucene.search.postingshighlighter.CustomPostingsHighlighter.hilightField`. Then at 4%, it was `org.apache.lucene.search.IndexSearcher.createNormalizedWeight` followed by other methods. Hope this information is useful.

**Comment by javanna** [comment]
Not surprised that method is the hotspot. The way we use the lucene postings highlighter is not the best...  #11223 would help here so that we can highlight documents in bulk rather than one document and one field at a time.

That said I don't yet see what made things so much worse when we moved to the lucene postings highlighter, which we did in 2.x, nor what changed in the plain highlighter that made things so much worse. The recreation might help.

**Comment by bittusarkar** [comment]
@javanna, @clintongormley I have a reproduction available but there is a huge file for which I cannot create a gist. Is there another way by which I can share the files? Email maybe?

**Comment by clintongormley** [comment]
@bittusarkar sure - clinton at elastic dot co

**Comment by bittusarkar** [comment]
Thanks @clintongormley. I just sent you the email.

**Comment by jimczi** [comment]
@bittusarkar sorry for the (very) late response, we've reproduced your issue and found why you're seeing such a big difference between 1.7 and 2.x. In 2.x we've removed our fork of the PostingsHighlighter and we now rely solely on the Lucene implementation. We did that because some of the functionalities we wanted were not present in Lucene at that time. We realized afterward that it was hard to maintain this fork and that we missed a lot of optimizations of the original implementation. This is why we decided to remove our fork and to integrate the original PostingsHighlighter directly. Though the way we've integrated the original Highlighter is not optimal and for some use cases it can be very slow. For instance in our fork we extract the terms of the query once and then we reuse the set of terms for each hit/field. In the new version we extract the terms of the query for each field in each hit. For simple queries it is fast but if you have a lot of fields and a lot of terms in your query it can be the bottleneck. In the example you sent us you have 240 fields to highlight and the query contains 240 terms (one for each field). This is really a bad use case for this highlighter since it needs to extract the terms of this big query 240 times for each hit. 
Since the issue is clearly related to the number of fields you want to highlight in a single query, 
can you explain why you need so many fields ? Maybe you could use a different model that requires less fields ?

**Comment by colings86** [comment]
No further feedback. @bittusarkar if you have answers to the questions above please comment and reopen this issue
