### ISSUE TITLE
Unxepected error when running command elasticsearch-plugin

### ISSUE THREAD

**Issue by ajaybhatnagar** [elastic/elasticsearch#18689]
**Elasticsearch version**:
5.0.0. alpha 3
**JVM version**:
1.8.0-92
**OS version**:
Ubuntu 3.16.0-71-lowlatency
**Description of the problem including expected versus actual behavior**:
Trying to install plugins with elasticsearch-plugin command, Checking new syntax with out any option or help gives error below:
**Steps to reproduce**:
 just run command

```
./elasticsearch-plugin
```

**Provide logs (if relevant)**:

```
/usr/share/elasticsearch/bin# ./elasticsearch-plugin
A tool for managing installed elasticsearch plugins

Commands
--------
list - Lists installed elasticsearch plugins
install - Install a plugin
remove - Removes a plugin from elasticsearch

Non-option arguments:
command

Option         Description
------         -----------
-h, --help     show help
-s, --silent   show minimal output
-v, --verbose  show verbose output
_**ERROR: E is not a recognized option**_

```

**Describe the feature**:

**Comment by jasontedor** [comment]
This is because you have not specified a command, one of `list`, `install`, or `remove`. The reason for the error message is because the plugin script passes something like `-Edefault.path.conf=/Users/jason/elasticsearch/elasticsearch-5.0.0-alpha3/config` to the `org.elasticsearch.plugins.PluginCli` Java class as a program argument. When you specify a command, this argument will trickle down to the appropriate sub-command. However, since you have not, `org.elasticsearch.plugins.PluginCli` itself is attempting to parse, but this command-line argument does not mean anything to the top-level class. I'm afraid there is not an issue here, but please let us know if you think otherwise?

**Comment by rjernst** [comment]
This is a bug IMO. I've seen this myself, and I imagine it would be very confusing to a user.

**Comment by rjernst** [comment]
@jasontedor Now that custom plugin paths are gone, what need is there for reading elasticsearch.yml?

**Comment by jasontedor** [comment]
> Now that custom plugin paths are gone, what need is there for reading elasticsearch.yml?

There isn't a need to read elasticsearch.yml, but there is a need to know where `path.conf` is for plugins that do package a plugin config file.

**Comment by jasontedor** [comment]
LGTM.

**Comment by Uvionicsssingapore** [comment]
> This is because you have not specified a command, one of `list`, `install`, or `remove`. The reason for the error message is because the plugin script passes something like `-Edefault.path.conf=/Users/jason/elasticsearch/elasticsearch-5.0.0-alpha3/config` to the `org.elasticsearch.plugins.PluginCli` Java class as a program argument. When you specify a command, this argument will trickle down to the appropriate sub-command. However, since you have not, `org.elasticsearch.plugins.PluginCli` itself is attempting to parse, but this command-line argument does not mean anything to the top-level class. I'm afraid there is not an issue here, but please let us know if you think otherwise?

nthuvadeyy... nthoru  thepppadey
