### ISSUE TITLE
Version conflict engine exception sometimes returns non-existing version number

### ISSUE THREAD

**Issue by zzzFelix** [elastic/elasticsearch#18792]
**Elasticsearch version**: 2.3.1

**JVM version**: 1.8.0_65

**OS version**: OS X 0.11.5 (15F34)

When trying to delete an object with a specified version number and the requested object does not exist, Elasticsearch throws a version conflict engine exception stating that the object is out of date since the current version is -1 (non-existent). However, if the object did still exist just moments ago the exception gives an actual version number (latest version + 1). I assume this is due to the object being only marked as deleted before it's actually thrown out. This state lasts about one minute and can't be avoided by a forced refresh. I get that it may be better performance-wise to mark objects as deleted until some sort of garbage collector comes by. With that exception though, it's not possible to tell whether the object was deleted or updated. Is it possible to set the version number of objects marked as deleted to -1?

**Steps to reproduce**:
 1. Index an object.
 2. Delete that object.
 3. Try to delete it again while specifying the version number (1 in this case).
4. Get a version conflict engine exception stating that the current version number is 2.
5. Wait about one minute and try to delete the object again: You'll get a version conflict engine exception stating that the current version number is -1.

**Comment by jasontedor** [comment]
Deletes and versions are tricky. If a delete operation is version 1024 of a document, you don't want a versioned update with version 1023 to bring the document back to life. Thus, Elasticsearch needs to keep the delete around so that it can resolve a version conflict like this. Alas, keeping deletes around forever would eventually lead to an exhaustion of resources. So, Elasticsearch strikes a balance and does garbage collection as you correctly surmised.

So, where are we? Elasticsearch has to keep versions on deletes, or it can't resolve updates, but it has to eventually garbage collect those deletes. Thus, your proposal of always returning -1 for the version of a deleted document is untenable.

Yet, there is an out. The time that Elasticsearch will hold on to a delete before garbage collecting it is an index-level setting: `index.gc_deletes`. The default is sixty seconds, as your experimentation discovered, but if you set this to zero, then a deleted document will be immediately garbage collected and it's as if the version is -1, non-existent.
