### ISSUE TITLE
Courier Fetch: Bad Gateway

### ISSUE THREAD

**Issue by pip00** [elastic/elasticsearch#18868]
I been getting this error lately as soon as fire up Kibana. Any ideas why this is happening ?
As soon as I hit the Go Back button my queries would populate.

![image](https://cloud.githubusercontent.com/assets/19933089/16049157/af59e2d0-3224-11e6-9a8a-4f99cfdee818.png)

![image](https://cloud.githubusercontent.com/assets/19933089/16049190/c7b95284-3224-11e6-9187-ec72ad1a09de.png)

**Comment by jasontedor** [comment]
There is a [dedicated repository for Kibana](https://github.com/elastic/kibana), maybe it's best to seek an answer there?

**Comment by pip00** [comment]
I don't think this is an issue with Kibana.

**Comment by jasontedor** [comment]
> I don't think this is an issue with Kibana.

I don't think it's an Elasticsearch issue, I don't think that we return 502 anywhere and anyway even if it is there is no indication where in Elasticsearch the issue could be since you've told us nothing. If you do think that this is an Elasticsearch issue, then your best bet is to ask a question on the [Elastic Discourse forums](https://discuss.elastic.co) in the Elasticsearch category until there is a verified bug here. Sorry, I really think you'll get the most effective help if you try to troubleshoot from the Kibana side.

**Comment by jasontedor** [comment]
> I don't think that we return 502 anywhere

I checked, Elasticsearch never sends a 502.
