### ISSUE TITLE
`deb` package from official repo does not restart the service

### ISSUE THREAD

**Issue by chillum** [elastic/elasticsearch#18861]
Hi,

I have this repository in Ubuntu 14.04: 'deb https://packages.elastic.co/elasticsearch/2.x/debian stable main'

I did `apt-get update` and it updated Elasticsearch (I had like 2.1.1 and this command updated it to 2.3.0).

The problem is: although, the new Elasticsearch is on the disk, the service is not restarted. That is: when I update the Elasticsearch from the official repo, I have to restart it manually to really update it.

I find this to be a rather confusing and non-standard behaviour, I really think, the official packages should restart on package upgrade. Like nginx, Postgres, Jenkins or many others do.

**Comment by jasontedor** [comment]
Sorry, we decided previously that we are not going to restart the service automatically. This is because we do not want shards to automatically start re-allocating during an upgrade without direct intervention by the user. However, you can use the flag [`RESTART_ON_UPGRADE`](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-service.html#_linux) to enable this, if you so desire.
