### ISSUE TITLE
How to properly recognize long running jobs in the _tasks reply

### ISSUE THREAD

**Issue by acarstoiu** [elastic/elasticsearch#18864]
The new `_tasks` API misses an important feature, namely the ability to tell which task is what. For example if someone launches [a long reindexing job](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html) and later on tries to have an idea about the progress, there is no strong identification of the task. As a human you might make a guess, but with several similar reindex jobs run concurrently, a programmatic decision is impossible.

Therefore I propose that all API calls that may result in entries in the tasks list carry a supplementary parameter, say `task_tag`, that would be tied to the respective task (so that in the `_tasks` reply you may identify it). It's safer than directly specifying a task ID and has less code impact.

**Comment by nik9000** [comment]
In 5.0 `?wait_for_completion=false` on reindex will be less dangerous because the results will persist (merged that about 20 minutes ago) so I expect for long running operations you'll be able to use that.

Rather than a tag I'd prefer to just spit the request that user made as part of the task. I believe that is what the `description` field is for, though I'm fairly sure we aren't using it properly now.

I believe that _tasks come back with a start time so you could use that too....

**Comment by clintongormley** [comment]
> In 5.0 ?wait_for_completion=false on reindex will be less dangerous because the results will persist (merged that about 20 minutes ago) so I expect for long running operations you'll be able to use that.

+1

> Rather than a tag I'd prefer to just spit the request that user made as part of the task. I believe that is what the description field is for, though I'm fairly sure we aren't using it properly now.

+1

If you put the task into the background with `wait_for_completion=false`, you get a task ID which you can use to track the task status.  I don't see the benefit of also specifying a `task_tag` if you're not intending the run the task in the background.

**Comment by acarstoiu** [comment]
First of all, when using `wait_for_completion=false` I should get not one, but several task IDs as there are normally several nodes that perform a certain request. But that's useless now because I would simply lose the outcome :-1: 
Even in the upcoming _5.0_, not waiting for a request's outcome implies that someone will have to keep polling the `_tasks` API until the results arrive, which is not resource friendly. It's monitoring and result getting combined together, but I believe most people will be able to live with that.

Using the quoted request to identify a task is just guessing (one could have simultaneous identical requests), akin the use of the _action_ property.

**Comment by clintongormley** [comment]
> First of all, when using wait_for_completion=false I should get not one, but several task IDs as there are normally several nodes that perform a certain request. 

You should get the parent task ID.

> But that's useless now because I would simply lose the outcome 👎 

In 2.x yes.  

> Even in the upcoming 5.0, not waiting for a request's outcome implies that someone will have to keep polling the _tasks API until the results arrive,

The tasks will be there immediately.  Once the task is complete the outcome will be stored in the tasks index but will be accessible via the same tasks API.

> which is not resource friendly.

How would a task tag be any different?

**Comment by nik9000** [comment]
The task get API in 5.0 (GET /_tasks/taskid) supports
?wait_for_completion=true. So if the task is still running it'll wait for
it to finish. As of now it won't load the result from the task index after
it has finished waiting though if you run it again it will. I'll fix that
though.

I expect that to be fairly resource friendly. You can handle timeouts or a
proxy chopping the connection by retrying the GET.

I'm not 100% sure a user provided tag on the request is a bad thing. I'm
just sure that returning the actual request is a good thing we should do
too.

I like user tags because you can put a session or something in there and
then cancel all cancelable tasks for a session.

**Comment by nik9000** [comment]
> I like user tags because you can put a session or something in there and then cancel all cancelable tasks for a session.

Like there session is some construct outside of ES.

**Comment by clintongormley** [comment]
Discussed it in fix it friday - we agree that the task ID is the preferred way to retrieve task statuses and see no immediate need for additional tags.  Will close this for now, but we can revisit if this proves popular.

**Comment by acarstoiu** [comment]
Just to answer the question
> > which is not resource friendly.

> How would a task tag be any different?

I have to repeat myself: monitoring and getting the result are _different_ things. Getting the result should be as quick as possible, while the sampling frequency in monitoring doesn't need to be high.

You see, a task tag is an identification decided by a requester willing to wait for the result. While monitoring can take place on another thread ;)

**Comment by clintongormley** [comment]
So why not just use two threads with the task API and the task ID: one with wait_for_completion (for the result) and one without wait_for_completion (for monitoring)?
