### ISSUE TITLE
Specialize the search script API

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#18863]
Currently the scripting API allows to return arbitrary objects. This is an issue for search scripts because they might be called billions of times in a single search request and missing information about the return type makes things harder to optimize.

So we could look into specializing the search script API so that it would only be allowed to return a double. This would break a couple of things however:
- scripts would not be able to return multiple values per document anymore,
- scripts would not be able to return anything else than a double, so eg. building a string in a script and returning it would be impossible.

This is likely not an issue for the main use cases that we want to support with scripting, such as multiplying the score with the log of the value of some field. However I wolud not be surprised that there are some existing search scripts producing arrays of numbers or strings in the wild.

**Comment by rmuir** [comment]
For us with painless, there are two main issues:
* forces boxing of return values
* means the "root" of our tree is untyped, this hurts us a lot.

Compare the QPS of expressions, which dodges these issues (https://benchmarks.elastic.co/index.html#search_qps_scripts). Look how much faster it is than painless. This is sad, its how much performance we are leaving on the table.

In general, search script and executable script need more separation. One of them gets called millions and billions of times and needs to be fast. The latter case is not really as much of a hotspot.

**Comment by nik9000** [comment]
> In general, search script and executable script need more separation. One of them gets called millions and billions of times and needs to be fast. The latter case is not really as much of a hotspot.

+1

**Comment by uschindler** [comment]
+1

I'd suggest to have 2 possible scripts: One returning Object and one returning just double (unboxed). We can handle that easily in painless. We just add the correct casts and implement the main logic in 2 different methods.

We can also add stuff for covariant returns: So scripts have to implement 2 methods: one returning double and one returning Object. Scripts returning doubles can implement the double method directly and add a covariant bridge to box (returning Object). If a script cannot return a double, it throws ClassCastException in the double returning method and only implements the Object one.

**Comment by nik9000** [comment]
Lots of non-search scripts don't need to return anything. Usually their job is to modify stuff in some `ctx` variable. I guess aggregations have scripts that want to return arbitrary stuff.

**Comment by clintongormley** [comment]
> In general, search script and executable script need more separation. One of them gets called millions and billions of times and needs to be fast. The latter case is not really as much of a hotspot.

Agreed.  I can think of two places where search scripts today need to return strings:

* Script Fields - These can return pretty much anything, and really they should be executable scripts instead of search scripts as they are only called once per hit.  The only problem here is that it would be a breaking change as users would need to use `ctx._source` instead of `_source`, but I think this is worth it.

* Term aggregations - I know users use this to eg combine multiple fields or to emit tags which represent some calculation

The last one is trickier.  With @uschindler's proposal, can we still keep the string return in term aggregations (and suffer the slower execution speed) and use the double version (pretty much?) everywhere else

**Comment by jpountz** [comment]
Discussed in FixitFriday: there are reservations about removing the ability to produce anything but doubles in all search scripts, so one idea would be to have the following APIs in `ScriptEngineService`:

```java
    // already exists: used for updates, ingest or search scripts that may need something else than doubles
    Object compile(String scriptName, String scriptSource, Map<String, String> params);

    // new API: used by search scripts that need to produce doubles only like script_score or sorting by script
    // for the script engine, the default implementation could delegate to #compile
    Object compileDouble(String scriptName, String scriptSource, Map<String, String> params);
```

Then it seems like we should easily be able to pick the right one depending on the call site. @jdconrad @uschindler @rmuir would it make things easier to optimize for Painless?

**Comment by uschindler** [comment]
`compileDouble` should of course return double :-)

**Comment by rmuir** [comment]
I'm not happy about it. Today we have 2 apis, and both are slow. The proposal here would make one of them more complicated.

If we are going to have 2 apis, why not just have one of them be fast?

**Comment by s1monw** [comment]
> If we are going to have 2 apis, why not just have one of them be fast?

can you explain the API and it's consequence ie. does it mean we remove functionality? Does it mean we restrict everything to a double? I mean if we can have 1 fine but how?

**Comment by rmuir** [comment]
No, i can't because these scripting apis are a disaster. Its literally impossible to tell what is going on outside of it. You've got slow shit using the "fast" apis and probably vice versa too.

Its willy nilly which one is used: ExecutableScript or SearchScript. And we don't even tell the script which one it needs to be at compile-time. Forget about return value, the slow hashmaps, etc: we can't even give a nice error if someone tries to use `_score` from an update script, because we don't know which one we are until runtime.

I'm going to exit the issue, I don't think i will be very helpful. 

I just repeat, look here: https://benchmarks.elastic.co/index.html#search_qps_scripts

Why is expressions 50% faster than painless? It generates the equivalent code. The difference is that expressions bypasses the scripting API. 

I find it ironic we don't seem to care about leaving 50% performance on the table, yet at the same time fork a joda-time class (causing immense engineering frustrations) so that a date operation will be 10% faster.

**Comment by jdconrad** [comment]
I would also make other major changes to the scripting API.

1) I would prefer that the ScriptService only be responsible for compiling a script.  The CompiledScript that is handed back should be what actually executes the script.  It seems odd to me that I have to call back into the ScriptService with this object every time I want to execute a script.  (The CompiledScript can know what contexts it's allowed to run under.)
2) I would move caching to the ScriptEngines.  Let the engines decide how to cache instead of having one big blob of random scripts in the service.  This would also prevent the one-off for callbacks into the Groovy ScriptEngine since it already does some form of its own caching.
3) This one is probably unrealistic because of the way we store scripts and how we want to execute a single script against multiple indices, but it would be awesome if we could compile a script against an index so that we know the types of fields coming in.  One big benefit of Expressions is that it can assume all fields are doubles, and pretty much backdoors directly into Lucene to get the field data.  It would be nice if this was available to Painless as well.

**Comment by s1monw** [comment]
@jdconrad you can do whatever you want there. I am all +1 to even deprecate the old API and build a new one that can be used only in search as a start. I am sure we are all on the same page and we want to make it to gain the 50% but I also think you guys know it best what needs to be done. Once the drama queen has calmed down and gets his willy nilly shit together I think everything is possible. Go ahead and make the changes.

**Comment by rjernst** [comment]
I'm going to close this because it duplicates #20426, which is the concrete issue to satisfy this problem.
