### ISSUE TITLE
Validate restored index templates

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#18883]
Now that index templates are validated on creation/update (#8802), it would be good to validate templates restored from a snapshot too.

**Comment by haiguo** [comment]
+1 would be good to get this into 2.x

**Comment by jpountz** [comment]
What should we do if the template is not valid?

**Comment by clintongormley** [comment]
Very good question... You don't want to refuse to restore everything else from the snapshot.  I'm hoping there is a way of reporting: "template Foo skipped because invalid"

**Comment by ywelsch** [comment]
Templates are currently not (re-)validated / upgraded when we upgrade a cluster. I see that as a pre-requisite to this as it would otherwise make the situation possible where a snapshot that was just done in a cluster cannot be restored in the same cluster. The change is thus broader than just "fixing" this for snapshot/restore. If we were to solve this, there is still the question on what to do when we run into an invalid template. A template can be invalid due to a number of reasons (changed naming rules, incompatible mapping or incompatible index settings). 

I see different ways forward: 1) Do the same as we do for the persistent cluster settings, namely just fail to restore. This might be very unsatisfactory for users which have this one template that is not compatible (and only find out when restoring). 2) Do a partial restore and notify the user that some templates could not be restored. This requires adding status fields for partial success and is totally different from an API perspective than what we do for incompatible indices. 3) Take the approach that we use for indices: When we restore indices at the moment, we have the possibility to select which indices should be restored, what settings should be ignored (and what new settings added / overridden). If an index has incompatible mappings, the overall restore operation fails right at the beginning and the user can repeat the restore process by choosing not to include that incompatible index in the restore. The same does not exist for templates (we can neither select which templates should be restored nor can we change their properties upon restore). It's unclear to me whether adding all that complexity to the restore API would be the right thing to do.
