### ISSUE TITLE
Rename `fields` to `stored_fields` and add `docvalue_fields`

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#18943]
As of https://github.com/elastic/elasticsearch/pull/15017 the `fields` parameter will no longer try to retrieve fields from the `_source` but will only return stored fields.  This is a breaking change and there is nothing to warn the user that their response may well be different.

Instead, let's rename `fields` to `stored_fields` and throw an exception if the user uses `fields`.

Also, add `docvalue_fields` as an adjunct to `fielddata_fields`

**Comment by kimchy** [comment]
we could also maybe throw a nice exception, if the field is stored, we can suggest stored_fields, and if not, we can suggest source filtering?

**Comment by jpountz** [comment]
Should we make `fields` a deprecated alias for `stored_fields`? Sure this makes things trappy if users used to retrieve `_source` using `fields`, but on the other hand we documented since 1.0 that `fields` should only be used for stored fields only: we are breaking all users of the `fields` option rather than only those who used it to retrieve fields from source?

**Comment by pickypg** [comment]
I think both should be deprecated aliases for the other side. It's trappy, but it at least allows people that are using those fields _properly_ to get the right thing without an issue. Then remove them in 6.0.

We should still throw an exception for bad usage, but presumably that check is in there anyway just because it has to be to ensure we do the right thing.
