### ISSUE TITLE
gateway.recover_after_nodes should support dynamic setting by api

### ISSUE THREAD

**Issue by jolestar** [elastic/elasticsearch#19082]
**Describe the feature**:

I write a elasticsearch service, support user dynamic add or remove elasticsearch node from cluster by web console. Elasticsearch cluster's zen discovery is good for this situation, new node join cluster did not need to restart old node for reloading config, cluster setting such as 'discovery.zen.minimum_master_nodes' support dynamic updating by api. But 'gateway.recover_after_nodes' is static, and only used by the master node, when the cluster scale_in and scale_out, how i change the setting? I have to restart old nodes for loading this config.

So I think gateway.recover_after_nodes should be a cluster setting and support dynamic setting by api.

**Comment by makeyang** [comment]
+1

**Comment by bleskes** [comment]
sadly there is a catch 22 here. Unlike min_master_node (which is used when ever nodes join and leave the cluster), gateway.recover* settings are only used during the initial cluster state recovery, when a cluster is formed for the first time. You should use these setting to prevent the master from starting to allocate shards before all nodes have joined, creating unneeded chatter. This means we can't store it in the cluster state because at that point it's not yet recovered (we have long terms plan to change things in that area, but for now this is how it works).  How ever, it is worth while to go and change the setting in the elasticsearch.yml files on the master nodes when the cluster size changes - it will be used in the next cluster outage. 

I'm closing this for now. Feel free to reopen if you feel something is not covered.

**Comment by jolestar** [comment]
Ok, i got it. Now, i change the recover* setting in elasticsearch.yam when cluster size change, but not restart  the node.  thanks. @bleskes

**Comment by LoadingZhang** [comment]
+1
