### ISSUE TITLE
arrays not rendering properly in search templates

### ISSUE THREAD

**Issue by asldevi** [elastic/elasticsearch#19119]
**Elasticsearch version**: 2.3.3

**JVM version**:1.8.0_25

**OS version**: Mac OSX

**Description of the problem including expected versus actual behavior**:

When an array like  `my_ids` with value `[90, 80, 74]` is passed to the search template which includes the following block,
 
```
                  "must_not":[
                    {
                      "ids" : {
                          "type" : "xxx",
                          "values" : {{my_ids}}
                      }
                    }
                  ]
```
 it renders as 

```
         "must_not":[
                    {
                      "ids" : {
                          "type" : "talents",
                          "values" : {0=90, 1=80, 2=74}
                      }
                    }
              ]
```

which used to be rendered as expected with `"values": [90, 80, 74]` in ES 2.1.1.

**Comment by clintongormley** [comment]
So this is an interesting one... yes the behaviour has changed, but this was never supported behaviour.  it happened to work in this case, but in other cases it fails.  For instance, if `my_ids` contained `["foo", "bar"]` it would get rendered as `[foo, bar]` which is not legal JSON.

Instead of fixing this issue, i think we should backport https://github.com/elastic/elasticsearch/pull/18856 instead, which gives proper support for rendering JSON arrays and objects.

**Comment by asldevi** [comment]
#18856 looks just great. With that upcoming, I agree that this doesn't need to be fixed. Thanks.

**Comment by tlrx** [comment]
> #18856 looks just great. With that upcoming, I agree that this doesn't need to be fixed. Thanks.

Great! The feature has been backported to 2.4 in #19153. I'm closing this issue then.
