### ISSUE TITLE
CLI tool to force create an empty translog

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#19123]
While the translog has been greatly improved, it is still possible that there are lurking bugs which can cause corruption, eg see #18972. When this occurs, there is currently no way for the user to recover the data in the index. 

We need a command line tool, for expert use only, which will write a fresh transaction log (losing data in the process) to allow users to recover what data they can.

**Comment by jpountz** [comment]
Should it integrate with the existing `index.shard.check_on_startup: fix`?

**Comment by s1monw** [comment]
yeah that is a good idea @jpountz

**Comment by bleskes** [comment]
> Should it integrate with the existing index.shard.check_on_startup: fix?

@jpountz can you elaborate?

**Comment by jpountz** [comment]
We already have a hook for removing the corrupted parts of a shard, even if this might cause data loss. So I think it would be nicer to integrate with it instead of having something completely different for the translog and the Lucene index. We might not like the fact it is a setting, but once it is abstracted as a single thing, we could consider exposing it as a command-line tool too if we like it better. For the record, `index.shard.check_on_startup: fix` removes all segments from the shard that appear as corrupted.

**Comment by dakrone** [comment]
Perhaps something like: `index.shard.check_on_startup: truncate_translog` ? (I dislike the word "fix" because it makes it sound like there isn't data loss, even though there is)

**Comment by bleskes** [comment]
OK. I agree this are related. But I think we're saying we want to move away from this being a setting (which can linger around and be dangerous) and create a command line tool that does both lucene level fixes and translog level fixes. Correct?

**Comment by jpountz** [comment]
I think a single option should take care of both the index and the translog? I am good with renaming `fix`, I agree we need something that better carries the fact that there will be data loss.

**Comment by dakrone** [comment]
I dunno, the more I think about it, the more I like the CLI tool, because we can warn users that their will be data loss and require confirmation.

Also, I was hoping in the future to be able to dump some diagnostic information from a translog using the CLI, or even dump the data itself in the case someone lost or deleted the shard but has a translog with some documents in it
