### ISSUE TITLE
vagrant tests should run `vagrant box update` too

### ISSUE THREAD

**Issue by brwe** [elastic/elasticsearch#19145]
Otherwise everyone needs to run this manually every now and then with is a PITA. See also: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+packaging-tests/826/consoleText

**Elasticsearch version**: master

**Comment by dliappis** [comment]
+1 on this one. vagrant boxes are versioned and usually bring important improvements or fixes for repos that may become unavailable.

Running `vagrant box update` in the root of the checked out repo, where the `Vagrantfile` resides, will update the boxes references in the machine definitions and run pretty fast is everything is already up to date.

Additionally it will avoid people scratching their heads with packagingtest failures due to having downloaded an older version of an elastic box at some point in the past and unnecessarily creating issues.

I think it is as simple as adding it before: https://github.com/elastic/elasticsearch/blob/master/qa/vagrant/build.gradle#L226
