### ISSUE TITLE
check for // norelease removed?

### ISSUE THREAD

**Issue by brwe** [elastic/elasticsearch#19246]
It seems like we removed the check for // norelease comments in https://github.com/elastic/elasticsearch/commit/5458d07ea28b80abfb28d1c6c096c9ec88ca but I am not sure this was intentional and if everybody is aware of it. Should we re introduce it? Or or is it still hidden somewhere and I just cannot find it?

**Comment by nik9000** [comment]
Reintroduce it I think.

**Comment by jasontedor** [comment]
> Should we re introduce it?

I would think yes as there are `norelease`s in the codebase right now that were added with the understanding that they would fail a release because they are marking items that must be changed before the next release. We can not change the meaning of that (to do nothing) with those having been added with that understanding.

**Comment by rjernst** [comment]
I opened a PR to add it to the gradle build (the python release script won't be used anymore with the unified release): #19873

FYI, this is the current list of nocommits:
```
> Found invalid patterns:
  - norelease on line 516 of core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataCreateIndexService.java
  - norelease on line 136 of core/src/main/java/org/elasticsearch/index/mapper/MappedFieldType.java
  - norelease on line 588 of core/src/test/java/org/elasticsearch/index/IndexWithShadowReplicasIT.java
  - norelease on line 649 of core/src/test/java/org/elasticsearch/index/IndexWithShadowReplicasIT.java
```
