### ISSUE TITLE
Low performance of source filtering

### ISSUE THREAD

**Issue by luisobo** [elastic/elasticsearch#19290]
**Elasticsearch version**:
2.3.3 on Elastic cloud

**JVM version**:
Not sure

**OS version**:
Not sure

**Description of the problem including expected versus actual behavior**:
When doing a query and providing a list of fields in `_source`, the filtering of those fields takes a considerable amount of time.

**Steps to reproduce**:
1. Given an index with at least a thousand documents
2. Make a query that matches at least a thousand documents and set `size: 1000`
3. Provide a list of fields  in the `_source` request param

This request takes a couple of seconds (specifically, the `took` field in the response body).

In contrast, when you set `_source: true` so that it returns all fields of the source, the request takes 100ms (but the transfer takes longer if each whole document is big)

It seems to be the case that most of the time goes into filtering the fields of every source object, and not reading the objects. If that is the case, I think there should be room for improvement in reformatting 1000 documents in less time.

I wouldn't mind making this my first contribution to ES. I'd propose to first, make a pull request to highlight source filtering in the profiler as I don't think that is measured. Make a second pull request that to improve the performance of source filtering. 

If this seems reasonable, I'd love to hear your thoughts as well as any pointers,

Thanks

**Comment by tlrx** [comment]
Yes, using source filtering adds an extra overhead compares with no filtering at all. As you said, in order to correctly filters the fields the source of every search hit must be loaded, parsed and then filtered. On 1000 hits that represent a fair amount of work. My own experiment shows that most of the time is spent at loading and parsing time, not at filtering time. But if you have any idea of improvement I'd be glad to discuss and help here.

> In contrast, when you set _source: true so that it returns all fields of the source, the request takes 100ms (but the transfer takes longer if each whole document is big)

Right, when there's no source filtering, the source of every search hit is loaded and passed "as it is" to the coordinating node.

Out of curiosity, did you try to use the [Response Filtering](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#_response_filtering) feature? I think it can filters search hits source now. It should be more efficient in your case because it only filters the "output", resulting in less data to transfert over the network.

**Comment by nik9000** [comment]
> In either case, I'm surprised that filtering 1000 documents takes several seconds.

Yeah, it is. It'd be a great thing to profile. We expect not filtering to be much more efficient but I didn't expect it to be *that* much more efficient.

**Comment by clintongormley** [comment]
>  if I understand correctly, loading and parsing time goes to both filtered and non-filtered requests

Loading yes, parsing no.  Non-filtered requests just pass back the binary blob in the JSON, there's no parsing.

**Comment by tlrx** [comment]
@luisobo There's certainly a room for improvement, that would be great if you can profile the code. Out of curiosity, how many shards are involved in your bench?

**Comment by colings86** [comment]
No further feedback
