### ISSUE TITLE
How to query negative number by query_string

### ISSUE THREAD

**Issue by gy1227** [elastic/elasticsearch#19381]
ES version:2.3

curl -XGET 'http://localhost:9200/test/_search?pretty' -d '{
    "query": {
        "filtered": {
            "query": {
                "query_string": {
                    "query": "f1:-123",
                    "default_operator": "AND",
                    "default_field": "_all"
                }
            }
        }
    },
    "size":10
}'

error:
nested: QueryParsingException[[test] Failed to parse query [f1:-123]]; nested: ParseException[Cannot parse 'f1:-123': Encountered " "-" "- "" at line 1, column 3.

**Comment by clintongormley** [comment]
You have to escape the `-` otherwise it is considered to be an operator:

    `"f1:\\-123"`

**Comment by xibaohe** [comment]
why we need two "\"?

**Comment by xibaohe** [comment]
why need two "\\"

**Comment by Vespira** [comment]
I discovered the issue with Spring Data Elasticsearch, on a field marked as Integer type. I had a method like findByNumber(), and if I passed a negative number, the results found were completly unrelated to the said number. Filter worked nicely with positive values. Because under the hood, it were using a query_string and the -X was converted to string and "-" interpreted as an operator character.

Just have to find how to escape this in Spring Data Elasticsearch. Thanks for the subject and answer, but what does "-" do in a query string so ?
