### ISSUE TITLE
Remove content detection mechanism from REST endpoints

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#19388]
Today, some Elasticsearch REST endpoints (e.g., update index settings API) attempt to determine the content type (e.g., JSON vs. YAML) of the request body with a [rudimentary detection mechanism](https://github.com/elastic/elasticsearch/blob/f6aec3fdb53d7e3d7693393c25d5c3012efecb07/core/src/main/java/org/elasticsearch/common/settings/loader/SettingsLoaderFactory.java#L59-L80). This mechanism breaks down on YAML bodies that contain braces because the content is inappropriately detected as JSON. Instead, this mechanism should not be used, Elasticsearch should default to JSON for all request bodies, and possibly obey the `Content-Type` header for allowing YAML.

Relates #19366

**Comment by javanna** [comment]
I was under the impression that we already obey to the `Content-Type` header, and it's a bug if some apis don't. Seems like we do things differently only for apis that handle settings. I noticed that we support "properties" format for settings, which may be the reason behind this weird choice... wondering who uses/remember we support properties format there.

**Comment by jasontedor** [comment]
> I was under the impression that we already obey to the `Content-Type` header, and it's a bug if some apis don't.

Sadly we do not. :cry:

> I noticed that we support "properties" format for settings, which may be the reason behind this weird choice... wondering who uses/remembers that we support properties format there.

I think that should be removed as part of closing this issue. :smile:

**Comment by javanna** [comment]
> Sadly we do not.

It seems like we do apart from where we accept settings in the body? Or are there other REST endpoints where we try and detect content type?

> I think that should be removed as part of closing this issue.

Sure, why not. Maybe it should be brought up before it gets removed though :)

**Comment by clintongormley** [comment]
> I noticed that we support "properties" format for settings, which may be the reason behind this weird choice... wondering who uses/remembers that we support properties format there.

Not documented. Please rip it out!

**Comment by javanna** [comment]
> Not documented. Please rip it out!

Perfect that makes it a no-brainer, with properties out of the way it makes no sense to do any auto-detection I think. We should do for settings what we already do for any other request I believe.

**Comment by jasontedor** [comment]
We can completely remove support for properties. I opened #19391.

**Comment by anti-social** [comment]
If you removed `---` requirement YAML parser could parse JSON since YAML is a superset of JSON.

**Comment by clintongormley** [comment]
To quote from https://metacpan.org/pod/JSON::XS#JSON-and-YAML

> YAML has hardcoded limits on (simple) object key lengths that JSON doesn't have and also has different and incompatible unicode character escape syntax, so you should make sure that your hash keys are noticeably shorter than the 1024 "stream characters" YAML allows and that you do not have characters with codepoint values outside the Unicode BMP (basic multilingual page). YAML also does not allow \/ sequences in strings

**Comment by popravich** [comment]
ok, but what about checking `Content-Type` header?
YAML format suits our flow the best -- its easier to read, write, add comments and maintain at all.
 It would be really great if you guys atleast keep current YAML support.

**Comment by jasontedor** [comment]
@popravich That's the plan.

**Comment by javanna** [comment]
I care to highlight that we already take into account the `Content-Type` header. I think the title of this issue is misleading as it makes people think that we guess the content type all the time, while we (used to) have this detection in place only for apis that accept settings in their request body. The general approach is to take `Content-Type` into account and that's always been the case apart from the mentioned exceptions.

**Comment by jasontedor** [comment]
@javanna It's in the [description](https://github.com/elastic/elasticsearch/issues/19388#issue-165076519) of the issue that this is a problem only on certain endpoints.

**Comment by javanna** [comment]
ok it appears that what I cared to highlight above was completely wrong. We don't read the `Content-Type` header, ever, sorry for the confusion. We rather auto-detect based on markers on all REST endpoints. Settings were indeed a special place as we supported also properties format there (now gone).

The reason for this is that we have the java api, which exposes a lot of `source` setters that allow to effectively provide the response body as a byte array. Those methods are also used from REST to transport where we convert from `RestRequest` to java api object, so no content type is ever taken into account.

**Comment by bleskes** [comment]
I think the discussion should be split in two. First for the future where we will rely on http for all out of cluster communication and then second for what to do until then. As Luca noted, we don't do anything with the incoming content type at the moment.

For the future, I would suggest we move over to using content type headers exclusively and use JSON as default. That means we will need to extend our transport layer to carry that information. Maybe move from `ByteReference` to `XContentByteReference` and drop support for setting raw strings.

Until then we have two options - either keep things as is (but improve detection and make it uniform - i.e., not have one detection logic for settings and another for the rest) or change our transport client to require content type information. If we go for the latter, we have to do it on a major version. Since that is quite a big job for us and will case pain for users to upgrade to something that will be going away any way, my vote is to keep things the same for now and just solve the little issues we find. As soon as we can fully rely on http this will become simpler on it's own.

**Comment by javanna** [comment]
One compromise could be to keep the current `source(BytesReference)` etc. methods (maybe deprecate them) and add new methods that accept the content-type as a second argument, so that the REST layer can call those instead and hand over the content-type header. Where we don't know, we would still auto-detect. This is a big job but it doesn't necessarily have to be a pain for users.

Looking at what we are moving towards to (http), having those new methods may actually end up helping users migrating as the content-type will always be required with the rest client when providing a request body. Not too sure about this but maybe worth considering.

Another option we would have is to copy the content-type header from REST layer to transport layer so that the info is accessible when actually parsing the bytes and can be taken into account if available. This is suboptimal as the transport client would not have that info unless the header is explicitly set for each request, which is something that I am not sure users would do. Would work within elasticsearch though without changing methods signatures, probably too sneaky though.

**Comment by clintongormley** [comment]
Discussed in FixitFriday.  To fix the transport client we have to either:

* Require a content header
* Remove the ability to specify bytes
* Remove the transport client

All of these are big changes.  In the meantime, should we just fix the REST layer and require a content header for anything that is not JSON?

**Comment by javanna** [comment]
Fixing the REST layer anyhow requires the transport layer to accept the content-type and carry it around wherever bytes can be provided. We agreed on FixItFriday that we want to fix the REST layer to not do auto-detection and rely on `Content-Type` instead. I think next step is to more closely evaluate what the impact is on the java api, and see if we can at least decrease the places where one can provide bytes in the java api, and add the content-type bit wherever providing bytes is needed.  It is a big job but it is required to fix the REST layer, regardless of future deprecation of transport client.

**Comment by javanna** [comment]
@jaymode should we close this? We have removed auto-detection from the REST layer, is there anything left to do here?

**Comment by jaymode** [comment]
@javanna you are correct. There is nothing left to do here.
