### ISSUE TITLE
Include other Reference to other ElasticSearch clients in Docs

### ISSUE THREAD

**Issue by dadepo** [elastic/elasticsearch#19399]
Include reference to other ElasitcSearch client in the documentation. Right now only Perl and Python are included. It is a little bit strange to have only just these two, when ElasticSearch does have other official clients. https://www.elastic.co/guide/en/elasticsearch/client/index.html

**Comment by clintongormley** [comment]
@dadepo anywhere in particular?

**Comment by dadepo** [comment]
I think only these two places:
* https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html
* https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html

**Comment by clintongormley** [comment]
I believe that Ruby and PHP don't have scroll helpers.  Not sure about .net

@polyfractal @karmi @Mpdreamz ?

**Comment by polyfractal** [comment]
PHP has iterator helpers that wrap scroll:  https://github.com/elastic/elasticsearch-php/tree/master/src/Elasticsearch/Helper/Iterators

However, it was a user contribution and not well documented at the moment.  So not a good page to link to currently.

No bulk helper outside the standard bulk endpoint.

**Comment by Mpdreamz** [comment]
We have a `Reindex()` helper. I'm actually adding helper version of `Bulk` and `Scroll` helpers that return observables (e.g they will return multiple responses vs the single requests to the endpoints)  as I write this :smile:.

**Comment by karmi** [comment]
Hi,

the Ruby client has a syntactic sugar for the Bulk API, where you can pass your data as a [`data`](https://github.com/elastic/elasticsearch-ruby/blob/master/elasticsearch-api/lib/elasticsearch/api/actions/bulk.rb#L22-L28) option, so users don't have to perform acrobatics with the action:data pairs in their code. (There is no "reversed" helper, which would take an Array and store it into Elasticsearch in bulks, because it seemed to me trivial to iterate over the Array and send the bulks in users code.)

There is no special wrapper or sugar for the Scroll API, which would for instance yield batches of documents from the index -- as a remedy, I've included a fair number of [copy&paste ready examples](https://github.com/elastic/elasticsearch-ruby/blob/master/elasticsearch-api/lib/elasticsearch/api/actions/scroll.rb#L31-L35). I might think about adding some kind of sugar for that in the `elasticsearch-extensions` gem, it's mostly a matter of nice naming and API.

Apart from supporting the core Reindex API in Elasticsearch 2, the Ruby client has a fairly complex [reindexing extension](https://github.com/elastic/elasticsearch-ruby/blob/master/elasticsearch-extensions/lib/elasticsearch/extensions/reindex.rb) which has a compatible API, works on old clusters, and allows extra tricks like transforming the documents during the reindexing operation. (The only downside is that it is not parallelized right now.)

**Comment by clintongormley** [comment]
Any of you are welcome to add per-client examples to the reference docs mentioned above

**Comment by Mpdreamz** [comment]
Aye Aye @clintongormley should have stated that I will ammed to the docs myself and not dump it on you :smile:

**Comment by colings86** [comment]
@clintongormley @Mpdreamz can this issue be closed? or is there still more to do?

**Comment by Mpdreamz** [comment]
Leave it open just a tad we'll be doing a big doc update on our end next week so we have somewhere nice to point people for scroll and bulk helpers. cc @russcam

**Comment by debadair** [comment]
[docs issue triage]

Note that we now have a mechanism for adding client-specific examples to the reference.

**Comment by lockewritesdocs** [comment]
I'd like to clarify the issue before delving deeper. It seems that we want to add links to the `scroll` helpers for each supported language to the [Scroll API](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html#request-body-search-scroll) in the Elasticsearch reference. For example, adding a link to the [Search Scroll API](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high-search-scroll.html#) for Java.

@debadair, is that determination correct?

**Comment by Mpdreamz** [comment]
Hey @lockewritesdocs I don't think there is anything actionable left here.

We recently coordinated on making sure all helpers that exist are documented:

https://github.com/elastic/clients-team/issues/129

And opened PR's for these e.g: https://github.com/elastic/elasticsearch/pull/51388

The linked Scroll API is not a helper but a 1-1 mapping of the API. The helpers aid in scrolling by providing an abstraction over the 1-1 mapping. Therefor I don't think java needs to be added to the call out.

**Comment by lockewritesdocs** [comment]
Thank you for the context and background @Mpdreamz! As you mentioned, this ticket is resolved by https://github.com/elastic/clients-team/issues/129. Marking this ticket as closed.
