### ISSUE TITLE
Stack overflow in Painless

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#19475]
The following produces a stack overflow in Painless:

    POST t/t/1/_update
    {
      "upsert": {},
      "scripted_upsert": true,
      "script": {
        "lang": "painless",
        "inline": "for (def key : params.keySet()) { ctx._source[key] = params[key]}"
      }, 
      "params": {
          "bar": "two",
          "baz": "two"
      }
    }

**Comment by clintongormley** [comment]
And related (perhaps?), `params` can't be used with this syntax: `params[var]`:

    POST t/t/1/_update
    {
      "upsert": {},
      "scripted_upsert": true,
      "script": {
        "lang": "painless",
        "inline": "for (def key : ['bar','baz']) { ctx._source[key] = params[key]}"
      }, 
      "params": {
          "bar": "two",
          "baz": "two"
      }
    }

produces:

        "_source": {
          "bar": null,
          "baz": null
        }

**Comment by jdconrad** [comment]
Just got back from vacation, so I'll take a look at this issue today.

**Comment by jdconrad** [comment]
@clintongormley 

In the first example, the reason you are seeing stack overflow is because the result ends up being an infinitely recursive.  Params contains 'ctx,' 'bar,' and 'baz' (more than just the user input); not just 'bar' and 'baz.'  This means that _source has 'ctx' -> '_source' -> 'ctx' -> 'source' ... forever :).  This is interesting behavior (not exactly a bug), and maybe something we should exclusively prevent from happening.  

In the second example, I'm not sure why those are null values, when I run the parameters as a local unit test, it seems to work well.  There must be some disconnect between in coming user values somewhere along the line, and this will require some more investigation.

**Comment by clintongormley** [comment]
> Params contains 'ctx,' 'bar,' and 'baz' (more than just the user input); not just 'bar' and 'baz.' This means that _source has 'ctx' -> '_source' -> 'ctx' -> 'source' ... forever :).

Ah ok.

> This is interesting behavior (not exactly a bug), and maybe something we should exclusively prevent from happening.

Just so you know, it crashes the node :)

**Comment by tlrx** [comment]
@clintongormley In your second example from https://github.com/elastic/elasticsearch/issues/19475#issuecomment-233326494, the `params` should be included in the `script` object, not at the same level.

**Comment by clintongormley** [comment]
Doh - thanks
