### ISSUE TITLE
Randomize cluster configuration for rest tests

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#19517]
We're using the REST tests more and more instead of `ESIntegTestCase`. This causes us to lose a few things:
1. REST tests run against a single node so we rarely test serialization. `ESIntegTestCase` tests ran against a randomized number of nodes and usually did serialization between the nodes. As much as we _should_ have unit tests for serialization I think we _should_ have integration tests that use it as well.
2. ESIntegTestCase ran the mock plugins which did things like assert that we didn't leave any contexts open across test cases. We don't do that at all in REST tests.

I'm sure there are more things about the cluster configuration but I can't think of them off the top of my head.

**Comment by javanna** [comment]
Good points!

I think we should re-evaluate what we use REST tests for and how we want to move forward, especially now that we have a REST client.

A bit of history: REST tests were first introduced to have all language clients run the same tests. Core elasticsearch started running those same tests as well to test the otherwise untested elasticsearch REST layer (integration tests used solely the java api). Core started to add REST tests too in order to increase coverage for the REST layer too, and those tests made sense for the clients too, as they effectively meant more coverage for the clients too. 

A while ago we decided to move away from testing against an internal cluster, which runs in the same jvm as the tests, as that is a scenario that's far from reality. The closer thing we had at the time to a real integration test relying on an external cluster was the REST tests, so we started using those more and more. We are now in a situation where we use REST tests for a lot of different tests, and clients run a subset of those. But REST tests come with limitations, as the infra wasn't made to run full blown integration tests with complicated setups, plus if we have REST tests that are only run by us to test core and integrations, I am wondering if it still make sense to write them in yaml format. Maybe we shouldn't invest in some other test infra that programmatically uses the REST client to send requests. I think we are where we are because we didn't have a java REST client, and REST tests were the easier way to write a test that was http based. Maybe other reasons too?

**Comment by karmi** [comment]
Chiming in here with @javanna. I think we should open up a discussion about the REST (YAML) test suite, asking ourselves questions such as "what is exactly the position of these tests within the Elasticsearch core suite", and "what goals should these tests fulfill".

As Luca writes, the REST (YAML) tests were historically a device to ensure all language clients, or "anything that talks to Elasticsearch over HTTP", can be verified in a shared way in its correctness. There's a tremendous value in that, however technically trivial and "small" it ultimately is.

Of course, over time, there are many specific things within the context of Elasticsearch core to test, and these things require a much more flexible and powerful infrastructure to support them. The question is, in my mind, whether we should "bend" the REST (YAML) tests for this purpose, or as Luca suggests, come up with a _different_ infrastructure for these. This other infrastructure could indeed leverage our knowledge and code implementations of the YAML tests, but could be something different, more flexible in terms of Elasticsearch core integration testing.

In other words, there's a big benefit in eg. randomizing the number of nodes the REST tests are run against, but that is more _interesting_ for Elasticsearch itself, than to various language clients we have. 

Even strictly pragmatically, imagine the Ruby test suite fails because the test assumed to be run against a single node, not two (as happened to me [the other day](https://github.com/elastic/elasticsearch/commit/9b1a4771207f21ca275cf10c3a4e8717c9e45311)). Now I'm probably left confused, sometimes the suite runs, sometimes it fails, I have to ask somebody about the problem, ... 

In summary, I think we should ask if what we need aren't _two different REST test suites_:

1. a common REST (YAML) test suite, which tests correctness of language clients and serves as their integration tests, and
2. an Elasticsearch core integration test suite, which might or might not be encoded in YAML, which is run only by Elasticsearch core, to serve as its integration tests suite, with all the nice things like randomized number of nodes, custom configurations, specific plugins installed, and so on.

**Comment by karmi** [comment]
CC: @elastic/es-clients

**Comment by nik9000** [comment]
So, yeah, I just had another conversation about this with @clintongormley. I think we should move away from putting *all* of the testing of REST things that we do for Elasticsearch into the REST tests. They function very well as smoke tests for Elasticsearch's REST behavior and for the client's interaction but their lack of power, specifically lack of arbitrary loops and methods, means we copy and paste things all over the place. *And* we keep adding more and more complexity to them and that adds more and more burden on the language clients.

I still think Elasticsearch should randomize the configuration when it runs the yaml rest tests because it can get more value out of that. I don't think the clients should need to worry about that. Their goal isn't to find Elasticsearch bugs, but instead to find bugs they might have in interacting with Elasticsearch.

So I'm going to spend some time this afternoon putting together some REST level tests for Elasticsearch in Java using the its client, probably by reverting the REST changes I made in https://github.com/elastic/elasticsearch/pull/19509 and redoing the checks as other tests.

**Comment by rjernst** [comment]
> I still think Elasticsearch should randomize the configuration when it runs the yaml rest tests because it can get more value out of that

The point of using rest tests for integTest was to test *integration* of all the componenents, not to test individual behavior. Eg, we should not be testing every variation of a feature, only that that feature is hooked in correctly (the integration of the components). I don't think randomizing is going to help, it will only be then like it was when we had more ESIntegTestCases: sporadic failures that have nothing to do with the feature/test that failed. Let's instead invest in more unit tests, and keep the integration testing to a bare minimum. I don't think randomizing the number of nodes is useful, but if we want to first run the rest tests on a single node cluster, and then run them on a two node cluster, I think that would be fine to ensure eg distributed actions are hooked up correctly.

**Comment by rjernst** [comment]
Also note, we already have a multi node test that runs all the rest tests, but that is only with the core rest tests (not those for plugins/modules). Making it a standard part of rest testing (test on one node cluster, then test on two node cluster) would be good, and we could remove the multi node smoke test.

**Comment by rmuir** [comment]
I don't think integration tests should be randomized. It is a good approach for unit tests.

**Comment by s1monw** [comment]
> I don't think integration tests should be randomized. It is a good approach for unit tests.

++

**Comment by bleskes** [comment]
> I don't think integration tests should be randomized. It is a good approach for unit tests.

We strive to make all our API work in multiple cluster setups - for example, with or without dedicated master nodes. I think it make sense to run the integration with all of those configurations and I don't think we need to test all of them all the time, or is that what you suggest? There is a combinatorial explosion issue here - dedicated coordinating nodes, dedicate ingest ndoes etc.

**Comment by rmuir** [comment]
I dont recommend using randomization for this purpose, myself. As far as there being too many possibilities, perhaps there shouldnt be so much complexity/so many damn settings :)

I definitely don't think randomization it should be applied to integration tests: nobody wants to debug that. Keep integration tests as simple as possible.

**Comment by nik9000** [comment]
> So I'm going to spend some time this afternoon putting together some REST level tests for Elasticsearch in Java using the its client, probably by reverting the REST changes I made in #19509 and redoing the checks as other tests.

I added a few commits to #19509 that make it relatively simple to use the REST client to test Elasticsearch with java code. It feels like the right tool for the job of testing the new header proposed in that PR, mostly because not all clients expose headers at all. It might be the right tool for other similar jobs. Anyone interested in that (admittedly small portion of this conversation) please review over there.

**Comment by nik9000** [comment]
If we aren't going to randomize while running the REST tests we should certainly run more than one node. That is a much more consistent test that things hook together.

I think some of the point of my opening this issue is lost in the question of randomization. I'd like to point out that the REST tests also have significantly less strong assertions around things like in flight contexts leaking out of the test. `ESIntegTestCase` has a handful of similar assertions that are quite helpful.

**Comment by karmi** [comment]
> If we aren't going to randomize while running the REST tests we should certainly run more than one node. That is a much more consistent test that things hook together.

+1

**Comment by s1monw** [comment]
we do run `smoke-test-multinode` and `backwards-5.0` with multiple nodes I think we are doing ok here?

**Comment by nik9000** [comment]
`smoke-test-multinode` doesn't run *all* the rest tests, just the ones from core, right? If we ran all rest tests with multiple nodes we could drop `smoke-test-multinode` I think.

I'd like us to think about the search context leaks and whatever other things that `ESIntegTestCase` adds that I can't name off hand as well.

**Comment by s1monw** [comment]
@nik9000 for stuff like this we still have `ESIntegTestCase`? we can still write stress tests in there etc?

**Comment by nik9000** [comment]
I remember the hanging search context checker catching all kinds of little mistakes when I was working on stuff in the past. I don't recall exactly what, but I'm fairly sure it wasn't stress tests.

**Comment by nik9000** [comment]
Another thing we should think about along these lines: should we run the rest tests with assertions enabled on the cluster we're testing?

**Comment by javanna** [comment]
@nik9000 introduced the ESRestTestCase base class, that allows to send rest requests via java to an external cluster. What else do we want to do/change in our test infra?

**Comment by nik9000** [comment]
The two points in the description are still valid, I think. We only use a single node for rest tests by default and we don't have any of the fancy leak detection. If we're fine with losing those as we write more rest tests then we should close the issue.

**Comment by javanna** [comment]
I think we are fine with the current limitations of our yaml tests. Closing.
