### ISSUE TITLE
Garbage Collector clearing less and less space.

### ISSUE THREAD

**Issue by dopey** [elastic/elasticsearch#19544]
**Elasticsearch version**: 1.7.3 - 2.3.3

**JVM version**: "1.8.0_72"

**OS version**: Ubuntu 14.04

**Description of the problem including expected versus actual behavior**:

Running ES on a 5 node cluster cluster where each node has 15GB of RAM. The max heap size is set to 7GB on each server. Using plugins searchguard-ssl, stats, and head.

![elasticsearchgc](https://cloud.githubusercontent.com/assets/1820847/17036297/891bb588-4f40-11e6-85db-17f6cd25bf11.png)

This is a screenshot of the heap usage on each node over a 10 day period. You can see the normal saw-tooth pattern, but the bottom of each cycle is rising. It seems that the garbage collector frees less and less memory every time that it runs. I was having a similar issue on ES 1.7.3 and hoped that bumping to 2.3.3 would help to alleviate, but no such luck.

Once the servers get up to ~6GB of heap used for ES we do a rolling restart of the cluster which restarts the whole cycle.

Let me know if there's any more information that might be useful.

**Comment by nik9000** [comment]
Have a look at https://www.elastic.co/guide/en/elasticsearch/guide/current/_limiting_memory_usage.html . Usually shapes like this come from fielddata which is a known defficiency in Elasticsearch that we've mostly migrated away from. It isn't the default for indexes created in 2.0 but if you migrated any indexes from 1.x to 2.x you'll still have indexes that use it.

Because this isn't a *new* bug it is probably best discussed on https://discuss.elastic.co/ . If we can pin it down to a new bug then it makes sense to reopen here.

**Comment by dopey** [comment]
Thanks for the reply! Posted an update discussion topic on the forum. -> https://discuss.elastic.co/t/elasticsearch-garbage-collection-issue/56143
