### ISSUE TITLE
Ability to update Marvel related configs via HTTP API

### ISSUE THREAD

**Issue by alefebvre-ls** [elastic/elasticsearch#19574]
We're currently using Elasticsearch v2.3.3 and it seems you can't dynamically update Marvel related settings (`marvel.*`) via the HTTP API.  Although it doesn't return an error, I can confirm that the setting doesn't show up in `/_cluster/settings` and Marvel data continues to be generated on all the nodes.

```
user@esclient01:~# curl -XPUT http://10.1.2.3:9200/_cluster/settings -d '{"persistent": {"marvel.enabled": false}}'
{"acknowledged":true,"persistent":{},"transient":{}}
```

```
user@esclient01:~# curl -XGET http://10.1.2.3:9200/_cluster/settings?pretty
{
  "persistent": {
    "indices": {
      "recovery": {
        "concurrent_streams": "3",
        "max_bytes_per_sec": "100mb"
      }
    },
    "cluster": {
      "routing": {
        "allocation": {
          "node_initial_primaries_recoveries": "3",
          "cluster_concurrent_rebalance": "2",
          "node_concurrent_recoveries": "2",
          "disk": {
            "watermark": {
              "low": "90%",
              "high": "93%"
            },
            "threshold_enabled": "true"
          }
        }
      },
      "info": {
        "update": {
          "interval": "30s"
        }
      }
    }
  },
  "transient": {}
}
```

Could this setting be updated to allow dynamic updates or is there a reason it needs to stay static within the elasticsearch.yml config?  Could the [documentation page](https://www.elastic.co/guide/en/marvel/current/configuration.html) be updated also to indicate if these settings are [dynamic or static](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html)?

Thank you

**Comment by pickypg** [comment]
Hi @alefebvre-ls, please ask these types of questions in our [Discuss forums](https://discuss.elastic.co).

Not every setting in ES is dynamically updateable. This will be a bit more obvious in 5.0 thanks to a large amount of work that has gone into the settings part of the code across Elasticsearch. You'll also be able to _unset_ persistent settings in 5.0.

```
user@esclient01:~# curl -XPUT http://10.1.2.3:9200/_cluster/settings -d '{"persistent": {"marvel.enabled": false}}'
{"acknowledged":true,"persistent":{},"transient":{}}
```

This indicates the the setting was not accepted. It was acknowledged that your request was well-formed, but the persistent and transient blocks were empty because nothing you passed in was accepted. This too will improve a bit in 5.0.

`marvel.enabled` is a setting that controls whether the plugin should initialize. If `false`, then it will not load them. The only way to set this usefully is within the `elasticsearch.yml` (or command line) so that it reads the value at startup.

The setting you're looking for is `marvel.agent.interval`, which controls the polling interval from the internal agent. You want to shut this down until you decide otherwise to effectively stop Marvel:

```http
PUT /_cluster/settings
{
  "persistent": {
    "marvel.agent.interval": -1
  }
}
```

Note the value is traditionally a time value (e.g., `"10s"`), but to disable it you currently set it to `-1`. In ES 5.0, this setting will change to be more obvious.

**Comment by debadair** [comment]
No longer updating Marvel docs.
