### ISSUE TITLE
Don't swallow the original IOException thrown at JSON parsing in slowlogs

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#19573]
**Elasticsearch version**: 1.7.5

**JVM version**: 1.8.0_77

**Description of the problem including expected versus actual behavior**:

The slowlogs are hidding and not logging the original IOException thrown in the [slowlog indexing](https://github.com/elastic/elasticsearch/blob/v1.7.5/src/main/java/org/elasticsearch/index/indexing/slowlog/ShardSlowLogIndexingService.java#L160-L168) and [searching](https://github.com/elastic/elasticsearch/blob/v1.7.5/src/main/java/org/elasticsearch/index/search/slowlog/ShardSlowLogSearchService.java#L203-L220) utility classes. The same seems to be happening for 2.3.x.

As such in slowlogs entries like the following are logged and there are no clues as to what the original request was and why it failed:

```
[2016-07-25 09:10:38,310][INFO ][index.indexing.slowlog.index] [some_node] [some_index][3] took[7.2s], took_millis[7200], type[some_type], id[12345], routing[12345], source[source[_failed_to_convert_]
```

**Comment by rjernst** [comment]
This is a typical case of exception swallowing. For master, the code is in `IndexingSlowLog` line 193.  We could easily change this catch to rethrow as an `UncheckedIOException`. However, that would propagate up and cause the indexing request to fail, even though the actual indexing already succeeded. So we could either do that, or log the exception in the slow log itself. I don't know which is better, I've marked this issue for discussion.

**Comment by nik9000** [comment]
Maybe we should log it in the main log file (not the slow log) at warn level? Then we can keep the slow log the way it is. I don't expect this to be especially common so warn level ought to be fine. If it become common we can bump that log level to error as a work around and we can fix the issue that makes it common in the mean time.

**Comment by javanna** [comment]
I don't think slowlog should cause a request to fail, but we should totally not lose what the problem was and log all its details. The odd part of polluting the slowlog file would be that it may break parsers out there that rely on a fixed format? So I think I agree with Nik to try and log it in the main log file if possible.

**Comment by rjernst** [comment]
Well, one problem here is rethrowing and putting into the general log means we will not have this indexing request in the slow log. I think that is kind of bogus? Propagating to fail the indexing request would have been painful yes, but we would know what the issue is and could fix much faster than it just being hidden away in another log file.

**Comment by jasontedor** [comment]
Letting the exception percolate up here will not fail the indexing request. The slow logs are implemented as indexing operation listeners. The post indexing operation loop that invokes such listeners catches all exceptions and logs them at the warn level. After logging, these exceptions percolate no further. Therefore, we can choose to not write the entry to the slow log, but instead carry the exception up to the post index listener loop where it will be logged at the warn level. With it, we carry the entry that would have been entered into the slow log (modulo the failed source conversion). I opened #29043.
