### ISSUE TITLE
Rest client's ResponseException's message should include the body

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#19622]
The body of the response is super useful in figuring out why the request failed. Without it the message for the exception doesn't give you a clue what is wrong other than "400 error when trying this request" or "500 error when trying this other one".

I know we removed that functionality as part of adding the async request methods but I want it back please. I gave it a shot as part of #19310 but it was fiddly because InputStream so I figured it should be fixed in its own PR.

**Comment by javanna** [comment]
We didn't remove the body from the exception, we just changed the way you get to it. It's just that it was pre-read before to avoid making an exception closeable, now you just have to read it through `responseException.getResponse().getEntity()`.

**Comment by javanna** [comment]
Maybe you mean that the body was before part of the exception message?

**Comment by nik9000** [comment]
Yes! That. Sorry.

You can always get the body from the exception but the trouble with that is that you have to intentionally do it. And that only works if you are explicitly handling the exception. If you aren't then you only have the exception message. I think it'd be much more user friendly to have the body in the message.

**Comment by javanna** [comment]
It would be better yes, but also a bit cumbersome because some entities are not repeatable hence if we read the body automatically users cannot get it back from the Response anymore. I could do tricks like I did in the `RequestLogger` to wrap the entity and make it repeatable, but I am not sure that is a good solution for every single exception. Or maybe just document the different and only way to get the body back. Which one do you prefer?

**Comment by nik9000** [comment]
Normally I'd prefer the simple way, but I think the request logger trick might be a better choice here just because exception messages are so important for debugging and the body is really the best part of the message.

**Comment by javanna** [comment]
I will look into this.

**Comment by nik9000** [comment]
Thanks!
