### ISSUE TITLE
Remove isCreated and isFound from the Java API

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#19631]
Callers can just use `getOperation` instead.

If this were the middle of a release cycle or the methods were very very popular we'd deprecate the methods instead but as is, we can get this in before 5.0 and slot it into the breaking changes list.

Note that if we don't get to this before 5.0 is GA we probably *would* want to deprecate the method instead and remove it in 6.0.

**Comment by nik9000** [comment]
Relates to #19566.

**Comment by nik9000** [comment]
@a2lin are you interested in doing this?

**Comment by a2lin** [comment]
Yes, I will do this.

**Comment by nik9000** [comment]
Awesome! I can't assign it to you so I'll assign it to myself as a stand in.

**Comment by colings86** [comment]
I wonder about this change since we will remove `isCreated` and `isFound` in the Java API here but surely when we move to using only the Java http client we will end up adding these methods back since the REST API has `found` and `created` rather than `operation` in it's response. I am not against this change but it will be annoying for users if we remove these methods only to effectively force them to go back when we deprecate the transport client in favour of the Java http client. /cc @javanna

**Comment by colings86** [comment]
Sorry, ignore the above comment, I hadn't seen that we have just added the `_operation` field to the response of these APIs. Sorry for the noise

**Comment by nik9000** [comment]
> Sorry, ignore the above comment, I hadn't seen that we have just added the _operation field to the response of these APIs. Sorry for the noise

It is cool! We'll have both in 5.0 and in 6.0 we'll drop `found` and `created`. I merged a PR to the docs this morning to explain that they are now deprecated.

I'd also like to rename `_operation` to `operation`. The logic goes: `_` is used for document metadata and `_operation` isn't document metadata.
