### ISSUE TITLE
Restarting a crashed master node can cause deleted indices to show up as unassigned shards

### ISSUE THREAD

**Issue by johnewing1** [elastic/elasticsearch#19658]
**Elasticsearch version**:
2.2.0
**JVM version**:
OpenJDK Runtime Environment (build 1.8.0_91-b14)

**OS version**:
Amazon linux 

Kernel version:
Linux ip-10-51-101-219 3.14.35-28.38.amzn1.x86_64 #1 SMP Wed Mar 11 22:50:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
In a cluster which has a pool of dedicated master servers, if one master server crashes and then subsequently indices are deleted restarting the failed master causes the deleted indices to reappear as unallocated shards.

**Steps to reproduce**:
 1. Induce master server to crash by exhausting heap memory
 2. Wait for election to complete
 3. Delete indices from cluster
 4. Restart failed master node

**Comment by abeyad** [comment]
This is a known issue which we solved in 5.0 by introducing index deletion tombstones, see https://github.com/elastic/elasticsearch/pull/17265.

Basically what happens is, in order to determine index deletions, we compare the current cluster state to the previous cluster state and if there is an index in the previous cluster state that isn't in the current one, we know its an index deletion.  If a node is offline while an index deletion happens, then it comes back online, it has missed the cluster state update that conveyed this deletion, so it instead imports the index as dangling.

Index tombstones solve this problem in 5.0 by explicitly recording index deletions in the cluster state and when a node (re)joins the cluster, we check the tombstones to make sure we don't import dangling indices that should in fact be deleted.
