### ISSUE TITLE
Reindex one index to multiple

### ISSUE THREAD

**Issue by loekvangool** [elastic/elasticsearch#19663]
**Describe the feature**:
Would be great if the Reindex API would support reindexing to multiple indices:

```
GET _cat/indices/logstash-*
logstash

POST /_reindex
{
  "source": {
    "index": "logstash"
  },
  "dest": {
    "index": "logstash-1, logstash-2"
  }
}

GET _cat/indices/logstash-*
logstash
logstash-1
logstash-2
```

**Comment by nik9000** [comment]
Like you want to be able to make two copies in one pass?

**Comment by loekvangool** [comment]
Yeah. I admit it was during testing that I found it, but I think it could be very handy for scripting tasks. Another more abstract point is my desire to have APIs that are predictable, so if something works in [certain APIs](https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-index.html) and not in others, it's annoying.

**Comment by nik9000** [comment]
I don't think we should do this. I don't think many people will want to do it and I think the syntax is confusing. Folks have been asking for some kind of pattern-wise reindex where they can specify multiple source indexes and multiple destination indexes and Elasticsearch just picks the right one. It is still a one for one copy though. We don't have that because we'd have to make assumptions about which index is the right one and I expect we'd be wrong as ofter as we are right. There are two work arounds for that (two reindex commands or using scripts). I think supporting writing to multiple indexes at a time would really confuse the folks that are looking for the pattern-wise reindex. And judging from discuss volume those folks are fairly common.

Also I don't think the consistency of APIs argument holds water. We have lots of APIs that don't allow you to target multiple indexes at once because it doesn't make sense like index, bulk, and update.
