### ISSUE TITLE
Update Shard Request Cache docs for 5.0

### ISSUE THREAD

**Issue by peterskim12** [elastic/elasticsearch#19695]
I believe the Shard Request Cache documentation needs to be updated for 5.0:

https://www.elastic.co/guide/en/elasticsearch/reference/current/shard-request-cache.html

* The doc currently says that queries that include the 'now' time reference point will not be cached. This has changed for 5.x -- queries that include 'now' are now cacheable. (Instant Aggregations feature)
* The doc currently says "The cache is not enabled by default". I believe for 5.x, this cache will be enabled by default. 

There may be additional updates necessary regarding this feature that I'm not aware of, but these are the two that I know of.

**Comment by colings86** [comment]
@peterskim12 queries that contain `now` are mostly still not cacheable. This is something we are working to improve over time but currently only the range query can be rewritten to remove `now` and that only happens if the field range and query range don't overlap (i.e. either they are disjointed or the field range is entirely within the query range). I have updated the documentation for the "The cache is not enabled by default" issue and slightly reworded the warning around queries using `now`.

**Comment by peterskim12** [comment]
Thanks @colings86! Do you think it's worth adding some more details regarding the enhancements around "instant aggregations" or does that make things confusing? The reason why I ask is because currently the blogs are the only place that make reference to this 5.0 enhancement.
