### ISSUE TITLE
Test parameters for external clusters dont work for rest tests

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#19713]
**Elasticsearch version**: master

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
Run tests and specify `-Dtests.rest.cluster=localhost:60000` or `-Dtests.cluster=localhost:60000` and see that those dont have any impact on the cluster being connected to

Our documentation states that this should be possible in [Testing the REST layer](https://github.com/elastic/elasticsearch/blob/master/TESTING.asciidoc#testing-the-rest-layer)

Not sure which one is authoritative here, the functionality or the docs. We should update one of them.

**Comment by rjernst** [comment]
Where did you get `tests.rest.cluster` from? As far as `tests.cluster`, while the integ tests use this internally, it isn't currently something that can be swapped out (the test framework always uses the cluster gradle started). The docs there were a result of find/replace when switching to gradle.

**Comment by spinscale** [comment]
`tests.rest.cluster` is from [ESRestTestCase](https://github.com/elastic/elasticsearch/blob/master/test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java#L90)

**Comment by rjernst** [comment]
Ah, you are right. We do also set `tests.cluster`, but it is unrelated to rest tests (for transport client qa tests). See the comment in `RestIntegTestTask` line 67.

**Comment by nik9000** [comment]
I've used `-Dtests.rest.cluster` to run the REST tests from Eclipse. I'd `gradle run` and then run the tests.

I think `tests.rest.cluster` is a better name anyway because it implies that it is the http address which is useful.

The whole section is fairly out of date now. The test names are wrong because I move the tests and didn't realize they were documented. The properly doesn't work because we rely on gradle to spin up the integration test cluster. We don't use the transport client for test cleanup and setup. We just do it over http.

I can open up a PR to make the documentation accurate again and we can can open an issue after that to decide if the power we have is good enough? For the most part it has been for me but I can't speak for everyone.

**Comment by spinscale** [comment]
Outdated. Closing.
