### ISSUE TITLE
remove memory pool interpretation?

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#19720]
Currently GCNames.java tries to bucket memory pools into "young", "survivor", and "old". If the pool does not match one of the expected names, it drops it (see #19717)

While this model might work for some cases, it doesn't work everywhere, and going forward I don't think its a good idea to try to "dumb down" all the pools, I think it should be up to the application/user to try to do any interpretation.

These names are very implementation-specific, change across versions, and there just isn't always a 1:1 correlation for dumbing down.

With java 7 perhaps we see `PS Perm Gen` but with java 8 we have `Metaspace`.

With shenandoah GC I see only `Shenandoah` gc pool 

With java 8 we have `Code Cache`, but with java 9 it is segmented into 3 codecaches `CodeHeap 'non-methods'`, `CodeHeap 'profiled nmethods'`, `CodeHeap 'non-profiled nmethods'`

Out of box with an IBM JRE I see these pools: `class storage`, `JIT code cache`, `JIT data cache`, `miscellaneous non-heap storage`, `Java heap`.

**Comment by abeyad** [comment]
I'm a bit confused as to why #19717 was not pursued further.  From what I gather, by introducing all kinds of new pools into the stats (pools that were previously suppressed if the name lookup wasn't found in `GcNames`), we have the possibility of unbounded pools and how to serialize that value was the point of contention?

What if we just open a PR that gets rid of `GcNames` entirely, using the "default" `GcThreshold` for young instead of a custom `GcThreshold`, and just using the memory pool name in the stats instead of buckets of "young" and "old"?  And for unbounded values, we can just use Long.MAX_VALUE as a temporary solution to the serialization problem?  That would seem to get us much further along than what we have now and not suppress valuable memory pool stats.

If not, then we probably need to make #19809 a blocker for this one.

**Comment by dakrone** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
