### ISSUE TITLE
ConcurrentModificationException when creating new TransportClient

### ISSUE THREAD

**Issue by itaifrenkel** [elastic/elasticsearch#19724]
**Elasticsearch version**: 2.3.2

**JVM version**: 1.8.0_40

**OS version**: linux ubuntu 12.04

**Description of the problem including expected versus actual behavior**:

We got ConcurrentModificationException in our ci suite sporadicly when creating new Transport Client.

**Steps to reproduce**:
 This  happens if someone modifies System properties while creating new transport client.
We think that System.getProperties() in InternalSettingsPreparer.initializeSettings() should be passed to Settings only after copying it to a new HashMap. we are not calling system.setProperty, but still we are getting this sporadic failure in our ci.

from the elasticsearch code we think that this was fixed in v5 but we didn't validate it since we havent upgraded to v5

**Provide logs (if relevant)**:
java.util.ConcurrentModificationException
	at java.util.Hashtable$Enumerator.next(Hashtable.java:1367) ~[?:1.8.0_40]
	at org.elasticsearch.common.settings.Settings$Builder.putProperties(Settings.java:1096)
	at org.elasticsearch.node.internal.InternalSettingsPreparer.initializeSettings(InternalSettingsPreparer.java:124)
	at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareSettings(InternalSettingsPreparer.java:63)
	at org.elasticsearch.client.transport.TransportClient$Builder.build(TransportClient.java:117)

**Comment by jasontedor** [comment]
This definitely does not exist in master, we've completely removed the system properties and settings entanglement there. I do not think there is a bug in Elasticsearch and I do not think it is worth trying to safeguard against this in the 2.x series. Note that the suggestion to copy isn't even safe, because someone could still concurrently modify system properties while the copy is taking place. The only safe fix is to synchronize the reading of system properties with anyone else that might be setting system properties. I think that this can also arise if your test runner modifies system properties, or if you're doing something like invoking `TimeZone#setDefaultZone` or any other method like that that indirectly modifies a system property.
