### ISSUE TITLE
Allow multi match queries to take fuzzy parameters for individual fields

### ISSUE THREAD

**Issue by leeavital** [elastic/elasticsearch#19732]
I'm performing a multi_match query and I only want one of the fields to be fuzzy-matched.  A possible syntax could be:

```
{
   "multi_match": {
        "query": "foobar",
        "fields": ["name~2", "subtitle^0.4~0"]
   }
}
```

Where `~x` signifies that `x` is the edit distance for that field.

Which would expand into:

```
"dis_max": {
   "queries": [
       { "match": {"name": "foobar", "fuzziness": 2}},
       { "match": {"subtitle": "foobar", "fuzziness": 0, "boost": 0.4}},
    ]
}
```

**Comment by clintongormley** [comment]
I'm against adding this because (1) it's easy to specify separately as you demonstrate and (2) it clashes with the best_fields vs most_fields vs cross_fields, where suddenly we'll need even more complex documentation for an already complex query.

Similar to the reason we split `string` fields into `text` and `keyword` - having simple building blocks which are easy to explain is much more valuable than having one mega-block with too many options.
