### ISSUE TITLE
Bug parsing command line args for java heap

### ISSUE THREAD

**Issue by podollb** [elastic/elasticsearch#19753]
Just downloaded the latest ES 2.3.4 and attempted to start it with command line heap settings (as the docs mention: https://www.elastic.co/guide/en/elasticsearch/guide/current/heap-sizing.html) like this:

> $ ~/Downloads/elasticsearch-2.3.4/bin/elasticsearch -Xmx3g -Xms3g
> ERROR: Parameter [-Xmx3g]does not start with --
> $

Seems like there is a bug in parsing those command line args.

**Comment by jasontedor** [comment]
Those docs are just not correct, I will push a change. You can do `ES_JAVA_OPTS=-Xms10g -Xmx10g` though.

**Comment by podollb** [comment]
There are situations where it would be very helpful to allow passing in the heap settings via command line, so ideally, it would be great if that were still be possible.

**Comment by jasontedor** [comment]
I opened elastic/elasticsearch-definitive-guide#579.

**Comment by jasontedor** [comment]
You can:

```bash
ES_JAVA_OPTS="-Xms10g -Xmx10g" ./bin/elasticsearch
.
.
.
[2016-08-02 12:37:41,809][INFO ][env                      ] [Morgan Le Fay] heap size [9.9gb], compressed ordinary object pointers [true]
```

**Comment by jasontedor** [comment]
Thanks for reporting @podollb.

**Comment by podollb** [comment]
No, I mean there are situations where it's **not** ideal or even possible to use env vars (via your example of `ES_JAVA_OPTS="-Xms10g -Xmx10g"`), for example upstart scripts etc., so allowing command line args to specify the heap (via `-Xmx10g -Xms10g`) is still preferable. Also, this seems to be a breaking change, since older versions of ES could specify those from the command line (so startup scripts, need to be updated/modified, in order to upgrade).

**Comment by jasontedor** [comment]
> No, I mean there are situations where it's **not** ideal or even possible to use env vars (via your example of `ES_JAVA_OPTS="-Xms10g -Xmx10g"`), for example upstart scripts etc., so allowing command line args to specify the heap (via `-Xmx10g -Xms10g`) is still preferable.

In 2.x, the best approach for your situation is to modify the startup scripts themselves (yes, this is unfortunate). In 5.x, the best approach will be to use the jvm.options configuration file, there will not be a need to use environment variables.

> Also, this seems to be a breaking change, since older versions of ES could specify those from the command line (so startup scripts, need to be updated/modified, in order to upgrade).

For the cases that we support (we do not official support upstart), this is not correct. You could just set `ES_HEAP_SIZE` or use `ES_JAVA_OPTS` and upgrading from 1.x to 2.x would go through with no issues. Now from 2.x to 5.x we are breaking this by getting rid of `ES_HEAP_SIZE`. This is so that we can introduce the jvm.options configuration file which *greatly* simplifies this entire situation.

**Comment by podollb** [comment]
Ok. Thanks for the info.
