### ISSUE TITLE
Return the common prefix on completion suggester

### ISSUE THREAD

**Issue by gathanase** [elastic/elasticsearch#19802]
**Describe the feature**:
When using the completion suggester, I would like to get the common prefix of ALL matching results along with the few proposed suggestions. The objective is to automatically *partially* complete input in a form, and make the filling of forms much faster.

For example, let's consider the data ["antibiotic", "antidepressant", "antidote", "circumstance"]
If the user enters "a" in my IHM, I would like the completion-suggester to answer:
<<< all matching suggestions start with "anti", some examples are "antibiotic" or "antidepressant" >>>
Then the IHM may automatically replace "a" with "anti" so the user does not have to write all letters.

**Comment by clintongormley** [comment]
My suspicion is that this would be prohibitively expensive to do as it would greatly increase the number of potential candidates which need to be scored and returned.

@areek what are your thoughts?

**Comment by s1monw** [comment]
it might be possible to automatically expand the given constant prefix by walking the FST. What I am convinced about is that it won't work with filters. in other words I think there might be a longer prefix than the one returned if you use filters since the filter might only allow suggestions with a longer common prefix. I can already see people complain about it so I wonder if we should do it in such a case?

**Comment by s1monw** [comment]
we discussed this in a group and given that we won't be able to implement this correctly especially with deleted document in mind we should't implement this. The internals of the suggester and special cases like this that don't hold with deleted documents confused many users before. if we have a efficient and correct solution to this we can reopen and revisit.
