### ISSUE TITLE
Move scripted_metric agg to a plugin

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#19821]
The `scripted_metric` aggregation is an expert level feature and has its own set of tradeoffs that need to be considered before reaching for it. Due to the fact that it uses scripts it is slow (when compared to other aggregations) especially as the complexity of the scripts increase. It also is not able to support certain functions, for example, you cannot sort a terms aggregation by the `scripted_metric` aggregation.

I think we should therefore move the `scripted_metric` aggregation to a plugin (not a module) so when users reach for it, it is a more explicit that this is an expert level aggregation

**Comment by polyfractal** [comment]
@elastic/es-search-aggs

**Comment by talevy** [comment]
Hi @colings86 it's been a while for this issue. Do you think this is still worth doing?

**Comment by talevy** [comment]
@jimczi let me know that there is a similar issue that there is a duplicate issue for this opened later. Since that issue, although a duplicate, has had more cross-references from other projects (kibana and grafana), then I'll close this in favor of https://github.com/elastic/elasticsearch/issues/63096

**Comment by polyfractal** [comment]
Whoops, I didn't realize we had this one open when I made the other.  My bad!
