### ISSUE TITLE
Searching iWork files

### ISSUE THREAD

**Issue by marbetschar** [elastic/elasticsearch#19965]
Ran into the same issue like @kirka121 over here: https://github.com/elastic/elasticsearch-mapper-attachments/issues/210

Indexing iWorks as part of a future release would be highly appreciated.

**Comment by rmuir** [comment]
I don't think there is anything we can do here: tika needs to support the format first. We enable the `IWorkPackageParser` today already.

Newer Tika has a `IWork13PackageParser`, with the idea to handle newer IWork formats, but it doesn't appear to actually be capable of parsing anything yet: https://github.com/apache/tika/blob/master/tika-parsers/src/main/java/org/apache/tika/parser/iwork/iwana/IWork13PackageParser.java

It seems at the moment, its a WIP, only capable of detecting the format, and the issue is still open (see https://issues.apache.org/jira/browse/TIKA-1358)

**Comment by marbetschar** [comment]
Sad to hear that, but thanks for the feedback anyways!

**Comment by rmuir** [comment]
Well, if you look at the TIKA issue, it seems people are working on it, its just not ready yet.

**Comment by clintongormley** [comment]
Not much we can do here, so closing this issue
