### ISSUE TITLE
ES returns error messages referring to fielddata_fields iso docvalue_fields

### ISSUE THREAD

**Issue by thomasneirynck** [elastic/elasticsearch#20039]
`fielddata_fields` is deprecated in favor of `docvalue_fields` (#19027) in ES 5.

When doing queries with the `docvalue_fields` property, you still may get error messages back that refer to the now deprecated `fielddata_fields`.

Tested on ES 5.0.0-alpha5.

To reproduce:
1) load some logstash data
2) perform following query:

```
GET _search
{
  "query": {
    "match": {
      "extension" : {
            "query" : "jpg",
            "operator" : "and"
        }
    }
  },
  "docvalue_fields": ["extension"]
}
```
3) get back:

```
{
  "took": 24,
  "timed_out": false,
  "_shards": {
    "total": 97,
    "successful": 96,
    "failed": 1,
    "failures": [
      {
        "shard": 0,
        "index": "logstash-0",
        "node": "PvKV4F3qQUuf5VbcAFmoUw",
        "reason": {
          "type": "illegal_argument_exception",
          "reason": "Fielddata is disabled on text fields by default. Set fielddata=true on [extension] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory."
        }
      }
    ]
  },
  "hits": {
    "total": 9072,
    "max_score": 0.43423796,
    "hits": []
  }
}
```

**Comment by jimferenczi** [comment]
I agree this is confusing ;) Though this is expected, the `Fielddata` in the message does not refer to `fieldata_fields` but rather to the fielddata cache. This is stipulated in the docs:

**Note that if the fields parameter specifies fields without docvalues it will try to load the value from the fielddata cache causing the terms for that field to be loaded to memory (cached), which will result in more memory consumption.**

This is what causes the exception in your recreation. The field `extension` is a text field with no docvalues so we try to load the data from the fielddata. This fails because we forbid the loading of fielddata unless you add `fielddata=true` in the field definition.

**Comment by thomasneirynck** [comment]
@jimferenczi thanks!
