### ISSUE TITLE
`update_by_query` with static, partial documents

### ISSUE THREAD

**Issue by marshall007** [elastic/elasticsearch#20135]
We'd like to be able to perform partial updates with a static document using "Update by Query" without having to enable any scripting modules. Are there any plans to support the static `doc` parameter from the "Update" API or is there a reason only scripted updates are supported?

**Comment by clintongormley** [comment]
Mainly because we assumed that doing a scripted update would be much more useful than applying the same change to all the docs matching a query.  This keeps the API a lot simpler than the update API itself.

In 5.0, you could also use an ingest processor to do much the same thing as you can with `doc`.

Could you talk more about your use case?

**Comment by clintongormley** [comment]
@marshall007 but you're applying the same change to many docs?  Surely each doc has its own changes and would be better handled with a bulk request?

**Comment by nik9000** [comment]
I think this kind of thing comes up more when you are working with data that you have to denormalize to get into elasticsearch. If you have a `one-to-many` relationship and you update something on the `one` side and want to push the update into the documents that module the `many` side of the relationship in ES.

**Comment by clintongormley** [comment]
The `update` API today is overburdened with accretions which make it messy, way too many parameters.  I'd like to clean it up at some stage.  This is making me resist adding support for static docs just yet, as I would like the two APIs to be as consistent as possible.

I thought you could use an inline ingest pipeline to achieve this in 5.0, but actually we don't support inline pipelines...

**Comment by marshall007** [comment]
@nik9000 outlined our use-case precisely. Whatever you guys decide on I would definitely be in favor of seeing the two APIs converge. Frankly, it's confusing that the update-specific parameters aren't exactly the same for these two endpoints.

**Comment by bleskes** [comment]
I'm going to close this as now one commented/showed interest since 2016 and it seems to be a problematic feature. Please feel free to voice your interest if needed.

**Comment by aduriseti** [comment]
Would be interested in this feature - found I had to replicate this behavior w/ a script, which was clumsy b/c of lack of reflection in painless.

**Comment by braedon** [comment]
Putting my hand up for this feature as well. It'd be really useful for some batch tasks.

My use case is updating a status field for a set of documents that match a condition. The query selects the appropriate documents, and they all need to be changed in exactly the same way - the status field updated to the new status. It'd be great to be able to do this with a partial document, rather than needing a script.

**Comment by sgurusharan** [comment]
Voting for this feature as well. Apart from keeping the update apis consistent plus there are perfectly valid use cases for the same.

**Comment by joelsemar** [comment]
What a heartbreaking end to this search.

**Comment by aniezurawski** [comment]
> What a heartbreaking end to this search.

Yup. +1 from me. :(
