### ISSUE TITLE
TinkerPop 3 and gremlin support

### ISSUE THREAD

**Issue by jeromatron** [elastic/elasticsearch#20165]
TinkerPop 3 and gremlin (http://tinkerpop.apache.org) are a common api for graph databases to do general traversals over data.  https://github.com/rmagen/unipop tries to provide an abstraction over ES but it would be really nice to have it built in.  It would allow people coming from other graph databases to use the same traversal api.

**Comment by markharwood** [comment]
>  are a common api for graph databases

Yes, I've worked with both in the past and had conversations with the people behind them.

When we looked to put a graph API on top of elasticsearch we felt it wasn't the right abstraction for a variety of reasons:

* We don't want to require that users convert rich business documents into selected "nodes" and "edges"
* We want to use the power of elasticsearch **aggregations** framework to quickly provide `A<->B` summary edges based on potentially millions of docs on the fly
* We want to use elasticsearch **relevance-ranking** features to give prioritized exploration of _relevant_ nodes rather than suffering the typical graph-database issue of quickly getting bogged down in super-nodes.
* We want a simple graph query language with a low barrier for entry to tackle the common use cases.

With these goals in mind Tinkerpop wasn't appropriate.

Tinkerpop is a little like JDBC in terms of its relationship to elasticsearch. It comes from a different, database-oriented, background and while it may be possible to build an API that offers this perspective on elasticsearch it prevents access to some of the powerful features that make elasticsearch different.

Closing but happy to discuss further.
