### ISSUE TITLE
Deterministic implementation of the cardinality aggregation stage for low-cardinality fields

### ISSUE THREAD

**Issue by pfreixes** [elastic/elasticsearch#20178]
Currently ES only supports a none deterministic algorithm called `Hyperloglog++` to compute on query time the cardinality of a field. The implementation claims to work very well for high-cardinality sets with an impact in terms of memory space constant, and configurable through the `precision_threshold`  attribute.

The issue here comes with low-cardinality fields, even thought `Hyperloglog++` claims to work with a excellent accuracy with them also. Current implementation can guarantee - correct me if Im wrong - a zero percentage of errors due the implementation.

The idea here is give to the user, up his responsibility and his own risk, a new implementation based on a determinist algorithm  - such as a hash implementation with collision support or a bitmap with the ordinals of this field- to get always a precision number of the cardinality. Regarding low-cardinality fields with a none high impact in memory.

Some defensive mechanisms can be implemented, such as give an attribute to configure the maximum number of elements allocatable per default, u others.

**Comment by jpountz** [comment]
> Current implementation can guarantee - correct me if Im wrong - a zero percentage of errors due the implementation.

Correct. For the linear counting part (ie. when before reaching the `precision_threshold`), which seems to be what you are interested in, see section 3 of http://dblab.kaist.ac.kr/Prof/pdf/Whang1990%28linear%29.pdf. It cannot guarantee a maximum error but it can give a standard error. You can use 2^25 for `m` in the formulas since the linear counting phase uses 25 bits of each hash value.

>  The idea here is give to the user, up his responsibility and his own risk, a new implementation based on a determinist algorithm - such as a hash implementation with collision support or a bitmap with the ordinals of this field- to get always a precision number of the cardinality. Regarding low-cardinality fields with a none high impact in memory.

It feels like something that can already be done today by using a `terms` aggregation. Say that you think the field has 50 unique elements or less, you could run a `terms` aggregation with both `size` and `shard_size` set to 51. Then on the client side you would count the number of returned buckets. If less than or equal to 50, this gives you the exact cardinality of the field. If 51, then you know the field has 51 unique values or more.

**Comment by pfreixes** [comment]
@jpountz as a workaround it can work for really low-cardinality sets and where it does not rise network issues, even though I was thinking more in low-cardinality sets with 10K or even bigger. 

The contras of the resources consumed for this sort of size vs the pros of get an exact accuracy value are IMHO out of discussion.

**Comment by jpountz** [comment]
> The contras of the resources consumed for this sort of size vs the pros of get an exact accuracy value are IMHO out of discussion.

I disagree, to me it is exactly what this is about. I don't want to expose features that do not scale.

I only see two ways to get accurate cardinalities, either in an offline way where values are streamed to a different node based on a hash of the value, and then sorted and counted before summing up the counts of all involved nodes (very high hanging fruit) or by optimizing the case that the field that the aggregation is computed on was used at index time for routing as suggested in #16433.

**Comment by pfreixes** [comment]
Correct me if Im wrong, just Im landing with the ElasticSearch internals. Your concerns are about introduce features that wont scale horizontally, something that I've already seen in other POSTs. I agree, and its a a sort of rule that it wouldn't be broken.

The global ordinals are a shared structure across the cluster with information about the fields values, as a first impressions looks like it might be used to implement that feature. The results got at each shard should be compatible, and an "easy" intersection would be enough to get the final cardinality.

If this way is reasonable, the footprint in terms of memory used by a bitmap, having it the occurrences of the ordinals in a specific query/aggregation for low-cardinality fields should be handleable.

**Comment by pfreixes** [comment]
I have just realized that the page about cardinality has a graphic with the relative error [1], I guess using a specific random corpus, where you can do the maths. In my environment a 2K field cardinality with a 10K threshold wouldn't get issues at all, only in exceptional cases.

Even though, IMHO There is room to implement a deterministic algorithm for low-cardinality fields instead of a discrete algorithm based on probabilistic and with a logarithmic behavior that penalizes low-cardinality sets.

If it was related with the global ordinals, and due to the needless use of hashing functions the performance should be better than the one used by HyperLogLog++. In terms of size and taking into account the scope of this feature, low-cardinality fields, it might acceptable. Even though hardcode limits could be implemented, having a limit such as the HyperLogLog++ it must afford field cardinalities till 300K different values. 

[1] https://www.elastic.co/guide/en/elasticsearch/reference/current/images/cardinality_error.png

**Comment by polyfractal** [comment]
> The global ordinals are a shared structure across the cluster with information about the fields values, as a first impressions looks like it might be used to implement that feature. The results got at each shard should be compatible, and an "easy" intersection would be enough to get the final cardinality.

Unfortunately, this isn't true.  Each shard constructs it's own set of global ordinals, so "foo" may be mapped to ID#1 on one shard, but ID#100 on another shard.  No easy fix here I'm afraid :(

Also, intersecting global ordinals would only work in the simple case where there isn't any filtering.  Once you start filtering, you can no longer run simple intersections, as multi-valued fields may share terms.  

E.g. if you filter out documents having `title: foo`, you won't know from just the ordinals that a document may have: `{ "title": ["foo", "bar"] }`.  In this situation, you'd mistakenly include "bar" as a distinct value when in reality it was filtered out.  The only way to find this is to run the actual filtering and collect the remaining documents into a Set (or sketch like HLL)

**Comment by pfreixes** [comment]
Let's for the moment leave aside the big issue with the global ordinals as structure only placed per shard.

About the example that you exposed, I thought that the cardinality of a field is the number of unique values of a set of documents filtered or not. If the document `{ "title": ["foo", "bar"] }` becomes part of the set of the documents that will be used as a source for the cardinality aggregation once we run it the `title` value will be used as a source for the algorithm. In that case, the implementation is not important. Im missing something ?

In another level but related to that, there is the multi-value field. Which will be the inputs for HLL u others implementations?  In an ideal world will be two inputs `foo` and `bar` that will compute two different values, in that case the implementation is not important. Im missing something ?

Getting back to the ordinals, let's reduce the range of places where it can be solved to get a deterministic. In my case, the field type is an integer and the domain range is `[0, 100000]`. Map it as a bitmap without optimization will get rough 125K. Therefore an ad-hoc implementation for integer fields is still plausible IMHO.

**Comment by polyfractal** [comment]
> About the example that you exposed, I thought that the cardinality of a field is the number of unique values of a set of documents filtered or not.

That is indeed the definition for the cardinality of the entire field, but you can use the cardinality agg in more scenarios:

Given these two documents:
```json
PUT /test/test/1
{
  "tags": ["foo"],
  "status" : "red"
}

PUT /test/test/2
{
  "tags": ["bar"],
  "status" : "green"
}
```

```json
GET /test/test/_search
{
  "query": {
    "match": {
      "tags": "foo"
    }
  },
  "aggs": {
    "cardinality": {
      "field": "status"
    }
  }
}
```

That aggregation only runs on documents who have the tag `"foo"`, and finds the cardinality of the `status` field.  In this case, the cardinality of `status` is 1 ("red"), while the overall, non-filtered cardinality of `status` is 2 ("green", "red").

That's just a simple example, but applies to many scenarios.  The cardinality agg is often used as a leaf calculation for many bucketing aggs: histograms, date histo, terms, etc.  Those all require filtering/partitioning in a way that the cardinality inside the bucket is different from the overall field's cardinality.

> Which will be the inputs for HLL u others implementations? 

The current implementation offers both values to the HLL sketch (e.g. both are hashed and sketched) as they are independent, distinct values.

> In my case, the field type is an integer and the domain range is [0, 100000]. Map it as a bitmap without optimization will get rough 125K.

The problem is that the feature needs to be general-case, and not everyone can guarantee small bounds like your data.  What would happen if someone used this proposed data structure* on data which had a much greater range?  We don't know cardinality until the agg is run (otherwise we'd just return it), and so there is no way to guarantee the bounds ahead of time.  So the only option is to throw some kind of exception mid-aggregation, or allow the node to OOM.  Neither are good solutions

*_assuming the technical bits could be ironed out, which I don't think are possible with ordinals for the previously mentioned reasons_

**Comment by clintongormley** [comment]
> The problem is that the feature needs to be general-case, and not everyone can guarantee small bounds like your data. 

Or the user puts the cardinality agg under a high cardinality terms agg

**Comment by pfreixes** [comment]
@polyfractal there is no misunderstanding with your explanation, maybe I've explained wrong. The aggregation as I tried to say is performed against the number of the documents belonging to the set documents gathered in an aggregation level. With all of the filters applied until there. Placed as a leaf usually. The implementation of the cardinality algorithm is not important.

Getting back to the ad-hoc case. You are right. The only way to deal with that will be moving from the bitmap to the HLL transparently for the user. Let's guess that it is still an option.

A new option for the `cardinality` agg might be aggregated, something like `try_bitmap`, that will be `False` per default. If the user sets up this field as `True`,  ES will apply the bitmap strategy together with the HLL. The size limit of the bitmap might be hard coded to the same limit that the HLL has - `40k * 8` ?. If some value overflows the bitmap only the HLL will be used. For those queries that are composed by N results from the N nodes, if one node does not send the bitmap the merge will use only the HLL result.

**Comment by polyfractal** [comment]
What you're describing is basically how the cardinality agg already works for fields that have ordinals:  https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/search/aggregations/metrics/cardinality/CardinalityAggregator.java#L96-L101

E.g. If a field has ordinals, and the size of those ordinals won't be drastically larger than the HLL sketch, collect the ordinals directly.  Otherwise, use the HLL sketch (which will first use the linear-counting mode before switching to the approximate, sketching mode).

Note: Ordinals only exist for string fields, so this whole conversation is moot for numerics. :)

**Comment by pfreixes** [comment]
@polyfractal  Amazing I haven't seen it, does it mean that If I would convert the integer field as a string and configuring it as an ordinal ... will I have a deterministic behaviour ? Which should be the maximum  cardinality of the ordinals to assert the previous sentence ?

As I can see the `precission_threshold` is still related to, then the value of the maximum cardinality relates also to the `precission_threshold`. Which cardinality can I expect as maximum with a 40k `precision_threshold`? 

The use of many shards and the merge of the different results gathered from them is an issue ?  If not, in our case that we are routing all data, that will be used for a specific query, to the same shard will help us ?

**Comment by polyfractal** [comment]
Sorry for delay, this fell off my radar.  First, disclaimer that we don't recommend basing data-design decisions off internal implementation details, as those are always subject to change.

Using a string vs number won't change the behavior of approximation.  The difference between the OrdinalCollector and the DirectCollector is just when values are hashed and offered to the HLL sketch; OrdinalCollector caches the ordinals during collection and offers them to HLL at the end, while Direct offers them during collection.

I'm unsure why this distinction is made, but it's likely for performance and reducing temporary memory overhead.  But they both end up in the HLL structure.

I'm going to defer the rest of the discussion to this forum post (https://discuss.elastic.co/t/default-precision-of-cardinality-aggregation/51665/8) which seems to have picked up steam again and covers much of the same material.
