### ISSUE TITLE
Provide better URIBuilder for RestClient

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#20182]
The `URIBuilder` that comes with the `RestClient` (by way of the `HttpClient`) is goofy with how it decides to parse `URI`s, specifically surrounding underscores, which can create a trappy experience. (In fairness, it just wraps the `URI` class itself, but chooses not to workaround any of _its_ weirdness)

This creates a lot of unexpected scenarios, like:

```java
final URIBuilder builder = new URIBuilder("_prefix.domain");

if (builder.getPort() == -1) {
  builder.setPort(9200);
}
```

For starters, the `scheme` is missing and it won't provide it. But more troublesome, is that the `_` will cause the `builder.getHost()` to be `null` and you can't tell that it actually knows what it is _unless_ you build the `URI` and manually parse the `uri.getRawAuthority()`. _Even worse_, the authority will consume the port if it's supplied, so when setting the port, it throws away the authority:

```java
final URIBuilder builder = new URIBuilder("http://_prefix.domain:9200");

if (builder.getPort() == -1) {
  builder.setPort(9200);
}
```

The port _will_ be `-1`, but the authority will be `_prefix.domain:9200`. So, when the code goes along defaulting the port, it will create an invalid URL, which throws an unexpected exception.

**Comment by javanna** [comment]
We don't provide anything to build uris as part of our RestClient, we rather accept instances of `HttpHost`, regardless of how they are created. I think we should keep it that way and go with what java / http client offer as much as possible. Otherwise we will be adding thin layers for a lot of things.

Maybe we should rather improve our docs and our examples on creating uris the right way?

**Comment by nik9000** [comment]
Maybe this is actually the start of a "mid-level" REST client? We have a low level client now. We want a high level client eventually, maybe we end up with mid-level client in the middle that has helpers for generating hosts, bodies, paths, whatever.

**Comment by javanna** [comment]
I was hoping that our n-level REST client would focus on something more interesting than building uris, as there is nothing es specific to that :) there are ways to create uris in java, http client provides a URIBuilder to simplify things, if that one is buggy we can open an issue there rather than working around it on our end maybe?

**Comment by pickypg** [comment]
The idea here was that, users will need to store their connection strings as configurations. With YAML / JSON configs in mind, they will either need an associative array:

```yaml
elasticsearch.host:
  scheme: http
  urls: [ "host1", "host2", "host3" ]
  ports: [ 9200, 9201, 9200 ]
```

or they can just do it in a less trappy way:

```yaml
elasticsearch.hosts: [ "host1", "host2:9201", "host3" ]
```

I think this is pretty basic functionality that, even for a low level client, we should provide.

At this point, I've used it _without_ the `HttpHostBuilder` and the experience left a bit to be desired because I need the configuration aspect and [`URIBuilder` runs into some pretty big walls surrounding host parsing](https://issues.apache.org/jira/browse/HTTPCLIENT-911) and it's by design. I could move this code to my own package, but I think it helps enough to be open source; also the `URIBuilder` does _way_ more than we want because it allows schemes that we don't support, doesn't default the port to 9200, and allows things like paths, which `HttpHost` doesn't use.

**Comment by javanna** [comment]
> or they can just do it in a less trappy way:
> elasticsearch.hosts: [ "host1", "host2:9201", "host3" ]

I agree that this configuration is better, but can we not require the scheme and the port in the configuration for each host and keep it simple? This seems to me something outside the scope of the low level rest client. If we need a bridge between configuration and HttpHost, I am not sure it should be in the low-level RestClient itself.

**Comment by pickypg** [comment]
> can we not require the scheme and the port in the configuration for each host and keep it simple?

We could, but then we're _really_ not providing much of anything to the user. In fairness, we _would_ still be working around the host parsing goofiness for them.

I get that the low-level client is low level (it's in the name :)), but I don't believe that that means it needs to be barebones if it doesn't impact performance in any way. That's why we have the `RestClientBuilder` after all, right? I'm okay just having this code locally, but I think users will really benefit from having it versus not having it.

**Comment by javanna** [comment]
We have the `RestClientBuilder` to build a `RestClient` instance, which is our own class that otherwise would require too many initialization arguments. I am against having a builder for the `HttpHost` as it is not something that we provide. URIs can be created without `URIBuilder` as well, with plain java that doesn't depend on apache http client. It's not about performance, it's about code that needs to be maintained, and I wouldn't want our users to need our own class to create a URI instance. I hope this explains it better. I will mark this for discussion so we can discuss this on next fixitfriday, then I will go with whatever the team decides :)

**Comment by s1monw** [comment]
I really think this is a pretty esoteric problem you have there with `_` as a first char. I think if there are problems they should be addressed upstream and we should use what comes from http-client.
