### ISSUE TITLE
Accessing data in _source field

### ISSUE THREAD

**Issue by kalyc** [elastic/elasticsearch#20352]
**Elasticsearch version**: 1.7

I am building a custom plugin that uses single value aggregation in ElasticSearch. 
Currently I aggregated analyzed text as the data and would like to use the raw text instead. I know that _source field stores the raw text. Is there any way that I can access it directly in the plugin - without having to create a separate "raw" field?  

Any help on how should I go about fetching that data would be appreciated!

**Comment by nik9000** [comment]
We like to keep github issue for actual features and bugs and have discussions like this on discuss.elastic.co.

That being said 1.7 is very old given the pace at which Elasticsearch moves. A lot has changed since then. Have a look at how the highlighters get access to the _source. You can also look at how the fetch phase works.
