### ISSUE TITLE
Add option to take structure of source index for destination index in Reindex API

### ISSUE THREAD

**Issue by dobariya** [elastic/elasticsearch#20465]
I was trying Reindex API and found that if destination index is not available then it will create a new index with auto mapping,settings etc.If possible can we have an option asking whether to use source index structure for new index.So if the destination is not available then it will directly create the new index with full source index structure

Thanks

**Comment by s1monw** [comment]
@dobariya I am not sure if we should do this since your source index will likely have legacy mappings and settings? You should rather work with templates or create the structure yourself? Maybe we should warn you instead and ask if we should auto-create the index unless specified ie. fail the reindex if the target doesn't exist?

**Comment by bleskes** [comment]
apart for playing around, what is your use case for this? typically one would reindex because they need to upgrade something/change settings etc.  Also, you need to be aware then when not locking your mapping new mapping may be introduced between the creation of the target index and when the scroll search of the reindex process starts making this not a completely trivial feature to add.

**Comment by dobariya** [comment]
@bleskes :I have a huge index around 100 million but from that we only need some documents to play around.To get those some documents i would need to apply filter every time rather i thought to create a new index and put those some documents using reindex api so this way i will only have few documents and will not have to search on entire index.

**Comment by bleskes** [comment]
hmm. makes sense although, since it's just a simple one liner in any script language to get the mapping and create a new index with it, I'm not sure it's worth making the reindex API more complex. Note that you also almost surely want to change the number of shards of the target index if it's going to be small.

**Comment by s1monw** [comment]
@dobariya I wonder if it makes sense to allow to clone and index without data ie. pimp the create index API. I really think that's a better primitive and you can just call this with source and target index name before you fire off reindex?

**Comment by bleskes** [comment]
@s1monw I thought about that too, and we can do - but I think it should have the semantics of take the given index setting as a template and apply the given request on top of it (so you can change things like number of shards).

**Comment by s1monw** [comment]
@bleskes that is bascially what `_shrink` does. I think we can generalize it

**Comment by dobariya** [comment]
@bleskes yes we can also have option to give shard size if its small.So can i conclude we are getting this update?

**Comment by nik9000** [comment]
> @bleskes yes we can also have option to give shard size if its small

Stuff like this is why I'm weary adding a general "make a new index with this index's settings". It is really "make a new index with this index's setting except these three settings". I feel like lots of folks are going to have a different list of three things and they are better off just making the index themselves.

> Maybe we should warn you instead and ask if we should auto-create the index unless specified ie. fail the reindex if the target doesn't exist?

I like this idea.

**Comment by clintongormley** [comment]
What about:

    PUT {new_index}/_from/{old_index}
    ... any settings, mapping, alias overrides...

This API would also delete the old version created, index uuid, etc settings

**Comment by dobariya** [comment]
yes this makes sense

**Comment by s1monw** [comment]
we spoke about this in fixit - FRYday :) and we agreed that having this option to auto-create an index from another index or copy settings / mappings is beyond the point. If you reindex you usually want to change something (mappings or settings) or you migrate from an old version. You also have templates in place to get mappings right OR you have a way to create your indices. I feel we have enough primitives in place to allow users to create indices easily. We also discussed and agreed that reindex should not automatically create an index but make it mandatory that this index exists. @nik9000 do you want me to open an issue?
