### ISSUE TITLE
attachment-mapper plugin fails for zip files

### ISSUE THREAD

**Issue by chindhuhari** [elastic/elasticsearch#20510]
**Elasticsearch version**: 2.3.6

**Plugins installed**: [mapper-attachments]

**JVM version**:1.8

**OS version**:Windows 7

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Run elasticsearch with attachment-mapper plugin
 2. Give a zip file as input to parse
 3. Gives an error

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by dadoonet** [comment]
The mapper attachment plugin does not support "crawling" inside ZIP files.
[The doc](https://www.elastic.co/guide/en/elasticsearch/plugins/current/mapper-attachments.html) says:

> The mapper attachments plugin lets Elasticsearch index file attachments in common formats (such as PPT, XLS, PDF)

BTW mapper attachments has been deprecated so we are not going to implement such a feature in it.
I don't believe we will do it in ingest-attachment. This is something you should deal with in your application layer.

Unzip, then for each file, send it to elasticsearch.

As the developer of the community project [FSCrawler](https://github.com/dadoonet/fscrawler), I think this is something which could be supported while crawling the filesystem. I opened https://github.com/dadoonet/fscrawler/issues/230 for this.

Closing this one as this won't be implemented.

**Comment by chindhuhari** [comment]
Thank you !
When we don't pass the subset of PARSERS to the AutoDetectParser, it works fine for zip files as 
well (in TikaImpl.java):
 _private static final AutoDetectParser PARSER_INSTANCE = new AutoDetectParser();_ 

Tried explicitly adding RecursiveParserWrapper in the list of PARSERS, that didn't work though.

**Comment by dadoonet** [comment]
Sorry for the late reply.

Yes. I believe we decided to support the most common patterns with the least cost in term of memory usage, CPU usage on elasticsearch side because overloading the index process (analyze part, mapping part) is definitely something we don't want to have. Plus security concerns
Furthermore, we decided to add dedicated ingest nodes which are responsible for doing that.
But, ingest-attachment does not support ZIP files as well and IMO it's good we don't support it.
Imagine you have one single ZIP containing 100 of PDF documents. If you index the content of 100 PDF documents inside a single Elasticsearch document, how the end user will know where to find the exact document?

I think this is something which must be solved on the client side. So on client side:

* Unzip the file
* For each file of the ZIP file create a JSON doc like
```json
{
  "parent_filename": "name of the zip.zip",
  "filename": "the internal file name within the ZIP",
  "content": "the BASE64 content"
}
```
* Send this JSON doc to elasticsearch (using mapper-attachments) or better, send it to an ingest pipeline which uses ingest-attachment

I hope this helps
