### ISSUE TITLE
`_flush` fails the replica shards in the case of an uncaught exception

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#20569]
Today we use TransportReplicationAction to flush a shard. Yet, this is problematic
since a shard might throw an exception that is just fine to catch and continue and should never
result in failing a shard. If a fatal exception happens that should fail the shard this happen on
the engine level. In contrast to write actions we should never fail a shards in such a situation.

This is a blocker for me since `_flush` should never fail a shard unless the engine decides to.

**Comment by s1monw** [comment]
apparently this is also in 2.x

**Comment by bleskes** [comment]
There is a couple of things at work here.

Most importantly, a flush request on a shard now may throw a `FlushNotAllowedEngineException` if the shard is already flushing. This will cause unneeded shard failing as the primary will fail the replica (as is the standard logic for TRA).

Second, the reason flush is a TRA is because we have seen it in the past as a "better refresh" when and move it to TRA when we moved refresh to inherit from TRA.  Refresh needs to be part of the TRA logic in order to honor the sequence `write, refresh, search` and guarantee that the docs in the write are returned.

The logic in TRA is such that any operation that failed on a replica, doesn't matter why, means that the replica is not a good copy of the current states of the replication group. Normally this means it misses some documents but, with the current hard semantics of refresh, failing to refresh quanitfies to the same thing.

IMO we can choose to do any of the following:

1) Reduce the chance of flush hitting exceptions on replicas by:
   1a) catching the `FlushNotAllowedEngineException` in `TransportFlushAction` and ignoring it (we should change the docs of the flush action here)
   1b)  remove the `wait_if_ongoing` flag from FlushRequest and make it always wait.
2) Change the semantics of `flush` to not be a superset of refresh and either move it from TRA or relax TRA's requirements for it.
3) If needed, relax the requirement of `refresh` & `flush`.

I'm in favor of 1b for 5.0. 2.x is better served  with 1a .

**Comment by s1monw** [comment]
I don't understand what guarantees you are talking about. The `_flush` doesn't have any visibility guarantees. It's only flush. We just don't need to fail the replica on flush? We can then just let exception reporting happen. I am also leaning towards always block but I think failing a replica on flush it the engines job and should not happen on such a high level

**Comment by s1monw** [comment]
>  Change the semantics of flush to not be a superset of refresh and either move it from TRA or relax TRA's requirements for it.

why is flush a superset of refresh? can you explain?

**Comment by bleskes** [comment]
> why is flush a superset of refresh? can you explain?

That's a good question. If I remember correctly, the argument was that if you see flush as "take everything you have and make lucene segments out of it" it also implies making it visible for searchers.  If see it as just "persist data and trim translog" it doesn't have to imply refresh imo. I'm good with both.

**Comment by s1monw** [comment]
>  it also implies making it visible for searchers. 

this is not true, you have to call `_refresh` to make it visible. 

Refresh:
 * write all segments to disk
 * reopen the lucene index reader
 * swap the new reader in

Flush:
 * write all segments to disk
 * fsync them

but even if we'd be a super set I'd argue that if a refresh fails it's the engines job to decide if the exception was fatal (btw. any exception in InternalEngine#refresh()) is fatal. So in TRA the only think we should do is either report to the user or retry (we know exactly when we can retry) the shard failure is the engines job. The only exception here is `TransportWriteAction` since it can make assumptions of consistency.
