### ISSUE TITLE
Installation issue in windows 10

### ISSUE THREAD

**Issue by BWdemo** [elastic/elasticsearch#20595]
I am trying to install elastic search 2.4.0 in windows 10. It showing the following error: Exception in thread "main" java.lang.NoSuchFieldError: LUCENE_5_4_1
        at org.elasticsearch.Version.<clinit>(Version.java:287)
        at org.elasticsearch.bootstrap.Bootstrap.<init>(Bootstrap.java:65)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:249)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.

I surfed and not getting any related results. I don't know how to resolve it.

Please help me.

**Comment by cbuescher** [comment]
This looks like there is some issue with your setup. My first guess would be you are installing over an older version of ES and there are mixed versions of the lucene somehere in your lib folder or on the classpath. I'm closing this because Elastic reserves GitHub for bug reports and feature requests, but you can get help if you ask this kind of question in the [discussion forum](https://discuss.elastic.co/) or the [IRC channels](https://www.elastic.co/community).
