### ISSUE TITLE
JarHell is too restrictive and limiting plugins features

### ISSUE THREAD

**Issue by hbs** [elastic/elasticsearch#20649]
**Elasticsearch version**:

2.4.0

**Plugins installed**: []

**JVM version**:

1.8

**OS version**:

all

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Create a plugin which needs to run Mustache compiler 0.9.1
 2. Attempt to launch ES
 3. Cry

**Provide logs (if relevant)**:

**Describe the feature**:

JarHell checks many things and it can be very helpful for identifying possible problems, but in some cases the identifies problems should be tolerated and JarHell should not abort ES launch.

This is particularly annoying for plugins which have their own classloaders and therefore do not cause any problem to the parent's CL.

**Comment by dadoonet** [comment]
Can you also add the logs output?

**Comment by martijnvg** [comment]
This is because the mustache dependency is part of core and is in the parent classloader. In 5.0 this dependency is part of of `lang-mustache` and a plugin should be free to use its own version of  mustache.

Having said that, we will not allow running ES without this check in place. In order to avoid unexpected behaviour at runtime, we require JarHell to fail node startup if it identifies the same classes in different jar files.

**Comment by hbs** [comment]
This last comment seems to defy the purpose of class loaders! Of course an identical class can be at several places in the class path, that's what class loaders hierarchies are for!

What's the point of loading plugins in their own class loader if they cannot have their own private version of a class present elsewhere in their parent class loader's class path?

Can you elaborate on what you are trying to protect the plugins from?
