### ISSUE TITLE
Replace `action.auto_create_index` with a template setting

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#20640]
In https://github.com/elastic/elasticsearch/issues/9359 we discussed the possibility of extending the `action.auto_create_index` setting to automatically recognise index names which match templates, and to allow those to be auto-created without having to maintain both the template and the setting.

In FixitFriday we came up with a better solution:
- Remove the `action.auto_create_index` setting
- Add an `auto_create_index` setting to index templates - if true, then an index can be auto-created
- Ship with a default match `*` index with `auto_create_index: true` - this can be overridden by the user
- If multiple templates match, the `auto_create_index` setting is merged just like all other template settings - the highest `order` wins

When upgrading, the user will see an exception if they set `action.auto_create_index` and will need to update their templates to reflect the same logic.

Possibly, we could add a deprecation period where the `action.auto_create_index` setting continues to work, but also accepts a `_template` value which switches to use the template-based logic instead.

**Comment by jamshid** [comment]
This would be a great feature, any chance?
I want the convenience of automatically creating an index but only if the cluster has the template defining the settings and schema that my application needs.

**Comment by gwbrown** [comment]
We discussed https://github.com/elastic/elasticsearch/issues/56369 in today's Fix-It meeting, and came to the conclusion that the proposal in this issue is closer to what we want to do that the one described in https://github.com/elastic/elasticsearch/issues/56369.

There are some new considerations, however. In particular, the suggestion of a wildcard template (`"index_patterns" : ["*"]`) with the setting to allow auto-creation as a means of backwards compatibility is not possible with the new component/composable templates. Because of this, the latest thinking on this is that we should implement a flag for component/composable templates which overrides `action.auto_create_index`. This way, most cases will continue to use the behavior of `action.auto_create_index`, but we can ensure that our internal indices will be able to be auto-created as necessary.

With this proposal, we have the option of deprecating and removing `action.auto_create_index`, but per our discussion today we are likely to allow them to coexist, with the index template flag overriding `action.auto_create_index`.
