### ISSUE TITLE
[Help] Cant change port config

### ISSUE THREAD

**Issue by SFzxc** [elastic/elasticsearch#20714]
**Elasticsearch version**:
elasticsearch-2.4.1.zip
**Plugins installed**: []
none
**JVM version**:
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
**OS version**:
Ubuntu 104.0.1

**Description:
I just install last version of elastic. Work well on port 9200. But when i change to 9300. It not working
 ~ curl http://127.0.0.1:9300
curl: (7) Failed to connect to 127.0.0.1 port 9300: Connection refused
Bonus: I tried change to 9201. It worked. But i need 9300. Anyone can help me. Thanks you

**Comment by bohyun-e** [comment]
Are you seeing the 'Address already in use' error? If so, this is because there is a conflict with `transport.tcp.port` parameter which we ship defaulted at 9300. If you want to set the custom port number to 9300 then try the following in your `elasticsearch.yml`:

`http.port: 9300`
`transport.tcp.port: 9400`

https://www.elastic.co/guide/en/elasticsearch/reference/2.4/modules-transport.html#_tcp_transport

[Note] If you're using Kibana with your Elasticsearch, make sure to change the following parameter in `kibana.yml` as below:

`elasticsearch.url: "http://localhost:9300"`

**Comment by jasontedor** [comment]
Elastic reserves GitHub for bug reports and feature requests; general help can be obtained on the [Elastic Discourse forum](https://discuss.elastic.co).
