### ISSUE TITLE
Note that Filedescriptors cannot be configured on Windows

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch#20732]
**Elasticsearch version**: current

In the docs section on [configuration -> file-descriptors](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration.html#file-descriptors) it is not mentioned that Windows does not have filedescriptor limits.  This may confuse Windows users when this cannot be configured on their systems.

**Comment by nik9000** [comment]
I spend a bit of time tracking this down - the reason this isn't an issue on windows is because the JDK uses [`CreateFileW`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363858(v=vs.85).aspx) on Windows which [looks](https://blogs.technet.microsoft.com/markrussinovich/2009/09/29/pushing-the-limits-of-windows-handles/) like the default limit is about 16 million which is plenty.

We don't check the maximum number of open files on Windows for this reason. I'll go an update the docs about this now.
