### ISSUE TITLE
geopoints type issue

### ISSUE THREAD

**Issue by Vikas-** [elastic/elasticsearch#20782]
I am replicating data from couchbase to elasticsearch using xdcr. While indexing couchbase is creating type for fields automatically as string. I want location field, to be used as a geopoint type. It seems, type can't be changed after the data is replicated. Is there any work around for this?
Thank you.

**Comment by eskibars** [comment]
You can't change the types of fields after they've been indexed.  You could potentially set up a new index with different types and then run a [reindex](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/docs-reindex.html) on the existing documents/index.

I'm going to close this out because it sounds like everything is fine in the elasticsearch here.  If there's something couchbase is doing wrong when pushing data into elasticsearch, you may want to file an issue with them.  For general purpose questions and troubleshooting, you can use [our discuss forums](https://discuss.elastic.co/c/elasticsearch).
