### ISSUE TITLE
Create S3 repository tests that test against a real S3 bucket

### ISSUE THREAD

**Issue by abeyad** [elastic/elasticsearch#20862]
Right now, the `repository-s3` plugin relies on tests that mocks the `AmazonS3` client.  However, this is a limited form of testing that does not bring to light issues one would find when interacting with the real Amazon SDK connecting to a real S3 repository.  Such tests are essential in uncovering even basic issues of interaction between our integration and the Amazon SDK.  As an example, see https://github.com/elastic/elasticsearch/pull/20861 which would have been uncovered with such tests.

**Comment by tlrx** [comment]
This issue is still a valid issue. We plan to create better integration tests for repository plugins using fixtures (we started the work with Google Cloud Storage in #28788) that will help to catch more bugs.

Once those tests are available, we'd like to be able to run them against a local fixture or against the real service.

**Comment by tlrx** [comment]
Closed by #29372
