### ISSUE TITLE
Add `max_concurrent_searches` to msearch-template

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#20912]
Multi-search supports the `max_concurrent_searches` QS parameter, but this is missing from the `/_msearch/template` endpoint:

```
PUT test/foo/1
{"user":"john"}

GET _msearch/template?max_concurrent_searches=1
{"index": "test"}
{"inline": {"query": {"match":  {"user" : "{{username}}" }}}, "params": {"username": "john"}} 

```

throws:

```
"request [/_msearch/template] contains unrecognized parameter: [max_concurrent_searches]"
```

**Comment by williamw1994** [comment]
Is this issue still there? I have seen the pull request is showing "This branch has conflicts that must be resolved". So it means this PR hasn't accepted yet. Would you mind if I taking over and fix the issue there?

**Comment by nik9000** [comment]
To be honest that PR looks pretty close. @martijnvg, would you like to adopt the PR?

**Comment by williamw1994** [comment]
I can try working on this issue now, would it be okay to assign this to me?

**Comment by martijnvg** [comment]
@nik9000 That PR only adds the setting to the request and request builder. Now I think about this more I think we shouldn't try to duplicate the `max_concurrent_searches` logic in this api, but rather duplicate the templating logic from the search template api. This `max_concurrent_searches` logic has turned out to be [pretty](https://github.com/elastic/elasticsearch/pull/23527) [tricky](https://github.com/elastic/elasticsearch/pull/23538).
