### ISSUE TITLE
SearchSourceBuilder not working for count

### ISSUE THREAD

**Issue by arosenheinrich** [elastic/elasticsearch#20969]
Beginning from 5.0.0-beta1 SearchSourceBuilder adds an "ext" field. This way count queries can not work with queries generated using SearchSourceBuilder as ext is not supported. 

Empty query by just creating new SearchSourceBuilder looks now like this:

{
  "ext": {}
}

_search will return results, _count will return 

{
  "error": {
    "root_cause": [
      {
        "type": "parsing_exception",
        "reason": "request does not support [ext]",
        "line": 2,
        "col": 3
      }
    ],
    "type": "parsing_exception",
    "reason": "request does not support [ext]",
    "line": 2,
    "col": 3
  },
  "status": 400
}

**Comment by clintongormley** [comment]
@javanna could you take a look at this please?

**Comment by javanna** [comment]
hi @arosenheinrich , thanks for opening this issue, sorry it took me a while to have a look at it. 

I see that we should probably not print out an empty `ext` object all the time, which I am going to address. That said I think you see this because you are sending via REST what gets generated through `SearchSourceBuilder`, is that right? If you use the Java API, you are one step ahead compared to other clients, parsing doesn't happen as you are already providing the parsed objects that will be sent around using the transport layer, hence it doesn't matter what the json representation of what you send is. That is why I don't expect this to be a problem in the Java API, but only in case you use SearchSourceBuilder to generate json that you then sent via REST layer. I'd appreciate if you can confirm this.

**Comment by arosenheinrich** [comment]
Indeed we are using the REST API here. Thanks for fixing it!
