### ISSUE TITLE
Documentation lost "when to use upgrade API"

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch#20963]
The [current docs for the upgrade API](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-upgrade.html) are missing the section "When to use upgrade API" which was in the [2.0 version of the page](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/indices-upgrade.html).  This section is very informative / helpful and IMO should be returned to the current version of the page.

**Comment by clintongormley** [comment]
@robin13 they weren't lost but were deleted on purpose.  and in 5.0, i've removed the documentation for the upgrade API because it is essentially flawed.  You need to use the reindex API instead.  I've added docs explaining why and how to the upgrade section: https://www.elastic.co/guide/en/elasticsearch/reference/5.0/reindex-upgrade.html

**Comment by robin13** [comment]
But if the upgrade API is essentially flawed, then perhaps _that_ should be noted on the current upgrade API docs page?  I find the current page of the upgrade API incomplete as it is not clear what it should be used for, and how/where it is different from doing a reindex.

**Comment by clintongormley** [comment]
I've opened https://github.com/elastic/elasticsearch/issues/21337 to remove the upgrade API
