### ISSUE TITLE
Template Ordering Results in Inheritance of Incompatible Setting

### ISSUE THREAD

**Issue by gingerwizard** [elastic/elasticsearch#20988]
**5.0 rc1**:

**1.8.0_60**:

**OSX**:

It seems incompatible settings can be inherited as the result of template merging. A setting can come from a lower order template that is not compatible with the new field configuration in a higher order template. The example considers keyword and text fields for the setting "ignore_above".

I believe the issue has been resolved in https://github.com/elastic/elasticsearch/pull/20630 which adds better merging.  However, can we do something more intelligent on the merging? It seems like users would like to be able to override the type.

```
DELETE test1

PUT /_template/template_1
{
  "template": "test1",
  "order" : 10,
  "mappings": {
    "test_type": {
      "properties": {
        "test_field": {
          "type": "keyword",
          "ignore_above": 10
        }
      }
    }
  }
}

PUT /_template/template_2
{
  "template": "test1",
  "order" : 11,
  "mappings": {
    "test_type": {
      "properties": {
        "test_field": {
          "type": "text"
        }
      }
    }
  }
}

POST test1/test_type
{
  "test_field": "foo"
}

GET test1/_mapping
```

**Comment by jpountz** [comment]
I agree it's not nice, and it would be nice to fix it. However, template merging works at the json level and doesn't know about mappings, settings, etc. it just recursively merges objects. So that would not be an easy fix.

**Comment by hub-cap** [comment]
This feature request is an interesting idea but since its opening we have not seen enough feedback that it is a feature we should pursue. We prefer to close this issue as a clear indication that we are not going to work on this at this time. We are always open to reconsidering this in the future based on compelling feedback; despite this issue being closed please feel free to leave feedback on the proposal (including +1s).
