### ISSUE TITLE
Integer mappings allow JSON strings to be returned rather than JSON integers

### ISSUE THREAD

**Issue by renewooller** [elastic/elasticsearch#21052]
**Elasticsearch version**:

2.4

**Plugins installed**: [Shovel, management]

**JVM version**:
 jdk-8

**OS version**:
(running on the official elasticsearch:2.4 docker image)

**Description of the problem including expected versus actual behavior**:

If the field mapping is an integer type,  I would have expected the integers retrieved to be returned as JSON integer types. Actual behaviour is that JSON string types can be returned. 

**Steps to reproduce**:

1. create an index with an integer mapping:

    curl -XPUT 'http://localhost:9200/shmap/' -d '{
        "settings" : {
            "number_of_shards" : 1,
            "number_of_replicas" : 0
        },
        "mappings" : {
            "type" : {
                "dynamic" : false,
                "properties" : {
                    "shint" : { 
                        "type" : "integer", 
                    }
                }
            }
        }
    }'

2. insert a string that is made of integers:

    curl -XPOST 'http://localhost:9200/shmap/type' -d '{
        "shint" : "00000001"    
    }'

3. Get it back. Note that the string is still a string, even though the type is integer:

    {"took":1,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":1,"max_score":1.0,"hits":[{"_index":"shmap","_type":"type","_id":"AVfgtbAbNiGlzqOiG3dD","_score":1.0,"_source":{
        "shint" : "00000001"    
    }}]}}

**Comment by dadoonet** [comment]
Elasticsearch never modifies your source document and stores it as is.
Not an issue here.

The thing is that 0001 can be parsed as a number so it's not rejected.

Change your mapping and store the field. The search and ask for this field instead of _source and you will hopefully see the numerical form.

**Comment by renewooller** [comment]
FYI, asking for field is still not returned as a JSON number, but as a JSON string eg:

http://dev-es.nightlifr.com:9200/shmap/type/_search?q=*:*&fields=shint

```
{
took: 1,
timed_out: false,
_shards: {
total: 1,
successful: 1,
failed: 0
},
hits: {
total: 1,
max_score: 1,
hits: [
{
_index: "shmap",
_type: "type",
_id: "AVfkZpuVNiGlzqOiHCLg",
_score: 1,
fields: {
shint: [
"00000001"
]
}
}
]
}
}
```
 
I understand that the source document is never changed, but is nonetheless seems wrong that if a mapping is an integer, it is returned back as a string.

**Comment by jpountz** [comment]
If you need these fields to be returned as numbers, then they would have to be provided as numbers at ingestion time too. If you want to reject such values, you could specify `coerce: false` in your mappings.

Side note: Elasticsearch 5.0 will have the ability to do conversions at index time so that numbers-as-strings can be converted to proper numbers at index time: https://www.elastic.co/guide/en/elasticsearch/reference/master/convert-processor.html.
