### ISSUE TITLE
histogram pipeline aggregation

### ISSUE THREAD

**Issue by bukzor** [elastic/elasticsearch#21097]
**Describe the feature**:

We want to compute a histogram of data that's only derivable via aggregation.

Would it be feasible to add this as a new pipeline aggregation, or is there already a better way to do this?

**Comment by bukzor** [comment]
I'm interested in providing this patch, but it was unclear from reading the code whether or not this is possible.

**Comment by eskibars** [comment]
Can you provide a bit more detail about what you'd like to do, e.g. an example?

**Comment by bukzor** [comment]
I have a first-tier aggregation which gives me a mailing from name to
status for 90000 buckets. This is too big to transfer in its entirety in
JSON, so I'd like to get a summary which makes status to count. I'd call
this second-tier aggregation a histogram, and currently there's no way to
implement such a thing, as it'd need to be a pipeline aggregation.

**Comment by bukzor** [comment]
I described my use case in detail on the forum, here 

https://discuss.elastic.co/t/pipelined-histogram-aggregation/63783/5

**Comment by markharwood** [comment]
Closing for same reasons as https://github.com/elastic/elasticsearch/issues/17590 and https://github.com/elastic/elasticsearch/issues/22537 
The recurring anti-pattern is that terms aggregations are being (ab)used to join related distributed data on very high-cardinality fields as a a form of mass data gathering and then the feature request is for some form of pipeline aggregation on the coordinating node to summarise this gathered state. 
This form of query-time fusion is not scalable and in each of these high-cardinality cases we advocate using entity-centric indexes - the data fusion costs are paid as a tax on each change of data rather than as a single bulk cost hitting every query.
