### ISSUE TITLE
Docs Rollover API - what happens when incremental number is exceeded?

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch#21104]
In the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-rollover-index.html#_naming_the_new_index) there is not currently any details what happens when the (admittedly large) 6 character number rolls over 999999.  It's unlikely, but we should know what happens: does it roll over to 000000 again (and succeed if that index has been deleted in the mean time), or throw an error?

**Comment by s1monw** [comment]
![boom](http://i.giphy.com/O3GqAYR9jFxLi.gif)

**Comment by clintongormley** [comment]
The docs say that the number is zero padded up to length 6, so after that the number will have length 7 etc

**Comment by jszwedko** [comment]
The docs are perhaps technically accurate, but I had the same question. I think it'd be useful to make that more explicit.

This also leaves the question of "is there a max suffix for the rollover API?" The answer to that question appears to be `Integer.MAX_VALUE` (https://github.com/elastic/elasticsearch/blob/e4391afd98c99e05ce1ca2163d1a096a0405d72b/server/src/main/java/org/elasticsearch/action/admin/indices/rollover/TransportRolloverAction.java#L232). I believe the rollover will blow up at that point since currently it looks for the last `-`. E.g. when rolling an index of `foobar-2147483647` you will end up with `foobar--2147483648` which the parser will pull `2147483648` off of and try to parse as an `int` causing a `java.lang.NumberFormatException`.

Admittedly an extreme edge case, but I'm wondering if ES should handle that behavior explicitly. Or at the least use a `long` which makes it an even more extreme edge case.
