### ISSUE TITLE
Elasticsearch don't work as service in Windows Service 2012R2

### ISSUE THREAD

**Issue by santiblanko** [elastic/elasticsearch#21183]
**Elasticsearch version**: 5.0

**Plugins installed**: []

**JVM version**: 1.8.011

**OS version**: Windows Server 2012

**Description of the problem including expected versus actual behavior**: I try to install elasticsearch as service in windows server 2012R2 and I can't.

**Steps to reproduce**:
1. Download JAVA and set the config in the system path
2. Download elasticsearch v5 from your servers.
3. Go to the bin folder
4. Execute this command
   `elasticsearch-service.bat install`
5. Execute this other command
   `elasticsearch-service.bat start`

I try this procedure in multiples computers and it´s fails.

**Comment by jasontedor** [comment]
> I try to install elasticsearch as service in windows server 2012R2 and I can't.

We can not help you if you do not provide a more detailed explanation of the problem that you're experiencing.

Either way, I am able to install and start the service just find on Windows so I suspect something environmental on your end. For example, do you have `JAVA_HOME` set properly?

Since Elastic reserves GitHub for verified bug reports and feature requests, I'm going to close this issue and direct you to the [Elastic Discourse forum](https://discuss.elastic.co) which is provided for support for general end-user questions.
