### ISSUE TITLE
_cat/thread_pool should output "unbounded" for null queue_size

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#21187]
_cat/thread_pool should output "unbounded" for null queue_size because the empty string it outputs now looks like an error.

https://discuss.elastic.co/t/bug-monitoring-the-queue-size-of-thread-pool-is-not-working-on-elasticsearch-5-0-0-release/63979

**Comment by colings86** [comment]
Discussed in FixItFriday and we said that we would like this change but would prefer to use `-1` instead of `unbounded` because:

* Its in line with the setting values where `-1` means unbounded
* It means that a script reading the `_cat` API doesn't need to worry about the possibility for getting a non-numeric value for these columns

**Comment by jasontedor** [comment]
Closed by #21342
