### ISSUE TITLE
Allow _source access in search query with Painless

### ISSUE THREAD

**Issue by nicolasgarfinkiel** [elastic/elasticsearch#21188]
I understand `doc_values` access is way faster than `_source`, that most use cases deal with values already in `doc_values`, and some features require hard limits for safety's sake.

What I don't understand is the call for blocking a feature because it is not as performant as another feature. Painless works inline as is, and it is very useful for ad_hoc querying. It is stupid to store a groovy query for a quick question and unsafe to allow it to run inline.

It is valid to need a quick answer from a `_source` field that is not indexed because it is usually not needed at query time for an app but that sometimes you need to check.

Why don't let the user worry about the consequences? In a SQL database you can easily blow it by issuing a simple `SELECT`, but you can issue it anyways.

**Comment by jpountz** [comment]
What is the use-case that you can solve with `_source` that you cannot solve with doc values? I'm reluctant to expose `_source` in painless but maybe there are other improvements we can make so that `_source` access would not be needed.

**Comment by nicolasgarfinkiel** [comment]
I have a lot of fields that I don't index because I never search for them as per my application needs, but of course I need them when retrieving the document source either by search or get. That saves me a lot of indexing and storage resources.

But for example the other day I needed to know if an array field contained null values. that field I would never ever query, but I needed to check its data integrity from an import process.

As I said, Painless is great for ad-hoc querying. Something that is trivial in a RDBMS and a bit "involved" in ES. IMHO Painless inline is good enough for me.

Anyhow, I don't see why it is ok to have _source in Groovy, JavaScript, etc. but not in Painless.

I know that ES offers me a lot of choices to accomplish a certain task. Some more performant than others. But I don't think that there is any gain in blocking a feature that is not a threat to ES security or stability (a clear line drawer) just because it is not as performant as the other choices, because you never know which use case they might be solving.

I will never index those fields just for the sake that, who knows, some day I might need to query them. Querying the _source allows me not to index "garbage fields".

What do you think?

**Comment by jpountz** [comment]
I did not make the decision to not expose source access but I understand the reasoning. I also understand how using source in queries can help do some one-off queries. I'll add the `discuss` label.

**Comment by s1monw** [comment]
When we made decisions for painless we wanted to ensure that it's secure and fast with respect to it's usecases. Allowing access to `_source` crosses the line here. It means you are doing linear IO on every document matching a query. This is what should be done in reindexing. Hold your breath for a second, I can already see you saying "but but but" yes it's not perfect! There are legit usecases where it might be ok to access `_source` like when you have low num of docs and you are not time-critical etc. Some of these usecases are simply not what painless was made for in the first place. Fetching every document in the index on a per-query bases can certainly cause huge stability issues on clusters. If you reindex you do this only once not on a per query basis. 

> I know that ES offers me a lot of choices to accomplish a certain task. Some more performant than others. But I don't think that there is any gain in blocking a feature that is not a threat to ES security or stability (a clear line drawer) just because it is not as performant as the other choices, because you never know which use case they might be solving.

I have to disagree with this theory on all levels. With painless we had no BWC at all that means we didn't have to support any feature that we would have not added today. Hence the `_source` limitation. That said, it's not a hard BWC break since we still kinda support other scripting languages that have that difficult feature. If you follow your theory you can't add anything anymore to elasticsearch since the theory renders removal impossible. The flip side is that addition becomes impossible since you have to get it perfect or you are lost. 

Back to a usecase and my dream... my dream would be to not have these drowning discussions where X is not supported. I know it's a dream since people think in X Y problems all over the place. When you want to access a value that has no doc values, what are your options? One would be to reindex, (it might be similarly fast in some cases) the other might be adding some functionality that can provide a doc values interface loading stuff from stored fields such that `_source` is not needed anymore. We can for instance make it memory bound and cache things to make it faster or even move it into a plugin etc. such that users need to actively opt in? Let's collect the usercases, and see if we can build a good solution for this rather than cluttering the scripting languages interface with a feature that surprises a lot of people, kills search performance and can cause disk IO to skyrocket.

**Comment by nicolasgarfinkiel** [comment]
You raise many valid points, which makes me understand the why on your decision, though I must say I don't agree with most of them. I will use a lot of RDBMS analogies here, but please bear with me.

- linear IO on every matching query is not as different as doing a sequential scan. It doesn't matter if the user planned for it. If he issued a query and the planner decided a sequential scan, that's the way it goes. That a user doesn't understand the consequences of his actions doesn't make the RDBMS accountable for.

- Reindexing is not a practical option. You are better off storing a groovy script.

- IMHO it has nothing to do with BWC. It has to do more with a lack of a very useful feature, which is a given in most other data stores: exploratory querying.

- Why not making it available as a DSL parameter? Something like _source_enabled: true. That way you are opting in for it. No surprises. You know what you are doing action.

BTW, is this restriction actually in the docs? I could not find it.

**Comment by clintongormley** [comment]
Discussed in FixItFriday.  We considered adding a safeguard setting which you'd have to explicitly enable to allow source access in scripts, but we have had bad experiences with things like this (eg dots in field names): unaware users tend to copy paste these settings without any thought for the consequences, and we have seen so many issues in the past with people using source in scripts that it's something we're not keen to revisit.

**Comment by HonzaKral** [comment]
I have seen several legitimate use cases for accessing `_source` in your scripts for both queries and aggregations. I would be perfectly comfortable with having this functionality disabled by default as long as it would be dynamically updatable at runtime.

Some use cases (especially compelling if you consider their use in `rescore`):
* look at detailed fields that are not indexed
* run complex computation on source of analyzed fields
* aggregate over fields with no doc_values (ad-hoc exploration)
* comparing different fields

I strongly believe that this is something we can just solve with documentation - a clear message about what accessing _source means and what are better solutions for that problem.

**Comment by nicolasgarfinkiel** [comment]
You can put as many safeguards as you want, but it won't stop people doing stuff they should not, because exceptions happen, of course, where you dont expect them to happen. Im not saying safeguards are bad, of course they are useful and some of them should be there, but in some cases it feels more like patronising.

You might create a problem when you try to solve it. An user might naively enable inline scripting for groovy, which was deemed unfit for security reasons, because he need ad hoc source searching, and now not only we have potential performance problems, but as well security problems.

Proper documentation and safe defaults are the way to go on this one IMHO.

**Comment by rpedela** [comment]
> When we made decisions for painless we wanted to ensure that it's secure and fast with respect to it's usecases. Allowing access to _source crosses the line here. It means you are doing linear IO on every document matching a query. This is what should be done in reindexing. Hold your breath for a second, I can already see you saying "but but but" yes it's not perfect! There are legit usecases where it might be ok to access _source like when you have low num of docs and you are not time-critical etc. Some of these usecases are simply not what painless was made for in the first place. Fetching every document in the index on a per-query bases can certainly cause huge stability issues on clusters. If you reindex you do this only once not on a per query basis.

When you are dealing with TBs (like me), reindexing is always the last resort. It is not a good solution.

> the other might be adding some functionality that can provide a doc values interface loading stuff from stored fields such that _source is not needed anymore

I like that idea because it still allows the use cases ```_source``` access enables, but ES can make better performance decisions.

**Comment by jdconrad** [comment]
Closing this issue.  _source will only be allowed in certain contexts.
