### ISSUE TITLE
Restore original update bulk item request on retry

### ISSUE THREAD

**Issue by areek** [elastic/elasticsearch#21221]
Currently, when we execute a update request as part of bulk, 
the update request is translated to a `index` or `delete` request 
at the shard level for primary execution and the translated request 
is set for replica execution. If the shard bulk request throws an exception, 
we restore the original version and version type for all bulk item requests 
but we don't restore the original update request (instead we use the 
translated update request). Opening this issue to figure out how to properly 
restore update requests in bulk in case of failure in shard bulk execution. 

see https://github.com/elastic/elasticsearch/pull/19105#discussion_r85712023

**Comment by dakrone** [comment]
This feature request is an interesting idea but since its opening we have
not seen enough feedback that it is a feature we should pursue. We prefer
to close this issue as a clear indication that we are not going to work on
this at this time. We are always open to reconsidering this in the future
based on compelling feedback; despite this issue being closed please feel
free to leave feedback on the proposal (including +1s).
