### ISSUE TITLE
Evaluate version conflict in bulk request during primary relocation

### ISSUE THREAD

**Issue by areek** [elastic/elasticsearch#21230]
Currently, we special case version conflict failures for bulk items 
when shard bulk request has partially executed in the primary and 
is retried due to primary relocation during shard bulk execution 
(as relocated shards could close in mid operations previously).
Now that we have proper primary relocation (i.e. relocated shard 
is only closed after operation completion), we should evaluate if 
we really need to special case version conflict failures for this case.

relates https://github.com/elastic/elasticsearch/pull/19105#discussion_r85712926

**Comment by dakrone** [comment]
This feature request is an interesting idea but since its opening we have
not seen enough feedback that it is a feature we should pursue. We prefer
to close this issue as a clear indication that we are not going to work on
this at this time. We are always open to reconsidering this in the future
based on compelling feedback; despite this issue being closed please feel
free to leave feedback on the proposal (including +1s).
