### ISSUE TITLE
Packaging: /etc/init.d/elasticsearch doesn't pass through ES_JVM_OPTIONS

### ISSUE THREAD

**Issue by martinb3** [elastic/elasticsearch#21255]
**Elasticsearch version**: 5.0.0 and master

**OS version**: sysv init distros

**Description of the problem including expected versus actual behavior**:

The addition of the `ES_JVM_OPTIONS` did not make it to [the debian init script packaging](https://github.com/elastic/elasticsearch/blob/master/distribution/deb/src/main/packaging/init.d/elasticsearch#L84-L86) or [the RHEL init script packaging](https://github.com/elastic/elasticsearch/blob/master/distribution/rpm/src/main/packaging/init.d/elasticsearch#L62-L65).

In the systemd scripts, all variables are passed through, but not in the init scripts. This blocks anyone from setting ES_JVM_OPTIONS to an alternate location using /etc/default/elasticsearch or /etc/sysconfig/elasticsearch. It also prevents any automation from using a non-standard location, and prevents anyone running multiple instances from using the existing init scripts to do it (unless they want a single /etc/elasticsearch/jvm.options file that they can't change).

**Comment by jasontedor** [comment]
Thanks for reporting this, this is indeed a mistake. I will fix.

**Comment by GaneshbabuRamamoorthy** [comment]
Hi @jasontedor 

Can we get any update on this?

I am trying to install ES 5.0 using ansible elasticsearch git project and since I am getting the below error after I set the ES_JAVA_OPTS in the below file.

**File location:-  (Under ansible-elasticsearch/templates/elasticsearch.j2) and during playbook file copied to the below path /etc/elasticsearch/master_node_elasticsearch**

**Note:- I have attached my customized playbook**

`fatal: [10.247.0.31]: FAILED! => {"changed": true, "cmd": ["sudo", "service", "master_node_elasticsearch", "start"], "delta": "0:00:00.086526", "end": "2016-11-09 07:46:34.015391", "failed": true, "rc": 1, "start": "2016-11-09 07:46:33.928865", "stderr": "", "stdout": "Starting elasticsearch: Error: encountered environment variables that are no longer supported\nUse jvm.options or ES_JAVA_OPTS to configure the JVM\nES_HEAP_SIZE=1g: set -Xms1g and -Xmx1g in jvm.options or add \"-Xms1g -Xmx1g\" to ES_JAVA_OPTS\n[FAILED]", "stdout_lines": ["Starting elasticsearch: Error: encountered environment variables that are no longer supported", "Use jvm.options or ES_JAVA_OPTS to configure the JVM", "ES_HEAP_SIZE=1g: set -Xms1g and -Xmx1g in jvm.options or add \"-Xms1g -Xmx1g\" to ES_JAVA_OPTS", "[FAILED]"], "warnings": ["Consider using 'become', 'become_method', and 'become_user' rather than running sudo"]}
`
Correct me know If I am doing any wrong in setting up ES_JAVA_OPTS.
[rdaas-elasticsearch.zip](https://github.com/elastic/elasticsearch/files/580760/rdaas-elasticsearch.zip)

**Comment by jasontedor** [comment]
@GaneshbabuRamamoorthy Your problem is unrelated to the issue reported here; you are using an environment variable (`ES_HEAP_SIZE`) that is no longer supported.

**Comment by martinb3** [comment]
Thanks for taking care of this one, @jasontedor! 👍
