### ISSUE TITLE
Add safeguard on very large cluster_concurrent_rebalance value

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#21277]
We have seen situations where shards ended up going back and forth (repeatedly and not settling) when the cluster_concurrent_rebalance is configured to a very large number (eg. hundreds).  Per discussion with @ywelsch , a large number like this will cause the cluster look 400 steps into the future to find the right balance (= optimistic model). If it takes the cluster too long time to actually execute on this plan (shards being failed after 30 minutes because recovery not started yet), it will make subsequent decisions based on an optimistic model that it's not able to realize.  

It can be helpful to add a safeguard/hard limit (linking parent ticket: https://github.com/elastic/elasticsearch/issues/11511) to prevent users from setting it to too high of a value.

**Comment by clintongormley** [comment]
Should this be a safeguard or just a hard limit?

**Comment by ppf2** [comment]
Maybe a hard limit ?  Will defer to @ywelsch , not sure looking how many steps ahead becomes a problem here ..

**Comment by probakowski** [comment]
@ywelsch @ppf2 is this still relevant today and something we want to act on?

**Comment by DaveCTurner** [comment]
We (the @elastic/es-distributed team) discussed this on 2019-10-02. We noted that the kind of problem described in the OP is perhaps better controlled by the `node_concurrent_recoveries` settings since they apply per-node and they apply to all recoveries including those that happen when a cluster is recovering from a restart or an outage.

The reason to limit the number of concurrent rebalances is that in a healthy cluster it should be rare to need to do this kind of rebalancing, and in a sense that a rebalancing relocation is less important than a recovery that builds a lost replica, so by limiting them we leave the cluster with enough capacity to recover replicas quickly if needed. The main risk of setting this too high is that a major rebalancing event would prevent allocation of missing replicas (e.g. if an index rolls over) possibly for many minutes.

We also mentioned the case of adding new empty nodes to a cluster, in which we rely on balancing to move some shards onto the new nodes. It's hard to distinguish this case from the usual steady-state of a cluster, and there are other related issues (e.g. the hotspotting described in #17213) but we expected that kind of scaling event to be relatively rare. Again `node_concurrent_recoveries` seems an important safety mechanism even if `cluster_concurrent_rebalance` is temporarily increased.

It was quite a broad discussion that touched on other ideas, such as pausing or cancelling any low-priority rebalancing recoveries to make way for higher-priority ones.

**Comment by DaveCTurner** [comment]
We (the @elastic/es-distributed team) discussed this again today and decided to close this issue on the grounds that we have not encountered very many cases in which the proposed safeguard would help.

We did note, however, that we had seen a case in which an excess of rebalancing shards caused a cluster to rebalance continuously for weeks. Reducing the concurrent rebalance limit stabilised the cluster relatively quickly. We didn't investigate further, but we decided to open #60747 which may have helped us to diagnose the underlying issue.
