### ISSUE TITLE
elasticsearch -Des.config=... ERROR: D is not a recognized option

### ISSUE THREAD

**Issue by kevin4z** [elastic/elasticsearch#21351]
I want to run multiple elasticsearch nodes on one machine. [This webpage](http://markreddy.ie/running-two-elasticsearch-instances-on-one-machine/) use `$ bin/elasticsearch -Des.config=$ES_HOME/config/elasticsearch.1.yml` to run multiple nodes. But, when I run this command, it's said `ERROR: D is not a recognized option`?  I run this command by `Win7` Cmder.

**Comment by jasontedor** [comment]
You didn't specify a version but I'm guessing version 5.0.0. That blog post is out of date for version 5.0.0. Command-line flags are specified using `-E` [now](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_settings_changes.html). I recommend using our docs instead of old blog posts. 

Elastic reserves GitHub for verified bug reports and feature requests. You can ask general questions on the [Elastic Discourse forum](https://discuss.elastic.co).

**Comment by ataliya-long** [comment]
not use
