### ISSUE TITLE
SearchRequestBuilder.wrapperquery can't set stringified JSON query (5.0.0)

### ISSUE THREAD

**Issue by 1ambda** [elastic/elasticsearch#21452]
**Elasticsearch version**: 5.0.0

**Plugins installed**: []

**JVM version**: 1.8

**OS version**: OSX 10.11.6

**Description of the problem including expected versus actual behavior**:

In 2.x, It is possible to set JSON query using `setExtraSource`. 
Since `setExtraSource` was removed in 5.0.0 and I am now trying to use `setQuery(QueryBuilders.wrapperQuery(query))`
But it doesn't work.
(mentioned in [discuss.elastic.co: setextrasource-in-elastic-5-0-0](https://discuss.elastic.co/t/setextrasource-in-elastic-5-0-0/64487))

Additionally, I'v also read [5.0 API breaking changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_50_java_api_changes.html)

Is there other API I can use instead?

```java
// SearchRequestBuilder reqBuilder = ...
// String query = "...";

    if (!StringUtils.isEmpty(query)) {
      // The query can be either JSON-formatted, nor a Lucene query
      // So, try to parse as a JSON => if there is an error, consider the query a Lucene one
      try {
        final Map source = gson.fromJson(query, Map.class);
        // reqBuilder.setExtraSource(source); // works in 2.x
        reqBuilder.setQuery(QueryBuilders.wrapperQuery(query)); // doesn't work
      } catch (JsonParseException e) {
        // This is not a JSON (or maybe not well formatted...)
        reqBuilder.setQuery(QueryBuilders.queryStringQuery(query).analyzeWildcard(true));
      }
    }
```

I tried `SearachSourceBilder` giving the same result. 

```java
        SearchSourceBuilder sourceBuilder = SearchSourceBuilder.searchSource()
            .query(QueryBuilders.wrapperQuery(query));
        reqBuilder.setSource(sourceBuilder);
```

**Comment by javanna** [comment]
Hi @1ambda,
wrapper query should work for the query part of the search request. Can you post more info on how it doesn't work for you please? Unfortunately I don't think we have the same for aggregations and the rest of a search request.

As a side note, we have removed most of the string setters from the java api as part of the search refactoring. The java api uses the transport layer which should ideally work with java objects rather than strings. Ideally, a search request comes in through the REST layer, gets parsed on the coordinating node, hence converted to its java api corresponding objects, and gets sent to the shard by serializing those objects. When using the java api you don't go through REST layer but you are already one step ahead. We previously were using json as the format to send the queries over to the shards which is why you could provide strings using the java api, as parsing was delayed. We wrote a series of blogs on moving parsing to the coordinating node and what it allows us to do: https://www.elastic.co/blog/the-tale-of-caching-and-why-it-matters .

In general, I'd recommend to use the java api builders to create search requests that are already in the binary format, so no parsing is needed. Otherwise, I would suggest to have a look at the newly released Java REST client that doesn't have builders yet but allows to provide strings.

**Comment by 1ambda** [comment]
@javanna 

Thanks for the detailed response! Now I understand why those APIs were removed and how they impact on the 5.x internals.

Zeppelin users pass stringfied JSON like [Zeppelin Elasticsearch Usage](http://zeppelin.apache.org/docs/0.6.2/interpreter/elasticsearch.html#search). I wanted to APIs like `setExtraSource` for this reason. But according to your reply, `wrapperquery` should work regarding to search request at least. It is quite weird. I will investigate further. 

I will use newly introduced REST API as you recommended because It seems that there is no API for agg operation.

**Comment by cbuescher** [comment]
It seems this got resolved, so I will close this. Please reopen if I missed something.
