### ISSUE TITLE
Permission issues with tribe nodes

### ISSUE THREAD

**Issue by salyh** [elastic/elasticsearch#21514]
For **ES 2.4.1** on a tribe node i get
<pre>
access denied ("java.net.SocketPermission" "localhost:9400" "listen,resolve")
</pre>
Seems the default security policy is missing the "listen" action for "java.net.SocketPermission"

For **ES 5.0.0** on a tribe node i end up in a
<pre>
Exception: java.security.AccessControlException thrown from the UncaughtExceptionHandler in thread "Thread-1"
</pre>
because of a
<pre>
access denied ("java.lang.RuntimePermission" "getClassLoader")
</pre>
which is seemingly requested by the log4j2 library (log4j-core-2.6.2.jar).
I also see ``access denied ("java.net.SocketPermission" "localhost:9400" "listen,resolve")``

A full log trace for ES 5.0.0 is here: https://gist.github.com/salyh/73964e8c56c332ee766b42f40a8e365d (line 803)

**Comment by jasontedor** [comment]
@salyh Thanks for the report, can you please share a simple reproduction?

**Comment by rjernst** [comment]
This is known issue: #16392

**Comment by jasontedor** [comment]
Duplicates #16392

**Comment by salyh** [comment]
I don't think it's a solely duplicate of #16392 because of ``access denied ("java.lang.RuntimePermission" "getClassLoader")`` on ES 5. And moreover on ES 5 you cannot circumvent this by disabling the security manager. I think fixing #16392 is easy, just add the "listen" action for "java.net.SocketPermission".

By doing this and by adding "java.lang.RuntimePermission" "getClassLoader" to the policy file (in my own elasticsearch fork) both problems described in this issue are gone.

#16392 is older than 6 month, i add another related issue for ES 5 and all that happens is hitting the duplicate button. Thats somewhat disappointing to be honest.

**Comment by jasontedor** [comment]
@salyh I think it is the same issue. We grant socket permissions dynamically based on the network settings and there is an issue as explained in #16392 for tribe nodes.

The logging issue appears to be an artifact of the tribe node failing to bind, because of the missed socket permission. Log4j has known issues when run under a security manager. We are not going to grant the runtime permission "getClassLoader" to the entire codebase nor to just the Log4j codebase.

I'm sorry that #16392 has sat for so long. I will bump the priority of it.

**Comment by jasontedor** [comment]
@salyh It occurred to me in the middle of the night that there is a broader problem here. You can see it even on a clean shutdown of tribe nodes. I opened #21519.

**Comment by jasontedor** [comment]
@salyh I've integrated #21519 and #16392 is closed by #21546.
