### ISSUE TITLE
Replace size mapper plugin by size ingest plugin

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#21520]
I'm opening this issue to discuss this proposal.
I think we can replace the mapper size feature with an ingest size plugin.

WDYT?

**Comment by jpountz** [comment]
This sounds good to me but we'd need to be very clear about the semantics since the size would be computed on the source document before the size field is added, so it would not take into account the size field, even though it is part of the source. We would also need to consider the serialization format to use. For instance, there are good reasons for Ingest to use `smile` to serialize the source document since it is slightly more efficient, but maybe the size the user is interested in is the `json` size.

**Comment by dadoonet** [comment]
As per discussion in #21604, we are not going to support it. I forgot to close this one.
