### ISSUE TITLE
Bug:ES5.0.0 Can't auto discover other node

### ISSUE THREAD

**Issue by hareteam** [elastic/elasticsearch#21524]
I'd download ES5.0.0 to my server(192.168.0.1, 192.168.0.2)
and i changed config file。
server 1:
network.host: 192.168.0.1
http.port: 9200
cluster.name:  cluster1
node.name: node1

server 2：
network.host: 192.168.0.2
http.port: 9200
cluster.name: cluster1
node.name: node2
 
But when i run  bin/elasticsearch  , they can't found other node..

**Comment by bleskes** [comment]
With 5.0, we removed multicast based discovery (which was made a plugin and deprecated in 2.x). This is because multicast is not available in many networks and is not reliable protocol. Instead you should configure `discovery.zen.unicast.hosts`. See here for more details: https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery-zen.html#unicast

I'm going to close this now. If you have any further questions I would like to ask you to use discuss.elastic.co - where we'd be happy to help. Github is used for issues and feature requests.

**Comment by hareteam** [comment]
@bleskes  But when i expand the cluster scope，example：
I have two server:server1, server2 before today，but tommrrow i need add a new server(server 3)，please tell me ,what should i do?

**Comment by bleskes** [comment]
if you configure the third server with the first two servers in it's hosts file it will be fine. An alternative - for 5.0 is to File based discovery. As said, please continue the discussion on https://discuss.elastic.co/

**Comment by dadoonet** [comment]
Yes please. Keep the discussion here: https://discuss.elastic.co/t/es5-0-0-cant-auto-discover-other-node/65939/2
