### ISSUE TITLE
Remove boolean query parsing leniency

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#21545]
Currently when querying a boolean field, we parse pretty much anything except for `false` or `0` to mean `true`. This can cause a lot of query confusion.

We should remove this boolean parsing leniency so that only the string `"true"` and `"false"` parse without exceptions.

**Comment by jpountz** [comment]
For the record, this is an issue when running queries on multiple fields and the field list includes a boolean field, since everything but `false`/`0` parses to true. We'd rather like to ignore such fields, which would only works if an error was raised, just like what happens when searching for a random string value on a numeric field.
