### ISSUE TITLE
Increase socket timeouts when reindexing

### ISSUE THREAD

**Issue by hariso** [elastic/elasticsearch#21707]
I'm involved in reindexing a large amount of data, a mix of smaller and larger documents. The source and target index belong to different clusters, and using different versions (source: 1.7.5, target: 5.0.1)

The reindexing is done in chunks, where the chunks are data ranges from the source index. And while some chunks we reindex without any problem, for some we see something like `Error(type=socket_timeout_exception, reason=null, additionalProperties={})` in the target cluster.

We have a small tool which coordinates a number of reindex tasks, and retries failures. However, in this case, the source cluster, sooner or later, becomes unstable: we start seeing OutOfMemoryErrors, nodes get down etc. My assumptions is that, if the socket timeout was higher, the target cluster would be able to consume the data, and not just flood the source with requests.

So far I see two options:
1. Use smaller and smaller chunks.
2. Use a larger socket timeout.

No. 1 isn't really helping. For no. 2 I couldn't find a way to accomplish.

**My question is**:  How can I work around those socket timeouts?

Thanks in advance!

**Comment by clintongormley** [comment]
@nik9000 are you passing (or allowing to be passed) `?search_type=scan` to the 1.x cluster (which doesn't understand `?sort=_doc`.  If not, then the 1.x cluster is doing deep pagination which is why it is timing out.  This PR was only added in v2 https://github.com/elastic/elasticsearch/pull/4968

**Comment by nik9000** [comment]
> @nik9000 are you passing (or allowing to be passed) ?search_type=scan to the 1.x cluster (which doesn't understand ?sort=_doc.

Yes. I switch to `?search_type=scan` when the target cluster is older than `?sort=doc` and handle the empty response that it gives differently. I admit we don't have automated integration testing for this though so we might be doing something wrong.

> we start seeing OutOfMemoryErrors, nodes get down etc

@hariso, this seems bad. There are, sadly, quite a few things that can cause an OOM on a 1.7 node. I don't want reindex to invoke those things though! Are you doing anything other than reindex? If not then we have some problem with reindex to look at.

Like you say it could be that your retry tool is flooding the cluster with these requests. You are right that configuring the socket timeout is probably a thing I should expose. Or bump the default to some crazy long time. Or both. Probably both. And that might help here. Because, you are right to assume that we don't have a mechanism to cancel the search requests. Actually that is added in 5.1 but isn't wired up to cancel the requests when the socket is closed....

Anyway, I'll experiment a bit with 1.7 today and see if I can reproduce.

**Comment by clintongormley** [comment]
@hariso could you paste the reindex request that you run in here please?

**Comment by hariso** [comment]
Thanks all for prompt responses!

@clintongormley Here is a single request:

```
{
    "dest": {
        "index": "reindex-01"
    },
    "script": {
        "inline": "ctx._source.remove('_type')",
        "lang": "painless"
    },
    "source": {
        "index": "my-index",
        "query": {
            "range": {
                "myDateField": {
                    "gte": "2013-11-05T00:00:00.000Z",
                    "lt": "2013-11-08T00:00:00.000Z"
                }
            }
        },
        "remote": {
            "host": "http://remote-host-one-dot-seven:9200"
        },
        "size": 5000
    }
}
```

But, as I mentioned, a number of those is run in parallel.

**Comment by hariso** [comment]
> @hariso, this seems bad. There are, sadly, quite a few things that can cause an OOM on a 1.7 node. I don't want reindex to invoke those things though! Are you doing anything other than reindex? If not then we have some problem with reindex to look at.

@nik9000 Yes, so I'll need to I'll need to find my way through that forest subsequently. It's a production cluster, and it's being used frequently, but I'm not sure how much is it for this index. And, of course, the nodes shards of `my-index`(121M docs, 2.6 TB) live, have shards from other indexes as well, so I'll need to see if some other index is heavily used (I doubt).

When I start reindexing (again: with a few reindex requests at a time), we start seeing the same nodes having problems (the nodes which host shards for `my-index`).

> Like you say it could be that your retry tool is flooding the cluster with these requests.

Yes, however, when it failed last time it was running 5-7 reindex tasks at the same time (reindex task example is above). That doesn't sound like something, but I might be wrong.

> Because, you are right to assume that we don't have a mechanism to cancel the search requests.

I'm not an Elasticsearch expert, and I'll be free to ask if there is something which could help me "clean up" a node after a failed search? E.g. [clearing the cache](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/indices-clearcache.html)?

**Comment by nik9000** [comment]
> I'm not an Elasticsearch expert, and I'll be free to ask if there is something which could help me "clean up" a node after a failed search?

So the trouble is that the search doesn't really terminate when you close the socket. In later versions of 2.x you can use the tasks API to see that it is still running. In 1.7 you are a bit blind. You can jstack and hunt for the thread running your query but that is kind of hard. You can tell if you have a stack dump and look at the objects and squint just right. Like, if you took one on OOM.

So retrying after a socket timeout is dangerous because the old query could still be there and you pile up queries. We make this less likely to blow up on you by having a limited queue depth and size for the search thread pool. So I'd expect you'd see thread pool rejections too.

I think the safest thing you can do for now is to refuse to retry on socket timeouts.

You might also want to make that size smaller - `?search_type=scan` returns `size` documents per shard rather than `size` documents total so 5000 is quite high. Maybe fine, maybe not. I dunno. Hard to tell without a heap dump of the oom. Which, btw, if you have one and you are willing to dump somewhere I'd be happy to look at it. That'd be the best way to figure out where the OOMs are coming from. But I'd see all the data in memory which can be sensitive.

**Comment by hariso** [comment]
> So the trouble is that the search doesn't really terminate when you close the socket. In later versions of 2.x you can use the tasks API to see that it is still running. In 1.7 you are a bit blind. You can jstack and hunt for the thread running your query but that is kind of hard. 

Got it, thanks! 

5000 is what I used initially, plus retrying with half the size when it fails (2500, 1250, etc.) Today I used 500, with 7 requests at a time at most, with no retries. It went further, but still made the cluster blush. I am not aware of thread pool rejections right now (I was looking at the tool, which registers errors it got from the Reindex API and Tasks API in the target cluster). Given that I was running a single reindex job, with 5-7 reindex tasks at a time, I would doubt that happened. But it's still good to know we have a layer of protection there!

> You might also want to make that size smaller - ?search_type=scan returns size documents per shard rather than size documents total so 5000 is quite high.

That's something I knew, but completely forgot.:S I did lower it down as mentioned above, but not because I was conscious of this. In any case, that explains some things. `my-index` has 10 shards: with 7 parallel reindex tasks and 500 docs per shard, that becomes 35 000 docs. And with the initial setting: 15 parallel reindex tasks and 5000 docs per shard, that is, wow, 750 000 docs.

> Which, btw, if you have one and you are willing to dump somewhere I'd be happy to look at it. That'd be the best way to figure out where the OOMs are coming from. But I'd see all the data in memory which can be sensitive.

I would be happy as well, but there is some customer data in the indexes, so it is quite sensitive. But I will try to get to one when it fails next time.

**Comment by nik9000** [comment]
> That's something I knew, but completely forgot.:S

I mean, reindex from remote *could* have done the division for you. I just didn't because I figured it was magic enough as is.

> 750 000 docs.

How big are the docs? Are they fairly uniform. That is a lot of docs to be floating in memory at once. Usually it won't be all of them.

> I would be happy as well, but there is some customer data in the indexes, so it is quite sensitive. But I will try to get to one when it fails next time.

We can talk over email about how to exchange it if you like.

**Comment by nik9000** [comment]
OK! I've played with reindex-from-remote from 1.7 and it works, sending `search_type=scan` just like when I first built it. I loaded a couple million docs without trouble on my laptop. I'll open a PR that makes timeout customizable and defaults it to 60 seconds, up from the 10 seconds that it is now.

**Comment by nik9000** [comment]
So I opened a PR to add the ability to set the timeout and to bump the default timeout to one minute. I'm not sure that it is going to help you if the cluster you are copying from is genuinely running out of memory though.

**Comment by hariso** [comment]
> How big are the docs? Are they fairly uniform. That is a lot of docs to be floating in memory at once. Usually it won't be all of them.

Nope, they are very different in sizes, even within a single type in the index. But if some kind of statistics would be valuable, I would pull it out (some overview of size ranges within the index). And definitely, quite a lot. Even with the reduced size I had, 7 threads and size = 500, and 10 shards, it's still a lot.

> We can talk over email about how to exchange it if you like.

Because of HIPAA and some other privacy regulations, it would be great if you would let me know, what you are looking for, and I can provide you the data. Something besides, would be harder to arrange, and I would to ask around in the company how we would do that.

> OK! I've played with reindex-from-remote from 1.7 and it works, sending search_type=scan just like when I first built it. I loaded a couple million docs without trouble on my laptop. I'll open a PR that makes timeout customizable and defaults it to 60 seconds, up from the 10 seconds that it is now.

You rock, man.:) I can try the #21741 PR out hopefully tomorrow. `search_type=scan` is not in the PR, as I see. Is that a part of the solution as well, or did I misunderstand?

> So I opened a PR to add the ability to set the timeout and to bump the default timeout to one minute. I'm not sure that it is going to help you if the cluster you are copying from is genuinely running out of memory though.

Thanks again! I'm aware of that, and we are investigating other possible issues of OOMs. But I'm hoping that this will at least alleviate some of the pains, since it won't leave hanging searches in the source cluster.

**Comment by nik9000** [comment]
> HIPAA

Yeah, lets not send that heap then. I'd look for large object arrays inside an `org.apache.lucene.util.PriorityQueue` to check for deep pagination. That is the min-heap implementation of choice in Lucene and Elasticsearch and is used for stuff like collecting all the search hits on a node.

> You rock, man.:) I can try the #21741 PR out hopefully tomorrow. search_type=scan is not in the PR, as I see. Is that a part of the solution as well, or did I misunderstand?

`?search_type=scan` was never broken. It was a good guess though. It was certainly the first place to look for the failure.

You may prefer to cherry-pick the contents of the PR onto the 5.x branch for testing. The PR is against master which is what will eventually be 6.0. I'll backport it once it is reviewed.

**Comment by hariso** [comment]
> Yeah, lets not send that heap then. I'd look for large object arrays inside an org.apache.lucene.util.PriorityQueue to check for deep pagination. That is the min-heap implementation of choice in Lucene and Elasticsearch and is used for stuff like collecting all the search hits on a node.

Gracias! Will do as soon as I have the opportunity.

**Comment by hariso** [comment]
I just realized the "feedback_needed" label and that I haven't gotten back to you.

@nik9000 I still haven't had the chance to examine the heap. However, I've backported the changes to 5.0.1 and it works pretty good; the problems are much less common (even though, we have documents which are up to 900 MB, so I'll do more "hacking" here, both with configuring the timeout and the buffer).

**Comment by nik9000** [comment]
> even though, we have documents which are up to 900 MB, so I'll do more "hacking" here, both with configuring the timeout and the buffer

Yeah, those kinds of documents don't make Elasticsearch happy! 

I'm glad to the see the patch worked. I was going to merge it this morning anyway because it looked "done" and I figured you'd reopen if it didn't work. To be honest all the time between opening the PR and merging the patch mostly came from my schedule (holidays and training) and me not being super noisy about getting a review and then not noticing when I had one.

**Comment by hariso** [comment]
@nik9000 Thank you very much!
