### ISSUE TITLE
max_doc_count doesn't work?

### ISSUE THREAD

**Issue by k2xl** [elastic/elasticsearch#21714]
I'm using Elasticsearch 5 to monitor systems, and I'm trying to query for all the systems that in the past hour haven't much data.

My query is as follows:

```
{
  "aggs": {
    
    "filtered": {
      "filter": {
        "bool": {
          "must": [{
            "range": {
              "@timestamp": {
                "from": "now-1h",
                "to": "now"
              }
            }
          }]
        }
      },
      "aggs": {
        "hosts": {
          "terms": {
            "field": "hostname",
            "size": 30
          }
        }
      }
    }
  },
  "size": 0
}
```
But this just returns all the systems that have sent data.

There is a ```min_doc_count``` which will return buckets that have a count of at least ```min_doc_count```, but surprisingly, there doesn't appear to be a ```max_doc_count```?

Is there are a workaround for returning results with low counts? The use case is if a system is expected to send a log every minute, and in the last hour less than 60 documents are in the system (or some other threshold, like 30) then it could mean there is an issue with that system.

I've been reading the Pipeline aggregation doc, but I can't seem to figure out how to access doc_count

**Comment by jpountz** [comment]
We have `min_doc_count` indeed, but it is really designed for the special values 0 and 1. One issue we have with implementing such a feature is that we can only know whether a bucket meets this constraints when we know the total doc count, which only the coordinating node can know. So this feature has important limitations and `max_doc_count` would have a similar one.

> I've been reading the Pipeline aggregation doc, but I can't seem to figure out how to access doc_count

You need to use the special path `_count`.

```
GET t/_search
{
  "aggs": {
    "filtered": {
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "@timestamp": {
                  "from": "now-1y",
                  "to": "now"
                }
              }
            }
          ]
        }
      },
      "aggs": {
        "hosts": {
          "terms": {
            "field": "hostname",
            "size": 30
          },
          "aggs": {
            "rare_hosts": {
              "bucket_selector": {
                "buckets_path": {
                  "doc_count": "_count"
                },
                "script": {
                  "inline": "params.doc_count < 3"
                }
              }
            }
          }
        }
      }
    }
  },
  "size": 0
}
```

Note using such a bucket selector means that you might end up with no buckets at all if none of the top buckets met the constraint.

I am closing this issue since wo have no plans to implement a `max_doc_count` constraint and we are thinking about making `0` and `1` the only two supported values for `min_doc_count`.
