### ISSUE TITLE
Painless script development tool

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch#21732]
**Describe the feature**:

My wishlist for painless Painless development: a command line tool to load a painless script and contexts, something like:

```
run-painless --script my-script.painless --context /path/to/context-files
```

where `--context` could be a single file or directory containing multiple files.
A context file would be a json document which could (for example to simulate a watch) could have something like:
```
{
  "ctx":{
    "payload":{
      "size":5
    }
  }
}
```
... or obviously much much more complex...

Once started, the tool would allow you to run again and again (reducing the JVM load time), each time reading the script and context files anew.

For bonus points the execution time for each of the contexts, and a summary for all of the contexts together would be very useful for optimising scripts.

**Comment by nik9000** [comment]
I'm not sure this is worth prioritizing because it emulates a script context rather than uses a "real" script context. I allude to my opinion about this in #21723. I think context is the hard part about scripting in Elasticsearch in general. A tool like this would be good to work on painless scripting syntax but doesn't really help you to understand the context in the first place. I'm trying to put together recipes that let you explore those contexts in #21723. I know that watcher is hard to explore but I think that is something watcher should solve.

I'm just really worried that a tool like this will give you a false sense of security because it only emulates the context in which a script runs. If we have a way to make it super accurate I'd be much more excited about this.

**Comment by robin13** [comment]
I don't think the tool could/should/would be used to determine "this takes 2ms to run here, so I presume it will be the same on the cluster", but rather to compare "is this way of solving the puzzle faster than that way", and moreover to have an ability to add lines / make changes to the script or context data and test the outcome in quick iterations without having to do the many steps necessary to transfer a script to a server, adjust the source data or query to get the desired context, wait for the server to automatically detect the new script, .... and then run it (only to notice some annoying syntax error, and have to wait at least one minute to be able to run it again).

**Comment by sunilpwyd** [comment]
This feature is highly recommended. Large projects with 100+ painless scripts can make use of it in their CI/CD pipeline. There are cases of auto generating painless scripts on the fly or at build time, and this feature will help in the tooling for validating them.

**Comment by jdconrad** [comment]
I'm going to close this as we now have the Painless Execute API (https://github.com/elastic/elasticsearch/pull/29164) that should cover this issue.

**Comment by csenol** [comment]
Maybe late to game but I created this project which can be used for testing, developing and also as some REPL
https://github.com/csenol/plsd
