### ISSUE TITLE
`require_field_match` should accept "true"|"false"

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#21802]
The `require_field_match` parameter in highlighting only accepts `true` or `false`,  not the string equivalents `"true"` or `"false"`:

```
GET t/_search
{
  "highlight": {
    "fields": {
      "*": {}
    },
    "require_field_match": "false"
  }
}
```

throws:  

```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "[highlight] require_field_match doesn't support values of type: VALUE_STRING"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "[highlight] require_field_match doesn't support values of type: VALUE_STRING"
  },
  "status": 400
}
```

**Comment by makeyang** [comment]
@clintongormley 
it seems to me that all boolean field should accept true|false|"true"|"false"
therefore, how about rename ValueType.BOOLEAN to ValueType.BOOLEAN_OR_STRING?

**Comment by nguyenuy** [comment]
I would like to take on this ticket to start as a first contribution to this project

**Comment by firstprayer** [comment]
Just did a little dive into the code - I feel like this change is not very easy, because the information of token comes from https://github.com/FasterXML/jackson-core/blob/master/src/main/java/com/fasterxml/jackson/core/JsonToken.java, from where it's already identified as String, not as Boolean, not to mention Boolean_Or_String, which is not defined in the json parser library.


 ![notsure](https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTcQacWQ6WXIqpn3xNz-looShhQn09nT5RQo-oRZBtRZGpTR3AVyCLIMLE)

**Comment by javanna** [comment]
The same happens whenever we parse a boolean field with `ObjectParser` in our codebase, as it doesn't support strings parsed as booleans. it is a very small change to make it do that.
