### ISSUE TITLE
Parent/child grouping without a physical parent document.

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#21820]
Sometimes "child" docs have a common parent ID but are missing a physical parent doc - @paullovessearch would like to see these "orphans" grouped in search results to achieve pagination of top-ranking groups.

### Background
Number-one-voted issue https://github.com/elastic/elasticsearch/issues/4915 contained several requests for **paging** in aggregations. Several different use cases were tied up on that issue so it was closed and this issue has been opened to focus on the use case of _paginating top-ranked groups_. However, my assumption here is that pagination of ranked groups should be achieved by search and not the aggregations framework.

### Pagination = search API
What we established in https://github.com/elastic/elasticsearch/issues/21785 is that efficient search (and especially efficient _paginated_ search) depends on heavy down-selection of results at the local level. "Local" can mean same document, same segment (nested docs) or same shard (parent/child). We can rank and page related items only if they are grouped locally (i.e. we do not attempt inefficient pagination on related content that is spread across multiple shards). 

The existing parent/Child construct is our means of:
1) Routing related items to the same shard at index-time
2) Ensuring a child has exactly one parent and therefore shard
3) Producing paginated search results for the grouped items

This is why I think Parent/Child might be the answer to tackling the "top group pagination" requirement.

### Support for "Orphans"
@paullovessearch suggested that in some systems the parent ID for child docs may serve only as a grouping key and there is no physical parent document to group child docs around at query-time. Some suggested using `terms` aggs and `top_hits` but this does not provide the pagination support that is required (or the required indexing discipline which means we can rely on the fact related items are held on the same shard).

### Next steps.
I think we have two possible solutions:
1) Parent/Child queries are adapted to work with missing physical parent docs
2) Users wanting pagination should provide physical parent docs

As with most things this is a cost/benefit analysis:

Re costs: @martijnvg - we spoke briefly. How insanely complex is 1) to implement?

Re benefits: @paullovessearch - I'd assume parent IDs nearly always have an authoritative data source simply to generate the unique numbers (order numbers, transaction IDs..) and are likely to hold other useful "who/when?" type info e.g. inception dates and instigators. Can you list the use cases where a solution is unlikely to incorporate a data source for parent info?

**Comment by paullovessearch** [comment]
Thanks @markharwood for this comprehensive summary.

In the real world, there may be a data source for the parent document, but it may be controlled by another group in the company to which the search team has no access. Or it may be managed by a legacy system and the owners of that system are too nervous to allow another reader.

And besides, just the extra effort of 1) ingesting a second stream from a second system, and 2) having to restate all of your child documents with a parent ID (rather than just specifying a field when the index is created, for example) is onerous.

Lots of examples also exist where the parent ID just comes from a counter or accumulator, and there is no actual parent record, per-se. In some of these cases, the parent ID document may be quickly abandoned (for example, due to a rollback).

Finally, there are examples where the parent ID is merely the grouping attribute. Such as the host name for a web crawler. There is no "document" which represents the "host name" (perhaps the Who-is entry?) but people are crawling HTML pages, and not who-is entries. Besides, crawling the entire who-is is unrealistic.

And finally, when determining duplicate or near-duplicate documents, we are simply stamping a "grouping ID" on a set of documents. There is no 'parent document' in this scenario, merely a set of documents with the same similarity hash or the same grouping ID.

Thanks,
Paul

**Comment by markharwood** [comment]
Thanks for the examples, Paul.
I suppose a third option is for elasticsearch to auto-create missing parent docs when orphan child docs are added (otherwise they will be invisible to parent-child searches). This could be an option for those systems with no feed for parent docs.

**Comment by markharwood** [comment]
Something like this in the mapping:

	{
	 "my_child_mapping":{
	   "_parent":{
		 "type" : "my_parent",
		 "referential_integrity" : "none/strict/auto_create"
	   }
	}
	
"none" is where we are today.
"strict" checks for parent, errors when missing
"auto_create" checks for parent, creates when missing

**Comment by paullovessearch** [comment]
Auto creating the parents feels like a brittle architecture to me. Too many opportunities for the parent to be missing or extra parents (after children are deleted) and all that. Especially when there are failures and rollbacks and so-on.

Parent-child joins require an in-memory map of parentId to/from childId. My recommendation is to simply build that map based on a field in the document. And then, in the searching logic, change any reference to an actual parent record with a search operator which returns as if the parent record exists and it only had a single field (the parent ID).

Finally, there will need to be a configuration on the index to route records to shards based on the field value.

**Comment by clintongormley** [comment]
> Auto creating the parents feels like a brittle architecture to me. 
++

**Comment by markharwood** [comment]
>Auto creating the parents feels like a brittle architecture to me. 

The status quo is already "brittle". Orphaned children are not include in parent/child query results.
Perhaps the phrase "referential integrity" is too strong here (expectations of cascading deletes etc) but as a convenience to clients we could perform some additional checks more cheaply than the clients could.
Granted though, inserting physical docs purely to satisfy the needs of an existing query impl feels ugly.

>My recommendation is to simply build that map

I had a word with parent/child guru @martijnvg and changing the way parent/child collects results to support absent parent docs is "non-trivial".

Perhaps this is a dead-end then. The good news is @jimczi has another proposal we can discuss in a different issue which I will link to when it emerges.

**Comment by jimczi** [comment]
@markharwood @paullovessearch I opened https://github.com/elastic/elasticsearch/issues/21833 

I think it can be a good compromise between pagination of terms aggregations and simple field collapsing where pagination is needed.

**Comment by markharwood** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/issues/21833
