### ISSUE TITLE
Remove all 2.x version constants from Version.java

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#21887]
We should remove the 2.x version constants from Version.java since master (a.k.a. 6.0) does not need to know about those versions.

**Comment by colings86** [comment]
We might need to change re-index slightly to allow this change. 

The reindex from remote determines the version of the remote cluster and changes its behaviour based on whether `version < 2.0.0`, `2.0.0 <= version < 2.1.0` or `version >= 2.1.0` (e.g. [1]). It does this by parsing the string version from a call to `GET /` into an instance of `Version`[2]. 

Maybe we should have re-index (and maybe the REST client) use their own version of the `Version` class that does not store the Lucene version (since they shouldn't need it), so that the versions that they are compatible with can be independent of the versions which are compatible internally?

[1] https://github.com/elastic/elasticsearch/blob/master/modules/reindex/src/main/java/org/elasticsearch/index/reindex/remote/RemoteRequestBuilders.java#L72
[2] https://github.com/elastic/elasticsearch/blob/master/modules/reindex/src/main/java/org/elasticsearch/index/reindex/remote/RemoteResponseParsers.java#L273

**Comment by nik9000** [comment]
Makes sense to me. We don't need the lucene version over rest. Or we
shouldn't, anyway. So long as they are comparable to each other that is
fine.

**Comment by colings86** [comment]
@jpountz suggested we could use `Version.fromId()` in reindex to solve the above

**Comment by nik9000** [comment]
That'd work for me.
