### ISSUE TITLE
Pipeline aggregation: full histogram of an aggregation

### ISSUE THREAD

**Issue by rcrezende** [elastic/elasticsearch#21962]
Want to estimate the distribution of an aggregation and I wonder if is there any way to perform the parent aggregation on all buckets (thing_id) and then the percentiles over the sum so I can estimate the full histogram.

For example, I could do the following:
```
GET /data/_search
{
    "size": 0,
    "aggs" : {
        "ActionsByThing" : {
            "terms" : {
                "field" : "thing_id"
            },
            "aggs": {
                "NumberActions": {
                    "sum": {
                        "field": "nActions"
                    }
                }
            }
        },
        "PercentileOfNumberActions": {
            "percentiles_bucket": {
                "buckets_path": "ActionsByThing>NumberActions", 
                "percents": [ 1.0, 2.5, 5.0, 10.0, 25.0, 50.0, 75.0, 90.0, 95.0, 97.5, 99.0] 
            }
        }
    }
}
```

But that represents only the TOP K thing_id, I'm looking for the overall distribution including the tail.

Even if I have K very large, it will be still biased (because doesn't cover the tail)

Even if the cardinality of thing_id is not that large and I can afford to have K > |thing_id|, the aggregation response will return ActionsByThing and I really don't need it, I just care about PercentileOfNumberActions (which has only 11 buckets, much less than the possible cardinality of thing_id). Possibly if ES knows the user doesn't care about thing_id buckets, it can optimize for memory/scalability.

In this example I'm using percentiles, but one could extend the concept to histogram aggregation as well.

**Comment by jpountz** [comment]
Due to the fact that data is sharded, we only know the number of actions per thing on the coordinating node. This means that this kind of aggregation would require shards to stream all buckets back to the coordinating node, which is not possible given how aggregations are designed today.

One way that these problems are sometimes solved is by building entity-centric indices, with one document per "thing" and the sum of the number of actions for this thing as a property. This way, a regular percentiles aggregation can be used to compute the distribution of the number of actions.

**Comment by clintongormley** [comment]
It sounds like there is nothing we intend to do here, so will close

**Comment by rcrezende** [comment]
Well, you could think about an approximation method for estimating such as bootstrapping. In your platform you already have the sampler aggregation so I think you have infrastructure to implement (not an exact method), but close enough. See https://en.wikipedia.org/wiki/Bootstrapping_(statistics)
