### ISSUE TITLE
[code issue][discuss]should method innerJoinCluster of ZenDiscovery class loop certain times and quit rather than loop forever when join master fail?

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#22133]
below is a abstract logic of innerJoinCluster:
{
    final boolean success = joinElectedMaster(masterNode);
    clusterService.submitStateUpdateTask("finalize_join (" + masterNode + ")", new ClusterStateUpdateTask(){
        public ClusterState execute(ClusterState currentState) throws Exception {
                    if (!success) {
                        // failed to join. Try again...
                        joinThreadControl.markThreadAsDoneAndStartNew(currentThread);
                        return currentState;
                    }
        }
    }
}
//I ask a node whose id is same with current master to join the cluster and then, this node goes into this dead loop and can't quit. In my opinion, we should deal with this error and ask the node quit.

**Comment by jasontedor** [comment]
Elastic reserves GitHub for verified bugs and feature requests. It's best to ask general questions about the code on the [forum](https://discuss.elastic.co).

**Comment by makeyang** [comment]
@jasontedor  I don't think it's a questions.

**Comment by bleskes** [comment]
@makeyang I agree this is not a question but rather a valid concern - if the node permanently can't join the cluster, it will indeed go into an infinite attempt loop. This was originally set up this because 99% of the reasons why a node can't form a cluster are temporarily and you actually want it to retry. Also, even if the node will quits an external service will just start it up again in many cases. 

With the the introduction of the hard node id rule, I agree it would be nice if the node will quit to make this issue more apparent. Sadly the current flow of code makes it hard to stop the node and I'm not sure it's worth the extra complexity - it is clear that something is wrong (the node doesn't join) and we log it. Also, since pinging takes 3 seconds, I think the amount of generated logs should not be that great.

**Comment by makeyang** [comment]
@bleskes  got it. thanks for replying.
