### ISSUE TITLE
Locked fields during update/upsert

### ISSUE THREAD

**Issue by seang-es** [elastic/elasticsearch#22170]
It would be useful to have the ability to have certain fields 'locked' during an upsert, so if the document does not already exist the field can be written, but if it does exist, the field is untouched.  The use case for this would be something like a 'creation time' where the initial time of document creation must be maintained, even if an upsert is making modifications to other fields.

**Comment by clintongormley** [comment]
This sounds like the typical request for a feature that would have 10 different sets of requirements from 9 different users.  This kind of thing can easily be implemented today application side (preferably using GET/PUT with versioning, rather than _update) which will give you complete control over which fields can and cannot be updated.
