### ISSUE TITLE
fix sum aggregation inline script bug

### ISSUE THREAD

**Issue by ozguryalcin** [elastic/elasticsearch#22205]
data : 

        [mid] => 1
        [providers] => Array
            (
                [0] => Array
                    (
                        [pid] => 1
                        [amount] => Array
                            (
                                [price] => 4.5
                                [currency] => 1
                            )
                    )

                [1] => Array
                    (
                        [pid] => 2
                        [amount] => Array
                            (
                                [price] => 5
                                [currency] => 1
                            )
                    )

                [2] => Array
                    (
                        [pid] => 2
                        [amount] => Array
                            (
                                [price] => 6
                                [currency] => 1
                            )

                    )

            )

search: 

**`{ "query" : { "bool" : { "must" : [ { "term" : { "mid" : 1 } } , { "term" : { "providers.pid" : 2 } } ] } } }`**

sum aggregation script :
**`{ "aggs": { "providers.amount.price" : { "sum" : { "script" : { "lang":"painless", "inline" : "Double.parseDouble(doc[\'providers.amount.price\'].value)" } } } } }`**

 total must be 5+6= 11 but  sum total output returns 6. what's wrong ?

**Comment by jimczi** [comment]
We reserve github for bugs or feature request. You can ask questions like this in the forum:
https://discuss.elastic.co/c/elasticsearch

Regarding your issue, the script is useless here since you can use the `sum` aggregation directly on a field name. Though the sum will be  15.5 since the aggregation takes all the values that are contained in the document for this field regardless of the query. You'll need to take a look at nested fields if you want to solve your issue:
https://www.elastic.co/guide/en/elasticsearch/reference/5.1/nested.html
https://www.elastic.co/guide/en/elasticsearch/reference/5.1/search-aggregations-bucket-nested-aggregation.html
