### ISSUE TITLE
elasticsearch java client 5.1.1: JsonGenerationException[Can not write a field name, expecting a value]

### ISSUE THREAD

**Issue by josidiez** [elastic/elasticsearch#22264]
**Elasticsearch version**: 5.1.1

**Plugins installed**: []

**JVM version**: 1.8 , spring boot 1.4.1

**OS version**: Windows 7

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. executing elasticsearch client 
 2. I just code this: SuggestBuilders.completionSuggestion("field").text("s")
 3. I get error JsonGenerationException[Can not write a field name, expecting a value]
 4. I'm thinking maybe jackson incompatilibity , my gradle dependency conf: 
dependencies {
    compile group: 'org.elasticsearch.client', name: 'transport', version: '5.1.1'
    compile group: 'org.elasticsearch', name: 'elasticsearch', version: '5.1.1'
    compile group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.7'
    compile group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.7'
    compile group: 'org.json', name: 'json', version: '20160810'
}

**Provide logs (if relevant)**:

**Describe the feature**:
I just want to build a suggestion feature. To start I test code example on api documentation in elastic search web.  When executing SuggestBuilders.completionSuggestion("field").text("s") I get error described above on json generated. After few hours spending on this I dont get an Idea what is going on. ¿jackson incompatibility? (spring boot 1.4.1) .

**Comment by cbuescher** [comment]
The CompletionSuggestionBuilder you get with (2.) should be fine. What do you do with it before you get the exception? The json generated for those builders is usually only valid inside larger structures, in this case it is usually used with SuggestBuilder#addSuggestion(String name, SuggestionBuilder<?> suggestion). Can you share a larger code example of what you are trying to do?

**Comment by josidiez** [comment]
I'm starting to play with this functionality so I decided to start with this basic code to see how it works:

CompletionSuggestionBuilder suggestion =  SuggestBuilders.completionSuggestion("name").text("AL");
transportClient.prepareSearch("locations").suggest(new SuggestBuilder().addSuggestion("provinces", suggestion)).get();

The result of suggestion json is:
 { "error" : "JsonGenerationException[Can not write a field name, expecting a value]"}
I don't have previous code. I've been testing with normal queries like QueryBuilders.matchAllQuery() and works fine. Something happens with SuggestBuilders.

**Comment by cbuescher** [comment]
> The result of suggestion json is:
> { "error" : "JsonGenerationException[Can not write a field name, expecting a value]"}

How do you get the suggestion json? The transportClient()...get() should give you a SearchResponse. Is the exception already thrown or only if you try to print/access something from the response? The code you posted looks like what we use in out integration tests, so I wouldn't expect a general problem there, its probably a usage problem. Would you mind if I close issue and reopen this this discussion in the [forums](https://discuss.elastic.co/c/elasticsearch)) since Elastic reserves GitHub for bug reports and feature requests?

**Comment by josidiez** [comment]
Ok, close it. I can post something on the forum. But It's notbad usage. It's nothing about transport client because I dont even execute it. The SuggestBuilders return than json error. On my code the variable suggestion is CompletionSuggestionBuilder type and its value is { "error" : "JsonGenerationException[Can not write a field name, expecting a value]"} . 
Just this line cause the error:
CompletionSuggestionBuilder suggestion = SuggestBuilders.completionSuggestion("name").text("AL");
I debugged, even inside elastic code, and it's wierd because it's just a constructor code there.

**Comment by cbuescher** [comment]
So it that JsonGenerationException actually thrown or do you just see this line as output when you try to print the CompletionSuggestionBuilder? That would be explainable, because all the SuggestionBuilder don't write a complete Json object, because they are nested inside other structures. So calling "toString()" on them (which also the debugger usually does) would return that line. The object is okay, the search should work regardless. Thats why I'm asking if you actually see an exception being thrown.

**Comment by josidiez** [comment]
Thank you very much. You were right, I was missing something.

**Comment by cbuescher** [comment]
@josidiez thanks for pointing this out, it looks like others might run into the same problem so I opened a PR that helps to prevent this missunderstanding.

**Comment by samkit96** [comment]
Even I got the same error. I resolved it by setting the shard size to some positive integer value. By default, the shard size is set to -1.
