### ISSUE TITLE
Dealing with red status

### ISSUE THREAD

**Issue by rpayanm** [elastic/elasticsearch#22394]
**Elasticsearch version**:
5.1.1

**JVM version**:
1.7.0_111

**OS version**:
Debian 8

**Description of the problem including expected versus actual behavior**:
When I do this request:
`GET _cluster/health/i?level=shards`
I got:
```
{
  "cluster_name": "c_rap00",
  "status": "red",
  "timed_out": true,
  "number_of_nodes": 1,
  "number_of_data_nodes": 1,
  "active_primary_shards": 0,
  "active_shards": 0,
  "relocating_shards": 0,
  "initializing_shards": 0,
  "unassigned_shards": 0,
  "delayed_unassigned_shards": 0,
  "number_of_pending_tasks": 0,
  "number_of_in_flight_fetch": 0,
  "task_max_waiting_in_queue_millis": 0,
  "active_shards_percent_as_number": 100,
  "indices": {}
}
```
You can see: `"status": "red",`

When I try index a document I got this error:
```
Server error: `PUT http://45.33.125.112:9200/i_rap00/garage/13340`
resulted in a `503 Service Unavailable` response:
{"error":{"root_cause":[{"type":"unavailable_shards_exception","reason":"[i_rap00][0]
primary shard is not active Timeou (truncated...)
```

What steps should I follow to fix this error?

**Comment by nik9000** [comment]
The [allocation explain](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-allocation-explain.html) API was created to help debug these issues. It'll help you figure out why the shard isn't being assigned.

In general we try to keep questions like this on https://discuss.elastic.co/ because it probably isn't a bug. *Hopefully* isn't a bug.
