### ISSUE TITLE
Translation document (Korea)

### ISSUE THREAD

**Issue by HueyPark** [elastic/elasticsearch#22399]
Hi,

I am a programmer working in Korea
I want to translate Elasticsearch documents, but how can I contribute?
I considering creating a docs/KR folder under this branch's docs and starting a translation

Thank you

**Comment by clintongormley** [comment]
Hi @HueyPark 

Thank you for the offer (and I'm sorry it has taken a long time to reply).  Community sourced translations of ever-changing documentation is tricky because it requires an enormous amount of work (so unpaid community contributors are likely to get burnt out) and we have no way of checking whether the translation is correct or not.

At some stage, we are likely to provide translations, but we would have to do it via a paid agency to ensure the standards are maintained long term.

Thank you for the offer.
