### ISSUE TITLE
Dynamic Mapping issue

### ISSUE THREAD

**Issue by rcastill** [elastic/elasticsearch#22470]
Hi,

I'm using Elasticsearch to index data from a MongoDB database. I am currently transporting the data from one to another via a Python script using pymongo and official elasticsearch 5.x python API.

I had one problem, that it seems I'll have to solve by manually mapping types because dynamic mapping is parsing the strings:

- OK
- CRITICAL
- UNKNOWN
- OPEN

As if they were integers, and so it raises a `NumberFormatException`.

I'd want to know if this is a known issue, and why is it caused for. If I find more strings that comply with this description, I'll let you know.

**Comment by jimczi** [comment]
Please use the forum for questions like this, we reserved github for bugs and feature request:
https://discuss.elastic.co/c/elasticsearch


Regarding your issue, dynamic mapping does not treat strings as numbers. The mapping for a dynamic field is set on the first document that contains the field and the type is inferred based on what this field looks like. So your problem is that the first document with this field contained a number. As you noticed one way to deal with this situation is to force the mapping for the field.

**Comment by rcastill** [comment]
I have just queried my MongoDB database and there is no document that has a number under that field
