### ISSUE TITLE
Painless script loop maximum number of statements limit exception on update_by_query call

### ISSUE THREAD

**Issue by sergpsu** [elastic/elasticsearch#22508]
Hi there
Here are details about the issue.
https://discuss.elastic.co/t/painless-script-loop-maximum-number-of-statements-limit/70895
elasticsearch version 5.0.0

**Comment by jdconrad** [comment]
I agree with @nik9000 this is a valid use case for having a higher limit.  Ideally, this limit could be set per context since I don't think we want people to have a higher limit for search where it doesn't make sense.  I'm also very hesitant to make this a runtime compiler option since it would allow an outsider to pretty much run an infinite loop.  A quick fix would be simply upping the limit to something like 100000 instead of 10000.  But maybe this should be an ES setting per context?  What do you think @nik9000?

**Comment by nik9000** [comment]
I was thinking that if we had contexts it would be a thing that came along with the context, yeah. If contexts are still a long way off maybe we should bump the value an order of magnitude. I'm not really sure to be honest. I don't want to allow searches to be slow but this is a totally reasonable use for update.

**Comment by jdconrad** [comment]
Unfortunately contexts in scripts are still a ways off :/  backcompat is *hard* as I'm sure you know.  So yeah, I think the order of magnitude bump makes sense for now, and then we can re-address this later on.

**Comment by sergpsu** [comment]
Guys, when can I expect this to work?

**Comment by jdconrad** [comment]
@sergpsu I'll change the setting today.

**Comment by nik9000** [comment]
> @sergpsu I'll change the setting today.

If he changes it today and backports to the change to the 5.2 branch you'd be able to get the fix by upgrading to 5.2.0 once we release it which should be soon-ish given that we've cut a branch for it. We are pretty coy about when we plan to release, mostly because we can't predict it well. Though  Elasticsearch 5.2 needs Lucene 6.4 which is being discussed [here](https://lists.gt.net/lucene/java-dev/336634).

**Comment by jdconrad** [comment]
This has been changed so I'm going to close this issue.  It will be backported to 5.1.2.
