### ISSUE TITLE
`index.store.preload` not present in default index settings or cluster settings

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#22686]
The `index.store.preload` setting, which can be set at node level or index level, is not visible in the default settings for either the cluster or the index:

    PUT my_index
    
    GET my_index/_settings?include_defaults&flat_settings
    GET _cluster/settings?include_defaults&flat_settings

**Comment by maddin2016** [comment]
Hi @clintongormley, i assume that `index.store.preload` is a module setting and is created when the first node is up. See [here](https://github.com/elastic/elasticsearch/blob/5.0/core/src/main/java/org/elasticsearch/index/IndexModule.java#L82). But [here](https://github.com/elastic/elasticsearch/blob/5.0/core/src/main/java/org/elasticsearch/common/settings/AbstractScopedSettings.java#L74) this setting is never added to the `keySettings` because `hasComplexMatcher` returned true for `index.store.preload`. What this `complexMatcher` exactly stands for?

**Comment by sunnyhwang** [comment]
Hey guys,

I would like to work on this if possible :)

**Comment by liketic** [comment]
@clintongormley I think this could be closed.  Both above two APIs can get the setting now.

**Comment by clintongormley** [comment]
thanks @liketic - closing
