### ISSUE TITLE
Fill in missing Javadoc

### ISSUE THREAD

**Issue by trejkaz** [elastic/elasticsearch#22705]
Many classes or methods in Elasticsearch are missing Javadoc.

Someone should probably go through and fill in the missing documentation. I believe there are javac warnings which can be turned on so that forgetting to document things becomes more visible.

As far as wanting to know anything in particular, this request is more the result of multiple days of trying to upgrade Elasticsearch 2 code to Elasticsearch 5, and thus wanting to read docs to determine the correct replacement method for methods which are deleted.

**Comment by javanna** [comment]
This has drastically improved in the last years and months. I am pretty happy with where we stand as  we had almost no javadocs 4 years ago. We are much more diligent now about adding javadocs to public methods whenever we add them or touch existing ones, also enforcing that habit as part of the review process.

But there is a distinction to make between internal code and public api. I sense that this issue comes from lack of javadocs specifically in our java api?

**Comment by dadoonet** [comment]
Related also to discussion happening on #22707, so I'm cross linking...

**Comment by trejkaz** [comment]
Certainly it was Java API, buuut then again where else would one find Javadoc?

**Comment by clintongormley** [comment]
> Someone should probably go through and fill in the missing documentation. I believe there are javac warnings which can be turned on so that forgetting to document things becomes more visible.

You do know that we accept PRs?

Closing in favour of #22707

**Comment by javanna** [comment]
> Certainly it was Java API, buuut then again where else would one find Javadoc?

Java api is a subset of our codebase. Can you point out what you struggled with and where you would like to see javadocs specifically? Everywhere would be good, but if you had to choose some specific places where it is missing?

**Comment by trejkaz** [comment]
Clinton, do engage at least one brain cell before making any further comments. Even an idiot would realise the logical problem with your suggestion.

As for which classes... I don't know. I remember hitting a lot of places where the class docs were just an empty Javadoc comment, but not any particular class. I could probably list them as I find them, but turning the warning on might do just as well.

**Comment by clintongormley** [comment]
@trejkaz Do engage a few brain cells to read the code, write some java docs, and become an actual contributor to this open source project that you're using.

**Comment by jasontedor** [comment]
> Clinton, do engage at least one brain cell before making any further comments. Even an idiot would realise the logical problem with your suggestion.

This is completely unacceptable.

We will happily listen to and carefully consider constructive criticism. By choosing to act confrontationally like this, you establish yourself as an adversary rather than a collaborator, it's an ineffective way to make a point, and contributes to furthering the poor reputation you've established for yourself on past issues.

I say this hoping that it will have a positive impact on you but even if not I state it for the benefit of the entire community that we expect civil discourse here.

**Comment by trejkaz** [comment]
@clintongormley naturally I have been doing so.

I don't think my comment was unacceptable. Being told to contribute docs for something you don't know even know how it works, when if you knew how it worked you wouldn't need docs? _That_ is unacceptable.

**Comment by jasontedor** [comment]
> Someone should probably go through and fill in the missing documentation.

As @javanna mentioned, we are working on this. It's something that happens iteratively, slowly, over time. These days, when we review PRs, we consistently ask for Javadocs for contributors. You will also see contributors adding Javadocs when they refactor methods.

If you have specific areas on the client APIs that need improvement, we would be happy to take a look.

> I believe there are javac warnings which can be turned on so that forgetting to document things becomes more visible.

This is not going to happen. The first problem is that there are too many classes without Javadocs that this will just be noise that no one will pay attention to. The second problem is that we treat warnings as errors. The first point is more important than the second point.
