### ISSUE TITLE
Support for Machine Learning Features is ELK Stack

### ISSUE THREAD

**Issue by SKumarMN** [elastic/elasticsearch#22760]
Hi,

This is not a bug, however wanted to bring your attention. Are there any plans of introducing features that aids machine learning using Elasticsearch(ELK stack). Like some sort of classification/regression for log analysis etc

**Comment by clintongormley** [comment]
We will be releasing an anomaly detection feature which uses ML as part of X-Pack (see https://www.elastic.co/blog/ai-dreams-ml-promises-ba-how-elastic-and-prelert-fit-together) and we will probably add other features which use ML in the future.

Typically, we'd prefer to add features which use ML under the covers, rather than exposing ML tools directly.

**Comment by rajibmitra** [comment]
@clintongormley Other than x-pack , what are other options for anomaly detection ?
