### ISSUE TITLE
Add Rolling Upgrade Tests for All Minor Versions

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#22771]
Right now rolling upgrade tests are only applicable for testing 5.X --> 6.0 in master.  It would be very useful to have these for minor upgrades as well including the following:

5.0 -> 5.1
5.0 -> 5.2
5.1 -> 5.2
5.0 -> 5.3
5.1 -> 5.2
5.2 -> 5.3

and on and on to ensure that each version has a place to test both XContent changes and wire protocol changes.

**Comment by jasontedor** [comment]
I think it would suffice to just randomize the version upgrading from amongst all released versions.

**Comment by jdconrad** [comment]
I'm not a big fan of the randomization there simply because I want to know on the first pass through if one of the versions has a bug.  I think it's quite difficult to debug if I only happen to get lucky and actually hit the failing test.

**Comment by jasontedor** [comment]
I think that running them all would be entirely too time consuming. We use randomization for upgrades in the packaging tests, I think it's a safe strategy with sufficiently many CI runs.

**Comment by jasontedor** [comment]
And there is a way to run with a specific version if you really do want to test all combinations locally.

**Comment by jdconrad** [comment]
With sufficient runs I agree it's safe, it's just a bummer to have all tests pass locally through a single run and then end up breaking something in master.  But given that we don't do very many bwc changes I'm happy to concede to randomization here to save time.  The tests in general are already slow enough :)

**Comment by abeyad** [comment]
A current run on my macbook pro takes about 25 seconds (just the tests themselves).  It could add up quite a bit if there are many minor versions of the same major version.  So randomization is probably the right way to go here.

**Comment by jasontedor** [comment]
> With sufficient runs I agree it's safe, it's just a bummer to have all tests pass locally through a single run and then end up breaking something in master.

With randomized tests and the matrix of configurations that we test, there's really no avoiding this. All we can do is gain more confidence with each CI run that our changes are safe.

> The tests in general are already slow enough :)

Yeah, that's what I want to avoid, adding even more time to them. :smile:

**Comment by rjernst** [comment]
I don't think this would be adding too much time, vs the pain that is caused when backcompat breaks (builds breaking for hours or days while someone figures out why it started breaking).  And the total number of variations is not as large as the initial comment suggested.  In 5.x (ie, 5.3 right now), there is no reason to test 5.0 -> 5.1 or 5.1 -> 5.2. For a given branch, we should be testing rolling upgrade from the previously released minor versions (the latest bugfix of that minor).  So for current 5.x, that means testing 5.0 -> 5.3, 5.1 -> 5.3 and 5.2 -> 5.3.  The 5.2 -> 5.3 is a little tricky since 5.2 is not yet released, but still doable with snapshots.  The key here is that we need a place to test the transition. When a feature is added/removed let's say in 5.2, and we want a specific rolling upgrade test for that from 5.2 to 5.3, we can't just stuff it in the tests that would be (randomly) run against 5.0 -> 5.3 or 5.1 -> 5.3.

**Comment by jasontedor** [comment]
> For a given branch, we should be testing rolling upgrade from the previously released minor versions (the latest bugfix of that minor) to the current version.

I don't think this is sufficient. For every branch, I think that we should be testing upgrades from all releases below that branch (so on 5.2.0, we'd test 5.0.0, 5.0.1, 5.0.2, 5.1.1, 5.1.2 all to 5.2.0).

**Comment by rjernst** [comment]
We could randomize within a minor. But the important part of my statement before is we need a place for tests which cannot work in rolling upgrades from any version.

**Comment by abeyad** [comment]
> But the important part of my statement before is we need a place for tests which cannot work in rolling upgrades from any version.

Don't we use the skip sections for this?

**Comment by rjernst** [comment]
> Don't we use the skip sections for this?

We could. But I prefer explicit. This is why the static index bwc tests exist (and are always run) for every version. No surprises.

**Comment by rjernst** [comment]
Our backcompat tests have changed considerably since this issue was created. We now test rolling upgrade from all compatible versions to the current version, so I am closing this issue.
