### ISSUE TITLE
Collapse aggregation packages

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#22868]
The fact that every aggregation has its own package requires to make too many classes public. We should look into collapsing packages and making as many classes package-private as possible. Ideally we'd do this close to the 6.0 release to keep backporting easy.

**Comment by sophiec20** [comment]
@jpountz Should this be an open blocker?

**Comment by jpountz** [comment]
Bumping the version, it's now too late to do this change.

**Comment by polyfractal** [comment]
@elastic/es-search-aggs

**Comment by jpountz** [comment]
Removing the `blocker` label since we won't treat it as a blocker.

**Comment by csoulios** [comment]
Now that metric and pipeline aggregations have been collapsed to one package each, does it make sense to do the same for bucket aggregations? Bucket agg packages may contain from 6 classes (`org.elasticsearch.search.aggregations.bucket.global`) to 51 classes (`org.elasticsearch.search.aggregations.bucket.terms`).

Also, lately we have developed `min`/`max`/`sum`/`avg` aggs for `histogram` and `aggregate_double_metric` field types as x-pack modules. This required changing some classes back to `public`. 

So, I wonder if this issue is still valid.

**Comment by csoulios** [comment]
We discussed this issue in the team meeting and agreed that collapsing all bucket aggregations to a single package would result in more confusing package structure. Therefore, we decided not to collapse bucket aggregations and close this ticket.
