### ISSUE TITLE
Elasticsearch nested mapping query not working- JAVA?

### ISSUE THREAD

**Issue by moghimire** [elastic/elasticsearch#22884]
I've set my one field to nested type. I followed as per this documentation https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/java-joining-queries.html#java-query-dsl-nested-query

Below is the snippet

```
"price":{  
           "type":"nested",
           "properties":{  
              "activity_price":{  
                 "type":"double"
              },
              "multimedia_price":{  
                 "type":"double"
              },
              "transportation_price":{  
                 "type":"double"
              }
           }
        }
```
While performing query

```
QueryBuilders.nestedQuery("price", QueryBuilders.boolQuery()
        .must(QueryBuilders.matchQuery("price.activity_price", price)),
            ScoreMode.Max);
```
I get **[nested] nested object under path [price] is not of nested type.**

I'm using Elasticsearch 5.1.2

**Comment by cbuescher** [comment]
Elastic reserves GitHub for bug reports and feature requests but provides a [Discourse forum](https://discuss.elastic.co) and [IRC channels](https://www.elastic.co/community) for general questions. Since you already opened the same [thread there](https://discuss.elastic.co/t/elasticsearch-nested-mapping-query-not-working-java/73345), can we keep the discussion in one place please?
