### ISSUE TITLE
Update Stored Scripts to Only Support the New Namespace

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#22887]
As a follow up to #22206, the lang parameter should be completely removed from version 6.0 in places it was deprecated in 5.3 to support the new stored script namespace.

**Comment by brusic** [comment]
Is this issue being worked on? There is a feature I want to add which would depend on this particular to be implemented in order to reduce code complexity.  jdconrad mentioned in the other issue that "requires another change to actually remove it from 6.0 that I'll try to follow up with this week.".

I can implement it myself, would prefer not to if it has already been worked on.

**Comment by jdconrad** [comment]
This has been completed.
