### ISSUE TITLE
Should we improve the way we compute ShardSearchLocalRequest#cacheKey

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#22901]
This is a follow up issue to track a discussion I had with @javanna about how we currently generate the cache key for shard level search results.
The cache key currently consists of a complete deserialized bytes array of most of the ShardSearchLocalRequest members, including a deserialized version of the SearchSourceBuilder. This has led to some issues where seemingly "equal" objects didn't have the same cache key because of undetermined serialization ordering of nested maps, sets etc... (https://github.com/elastic/elasticsearch/issues/19986, https://github.com/elastic/elasticsearch/issues/22808). 
While we have tests catching this and can try to ensure a consistent ordering of the deserialized bytes array, we can probably find a better way to computer the cache key. Now that the whole SearchSourceBuilder has a `hashCode()` method, maybe we can use that in the cache key computation instead?

**Comment by jpountz** [comment]
Discussed in FixitFriday: Using a contiguous byte[] array as a key has interesting virtues:
 - memory accounting is easy
 - it puts less pressure on garbage collection

Also we are on the fence about using a hash of the request as a cache key because of potential collisions. Even if they would rarely happen, they would be terrible bugs as they would return responses for the wrong requests.

Agreement seemed to be to improve testing of consistent serialization instead.

**Comment by cbuescher** [comment]
Okay, closing this then.
