### ISSUE TITLE
Bucket Selector and params

### ISSUE THREAD

**Issue by bsideup** [elastic/elasticsearch#22957]
Hi.

I would like to request a feature - allow Bucket Selector script to accept the whole bucket as a parameter.

We analyze our data and filter out some of it with a script. Some of the analysis based on percentiles. 

Right now we use a hack to pass all percentile buckets like so:
```json
buckets_path: {
              "a_p1": "a>p[4.0]",
              "b_p1": "b>p[4.0]",

              "a_p2": "a>p[8.0]",
              "b_p2": "b>p[8.0]",

              "a_p3": "a>p[12.0]",
              "b_p3": "b>p[12.0]",

... more records like this...

              "a_p24": "a>p[96.0]",
              "b_p24": "b>p[96.0]",

              "a_p25": "a>p[100.0]",
              "b_p25": "b>p[100.0]",
            }
```

But it's awful and hard to support. Would be good if we could do:

```json
buckets_path: {
    "a_p" : "a>p",
    "b_p" : "b>p",
}
```

Thanks!

**Comment by polyfractal** [comment]
I looked into this, and it seems doable with minimal fuss.  Building on the changes in https://github.com/elastic/elasticsearch/pull/30152/, it basically needs:

1. Whitelisting the `Percentiles`/`PercentileRanks` class with painless, which should be fine since that interface only exposes `percentiles(double)` and `percentilesAsString(double)`
2. Implement a `getProperty()` that returns an `Object`, and defers checking the type restrictions to other overloads that return `Double`
3. Make `bucket_selector` (and probably `bucket_script` for consistency) use the `Object` overload

This gives full access to the Percentiles object in a safe manner, and if the user tries to access any other object it won't work (since those interfaces aren't whitelisted with Painless).

The only quirky bit is with `gap_policy`, as usual.  Insert_zero is kinda weird with respect to an object.  Perhaps just return `null` for both insert_zero and skip?

**Comment by wchaparro** [comment]
Closing as not planned.
