### ISSUE TITLE
auto_expand_replicas with closed indices

### ISSUE THREAD

**Issue by dshopov** [elastic/elasticsearch#22993]
**Elasticsearch version**: 5.2.0
**Description of the problem including expected versus actual behavior**:
Setting auto_expand_replicas works as expected when you add a node, however if you have a closed index with the setting ES will not update the number_of_replicas on any index when stopping a node.

I guess this is connected to the error you get when trying to set number_of_replicas on a closed index:
Can't update [index.number_of_replicas] on closed indices [[index/lHETwEIvTy23Zm2kaAhJ0g]] - can leave index in an unopenable state

**Steps to reproduce**:
 1. Make 2 indices with "auto_expand_replicas": "0-all"
 2. Close one of the indices 
 3. Add a node to expand the replicas to nodes-1 (as expected)
 4. Stop one node - cluster goes to yellow state

**Comment by ywelsch** [comment]
This is indeed a bug. Two things come to my mind here:
1) The system should probably not automatically adjust the number of replicas on a closed index.
2) The reason why `index.number_of_replicas` cannot be updated on a closed index - leaving the index in an unopenable state, is not true anymore since ES v5.0.0 as we are now using allocation IDs (https://github.com/elastic/elasticsearch/issues/14739) that don't have that problem.

**Comment by ywelsch** [comment]
Fixed by #30423, in particular https://github.com/elastic/elasticsearch/pull/30423/files#diff-495f5ad1cf8822630b8ab7779926d8beR136 where we now don't expand `number_of_replicas` when an index is closed.
