### ISSUE TITLE
_reindex API restriction

### ISSUE THREAD

**Issue by maxosprojects** [elastic/elasticsearch#23033]
Hi,
Apologies if I missed the reason for the following to be implemented the way it is, but it looks like a restriction without a good reason. For that reason I'm not sure whether this would be a bug report or a feature request.

**Elasticsearch version**: 2.4, 5.x, master

**Plugins installed**: []

**JVM version**: 8.0

**OS version**: MacOS Sierra

**Description of the problem including expected versus actual behavior**:
There is an index with a parent type and two child types.
The use-case requires to reassign child types to other parents.
The `conflicts` query parameter is to be set to `proceed` in this use-case as the application guarantees no changes to the documents during reindexing.
As the number of child documents to reassign may be quite large `_reindex` API looks like a perfect tool for the job to offload that to and to avoid transferring large amounts of data back and forth.
The idea was to update `_routing` and `_parent` to do that.
The same use-case also requires to update one field in child documents to match a field in the new parent as data denormalization technique to enable certain queries. An example of such a query would be "get all child documents with trigger date 6 months after trigger date in parent document", thus child documents have both dates, one of which must always match parent's trigger date.
However, there is a check in `org.elasticsearch.index.reindex.TransportReindexAction.validateAgainstAliases()` that prevents reindexing into the same index. I can't find a good reason why.
Please let me know if more information is required.
Please also let me know if that is a reasonable and actionable request so I can create a PR to change/fix this.

**Steps to reproduce**:
 1. Create an index with one type
 2. Create a document in that type
 3. Reindex that document using `_reindex` API supplying the same index in both `source` and `dest` fields in the reindex query

**Expected**:
The document is reindexed without an error.

**Observed**:
Exception is thrown stating: `reindex cannot write into an index its reading from [some_index]`

**Comment by clintongormley** [comment]
@nik9000 could you reply please?

**Comment by nik9000** [comment]
Sure, sure. We chose not to let reindex index back to the same index because for the most part it isn't the right thing to do. It is very easy to get into trouble with versioning when you reindex back to the same index or to make duplicate copies, etc. At the time we figured "folks can always do the _scroll/_bulk process themselves". And, you totally can. `_reindex` still doesn't do anything you couldn't do with a script running on the coordinating node. It is much easier though.

And the process you are trying to do is fairly fraught - moving a document from one parent to another means you very well *might* have two copies of the document. You might not, if the two parents happened to be on the same shard.

Anyway, presuming you work around that issue on your own, you actually *can* reindex to the same index. As soon as you turn on `remote` reindex turns off the same index check. So you can totally try it.

Personally I'd write a script that deletes and indexes each document. If you do it in two bulks, both of which `refresh=true` or `refresh=wait_for`, putting all the deletes first and all the indexes second then you won't see duplicate documents. You will miss documents though, but that is the price we pay for not coordinating refreshes across shards.

**Comment by clintongormley** [comment]
thanks @nik9000

**Comment by maxosprojects** [comment]
Thank you for your response!
I do understand the risks when applying it without due care. However, at the same time there are plenty other ways to screw your data.

Could you please elaborate on "You will miss documents though, but that is the price we pay for not coordinating refreshes across shards"? Is that in case we delete first?
Also, I'm not sure if I missed a feature in Elasticsearch or you're referring to some script to run outside elasticsearch when you say "Personally I'd write a script that deletes and indexes each document". Could you please clarify?

And one more thing, "folks can always do the _scroll/_bulk process themselves" assumes physically loading documents to the application and then reindexing them from that application back, did I get that right?

I know it is recommended to delete first, but in order to not lose a single document we can't do that (there are plenty possible failure scenarios that would interrupt indexing documents back). The way our index is set up it is easy to find and delete old copies (that has been accounted for) - the new copies will belong to new parent and both have some identifying information, so it's easy to delete old copies by query.

Thanks again for taking time to respond!
