### ISSUE TITLE
Deadlock when index.translog.sync_interval: 99999s

### ISSUE THREAD

**Issue by avleen** [elastic/elasticsearch#23084]
**Elasticsearch version**: 2.4.4

**Plugins installed**: delete-by-query, mapper-size

**JVM version**: Oracle JDK 1.8.0_60

**OS version**: CentOS 7.3

**Description of the problem including expected versus actual behavior**:
Accepting that this increases the potential for data loss, we wanted to try and disable the translog flush, for performance reasons.
We can't actually disable it, so we set it to 99999s, and the size to 1Gb.
We have a 32Gb heap and there should be plenty of room for the extra data.
After a few minutes of running, the node mostly stops processing data, except for maybe we very small trickle.

Data is log lines coming from Logstash and we see the bulk thread pull maxed out, as well as the bulk queue. Neither number moves.

**Steps to reproduce**:
 1. Close all indices
 2.
```
curl -XPUT 'localhost:9200/_all/_settings' -d '{
  "settings": {
    "index.translog.durability": "async",
    "index.translog.sync_interval": "99999s"
  }
}'
```
 3. Ship large amounts of logs.

**Provide logs (if relevant)**:
The output of hot_threads?threads=20 for this host is available here:
https://gist.github.com/avleen/640903a62ad422fe5b4997a198d0c85b

The thread dump is available here:
https://gist.github.com/avleen/859a36980c580d5ec1b90c1af8074185

**Comment by jasontedor** [comment]
I note that every bulk thread is waiting to acquire the same keyed lock (`parking to wait for  <0x00007f26766977b8>`) except for one which is busy indexing and presumably holding the lock that the other threads want. As locks are held by uid, this indicates to me that all your threads are indexing the same uid. Through the engine, indexing is single-threaded per uid. I see no indication that the translog is the problem here, but rather there appears to be a problem with your requests all using the same uid.

**Comment by avleen** [comment]
Huh. This is awesome to know. I have no idea why that would be the case, but I'll dig into it.
Appreciate it, thank you!
