### ISSUE TITLE
Index aliases and delete operation

### ISSUE THREAD

**Issue by Paikan** [elastic/elasticsearch#2318]
Suppose we use the "usersdata flow" exposed in kimchy's "Big Data, Search and Analytics" presentation to index users documents in a big oversharded index with routing+filtering aliases. Some users content are moved to their own index when becoming too big.

From the client perspective we don't know if we are manipulating a virtual index via an alias or a real index dedicated to the user and the code should be the same. So if an user is deleted and we want to remove its content the client code do something like curl -XDELETE localhost:9200/$INDEX_NAME. The power of aliasing being that the client is agnostic of knowing if it deals with a real index or an aliased one.

But with the current behavior if $INDEX_NAME is an alias the whole big oversharded index will be deleted and all users document are lost!

IMHO it is really dangerous. I was expecting a simple delete index if the $INDEX_NAME is a real index under the hood and maybe a delete by query (even if it is expensive) or at least a failure or something like that maybe configurable via a parameter if $INDEX_NAME is an alias linking to the big oversharded index.

What do you think?

**Comment by javanna** [comment]
I just labelled back for discussion, in #11496 we started discussing again what we should do with delete against aliases. Seems like the best approach would be to reject delete against any alias (regardless of whether it's filtered or not). Also, when we expand wildcards we should not expand to aliases only for this api. The latter is trickier to be honest, we don't currently support this and in order to support it we should probably add yet another "indices options", which are already too many. I would love to simplify those indices options and the code around it before adding other ones to the mix.

**Comment by clintongormley** [comment]
++ for not allowing aliases in the DELETE /index api

**Comment by sundarv85** [comment]
+1

**Comment by compasses** [comment]
agree with @jprante , and want to know when will it be fixed.

**Comment by clintongormley** [comment]
Discussed in FixItFriday: expand wildcards to aliases and concrete indices.  If any aliases are present, throw an exception

**Comment by BrickXu** [comment]
+1
In my production cluster, I set an alias for a collection of indices and make the query easily, but somebody delete this alias and indices were lost, it is really dangerous if elasticsearch do nothing for alias.

**Comment by neogeo** [comment]
At the very least, the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html#deleting) should be updated to mention this unexpected behavior. It looks like a lot of people find this out by  trial and error.
