### ISSUE TITLE
Send JSON query via Java API (setSource replacement)

### ISSUE THREAD

**Issue by schulm** [elastic/elasticsearch#23188]
With the big query parsing refactoring in ES 5.x the official Java API for using simple JSON queries is lost "in transit". Before ES 5.x it was the SearchRequestbuilder.prepareSearch().setSource(jsonString) method to get it going. 
In [Elastic.co- Search elasticsearch with java client using JSON query](https://discuss.elastic.co/t/search-elasticsearch-with-java-client-using-json-query/74329/12) @jprante gives a workaround for ES 5.1.1 which is unstable and will break or are already broken in later versions. This feature is really useful while developing complex queries.

**Comment by javanna** [comment]
Queries can be provided as Strings using `WrapperQueryBuilder`. That only works for the query section of a search request though. If json search requests have to be sent, I would recommend to use the low-level REST client rather than the java api. The latter uses the binary transport layer to send the request over to the nodes, hence parsing doesn't happen, what is sent is the binary representation of the requests.

**Comment by zhouhuakang** [comment]
I also need to send the raw json query string to es.how?low level rest client? @mongoDynamo

**Comment by mongoDynamo** [comment]
@zhouhuakang You can convert the high level client to low level like this : https://pastebin.com/9d9kGVeE

Then if you still want to use the functionality of the highlevel client, you can convert the low level response to a SearchResponse (used by high level client) : https://pastebin.com/Lkvz8ELh

I gave up on this approach though as its hard to see what the performance implications are, also its annoying doing a work around for something that used to be supported. 

Since ES doesn't support this, I would recommend maybe using this as a learning or testing item, but not sure if it would be good as permanent implementation.
