### ISSUE TITLE
Update `discovery.zen.fd.timeout` dynamically.

### ISSUE THREAD

**Issue by jason-heo** [elastic/elasticsearch#23230]
This feature request is a follow up issue of [this discussion](https://discuss.elastic.co/t/how-to-update-discovery-zen-fd-timeout-dynamically/75421/5)

`discovery.zen.fd.*` are not dynamically updatable. (tested on Elasticsearch 5.2.1 and 2.3.2)

I hope they can be updated without rolling restart.

Request:
```
PUT /_cluster/settings
{
    "persistent": {
        "discovery.zen.fd.timeout": "10s"
    }
}
```

Response of ES 5.2.1:
```
{
   "error": {
      "root_cause": [
         {
            "type": "illegal_argument_exception",
            "reason": "persistent setting [discovery.zen.fd.timeout], not dynamically updateable"
         }
      ],
      "type": "illegal_argument_exception",
      "reason": "persistent setting [discovery.zen.fd.timeout], not dynamically updateable"
   },
   "status": 400
}
```

**Comment by jasontedor** [comment]
What's the use case for this being dynamically updatable? These settings should generally be kept small, but not too small, and I do not see a good reason for them to be dynamically updatable. Can you please explain?

**Comment by jason-heo** [comment]
@jasontedor 

Hi. Thank you for your reply.

Yesterday, I had to take heap dump of ES java process. During heap dump, JVM stopped longer than `discovery.zen.fd.*` settings, so that the node disconnected from the cluster.

I agree with `These settings should generally be kept small, but not too small` but I think this is not reasonable they should be static.

I didn't know that it's going to complicated and my use case is very rare. (The reason I needed heap dump is that I just wanted to know which classes take more memories) So it's up to you ;)

Thanks.

**Comment by jasontedor** [comment]
Thanks for the reply @jason-heo. When you take a heap dump of a node, the node is in a stop-the-world pause and is indistinguishable from being dead. You want fault detection to do its job so that client and indexing requests are not routed to this node otherwise the effects will trickle through the entire cluster and impact client traffic. If you're concerned about replica shards reallocating away from this node while it's offline, you can use [delayed allocation](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/delayed-allocation.html) to address this.

Additionally, modifying the fault detection settings in a scenario like this is dangerous. If you forget to return the settings back to their reasonable values after performing the heap dump, you're subject to the same risks anytime the node enters a natural long garbage collection pause.

Thanks for the feature request @jason-heo, this setting should stay static though.
