### ISSUE TITLE
1,526,477,536 bytes (36 %) of Java heap is used by 480 instances of org/apache/lucene/index/SegmentCoreReaders

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#23283]
Elasticsearch version:
2.1
Plugins installed: []
delete-by-query
elasticsearch-analysis-ik
repository-hdfs
JVM version:
jdk1.8.0_60
OS version:
CentOS Linux release 7.1.1503
Description of the problem including expected versus actual behavior:
data nodes' memory is under a lot of presure and use heap dump to check and found below info:
1,526,477,536 bytes (36 %) of Java heap is used by 480 instances of org/apache/lucene/index/SegmentCoreReaders
Contains 2 instances of the following leak suspects:
- array of java/util/concurrent/RunnableScheduledFuture holding 30,322,632 bytes at 0x638849500
- array of java/util/concurrent/ConcurrentHashMap$Node holding 958,549,704 bytes at 0x66253cb60

so my question is:
https://issues.apache.org/jira/browse/LUCENE-5254
is this only fix in  4.5.1, 4.6, 6.0  but not in 5.3.1.jar?

**Comment by jpountz** [comment]
Thanks, I just fixed the versions, it was fixed in 5.0 too.

**Comment by jpountz** [comment]
This likely means the node you are looking at has about 480 segments, which is not too surprising if you have 5+ shards on this node. You can look at the segments API with the `verbose` flag turned on in order to see where memery goes: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-segments.html#_verbose_mode (beware, the output is very verbose).

**Comment by makeyang** [comment]
@jpountz  thanks. so I guess we can close this issue.
