### ISSUE TITLE
ES_* deprecated variables shouldn't exit 1 based on ES own recommendation

### ISSUE THREAD

**Issue by cdenneen** [elastic/elasticsearch#23332]
Line 76 of 5.2.1 /usr/share/elasticsearch/bin/elasticsearch recommends adding ES_HEAP_SIZE to ES_JAVA_OPTS but if testing for that causes an `exit 1` then it's not correct.

```
    64	if test -n "$ES_MIN_MEM" ||
    65	   test -n "$ES_MAX_MEM" ||
    66	   test -n "$ES_HEAP_SIZE" ||
    67	   test -n "$ES_HEAP_NEWSIZE" ||
    68	   test -n "$ES_DIRECT_SIZE" ||
    69	   test -n "$ES_USE_IPV4" ||
    70	   test -n "$ES_GC_OPTS" ||
    71	   test -n "$ES_GC_LOG_FILE"; then
    72	    echo "Error: encountered environment variables that are no longer supported"
    73	    echo "Use jvm.options or ES_JAVA_OPTS to configure the JVM"
    74	    unsupported_environment_variable "$ES_MIN_MEM" ES_MIN_MEM "set -Xms$ES_MIN_MEM in jvm.options or add \"-Xms$ES_MIN_MEM\" to ES_JAVA_OPTS"
    75	    unsupported_environment_variable "$ES_MAX_MEM" ES_MAX_MEM "set -Xmx$ES_MAX_MEM in jvm.options or add \"-Xmx$ES_MAX_MEM\" to ES_JAVA_OPTS"
    76	    unsupported_environment_variable "$ES_HEAP_SIZE" ES_HEAP_SIZE "set -Xms$ES_HEAP_SIZE and -Xmx$ES_HEAP_SIZE in jvm.options or add \"-Xms$ES_HEAP_SIZE -Xmx$ES_HEAP_SIZE\" to ES_JAVA_OPTS"
    77	    unsupported_environment_variable "$ES_HEAP_NEWSIZE" ES_HEAP_NEWSIZE "set -Xmn$ES_HEAP_NEWSIZE in jvm.options or add \"-Xmn$ES_HEAP_SIZE\" to ES_JAVA_OPTS"
    78	    unsupported_environment_variable "$ES_DIRECT_SIZE" ES_DIRECT_SIZE "set -XX:MaxDirectMemorySize=$ES_DIRECT_SIZE in jvm.options or add \"-XX:MaxDirectMemorySize=$ES_DIRECT_SIZE\" to ES_JAVA_OPTS"
    79	    unsupported_environment_variable "$ES_USE_IPV4" ES_USE_IPV4 "set -Djava.net.preferIPv4Stack=true in jvm.options or add \"-Djava.net.preferIPv4Stack=true\" to ES_JAVA_OPTS"
    80	    unsupported_environment_variable "$ES_GC_OPTS" ES_GC_OPTS "set ${ES_GC_OPTS// / and } in jvm.options or add \"$ES_GC_OPTS\" to ES_JAVA_OPTS"
    81	    unsupported_environment_variable "$ES_GC_LOG_FILE" ES_GC_LOG_FILE "set -Xloggc:$ES_GC_LOG_FILE in jvm.options or add \"-Xloggc:$ES_GC_LOG_FILE\" to ES_JAVA_OPTS"
    82	    exit 1
    83	fi
```

Either that recommendation needs to be removed or the test wrapped around ES_HEAP_SIZE needs to be more forgiving (in it's own test that doesn't `exit 1`)

Many of these suggestions are to add these variables to `ES_JAVA_OPTS` but if they exist then it will not start. May the `exit 1` be removed from line 82?

**Comment by jasontedor** [comment]
I think that you're misunderstanding the purpose of these lines. The purpose of these lines is to inform you that environment variables that we use to support are no longer supported. It would be awful to migrate from Elasticsearch 2.x (where `ES_HEAP_SIZE` was a common way to set the heap size) to Elasticsearch 5.x (where `ES_HEAP_SIZE` does nothing) and Elasticsearch silently marches on ignoring `ES_HEAP_SIZE`. Instead we say if `ES_HEAP_SIZE` (or any of the other now unsupported environment variables are set, we are going to refuse to start); this way the user can fix their configuration so that Elasticsearch starts the way that they intended it. In this specific case, we are not saying to set `ES_JAVA_OPTS` to the literal string `-Xms$ES_HEAP_SIZE -Xmx$ES_HEAP_SIZE` but rather to set it to the literal string `-Xms1g -Xms1g` if `ES_HEAP_SIZE` was equal to `1g` (or, more preferably, set these in `jvm.options`). Precisely, if you start Elasticsearch 5.x with `ES_HEAP_SIZE` set, this is what is displayed:

```
12:57:30 [jason:~] $ ES_HEAP_SIZE=1g ~/elasticsearch/elasticsearch-5.2.1/bin/elasticsearch
Error: encountered environment variables that are no longer supported
Use jvm.options or ES_JAVA_OPTS to configure the JVM
ES_HEAP_SIZE=1g: set -Xms1g and -Xmx1g in jvm.options or add "-Xms1g -Xmx1g" to ES_JAVA_OPTS
```
