### ISSUE TITLE
Disk Threshold Decider should be disabled only in development mode

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#23395]
Currently the disk threshold decider is disabled, when there is only [one data node available](https://github.com/elastic/elasticsearch/blob/7c6d5cbf1fd7e43667cd5e796fe106694016f026/server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/DiskThresholdDecider.java#L373) in the cluster (the decider was added way before we had a notion of development/production mode). I think it might make sense disable the disk threshold decider only in development mode, so that even single node clusters do not allocate new shards, when there is not enough space left.

**Comment by DaveCTurner** [comment]
[Two ideas](https://github.com/elastic/elasticsearch/pull/26854#pullrequestreview-66822620) are:

- get rid of the `cluster.routing.allocation.disk.threshold_enabled`, since this can be emulated by setting all the thresholds to `"100%"`, and

- have different default thresholds based on the production/development distinction. It makes sense that the "developer running on laptop that's low on space" use case would perhaps want a small (absolute?) threshold just to prevent the whole thing breaking on a full disk without unduly restricting usage.

**Comment by DaveCTurner** [comment]
We discussed this briefly and think [this](https://github.com/elastic/elasticsearch/issues/23395#issuecomment-378354313) are reasonable ways forward. There is no urgency on this so it's being marked as adoptme.

**Comment by DaveCTurner** [comment]
I opened #30254 and #30256 to remove the `cluster.routing.allocation.disk.threshold_enabled` setting.

I'm not sure about the second point, however. There do not seem to be many (any?) other settings whose default values vary between production and development mode, so this behaviour may cause surprise.

One possible approach is to remove the default values for the watermarks in production mode, insisting that they are explicitly configured, and then change the (development-mode-only) defaults to more appropriate values. It seems a little harsh to do this, but the alternatives all seem to be trappily lenient.

**Comment by jasontedor** [comment]
> There do not seem to be many (any?) other settings whose default values vary between production and development mode, so this behaviour may cause surprise.

I agree that we should not do this.

**Comment by DaveCTurner** [comment]
We have looked at this a few times and have been unable to reconcile it with our desire for dev mode and prod mode to be as close as possible in behaviour. Although it's a good idea we have also not seen a lot of further support for it. I would like to close this to indicate that we do not intend to work on this now, but you are welcome to leave further comments, including +1s indicating that this change would be valuable to you, so that we might reconsider this decision in future.
