### ISSUE TITLE
Lost data in Elasticsearch Cluster

### ISSUE THREAD

**Issue by DienNM** [elastic/elasticsearch#23412]
**Elasticsearch version**: 2.4.1

**JVM version**: 1.7

**OS version**: Ubuntu 14.0.10

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

I am setting up ES cluster (v.2.4.1). There are 2 nodes in my cluster, called: A, B.
I started 2 nodes and feed data into ES by using java api. My index had 3 shards and 1 replica. I did query from every nodes, I got the same data. Total is 1000 records.

I stopped Node A. Keep feeding data into ES by my java app. total record I counted from Node B is 1500.

I stopped Node B. And started Node A. Total records are 1000 in Node A. After some minutes, I started Node B. But total records are 1000 now for both nodes.

I expected to get 1500 records after Node B started again. But did not. Could you please help on this?

I just changed the ES config: discovery.zen.ping.multicast.enabled: false discovery.zen.ping.unicast.hosts: ["Node A", "Node B"]

My Java code: servers=ip_nodeA:9300,ip_nodeB:9300

**Provide logs (if relevant)**:
Here is my java code: 
Settings settings = Settings.settingsBuilder()
                .put("client.transport.sniff", true)
                .put("cluster.name", esClusterName)
                //.put("client.transport.ping_timeout", clientPingTimeout)
                .build();
        client = TransportClient.builder().settings(settings).build();
        for (String[] server : servers) {
            String host = server[0];
            int port = Integer.valueOf(server[1]);
            client.addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName(host), port));
        }

**Describe the feature**:

**Comment by bleskes** [comment]
There are a couple of problems in this setup. The first is the use of a two node cluster without setting [min master node](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/modules-node.html#split-brain) to 2. This is required to make sure each node doesn't make it's own decisions while the other node is away.  This also means that a 2 node setup can not be safe and highly available. 

Sadly, even if you used 3 nodes (add a node C to your mix), ES prior to 5.0 was too trigger happy to accept an old stale shard copy. The assumption was that you better have some data than no data at all. I.e., when node A is started, together with node C, 2.x prefered to use node A' copy rather than waiting for Node B's copy to become available. Of course, this is wrong and should be not be done automatically. This issue has been fixed in 5.x and you can read about it [here](https://www.elastic.co/blog/tracking-in-sync-shard-copies).

Last, if you start a new clusters, please do use the latest 5.x. So many good things went into it and its a shame to miss them.

**Comment by DienNM** [comment]
Thank you for your explain.
I am using ES 2.4.1, and I must set minimum_master_node to 2 to prevent writes. 
By the way, If my data only needs to scale (disk) on X servers (Digital Ocean droplets), should I set  minimum_master_node corresponding to number of servers?

**Comment by DienNM** [comment]
Ok. Thanks
