### ISSUE TITLE
Installation from deb fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by Uninen** [elastic/elasticsearch#23498]
**Elasticsearch version**:

5.2.2

**Plugins installed**: []

[]

**JVM version**:

openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

**OS version**:

Ubuntu 16.04

**Description of the problem including expected versus actual behavior**:

Installation gives an error and while binaries are installed, for example /etc/elasticsearch has only script folder but no files.

`Preparing to unpack .../elasticsearch_5.2.2_all.deb ...
Unpacking elasticsearch (5.2.2) ...
Processing triggers for systemd (229-4ubuntu16) ...
Processing triggers for ureadahead (0.100.0-19) ...
Setting up elasticsearch (5.2.2) ...
Couldn't write '1' to 'kernel/yama/ptrace_scope', ignoring: No such file or directory
`

**Steps to reproduce**:
 1. follow instructions at https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html
 2. sudo apt get install elasticsearch

**Provide logs (if relevant)**:

service status displays this message:

`root@controller:/etc/default# service elasticsearch status
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since ti 2017-03-07 11:53:13 EET; 2s ago
     Docs: http://www.elastic.co
  Process: 16199 ExecStart=/usr/share/elasticsearch/bin/elasticsearch -p ${PID_DIR}/elasticsearch.pid --quiet -Edefault.path.logs=${LOG_DIR} -Edefault.p
  Process: 16183 ExecStartPre=/usr/share/elasticsearch/bin/elasticsearch-systemd-pre-exec (code=exited, status=0/SUCCESS)
 Main PID: 16199 (code=exited, status=78)

maalis 07 11:53:12 controller elasticsearch[16199]:         at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:197)
maalis 07 11:53:12 controller elasticsearch[16199]:         at org.elasticsearch.common.logging.LogConfigurator.configureStatusLogger(LogConfigurator.ja
maalis 07 11:53:12 controller elasticsearch[16199]:         at org.elasticsearch.common.logging.LogConfigurator.configureWithoutConfig(LogConfigurator.j
maalis 07 11:53:12 controller elasticsearch[16199]:         at org.elasticsearch.cli.Command.main(Command.java:85)
maalis 07 11:53:12 controller elasticsearch[16199]:         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89)
maalis 07 11:53:12 controller elasticsearch[16199]:         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82)
maalis 07 11:53:13 controller elasticsearch[16199]: ERROR: no log4j2.properties found; tried [/etc/elasticsearch] and its subdirectories
maalis 07 11:53:13 controller systemd[1]: elasticsearch.service: Main process exited, code=exited, status=78/n/a
maalis 07 11:53:13 controller systemd[1]: elasticsearch.service: Unit entered failed state.
maalis 07 11:53:13 controller systemd[1]: elasticsearch.service: Failed with result 'exit-code'.
`

/var/log/elasticsearch is empty.

There was an (really) old elasticsearch install on the server at some point but it was uninstalled years ago, if it makes a difference.

**Comment by jasontedor** [comment]
As we test installation of the Debian package on Ubuntu 16.04 as part of our packaging tests, I think that this is something that is specific to your system rather than a bug in the packaging. I think their are culprits to check; in my mind SELinux would be the first culprit to check. You could also try installing the Debian package with the environment variable `ES_SKIP_SET_KERNEL_PARAMETERS` set to `true` (if you use `sudo`, keep in mind that environment variables will be lost by default so you have to account for this). Note that this will leave you without `vm.max_map_count` check set to 262144, so you should set this manually.

Since this looks like an environment problem on your end, and Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests, I hope that you do not mind if I close this issue. If you do open a post on the forum, please feel free to link to it from here.
