### ISSUE TITLE
Reindex: support script fields

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#23558]
Right now reindex doesn't do anything special with `script_fields`. It'd be nice if it crammed them into the document being reindexed. This'd make it convenient to generate new fields using doc values. It'd look like:

```
POST _reindex
{
  "source": {
    "index": "foo",
    "script_fields": {
      "radish": {
        "script": "doc.ints.stream().map(i -> i * i).collect(Collectors.toList())"
      }
    }
  },
  "dest": {
    "index": "copy"
  }
}
```

That'd create a new index, copying `foo` and adding the field `radish` field. The nice thing about the script for `radish` is that it is the same script as you'd use in `script_fields` or a `terms` aggregation.

**Comment by kris-t-tsoi** [comment]
I'm new to this project and am interested in trying to implement this enhancement.
can I confirm that you are wishing to put the below text into the document being re-indexed? 
"script_fields": {
      "radish": {
        "script": "doc.ints.stream().map(i -> i * i).collect(Collectors.toList())"
      }


Is there anything else I should know about this ?
Thanks !!!!

**Comment by henningandersen** [comment]
We discussed this issue as a team and seek further clarification. The example given in the description seems to be equally easily solved by applying a script at index time instead.

But we were wondering if there is another underlying use case: supporting reindex of documents with [disabled source or source filtering](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-source-field.html).

Our question is: Are there any valid use cases where reindex would need to reconstruct the source due to disabled source or source filtering? Or would such use cases not really care about reindex since data age out quickly anyway?

If there are no such use cases, we intend to close this issue.
