### ISSUE TITLE
Tasks index backwards compatibility work for 6.0

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#23631]
We need to enhance `OldIndexBackwardsCompatibilityIT` to always include the `.tasks` index for versions after 5.0. And we'll need to make `.tasks` compatible with #15613.

**Comment by bleskes** [comment]
@nik9000 I presume this is no longer relevant?

**Comment by nik9000** [comment]
I suspect we're safe here, yes. We should do *something* about the tasks index but that can wait for a while.

**Comment by ofavre** [comment]
On my cluster upgraded from 6.x (6.2 and probably 6.1 before that) to 6.4, the `.tasks` index was not automatically created.
What can I do to create it with proper mapping?
How can I ensure the mapping will stay up-to-date when upgrading ES without manual steps if possible?

**Comment by ofavre** [comment]
OK forget it, I found https://github.com/elastic/elasticsearch/blob/master/server/src/main/resources/org/elasticsearch/tasks/task-index-mapping.json and the code https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/tasks/TaskResultsService.java shows that it is auto-created and auto-updated.
The issue was that I had an index template that used _doc as mapping, so the index creation failed with `Rejecting mapping update to [.tasks] as the final mapping would have more than 1 type: [task, _doc]`, and I could have seen this in the logs.
Thanks.

**Comment by nik9000** [comment]
Ah! Sorry about that. I'm finding more and more things that make me regret having a tasks index at all. It made sense at the time but is making less sense now.
