### ISSUE TITLE
Sort on multiple fields doesn't work

### ISSUE THREAD

**Issue by SLavrynenko** [elastic/elasticsearch#23730]
"version" : {
    "number" : "2.4.4",
    "build_hash" : "fcbb46dfd45562a9cf00c604b30849a6dec6b017",
    "build_timestamp" : "2017-01-03T11:33:16Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.2"
  },

NEST version 2.4.6

I've the following code:

response = client.Search<MyEntity>(
                  s => s.Query(
                    q => GetQueryContainer(q))
                    .Index(Settings.IndexName)
                    .Source(sfd => SourceSelector(sfd))
                    .From(fromRow)
                    .Size(pageSize)
                    .Sort(s1 => s1.Field("Firstname", SortOrder.Descending))
                    .Sort(s1 => s1.Field("Lastname", SortOrder.Descending))
                    );

and as I see in the logs I have sort on the field that is used in the last Sort method. If I add the new Sort method in a chain I will get sorting on that field and not on all of them:

{"from":0,"size":20,"sort":[{"Lastname":{"order":"desc"}}],"_source":{"include":["Firstname","Lastname"],"exclude":[]},"query":{...}}

**Comment by javanna** [comment]
hi @SLavrynenko , are you able to print out the request that gets sent? That would be useful to figure out where the problem is, either in the interaction with the client or on the server side. May I ask you to move this to our [discuss forum](https://discuss.elastic.co/) though as it seems more of a question than a bug? The github issues list is reserved for bug reports and feature requests only. Feel free to reopen if it turns out that this is a bug in elasticsearch.
