### ISSUE TITLE
Why Amazon's Elasticsearch Service getting so slow while adding multiple mappings?

### ISSUE THREAD

**Issue by penteleq** [elastic/elasticsearch#23748]
I'm trying to add multiple mappings into single index. 

Does AWS has unwritten limits for setting up multiple types for one index ? 

Regarding to best practices from: https://www.elastic.co/guide/en/elasticsearch/guide/current/mapping.html

I'm putting same mapping structure for different type in single index just to limit entries by its type (products).

The case is that adding about 200 types into index is executed quite fast, but after this limitation (I'm currently at 416th element) it takes about 2 minutes to execute PUT method, and returns response exception from AWS without any message - but in the end type is added. This is working but adding new types is like a pain. 

Please advise!

**Comment by jasontedor** [comment]
We do not support the AWS Elasticsearch Service. Additionally, Elastic prefers to use GitHub only for verified bug reports and feature requests. We do provide a [forum](https://discuss.elastic.co) where you might be able to get answers to your questions. Since there is no bug report here, I hope you don't mind if I close this.
