### ISSUE TITLE
Elements of a long array field have either int or long type depending on the value in painless script

### ISSUE THREAD

**Issue by Tomassino** [elastic/elasticsearch#23763]
**Elasticsearch version**: 5.2.2

**JVM version**: openjdk version "1.8.0_121"

**OS version**: Ubuntu 16.04

**Description of the problem including expected versus actual behavior**:

I'm experiencing problems while writing a painless script to remove values from an array field of type long. When using `indexOf` to find the index of a value in the field, it only works if the value is "big", as it seems that elements from the field are returned as int or long depending on their value (i.e. they are only returned as long if they don't fit in an int)

**Steps to reproduce**:
 1. Create a mapping with a long field

```
curl -XPUT localhost:9200/test_20170327 -d '{
  "mappings": {
    "test" : {
      "properties" : { "values" : {"type": "long"} }
    }
  }
}'
```

 2. Put a document

```
curl -XPUT localhost:9200/test_20170327/test/1 -d'{
  "values": [1, 2, 3, 999999999999999999]
}'
```

 3. Update the document to remove some values using a script

```
curl -XPOST localhost:9200/test_20170327/test/1/_update -d'{
  "script": {
    "inline": "for (long v: params.values) { int idx = ctx._source.values.indexOf(v); if (idx != -1) {ctx._source.values.remove(idx)} }",
    "lang": "painless",
    "params": { "values": [1, 7, 999999999999999999] }
  }
}'
```

 4. The result of a get on the document is now:

```
{
  "_index" : "test_20170327",
  "_type" : "test",
  "_id" : "1",
  "_version" : 2,
  "found" : true,
  "_source" : {
    "values" : [
      1,
      2,
      3
    ]
  }
}
```

The value 1 has not been removed. What is strange is that, before the update, using `Debug.explain(ctx._source.values[0])` (the element in the array is 1) gives `"class" : "java.lang.Integer"`, while `Debug.explain(ctx._source.values[3])` (the element in the array is 999999999999999999) gives `"class" : "java.lang.Long"`. Moreover if in the for loop I substitute `def` to `long` as the type of `v`, everything works as expected.

I'm not sure whether this is a bug or not and whether the solution using `def` is the correct approach, but treating elements of a long field as either int or long depending on the value (and as a consequence not finding them in the array) doesn't sound "right" to me. Things are even worse considering that (as it seems) 1L != 1 (I have verified that the call to `indexOf` with 1L actually returns -1, even if the array actually contains a 1)

**Comment by markharwood** [comment]
I expect the issue being that stored values are not being materialized into the script context using the numeric type defined in the mapping.

**Comment by jdconrad** [comment]
I believe @markharwood is correct here.  If _source was working with mappings, using long as the type in the for loop would be correct as well.  

Unfortunately, since that isn't the case, there's a few things happening here leading to the current situation.

1. The values as part of the params list is being parsed where the smallest available type starting with int will be applied to the number.  That means params.values ends up being a  List of Integers and Longs (note the difference here is they are boxed types since Java forces them to be so as part of a List)
2. _source not respecting mappings means that it's parsed with the smallest available type starting with int.  This means that _source.values ends up being a List of Integers and Longs as well
3. In Painless 1L == 1 is a true statement; however, for boxed types this is not the case (and it's not the case in Java or Groovy either).  We are left with few reasonable options here other than to follow the Java model since Painless is built on the JVM and for performance reasons.   When indexOf is called on the values List the type is implicitly boxed meaning that int becomes Integer or long becomes Long, and Long(1) == Integer(1) is a *false* statement unfortunately.

Since there is symmetry between the types in params.values and _source.values, def will work here.  def will either become an int or a long depending on the value pulled from the params.values List and the boxed to an Integer or Long when _source.values.indexOf is called.

However, I believe you can simplify this script by doing ```ctx._source.values.removeAll(params.values);```

**Comment by Tomassino** [comment]
I found another variation of this problem when using the java api. To be honest I'm using scala and elastic4s, but that library is only a wrapper, so I suppose what I'm going to say also holds when using the java api directly (if you think that there could be a substantial difference, I could try to write a small java program to verify the issue). In the example above, even when using `removeAll` of `def` in the for loop, the value 1 is not removed. It seems like in this case 1 in the list of values is actually considered a `long`. I'm not sure, but could this be related to the fact that the java api uses protocol different from the one used by the curl example?

P.S.: thanks @jdconrad for the hint about `removeAll`!
P.P.S.: I've not yet tried 5.3, I'll do as soon as possible

**Comment by jdconrad** [comment]
@Tomassino When using def are the other numbers except for 1 removed or are all the numbers in the Java int range being left behind?  If only 1 is left that seems like a bug and would certainly be worth looking into more.  As for the java api versus curl, it's very possible that using java causes all the values to be longs in the params list.  If that's the case, we should probably find a way to at least be consistent.

**Comment by Tomassino** [comment]
No number in the Java int range is removed (e.g. 2147483647 is NOT removed, while 2147483648 is). It really seems that all values in parameters are taken as long, when using the java API, while for values in the document the type is inferred taking the value into account

**Comment by jdconrad** [comment]
This is another issue outside of scripting related to JSON parsing and how values are input into the scripts.

**Comment by jdconrad** [comment]
Closing this as there's a work around and it's related to parsing issues.
