### ISSUE TITLE
Cannot recover from bad analysis settings

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#23787]
This problem was reported at https://discuss.elastic.co/t/keyword-filter-requires-either-keywords-or-keywords-path-to-be-configured/80332/3. If you update analysis settings with an empty list of keywords in a keyword marker filter on a closed index, the index will fail to reopen and there does not seem to be any way to recover from this situation. This problem was reported on Elasticsearch 5.2 but reproduces on master:

```
DELETE my_index

PUT my_index

POST my_index/_close

PUT my_index/_settings
{
  "index": {
    "analysis": {
      "filter": {
        "my_keywords": {
          "type": "keyword_marker"
        }
      }
    }
  }
}
```

Once we reach this point, it does not seem possible to open the index again. For instance, the commands below that try to set a dummy list of keywords to make the filter valid again fail:

```
POST my_index/_open

POST my_index/_close

PUT my_index/_settings
{
  "index": {
    "analysis": {
      "filter": {
        "my_keywords": {
          "type": "keyword_marker",
          "keywords": [ "foo", "bar" ]
        }
      }
    }
  }
}
```

**Comment by talevy** [comment]
I dug into this a little to learn more about how things work.

Looks like nothing in the MetadataUpdateSettingsService actually verifies the contents of these analyzers.

There is some verification code in place [here](https://github.com/talevy/elasticsearch/blob/4f694a3312a8bf57794ac9c3613ca6b5a2b52c58/core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataUpdateSettingsService.java#L281)

When it finally reaches a point that it is prepared with a temporary IndexService for checking the metadata update, it never verifies the analyzers, like [how is verified during a true new IndexService creation](https://github.com/talevy/elasticsearch/blob/9a0b216c36e3debb9d48374ced1e58d6568429bd/core/src/main/java/org/elasticsearch/index/IndexService.java#L150)

Since there AnalyzerRegistry in the updateMetadata context, I do not see a way to achieve the same as is done during index creation without more refactoring. If the IndexService kept the AnalysisRegistry that is passed-in around, then it would be as easy to bring that same verification logic into the update code.

I may have an incomplete view into how to properly tackle this, but thought I'd leave these notes just in case it helps
