### ISSUE TITLE
S3 Restore - Repo index files not refreshed

### ISSUE THREAD

**Issue by russellday** [elastic/elasticsearch#23806]
**Elasticsearch version**: 5.1.1

**Plugins installed**: [discovery-ec2, repository-s3]

**JVM version**: 1.8.0_121"

**OS version**: Amazon Linux

**Description of the problem including expected versus actual behavior**:
We hit an issue with trying to restore a from a 2.3.2 ES cluster S3 Repository to a ES 5.1.1 cluster. 

When two clusters have repositories pointing to the same S3 bucket, it looks like different versions of ES get the list of available snapshots for the bucket differently. ES 2.3 uses the index and ES 5.1.1 uses the index-[number] files.

**Steps to reproduce**:
1. Create an S3 repository on a ES 2.3.2 cluster
2. Take a snapshot for the repository created in Step 1.
3. Create a S3 repository on a ES 5.1.1 cluster with the same bucket used in step 1.
4. List snapshots for the repository created in step 3 on the ES 5.1.1 cluster.
5. Create another snapshot in the ES 2.3.2 cluster
6. List snapshots on the ES 5.1.1 cluster repository created in step 3. The results will not contain the snapshot created in step 5.

Workaround:
1. On the ES 5.1.1 S3 repository, delete the index-x files.
2. Issue a list snapshots for the ES 5.1.1 repository forcing the index-x files to be recreated with the current list of snapshots.

**Comment by abeyad** [comment]
This is a known behavior.  Once you connect a 5.x cluster to a repository location, any 2.x clusters connected to the same repository should be setup to be `readonly`.  In fact, that's a general rule with snapshot repositories - only one cluster should be connected to a repository with write permissions, all other clusters connected to that same repository should be in read-only fashion.

**Comment by cheruvian** [comment]
Agreed, however the use case presented here is a setup where the repo is readonly for the ES5 cluster. 

Interestingly, the command to list snapshots does a write to the repo. Most likely in an effort to cache the index state.  This is what causes the problems since the index metadata file is then permanently stored on disk/in the cloud.

i.e. GET /_snapshot/repo_name on ES5 creates the index-x files in the repo.

**Comment by abeyad** [comment]
Actually, the issue here is that when a 5.x cluster connects to the repository, it has to update the snapshot files so it is in a format understood by 5.x (which is a bit different than 2.x) - that's the initial write that you're seeing.  That's why, once a 5.x cluster connects to a repository, the 2.x one should be set to read-only.

**Comment by cheruvian** [comment]
This makes ES5 migrations a little tricky then for users who want to test out ES5 while maintaining their ES2 infrastructure and ingestion until they are able to make a complete cutover. This sounds (to me) like a pretty common/reasonable use case.

I guess I'm ok with marking this as by design if we update [the docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html) since it doesn't seem to mention anywhere about readonly uses.  I would also just like to have this use case kept in mind for the next MV bump.

**Comment by abeyad** [comment]
> This makes ES5 migrations a little tricky then for users who want to test out ES5 while maintaining their ES2 infrastructure and ingestion until they are able to make a complete cutover. This sounds (to me) like a pretty common/reasonable use case.

Its a fair point.  One suggestion is to use your 2.x cluster to take a single snapshot to a different S3 bucket (different repository), then connect your new 5.x cluster to this different S3 bucket so you can experiment with 5.x.  Not sure if this is feasible in your case.

> I guess I'm ok with marking this as by design if we update the docs since it doesn't seem to mention anywhere about readonly uses.

I thought I had updated the docs on this but looks like I forgot to issue a PR for my branch.  Here is the PR to update the docs on this matter: https://github.com/elastic/elasticsearch/pull/23807

> I would also just like to have this use case kept in mind for the next MV bump.

We are aiming for it.

**Comment by dadoonet** [comment]
Interesting. Actually even if someone marks the 5.x repository as readonly the 5.x cluster will write files on the repository to upgrade it? If so I feel it like a bug. WDYT?

**Comment by abeyad** [comment]
> Actually even if someone marks the 5.x repository as readonly the 5.x cluster will write files on the repository to upgrade it? If so I feel it like a bug. WDYT?

@dadoonet No, if the 5.x repository is `readonly`, then the repository data will *not* be upgraded.  

@russellday @cheruvian you *should* be able to set the 5.x repository to `readonly` and not have the data upgraded.  It was my understanding though that the 5.x repository was not set to `readonly`, causing the issue.  If you are setting the 5.x repository to `readonly` and its still upgrading the repository data to have `index-{N}` blobs, then its a bug.

**Comment by abeyad** [comment]
However, I'd still like to point out that while it should work, its not a setup we support.

**Comment by abeyad** [comment]
I confirmed that if you connect the 5.x cluster to the repository in `readonly` mode from the very start, it will *not* upgrade the repository data.
