### ISSUE TITLE
Details of logger for each module 

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch#23819]
It would be great to have information for each section of elasticsearch noting what the name of the logger is which you would make loglevel changes to to debug. I keep on looking and as far as I can tell it's not documented at all and the only way you have if you don't know is to enable debug for the root logger, then identify the entries you want, and update the logging output settings.

We have documentation about [how to change the loglevel](https://www.elastic.co/guide/en/elasticsearch/guide/current/logging.html#logging) but it is very difficult to find the correct module path - e.g. in [alerting troubleshooting](https://www.elastic.co/guide/en/x-pack/5.2/watcher-troubleshooting.html) or [zen discovery](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/modules-discovery-zen.html)

**Comment by colings86** [comment]
This would be a massive effort and unfortunately would go out of date very quickly. The loggers often go down to the class level and even if we detail the loggers at the package level there will be a lot of them and they are subject to change constantly (not just in minor versions). This poses two problems, firstly by documenting them it would set an expectation of backwards compatibility of these loggers which we could not keep in and practical way and secondly it would be hard to impossible to ensure that the documentation of the loggers and the actual loggers used do not diverge. For this reason and because this issue has been open for over a year without gathering much interested I'm going to close it.
