### ISSUE TITLE
Integration tests for reindex-from-remote from older versions

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#23828]
#23805 and other issues have demonstrated that we really need integration tests for reindex-from-remote from older versions of Elasticsearch.  This isn't low hanging fruit because versions of Elasticsearch prior to 5.0 don't know how to spit out pidfiles so we can't use our standard Elasticsearch startup stuff.

**Comment by rjernst** [comment]
> versions of Elasticsearch prior to 5.0 don't know how to spit out pidfiles

Do you mean port files?  I had thought we had those in 2.x, but looking back you are right, it was not until 5.0. However, we could still have a fixture to start those older versions, we would probably want to explicitly pass in a randomly generated port (from a range). And we would need to have different cluster setup tasks, since both we won't be able to look for the ports files, and even configuration like how we pass command line args, or how we install plugins, is different.

**Comment by nik9000** [comment]
Yes, I was thinking that older version of ES would be an independent
fixture and we'd feed it a port. We could check the logs for bind errors.
Or other things to make reasonably sure we don't get them.
