### ISSUE TITLE
Better handling of inline scripts in ingest

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#23824]
Anywhere that scripts are used, we allow writing an inline script in a short form, eg:

    { "script": {
        "lang": "painless",
        "inline": "ctx.foo='bar'
    }}

can also be written as:

    { "script": "ctx.foo='bar'"}

If I try this in ingest:

```
POST _ingest/pipeline/_simulate
{
  "pipeline": {
    "processors": [
      {
        "script": "ctx.foo='bar'"
      }
    ]
  },
  "docs": [
    {
      "_index": "t",
      "_type": "t",
      "_id": "1",
      "_source": {}
    }
  ]
}
```

I get:

```
     {
        "type": "class_cast_exception",
        "reason": "java.lang.String cannot be cast to java.util.Map"
      }
```

While I understand that all processors expect an object and so the short form may not be supported (although it'd be nice to make an exception for scripts), we should at least have an exception which is easier to understand.

**Comment by Dimitrees** [comment]
Hello, I am new to both your project and working with GitHub in general. Can I work on resolving this issue since its labeled as Low Hanging Fruit?

Thanks

**Comment by asettouf** [comment]
Hello,

@Dimitrees are you still working on it, or can I pick it up?

Thanks,

Adonis

**Comment by Dimitrees** [comment]
Its yours, sorry for not unassigning myself earlier.

**Comment by asettouf** [comment]
#24410 

Here is my PR regarding this issue.

**Comment by liketic** [comment]
@talevy Can I work on this? Thanks. 😄

**Comment by talevy** [comment]
yeah @liketic!

If you look at my comment here: https://github.com/elastic/elasticsearch/pull/24410#pullrequestreview-42156108, that is what I had in mind for a possible solution.

**Comment by liketic** [comment]
@talevy Thanks for your help. Seems like this issue is much complexer than I thought. We read the processor configs as `List<Map<String, Map<String, Object>>>`, and in all methods, we assume the value of each key in a `Map` is a `Map`, however, `script` allows the value to be a `String`. That's the problem. So I think we can resolve this through:
1) Read processor configs as  `List<Map<String, Object>>`. But for method `readProcessor`, we need to detect if the `value` object is a `Map` or a `String`. If it's a `String`, need to normalize it to a `Map`.
2) In `ScriptProcessor`, parse `Script` by `Script.parse` as you mentioned. and clear all script related properties. 

I didn't find another place can call the `readScript` method, because the `script` parsing is done in `ScriptProcessor` and `ScriptProcessor` is created in `factory`.  So seems like this resolution is another work around. I'm not a expert to `es`, so I'm not sure if this resolution is make sense to you. 
Happy to know your thoughts. Thanks very much!

**Comment by liketic** [comment]
@talevy I opened a PR as I thought. Please add your comments or close it if it does not make sense. Thanks. 😄
