### ISSUE TITLE
Automatic Source Filtering from Filter Path

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#23858]
I have recently found myself using `filter_path` a lot from REST API calls, which is incredibly useful for reducing the response size, not to mention making it easier to figure out what you actually want from it.

This got me thinking that it would be incredibly convenient to automatically add `_source` filtering when it's not explicitly done, to help to reduce bandwidth between nodes during the fetch phase.

The natural caveat is that it adds a little more work to the data nodes, so it would have to be benchmarked. However, it should be rather trivial to implement because the check is a matter of: `hits.hits._source.*` -> source filtering (plus the few special cases, like `hits.hits._id`). It would similarly be useful to avoid the fetch phase if the filter path doesn't even want `hits.hits` (versus `hits.total` or `aggregations.*`).

**Comment by jpountz** [comment]
> it would be incredibly convenient to automatically add _source filtering when it's not explicitly done, to help to reduce bandwidth between nodes during the fetch phase.

I'm worried it would add significant complexity for marginal gains since nodes of a given cluster must be on a local network.

> It would similarly be useful to avoid the fetch phase if the filter path doesn't even want hits.hits

I have a similar concern about complexity, but this time also about the fact it could make Elasticsearch look faster when source filtering is enabled, which will make users jump to the conclusion that the thing that makes Elasticsearch slow is the size of the produced responses. There is already some tension about the verbosity of the responses that I would like not to increase.

**Comment by bleskes** [comment]
discussed it FixItFriday and agree with @jpountz arguments. We rather not implement this.
