### ISSUE TITLE
Trailing comma in batch size reindex example

### ISSUE THREAD

**Issue by Phrozyn** [elastic/elasticsearch#23865]
For documentation of _reindex usage in 
**Elasticsearch version**: 2.4

I'd like to remove the trailing comma
https://github.com/elastic/elasticsearch/compare/2.4...Phrozyn:patch-1#diff-b79a62e74f359eb1f0fb0ffc7e418104

**Comment by nik9000** [comment]
Sure! Open a PR.

On Sat, Apr 1, 2017, 6:50 PM A Smith <notifications@github.com> wrote:

For documentation of _reindex usage in
*Elasticsearch version*: 2.4

I'd like to remove the trailing comma
2.4...Phrozyn:patch-1#diff-b79a62e74f359eb1f0fb0ffc7e418104
<https://github.com/elastic/elasticsearch/compare/2.4...Phrozyn:patch-1#diff-b79a62e74f359eb1f0fb0ffc7e418104>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/elastic/elasticsearch/issues/23865>, or mute the thread

**Comment by jasontedor** [comment]
Yes, a PR would indeed be appreciated here. To be clear though, an issue is not necessary for a PR, you can directly open and we will give it the attention it deserves!

**Comment by jasontedor** [comment]
Closed by #23878
