### ISSUE TITLE
install elasticsearch 5.3.0  on unbuntu 16 get error

### ISSUE THREAD

**Issue by pangff** [elastic/elasticsearch#24008]
install elasticsearch  on unbuntu 16 get error

```
root@iZ25xhp6pf2Z:~# sudo dpkg -i elasticsearch-5.3.0.deb
(Reading database ... 219497 files and directories currently installed.)
Preparing to unpack elasticsearch-5.3.0.deb ...
Unpacking elasticsearch (5.3.0) over (5.3.0) ...
Setting up elasticsearch (5.3.0) ...
Couldn't write '1024 65536' to 'net/ipv4/ip_local_port_range', ignoring: Invalid argument
dpkg: error processing package elasticsearch (--install):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for systemd (229-4ubuntu14) ...
Processing triggers for ureadahead (0.100.0-19) ...
Errors were encountered while processing:
 elasticsearch
root@iZ25xhp6pf2Z:~# 
```

**Comment by jasontedor** [comment]
At first glance, this does not look like a bug (since the package is known to install successfully in our packaging tests) but rather an issue with your environment. Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
