### ISSUE TITLE
Large json body causes broken pipe error

### ISSUE THREAD

**Issue by ShihaoJing** [elastic/elasticsearch#24038]
Hi,  I am a newbie to elastic search. I need to index many large csv documents (about 150MB). 
My plan is to create a mapping like this:
```
"basetype": {
        "_all": {
          "enabled": false
        },
        "properties": {
          "data": {
            "type": "text"
          },
          "description": {
            "type": "text"
          },
          "downloadURL": {
            "type": "text"
          },
          "format": {
            "type": "text"
          },
          "keyword": {
            "type": "text"
          },
          "title": {
            "type": "text"
          }
        }
      }
```
For 'data' field,  this will be the json string converted from csv file.
When I was trying to post a new json to elastic search, it gave a following error:
```
ConnectionError: ConnectionError(('Connection aborted.', OSError(41, 'Protocol wrong type for socket'))) caused by: ProtocolError(('Connection aborted.', OSError(41, 'Protocol wrong type for socket')))
```
Can anyone help me with this issue? Thanks!

**Comment by jasontedor** [comment]
I suspect that your problem is that you need to increase the `http.max_content_length` which defaults to only 100 MB. If you're sending 150 MB down the pipe and you haven't increased this setting, then Elasticsearch is going to close the connection.

Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by asafm** [comment]
Happened to me too, so it's good that it was here :)
