### ISSUE TITLE
Add test for deploying transport client in Wildfly

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#24050]
A lot of users deploy the transport client inside an application container like Wildfly. This is broken for a lot of users starting in 5.3.0 due to a chain of initializations that ultimately lands in Build which given some deployment models will fail during static initialization. I think this an important use-case for our users, and we should have a qa module that tests deploying the transport client inside of Wildfly so that we do not break this use-case again.

Relates #21955

**Comment by nik9000** [comment]
We should probably also add tests for the high and low level rest client in wildfly while we're at it.

**Comment by Sanne** [comment]
Hi all,

I work on the Hibernate Search project, and we do use the Elasticsearch client on WildFly. We also run integration tests of course.

I had a chat recently with @javanna and promised him that I'd reach out to see if we could contribute the WildFly module structure I'm creating and the related integration tests directly to the Elasticsearch community.

By "module structure" I mean we're repackaging the client as a set of Modules for WildFly, that's a great way for people to use it in this container.
It's work in progress, but if you build this project (just standard Maven) you should already see the structure being built: https://github.com/hibernate/hibernate-search

Please ignore older releases, as they were using Elasticsearch 2 and didn't use the new client yet.

I wasn't really ready to mention this yet, but since I stumbled on this issue I thought it might be worth sharing already... HTH

**Comment by jasontedor** [comment]
> We should probably also add tests for the high and low level rest client in wildfly while we're at it.

I agree with this @nik9000. I started on a subproject that includes the transport client (#24147), and I think that the low-level and high-level REST clients can easily be added to that as follow-ups.

**Comment by jasontedor** [comment]
> I had a chat recently with @javanna and promised him that I'd reach out to see if we could contribute the WildFly module structure I'm creating and the related integration tests directly to the Elasticsearch community.

@Sanne Thanks for the offer, but I do not think we will pull something like that into this repository. I don't think that anyone here would be able to maintain it, and we have a philosophy that if we can not maintain something we should not pull it in. I think that a standalone project would suffice though, and be a useful contribution to the Elasticsearch community.

**Comment by Sanne** [comment]
@jasontedor np, makes perfect sense.

I'm still tinkering on it as we figure out some details for Hibernate Search needs, I certainly plan to extract it into a standalone project: that would allow me to make a new release as soon as a new Elasticsearch release is published.

I merely don't want to keep it into the Hibernate Search repository, as this would tie it up to our release cycles, making it less useful to people interested in using it independently from the Hibernate components.

When I'll separate it, I'll advertise it in the Elasticsearch forums so hopefully we'll be able to collaborate on it with the wider community.

Thanks!
