### ISSUE TITLE
colon seperate

### ISSUE THREAD

**Issue by heiterzhang** [elastic/elasticsearch#24084]
the test as below
"
tody we go to  gdp: debug:DS::MimiFailInfo:return
"

when i search use **MimiFailInfo:return** to  search  ,it returns normally;
bu when i use  part of this words , such as use  **MimiFailInfo** ,it returns empty？？？

**Comment by danielmitterdorfer** [comment]
Hi @heiterzhang. Please ask questions like these in the forum instead: https://discuss.elastic.co/ The Github issues list is reserved for bug reports and feature requests only. Thanks!

When you create a post on Discuss, please include a small self-contained example to reproduce the scenario you are asking about. Otherwise, it is next to impossible to answer your question.
