### ISSUE TITLE
Percolator: High memory usage issue when nested query is registered

### ISSUE THREAD

**Issue by anatoly21** [elastic/elasticsearch#24108]
ES version: 5.2.2.
JDK: 1.8.0_65
OS version: Ubuntu 14.04.4 

We faced high memory usage issue when using percolator.
Dedicated index is configured for percolator.
It works as expected and JVM heap usage picture is 

![without_nested_queries](https://cloud.githubusercontent.com/assets/27484990/25040396/b5e6e152-2111-11e7-92db-3182e11dc73c.JPG)

After registering a nested nested query the picture changes and there is a steady grow of used memory and CPU on the same input document set

![with_nested_query](https://cloud.githubusercontent.com/assets/27484990/25040463/2acc2f0e-2112-11e7-8a10-2edc730e4fc9.JPG)

Input documents contain up to hundred of nested documents. Caching settings are by default.

Memory dump:
![memory1](https://cloud.githubusercontent.com/assets/27484990/25040531/a17841ba-2112-11e7-98d3-b1060a68ad4a.JPG)
![memory2](https://cloud.githubusercontent.com/assets/27484990/25040536/a59bfbe2-2112-11e7-8e43-16212e0d7333.JPG)

**Comment by martijnvg** [comment]
@anatoly21 Just double checking: So after registering a single percolator query that has a `nested` query this memory issue happens? Also I assume that search requests (containing `percolate` queries) are being executed. Do you have a lot of these search requests or just a few?

**Comment by anatoly21** [comment]
Yes, this issue occurs after registerering a single nested query. The attached pictures show results after execution of about 300 000 search requests (percolate queries).

**Comment by martijnvg** [comment]
@anatoly21 Thanks, are the search requests (with `percolate` query) similar? If possible can you share the search request (or at least how this query is structured)? I like to figure out if the `percolate` query itself gets cached.

**Comment by anatoly21** [comment]
Mapping has a lot of keyword fields, therefore the attachment is a simplified version.

[env.zip](https://github.com/elastic/elasticsearch/files/922050/env.zip)

**Comment by martijnvg** [comment]
Thanks for reporting @anatoly21 and this is indeed a bad bug.

This problem is quite easily reproducible and affects all 5.x releases.
The cause of the memory issues / OOM is that the index reader for the memory index isn't closed,
which then causes the cache entries in `BitsetFilterCache` to never get cleaned up.

Prior to 5.0 the percolator had its own search context (PercolateContext), which always closed the readers of the in-memory index.

I'll work on a fix. The percolator should just never use the `BitsetFilterCache` and it doesn't need since it is querying an in-memory index.

**Comment by anatoly21** [comment]
Thank you.
