### ISSUE TITLE
Can Field Collapsing provides total number of distinct group

### ISSUE THREAD

**Issue by jayqie** [elastic/elasticsearch#24130]
**Describe the feature**:
In the elasticsearch document, I find "The total number of hits in the response indicates the number of matching documents without collapsing. The total number of distinct group is unknown."

Now I want to know the total number of distinct group, can you provide this kind of feature in the next release?

**Comment by jasontedor** [comment]
@jimczi Can you take a look?

**Comment by jimczi** [comment]
@jayqie the total number of distinct group is unknown simply because it would be too costly to compute. The `collapsing` is done on the `top_hits` only in order to provide a fast and accurate solution. Returning the accurate number of distinct groups would defeat the purpose as it would be slow and costly to compute. 
Though you can use the `cardinality` aggregation in the same query to get an approximate number of distinct group on the field (`collapsing` does not modify the aggregations):
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html
