### ISSUE TITLE
[feature request]smart client

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#24277]
**Describe the feature**:
hbase client will fetch metadata from zookeeper and then execute read/write operation based on metadata(routing table)
so if ES will implement this process:
1. each ping will get routing table based on client's config(whether enable fetch routing table or not) and server's config(allow client to fetch routing table or not)
2. if client can get routing table, then some operations, such is index/update a document and get doc by id, can visit data node directly.
3. if client can't get it, then act as before.

**Comment by javanna** [comment]
Hi @makeyang we moved away from the concept of a client that has knowledge of internals of the cluster, even in Java (that used to have the node client which sounds similar to what you describe). We are rather working on having the Java client go through REST like all of the other language clients, so that ideally the client shares a minimal part of the server code only, and doesn't use any internal mechanism that ended up being exposed to client users with the Java API. 

A smarter REST client could be implemented provided that the needed info is exposed via some API, but we don't plan on implementing anything like this for the time being.

**Comment by makeyang** [comment]
if it's for time being, why close it rather than put it high-hang fruit and at least open it for community to discuss and implemet it?

**Comment by javanna** [comment]
Because we are not interested in having such a client in our repo for the reasons mentioned above.
