### ISSUE TITLE
[feature request] add some doc/index size metrics

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#24279]
**Describe the feature**:
can we add max/min/ave doc size in index request?
can we add max/min/ave doc size in search response?

**Comment by markharwood** [comment]
Thanks for the suggestion.

>can we add max/min/ave doc size in search response?

This requirement makes sense to me (but see below for concerns/workarounds)

>can we add max/min/ave doc size in index request?

I'm not sure what the purpose is of providing this as part of an index request?  The client provides an average of what? 

As for providing max/min/ave lengths in the search response, many elasticsearch users have very large numbers of small, same-sized machine-generated documents. For them this length information would be uninteresting in search results and unnecessary overhead on storing each doc. For this reason it would have to be "opt-in" rather than a standard feature.

You can potentially "opt-in" by adding your own custom field to the JSON docs that includes a `length` integer and then use something like the [stats aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/5.3/search-aggregations-metrics-stats-aggregation.html) on this length field.
You could potentially use an [ingest pipeline](https://www.elastic.co/guide/en/elasticsearch/reference/master/pipeline.html) to derive this field in elasticsearch for you just prior to indexing.

**Comment by clintongormley** [comment]
You can use the [mapper-size plugin](https://www.elastic.co/guide/en/elasticsearch/plugins/current/mapper-size.html) for this
