### ISSUE TITLE
Small inconsistency in stats aggregation rest output vs. java api

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#24287]
While working on adding parsing for the `stats` aggregation I noticed a small difference between the output of the formatted 
`count` value in the Java API vs. the rest output. The xContent output of `InternalStats` writes formatted "as_string"-fields for 
all calculated statistics (min/max/avg/sum) except for the count. Using the Java API and `getCountAsString()` (which is also
part of the `Stats` interface) however, it is possible to retrieve a formatted value that uses the configured formatter 
(e.g. a decimal or date formatter).

It would be good to either make this consitent by either adding the `count_as_string` output to rest or change `getCountAsString()` so it 
doesn't use the formatter and instead only returns the long as a string. Another option, at least for the parsing in #24239, would be to
remove `getCountAsString()` from the `Stats` interface.

Relates to #24239

**Comment by cbuescher** [comment]
@colings86 do you think we can add this field in v6.0.0 or do you think this needs fixing at all? We can also ignore it as an edge case but if possible I'd like to fix it.

**Comment by colings86** [comment]
I don't think we should add a `count_as_string` field here as I don't think it would make sense since trying to format a count of e.g. `3` as a date etc. does not produce a meaningful result.

IMO we should remove the `getCountAsString()` field form the java class in 6.0.0 and deprecate it in favour of `String.valueOf(getCount)` in 5.x
