### ISSUE TITLE
Primary shards shouldn't be stuck in excluded allocation nodes during rolling patch upgrade

### ISSUE THREAD

**Issue by f-w** [elastic/elasticsearch#24339]
I have ES (based on official docker image) running in OpenShift/Kubernetes that supports rolling deployement. During a deployment which also upgrades ES from 2.4.3 to 2.4.4, if I cancel in the middle and try to roll back gracefully by putting the new version nodes onto excluded shard allocation filter, I found to my surprise all primary shards are stuck in the new nodes, not honoring the filter. The cause is found to be node version difference using `_cluster/reroute` api.

I understand data schema/structure depends on version. But according to semver, a patch difference should be backwards-compatible and contains only bug fixes. It's a common practice that incompatible data schema change calls for a major version bump up so I don't expect to see this happening, especial during a production deployment.

At a minimum this behavior should be documented on page [Shard Allocation Filtering](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/allocation-filtering.html).

**Comment by jasontedor** [comment]
> But according to semver, a patch difference should be backwards-compatible and contains only bug fixes.

Semver is about APIs, and while we maintain these at the REST level across patch releases, we do not purport to follow semver.

After a primary is allocated to a node with version X, it and its replicas can not be allocated to a node with version Y < X because new segments could have been written that are not compatible with the version of Lucene backing version Y (we pick up Lucene bug fixes in patch releases).

> At a minimum this behavior should be documented.

We discuss this in the section on [rolling upgrades](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/rolling-upgrades.html#_step_6_wait_for_the_node_to_recover).

>
