### ISSUE TITLE
Bootstrap mlockall check checks root not elasticsearch user.

### ISSUE THREAD

**Issue by russmac** [elastic/elasticsearch#24380]
**Elasticsearch version**: 5.3.2

**Plugins installed**: [ec2-discovery]

**JVM version**: openjdk-8-jre-headless:amd64   8u121-b13-1~bpo8+1 

**OS version**: Debian 8.7

**Description of the problem including expected versus actual behavior**:
Bootstrap mlock check checks root user. `su -c 'ulimit -a' elasticsearch -s /bin/bash` shows elasticsearch as unlimited memory locking. However root is limited. This means root must be unlimited (or increased limit) for Elasticsearch to pass bootstrap checks.

**Steps to reproduce**:
 1. Set elasticsearch user unlimited in /etc/security/limits.conf
```
#/etc/security/limits.conf
elasticsearch soft memlock unlimited
elasticsearch hard memlock unlimited
```
 2. Start SysVinit elasticsearch script installed by Elasticsearch debian package.
 3. Check logs to see memory locking bootstrap check failed. Advising to apply the currently applied ulimits to elasticsearch user.
```
[2017-04-28T01:13:17,948][WARN ][o.e.b.JNANatives         ] Unable to lock JVM Memory: error=12, reason=Cannot allocate memory
[2017-04-28T01:13:17,950][WARN ][o.e.b.JNANatives         ] This can result in part of the JVM being swapped out.
[2017-04-28T01:13:17,950][WARN ][o.e.b.JNANatives         ] Increase RLIMIT_MEMLOCK, soft limit: 65536, hard limit: 65536
[2017-04-28T01:13:17,951][WARN ][o.e.b.JNANatives         ] These can be adjusted by modifying /etc/security/limits.conf, for example: 
	# allow user 'elasticsearch' mlockall
	elasticsearch soft memlock unlimited
	elasticsearch hard memlock unlimited
```

SysVinit script contains ES user vars correctly and the first process is run as elasticsearch.
```
# Run Elasticsearch as this user ID and group ID
ES_USER=elasticsearch
ES_GROUP=elasticsearch
```
Unlimiting root memory locking in /etc/security/limits.conf resolves the issue.

**Comment by jasontedor** [comment]
This is not correct, we [invoke](https://github.com/elastic/elasticsearch/blob/v5.3.2/core/src/main/java/org/elasticsearch/bootstrap/JNANatives.java) [`getrlimit(2)`](http://man7.org/linux/man-pages/man2/setrlimit.2.html) with `RLIMIT_MEMLOCK` as the resource for the currently executing proces). You can compare the same if you cat `/proc/<pid>/limits` for the running Elasticsearch process (start it without binding transport so that the bootstrap checks aren't enforced, and then do this and you'll see `/proc/<pid>/limits` shows the same). What I think you're seeing is that you did not start a new shell that did not derive from your currently existing shell after increasing the limit to unlimited. Resource limits are preserved across [`fork(2)`](http://man7.org/linux/man-pages/man2/fork.2.html), so if you do not, for example, log out and log back in, you'll be stuck with the old limits.

**Comment by russmac** [comment]
>> What I think you're seeing is that you did not start a new shell that did not derive from your currently existing shell after increasing the limit to unlimited.

I rebooted so the limit worked, and checked it with ulimit -a.

**Comment by jasontedor** [comment]
I also notice also that you're on Debian 8 which is `systemd` based, not Sys V init based (the Sys V `/usr/sbin/service` script is just a compatibility layer that will redirect you to `systemd`). For `systemd` you need to create a file `/etc/systemd/system/elasticsearch.service.d/elasticsearch.conf` and add the following content:

```
[service]
LimitMEMLOCK=infinity
```

**Comment by russmac** [comment]
Thanks, I did mention I'm trying that in the previous post.

**Comment by jasontedor** [comment]
I'm sorry, but you did not say that in any of your previous posts. I see you referring to Sys V init, never `systemd`. You're on a `systemd`-based system (Debian 8), you need to add the unit file that I mentioned.

**Comment by russmac** [comment]
"I looked further into the doc and it seems I can configure the limit in a systemd service config file so I'm trying that as an alternative."

**Comment by jasontedor** [comment]
You edited your post.

**Comment by russmac** [comment]
No. I'm not quite sure what to say here, I posted that information well before your response, Thank you for your time.
