### ISSUE TITLE
Add option for boolean 'AND' logic to Context Suggester

### ISSUE THREAD

**Issue by n0othing** [elastic/elasticsearch#24421]
There are some scenarios where a user might like to filter suggestions via several contexts. However, today the context suggester uses `OR` logic when specifying multiple contexts. For example, a search for:

```
GET myindex/mytype/_search
{
  "suggest": {
    "my_suggestion": {
      "prefix": "sta",
      "completion": {
        "field": "suggest",
        "contexts": {
          "context1": [
            "A"
          ],
          "context2": [
            "11"
          ]
        }
      }
    }
  }
}
```

Will return suggestions that have a context of `"context1" : "A"` OR `"context2" : "11"`. This poses a problem if you'd like to return suggestions to the user for a specific combination of contexts.

As a workaround today, you can concatenate the contexts to simulate the logic:

```
"contexts": {
      "context1_and_2": [
        "A:11"
      ]
    }
```

**Comment by devikiranr** [comment]
@n0othing  
Great to see that we were not the only ones requiring this feature ..!!! We feel most of the use cases dealing with filters are `AND` in nature. 
We have done fair bit of work on this and have solved it already even for the nested Model where the said workaround would not work .
[Feature request](https://github.com/elastic/elasticsearch/issues/23476)
[Pull request](https://github.com/elastic/elasticsearch/pull/23232)

**Comment by nilabhsagar** [comment]
Great this is what we have given in this [Pull Request](https://github.com/elastic/elasticsearch/pull/23232). as well as in this [Feature request](https://github.com/elastic/elasticsearch/issues/23476), but both were closed. we were hoping to have it discussed as it supports Nested docs too. If required we can break-up the changes and make separate pull request. Please provide your opinion.

**Comment by clintongormley** [comment]
See https://github.com/elastic/elasticsearch/pull/24565 - WIP

**Comment by andyb-elastic** [comment]
@elastic/es-search-aggs

**Comment by jimczi** [comment]
When multiple contexts are provided at indexing time, we build one suggestion per context value and index them separately. This is done so that we don't need to perform all the combinations (contextA + contextB and contextA + contextC, ....) and avoid the combinatorial explosion. Since all contexts are indexed individually it is difficult to add a boolean logic to match this context especially considering that we match each suggestion in the order of their weights. Matching with a `must` can degrade the performance considerably so I am going to close this issue, speeds really matter here and the suggester cannot be as flexible as a real index. When more flexibility is needed on the query side it is preferable to use a normal field and to apply edge ngram on it so that a prefix query can be mixed with another filter targeting a different field.
