### ISSUE TITLE
ProcessProbe.java is not using the JVM implementation independant API

### ISSUE THREAD

**Issue by klangman** [elastic/elasticsearch#24446]
The current implementation of ProcessProbe.getMethod() and ProcessProbe.getUnixMethod() are using hard coded reference to com.sun.management.* classes which makes the code specific to the Oracle JVM. A JVM independent method for accessing the OperatingSystemMXBean is used in the following code:

        /**
         * Returns a given method of the OperatingSystemMXBean,
         * or null if the method is not found or unavailable.
         */
        private static Method getMethod(String methodName) {
            try {
                return osMxBean.getClass().getMethod(methodName);
            } catch (Exception t) {
                // not available
                return null;
            }
        }

        /**
         * Returns a given method of the UnixOperatingSystemMXBean,
         * or null if the method is not found or unavailable.
         */
        private static Method getUnixMethod(String methodName) {
            try {
                return osMxBean.getClass().getMethod(methodName);
            } catch (Exception t) {
                // not available
                return null;
            }
        }

Using the above code should work on all JVM implementations.

**Comment by jasontedor** [comment]
This will not work, this will lead to `IllegalAccessException` when you try to invoke the method on the operating system management bean (we do not and will not grant the runtime permission `suppressAccessChecks` so that set accessible can utilized to work around this). That is why these methods are reflectively loaded this way, they are methods on Sun interfaces only (`com.sun.management.UnixOperatingSystemMXBean` and `com.sun.management.OperatingSystemMXBean`).

> Using the above code should work on all JVM implementations.

As an important point of clarification, we only support certain OpenJDK distributions (as packaged by OS distributions such as Fedora, Red Hat, CentOS, etc. for x64) and Oracle distributions for Linux x64, macOS, and certain Windows OS).
