### ISSUE TITLE
Slow shard initialization time

### ISSUE THREAD

**Issue by deepakmehtaegnyte** [elastic/elasticsearch#24454]
We are facing the  slow shard initialization time. I went thru the post http://elasticsearch-users.115913.n3.nabble.com/Restarting-an-active-node-without-needing-to-recover-all-data-remotely-td4039346.html#a4039355

and it suggest Elasticsearch is going to do some improvement on slow restart process.

Since there was no ETA mentioned. I am creating ticket to know if any fix has been made? If yes then in which release.

Thanks

**Comment by spinscale** [comment]
This is a four year old post and since then a lot of things have changed (and are changing in the next major version) in this regard. I suggest you take a look at [synced flush](https://www.elastic.co/guide/en/elasticsearch/reference/5.3/indices-synced-flush.html).

Apart from that, we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) instead. Thank you!
