### ISSUE TITLE
Establishing relationships between plugins and their persistent data

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#24465]
As elasticsearch plugins become more sophisticated, they rely more and more on the data that they persist in elasticsearch. This persistent data can be found in three places: plugin-specific indices, index templates that control these indices, and custom cluster state metadata components. 

Currently, any plugin can freely create and modify any of these structures in the cluster and we cannot limit certain potentially dangerous operation (such as upgrade for example https://github.com/elastic/elasticsearch/pull/24379#issuecomment-298435283) to plugin's own data structures since no relationships between these structures and the plugin is maintained. 

One possible solution that was discussed before is to formalize and unify the interface through which a plugin registers and upgrades custom cluster state and templates. At the same time the plugin might register the mask for its indices or we can come up with some index naming convention that could use to identify that an index "belongs" to a certain plugin.

We would like to discuss this and other possible solutions for this problem.

**Comment by droberts195** [comment]
I think it would also be good to consider how such a framework could allow the yaml test framework to be made more robust.  At the moment plugins that rely on their index templates and/or custom cluster state to be set up before they run their yaml tests generally do this by creating a `@Before` method in a test class that extends `ESClientYamlSuiteTestCase`.  Different developers do the checks in different ways, so it gets messy, and we can also get problems like the one described in #25100.

If part of the registration process for custom cluster state and index templates was to specify the mechanism to wait for a remote cluster to have fully set these up then some of the classes that extend `ESClientYamlSuiteTestCase` could be removed.

It would also be good to allow plugins that register custom cluster state to register a mechanism for cleaning up that state between tests.  This would allow almost all plugin test classes that extend `ESClientYamlSuiteTestCase` to be removed.

**Comment by bleskes** [comment]
@imotov I think the idea is appealing and I can see a bit how we can add proper plugin API in the custom cluster state metadata. This is because we have some experience in that area. When it comes to indices I'm less sure of what would be a good plan. Can you may come up with some examples?

**Comment by imotov** [comment]
@bleskes we have applications/plugins that run as part of the elasticsearch cluster and generate potentially large amount of data. Examples of these apps are monitoring, ml, and watcher. This data falls into 2 categories: app configuration information (watches, for example) and reports of app execution (watch history). The current approach is to store this data in special indices. On one side this solution provides maximum flexibility - you have full power of elasticsearch to work with these indices. On the other side, this flexibility means that any user or plugin can modify these indices any way they want, we can have potential naming conflicts, users or other plugins may inadvertently make incompatible mapping or template changes.

**Comment by imotov** [comment]
We discussed it in FixItFriday and decided that it warrants a bigger separate discussion.

**Comment by williamrandolph** [comment]
I believe that the System Indices (#50251) effort handles plugin-specific indices and index templates, but do we have a plan for cluster state metadata components?

**Comment by williamrandolph** [comment]
We discussed this issue in today's core-infra meeting.

In the long run, we will benefit from having strong, isolated relationships between plugins and their persistent data. This will be particularly useful for allowing wide use of custom plugins in Cloud. We believe that we're making progress towards this state through several separately defined meta issues.

First of all, as mentioned above, the System Indices (#50251) project introduces a defined association between plugins and indices of several different sorts (associated, internally managed, and externally managed), and introduces APIs for resetting the plugin's system state. It does not introduce any specific notion of plugin-level resource ownership, and nothing prevents one plugin from modifying another plugin's data.

Second, we will be working on a plugin API that will decouple plugins from particular versions of Elasticsearch.

We think that when this work is done, we'll be better able to analyze and define two issues:

1. Plugin-level access control for system resources
2. Improvements needed for the Cluster State API that would support this work. We might want to look broadly at rewriting this API.

We would not want to start on either of those efforts while we're doing major work on system indices and the plugin API.

Since this ticket overlaps with existing work, we are going to close it, and we'll open more narrowly defined issues once we get to the early stages of designing them.
