### ISSUE TITLE
Not able to install elasticsearch in centos 7

### ISSUE THREAD

**Issue by sivaprakash16** [elastic/elasticsearch#24462]
**Elasticsearch version**:5.3 /5.3.2

**Plugins installed**: []

**JVM version**:1.8

**OS version**:centos

**Description of the problem including expected versus actual behavior**:

Error: Could not find or load main class org.elasticsearch.tools.JavaVersionChecker
Elasticsearch requires at least Java 8 but your Java version from /usr/java/jdk1.8.0_73/bin/java does not meet this requirement
**Steps to reproduce**:
 1. install elastic search
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by jasontedor** [comment]
Since it installs fine in our packaging tests, I'm assuming that this something about your environment. We reserved GitHub for verified bugs and feature requests only. Please open a topic on the [forum](https://discuss.elastic.co) and link to it from here and I will try to help you. If there is indeed a bug here, we can reopen this.

**Comment by spinscale** [comment]
Do you have a special/custom version of java? Maybe pasting the output of `/usr/java/jdk1.8.0_73/bin/java -version` sheds some light

**Comment by spinscale** [comment]
so, rereading this, my question does not stand. The problem is, that the version checker class cannot be loaded at all.

Can you be more verbose on how you installed Elasticsearch? RPM or tar.gz or zip? Where did you install it? Did you upgrade from an older version? Did you change any files inbetween upgrades?

how do you try to start Elasticsearch?

**Comment by spinscale** [comment]
forum post with similar issue (no feedback provided there though) https://discuss.elastic.co/t/error-could-not-find-or-load-main-class-org-elasticsearch-tools-javaversionchecker/82213

**Comment by sivaprakash16** [comment]
I Try to install zip (5.3.2) file in centos 7 machine:    
Virtualization: vmware
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-514.el7.x86_64
      Architecture: x86-64
I changed to  openjdk version "1.8.0_102"
OpenJDK Runtime Environment (build 1.8.0_102-b14)
OpenJDK 64-Bit Server VM (build 25.102-b14, mixed mode)

still i got this error: [siva@kfos-vmelk-1 bin]$ ./elasticsearch
Error: Could not find or load main class org.elasticsearch.tools.JavaVersionChecker
Elasticsearch requires at least Java 8 but your Java version from /bin/java does not meet this requirement

**Comment by sivaprakash16** [comment]
alternatives --config java

There are 3 programs which provide 'java'.

  Selection    Command
-----------------------------------------------
*  1           java-1.8.0-openjdk.x86_64 (/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.102-4.b14.el7.x86_64/jre/bin/java)
   2           java-1.7.0-openjdk.x86_64 (/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.111-2.6.7.8.el7.x86_64/jre/bin/java)
 + 3           /usr/java/jdk1.8.0_73/jre/bin/java

Enter to keep the current selection[+], or type selection number: 1

**Comment by jasontedor** [comment]
I replied to you this morning on the [forum thread](https://discuss.elastic.co/t/error-could-not-find-or-load-main-class-org-elasticsearch-tools-javaversionchecker/82213). Let us keep the discussion in one place and let us use the forum since I replied there and I do not think there is an Elasticsearch bug here but rather an environment issue that we will help you get to the bottom of.
