### ISSUE TITLE
Provide Maven artifacts for modules and plugins

### ISSUE THREAD

**Issue by joschi** [elastic/elasticsearch#24528]
**Describe the feature**:

Using the [Java Testing Framework](https://www.elastic.co/guide/en/elasticsearch/reference/current/testing-framework.html) is a great way to test client implementations such as [Jest](https://github.com/searchbox-io/Jest) against various scenarios involving one or more Elasticsearch nodes.

Unfortunately, it doesn't seem to support installing plugins on the Elasticsearch test instances out of the box except for [registering the plugin classes directly by overriding `ESIntegTestCase#nodePlugins()`](https://github.com/elastic/elasticsearch/blob/v5.4.0/test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java#L1723-L1728). In order to do this, the plugins need to be on the JVM class path at compile time, but since there are no official Maven artifacts for the various Elasticsearch modules and plugins, such as `lang-painless`, people need to resort to third party artifacts (such as [`org.codelibs.elasticsearch.module:lang-painless`](https://search.maven.org/#artifactdetails%7Corg.codelibs.elasticsearch.module%7Clang-painless%7C5.4.0%7Cjar)).

This is basically a follow-up for https://discuss.elastic.co/t/elasticsearch-java-testing-framework-and-plugins/84703.

**Comment by jasontedor** [comment]
This has been discussed previously, for example #18131.

`ESIntegTestCase` is useful for testing the internals of Elasticsearch but we think that client integration tests should not use it but rather spin up an actual node with any necessary plugins installed (relates #21544). We provide infrastructure for this, although it needs some polishing (relates #21119).

Since this has been discussed previously and I think we're going to come to the same conclusion, I'm going to close this issue.
