### ISSUE TITLE
Should we detect IPv4/IPv6 bind settings before starting the JVM?

### ISSUE THREAD

**Issue by seang-es** [elastic/elasticsearch#24591]
See https://github.com/elastic/elasticsearch/issues/16994

Should we enhance the startup script to be able to detect 'non_loopback:ipv4' or similar bind settings in elasticsearch.yml?  This would add complexity, but we are including settings that specifically refer to exclusive ipv4 binds without actually enforcing them at startup time.  This could either be a smarter startup script or a bootstrap check to ensure that the user is aware that they won't actually have a node binding to ipv4 only unless they explicitly set the -Djava.net.preferIPv4Stack=true setting in the JVM.

**Comment by jasontedor** [comment]
Sorry, what's the problem here? We do only bind to IPv4 addresses when the `:ipv4` restriction is applied.

**Comment by seang-es** [comment]
We had a complaint with netstat still showing the '::ffff:<ipv4_address>:9200' address.  If we're still binding to the IPv6 versions of the IPv4 address it may not comply with some environments.

**Comment by jasontedor** [comment]
That's an IPv4 mapped address using the IPv6 stack. The JVM will default to using the IPv6 stack with IPv4 mapped addresses unless explicitly told not to (via `-Djava.net.preferIPv4Stack`). Alternatively, this can be controlled at the OS level with (`net.ipv6.conf.all.disable_ipv6=1`, `net.ipv6.conf.default.disable_ipv6=1`, and `net.ipv6.conf.lo.disable_ipv6=1`). Since there's no harm in using the IPv6 stack with IPv4 mapped addresses, I see no reason to auto-disable Elasticsearch from using it, I think it should require explicit action on the part of the user. They can disable the IPv6 stack if this is a problem for them, or just `-Djava.net.preferIPv4Stack` to tell Java to only use the IPv4 stack.

**Comment by jasontedor** [comment]
Also, I think it would super-complicated to even come close to getting this right. For example, the user could request `-E http.host=_eno1:ipv4_` `E transport.host=_eno1_ipv6_` and many other permutations that greatly complicate this.
