### ISSUE TITLE
Aliases and index exclusion does not work as expected

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#24621]
**Steps to reproduce**

1. Create index `foo-1` with alias `read`
2. Create index `foo-2` with aliases `read` and `write`.
3. Index a doc in `foo-1`
4. Index a doc in `foo-2`
5. Search `/read,-foo-2/_search`

**Observations**

My expectation was to only see results from `foo-1`. However, the request fails with `IndexNotFoundException` for index `-foo-2`.

Note that trying `/read*,-foo-2/_search` works.

Also, trying `/read*,-write/_search` does not work (index `-write` doesn't exist), but `/read*,-write*/_search` works.

**Versions**

I've tested this on master (v6, commit 2486086980663bce5ff25f5ed7eb25d6a2cfc7c7).

**Comment by javanna** [comment]
The reason for this issue is #20898 . We only interpret '-' as a negation when it is preceded by a wildcard expression. The fact that an alias was used is irrelevant, `/foo-1,-foo-2/_search` gives the same result as `/read,-foo-2/_search`. I would lean towards leaving everything as-is given that #20898 was a great improvement and I wouldn't want to go back. @dakrone what do you think?

**Comment by dakrone** [comment]
I agree with @javanna, the reason why we only interpret `-` as a negation when preceded by a wildcard expression is that prior to #20033 we allowed indices to be created that started with `-`, so we need a way to be able to select those indices for a query.

**Comment by javanna** [comment]
@dimitris-athanasiou would you be ok with closing this given the above explanation?

**Comment by dimitris-athanasiou** [comment]
@javanna I see. Not ideal but it looks like the lesser evil. Closing this issue.
