### ISSUE TITLE
5.4+ Add note in docs for users to prefer `word_delimiter_graph` over `word_delimiter`

### ISSUE THREAD

**Issue by vsiv** [elastic/elasticsearch#24665]
`WordDelimiterFilter` is deprecated in Lucene 6.5. Users should prefer `WordDelimiterGraphFilter` instead as it will function correctly for phrase queries when used as a search analyzer. This was added in v5.4 and hence only applies to versions 5.4+.

It might help and assist users reading the docs if this is noted.

links-
* https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-synonym-tokenfilter.html
* https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-synonym-graph-tokenfilter.html
* http://lucene.apache.org/core/6_5_1/analyzers-common/org/apache/lucene/analysis/miscellaneous/WordDelimiterFilter.html

**Comment by javanna** [comment]
@jimczi could you have a look please?

**Comment by j-haj** [comment]
@lcawl @vsiv can I get some more context on this? Both of the referenced pages seem to be discussing configuration files with no mention to a Java API.

**Comment by lcawl** [comment]
Looks to me like the most important link is this one: http://lucene.apache.org/core/6_5_1/analyzers-common/org/apache/lucene/analysis/miscellaneous/WordDelimiterFilter.html

**Comment by j-haj** [comment]
@lcawl Thanks for the follow-up! I understand what has been deprecated, my question is more around the docs themselves. There is no reference to a Java API in either of the `analysis-synonym-tokenfilter` or `analysis-synonym-graph-tokenfilter` so I am having a hard time understanding why we are putting this notice to users on these pages. Regardless, I will prepare a PR with a notice regarding the deprecation.

Also, I noticed that both `elasticsearch/analysis/common/WordDelimiterTokenFilterFactory.java` and `elasticsearch/analysis/common/CommonAnalysisPlugin.java` use `WordDelimiterFilter` rather than `WordDelimiterGraphFilter`. Should I open a separate issue to change these usages to `WordDelimiterGraphFilter`?

**Comment by lcawl** [comment]
@j-haj If you haven't already started the documentation PR, I can do it. 

With respect to your second comment, it looks like there's already an issue here: https://github.com/elastic/elasticsearch/issues/29061

**Comment by jrodewig** [comment]
[docs issue triage]

Leaving open as this is still relevant.

Links:

- https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-word-delimiter-tokenfilter.html
- https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-word-delimiter-graph-tokenfilter.html

**Comment by debadair** [comment]
Closing this, as @lcawl's  change adds the notice that word-delimiter-tokenfilter is deprecated in Lucene.
