### ISSUE TITLE
Rename "Ingest Node" to align with its provided functionality and with Beats and Logstash

### ISSUE THREAD

**Issue by jordansissel** [elastic/elasticsearch#24686]
Background:

Logstash calls a `filter` what Beats and Ingest Node call a `processor`. We (the cross-team ingest group) met last week to discuss improvements to naming, and filter-vs-processor came up. Our decision during this meeting was to rename things which modify data in-flight to be called, "Processors". 

The net impact of this is Logstash will rename filter to be called, "processor".  

This also should mean Ingest Node renames to be called, "Processor Node"

**Comment by clintongormley** [comment]
I don't agree with this at all.  Ingest is just one of many aspects to Elasticsearch.  Renaming this aspect to "processor node" would be entirely confusing as processor is way too generic.  Could easily be confused with analysis, percolation, machine learning, and many other things.

**Comment by jordansissel** [comment]
@clintongormley I agree, though "ingest" is not what this feature does. The ingest feature already exists: index api. This feature is not ingestion (eating), it is processing (digestion, perhaps, for the food metaphor).

I know it's confusing. Ingest is a confusing name, and with Logstash renaming its processing capabilities to be called "processor", ingest node should align as well, even if that means renaming.

I am open to other names.

**Comment by clintongormley** [comment]
The one thing I've never heard from any user (yourself excepted) is how this is confusing.  I see no reason to break all of our ingest APIs for something which does not seem to be a problem in the slightest.

**Comment by jordansissel** [comment]
@clintongormley ok, I think I understand your concerns.

If naming consistency isn't important, then we should cancel any future consistency discussion in the ingest group. I'll update the agenda. We can revisit renaming Logstash filters as well.

**Comment by ruflin** [comment]
I think this can be looked at from 2 sides. Looking at it from the Elasticsearch side for example from  a data node perpsective, the ingest node is definitively ingesting data. Looking at it from Beats / Logstash, we send that to a "processing" node to do the processing.

The part where it's getting confusing to me is when we talk about the "ingesting data" part of our Elastic Stack and actually mean Beats and Logstash because these are actually doing the ingest part (which I think is correct). Also in the docs of the ingest node we correctly state that ingest is not actually ingesting data itself: "You can use ingest node to pre-process documents before the actual indexing takes place." We only talk about processing.

I'm on the same page with @jordansissel here that I think when looking at the Elastic Stack "Ingest Node" is definitively not an optimal name. From just an elasticsearch perspective it makes more sense. I don't think we should make a change here in the short term as it would break lots of things but it's definitively something we should keep in mind when talking about the long term vision of the "ingest parts".

**Comment by dadoonet** [comment]
Was funny that this question came yesterday at a training we gave with @zumo64. People were confused by "ingest". They thought it was the node which is receiving all index requests. Other nodes can't receive index operations. That's what they thought by hearing that term.

It cames out that the right terminology should be something like `enrichment node` instead of `ingest node`.

But I agree that Ingest node is now widely use and renaming is something hard IMO. I'm not sure it's worth it.
