### ISSUE TITLE
Misleading behavior with invalid Content-Length header

### ISSUE THREAD

**Issue by jsmucr** [elastic/elasticsearch#24729]
**Elasticsearch version**: 5.4.0

**Plugins installed**: Netty4Plugin, GroovyPlugin

**JVM version**: 1.8.0_45

**OS version**: Windows 8.1

**Description of the problem including expected versus actual behavior**:
If you accidentally replace `Content-Type: application/json` with `Content-Length: application/json` (may happen with some REST clients easily) in the `search` query, ES behaves as if you queried for all the data, not just the subset.

* Expected behavior: ES returns `400 Bad Request`
* Actual behavior: ES returns the full result set (`match_all` query).

**Steps to reproduce**:
Send `Content-Length: application/json` header instead of `Content-Type: application/json` querying a specific subset of data. For example:

    POST http://localhost:9200/messages/artifact/_search
    Content-Length: application/json

    {
        "query": {
            "term": {
                "type": "vda"
            }
        }
    }

**Comment by nik9000** [comment]
This seems bad. I mean, easy to work around and all, but I don't like when we ignore silly stuff like this and don't throw errors. Though I'd have to read the spec to make sure that behavior isn't mandated....

**Comment by jasontedor** [comment]
The spec mandates the `Content-Length` header should be digits, Netty is lenient here. I'll take it upstream.

**Comment by nik9000** [comment]
> I'll take it upstream.

❤️

**Comment by jasontedor** [comment]
I'm providing an update here that the Netty maintainers have agreed to remove the leniency that was introduced in netty/netty#5861 that is leading to the problem here. I will open a PR against Netty to do this soon, probably in the middle of next week. The change requires three things:
 - revert the change that introduced the leniency
 - correct the Javadocs for the content length method to indicate that the method is not lenient
 - a small change will be needed in io.netty.handler.codec.http.HttpObjectAggregator to handle the possibility of getting the content length throwing a number format exception

I have a patch against Netty that does these things and have tested it against Elasticsearch which now does the correct thing when receiving a request like reported here.

Thank you for the report @jsmucr.

**Comment by jasontedor** [comment]
I opened netty/netty/#6866.

**Comment by jasontedor** [comment]
The upstream fix netty/netty#6866 has been merged and now we await the release of Netty 4.1.13.Final.
