### ISSUE TITLE
failed to recover from translog

### ISSUE THREAD

**Issue by EngineersRock** [elastic/elasticsearch#24755]
**Elasticsearch version**:
5.2.2
**Plugins installed**: [x-pack, cabana 5.2.2, timelion]

**JVM version** (`java -version`):
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
macOS Sierra 10.12.3

Darwin ws-reporting.apple.com 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:
The machine rebooted without warning while ElasticSearch and Kibana were running. It appears as though the trans logs for one of the indices is corrupted. I have identified a trans log file in every shard that is 30+MB as opposed to the normal 43 bytes.
**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. probably power off computer while elastic is writing to trans log.
[logs.zip](https://github.com/elastic/elasticsearch/files/1009144/logs.zip)

**Provide logs (if relevant)**:
attached elastic logs and relevant trans logs.

**Comment by clintongormley** [comment]
What filesystem are you using for your `data/` dir?

**Comment by s1monw** [comment]
I think this is still related to java issues on mac OS related to fsync... [here](http://mail.openjdk.java.net/pipermail/nio-dev/2015-May/003156.html) is an example where this was raised on the mailing list and it should be fixed in JDK9 if I read [this](https://bugs.openjdk.java.net/browse/JDK-8084262) correctly

**Comment by bleskes** [comment]
I looked at the logs and agree with Simon that this is consistent with the translog file not being fsynced correctly and as a result it was trimmed due to the unexpected shutdown. I also read the JDK9 fix in the same way.

Since this is the only copy of the data, the only way to recover is to use the [translog trimming tool](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-translog.html#corrupt-translog-truncation) to be able to recover the data from the lucene index and accept that the data in the translog is lost.

Sadly, I think we should close the issue as there is nothing much we can do on our end. @s1monw do you agree?

**Comment by s1monw** [comment]
I agree @bleskes
