### ISSUE TITLE
Wrapping collect(doc) with System.nanoTime() calls is a poor choice

### ISSUE THREAD

**Issue by sabi0** [elastic/elasticsearch#24799]
`org.elasticsearch.search.profile.ProfileCollector` uses this approach to measure time spent:
```
            public void collect(int doc) throws IOException {
                final long start = System.nanoTime();
                try {
                    super.collect(doc);
                } finally {
                    time += Math.max(1, System.nanoTime() - start);
                }
            }
```

`nanoTime()` however is rather slow itself (in the range of 30-40 ns). And can even have microseconds granularity on some platforms.

See this, for example:
http://stas-blogspot.blogspot.nl/2012/02/what-is-behind-systemnanotime.html
https://shipilev.net/blog/2014/nanotrusting-nanotime/

So for high-rate calls like `collect(doc)` you'd get something like this:
![image](https://cloud.githubusercontent.com/assets/11509875/26252004/5ad2efa4-3caf-11e7-803c-b83a5bfb4ef2.png)

Instead you should probably measure time for every 1000 `collect()` calls.
Or use stack trace sampling like [commercial profilers do](http://stackoverflow.com/a/2482313/306345). (which is probably an overkill in this case)

**Comment by jonathanihm** [comment]
Could this possibly be a low-hanging fruit issue which I could handle as a new contributor?

**Comment by danielmitterdorfer** [comment]
Thanks for the ticket @sabi0! I can confirm that the behavior that you describe is indeed a problem. The microbenchmarking framework JMH uses a similar approach (take start timestamp, run benchmark for a while and then take the end timestamp) for that reason (and has a fat warning for the benchmark mode `SingleShotTime`). 

Hence I also think that we need to reduce the sampling granularity for such short-running calls. However, I do not know the design of the query profiler well enough to give a definitive answer on how easy that is (maybe @polyfractal knows better?). 

While a sampling approach makes sense to me, taking stack traces does not. One of them is about granularity (tracing vs. sampling) and the other one is what information is captured. Stack traces would not help us much here because we don't want a Java execution profile but a more application specific one.

**Comment by jpountz** [comment]
I like the idea of reducing the sampling granularity, I don't think that would be too hard to change. Maybe we should use an interval that grows linearly (something like `min(1000, i++/1024)`) in order to still have a meaningful profile with queries that match few documents. We'd probably also want to do it in the `ProfileScorer` class since most its methods are also cheap and called in a tight loop.

**Comment by polyfractal** [comment]
Whoops, just saw this (been fiddling with email filters lately and apparently broke everything).

I don't think this will be very difficult to add... we are already maintaining a count of method invocations, so implementing sampling should be relatively trivial.  Just need some logic at the end to extrapolate based on the sampled data.

I agree with @jpountz point, it would be nice if this could grow in some fashion so that small matching sets.  It's not uncommon to have slow queries (scripts, etc) that only match a few documents
