### ISSUE TITLE
filesystems stats (_nodes/stats/fs) stats are missing for a client, non-master, non-data node

### ISSUE THREAD

**Issue by khachik** [elastic/elasticsearch#24804]
## Environment
**Elasticsearch Version:** `2.3.3` **seems to apply to the master branch code as well**
**Plugins Installed:** n/a
**JVM Version:** `1.8.0_66`
**OS Version:** `Linux HOSTNAME_REMOVED 2.6.32-431.1.2.0.1.el6.x86_64 #1 SMP Fri Dec 13 13:06:13 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux`

## Description of the problem

The following API returns empty fs stats for a node that is configured as:
- non-master
- non-data
- client

```
    curl -XGET 'http://localhost:9200/_nodes/NODE_ID/stats/fs?pretty
    # response
      ...
      "fs" : {
        "timestamp" : 1495216530699,
        "total" : { },
        "data" : [ ]
      }
      ...
```

### Some hints on why this is happening

`org.elasticsearch.env.NodeEnvironment` is not creating the lock file (usually located at `{data}/{cluster-name}/nodes/0/node.lock`) and its parent directories for a (client, non-master, non-data) node:
```
       // the call below is checking
       // return !(settings.getAsBoolean("node.client", false) 
       //              || (!settings.getAsBoolean("node.data", true) 
       //              && !settings.getAsBoolean("node.master", true)));
       if (!DiscoveryNode.nodeRequiresLocalStorage(settings)) {
            nodePaths = null;
            sharedDataPath = null;
            locks = null;
            localNodeId = -1;
            return;
        }
```

and `org.elasticsearch.monitor.fs.FsProbe` is not collecting fs stats if the local variables for the lock file and `nodes` dir are null (which is the case as per the code snippet above):
```
    public FsInfo stats() throws IOException {
        // the check below is doing
        // return nodePaths != null && locks != null;
        if (!nodeEnv.hasNodeFile()) {
            return new FsInfo(System.currentTimeMillis(), new FsInfo.Path[0]);
        }
        ...
    }
```

**Comment by bleskes** [comment]
@khachik thx. This stems from the old habit of advertising the node client as the "easiest" way to connect to the cluster. Under the hood that node client was node really a client but rather a full blown node that had it's master and data setting set to false (with a syntactic sugar of `node.client: true`). Since it's a client embedded in other processes you don't want it to write stuff to disk and that's why the node env. logic disabled writing/reading. A side effect was that it indeed doesn't have fs stats (because it doesn't have a "file system"). As you can see this is all confusing and also a full node is not really the best way to connect to the cluster. This is why we moved to using the term coordinating node and removed the `node.client` setting.

master/5.x have different logic which is way simpler to read and they don't have this behavior. 

I'm going to close this issue. If you do have problems with 5.x/master please reopen.
