### ISSUE TITLE
Date range query does not work for lte comparision with format "yyyy-MM"

### ISSUE THREAD

**Issue by yagotome** [elastic/elasticsearch#24874]
**Elasticsearch version**: 5.1

**Plugins installed**: none

**JVM version** (`java -version`): 1.8.0_131

**OS version** (`uname -a` if on a Unix-like system): Windows 10 Pro

**Description of the problem including expected versus actual behavior**:

When I try to query an index using *Range Query* for dates using `lte` field and `format` field equals to `yyyy-MM`, I expect to have documents whose date field used in *Range Query* has year and month equals to my searched date's ones.

**Steps to reproduce**:

1. Create an index with a date field as the following mapping:
```
{
    "mappings": {
        "foo": {
            "properties": {
                "foobar": {
                    "type": "integer"
                },
                "created": {
                    "type": "date",
                    "format": "yyyy-MM-dd HH:mm:ss"
                }
            }
        }
    }
}
```
2. Insert a document:
```
{
	"foobar": 1,
	"created": "2017-05-24 19:46:13"
}
```
3. Query documents created this month or before:
```
{
    "query": {
    	"range": {
	      "created": {
	        "lte": "2017-05",
	        "format": "yyyy-MM"
	      }
	    }
    }
}
```
The query above should return the document created in step 2 because they have same years and months. However, it won't match this query.

It looks like days are being considered in that query even though I didn't pass days in `format` field,  because that query with `gte` instead works.

**Provide logs (if relevant)**: none

**Comment by abeyad** [comment]
This does work as expected.  2017-05 is interpreted as the beginning of May 2017, so 2017-05-24 doesn't match.  If you supply `lte: 2017-06`, the result is returned

**Comment by yagotome** [comment]
@abeyad This behavior is not specified in the [Range Query documentation](https://www.elastic.co/guide/en/elasticsearch/reference/5.1/query-dsl-range-query.html) . Anyway, I suppose if it is allowed to pass `format` as `yyyy-MM`, it should only consider `yyyy-MM` so that `2017-05` and `2017-05-24` match either using `lte` or `gte`. Otherwise, it shouldn't allow this kind of format.

**Comment by abeyad** [comment]
That's not the way it should work.  These are date fields.  Date fields imply an increasing range of values, similar to a long or a double.  If you had a long value in your field `789` and you specified `lte: 78` would you expect it to match?  You would not, because 78 is less than 789.  We are not matching prefixes.  

I think your confusion is arising from the fact that you are viewing date fields as string fields with a prefix, but that is not how date fields work.  With dates, just like any other ranged set of values, a prefix match does not make sense when using less than and greater than matches.

**Comment by clintongormley** [comment]
There is some confusion here about rounding.   As @abeyad says, a date like `2017-05` is converted to the datetime `2017-05-01T00:00:00`.  However, the following query will do what you want:

```
{
    "query": {
    	"range": {
	      "created": {
	        "lte": "2017-05||/M",
	        "format": "yyyy-MM"
	      }
	    }
    }
}
```

The reason is that, with `lte` and date rounding (the `||/M`), we round up to the next value - 1 millisecond.

**Comment by yagotome** [comment]
I got it! That's what I was looking for, @clintongormley . Thank you!

**Comment by saurabh35** [comment]
Could someone please tell me where to read, how `||/M` or anything like `some-date||something` work in elasticsearch's context?
