### ISSUE TITLE
Add MUST_NOT(Negation) filter option in completion(context) suggester

### ISSUE THREAD

**Issue by surwasevb** [elastic/elasticsearch#24917]
Currently context suggester provides filter using category and geo. It also supports AND and OR operation among contexts. But i havent found any feature that support negation(MUST_NOT) kind of filter in context.

**Elasticsearch version**:
2.4.5

**Comment by jpountz** [comment]
@jimczi What do you think?

**Comment by jimczi** [comment]
I think it's a good idea though `AND` is not implemented in suggest v2 yet. There is an old PR that is on my TODO for some time now:
https://github.com/elastic/elasticsearch/pull/24565
I am currently working on a rebase version of it and I should be able to open a new PR in a couple of days. `MUST_NOT` support should be easy to add if we support `AND` and `OR` so I can do that in a follow up or add it in the current PR. I'll see how much code change is needed.

**Comment by jimczi** [comment]
I thought at first that it would be easy to add this feature to the existing PR: https://github.com/elastic/elasticsearch/pull/24565 but realized afterward that it's not possible. The details can be found in https://github.com/elastic/elasticsearch/pull/26407.
I am closing this issue because this feature would require a complete redesign of the suggest in es (and lucene). Currently contexts are matched independently and there is no way to ensure that we can match all contexts in a single document. This makes context filtering impossible to implement at query time with the expected precision and speed.
