### ISSUE TITLE
Consider additional java classes for whitelisting

### ISSUE THREAD

**Issue by geekpete** [elastic/elasticsearch#24946]
Consider the following classes for whitelisting:

- org.elasticsearch.common.unit.DistanceUnit
- org.elasticsearch.common.geo.GeoUtils
- org.elasticsearch.common.geo.GeoDistance

For the purposes of performing unit conversions when doing arc distance calculations.
Alternatively provide functions in Painless that wrap necessary classes to perform the same unit conversions and calculations.

These examples (though these are groovy examples rather than painless ones, the use case is still valid). These examples require whitelisting of the classes involved.

## Using DistanceUnit and GeoUtils classes:
```
GET /test/type/_search
{
    "script_fields" : {
        "test1" : {
            "script" : {
                "lang": "groovy",
                "inline": "org.elasticsearch.common.unit.DistanceUnit.MILES.fromMeters(org.elasticsearch.common.geo.GeoUtils.arcDistance(0.0, 0.0, 1.0, 1.0))"
            }
        }
    }
}
```

## alternatively using GeoDistance and DistanceUnit classes:

```
_source['NETWORK_LOCATION'].collectEntries { it -> if (it != null && it.COORDINATES != null){ [(it.PCO_NET_LOC_CYCLE_CK.toString()) : org.elasticsearch.common.geo.GeoDistance.ARC.calculate(it.COORDINATES.lat, it.COORDINATES.lon, lat, lon, org.elasticsearch.common.unit.DistanceUnit.MILES)]} else{[('-1'):'-1']}} 
```

**Comment by geekpete** [comment]
Possibly related: https://github.com/elastic/elasticsearch/issues/17506

**Comment by jdconrad** [comment]
Adding discuss to talk about which contexts make sense to have these new APIs.  Really falls under context/whitelist clean up.

**Comment by jdconrad** [comment]
Given the speed at which the contexts are being developed it probably makes sense to add these to the default whitelist for now and move them to the appropriate contexts when they're ready.

**Comment by rjernst** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.

**Comment by cryptic-mystic** [comment]
Oh joy, so all the numerous GH issues that would be resolved by this are now left hanging. Fantastic. For everyone like me struggling with this, welcome to a dead end!

Do you know how many Elastic help articles and Stack Overflow's there are related to "computing closest distance for an array of geo_points"?

Looks like I'm writing my own `arcDistance` calculations today. Thanks guys.

**Comment by craigtaverner** [comment]
@cryptic-mystic It might help to know that the ES|QL language added support for the `ST_DISTANCE` function last year. See the blog at https://www.elastic.co/search-labs/blog/esql-geospatial-distance-search for more information about this feature.

The original issue here talks about doing unit conversions. That should be trivial in ES|QL, because it already has a bunch of [generic maths functions](https://www.elastic.co/docs/reference/query-languages/esql/functions-operators/math-functions), and as such this might already be what you need. It would be great if you gave ES|QL a try and if it does not do everything you need, open a new issue asking for the missing feature in ES|QL, instead of painless.

However, If the requirement is to find the shortest distance between one point and a collection of points, the only way this currently works in ES|QL is if the collection is actually a multi-value field of type geo_point or point. Currently, if the user specifies a literal multi-value using `ROW points=[…]` syntax, this is converted to a `GeometryCollection`, and we do not yet allow distance to that. So, while `ST_DISTANCE` works in ES|QL it is mostly for point-point calculations with the single exception of supporting multivalued points from the index. It would be relatively easy to expand this to support geometry collections (literal or geo_shape) as long as they are only points. Supporting distance to arbitrary shapes is a lot more work. The blog itself does not touch on these subtleties at all, other than one mention of not supporting distance calculation to `geo_shape`.
