### ISSUE TITLE
  Time parsing exception 

### ISSUE THREAD

**Issue by Alfred1992** [elastic/elasticsearch#24998]
**Elasticsearch version **: 5.4.0

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_91

**OS version** (`uname -a` if on a Unix-like system): Windows 10

**Description of the problem including expected versus actual behavior**:
  Time parsing exception if the time string has equal or more than 10 decimal digits,
  for example: "2017-05-24T17:56:28.0123456789+02:00"

**Steps to reproduce**:
Just execute this request: 

PUT /test/event/1?pretty
{
  "time": "2017-05-24T17:56:28.0123456789+02:00"
}
there will be an exception. 
normal if there is one decimal digit less:

PUT /test/event/1?pretty
{
  "time": "2017-05-24T17:56:28.012345678+02:00"
}

**Provide logs (if relevant)**:

{
   "error": {
      "root_cause": [
         {
            "type": "mapper_parsing_exception",
            "reason": "failed to parse [time]"
         }
      ],
      "type": "mapper_parsing_exception",
      "reason": "failed to parse [time]",
      "caused_by": {
         "type": "illegal_argument_exception",
         "reason": "Invalid format: \"2017-05-24T17:56:28.0123456789+02:00\" is malformed at \"9+02:00\""
      }
   },
   "status": 400
}

**Comment by cbuescher** [comment]
This is expected, the default date parsing format `strict_date_optional_time` does not support more digits. If you need more digits you can define your own [format](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html), e.g. using `"format": "yyyy-MM-dd'T'HH:mm:ss.SSSSSSSSSSZ"` will give you ten digits, and you can specify even more. However, internally dates will be stores as  a long number representing milliseconds-since-the-epoch, so this will not increase the precision on the date stored internally.

**Comment by Alfred1992** [comment]
Thank you
