### ISSUE TITLE
Configurable Netty4 EventLoopGroup in Client

### ISSUE THREAD

**Issue by sschepens** [elastic/elasticsearch#25007]
One of the benefits of Netty and recommended setting is to use the same EventLoopGroup in an application, this allows for reduced thread usage and context switching.

It would be great if client would allow to provide an external EventLoopGroup and be used by the transport instead of creating a new EventLoopGroup for each client instance.

Furthermore client could reuse a single static EventLoopGroup among all client instances.

**Comment by javanna** [comment]
hi @sschepens ,
does that mean that you are using multiple transport client instances in your application? Can you elaborate on that?

**Comment by jasontedor** [comment]
You're right @sschepens, we probably should enable this. However, the are some complications:
 - the transport client is going to be deprecated and removed
 - we do not want to entangle the transport client with Netty 4 as other transport implementations can be used
 - because of the way in which in plugins are instantiated, we do not have an easy way for a plugin to provide a specific object used to instantiate any of its dependencies

This means that to make all of this work:
 - we would need to add plumbing to be able to push a shared event loop group down
 - we would need to add a rather ugly static method to Netty4Plugin to enable setting the event loop group so that it can be pushed through the plumbing
 - this would then enable touching Netty classes before we have a chance to initialize which gets delicate because we go to great lengths to ensure we've initialized everything that we want before any Netty classes are touched as they start initializing

Given this, while I think this would be a good change to make, I do not think that it is a change that we should make. The combination of the transport client eventually being removed combined with the costs of making this change are not less than the benefits.
