### ISSUE TITLE
HEAD /*  returns http status code 200 when there are no indices in the cluster

### ISSUE THREAD

**Issue by JefStat** [elastic/elasticsearch#25056]
**Elasticsearch version**: 5.4.1

**Plugins installed**: none

**JVM version** (`java -version`): java version "1.8.0_131"

**OS version** (`uname -a` if on a Unix-like system): Window 10

**Description of the problem including expected versus actual behavior**:

`HEAD /*`  returns 200 when there are no indices in the cluster. This behaviour is changed from 5.3.1 which returns a 404. Any index name and the `*` wildcard always return http status code 200 even when the index pattern doesn't exist.

**Comment by tlrx** [comment]
`HEAD` and `GET` requests were reworked in 5.4.0 so that behavior are now aligned (see [5.4.0 releases notes](https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-5.4.0.html))

In 5.4.0 a HEAD request with * wildcard does not fail as it _allows that no indices are resolved from wildcard expressions (not returning an error)_ . If you want to get back the old behavior then you can explicitly set the parameter `allow_no_indices` to `false`.

**Comment by tlrx** [comment]
I'm marking this as a non-issue but @jasontedor or @javanna know better the whole story around HEAD and GET requests.

**Comment by jasontedor** [comment]
I think you covered it perfectly @tlrx.
