### ISSUE TITLE
Field collapsing

### ISSUE THREAD

**Issue by imranazad** [elastic/elasticsearch#25135]
Is there any documentation on using field collapsing the issues it causes with pagination? How is one supposed to paginate through results that have been collapsed?

**Comment by clintongormley** [comment]
Yes, [it says](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/search-request-collapse.html): 

> The total number of hits in the response indicates the number of matching documents without collapsing. The total number of distinct group is unknown.

You can't count the total number of unique values in the collapsed field without scrolling through all results.  You could use a `cardinality` aggregation on that field to estimate the number of unique values, but that will introduce overhead.

You can do what google does and say "duplicate results have been removed", or you could use continuous scrolling instead of pagination
