### ISSUE TITLE
mapper_parsing_exception returns status 400 in JSON response, but HTTP status is 200

### ISSUE THREAD

**Issue by grasmanek94** [elastic/elasticsearch#25156]
**Elasticsearch version**: 5.4.1

**Plugins installed**: []

**JVM version** (`java -version`):

openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-1~bpo8+1-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

**OS version** (`uname -a` if on a Unix-like system): 

Linux luna 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

Actual behaviour: When trying to bulk index a document with an invalid mapping (adding values that do not exist in the mapping), elasticsearch returns a 'mapper_parsing_exception'. In the JSON response a status code of 400 is specified and the HTTP status code is 200.

Expected behaviour: The HTTP status code is also 400. The expected behaviour is reflected when performing an invalid search for example.

**Steps to reproduce**:

1. Create a mapping for a document
2. Bulk update the document with fields that are not defined in the mapping

Also see https://github.com/ErickTamayo/laravel-scout-elastic/issues/37

**Provide logs (if relevant)**:

The HTTP response in question:

    HTTP/1.1 200 OK
    Date: Fri, 09 Jun 2017 15:00:27 GMT
    Server: Apache/2.4.10 (Debian)
    content-type: application/json; charset=UTF-8
    content-length: 481
    
    {"took":4,"errors":true,"items":[{"update":{"_index":"balaena-erp-dev3","_type":"offers","_id":"11202","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse [offer.operational_lease_neutral]","caused_by":{"type":"json_parse_exception","reason":"Current token (VALUE_TRUE) not numeric, can not use numeric value accessors\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@6015afde; line: 1, column: 1225]"}}}}]}

**Comment by jasontedor** [comment]
The status in the response is per bulk item, so each bulk item can have a separate status. The actual HTTP status of 200 OK means that the coordinating node that received the request successfully processed the request handling each bulk item as expected. To know if there are failures, you have to check the `errors` key

**Comment by grasmanek94** [comment]
Alright, that explains it I think. But what is the suggestion then? Report this as a bug to elasticsearch-php, or to the package maintainer that uses elasticsearch-php? We have no access to the http output in our application. And it's debatable that a 200-OK (everything OK) response when 100% of the items fail to update is the correct response, especially when a exception occurs...

**Comment by jasontedor** [comment]
> But what is the suggestion then? Report this as a bug to elasticsearch-php, or to the package maintainer that uses elasticsearch-php?

@polyfractal Does the PHP client expose the `errors` key in a bulk response?

> And it's debatable that a 200-OK (everything OK) response when 100% of the items fail to update is the correct response, especially when a exception occurs...

I will try to explain again. The 200 OK means that the coordinating node did its job. The only time in which a 200 OK is not acceptable here is if the coordinating node fails to do its job, either because of a client error in the request, or because of a server error handling the request. A 200 OK means: I took your requests, I parsed the body, I sent the bulk items to the responsible shards, I waited for their replies, I received their replies, here are the aggregated responses.

**Comment by polyfractal** [comment]
Sorry for delay, was out of town friday/weekend.

@jasontedor @grasmanek94 Yes, the `errors` key is available in the response.  The PHP client returns the entire JSON body of the response (encoded as a associative array), so you can access it like this:

```php
$responses = $client->bulk($params);
print_r($responses['errors']);  // Print out the error array
print_r($responses['items']);   // Print out the individual bulk item responses
```

For example, this snippet will cause an error because only the first document can be indexed due to the `create` operation.  The other two documents will fail since the initial document already exists and they all share the same ID:

```php
$client = Elasticsearch\ClientBuilder::create()->build();
$params = [];
for($i = 0; $i < 3; $i++) {
    $params['body'][] = [
        'create' => [
            '_index' => 'my_index',
            '_type' => 'my_type',
            '_id' => 1
        ]
    ];

    $params['body'][] = [
        'my_field' => 'my_value',
        'second_field' => 'some more values'
    ];
}

$responses = $client->bulk($params);
if (isset($responses['errors']) && $responses['errors'] === true) {
    echo "There was one or more errors in the bulk response.\n\n";
}
foreach ($responses['items'] as $item) {
    echo "Status: {$item['create']['status']}\n";
    if (isset($item['create']['error']) === true) {
        print_r($item['create']['error']);
    }
    echo "\n";
}
```
Which will output the following values:

```
There was one or more errors in the bulk response.

Status: 201

Status: 409
Array
(
    [type] => version_conflict_engine_exception
    [reason] => [my_type][1]: version conflict, document already exists (current version [1])
    [index_uuid] => maU4iW15SmyoZadsmRiNWw
    [shard] => 3
    [index] => my_index
)

Status: 409
Array
(
    [type] => version_conflict_engine_exception
    [reason] => [my_type][1]: version conflict, document already exists (current version [1])
    [index_uuid] => maU4iW15SmyoZadsmRiNWw
    [shard] => 3
    [index] => my_index
)
```

You can see that at the top level of the response, we can check if the `errors` element is set and if it's true/false.  This lets you know that you need to check for errors in the individual responses.

Then, when iterating over the response items, you can check to see if there is a `error` element.  If it exists, it will list the exception that caused the item to fail.  There is also a per-item status code which corresponds to that individual item's failure (`409` in this case)

**Comment by jasontedor** [comment]
@grasmanek94 Given that the PHP client does expose the `errors` key, I do not think there's anything to change here. Do you concur?

**Comment by grasmanek94** [comment]
@jasontedor that's quite clear and I agree with the statements made here, I'll forward this info to the package maintainer ( https://github.com/ErickTamayo/laravel-scout-elastic/issues/37 ) and discuss possible solutions.
