### ISSUE TITLE
`geo_bounding_box` should be smarter about how it parses geo hashes

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#25154]
Say you ran a `geohash_grid` aggregation and want to filter documents that fell into a particular bucket. Currently, we do not provide an easy way to do that: the user has to compute the top left and bottom right coordinates that map to this geohash.

The `geo_bounding_box` already accepts geohashes as input to the corners, but we just parse it into one point that belongs to the geohash cell. If instead we made sure to round correctly and parse the top-left geohash as the top-left point of the geohash and the bottm right geohash as the bottom right point of the geohash then users could just pass the same geohash as a top-left and bottom-right corner and the bounding box would match the right documents?

cc @nknize

**Comment by nknize** [comment]
Thanks @jpountz. I've got a method in GeoUtils to compute the bounding box from a geohash. I can go ahead and add this to the GeoBoundingBoxBuilder so if the user passes just a geohash (without top_left and bottom_right) the correct bounding box is computed.

**Comment by tobias74** [comment]
which would basically bring back geohash_cell, wouldn't it? :-)

**Comment by jpountz** [comment]
Not really, geohash_cell worked by indexing geohashes at index-time and querying at search time using (combinations of) `term` queries. From a user perspective, it probably looks similar, but in that case we actually plan on running a bbox query on the coordinates of indexed geo-points, without requiring geo hashes to be indexed.

**Comment by imotov** [comment]
While writing the tests for this issue I realized that if we index a geopoint specified as a geohash it is indexed as a bottom left corner of the corresponding geohash cell instead of the center as one would expect. On high precision geohashes it doesn't really matter but with low precision geohashes it produces somewhat strange results. Would it makes sense change this as well? @nknize what do you think?

**Comment by imotov** [comment]
I have discussed this with @nknize. For me, the main conclusion of this discussion was that we support two very different data structures using the same elasticsearch datatype: geohashes and geo point and that's the source of many issues. Geo points are zero dimensional objects that are represented by longitude and latitude pairs. The geohashes are two dimensional objects that represent cells of geohash grid, which are stored as longitude and latitude of the bottom left point of the cell. 

Currently, if we operate only using geopoints or only geohashes with the same precision everything works, but the moment we try to mix together geo points with geohashes or geohashes with different precision, the fact that geohashes are stored as a single point without precision breaks things. 

For example, if we index 4 geohashes `drt70`, `drt71`, `drt40`, and `drt41` and then search for:
```
    "geo_bounding_box": {
      "pin":
      {
        "top_right": "drt7",
        "bottom_left": "drt4"
      }
    }
```
 we will get back `drt40`, `drt41`, and `drt70` but will not get back `drt71` because our current implementation only includes My PR #30698 fixes this issue, but it introduces another issue - since the top right corner of `drt7` is the same point as the bottom left corner of `drts` with my PR the query above will also include `drts`, `drts0`, `drts00` and so on. I could modify my PR to make top right edges exclusive, but then we will get into a variation of missing edge points problem #29196 but this time for top right edge. I am not really sure what's the right way to proceed here.

**Comment by tobias74** [comment]
AS @nknize pointed out he has a method that calculates top_left and bottom_right from a geohash_cell. So if a user passes a geohash_cell to the query it could be translated to a bounding_box_query. Without bringing back the old "geohash_cell"-filter (calculating geohashes at indexing-time and using terms-filters at query time) **the bounding-box-filter could be used and just accept a geohash_cell as its input**.

This would make the process of aggregating over geohashes and filtering over the resulting geohash_cells seamless again. Currently I have to calculate the top_left and bottom_right from the geohash_cell in my client, and perform a bounding-box-query manually. 

In the end it seems a little odd, having an aggregation-result in form of geohashes and not being able to use them again as an input.

**Comment by jpountz** [comment]
@tobias74 that would look something like that:

```
GET /_search
{
    "query": {
        "geo_bounding_box" : {
            "pin.location" : {
                "top_left" : "mygeohash",
                "bottom_right" : "mygeohash"
            }
        }
    }
}
```
