### ISSUE TITLE
Provide option to make unavailable path.repo nonfatal

### ISSUE THREAD

**Issue by charles-dyfis-net** [elastic/elasticsearch#25184]
At present:
- Any directory to be used for snapshots must be listed in `path.repo`.
- Every directory listed in `path.repo` must exist.

This means that if a directory listed in `path.repo` is temporarily unavailable, ElasticSearch cannot start. This complicates efforts to build a robust configuration which survives unavailability of its backup storage, and which does not require a restart to be able to use such storage should it become available again after having been down.

Preferring to fail fast with invalid configurations is understandable, and in many situations desirable; however, in this specific case, it is contrary to robust operation. A knob should be provided to allow ES to start up even if not all of the directories in `path.repo` are available, with the understanding that snapshot operations will fail until/unless this is rectified.

**Comment by charles-dyfis-net** [comment]
BTW -- I'm entirely happy to do the development on this one, should y'all indicate willingness to merge such a feature (should it be implemented to your satisfaction).

**Comment by nik9000** [comment]
A small group of the maintainers talked about this and decided that the behavior we have is almost certainly the safest. The trouble is that being able to pick up the directory later one is much more complex then we'd like and we won't be able to test it properly.

The things that worry me about this are:
1. To setup the jvm security on bootstrap we need to call [toRealPath](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Path.html#toRealPath-java.nio.file.LinkOption...-) on the thing to resolve symlinks. Mounting a new path is very likely to make this incorrect. We can't delay this because the transition into the java sandbox is one way.
2. The extra complexity around rejecting snapshots until the directory is "ready" isn't a thing we'd like to maintain either.
3. We're quite unlikely to test this well because we'd have to emulate things mounting which we don't have good infrastructure for.
