### ISSUE TITLE
feature request for hot switching primary shard and special settings for master node

### ISSUE THREAD

**Issue by sinsonglew** [elastic/elasticsearch#25239]
I know there has been the feature request for hot switching master node, even more, 

**1. is it possible to switch primary shard except bringing down the node hosting the shard.** 

**2. is it reasonable to support special settings for master node, such as  only replicate shard can locate on it, less requests assigned on it.**

Thanks!

**Comment by bleskes** [comment]
@sinsonglew replicas and primary in Elasticsearch are doing almost exactly the same amount of work (except for when you have gazillion version conflicts or updates - a known issue we plan address) due to sync replication. People requesting for this feature typically have something going on. I suggest you open a question on our [forums](http://discuss.elastic.co) to figure things out further. If it ends up we don't have an open issue/feature to track it we can move back to github.
