### ISSUE TITLE
[feature request]in place update for certain fields

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#25332]
solr has already had this feature:
https://cwiki.apache.org/confluence/display/solr/Updating+Parts+of+Documents
In-Place Updates

In-place updates are very similar to atomic updates; in some sense, this is a subset of atomic updates. In regular atomic updates, the entire document is re-indexed internally during the application of the update. However, in this approach, only the fields to be updated are affected and the rest of the documents are not re-indexed internally. Hence, the efficiency of updating in-place is unaffected by the size of the documents that are updated (i.e., number of fields, size of fields, etc.). Apart from these internal differences, there is no functional difference between atomic updates and in-place updates.

An atomic update operation is performed using this approach only when the fields to be updated meet these three conditions:

    are non-indexed (indexed="false"), non-stored (stored="false"), single valued (multiValued="false") numeric docValues (docValues="true") fields;
    the _version_ field is also a non-indexed, non-stored single valued docValues field; and, 
    copy targets of updated fields, if any, are also non-indexed, non-stored single valued numeric docValues fields.

To use in-place updates, add a modifier to the field that needs to be updated. The content can be updated or incrementally increased.

So I'd like to see if ES will provide this feature or not.

**Comment by jpountz** [comment]
This is a feature we have been wondering how to expose, it's a bit tricky.

> the efficiency of updating in-place is unaffected by the size of the documents that are updated

This is correct, however it depends on the number of docs of the segment that contains the updated doc, since all values for that segment need to be rewritten. So doc-values updates are no silver bullet. This is quite a complicated trade-off actually.

> only when the fields to be updated meet these three conditions: are non-indexed (indexed="false") [...]

It is quite an uncommon case to have fields that have doc values but are not indexed. Not only because fields are indexed by default, but also because one you aggregate a field, the next step is often to filter documents that match a particular bucket.

Also Elasticsearch makes this feature more tricky to expose due to the `_source` field. The update of doc-values updates would mean that `_source` and doc values could go out of sync.

I'm curious on what fields you want to use this feature?

**Comment by makeyang** [comment]
@jpountz 
It is quite an uncommon case to have fields that have doc values but are not indexed. 
here is the thing: in the database fields, there is a query optimizer sitting there to rewrite query based on cost. if one index is poorly selective, then the execution plan will go throgh the table scan rather than using index. 
actually I borrowed this idea when using elasticsearch: my use case is I have to search some products in e-commerce business with certain price range. but the price is update very frequently and it is poorly selective. so yes, I don't index it, yes I have to update it, yes I have to use it to post filter out results. And all these yes combined together, we do need this in place update feature.

**Comment by jpountz** [comment]
Thanks for the explanation. This is one of the use-cases that would make sense for this feature. But it still remains pretty tricky to expose and use right. I'm adding the `discuss` label to get more eyes on it.

**Comment by s1monw** [comment]
> So I'd like to see if ES will provide this feature or not.

Lemme try to explain the issue with this feature. If you update a document in es today everything will be consistent. your source will be updated, the values will be searchable, you can use it for scoring etc. With the  doc values updates you would loose all this. This has a significant impact on how the system works which we are not willing to take at this point without a clear path forward. That said, even if we had a clear plan the implementation in lucene (segments are updated in a copy-on-write fashion) will very likely have a significant impact on the systems stability since users might wanna use this as counters etc. or values that frequently change. in such a case we will rewrite segments on a constant basis which is a showstopper at this point. if the internals of the feature changes we might reconsider exposing it.
