### ISSUE TITLE
Article highlighting gets "fuzzied" if a field is matched both fuzzy and non-fuzzy way in the same query.

### ISSUE THREAD

**Issue by kori0129** [elastic/elasticsearch#25378]
**Elasticsearch version**: 5.2

**Plugins installed**: none

**JVM version** (`java -version`): 1.8.0_131

**OS version** (`uname -a` if on a Unix-like system):
Linux 3.10.0-514.6.1.el7.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**: 

Action: I match on textfield "myfield" twice in the same query: once normally, once fuzzy (with a 0.1 boost factor), then I apply highlighting on "myfield".

Expected Behaviour: Highlighting shouldn't highlight fuzzy results unless asked to do so.

Actual Behaviour: The highlighting highlights fuzzy results. 

**Steps to reproduce**:

 1. Create an index with a type and one text field in it called "myfield"
 2. Add documents with the following value for "myfield":  "gas", "was", "has"
 3. Query the index matching on 1)myfield, and 2)myfield with fuzzyness of AUTO. Add highlighting for myfield. Use search term "gas". 
 4. Highlighting will highlight "was" and "has"

**Comment by nik9000** [comment]
Highlighting doesn't work like this. But it is *so* close to possible. So here is what I think you are doing:
```
DELETE /test

PUT /test/doc/1?refresh
{
  "test": "gas was has"
}

POST /test/_search
{
  "query": {
    "bool": {
      "should": [
        {"match": {"test": "gas"}},
        {"fuzzy": {"test": "gas"}}
      ]
    }
  },
  "highlight": {
    "fields": {
      "test": {}
    }
  }
}
```

That gets you `<em>gas</em> <em>was</em> <em>has</em>` which isn't what you wanted.

My instinct was to try:
```
POST /test/_search
{
  "query": {
    "bool": {
      "should": [
        {"match": {"test": "gas"}},
        {"fuzzy": {"test": "gas"}}
      ]
    }
  },
  "highlight": {
    "fields": [
      {
        "test": {
          "highlight_query": {"match": {"test": "gas"}}
        }
      },
      {
        "test": {
          "highlight_query": {"fuzzy": {"test": "gas"}}
        }
      }
    ]
  }
}
```

Which *almost* works. It doesn't *quite* work because of the way highlighting returns results. Internally, the highlighter executes this to produce the right results but it throws away the first one. If you reorder the list in `fields` you can see that.

Now, we *could* fix this. And maybe we should for completeness sake. But it is often a better choice to use the term or phrase suggester and run the query without any fuzziness. Then you can present a "did you mean" style prompt. As compared to running with a fuzzy and non-fuzzy query. I don't know for sure what you are trying to do, but the reason I've never needed this feature before is because I've used the phrase suggester for "did you mean" instead of doing this.

I suppose the question is, "is it worth changing the response in the highlighting API so you can do this?" I don't know the answer to that so I've marked the issue as `discuss`. I expect @jimczi to have some opinions about it but he is away.

**Comment by clintongormley** [comment]
Discussed in FixItFriday.  The highlighter is actually doing the same thing the query is doing.  For instance, a query on the field `gas has` would match both terms with both fuzzy and non-fuzzy, and the highlighter reflects that.

@nik9000 while we could change the format to handle multiple highlights on the same field, we prefer the idea you implemented for wikipedia of prioritised/fallback highlighting.  That's obviously a big project though, but I think it would be widely useful

**Comment by jimczi** [comment]
Closing this in favor of https://github.com/elastic/elasticsearch/issues/5172 which has a different scope but I assumed that this is what @clintongormley had in mind in the previous comment.
Regarding the original issue to **not** highlight some part of the query, the `highlight_query` option should work fine as long as you don't need to highlight the same field multiple times (with different `highlight_query` as @nik9000 pointed out).
