### ISSUE TITLE
Add Restart=on-failure to systemd in packaging

### ISSUE THREAD

**Issue by martinb3** [elastic/elasticsearch#25425]
We've got some folks using the Elasticsearch cookbook for Chef asking after systemd packaging changes, specifically:
```
Restart=on-failure
RestartSec=30
```

Is this something we should include in Elasticsearch itself, in the systemd packaging? It feels like restarting on failure is a pretty safe change for systemd. The default is to do nothing, and on-failure's behavior is described as;

> If set to on-failure, the service will be restarted when the process exits with a non-zero exit code, is terminated by a signal (including on core dump, but excluding the aforementioned four signals), when an operation (such as service reload) times out, and when the configured watchdog timeout is triggered.

**Comment by tlrx** [comment]
I'm not really in favor of adding this option by default, because it can be trappy by hiding a node failure. And also because the behavior on systemd would be different from the sysv init one. I'm also curious about the behavior if a wrong JVM option has been set. In this case the JVM should exit with a non zero exit code, and systemd restart it over and over?

**Comment by pandamako** [comment]
Hi @tlrx.
May be set 'on-faileur' by default is not good idea, but we can use value 'no' by default.

**Comment by jasontedor** [comment]
We discussed this in Fix-it-Friday and agreed that we should not do this essentially for the reasons that @tlrx outlines above. Users that do want this functionality can easily do this by adding an additional unit file in `/etc/systemd/system/elasticsearch.service.d/elasticsearch.conf` (and a few other places that `systemd` supports).
