### ISSUE TITLE
[CI] Failure of org.elasticsearch.common.logging.EvilLoggerTests testDeprecatedSettings

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#25498]
Console log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.x+multijob-unix-compatibility/os=ubuntu/927/console

Stack:

```
FAILURE 0.04s J0 | EvilLoggerTests.testDeprecatedSettings <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <1>
   >      but: was <0>
   > 	at __randomizedtesting.SeedInfo.seed([996F8227E4E1FD0B:F91679FDCF0EEB84]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.common.logging.EvilLoggerTests.testDeprecatedSettings(EvilLoggerTests.java:271)
   > 	at java.lang.Thread.run(Thread.java:748)
```

Repro command:

```
gradle :qa:evil-tests:test -Dtests.seed=996F8227E4E1FD0B -Dtests.class=org.elasticsearch.common.logging.EvilLoggerTests -Dtests.method="testDeprecatedSettings" -Dtests.security.manager=false -Dtests.locale=es-US -Dtests.timezone=Asia/Beirut
```

This does not reproduce for me.

I wonder if the problem is not actually in the test that is failing but in some sort of unfinished processing that is still in progress when the concurrent test that was recently added in 11f491d43b1559055eecf6822f6bc0b66eb48730 completes?

**Comment by jasontedor** [comment]
It's really unclear to me what happened here, and this has not reproduced since, and did not reproduce for me after 4096 executions. I do not think the two tests interfered with each other as they use separate temporary directories and independent loggers. I did push fe04b666ea36a428d5ac174ccf72db9924744658 so that we can see the actual logging here in case this occurs again. I'm going to close this for now, if we see this occur again I will take a deeper look.
