### ISSUE TITLE
Remove `_default_` type

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#25500]
With the move to a single type, it no longer makes sense to provide a `_default_` type as you can only every create one type.

We should deprecate and remove the `_default_` type.

**Comment by clintongormley** [comment]
@jpountz what do you think?  deprecate in 5.6 and remove in 6.0?

**Comment by jpountz** [comment]
Agreed the `_default_` type becomes useless now. My only worry is that I saw it used in many templates, including by users who only plan on having a single type anyway. So I'm thinking of deprecating in 6.0 since it is the first version to enforce a single type, but only removing in 7.0 in order for existing templates to keep working a bit longer, similarly to how we added a translation layer from strings to text/keyword in order to keep templates working when we released 5.0?

**Comment by clintongormley** [comment]
@jpcarey agreed

**Comment by clintongormley** [comment]
@jpountz @colings86 actually i think we should deprecate in 5.6 and remove in 7.0.  It no longer makes sense from 6.0 onwards.

**Comment by jpountz** [comment]
If someone wants to give it a try, all that is needed is probably to add `if (reason == MergeReason.UPDATE) { log deprecation warning }` under the `if (defaultMapper != null) {` at line 358 of `MapperService`. Checking the merge reason helps only emitting the warning when the mapping is put as opposed to just replicated to other nodes of the cluster.
