### ISSUE TITLE
Shingles not working as expected

### ISSUE THREAD

**Issue by fhelje** [elastic/elasticsearch#25555]
Im trying to use elastic to extract brands from a texts. For this I created a index containing brands a synonyms where the synonyms are analysed as keywords. I then search for brand with shingles (scripts to reproduce is below). This works great in elastic version 2.4.4. When I try this in elastic 5.4.3 it doesn't work at all, I looked at the data with the analyze endpoint and it looks like it should work.

Had a disussion about how shingles work here: https://discuss.elastic.co/t/extracting-brands-in-documents-using-keyword-and-shingles/91873.

We agreed that this is a regression for elastic 5.4.3.

Scripts to reproduce:

```
PUT brand
{
  "settings": {
    "analysis": {
      "analyzer": {
        "my_analyzer_keyword": {
          "type": "custom",
          "tokenizer": "keyword",
          "filter": [
            "asciifolding",
            "lowercase"
          ]
        },
        "my_analyzer_shingle": {
          "type": "custom",
          "tokenizer": "standard",
          "filter": [
            "asciifolding",
            "lowercase",
            "shingle"
          ]
        }
      }
    }
  },
  "mappings": {
    "brand": {
      "properties": {
        "keyword": {
          "type": "text",
          "analyzer": "my_analyzer_keyword",
          "search_analyzer": "my_analyzer_shingle"
        }
      }
    }
  }
}
```

Some documents:

```
POST /brand/brand/1
{
  "id": 1,
  "keyword": "nike"
}
POST /brand/brand/2
{
  "id": 2,
  "keyword": "adidas originals"
}
```
I then search like this:
```
POST /brand/brand/_search
{
  "query": {
    "match": {
      "keyword": "I like nike shoes and adidas originals"
    }
  }
}
```
I expect to get **nike** and **adidas originals** as the result but I don't get anything back.

Looking at how this is analysed we see: 
Query:
```
GET _analyze
{
   "tokenizer": "standard",
   "filter": [
      "asciifolding",
      "lowercase",
      "shingle"
   ],
   "char_filter": [
      "html_strip"
   ],
   "text": [
      "I like nike shoes and adidas originals"
   ]
}
```
Result (shortened for brevity):
```
{
   "tokens": [
      ...
      {
         "token": "nike",
         "start_offset": 7,
         "end_offset": 11,
         "type": "<ALPHANUM>",
         "position": 2
      },
      {
         "token": "nike shoes",
         "start_offset": 7,
         "end_offset": 17,
         "type": "shingle",
         "position": 2,
         "positionLength": 2
      },
      ...
      {
         "token": "adidas",
         "start_offset": 22,
         "end_offset": 28,
         "type": "<ALPHANUM>",
         "position": 5
      },
      {
         "token": "adidas originals",
         "start_offset": 22,
         "end_offset": 38,
         "type": "shingle",
         "position": 5,
         "positionLength": 2
      },
      {
         "token": "originals",
         "start_offset": 29,
         "end_offset": 38,
         "type": "<ALPHANUM>",
         "position": 6
      }
   ]
}
```
Index:
```
GET _analyze
{
   "tokenizer": "keyword",
   "filter": [
      "asciifolding",
      "lowercase"
   ],
   "char_filter": [
      "html_strip"
   ],
   "text": [
      "adidas originals"
   ]
}

```
Result:
```
{
   "tokens": [
      {
         "token": "adidas originals",
         "start_offset": 0,
         "end_offset": 16,
         "type": "word",
         "position": 0
      }
   ]
}
```
Tried it on elastic version 2.4.4 and there it worked just fine.

I got the expected result 
```
{
   "took": 73,
   "timed_out": false,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   },
   "hits": {
      "total": 2,
      "max_score": 0.003867892,
      "hits": [
         {
            "_index": "brand",
            "_type": "brand",
            "_id": "2",
            "_score": 0.003867892,
            "_source": {
               "id": 2,
               "keyword": "adidas originals"
            }
         },
         {
            "_index": "brand",
            "_type": "brand",
            "_id": "1",
            "_score": 0.003867892,
            "_source": {
               "id": 1,
               "keyword": "nike"
            }
         }
      ]
   }
}
```

**Comment by jimczi** [comment]
## It's a bug

Thanks, the bug affects only the default `shingle` filter so the workaround is to force a custom `shingle` filter in the mapping and use it instead.
The following restores the 2.x behavior:

````
PUT brand
{
  "settings": {
    "analysis": {
      "filter": {
    	"my_shingle": {
        	"type": "shingle"
    	}
      },
      "analyzer": {
        "my_analyzer_keyword": {
          "type": "custom",
          "tokenizer": "keyword",
          "filter": [
            "asciifolding",
            "lowercase"
          ]
        },
        "my_analyzer_shingle": {
          "type": "custom",
          "tokenizer": "standard",
          "filter": [
            "asciifolding",
            "lowercase",
            "my_shingle"
          ]
        }
      }
    }
  },
  "mappings": {
    "brand": {
      "properties": {
        "keyword": {
          "type": "text",
          "analyzer": "my_analyzer_keyword",
          "search_analyzer": "my_analyzer_shingle"
        }
      }
    }
  }
}
`````

## The default setting for the `shingle` filter are not sane

Though this issue hides a bigger problem, we should not avoid `shingles` of different size in the same field.
In 5.3 we introduced graph analysis at query time and this reveals this kind of problem where users are mixing unigrams and bi-grams on the same field (totally not your fault though since this is the default ;) ). 
Then in 5.3.1 we restored the old behavior automatically for analyzer that defines a graph `shingle` filter but this fix has not been applied to the already registered default `shingle` filter.
So I think we should also remove the ability to create such fields in 6, which means changing the default to not output unigrams and replace `min_gram`, `max_gram` with `gram_size`.
We discussed this is FixItFriday some times ago but I did not had time to work on it.

I'll work on a fix for 5.x (we should also disable graph analysis for the already registered default shingle filter) and I'll open a new issue if needed for 6.
In the mean time you can use the work around described or try another approach with two queries, one that search for bi-grams and one for unigram. In your case you don't even have to reindex since the goal is to find exact matches in the document from partial queries.
