### ISSUE TITLE
[Feature Request] Sharing nested documents across primary documents

### ISSUE THREAD

**Issue by yazaddaruvala** [elastic/elasticsearch#25656]
**Describe the feature**:

Hey, I'm not very familiar with the internals of ElasticSearch, forgive me if this feature request is far fetched. If so, please educate me I'm happy to learn about any limitations.
 
I work at Amazon. We have a use case where we use nested documents that can be shared across primary documents. Currently, the data is all denormalized, and there is a lot of duplication. What I'm looking for is to be able to specify the nested document's key+version at index time.
 
You may want to recommend we index these as two different types and do application side joins. We tried this, and apart from the latency impact, it was very limiting. Primarily, we need to be able to filter on both the fields of the primary document and the nested document at the same time (I can explain more about this if people would like).
 
Contrived Example:
 
Houses have windows, but different houses can have the same window model.
 
Example:
```
{
  _id: "House A",
  windows: [
     {
         manufacturer_id_part_number: "Windows R Us_123456",
         inspections_passed: [12, 13123, 123, 31231, 13213, ...],
     },
     ...
  ],
  ...
},
{
  _id: "House B",
  windows: [
     {
         manufacturer_id_part_number: "Windows R Us_987654",
         inspections_passed: [31231, 13213, ...],
     },
     {
         manufacturer_id_part_number: "Windows R Us_123456",
         inspections_passed: [12, 13123, 123, 31231, 13213, ...],
     },
     ...
  ],
  ...
},
```
 
I imagine the inverted index looks something like:
There will be three nested documents (mapping to their primary document):
```
{
    "House A::<Random UUID>" -> "House A", /* Represents: "Windows R Us_123456" */
    "House B::<Random UUID>" -> "House B", /* Represents: "Windows R Us_987654" */
    "House B::<Random UUID>" -> "House B", /* Represents: "Windows R Us_123456" */
}
```
 
Ideally: There should only be two nested documents:
```
{
    "Windows R Us_123456" -> ["House A", "House B"],
    "Windows R Us_987654" -> ["House B"],
}
```
 
Query:
```
GET yazad_test/_search
{
 "query": {
   "bool": {
     "filter": {
       /* House fields */
     }, 
     "must": [
       {"nested": {
         "path": "windows",
         "query": {
           "bool": {
             "minimum_number_should_match": 2,
             "should": [
               { "match": { "inspections_passed": "123" }},
               { "match": { "inspections_passed": "987" }}
             ]
           }
         }
       }
     }]
   }
 }
}
```
 
In the real usecase, there are a lot of window documents, and each is relatively large (`inspections_passed` has on average 1000 values). There are also a large ratio of these nested window documents which are duplicates.
 
Now for the tricky parts: What we are asking for above, is basically joins across types, which we understand is not ideal. Multi-shard joins would be non-performant. As such, joins on nested documents are likely fast because they are colocated on the same shard.
 
Given that, we would be happy to see the reduction in duplicate nested documents, even at a per shard level (we have a lot of documents). Extending the example from above:
```
{
    "<Shard 1>::Windows R Us_123456" -> ["House A", "House B"],
    "<Shard 1>::Windows R Us_987654" -> ["House B"],
},
{
    "<Shard 2>::Windows R Us_123456" -> ["House C"],
}
```
 
Let me know what you think.
 
Thanks,
Yazad

P.S. We can consider the "window documents" as immutable, as such I'm not so concerned about specifying an external version, but for the sake of completeness thought I'd include it in this request.

**Comment by javanna** [comment]
hi @yazaddaruvala ,
when using the nested type, you submit a single document that contains all of its nested documents. The nested ones get extracted and indexed as separate lucene documents, but the whole structure is stored in the same lucene segment block. Parent and all its nested are stored contiguously, which is what makes nested documents the fastest way to do "joins" within Elasticsearch.

Lucene segments are immutable, which is why updating a single nested document in the whole tree structure requires reindexing the parent with all of its nested docs.

Due to the way nested docs are stored in lucene and the immutability of segments, I do not think that what you are asking is possible. You can't have a new document referencing an existing nested document that is stored in some other segment. The assumption that the whole structure is stored in the same segment block wouldn't hold anymore.

Same wouldn't be possible using parent-child either, which tends to be a bit more flexible than nested, but it allows to specify only one parent id per document. One document can't have multiple parents.

@martijnvg @jimczi do you have anything to add?

**Comment by jimczi** [comment]
> Same wouldn't be possible using parent-child either, which tends to be a bit more flexible than nested, but it allows to specify only one parent id per document. One document can't have multiple parents.

Nothing to add, that's a limitation of the parent-child and there is nothing we can do about it at the moment.

Since the number of child documents per parent is small (an house cannot have thousands of windows) I think that using `nested` is a good solution. You have fast joins but you have to pay the price of child duplications on disk. That's a good trade off considering how slow another type of join could be.

**Comment by javanna** [comment]
Thanks @jimczi . Given that we cannot support this feature, I am going to close this issue.

**Comment by yazaddaruvala** [comment]
Interesting. Its good to know more about how nested docs in Lucene work.

Thanks for the quick turn around time and for eliminating this option early. We will focus on other ways to optimize our clusters.
