### ISSUE TITLE
Allow scripts to be built by automation

### ISSUE THREAD

**Issue by klahnakoski** [elastic/elasticsearch#25729]
Apparently `false ? 0 : 1` is not a legitimate painless script; it throws "Extraneous conditional statement" error.  Humans do not write code like this, but some machines do.  Please remove the constant checking.

https://github.com/elastic/elasticsearch/blob/f5c8c746e6ea1750e59a7b683db4f60046dfe2fa/modules/lang-painless/src/main/java/org/elasticsearch/painless/node/EConditional.java#L67

**Comment by klahnakoski** [comment]
Until this is fixed, what should I replace Booleans with?  I am currently using `System.currentTimeMillis() < 0` for `false`.

**Comment by rjernst** [comment]
Checks like this are there explicitly because painless is meant to be a language for humans to write. This is essentially an unreachable statement.

> Humans do not write code like this, but some machines do

But you can change what the machine does.

I don't see this as a bug, so I am going to close. You are welcome to continue using your workaround, but I suggest you change your code generation to not emit dead code.

**Comment by s1monw** [comment]
++ to close you can't do this in java either afaik

**Comment by klahnakoski** [comment]
@rjernst ok, painless does not allow (some) dead code.  Should I make an issue to document this feature?

**Comment by rjernst** [comment]
@klahnakoski If you see a place in the docs that noting this would have alleviated pain for you, we would be happy to find a way to include it. We happily accept PRs. :)
