### ISSUE TITLE
failed to commit cluster state version

### ISSUE THREAD

**Issue by krisko** [elastic/elasticsearch#25925]
**Describe the feature**:

**Elasticsearch version**: 5.3.0

**Plugins installed**: x-pack

**JVM version** (`java -version`): 1.8.0_131

**OS version** (`uname -a` if on a Unix-like system): Linux 2.6.32-642.el6.x86_64 #1 SMP Wed Apr 13 00:51:26 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
Red Hat Enterprise Linux Server release 6.8 (Santiago)

**Description of the problem including expected versus actual behavior**: We are running 2 nodes set as master, with discovery.zen.minimum_master_nodes: 2, one node has low disk space and reaches threshold, occasionally moving shards to the other node.
The issue we have is that the nodes are disconnecting every few hours for period of 15 minutes. This occurs mainly during night when the instance load is minimal.
![elasticissue](https://user-images.githubusercontent.com/2367953/28659080-5eae6fce-72ae-11e7-9194-d00d70806249.png)

The network connection between nodes is working, I was able to connect to the nodes with curl.

Please see the log attached.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

**Provide logs (if relevant)**:
[elastic.log.txt](https://github.com/elastic/elasticsearch/files/1179162/elastic.log.txt)

**Comment by bleskes** [comment]
with two nodes, min master nodes set to 2 (good!) and some network this is expected behavior. We will need to do some debugging to see what the source of the problems. I would suggest you open an forum topic on discuss.elastic.co and we can pick it up there. If it turns out to be a bug in ES we can open an issue with the relevant details.

PS. When you post information to the forum, can you please add trace logging to `org.elasticsearch.discovery.zen.PublishClusterStateAction`? it will help figuring out what goes on.
