### ISSUE TITLE
Elasticsearch  start fail when I configure network.host in elasticsearch.yml. 

### ISSUE THREAD

**Issue by fooltux** [elastic/elasticsearch#25963]
**Elasticsearch version**: 5.5.1-1

**Plugins installed**: [ no ]

**JVM version** (`java -version`): 1.8.0_122

**OS version** (`uname -a` if on a Unix-like system): centos 6.8 x86_64 

**Description of the problem including expected versus actual behavior**: elasticsearch cant' start when I configure  network.host

**Steps to reproduce**:

 1.   Install the newst version of ES and configure
 2.  uncomment network.host and configure It 
 3.  restart elasticsearch  and it's fail

**Provide logs (if relevant)**:
 No logs

**Comment by dadoonet** [comment]
Either the config file is totally messed up otherwise you should get logs.

The guess is that your logs will show you that bootstrap checks are failing. Look at documentation if it's the case.

Better to ask on discuss.elastic.co and come back here if it's really an issue.
I'm closing for now if you don't mind.
