### ISSUE TITLE
Protection against bucket explosion in aggs

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#26012]
This is a continuation for https://github.com/elastic/elasticsearch/issues/14046.
https://github.com/elastic/elasticsearch/pull/19394 solved the original issue but only for the deep nested case. It will fail to detect a root histogram aggregation that returns a gazillon number of buckets for instance:
https://github.com/elastic/elasticsearch/issues/14046#issuecomment-243341863
.. or multi buckets aggs that create empty buckets.

The fact that aggregators use big arrays allocations should be enough to detect deep nested bucket explosion so I have the feeling that adding the static weight of 5kb just fails the big agg faster (and less accurately) than big arrays.
Maybe the accounting of the 5kb could be moved to `InternalMultiBucketAggregation.InternalBucket` creations ? That way we would always detect when a multi bucket aggs creates too many buckets in the final build and maybe even during reduce. I don't know how this would work with incremental reduction of buckets though. Anyway I mark this issue as discuss so that we can evaluate what can be done or not. Bottom line is that bucket explosion can still kill a cluster too easily.

**Comment by jimczi** [comment]
Discussed with @dakrone and during FixItFriday and decided that this is something we should investigate. The weighting of each bucket could be done directly in `InternalMultiBucketAggregation.InternalBucket`. That would also gives the possibility to apply the request circuit breaker in the coordinating node.
I mark this issue as adoptme because neither @dakrone or I have time to work on it at the moment.

**Comment by colings86** [comment]
Adding this to the `InternalBucket` might be tricky because `InternalMultiBucketAggregation ` and `InternalBucket`are not just created on the shard but also on the coordinating node during the reduce phase and on the High Level REST client. Adding the accounting would require us to pass in a `CircuitBreakerService` to the `InternalBucket` and `InternalMultiBucketAggregation ` which would not be possible on the coordinating node or in the client.

I spoke to @jimczi about this and we said that maybe we actually only need to add this kind of accounting on the histogram aggregations since they are the only ones that insert empty buckets so are the only aggregations that should cause this kind of problem at the `buildAggregation()` stage.

**Comment by jimczi** [comment]
As @colings86 said we can protect the bucket explosion directly in the (date)histogram when the final buckets are created. I removed the high hanging fruit label because this is much easier to add and should protect against crazy histogram aggs that tries to create millions of empty buckets.

**Comment by jimczi** [comment]
Closed by #27581

**Comment by synhershko** [comment]
This still seems to happening, opened as https://github.com/elastic/elasticsearch/issues/35896
