### ISSUE TITLE
[CI] Vagrant centos packaging tests fail reliably

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#26017]
This seed reproduces it locally for me

```
gradle clean :qa:vagrant:vagrantCentos6#packagingTest -Dtests.seed=26CF6DE57E3F0087
```

Error message looks similar to https://github.com/elastic/elasticsearch/issues/25295 - but that might not be the true underlying issue I assume

**Comment by nik9000** [comment]
I confirmed locally. I'll have a look soonish. I think it is a similar problem.

**Comment by nik9000** [comment]
The problem is that we tried to upgrade to the rpm named `elasticsearch-6.0.0-SNAPSHOT.rpm` but the rpm that we actually had is `elasticsearch-6.0.0-beta1-SNAPSHOT.rpm`.

**Comment by nik9000** [comment]
@rjernst do you have an opinion on how we should fix this? The bwc builds don't pick up the artifact because it is build with `-beta1` in the version. The bwc build doesn't notice this and when the upgrade tests go to run they don't have anything to upgrade from. The way I see it we could either:
1. Remove the alphas and betas from the upgrade tests again.
2. Fix the bwc build to pick up the alphas and betas correctly and convince the upgrade tests to pick them up as well.

Both are fairly simple, but would require scanning the suffix into the build's Version class or building another list in the root build file, this time without alphas trying to stand in for unreleased versions.

**Comment by rjernst** [comment]
I guess making the gradle Version class understand alpha/beta/rc is necessary. But we should keep it as "only have a alpha/beta/rc in versions list if it is the last", ie snapshot of unreleased major version.
