### ISSUE TITLE
Query cache misses for identical queries

### ISSUE THREAD

**Issue by kewats** [elastic/elasticsearch#26022]
I am working on tuning performance of some of my queries. As a test, I am running the same query over and over again and understand the query_cache stats.

I see that even for the same query, miss_count increases. My index data is really small and am happy to keep all of it in memory. Is there something that can help get rid of cache misses in such cases?

```
"indices" : {
    "design" : {
      "primaries" : {
        "query_cache" : {
          "memory_size_in_bytes" : 18120,
          "total_count" : 7872,
          "hit_count" : 2880,
          "miss_count" : 4992,
          "cache_size" : 144,
          "cache_count" : 144,
          "evictions" : 0
        }
      },
      "total" : {
        "query_cache" : {
          "memory_size_in_bytes" : 18120,
          "total_count" : 7872,
          "hit_count" : 2880,
          "miss_count" : 4992,
          "cache_size" : 144,
          "cache_count" : 144,
          "evictions" : 0
        }
      }
    },

```

**Comment by jpountz** [comment]
What version is it and what do the queries that should be cached but are not look like?
Is the index read-only?

**Comment by kewats** [comment]
I am using version 5.4.2. My index is infrequently updated, say once in a day.

Here is what my query looks like:

```
“size”: 10,
“from”: 0,
“query”: {
	“bool”: {
		“filter”: {
			“nested”: {
				“query”: { … },
				“path”: “childProperties”,
				“inner_hits”: {
					“name”: “attribute”,
					“from”: 0,
					“size”: 1
				}
			}
		}
	}
},
“_source”: [ … ],
“sort”: { … },
“aggregations”: { … }

```

**Comment by jpountz** [comment]
I am assuming that you are seeing cache misses, but also cache hits? If this is actually the case then it is due to the query cache policy to not cache queries on small (less than 10k docs) segments that are unlikely to live long. There is nothing to worry about, such small segments are fast to search anyway.

If your index only gets updated once a day, you could consider running a force-merge with `max_num_segments=1` after the update, which will merge all your shards down to 1 segment. This will help reduce cache misses, but this is anecdotal. It will especially help because few large segments are more efficient to search.
