### ISSUE TITLE
Avoid creating indexes with UID's that begin with "-" (a dash)

### ISSUE THREAD

**Issue by guhcampos** [elastic/elasticsearch#26031]
ElasticSearch index UID's include the dash as a valid character, and that seems to work fine on the ES side, which is the reason I'm not considering this a bug.

This behavior, however, might be a major nuisance for a system administrator, as most shells will have trouble dealing with the dash as the first character of a directory name.

A classical example is trying to run any linux command in the parent directory using the "named-with-a-dash" dir as a parameter:

```
  #  ls
  -0lMGzGiTga5-f39nAug1w
  # ls -0lMGzGiTga5-f39nAug1w
  ls: invalid option -- '0'
  Try 'ls --help' for more information.
  # cd -0lMGzGiTga5-f39nAug1w
  -bash: cd: -0: invalid option
  cd: usage: cd [-L|[-P [-e]]] [dir]
```

For the aware admin, this is easy to circumvent: 

```
# ls -- -0lMGzGiTga5-f39nAug1w
1  2  4  _state
# ls ./-0lMGzGiTga5-f39nAug1w
1  2  4  _state
```

However it can lead to unforeseen consequences on all sorts of shell scripts and general confusion if the person is not mindful of this.

**Comment by jasontedor** [comment]
The need to mess around with these on the command line is rare (what are you doing?), I don't see the need to make a change here.

**Comment by colings86** [comment]
We discussed this in our FixItFriday meeting and we agree that we don't think there is anything that needs to change here. We do not advise touching the index directories as this can easily lead to corruptions and other issues, there is a workaround, and this is no different to any other folder on the file system which may need to be dealt with carefully due to limitations of the shell (e.g. spaces in a directory name)
