### ISSUE TITLE
Upsert using index aliases

### ISSUE THREAD

**Issue by jhberthemet** [elastic/elasticsearch#26060]
We're using 1.7.5 for now but we are migrating to 5.5 soon. We use index aliases to update our mapping, usually to add a new field, it does not happen often and data is to be kept between 1 and 5 years depending on the deployment.

A document is large (emails/chats) so we use partial upserts to update status, add comments or metadata. When a new mapping is applied using a new index on the alias, and using upsert on an existing document in the previous index, the delta is created to the new index, the old version of the document still exists in the old alias and only the new data is in the new index. If we count the data, using _id:* for example we have extra results too.

When searching we can still find the doc using old data, such as status=processing as well as status=done.
Deletes works fine, but upserts don't work as we'd expect.

When using upsert, I obviously don't know if the document already exist and in which index it may exist. Is there a solution so that upserting a document would move the data to the newest index?

**Comment by danielmitterdorfer** [comment]
Hi @jhberthemet, we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) instead. Thank you!

**Comment by jhberthemet** [comment]
Hi @danielmitterdorfer, to me that's a bug, upsert should update the existing document, not create a new one with the delta.

**Comment by danielmitterdorfer** [comment]
>  Deletes works fine, but upserts don't work as we'd expect.

How does it work at the moment and what do you expect? Can you please share a self-contained example that reproduces the problem you're experiencing?

> Is there a solution so that upserting a document would move the data to the newest index?

To me this sounds like a second topic? I'm not sure I understand you correctly but in the update case the document will stay in the same index. So I don't think it's possible what you describe.

**Comment by jhberthemet** [comment]
I'll work on a full example an provide it here. For now, according to the documentation it should "reindex" the document, to me that should make it go to the newest index:
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html
> Note, this operation still means full reindex of the document, it just removes some network roundtrips and reduces chances of version conflicts between the get and the index. 

Here is the scenario. I have "EmailIndex" alias with "EmailIndexV1" index that contains:
{
_id=42,
status=processing,
text=hello,
}

I create a new index "EmailIndexV2" (with a different mapping) and send something like:
POST EmailIndexV2/email/42/_update
{
    "doc" : {
        "status" : "done"
    },
    "doc_as_upsert" : true
}

The problem is that if I use the alias instead of an index name I get an error.

**Comment by danielmitterdorfer** [comment]
> it should "reindex" the document, to me that should make it go to the newest index:
>> Note, this operation still means full reindex of the document, it just removes some network roundtrips and reduces chances of version conflicts between the get and the index.

Thanks for the explanation. Now I can see from where you're expectation is coming. I think the wording in the documentation is not accurately describing [what's going on](https://github.com/elastic/elasticsearch/blob/3518e31/core/src/main/java/org/elasticsearch/action/update/UpdateHelper.java#L85-L99):

* Either the alias is pointing to the "old" index (`EmailIndexV1`), then the upsert would find the document, and [update it](https://github.com/elastic/elasticsearch/blob/3518e31/core/src/main/java/org/elasticsearch/action/update/UpdateHelper.java#L214-L241)
* Or the alias is pointing to the "new" index (`EmailIndexV2`), then the upsert would *not* find the document (it's looking in `EmailIndexV2`) and hence it would create a *new* document and insert it.

So "reindexing" refers here to the fact that a new document is added to the (same) index instead of replacing the same document in-place in the index (which is impossible in Lucene). However, this behavior is intentional. The usual procedure if you change the mapping is to use the [reindex API](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/docs-reindex.html) that has been introduced in 2.x which really does what you want.

**Comment by jhberthemet** [comment]
The thing is that in the prepare() phase:
https://github.com/elastic/elasticsearch/blob/3518e31/core/src/main/java/org/elasticsearch/action/update/UpdateHelper.java#L73

we're doing a search on the current index, would it be possible to do a search on on all the indexes of the alias? Afterall the regular search is working like that, here it's a search by id so it should be fast. Upsert behavior would be more consistent.

**Comment by danielmitterdorfer** [comment]
While it may look simple, getting such an operation right in a distributed system like Elasticsearch is an extremely tough challenge. The key problem is that you have to execute two operations: One delete in the old index and one insert in the new index and all this has to work in the face of all sorts of failures (different network failures , failing nodes, long GC pauses, etc. etc.) or otherwise we'd risk data loss (see also our [docs on replication](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/docs-replication.html)).

We've already put in a ton of work into [getting this right for just a single shard](https://github.com/elastic/elasticsearch/issues/10708). I don't say that it's impossible but I think it is more complex than it seems.

**Comment by jhberthemet** [comment]
You're right, and in the end that's not really the root of my problem. The problem is that upsert is creating a new document whereas one already exists in an other index.

Would it be possible for upsert to keep updating the exiting document in the other index? I'd propose that if you upsert on the alias (that is not possible today) it will search for the doc in all indexes and update in the found index or insert in the latest. Whereas upsert in a particular index would work like it is today.

That way we'll be able to run a reindex in the background while keep a consistent index.

**Comment by danielmitterdorfer** [comment]
I really hear your need. However, I think there are a couple of problems that prevent to allow aliases in upsert operations:

1. An id can only be unique within an index. What happens if we find multiple documents with the same id?
2. If we do not find any document, we need to insert it into an index. You propose to use the "latest" one but Elasticsearch has no notion of "latest index". Yes, there are use-case specific conventions for index names (like date patterns for the logging use-case) but how would we decide in the general case of multiple matching indices, e.g. three indices with the name "A", "B" and "C" which is the right one?

To me all this hints that Elasticsearch is not the right component in your architecture to handle this situation. The notion of a "latest" index is something that's application specific and the same goes for which documents we should touch. I think you'd be better off with less indices and either full or partial reindexing of your data.

**Comment by jhberthemet** [comment]
1. I would consider that as an error and an improper usage of upsert on alias and throw an exception. What would happen for a search on the alias, would it return two documents with the same _id?
2. When I said latest, I meant the one the alias is currently pointing to, like it's done for an index operation on an alias.

Everything else is working well with Elasticsearch for us, I don't think the fix on upsert is that complicated compared to what ES can already do.

**Comment by jhberthemet** [comment]
Any news, is it possible to reopen this issue?
