### ISSUE TITLE
Merge High/Low Level REST client functionalities

### ISSUE THREAD

**Issue by sherry-ger** [elastic/elasticsearch#26086]
When using the high level REST client, one would need to create a low level REST client to manage connection options.  The high level client is only used to serialize and deserialize JSON requests and responses.  It seems the high level REST client is an aux pack to the low level REST client.  It is cumbersome to use two "clients" (high/low).  It would be simpler just to have a single client (encompassing high and low) to create connections, query, index, and make some cluster wide calls like cluster health.

**Comment by dadoonet** [comment]
Because of the HL transitive dependencies we have today, I really like having a low level one much lighter.
So for now, I'm not a fan of this proposal.

Once we won't be depending on core anymore, I'd be +1 for this.

My 2 cents

**Comment by javanna** [comment]
Merging them is not an option, as there are users using low-level client only. I think the problem here is that some users are confused by having to do:

```
RestClient lowLevelClient = RestClient.builder(new HttpHost("localhost", 9200));
RestHighLevelClient client = new RestHighLevelClient(lowLevelClient);
```

and then having to close the low level one. We could for instance make the high level client `Closeable` and have it close the internal low level client instance, so that the close part is less confusing.

Also, we could have a specialized constructor that allows to do the following:

```
RestHighLevelClient client = new RestHighLevelClient(new HttpHost("localhost", 9200);
```

We could internally create the low-level client instance and feed it with the provided hosts. That said, whenever any http setting has to differ from the default values, like timeouts, authentication etc. a properly configured low level client instance will need to provided. That is because we don't want to  hide the fact that the high level client works on top of the low level client, which would also require to add more abstraction layers that complicate things and become hard to maintain.

**Comment by tlrx** [comment]
I agree with Luca's comment. If having two clients to manage is confusing then we can provide a closing method in the high-level client that takes care to close the underlying low-level client, but I'm against merging the code of the 2 clients together for the same reasons already mentioned.

I also think that providing a specialized constructor would make things even less confusing for people using dependency injection frameworks like Spring (only 1 bean to declare, and its lifecycle can be managed by the framework itself), but maybe we should wait a bit for more feedback before adding such ctor.

**Comment by dadoonet** [comment]
@tlrx I agree that having 2 clients has been a bit painful when I updated the spring-elasticsearch project (https://github.com/dadoonet/spring-elasticsearch/pull/123) as I had to reference the low level one with something like:

```java
<elasticsearch:rest-high-level-client id="esHighLevelClient" client="esClient"/>
```

or

```xml
	<bean id="esClient"
		class="fr.pilato.spring.elasticsearch.ElasticsearchRestClientFactoryBean" >
		<property name="esNodes">
			<list>
				<value>localhost:9200</value>
			</list>
		</property>
	</bean>

	<bean id="esHighLevelClient"
		  class="fr.pilato.spring.elasticsearch.ElasticsearchHighLevelRestClientFactoryBean" >
		<property name="client" ref="esClient" />
	</bean>
```

So definitely I'm +1 for having the high level client as a Closeable one with a way to build it more easily.

I just wonder why actually we don't have:

```java
public class RestHighLevelClient extends RestClient {
   // 
}
```

Because actually the RestHighLevelClient is like an extension of the LowLevel one.

**Comment by tlrx** [comment]
@dadoonet Yes, I expect Spring users to do something like this. To be honest I don't see this as painful because it is very common to define a low level object (like a data source) that is used by another one at a higher level in the application layers (like a DAO or something). I also think that most user will define custom timeout values for their production platforms.

Having the `RestHighLevelClient` extending `RestClient` will confuse things I think. This will expose `bulk()` or `search()` domain specific methods along with `buildUri()` or `performRequestAsync()` methods and I don't think we want to do that. `RestHighLevelClient` is not an extension of `RestClient`, it just operates at a different level.

**Comment by javanna** [comment]
This may just be a naming issue after all. I see the high-level client as a wrapper more than an extension. They should be two separate objects, and high-level uses/depends on low-level. The concept is: low-level handles connections and sends requests, while high-level takes care of requests marshalling and responses un-marshalling.

**Comment by dadoonet** [comment]
At the end of the day, I often have to use the high level methods and the low level methods when something is not exposed yet by the high level client (create an index for example).

For now I write something like:

```java
RestClient lowLevel = // init
RestHighLevelClient highLevel = // init

lowLevel.performRequest("PUT", "/index");
highLevel.search(new SearchRequest());
lowLevel.performRequest("DELETE", "/index");
```

So I need to have access to the Low Level client. Which means that if we don't extend the Low Level client, then we need to provide a getter to have an access to the low level one anyway.

Extending the low level client would simplify this a bit:

```java
RestHighLevelClient client = // init

client.performRequest("PUT", "/index");
client.search(new SearchRequest());
client.performRequest("DELETE", "/index");
```

I know we are exposing "more advanced" methods but that's ok IMO.

Note: I'm just expressing my thoughts here. One way or another is fine to me.

**Comment by cbuescher** [comment]
> So I need to have access to the Low Level client.

This makes sense, I think keeping track of both LL and HL client references complicates things a bit. I think a getter would be better a better solution than `RestHighLevelClient extends RestClient` though, for the same reasons @tlrx and @javanna mentioned. Maybe another option would be to make `RestClient` an interface that only exposes the functionality that the HL client also needs and then have HL client implement that interface and delegate to the LL client implementation (e.g. for `performRequest()` like in your example). Or even without the interface, by just adding those delegating methods that are needed to the HL client as well?

**Comment by dadoonet** [comment]
> Or even without the interface, by just adding those delegating methods that are needed to the HL client as well?

I think that would be a very good compromise.
