### ISSUE TITLE
HTTP/REST Client API compatibility with Abstract Client Interface

### ISSUE THREAD

**Issue by robertoandrade** [elastic/elasticsearch#26117]
I'm not sure why the decision to make the REST Client incompatible with the existing Abstract Client Interface that both Transport and Node Clients abide by so you can easily switch clients depending on what protocol/transport layer you want to use, but have since found a [neat project](https://github.com/jprante/elasticsearch-client-http) that tries to make that a reality and was wondering what the maintainers motivations were to expose a similar but different API for the REST Client

In the project mentioned above, it exposes HTTP as another option in addition to the REST/Transport/Node clients but is contractually aligned with the last 2 which the REST one is not, surprisingly.

Is there any particular reason why that is so and would there be any interest in incorporating such HTTP Client as part of the main set of clients shipped with ES similarly to the high/low level REST Client?

**Comment by nik9000** [comment]
My understanding (@javanna is more authoritative here) is that we intentionally wanted to break from the `Client` interface because it was fairly confusing (#9201). For me it'd be useful to have something that implements the `Client` interface for testing and migrating but I understand the logic of wanting the break with the interface. I believe we haven't implemented that shim layer to the `Client` interface because of the time it'd take, because it'd be incomplete as the high level client doesn't have all of the `Client` features, and we believe that it is *probably* a good idea to migrate away from `Client` anyway.

Anecdotally, as much as I'm comfortable with the `Client` interface because I'm familiar with it, I'm a long way away from loving it. It feels very large and ceremonial to me.

**Comment by javanna** [comment]
thanks @nik9000 for the concise yet complete explanation. Have a look at #9201 to see some more opinions and reasons behind the decisions we made. We decided not to implement the `Client` interface for the reasons stated above, but to help users migrate from the transport client we have kept the same request and response objects. Have a look at the [migration guide](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/master/java-rest-high-level-migration.html) to know more.
