### ISSUE TITLE
NoClassDefFoundError: org/apache/logging/log4j/core/config/Configurator

### ISSUE THREAD

**Issue by sschwell** [elastic/elasticsearch#26123]
Version: 5.5.1

We use slf4j for logging so I tried [this](https://logging.apache.org/log4j/2.0/log4j-to-slf4j/index.html) as a bridge. It works just fine for most cases, except for during testing where I use an embedded node, which throws the above exception.

I realize that embedded node is ["not supported"](https://www.elastic.co/blog/elasticsearch-the-server), but it is just too useful for automated testing to give it up without a fight.

So this difficulty lives at the crossroads of 2 debatable decisions: abandoning slf4j and refusing to support embedded nodes even for testing. And these decisions have been debated, e.g. #19415, #21011, #22671.

@ctron 's cluge mentioned in #19415 seems to be the best solution available at the moment. Perhaps we should reconsider using slf4j, or come up with a better solution. This does seem to be a common use case.

**Comment by nik9000** [comment]
We've been slowly migrating away from embedded testing where possible because it doesn't consistently give the same results as starting the server. I know in a lot of cases it is close enough but it has bitten us enough that we just don't think it is worth it. I also found it super useful for testing and fought the fight and lost.

I know that is super paternalistic. You are a professional and can decide for yourself if embedded nodes work for you. But since we've been burned by it we're not going to make changes to make it easier because they are extra effort to support a behavior we've been burned by in the past. It feels like the worst kind of waste of time.

If you have a working kluge then great. The nature of such kluges is that they are going to break one day without warning because we don't test them.
