### ISSUE TITLE
HL Rest Client 6.0.0-beta1 is not full compatible with 5.5.1

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#26142]
Let's say you have a 5.5.1 cluster running. You want to run a QueryString query on it with:

```java
SearchResponse response = hlclient.search(
  new SearchRequest("foo").source(
    new SearchSourceBuilder().query(
      QueryBuilders.queryStringQuery("bar"))));
```

It fails because 6.0.0-beta1 QueryString object has now a `type` field which a 5.x version can not read:

```
ElasticsearchStatusException[Elasticsearch exception [type=parsing_exception, reason=[query_string] query does not support [type]]]
	at __randomizedtesting.SeedInfo.seed([1454848CA14180A5:1ED18A07CB044C51]:0)
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177)
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:522)
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:498)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:405)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:378)
	at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:319)
```

Ideally the JSon serialization of those objects should take care of this compatibility and be aware of the version currently running.

If we don't fix it, it will mean that the HL Rest client is somehow tight to the cluster version we are running.

**Comment by dadoonet** [comment]
Also got a similar type of error with:

```
            SearchResponse response = elasticsearchClient.search(new SearchRequest("foo").source(
                    new SearchSourceBuilder()
                            .size(0)
                            .aggregation(AggregationBuilders.terms("folders").field("path.virtual.tree"))));
```

Which gives once executed on a 5.5.1 cluster:

```
	Suppressed: org.elasticsearch.client.ResponseException: GET http://127.0.0.1:9200/fscrawler_test_subdirs_deep_tree/_search?typed_keys=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&search_type=query_then_fetch&batched_reduce_size=512: HTTP/1.1 500 Internal Server Error
{"error":{"root_cause":[{"type":"aggregation_execution_exception","reason":"Invalid term-aggregator order path [_key]. Unknown aggregation [_key]"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"fscrawler_test_subdirs_deep_tree","node":"SvuZnFMQTKC37-QoAdB0ww","reason":{"type":"aggregation_execution_exception","reason":"Invalid term-aggregator order path [_key]. Unknown aggregation [_key]"}}]},"status":500}
```

**Comment by javanna** [comment]
What is the purpose of using the 6.0 client to communicate with a 5.5 cluster? I think that is because we haven't released yet 5.6 hence the 5.6 client is not out yet?

In general, when upgrading a cluster one would upgrade all the nodes and then the client last, so forward compatibility is important, which is the opposite: 5.6 client that talks to 6.x cluster. Forward comp also works up to a certain point, the client cannot know about breaking changes made and new APIs that are added in 6.x.

I suspect that if you try the same with any of our language clients, you would hit the same problem. A new client version is usually released with each major version of Elasticsearch, to address breaking changes and make the client 100% compatible with the new major.

The purpose of the high-level client is not building a client that works against any version of Elasticsearch (that is rather the purpose of the low-level client). The expectation is that version x.y of the high-level client works against w.z version of Elasticsearch where x==w (same major version) and y<=z (client in lower or same minor version). Things should also work with y>z although it is not a situation that we test nor strongly guarantee, as it doesn't make much sense to upgrade a client before the application that it talks to.

**Comment by dadoonet** [comment]
> What is the purpose of using the 6.0 client to communicate with a 5.5 cluster?

Let say I'm building an application which communicates with an elasticsearch 5.6 cluster.
I'm using the 5.6 Rest Client. So good so far.

Then, I know that elasticsearch 6.1 has been released and I want to prepare my application to be ready for it.
So, I take the 6.1 Rest Client, update my application and deploy it in production. As for now my cluster is still 5.6.

I'm now ready to upgrade my 5.6 cluster to 6.1.

> it doesn't make much sense to upgrade a client before the application that it talks to.

But here is my real use case. I'm building a tool which can be used with whatever version of elasticsearch the end user wants to use or have in production already. My tool does not embed elasticsearch which is may be the problem here. So I'm expecting that the REST Client I'm using to be able to automatically adapt itself to the version I'm using.

Now I understand why it is so complicated to do it here as we depend on elasticsearch core objects and not on a public API (rest api specs) which is independent from the implementation.
Also we don't use versions in our objects like package name "o.e.api.v5.SearchRequest".
The REST endpoints are not using any version either like http://localhost:9200/v5/_search and http://localhost:9200/v2/_search... I'm calling that "a la Twitter" versioning system: https://api.twitter.com/1.1/search/tweets.json (note the API spec version in the URL).
Which makes all that thing super hard to solve IMO.

I'm fine saying that we don't want to complicate things. But at least we can't say something like:

> The High Level Client is backwards compatible but can only communicate with Elasticsearch version 5.5 and onwards.

(from https://www.elastic.co/guide/en/elasticsearch/client/java-rest/6.x/java-rest-high-compatibility.html)

I just proved I think that the 6.0 client is not "fully" backwards compatible with Elasticsearch version 5.5.
So at the very least if we don't want or if we can't solve that issue, we need to say that a REST client major version is only compatible with the same major version of an elasticsearch cluster.

**Comment by javanna** [comment]
As I said before, the client should be the last piece to be upgraded when a cluster is upgraded and not the first like in your usecase. Ppgrading the app in production to prepare for a cluster upgrade is not the way to do it. Things should be tested on the new major version first, with both sides upgraded, in a test/acceptance environment. Then the move should be done in production, upgrading the client last.

This is also the sentence in the docs that's right after what you mentioned above:

>  It is recommended to upgrade the High Level Client when upgrading the Elasticsearch cluster to a new major version, as REST API breaking changes may cause unexpected results, and newly added APIs will only be supported by the newer version of the client. The client should be updated last, once all of the nodes in the cluster have been upgraded.

What you encountered is in fact a change that is causing an incompatibility, which requires upgrading, probably same happens if you try the 5.6 client against 6.0.0-beta1 with the same request.

We can certainly clarify what backwards compatible means in that sentence, although I thought that the following sentence woulda already clarify things. What I meant is that we guarantee bw comp within the same major version, and we do it as a best-effort between different majors (if there are no breaking changes involved for sure everything works). The case where the client is in a lower version compared to the cluster is uncommon, so if you go that route, you may run into problems and there isn't much that we can do about it.

We never meant nor promised to build a conversion layer so that the client would automagically work against every Elasticsearch version. None of our language clients do. Users will still have to upgrade their clients, but they will only have to do it at least once per major version, which is reasonable.

**Comment by dadoonet** [comment]
Let's close this issue then as the behavior is expected.

**Comment by javanna** [comment]
good call @nik9000 I am on it, will open a PR later today.

**Comment by javanna** [comment]
This should work @dadoonet . Just not sure what it buys. I still think that upgrading the client last is the best way. I guess I also would need to have a better feeling of how many of these incompatibilities there are, to understand whether it's just a few edge cases or a more serious problem.

**Comment by frekele** [comment]
Any prediction for elasticsearch 5.6? We waiting to be able to use the RestHighLevelClient.

Thak you.

**Comment by cbuescher** [comment]
@frekele great to hear. And sorry, we don't give dates.

**Comment by s1monw** [comment]
@frekele if you look at our previous release cycles you should get a pretty good estimate when it will come. we just don't give promises or anything along those lines.
