### ISSUE TITLE
[CI] "s3 repository can be registered" test fails intermittently

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#26240]
`{yaml=repository_s3/20_repository/S3 repository can be registered}` failed on the CI in: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.5+intake/21/console.

Reproduce command:

```
gradle :plugins:repository-s3:integTestRunner -Dtests.seed=7A2029E35B0854DD -Dtests.class=org.elasticsearch.repositories.s3.RepositoryS3ClientYamlTestSuiteIT -Dtests.method="test {yaml=repository_s3/20_repository/S3 repository can be registered}" -Dtests.security.manager=true -Dtests.locale=pt -Dtests.timezone=America/Puerto_Rico
```
The test times out as seen in:

```
  > Throwable #1: java.lang.RuntimeException: Failure at [repository_s3/20_repository:4]: listener timeout after waiting for [30000] ms
   > 	at __randomizedtesting.SeedInfo.seed([7A2029E35B0854DD:F2741639F5F43925]:0)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:348)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:330)
   > 	at java.lang.Thread.run(Thread.java:748)
   > Caused by: java.io.IOException: listener timeout after waiting for [30000] ms
   > 	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:660)
   > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:219)
   > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:191)
   > 	at org.elasticsearch.test.rest.yaml.ClientYamlTestClient.callApi(ClientYamlTestClient.java:158)
   > 	at org.elasticsearch.test.rest.yaml.ClientYamlTestExecutionContext.callApiInternal(ClientYamlTestExecutionContext.java:161)
   > 	at org.elasticsearch.test.rest.yaml.ClientYamlTestExecutionContext.callApi(ClientYamlTestExecutionContext.java:93)
   > 	at org.elasticsearch.test.rest.yaml.section.DoSection.execute(DoSection.java:221)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:346)
   > 	... 38 more
```

Cannot reproduce locally.

**Comment by tlrx** [comment]
I'm working on a fix.

**Comment by Delostik** [comment]
this also happens on v6.1.3 
I think it's a common failure on many versions.

**Comment by tvernum** [comment]
This just happened for HDFS repository as well, and I guess the underlying cause is not repo specific

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.2+multijob-unix-compatibility/os=centos/125/console
```
05:20:49 ERROR   30.8s | RepositoryHdfsClientYamlTestSuiteIT.test {yaml=secure_hdfs_repository/30_snapshot/take snapshot} <<< FAILURES!
05:20:49    > Throwable #1: java.lang.RuntimeException: Failure at [secure_hdfs_repository/30_snapshot:8]: listener timeout after waiting for [30000] ms
```

I checked the node's log, it has nothing related to this request. It ends with:
```
[2018-02-21T06:20:48,859][INFO ][o.e.r.RepositoriesService] [node-0] put repository [test_repo_hdfs_1]
[2018-02-21T06:20:48,948][INFO ][o.e.r.RepositoriesService] [node-0] delete repository [test_repo_hdfs_1]
[2018-02-21T06:20:49,021][WARN ][o.e.r.h.HdfsRepository   ] Hadoop authentication method is set to [SIMPLE], but a Kerberos principal is specified. Continuing with [KERBEROS] authentication.
[2018-02-21T06:20:49,032][INFO ][o.e.r.RepositoriesService] [node-0] put repository [test_repo_hdfs_1]
[2018-02-21T06:20:49,122][INFO ][o.e.r.RepositoriesService] [node-0] delete repository [test_repo_hdfs_1]
```
The "test_repo_hdfs_1" repo is referenced exclusively in `20_repository_delete.yml`

**Comment by tlrx** [comment]
Thanks @tvernum. The underlying cause - at least for s3 and other cloud based plugins - is that a repository creation with a `verify` flag to false is still executing some remote accesses like verifying the bucket existence. If the network is not available or the remote host not reachable the test times out.

I plan to change the repository verification action so that it does *actually* nothing if the `verify` flag is set to false and so that it always does something if the flag is set to true (because today, read only URL repository are not verified for reads) but I had to hold on this work recently because of CI failures.

Also, before doing this change I'd like to have integration tests based on fixtures.

**Comment by bleskes** [comment]
@tlrx is this test failure issue the only place we track this or can we close this one in favour of something that better describes the problem?

**Comment by tlrx** [comment]
This has been fixed by the recent work on the lazy repository initialization in #31606
