### ISSUE TITLE
Index with lots of fields consumes lot of memory

### ISSUE THREAD

**Issue by yiguolei** [elastic/elasticsearch#26244]
One of my index contains about 6000 fields, and I found the field info consumes lots of JVM memory. This is the jmap info:
 num     instances         bytes  class name
   1:       6008442     4577941768  [B
   2:       2792701     4396718000  [J
   3:      35410100     3652501000  [C
   4:      49411788     1581177216  java.util.HashMap$Entry
   5:      35241631      845799144  java.lang.String
   6:       6420067      790259072  [Ljava.util.HashMap$Entry;
   7:      12440681      497627240  java.util.TreeMap$Entry
   8:       6181515      494521200  org.apache.lucene.codecs.lucene410.Lucene410DocValuesProducer$NumericEntry
   9:      17975247      431405928  org.elasticsearch.common.collect.ImmutableEntry
  10:       4846348      348937056  org.apache.lucene.store.NIOFSDirectory$NIOFSIndexInput
  11:      20881305      334100880  java.lang.Integer
  12:       6502117      312101616  java.util.HashMap
  13:       6307597      302764656  org.apache.lucene.index.FieldInfo
  14:       6131061      196193952  java.util.Collections$UnmodifiableMap

You can see, there are 6307597  field infos, because there are about   1000 segments. Every field info contains a hashmap<string,string>， like `{PerFieldDocValuesFormat.format=Lucene410, PerFieldPostingsFormat.format=Lucene41, PerFieldPostingsFormat.suffix=0, PerFieldDocValuesFormat.suffix=0}` these strings consumes lot of memory.

I think we could use a map for one segment to contains these values and in fieldinfo just maintains the pointer to these string values. I will reduce lots of memory.

My version is Elasticsearch 1.7.3 and Lucene version 4.10。 And I have checked Elasticsearch 2.3.3 and Lucene 5.x , it is the same issue.

**Comment by jpountz** [comment]
Field infos are just the tip of the iceberg. I don't think we should try to optimize this. It will add complexity and there will be other issues almost immediately.

**Comment by yiguolei** [comment]
@jpountz 

Why is it just the tip of the iceberg? Is there any other problems or data structures that consumes so much memory?

**Comment by jpountz** [comment]
FieldInfos are one thing, but there are other resources that we need per field. For instance doc values need some per-field metadata in memory (such as the `Lucene410DocValuesProducer$NumericEntry` class that you saw), postings and doc values need to maintain open index inputs, we need to load the terms dictionary for term-based fields and the BKD tree index for point-based fields, etc.

Plus there is also information that we need to maintain at the Elasticsearch level because of mappings.

The resource usage that you are seeing is a function of `${num_fields} x ${num_segments}`. You should look into reducing either or both of them, eg. by having fewer shards, force-merging read-only indices if any or modeling documents differently in a way that there are fewer fields at the Lucene level.
