### ISSUE TITLE
Nodes Stats API: indices.recovery.current_as_target always zero

### ISSUE THREAD

**Issue by shoggeh** [elastic/elasticsearch#26298]
**Elasticsearch version: 5.5.2**
**Description of the problem including expected versus actual behavior**:

Monitoring API under /_nodes/stats can provide info about source/target hosts used in recovery process, however `indices.recovery.current_as_target` is always 0, no matter how many ongoing recoveries/relocations/initializations are happening on/to said host. 

I believe these values should be in sync with _source ones.

**Steps to reproduce**:

- Trigger any recovery and observe current_as_source / current_as_target stats (example output from three node setup):

```
$ curl -s 'http://localhost:9200/_cat/recovery?h=source_node,target_node,stage'  | grep -v done$
host1 host2 index
host2 host3 index
host3 host1 index
```
```
$ curl -s http://localhost:9200/_nodes/stats?pretty | jq '.nodes | .[] | {name: .name, target: .indices.recovery.current_as_target, source: .indices.recovery.current_as_source }'
{ 
  "source": 1,
  "target": 0,
  "name": "host1"
}
{
  "source": 1,
  "target": 0,
  "name": "host2"
}
{
  "source": 1,
  "target": 0,
  "name": "host3"
}
```

**Comment by jimczi** [comment]
@ywelsch can you take a look ?

**Comment by ywelsch** [comment]
I've verified this bug. The reason for this behavior is that the stats collection for some of the stats does not work for shards that have not completed their recovery yet (i.e. haven't made it into POST_RECOVERY state), see e.g. `IndexShard.docStats()`. This makes it so that the overall stats collection for that index on that node will be ignored, see https://github.com/elastic/elasticsearch/blob/f0cba4fce5cc41a68e6c2b8fb686ee4e6121ed02/core/src/main/java/org/elasticsearch/indices/IndicesService.java#L310-L313
If you modify the curl request to include only the recovery stats (`http://localhost:9200/_nodes/stats/indices/recovery?pretty`), it will work, but other stats (e.g. `docs`) will break this.

**Comment by percygrunwald** [comment]
This behavior is still present on 7.x

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
