### ISSUE TITLE
should we alter PeerRecoverySourceService.START_RECOVERY request's response not waiting?

### ISSUE THREAD

**Issue by keenbo** [elastic/elasticsearch#26337]
PeerRecoverySourceService.START_RECOVERY(internal:index/shard/recovery/start_recovery)  may be should not use one thread to wait for response ?
Because the request's threadpool is very limit, if one instance recovery many shards(for example 100shards), it may lead one result, all of the thread in threadpol is waiting for START_RECOVERY's response. As we know, recovery generally will cost much time to finish.

**Comment by bleskes** [comment]
@keenbo I'm not 100% sure what you mean. I think you mean that we should move the recovery logic around that request to be async with callbacks rather than the blocking logic. This will be a big effort and we have other plans for this code. That said - it is currently run on the generic thread pool which can spawn all the thread it needs. Also, recovery is throttled both on source and target, so each node will only have a few outgoing requests.  I'm going to close this now. Feel free to reopen and explain more if I misunderstood. Please also include information (with numbers) about your concrete issue if so.

**Comment by keenbo** [comment]
@bleskes ok, thanks
