### ISSUE TITLE
Split doesn't work in painless 

### ISSUE THREAD

**Issue by terancet** [elastic/elasticsearch#26338]
Given the following input string
'http://hostname.domain'
I need to split it into two parts: 'http:' and 'hostname.domain'

However, when executing the following code
```
String urlAsString=String.valueOf(ctx.url); 
ctx.domainAndHost=urlAsString.split('//')[1]
```
I do encounter the following error message
```
{
        "type": "script_exception",
        "reason": "compile error",
        "script_stack": [
          "... ); ctx.domain=urlAsString.split('//')[0]",
          "                             ^---- HERE"
        ],
        "script": "String urlAsString=String.valueOf(ctx.url); ctx.domain=urlAsString.split('//')[0]",
        "lang": "painless",
        "header": {
          "processor_type": "script",
          "property_name": "inline"
        }
      }
```

**Comment by nik9000** [comment]
[`String#split`](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/painless-api-reference.html#painless-api-reference-String) is not whitelisted because it creates dynamic `Pattern` objects internally. Use [`Pattern#split`](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/painless-api-reference.html#painless-api-reference-Pattern) instead like `/\//.split(urlAsString[0])`.

**Comment by terancet** [comment]
@nik9000 , 
Thank you for your response. Appreciate it =)

**Comment by xcl3721** [comment]
hi.
i got same wrong 
i wrote the script filed on the kibana 5.6.1
it's not work  /&/.split(param)

int path = doc['x_name.keyword'].value.indexOf('http');
if(path != -1) {
    int paramstart = doc['x_action.keyword'].value.indexOf('?');
    if(paramstart != -1){
        def url = doc['x_action.keyword'].value.substring(0,paramstart);
        def param = doc['x_action.keyword'].value.substring(paramstart+1);
        if(param != '' && param.indexOf('teset') != -1){
           //def cfrom = param.split(/&/);
           return param;
        }
        return url;
    }else{
        return doc['x_action.keyword'];
    }
}

**Comment by synthesize** [comment]
This issue is closed and a bit old, but I have a question regarding Patterns. For my painless script, the pattern is defined through params. Is it possible for me to create a Pattern object from a string? The url you provided to the API docs lists `String pattern() (java 9)`, however all attempts to use this causes compile errors similar to `Caused by: java.lang.IllegalArgumentException: Unknown call [pattern] with [1] arguments.`

**Comment by rjernst** [comment]
@synthesize Please ask questions on [our forum](https://discuss.elastic.co/c/elasticsearch). We use github for feature requests and confirmed bug reports. Comments on a closed issue are likely to be overlooked or ignored.
