### ISSUE TITLE
Use versioneye gradle plugin to detect outdated deps and incompatible licenses

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#26398]
I came today to the following plugin: https://github.com/stempler/gradle-versioneye-plugin

I'm using it on Maven projects and it really helps to have an overview of outdated jars/plugins and also a list of incompatible licenses.

Example here: https://www.versioneye.com/user/projects/59a174f8368b080052a6aa40

Marking as discuss. Feel free to close it if we don't want to add such a check to elasticsearch. 
Note that we can also add a badge to the README so we can immediately have an overview.

**Comment by dadoonet** [comment]
Hmmm. The plugin is under a MIT license which is may be not compatible...

**Comment by nik9000** [comment]
I think we have the licensing part covered with our licensing tools. I like that ours force you to commit a sha as well to make extra sure no one man in the middles the jar. The out of date versions we've typically handled by having "someone" watch the upstream versions and pay attention to them. We also don't take a super aggressive stance on upgrading versions. We've kept a fairly old ANTLR version for a while because our ANTLR watchers haven't seen anything we really need, for example.

**Comment by jasontedor** [comment]
> We also don't take a super aggressive stance on upgrading versions.

I agree with this, I don't think we need to add this plugin here.

**Comment by dadoonet** [comment]
Thanks for the feedbacks. I'm closing it.
