### ISSUE TITLE
terminated_early is set incorrectly 

### ISSUE THREAD

**Issue by jmlucjav** [elastic/elasticsearch#26408]
**Elasticsearch version** 
Version: 6.0.0-beta1-SNAPSHOT, Build: Unknown/2017-08-13T15:13:28.500Z, JVM: 1.8.0_102

**JVM version**
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

**OS version**
win10, 64b

**Description of the problem including expected versus actual behavior**:
Using a sorted index, terminated_early is set incorrectly to true

**Steps to reproduce**:

1. create the index, with 2 docs
```
curl -XDELETE http://localhost:9200/twitter
curl -XPUT 'localhost:9200/twitter?pretty' -H 'Content-Type: application/json' -d'
{
    "settings" : {
        "number_of_shards" :   1,
        "number_of_replicas" : 0,
        "index" : {
            "sort.field" : "date", 
            "sort.order" : "desc" 
        }
    },
    "mappings": {
        "tweet": {
            "properties": {
                "field1": {
                    "type": "keyword"
                },
                "date": {
                    "type": "date",
                    "format": "yyyy-MM-dd"
                }
            }
        }
    }
}
'
curl -XPOST 'localhost:9200/_bulk?pretty' -H 'Content-Type: application/json' -d'
{ "index" : { "_index" : "twitter", "_type" : "tweet", "_id" : "1" } }
{ "field1" : "value1", "date" : "2017-08-28" }
{ "index" : { "_index" : "twitter", "_type" : "tweet", "_id" : "2" } }
{ "field1" : "value2", "date" : "2017-08-28" }
'
```

2. test early termination when asking for 1 doc
```
curl -XGET 'localhost:9200/twitter/_search?pretty' -H 'Content-Type: application/json' -d'
{
    "size": 1,
    "sort": [ 
        { "date": "desc" }
    ],
    "track_total_hits": false
}
'
```

this returns correctly terminated_early" : true and "total" : -1:

```
{
  "took" : 0,
  "timed_out" : false,
  "terminated_early" : true,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : -1,
    "max_score" : null,
    "hits" : [
      {
        "_index" : "twitter",
        "_type" : "tweet",
        "_id" : "1",
        "_score" : null,
        "_source" : {
          "field1" : "value1",
          "date" : "2017-08-28"
        },
        "sort" : [
          1503878400000
        ]
      }
    ]
  }
}
```

3. ask for 5 docs, no early termination

```
curl -XGET 'localhost:9200/twitter/_search?pretty' -H 'Content-Type: application/json' -d'
{
    "size": 5,
    "sort": [ 
        { "date": "desc" }
    ]
}
'
```

returns 

```
{
  "took" : 0,
  "timed_out" : false,
  "terminated_early" : true,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : null,
    "hits" : [
      {
        "_index" : "twitter",
        "_type" : "tweet",
        "_id" : "1",
        "_score" : null,
        "_source" : {
          "field1" : "value1",
          "date" : "2017-08-28"
        },
        "sort" : [
          1503878400000
        ]
      },
      {
        "_index" : "twitter",
        "_type" : "tweet",
        "_id" : "2",
        "_score" : null,
        "_source" : {
          "field1" : "value2",
          "date" : "2017-08-28"
        },
        "sort" : [
          1503878400000
        ]
      }
    ]
  }
}
```

here "terminated_early" : true, is incorrect, we didn't even ask for it. Hits   "total" : 2 is ok

4. now enable early termination for the same request

```
curl -XGET 'localhost:9200/twitter/_search?pretty' -H 'Content-Type: application/json' -d'
{
    "size": 5,
    "sort": [ 
        { "date": "desc" }
    ],
    "track_total_hits": false
}
'
```

This returns:

```
{                                                     
  "took" : 0,                                         
  "timed_out" : false,                                
  "terminated_early" : true,                          
  "_shards" : {                                       
    "total" : 1,                                      
    "successful" : 1,                                 
    "skipped" : 0,                                    
    "failed" : 0                                      
  },                                                  
  "hits" : {                                          
    "total" : -1,                                     
    "max_score" : null,                               
    "hits" : [                                        
      {                                               
        "_index" : "twitter",                         
        "_type" : "tweet",                            
        "_id" : "1",                                  
        "_score" : null,                              
        "_source" : {                                 
          "field1" : "value1",                        
          "date" : "2017-08-28"                       
        },                                            
        "sort" : [                                    
          1503878400000                               
        ]                                             
      },                                              
      {                                               
        "_index" : "twitter",                         
        "_type" : "tweet",                            
        "_id" : "2",                                  
        "_score" : null,                              
        "_source" : {                                 
          "field1" : "value2",                        
          "date" : "2017-08-28"                       
        },                                            
        "sort" : [                                    
          1503878400000                               
        ]                                             
      }                                               
    ]                                                 
  }                                                   
}                     
```                                

"terminated_early" : true,  is incorrect. And  Hits "total" : -1 is  debatable, we asked for it so it could be ok if set, but it also can be argued that as it had the correct info it should return it?

**Comment by jimczi** [comment]
Thanks @jmlucjav 

We always set `terminated_early` when the top hits collector was able to shortcut the collection even when `track_total_hits` is not disabled. When you set a size of 1 in your request, early termination is activated but it's also activated when you set the size to 5 because your shard contains only 2 documents. In such case the maximum size value is 2 and early termination kicks in on the last document, if you want to test a search without early termination you can send a query with size set to 3. 
`terminated_early` just means that the top hits collection did not check all documents to select the best N. Setting `track_total_hits` to false allows the entire query to terminate early (we don't need to count the total number of docs). Not sure if we should remove the flag when `track_total_hits` is not disabled, this is not a bug I did it conscientiously. IMO this is a good indication that the search was able to use the index sort to shortcut the collection (even if we had to count all documents). @jpountz WDYT ?

**Comment by jpountz** [comment]
>  Not sure if we should remove the flag when track_total_hits is not disabled

I was thinking along the same lines.

I can see why the `terminated_early` flag can be confusing. Sometimes it means results are partial, sometimes it means that we were able to early terminate the collection of top docs but results are complete. It is also not clear to which part of the request it applies: when `terminate_after` is used then it applies to everything while it otherwise it only applies to top docs.

I'm actually wondering about going one step further than your proposal: maybe we should only put `terminated_early` in the response as a way to indicate partial results, ie. when `terminate_after` is used.

> Hits "total" : -1 is debatable, we asked for it so it could be ok if set, but it also can be argued that as it had the correct info it should return it?

In this special case with few matches, we could indeed know the match count. However we don't know it in the general case so I'd rather keep things the way they are today and potentially improve documentation in order to say that we will return `-1` when `track_total_hits` is `false` even if we had to visit all matches. I think this behaviour is also beneficial for testing: you would get similar results with a few documents in your index or millions of documents.

**Comment by EricMCornelius** [comment]
Just hit upon this issue myself.  I agree with @jpountz  that interpreting "terminated_early" as indicating partial results is what most current users expect (given this only happens on "terminate_after" at present), so keeping that behavior intact with index sorting would be very much appreciated.

As for the special case, I imagine there might actually be many situations where users want to know if they're seeing a complete or partial set of hits.

Granted, I believe this is actually the same as a client setting `hits.total = (query.size == hits.hits.length) ? hits.hits.length : -1`

**Comment by jmlucjav** [comment]
I just realized that my email was not public at the time I opened this ticket. Is the pioneer program still on? do I need to do something?

**Comment by markwalkom** [comment]
If you want to reach out to us (community@elastic.co) we will make sure the things that need to happen happen :)
