### ISSUE TITLE
feature request for  reindex plugin without downtime ,can process delete or update

### ISSUE THREAD

**Issue by sshling** [elastic/elasticsearch#26466]
- reindex  without downtime  ,while doing reindex by the reindex plugin, at the same time ,the ES cluster can process delete and update, at last ,remove old index,keep new index

**Comment by dakrone** [comment]
This feature request is an interesting idea but since its opening we have
not seen enough feedback that it is a feature we should pursue. We prefer
to close this issue as a clear indication that we are not going to work on
this at this time. We are always open to reconsidering this in the future
based on compelling feedback; despite this issue being closed please feel
free to leave feedback on the proposal (including +1s).
