### ISSUE TITLE
Provide a way for plugins to implement new rescore builders 

### ISSUE THREAD

**Issue by nomoa** [elastic/elasticsearch#26469]
While working on a plugin I found that implementing a custom Rescorer would allow me to address issues that I cannot address with the default QueryRescorer : 
- Allow some performance optimizations for specific queries provided by the plugin (very specific bulk scoring operations)
- Maybe add some code to support replacing the initial score, there are no easy ways to do this right now
- And certainly other use cases

While digging into the code I found that most of the code seems ready to accept multiple rescorer implementations but sadly the SearchPlugin does allow me to specify custom RescoreBuilders.

Are there any objections/comments into providing such extension point? I'm willing to work on this if there are no objections.

For more contexts:
we are working on a learning to rank plugin (very similar to the one provided by solr). Decision trees is one the ranker we provide and @Ebernhardson made a nice proof of concept that we could improve evaluation time up to to 5x if we could do bulk scoring.
Concerning the issue of not being able to easily replace query_score, I can (I think) workaround my problem with a custom lucene query to normalize scores but putting this code into the rescorer sounds more natural to me.

**Comment by cbuescher** [comment]
Hi @nomoa,
maybe this PR already solved your needs? https://github.com/elastic/elasticsearch/pull/26368 
It has been merged fairly recent and I don't know to which extend it might help in your case, but it seems to contain an example rescore plugin that you might want to take a look at. I'll label this with "feedback needed" because it would be great to hear if you can work with that. If thats the case also please feel free to close this issue, otherwise maybe you can come back with more information whats missing.

**Comment by nomoa** [comment]
@cbuescher yes this exactly what I need, sorry for the noise I was looking at the 5.x code base.
Thanks!
