### ISSUE TITLE
add/remove alias timeout

### ISSUE THREAD

**Issue by chilingpan** [elastic/elasticsearch#26477]
**Elasticsearch version** (`bin/elasticsearch --version`): 5.4.0

**JVM version** (`java -version`): 1.8.0_131

**OS version** (`uname -a` if on a Unix-like system): Linux es-master-3437466560-sz82h 3.10.0-514.16.1.el7.x86_64  #1 SMP Sun Apr 16 03:27:14 UTC 2017 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
We use Java API to add/remove aliase: client.admin().indices().prepareAliases().removeAlias(preIndex, indexAlias).Alias(newIndex, indexAlias).execute().actionGet();
This operation timeout quite often. 
The ES cluster has 3 master nodes, 2 client nodes, and 12 data nodes. There are about 3500 indices.

**Steps to reproduce**:
 1. create an alias for a index
 2. create a new index
 3. remove the alias to the old index and add alias to the new index

**Provide logs (if relevant)**:
org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: failed to process cluster event (delete-index [[computecapa-2017.08.31.08.00/yLyd8R7aT4Se5t1bRgOd3A]]) within 30s
    at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.lambda$null$0(ClusterService.java:254) ~[na:na]
    at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_31]
    at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.lambda$onTimeout$1(ClusterService.java:253) ~[na:na]
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) ~[elasticsearch-5.3.2.jar:5.3.2]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_31]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_31]
    at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_31]

**Comment by jasontedor** [comment]
This is a delete index request that failed to process before the master timeout (30 seconds by default), not an alias update. You can set the `master_timeout` on the REST API, or the `masterNodeTimeout` on the transport API to adjust this. However, note that this only treating the symptoms of the problem, not treating the actual problem. The actual problem is: your cluster state update is taking thirty seconds to process, this is too long. You should fix that. 

We are not going to remove a timeout here, cluster state updates are single-threaded, we can not block the entire processing pipeline forever for one task, the other tasks in the pipeline (nodes leaving and joining, failing shards, creating indices, etc.) are too important. 

Right now we can not treat this as a bug in Elasticsearch, it's a problem on your side to investigate; it usually boils down to underpowered master nodes, too large of a cluster state, etc. For general questions, we ask that you use the [forum](https://discuss.elastic.co). We reserve GitHub for verified bug reports and feature requests.
