### ISSUE TITLE
Range query on integer field is failing if value is float and placed inside double quotes

### ISSUE THREAD

**Issue by amver7** [elastic/elasticsearch#26471]
Elasticsearch version : elasticsearch 5.4.1

Plugins installed: [codesearch extension (for visualstudio.com)]

JDK version : 1.8.0_144
JRE version : 1.8.0_144

OS Version : Windows 10

DESCRIPTION :
If a range query is done on an integer field and the value field is float and this value is specified inside double quotes, then it is throwing error, with message : 'failed to create query"

STEPS TO REPRODUCE :

1. Create an index named "twitter", with mapping specifying field as "id" and its type as "integer".

PUT twitter 
{
  "mappings": {
    "tweet": {
      "properties": {
        "id": {
          "type": "integer"
        }
      }
    }
  }
}

2. Put a document with id value equals 2 (and put other documents as well)

POST twitter/doc1
{
    "id":2
}

3. Now query for documents with id greater than or equal to "3.21212" (put the value inside the quotes)

POST twitter/_search
{
    "query": {
        "range": {
           "id": {
              "gte":"3.21212"
           }
        }
    }
}

ERROR GETTING:

"error": {
      "root_cause": [
         {
            "type": "query_shard_exception",
            "reason": "failed to create query: {\n  \"range\" : {\n    \"id\" : {\n      \"from\" : \"3.21212\",\n      \"to\" : null,\n      \"include_lower\" : true,\n      \"include_upper\" : true,\n      \"boost\" : 1.0\n    }\n  }\n}",
            "index_uuid": "9PRLIDKQTlq0O8_7PT-vtA",
            "index": "twitter"
         }
      ]}

NOTE : I am running queries using SENSE plugin on Chrome browser.

**Comment by cbuescher** [comment]
Hi @amver7,
thanks for opening the issue, I believe this has already been fixed in the upcoming 5.6 release and the next major relese in this PR: https://github.com/elastic/elasticsearch/pull/25835
I just checked your example and I don't get the error you are seeing in 5.4.1 in our latest 6.0.0-beta2 release. I'll close this for now, you might want to check this yourself on one of the preview 6.0 releases available on our download site. If you still get this error please reopen.
