### ISSUE TITLE
Circuit breaker for number of tokens used in in-memory highlighter

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#26515]
ES 2.4

![image](https://user-images.githubusercontent.com/7216393/30091131-b9e79978-926c-11e7-9509-0c1971cc5a3c.png)

We have seen a situation when there's limited amount of heap and the user was trying to use the default highlighter against a field with millions of tokens.

@s1monw is wondering if we could potentially limit the number of tokens used in our in-memory highlighter to stop creating tons of tokens in these situations.  He noted that we could potentially do this transparently in ES by wrapping the token streams somehow and this can also be a per-request
limit that users can configure.  Creating a discussion ticket on this topic.

**Comment by jpountz** [comment]
I'm on the fence about adding a new per-request option since we already have plenty of highlighter options. However I'm +1 to having a setting that controls the maximum number of tokens that highlighters are allowed to consume on a per-field basis, and fail requests if that limit is reached.

**Comment by jimczi** [comment]
The `plain` highlighter uses a `CachingTokenStream` to cache all tokens created for a field even though only few tokens may be use for highlighting (those that are extracted from the query). The caching is done because it needs to consume the stream twice so it's just an optimization but for big text this is clearly inefficient. I don't think that the number of total tokens should matter for an in memory  highlighter, what matters is the number of tokens that could be potentially highlighted.
The  `unified` highlighter filters the tokens in the token stream directly so it only keeps the tokens that are extracted from the query. This is a big difference in terms of memory because it doesn't cache the whole token stream, it just needs to create the tokens once and keeps only the relevant ones. The other difference is that it also creates a memory index but only from the tokens extracted in the query, this makes the index much smaller than the one created by the `plain` highlighter.
I'd need to do some benchmark but this differences make me think that the `unified` highlighter
can handle big fields efficiently as long as the number of terms extracted from the query is small. 
Since the `unified` highlighter is the new default in 6 I wonder if the requested feature is really needed. There is also the option to remove the CachingTokenStream from the `plain` highlighter if we really want to "fix" this one too but the goal is to remove it soon...
I'll run some experiment with the `unified` highlighter on big fields to verify my assumptions first but the memory profile should be completely different.

**Comment by jimczi** [comment]
The `unified` and `plain` highlighter have a setting to limit the number of tokens that are allowed to be re-analyzed:
https://github.com/elastic/elasticsearch/issues/27517
This limit has been added to point users to strategies that doesn't require to re-analyze the text if they try to apply highlighting on big fields. Regarding the memory consumption for the re-analysis, the `unified` highlighter is now the default in 6.x and it doesn't use a caching strategy for the analyzed tokens. Instead it filters the tokens that should not be highlighted (they are simply ignored) and index the rest in an in-memory index. Since the number of highlighted tokens should be small the memory should not be an issue so I am closing this issue.
