### ISSUE TITLE
Fuzzy queries give incorrect scores

### ISSUE THREAD

**Issue by isonil** [elastic/elasticsearch#26523]
**Elasticsearch version**: 5.5.2

Fuzzy queries give completely random unintuitive scores.

For example, searching for `testitem3` will give `testitem3` the **lowest** score, which is contradictory to what all fuzzy queries tutorials you can find say and is completely unintuitive.

Example query:

```
{
  "size": 5,
  "query": {
    "match": {
      "name": {
        "query": "testitem3",
        "fuzziness": "AUTO",
        "fuzzy_transpositions": true
      }
    }
  }
}
```

Result:
```
{
  "took" : 8,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 3,
    "max_score" : 0.8582256,
    "hits" : [
      {
        "_index" : "project",
        "_type" : "itemsearch",
        "_id" : "1",
        "_score" : 0.8582256,
        "_source" : {
          "id" : 1,
          "name" : "testitem"
        }
      },
      {
        "_index" : "project",
        "_type" : "itemsearch",
        "_id" : "2",
        "_score" : 0.6161308,
        "_source" : {
          "id" : 2,
          "name" : "testitem2"
        }
      },
      {
        "_index" : "project",
        "_type" : "itemsearch",
        "_id" : "3",
        "_score" : 0.2876821,
        "_source" : {
          "id" : 3,
          "name" : "testitem3"
        }
      }
    ]
  }
}
```

**Comment by martijnvg** [comment]
@isonil I suspect that the unexpected scores in this case is caused by the fact that these documents are spread across different shards, which makes ES unaware of the existing of some or all docs in the case when computing the score. Can you try with a single shard index or use the dfs_query_then_fetch search type? (https://www.elastic.co/guide/en/elasticsearch/reference/5.5/search-request-search-type.html#dfs-query-then-fetch)

**Comment by isonil** [comment]
@martijnvg dfs_query_then_fetch solved the problem. Thank you very much.
