### ISSUE TITLE
Dynamic Secure Settings

### ISSUE THREAD

**Issue by scottsom** [elastic/elasticsearch#26589]
It is considered a [best practice](http://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html#rotate-credentials) to regularly rotate AWS credentials.

When using the `repository-s3` plugin along with secure settings, it does not appear to be possible to change the credentials on the S3 client without restarting the node. Having to restart a cluster just to rotate credentials makes this process difficult and potentially disruptive.

It would be nice if the secure settings could be updated and the new value is eventually picked up by the node without a restart.

Can it be changed to refresh the keystore from disk periodically?

**Comment by rjernst** [comment]
Refreshing from disk is not possible, due to how the keystore is loaded essentially as part of elasticsearch.yml (but from a secure source) when elasticsearch is started. Node settings are passed around and held onto all over the system during initialization. There is no mechanism to pass "updated" settings around, or what this would imply (for example, some node settings are used to construct service implementations inside the Node, so refreshing them would mean reconstructing running services, which themselves may be held onto by other services).

At the moment, there is not a good, secure solution for this.  For the time being, there is an undocumented system property, `es.allow_insecure_settings` which you can set to true, and will allow you to pass the access/secret key in the repository settings (which is inherently insecure since the cluster state is stored in plaintext on disk).  We do intend to come up with a better solution for this in the future, but there are not yet concrete plans for that.

**Comment by scottsom** [comment]
Maybe I am missing something but an instance of `KeyStoreWrapper` is created during the bootstrap and then this same instance appears to be passed around (i.e. it is effectively a singleton). If this instance refreshed itself internally then new settings would be made visible on future reads.

Is there a particular reason the setting values are read at construction time into member variables rather than reading from `SecureSettings` at time of use?

For example, in the repository-s3 case, instead of constructing the S3 client with an instance of `StaticCredentialsProvider`, the plugin could extend `AWSCredentialsProvider` to something like `SecureSettingsCredentialsProvider` that reads directly from the secure settings instance to pick up the latest keys without having to reconstruct anything.

**Comment by rjernst** [comment]
> If this instance refreshed itself internally then new settings would be made visible on future reads

It is more complicated than that. The keystore is _closed_ after the node is initialized. We keep this stuff in memory for as little time as possible. The contract is plugins/services must read their secure settings during initialization.  S3 repository iterates over all the named clients, pulling creds/settings together, and then stores those in its own internal map of client settings, then looks up from there later when creating a new repository.

With secure settings, we wanted to start out simple, and that is why we went with a local keystore. But long term this is likely to be expanded in scope to store cluster settings securely as well. This would then enable repository settings to be marked as secure, and change how we store them in cluster state.  As I mentioned before, there is more work to come on secure settings. The insecure flag is only at temporary measure to allow faster update of certain secure settings (which is no worse than already existed in 5.x).

**Comment by scottsom** [comment]
Got it, thanks for the explanation.
