### ISSUE TITLE
Repository S3 compatibility

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/elasticsearch#26604]
@rjernst @dadoonet 

I have seen that there are many deprecated features (see https://github.com/elastic/elasticsearch/issues/22800, https://github.com/elastic/elasticsearch/issues/25619 as examples) where now for Elasticsearch 6.0 you can't just set some of the `repository-s3` configurations.

This was useful for compatible s3 services, however it seems to be that for this version we are only allowing people to configure the minimum necessary for get it working with AWS s3. 

My proposal here is to:

- Add a warning in the documentation that mentions that only AWS S3 is Supported.
- Add in the breaking changes (https://www.elastic.co/guide/en/elasticsearch/reference/6.x/breaking_60_plugins_changes.html#_s3_repository_plugin) that settings such as `path_style_access` cannot be actually configured at the global repository setting or per repository.

**Comment by rjernst** [comment]
> Add a warning in the documentation that mentions that only AWS S3 is Supported.

I'm not sure where such a warning should go. It is also not exactly true, it is just we no longer support untested settings which allowed working with older s3 compatible apis (namely ones that used legacy url formats and signing methods).

> Add in the breaking changes that settings such as path_style_access cannot be actually configured 

This is already there, in the `Global repositories settings have been removed` bullet.

**Comment by gmoskovicz** [comment]
@rjernst thanks for the quick answer ! :)

So i saw there that we mention that global settings have been removed. But then we also state that: `Instead, these settings should be set directly in the settings per repository. See S3 Repository settings.`.

This means that one should be able to set some of this using S3 repository settings, per repository. Which isn't true. As for example `path_style_access` cannot be used now.

Also, regarding the following:

>  It is also not exactly true, it is just we no longer support untested settings which allowed working with older s3 compatible apis (namely ones that used legacy url formats and signing methods).

For example `path_style_access` allowed you to use some services that only support path style access. This isn't just old S3 compatible APIs but some other currently used APIs such as Cleversafe from IBM for example. And this is just a single example.

The main intention of this issue is to discuss whether it makes sense to state the only `AWS S3` is intended to be used with the plugin. What do you think?

**Comment by rjernst** [comment]
> The main intention of this issue is to discuss whether it makes sense to add in the documentation that only AWS S3 is intended to be used with the plugin.

Again, we do not "only" support AWS S3. We just use the official s3 client, and no longer expose any "special" settings. Instead of having our code support multiple styles of accessing the bucket (one of which was untested before), we are trying to consolidate and make sure we have exactly one access pattern. In the case of path style access, it is a little tricky because it depends on the endpoint. The java client will first find info about the bucket from the configured endpoint, and then choose which access style to use based on that. So, if the s3 compatible layer supports this information retrieval about the bucket, then it should "automatically" use the appropriate access style.  Essentially, we don't want to special case this in our case (have the flag), but instead rely on the client/sdk.

I will add a note to the migration docs as you suggested, to clearly point out this setting has been removed.

**Comment by ywelsch** [comment]
@rjernst can we close this?

**Comment by debadair** [comment]
Fixed.
