### ISSUE TITLE
search in multi analyzer

### ISSUE THREAD

**Issue by kinandwair** [elastic/elasticsearch#26609]
I have index contains field with multi analyzer synonyms and phonetic and snowball
the problem appear when I try to search for this field some query for phonetic and other query work for synonyms is there away to search in both

**Comment by rjernst** [comment]
There is no discernible bug report here, as there is no reproduction information. Please ask questions on [our forum](https://discuss.elastic.co/c/elasticsearch). We use github for feature requests and confirmed bug reports. After asking for help on the forums, if the issue is indeed a bug, please fill out the information in the issue template when creating an issue. This information can help us more quickly identify and reproduce the bug, which can then result in a faster turnaround for a fix.
