### ISSUE TITLE
Short response for Bulk API

### ISSUE THREAD

**Issue by knocte** [elastic/elasticsearch#2661]
When using the bulk API with _a lot_ of documents (say 100K), it's kind of pointless to get a response for each of those documents because the response is huge! Cannot we have a way to call this API and only receive a response that is either:
- Successful insertion of all documents (count).
- Some insertion failed (count of the ones that failed).
- All insertion failed (count).

I know that I could probably use Bulk UDP (and I'll probably give it a go soon), but UDP doesn't receive any response whatsoever, so it's like having black&white, but not any shade of grey.

Thanks!

**Comment by mbonaci** [comment]
Very nice, this is really overdue.
Have you thought about returning only the failed docs in the response? Or even just ordinal numbers of failed docs. I assume people often want to further treat unsuccessful docs in some way, e.g. retry after modifications, store unstructured, ...

Also, instead of returning `200` or `201`, there are perhaps more suitable response codes in this situation, which would make the flag check inside the response obsolete.
Perhaps `207` or `422`?

> The 207 (Multi-Status) status code provides status for multiple independent operations (see Section 13 for more information). A Multi-Status response conveys information about multiple resources in situations where multiple status codes might be appropriate. The default Multi-Status response body is a text/xml or application/xml HTTP entity with a 'multistatus' root element. Further elements contain 200, 300, 400, and 500 series status codes generated during the method invocation. 100 series status codes SHOULD NOT be recorded in a 'response' XML element. Although '207' is used as the overall response status code, the recipient needs to consult the contents of the multistatus response body for further information about the success or failure of the method execution. The response MAY be used in success, partial success and also in failure situations. The 'multistatus' root element holds zero or more 'response' elements in any order, each with information about an individual resource. Each 'response' element MUST have an 'href' element to identify the resource.
MULTI_STATUS(207)

> The 422 (Unprocessable Entity) status code means the server understands the content type of the request entity (hence a 415(Unsupported Media Type) status code is inappropriate), and the syntax of the request entity is correct (thus a 400 (Bad Request) status code is inappropriate) but was unable to process the contained instructions. For example, this error condition may occur if an XML request body contains well-formed (i.e., syntactically correct), but semantically erroneous, XML instructions.

**Comment by rpedela** [comment]
+1

**Comment by avoxm** [comment]
It has been over 3 years guys any hope to have this implemented. Bulk API is quite memory hungry because of this issue.

**Comment by nik9000** [comment]
The `adoptme` and `low hanging fruit` mean the repository owners would love to review and merge a pull request that implements the feature but it isn't anyone's priority. If anyone wants to write a PR for this I'll certainly review it and, once we get to the other side of the review process, merge it.

**Comment by nik9000** [comment]
I'll just go do it.

I'll make an option that will just count successful operations rather than returning the whole result for it. Any failures will still come back because you can act on them.

**Comment by rpedela** [comment]
Thanks Nik!

**Comment by kimchy** [comment]
sorry for chiming in late, especially in the context of #17932. I am not a fan of this change, a short response format breaks the structure of how we return responses for bulk requests, and no longer relies on position within an array to match response to request. It means special code handling, different one, depending on the parameter of the request, which is not user friendly.

I also challenge the fact that parsing the response of a bulk requests is "heavy". Compared to setting up the requests to be indexed (which is the "other" client side work), I am very surprised that parsing the response takes so long as a whole compared to the whole bulk execution. This is definitely not the case in Java.

I would be ok with a flag that will simply not return anything except for top level summary fields if everything is successful. This is probably the most common case, and if something failed, just use the current way to correlate request/response.

**Comment by nik9000** [comment]
For what it is worth I don't have a strong opinion on how this should comes out or even if we merge #17932. I just implemented my first instinct and my first instinct is rarely right. My only strong opinion is "if Elasticsearch doesn't want any sort of short format on the bulk response then we need to close this issue".

**Comment by clintongormley** [comment]
> I would be ok with a flag that will simply not return anything except for top level summary fields if everything is successful. This is probably the most common case, and if something failed, just use the current way to correlate request/response.

+1

**Comment by rpedela** [comment]
> I would be ok with a flag that will simply not return anything except for top level summary fields if everything is successful. This is probably the most common case, and if something failed, just use the current way to correlate request/response.

I think the summary should be the default, and the current response should be behind a verbose flag. Otherwise +1.

**Comment by clintongormley** [comment]
> I think the summary should be the default, and the current response should be behind a verbose flag. Otherwise +1.

This would be a breaking change, so best to keep the default as it is today.

**Comment by rpedela** [comment]
The default should always be the most common case. In addition, the current, default behavior requires more CPU, memory, and network resources which seems like a bad thing. Besides aren't breaking API changes the norm for this project? It seems like every major version, sometimes even minor versions have major changes to the API.

**Comment by clintongormley** [comment]
@rpedela We think long and hard about every breaking change that we make, and try to find ways to smooth the migration.  This is a good example of something that we shouldn't break.

**Comment by clintongormley** [comment]
Rediscussed this in FixItFriday. We're loathe to change the API (which pushes complexity towards the clients and runs the risk of bugs) without any benchmarks demonstrating how much performance gain there is from making this change.  The bulk response is very compressible so we could well find that leaving out the bulk items make a negligible difference.

I'm going to close this for now, but feel free to reopen if you can show a significant difference in performance when compression is enabled.

**Comment by garakelian** [comment]
@kimchy @nik9000 I came across this thread while researching bulk api requests format. It's worth mentioning here that [bulk api documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html) doesn't mention that request/response are correlated by index order.  Would you mind adding that as an API guarantee?

I use in ES a production environment which indexes hundreds of billions of documents, and we retry individual documents that fail via the bulk API. Since the documentation doesn't guarantee ordering of the response, we had been matching request/response items via index/type/id, but there is a subtle problem with that approach.  We use index aliases, and when you do that, the request will have the alias, but the response has the physical index name.. a mismatch occurs.

**Comment by jasontedor** [comment]
@garakelian I believe that's covered [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/_batch_processing.html):

> When the bulk API returns, it will provide a status for each action (in the same order it was sent in) so that you can check if a specific action failed or not.

**Comment by garakelian** [comment]
@jasontedor Thanks for quick reply. I missed that page, thank you. Do you know if a PR request would be welcomed to update the documentation on the other page I referenced, to at least point to this page, and/or add the note about the index name being different on the reply when aliases are being used.

**Comment by jasontedor** [comment]
An update to the bulk API documentation that you referenced would be welcomed (I would prefer explicitly mentioning the API guarantee that we provide, rather than linking elsewhere in our docs).

As for the response when indexing using an alias, I think that is covered in the alias docs (if it's not, it should be here), but I don't think that the bulk API docs are the right place (should be more general).

Does that make sense?

**Comment by garakelian** [comment]
@jasontedor Sure. I'll submit a PR based on your suggestion... Thanks.

**Comment by jasontedor** [comment]
Thank you @garakelian.

**Comment by sinylei** [comment]
@clintongormley, I am not sure if the performance would get great improved by short return message, but I am sure it will save a lot of money paid for the network traffic when using in Cloud environment.
For most Cloud platform, the inbound traffic is free and only charge the outbound traffic.
When we deployed a cloud based ES system, and the clients call bulk api, for the cloud ES, the request from client is an inbound traffic, that is free, but the response to client is outbound traffic which needs to be paid at some rate.

**Comment by wnojopra** [comment]
I came across this thread while looking for a way to reduce the response from Bulk API. A few days later, I discovered the [filter_path](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#common-options-response-filtering) parameter that drastically reduced the response size for my large bulk requests. This seems to have existed since [2015](https://github.com/elastic/elasticsearch/pull/10980). 

Is there any reason using filter_path wouldn't solve the problems discussed in this thread?

**Comment by panthony** [comment]
@wnojopra I stumbled upon this issue because I have a timeout problem using Bulk API that appeared after I enabled SSL on ElasticSearch 8.5

At some point ES does not sent the last few bytes of the huge response (~50k docs per request) thus it hang until it reached the timeout, retry, and create duplicates since I relied on ElasticSearch to generate the IDs.

Long story short, I stumbled upon `?filter_path=took,errors,items.*.error` to return only items in errors and it "solved" the issue in a way as it heavily reduce the response size but in introduce new challenges:

1) The BulkProcessor does NOT expect missing values when building BulkResponseItem (ex: missing shard, etc.) and create a runtime error (null value whereas an `int` was expected for ex)
2) The per-doc retry logic of the BulkProcessor rely on the position of the item in error in the response to find the corresponding request. Breaking the retry logic.

An easy workaround for 2) would have been to have, in the response, the position of the item within the request
