### ISSUE TITLE
about  script in java

### ISSUE THREAD

**Issue by jianwei2** [elastic/elasticsearch#26619]
`Map<String, Object> params = new HashMap<String, Object>(); 
params.put("message2", "22345678dddd91");

updateRequest.script(new Script(Script.DEFAULT_SCRIPT_TYPE, Script.DEFAULT_SCRIPT_LANG, "def message2 =''; ctx._source.message2 = message2;",params));`

the result is   "message2 =''"。

**Comment by cbuescher** [comment]
Sorry, there is no discernible bug report here. For general questions, please use [our forum](https://discuss.elastic.co/c/elasticsearch). We use github for feature requests and confirmed bug reports. After asking for help on the forums, if the issue is indeed a bug, please fill out the information in the issue template when creating an issue. This information can help us more quickly identify and reproduce the bug, which can then result in a faster turnaround for a fix.

**Comment by jianwei2** [comment]
ctx._source.message2 = params.message2
