### ISSUE TITLE
Release build fails to find BWC branches

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#26702]
[This](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.0+release-tests/31/consoleFull) release build failed to find the bwc build:
```
22:18:24 Cannot expand ZIP '/var/lib/jenkins/workspace/elastic+elasticsearch+6.0+release-tests/distribution/bwc/build/bwc/checkout-5.6/distribution/zip/build/distributions/elasticsearch-5.6.2-SNAPSHOT.zip' as it does not exist.
```

Here is what *does* exist:
```
manybubbles@slave-0b5b99f34015422a8:/var/lib/jenkins/workspace/elastic+elasticsearch+6.0+release-tests$ ls /var/lib/jenkins/workspace/elastic+elasticsearch+6.0+release-tests/distribution/bwc/build/bwc/checkout-5.6/distribution/zip/build/distributions/
elasticsearch-5.6.2.pom  elasticsearch-5.6.2.zip
```

I expect the trouble is that we pass the release flag down to the bwc snapshot builds. Either we shouldn't do that or we should look without the `-SNAPSHOT` suffix in release build tests.

Fun times.

**Comment by rjernst** [comment]
We don't do it intentionally, it is just how gradle works, unfortunately. We use a `GradleBuild` task to build the bwc projects. That is like loading another gradle build inline within the current build, so it is not forked, and thus operates with the exact same sysprops.  I think we should look for this sysprop, and if it we are in a non-snapshot build, we setup the bwc build task with Exec instead of GradleBuild. This means when running most of the time we will still get nice integration of the gradle logging between the two builds. Only during the release CI testing will the logging be different, and it won't matter for CI (it just matters for the build status line which CI does not have).

**Comment by ywelsch** [comment]
> That is like loading another gradle build inline within the current build, so it is not forked, and thus operates with the exact same sysprops. I think we should look for this sysprop, and if it we are in a non-snapshot build, we setup the bwc build task with Exec instead of GradleBuild. 

According to the [Gradle docs](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.GradleBuild.html#org.gradle.api.tasks.GradleBuild:startParameter), the system properties of the GradleBuild can be influenced using the `startParameter.setSystemPropertiesArgs(...)` method.
