### ISSUE TITLE
UseConcMarkSweepGC

### ISSUE THREAD

**Issue by tstsogoo** [elastic/elasticsearch#26788]
`Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.`
elasticsearch-5.5.0, windows x64

**Comment by tvernum** [comment]
Hi @tstsogoo

Thanks for reporting this, however we do not consider this to be a bug because:

- Elasticsearch 5.5 [does not support Java 9](https://www.elastic.co/support/matrix#matrix_jvm)
- Despite CMS being deprecated, it is still [the best GC method](https://www.elastic.co/guide/en/elasticsearch/guide/current/_don_8217_t_touch_these_settings.html#_garbage_collector) for Elasticsearch at this point in time.

Thanks.
