### ISSUE TITLE
query_string failed to search non empty string with single asterisk

### ISSUE THREAD

**Issue by changsijay** [elastic/elasticsearch#26801]
Hi, I am using elasticsarch `5.6.1`, I am trying to query the documents which `tag` is not empty by

```
{"query": {"query_string": {"query": "tag:*" }}}
```

it return all documents including those which tag is empty.

howerver, before I migrated from `2.4` to `5.6.1`, this query worked fine on `2.4`.
It only return documents which tag is not empty.

Is there any default setting changed caused this query failed?

In the same time I tried below query with `?` before asterisk on current `5.6.1`

```
{"query": {"query_string": {"query": "tag:?*" }}}
````

it works as I expected, although I prefer not to modify all source code to this syntax.

**Comment by jpountz** [comment]
Am I correct that your `tag` field is mapped as `text`? I think this is because we now rewrite pure wildcards to `exists` queries for efficiency. But it might indeed perform differently on `text` fields.

@jimczi What do you think?

**Comment by changsijay** [comment]
@jpountz , yes, the `tag` field is `text`

**Comment by jimczi** [comment]
> it return all documents including those which tag is empty.

Yes this is a change in behavior compared to 2.x. Note that the field is empty and not null, the following document would match `tag:*`:
````
{ "tag": "" }
````
and this one would **not**:
````
{ "tag": null }
````

This is true for `keyword` and `text`field.

> it works as I expected, although I prefer not to modify all source code to this syntax.

Can you reindex your data with null values instead of empty ?
`?*` works as expected but is also horribly costly if you have a lot of distinct terms.
I'll add a note in the documentation, thanks for reporting @changsijay !
