### ISSUE TITLE
Remove unused dependencies from high level rest client/transport client

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#26885]
One day we'd like to have a far fewer dependencies in the high level rest client but right now it depends on Elasticsearch core and all of the "client" module jars. I think a good first step for us would be to remove all of the dependencies from the client jars that aren't really needed.

I don't know how this plays out with the transport client and the high level rest client depending on the same client jars.

I think this is worth pursuing but I'd like to gauge interest in this so I'm opening it with discuss.

**Comment by fsosa** [comment]
Great timing! We were just discussing this exact problem as we were planning out our migration from a custom Lucene engine to Elasticsearch. We originally hoped to use the high-level rest client, but the dependency on elasticsearch core, and transitively on Lucene, prevented us from doing so. It seems that our only option is to use the low-level rest client. 

Although our migration situation may not exactly be the most common, it does speak to the need to make the high-level rest client as thin as possible with regards to dependencies. Adding my support (and pitching in myself as a resource) to help.

**Comment by s1monw** [comment]
While it's a long term goal to get rid off most of the dependencies we would need to move all the shared stuff into a higher level JAR and depend on it in the REST client and core. I don't see this happening for a long time and the high level REST client wasn't aiming to solve this problem it in-fact didn't make the situation worse since TransportClient had the exact same issue. Unless we can extract the shared classes I am against excluding anything since it might just be huge time sink testing wise. I think it might make sense to move out certain dependencies into modules like #26850 does. I don't think we should leave this open for now. We can come back to this once we have the resources to do it.

**Comment by nik9000** [comment]
All I wanted to do in this is:


> remove all of the dependencies from the client jars that aren't really needed.

By that I mean remove from the dependencies list in the high level REST client the dependencies that it doesn't need to function. I just want that list to be better curated then it is now.

**Comment by javanna** [comment]
@nik9000 an example of what is not needed and can be removed?

**Comment by nik9000** [comment]
I'm not sure to be honest. I know in the case of the transport client we bring in the low level rest client because we depend on Reindex's client jars. I don't think those are needed for the transport client. At least, they shouldn't be. I'm not sure how much time we want to spend on the transport client but it is an example how this sort of things happens. If we've already done all this for the high level rest client I'm happy to close leave it closed. Or if we just don't feel now is the right time to do this then we should leave it closed.

**Comment by javanna** [comment]
I think that we want to focus on the high level REST client only at this point and leave the transport client untouched unless we find bugs there. 

I am afraid that users will read this issue as it happened above as "let's remove the Elasticsearch dependency from the high level REST client" which is a totally different story that will take a long time to accomplish. Unfortunately the Elasticsearch dependency is not unused and that would require to have a common artifact that is shared between server and client, but because of how we treated the Java api until now, that's a long shot.

I didn't think that we are releasing the high level REST client with unused dependencies. If there are any, we can and should certainly remove them, but I still can't think of any :)

@fsosa if the high level REST client dependency on elasticsearch/lucene concerns you, you can probably have a look at shading it (although SPI may be a problem). This issue wasn't about addressing that problem though.
