### ISSUE TITLE
Using phonetic analyzer affects queries with fuzziness

### ISSUE THREAD

**Issue by davidlmorton** [elastic/elasticsearch#26921]
**Elasticsearch version** (`bin/elasticsearch --version`): 5.6.2 and 6.0.0-rc1 (maybe others)

**Plugins installed**: [analysis-phonetic]

**JVM version** (`java -version`): official docker containers from docker.elastic.co

**OS version** (`uname -a` if on a Unix-like system): Linux ubuntu-xenial 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**: Match queries with fuzziness do not work as expected when a phonetic analyzer is used on the field.  Removing the analyzer from the example below restores the expected behavior of the fuzziness.

**Steps to reproduce**:

```python
from elasticsearch import Elasticsearch
import sys

es = Elasticsearch(hosts=[sys.argv[1]])

index_body = {
    'settings': {
        'number_of_shards': 1
    },
    'mappings': {
        'test': {
            'properties': {
                'last_name': {
                    'type': 'text',
                    'analyzer': 'phonetic_analyzer',
                },
            },
        },
    },
    'settings': {
        'index': {
            'analysis': {
                'analyzer': {
                    'phonetic_analyzer': {
                        'filter': ['lowercase', 'phonetic_filter'],
                        'tokenizer': 'standard',
                        'type': 'custom'
                    },
                },
                'filter': {
                    'phonetic_filter': {
                        'replace': 'false',
                        'type': 'phonetic',
                    },
                },
            },
        },
    },
}
create_result = es.indices.create(index='test', body=index_body)

index_result = es.index(index='test', doc_type='test',
        body={'last_name': 'CONNE'},
        refresh=True)

index_result = es.index(index='test', doc_type='test',
    body={'last_name': 'CONNER'},
    refresh=True)

search_body = {
    'query': {
        'match': {
            'last_name': {
                'query': 'CONNER',
                'fuzziness': 'auto',
            },
        },
    },
    'explain': True,
}
search_result = es.search(index='test', doc_type='test',
        body=search_body)

print("This should have returned two hits, but only returned %s." %
        search_result['hits']['total'])  # 1

print("We only matched record with name: %s" %
        search_result['hits']['hits'][0]['_source']['last_name'])  # CONNER
print("This should have also matched the CONNE record too!")
```

**Comment by jpountz** [comment]
Fuzziness is not applied because the phonetic filter has `replace: false`, which creates synonyms under the hood. The parsed query is `Synonym(last_name:KNR last_name:conner)`. @jimczi Do you have an opinion as to whether this should be fixed / documented?

Here is a Console recreation if someone needs to iterate on it:

```
PUT test 
{
  "settings": {
    "index": {
      "analysis": {
        "analyzer": {
          "phonetic_analyzer": {
            "tokenizer": "standard",
            "filter": [ "lowercase", "phonetic_filter" ]
          }
        },
        "filter": {
          "phonetic_filter": {
            "type": "phonetic",
            "replace": false
          }
        }
      }
    }
  }, 
  "mappings": {
    "doc": {
      "properties": {
        "last_name": {
          "type": "text",
          "analyzer": "phonetic_analyzer"
        }
      }
    }
  }
}

PUT test/doc/1
{
  "last_name": "CONNE"
}

PUT test/doc/2
{
  "last_name": "CONNER"
}

GET test/_search
{
  "query": {
    "match": {
      "last_name": {
        "query": "CONNER",
        "fuzziness": "AUTO"
      }
    }
  }
}

GET test/_validate/query?rewrite=true
{
  "query": {
    "match": {
      "last_name": {
        "query": "CONNER",
        "fuzziness": "AUTO"
      }
    }
  }
}
```

**Comment by jimczi** [comment]
This is not the first time that this issue is reported so I agree that we should do something to support this use case. The `SynonymQuery` has been added in 2.x to handle cases where multiple terms appear in the same position. The `SynonymQuery` tries to score the terms as if you
 had indexed them as one term and gives similar score to documents that match different `synonym`. This is confusing because this situation happens not only with `synonym` filter but also with token filters that preserve multiple rewriting of the same term. So for instance the `phonetic` filter can preserve the original term and add the phonetic form as a synonym when `replace` is set to true. When fuzziness is applied to a `match` query, `synonyms` are ignored and we run into situation like the one described in this issue. 
I think we could just apply the fuzziness to all terms if they appear at the same position and use a disjunction max query instead of a synonym query. This would break the similar score on synonyms that we usually have with the `SynonymQuery` but IMO it's an acceptable trade off when dealing with fuzziness and analysis expansion. Another option would be to remove the `replace` option (with a deprecation period) but this would not fix the issue with other token filters that keep multiple terms per position so I am leaning toward the first solution.

**Comment by davidlmorton** [comment]
I don't know how much my vote matters, but I would prefer that it were fixed rather than simply documented.  Detecting that this is happening and issuing a warning or error would be preferable to silently ignoring the fuzziness setting too.  I would personally be okay with the disjunction max solution's side effect.  Would the synonyms only be under a disjunction max query in the case where fuzziness were applied or always?  What about fuzziness of 'auto' and a list of short synonyms?

**Comment by jimczi** [comment]
We've decided that the current behavior is more easy to understand and reason about. See https://github.com/elastic/elasticsearch/pull/26940#issuecomment-342241790.
The workaround for the example in this issue is to use two fields, one for the phonetic and one for the original form. Then it is easier to apply fuzziness to the original form only since applying fuzziness to phonetic form would lead to unexpected results.

**Comment by davidlmorton** [comment]
I hope that this at least gets documented, or did I stumble upon an exceptionally unusual use-case?

**Comment by romseygeek** [comment]
cc @elastic/es-search-aggs
