### ISSUE TITLE
Format doc values fields

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#26948]
Follow-up of #22146, which has been stalled for a long time and probably needs to be re-done entirely now.

Currently docvalues_fields return the values of the fields as they are stored
in doc values. I don't like that it exposes implementation details, but there
are also user-facing issues like the fact it cannot work with binary fields.
This change will also make it easier for users to reindex if they do not store
the source, since docvalues_fields will return data is such a format that it
can be put in an indexing request with the same mappings.

**Comment by dakrone** [comment]
Just a random aside, but it used to be the case with Kibana that they relied on
the non-formatting of doc_values for displaying data. For example, with dates
they used to ask for `fielddata_fields`/`docvalues_fields` of the date to get it
back in the epoch long format, rather than `YYYY-mm-dd:HH:mm:ss,SSS` (Kibana may
have since changed not to use it, I just wanted to leave a warning that we
should check).

**Comment by jpountz** [comment]
Absolutely, this is actually the reason that I delayed the merging since it required synchronization with Kibana at a time when I had few free cycles.

**Comment by talevy** [comment]
Pinging @elastic/es-search-aggs

**Comment by jpountz** [comment]
Fixed by #30831.
