### ISSUE TITLE
Snapshots to S3 Repository in 5.x cause a much higher object churn/GC than previous versions

### ISSUE THREAD

**Issue by centic9** [elastic/elasticsearch#26969]
Elasticsearch version: Ok on 2.3.3, Not Ok on 5.3.3
Plugins: S3, EC2
JVM: 1.8.0_102
OS Version: Linux ip-10-176-42-66 4.9.32-15.41.amzn1.x86_64 #1 SMP Thu Jun 22 06:20:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
heap size [4.6gb], compressed ordinary object pointers [true]

We have a number of Elasticsearch nodes in multiple clusters on EC2 instances. Previously we were running version 2.3.3, but lately upgraded to 5.3.3.

We run Snapshots every hour to back up data regularly to S3.

Since upgrading from 2.3.3 to 5.3.3 we see a regular pattern of high GC, both in our monitoring (Dynatrace) and the newly introduced gc-logs from Elasticsearch itself. 

![image](https://user-images.githubusercontent.com/548322/31443863-d3d305a8-ae9a-11e7-9a7a-1cf174988a10.png)

It seems the Snapshot operation changed in 5.x and now causes quite a large spike in GC activity on the Elasticsearch server. 

We analyzed this with Java Flight Recorder and it shows that almost all of the memory churn is caused by the constructor S3OutputStream(), which seems to allocate a huge byte[]. 957 allocations of byte[] cause 94GB of memory allocation, this would mean 100MB per invocation of S3ObjectStream(). This matches with the debug-output from S3Repository:

`[2017-10-11T13:46:28,431][DEBUG][o.e.r.s.S3Repository     ] [i-052912327e74e66e0] using bucket [ruxit-elasticsearch-testbackups], chunk_size [1gb], server_side_encryption [false], buffer_size [100mb], cannedACL [], storageClass []`

So it seems the buffer is re-allocated again and again, which causes quite high object churn/GC spikes. I am not sure if it is on-purpose to re-create this buffer continuously or not, so either this re-allocation is wrong or the memory size calculation (see below) does not fit well for 4GB heap instances. (we also see it for 8GB instances, BTW)

This is what JFR reports:

![Java Flight Recorder allocation analyzis](https://user-images.githubusercontent.com/548322/31443429-b8b71616-ae99-11e7-9629-2952e09c88ac.png)

**Steps to reproduce**:

1. Use a normal EC2 instance, e.g. m4.large
2. Set up Elasticsearch 5.3.3 using the default setup and add S3 plugins
3. Add some index-data, e.g. in our case 8GB in 12 indices with 3 shards, 0 replicas each
3. Set up an S3 snapshot repository
4. Trigger a snapshot to S3
=> We see GC-logs stating that more than 500ms were spent for GC in 1s:

**Provide logs (if relevant)**:

```
[2017-10-10T11:10:26,254][INFO ][o.e.m.j.JvmGcMonitorService] [i-052912327e74e66e0] [gc][82970] overhead, spent [258ms] collecting in the last [1s]
[2017-10-10T11:11:02,393][INFO ][o.e.m.j.JvmGcMonitorService] [i-052912327e74e66e0] [gc][83006] overhead, spent [281ms] collecting in the last [1s]
[2017-10-10T11:12:08,671][INFO ][o.e.m.j.JvmGcMonitorService] [i-052912327e74e66e0] [gc][83072] overhead, spent [255ms] collecting in the last [1s]
[2017-10-10T11:13:15,227][INFO ][o.e.s.SnapshotShardsService] [i-052912327e74e66e0] snapshot [s3_repository:snapshot_dost-test-apm-108329_1507633631823/mWeSRcliTSKvN8NYDzApGA] is done
```

**Additional info**:

The buffer size is computed as follows, for 4.6GB, it leads to 100MB

```
                Math.max(
                        ByteSizeUnit.MB.toBytes(5), // minimum value
                        Math.min(
                                ByteSizeUnit.MB.toBytes(100),
                                JvmInfo.jvmInfo().getMem().getHeapMax().getBytes() / 20)),
```

**Comment by centic9** [comment]
It seems in Elasticsearch 2.x the BufferSize was 5MB:

    `public static final ByteSizeValue MIN_BUFFER_SIZE = new ByteSizeValue(5, ByteSizeUnit.MB);`

**Comment by tlrx** [comment]
@centic9 Thanks for your report and analysis.

Some background around the buffer_size setting: long time ago, we saw users having connection issues like timeouts when snapshoting or restoring using S3. It often involved large files, so in 1.4 we changed the implementation and introduced the S3OutputStream in order to use the _Multipart Upload API_ provided by AWS. This API allows to send large files using multiple upload requests instead of a single large one. At this time, we followed the AWS S3 recommendations because we were a bit blind on the right value to use, and we also exposed them through settings. I think this new implementation helped some users that were just not able to snapshot their data on S3. A bit later, few users complain about an increase of the requests executed to snapshot the data on S3. It was because of the fixed 5Mb buffer size and the default value was changed in 5.0 from 5Mb to 100Mb (see #17244) in order to reduce the number of S3 requests executed to upload large files. As the 100Mb could be a bit large for node with small heap it was enhanced in #21299 to be 100Mb for node with 2Gb heap or 20% of the heap.

Now, I agree that the current implementation should not blindly allocate a 100Mb buffer but should allocate only the required size to buffer the current file to upload. I think this change is simple as the blobSize is available when creating the S3OutputStream, I'll take a look at this soon.

On a different level I think that the current S3 repository plugin could be improved in different ways (it has some TODOs and legacy code) and we should also use a newer version of the AWS SDK (it has been improved a lot the past two years). I'm thinking of removing S3OutputStream in favour of the AWS SDK's TransferManager utility class: it should reduce the allocations. Also, AWS SDK 2.0 is coming with some nice features that could help too.

**Comment by dadoonet** [comment]
@tlrx FYI about S3 SDK update there is this pending PR: #25552

**Comment by centic9** [comment]
Thanks for the detailed explanation, so setting the buffer-size back to 5mb should mostly revert this behaviour, right? 

I am surprised that nobody else seems to run into this, but maybe our machines use a small heap compared to most other setups (We have many smaller separate clusters).

We did see some failures to send the data to S3 in 2.3.3, but as we retry it every hour anyway, it was not a big problem for us.

**Comment by centic9** [comment]
FYI, setting the buffer_size back to 5mb makes the situation look much better for us. We now see count of allocations of byte[] are 5 times up (5000 compared to 1000), but overall allocation is only 1/60th compared to before (94GB compared to 1.49GB). GC-Logs are gone as well.

=> Seems the 100m buffers are much too large for the required transfer-size most of the time and thus a lot of useless allocation is done currently!

**Comment by tlrx** [comment]
> FYI, setting the buffer_size back to 5mb makes the situation look much better for us. We now see count of allocations of byte[] are 5 times up (5000 compared to 1000), but overall allocation is only 1/60th compared to before (94GB compared to 1.49GB). GC-Logs are gone as well.

That makes sense, but note that the number of requests against the S3 service might be increased too (ie, watch if you don't exceed your S3 limits as it can have extra costs)

> Seems the 100m buffers are much too large for the required transfer-size most of the time and thus a lot of useless allocation is done currently!

That was the purpose of #21299, to adapt the size of the buffer, but the real issue is that the buffer is fully allocated even if there's only few bytes to send... and this is a bug.

Anyway, thanks a lot for your feedback, it helps a lot!

**Comment by patil-abhi** [comment]
@tlrx You are right. setting the buffer_size back to 5mb makes us get AWS S3 slow down error and the snapshots fail partially. Is there a workaround for this? We use ES 5.6.10.
