### ISSUE TITLE
Update By Query documentation mentions size parameter but never explains it

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#26981]
In https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docs-update-by-query.html

> Parameters like requests_per_second and **size** on a request with slices are distributed proportionally to each sub-request. Combine that with the point above about distribution being uneven and you should conclude that the using **size** with slices might not result in exactly size documents being `_update_by_query`ed.

The thing is that `size` parameter exists but is not documented.

**Comment by adityasrini** [comment]
I've found the max size and would love to do a PR on this. Can someone be so kind to guide me through this?

**Comment by nik9000** [comment]
The simplest way is to go to the version of the docs for the master branch (https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-update-by-query.html) and then click the "edit" icon in the top right. That should give you a web interface to make your change and open a PR.

If you want to clone the repository you can open `update_by-query.asciidoc` and make your change there. That is nicer in a lot of ways because you can change more than one file (maybe the same change has to be made to reindex.asciidoc and delete_by_query.asciidoc?) and you can build the docs (instructions [here](https://github.com/elastic/docs)) to see how it looks before opening the PR.

**Comment by adityasrini** [comment]
I will look at all docs that need the change implemented and update them accordingly!

**Comment by adityasrini** [comment]
I did a search on "size" for this repo with Asciidoc results filtered out, and out of the many I felt like it made sense to document max sizes for the following documents: [`update-by-query.asciidoc`](https://github.com/elastic/elasticsearch/blob/0d11b9fe34c007fddc5cbf2c821ef226b7a0fc75/docs/reference/docs/update-by-query.asciidoc), [`reindex.asciidoc`](https://github.com/elastic/elasticsearch/blob/0d11b9fe34c007fddc5cbf2c821ef226b7a0fc75/docs/reference/docs/reindex.asciidoc), [`delete-by-query.asciidoc`](https://github.com/elastic/elasticsearch/blob/0d11b9fe34c007fddc5cbf2c821ef226b7a0fc75/docs/reference/docs/delete-by-query.asciidoc). But before I make commits I wanted to ask if it makes sense for [`significantterms-aggregation.asciidoc`](https://github.com/elastic/elasticsearch/blob/0d11b9fe34c007fddc5cbf2c821ef226b7a0fc75/docs/reference/aggregations/bucket/significantterms-aggregation.asciidoc) to have a max size documentation under the "Size & Shard Size" subsection.

**Comment by dakrone** [comment]
I believe the latest version of the documentation explains the "size" parameter much better, so I am going to close this. If someone disagrees please let us know or open a new issue.

**Comment by adityasrini** [comment]
Shall I close my PR?
