### ISSUE TITLE
multi_match ignores type when expanding phrase_prefixes

### ISSUE THREAD

**Issue by tsuthers-ccpgames** [elastic/elasticsearch#27023]
Hi all, a quick set of commands for you:

```
curl -XPUT -d '{"settings": {"index":{"number_of_shards": 1}}}' http://localhost:9200/personnel/
curl -XPUT -d '{"first_name": "bob", "last_name": "smith"}' http://localhost:9200/personnel/managers/1
curl -XPUT -d '{"first_name": "bobby", "last_name": "tanner"}' http://localhost:9200/personnel/contractors/2
curl -XGET -d '{"query": {"bool": {"should": [{"constant_score": {"filter": {"bool": {"must": {"multi_match": {"query": "bob","type": "phrase_prefix","max_expansions": 50,"fields": ["first_name", "last_name"]}}}}}}]}}}' 'http://localhost:9200/personnel/contractors/_search?pretty=true&explain'
```
Observe the following excerpt from the output:
```
"description" : "ConstantScore(((first_name:bobby first_name:bob) | MatchNoDocsQuery(\"No terms supplied for org.elasticsearch.common.lucene.search.MultiPhrasePrefixQuery\"))), product of:",
```

Intuitively, I expected the multi_match to execute over just the contractors type, and thus would not expect "bob" from the managers type to be in the set of documents queried by multi_match, but it seems I am mistaken. 

Note that the constant score stuff is not required to repro this. I include it in the demo because it causes the explain argument to highlight the issue better. Without it, it's hard to detect this issue on small datasets.

The secondary effects of this issue (missing data in the result sets) can be reproduced on my development cluster with the following style of query:
```
{"query":{"bool":{"must":{"multi_match":{"query":"bob","type":"phrase_prefix","max_expansions":50,"fields":["first_name","last_name"]}}}}}
```

This issue has been seen in production on AWS Elasticsearch 5.3, and reproduced using the curl commands at the top of this issue against a local Elasticsearch 5.6.3.

As far as I can tell. this is what's happening:

When running a multi_match phrase_prefix query with a specific type in the URL, Elasticsearch picks a shard. Elasticsearch then expands all documents in the shard, regardless of whether the documents are of the requested type or not. After the phrase_prefix query on the whole shard is complete, it discards any matches with types that do not match the type requested in the URL.

This is a problem if one type has many more potential hits than another. The query will hit the max_expansions limit while querying types that are not relevant to the query, and then fail to run the query over the types requested.

I have attempted without success to apply some kind of pre-filtering to reduce the dataset the multi_match is querying down to just the type I want.

I am uncertain if this is a bug, a problem with my search strategy or simply that I am lacking a magical invocation to solve the problem. Any ideas?

**Comment by nik9000** [comment]
So normally we'd bounce you to the forums because this is totally "how types work" but it is a great example of why types are a problem. And you wrote such great reproduction steps it'd be a shame not to keep this here for people that find this issue in the future.

So, types are just a field added to the document and we automatically set up filters based on the URL. The whole point of types initially was to reduce the number of indexes you need because they have some overhead ([more](https://www.elastic.co/blog/index-vs-type)). The problem with types is that people think that they partition the data internally somehow. They don't do that precisely because such partitions would come with fairly high overhead, both in memory to track the separate fields and on disk because the fields are sparse. This misconception is super common. I thought they worked that way until I really started hacking on Elasticsearch consistently and bumbled into how they are implemented. It was a total "ah ha!" moment.

And you are bumping up against the way that multi-term queries like phrase prefix work. They rewrite to a list of matching terms and then execute the query. This is because queries have to iterate in a particular order that isn't compatible with walking the terms dictionary at query time. At least, not compatible without doing some serious tricks.

This is why we're slowly [migrating away from types](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/removal-of-types.html). They are just confusing. In the future, if you want a field to use as a filter you should declare a keyword field and filter on it. If you want separate fields then use a separate index. You can't quite do that with parent/child (replaced by [`join`](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/parent-join.html) fields), but joins come with compromises.

One last this. This:
> After the phrase_prefix query on the whole shard is complete, it discards any matches with types that do not match the type requested in the URL.
isn't 100% correct. The rewrite is indeed done first but the rewritten phrase prefix query and type filter are interleaved. The actual order is a bit complicated because of the phrase bit, but the upshot is that you *mostly* get the benefit of whichever filter is sparser.
