### ISSUE TITLE
Add soft limit on number of tokens produced by analyzers

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#27038]
Per discussion with @jpountz , it is unlikely that we can implement a circuit breaker on the memory used by the _analyzer api when generating tokens.  But we may be able to implement a soft limit on the number of tokens produced which is directly related to memory usage.

**Comment by mayya-sharipova** [comment]
@colings86 What should a reasonable default limit on number of tokens? Will 10000 be a good limit?
Also, should we throw an error when number of generated tokens exceeds this limit, or should we silently stop producing more tokens when the limit is exceeded?

**Comment by jpountz** [comment]
> Will 10000 be a good limit?

10k sounds good to me.

> should we throw an error when number of generated tokens exceeds this limit, or should we silently stop consuming more tokens when the limit is exceeded?

Ignoring tokens silently sounds trappy to me. I would rather fail the request.

**Comment by s1monw** [comment]
what is the plan here to use this limit. will we only limit highlighting usecases of also on indexing? I wonder if we should only do this for highlighting for now.

**Comment by mayya-sharipova** [comment]
I was thinking it only applies to `_analyze` API, as it is originated from this issue.

**Comment by colings86** [comment]
I was thinking that this should apply to anywhere we use analyzers at search time. So the `query_string_query`, `match` query` , etc. would apply this limit when analysing the query to stop queries that expand into massive number of tokens from running, and it would also apply to highlighting as @s1monw mentioned and the _analyze API could use this limit too as @mayya-sharipova mentioned

**Comment by jimczi** [comment]
We had a chat with @colings86 and @mayya-sharipova about this and decided that it would be difficult to apply the same limit to queries and highlighters.
For queries, it should be simpler to limit the size of the input to a few kbytes and get done with it since we don't want/need to handle big queries in `query_string` or `match` queries.
For highlighters, the main issue is when the field is not indexed with `offsets` nor `term_vectors`. In such case we need to re-analyze the text to extract the offsets of the matching terms and this can create a lot of tokens if the text to analyze is big. So instead of adding a soft limit, we've decided to add a new feature in the highlighter that would limit the number of tokens that should be considered during the re-analysis. When this limit is reached the remaining tokens are discarded and a flag should be added in the response to indicate that the highlighting response for this hit is partial.
This issue originated from an highlighting issue with big texts so I am closing it in favor of https://github.com/elastic/elasticsearch/issues/27517 that will try to address the problem differently.

**Comment by jpountz** [comment]
> This issue originated from an highlighting issue with big texts

This is not correct. :) This issue originated from an admin who wanted to prevent callers of the `_analyze` API from making the cluster run out-of-memory. So I think we should keep it open and address it?

**Comment by jimczi** [comment]
Oups I mixed two cases then sorry. Let's reopen, sorry for the noise I got confused with the comments.

**Comment by jimczi** [comment]
So let's just add a limit for the `_analyze` endpoint and fails the request if the number of produced tokens hits the limit:
@mayya-sharipova @colings86 ^^
