### ISSUE TITLE
Number of fragments in highlight field mapping

### ISSUE THREAD

**Issue by cexmmaqsood** [elastic/elasticsearch#27057]
**Elasticsearch version**: 5.4

**Description of the problem including expected versus actual behavior**:

In 1.7, I was able to define the property `number_of_fragments` in the field mapping. In the documentation examples I see, this property is always set in the query. When upgrading to 5.4, I started getting the following error:
`Mapping definition for [fields] has unsupported parameters:  [number_of_fragments : 0]`

Is defining that property in the field mapping no longer supported in 5.4?

**Steps to reproduce**:
 1. Create field mapping with `number_of_fragments` property set

**Provide logs (if relevant)**:
`Mapping definition for [fields] has unsupported parameters:  [number_of_fragments : 0]`

**Comment by tvernum** [comment]
Hi @cexmmaqsood 

Elastic uses GitHub issues for tracking bugs and feature requests. For questions such as these, we ask that you use our [discuss forum](https://discuss.elastic.co/) instead.
The forum is better suited to providing this sort of support.

Since 5.4 is working as documented, I hope you dont mind if I close this issue, and leave the dicussion to the forums.

Thank you.

**Comment by cexmmaqsood** [comment]
@tvernum I would think this is an issue just because it's something that works on a previous version, doesn't work on a newer version, and isn't documented.
