### ISSUE TITLE
Incorrect Documentation: nested_path

### ISSUE THREAD

**Issue by lukas-gitl** [elastic/elasticsearch#27098]
It is not clear when one should use `nested_path`. We've had some issues with this. More details in next post.

**Comment by MacMcIrish** [comment]
The issue was actually not related to boolean search, but to nested search. Here is a short outline of the problem and our solution.

We would like to request the documentation (https://www.elastic.co/guide/en/elasticsearch/guide/current/nested-sorting.html) to be updated to better reflect how and when someone should use the `nested_path`

It's mentioned that the field is mandatory in https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html , but very few examples show it's use.

Our test data: [data.txt](https://github.com/elastic/elasticsearch/files/1412508/data.txt)

Our test schema: [schema.txt](https://github.com/elastic/elasticsearch/files/1412509/schema.txt)

Our test query: [query1.txt](https://github.com/elastic/elasticsearch/files/1412519/query1.txt)

Resulted in : [result1.txt](https://github.com/elastic/elasticsearch/files/1412520/result1.txt)

Note the negative integer under `sort`.


Changing the query to : [query2.txt](https://github.com/elastic/elasticsearch/files/1412521/query2.txt)
(Note the newly added "nested_path" field)
Resulted in : [result2.txt](https://github.com/elastic/elasticsearch/files/1412522/result2.txt)

**Comment by jimczi** [comment]
Thanks @MacMcIrish and @lukas-gitl and sorry for the (very) late reply. The negative value in the first example is the default value that we use when the field is missing in the document. It's happening because the field is nested but the `nested` context is missing so we search the value inside the root document. The `nested` value is correctly extracted in the second example where the `nested` context is correctly set. I opened https://github.com/elastic/elasticsearch/pull/42809 to throw an exception if a nested field is used in a sort specification without the `nested` context and added a note in the documentation regarding this behavior.
