### ISSUE TITLE
have an query/aggregation execution plan and avoid dispatch requests to nodes/shards whenever is possibl

### ISSUE THREAD

**Issue by rcrezende** [elastic/elasticsearch#27103]
By running a top_hits aggregation I realized that some query optimizations could be applied.

I ran:
```
"aggs": {
	"autogen_by_kibana": {
	  "top_hits": {
		"docvalue_fields": [
		  "field_xyz"
		],
		"_source": "field_xyz",
		"size": 1,
		"sort": [
		  {
			"field_xyz": {
			  "order": "desc"
			}
		  }
		]
	  }
	}
...
}
```

and sorted the top hit by field_xyz, which is not on every index.
But as part of the request we filter with:

```
{
  "exists": {
	"field": "field_xyz"
  }
}
```

But response fails execution on every shard when field_xyz is not present.

> No mapping found for [field_xyz] in order to sort on

Would be possible to not even dispatch the query to those shards since no record will match anyway?

Running ES 5.4.

That said, I see two points here:

1. normalize mappings: I can certainly act on this and fix it, not sure what additional feature on ES would improve that without user intervention.
2. load/dispatch requests only to needed nodes/shards: this seems to benefit ES overall through a query execution plan/optimization phase (for both regular search and aggregations) before dispatching the tasks. This error wouldn't even exist, but better than that may be the performance gain on coordinating.

**Comment by jpountz** [comment]
Mappings are only materialized on the shards, not necessarily on the coordinating node. While we could change it in order to make your suggestion work, the gain is almost certainly not worth the effort. Round-trips are cheap in a local network, and the shard request will be cheap if one filter doesn't match any docs.

You can fix your problem by using the `unmapped_type` option.
