### ISSUE TITLE
RecoveryFailedException after deleting many index

### ISSUE THREAD

**Issue by zzt93** [elastic/elasticsearch#27314]
**Elasticsearch version** (`bin/elasticsearch --version`): 5.6.1

**Plugins installed**: [xpack, analysis-icu, analysis-smartcn, analysis-ik]

**JVM version** (`java -version`):1.8.0.45

**OS version** (`uname -a` if on a Unix-like system):
Linux ubuntu-100 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
After deleting many index, ES reports `RecoveryFailedException` repeatedly. Do I make any mistakes that make ES trying to recover those index?

**Provide logs (if relevant)**:
[log file](https://gist.github.com/zzt93/401a668bad9262a83643080a9175739e)

**Comment by jimczi** [comment]
>  Do I make any mistakes that make ES trying to recover those index?

I don't know, can you share the requests that you sent and the actions that you did on the node ?
It is not possible for us to reproduce your issue if we don't know the exact scenario where this happened.

**Comment by bleskes** [comment]
This is an expected behavior if you delete an index will it is being recovered from local files, for example, if open a closed index and then delete it while it's being allocated. It's fine if this happens a few times (one per primary shard) and then settles down. If this is not the case, please open a discussion on the forums at discuss.elastic.co and we can figure it out.
