### ISSUE TITLE
Chain multiple search requests to pass results from the first query to a subsequent query

### ISSUE THREAD

**Issue by dougnelas** [elastic/elasticsearch#27315]
It would be very useful to be able to chain search queries together in such a way that results from the first query could be used in the second query.  For example, let's say I construct the first query to return a list of ids, terms, etc.  and then be able to have these results passed to the second query, for example the list of ids could be used to return the documents that matched the ids from the first.  Today, this requires intervention from a client within the application code and results in having to make multiple search requests to obtain the final result.  Let's say for example I have a separate index for attributes.  I can search the index to find a list of attributeIds.  I could then use this list of ids in a filter against another index to return items which have this attribute associations.

**Comment by jimczi** [comment]
I marked this issue with the discuss label to gather more feedbacks but IMO this kind of feature should be implemented on client side. It requires to send multiple requests to Elasticsearch but you have full control on the queries and how you want to chain them.

**Comment by jimczi** [comment]
@dougnelas I misunderstood your issue the first time.
This was discussed several times:
https://github.com/elastic/elasticsearch/issues/6769
https://github.com/elastic/elasticsearch/pull/3278
See the number of comments in the pull requests. 
We don't have any plan to support such feature mainly because it would only work if the list of ids to retrieve is small. We don't support streaming so if the first query needs to retrieve 1M ids this won't scale. Assuming the first query works, sending a query with tons of ids won't work either.
Instead I'd suggest you to modelize your data to cope with Elasticsearch nature. You can denormalize your data and index the attributes directly in the main index.

**Comment by maxnilz** [comment]
mark
