### ISSUE TITLE
index _settings should return which templates created the index

### ISSUE THREAD

**Issue by jpcarey** [elastic/elasticsearch#27321]
**Describe the feature**: I would be useful to have the templates that created an index stored in the index metadata somehow, so it could be returned from the `GET index/_settings` api. Currently, this information is only contained in the log file - but the typical lifespan of an index is far greater than the logs retention.

Current log entry
`[2017-11-08T07:02:59,817][INFO ][o.e.c.m.MetaDataCreateIndexService] [1g9MtQh] [logstash-00001] creating index, cause [auto(bulk api)], templates [logstash, makelogs_index_template__logstash-], shards [1]/[0], mappings [_default_]`

It would also be useful that if the template contains a versioning number, that number is appended to the information logged. Example: `logstash@50001`

Example of what `_settings` return should look like (added `creation_type` and `templates`:
``` json
{
  "logstash-00001": {
    "settings": {
      "index": {
        "refresh_interval": "5s",
        "number_of_shards": "1",
        "provided_name": "logstash-00001",
        "creation_date": "1510149779809",
        "creation_type": "auto(bulk api)",
        "templates": ["logstash@50001", "makelogs_index_template__logstash-"],
        "analysis": {
          "analyzer": {
            "makelogs_url": {
              "type": "standard",
              "max_token_length": "1000",
              "tokenizer": "uax_url_email"
            }
          }
        },
        "number_of_replicas": "0",
        "uuid": "QFWJGBWFTymqQ5g2G7O2Yw",
        "version": {
          "created": "5060399"
        }
      }
    }
  }
}
```

**Comment by jasontedor** [comment]
The problem with placing this in the index settings (or index metadata) is that the underlying templates could have changed (or have been removed) since the time the index was created via the template. I think a log message is appropriate as there's an understanding that log messages are ephemeral, and I am not keen to move or duplicate "logging" in index settings (or index metadata).

**Comment by jpcarey** [comment]
@jasontedor I understand the templates can change, and can understand your point that this could cause confusion with it permanently stored in the index settings / metadata. It just becomes difficult when the log message can be gone in as little as a couple days - but knowing the templates involved at creation is better (even if they have been updated, which can be discovered through comparing the template vs. mapping) than not knowing at all in my opinion.

**Comment by jasontedor** [comment]
I would like to explain a little bit about our philosophy here. Every feature comes with weight added on the system. This one I suspect is being requested because it might have once helped debugging some problem (please clarify if my assumption here is wrong, I don't otherwise see a use to this except for debugging). We can not simply go add features every time something might have one time been useful, it has to have broader usefulness and in general not come with caveats, gotchas, or leniency (we will sometimes use the pejorative "trappy"). When we take a feature on, we carry the weight of the code (e.g., maintaining it), we carry the weight of documenting and supporting the feature, and carry the weight of not breaking its use cases (both the intended and unintended ones). The case has to be made then: is the benefit of the feature worth this weight? For this one I am not seeing it. It comes with caveats, and it's logging ephemeral information in a place where we do not normally log ephemeral information. It's trying to solve a problem (log messages might be gone) that is a much broader problem than this specific log message for which the general solution should absolutely not be shove log messages into metadata. Since this is not how we would solve the general problem, I think we shouldn't solve the specific problem here this way either, especially given the caveats about its use.

**Comment by jasontedor** [comment]
We discussed this in Fix-it-Friday and agreed that we should not add this.
