### ISSUE TITLE
Snapshot and restore queue

### ISSUE THREAD

**Issue by redlus** [elastic/elasticsearch#27353]
Hey

We've been trying to automate index snapshot creation through the elasticseasrch snapshot API. However, we get an exception when trying to run more than one snapshot in parallel:
`elasticsearch.exceptions.TransportError: TransportError(503, 'concurrent_snapshot_execution_exception', 'a snapshot is already running')`

This is an odd behavior, as elasticsearch already has many queues for many of its operations - and I'd expect the same for snapshots and restores. I understand there is a technical limitation for actually running two snapshots concurrently, but I think it would be a good idea to have elasticsearch add snapshots requests to a queue, automatically executing each snapshot as the previous finished running.

**Comment by imotov** [comment]
This is an interesting idea. We should definitely consider it for snapshot redesign, unless we go with the continues backup idea, in which case this is not going to be applicable.

**Comment by s1monw** [comment]
we spoke about this and decided that we don't want to add a queue since it's nice to give feedback to the user immediately that we can't run more than one snapshot. There is also the fact that we don't queue long running processes and this one would be an exception.

**Comment by packetrevolt** [comment]
Specific to using this in the typical ELK stack logging solution we have found the lack of a snapshot/restore queue to be confusing and a major limitation.

Automation tools that create snapshots need to either wait until completion and then run the next snapshot creation sequentially (Curator) or continually retry the snapshot creation task until successful.  The sequential creation of snapshots can get derailed should there be a failure during the process (the server running the snapshot creation tasks getting rebooted for example) and necessary logic introduced to verify that snapshots were indeed created and/or restarting from where the sequential task left off at.  This has led to mostly using the continual retry method where independent snapshot jobs all continually attempt to create snapshots until they are successful.  It works, but it is very messy and less then idea.  This is especially problematic if you want to give certain users the ability to create a snapshot in a cluster where there are continual background snapshot tasks running throughout the day, a user either has to get lucky and create a snapshot when no other one is running or the user has to resort to scripting a loop for the snapshot creation request that continues to loop until successful.

Restores are particularly painful.  Data is rolled off into snapshots for long term retention of logs, a few months are kept active in the cluster and everything older is snapshotted and deleted.  Users sometimes need to go back to back and reference the data that was archived off in snapshots which means it needs to be restored.  This runs into the same problem above in that there is no queue for snapshot tasks in Elasticsearch so a user is either left trying to manually restore a snapshot repeatedly until successful, or writing a script that loops indefinitely until successful.  How does a user get his restore to happen sooner?  Have the script loop once per second of course!! since the snapshot API is first come first serve.

**Comment by DaveCTurner** [comment]
There is still interest in this issue from time to time, particularly with users wanting to enqueue restore jobs. Snapshots are normally a periodic cluster-wide activity so it doesn't make so much sense to queue them up, but restores are more ad-hoc and typically only focus on a few indices so a bit of asynchrony might be useful.

As of 6.6.0 Elasticsearch now supports [concurrent restores](https://github.com/elastic/elasticsearch/pull/36397). A user can trigger multiple the restores at once and Elasticsearch will throttle the corresponding recoveries, effectively enqueueing the restoration of each shard until it has the capacity to handle it.

However Elasticsearch still forbids restores occurring concurrently with either taking or deleting a snapshot. We recommend taking frequent incremental snapshots, which can make it challenging to find a good time to perform a restore.

**Comment by redlus** [comment]
@DaveCTurner these are good news. I'd have to ask, though. I'd expect only the relevant shards to be locked for concurrent snapshot actions. Is there a technical limitation to performing snapshots/restores which do not touch the same shards, or is it just plain code?

**Comment by DaveCTurner** [comment]
> is it just plain code?

"Just" is just the worst word :grin: There are some quite significant obstacles.

**Comment by johanmha** [comment]
@DaveCTurner have there been any new discussion on the theme of a snapshot queue? I can see several people on the internet argue that it is better to simply take one large snapshot. However, one might as well argue that one large snapshot of the whole cluster leaves you vulnerable to user errors, for example someone manually deleting the container with snapshots, or to errors such as the snapshot or container being corrupt. If you implement different snapshots for different bulks of indexes, this would help to even further mitigate potential risks. 
Any input would be highly appreciated.

**Comment by DaveCTurner** [comment]
@johanmha I think the implementation is complete now so there's nothing left to discuss.

It's generally best to put all your snapshots in one repository rather than spreading them around, since it's going to be painful to reconstruct your cluster from multiple snapshots in different repositories after a disaster. There's no technical reason not to do this, it's just a bad idea. We can't really offer much advice on protecting a repository from damage (whether malicious or accidental) - it's up to you to apply appropriate access controls and monitor your disks for errors and so on.

**Comment by packetrevolt** [comment]
The lack of some sort of snapshot queue is an ongoing problem for us.  It is to the point that if there was a third party plugin available we would buy it. 

On average if we use a single big snapshot job it takes about 7 hours and runs at about 2TB per hour.  Different sets of data have regulatory or legal requirements for different sets of data which require different snapshot jobs and in actuality we are running snapshot jobs nearly 24x7.   Keeping several sets of jobs scheduled so they don’t stomp on each other is not fun.  Dedicating 2 hours of staff time per day and a big Excel sheet to try and keep it all sorted, plus automated scripting to retry failed jobs.   Time consuming and poorly working hack, but not many other options.

**Comment by DaveCTurner** [comment]
> Keeping several sets of jobs scheduled so they don’t stomp on each other is not fun.

... or necessary? You can run snapshots in parallel these days.

**Comment by johanmha** [comment]
Thanks for the prompt reply, and the clear cut advise!

**Comment by DaveCTurner** [comment]
This conversation isn't really on-topic for a Github issue so I suggest we continue it over on the [discussion forum](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6). I won't be replying here any more, but feel free to link to your forum thread below.

**Comment by johanmha** [comment]
Link to discussion forum as requested: 
https://discuss.elastic.co/t/taking-several-snapshots-in-parallell/257054
