### ISSUE TITLE
[CI] 6.x packaging tests failing on Fedora

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#27372]
The [6.x packaging tests](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+packaging-tests/) are consistently failing on Fedora. The first build that failed here was [303 at 2017-11-13T18:22Z](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+packaging-tests/303/) but there were other failures going back to [292 at 2017-11-10T02:18Z](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+packaging-tests/292/) so it's hard to pinpoint a bad commit.

```
not ok 213 [UPGRADE] start old version
not ok 213 [UPGRADE] start old version
# (from function `wait_for_elasticsearch_status' in file /project/build/bats/utils/utils.bash, line 426,
# (from function `wait_for_elasticsearch_status' in file /project/build/bats/utils/utils.bash, line 426,
#  from function `start_elasticsearch_service' in file /project/build/bats/utils/utils.bash, line 312,
#  from function `start_elasticsearch_service' in file /project/build/bats/utils/utils.bash, line 312,
#  in test file /project/build/bats/tests/80_upgrade.bats, line 58)
#  in test file /project/build/bats/tests/80_upgrade.bats, line 58)
#   `start_elasticsearch_service' failed
#   `start_elasticsearch_service' failed
# Making sure elasticsearch is up...
# Making sure elasticsearch is up...
# --2017-11-13 19:04:32--  http://localhost:9200/_cluster/health
# Resolving localhost (localhost)... ::1, 127.0.0.1
# --2017-11-13 19:04:32--  http://localhost:9200/_cluster/health
# Resolving localhost (localhost)... ::1, 127.0.0.1
# Connecting to localhost (localhost)|::1|:9200... failed: Connection refused.
# Connecting to localhost (localhost)|127.0.0.1|:9200... failed: Connection refused.
# Connecting to localhost (localhost)|::1|:9200... failed: Connection refused.
# Connecting to localhost (localhost)|127.0.0.1|:9200... failed: Connection refused.
# Retrying.
# 
# --2017-11-13 19:04:33--  (try: 2)  http://localhost:9200/_cluster/health
# Connecting to localhost (localhost)|::1|:9200... failed: Connection refused.
# Retrying.
...
:qa:vagrant:vagrantFedora26#packagingTest FAILED
REPRODUCE WITH: gradle :qa:vagrant:vagrantFedora26#packagingTest -Dtests.seed=2321C67D5DCE7378 
:qa:vagrant:vagrantFedora26#packagingTest (Thread[main,5,main]) completed. Took 7 mins 2.216 secs.
:qa:vagrant:vagrantFedora26#halt (Thread[main,5,main]) started.
:qa:vagrant:vagrantFedora26#halt
Putting task artifact state for task ':qa:vagrant:vagrantFedora26#halt' into context took 0.0 secs.
Executing task ':qa:vagrant:vagrantFedora26#halt' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
Starting process 'command 'vagrant''. Working directory: /var/lib/jenkins/workspace/elastic+elasticsearch+6.x+packaging-tests/qa/vagrant Command: vagrant halt fedora-26
Successfully started process 'command 'vagrant''
==> fedora-26: Removing cache buckets symlinks...
==> fedora-26: Attempting graceful shutdown of VM...
:qa:vagrant:vagrantFedora26#halt (Thread[main,5,main]) completed. Took 7.58 secs.

FAILURE: Build failed with an exception.
```

@tlrx you fixed one issue with this build in d4b7f7a58d39f55d27214e3796f9be95e23ae245, could you have a look at this too?

**Comment by DaveCTurner** [comment]
Possibly related to #27340 and thence to #25003.

**Comment by tlrx** [comment]
Failures from [build 292](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+packaging-tests/292/) to [build 302](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+packaging-tests/302/console) inclusive are all related to the POI version fixed in https://github.com/elastic/elasticsearch/commit/d4b7f7a58d39f55d27214e3796f9be95e23ae245.

I suspect that for the 303 and 304 builds the vagrant box was so slow so it took more than 60 sec to check that elasticsearch correctly started. I increased the timeouts to 120 sec in Failures from [build 292](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+packaging-tests/292/) to [build 302](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+packaging-tests/302/console) inclusive are all related to the POI version fixed in https://github.com/elastic/elasticsearch/commit/d4b7f7a58d39f55d27214e3796f9be95e23ae245 and since the builds are green again I don't think we need to do more than that.
