### ISSUE TITLE
Crash of elasticsearch node

### ISSUE THREAD

**Issue by pavel-sbor** [elastic/elasticsearch#27423]
**Elasticsearch version** (`bin/elasticsearch --version`): Version: 2.3.3, Build: 218bdf1/2016-05-17T15:40:04Z, JVM: 1.8.0_121

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_121

**OS version** (`uname -a` if on a Unix-like system): Linux 3.10.0-327.22.2.el7.x86_64
Red Hat Enterprise Linux Server release 7.3 (Maipo)

**Description of the problem including expected versus actual behavior**:
One node of elasticsearch claster unexpectedly crashed. 
It's not a single case, node's crashes happen time after time.

**Steps to reproduce**:

Actually it's difficult  to say how to reproduce it, because no special actions were made.
Probably logs will help to understand the situation.

**Provide logs (if relevant)**: [logs.tar.gz](https://github.com/elastic/elasticsearch/files/1479605/logs.tar.gz)

**Comment by spinscale** [comment]
A segmentation fault is occuring during what seems a search request. This can hint at faulty hardware (i.e. memory). Is this a VM or a bare metal system?

You could try to upgrade to the latest JVM and maybe a newer Elasticsearch (as 2.3.3 is pretty old), but you should try to run on different hardware first and see if the problem remains.

**Comment by pavel-sbor** [comment]
Thanks!
This is a VM.

**Comment by jpountz** [comment]
This is likely an Elasticsearch bug due to a read on a closed mmap'ed file. Like @spinscale said, this is a pretty old version of Elasticsearch and this is a problem that got improved/fixed in the 5.x series.

If an upgrade is not an option for you, as a workaround for now you can switch to the `niofs` store instead of the default store which will fail with an exception and keep the cluster running instead of killing the JVM. See https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-store.html#file-system.
