### ISSUE TITLE
Post-Ingest Failure Handler

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#27486]
This is a feature request that would enable `ingest` to be used as a handler for failed indexing attempts. The use case is straight forward:

Imagine that you have a lot of data (e.g., logging) that has a mostly-stable format. However, from time-to-time, there are changes that can come in that need to be manually cleaned up. Instead of requiring that the  user setup error handling in their clients to reroute the failed document(s), a post-ingest processor could be executed.

This would make it trivial to send documents that fail to be indexed to a dead letter queue. Ideally the handler would itself be an ordinary ingest processor, thus behaving in the same way that they do without too much effort.

**Comment by s1monw** [comment]
We discussed this in fixit friday and decided to not do this since we believe that error handling should happen on the client side. It's also has some implication that are non trivial and hard to get right. For instance:

 * how many failed requests do we queue and do we reject falied ones at some point
 * how do we handle this if the request is handed on a node that is not an ingest node?
 * what do we do if a failed request failed again, do we apply another ingest processor?

I think net net it's to complicated
