### ISSUE TITLE
Completion suggester with supports for a query statement

### ISSUE THREAD

**Issue by nithril** [elastic/elasticsearch#27513]
Hello,

**Describe the feature**:

The purpose will be to filter/boost the completion suggester result based on a query.

For example, an user makes a search with this input "elasticsearch suggester **comple**".

It can make sense to boost completion results for "comple" based on the preceding terms of the query. Eg. to promote completion for document that have a titles that contain "elasticsearch suggester"

```
{
  "query": {
    "query": {
      "query": "elasticsearch suggester"
    }
  },
  "_source": "titles_suggest",
  "suggest": {
    "titles": {
      "prefix": "comple",
      "completion": {
        "field": "titles_suggest",
        "size": 10
      }
    }
  }
}
```

Does it make sense?

**Comment by jimczi** [comment]
The completion suggester is supposed to be fast, lightning fast. Adding a query to filter the results will inevitably slow down the process since the completions are built in a data structure that is decorrelated from the index itself (it is not possible to run conjunctions efficiently). Though this functionality exists in the library that we use (the completion suggester is in Lucene) but it is not designed to be used with random queries but rather with a filter query that is reused among the suggestions query. 
For these reasons I think that it would be better for you to use a regular field to build your "custom" suggester. You could for instance use the `edge_ngram` filter to perform fast prefix queries and use the `query_string` or the `match` query to build a query that handles prefix on the last term.

**Comment by nithril** [comment]
From my understanding, the fundamental difference is that the completion suggester returns suggestions whereas a regular query will not return suggestions but the whole matching document.

So yes the document will match, but then how to extract the matching term?

**Comment by jimczi** [comment]
The completion suggester in es 5 is document-based, it returns documents, not suggestions so the issue is the same. The completion field contains the entire suggestion and the completion query will return documents that match, then you can extract the suggestions from the completion field inside the `_source`.

**Comment by nithril** [comment]
Sorry but the completion suggester return suggestion [cf. the documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-completion.html) 

In the above example, it returns "nirvana"

```
{
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "skipped" : 0,
    "failed" : 0
  },
  "hits": ...
  "took": 2,
  "timed_out": false,
  "suggest": {
    "song-suggest" : [ {
      "text" : "nir",
      "offset" : 0,
      "length" : 3,
      "options" : [ {
        "text" : "Nirvana",
        "_index": "music",
        "_type": "song",
        "_id": "1",
        "_score": 1.0,
        "_source": {
          "suggest": ["Nevermind", "Nirvana"]
        }
      } ]
    } ]
  }
}
```

Is there a misunderstood?

**Comment by jimczi** [comment]
Sorry I see how this can be misleading. It returns the suggestion value that match inside the document, so if you have two values for the suggestion field it will return the value that match in the `suggest` field but the result is a document. You can have multiple documents that contain the same suggestions and in such case the suggester will return one hit per matching document.

Regarding your example, the completion suggester considers **all** terms in the query `elasticsearch suggester compl` so it's unclear to me why you would need to boost documents that match `elasticsearch suggester`.
 
Can I ask you to open a new topic in the forum:
https://discuss.elastic.co/c/elasticsearch 
No need to answer in this issue, we'll be happy to help in the forum, it's a better place to handle this discussion.
