### ISSUE TITLE
Remove `index.optimize_auto_generated_id`

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#27583]
We are happy with auto-ID optimization and we can now remove the `index.optimize_auto_generated_id` setting.

**Comment by gokberksahin** [comment]
Hello, i started to work on this since PR hasn't been accepted and has conflicts.

**Comment by gokberksahin** [comment]
I'm curious, how can i solve issues like this quickly, source code is too long nobody can't read it all so how to find related files to this issue, i used grep -R command but is there another way?

**Comment by bleskes** [comment]
@gokberksahin  Grep indeed for the the setting string and the you'll find
the java source code in which it's defined (some instance of Setting). From
there you can use an IDE to see where setting instance is used.

**Comment by videetssinghai** [comment]
Hello is this issue still open?

**Comment by videetssinghai** [comment]
hey @clintongormley how do i go ahead with this?

**Comment by javanna** [comment]
@videetssinghai yes the issue is still open, but @liketic is already working on it. See #27600 and #28862 .

**Comment by videetssinghai** [comment]
I can work on this if nobody is working

**Comment by MorTD** [comment]
Is this still active?  I see #27600 and #28862 but don't understand if they're done or not

**Comment by danielmitterdorfer** [comment]
The plan to remove this setting is as follows (as outlined in https://github.com/elastic/elasticsearch/pull/27600#issuecomment-368556651):


* [x] deprecate in 6.x #28862
* [ ] prevent the ability to modify this setting on indices created since 7.0.0  - #28895
* [ ] remove this setting completely in 8.0.0 #27600

**Comment by lign0** [comment]
Now I have an issue with "index.optimize_auto_generated_id" configured on version 7.6.0 to optimize ES performance: "true", because of some other reason, the cluster was rolled back, causing all index to become red. Now I want to remove the configuration "index.optimize_auto_generated_id", but the message is obsolete and will not be called. Is there any way to solve this problem

**Comment by lign0** [comment]
Now I have an issue with "index.optimize_auto_generated_id" configured on version 7.6.0 to optimize ES performance: "true", for some other reason, rolled back the cluster, causing all index to become red. Now I want to remove the configuration "index.optimize_auto_generated_id", but the warning message indicates that the configuration is obsolete and will not be called. Is there any solution to this problem
