### ISSUE TITLE
REST/YAML tests: Add equivalent of assertBusy() to framework

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#27699]
With the increased usage of REST and YAML tests there are also use-cases where a REST test needs to wait for something to happen in the background, be it a cluster state listener applied or resources added.

In order to not use the equivalent of `Thread.sleep` by waiting for a request to timeout (i.e. a health check with a too high number of nodes), we should maybe have something like `assertBusy` in our YAML test, that allows for repetitive checking of a query block to wait for something to happen without blocking a fixed amount of time.

A current workaround for this is to not write a YAML test but just extend from `ESRestTestCase` and use the java `assertBusy` in there.

**Comment by javanna** [comment]
Some philosophical questions: why do we have an increased usage of yaml tests? What is the advantage of writing yaml tests over Java tests? Yaml tests were created so that they could be run from the the different language clients. Are we adding yaml tests that the language clients won't ever run? What has changed compared to the initial goal of the yaml suite?

I think the answers to these would help clarifying if we should add more assertions to the yaml tests, or rather go with Java tests for these cases.

**Comment by spinscale** [comment]
We talked about this, and it makes sense to keep using `ESRestTestCase` in such cases, as they are much more likely feature tests and should not run when the client test things. The correct way would be to make sure all the APIs are supported in the high level rest client and use that one inside of `ESRestTestCase`
