### ISSUE TITLE
Change Default # Shards to 4 or 8

### ISSUE THREAD

**Issue by morphers82** [elastic/elasticsearch#27760]
So why is the default shard count for a new index 5?

With the Shrink API, having a shard count of 5 would only allow it to shrink to 1.
If the default was 4 or 8, that would give the opportunity for a person to shrink it from 
8 to 4 or 4 to 2 shards, and then from 2 to 1 shards.

On that note, maybe recommendations for number of shards should be partially based on this fact, so shard counts should be a multiple of 2, and or a number that is 2^n, ie 1,2,4,8,16,32,64 etc?

**Comment by s1monw** [comment]
@morphers82 first off, you are correct. When I added the split API and I realized you should have a prime number if you wanna use it 🤦‍♂️. Yet,  we had a ton of discussions internally what should be the default and there are multiple camps. Today since we have shard splitting I personally feel we should just go with 1 shard by default which is also a great starting point for capacity planning and scaling out. From 1 you can go to any number. I think we will make a call regarding the number of shards for ES 7 and I will update this issue once we did.

**Comment by jasontedor** [comment]
Closing as we are going to migrate to a different default number of shards, but it will not be 4 nor 8 (instead, 1).
