### ISSUE TITLE
Shard splitting / merging

### ISSUE THREAD

**Issue by ddorian** [elastic/elasticsearch#27809]
A way to grow/shrink an index by splitting/merging shards. 

In the future this could be done also automatically.

Solr already has it. Maybe the _routing function should be changed to achieve it.

Why not ?

**Comment by jkakavas** [comment]
Hi @ddorian 

Shard splitting is implemented in 6.1.0, please take a look at the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/6.1/indices-split-index.html#_splitting_an_index)

**Comment by ddorian** [comment]
Hi @jkakavas ,

I created the issue after seeing that. See "shard-splitting", but that is "index splitting".
Meaning, on shard-splitting::

1. index is alive and accepting changes
2. index is bigger than 1 node can keep (say you have 50 shards * 50GB)
3. only 1/some shards can be splitted 

See here for an old blog post that explains in solr: https://lucidworks.com/2013/06/19/shard-splitting-in-solrcloud/

**Comment by s1monw** [comment]
> index is alive and accepting changes

@ddorian we don't have any of the 3 point on our roadmap. We also don't thing that splitting an index/shard while it's accepting requests is what our system should do. We wanted to have a way to cleanly roll-back and that is basically copy on write in a very fast way. Today if you use the shards splitting feature it will be almost instant and no data-copying is required. It's absolutely safe with regards to data-loss and that is our main priority. 

> index is bigger than 1 node can keep (say you have 50 shards * 50GB)

For shard splitting you don't need to relocate it will work out of the box without moving any shards.

> only 1/some shards can be splitted

I don't think this will add much value since our assumption is that indices are balanced. if you need to distribute hotspots use a [routing partitioned index](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-routing-field.html#routing-index-partition)

**Comment by ddorian** [comment]
@s1monw I understand that it's a little troublesome to do it but ALL other systems do that: bigtable/hbase/cockroachdb, cassandra/scylladb, solr/vespa.ai . 

Also, the problem with routing partitioned index is that it does that for all `routing` values (even small tenants). While if you'd use _routing like solr, along with live shard splitting, you can also scale large tenants by just splitting the index.

Meaning, can we keep an issue open for live-index-splitting ?
