### ISSUE TITLE
`sum`, `stats` and `avg` aggregations should use Kahan summation

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#27807]
[Kahan summation](https://en.wikipedia.org/wiki/Kahan_summation_algorithm) gives better accuracy than naive summation. For instance when summing up N positive values, the relative error of Kahan summation is bound by `2^-52` while with naive summation, the error is linear with the number of values that are summed up.

**Comment by colings86** [comment]
One thing to note with this is the tradeoff for accuracy is that the memory required to store the sum for each parent bucket will be doubled (since we need to store the sum and the compensation value) and the number of operations to calculate the sum increase 4-fold. In practice this should not matter that much for these aggregations since their memory footprint is also nothing in comparison with other aggregations like percentiles, and the time for calculating the sum should still be low compared with the time to collect the doc value itself but I am mentioning it here in case its relevant for other places we may want to implement Kahan summation in the future.
