### ISSUE TITLE
field_value_factor case function_score equal 0 when it's long type

### ISSUE THREAD

**Issue by zjjott** [elastic/elasticsearch#27810]
**Elasticsearch version** (`bin/elasticsearch --version`):
"version" : {
    "number" : "5.3.2",
    "build_hash" : "Unknown",
    "build_date" : "2017-04-28T21:44:52.237Z",
    "build_snapshot" : false,
    "lucene_version" : "6.4.2"
  }

consider this mappings:
`PUT test`

```
{
    "mappings" : {
        "type1" : {
            "properties" : {
                "field1" : { "type" : "text" },
                "field2" : { "type" : "long" }
            }
        }
    }
}
```

and we can put some documents in it

```
PUT test/type1/1
{
    "field1" : "asd",
    "field2" : 0.7
}
PUT test/type1/2
{
    "field1" : "asd",
    "field2" : 0.8
}
PUT test/type1/3
{
    "field1" : "qwe",
    "field2" : 0.6
}
```

and when I search use function_score,such as:
```
{
    "size": 10,
    "query": {
        "function_score":{
            "query": {
                "term": {
                    "field1":"asd"
                }
            },
            "field_value_factor": {
                "field": "field2",
                "missing": 0
            }
        }
    },
    "from": 0
}
```

I get a result like this:

```
{
    "_shards": {
        "failed": 0,
        "successful": 5,
        "total": 5
    },
    "hits": {
        "hits": [
            {
                "_id": "2",
                "_index": "test",
                "_score": 0.0,
                "_source": {
                    "field1": "asd",
                    "field2": 0.8
                },
                "_type": "type1"
            },
            {
                "_id": "1",
                "_index": "test",
                "_score": 0.0,
                "_source": {
                    "field1": "asd",
                    "field2": 0.7
                },
                "_type": "type1"
            }
        ],
        "max_score": 0.0,
        "total": 2
    },
    "timed_out": false,
    "took": 2
}
```

we can see the `_score` field are all equal 0.0,further I found it depends on field_value_factor `missing` attr,just like this field1 not exist ,it's irrational. 
If I change the mapping to
```
{
    "mappings" : {
        "type1" : {
            "properties" : {
                "field1" : { "type" : "text" },
                "field2" : { "type" : "float" }
            }
        }
    }
}
```
MENTION:change field2 from long to float,it works.

I found there is not any mentioned in ES documents,may be it need to be fixed?

**Comment by colings86** [comment]
This is expected because your mapping is type long but you are indexing float values which will be truncated by default since the default value of the coerce parameter is `true`[1][2]. For an integer or long field, when coerce is true and a float value is indexed, Elasticsearch will truncate the value to make it a int/long value. If you don't want Elasticsearch to index float values for your integer/long fields then you should set coerce to false and the index operation will fail instead. If you want to index and use the field as a floating point value then you should use the float/double/half_float/scaled_float field type in your mapping

[1] https://www.elastic.co/guide/en/elasticsearch/reference/6.1/number.html
[2] https://www.elastic.co/guide/en/elasticsearch/reference/6.1/coerce.html

**Comment by zjjott** [comment]
@colings86 Thank you very much!
