### ISSUE TITLE
GeoIP ingest plugin to support ASN

### ISSUE THREAD

**Issue by kiawin** [elastic/elasticsearch#27849]
Hi, I would like to know if there is any accessible repository for ```org.elasticsearch:geolite2-databases``` that I could add GeoLite2-ASN.mmdb.gz to. Unable to access https://github.com/elastic/geolite2-databases (I found it in the pom)

The reason I'm asking this is because I'm currently working on ASN support for ingest-geoip plugin. I would need to update this module for unit testing purposes.

Thanks :)

**Comment by martijnvg** [comment]
@kiawin Thanks for opening this issue and working on this! I think opening that repository makes sense. However for now I opened a pr that upgrades ingest-geoip plugin's geolite2-databases dependency that also include the asn data based file (but not uses it), because it requires someone from the Elastic team to release this dependency.

**Comment by kiawin** [comment]
I saw the merge is completed in #27897. Not sure about the workflow for elasticsearch team, should I modify the title of this issue to "GeoIP ingest plugin to support ASN", or open a new issue?

I will work on the ASN code :)

**Comment by martijnvg** [comment]
@kiawin Whatever you prefer :)

**Comment by kiawin** [comment]
@martijnvg free to review? :D

**Comment by martijnvg** [comment]
@kiawin Thanks for the ping, I will take a look at it.
