### ISSUE TITLE
HTTP/1.1 406 Not Acceptable..content-type: application/json; 

### ISSUE THREAD

**Issue by AnwarAlg** [elastic/elasticsearch#27971]
After log stash forwards logs to elastic search,
elastic provides the below reply 

HTTP/1.1 406 Not Acceptable..content-type: application/json; charset=UTF-8..content-encoding: gzip..content-length: x x

I have used the standard template from elastic search website 

https://www.elastic.co/blog/how-to-centralize-logs-with-rsyslog-logstash-and-elasticsearch-on-ubuntu-14-04

what would be the issue. would beats be a better alternative?

**Comment by AnwarAlg** [comment]
I would like to mention that Elastic search is accepting content from winlogbeat but not from Logstash!

**Comment by DaveCTurner** [comment]
Hi @AnwarAlg! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a support question than a bug report. In particular, a bug report would need much more detail in order to help us try and reproduce what you're seeing, which isn't possible from the limited information you give above. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
