### ISSUE TITLE
Show client connections in Nodes Stats

### ISSUE THREAD

**Issue by robgil** [elastic/elasticsearch#28017]
While troubleshooting various clients, I'd like to be able to verify that they are properly connecting to all nodes in a cluster. I'd also like to be able to determine how many concurrent/open client connections there are to each node.

I'm not sure whether it should be in the full `GET /_nodes/stats` or perhaps something separate like `GET /_nodes/clients`.

Furthermore, this would allow me to see what TLS/SSL a client is connecting with, potentially list the last command, and whether its authenticated or not.

**Comment by DaveCTurner** [comment]
We discussed this request in Fix-it-Friday.

Firstly:
> ... properly connecting to all nodes ...

Clients don't connect to _all_ nodes at once, so we interpreted this to mean "... properly connecting to each node ...", i.e. that you want to loop through all the nodes and check that the client connects to each one individually. Is that what you meant?

Secondly, normally a connection from a client only lives for the duration of a single request, so we weren't sure that this'd be a useful thing to expose. The exceptions to this are transport clients and REST clients that use `Connection: keep-alive`. [The transport client is on its way out](https://www.elastic.co/guide/en/elasticsearch/client/java-api/6.0/client.html) and persistent HTTP connections are not commonly used. We concluded that this wouldn't be a sufficiently useful thing to expose to the API.

There's already various tools (particularly logging, and OS-level things like `lsof` and `netstat`) to help troubleshoot a connection problem if you find one.

**Comment by robgil** [comment]
WRT connecting to all nodes: in ECE and EC, requests are apparently load balanced. I don't know whether they are load balanced across all nodes, or just hit one node. I'm trying to determine that behavior, and my request was that I could look to see a list of client connections on ES.

WRT connections: Yes, we run keepalive everywhere to reduce overhead of instantiating a new connection with every request. 

WRT lsof/netstat: That assumes you have access to the host. With EC, you don't, which makes it hard to troubleshoot connection issues.

The other thing im trying to determine with this, is whether the host is getting saturated with connections, and just how many it has concurrently open. Similar to apache mod_status, in mongo (db.serverStatus() and db.serverStatus.connections), mysql (SHOW PROCESSLIST), and so on. Almost all other systems provide this information for monitoring.

**Comment by DaveCTurner** [comment]
I've raised your questions about Cloud with the Elastic Cloud team, but you might be better asking these again in [the ECE discussion forums](https://discuss.elastic.co/c/cloud-enterprise) or with [your EC support service](https://www.elastic.co/blog/announcing-support-for-elastic-cloud-hosted-elasticsearch-standard) as this sort of discussion tends to get lost in this issue tracker.

Note that `GET /_nodes/stats/http` returns the number of HTTP connections that are currently open, and the total number of connections ever opened.

Are you actually seeing problems that you think are related to too many connections to individual hosts? What are the symptoms you see? How many connections are you making to your cluster, and how many nodes do you have? Have you determined the number of connections that count as "saturated" and, if so, how?

Elasticsearch's networking model is quite different from those in Apache, MySQL and MongoDB. It makes a lot of sense to worry about saturating a host with connections when each connection corresponds to a thread, which is quite a limited resource. Connections in Elasticsearch are not like this.

**Comment by DaveCTurner** [comment]
I spoke about this with @robgil out-of-band. The ultimate origin of this request was a debugging session which we eventually determined to be because the client was sending a subtly malformed request by looking at packet captures. It turns out that this was reported as expected in the Elasticsearch logs but for various reasons we missed or misunderstood the vital messages. The confusion was compounded a little by the proxies that sit between Elasticsearch instances running in EC and the outside world: Elasticsearch dropped the connection as expected, but somewhere in the proxy layers this was turned into a 502 with a misleading message:

    {"ok":false,"message":"Unable to connect to the server."}

`GET /_nodes/stats/http` solves the "how many connections" question, and the "correctly connecting" question is solved by logs and client-side errors, as long as you are aware of their possible mutilation by intervening proxies. I expect that the logs are also useful in tracking down TLS and authentication issues but if there's something vital that's missing from the logs then we can consider that a separate bug.

I'm uncomfortable with the security implications of exposing the last command(s) issued on each connection via an API endpoint, and feel this is best determined from the logs too.
