### ISSUE TITLE
Inconsistent FuzzyQuery deprecation notice in docs

### ISSUE THREAD

**Issue by gskema** [elastic/elasticsearch#28035]
ES 5.0 and 5.1 say that **FuzzyQuery** is deprecated, but docs for newer versions (5.2 and up) do not have this notice. It this a mistake?

https://www.elastic.co/guide/en/elasticsearch/reference/5.0/query-dsl-fuzzy-query.html
https://www.elastic.co/guide/en/elasticsearch/reference/5.1/query-dsl-fuzzy-query.html

**Comment by jimczi** [comment]
The `fuzzy` query is not deprecated, we wanted to remove it at some point because it is possible to use the `match` query with the `fuzziness` parameter instead. Though the `fuzzy` query can be used in a `span` query so we've decided to un-deprecate and keep this query in the DSL.
See: https://github.com/elastic/elasticsearch/pull/22088
