### ISSUE TITLE
Support for Google S2 Library: Geometry on a Sphere

### ISSUE THREAD

**Issue by mveitas** [elastic/elasticsearch#28121]
**Describe the feature**:
I was curious to see if anyone has looked into the feasibility of adding support for [Google's S2](https://opensource.googleblog.com/2017/12/announcing-s2-library-geometry-on-sphere.html) library that allows for geometry on a sphere as an alternative to geohash

**Comment by DaveCTurner** [comment]
One advantage that S2 has over our existing geospatial indexing is that the its cells are much more consistent in size (and shape) across the whole globe which may permit more accurate bounds on the margin of error.

There's a couple of major drawbacks that I can see. Firstly, the Java implementation seems very much to be a second-class citizen at the moment:

> The Java port is based on the 2011 code and does not have the same robustness, performance, or features as the current C++ version.

Secondly, S2's straight lines are geodesics (great circles), whereas GeoJSON specifies that straight lines are straight in latitude-longitude space (i.e. in the equirectangular projection) so they will disagree on things like point-in-polygon queries if implemented in the "obvious" fashion. Geodesics make a bunch of sense for a variety of reasons, but I think we should strive to follow the spec here, and that sounds troublesome to achieve.

**Comment by DaveCTurner** [comment]
TIL that you can draw geodesics in Google maps, so here's an example of the difference it makes. These points form a perfectly fine polygon in GeoJSON:

<img width="600" alt="screen shot 2018-01-12 at 13 40 52" src="https://user-images.githubusercontent.com/5058284/34877560-771adcee-f79e-11e7-878b-e3501ed1ca99.png">

In S2 they don't define a valid polygon since it self-intersects:

<img width="766" alt="screen shot 2018-01-12 at 13 39 28" src="https://user-images.githubusercontent.com/5058284/34877614-9daaa5ce-f79e-11e7-9db5-01d8cf6e4bd8.png">

**Comment by jpountz** [comment]
Discussed in FixitFriday: this would have very deep implications on how we index geo shapes. Coincidentally, an issue was open recently about using it to index geo shapes, so I'm going to close this issue and recommend following https://issues.apache.org/jira/browse/LUCENE-8126.

@nknize I'd be curious to have your opinion, does it have a potential impact for the upcoming BKD-based geo-shape support?
