### ISSUE TITLE
Using CustomAnalyzer with multiple TokenFilters , EnglishMinimalStem is not getting applied

### ISSUE THREAD

**Issue by ajeetiiita** [elastic/elasticsearch#28154]
private Analyzer minimallyStemmedFullTextAnalyzer = CustomAnalyzer.builder().withTokenizer("standard").
            addTokenFilter("asciifolding").
           addTokenFilter("worddelimiter").
            addTokenFilter("lowercase").
            addTokenFilter("englishminimalstem").
            build();

used this CustomAnalyzer . All Token filters are working fine except  "englishminimalstem". I am calling 
String normalizedValue = minimallyStemmedFullTextAnalyzer.normalize("fieldname", "Bricks");
It is always returing "bricks". But I am expecting it to be "brick" as "englishminimalstem" is used.
Other TokenFilters are absolutely working fine.

**Comment by colings86** [comment]
`CustomAnalyzer.normalize()` will ignore any token filters that are not `MultiTermAware`. the "englishminimalstem" token filter is not `MultiTermAware` and as such will be ignored when you run this method.

Why are you wanting to call this method yourself? In order to use an analyzer on a field in your index you should create it in the index settings and then reference it in your mappings. See here for more information: https://www.elastic.co/guide/en/elasticsearch/reference/6.1/analysis-custom-analyzer.html.

I don't think it is intended that this class be used client side (/cc @jpountz )

**Comment by ajeetiiita** [comment]
@colings86  To answer your question.
Why are you wanting to call this method yourself?
In my system, I am writing Junit test cases to validate elasticsearch node behaviour. The elastic search is running on production and index mapping, Analyzer Settings are created manually . I have to verify whether Custom Analyzer that I am creating in above code snippet is actually mimicking production analyzer settings properly or not. The elasticsearch production machine is behaving correctly if I expect stemmed results out of a query string. But in Custom Analyzer as I explained above stemmming is not happening.

**Comment by jpountz** [comment]
@ajeetiiita Then the method you should call is `Analyzer.tokenStream`, not `Analyzer.normalize` which only applies a subset of the analysis chain.
