### ISSUE TITLE
My es5.5.2-cluster is always red.

### ISSUE THREAD

**Issue by leeningli** [elastic/elasticsearch#28214]
one of data-node is always red, its uptime upper 100.
my datanode:32c 128G.
my config as follow:
elasticsearch.yml
discovery.zen.ping.unicast.hosts: ["26.6.0.163:9310", "26.6.0.162:9310", "26.6.0.161:9310"]
discovery.zen.minimum_master_nodes: 2
gateway.recover_after_nodes: 5
http.max_content_length: 100mb
transport.tcp.compress: true
transport.tcp.port: 9300
discovery.zen.ping_timeout: 100s
discovery.zen.fd.ping_timeout: 100s
node.max_local_storage_nodes: 2
action.destructive_requires_name: true
indices.fielddata.cache.size: 5gb
indices.breaker.fielddata.limit: 40%
indices.breaker.request.limit: 60%
indices.breaker.total.limit: 70%
indices.requests.cache.expire: 5m
#use for head plugins
http.cors.enabled: true
http.cors.allow-origin: "*"

jvm:
-Xms30g
-Xmx30g
## GC configuration
#-XX:+UseConcMarkSweepGC
#-XX:CMSInitiatingOccupancyFraction=75
#-XX:+UseCMSInitiatingOccupancyOnly
-XX:+UseG1GC
-XX:MaxGCPauseMillis=200

other configs are default.

**Comment by tvernum** [comment]
Hi @leeningli
 
Could you please ask this question on our [discuss forum](https://discuss.elastic.co/c/elasticsearch) where we can provide better support. Those forums are designed to support the kinds of conversations that are necessary for this sort of troubleshooting and problem diagnosis.

Elastic uses GitHub issues for tracking clearly identified bugs and feature requests. Since there is no specific bug identifed in your issue, I'm going to close this ticket, but I'm sure someone will be able to help you work through this issue on the [forums]((https://discuss.elastic.co/c/elasticsearch) .

Thank you.

**Comment by leeningli** [comment]
thank you,i will close it.
