### ISSUE TITLE
Help,Please!

### ISSUE THREAD

**Issue by smithyj** [elastic/elasticsearch#28233]
How to count of nested elasticsearch inner_hits document

This is my query synatx:
```
GET zentrust_cn_test:label_user/_search
{
  "_source": [
    "_id",
    "inner_hits"
  ],
  "query": {
    "function_score": {
      "query": {
        "bool": {
          "must": [
            {
              "bool": {
                "must": [
                  {
                    "nested": {
                      "path": "interaction.activity",
                      "query": {
                        "function_score": {
                          "query": {
                            "bool": {
                              "must": [
                                {
                                  "match_phrase": {
                                    "interaction.activity.interaction": {
                                      "query": "讲"
                                    }
                                  }
                                },
                                {
                                  "script": {
                                    "script": "doc['interaction.activity.ref_id'].size() > 1"
                                  }
                                }

                              ]
                            }
                          }
                        }
                      },
                      "inner_hits": {}
                    }
                  }
                ]
              }
            }
          ]
        }
      }
    }
  }
}
```
How to count of nested elasticsearch inner_hits document

but I want to return count nested > 2 or more doc

```
{
  "took": 3,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 0,
    "max_score": null,
    "hits": []
  }
}
```
I very thank you much!

**Comment by tvernum** [comment]
Could you please ask this question on our [discuss forum](https://discuss.elastic.co/c/elasticsearch) where we can provide better support. Those forums are designed to support the kinds of conversations that are necessary for this sort of troubleshooting and problem diagnosis.

Elastic uses GitHub issues for tracking clearly identified bugs and feature requests. Since there is no specific bug identifed in your issue, I'm going to close this ticket, but I'm sure someone will be able to help you work through this question on the [forums]((https://discuss.elastic.co/c/elasticsearch) .

Thank you.

**Comment by smithyj** [comment]
Please see [`https://discuss.elastic.co/t/how-to-query-count-of-nested-elasticsearch-inner-hits-document/115622`](https://discuss.elastic.co/t/how-to-query-count-of-nested-elasticsearch-inner-hits-document/115622)

**Comment by smithyj** [comment]
@tvernum
