### ISSUE TITLE
Rescore and Sort doesn't work together in elasticsearch 6

### ISSUE THREAD

**Issue by aslamy** [elastic/elasticsearch#28250]
In Elasticsearch 6 rescore and sort doesn't work together. There is no information about this breaking changes.
Using sort and rescore together gives this exception:
```
"reason": {
"type": "query_phase_execution_exception",
"reason": "Cannot use [sort] option in conjunction with [rescore]."
}

```

**Comment by jimczi** [comment]
This is forbidden in 6x since rescore does not work with a `sort` that is not on `_score`.
Though this change has not been propagated to the docs and breaking change.
I opened https://github.com/elastic/elasticsearch/pull/28251

**Comment by aslamy** [comment]
Ok thank you.

> The rescore phase is not executed when sort is used

I think this solution was much better.

**Comment by jimczi** [comment]
> I think this solution was much better.

This was lenient and users that don't read docs may think that the rescorer was executed. Sort and rescore does not work together so throwing an error seemed the best solution when we added real support for custom rescorer.

**Comment by felipedrumond** [comment]
I have the scenario where I need to fetch products and display them divided into two groups **in stock** and **out of stock**, and among these two groups, sort them by their names.

I could rescore what's in stock to a score of 100 and what's not to 10, so that sorting by score would put these two groups apart of each other (as there are only two score values 100 and 10), then sort by name would produce exactly the response I need. However, because rescore will only with _score, that's not feasible.

```
"sort": [
    {
      "_score": {
        "order": "desc"
      }
    },
    {
      "displayname": {
        "order": "asc"
      }
    }
  ],
```
==> "Cannot use [sort] option in conjunction with [rescore]."

Not sure why this is not supported, but based on the scenario above, it is wanted.

**Comment by maoxiajun** [comment]
> I have the scenario where I need to fetch products and display them divided into two groups **in stock** and **out of stock**, and among these two groups, sort them by their names.
> 
> I could rescore what's in stock to a score of 100 and what's not to 10, so that sorting by score would put these two groups apart of each other (as there are only two score values 100 and 10), then sort by name would produce exactly the response I need. However, because rescore will only with _score, that's not feasible.
> 
> ```
> "sort": [
>     {
>       "_score": {
>         "order": "desc"
>       }
>     },
>     {
>       "displayname": {
>         "order": "asc"
>       }
>     }
>   ],
> ```
> 
> ==> "Cannot use [sort] option in conjunction with [rescore]."
> 
> Not sure why this is not supported, but based on the scenario above, it is wanted.

strongly agreed, no idea why this is not supported as it is a basic requirement in most search engine applications.

**Comment by Toojie** [comment]
Has there been any internal movement or discussions around implementing sort when using rescore? 

I have two customers within the space of a month requesting this functionality

**Comment by stewi2** [comment]
Sorting by something other than `_score` obviously doesn't make sense when rescoring. However using a secondary sort in addition to `_score` does make sense, since it ensures ranking stability across replicas:

```
"sort": [
    {
      "_score": {
        "order": "desc"
      }
    },
    {
      "id": {
        "order": "desc"
      }
    }
  ]
```

This ensures that results with the same score are sorted consistently (if id is a unique doc id). Right now docs that have the same score are iirc returned in Lucene docid order, and that can drastically change after segment merges for example.
