### ISSUE TITLE
ThirdPartyAudit fails - JAXB

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#28287]
Task `:plugins:discovery-ec2:thirdPartyAudit` fails [[1]](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.1+intake/183/console), [[2]](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.1+openjdk-java9-periodic/5/console), [[3]](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.1+intake/184/console),[[4]](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.1+zing/50/console), [[5]](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.1+release-tests/170/console) with the following error 

> 08:34:47 > CLASSES ARE MISSING! [javax/xml/bind/JAXBContext.class]

This looks similar to ones we were seeing recently ( #28252 for instance ) but the root cause seems to be different so I'm opening a new issue.

**Comment by jasontedor** [comment]
These are infra issues that are being handled internally. Note these failures are only on the 5.6 and 6.1 branches. This is because the infra changes to support JDK 9 were applied to all CI branches when they should only have been applied to 6.x and master (where we applied the JDK 9 changes). Since there is no actionable item on this repository and this is being tracked internally, I am closing this issue.
