### ISSUE TITLE
ThirdPartyAudit fails javax.xml.bind.Marshaller javax.xml.bind.helpers.DefaultValidationEventHandler

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#28291]
A lot of `:plugins:ingest-attachment:thirdPartyAudit` tasks on 5.6 fail today due to 

> 10:56:44 Execution failed for task ':plugins:ingest-attachment:thirdPartyAudit'.
> 10:56:44 > Invalid exclusions, nothing is wrong with these classes: [javax/xml/bind/Marshaller.class, javax/xml/bind/helpers/DefaultValidationEventHandler.class]

Looks like this is also related to the Java 9 upgrade, builds that have failed 

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+multijob-unix-compatibility/os=amazon/571/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+periodic/1310/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+release-tests/395/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+openjdk-java8-periodic/5/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+multijob-unix-compatibility/os=fedora/571/console

**Comment by jasontedor** [comment]
These are infra issues that are being handled internally. Note these failures are only on the 5.6 and 6.1 branches. This is because the infra changes to support JDK 9 were applied to all CI branches when they should only have been applied to 6.x and master (where we applied the JDK 9 changes). Since there is no actionable item on this repository and this is being tracked internally, I am closing this issue.
