### ISSUE TITLE
Eagerly fetch future results while scrolling

### ISSUE THREAD

**Issue by scottsom** [elastic/elasticsearch#28303]
From looking over the logic for scrolling, I suspect that there should be a decent optimization opportunity by having scrolls eagerly retrieve results before they are requested. It seems that after Elasticsearch returns the scroll results, it isn't doing any work (related to the scroll) until the client makes the next request at which point it runs the query then fetches the results.

Instead of sitting idle, each node involved in the scroll could do the query then buffer future results and when the client asks for the next batch, it flushes them from memory. This is possible since the scroll is a point-in-time snapshot, so whether the client asks for the next batch in 1s or 10s, they'll get the same response (no need to worry about invalidating stale buffered data).

This would be analogous to how an operating system might populate a readahead buffer of subsequent files on disk in anticipation of them being used. In this situation, it is highly likely that the buffered data will be used since you are probably looking for an exhaustive result set when scrolling.

This could be opt-in with a configurable buffer size and not require any API changes.

Has this been considered / prototyped in the past? 

Would there be any interest in accepting a pull request that implements this? (provided it actually improves scroll benchmarks)

**Comment by s1monw** [comment]
I think the biggest issue here is that this suggestion assumes that there are no other users of the server. In reality server wouldn't sit idle here. It's not very obvious to me how much you would prefetch and if you'd use a dedicated thread to do it, when you trash the prefetched data and how much it would actually buy us to have such a complexity on the server side. On the client side I'd rather get the result and fire off a request to get the next batch and gain concurrency due to that or maybe use slicing to get more concurrency. 
Also if you sort we do a fair bit of preprocessing on the shards. Yet I think I'd rather not go down the path of actively prefetching for the reasons mentioned and the concurrency model we use.

**Comment by scottsom** [comment]
Ultimately your call on closing this but I will offer some rebuttal:

Yes, I was suggesting that dedicated thread(s) do the readahead. At the end of the query phase, you can signal another thread to start working on the next batch. Today you have to wait for the fetch phase to complete, the results to be returned to the client, the client to parse the results, and the client to request the next page. In that time, the other thread could have already prepared the results (or at least got a good head start).

It won't reduce the overall work being done but the idea is you can get the data out faster and the sooner you'll be able to clear the scroll context.

I realize the server will be handling other requests so it isn't completely idle but it also probably isn't being 100% utilized and has spare capacity to get started on work that it is almost certainly going to have to do anyways.

There are other ways to speed up your scrolls such as slicing and/or making the client call back ASAP but this is just another (complementary) approach.

**Comment by clintongormley** [comment]
Also see https://github.com/elastic/elasticsearch/issues/23022
