### ISSUE TITLE
ScriptDocValues getDate() on long field triggers AccessControlException

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#28408]
In #22948 we added a deprecation warning when using `.date` on a long field. However, since scripts run in a reduced permission environment, the underlying call to log the message results in a security manager exception. We need to do this in a doPrivileged block.

See https://discuss.elastic.co/t/painless-script-appender-deprecation-rolling-java-security-accesscontaccess-denied/117313

**Comment by rjernst** [comment]
cc @nik9000

**Comment by nik9000** [comment]
Eep. This is a pretty terrible bug. I'll take a look at it soon-ish. There are 5 or 6 things ahead of it in my TODO list but I'll see about bumping it up.

**Comment by nik9000** [comment]
I had a look at this. I can't reproduce it, but from the stacktrace in the discuss post it *looks* like this isn't an "all the time" thing. It *looks* like this is triggered when log4j goes digging around in the filesystem which it doesn't do all the time. I'm going to open a PR that goes under the assumption that this is caused by that.

**Comment by nik9000** [comment]
OK. I can reproduce "something" happening locally. If I leave the code as is it can break file rolling. But instead of failing the request the line fails to log. I can fix that with the fix that, I think, should fix this issue.
