### ISSUE TITLE
Suggest term search result not proper in elasticsearch

### ISSUE THREAD

**Issue by arpitdadheech** [elastic/elasticsearch#28495]
**Elasticsearch version** 6.1
**Plugins installed**: None
**JVM version** 1.8
**OS version** windows

 I want to use "Suggester" of its feature. I have dumped data in the format its required for suggester.

I have used these queries.

PUT /hotels
{
 "mappings": {
"hotel" : {
  "properties" : {
   "name" : { "type" : "keyword" },
   "city" : { "type" : "keyword" },
   "name_suggest" : {
     "type" :     "completion"
   }
 }
 }
 }
 }

put hotels/hotel/1
{
"name" :         "Mercure Hotel Munich",
"city" :         "Munich",
"name_suggest" : "Mercure Hotel Munich"
  }

put /hotels/hotel/2
 {
  "name" :         "Hotel Monaco",
  "city" :         "Munich",
"name_suggest" : "Hotel Monaco"
 }

put /hotels/hotel/3
 {
  "name" :         "Courtyard by Marriot Munich City",
 "city" :         "Munich",
 "name_suggest" : "Courtyard by Marriot Munich City"
  }
Then I fire my search query that is

Post  http://localhost:9200/hotels/_search 
      {
        "suggest": {
        "name_suggest": {
             "text": "h",
           "completion": {
              "field": "name_suggest"
           }
      }
    }
 }

I get the output result. It only return me the 2 data that is "Hotel Monaco" but it doesn't suggest me "Mercure Hotel Munich" it has hotel.

I want both in my suggest result set I have tried with "prefix" as well.

Has anyone tried it. Please suggest me any solution to it.

I am working on building a google like search. So I want to get suggestions, word suggestion and phrase suggestion. So If I am going in wrong direction Please suggest me a good way.

Thanks in advance. 
@kimchy @s1monw @jasontedor @imotov @abeyad

**Comment by colings86** [comment]
@arpitdadheech , we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) instead.

The suggester will only match suggestions that start with the text provided in the search request. "Mercure Hotel Munich" is not returned because it does not start with `h`. You will probably want to look into providing multiple "inputs" in your completion field when you index your documents. See the following for more details: https://www.elastic.co/guide/en/elasticsearch/reference/6.1/search-suggesters-completion.html#indexing

**Comment by jasontedor** [comment]
@arpitdadheech Please do not ping people directly.
