### ISSUE TITLE
Inconsistent Java formatters

### ISSUE THREAD

**Issue by olcbean** [elastic/elasticsearch#28519]
Having incomplete formatting rules makes PR review process difficult.

In [CONTRIBUTING](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md) only two changes are mentioned, and `The rest is left to Java coding standards`. Unfortunately there are differences between Eclipse and IntelliJ defaults. Moreover there are 3 build-in profiles in Eclipse : all slightly different.

Here are a few examples : 
* Indentation for wrapped line : 
in Eclipse all three build-in profiles set it to **2**
in IntelliJ it is set to **1** ( https://github.com/elastic/elasticsearch/pull/28503#discussion_r165762141 )
* Eclipse : Maximum width of comments is 80 ( although most of the comments are using 140 )
* Eclipse : White spaces in Arrays initializers is different for the different Eclipse build-in profiles ( "after opening brace" and "before closing brace" ) : `new int[]{1, 2, 3};` vs `new int[]{ 1, 2, 3 };`

**Comment by jasontedor** [comment]
This is okay, we will accept this for now until someday we implement automatic code-formatting on commit. I would prefer to close this issue since it is not actionable at this time.

**Comment by nik9000** [comment]
I think it'd be more correct to say "do whatever you and the reviewing agree reads the best" which isn't really a great state of events. But we aren't unique in having this problem. Having more standards would make PRs easier but they are hard because:
1. There are lots of times when you want to break the standards and we need to account for that.
2. We have a ton of code that wouldn't comply with the standard and it is difficult with tools like checkstyle don't [support](https://github.com/checkstyle/checkstyle/issues/3242) properly ratcheting down failures. Look at how many of our files still have lines longer than 140 characters. Cleaning those up is fairly time consuming.

**Comment by olcbean** [comment]
What I had in mind here was not to suggest 'enforcement' ( as it would be rather challenging at this stage and AFAICS no obvious benefits ). But rather introducing a simple formatter that should be used for new code to avoid unnecessary reformatting. Basically instead of 

> - Java indent is 4 spaces
> - Line width is 140 characters
> - The rest is left to Java coding standards

share a simple eclipse formatter ( which AFAIK can also be imported in IntelliJ )
