### ISSUE TITLE
Points of LinearRing do not form a closed linestring

### ISSUE THREAD

**Issue by corradio** [elastic/elasticsearch#28520]
When indexing a geo_shape, I get the following error:

```json
{
  "error" : {
    "root_cause" : [
      {
        "type" : "mapper_parsing_exception",
        "reason" : "failed to parse [geometry]"
      }
    ],
    "type" : "mapper_parsing_exception",
    "reason" : "failed to parse [geometry]",
    "caused_by" : {
      "type" : "illegal_argument_exception",
      "reason" : "Points of LinearRing do not form a closed linestring"
    }
  },
  "status" : 400
}
```
I've attached the geometry.
[geo.txt](https://github.com/elastic/elasticsearch/files/1695084/geo.txt)

It correctly passes geoJSONLint:
![image](https://user-images.githubusercontent.com/1655848/35804801-8ae85830-0a79-11e8-949a-ec64f664b6cd.png)

**Elasticsearch version** : 6.1.3

Related to #12325

**Steps to reproduce**:

**Comment by DaveCTurner** [comment]
The geometry given self-intersects: it contains point `[-47.302481858850655,-16.04005421243197]` twice, which is not legal. You need to model this shape as an outline and a hole, rather than trying to combine them into a single outline.

GeoJSONLint (http://geojsonlint.com) is unfortunately not very thorough, and does not pick this up.
