### ISSUE TITLE
Enhancement on the Update by Query API 

### ISSUE THREAD

**Issue by georgezoto** [elastic/elasticsearch#28541]
Hello everyone,

Please bear with me, this is my first feature request for elastic.
I have combed the web, GitHub issues and the discussion forums but I haven't seen something close to this. So I need some expert opinion on how challenging this feature would be. In terms of benefits, the list just keeps growing as I will explain in detail.

**Challenge**: 
I have a dataset of several thousands records, related to 10 custom fields and zip code being one of them. Initially only these 10 fields are available for analysis. Later on I have 2 new fields in another dataset that I want to analyze my data over, County and City for example. Note that I can associate each zip code to a County and City, i.e. I can join the 2 datasets on the common field/key zip code.
(Before you immediately think that Elastic does not handle join please read along...)
Currently my mappings look like:

	"index-zipcode: {
		"mappings": {
			"doc": {
				"properties": {

	  				"Zip Code": {
            					"type": "text",
            					"fields": {
              						"keyword": {
                						"type": "keyword",
                						"ignore_above": 256
              						}
            					}
          				},
	  ...

				}
			}
		}
	}

**Current Approach**:
Write a custom script to perform that contains the newly added information.
Use this script and utilize Elasticsearch’s Update by Query API (https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update-by-query.html) to update any individual records that match a criteria. For example a trivial script in bash would be:

	#Zip Code,City,County
	#59003,Ashland,Rosebud
	#59648,Wolf Creek,Lewis And Clark
	#59410,Augusta,Lewis And Clark

	#!/bin/bash

	myindex=“my-always-updating-index-2018.01.23"

	IFS=$'\n';
	for item in `cat $1`; do
		myzipcode=$(echo $item|cut -d, -f1);
		mycity=$(echo $item|cut -d, -f2);
		mycounty=$(echo $item|cut -d, -f3);
		echo $myzipcode,$mycity,$mycounty;

		echo "{
          	\"script\": {
            	\"lang\": \"painless\",
            	\"source\": \"ctx._source.County = params.county; ctx._source.City = params.city;\",
           	 \"params\": {
               	 \"county\": \"$mycounty\",
               	 \"city\": \"$mycity\"
            	 }
	   	},

         	 \"query\" : {
                	\"constant_score\" : {
                   		 \"filter\" : {
                       	 		\"terms\" : {
                           		 		\"Zip Code\": [\"$myzipcode\"]
                        			}
                    	}
               	 }
            }

        	}" | curl -XPOST “mycluster:9200/$myindex/_update_by_query?pretty" -H 'Content-Type: application/json' -d "$(</dev/stdin)"
	done

	unset $IFS;

**Recommended Approach**:
Enhance the Update by Query API or create a new API to perform something like (warning, this code will not run, it is used for demonstration purposes only):

	POST “mycluster:9200/index-zipcode/_update_by_query?pretty" -H 'Content-Type: application/json' -d "
	{
  	"script": {
    	"lang": "painless",
    	"source": "ctx._source.County = params.county; ctx._source.City = params.city;",
    	"params": {

      		"query" : {
        			"index": "index-county-city-zipcode",
				"constant_score" : {
	  				"filter" : {
	    					"terms" : {
              						"Zip Code"
	    					}
	  				}
				},
        		"_source" : ["County","City","Zip Code"],
			"namespace": "inner-query"
      		},

		"county": "inner-query.County",
		"city": "inner-query.City"
     	}
   	}
	}

Note that the params section is enhanced to incorporate a query that would return the County and City for each zip code in a second index and update this information on the first index. In other words, we are enabling document updates with the update criteria being the result of query instead of the trivial constants or counter increments I have seen in the documentations and on the discussion forums.

**Issue with Current Approach and Benefits or Recommended Approach**:
The current approach takes away one dataset from Elastic (in this case stores is as a csv) and performs the join/document updates outside of it. If you take a step back and think that both datasets are present in Elastic with a common field, it would be natural to think that Elastic itself would support this capability. This would eliminate any offloading of data outside of Elastic which keeps updating over time. For performance reasons, the inner query could be limited at a batch of documents at a time.

**Summary**: In the ever changing world, new fields and datasets become available over time. An Elastic only solution to updating or enriching documents based on another field in another index would solve many data engineering challenges of offloading data out of Elastic, enriching them and finally updating them in Elastic.

I apologize for the long post, I just feel that the Elastic team has done a tremendous job in terms of APIs but I feel that these are all pieces of a greater puzzle that together would solve a much larger problem.

Thank you,
George Zoto

**Elasticsearch version** (`bin/elasticsearch --version`):
elastic-6.1.0

**Plugins installed**: []

**JVM version** (`java -version`):
openjdk version "1.8.0_151"

**OS version** (`uname -a` if on a Unix-like system):
Ubuntu 16.04.3 LTS

**Comment by nik9000** [comment]
I think you can use the current API to get something partly between that has some nice properties. One thing that jumps out at me about your bash solution is that you can monitor its progress quite well and you can resume it by restarting where you left off if you have to kill it. You could get something pretty similar but probably faster if you chunked the update by queries into buckets of 100 or so zip codes. You ought to be able to pass a json object with one field per zip. Each field contains an object with the city and county. Then you can do the update by query with a `terms` query against all the zips that you sent.

I feel it is important to say that updates in Elasticsearch are functionally quite similar to an atomic delete and index of the entire document. So if you can avoid enriching after the fact it is usually faster.

What you've proposed is, I think, more brains then we want to put into update by query at the moment. As it stands it is one of the "bigger" APIs that Elasticsearch offers. We prefer to make smaller components that you string together to build a thing because we think we're less likely to make assumptions that invalidate the whole feature that way. So we're really loath to add more things like this to update_by_query.

**Comment by polyfractal** [comment]
I suspect there are a lot of gnarly edge-cases which would be non-trivial for the API to deal with.  E.g. handling partial, failed or rejected search responses, dealing with the real-time nature of search (one update may see a different value from the very next update), etc.  And latency would be a big concern, since updates now have to pend for a search to finish

**Comment by dakrone** [comment]
Going to close this for now, as it sounds like we have plans to add the additional complexity to update-by-query
