### ISSUE TITLE
Plugin installation fails on Alpine

### ISSUE THREAD

**Issue by ndegory** [elastic/elasticsearch#28561]
Installing a plugin on ES 6.2.0 fails on Alpine:
```
$ /opt/elasticsearch/bin/elasticsearch-plugin install -b https://distfiles.compuscene.net/elastic  search/elasticsearch-prometheus-exporter-6.2.0.0.zip
mktemp: Invalid argument
```
_/opt/elasticsearch/bin/elasticsearch-env_ uses _mktemp_, with two different syntaxes for the coreutils version and the darwin version. Unfortunately _mktemp_ on Alpine Linux is provided by BusyBox and requires a different syntax.

**Comment by colings86** [comment]
Alpine Linux is not a supported OS for running Elasticsearch (see https://www.elastic.co/support/matrix for a list of OSes that are supported). We had looked into supporting Alpine linux before specifically around using it in docker images but found many problems including https://github.com/elastic/elasticsearch-docker/issues/44#issuecomment-291172031 and ultimately decided that supporting Alpine Linux was not something we want to pursue.

**Comment by jasontedor** [comment]
@ndegory As @colings86 mentioned, we indeed do not support Alpine Linux. We resist making changes to our codebase for OS that we do not support. This is because without CI infrastructure in place, we can not maintain that code.

In this specific case, you can workaround this issue by setting `ES_TMPDIR` inside the container (use the `ENV` directive). This will bypass the use of `mktemp`.

I want to emphasize: we can not guarantee that a future change will not break that workaround on Alpine Linux, but it stands today as an option.
