### ISSUE TITLE
Feature request: explicit unique count metric

### ISSUE THREAD

**Issue by Mikhail-Sveshnikov** [elastic/elasticsearch#28599]
Redirected from:
https://discuss.elastic.co/t/explicit-unique-count-for-business-intelligence-tasks-no-chance/118641

Request to add a new metric that will allow to get an explicit unique count by field apart from existing approximate Unique Count that utilizes cardinality.

**Comment by jimczi** [comment]
We don't do exact unique count because it doesn't scale, elasticsearch is distributed so getting all unique values would require that each shard send their full list to the coordinating node. This could work for few values but it would break as soon as the number of unique values grow.  For this reason we rely on HyperLogLog to do an approximation using a reasonable amount of memory. You can also tweak the parameters to get a better precision:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html#_precision_control
Note also that if the number of unique values is below the provided threshold the count is accurate.

**Comment by jimczi** [comment]
> Note also that if the number of unique values is below the provided threshold the count is accurate.

Sorry my mistake, the count is close to accurate in this case but there is no guarantee that it is completely accurate since we use hashing and there might be some collisions (very low probability but can happen so the count is not always accurate in this case too).
