### ISSUE TITLE
Create new indice stuck forever

### ISSUE THREAD

**Issue by diman82** [elastic/elasticsearch#28632]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 6.2.1

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_162

**OS version** (`uname -a` if on a Unix-like system): Windows 10x64 latest version

**Description of the problem including expected versus actual behavior**:
Creation of a new indice on a fresh Elastic instance simply runs forever

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. curl -X PUT "http://localhost:9200/products"  -H 'cache-control: no-cache' -H 'postman-token: 173dfd2d-094c-317e-db9c-badb41a0b09c'
 2. Same behavior with POSTMAN
 3. Wait forever

**Provide logs (if relevant)**:

**Comment by jasontedor** [comment]
This does not reproduce, I suspect an issue in your environment. Since we reserve GitHub for verified bug reports and feature requests, I would like to ask you to use the [forum](https://discuss.elastic.co) where we can provide support for such issues. If we do find a bug here, we can reopen this. Please feel free to drop a link here to any forum topic that you open.
