### ISSUE TITLE
RestoreSnapshotRequest should implement IndicesRequest interface

### ISSUE THREAD

**Issue by sscarduzio** [elastic/elasticsearch#28671]
According to the comments in IndicesRequest:

```
/**
 * Needs to be implemented by all {@link org.elasticsearch.action.ActionRequest} subclasses that relate to
 * one or more indices. Allows to retrieve which indices the action relates to.
 * In case of internal requests  originated during the distributed execution of an external request,
 * they will still return the indices that the original request related to.
 */
```

`org.elasticsearch.action.admin.cluster.snapshots.restore.RestoreSnapshotRequests` should implement IndicesRequest.

This is important in my plugin, as because of now, I rely on this type to understand if or not to apply the ACL rule for indices.

**Comment by ywelsch** [comment]
@tvernum and I discussed this and we think that `RestoreSnapshotRequest` is different than other requests that implement `IndicesRequest`, namely that the indices that it talks about are in a snapshot, and not necessarily part of the current cluster (state). Furthermore, `RestoreSnapshotRequest` allows to rename indices when restoring them, so this means that the request may affect a completely different index than what's specified in the `indices` array. We feel that, due to this semantic difference, adding the `IndicesRequest` interface to `RestoreSnapshotRequest` would be misleading. Plugins need to treat this request type with special care, and we think that it would be dangerous to just treat it as any other request that implements `IndicesRequest`.

**Comment by sscarduzio** [comment]
OK, makes sense thanks guys for taking a look at this. My plugin already handles this in a special way.
