### ISSUE TITLE
[DOC] Wrong disable/re-enable shard allocation commands. 

### ISSUE THREAD

**Issue by tsouza** [elastic/elasticsearch#28747]
As of `6.0`, the documentation on rolling upgrading is disagreeing on shard allocation commands:

Link: https://www.elastic.co/guide/en/elasticsearch/reference/6.0/rolling-upgrades.html

Step 1:
>PUT _cluster/settings
{
  **"persistent"**: {
    "cluster.routing.allocation.enable": "none"
  }
}

Step 7:
>PUT _cluster/settings
{
  **"transient"**: {
    "cluster.routing.allocation.enable": "all"
  }
}

This should be putting many clusters out there in a state that it won't allocate at the next full cluster restart.

**Comment by inqueue** [comment]
The bug here is the doc does not mention how to put the cluster back into its original state at the end of the rolling upgrade process. Perhaps there should be a step 10 that either nulls out the persistent cluster setting or sets `"cluster.routing.allocation.enable": "all"` in persistent cluster settings.

**Comment by tsouza** [comment]
I agree with @inqueue . The cluster state should end in the same state that it was before starting the rolling upgrade process.

**Comment by gmoskovicz** [comment]
Relates to https://github.com/elastic/elasticsearch/issues/27677

**Comment by jasontedor** [comment]
Duplicates #27677
