### ISSUE TITLE
Elasticsearch plugins missing from maven central

### ISSUE THREAD

**Issue by minfrin** [elastic/elasticsearch#28765]
Elasticsearch v6.2.2 is available from maven central:

https://repo1.maven.org/maven2/org/elasticsearch/elasticsearch/6.2.2/

Elasticsearch plugins, like elasticsearch-analysis-icu plugin, are not available from maven central:

https://repo1.maven.org/maven2/org/elasticsearch/elasticsearch-analysis-icu/ (up to v2.7.0)
https://repo1.maven.org/maven2/org/elasticsearch/plugin/analysis-icu/ (up to 5.0.0-alpha5)

This makes it difficult to inject elasticsearch artifacts into maven projects.

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

**Comment by minfrin** [comment]
Looking further in the source code, there is a feature to download plugins from maven central:

distribution/tools/plugin-cli/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java

        // now try as maven coordinates, a valid URL would only have a colon and slash
        String[] coordinates = pluginId.split(":");
        if (coordinates.length == 3 && pluginId.contains("/") == false && pluginId.startsWith("file:") == false) {
            String mavenUrl = getMavenUrl(terminal, coordinates, Platforms.PLATFORM_NAME);
            terminal.println("-> Downloading " + pluginId + " from maven central");
            return downloadZipAndChecksum(terminal, mavenUrl, tmpDir, true);
        }

If the deployments to maven central have been purposefully stopped, this code needs to be removed from InstallPluginCommand.java.

**Comment by dadoonet** [comment]
@minfrin No this code is still useful for the community who are building their plugins and often distribute them on Maven central.

**Comment by s1monw** [comment]
to clarify this, we publish maven artifacts for historic reasons. We have a Java client that depends on elasticsearch core / server for request and response objects and serialization. Users of these clients have all necessary plugins in maven central that are required to run these clients. Our server distribution is not in maven central, it's distributed as a zip/tar.gz/rpm etc. from our download mirrors. If there is a plugin missing please let us know. To my knowledge there is none. For `analysis-icu` there is no need to publish it since the client doesn't have a dependency on that plugin. 

For instance reindex is needed to be used with the client: https://repo1.maven.org/maven2/org/elasticsearch/plugin/reindex-client/

Same is true for percolator: https://repo1.maven.org/maven2/org/elasticsearch/plugin/percolator-client/

hence they are on maven central. Other plugins that are not needed as a java-dependency are not and we don't plan to do so since it's not intended to be used outside of the elasticsearch server. We also don't support embedded server for reference please read this: https://www.elastic.co/blog/elasticsearch-the-server

I hope this clarifies the issues here.
