### ISSUE TITLE
ThrottlingAllocationDecider outgoing message's nodeid is wrong

### ISSUE THREAD

**Issue by czjxy881** [elastic/elasticsearch#28777]
**Elasticsearch version** (`bin/elasticsearch --version`):
5.3.0

**Plugins installed**: []

**JVM version** (`java -version`):
1.8.0_111

**OS version** (`uname -a` if on a Unix-like system):
CentOS

**Description of the problem including expected versus actual behavior**:

the node.nodeId() should be primaryShard.currentNodeId()
![default](https://user-images.githubusercontent.com/3929477/36518448-5e9dfa14-17c1-11e8-941b-3ae3cbc35373.png)

**Comment by DaveCTurner** [comment]
Hm, yes, that does look incorrect. Although this report is against 5.3.0, it looks like this is still the case in master:

https://github.com/elastic/elasticsearch/blob/99f88f15c5febbca2d13b5b5fda27b844153bf1a/server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java#L149-L169

@czjxy881 it looks from your colour scheme that you're using IntelliJ. If so, you may like to know that you can select some code and select 'Open in Github' from the context menu to get a URL that links to code, rather than using a screenshot.

@elastic/es-distributed I'm marking this as adoptme.

**Comment by ywelsch** [comment]
@czjxy881 would you like to make a PR?

**Comment by czjxy881** [comment]
@DaveCTurner thank you , i really don't know yet

**Comment by czjxy881** [comment]
@ywelsch already submit
