### ISSUE TITLE
Feature Request:  Auto discover certain coordinator nodes only.

### ISSUE THREAD

**Issue by linker-mist** [elastic/elasticsearch#28831]
**Describe the feature**:
I have setup my ES cluster to write to ingest only nodes, and read from coordinator nodes that's not master nor data nodes.
The problem is if I add more coordinator "client" nodes (not master, not ingest, not data) to server query spikes, there's no way for the client to auto discover those nodes without including either master or data nodes.  The workaround I have now is to make those new nodes to be ingest nodes as well.
So I just auto discover ingest nodes for read, but then I won't be able to split write & read nodes.

The only way to discover nodes via REST afaik is to use /_nodes/xyz, where xyz is a comma separated "node roles".  Maybe there's another way to do this?  Or maybe splitting read from write like what I'm doing is overkill?

**Comment by nik9000** [comment]
I *think* you could give your coordinating nodes an attribute. Like `coordinating:true`. See the docs for [allocation awareness](https://www.elastic.co/guide/en/elasticsearch/reference/current/allocation-awareness.html) for how. Then you could use something like `_nodes/coordinating:true` ([documentation](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/cluster.html#cluster-nodes)) for detection.

I'll mark this as `discuss` because I think it might be nice to be able to do have more expressive syntax in this API. That, or we can document the node attributes trick explicitly somewhere.

**Comment by ywelsch** [comment]
We discussed this in FixitFriday and would like to add `coordinating_only` as a filtering option for resolving node ids (affecting APIs such as `_nodes`). In the meanwhile you can use the workaround suggested by @nik9000.

**Comment by ywelsch** [comment]
You can also negate node roles, e.g. `master:false`. This requires a little hack, though, namely to use the wildcard `*` as first parameter in the request, so that all nodes are initially selected, and the master-eligible then subtracted, ...

The following should achieve what you're looking for:

```
/_nodes/*,master:false,data:false,ingest:false
```

The adoptme here is to simplify the API so that the "wildcard" hack is not needed.

**Comment by PnPie** [comment]
Hi @ywelsch @nik9000,
I made a PR for this.
