### ISSUE TITLE
Ability to limit the bitset filter cache size

### ISSUE THREAD

**Issue by antonpious** [elastic/elasticsearch#28857]
When using queries on nested documents, there is a  bitset filter cache that grows uncontrollably. We should have levers to control how much memory is allocated to this cache. This could be a percentage based on a configured total memory and explicit control only for this cache should be provided for clients who use nested documents a lot.

The following shows a dump of memory from a node which has this filter cache.
![bitsetfiltercache](https://user-images.githubusercontent.com/15054021/36822701-fa8a939a-1cbe-11e8-9df2-5a812e754eb5.png)

A related issue is filed in the forum but no feature action has been taken on the same. Not sure if this can be treated as a bug and down merged into lower versions namely 5.0 and above.
Forum Post
[Can I print out bitset cache sizes by filter (or what’s eating my heap)?](https://discuss.elastic.co/t/can-i-print-out-bitset-cache-sizes-by-filter-or-whats-eating-my-heap/33103)

**Comment by martijnvg** [comment]
Nested queries need a bitset to work well. If these bitsets are loaded on the fly then this will slow down searches significantly (load time is linear to the number of parent documents). Further more it can cause cache churn (bit sets constantly being built / cached and then removed). So adding a limit to the bitset filter can cause more harm than good.

If you have many nested fields you need to increase the heap space. On the long term the way how nested queries are implemented can be changed to use doc values instead of bit sets [1]. Doc values are stored on disk and are cached in the file system cache, and this combination allows for better LRU cache eviction.

1: https://issues.apache.org/jira/browse/LUCENE-7304
