### ISSUE TITLE
search_analyzer definitions in index settings to allow for dynamic updates to query-time analyzers

### ISSUE THREAD

**Issue by osman** [elastic/elasticsearch#28877]
something like this:

```
PUT /test_index
{
    "settings": {
        "index" : {
            "analysis" : {
                "filter" : {
                    "synonym" : {
                        "type" : "synonym", 
                       "synonyms" : [
                            "i-pod, i pod => ipod",
                            "universe, cosmos"
                        ]
                    }
                },
                "search_analyzer" : {
                    "synonym" : {
                        "tokenizer" : "whitespace",
                        "filter" : ["synonym"] 
                    }
                }
            }
        }
    }
}
```

This denotes the analyzer as one that is only used at search time, and is thus safe to update dynamically. My use-case is dynamically updating synonyms without having the open/close the index. But I imagine there are other useful properties to being able to dynamically update analyzers used only at query time.

**Comment by rjernst** [comment]
The `search_analyzer` setting used within mappings is just the name of an analyzer. Can you elaborate on the problem with using the existing `analyzer` specification within `analysis`?

**Comment by colings86** [comment]
@osman being able to update search analyzers (specifically being able to update the synonyms in a synonym token filter only used at search time) is something we are actively thinking about. However it is not so straight-forward since a token filter can be used by any analyzer and any analyzer can be used as either an "analyzer" or "search_analyzer" in the mappings. This means that determining if a synonym list can be updated would currently require going through all the analysis settings and mappings which is not a great solution. We have spoken about denoting token filter definitions as "search only" but there is more thinking to be done around how this actually plays out when validating analyzer settings and mappings and when trying to update the synonym list

**Comment by mayya-sharipova** [comment]
Closing this issue as implemented. 
 
Synonym filters can be updateable with property: "updateable": true and file based synonyms can be [reloaded](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-reload-analyzers.html).

Alternatively [Synonyms Management API](https://www.elastic.co/guide/en/elasticsearch/reference/current/synonyms-apis.html) can be used to manage synonyms in an internal system index.
