### ISSUE TITLE
GC logging location not found when CWD is on a different drive on Windows

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch#29057]
When starting `elasticsearch.bat` from a different drive the gc logging location `-Xloggc:logs/gc.log` in `jvm.options` will yield the following warning on standard error:

> Java HotSpot(TM) 64-Bit Server VM warning: Cannot open file logs/gc.log due to No such file or directory

e.g our teamcity working directory is on `T:` and therefore conceptually starting elasticsearch as followed:

> T:\TeamCity\buildAgent\work\95d288ead8086b51> C:\Users\teamcity\AppData\Roaming\NEST\6.2.1\elasticsearch-6.2.1\bin\elasticsearch.bat 

Since our (.NET team) automation bails out on standard error messages this was killing our `6.2.x` NEST integration tests on CI.

This is a rather obscure bug that I am not even sure warrants fixing feel free to close @elastic/es-core-infra. Opening for future googlers (myself included) sake.

**Comment by jasontedor** [comment]
Are you sure that's the problem here? We change directory to the home directory for Elasticsearch exactly for this reason: https://github.com/elastic/elasticsearch/blob/v6.2.1/distribution/src/main/resources/bin/elasticsearch.bat#L53. Do you instead maybe not have a `logs` directory under `C:\Users\teamcity\AppData\Roaming\NEST\6.2.1\elasticsearch-6.2.1`? Since we package one, maybe it was removed? Can you check this?

**Comment by Mpdreamz** [comment]
Opened https://github.com/elastic/elasticsearch/pull/29086 to fix this. `cd` does not change drives unless `/d` is also provided.

**Comment by jasontedor** [comment]
Closed by #29086
