### ISSUE TITLE
a typo in the documentation?

### ISSUE THREAD

**Issue by greenx** [elastic/elasticsearch#29058]
In exapmle https://www.elastic.co/guide/en/elasticsearch/reference/5.2/_profiling_queries.html
```
...
       "description": "message:message message:number",
       "time": "1.873811000ms",
       "breakdown": {...},
...
```
But in text other digits.
```
The "time" field shows that this query took ~15ms for the entire BooleanQuery to execute. The recorded time is inclusive of all children.
```

**Comment by cbuescher** [comment]
@greenx thanks for noting this
The error you mentioned has been corrected since the 5.3 version (e.g. https://www.elastic.co/guide/en/elasticsearch/reference/5.3/_profiling_queries.html) and we usually don't correct all of the older documentation branches for minor issues like this, so I hope you don't mind me closing this.
