### ISSUE TITLE
Node's shards not synced after restarting

### ISSUE THREAD

**Issue by ahmadazimi** [elastic/elasticsearch#29133]
**Elasticsearch version**: 6.2.2, Build: 10b1edd/2018-02-16T19:01:30.685723Z

**Plugins installed**: []

**JVM version**: 1.8.0_144

**OS version**: Ubuntu, Linux 4.4.0-104-generic

I have 3 replica with 8 shards in each one. I've indexed documents when all of nodes are alive, then after I restarted a node, that node never synced and always its `primary` is `false`.
I've testing multiple stop and start nodes, but only one node has all shards in! (`primary: true)`

![screen shot 1396-12-28 at 13 13 28](https://user-images.githubusercontent.com/1847191/37588400-60b5f0a8-2b77-11e8-90da-9caeddf9921b.png)

![image](https://user-images.githubusercontent.com/1847191/37588417-71733946-2b77-11e8-8164-f7a4f7e58fc6.png)

**Comment by colings86** [comment]
the `primary` flag is not an indication that the shard copy is in sync, it is an indication that the particular shard copy for that shard is considered to be the copy that leads the shard group and receives indexing requests first. at any one time only one shard copy in each shard will be a primary. Also after a restart it is expected that any shard copies on the restarted node will no longer be primary since while the node is down another shard copy for the shard will be promoted to being the primary to maintain availability. 

Primary shard copies do not experience more load than the replicas inn the shard group since all shard copies are sent all indexing operations and read operations are evenly-distributed amongst shard copies. The only difference is that the primary shard will receive the indexing operation first before it is forwarded on to the replicas in the shard group.

For more information on the above you can read the following sections of the Elasticsearch Definitive Guide book:
https://www.elastic.co/guide/en/elasticsearch/guide/2.x/_how_primary_and_replica_shards_interact.html
https://www.elastic.co/guide/en/elasticsearch/guide/2.x/distrib-write.html
https://www.elastic.co/guide/en/elasticsearch/guide/2.x/distrib-read.html

(The guides content is mostly written for thee 2.x versions but these principles are still relevant and largely the same in todays versions)

**Comment by ahmadazimi** [comment]
@colings86 Thank you for your complete reply.
