### ISSUE TITLE
Improve documentation on how to set up file descriptors if a graphical environment + systemd is used

### ISSUE THREAD

**Issue by jakommo** [elastic/elasticsearch#29163]
From time to time I see issues with file descriptor changes in `/etc/security/limits.conf` not being picked up, if the user runs a GNU/Linux system with a graphical environment and runs Elasticsearch from `tgz/zip` distribution.

It looks like newer distributions that run with `systemd` and a GUI require additional settings to be applied.
We already document that the limits need to be changed in `/etc/security/limits.conf` (and that's still true) and that [ubuntu might also require a pam.d setting to be applied](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/setting-system-settings.html#limits.conf), but if systemd is used it might also require the user to set `DefaultLimitNOFILE=65536` in `/etc/systemd/system.conf` and `/etc/systemd/user.conf `.

My proposal is to add to the current documentation that  it might also require the user to set `DefaultLimitNOFILE=65536` in `/etc/systemd/system.conf` and `/etc/systemd/user.conf ` (in addition to what's already documented).

I'm pretty sure there is a way to have systemd picking up the new settings without a restart, but logging out and in to the graphical session wasn't enough in my testing and it only worked after a reboot of the system.

**Comment by rjernst** [comment]
@jakommo We set `LimitNOFILE=65536` in our systemd service file. You mentioned you've seen this problem with users running tar/zip distributions. Since we only package our service file with rpm/deb, these users must be creating their own service file. I don't think we should document all the intricacies of systemd.  Instead, we should guide users to use the provided packages which come with service startup scripts which we have tested. Given that, I hope you don't mind that I close this issue.

Regarding why systemd did not pickup your changes, I believe you need to run `systemctl daemon-reload`.

**Comment by jakommo** [comment]
Hey @rjernst, this isn't about users writing their own service file, but about users running the .tgz in a terminal for playing around / development. 
I encountered this several times during our training's (where we use the .tgz), that the file descriptor bootstrap check fails and the instructions we have [here](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/setting-system-settings.html#limits.conf) aren't solving this, if the user runs e.g. gnome 3 on a system using systemd. 
In that case the steps I described above are required to start up elasticsearch in a production mode.

I do agree that we should not cover all intricacies of systemd, but I feel like documenting this would help with a better getting started experience for users that are running a GUI on a system with systemd and that do not want to install the rpm/deb because they are just playing around.
