### ISSUE TITLE
_source filtering in index alias

### ISSUE THREAD

**Issue by ZLightning** [elastic/elasticsearch#29271]
**Describe the feature**:

It would be useful to add `_source` filtering in an index alias to enable removal of fields from one index while leaving the same field from other indexes alone.

For example, I have 2 indexes that I want to search from the alias `notes_search`.  One index has `notes` that I need to show, while the other index has `notes` that need to filter, but the exact contents should not be exposed.  The `notes` field of the `notes_are_private` index mark the record as confirmed and contain an audit log of who confirmed the record.  Certainly the same thing could be accomplished by changing the name of the `notes` field in `notes_are_private` to another name and excluding that field from the entire query.  However, the intent is to complete the unique "view" of the same index that the filter is designed to provide.
```JSON
{
  "actions": [
    {
      "add": {
        "index": "notes_are_public",
        "alias": "notes_search"
      }
    },
    {
      "add": {
        "index": "notes_are_private",
        "alias": "notes_search",
        "filter": {
          "term": {
            "notes": "confirmed"
          }
        },
        "_source": {
          "excludes": [ "notes" ]
        }
      }
    }
  ]
}
```

**Comment by bleskes** [comment]
the main goal of aliases is to give people flexibility to change the indices an application searches/indexes to without any down time and without changing application code. This is handy for time based data, roll over APIs, versioned indices etc. The filters in the aliases are meant as a convenience (instead of adding them to each search) mostly for a multi-tenancy scenario where the data from multiple users is put into one index and come really handy together with a routing value. Alias are not meant as a full security feature (the security use cases are way more complicated). 

I'm going to close this as won't fix. I suggest you implement this on the client side.
