### ISSUE TITLE
40% CPU Usage All the Time

### ISSUE THREAD

**Issue by coolrecep** [elastic/elasticsearch#29317]
**Elasticsearch version** (`bin/elasticsearch --version`): **6.2.3**

**Plugins installed**: []

**JVM version** (`java -version`):

java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):

Linux 2.6.32-696.23.1.el6.x86_64 #1 SMP Tue Mar 13 22:44:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
CentOS 6.9

**Description of the problem including expected versus actual behavior**:

High CPU Usage. Always around 40%.

![image](https://user-images.githubusercontent.com/13221472/38141037-2645e2ea-343f-11e8-915f-8e3fe61c4b88.png)

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

- XenForo 2.0.4
- LiteSpeed 5.2.6
- XenForo Enhanced Search + [Similar Threads Plugin](https://xenforo.com/community/resources/similar-threads.5624/)
- PHP 7.2
- CPU COre i7 3770

Regenerated search index but did not help.

**Provide logs (if relevant)**:

Don't know log location.

**Comment by nik9000** [comment]
> The easier you make for us to reproduce it, the more likely that somebody will take the time to look at it.

With your bullet points we have no chance of figuring out what is going on so I'm going to close this.

For what it is worth, Elasticsearch has [asynchronous processes](https://www.elastic.co/guide/en/elasticsearch/guide/current/merge-process.html) that run after indexing to optimize the index. So that might be what is going on. Also, your tools may be actually sending documents. I really can't tell. You can tell what is going on by looking at the [hot threads](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-hot-threads.html) API but it will only tell you what Elasticsearch is doing, not why it is doing it.

I suggest talking to the folks behind "XenForo Enhanced Search + Similar Threads Plugin" though. They are likely going to know what is up better than we will.
