### ISSUE TITLE
It would be nice if zero_terms_query was supported by the new match_phrase syntax

### ISSUE THREAD

**Issue by JFogh** [elastic/elasticsearch#29344]
**Describe the feature**:
In the new NEST version 6.x.x the "type" option on "match" query is obsolete.
Thus you now use "match_phrase" instead of match with type "phrase".
When using the old "match" there was a "zero_terms_query" possibility supported.
This is not supported by the "match_phrase" query.
This makes it harder to rewrite queries using the old "match"-syntax to use the new "match_phrase",
thus it would be nice to have the "zero_terms_query" possibility, especially for backwards compability.

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by jimczi** [comment]
Some options that were available on the `multi_match` and `match` queries are no longer available in the `match_phrase` query. You could use a `multi_match` query and set the `type` to `phrase` but I agree that it would be nice to re-enable the support for `zero_terms_query` option in a simple `match_phrase` query. Would you like to work on a pull request for this issue @JFogh ? Otherwise I'll mark the issue with an adoptme tag.

**Comment by JFogh** [comment]
@jimczi I do not think I will have time to look into it, in the near future - so maybe the "adoptme"-tag would be fine.

**Comment by jimczi** [comment]
Ok thanks @JFogh

**Comment by jtibshirani** [comment]
This option was added in https://github.com/elastic/elasticsearch/pull/29598.
