### ISSUE TITLE
Add RequestedAuthnContext for MFA in SAML SP

### ISSUE THREAD

**Issue by dherrhoyiu** [elastic/elasticsearch#29367]
Support MFA (Multifactor Authentication) using the authnContextClassRef="http://id.incommon.org/assurance/mfa" attribute on the SP side (Kibana).  This is for Shibboleth, which we are using for federated IdM in the Omnisoc initiative (http://omnisoc.iu.edu).  The federation is InCommon, a higher ed federation.

I have used Shibboleth on the SP side in ES 6.1 to do MFA, but it's really just an overlay on ES.  There's shibd running, which is the SP, and I can add RequestedAuthnContext there within /etc/shibboleth/shibboleth2.xml as authnContextClassRef="http://id.incommon.org/assurance/mfa" in the <SSO ...> entity.
Should be able to do something similar in the ES SAML implementation.

I do have SAML working in a dev ELK with ES 6.2.2.

**Comment by danielmitterdorfer** [comment]
Hi @dherrhoyiu, as this is an x-pack related issue, I will open an identical internal issue and close this one. You might be aware that [we are about to open x-pack](https://www.elastic.co/products/x-pack/open) so that issue should reappear again in the coming weeks in this repository. Sorry for the inconvenience in the meantime.

**Comment by danielmitterdorfer** [comment]
Yes, that will fortunately get straightforward after x-pack has been opened. W.r.t. to the issue id: I have mentioned this issue in the internal one so it will show up here after the repository migration.
