### ISSUE TITLE
Multi field primary key to lower overhead

### ISSUE THREAD

**Issue by ddorian** [elastic/elasticsearch#29383]
On cases where the documents are small, often times the "_id" is just a string of "field1:field2:field3", like you do in normal RDBMS with mutli column primary keys.

But currently you have to duplicate which will have 1 more inverted-index(each term 1 value) and another dictionary for the term which may or not be good compressible. 

In this, you can store on translog a json_array(f1,f2,f3) while on lucene not storing an _id. Of course you'll have to store the fields to return them when querying to build the _id.

Makes sense ?

**Comment by jpountz** [comment]
Sorry, we don't have plans to support composite primary keys.

Today, Elasticsearch requires that a field is indexed on its own in order to be searchable. The absence of primary keys is due to the fact that indexes can be combined rather efficiently, due to the fact that they are all ordered by doc ID. If you filter on two fields, two indices are going to be used unlike with RDBMS. While this is performant enough for search, I wouldn't want to rely on this for updates though, which may run at a much higher throughput than searches.

**Comment by ddorian** [comment]
It could be optional so you could chose between update/search performance but I understand the reasoning.
