### ISSUE TITLE
Allow to create local alias for a remote index in a cross cluster search setup

### ISSUE THREAD

**Issue by Kamleshpa** [elastic/elasticsearch#29381]
**Allow to create local search alias on a remote index.**:

**Elasticsearch version** (`6.1`):

**Description of the problem including expected versus actual behavior**:
Currently elasticsearch does not allow to create a local alias for a remote index
For example: 
```
   POST _aliases
{
    "actions" : [
        { "add" : { "index" : "cluster2:logstash-2018.03.18", "alias" : "logstash" }}
    ]
}
```
Above api call gives an error saying index does not exists. However it should check if there is any remote cluster attached and is the index available on that cluster.

**Comment by javanna** [comment]
I see a couple of problems with this proposal, that make it collide with our current design decisions.

An alias is a piece of metadata attached to an existing index. It would be a new concept to have an alias point to something that is not locally present, it would mean storing aliases differently in the cluster state. Not saying it's not possible, but it's quite a change compared to how aliases are currently handled.

Most importantly, when we implemented Cross Cluster Search we consciously went for addressing the hard problem, namely search against multiple clusters, which couldn't be handled on the client side. 
For this reason we only added the cross-cluster execution to the search API only.  I don't think we want to add support for remote calls to external clusters in other API, especially to solve problems like mapping an alias to an index, which can be easily done on the client side.

Also we didn't want to abstract remote calls away, rather have users consciously query remote clusters by adding their name as part of the index. Creating an alias to a remote index would mean that users don't know anymore whether they are querying a remote index or not, which seems dangerous to me.

**Comment by lanerjo** [comment]
This would be a very useful option to have.
I can think of many use cases that this would come in very handy. Consider one of my particular use cases, where we ingest 6tb of primary data per day, with over 4 billion events per day. This scale without cross cluster search is nearly impossible to manage efficiently, the cluster state grows large very quickly.

1. When architecting data sets (beyond just logs), it is often useful to join multiple datasets together in a single query inside kibana, the best way to handle this is to use aliases. 
2. When architecting a highly resilient, minimal blast radius when having performance issues in a cluster, it is better to have multiple smaller clusters rather than 1 huge all encompassing cluster.
3. When considering the above 2 points, cross cluster search using aliases would be very helpful, This really wouldn't be too much more difficult than how kibana stores saved objects currently, such that kibana stores index patterns in the .kibana index currently.
