### ISSUE TITLE
Restricted cardinality

### ISSUE THREAD

**Issue by alepuccetti** [elastic/elasticsearch#29470]
**Describe the feature**:

I am trying to achieve something that I would define as restricted cardinality. I would like to compute the cardinality of a field but restricted to a domain provided as input.

Proposal:

```
{
  "size": 0,
  "aggs": {
    "restricted_cardinality": {
      "cardinality": {
        "field": "target_ids",
        "include": ["000", "111", "222"]
      }
    }
  }
}
```

However, it would be nice to have a parameter "include" in the cardinality to tell to Elasticsearch that you are only interested in those values. Bonus points for having back as result the percentage:
`p = restricted_cardinality / include.size`.

Benefits:
- New more powerful functionality. when you filter for some values on an array field (in the example `target_ids` is an array) and compute the cardinality of the field you get back the total cardinality instead the one applied to the filtered values.
- Less memory usage because you can allocate a smaller size hashmap do to the fact that you know the maximum number of elements you want to consider.
- Possible performance improvement once you reached the cardinality equal to the size of your include list than you can early terminate the computation.

## Workaround
I found a sort of work around by doing using the include in the terms aggregation with the include option:

```
{
  "size": 0, 
  "query": {
    "bool": {
      "filter": {
        "terms": {
          "target_ids": [
            "000",
            "111",
            "222"
          ]
        }
      }
    }
  },
  "aggs": {
      "metric": {
        "terms": {
          "field": "target_ids",
          "include": ["000", "111", "222"], 
          "size": 3
        }
      }
    }
  }
}
```

Of course, this does not give you back the cardinality but it can be computed easily by counting the keys in the buckets

**Comment by atdfairfax** [comment]
:thumbsup:

**Comment by polyfractal** [comment]
Heya @alepuccetti.  I think this should be doable today with the existing DSL.  Let me know if you think these will work for you.  We'd prefer not to add this functionality if possible, since it opens up a big can of worms; if we add that functionality here, the case could be made that it be added to all other aggregations too.  Which increases the complexity of the change enormously.

It would also tend to be less efficient, since the include/exclude would need to be checked on each document rather than using Lucene's more efficient search methods.

There are three scenarios that I can think of, which should be doable today with the existing DSL:

**Single-valued fields, filtering applies to entire aggregation**
If the terms you want to filter apply to the entire aggregation tree, you can perform the filtering in the query.  The aggregations are computed over the set of documents that match the query, so this will give you the cardinality just for that matching group.

This is also the most efficient, since the aggregation will only run on the matched documents:

```js
{
  "size": 0,
    "query": {
    "bool": {
      "filter": {
        "terms": {
          "target_ids": [ "000", "111","222"]
        }
      }
    }
  },
  "aggs": {
    "restricted_cardinality": {
      "cardinality": {
        "field": "target_ids"
      }
    }
  }
}
```

**Single-valued fields, filtering applies to subset of aggregation**

If you need the filtering to only apply to part of the aggregation, because other parts should remain unfiltered, you can use the `filter`/`filters` aggregation to isolate the scope:

```js
{
  "size": 0,
  "aggs": {
    "agg_filter": {
       "filter": { "terms": { "target_ids": [ "000", "111", "222"] } },
       "aggs": {
         "restricted_cardinality": {
            "cardinality": {
              "field": "target_ids"
            }
          }
       }
    },
    "unrelated_max": {
      "max": { "field": "some_other_field" }
    }
  }
}
```

Note that the cardinality aggregation will be filtered to just documents that have those three tokens, while `unrelated_max` will calculate the max over all documents because it is outside of the `filter` aggregation

**Multi-valued field**

The above two solutions work great if your fields are single-valued, but can be problematic if you have multi-valued fields (multiple values in each field).  A field may match the filter criteria, but since it has multiple values, the cardinality agg will pick all of those up even though only one matched the filter.

In that case, scripting support on the cardinality agg should work:

```js
"restricted_cardinality" : {
  "cardinality" : {
    "script": {
      "lang": "painless",
      "source": "doc['target_ids'][0].value"
    }
  }
}
```

This allows you to select the specific value you care about, or loop over all the values to find the one that matches your filtering criteria.  Not quite as clean, but it should work.  This approach can be combined with either query filtering or agg filtering as appropriate.

Let me know if this helps!

**Comment by polyfractal** [comment]
Thanks for the discuss link, that helped with background context.

Based on that workaround example you give, the value of `"intersect"` aggregation will be a value from 0 to 3.  Since you said `target_ids` field is single-valued, and you're filtering for certain values in the query, those are the only options, so the `metric` terms agg can have at most 3 buckets.

If that's the case, you could do this:

```js
GET data/_search
{
  "size": 0, 
  "query": {
    "bool": {
      "filter": {
        "terms": {
          "target_ids": ["000", "111", "222"]
        }
      }
    }
  },
  "aggs": {
    "bucket": {
      "terms": {
        "field": "ref_id",
        "size": 10
      },
      "aggs": {
        "restricted_cardinality": {
          "cardinality": {
            "field": "target_ids"
          }
        }
      }
    }
  }
}
```

That will give you the cardinality of `target_ids` for each `ref_id`.  And because the fields are all single-valued, and pre-filtered, you know that the cardinality will only be counting the values of a limited subset (some combination of `["000", "111", "222"]`, or none at all).

I think that's equivalent, but much cleaner since it's using the cardinality agg instead of counting buckets.

> I did not quite get the multi-valued field solution you proposed doc['target_ids'][0].value will just retunr the first id in the list.

Sorry, it wasn't a complete example... I was just writing out a quick script to say that scripting is possible.  An actual script to check multi-values would be more extensive :)

**Comment by alepuccetti** [comment]
@polyfractal 
> Since you said target_ids field is single-valued

Probably I did not explaned me very well. `target_ids` is a multi-valued field. This is why cardinality will not work. It will count also values not in the filter.

**Comment by polyfractal** [comment]
@alepuccetti Ah I see, that does complicate things.  I think this can still be done via a script, but not sure how gross it will be.  Let me play around a little to see the best way to do it, and maybe we can put it back up fro discussion with the search team to see about a feature enhancement if it turns out to be too difficult.

Regarding your bucket_script example, that's actually a very good solution (and one I was going to suggest), with the caveat that the terms agg should remain small.  I noticed in your discuss post that you said there were thousands of `target_ids`, which will make the terms agg difficult to use.  It is optimized for smaller "top n" situations, not returning all the terms.  You may run into performance or memory issues with that route.

**Comment by alepuccetti** [comment]
> maybe we can put it back up fro discussion with the search team to see about a feature enhancement if it turns out to be too difficult.

@polyfractal I am happy to contribute to the discussion. Mine is just a use case, an extreme one, but I believe that this could provide some great out-of-the-box feature.
having a way to get back the "intersect cardinality" with a given input array seems very interesting in general.

> with the caveat that the terms agg should remain small

Unfortunately, I need to set the aggregation size to the number of the ids in the include. I am running performance tests. I am open to other ideas.

> I noticed in your discuss post that you said there were thousands of target_ids, which will make the terms agg difficult to use. It is optimized for smaller "top n" situations, not returning all the terms.

This was the workaround but I know it is not the best (or the supposed) usage of terms aggregation.
In fact, the term aggregation on `target_ids` it is a trick to get back the number of ids ( value between 0 and the number of ids in the include). Also, it has the downside that sorting cannot be performed on the bucket_script metric. I am using doc count as an approximation.

**Comment by colings86** [comment]
@alepuccetti the problem here is that the cardinality aggregation is designed to be used with cardinalities which are not practical to be stored in a HashSet. Providing a list of items to include or exclude is at odds with this since the expectation is that the include/exclude list could be similarly large so would not fit well with a HashSet/List. For this reason we do not think this would be something we'd want to pursue.

**Comment by alepuccetti** [comment]
@colings86 Thank you for the explanation.
I do not know the underline implementation of cardinality operation but I thought that knowing beforehand the element on which compute the cardinality could be a good thing. The include/exclude lists would be just a filter and that the cardinality function will check before update the count.

I have a workaround but it is not precise and has a lot of limitations, I will keep looking for a better solution.
