### ISSUE TITLE
Expunge deletes after shrink

### ISSUE THREAD

**Issue by inqueue** [elastic/elasticsearch#29482]
**Describe the feature**:
[Looking at the Shrink API](https://gist.github.com/inqueue/4e4b43ef0c63ef2af23b78d543022139), the target index consumes twice the amount of disk space as the source index due to unsearchable segments left behind by the API. It would be an easy win to free up disk space by executing a force merge with `only_expunge_deletes=true` after completing the shrink operation. Could these options be considered?

* Add a parameter to `_shrink` to trigger segment removal merged segments; i.e., call `/_force_merge?only_expunge_deletes=true`.
* [Document](https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-shrink-index.html) a clean up step to execute force merge with `only_expunge_deletes=true`.
* Both options above.

**Elasticsearch version** (`bin/elasticsearch --version`):
```
Version: 6.2.2, Build: 10b1edd/2018-02-16T19:01:30.685723Z, JVM: 1.8.0_51
```

**Comment by s1monw** [comment]
hey @inqueue thanks for opening this. I first need to clarify a couple of things:

 * the index you show doesn't have any deleted documents so an call that expunges deletes won't help
 * the reason that there is more space used is that we kick of a [merge](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/index/shard/StoreRecovery.java#L136) after the shrink but don't wait for it to finish. We could but this would mean we need to block for a long time and we don't want that since this is during a recovery.
 * a call to force merge with `/_force_merge?only_expunge_deletes=true` is blocking and will cause a commit (flush in ES terms) after it's done.  The commit / flush is what will free up the merged segments since lucene won't select any segments to force merge (no deletes are present). 
 * if a shard is idle we will force a commit (5 min no indexing) or we commit after a period of indexing. This will cause the old segments to go away. All we need is to wait for the flush to happen. 
* if the merge finishes after the shard is idle we will cause a [flush](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java#L2046) once the last merge is done

given that I think we can close this issue since we are already doing what's needed?

**Comment by s1monw** [comment]
@inqueue I am going to close this for now.
