### ISSUE TITLE
shards Stuck in INITIALIZING of one node

### ISSUE THREAD

**Issue by zyb1994** [elastic/elasticsearch#29553]
**Describe the feature**:restart elasticsearch cluster,primary shards  INITIALIZING

**Elasticsearch version** (`bin/elasticsearch --version`):version-5.6.1

**Plugins installed**: [analysis-icu       5.6.1
                                  analysis-ik        5.6.1
                                  analysis-stconvert 5.6.1
                                  dynamic-synonym    5.6.1
                                  repository-hdfs    5.6.1
                                  x-pack             5.6.1]

**JVM version** (`java -version`):1.8

**OS version** (`uname -a` if on a Unix-like system):3.10.0-693.5.2.el7.x86_64

**Description of the problem including expected versus actual behavior**:my elasticsearch cluster has 16 nodes,when i restart elasticsearch cluster ,all primary shards of one node stuck in INITIALIZING. i hope someone can tell me why it happend and how can i fix it.thanks a lot!

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by tvernum** [comment]
Could you please ask this question on our [discuss forum](https://discuss.elastic.co/c/elasticsearch) where we can provide better support. Those forums are designed to support the kinds of conversations that are necessary for this sort of troubleshooting and problem diagnosis.

Elastic uses GitHub issues for tracking clearly identified bugs and feature requests. Since there is no specific bug identifed in your issue, it would not be possible for us to work on this as a "bug fix".
I'm going to close this ticket for now, but I'm sure someone will be able to help you work through this issue on the [forums](https://discuss.elastic.co/c/elasticsearch). If that process reveals a previously unidentified bug in Elasticsearch, then we can re-open this issue.
 

Thank you.
