### ISSUE TITLE
TermsSetQueryBuilder should support terms lookup

### ISSUE THREAD

**Issue by twilson-palantir** [elastic/elasticsearch#29595]
It seems like it should be possible to implement completely analogously to how it's implemented for terms queries.

I'm using terms set queries to implement conjunctive security polices as envisioned in https://github.com/elastic/elasticsearch/issues/26915#issuecomment-335100412

**Comment by jpountz** [comment]
Actually this is a feature that we are not very happy with due to the fact that it has little benefit compared to fetching terms on client-side, and also introduces complexity internally due to the fact that results of a request do not only depend on the request and the current index but also on data stored elsewhere, which has been challenging for the shard request cache. I would like to not implement it on this query builder and recommend users to fetch terms on the client side.

**Comment by jpountz** [comment]
Discussed in FixitFriday: we won't implement it for the reasons mentioned above.

**Comment by Ghost93** [comment]
Hi,
We are looking to manipulate a score of terms lookup query using the amount of matched terms and could not find a way of doing so. 
Maybe we could achieve something similar using lookup terms set query with manipulation of the ```minimum_should_match_script``` field.
Any chances the Elastic team reconsiders this?
