### ISSUE TITLE
Percolator not working with referenced parent/child queries

### ISSUE THREAD

**Issue by randunel** [elastic/elasticsearch#2960]
I have a `parent` and a `child` collection. The child has the parent properly declared, and all the _search queries seem to be working correctly. But the percolator doesn't seem to work with the has_child query. Is this feature implemented?

**Comment by jpountz** [comment]
I suggest that we document that the percolator does not support parent/child queries and close this.

**Comment by martijnvg** [comment]
The fact that these queries can't be used is already documented: https://github.com/elastic/elasticsearch/blob/master/docs/reference/mapping/types/percolator.asciidoc#limitations

In order to make it more clear that these queries are not supported, I also suggest that fail adding a percolator query that contains a `has_child` or `has_parent` query in the same as we fail when a percolator query contains `range` query with range based on the current time (now).

**Comment by jpountz** [comment]
+1

**Comment by jpountz** [comment]
Thanks @martijnvg !
