### ISSUE TITLE
add AES-GCM cipher to default SSL suites

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29695]
*Original comment by @jaymode:*

The AES-GCM cipher is a AEAD cipher that is available in JDK 8 and has intrinsics in the OpenJDK and Oracle VM. We should add this cipher to the list of supported ciphers in master and start testing with it.

In the past, there have been issues with this cipher being used for LDAP communication with Active Directory. We'll want to keep an eye out for this.

**Comment by jkakavas** [comment]
Looks like https://bugs.openjdk.java.net/browse/JDK-8129238 is backported to Java 8 ( since 8u60 ) and that gives a significant performance boost, not sure if this is enough to motivate us adding AES-GCM to the default supported ciphers in 7.x even when running with < Java 11

**Comment by jaymode** [comment]
This issue should be considered resolved IMO since we support these ciphers running on JDK 11+ since #42082 in 7.x. Regarding support for older JDKs like 8, I think it is worth considering but proper detection of the true hardware acceleration might be a bit tricky due to the fact that OpenJDK and Oracle JDK actually differ in this intrinsic support for 8u, see https://mail.openjdk.java.net/pipermail/jdk8u-dev/2019-November/010630.html and https://bugs.openjdk.java.net/browse/JDK-8129238.

@jkakavas are you ok with closing this issue and possibly opening a new one for support on pre-11 JDKs?
