### ISSUE TITLE
Add built-in client role

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29749]
*Original comment by @uboness:*

Currently we have the `transport_client`role defined in the `roles.yml`. This should be a built-in role that is always available and no need for it to be configurable by the users. In addition, the other lang client libs also require a dedicated role for sniffing. 

Ideally we would define a single roles called `sniffing_client` that both the transport client and the client libs will be able to use. The transport client will always require this role as it's always sniffing (either via `liveness` or via cluster state). The client libs will only need to have this role if sniffing is turned on.

For this to work, we should try to align the sniffing between the client libs and the transport client. Right now the libs use the `nodes info` API while the transport client uses the cluster state. Both approaches are actually insecure as both APIs expose too much sensitive information to the clients. We should probably have another dedicated endpoint for sniffing, one that will only return the transport addresses of the nodes.

> NOTE: 
> 
> One more difference between the client libs and the transport client is that the latter is a local execution (based on the local state of the hit node), while for the client libs (nodes info) it's a broadcasted request.

**Comment by polyfractal** [comment]
Chatted in Fixit Thursday.  Closing due to lack of interest, and the fact that TransportClients will be going away soon.

There's still potential for a dedicated lang-client/http sniffing role... but it feels like a pretty esoteric use-case.  Most production configurations tend to use static lists anyhow, and wouldn't be too hard for users to add a sniffing role if required.
