### ISSUE TITLE
Teach reindex to honor `xpack.ssl.certificate_authorities`

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29755]
*Original comment by @nik9000:*

Right now reindex is fine with ssl but doesn't read `xpack.ssl.certificate_authorities`. It probably should, but I'm not really sure how to make that work because reindex and x-pack don't know about each other. I'm sure we could get it to work by making some common thing inside core that x-pack implements and reindex uses, but I'm not sure it is worth the effort. Maybe? Thus, discuss label.

**Comment by tvernum** [comment]
_Note, this issue is specifically about how to make X-Pack based SSL config available in `_reindex`, not general reindex/SSL questions _

I propose that we do something based around the following

-  *Not* use `xpack.ssl.*` settings because:
   1.  these tend to interfere with other X-Pack features (like watcher connections to https URLs), which prompted us to change the docs in 42f9a990d17c220766614c7b8888bfd12143ce6c 
   2. we're looking to remove those fallback settings anyway (https://github.com/elastic/elasticsearch/issues/29797)

- *Not* add overwrite the system trust config (`SSLContext.setDefault`) because configuring the default system trust incorrectly will also break other features (like watcher) and experience shows that configure SSL well is tricky, and customers often don't completely understand the implication of changes they're making. Making changes to the default SSL context seems trappy. Even if we only supported _adding_ additional CAs, that still has the risk that the JVM would start trusting certs that it shouldn't.

 - As part of a fix I'm working on for #30344, we're planning to introduce _named_ ssl contexts. These allow code that uses the X-Pack SSL Service to ask for a context by name, without needing to have a copy of the actual settings. 

- We now have an SPI concept via #27881. This would allow the reindex module and x-pack module to share code in ways that weren't possible when this issue was raised.

Putting those together, would mean that 

- X-Pack can add some settings to configure an SSL context for "_reindex"
- We can implement a basic SSL provider concept, either in server (core) or in the reindex module through SPI
- X-Pack implements this provider interface, to make SSL contexts available to non X-Pack code
- Reindex uses the discovered service providers to configure an appropriate SSL context.

There's some open questions there like:
- do you need to tell reindex that it should look for a named SSL context?
- is it too lenient to: use x-pack if configured, otherwise use the system default? (We typically lean towards explicit over implicit)
- is SPI the correct approach, or would a standard plugin make more sense?
- do we want to support multiple SSL providers, or require that there be only one?

but all those questions are relatively minor and could be resolved as part of the implementation.

**Comment by tvernum** [comment]
ping: @elastic/es-security , @joshbressers , @eskibars

**Comment by jkelastic** [comment]
@eskibars Do you know if there's an ETA on this? If so, approximately when?
