### ISSUE TITLE
Document Graph API

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29757]
*Original comment by @cwurm:*

It seems there's no documentation on how to use the Graph plugin from Java so far. Instead one has to rely on googling to find tidbits such as https://discuss.elastic.co/t/java-api-for-graph/48076/2

The same seems to be true for all other other X-Pack APIs as well, but it's probably most pressing for Graph since it adds a completely new way of working with the data and brings the most benefit when integrated into an application.

**Comment by debadair** [comment]
Closing as fixed.

The graph Explore API is documented as part of the High level REST client at https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high-x-pack-graph-explore.html.

The documentation for the X-Pack APIs in general have gone through several iterations since this issue was opened.
