### ISSUE TITLE
Allow LDAP realm to restrict authentication to particular group(s)

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29920]
*Original comment by @tvernum:*

Inspired from: https://discuss.elastic.co/t/ldap-group-seems-to-dont-work/67782/4

At the moment, we can restrict LDAP authentication to particular sub-trees, (using either user-templates, or user-search from a particular root node), but we don't have anything that can be used to achieve a similar outcome based on groups.

I propose that we add configuration for `require_groups.names` (array setting) and `require_groups.count` (integer setting) 

If `require_groups.names`is set, then users can only authenticate if the group resolver has assigned them to _N_ of the named groups, where _N_ is `require_groups.count` _or-else_ `1`

If `require_groups.count` is set, but `.names` is not, just require that the user is resolved to be in at least `.count` groups, of any name.

If the user is not in the required groups, then authentication would fail in the same manner as if the user was not found. 

I would apply this _before_ role-mapping, so it would work directly on LDAP groups, even those that might not be mapped onto a role.

**Comment by tvernum** [comment]
Discussed with @elastic/es-security 

We could have a `allow_no_roles` option that would trigger a specific security failure message like "you have no roles" instead of the standard "you are not authorized to ...." but that's not really going to deliver a lot of value.

The solution that customers typically want is: https://github.com/elastic/kibana/issues/18270 instead of something in ES.
