### ISSUE TITLE
Should we add a value_count to buckets in bucket aggregations?

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#30268]
A few requests such as https://github.com/elastic/elasticsearch/issues/23384 have asked for a count of the values that have fallen into the buckets of a bucket aggregation rather than just the document_count. So if you had a document with the values [1,2,2,4] and you ran a histogram agg with interval 1 the response would be the following 4 buckets:
```
{
    "key": 1,
    "doc_count": 1
    "value_count": 1
},
{
    "key": 2,
    "doc_count": 1
    "value_count": 2
},
{
    "key": 3,
    "doc_count": 0
    "value_count": 0
},
{
    "key": 4,
    "doc_count": 1
    "value_count": 1
}
```
So the doc_count returns the number of documents that fell into the bucket but the value_count returns the number of values which fell into that bucket.

Note that this is different from adding a value_count sub-aggregation which would return 4 for buckets 1, 2, and 4 in the above example.

**Comment by jimczi** [comment]
Just a note to say that it might look very easy to do for numeric doc values and scripts since the deduplication per document is done in the aggregator directly but for `keyword` doc values the deduplication for each document is done at index time so the frequency of the duplicated values is lost and we would need to check the postings (if the field is indexed) to retrieve the information. I don't see this as a blocker though but more of something that makes this issue more complex than it sounds since it should work seamlessly on all types.

**Comment by csoulios** [comment]
With the introduction of summary field types such as `histogram` and `aggregate_metric_double` field (#56745) running aggregations on summary fields became more complicated. This complexity can be found when querying rollup indices as a single document in the rollup index represents a bucket of documents in the "raw" index. 

To solve the problem of correctly computing the `doc_count` of the bucket we came up with the the `_doc_count` metadata field (#58339).  

It seems that computing a `value_count` in the result of bucket aggregations will hit the same problem as `doc_count`.

**Comment by not-napoleon** [comment]
We don't feel that there's enough benefit to this at this time.  If you need a value count, you can run a value count aggregation under the bucket.
