### ISSUE TITLE
[CI] HTTP Authorization failure in integTestCluster#wait

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#30306]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/6224/console failed in `:x-pack:qa:multi-node:integTestCluster#wait`:

```
> Task :x-pack:qa:multi-node:integTestCluster#wait
Task ':x-pack:qa:multi-node:integTestCluster#wait' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
[ant:get] Getting: http://[::1]:37815/_cluster/health?wait_for_nodes=>=2&wait_for_status=yellow
      [get] Getting: http://[::1]:37815/_cluster/health?wait_for_nodes=>=2&wait_for_status=yellow
[ant:get] To: /var/lib/jenkins/workspace/elastic+elasticsearch+master+periodic/x-pack/qa/multi-node/build/cluster/integTestCluster node0/cwd/wait.success
      [get] To: /var/lib/jenkins/workspace/elastic+elasticsearch+master+periodic/x-pack/qa/multi-node/build/cluster/integTestCluster node0/cwd/wait.success
[ant:get] Getting: http://[::1]:43334/_cluster/health?wait_for_nodes=>=2&wait_for_status=yellow
      [get] Getting: http://[::1]:43334/_cluster/health?wait_for_nodes=>=2&wait_for_status=yellow
[ant:get] To: /var/lib/jenkins/workspace/elastic+elasticsearch+master+periodic/x-pack/qa/multi-node/build/cluster/integTestCluster node1/cwd/wait.success
      [get] To: /var/lib/jenkins/workspace/elastic+elasticsearch+master+periodic/x-pack/qa/multi-node/build/cluster/integTestCluster node1/cwd/wait.success

[ant:get] HTTP Authorization failure
      [get] HTTP Authorization failure

> Task :x-pack:qa:multi-node:integTestCluster#wait FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':x-pack:qa:multi-node:integTestCluster#wait'.
> Elasticsearch cluster failed to pass wait condition
```

There is nothing of note in either of the nodes' logs, which are included in the CI log in full. No `REPRODUCE WITH` line was given.

**Comment by jaymode** [comment]
For closure, I pushed https://github.com/elastic/elasticsearch/commit/9573492a9ee7dc7c5f184e6be854ddc0d82608d8 to fix this failure after seeing https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=ubuntu&&virtual/2397/console fail earlier today.

With the added debug logging we never see any authentication attempts on node-1. However, upon further review the last log line reveals an issue:

[2018-05-03T13:19:02,645][INFO ][o.e.l.LicenseService     ] [node-1] license [898943ad-c458-4728-b883-6e4c83e8a073] mode [basic] - valid

The license doesn't enable authentication/authorization, which may take effect while the request is in flight and we throw an exception from security that results in a 401. In this case, the request has made it into the AuthenticationService prior to the license change to basic. The license changes to basic and then we try to iterate over the realms (either for token extraction or authentication). Since the license does not enable authentication, the realms iterator is empty so authentication fails and the 401 is returned.
