### ISSUE TITLE
Elasticsearch High Level Client : add support for java bean mapping

### ISSUE THREAD

**Issue by fbaligand** [elastic/elasticsearch#30408]
Currently, on Elasticsearch High Level Client, when we index a document or search documents, we can provide or get the document source as a string or as a map ; but not as a java bean.
This would be great to support java bean as a possible source. 

IMO, it is tedious to have to do manually the mapping bean to JSON or JSON to bean, each time we index or search a document.
The community client Jest supports this feature very well, and this is the main reason why I prefer to use Jest for the moment.
This feature makes the development way more easy, comfortable, concise and elegant.

**Comment by fbaligand** [comment]
I'm ready to discuss with you @javanna ! :)

**Comment by nik9000** [comment]
I expect doing this requires some extra dependencies to do the serialization and we have far too many in the high level client as it is. I wonder if we can provide an example of how to do it rather than build it in.

**Comment by fbaligand** [comment]
@nik9000 
Well, given the current dependencies, there is already jackson-core, but indeed, it's not enough.
To do json-bean mapping, the only dependency to add is jackson-databinding.

IMO, the idea would be to add the following method to the API, for search : 
`T SearchHit.getSourceAsBean(Class<T>)`

And this one to index a document : 
`IndexRequest IndexRequest.source(Object source)`

What do you think about ?

**Comment by nik9000** [comment]
I still think we'd be better off giving examples of how to do it. `jackson-databinding` isn't something I want to force on folks.

**Comment by dadoonet** [comment]
It can be marked as optional IMO. So by default people won't have it but if they want to use methods Fabien proposed, they will need to explicitly add the dep in their project.
It also can be a SuperHighLevelClient :) (like what the .Net team has IIRC)

**Comment by fbaligand** [comment]
I like @dadoonet suggestion : add Jackson-databinding as an optional dependency. 
Like this, user can choose to add or not the dependency.

**Comment by nik9000** [comment]
Sooo this has been sitting in my TODO queue for a while, mostly because I hate to do this sort of thing. I talked with a bunch of Elasticsearch developers and we decided not to do this thing, mostly out of concern for another dependency, especially jackson-databinding which has a history of CVEs. It just doesn't sit right with our paranoia.

I think this'd be a super reasonable thing to make as a utility and I'd be support happy to link to this code on the [clients](https://www.elastic.co/guide/en/elasticsearch/client/community/current/index.html#java) page if someone writes it.
