### ISSUE TITLE
How to use aggs query on decimal type field?

### ISSUE THREAD

**Issue by Lee-Think** [elastic/elasticsearch#30524]
I have read the issue #17006, it discussed storing decimal as string. But i want to use aggs query on the decimal type field, how can i do?

**Comment by martijnvg** [comment]
Could you please ask this question on our [discuss forum](https://discuss.elastic.co/c/elasticsearch) where we can provide better support. Those forums are designed to support the kinds of conversations that are necessary for this sort of troubleshooting and problem diagnosis.

Elastic uses GitHub issues for tracking clearly identified bugs and feature requests. Since there is no specific bug identifed in your issue, I'm going to close this ticket, but I'm sure someone will be able to help you work through this issue on the [forums](https://discuss.elastic.co/c/elasticsearch) .

Thank you.
