### ISSUE TITLE
Stemmer Token Filter before Synonym (Graph) Token Filter stems synonyms

### ISSUE THREAD

**Issue by byronvoorbach** [elastic/elasticsearch#30614]
When using stemming before synonyms, my results still get stemmed: (_analyze explained output)
 
   ```
{
        "name": "stemming_nl",
        "tokens": [
          {
            "token": "aap",
            "start_offset": 0,
            "end_offset": 3,
            "type": "word",
            "position": 0,
            "bytes": "[61 61 70]",
            "keyword": false,
            "positionLength": 1,
            "termFrequency": 1
          },
          {
            "token": "mies",
            "start_offset": 4,
            "end_offset": 8,
            "type": "word",
            "position": 1,
            "bytes": "[6d 69 65 73]",
            "keyword": false,
            "positionLength": 1,
            "termFrequency": 1
          }
        ]
      },
      {
        "name": "synonymgraph",
        "tokens": [
          {
            "token": "aapmie",
            "start_offset": 0,
            "end_offset": 8,
            "type": "SYNONYM",
            "position": 0,
            "bytes": "[61 61 70 6d 69 65]",
            "keyword": false,
            "positionLength": 1,
            "termFrequency": 1
          }
        ]
      }
```
Is this to be expected? Or is this an issue?

I'm seeing this problem in ES5.5.1 and ES6.2.2
A complete example to try out:

```
DELETE test
PUT test
{
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 0,
    "analysis": {
      "filter": {
        "synonyms": {
          "type": "synonym_graph",
          "synonyms": [
            "aap mies=>aapmies"
          ]
        },
        "stemming_nl": {
          "type": "stemmer",
          "language": "dutch_kp"
        }
      },
      "analyzer": {
        "match_analyzer_search": {
          "tokenizer": "whitespace",
          "filter": [
            "trim",
            "asciifolding",
            "lowercase",
            "stemming_nl",
            "synonyms"
          ]
        }
      }
    }
  }
}

GET test/_analyze
{
  "explain": "true",
  "analyzer": "match_analyzer_search",
  "text": [
    "aap mies"
  ]
}
```

According to the defined filters, you would expect synonyms to be handled as the last filter. Resulting in to the term: `aapmies`. This sadly doesn't happen. It feels as if the `stemming_nl` get handled last, no matter the order compared to synonyms. 
Tested with both `synonym` & `synonym_graph` token filters, but changing that didn't matter

**Comment by jimczi** [comment]
> Is this to be expected? Or is this an issue?

Your recreation in 5.x gives different result (`appmies`) because this is a 6.x change, starting in 6.0 synonyms are analyzed with whatever tokenizer and token filters appear before it in the chain:
https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_60_analysis_changes.html#_synonym_token_filter
This is an important change that makes sure that the synonym forms registered in the dictionary match the form of the tokens after the transformation of the previous filters. If you have a stemmer in your chain then all tokens should be stemmed otherwise you'll miss synonym hits and matches (what happens if you search for `appmies` directly). 
I see this behavior as an enhancement, you don't need to apply the filters to your synonyms manually and that simplifies the creation of synonym rules greatly. Can you explain why do you think it's an issue ?

**Comment by jimczi** [comment]
> But aapmies is on the right-hand side & I'm only using synonym_graph during search-time.
If I have aapmies in my index, I will never match it.

Isn't it the opposite ? If we don't apply stemming to `appmies` at query time (whether it comes from a synonym or is queried directly) then it will never match anything since stemming is also applied at index time ?

**Comment by byronvoorbach** [comment]
But what if I don’t use stemming on index-time? It feels like I’m less in control now, since I was already able to do stemming by placing a stemming filter after my synonym filter.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jimczi** [comment]
> But what if I don’t use stemming on index-time?

Why would you do that ? Stemming is not like synonyms, if you apply it it should be at index **and** query time. Again I really see this behavior as an enhancement that simplifies things. What happens if you add a synonym output with uppercase characters or characters that are rewritten by a char filter ?Without this behavior you need to ensure that the synonym output matches the output that you index. 
Sorry but I don't see a valid use case where this behavior is not wanted and without it you'd need to perform the transformation manually before setting your synonym rules.

**Comment by romseygeek** [comment]
Closing as we don't believe this to be an issue.  Please re-open if you feel there are still problems to be discussed.

**Comment by sachin-frayne** [comment]
I am trying to figure out why the following does not work with synonyms `cours,learn`, but it does work with `course,learn`, as far I I understand the stemmed version of `course` is `cours` in the same way as the root form for `learning` is `learn`.

```
PUT index
{
  "settings": {
    "analysis": {
      "filter": {
        "my_synonym": {
          "type": "synonym",
          "lenient": true,
          "synonyms": [
            "cours,learn"
          ]
        },
        "english_stemmer": {
          "type": "stemmer",
          "language": "english"
        }
      },
      "analyzer": {
        "my_analyzer": {
          "type": "custom",
          "tokenizer": "standard",
          "filter": [
            "lowercase",
            "english_stemmer",
            "my_synonym"
          ]
        }
      }
    }
  }
}

POST index/_analyze
{
  "analyzer": "my_analyzer",
  "text": ["courses"]
}
```

**Comment by cbuescher** [comment]
>  as far I I understand the stemmed version of `course` is `cours` in the same way as the root form for `learning` is `learn`

Yes, but the analysis chain preceeding the synonym filter is applied to the input rules as well. So if you used the "cours, learn" rule, that gets stemmed to "cour, learn" and won't match. No helpful here, but generally speaking also using "explain: true" with in the analyze endpoint gives you more insight into what happens after each filter.

**Comment by sachin-frayne** [comment]
Thanks, just came back to type exactly that, I added in the English stemmer twice started getting the right results and then figured that the synonyms must also be going through the stemmer, I did not understand that from the wording.

> This is an important change that makes sure that the synonym forms registered in the dictionary match the form of the tokens after the transformation of the previous filters. 

So in essence, both the user's text plus the synonyms pass through the stemmer, and `course` is just, unfortunately, a term that can be stemmed twice, unlike `cats` for example
