### ISSUE TITLE
Use `enabled=0` for yum repository docs

### ISSUE THREAD

**Issue by jpcarey** [elastic/elasticsearch#30660]
**Describe the feature**: Change documentation to have repositories disabled by default (`enabled=0`). It would be safer and avoid unintentional upgrades to have the repository disabled and instruct users to explicitly enabled it when actually necessary (ex. `yum --enablerepo=elasticsearch install elasticsearch`). We should add a short paragraph explaining why it is disabled by default, and that it is an operational choice on whether to enable it.

For deb installs, it looks like we would need to provide default instructions for pinning, but the steps involved can vary depending upon the distribution - which seems better suited to be split out to a different issue if that is something we want to tackle.

https://www.elastic.co/guide/en/elasticsearch/reference/current/rpm.html#rpm-repo

**Comment by rjernst** [comment]
We discussed this in FixItThursday, and agree to move ahead with this. A couple additional things we plan to do:
* add an explicit comment in the example repo file indicating the enabled=0 means it must be explicitly enabled when running commands
* change the repo name to just `elasticsearch`, so that users do not accidentally add eg both 6.x and 7.x and unknowingly upgrade a major version

**Comment by jrodewig** [comment]
[docs issue triage]

Leaving open. This is still relevant:
https://www.elastic.co/guide/en/elasticsearch/reference/7.4/rpm.html#rpm-repo
