### ISSUE TITLE
Attempt to get cardinality or the count of buckets in date histogram 

### ISSUE THREAD

**Issue by toddferg** [elastic/elasticsearch#30685]
It would be helpful to have a method to retrieve the count of available buckets before querying all of the documents.  In the query to prevent extremely large queries from taking place.  For example: it would be helpful to be able to run this aggregation to see the total number of buckets that could be returned before actually querying the bucket size.

An example aggregation that gets close by returning the count of the buckets but this query still hits all of the documents : 

```
GET unifi-2018*/_search
{
  "size": 0, 
  "aggs": {
    "date_histo": {
      "date_histogram": {
        "field": "@timestamp",
        "interval": "month"
      }
    },
    "count_buckets" : {
      "stats_bucket": {
        "buckets_path": "date_histo._count"
      }
      }
    }
}
```

Being able to get the list of the potential buckets before executing the query would be helpful to prevent a cluster from being overwhelmed by an extremely large date range.

**Comment by animageofmine** [comment]
Todd, thank you for filing this request. This would be really helpful enhancement / feature and I hope this is implemented ASAP.

**Comment by colings86** [comment]
I'm not sure I understand how we could achieve this without hitting all the documents. We have no idea before collecting documents which buckets might be created. In theory we can look at the range of values in the whole shard but this:
1. does not generalise well to all aggregations (I think if we implemented a feature like this it would be important it applied to more than one aggregation)
2. Does not take into account the fact that the query can vastly limit the buckets collected (the query does not have to be a date range query to limit the results to a much smaller number of buckets)

So the only way to know how many buckets will be created by an aggregation is to collect the documents that match the query and create the resulting buckets, which means we can't do much better than just running the aggregation IMO.

Can we take a bit of a step back here and can I ask, what is the problem you are trying to solve by this request? What issue is causing this feature request?

**Comment by jimczi** [comment]
In 6.2 we added a new dynamic cluster setting called `search.max_bucket` that fails requests that try to return more than N bucket:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket.html
 It is disabled by default in 6.x and set to `10,000` by default in 7. This setting is applied at the shard level and in the coordinating node when the aggregation responses are merged. It doesn't prevent OOM completely since the number of buckets is checked at the end of the collection on each shard (we collect all buckets and then check the number of reduced buckets that need to be sent to the coordinating node) but it will prevent the coordinating node to run the pipeline aggregation if the number of buckets is too high. In a sense it is similar to the second solution that you propose but it is not restricted to `date_histogram` or single level aggregation and can be integrated in the main request (no need to run a pre-aggregation).

**Comment by tomcallahan** [comment]
@animageofmine do you think @jimczi suggestion will work well?

**Comment by animageofmine** [comment]
@tomcallahan On a vacation right now, but will check as soon as I get back. Just wanted to ack in the meanwhile.

**Comment by javanna** [comment]
hi @animageofmine did you have the chance to check this out? We would like to know whether the proposed solution works for you.

**Comment by astefan** [comment]
Hey @animageofmine, we haven't heard back from you in more than 3 months and I'm assuming you adopted one solution after all. We would love to hear what did work for you in the end. Until then, though, I'll go ahead and close this issue since it stalled for too long. Please, feel free to update it afterwards if you have any feedback/follow up for us.

@harishks even though your issue might be similar, the feature you are looking for is different. I suggest having a look at [`value_count` aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/6.4/search-aggregations-metrics-valuecount-aggregation.html) which might help you or, if you believe it's not the feature you are looking for, please raise another issue describing the new desired functionality.

**Comment by animageofmine** [comment]
@astefan @javanna I am so sorry I didn't respond back to this (my bad). We don't have a clean solution unless we pull a reasonably large payload out of ES and compute ourselves, which is expensive. IMO, the best option is to consider implementing this in ES itself. Anything that you can do to help us would be really appreciated.
