### ISSUE TITLE
Rest apis not allowing body are not testable

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#30749]
The forcemerge api taks all arguments in http params. The rest api spec for this api sets the body to null, meaning "does not allow body". However, the rest action doesn't actually check this (see #29584).

When adding validation no body exists in forcemerge requests, I tried adding a rest test. Unfortunately, the rest test runner rejects this test because the api spec says a body is not allowed.

This issue is to discuss the best way to test such exceptions of similar apis.

**Comment by jasontedor** [comment]
I think this can be done with a unit test on the handler. I do not see a need for this to be a YAML test as those are primarily geared towards enabling the language clients to test client functionality whereas I think this issue is more about testing that the REST handler does the right thing when given a body when it should not be given one. A handler is easy to create in a unit test:

```java
        final RestForceMergeAction handler = new RestForceMergeAction(Settings.EMPTY, mock(RestController.class));
```

and a request with a body can be cooked up

```java
        final FakeRestRequest request =
                new FakeRestRequest.Builder(NamedXContentRegistry.EMPTY).withContent(...).build();
```

and then check that the handler throws an exception on 

```java
        handler.prepareRequest(request, mock(NodeClient.class));
```

**Comment by nik9000** [comment]
I think we could do it with a Java based REST test if we want to but I agree with Jason that it is probably good enough to do it with a unit test. It'd certainly be faster.

**Comment by rjernst** [comment]
I'm certainly happy with unit tests and have written one. I opened this issue more to discuss how to ensure we check all apis that claim to not support body. But I guess that is too advanced for now. Maybe if we ever generate classes from the spec we can generate some tests too.
