### ISSUE TITLE
About Coordinating Node Issue

### ISSUE THREAD

**Issue by softwareklinic** [elastic/elasticsearch#30773]
We are using Elasticsearch 5.x and in production - we have a Java based application that communicates with Elasticsearch using the TCP transport API -- we are passing 4 coordinator node HOST & PORT while establishing the connection...

But what we observed is that when the 1st node in the LIST (one node) - went down -- none of the clients were able to connect and the entire site was down --- that was dependent on elasticsearch.

Thoughts --- feel free to ask for more details if need be -- appreciate urgent response from anyone who can provide any insights... 

Thank you
 Keyur

**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by tvernum** [comment]
Could you please ask this question on our [discuss forum](https://discuss.elastic.co/c/elasticsearch) where we can provide better support. Those forums are designed to support the kinds of conversations that are necessary for this sort of troubleshooting and problem diagnosis.

Elastic uses GitHub issues for tracking clearly identified bugs and specific feature requests. Since there is no specific bug identifed in your issue, I'm going to close this ticket, but I'm sure someone will be able to help you work through this issue on the [forums](https://discuss.elastic.co/c/elasticsearch).

Thank you.

**Comment by softwareklinic** [comment]
Yes makes perfect sense...

**Comment by DaveCTurner** [comment]
Discuss thread: https://discuss.elastic.co/t/issue-with-coordinator-node-down/132722/2
