### ISSUE TITLE
[Feature Request] Request to honour the aggregate nested filters despite reverse nesting.

### ISSUE THREAD

**Issue by kkhaitan** [elastic/elasticsearch#30841]
**Describe the feature**: As of today if a nested aggregate filter is defined post which a reverse nested sub-aggregate is placed the context for the filter is lost for any further nested sub-aggregate. The only resolution for this is to repeat the filter over and over again at each of the sub-aggregate level. This problem has been faced by multiple developer one of the instance being:
https://discuss.elastic.co/t/reverse-nested-aggregations-with-filters/125128

Ideally until and unless a nested sub-aggregate overrides the filter the parent nested filter should be honoured despite the introduction of reverse nesting instead of the same filter being repeated in each of the nested sub-aggregate instance.

Please feel free to revert back if you need any additional information from my end.

(From my end verified the existing list of feature/bug but couldn't find the relevant information, currently I'm using v5.5.2)

**Comment by jpountz** [comment]
> Ideally until and unless a nested sub-aggregate overrides the filter the parent nested filter should be honoured despite the introduction of reverse nesting instead of the same filter being repeated in each of the nested sub-aggregate instance.

I think we are on the same page, but to clarify, the filter is not ignored, the use of `reverse_nested` then `nested` again just changes its meaning. Instead of meaning "all documents that match X", it means "all documents whose parent has a nested document that matches X" where `X` is the filter that you decided to apply to your nested documents.

We might be able to apply your suggestion, but then some aggregations that can be run today couldn't be run anymore. Let's image an index that contains movies and actors as nested documents. Now we want to aggregate all actors that played in a movie with John Wayne. We need to go to the actor documents to filter on "John Wayne" then go back to the movies and forth to actors to find other actors from the same movie. But if the second nested aggregation had applied the same filter, then we would only see "John Wayne" even though the actors we are interested in are the other ones.

I also like to keep the behavior of aggregations independent of each other, so I'd be a bit on the fence to implicitly apply filters because they were applied on a parent aggregation on the same nested path.

Note that since nested and reverse nested aggregations have some overhead, it's also useful to think about whether denormalization can help. For instance in the example from the discuss link, repeating `rootName` on all elements in the second nesting level would help simplify the aggregation by removing the need to use a `reverse_nested` aggregation to aggregate on a property of a parent document. So it wouldn't be necessary to repeat the filter anymore and the aggregation would likely run significantly faster.

**Comment by imotov** [comment]
Based on @jpountz comment this is not something that we are planning to implement in the near future. Should we close it?
