### ISSUE TITLE
missing functionality to aggregate all geo shape points in index

### ISSUE THREAD

**Issue by maltegrosse** [elastic/elasticsearch#30896]
Hi,

i couldnt find any solution to aggregate all geo_shape points of one index.
example mapping would be like:

`{
	"weather-index": {
		"mappings": {
			"doc": {
				"properties": {
					"atmospheric_pressure": {
						"type": "float"
					},
					"average_air_temperature": {
						"type": "float"
					},
					"location": {
						"type": "geo_shape"
					},
					"observation_date": {
						"type": "date"
					},
					....
				}`

as for every date and location there is one new entry, i can only find all documents with locations (exists), but not aggregate (count same) them.
each location + date is unique. but in one index is only a certain amount of same locations.

any suggestions?
(a workaround on client level: query each day, save them in a list and remove duplicates...but takes quite long for multiple years)

**Comment by cbuescher** [comment]
Hi @maltegrosse! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. 
I'm closing this as an issue here, but encourage you to ask this question in the forum instead. If it turns out there is some functionality missing after discussing this in the forums, I encourage you to re-open this issue here, maybe with a link to the previous forum discussion. Many thanks.
