### ISSUE TITLE
How to achieve it just like "select user_id from sales group by user_id having count(*) > 3"

### ISSUE THREAD

**Issue by nicholas251291740** [elastic/elasticsearch#30918]
How to achieve it just like "select user_id from sales group by user_id having count(*) > 3". I'm using the way of nested, thanks!

**Comment by dnhatn** [comment]
@nicholas251291740 Please ask questions on https://discuss.elastic.co where we can give you a better support. We use Github for bug reports and feature requests. Thank you.

**Comment by tvernum** [comment]
Could you please ask this question on our [discuss forum](https://discuss.elastic.co/c/elasticsearch) where we can provide better support. Elastic uses GitHub issues for tracking clearly identified bugs and feature requests. Since there is no specific bug identifed in your issue, I'm going to close this ticket, but I'm sure someone will be able to help you work through your question on the [forums](https://discuss.elastic.co/c/elasticsearch) .

Thank you.
