### ISSUE TITLE
Access _source in query script 

### ISSUE THREAD

**Issue by ruizmarc** [elastic/elasticsearch#30984]
**Feature request** 

Although it is known that accessing doc is much faster, there are some use cases in which _source is required when filtering, for example due to the the limitations of doc with nested objects, especially if they are related and have an impact on the parent.

**Comment by colings86** [comment]
Accessing the `_source` field is slow and something that we don't want to expose in the ScriptQuery because it would be need to be accessed on every document making the search very inefficient. 

What is the reason that using nested queries does not fit your use case?

**Comment by ruizmarc** [comment]
Let's imagine that we have a hierarchy of three levels. 

Grandparent 1 - n parent
parent 1 - n child. 

Each level has an status. Grandparent status is calculated based on each of the parents. Each parent status is calculated based on each child status. So if I want to filter based on grand parent status, I need an script to calculate the status of parents and childs. I didn't really find a way to do this with nested queries. Maybe there is a way, but I couldn't really find it.

**Comment by colings86** [comment]
Given you are using nested documents and therefore need to re-index the grandparent, all parents and all there grandchildren with every update you could just calculate the status at each level at index time and add a status field to the grandparent, parents, and children which can then be queried directly using the match query

**Comment by ruizmarc** [comment]
Really? I was using nested objects to avoid reindexing the entire document. I really thought they were indexed indepedently according to documentation:

> The nested type is a specialised version of the object datatype that allows arrays of objects to be indexed and queried independently of each other.

Childs are edited constantly, so I wanted to avoid reindexing the entire document to update status everywhere. That's why it is currently being calculated. If the entire document is reindexed it doesn't really make sense to use nested objects in this scenearios... which I thought it was the really advantatge of using nested objects.

**Comment by colings86** [comment]
The advantage of using nested docs is to avoid something called "cross-matching". To explain what this is imagine you are indexing actors and in the actor document you store an array of objects representing the films they have been in. These inner film objects have a name, genre and total box office sales amount. If you are searching for actors that have been a film which is a comedy and got over 50 million in box office sales then without using nested documents you can match actors who have been in a comedy  and in a different film that got over 50 million at the box office. Making the film a nested object and using the appropriate nested queries will allow the two conditions to be connects so a single film the actor has been in must both be a comedy AND have got over 50 million at the box office.

The searches with nested object can still be relatively fast (still slower than embedded object though) because the nested documents are always stored next to the root document in the index. This proximity is the reason that the entire hierarchy has to be re-indexed on every update to even a single document in the hierarchy.

I agree the documentation is a little confusing here I think it is trying to say:

> The nested type is a specialised version of the object datatype that allows arrays of objects to be indexed in a way that they can be queried independently of each other.

I will raise a PR to make this change int he documentation. Since the original feature request for this issue is not something we are wanting to pursue I am also going to close this issue
