### ISSUE TITLE
delayed shards can not allocate on left_node, due to ShardsLimitAllocationDecider or SameShardAllocationDecider after left_node joined cluster

### ISSUE THREAD

**Issue by vsop-479** [elastic/elasticsearch#31052]
Elasticsearch version:
5.2.1

Plugins installed: 
null

JVM version: 
1.8.0_112

OS version:
Linux   2.6.32-220.el6.x86_64 #1 SMP Tue Dec 6 19:48:22 GMT 2011 x86_64 x86_64 x86_64 GNU/Linux

Description of the problem including expected versus actual behavior:
After left_node rejoined the cluster, somehow it will be allocated some other shards, 
but not the shards which delayed because its left. 
So delayed shards can not allocate on left_node, due to ShardsLimitAllocationDecider or SameShardAllocationDecider after left_node joined cluster.

**Comment by cbuescher** [comment]
Hi @vsop-479. At first glance, it seems your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and from the limited amount of information available I'm not conviced this is a bug. 
I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Please provide some more input about the context (like: what does your cluster look lioke, what are you doing when this error happend) when you state your question there. If it turns out to be a genuine bug we can open another issue here. Hope this helps.

**Comment by vsop-479** [comment]
@cbuescher ok, thanks.
