### ISSUE TITLE
suggest/30_context.yml "Indexing and Querying without contexts is deprecated" failing

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#31116]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=oraclelinux/1104/console

REPRODUCE WITH: ./gradlew :x-pack:qa:core-rest-tests-with-security:integTestRunner \
  -Dtests.seed=D58499EECE0F23E3 \
  -Dtests.class=org.elasticsearch.xpack.security.CoreWithSecurityClientYamlTestSuiteIT \
  -Dtests.method="test {yaml=suggest/30_context/Indexing and Querying without contexts is deprecated}" \
  -Dtests.security.manager=true \
  -Dtests.locale=nl-NL \
  -Dtests.timezone=NZ \
  -Dtests.rest.blacklist=cat.aliases/10_basic/Empty cluster,index/10_with_id/Index with ID,indices.get_alias/10_basic/Get alias against closed indices,cat.templates/10_basic/No templates,cat.templates/10_basic/Sort templates,cat.templates/10_basic/Multiple template

fails with an error:
FAILURE 0.31s | CoreWithSecurityClientYamlTestSuiteIT.test {yaml=suggest/30_context/Indexing and Querying without contexts is deprecated} <<< FAILURES!
16:06:40    > Throwable #1: java.lang.AssertionError: Failure at [suggest/30_context:402]: did not get expected warning header [
16:06:40    > 	The ability to query with no context on a context enabled completion field is deprecated and will be removed in the next major release.
16:06:40    > ]

The failure (without blacklist option) doesn't reproduce on my local machine.

**Comment by jimczi** [comment]
I muted the test and will investigate.

**Comment by jimczi** [comment]
I reenabled this test since we were not able to reproduce. I'll reopen if it happens again.

**Comment by jimczi** [comment]
It fails in CI again. I muted the test again and will investigate the logs

**Comment by colings86** [comment]
Latest Build failure was: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+periodic/2701/console

**Comment by colings86** [comment]
This comment from another issue could be relevant here: https://github.com/elastic/elasticsearch/issues/28600#issuecomment-385079819

It was similar in that an expected warning header was not found and was "solved" by reducing the test to only use one shard. The fact that the test no longer failed indicates that the problem might be in the warning header system rather than in specific deprecation call sites so maybe we could try moving to a single shard here and if that stops the failures look into this as a systematic problem in the deprecation warnings infrastructure?

**Comment by jimczi** [comment]
This test revealed a bug in how we pass the response headers from internal shard search request to the final search response. I opened https://github.com/elastic/elasticsearch/issues/33936 to track this issue. However there is another issue here, we don't issue the deprecation warning on empty indices because suggesters are omitted in this case. I'll open a pr to fix this since we want the deprecation warning even if the index is completely empty.

**Comment by jimczi** [comment]
This issue is not related to test-failure anymore and the bug is tracked by #33936 so I am closing it.
