### ISSUE TITLE
ElasticSearch 5.6.9: Issue with updating dynamic template created on 2.x 

### ISSUE THREAD

**Issue by shashanka981** [elastic/elasticsearch#31231]
{
   "error":    {
      "root_cause": [      {
         "type": "mapper_parsing_exception",
         "reason": "failed to parse"
      }],
      "type": "mapper_parsing_exception",
      "reason": "failed to parse",
      "caused_by":       {
         "type": "illegal_argument_exception",
         "reason": "Can't parse [index] value [not_analyzed] for field [ID_NEW], expected [true] or [false]"
      }
   },
   "status": 400
}

Facing the above issue when Performing indexing into an index that was created on 2.4, but started using 5.6.9 version of ElasticSearch. 

For reproducing the issue, follow the below steps
1) Create an index in ElasticSearch 2.4 version with the following dynamic template
  {  
   "dynamic_templates":[  
      {  
         "others":{  
            "path_match":"*",
            "mapping":{  
               "index":"analyzed",
               "norms":{  
                  "enabled":false
               },
               "store":false,
	       "type": "string"
            }
         }
      }
   ]
}

2) index a sample document
 {  
   "ID":[  
      "emp1"
   ]
}

3) Now start the ES 5.6.9 version against the index created above. update the above Dynamic Template definition to remove the  **type** attribute. So, template now looks like 

{  
   "dynamic_templates":[  
      {  
         "others":{  
            "path_match":"*",
            "mapping":{  
               "index":"analyzed",
               "norms":{  
                  "enabled":false
               },
               "store":false,
            }
         }
      }
   ]
}

4) Now index a new document, with a new field for which mapping was not already existing in the index 

{  
   "ID":[  
      "emp1"
   ],
    "ID_NEW"[
       "empnew"
   ]
}

This step would fail with a mapping parser exception , as pointed at the start of the post.
Something seems to be wrong with dynamic mappings on updation of dynamic templates.

However, creating the index on a 5.6.9 version using the dynamic templates mentioned in step 3 would work fine..

**Comment by jtibshirani** [comment]
Hi @shashanka981, I'm sorry for the very late response to your issue. When I ran through the reproduction steps, I got the following error (slightly different from the one you pasted above, which mentions `not_analyzed` instead of `analyzed`):

```
"caused_by": {
    "type": "illegal_argument_exception",
    "reason": "Can't parse [index] value [analyzed] for field [field], expected [true] or [false]"
}
```

In 5.0, the `string` field type was [broken into two distinct types](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_mapping_changes.html#_literal_string_literal_fields_replaced_by_literal_text_literal_literal_keyword_literal_fields), `keyword` and `text`. The `keyword` type is meant for unanalyzed strings, whereas the `text` field applies an analyzer to the field content. With this distinction in place, the `index` settings now only accepts a boolean, as opposed to enums like `analyzed`, `not_analyzed`. The proper way to adjust the dynamic template from 2.x would be to remove the `index` setting, and switch to the `text` type:

```
{
  "dynamic_templates": [
    {
      "others": {
        "path_match": "*",
        "mapping": {
          "norms": false,
          "store": false,
          "type": "text"
        }
      }
    }
  ]
}
```

Note that the `norms` setting has also been collapsed into a single boolean.

I'm not clear on why there is a difference in behavior between 2.x and 5.x in terms of how we handle the setting `"index": "analyzed"`. We are not likely to dig further into this because we are no longer cutting new 2.x and 5.x releases, so I think it's best to close out the issue.
