### ISSUE TITLE
RollupIT disables all thread leak detection

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#31258]
Currently the main rollup integration test disables all thread leak detection: https://github.com/elastic/elasticsearch/blob/2efd22454a62e7387c51eb0cd973e5ff7a3fb09f/x-pack/plugin/rollup/src/test/java/org/elasticsearch/xpack/rollup/RollupIT.java#L64-L65

I think that this should be unnecessary, I think that the only thread that should be filtered out here is the `ObjectCleanerThread` from Netty (relates elastic/elasticsearch#31232). It looks like this was added for the `trigger_engine_scheduler` thread. Can we look into this and see if the thread leak none can be removed and reduced to filter the `ObjectCleanerThread` only (extend `XPackIntegTestCase`)?

**Comment by jasontedor** [comment]
We have reverted the Netty upgrade (#31282, netty/netty#8017) so now I think we should find a way to not need thread leak control here at all.

**Comment by polyfractal** [comment]
I'm inclined to just delete all of `RollupIT`.  

The actual utility of these tests have degraded over time to account for variance... they were supposed to test a end-to-end run and check for accuracy.  But this is hard to check algorithmically, especially once doubles get involved.  So it's mostly just verifying doc counts now, which we are doing in unit tests elsewhere.

It is also flaky, with some transient failures (https://github.com/elastic/elasticsearch/issues/30232). I'm fairly certain are related to tests running over physical midnight -- which changes doc counts slightly -- but I haven't been able to reproduce yet.

It feels like chasing a flaky IT isn't the best use of time (I'm sure @rjernst won't mind deleting an IT :P ).  `testBig` is the only one of semi-value... the other tests have since been replicated in yaml tests.

@colings86 do you have any thoughts?  Mind if I just remove this whole test suite?  If we see value in this sort of test, I'm still inclined to delete it and redo it better as a QA test.
