### ISSUE TITLE
MAX_MAP_COUNT is ignored in BootstrapCheck

### ISSUE THREAD

**Issue by joakimberglund** [elastic/elasticsearch#31354]
**Elasticsearch version** (`bin/elasticsearch --version`):
6.3.0

**Plugins installed**: []
none

**JVM version** (`java -version`):
openjdk version "1.8.0_171"

**OS version** (`uname -a` if on a Unix-like system):
RHEL7.3 in Openshift 3.9

**Description of the problem including expected versus actual behavior**:

MAX_MAP_COUNT=64000
# sysctl -n vm.max_map_count
65530

**[1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]**

The 262144 value is hard coded in the java code **MaxMapCountCheck** instead of using the environment variable.

**Steps to reproduce**:

1. sysctl -q -w vm.max_map_count=65530
2. set MAX_MAP_COUNT=64000 in /etc/sysconfig/elasticsearch
3. run /usr/share/elasticsearch/bin/elasticsearch

**Comment by danielmitterdorfer** [comment]
Quoting the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/6.3/rpm.html#rpm-configuring) for `MAX_MAP_COUNT`:

> Maximum number of memory map areas a process may have. [...]. This is set via sysctl before starting Elasticsearch.

Also:

> Distributions that use systemd require that system resource limits be configured via systemd.

This means that `MAX_MAP_COUNT` is ineffective (because you're not using init.d). Also, the [maximum map count bootstrap check](https://www.elastic.co/guide/en/elasticsearch/reference/6.3/_maximum_map_count_check.html) is intentionally not configurable from the outside so `vm.max_map_count` needs to be set to at least 262144 to pass the check.
