### ISSUE TITLE
[X-Pack] Elasticsearch SQL using JDBC : missing information in official documentation

### ISSUE THREAD

**Issue by fbaligand** [elastic/elasticsearch#31367]
I would try to use Elasticsearch SQL via JDBC, but I miss some information in official documentation : 
https://www.elastic.co/guide/en/elasticsearch/reference/6.3/sql-jdbc.html

Here are the missing points : 
- what is the elasticsearch JDBC driver class name ?
- what is "elasticsearchAddress" format ? "localhost:9200" ? How can I set multiple hosts ?
- what is the full options list I can set into "Properties" object ?
- where can I download Elasticsearch SQL JDBC driver JAR ?

Could you add these missing points in documentation ?

**Comment by nik9000** [comment]
I'll leave it to @costin to update the docs but I'll try an answer some of these:

> what is the elasticsearch JDBC driver class name ?

I don't think you need to specify it because it is in meta-inf, but it is `org.elasticsearch.xpack.sql.jdbc.jdbc.JdbcDriver`.

> what is "elasticsearchAddress" format ? "localhost:9200" ? How can I set multiple hosts ?

`localhost:9200` or `http://localhost:9200` or `https://localhost:9200`.

I don't believe you can set multiple hosts at this point.



> what is the full options list I can set into "Properties" object ?

It looks like `debug=true|false`, `debug_output=err|out`, `timezone=some_time_zone_id`. The defaults are `false`, `err`, and whatever your JVM's default time zone is.

> where can I download Elasticsearch SQL JDBC driver JAR ?

You can download it [here](https://artifacts.elastic.co/maven/org/elasticsearch/plugin/jdbc/6.3.0/jdbc-6.3.0.jar) but you'll probably want to resolve it from our maven repository.

For 6.3.x we bundle it with all of its dependencies [here](artifacts.elastic.co/downloads/elasticsearch/elasticsearch-jdbc-with-dependencies-6.3.0.zip). Like the high level rest client it depends on a bunch of bits of the Elasticsearch server. In 6.4 we removed most of the dependencies. It'll depend on just `jackson-core` which we've shaded into it. But in 6.3 you'll have to suffer through too many dependencies.

**Comment by fbaligand** [comment]
Hi @nik9000,

Thanks a lot for all these answers ! It helps a lot !

That said, the link you give for "driver with dependencies" seems to be broken. Could you fix it ?

Concerning maven repository, indeed, a driver on central maven repository would be very useful.

**Comment by nik9000** [comment]
> Concerning maven repository, indeed, a driver on central maven repository would be very useful.

I don't believe it can go in maven central because it is under the Elastic license. The link that I gave for the jar *is* a maven repository.

I've fixed the to the "with all dependencies" zip in my original comment.

**Comment by fbaligand** [comment]
OK, given jar license, I understand it can’t be deployed on maven central. 
So Elastic maven repository is a great alternative for users like me. 

BTW, as Elasticsearch SQL is free to use, why do Elastic choose X-Pack and  Elastic License, rather than open source and Apache License ?

**Comment by nik9000** [comment]
> BTW, as Elasticsearch SQL is free to use, why do Elastic choose X-Pack and Elastic License, rather than open source and Apache License ?

SQL is free to use but JDBC [requires](https://www.elastic.co/subscriptions) a platinum license. But we totally have things that are free to use but under the Elastic License and for the explanation for that I have to point you to the official Elastic [blog](https://www.elastic.co/products/x-pack/open) post on the topic and to the license itself.

**Comment by fbaligand** [comment]
Thanks for these precisions !
Damned, I didn’t notice that JDBC driver required a platinum license :(

**Comment by costin** [comment]
Hi @fbaligand, thanks for trying out SQL.
The [JDBC page](https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-jdbc.html) has been updated.

Cheers,

**Comment by fbaligand** [comment]
Great ! Thanks @costin !
I look at the new documentation => it is really complete now !
Good job here!

**Comment by hatcherfang** [comment]
> Great! Thanks, @costin!
> I look at the new documentation => it is really complete now!
> Good job here!

Hi @fbaligand,  Does the new documentation solve your case?

 The new documentation seems not complete for me.  

Could you show me the JDBC example code?

**Comment by costin** [comment]
@hatcherfang if you have questions, please use the forum not the issue tracker which is reserved for bug reports.
The documentation of JDBC including examples is available at: https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-jdbc.html
