### ISSUE TITLE
On test failure for upgrades we should log all of the nodes

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#31466]
Right now when an *upgrade* test fails we only log information from the last cluster that we start. But sometimes the interesting failure is hiding in the logs of the other nodes. I think the build should spit out the logs for all of the nodes that we've started as part of the test. I'm not sure how to do that, but it'd be nice.

**Comment by rjernst** [comment]
This was always my intention (see my note in the original PR that added dumping of the logs: https://github.com/elastic/elasticsearch/pull/23688), but, as you say, it is difficult. I think the work @atorok is investigating to create the clusters outside of gradle tasks could make this easier, since we would have a first class view of what clusters/nodes are depended on.

**Comment by atorok** [comment]
This is now solved by testclusters. 
Since nodes are upgraded in-place there's no separate log, the same log is appended to so when we dump it it will dump both pre-and post upgrade logs.
