### ISSUE TITLE
ElasticSearch 6.3 - Binding to Docker0 instead of eth0

### ISSUE THREAD

**Issue by rusher81572** [elastic/elasticsearch#31478]
**Elasticsearch version 6.3.0** 

**Plugins installed**: None

**JVM version** (`java -version`):
```
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system):
```
Linux rpi-1 4.14.44-v7+ #1117 SMP Thu May 31 16:57:56 BST 2018 armv7l GNU/Linux
```

**Description of the problem including expected versus actual behavior**:
ES is trying to bind to docker0's IP, not the machines IP
```
[2018-06-20T12:21:14,679][INFO ][o.e.t.TransportService   ] [rpi-1] publish_address {172.17.0.1:9300}, bound_addresses {0.0.0.0:9300}
[2018-06-20T12:21:14,752][INFO ][o.e.b.BootstrapChecks    ] [rpi-1] bound or publishing to a non-loopback address, enforcing bootstrap checks
ERROR: [1] bootstrap checks failed
```
I tried this outside of docker and installed ES directly on the host to see why the cluster is not joining.
Here is my config:
```
xpack.ml.enabled: false
node.name:  rpi-1
discovery.zen.ping.unicast.hosts: ['live', 'rpi-1', 'rpi-3', 'rpi-4']
http.cors.enabled: true
http.cors.allow-origin: "*"
node.master: true
node.data: true
http.port: 9201
network.host: 0.0.0.0
network.bind_host: 0.0.0.0
```
Specifiying an IP instead of 0.0.0.0 results in the same issue

On an x86 box, my config is the following and everything works fine:
```
network.host:  761db145dc8d
node.name:  761db145dc8d
discovery.zen.ping.unicast.hosts: [ 192.168.0.108, 192.168.0.103, 192.168.0.104]
http.cors.enabled: true
http.cors.allow-origin: "*"
node.master: true
network.publish_host:  192.168.0.108
http.port:  9201
```

When copying the config over to the arm node, I get this error:
```
[2018-06-20T12:29:39,436][INFO ][o.e.d.DiscoveryModule    ] [rpi-1] using discovery type [zen]
[2018-06-20T12:29:44,744][INFO ][o.e.n.Node               ] [rpi-1] initialized
[2018-06-20T12:29:44,745][INFO ][o.e.n.Node               ] [rpi-1] starting ...
[2018-06-20T12:29:45,467][INFO ][o.e.t.TransportService   ] [rpi-1] publish_address {192.168.0.101:9300}, bound_addresses {192.168.0.101:9300}
[2018-06-20T12:29:45,548][INFO ][o.e.b.BootstrapChecks    ] [rpi-1] bound or publishing to a non-loopback address, enforcing bootstrap checks
ERROR: [1] bootstrap checks failed
```
I have never had any issues with ES 6.1.0 and prior on ARMv7, only 6.2.4 and 6.3.0.

**Comment by hub-cap** [comment]
Hi, thanks for the report. The message in the logs about the bind address is only there for elasticsearch to decide whether to enforce bootstrap checks or not. I dont know if its the problem. It is an interesting problem though. Are there no more logs that mention what bootstrap check is failing?

We do not officially support ARMv7, but I think we have some members running it, so I will be sure to ask some internally.

**Comment by rusher81572** [comment]
Thanks for replying. The complete error is:
```
[WARN ][bootstrap ] jvm uses the client vm, make sure
to run java with the server vm for best performance by adding - server to the command line
```

If I remove network publish address, it starts up fine. ES worked fine on ARM before 6.2.4. I had to roll back to 6.1 on my 4 node cluster for the time being.

**Comment by jasontedor** [comment]
From your `uname` output, I see that you're using `armv7l` which is a 32-bit processor. This means that the JVM defaults to the client JVM and that is why this bootstrap check is failing, we require a server JVM when in [production mode](https://www.elastic.co/guide/en/elasticsearch/reference/6.3/bootstrap-checks.html#_development_vs_production_mode). You need to specify the `-server` flag in `jvm.options`. For additional references, please check the [bootstrap check docs](https://www.elastic.co/guide/en/elasticsearch/reference/6.3/_client_jvm_check.html). Why you were not experiencing this before, I can not say. Maybe you had a `jvm.options` file from the 5.x series which contained a `-server` flag by default that we have since removed. Either way, I do not see a bug here so I am going to close this issue. We can reopen if you have additional information that would classify this as a bug.
