### ISSUE TITLE
cannot change logging.yml 

### ISSUE THREAD

**Issue by 13567436138** [elastic/elasticsearch#31495]
version : 2.4.5

```
FROM centerforopenscience/elasticsearch:2.4
ADD  plugins/ /usr/share/elasticsearch/plugins/
ADD  config/synonym.txt /usr/share/elasticsearch/config/analysis/
USER root
RUN mkdir /home/elasticsearch && chown elasticsearch:elasticsearch /home/elasticsearch
ADD  java.policy /etc/java-8-openjdk/security/
USER elasticsearch
ADD home/elasticsearch /home/elasticsearch/
ADD  logging2.yml /usr/share/elasticsearch/config/logging.yml
#ADD  logging2.yml /etc/elasticsearch/logging.yml
ADD  elasticsearch.yml config/elasticsearch.yml
```

the content of /usr/share/elasticsearch/config/logging.yml can not be replaced

**Comment by tvernum** [comment]
Could you please ask this question on our [discuss forum](https://discuss.elastic.co/c/elasticsearch) where we can provide better support. Those forums are designed to support the kinds of conversations that are necessary for solve these sorts of issues. 

Elastic uses GitHub issues for tracking clearly identified bugs and feature requests. Since there is no specific bug identifed in your issue, I'm going to close this ticket, but I'm sure someone will be able to help you work through this issue on the [forums](https://discuss.elastic.co/c/elasticsearch) .

Thank you.
