### ISSUE TITLE
how to config elasticsearch-jdbc from maven?

### ISSUE THREAD

**Issue by kervin521** [elastic/elasticsearch#31641]
![image](https://user-images.githubusercontent.com/9798724/42008777-d4d7128c-7ab9-11e8-909c-8e27f8ab6dea.png)

**Comment by tvernum** [comment]
The SQL/JDBC docs are here: https://www.elastic.co/guide/en/elasticsearch/reference/6.3/xpack-sql.html

Elastic uses GitHub issues for tracking clearly identified bugs and feature requests.
Questions such as these should be asked on our [discuss forum](https://discuss.elastic.co/c/elasticsearch) where we can provide better support.

Since there is no specific bug identifed in your issue, I hope you don't mind if I close this ticket.
Thank you.
