### ISSUE TITLE
Document changes to forcemerge as a breaking change for 6.5

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#31689]
As of Lucene 7.5 (probably Elasticsearch 6.5), the `max_num_segments` option will only be a best effort, and will not be honored if it would require creating segments that are larger than the maximum segment size. https://issues.apache.org/jira/browse/LUCENE-7976

Stalled on the upgrade to Lucene 7.5.

**Comment by polyfractal** [comment]
I think this is unstalled since https://github.com/elastic/elasticsearch/pull/32390 landed?

I think the behavior is slightly different than originally intended, since https://github.com/elastic/elasticsearch/pull/32291 also landed (e.g. we respect `max_num_segments`), but I think that means we may also end up with fewer segments than `max_num_segments`?  The docs still state that you'll get exactly `max_num_segments`

Related: https://github.com/elastic/elasticsearch/issues/32323

**Comment by danielkasen** [comment]
This leads to Force merging down to 1 segment everytime. So even if I say force merge to 20 it'll do the large operation and try to shrink it to 1.

**Comment by danielkasen** [comment]
Any update on if this is the expected behavior going forward? This is causing serious issues within our cluster due to an inability to perform force merge operations.

**Comment by jpountz** [comment]
We made the decision that forcemerge should keep honoring the `max_num_segments` parameter in #32291.
