### ISSUE TITLE
Can we remove get `_source` API

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#31728]
Users can fetch the source only by using `/{index}/{type}/{id}/_source` I do wonder if this is necessary to maintain an extra API for it if somebody can just use [response filtering](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#common-options-response-filtering) for it? I might be missing something...

**Comment by dadoonet** [comment]
I agree that I never heard a lot of usage of this API (if any). The only moment I'm speaking about it is during trainings because there is a slide about this :).

Just a note: source filtering does not do exactly the same thing. It removes non needed meta data but you will still see a structure like:

```
{
  "_source": {
    // My object here
  }
}
```

instead of:

```
{
  // My object here
}
```

But I'm +1 to remove this API.

**Comment by javanna** [comment]
I think it is nice for users to be able to get the document directly without the rest of the fields. I am not sure about how many users use this feature. I would be fine removing it if we had a 1:1 replacement but with `filter_path` you can't really get the same output like David said above, the `_source` field will always be returned it seems?

**Comment by s1monw** [comment]
> I think it is nice for users to be able to get the document directly without the rest of the fields. 

yeah that's the end of every removal discussion.

**Comment by dadoonet** [comment]
I would keep this opened. For now we don't know if people are really using this or not and if they do, is the source filtering workaround ok.

**Comment by javanna** [comment]
The suggested `filter_path` workaround is not a replacement for the get _source api. 
I don't think it helps to tell people to use `filter_path` instead, because if they need to parse the response to extract the `_source`, it makes very little difference whether the other header fields are in there or not. The point of this API is to get the source only, not wrapped in any other object.

That's why I think we should be reasoning around the "are users using this feature?" question and decide whether we can remove it based on that, knowing that there is no replacement for it, as part of the effort to reduce the number of API that we expose.
