### ISSUE TITLE
Unable to index certain files in ElasticSearch

### ISSUE THREAD

**Issue by ujjwalGargFS** [elastic/elasticsearch#31770]
**Describe the feature**:

**Elasticsearch version** 6.0:

**Plugins installed**: [Ingest]

**JVM version** (`java -version`):

**OS version** AWS ElasticSearch Instance:

**Description of the problem including expected versus actual behavior**:
I have an AWS ElasticSearch instance. I am using Ingest plugin to index attachments (doc, docx, pdf, pptx, ppt, txt, xls,and xlsx) and perform the full-text search. To test, I index sample files of each format and it worked fine.

Now the problem is, for certain file, it throws an error.
 

**Provide logs (if relevant)**:

"type\":\"exception\",\"reason\":\"java.lang.IllegalArgumentException: ElasticsearchParseException[Error parsing document in field [data]]; nested: TikaException[Unexpected RuntimeException from org.apache.tika.parser.ParserDecorator$2@7affdf61]; nested: IllegalStateException[Schemas (*.xsb) for CTTable can't be loaded - usually this happens when OSGI loading is used and the thread context classloader has no reference to the xmlbeans classes - use POIXMLTypeLoader.setClassLoader() to set the loader, e.g. with CTTable.class.getClassLoader()];\",\"caused_by\":{\"type\":\"illegal_argument_exception\",\"reason\":\"ElasticsearchParseException[Error parsing document in field [data]];

I didn't understand why this is happening. This error occurs mostly due to pptx files.

Is there any limitation wrt pptx files

**Comment by talevy** [comment]
@ujjwalGargFS often times these are third-party parsing problems with the Tika library this attachment processor is leveraging. We have upgraded our dependency on the POI library to 3.17 that shows some bug-fixes surrounding some of these powerpoint parsings. Would you mind trying to upgrade to Elasticsearch 6.3 to find out if the latest versions solve your problem?

If not, feel free to share the pptx that is causing the problem, and I can test out locally

**Comment by tballison** [comment]
We fixed a serious class loading issue in POI 4.0.0, which is now shipping with Tika 1.19.  See TIKA-2693.
@kiwiwings, does the class loading problem above jibe with your understanding of TIKA-2693?

**Comment by talevy** [comment]
@ujjwalGargFS have you tried upgrading? is this still an issue?

**Comment by yadygarovadt** [comment]
Hello here. Writing to this issue because I have the same problem. I am using ingest attachment to index some documents and the same problem appeared on .pptx (as it is mentioned earlier). Should i upgrade to newer Elasticsearch version? 

**Elasticsearch version:** 5.6.14
**Error logs:**
`{ServerError: 500
Type: exception
Reason: "java.lang.IllegalArgumentException: ElasticsearchParseException[Error parsing document in field [data]]; nested: TikaException[Unexpected RuntimeException from org.apache.tika.parser.ParserDecorator$2@5e6141e9]; nested: IllegalStateException[Schemas (.xsb) for CTTable can't be loaded - usually this happens when OSGI loading is used and the thread context classloader has no reference to the xmlbeans classes - use POIXMLTypeLoader.setClassLoader() to set the loader, e.g. with CTTable.class.getClassLoader()];"
CausedBy: "Type: illegal_argument_exception Reason: "ElasticsearchParseException[Error parsing document in field [data]]; nested: TikaException[Unexpected RuntimeException from org.apache.tika.parser.ParserDecorator$2@5e6141e9]; nested: IllegalStateException[Schemas (.xsb) for CTTable can't be loaded - usually this happens when OSGI loading is used and the thread context classloader has no reference to the xmlbeans classes - use POIXMLTypeLoader.setClassLoader() to set the loader, e.g. with CTTable.class.getClassLoader()];" CausedBy: "Type: parse_exception Reason: "Error parsing document in field [data]" CausedBy: "Type: tika_exception Reason: "Unexpected RuntimeException from org.apache.tika.parser.ParserDecorator$2@5e6141e9" CausedBy: "Type: illegal_state_exception Reason: "Schemas (*.xsb) for CTTable can't be loaded - usually this happens when OSGI loading is used and the thread context classloader has no reference to the xmlbeans classes - use POIXMLTypeLoader.setClassLoader() to set the loader, e.g. with CTTable.class.getClassLoader()"""""}`

**Comment by talevy** [comment]
@yadygarovadt would you be able to share the file that is causing this issue? It would be good to verify whether it is still happening in latest version of Elasticsearch with the upgraded libraries

**Comment by yadygarovadt** [comment]
@talevy Hello, I'm sorry I can't share the file that's causing this issue due to job issues, well, perhaps in public, but i could possibly share that troubled file PM only, and I can tell you that file size was less than 1 mb. We have a temporal solution to solve this issue, but not on ES side.
