### ISSUE TITLE
SQL: support queries across indices with different mappings

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#31837]
For ease of use, it should be possible to run SQL queries across multiple indices (which we support) with different mappings (which we do not).
This entails creating a virtual schema from merging the mapping and dealing with missing fields across the various indices.

The areas of investigation are dealing with the field source (especially for missing fields) and aggregations.

**Comment by costin** [comment]
Hi,
It took a bit more time (with holidays and all) but this issue has been finally been resolved. Available in the upcoming 6.5.x and 7.x

**Comment by bitkowitz** [comment]
Thank you. I’m looking forward to trying it.

**Comment by costin** [comment]
Cheers and thanks for your patience!

**Comment by happybin92** [comment]
hi @costin thank you for your solve this problem, but i also find some case can't do. Could you help me?
1.

**Comment by happybin92** [comment]
hi @costin  thank you for your solve this problem, but i also find some case can't do. Could you help me?
1. two index with different

**Comment by happybin92** [comment]
hi @costin  thank you for your solve this problem, but i also find some case can't do. I use es 6.8.1.
Could you help me?  
1. the same field in 2 index with different doc_values.
    doc_values is for Sorting, aggregations.
   

> PUT log-20190720, log-20190719
{
  "aliases": {"log":{}},
  "mappings": {
    "log":{
      "properties":
      {
        "age" : {
           "type": "long",
           "doc_values": true
        }
      }
    }
  }
}

> PUT log-20190721
{
  "aliases": {"log":{}},
  "mappings": {
    "log":{
      "properties":
      {
            "age" : {
           "type": "long",
           "doc_values": false
        }
      }
    }
  }
}

and use sql:
> SELECT * from log group by age

it will error with "Can't load fielddata on [age] because fielddata is unsupported on fields of type [long]. Use doc values instead."

I know it 's log-20190721 without doc_values. but the  log-20190720, log-20190719 is ok
So,  i think the better result is that, sql execute in that right indexes ( log-20190720, et), and ignore the wrong indexes.
