### ISSUE TITLE
Optimize `phrase_prefix` match query

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#31921]
We can leverage https://github.com/elastic/elasticsearch/pull/28290 to optimize `phrase_prefix` on `match` query. If the `index_prefix` option is set on the field we can query the last term using the `prefix` field, this should speed up the query significantly (a single term query) and increase the recall since all expansions would match.

**Comment by markharwood** [comment]
>this should speed up the query significantly (a single term query) 

That makes sense to me. The search for `"brown f*"` would be able to match all docs with `text._index_prefix` field with the term `f` rather than searching `text` field for `fab`, `fan` etc

>and increase the recall since all expansions would match.

This bit I don't get. [The phrase_prefix docs](https://www.elastic.co/guide/en/elasticsearch/reference/master/query-dsl-match-query-phrase-prefix.html) already include a warning that the `f*` expansions tried are not verified to be prefixes that exist as a phrase with the previous term e.g. may suggest the non-existant `brown fab` and `brown fan` etc rather than the `fox` in the existing phrase `brown fox`.

To solve that problem shouldn't this issue be about using the `index_phrases` enabled fields rather than the `index_prefix` field?

**Comment by jimczi** [comment]
> This bit I don't get. The phrase_prefix docs already include a warning that the f* expansions tried are not verified to be prefixes that exist as a phrase with the previous term e.g. may suggest the non-existant brown fab and brown fan etc rather than the fox in the existing phrase brown fox.

When prefixes are not indexed we extract the first 50 terms that match the prefix by default. With indexed prefixes we can match all documents that contain the prefix with a single term which ensures that all documents that should match will be taken into account. We could also use a mix of `index_phrases` and `index_prefixes` to make the query faster but we can do that in a follow up.

**Comment by markharwood** [comment]
Ah OK. so the phrase(/span/interval) query we run has a the full term (eg `brown`) and only the single prefix term (e.g. `f`) and both indexed terms share a common idea of position info that means we can test they occur next to each other.
