### ISSUE TITLE
min Agg with top Hits

### ISSUE THREAD

**Issue by sundarv85** [elastic/elasticsearch#32268]
It seems that min metric aggregation cannot have sub-aggregation (top hits). I already see such an issue #16537.

The reason behind this feature request is, I have an aggregation where I find the min time taken. However, from that entry we would like to find the top URL that contributed to this time taken, which is another field.

If top hits would work under min aggregation, it would be awesome to resolve this issue. Or is there already a way around this.

PS: We are using ES 5.6

**Comment by cbuescher** [comment]
@sundarv85 the Min Aggregation cannot have sub-aggregations because it is a Metrics Aggregations that returns a value, not a bucket of documents like the bucket aggregations. I don't quite understand what you are trying to achieve? You can probably find documents with a minimum time value by just using a `sort` in the search and then aggregate with top hits on that? I'd like to understand the use case better.

**Comment by sundarv85** [comment]
@cbuescher I'm trying to first group them into buckets based on users. Then within each user bucket, I would like to find the min time take and its corresponding URL (which are both fields). What I found is, I could sort it in top hits and then fetch the top hit. Therefore, I suppose, I don't need this sub aggregation within min aggregation.
