### ISSUE TITLE
does ESSQL support group by multies

### ISSUE THREAD

**Issue by wenfang6** [elastic/elasticsearch#32274]

**Comment by tvernum** [comment]
Could you please ask this question on our [discuss forum](https://discuss.elastic.co/c/elasticsearch) where we can provide better support. Those forums are designed to support the kinds of conversations that are necessary to answer these sorts of questions.

Elastic uses GitHub issues for tracking clearly identified bugs and feature requests. Since there is no specific bug identifed in your issue, I'm going to close this ticket, but I'm sure someone will be able to help you work through this issue on the [forums](https://discuss.elastic.co/c/elasticsearch) .

Thank you.
