### ISSUE TITLE
Composite aggregation is inconsistent

### ISSUE THREAD

**Issue by HonzaKral** [elastic/elasticsearch#32414]
When defining `sources` for `composite` aggregation it expects a list of objects where each object has a single key - the name of the source - and value - the actual aggregation. This is super unexpected pattern as in other places where the DSL has similar requirements it just accepts an object with multiple keys - names of the subaggregations (like `aggs` itself for example or a list of aggregations directly without a name if order is important (like filters agg with anonymous filters).

Additionally there is no protection against duplicate names of sources so a following example just uses the second aggregation, silently ignoring the first definition:

```
curl localhost:9200/_search -d '{
  "aggs": {
    "my": {
      "composite": {
        "size": 1,
        "sources": [
          {"test": {"terms": {"field": "files"}}},
          {"test": {"terms": {"field": "stats.lines"}}}
        ]
      }
    }
  }
}'
```

Could we perhaps do the same as with `filters` for consistency? Use keyed request if order does not matter (order can be either implicit by key or explicit by specifying `order` key at the top level) or a list of anonymous objects? If not, it would still be great to have protection against duplicate keys - the above example should raise an exception to alert the user they are doing something unsupported.

Thank you!

**Comment by jimczi** [comment]
> Use keyed request if order does not matter (order can be either implicit by key or explicit by specifying order key at the top level) or a list of anonymous objects?

The order always matters in the `composite` aggregation but we've decided to return a map for each bucket rather than a simple list of values because it is easier to read. Each value in the composite bucket has a name associated to it and the value can be retrieved from the returned map with a simple get.

> Could we perhaps do the same as with filters for consistency? Use keyed request if order does not matter (order can be either implicit by key or explicit by specifying order key at the top level) or a list of anonymous objects? If not, it would still be great to have protection against duplicate keys - the above example should raise an exception to alert the user they are doing something unsupported.

That would break the current response format which always return the bucket key as a map. 
The duplicate key in the source is a bug though, we should detect this discrepancy and throw an exception in this case. I'll work on a fix.
