### ISSUE TITLE
How should we backup the .security index

### ISSUE THREAD

**Issue by joshbressers** [elastic/elasticsearch#32562]
We receive requests on how to best backup the .security index which the only answer today is to backup with a user that has superuser privileges. This is less than ideal as giving a backup system this level of privilege can be dangerous.

However the .security index in general can be considered very sensitive

We should discuss possible options. Two that spring to mind:

- Do nothing, we don't solve this problem and tell users to use a superuser
- Have an API to backup certain aspects of .security - perhaps backup only roles, or roles and users but no passwords or tokens

**Comment by jakommo** [comment]
I'm proposing a third option, which is a dedicated .security backup role, that only allows a (full) backup of .security, but does not grant all the other superuser permissions.

**Comment by albertzaharovits** [comment]
To be precise, to create and restore snapshots, the user needs the `manage` cluster privilege. It is a rather broad privilege so it's not completely erroneous to refer to it as `superuser`. Reading the linked SDHEs, it looks like `superuser` is indeed required when doing the snapshot from curator which first lists the indices that it is suppose to snapshot.

Since the request is to lower the privilege for snapshot/restore I think it's important to note that because we don't authorize on the indices being restored, but on the restore action itself, any restore privilege is equivalent to the `manage_security`, when restoring includes the `.security` index, because a user can restore a snapshot that it had altered on it's own local cluster.

So, if the goal is to downgrade privileges for ordinary snapshots I think we could have a `manage_snapshot` privilege. However, it should not snapshot access tokens from the `.security` index. And I would also not allow it to restore anything?
The action of restoring should be higher privileged, especially if the `.security` index is involved (at least `manage_security`). I don't like @joshbressers solution of a separate API dealing with the snapshoting of the `.security` index specifically, but given the present authz architecture I think it's the easiest way.

Or, we could check indices permissions for read when snapshoting and indices permissions for write when restoring? I think that's the best way, but I think it's difficult to implement.

**Comment by albertzaharovits** [comment]
We had a meeting at EAH and we've put together a meta issue https://github.com/elastic/elasticsearch/issues/34454 with an action plan about the plan to implement this. That issue supersedes this one. Closing.
