### ISSUE TITLE
Allow index template replacing, not just merging

### ISSUE THREAD

**Issue by vbohata** [elastic/elasticsearch#32612]
For log management deployment there could be hundereds of templates loaded to elasticsearch - just for beats it is for each beat, for each version one template. Sometimes the template definitions for a lot of versions is the same. It would be great to be able to create template with match to "filebeat-6.2.*" and if needed add another one with "order: 2" matching "filebeat-6.2.3". The second template should replace (not merge with) the first template. The replace/merge decision could be controlled by some "template uuid". If two templates share the same uuid, the template with higher order will replace the other one.

**Comment by colings86** [comment]
We discussed this in FixItFriday and said that template inheritance is already very complex and something we need to re-think anyway because of the problems it causes especially with validating index templates. We are inclined not to add further complexity to template inheritance at this time but will bear this in mind for the outcome of https://github.com/elastic/elasticsearch/issues/21105
