### ISSUE TITLE
Allow the keystore to be password protected

### ISSUE THREAD

**Issue by joshbressers** [elastic/elasticsearch#32691]
Now that we have a keystore we need to add the ability to encrypt it with a secret. Ideally when a node starts up a secret must be passed in somehow.

Some questions we need to answer

- What does this mean for reloading the keystore
- How do we want to pass in the secret securely
- What other secret storage technologies should we support (like vault)
- What happens to node startup if the secret fails to unlock the keystore

**Comment by albertzaharovits** [comment]
I can answer the easy one:
> What does this mean for reloading the keystore

As it stands the reload-secure-store API has a request body param that is used to convey the password, or the vault token, for that matter, to some node which will then broadcast it to the full cluster, during reloading. The password/token is never stored, and it is not obfuscated at any step.

**Comment by jasontedor** [comment]
A few thoughts from a discussion in the @elastic/es-core-infra team meeting:

> What does this mean for reloading the keystore

We should require HTTPS to be able to specify a password in the reload settings API. How exactly we do this is open to discussion, but we think that we should remove the ability to specify a password on the current reload settings API, and add a new API that allows specifying a password, and this API will require HTTPS. The idea here is that we want to avoid plaintext transmission of passwords.

> How do we want to pass in the secret securely

With `systemd` there are built-in facilities for this that we can leverage, but that doesn't solve this for us on Sys V init, and the archive packages (e.g., on Windows). We can read from standard input or on an IPC socket (now that Windows is adding support for `AF_UNIX`), or via a named pipe. We lean towards avoiding environment variables.

> What other secret storage technologies should we support (like vault)

We see this question as completely orthogonal to adding password support to the keystore.

> What happens to node startup if the secret fails to unlock the keystore

We should fail the node.

**Comment by williamrandolph** [comment]
@rjernst, @jkakavas, and I met yesterday to discuss approaches to password prompts during app startup. Ryan advocated for an approach that delegates the complexities of password prompting to the startup scripts or environment configurations and limits the changes in application code to an absolute minimum. This approach is desirable because it sets us up for the use of a launcher tool, which happens to be something that Ryan has been working on for some time now. (The launcher tool will solve the problem of a user having to watch logs or ping the rest API to see if Elasticsearch has launched correctly when running in the background.)

In short, we're going to aim to use standard input as the bridge between startup scripts and the Elasticsearch app itself, and delegate the handling of FIFOs, passphrase files, environment variables, etc., to the startup scripts.

We have the ability to parameterize our startup scripts and configuration files by distribution type, e.g., a windows archive can have different java options than a lentos RPM. Ryan pointed out that this mechanism may be useful for taking different approaches to password prompting in the Docker and Systemd cases.

Finally, there are some complexities to Systemd password prompting: specifically, to the systemd-ask-password tool. The version of the tool that comes with centos7 has the restriction that system-wide password prompting is only available to privileged processes ( [man page](http://man.linuxtool.net/centos7/u3/man/1_systemd-ask-password.html) ). I've had Systemd success with an environment variable that passes the location of a passphrase file or FIFO (not the passphrase itself).

I'll post a PR with my work so far next week.

**Comment by williamrandolph** [comment]
This main work is close to finished, but there are three known tasks that need to go into the feature branch (currently #49268) before we will be ready to merge in the feature:

1. Documentation for providing passwords at startup. (#49338)
2. Handle the Docker case in keystore tests. (This work hasn't been done because the Docker packaging tests were developed in parallel to the work on this branch.) (#49469)
3. Fix the currently flaky expect-based tests, and get them working on Windows. This may involve using a different Java library to simulate an interactive terminal. (#49340)

**Comment by jasontedor** [comment]
The plan sounds good to me! Thank you for writing it down, and also including docs as part of it.
