### ISSUE TITLE
Commit containing @Seed annotation passed CI

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#32772]
Commit 27f7422426a1f94d190a309e140113602956a9af, part of https://github.com/elastic/elasticsearch/pull/32723/commits, passed CI, but included an accidentally-committed `@Seed` annotation in [test/framework/src/main/java/org/elasticsearch/test/InternalAggregationTestCase.java](https://github.com/elastic/elasticsearch/commit/27f7422426a1f94d190a309e140113602956a9af#diff-10b88e15ffce654cae4d9be787230bedR233). This is supposed to be forbidden:

https://github.com/elastic/elasticsearch/blob/27f7422426a1f94d190a309e140113602956a9af/buildSrc/src/main/resources/forbidden/es-test-signatures.txt#L18

Had this annotation been in the `:server` module it would have failed the build, but it seems that this wasn't checked here.

**Comment by rjernst** [comment]
I've spent quite a while investigating this and I'm a bit baffled. The fix is simple: adding es-test-signatures to forbiddenApisMain in test:framework. However, it doesn't actually work because forbidden apis is skipped in test:framework from some reason I cannot figure out:

```
> Task :test:framework:forbiddenApisMain SKIPPED
Skipping task ':test:framework:forbiddenApisMain' as task onlyIf is false.
```

I have tried various ways of overriding this, even in a `gradle.projectsEvaluated` block, but the task is always skipped. @atorok do you have any ideas?

**Comment by atorok** [comment]
@rjernst `task.enable` is implemented as an `onlyIf` on the task, thus the misleading log,
since the reason it's skipped is that `test/build.gradle` disables it. 
There's a contradiction in that build script, since it both configures and disabled the task.
Som configuration is likely incorrect as it errors out:
```
Caused by: java.lang.NullPointerException
	at de.thetaphi.forbiddenapis.Checker.parseSignaturesFile(Checker.java:501)
```

**Comment by rjernst** [comment]
Thanks @atorok! This makes sense now. I will figure out the NPE.
