### ISSUE TITLE
SQL: ORDER BY RAND() always returns values in the same order

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#32838]
As the title suggests, ORDER BY RAND() always returns results in the same order, no matter what seed is supplied.

```
POST /_xpack/sql?format=txt
{
    "query": "SELECT geoip.continent_name AS name FROM \"cyclops-sessions\" ORDER BY RAND(123) LIMIT 2"
}
```

ES `v6.3.1`

**Comment by Luegg** [comment]
I just run into this as well but I think this works according to the spec. Since the SEED is constant, you should always get the same result. @astefan WDYT? Can this be closed?

What would be handy though, is a version of `RANDOM()` that produces random results on every invocation (e.g. for every record in the above example).

**Comment by astefan** [comment]
`RAND(same_seed)` should always return the same value (which makes it deterministic by definition). Having a way to always return random numbers is a different matter. Maybe something that can be discussed further in https://github.com/elastic/elasticsearch/issues/34152.
