### ISSUE TITLE
Need feature like solr TermsComponent-

### ISSUE THREAD

**Issue by snigdharao123** [elastic/elasticsearch#32925]
I have an usecase where i need to match text in multiple fields and have response similar to terms component where the response includes matched fields and unique values.
For more information
https://wiki.apache.org/solr/TermsComponent

**Comment by spinscale** [comment]
please use our forum for usability questions like this. It is available at https://discuss.elastic.co/c/elasticsearch

You also might want to take a closer look at the existing suggesters or term vectors before and explain your use-case a bit more in detail in the forum, so that people can have a look whether an already existing feature you may help you with your concrete problem. Thanks a lot!
