### ISSUE TITLE
Configurable disk size

### ISSUE THREAD

**Issue by yanjunh** [elastic/elasticsearch#33068]
**Describe the feature**: Currently ES allows configuring number of processors. (https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-threadpool.html#processors) Can we also allow configuring the disk size so ES will only use the space configured?

**Comment by jasontedor** [comment]
I don't think we will add a feature like this since this is easily and correctly handled at the OS level where you can use partitioning and logical volumes to do the same. Importantly every OS that we support has a feature for this. This is distinguished from the processors setting wherein even if you use OS functionality for thread affinity, the JVM does not know that it is limited in the cores in the machine that it would be scheduled on, so we have to explicitly tell Elasticsearch to pretend that it only has a certain number of cores available to it. Additionally, not every OS has functionality for setting the thread affinity of a process (e.g., for macOS there is not a CLI tool like `taskset` while there is a thread affinity API; this does not help end-users).

**Comment by yanjunh** [comment]
Yes it's different from Processors override in the way that OS always reports the correct volume size. This feature is for easy collocating on RAID-0 volume without the need to manage partitions and mountable volumes.

**Comment by jasontedor** [comment]
We discussed this in our weekly team discussion meeting and we agree that we should not implement this functionality. We feel that the OS is the right place to manage this.
