### ISSUE TITLE
why does alias name point to more than one index ?

### ISSUE THREAD

**Issue by jain108shubhamtbt** [elastic/elasticsearch#33117]
Please help me .

**Comment by tvernum** [comment]
Could you please ask this question on our [discussion forum](https://discuss.elastic.co/c/elasticsearch) where we can provide better support. Those forums are designed to support the kinds of conversations that are necessary to understand and resolve your question.

Elastic uses GitHub issues for tracking clearly identified bugs and feature requests. Since there is no specific bug identifed in your issue, I'm going to close this ticket, but I'm sure someone will be able to help you work through this issue on the [forums](https://discuss.elastic.co/c/elasticsearch) .

Thank you.

**Comment by jain108shubhamtbt** [comment]
ok, 

thanks
