### ISSUE TITLE
Elasticsearch WebUI page display issue

### ISSUE THREAD

**Issue by kaushikbbr** [elastic/elasticsearch#33115]
Hi Team,

**Describe the feature**:
The cat indices API gives us the tabular form of all the indices present in elastic search very intuitively. But when the same is viewed on mobile or a tablet the lines get wrapped with respect to the screen.

It would be real nice and informative if we have a scroll bar rather and the lines un-wrapped.

Please kindly update if possible!

View on Laptop screen
![image](https://user-images.githubusercontent.com/38374696/44565373-67471200-a785-11e8-8e92-e36381b60cea.png)

View on a tablet sized screen
![image](https://user-images.githubusercontent.com/38374696/44565401-8e054880-a785-11e8-89e0-decca0b759ad.png)

View on a mobile sized screen
![image](https://user-images.githubusercontent.com/38374696/44565426-ae350780-a785-11e8-8aa2-2230d6236b2d.png)

**Elasticsearch version** (`bin/elasticsearch --version`): v6.3.2 (On cloud Instance)

**Description of the problem including expected versus actual behavior**:

The expected behavior is that one should be able to see the lines unwrapped. This helps analyzing in a very intuitive manner.

_Let me know if any further details required?_

Regards

Kaushik Vankayala

**Comment by tvernum** [comment]
Hi @kaushikbbr 

The `_cat/` APIs are designed to be used in command line tools like `curl` rather than through the browser, so they are just plain text and it is your browser that is deciding how to format the output (wrapping _vs_ scrolling), as their is not HTML involved.

I'll leave this issue open so that the team that looks after these APIs can comment, but I think it's unlikely that we'll be making any changes to this.

**Comment by jasontedor** [comment]
Heya, this is an unfortunate experience indeed. This is Chrome that is the culprit here though. Here's an explanation:
 - the cat APIs are not intended to be used from a browser, instead from the command line and with plain text tools; this is why they serve text/plain content type, and there is no HTML or styling involved
 - however, I understand the appeal of using these APIs from the browser, and I agree with you that this is an unfortunate experience for a user
 - that said though, this is Chrome behavior on text/plain content type
 - you can see examples such as this [one](https://stackoverflow.com/questions/5837556/how-to-disable-word-wrapping-in-plain-text-files-in-chrome/24213373) where others are trying to figure out how to get Chrome to disable this behavior
 - and Firefox has `plain_text.wrap_long_lines` for controlling this behavior 

So given the above: there is nothing that we are going to do here. I suggest if you find yourself commonly using these APIs from the browser to use Firefox where you have control over this. Might I suggest using Kibana as a front-end to your cluster though?
