### ISSUE TITLE
Don't use global ordinals on join-field when _id is guaranteed to be integer

### ISSUE THREAD

**Issue by ddorian** [elastic/elasticsearch#33145]
In many cases, the _id are guaranteed to be integer/long since they come from another db. In those cases, we can use a doc_values(long) to make the join_field() and not use global ordinals.

Makes sense ?

**Comment by albertzaharovits** [comment]
@ddorian Can you please elaborate on what exactly are you suggesting as an optimization?
I get it is something related to disabling global ordinals in the case of a join relation, but I cannot fathom exactly for what field to disable global ordinals for and in which case that is supposed to improve performance.

**Comment by ddorian** [comment]
@albertzaharovits in cases where the _id you're joining is a `number` since aggregations on `number` don't need global ordinals.

**Comment by ddorian** [comment]
From the docs
question parent:
```
PUT my_index/_doc/1?refresh
{
  "text": "This is a question",
  "my_join_field": "question" 
}
```
answer child:
```
PUT my_index/_doc/3?routing=1&refresh 
{
  "text": "This is an answer",
  "my_join_field": {
    "name": "answer", 
    "parent": "1" 
  }
}
```

We can set an option, that guarantees that all `_id` are `number`, and then don't use global-ordinals on the join field.

**Comment by jimczi** [comment]
That's an interesting idea but `global ordinals` are also used because they provide a dense mapping. 
For queries for instance we use a bitset to record the global ordinals of the parent that matches the query and then use this bitset to filter children. Without a dense mapping we'd need to use a `Set` to record the `Integer` (assuming that the ids are integers) and this would require a lot of memory if the query matches a lot of parents. The advantage of global ordinals is that they are shared so we don't need to use a `Set` or remaps integers to a dense mapping on a per query basis. If you want to avoid using global ordinals you can force merge your index to 1 segment. Indices with a single segment  use the segment ordinals (computed on flush) directly. Though force merging should only be used if you don't update documents so it is a good fit for time based indices (append-only case).

**Comment by ddorian** [comment]
Hmmm, this maybe can be fixed with a per-shard dictionary. 
Don't know how that works and it's cons.

Have no other idea for now.

**Comment by jimczi** [comment]
> Have no other idea for now.

I am closing this issue for now since global ordinals are a lightweight per-shard dictionary that work for all type of ids. Switching to different implementations based on the type of the ids would complicate the code and is not guaranteed to be faster.
