### ISSUE TITLE
Search Performance Improving In Concurrency Searcher?

### ISSUE THREAD

**Issue by luyuncheng** [elastic/elasticsearch#33159]
**Describe the feature**:
I Checked ES6.x and other version which before 6.3.2, Every query use just one thread to execute query in one shard. Every IndexSearcher do search function in one thread, and they have to search each sub reader in one loop, at same time,  every Collector doesn't concurrent use LeafReader.  I wonder why not use SearcherManager and Concurrent Collector?

**Comment by albertzaharovits** [comment]
@luyuncheng You seem to be in the know of Lucene datastructures and you are suggesting a concurrency improvement. Although I cannot help with an answer, I will label this issue in the hope it will garner more qualified attention.

In the mean time, may you please elaborate your question a bit:
>  I wonder why not use SearcherManager and Concurrent Collector?

Where use it? In place of what? Does this improvement sits in the Elasticsearch or the Lucene land?

**Comment by luyuncheng** [comment]
@albertzaharovits As a example in es6.3.2, and lucene7.3.1, when QueryPhase do the searcher.search(query, queryCollector) job, it jump to Lucene IndexSearcher's search function. this function is lower-level search API.  All the search operation only in one thread like Read Segment, Collect field etc. However, another search API with collectorManager it can slice LeafReader which is multi thread. is it  more efficient for search job? 
I think this improvement sits in the ES land.

**Comment by javanna** [comment]
hi @luyuncheng sorry it has taken a while to get back to you. If I understand correctly, you are referring to the fact that each segment is a searchable inverted index, yet Elasticsearch searches through each segments belonging to an index in a sequential manner. We will discuss your suggestion with the team and see whether this part can be improved.

**Comment by colings86** [comment]
@luyuncheng Elasticsearch provides parallelisation of reads on the request level. It is expected that a shard will be serving multiple requests concurrently and therefore the parallelisation can be achieved in processing multiple requests concurrently rather than trying to concentrate on parallelising an individual request. We have found that combining concurrent requests with parallel segment readers does not offer any performance benefits and actually can hurt performance because of the cost of context switching so to keep the model simple we prefer to concentrate on keeping each search request processed on a single thread but support processing multiple search requests concurrently. I hope this answers you question.

**Comment by luyuncheng** [comment]
@colings86   Thanks for answer it

**Comment by nitin2goyal** [comment]
@colings86 @jpountz Sorry for commenting on an old/closed thread. We have use case where we don't have much concurrent queries at any given time but we suffer from latencies due to sequential segment search (though we have enough compute to spare). So we end up having higher latencies and under utilised compute. So, I was thinking to make use of Lucene's concurrent searcher and wanted to understand what could be other caveats.

From what I understand, there would be 2 things that we would need to do -

1. Create a new search context per segment having it's own bigArrays object. This might result in more memory/GC ?

2. Reduce the segments results in collector manager reduce like Elasticsearch does in SearhPhaseController.

Even though I understand ES team doesn't want to move in that direction, I just wanted to check if I can live with a patch at my end without making it complex and I am not missing anything. 

It would help me a lot if you could review the above approach and may have been discussed internally earlier with some different/same approach?

**Comment by jpountz** [comment]
@nitin2goyal We might move in this direction one day, though it's right it's not a priority. I'm afraid it's more complex than what you suggested. I don't have all the details but I remember that @s1monw looked into what it would take to start searching shards concurrently and this raised a number of interesting problems.
