### ISSUE TITLE
Execution failed for task ':test:fixtures:krb5kdc-fixture:extractJar'

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#33201]
This one failed four times in the last ten days. Last two failures are: 

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos/2628/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos/2637/console

Looks like a test infra problem:

```
02:53:54 java.nio.file.NoSuchFileException: /var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-unix-compatibility/os/centos/test/fixtures/krb5kdc-fixture/build/distributions/krb5kdc-fixture-7.0.0-alpha1-SNAPSHOT.jar
02:53:54 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
02:53:54 :test:fixtures:krb5kdc-fixture:extractJar (Thread[Task worker for ':' Thread 6,5,main]) completed. Took 0.095 secs.
02:53:54 3917 actionable tasks: 2565 executed, 1352 up-to-date
02:53:54 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
02:53:54 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
02:53:54 	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
02:53:54 	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:145)
02:53:54 	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
02:53:54 	at java.base/java.nio.file.Files.readAttributes(Files.java:1755)
02:53:54 	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1220)
02:53:54 	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
02:53:54 	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:845)
02:53:54 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:245)
02:53:54 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:175)
02:53:54 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:146)
02:53:54 	at jdk.jartool/sun.tools.jar.Main.extract(Main.java:1377)
02:53:54 	at jdk.jartool/sun.tools.jar.Main.run(Main.java:396)
02:53:54 	at jdk.jartool/sun.tools.jar.Main.main(Main.java:1669)
```

**Comment by atorok** [comment]
Looking at the logs, `:test:fixtures:krb5kdc-fixture:jar` never ran, despite  the `extractJar` task having `dependsOn jarTask`. Indeed checking on the build machine, the Jar is not there, only the src and doc jars are.  I suspect this is a bug in Gradle around lazy task evaluation  introduced in 4.8 and publicized in 4.9. We recently updated to 4.10 which might have fixed it.

In general it's very time consuming to create reproductions for intermittent issues like this one, instead I will remove the failing tasks completely because:
   - there's no up to date checking on them - so it does needles work when running check on dev machines 
   - it does the extract in an external process, which takes more time
   - but most importantly, we have testkit now and that's a better place to assert that the build plugin does indeed add those files.

**Comment by nik9000** [comment]
This reproduces consistently for me on 6.x on my desktop. If you want access I can give it. But if you are removing the tasks you probably don't need it.

**Comment by javanna** [comment]
I have exactly the same on my box, whenever I build 6.x. I talked to Alpar about it yesterday. His PR should address it.
