### ISSUE TITLE
Elastic search 6.4.0 test case execution failed due to an exception.

### ISSUE THREAD

**Issue by chakravarthy392** [elastic/elasticsearch#33242]
**Elasticsearch version** (`bin/elasticsearch --version`): v6.4.0

**JVM version** (`java -version`): openjdk version "10.0.2-adoptopenjdk"

**OS version** (`uname -a` if on a Unix-like system): Linux ubuntu 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
Elastic search build is succesful but test case execution failed with an exception.

**Actual:** 
all test cases should pass
**Observed:**
```Found the 1 `test` tasks:
  :client:benchmark:test -> class org.gradle.api.tasks.testing.Test_Decorated
  BUILD FAILED```
Elastic search 6.3.x is getting built and TC are passing with the same steps mentioned below.

**Steps to reproduce**:
 1. Install and export JAVA (adopt open jdk 10 hotspot) from https://github.com/AdoptOpenJDK/openjdk10-nightly/releases/download/201808211500/OpenJDK10_x64_Linux_201808211500.tar.gz
2. cd /home/test
3. git clone https://github.com/elastic/elasticsearch
4. cd elasticsearch
5. git checkout v6.4.0
6. ./gradlew assemble 
7. ./gradlew test --continue -Dtests.haltonfailure=false -Dtests.es.node.mode=network

**Provide logs (if relevant)**:
Full log : [ES640Network_log.txt](https://github.com/elastic/elasticsearch/files/2332614/ES640Network_log.txt)

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This does not appear to be a bug. The reason I say this is because our build are green right now, so this failure is likely environmental.

Instead, this appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by chakravarthy392** [comment]
Hi @jasontedor , I am getting the same issue with [openJDK10-hotspot](https://adoptopenjdk.net/?variant=openjdk10&jvmVariant=hotspot) and [OracleJDK10](http://www.oracle.com/technetwork/java/javase/downloads/jdk10-downloads-4416644.html). May I know which variant of Java you have used!

**Comment by jasontedor** [comment]
There should be no problem with either of those. Would you open a topic on the forum?

**Comment by chakravarthy392** [comment]
Yes @jasontedor , I have opened an issue @ https://discuss.elastic.co/t/elastic-search-6-4-0-test-case-execution-failed-due-to-an-exception/146615

Seems it is not an issue with java/gradle version as mentioned in https://github.com/elastic/elasticsearch/issues/28601#issuecomment-365242949 , but the strange thing is I am getting the issue with v6.4.0 only whereas v6.3.2 TCs are getting executed on the same VM with same settings.
