### ISSUE TITLE
Allow ILM's Shrink Action to progress successfully on indices with 1 shard

### ISSUE THREAD

**Issue by bmcconaghy** [elastic/elasticsearch#33275]
When a user specifies the shrink action and the index it is supposed to shrink already has only 1 shard, this error crops up:

        "failed_step": "shrink",
        "phase": "warm",
        "action_time": "1535643967009",
        "rollover_alias": "thing-alias",
        "phase_time": "1535643367314",
        "step_info": "{\"type\":\"illegal_argument_exception\",\"reason\":\"can't shrink an index with only one shard\"}",

ILM should just noop this (or shrink should).

**Comment by talevy** [comment]
I do not like the idea of a noop because then the semantics of shrink would not be the same. The shrink should only succeed if it successfully made a new shrunken index. That would mean allowing shrink to operate on an index with one shard, and simply copy without reducing the number of shards (since it cannot).
