### ISSUE TITLE
De-counting statistics are biased

### ISSUE THREAD

**Issue by huangjava** [elastic/elasticsearch#33293]
Other ways to solve the problem of distinct-statistical accuracy？

**Comment by astefan** [comment]
Hi @huangjava,

Thanks very much for your interest in Elasticsearch.
This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. Also, when you post your question there, do please provide more details because as it is now, is not very clear what you are asking.

Given the above, I hope you don't mind if I go ahead and close this for now.
