### ISSUE TITLE
Make the JAR hell check optional

### ISSUE THREAD

**Issue by jmnarloch** [elastic/elasticsearch#33341]
**Describe the feature**: I wish to be able to disable jar hell check completely. Currently this is a to much nuclear option to have it work in every possible client developer environment. The problem that I am facing is that I am not able to make the tests running because of Mockito dependencies. The problem is that I don't own all of my 3-rd party dependencies and if any of the packages either decides to repackage the same classes I am stuck and not able to proceed. The alternative that I was considered was pretty much forking the entire ESTestCase code together with bootstrap package, but because of the package level visibility it pretty much means need to fork over almost everything.

The only thing that I would expect is support for env variable `es.jarhell.check=false` or similar.

**Elasticsearch version** (`bin/elasticsearch --version`): 6.3.0

**Plugins installed**: [NA]

**JVM version** (`java -version`): java 10.0.2 2018-07-17

**OS version** (`uname -a` if on a Unix-like system): Darwin 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 21 20:07:40 PDT 2018; root:xnu-3248.73.11~1/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**: Jar hell check is making the integration test unecessary hard to onboard. 

**Steps to reproduce**: Importing any dependency that uses jarjar to package either mockito, guava or any other 3rd library causing the jar hell check to report errors.

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by jasontedor** [comment]
Sorry, I understand it can be painful, but we are simply not going to relax this at all. We have lived with the JAR hell checks for many years now and despite the pain that they can cause, we firmly believe it's best for our project that they be mandatory.

Also, depending on the kind of test that you're running, you might be best served by running a standalone integration test (i.e., one that starts a real instance of Elasticsearch and you fire requests at it) instead of an `ESSingleNodeTestCase` or an `ESIntegTestCase`. With this, since you're starting a real node, you would completely avoid the JAR hell issue test side since you would not have to use `ESTestCase` and it's class hierarchy which brings along the conflicting dependencies.

**Comment by jmnarloch** [comment]
My other question is, did you manage to run the tests with coverage, I am pretty sure that this isn't working as well, as the same instrumented classes are going to be on the classpath.

**Comment by jmnarloch** [comment]
So I don't want to start unnecessary heated discussion, this is not my point. But the original requests it to make the client opt out of it, not disable it by default.

**Comment by jmnarloch** [comment]
```
Also, depending on the kind of test that you're running, you might be best served by running a standalone integration test (i.e., one that starts a real instance of Elasticsearch and you fire requests at it) instead of an ESSingleNodeTestCase or an ESIntegTestCase. With this, since you're starting a real node, you would completely avoid the JAR hell issue test side since you would not have to use ESTestCase and it's class hierarchy which brings along the conflicting dependencies.
```

This is exactly what I am doing, my class inherits from ESIntegTestCase, which by itself inherits from  ESTestCase. ESTestCase is responsible for kicking out the Bootstrap which will eventually check the classpath.

**Comment by atorok** [comment]
@jmnarloch I think what @jasontedor means is to run elasticsearch by executing the jar, or using the docker images ( I have used the Gradle docker compose plugin to start elasticsearch before running the tests ). We don't know your exact  scenario  so this may or may not work for you.

**Comment by atorok** [comment]
@jasontedor as a side note, the jar hell check from  `ESIntegTestCase` may be redundant as we have a Gradle task that does that for the test classpath before running the test, we may actually be able to save some time during testing by not doing it (I did not check how significant). Of course this would be a breaking change since some users of `ESIntegTestCase` will expect the jar hell check to happen. On the other hand, unlike the test check in the test case, the Gradle task, like any other, can be disabled.

**Comment by jasontedor** [comment]
> This is exactly what I am doing, my class inherits from ESIntegTestCase, which by itself inherits from ESTestCase. ESTestCase is responsible for kicking out the Bootstrap which will eventually check the classpath.

As @atorok mentions, this is exactly what I am suggesting that you do not do. Within Elasticsearch, we are disfavoring the use `ESSingleNodeTestCase` and `ESIntegTestCase`. They are really for when we need low-level control of components within Elasticsearch. For all other test use-cases, we prefer to use standalone integration tests where we startup a real cluster of Elasticsearch and use that for testing.
