### ISSUE TITLE
SQL: functions improvements

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#33477]
- order alphabetically functions in FunctionRegistry
- missing aliases, ie CHARACTER_LENGTH
- missing function OCTET_LENGTH
- inconsistencies between functions (0-based vs. 1-based)

**Comment by costin** [comment]
> order alphabetically functions in FunctionRegistry
The order should be applied per batch / group of functions not across all functions. Further more in some cases we add aliases (`DAYOFMONTH`, `DAY_OF_MONTH`) which don't seem to be ordered correctly.
Instead of preserving the order by hand (which increases readability) the `FunctionRegistry` could be enhanced to allow registration of functions per ordered batch (aka `TreeSet`) into the list.
This makes the declaration more forgiving and the outcome correct.

**Comment by astefan** [comment]
Documentation for the `Random()` function needs to be added.

**Comment by astefan** [comment]
master: https://github.com/elastic/elasticsearch/commit/d7a94fb6aa1f85709a2a03ca30099fa8fbb04395
6.x: https://github.com/elastic/elasticsearch/commit/0238151650a0a741b780b9b5f6b7d58736d30bbb
