### ISSUE TITLE
Can the java client join a DB transaction?

### ISSUE THREAD

**Issue by AI-PaaS** [elastic/elasticsearch#33491]
**Describe the feature**:

I have searched the issues list but found nothing about my scenario. I use ES as a nosql db, so the data must be strictly same as data in relational database. i use java client and tcp mode to submit the data ES server,  after that save the data in the oracle, all this code in a same method with spring transaction.  Can this method guarantee data consistency?

BTW, i know the kafka has provide the send transaction with db data, does ES has a same plan?

Thx.

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by tvernum** [comment]
Could you please ask this question on our [discuss forum](https://discuss.elastic.co/c/elasticsearch) where we can provide better support. Those forums are designed to support Q&A style conversations such as the question you have raised.

Elastic uses GitHub issues for tracking clearly identified bugs and feature requests. Since there is no specific bug identifed in your issue, I'm going to close this ticket, but I'm sure someone will be able to help you find some answers on the [forums](https://discuss.elastic.co/c/elasticsearch) .

Thank you.
