### ISSUE TITLE
Painless hourOfDay not accounting for timezone/offset of data

### ISSUE THREAD

**Issue by veqryn** [elastic/elasticsearch#33543]
**Elasticsearch version**:
6.2 (AWS ElasticSearch Service)

**Description of the problem including expected versus actual behavior**:
I am trying to get the hour of the day of a date field.
The data sent to the date field includes timezone/offset information, I would like this to be accounted for. (Example: The hour of the day of `2018-06-29T19:31:30-03:00` would be `19`)
I would like to use painless, as all other languages are turned off.

**Steps to reproduce**:
The date-time information I am putting into the `lts` date field:
```
2018-06-29T02:15:01+02:00
2018-06-29T08:15:01+08:00
2018-06-29T19:31:30-03:00
```

The query I am running:
```json
{
  "size": 0,
  "aggs": {
    "time_buckets": {
      "terms": {
        "field": "lts",
        "size": 24,
        "script": {
          "lang": "painless",
          "source": "doc.lts.value.hourOfDay"
        },
        "order": {
          "_term": "asc"
        }
      }
    }
  }
}
```

The results I am getting:
0 hour has 2 doc count
22 hour has 1 doc count

The results I am expecting:
2 hour has 1 doc count
8 hour has 1 doc count
19 hour has 1 doc count

I consider this a bug, but if this is not a bug then please let me know how I am expected to get what I want using painless?

**Comment by rjernst** [comment]
Thanks very much for your interest in Elasticsearch.

This does not appear to be a bug. All dates are stored as epoch millis in UTC.

Instead, this appears to be a user question, and we'd like to direct these kinds of things to the forums. If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by veqryn** [comment]
@rjernst if this is not a bug, then I would like to make this a feature request that the next version of ElasticSearch have a date datatype that includes location information in it.
For space reasons it makes sense to keep a timestamp data type (the current date type) that is just a long integer normalized to UTC time, and then have a second data type that is location aware.

**Comment by rjernst** [comment]
@veqryn This would be a significant change to the date field type, and require a "sidecar" field (to keep the timezone info). This is better done client side.

**Comment by veqryn** [comment]
I mean, you should have two different data types, just like how `integer` and `long` are different data types.
You would have `date` (the current, UTC normalized timestamp in epoch milliseconds), and also `zoned-date-time` (it could be milliseconds or nanoseconds since epoch, along with the location/timezone information, similar to how golang represents its timestamps).

**Comment by rjernst** [comment]
It's not about the data type in Elasticsearch. This is about how it is stored to allow searching in Lucene. Date fields are currently numeric fields (long values) and the codec in Lucene for long fields allows several optimizations over just using a binary term (eg range queries). In order to store the timezone along with a date, we would need a first class field type in Lucene which could still use the numeric structure, but store this extra information per document, within a single field. It would not be trivial.

It is certainly possible, but since it is trivial to store this information by a user in a separate field, and this does not appear to be a common need (this is the first I have seen anyone asking for it), I think our time is better spent elsewhere in the system. This is all open source, though, and if you find this feature to be important, you could start a discussion and work in Lucene.
