### ISSUE TITLE
Configurable option to improve multi index msearch requests

### ISSUE THREAD

**Issue by JacobBrandt** [elastic/elasticsearch#33586]
**Describe the feature**:
Add a configurable option that when enabled would remove portions of the request from the query context and/or filter context that doesn't exist in the index before sending it along to Apache.

Some back story to this can be found in this ticket https://github.com/elastic/kibana/issues/14081.

Basically, when you have a cluster that contains multiple indices and you want to do analysis across all of them it's better for the search requests of each index to only contain fields of that index.  This is not a trivial thing to accomplish with the multitude of lucene query syntax out there if you are trying to roll your own lucene parser.  However, Apache provides a QueryParser in java that is designed for this kind of parsing.  So with this option enabled, the server would use the QueryParser to determine which clauses are applicable to the index and remove the ones that are not.

**Comment by javanna** [comment]
heya @Bargs I have looked into this issue and read the other kibana issue that it originated from. We have discussed it with other folks in the search team and we would like to understand more about the usecase. Removing clauses from a query makes it hard to understand the returned result, could you elaborate on this functionality in kibana and what we may be able to do to help out?

**Comment by Bargs** [comment]
Sorry for the slow response.

This feature is mostly useful for dashboards in Kibana. Let's say you have two panels on a kibana dashboard, each targeting a different index with completely different fields. By default, if you create a filter on a field by clicking one of those visualizations, the data in the other visualization will go blank because no documents contain the field from the other index. This behavior is undesirable in some scenarios, where the user would only like a filter to apply to a visualization if its underlying index actually contains the field the filter is targeting.

In Kibana we have a setting to address this called `ignoreFilterIfFieldNotInIndex`. This works for simple things like `match` queries where Kibana can easily discern which field is being targeted. We can't do it for the `query_string` query though because we do not parse the Lucene query. So @JacobBrandt 's proposal here is to add a similar functionality to ES, since ES can much more easily discern the target field for every query type.

**Comment by javanna** [comment]
Kibana evolved a lot over time, and I believe loads now dashboards differently, which makes me think that this feature request can be closed. Please feel free to comment or reopen if you think otherwise.
