### ISSUE TITLE
When 'discovery.type' is set to 'single-node', default value of 'number_of_replicas' should be 0

### ISSUE THREAD

**Issue by fbaligand** [elastic/elasticsearch#33739]
Currently, default value of 'number_of_replicas' is 1, whatever cluster settings.

It would be great that default value of 'number_of_replicas' is 0, when 'discovery.type' is set to 'single-node'.

Because when we have a "one-node" cluster, it is impossible to have a replica.
And it avoids to have a "yellow" cluster state on a "one-node" cluster.
Finally, for people starting with Elasticsearch (probably with one node), it avoids to have to do tuning (define number_of_replicas) to have a "green" cluster state.

**Comment by dadoonet** [comment]
Hey Fabien.

May be have a look at index.auto_expand_replicas setting. You can add it to your index templates.

See https://www.elastic.co/guide/en/elasticsearch/reference/6.4/index-modules.html

**Comment by fbaligand** [comment]
Well, that is the point. 
I wish to not have to define a template to avoid yellow cluster state. 
This is the first thing that I do each time I start a elasticsearch cluster. And the first thing I explain to Dev and Ops that start with Elasticsearch. 

It would be great, at least, to do only elasticsearch.yml config or CLI config.

**Comment by jasontedor** [comment]
I agree with @DaveCTurner for exactly the reasons he gives.

I will add a couple more minor points:
 - We generally shy away from settings defaults that depend on other settings except when they truly make sense (e.g., sizes of thread pools make sense based on the `processors` setting because that’s *exactly* the point of the `processors` setting). We don’t like dependent default settings because they make the system hard to reason about for us, and our users. The point of the `discovery.type` `single-node` value is for the node to declare: I am not going to form a cluster while I am running, and that is it. As @DaveCTurner mentions, you can always form a cluster later and now you’re hurting because one time you made an index while on `single-node`. That’s trappy.
 - Building on another point that @DaveCTurner made, we do have a lot of users that start with a single node and as they expand their uses of Elasticsearch, they come to add more nodes. When they add that second node, we want those replicas already defined so their redundancy grows automatically without effort on their part. It’s part of our goal to be a friendly distributed system. 

Further, this has been proposed and considered it before and we came to the same conclusion. I’m on mobile so I am having trouble locating the original discussion. Either way, I don’t think we will be changing this.

**Comment by fbaligand** [comment]
OK, thanks for your explanations.
