### ISSUE TITLE
Add 'elasticsearch.reference.yml' file into elasticsearch distribution package

### ISSUE THREAD

**Issue by fbaligand** [elastic/elasticsearch#33741]
Currently, the packaged `elasticsearch.yml` file is quite light. It contains few possible settings.
And in documentation, there is no page referencing all possible settings in `elasticsearch.yml`.

And so, there is currently no way to see all available settings in one location.
And sometimes, it is frustrating and painful.

That's why it would be great to add 'elasticsearch.reference.yml' file into Elasticsearch distribution, with all possible settings (like FileBeats does).
Or else add a documentation page with all possible settings ([like Logstash does](https://www.elastic.co/guide/en/logstash/current/logstash-settings-file.html)).

**Comment by jasontedor** [comment]
We have considered similar requests to this before (e.g., a request for a single documentation page that includes a list of all settings that Elasticsearch supports). While we understand the appeal of this, and how for some users like yourself it might be "frustrating and painful" to not have it, ultimately we do think this is not friendly to most of our users and would create more problems than it solves.

Elasticsearch currently has hundreds of settings (something on the order of 300, I am not sure, and it's continuing to grow as we add more functionality). The vast majority of these *never* need be touched by a user (if they do, we think it's a bug) and then some users need settings for one module (e.g., Security) while another set needs another (e.g., Watcher) and so on. For the really common settings, we aim to pick good defaults. 

Listing all settings in a single page, or in a reference elasticsearch.yml only encourages fiddling with settings. We also do not think that is the right way to consume settings. That is, scanning a list of hundreds of settings and their default values doesn't really help users solve their problems. Instead, we want to focus on high-quality settings documentation and feedback in the software so that when a user has a problem (e.g., "how do I increase the size of a thread pool") they can either find these by search and find the settings page for the relevant module (e.g., documentation for machine learning) or the software tells them "what you are using is deprecated, set this setting now to start using the non-deprecated behavior").

**Comment by jasontedor** [comment]
Relates #11504, relates #26251

**Comment by fbaligand** [comment]
OK, thanks for the explanation.

**Comment by jasontedor** [comment]
> Elasticsearch currently has hundreds of settings (something on the order of 300, I am not sure, and it's continuing to grow as we add more functionality).

I looked into this. For the 6.4.0 open source distribution (so excluding X-Pack features), there are 483 settings registered at startup. For the 6.4.0 default distribution (so including X-Pack features), there are 1346 settings registered at startup.

**Comment by fbaligand** [comment]
For people eventually interested by getting `elasticsearch.yml` settings full list, here's the REST command to get it (in Kibana for instance) : 
`GET _cluster/settings?include_defaults&format=yaml`
