### ISSUE TITLE
elasticsearch6.3.1增加x-pack，maven增加x-pack-transport依赖，但是有一个包下载不下来，请教下各位大佬

### ISSUE THREAD

**Issue by liufan1993** [elastic/elasticsearch#33883]
我的elasticsearch版本：6.3.1，
maven依赖：
<dependency>
    <groupId>org.elasticsearch.client</groupId>
    <artifactId>x-pack-transport</artifactId>
    <version>6.0.0-beta2</version>
</dependency>
其他的包都可以下载下来，只有tribe-6.0.0-beta2.jar下载有问题，如图
![image](https://user-images.githubusercontent.com/24200096/45801332-35728e00-bce6-11e8-8109-471742dc6820.png)

排除以下原因：1、网络问题，我的网进外网是没有问题的
                          2、已经增加了es的maven库，如下
         
        <repository>
            <id>elasticsearch-releases</id>
            <url>https://artifacts.elastic.co/maven</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>

**Comment by tvernum** [comment]
You should not be depending on 6.0.0-beta2
That was a beta release, and it shipped with [incorrect dependencies](https://github.com/elastic/elasticsearch/issues/26867).
Please update your pom file to use a GA release of X-Pack.

We strongly recommend that you use the transport client release that corresponds with the version of Elasticsearch you are running (6.3.1)
Note: The maven artifacts for 6.3.x had some missing dependencies (see https://github.com/elastic/elasticsearch/issues/31946) that you will need to add explicitly.

If you have any further questions  please ask on our [discuss forum](https://discuss.elastic.co/c/elasticsearch) (or in [chinese](https://discuss.elastic.co/c/in-your-native-tongue/chinese)) where we can provide better support. 
Elastic uses GitHub issues for tracking clearly identified bugs and feature requests. Since the problem to which you refer has been resolved in more recent versions of Elasticsearch, there is nothing for us to track, and I will close this ticket.

Thank you.
