### ISSUE TITLE
Get rollup jobs returns an empty array when you ask for a missing one

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#33919]
If you do something like
```
curl localhost:9200/_xpack/rollup/job/missing
```

Then the response is just
```
{"jobs":[]}
```

Which doesn't seem right.

**Comment by ronborneo** [comment]
Hi, may I work on this?

**Comment by nik9000** [comment]
@polyfractal, could you confirm that it ought to 404? I think it should but
I'd like a second opinion before I say "yes" to about folks working on it.

**Comment by nik9000** [comment]
@ronborneo I've conferred with some other folks to make sure I'm not crazy and they agree with me.

One point: we'd like the API to still return an HTTP 200 when you do `curl localhost:9200/_xpack/rollup/job/_all` and there aren't any jobs but 404 in all other cases. This is what we do in a few other places. I'm not sure it is really the right thing from an REST standpoint, but if it is wrong then we're at least consistently wrong.

**Comment by wchaparro** [comment]
With the 8.7 release of Elasticsearch, we have made a [new downsampling capability](https://www.elastic.co/guide/en/elasticsearch/reference/current/downsampling.html) associated with the new [time series datastreams](https://www.elastic.co/guide/en/elasticsearch/reference/current/tsds.html) functionality generally available (GA). This capability was in tech preview in ILM since 8.5.  Downsampling provides a method to reduce the footprint of your time series data by storing it at reduced granularity. The downsampling process rolls up documents within a fixed time interval into a single summary document. Each summary document includes statistical representations of the original data: the min, max, sum, value_count, and average for each metric. Data stream time series dimensions are stored unchanged. 

Downsampling is superior to rollup because:

- Downsampled indices are searched through the _search API
- It is possible to query multiple downsampled indices together with raw data indices
- The pre-aggregation is based on the metrics and time series definitions in the index mapping so very little configuration is required (i.e. much easier to add new time serieses)
- Downsampling is managed as an action in ILM
- It is possible to downsample a downsampled index, and reduce granularity as the index ages
- The performance of the pre-aggregation process is superior in downsampling, as it builds on the time_series index mode infrastructure

Because of the introduction of this new capability, we are deprecating the rollups functionality, which never left the Tech Preview/Experimental status, in favor of downsampling and thus we are closing this issue. We encourage you to migrate your solution to downsampling and take advantage of the new TSDB functionality.
