### ISSUE TITLE
[Rollup] Better create job API error message when index pattern captures rollup index

### ISSUE THREAD

**Issue by cjcenizal** [elastic/elasticsearch#33960]
The current message is `[x_content_parse_exception] Failed to build [xpack/rollup/jobconfig] after last required field arrived`. If this error specified that the index pattern captures the rollup index, then this will be more helpful for the user.

**Comment by anshul27jain** [comment]
I am also facing same issue. Any suggestions for Rolling up indices?

**Comment by cjcenizal** [comment]
> Any suggestions for Rolling up indices?

Would you mind explaining what you're trying to do, and what the problem is?

**Comment by cjcenizal** [comment]
@anshul27jain Actually, the Elasticsearch forum would be a better place to ask questions about solutions and workarounds (https://discuss.elastic.co/c/elasticsearch). We try to reserve discussion on GitHub for features, bug fixes, and technical/product decisions.

**Comment by lizozom** [comment]
Just ran into this issue myself. +1

**Comment by pulberg** [comment]
Same issue here, I added `rollup-` to the names, but this really should be fixed in the UI

**Comment by wchaparro** [comment]
With the 8.7 release of Elasticsearch, we have made a [new downsampling capability](https://www.elastic.co/guide/en/elasticsearch/reference/current/downsampling.html) associated with the new [time series datastreams](https://www.elastic.co/guide/en/elasticsearch/reference/current/tsds.html) functionality generally available (GA). This capability was in tech preview in ILM since 8.5.  Downsampling provides a method to reduce the footprint of your time series data by storing it at reduced granularity. The downsampling process rolls up documents within a fixed time interval into a single summary document. Each summary document includes statistical representations of the original data: the min, max, sum, value_count, and average for each metric. Data stream time series dimensions are stored unchanged. 

Downsampling is superior to rollup because:

- Downsampled indices are searched through the _search API
- It is possible to query multiple downsampled indices together with raw data indices
- The pre-aggregation is based on the metrics and time series definitions in the index mapping so very little configuration is required (i.e. much easier to add new time serieses)
- Downsampling is managed as an action in ILM
- It is possible to downsample a downsampled index, and reduce granularity as the index ages
- The performance of the pre-aggregation process is superior in downsampling, as it builds on the time_series index mode infrastructure

Because of the introduction of this new capability, we are deprecating the rollups functionality, which never left the Tech Preview/Experimental status, in favor of downsampling and thus we are closing this issue. We encourage you to migrate your solution to downsampling and take advantage of the new TSDB functionality.
