### ISSUE TITLE
6.4.0: very long startup without any log at all.

### ISSUE THREAD

**Issue by soulne4ny** [elastic/elasticsearch#33970]
**Elasticsearch version**:
Version: 6.4.0, Build: oss/tar/595516e/2018-08-17T23:18:47.308994Z, JVM: 1.8.0_171

**Plugins installed**:
none

**JVM version**:
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (IcedTea 3.8.0) (Alpine 8.171.11-r0)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

**OS version**
Alpine 3.8.0 inside docker 17.05.0-ce at
Linux 2cdfc9017dae 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 Linux

**Description of the problem including expected versus actual behavior**:
It took ~1h20m since start before `INFO o.e.n.Node: initializing ...` appeared in log. It was eating 102% cpu (1 core) all the time.

I would expect `initializing...` to appear right after start, followed by smth like `checking storage...`

**Comment by danielmitterdorfer** [comment]
Thanks very much for your interest in Elasticsearch.

Elasticsearch is running on top of the Java virtual machine (JVM) and this time delay is caused by the startup routine of the JVM itself and on which Elasticsearch has no influence. Hence we can not log anything because at that point Elastisearch has not even started yet. 

Due to `-XX:+AlwaysPretouch` the JVM will ensure that all memory pages are actually reserved by the operating system and the fact that you mention that one CPU was begged during this period of time is another hint (pretouching happens single-threaded in the JVM). This can be slow for example when memory is fragmented and the operating system needs to free up chunks of memory (see e.g. https://github.com/elastic/elasticsearch/issues/28650#issuecomment-365629315 for hints how you diagnose this yourself). 

However, I advise against removing this flag as this can negatively impact runtime behavior because the operating system might need to do this costly operation not on Elasticsearch startup but rather while the system is running.
