### ISSUE TITLE
Docs: percolate refers to multiple types per index

### ISSUE THREAD

**Issue by jaddison** [elastic/elasticsearch#34056]
On https://www.elastic.co/guide/en/elasticsearch/reference/current/percolator.html: 

> Fields referred in a percolator query may exist in any type of the index containing the percolator field type.

Given that multiple types per index is not an option anymore, should this text be adjusted?

**Comment by jpountz** [comment]
Absolutely, thanks for catching this.

**Comment by jaddison** [comment]
This also seems related to multiple types (how else could you have multiple fields in the same index?):
> The ignore_above setting is allowed to have different settings for fields of the same name in the same index.

from https://www.elastic.co/guide/en/elasticsearch/reference/6.4/ignore-above.html

**Comment by psylone** [comment]
Sorry, if this is not fully relevant to this topic, but on the same documentation page: https://www.elastic.co/guide/en/elasticsearch/reference/current/percolator.html there's example where a **single index** is using both **for documents and percolate queries**:

```
PUT my_index
{
    "mappings": {
        "_doc": {
            "properties": {
                "query": {
                    "type": "percolator"
                },
                "field": {
                    "type": "text"
                }
            }
        }
    }
}
```

Since `percolator` mapping type was introduced, I'm curious about is it just an example or some kind of _best practices_ to use a single index?

We had a little discussion here: https://discuss.elastic.co/t/how-to-store-percolate-queries-and-documents/154438

**Comment by jtibshirani** [comment]
@psylone I updated the percolator documentation as part of a larger clean-up around types in our docs (#34662). I'm sorry this caused confusion! I'm now tracking down our recommendation around percolator best practices and will loop back + try to clarify those docs.

**Comment by psylone** [comment]
@jtibshirani thanks!

**Comment by jtibshirani** [comment]
I've fixed the outdated documentation that assumes multiple types, and opened a PR clarifying the recommendation around percolator + multiple indices. I plan to close this out after the last PR merges.
