### ISSUE TITLE
Fuzzy Search not returning exact match

### ISSUE THREAD

**Issue by jaksmid** [elastic/elasticsearch#34070]
Bug report: fuzzy search returning no results for exact match

Version:
vanilla `docker.elastic.co/elasticsearch/elasticsearch:6.4.1`
ports `9200:9200`, environment `discovery.type=single-node
`
running on Docker Mac

**Description of the problem including expected versus actual behavior**:
Fuzzy search does not return exact match. However, it does return results on substring match.

Put sample data to elastic: 
```
POST http://localhost:9200/test/user/0
{
    "user" : "Hello World",
    "role" : "trying out Elasticsearch"
}
```

Query:
```
POST http://localhost:9200/test/_search
{
    "query": {
        "fuzzy" : {
            "user" : {
                "value": "Hello World"
            }
        }
    }
}
```
Return no results. However, the searched values should exactly match the only value stored in the DB.

The query without `Hello` returns the result.
```
{
    "query": {
        "fuzzy" : {
            "user" : {
                "value": "World"
            }
        }
    }
}
```

**Comment by jimczi** [comment]
`fuzzy` queries are considered as [term level](https://www.elastic.co/guide/en/elasticsearch/reference/current/term-level-queries.html) query. This means that the string is not analyzed when the query is built. With dynamic mapping a field that contains a string is mapped into a `text` field with a `standard` analyzer which will splits `Hello World` in two tokens `hello` and `world`. Since `fuzzy` query do not use analyzers, the query `Hello World`  will try to match any term in the index that is similar. However you field only contains `hello` and `world` as separate tokens in the index which is why your example does not match any document.
You can use a `match` query and sets the [fuzziness](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query.html#query-dsl-match-query-fuzziness) to force the analysis of the query string. Otherwise if you want to apply fuzziness to the entire content of a field you can use a `keyword` field which will not split the input into multiple tokens.
