### ISSUE TITLE
Extend named queries to provide token matched

### ISSUE THREAD

**Issue by v00d00c0de** [elastic/elasticsearch#34214]
**Describe the feature**:
Given a bool query containing number of **named** sub-queries, I want to be able to know **for each token** matched in the resulting document, the name of the query that matched it.
Preferably modify the "matched_queries" section to be a list of mappings <QUERY_NAME> -> <TOKEN_FOUND>.

**Comment by romseygeek** [comment]
This is something that can be done with lucene Matches, and we would indeed like to do this.  There are a number of open questions around the API and exactly how the implementation should be done, which we are actively discussing.

**Comment by v00d00c0de** [comment]
The feature should also support multi-fields.
Example use case: a multi-field where each sub-field is analyzed differently.
```
{
	"query": {
		"bool": {
			"should": [{
					"match": {
						"field.standard": {
							"query": "query",
							"_name": "standard"
						}
					},
					"match": {
						"field.phonetic": {
							"query": "query",
							"_name": "phonetic"
						}
					}
				}
			]
		}
	}
}
```

**Comment by jimczi** [comment]
We discussed internally and this is something we want to achieve using the Lucene's Matches API.
Extending `_name` query is one way to go but we'd prefer a new option with a better name that could replace the `_name` option entirely. The idea is to start simple by handling `phrase`s and `term`s created by any type of query but not multi-term queries (`prefix`, `wildcard`, ...) in the first implementation (the term that matches is not available in the current version of the Matches API).

**Comment by mgrishaber-merlin** [comment]
Apparently I posted this to the wrong issue earlier, so I will repost here.

I have a request for a new highlighter that returns a simple word list as part of the json, rather than returning marked up html text for each hit. So if I get 1000 hits for a query, I would expect to get back a single word list that contains all of the words that matched rather than 1000 html snippets.
Something like the following,
"hits": {
"total": 1000,
"max_score": null,
"hitlist": [
{
"ski",
"skiier",
"skiing",
"skiied",
"skiis"
]
}
"hits": [
{
"_index": "myindex",
"_type": "mytype",
"_id": "1",
"_score": 2.7186205,
"sort": [
1438971741000,
2.7186205,
.
.
.
"_index": "myindex",
"_type": "mytype",
"_id": "1000",
"_score": 2.7186205,
"sort": [
1438971741000,
2.7186205
]
}
}

Thanks
Mike

**Comment by jimczi** [comment]
@mgrishaber-merlin  I think that what you describe here is inlined with the proposal outlined in this issue. The only difference is that the list of words would be per document rather than for all documents.

**Comment by mgrishaber-merlin** [comment]
jimczi.  Thank you for your reply.  
The list per document is an issue for us.  We cap the number of documents at 5000.  So if there are 5000 documents, there are 5000 more serialized json snippets, which impacts performance.
Plus, since the words matched will vary from one document to another, we will have to parse the word list for each document, and compile a list of unique words.  This also impacts performance.  By returning the word list for each document, you are in fact replicating information and bloating the returned json string.
Please consider returning just a single list of all of the matched words at the start of the json string.  
All we are interested in is the id of the document, the scoring, and the matching word list for the query.

**Comment by jimczi** [comment]
> By returning the word list for each document, you are in fact replicating information and bloating the returned json string.

Each document can match a different list of terms (imagine you have multiple optional terms in the query) so I think it's mandatory to return it per document. Regarding performance we'll need to extract the terms for each top document anyway so returning or not returning the list per document should not make a difference (apart from the size of the response).

**Comment by mgrishaber-merlin** [comment]
It has been our experience in testing that serializing the json objects for thousands of hits has a significant overhead, so I would disagree that the size of the response is not a factor.
For our use case we really don't care which  document matched what.  We only care about the total word list.  If our users don't actively view a document, then the highlighted text is never used anyway.

How about if the new hit highlighter had an option to behave the way I have described, and otherwise would behave as you describe?

**Comment by jimczi** [comment]
This issue is not about a new highlighter, it's a proposal to extend (or replace) `_named` query with  something that can return the terms that match each document. We can add your idea in the mix but for simplicity I think we should start with a list of terms per document because this is the most relevant way to provide the informations.

**Comment by markharwood** [comment]
>Please consider returning just a single list of all of the matched words

What's the end goal here? What would your client use this list for?
The reason for asking is :
1) There may be another way of doing what you want (see `filters`/`adjacency_matrix` agg) or
2) It may reveal extra requirements e.g. would you want to see `IDE` in results for  the search `("java IDE" OR eclipse)` if the matched doc was "eclipse IDE"? Does the phrase-match logic need to be strict?

**Comment by javanna** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
