### ISSUE TITLE
maven引入spring-boot-starter-data-elasticsearch版本为3.0.7，为什么jar包@File注解中没有找到term_vector

### ISSUE THREAD

**Issue by liufan1993** [elastic/elasticsearch#34374]
### 1、这是我的maven依赖
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-elasticsearch</artifactId>
        </dependency>
        <dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>x-pack-transport</artifactId>
            <version>5.6.1</version>
        </dependency>
### 2、这是我要引入@File的地方
![image](https://user-images.githubusercontent.com/24200096/46715675-b0024e00-cc93-11e8-95d8-5739f1b8ba51.png)
我知道答题原因是，引入的spring-boot-starter-data-elasticsearch包中@File注解没有term_vector参数，
下面是@File注解类的内容，
`![image](https://user-images.githubusercontent.com/24200096/46715803-1f783d80-cc94-11e8-8c8e-eb1cc12ca8e7.png)`

想问一下，我要用term_vector该引入哪个jar包？谢谢

**Comment by jasontedor** [comment]
I am so sorry, but none of the maintainers of Elasticsearch can read this issue. We would like to help you, but since we do not know what you're saying, we can not. Could you please ask this on the [forum](https://discuss.elastic.co) where someone from the broader community might be able to help you.
