### ISSUE TITLE
Merge polygons(elasticsearch type geo_shape) and plot only outer boundary on google map.

### ISSUE THREAD

**Issue by Mayur91193** [elastic/elasticsearch#34416]
I am using Elasticsearch 6.2.

I have lots of polygons with geo_shape type in the elasticsearch and am using the same to plot the area on the google map.

What I want to do is merge few areas(type geo_shape polygons) and plot each group as outer boundaries on the google map.

I know one library named TurfJs which do the same thing by merging boundaries but I want to do this using elasticsearch.

Is it possible to do with the Elasticsearch? If yes, how?

**Comment by imotov** [comment]
Elasticsearch doesn't really perform operations on geoshapes. It can only be used to run searches and aggregations. Since this is a question about visualization, I think a better place to ask it would be in our Kibana forum https://discuss.elastic.co/c/kibana We are trying to use elasticsearch's github repository only for issues and feature requests and handle questions on the forum.
