### ISSUE TITLE
[Enhancement Request] Index Lifecycle policy execution metrics

### ISSUE THREAD

**Issue by yaronp68** [elastic/elasticsearch#34578]
## Background

For ILM monitoring, we need a short list of meaningful metrics for ILM we can collect using metricbeat and ship to the monitoring cluster for monitoring GUI and alerts consumption. The current API doesn't provide summarised counters. 

## Description of usage

To realise if everything goes as planned, user can relay on summarised metrics provided by a new API.

Several flows / steps:
* The user wants to realize how many transitions are successful on her cluster: hot-. warm warm->cold or warm -> delete etc and how many failed transition of each kind (how many indices are in ERROR).
* This can help with setting thresholds and alerts and as a starting point to realize if further investigation is needed.

For further investigations, propose to have a breakdown of the info by policy and by index name
So user can filter by index pattern, index and policy name

CC: @colings86 @bleskes @ruflin @ycombinator @chrisronline

**Comment by colings86** [comment]
The ultimate reason for having a summary API here is so the user has an "at a glance" view of whether there is something that they need to fix with their indexes which is stopping them progressing through their policy. In my mind there are 2 types of scenario the user is going to need to be alerted to:
1. There are indexes in the ERROR step - This isn't to do with a transition between phases but rather something has gone wrong on a specific step in the policy. I think for this one just highlighting that for all the indices using `policy_x` there are N indexes in the ERROR step (and maybe providing a list of those indices) is enough for the user to go digging to the source of the issue (first step would be to run the explain API on that index).
2. There are indexes that are stuck on a particular step in the policy but have not errored - This can be due to a range of things including not being able to move shards in the allocate action because e.g. the disks on the target nodes are past the watermarks. In this instance its hard to see at a glance that there is a problem so maybe having an indication of how many indices for a policy have managed to go from hot->warm, warm->cold etc. would give an indication to the user something is wrong. The thinking being that the user will know how many indexes should transition between each phase per day. We could also just count the number of indices that have completed (got to the phase complete step) for each phase rather than doing this on the transitions themselves.

The potential problem with 2 is the assumption that the user knows how many transitions to expect. This works fine with daily indexes as you expect 1 index to be created per day and then its easy to reason about the transitions from there. With rollover this is harder because if the indexing load is spiky you may have 2 indexes created one day and then none for the next 3 days and then 1 more the day after. Reasoning about these kinds of workloads can be a lot harder.

Another option is to try to summarise the information we already have per index in the `phase_time`, `action_time` and `step_time` and try to highlight to the user the maximum time an index has been waiting in a step. It may be easier for users to reason about how long they expect actions to take than how many they expect to be done in a certain timeframe and this information may allow the user to spot problems more easily?

**Comment by yaronp68** [comment]
@colings86 I really like the idea to use maximum step_time as an indicator for something going wrong and action_time for how slow an action might have taken (if I got it right)

**Comment by bleskes** [comment]
The main question I have is whether we want to have an index centric view into this (i.e., is my index managed OK?) or an ILM centric view (are all indices under ILM OK).  I think we can do both ways (though I'm more inclined to have an index view) and that that decision will impact how we design the API and the UI. Note that I do not mean to imply that we have to have one endpoint. we can still collect data from multiple endpoints if need be, but the response should be organized such that it's easy to combine.

Re the time based aspect - maybe we can keep simple and have a per phase expected time? if we a phase didn't finish (i.e., the index isn't just sitting there waiting for the next phase to start) within a certain amount of time we can flag the index? For example - All the actions needed to be taken by the warm phase should be done within 2 hours. The hot phase is an exception here IMO (because it is mainly driven by the roll over logic).

**Comment by colings86** [comment]
> The main question I have is whether we want to have an index centric view into this (i.e., is my index managed OK?) or an ILM centric view (are all indices under ILM OK). 

Personally I would also prefer an index-centric view here though I can see the appeal of a UI being able to aggregate to a higher level to indicate to the user if something is wrong across an entire use-case or even the entire cluster. Not sure if this aggregation should be kept in the UI or available on the API though. If we decide this should be kept to a UI then I think the required information is already available in an index-centric view on the explain API. If we decide we need some kind of summarise API then I think we can take the information from the explain API and repackage the response.

> Re the time based aspect - maybe we can keep simple and have a per phase expected time? if we a phase didn't finish (i.e., the index isn't just sitting there waiting for the next phase to start) within a certain amount of time we can flag the index? For example - All the actions needed to be taken by the warm phase should be done within 2 hours.

In general I think having a single time to monitor rather than phase, action and step times is a good thing. My only concern here is that the expected time to complete a phase is dependant on what actions the phase is doing, how big the index its performing the action on is, and the resources available to the cluster. Maybe having a set time of 2 hours is ok for most cases but it would be annoying for a user to be told something is wrong constantly when its just that the combination of allocate, shrink, and forcemerge on their cluster with their data volume takes over 2 hours. I guess this could be an option the user sets on the UI though?

**Comment by bleskes** [comment]
>  If we decide this should be kept to a UI then I think the required information is already available in an index-centric view on the explain API. If we decide we need some kind of summarise API then I think we can take the information from the explain API and repackage the response.

Classically this has been done in the UI. It doesn't feel like it reaches the scale that will require support from the ES nodes to aggregate the data.

>  I guess this could be an option the user sets on the UI though?

In general there a two options here - be super conservative with a value that only raises alarm when we're pretty sure there is a problem (1 day?) or make it configurable and go with a sane default. I'm not sure how far we are in the UI to support config options.

**Comment by yaronp68** [comment]
If we go with an index centric approach only, the metricbeat will need to aggregate the data, as reporting this information for each index will be too much of data to ship. We are already aware that we ship a lot of data per cluster. So it is worth doing some aggregation in ES if it doesn't take too much resources (I assume not)

**Comment by yaronp68** [comment]
Regarding alarms - we still don't have configurable thresholds for alarms

**Comment by bleskes** [comment]
> If we go with an index centric approach only, the metricbeat will have to aggregate the data

Can you clarify why? it's the UI that did the aggregation so far AFIAK.

**Comment by yaronp68** [comment]
@bleskes If Elasticsearch reports information at the index level and there are multiple indices in the cluster (like a 100s of them) we will have to add few values to each one or make the metricbeat module (as we are moving to metricbeats) sum them into policy level or cluster level

**Comment by bleskes** [comment]
@yaronp68 my question was why the UI can't do that, if harvests an endpoint that returns a JSON for, say, 2000 indices, can't it some it up? if it can't we should adapt the end point. TBH i feel we're having fairly low level discussions without first settling on the bigger picture. It feels inefficient.

**Comment by yaronp68** [comment]
@bleskes Just to briefly document our zoom. Agreed that this feature should have index level information in order to provide the picture and that the monitoring cluster can provide the aggregation to policy level if needed

**Comment by yaronp68** [comment]
this one is out-dated. Will close and open another one with current user stories
