### ISSUE TITLE
QUERY: `_all` why deprecated ?

### ISSUE THREAD

**Issue by PMickael** [elastic/elasticsearch#34587]
Hello,

I was trying the elastic 6.4.2 to plan an upgrade, and the biggest problem in my case is `_all` field, why did you choose to do that (there isn't any explanation on the website) ?
Because in this example:
```json
{
  "span_near": {
    "clauses": [
      {
        "span_term": {
          "_all": "hello"
        }
      },
      {
        "span_term": {
          "_all": "world"
        }
      }
    ],
    "in_order": true,
    "slop": 10
  }
}
```

To make this query, with all field I want (for example 5), it make me copy/paste 5 time the exact same query, and also it's a way more complicated if I need to combine 2 of this type of research, because for example, if I have 2 match like this to do, I can't use minimum_should_match: 2, because maybe my first one will match in name, fullname for example.

Regards,
Mickael

**Comment by PMickael** [comment]
I found the explanation:

`The “_all” field was deprecated in Elasticsearch 6.0, this is the first part in the explanation for the storage space savings we’re seeing. If you’re unfamiliar with the “_all” field, it’s a special field used to concatenate all values together, making it easy to search everything. The “_all” field made it easy to get started with Elasticsearch, however, the “_all” field uses a lot of additional storage space (especially as values are duplicated).`

Maybe there is a workaround ?

**Comment by romseygeek** [comment]
Hi @PMickael, thanks for raising the issue.  For most queries, this isn't a problem because you can set  `default_field:*` and you'll get the same results, but span queries are tricky (in general!).  In your case, you should be able to use `copy_to` directives on the five fields you are interested in to create your own version of the `_all` field.  Or you may be able to produce the same sort of results using match queries and phrase slop.

Seeing as this is a usage question, and we try and keep github for bugs or enhancements, I hope you don't mind that I close this issue.  If you want further help, we have discussion forums at https://discuss.elastic.co which is the best place to open an issue.
