### ISSUE TITLE
[CI] GetUserPrivilegesResponseTests failure [:x-pack:plugin:core]

### ISSUE THREAD

**Issue by lipsill** [elastic/elasticsearch#34610]
I just notice a CI failure in GetUserPrivilegesResponseTests 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request/242/console

```
18:04:31   2> REPRODUCE WITH: ./gradlew :x-pack:plugin:core:test -Dtests.seed=1E5F34897FD60A6C -Dtests.class=org.elasticsearch.xpack.core.security.action.user.GetUserPrivilegesResponseTests -Dtests.method="testEqualsAndHashCode" -Dtests.security.manager=true -Dtests.locale=uk -Dtests.timezone=Atlantic/St_Helena -Dcompiler.java=11 -Druntime.java=8
```

```
18:04:31 FAILURE 0.03s J3 | GetUserPrivilegesResponseTests.testEqualsAndHashCode <<< FAILURES!
18:04:31    > Throwable #1: java.lang.AssertionError: GetUserPrivilegesResponse mutation should not be equal to original
18:04:31    > Expected: not <org.elasticsearch.xpack.core.security.action.user.GetUserPrivilegesResponse@8a3a3b0>
18:04:31    >      but: was <org.elasticsearch.xpack.core.security.action.user.GetUserPrivilegesResponse@8a3a3b0>
18:04:31    > 	at __randomizedtesting.SeedInfo.seed([1E5F34897FD60A6C:6D91CC447C73755D]:0)
18:04:31    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
18:04:31    > 	at org.elasticsearch.test.EqualsHashCodeTestUtils.checkEqualsAndHashCode(EqualsHashCodeTestUtils.java:82)
18:04:31    > 	at org.elasticsearch.xpack.core.security.action.user.GetUserPrivilegesResponseTests.testEqualsAndHashCode(GetUserPrivilegesResponseTests.java:100)
18:04:31    > 	at java.lang.Thread.run(Thread.java:748)
```

I was able to reproduce it locally and on master ca51fb687393ede4b3ed27145efbd46a3ae883b0 as well.

**Comment by lipsill** [comment]
@tvernum can you have a look at this? Thanks!

**Comment by lipsill** [comment]
@jasontedor I just saw that @tvernum added the test a few hours back 9200e15b74d92593aea0c157741739c12247f6c4 so I assumed that they still 'have the context' and will be able to quickly pinpoint the issue ;) I should have used more words, sorry ...

**Comment by andyb-elastic** [comment]
Hi @lipsill - in the future if a CI test failure is blocking a pull request you submitted, it would be helpful to us if you noted it on the pull request rather than opening a new issue. The issues in this repo that look like this one are part of a CI failure triage process we have.

Also, it's not helpful to us to ping individuals directly when opening an issue - the way we label issues ensures that the right team members will be notified (for example Tim is part of the es-security team pinged above).

No worries, thanks for bringing this to our attention and your enthusiasm contributing to the project

**Comment by lipsill** [comment]
@andyb-elastic thanks for the clarification. I did not know that you have a strict internal process for any CI failures. Sorry for muddying the waters. 
Should I just close the issue?

**Comment by andyb-elastic** [comment]
No problem at all, let's leave it open :)
