### ISSUE TITLE
[Enhancement] Add elapsed time to rollup job metrics

### ISSUE THREAD

**Issue by yaronp68** [elastic/elasticsearch#34712]
### The ask
Add elapsed time metering the time for this job execution to rollup job under the `GET _xpack/rollup/job/_all` 

e.g. 

```
"status" : {
            "job_state" : "stopped",
            "upgraded_doc_id": true
          },
          "stats" : {
            "elapsed_time_millis": 12000,
            "pages_processed" : 0,
            "documents_processed" : 0,
            "rollups_indexed" : 0,
            "trigger_count" : 0
          }
        }
```
### Motivation:
Elapsed time together with other metrics gives an indication about the load running in the background on the cluster and how slow / fast the rollup information is processed and indexed

**Comment by polyfractal** [comment]
Note: to support this we'll likely add a `start_time` to the task stats/status too, since it'll be needed to create the elapsed time.

Or maybe _just_ the start time, and let clients/UI calculate the elapsed time.

**Comment by colings86** [comment]
I wonder if it would be useful for the persistent task framework itself to store a start time as this seems like useful information for all persistent tasks?

**Comment by polyfractal** [comment]
++ Good point, it's probably a generically useful feature for anything using persistent tasks.

**Comment by wchaparro** [comment]
With the 8.7 release of Elasticsearch, we have made a [new downsampling capability](https://www.elastic.co/guide/en/elasticsearch/reference/current/downsampling.html) associated with the new [time series datastreams](https://www.elastic.co/guide/en/elasticsearch/reference/current/tsds.html) functionality generally available (GA). This capability was in tech preview in ILM since 8.5.  Downsampling provides a method to reduce the footprint of your time series data by storing it at reduced granularity. The downsampling process rolls up documents within a fixed time interval into a single summary document. Each summary document includes statistical representations of the original data: the min, max, sum, value_count, and average for each metric. Data stream time series dimensions are stored unchanged. 

Downsampling is superior to rollup because:

- Downsampled indices are searched through the _search API
- It is possible to query multiple downsampled indices together with raw data indices
- The pre-aggregation is based on the metrics and time series definitions in the index mapping so very little configuration is required (i.e. much easier to add new time serieses)
- Downsampling is managed as an action in ILM
- It is possible to downsample a downsampled index, and reduce granularity as the index ages
- The performance of the pre-aggregation process is superior in downsampling, as it builds on the time_series index mode infrastructure

Because of the introduction of this new capability, we are deprecating the rollups functionality, which never left the Tech Preview/Experimental status, in favor of downsampling and thus we are closing this issue. We encourage you to migrate your solution to downsampling and take advantage of the new TSDB functionality.
