### ISSUE TITLE
Cannot index _size with Mapper Size plugin in Graylog

### ISSUE THREAD

**Issue by eroji** [elastic/elasticsearch#34786]
Not sure if this is a Graylog issue or ES/plugin issue. I have installed mapper size plugin on all ES nodes in the cluster and I have enabled the plugin for the default mapping of "documents" for Graylog index. However, the _size field does not populate anywhere nor can I search it in Graylog. I also tried enabling _size in the custom index template I have created for Graylog.

```
{
  "order": 0,
  "template": "graylog_*",
  "settings": {},
  "mappings": {
    "message": {
      "_size": {
        "enabled": true
      },
      "properties": {
...
        }
      }
    }
  },
  "aliases": {}
}
```

Following the example on https://www.elastic.co/guide/en/elasticsearch/plugins/2.0/mapper-size-usage.html when I try to search the index of _size value, I get results but none of them show what the _size value is, which leads me to believe it isn't working correctly.

My cluster configuration is the following:

- CentOS 6.9
- ElasticSearch 2.4.4 nodes
- Graylog 2.2.3

**Comment by spinscale** [comment]
please use the [discuss forum](https://discuss.elastic.co/c/elasticsearch) for these kind of questions, as we try to reserve github for bugs/features only. Also, please ensure you are coming up with a fully fledged example there, see [our help](https://www.elastic.co/help). Thank you!

**Comment by dmuensterer** [comment]
For anyone having the same problem:
OP made the issue of setting "_size" for message - that's wrong because _size is an Elasticsearch field that is non-dependend on other fields. It does nothing else than "when enabled, indexing the size in bytes of the original _source field" as per the [documentation](https://www.elastic.co/guide/en/elasticsearch/plugins/7.17/mapper-size.html)

Instead what you would want to do is something similar to:

```
{
  "order": 0,
  "template": "graylog_*",
  "settings": {},
  "mappings": {
    "_size": {
        "enabled": true
      },
    "message": {
      "properties": {
...
        }
      }
    }
  },
  "aliases": {}
}
```
