### ISSUE TITLE
ILM DELETE API does not support multiple delete

### ISSUE THREAD

**Issue by bmcconaghy** [elastic/elasticsearch#34873]
If I want to delete more than 1 ilm policy I need to make n calls to `DELETE _ilm/{policyName}` rather than passing a comma separated list as policyName
I expect it to allow for a comma separated list like other ES APIs.

**Comment by nik9000** [comment]
>  I expect it to allow for a comma separated list like other ES APIs.

We've been thinking more in the opposite direction: these APIs that support comma delimited lists make error handling complex to implement and complex to describe. Things like `_search` need it so it, but APIs like ILM maybe don't.

**Comment by dakrone** [comment]
I think we should stick with 1, we've had some weirdness in the past with APIs that support comma-separated lists and responses, for example, what happens if some of the items exist and others don't, what HTTP status code should we use? What should the response look like? It's much simpler and easier to get correct with only supporting a single policy.

**Comment by bmcconaghy** [comment]
Good by me, closing.
