### ISSUE TITLE
SQL: Wrong NULL folding of expression

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#35232]
```
SELECT POSITION('x',LCASE("first_name")) pos, "first_name" FROM "test_emp"
WHERE POSITION('x',LCASE("first_name")) != 0 OR POSITION('x',LCASE("first_name")) IS NULL;
```
is  translated to: 

```
"InternalSqlScriptUtils.nullSafeFilter(InternalSqlScriptUtils.neq(InternalSqlScriptUtils.position(params.v0,InternalSqlScriptUtils.lcase(InternalSqlScriptUtils.docValue(doc,params.v1))),params.v2))"
```

The right part of the `OR` is missing because it's wrongly folded by the FoldNull rule. The POSITION can potentially be null.

**Comment by costin** [comment]
Likely the nullability of the right side is reported incorrectly. `IS NULL` is not nullable which should cause `OR` to not be nullable.
As a separate side, due to the 3VL, both `OR` and `AND` need to take into account their folding - if it's possible, then they are not nullable (one side is `true` for `OR` or one is `false` for `AND`).

**Comment by matriv** [comment]
Yep, also functions like POSITION can have any of their arguments NULL so they are nullable->true
