### ISSUE TITLE
HLRC: remove duplication from ascii docs 

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#35345]
there is a way to decrease duplication when writing the documentation for HLRC

Things to fix:
- migration API - once commited #34898
- bulk API - mostly done by @nik9000 in #34925, small improvements in #35413 
- reindex API - improvments in #35413

see #34925

**Comment by pgomulka** [comment]
@jakelandis @nik9000 there is obviously always a way to improve the documentation, but I suppose that this issue can be now closed. It would be better to open a new one, then to have this one hanging around open. 
what do you think?

**Comment by jakelandis** [comment]
I still have a TODO reminder (that pops up weekly) to organize and distribute some of the work here.  I have a minor preference to keep this one open since it has some relevant history. I suspect in the next couple weeks I will be able to update this (or a different) issue with something actionable.

**Comment by jrodewig** [comment]
[docs issue triage]

Leaving open. This is still relevant and planned for work.
