### ISSUE TITLE
[docs] forward referencing to newer version

### ISSUE THREAD

**Issue by monfera** [elastic/elasticsearch#35363]
Google search, or other means of landing on our docs pages often lead users to an earlier version of the document, and finding the corresponding current version is sometimes not a direct step.

Example: [old version](https://www.elastic.co/guide/en/x-pack/current/actions-pagerduty.html) [new version](https://www.elastic.co/guide/en/elastic-stack-overview/current/actions-pagerduty.html) but the old version points to a [document root](https://www.elastic.co/guide/en/elastic-stack-overview/current/index.html)

Users may expect version cross-referencing for everything, as it's a search problem and the documents are about a search product.

Due to product changes, in this case, the link from the old version chain to the new is interrupted,  leading to a document root,though the contents are identical. Some ideas (of which a dime a dozen, of course):

- somehow link the doc versions even in the face of product / repo structure change (which is the cause here) by searching for similar cases (or migrate old page versions for an uninterrupted version chain)
- provide means for editing the doc by visitors (it's not an open repo so users don't have the `Edit` button available, but there could be some other means for doc Suggestion or Feedback)
- alternatively, when the cross-referencing just points to a generic root page, there could be some comment that due to product changes, the version chain is terminated, otherwise it has a slight 404 feel
- the root doc page could have a search feature, it might be a general expectation especially if detail visitors are landed there, as we're in search
- maybe web search engines have a more refined tool than e.g. [making content outdated](https://support.google.com/websearch/answer/6349986?hl=en) that could let us readjust intra-site priorities to land general, non-version specific queries on the current version page

**Comment by nik9000** [comment]
I think we've talked about this problem on and off for a few months now. I wonder if we should have the "current" versions of those pages redirect to the actual current location. That interrupts the version navigation, but it'd prevent the "current version isn't the current version" problem.

**Comment by debadair** [comment]
So set up redirects for every "current" page in the X-Pack ref? That would get people to the right pages, but that's a lot of redirects and the experience would still be jarring. I'd be hesitant to go that route--we already have issues due to the large number of doc redirects. (It's fragile to manage them and easy to end up with conflicts.)

We could easily tweak the messaging in the banner that links to the stack docs. So ending up at the TOC page is less unexpected. (Assuming people actually read it.)

From 6.3 onward, everything except the Cloud docs can be edited. We've also discussed adding a feedback collection widget. (That's one of several things on our improvements wishlist.)

There is a search-in-docs capability today--it's built into the site search. I agree, though, that making it more obvious from the doc pages would be helpful. (I wonder given the current design how many people even realize you can search the docs.)

We've been discussing SEO considerations with @AnneB-SEO. Driving web searches to the current version is kind of problematic due to the way pages get ranked. Duplicating the pages under current kind of exacerbates the SEO problems. It's convenient at one level, but keeps coming back to haunt us in various ways.
