### ISSUE TITLE
search_after request documentation may be misguiding

### ISSUE THREAD

**Issue by rdigiorgio** [elastic/elasticsearch#35369]
Using the search_after request, I did follow the "recommended way" to use the `_id` property as a sorting tiebreaker. Having a string as `_id` for something near 2.000.000.000 documents and using search_after request to scroll fair amounts of documents, if I am correct, my fielddata cache did fill up with data necessary to apply the sort on my documents. To get around this problem, I just went back to sorting on integer properties (that I use to build the `_id` property...).

To me, recommending to use the `_id` property without warning against potential issues using it seems to be problematic: **should the documentation be updated to add more specific information about this case ?**

If I am not mistaken, the recommendation is only valid if using a generated `_id`, or an integer.
Also, those two documentation page seem to be conflicting:
 - https://github.com/elastic/elasticsearch/blob/master/docs/reference/search/request/search-after.asciidoc
 - https://github.com/elastic/elasticsearch/blob/master/docs/reference/mapping/fields/id-field.asciidoc

One says that using `_id` for aggregations and sorting is not recommended, the other recommends using `_id` as part of the sort tiebreaker for search_after requests.

**Comment by jimczi** [comment]
Thanks @rdigiorgio

>  should the documentation be updated to add more specific information about this case ?

Agreed, I opened #35370 to change the recommendation. 

> If I am not mistaken, the recommendation is only valid if using a generated _id, or an integer.

It is valid for any type of `_id` since it is required to have a unique value per document in this field.
However we don't build `doc_values` for this field so we need to load the values in the `field_data` which is costly if you have a lot of documents. I changed the recommendation in the docs to advise to use a copy of the `_id` field with doc_values enabled.
