### ISSUE TITLE
Block Mapping on Reserved Field

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#35389]
When trying to change the behavior of certain reserved fields, a user may be tempted to try to change their mapping:

```http
PUT my_index
{
  "mappings": {
    "_doc": {
      "_field_names": {
        "type": "keyword"
      }
    }
  }
}
```

This doesn't work (it remains mapped as `text` in this case, which coincidentally seems wrong), but the request is accepted. When fetching the mapping, this attempted alteration does not exist in the response.

Relates to #8143.

**Comment by pickypg** [comment]
As a side note, if you try to put it into the `properties` section of the type, then it does properly reject the field with `Field [_field_names] is defined twice in [_doc]`.

It seems like we need to become a little stricter about unknown fields outside of the `properties` block.

**Comment by jtibshirani** [comment]
Thanks @pickypg for reporting this and sorry for the very late response! I dug a bit into this behavior and had a few clarifications:
- The correct way to configure `_field_names` is indeed outside the `properties` block (https://www.elastic.co/guide/en/elasticsearch/reference/7.1/mapping-field-names-field.html). We correctly reject invalid fields outside the property block, returning the error ""Root mapping definition has unsupported parameters: ..."
- As you noted, it is not possible to update metadata field mappings, as we throw an error of the form "Field ... is defined twice in ...".

I think a big reason your original example caused confusion is that we accept `"type": "keyword"` in the `_field_names` configuration, even though this is not a valid argument. This bug seems to be specific to the 'type' key, as we correctly reject other invalid keys. I'll open a PR to fix this leniency.
