### ISSUE TITLE
Create Rust client

### ISSUE THREAD

**Issue by andrewbanchich** [elastic/elasticsearch#35538]
**Describe the feature**:

It would be fantastic to have an Elasticsearch client for Rust. There are currently only a couple third party offerings that are not anywhere near ready for production.

Rust has been voted the most loved programming language for the last three consecutive years on StackOverflow, and with companies beginning to move to its use in production, it would fit a pretty big hole in the Rust ecosystem to have an official ES client and allow developers to begin integrating with Elasticsearch from the start.

**Comment by markharwood** [comment]
@polyfractal care to comment? 
Not sure where best to lodge this issue as it technically is a request for a whole new repo/project.

**Comment by polyfractal** [comment]
Yeah, I'm not sure either.  @sophiec20 is probably best to handle this since she's in charge of the clients team now.

<3 Rust!

**Comment by eskibars** [comment]
Hey @andrewbanchich, thanks for the input!  We are considering which client(s) to work on, so it's useful to hear this request.  As @markharwood mentions, we don't really have a place to file client requests right now, so we may end up moving this at some point.  We are aware of the community-contributed clients (which, for those that end up finding this issue later, can go to https://www.elastic.co/guide/en/elasticsearch/client/community/current/index.html#rust to see).  I have to admit I'm not a rust developer myself: I'd love to hear about what the existing clients isn't production-ready in your mind.

**Comment by russcam** [comment]
@KodrAus would you be able to comment on what might be currently missing in the Rust client that you've worked on?

**Comment by KodrAus** [comment]
@russcam the client I built is a bit of an artifact of an older Rust before it offered async io and code generation. With those features in mind today I would approach it a little differently.

**Comment by andrewbanchich** [comment]
@eskibars The existing clients all have notes like "not for production" or "use at your own risk." None of them are ready for prime time, so it would be very beneficial to the Rust community to have something with official support.

**Comment by polyfractal** [comment]
For completeness, I'm also aware of [rs-es](https://github.com/benashford/rs-es) which is trying to provide a fully typed ES client (request objects, query DSL and and responses).  It was also built before async io came to rust-land, and I believe it's still using an older pre-Tokio version of Hyper so it doesn't support async requests either.  

And just generally, since it is trying to strongly type everything there's a lot of work to do and many less common endpoints are missing.

**Comment by KodrAus** [comment]
I've got about 12 months of inventory sitting in a branch and in PRs in `elastic`, the Rust client I wrote, that I really want to get out the door that is at least a more solid foundation for consumers. A lot of the API complexity in `elastic` has come from trying to support both a synchronous and asynchronous client with a single API because the early Rust `futures` are a bit tricky to work with and not everybody will want to take them on. The limiting factor for me right now is that we're still in a state of steady churn with Rust's async story, so focusing time on building out Elasticsearch's APIs means falling behind in the underlying http infrastructure, and vice-versa.

So given that I think once Rust has its [`async`/`await` language support on the stable channel](https://github.com/rust-lang/rust/issues/50547) that's about the right time to look really seriously at what an ideal Rust client would look like.

**Comment by nateeklund** [comment]
It sounds like the thought was to wait until async/await was out, which it now is.
Is now the time to look further into a Rust client?

**Comment by andrewbanchich** [comment]
@KodrAus Any thoughts / updates on this now that async / await has been stabilized?

**Comment by KodrAus** [comment]
@andrewbanchich It definitely seems like the right timing now to start thinking seriously about an ideal Elasticsearch Rust client! Personally, I would be leaning towards something that's only async/await out-of-the-box, and let callers do the async-to-sync bridging if they need it. This used to be quite tricky to do in the early days of futures, but I think it's much more straightforward now.

**Comment by philkra** [comment]
We are currently working on a Rust client that will "only" support async-await. A definite release date of a public alpha version is not yet set. Let's keep this thread alive to keep everyone up to date on the client's status.

/cc @KodrAus & @andrewbanchich & @nateeklund

**Comment by andrewbanchich** [comment]
Awesome! @philkra I'd love to help out with that if you guys want.

**Comment by philkra** [comment]
You're more than welcome to contribute 👍 The client is currently residing in a private repo, we are working on getting it out publicly. I'll ping you first thing once it's public

**Comment by russcam** [comment]
@andrewbanchich the [rust client repository is now public](https://github.com/elastic/elasticsearch-rs), with the [first _alpha_ release to crates.io](https://crates.io/crates/elasticsearch).

**Comment by philkra** [comment]
closing this, the rust client is now public.
