### ISSUE TITLE
ES6.5.0 to ES5.0.1

### ISSUE THREAD

**Issue by CrocdileChan** [elastic/elasticsearch#35635]
I have a problem.if I used to ES6.5.0 to store data. and now, I want to take data  into a ES5.0.1  .

Can the data path and the logs path still use ES6.5.0?

Sorry for my bad english!

thanks a lot

**Comment by DaveCTurner** [comment]
Hi @CrocdileChan, thanks for your question. We prefer to keep GitHub issues for confirmed bug reports and features, and your question is better suited for the [discussion forum](https://discuss.elastic.co/c/elasticsearch). I'm closing this issue here, but it's a good question and you should get a useful response on the discussion forum.
