### ISSUE TITLE
[CI] MovAvgIT.testHoltWintersValuedField fails for specific seed in 6.x

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#35632]
Build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-darwin-compatibility/61/console

Failure:

```
> Throwable #1: java.lang.AssertionError: [value] movavg does not match expected [-4.1001959348322787E-7 vs -3.580961465707474E-7] expected:<-4.1001959348322787E-7> but was:<-3.580961465707474E-7>
   >    at __randomizedtesting.SeedInfo.seed([658B5ACAC4C41985:AE8604C1A0B0A9AB]:0)
   >    at org.elasticsearch.search.aggregations.pipeline.moving.avg.MovAvgIT.assertBucketContents(MovAvgIT.java:1305)
   >    at org.elasticsearch.search.aggregations.pipeline.moving.avg.MovAvgIT.testHoltWintersValuedField(MovAvgIT.java:649)
   >    at java.lang.Thread.run(Thread.java:748)
```

Reproduce with:

```
 ./gradlew :server:integTest -Dtests.seed=658B5ACAC4C41985 -Dtests.class=org.elasticsearch.search.aggregations.pipeline.moving.avg.MovAvgIT -Dtests.method="testHoltWintersValuedField" -Dtests.security.manager=true -Dtests.locale=zh-CN -Dtests.timezone=America/Santo_Domingo -Dcr.java=11 -Druntime.java=8
```

Reproduces consistently on my machine.

**Comment by cbuescher** [comment]
This looks very similar to #29456, maybe @polyfractal can tell whether that fix got backported or not and if those two are related?

**Comment by polyfractal** [comment]
Unfortunately, it was backported in https://github.com/elastic/elasticsearch/commit/edbb806ea10bc895be43854f53f55d8633ec2d1f.  Shame since that would have been an easy fix.

It's the holt winters test, which has a habit of being afflicted by floating point error due to the random nature of the test.  There's also a slim chance that it's related to the moving function pipeline agg, which shuffled the code around a bit and may have had a side effect.

But I'd put my money on compounded fp error.

@dimitris-athanasiou would you mind muting this until I get a chance to take a look?

**Comment by dimitris-athanasiou** [comment]
@polyfractal Happy to!

**Comment by dimitris-athanasiou** [comment]
Muted in efd1f1b29ff51d28a1a1c702cef6a7ce2554ee2a

**Comment by dimitris-athanasiou** [comment]
Note that I couldn't reproduce on master with the same seed.

**Comment by polyfractal** [comment]
Hm, so I can't reproduce this.  I've had hundreds of thousands of test iterations (just left it running in background) and can't get this to fail, either on the provided seed or random seeds.

I'm thinking perhaps the failure was from before https://github.com/elastic/elasticsearch/commit/edbb806ea10bc895be43854f53f55d8633ec2d1f and CI was just lingering or something.  I'm going to unmute the test and we'll see if it fails again.
