### ISSUE TITLE
Cluster settings returns boolean fields as strings

### ISSUE THREAD

**Issue by jen-huang** [elastic/elasticsearch#35671]
**Actual behavior**

I'm changing a cluster's `skip_unavailable` boolean setting:

```
PUT _cluster/settings
{
  "persistent": {
    "cluster": {
      "remote": {
        "test_cluster": {
          "skip_unavailable": true
        }
      }
    }
  }
}
```

That request returns:
```
{
  "acknowledged" : true,
  "persistent" : {
    "cluster" : {
      "remote" : {
        "test_cluster" : {
          "skip_unavailable" : "true"
        }
      }
    }
  },
  "transient" : { }
}
```

Note that the request returns `skip_unavailable` as `"true"` instead of `true`. I am not sure if it would do the same for numeric fields.

This also occurs when retrieving settings with `GET _cluster/settings`.

**Expected behavior**

Return with correct type (like how `GET _remote/info` returns `skip_unavailable` as a boolean).

**Comment by rjernst** [comment]
This is due to how settings are stored internally. They are essentially a flat key/value map (string to string). Serializing to json just expands that map based on dots in the field name, but the values are still the "raw" string values. This could certainly be changed, but I think it will be a large amount of work. We would need the corresponding `Setting` object for each setting contained, in order to interpret the value and decide on an appropriate json representation and the `Setting` objects are not anywhere accessible by this response writing code.

**Comment by gwbrown** [comment]
I'm labeling this as `team-discuss` to determine whether this is something important enough to us that we're likely to invest enough development effort into fixing it, or if this should be a known limitation.

**Comment by gwbrown** [comment]
We discussed this in today's core/infra sync and decided that we're not likely to fix this issue in the near future.

This issue, while perhaps annoying, is generally quite easy to work around: Parsing a string into a boolean is not a particularly difficult task in any programming language. Additionally, this would require a significant amount of work to change, due to how Elasticsearch stores and serializes settings.

Without a concrete issue that this is causing that's difficult to work around, this issue remains a low-priority one. Given the amount of higher-priority features and bug fixes we could address using the time and effort that would be required to address this issue, we are not going to get to this issue in a reasonable time frame. As such, we're going to close this issue.

If you have a use case that this bug blocks, or another compelling reason we should reconsider fixing this in the near future, please comment and we can potentially reopen this.
