### ISSUE TITLE
Task integTest can not run individual tests with parenthesis in name

### ISSUE THREAD

**Issue by lukas-vlcek** [elastic/elasticsearch#35692]
**Elasticsearch version** (`bin/elasticsearch --version`):  Tested with `6.4.3`.

Say I have rest api test file with the following content:
```
$ head -n 2 src/test/resources/rest-api-spec/test/resthandler/10_Foo.yml
---
"Bar (Hello)"
```

When I run complete integration tests using `gradle clean check`, everything goes fine.

But if I use `integTest` task to run specific test like this:

```
gradle :integTest \
  -Dtests.class=org.elasticsearch.rest.SomeYamlTestSuiteIT \
  -Dtests.method="test {yaml=resthandler/10_Foo/Bar (Hello)}"
```
This ends with:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':integTestRunner'.
> There were no executed tests: 1 suite (1 ignored), 0 tests
```
However, if I remove parenthesis from the test name (i.e. I modify second line in `10_Foo.yml` file) and run:

```
gradle :integTest \
  -Dtests.class=org.elasticsearch.rest.SomeYamlTestSuiteIT \
  -Dtests.method="test {yaml=resthandler/10_Foo/Bar: Hello}"
```
then it works as expected.

**Comment by dliappis** [comment]
I've been able to reproduce this, e.g. tinkering with `./rest-api-spec/src/main/resources/rest-api-spec/test/info/10_info.yml` on the 6.5.0 branch and using `./gradlew :distribution:archives:integ-test-zip:integTest -Dtests.class="org.elasticsearch.test.rest.*Yaml*IT" -Dtests.method="test {p0=info/10_info/Info}"`. (FYI we've switched to `./gradlew` since https://github.com/elastic/elasticsearch/commit/74dc60fc97c03317ec3f13fdeb6332fba2e9fa3d).

The issue here is that `com.carrotsearch.ant.tasks.junit4.dependencies.com.carrotsearch.randomizedtesting` globs things very aggressively and the parens used in the string passed in `-Dtests.method` are interpreted as capture groups e.g. if I introduce a trailing parens by mistake, I see:

```
./gradlew :distribution:archives:integ-test-zip:integTest -Dtests.class="org.elasticsearch.test.rest.*Yaml*IT" -Dtests.method="test {p0=info/10_info/Info)}"

<snip...>
> At least one slave process threw an exception, first: Forked process returned with error code: 240. Very likely a JVM crash.  See process stderr at: /home/dl/source/elastic/elasticsearch/distribution/archives/integ-test-zip/build/testrun/integTestRunner/temp/junit4-J0-20181119_192609_4425197339072811181731.syserr
```

and then looking at the syserr file:

```
cat /home/dl/source/elastic/elasticsearch/distribution/archives/integ-test-zip/build/testrun/integTestRunner/temp/junit4-J0-20181119_192609_4425197339072811181731.syserr
WARN: Exception at main loop level. -> java.util.regex.PatternSyntaxException: Unmatched closing ')' near index 27
^test \{p0=info/10_info/Info)\}$
                           ^
        at java.util.regex.Pattern.error(Pattern.java:1957)
        at java.util.regex.Pattern.compile(Pattern.java:1702)
```

Trying to escape `()` with `\` doesn't help as `RandomizedRunner` escapes the `\'` itself :)

Discussed with @nik9000 who was kind enough to provide a thorough explanation and will take a look.
