### ISSUE TITLE
Feature request: Label on bulk api 

### ISSUE THREAD

**Issue by najdanovicivan** [elastic/elasticsearch#35739]
I'd like to have ability to pass the label in bulk api Index and update parameters this can be used to track responses much better. For example I am migrating the data from MySQL and I want ElasticSearch to generate the ids but at the same time I want to keep track of ids from MySql.

I'd like to be able to send request in the following format

```json
{ "index" : { "_index" : "test", "_type" : "_doc" ,"label":"my_label"} } 
```
I like to get that same label field completely the same in response 

```json
{
   "took": 30,
   "errors": false,
   "items": [
      {
         "index": {
            "_index": "test",
            "_type": "_doc",
            "_id": "1",
            "_version": 1,
            "result": "created",
            "_shards": {
               "total": 2,
               "successful": 1,
               "failed": 0
            },
            "status": 201,
            "_seq_no" : 0,
            "_primary_term": 1,
            "label":"my_label"
         }
      },
   ]
}
```

Would be great if this could be done for all types of requests: "index","delete","create" ,"update"

**Comment by MirAkram** [comment]
mj1265849@gmail.com
در تاریخ ۲۰ نوامبر ۲۰۱۸ ۷:۳۴ بعدازظهر، "Najdanovic Ivan" <
notifications@github.com> نوشت:

**Comment by imotov** [comment]
> I want ElasticSearch to generate the ids but at the same time I want to keep track of ids from MySql

Could you explain the reason for this? Why not just use MySql ids instead of asking Elasticsearch to generate ids and risk having the duplicate data?

I would also like to mention that the responses are coming back in the same order as the requests, so keeping track of this on the client side is as simple as keeping an array of strings with MySql ids until you get the response back.

**Comment by najdanovicivan** [comment]
I migrating from SQL database and I have to use joins in ElasticSearch. There is data from multiple tables so there are same id's across various tables. I am unable to use different types anymore since mapping type is deprecated in 6.0.0 

The the other reason I need those Ids to be generated by ElasticSearch is because I am going to use ElasticSearch not only as search engine but as the main database for the project. MySQL tables are going to be removed. Project is based on data aggregation from various APIs and later on the new data will be aded directly to the ElasticSearch. So the ids from MySQL will be numeric values while new ones will have them as hashes. I wan't all of the documents to have id's in same format.

About the responses coming in order.  That is how I'm currently doing it by tracking what is being send and what is returned. But it will be much more convenient if label can be passed especially when things are done asynchronously.

**Comment by jasontedor** [comment]
We have had previous requests like this to be able to incorporate some context into the request that is maintained and returned server side. Our reasoning for not accepting these requests is because that context can be held client side already (for example, in the capture of an asynchronous callback). Additionally, with this way, you can structure the context however you like, and we are not subject to a myriad of requests to format it for specific use cases. I still think this is the right way to handle this, as opposed to passing it around in requests and waiting for it to come back in responses.

**Comment by jasontedor** [comment]
Additionally, a goal we have is to (within other constraints) keep APIs small and accepting this request runs counter to that. It increases the surface area of the API without a concomitant increase in functionality.

**Comment by jasontedor** [comment]
No further feedback, closing.
