### ISSUE TITLE
POST _aliases remove_index does not support wildcard exclusion

### ISSUE THREAD

**Issue by exe-dealer** [elastic/elasticsearch#35882]
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 6.5.1, Build: default/tar/8c58350/2018-11-16T02:22:42.182257Z, JVM: 11.0.1

**OS version** (`uname -a` if on a Unix-like system):
Linux 15484e2ef940 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

```
PUT test-1
PUT test-2
POST _aliases
{
  "actions": [{
    "remove_index": {
      "index": "test-*,-test-1"
    }
  }]
}
```

Last command produces

```json
{
  "error" : {
    "root_cause" : [
      {
        "type" : "index_not_found_exception",
        "reason" : "no such index",
        "resource.type" : "index_or_alias",
        "resource.id" : "test-*,-test-1",
        "index_uuid" : "_na_",
        "index" : "test-*,-test-1"
      }
    ],
    "type" : "index_not_found_exception",
    "reason" : "no such index",
    "resource.type" : "index_or_alias",
    "resource.id" : "test-*,-test-1",
    "index_uuid" : "_na_",
    "index" : "test-*,-test-1"
  },
  "status" : 404
}
```

But I expect the last command to successfully delete test-2 and keep test-1 because doc says that `remove_index` is just like Delete Index
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html#CO181-3
And `DELETE test-*,-test-1` works as expected

**Comment by exe-dealer** [comment]
`remove_index` does not support commas at all. The following script also does not work trying to delete `test-1,test-2` as single index 

```
PUT test-1
PUT test-2
POST _aliases
{
  "actions": [{
    "remove_index": {
      "index": "test-1,test-2"
    }
  }]
}
```

**Comment by lipsill** [comment]
I had a look at this and the issue seems to be that `_aliases` support two separate fields `index` and `indices`. If an `index` is provided, ES will take the expression as is (without splitting it by `,`), and then try to resolve it. Hence ES cannot find the expression `test-*,-test-1`. 
If `"index":"test-*"` is provided, both `test-1` and `test-2` are deleted. If you want to delete only `test-2`, please use `"indices" : ["test-*", "-test-1"]` 

To delete `test-2` using `_aliases` endpoint
```
POST _aliases
{
  "actions": [{
    "remove_index": {
      "indices": ["test-*", "-test-1"]
    }
  }]
}
```
To delete `test-1` and `test-2`
```
POST _aliases
{
  "actions": [{
    "remove_index": {
      "index": "test-*"
    }
  }]
}
```
```
POST _aliases
{
  "actions": [{
    "remove_index": {
      "index": "test-*,-test-1"
    }
  }]
}
```
results in 
```
"type" : "index_not_found_exception",
"reason" : "no such index",
"resource.type" : "index_or_alias",
"resource.id" : "test-*,-test-1",
```

This difference is also documented in [Multiple Indices](https://www.elastic.co/guide/en/elasticsearch/reference/master/multi-index.html) Note
> Single index APIs such as the Document APIs and the single-index alias APIs do not support multiple indices.

@exe-dealer @colings86 I *think* that `_aliases` works as documented. 

Another option is to change the alias API
- split the `index` by comma - this will align it with the other APIs that support multiple indices
- split the `index` by comma and deprecate `indices` to avoid any further confusion

**Comment by exe-dealer** [comment]
I would never guess that "indices" accepts wildcards and even negation. 
`"indices": ["test-*", "-test-1"]` solves my problem, thank you @lipsill
