### ISSUE TITLE
Watcher: Scripting does not allow use of DateTime objects anymore

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#35913]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.5.1

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

```
POST _xpack/watcher/watch/_execute
{
  "watch": {
    "trigger": {
      "schedule": {
        "interval": "10s"
      }
    },
    "input": {
      "none": {}
    },
    "transform": {
      "script": {
        "source": "return [ 'time_scheduled': ctx.trigger.scheduled_time.getMillis() ]",
        "lang": "painless"
      }
    },
    "actions": {
      "logging": {
        "logging": {
          "text": "{{ctx.payload}}"
        }
      }
    }
  }
}
```

Returns

```
"script" : "return [ 'time_scheduled': ctx.trigger.scheduled_time.getMillis() ]",
  "lang" : "painless",
  "caused_by" : {
    "type" : "illegal_argument_exception",
    "reason" : "dynamic method [org.joda.time.DateTime, getMillis/0] not found"
}
```

I think the reason for this is, that we do not expose `org.joda.time.DateTime` in scripting anymore, only, correct @rjernst ?

I think the proper solution is to convert the DateTime objects in the watch context to joda compatible zoned date times in the next patch release.

**Comment by rjernst** [comment]
First reported in https://discuss.elastic.co/t/ctx-execution-time-getmillis-no-longer-works-with-elasticsearch-6-5-0/157788/2

Yes, the reason is DateTime was removed from the whitelist. I did not realize there were other places exposing joda objects in scripts. I will start with a fix to add it back to the whitelist, then followup with fixing watcher to expose the date as the same joda compatible object doc values use.
