### ISSUE TITLE
Expose MultiPhraseQuery via rest api

### ISSUE THREAD

**Issue by omrivm** [elastic/elasticsearch#35977]
Following this discussion: https://discuss.elastic.co/t/multiphrasequery-in-elastic-using-nest/157218/3
Lucene's MultiPhraseQuery is a powerful query type and it is not exposed via elastic's rest api.

**Comment by jimczi** [comment]
We discussed this internally and we've agreed that we don't want/need to support this query. It is an expert query that is used internally to resolve phrase queries with synonyms or phrase prefix queries but otherwise you should be able to use a mixed of `span_or` and `span_near` queries to perform the same. MultiPhraseQuery and spans should also be similar in terms of scoring and we don't have strong evidence that shows that a MultiPhraseQuery is faster.

**Comment by omrivm** [comment]
AFAIK, span_or (which is the closest alternative) calculate scoring similar to boolean query – that means that the score of this function will be the sum the spans score and MultiPhraseQuery uses dismax. 
This is a big difference in scoring and can dramatically impact the quality of the search results.
