### ISSUE TITLE
Replace manual index checks with Objects.check*Index

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#36108]
In a number of places we either don't perform bound checks or perform them manually, see eg. https://github.com/elastic/elasticsearch/blob/237650e9c054149fd08213b38a81a3666c1868e5/server/src/main/java/org/elasticsearch/common/bytes/ByteBufferReference.java#L58-L62.

This could be replaced with `Objects#checkFromIndexSize`, which has a number of benefits that @uschindler nicely summarized at https://issues.apache.org/jira/browse/LUCENE-7966?focusedCommentId=16162647&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16162647. It also tends to be less lenient, for instance you wouldn't get any exception in the code above if `from+length` happens to overflow, while `Objects#checkFromIndexSize` would detect it.

These bound checks are only available in Java 9 onwards but Lucene already did the work of making those available in Java 8 as well (just not as intrinsics) via the `org.apache.lucene.util.FutureObjects` class. Calls to methods of this class are effectively replaced with calls to `java.util.Objects` if you are running Java 9 or newer.

**Comment by uschindler** [comment]
Are you planning to add the ClassRewriter groovy code to elastic, so you can do the same FutureObjects->Objects replacements in Elasticsearch, too?

I haven't seen any code yet.

**Comment by uschindler** [comment]
It should work easily, because Elasticsearch already builds an MR-JAR for the "server" code. So running the above rewriter on the Java 8 class files using FutureObjects/Arrays and storing the rewritten result in the java9 classes dir should be easy. It would not interfere with the current MR-JAR code in build.gradle.

**Comment by jpountz** [comment]
We discussed this issue in FixitFriday and agreed that this move would be a win. However some concerns have been expressed regarding patching class files so we might want to build a MR JAR that exposes this functionality (similarly to the first patches on the Lucene issue) instead of the Lucene approach of patching call sites.

**Comment by uschindler** [comment]
Thanks @jpountz, 
I am fine with any solution. It would just be interesting what the concerns were. To me it has been always something from "I am just afraid to patch classfiles" to "how to test"?

As disussed in the Lucene issue: Especially about optimization of duplicate checkIndex checks on different levels in the call stack, the additional overhead brings the risk that optimzer cannot replace everything with native code and may also not able to remove the duplicate checks.

About the risks: Patching class files is harmless here if you can ensure the following: Signatures are 100% identical. If you reuse the Lucene FutureObjects and FutureArrays classes, this is tested already by the Lucene tests with several checks (I wanted to add more). Using a different approach to build the MR-JAR in ES would also not add any safety, because if the Lucene approach would be broken, it would break ES anyways. It's now tested in several releases, no problems.

In contrast, if you add a new layer of indirection with 2 different source trees, the risk of bugs is much higher. Because you have to be 100% sure that both of your source trees compile to the same method signatures! If you reuse the already tested Lucene approach, the risk is zero.

The only backside with patching the caller code is a larger JAR file: Every class that uses FutureObjects/FutureArrays is duplicated in the JAR file while a single wrapper class does not blow up. But on Lucene it has shown that JAR file only growed minimally (around 10%). Of course this depends on number of usages.

So I tend to use the same approach. I can help in moving the pater groovy code as a Gradle Task (that's quite easy). It can then be added easily.

**Comment by jpountz** [comment]
@uschindler I think the concern is mostly that some of the class files that we would package would no longer be directly produced by the compiler. We are not too concerned with getting worse performance, the main benefit that we are looking for is correctness. I agree that both approaches have risks, just different ones. :)

**Comment by uschindler** [comment]
The class files created by painless are also not coming from the compiler...

As said before, correctness cannot be ensured by the separate compile steps, because the output of the real compiler can still be incompatible. That's what I wanted to say.

Nevertheless, I'm happy to help.

**Comment by pugnascotia** [comment]
Closed in #46953.
