### ISSUE TITLE
Tasks: Create Internal Tasks User

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#36282]
As a follow up to #35667 I'd like to create an internal tasks user so tasks don't have to use the `XPackUser` that has permission for a ton of stuff. I'm already working on a first step for this but I wanted to create this to make sure that it doesn't fall through the cracks.

**Comment by henningandersen** [comment]
@nik9000 do you still want to provide a change for this?

**Comment by tlrx** [comment]
We discussed this is small group today and we think this issue is now obsolete now we have a system user for internal action.

I'm going to close this as part of our spring cleaning duty but feel free to reopen if our assumption is wrong.

**Comment by tvernum** [comment]
This might not be a priority, but I don't think we've made any changes that would resolve this issue since @nik9000 raised it.
See: https://github.com/elastic/elasticsearch/blob/44fa734bbd60a571dfa49d8e80440df9fc85e105/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/AuthorizationUtils.java#L141-L142

**Comment by tlrx** [comment]
Thanks for the precision Tim. I'm tempted to leave this issue closed given it received very small attention in the last 4 years.
