### ISSUE TITLE
Upgrading from 6.1.2 to 6.5.1 indexing performance drop 40%

### ISSUE THREAD

**Issue by luann-trend** [elastic/elasticsearch#36338]
**Elasticsearch version** (`bin/elasticsearch --version`):

6.5.1

**Plugins installed**: []

repository-gcs

and disable all x-pack features

xpack.security.enabled: false
xpack.watcher.enabled: false
xpack.ml.enabled: false
xpack.monitoring.enabled: false
xpack.graph.enabled: false
xpack.rollup.enabled: false
xpack.logstash.enabled: false

**JVM version** (`java -version`):
Using docker image from docker.elastic.co/elasticsearch/elasticsearch:6.5.1

**OS version** (`uname -a` if on a Unix-like system):
Using docker image, uname -a give this info

Linux es-data-hot-0 4.14.56+ #1 SMP Sat Aug 11 23:13:59 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

Index performance drop significant when upgrading from ES 6.1.2 to 6.5.1

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 Running the indexing performance test with the following setup 

- Elasticsearch cluster with 10 hot data nodes and 3 warm nodes, 1 replica, 10 shards, container start with 32G of memory
- Each hot node is individual VM with "High memory machine type with 8 vCPUs and 52 GB of memory."
- "settings": {
    "index": {
      "number_of_shards": 10,
      "number_of_replicas": 1,
      "refresh_interval": "60s",
      "routing.allocation.require.box_type": "hot",
      "translog": {
        "durability": "async",
        "sync_interval": "10s",
        "flush_threshold_size": "1gb"
      }
     }
  }

- JVM options:
-Xms24G 
-Xmx24G
-XX:+UseG1GC
-XX:MaxGCPauseMillis=400

The same configuration on 6.1.2 except for JVM 
-Xms24G 
-Xmx24G
-XX:+UseConcMarkSweepGC
-XX:CMSInitiatingOccupancyFraction=75
-XX:+UseCMSInitiatingOccupancyOnly

***Notes: if using the same JVM of 6.1.2 for 6.5.1 the performance get even worst.

Please see ES 6.1.2 vs 6.5.1 Documents Indexed Rates from the graphs

![6 1 2indexingperformance](https://user-images.githubusercontent.com/36053673/49615073-6b84ed00-f97a-11e8-94ec-9e3fecadb8ec.png)

![6 5 1indexingperformance](https://user-images.githubusercontent.com/36053673/49615108-7f305380-f97a-11e8-93a1-8a7551c42cc7.png)

**Comment by synhershko** [comment]
Can you share GC counts and times during the indexing, for both the old and young pools - compared between the versions? we are too seeing some high young gen GC in more recent versions

**Comment by luann-trend** [comment]
I have tried to build our own docker ES image in which uses openjdk:8 to make sure our JVM is at 1.8 with latest elasticsearch 6.5.2 and able to confirm the index performance is the same as old official docker ES image 6.1.2. This is telling me that the index performance issue is caused by switching to the new jdk.

**Comment by luann-trend** [comment]
@danielmitterdorfer From previous performance test with official image 6.5.1 and out of the box JVM config, the performance was even worst. That's why I tried to use the G1GC however I did not follow exact the G1GC default config. I will try the performance test again with default G1GC with the 6.5.1 official Docker file and lets you know the result.

**Comment by danielmitterdorfer** [comment]
>  From previous performance test with official image 6.5.1 and out of the box JVM config, the performance was even worst.

This sounds as if some other component in the JDK affects your performance negatively because you also state in https://github.com/elastic/elasticsearch/issues/36338#issuecomment-445990327:

> I have tried to build our own docker ES image in which uses openjdk:8 to make sure our JVM is at 1.8 with latest elasticsearch 6.5.2 and able to confirm the index performance is the same as old official docker ES image 6.1.2.

So my understanding is that we are talking about these scenarios:

| Version                                          | JDK | GC                                              | Notes                                                                                                            | 
|--------------------------------------------------|-----|-------------------------------------------------|------------------------------------------------------------------------------------------------------------------| 
| Elasticsearch Docker image 6.1.2                 | 8   | CMS (out-of-the-box default for Elasticsearch) | performance ok                                                                                                   | 
| custom Docker image based on Elasticsearch 6.5.1 | 8   | CMS (out-of-the-box defaults for Elasticsearch) | performance ok (as per https://github.com/elastic/elasticsearch/issues/36338#issuecomment-445990327)                                                                              | 
| Elasticsearch Docker image 6.5.1                 | 11  | CMS (out-of-the-box default for Elasticsearch) | performance drop of > 40%? (as per https://github.com/elastic/elasticsearch/issues/36338#issuecomment-451958840) | 
| Elasticsearch Docker image 6.5.1                 | 11  | G1GC with custom options                        | performance drop of roughly 40% (as per https://github.com/elastic/elasticsearch/issues/36338#issue-388421562)  |

**Comment by luann-trend** [comment]
That's correct summary. I have not get the time to try ES docker 6.5.1  JDK 11 with G1GC (out of the box default for ES) yet. Thanks

**Comment by danielmitterdorfer** [comment]
Closing due to lack of feedback. Please feel free to reopen with new feedback. Thank you!
