### ISSUE TITLE
Ordering percentiles aggregation with NaN values ignores the NaN's

### ISSUE THREAD

**Issue by itaydvir** [elastic/elasticsearch#36402]
Ordering percentiles aggregation with NaN values ignores the NaN's

**Elasticsearch version** (`bin/elasticsearch --version`): `2.3.3 (but also tested on 6.2.4)`

**JVM version** (`java -version`): `1.8.0_161`

**OS version** (`uname -a` if on a Unix-like system): `3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:
I have [opened a discussion on elastic forum](https://discuss.elastic.co/t/sorting-percentiles-aggregation-with-nan-values/154462), but no one answered, so i'm assuming it's a bug.

The problem is: When trying to sort a percentiles subaggregation, some bucket might return NaN. and these documents will always be last on both "asc" and "desc" order.
I've tried adding "missing": 0 inside percentiles aggregation but it still returns a NaN.

I would expect that missing field will work on NaN documents so I will have a way to sort those results as well, or at least have a way to handle those values.

**Steps to reproduce**:

Full steps to recreate:
 1. create index with mapping:
```
PUT comments
{
    "mappings" : {
        "comment" : {
            "properties" : {
                "location_i" : { "type" : "integer" },
                "type_i" : { "type" : "integer" },
                "duration" : { "type" : "integer" }
            }
        }
    }
}
```
 2. add 2 docs:
```
PUT comments/comment/1
{
  "location_i": 1,
  "type_i": 1,
  "duration": 100
}
PUT comments/comment/2
{
  "location_i": 2,
  "type_i": 2,
  "duration": 50
}
```
 3. run the query:
```
POST comments/_search
{
  "size": 0, 
  "query": { "match_all": {}},
  "aggs": {
    "locations": {
      "terms": {
        "field": "location_i",
        "size": 10,
        "order": [
		{
			"onlyTypeOne>medianDuration.50": "asc"
		}
	]
      },
      "aggs": {
        "onlyTypeOne": {
          "filter": {
            "term": {
              "type_i": 1
            }
          },
          "aggs": {
            "medianDuration": {
              "percentiles": {
                "field": "duration",
                "percents": [50],
                "missing": 0
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by polyfractal** [comment]
The reason `missing` doesn't work is because that only fills in values when a document is missing the particular field.  In this case, there are no documents in the bucket so there is nothing `missing` could be applied to.  The `NaN` that is being returned by the percentiles is basically an "empty result" (no values collected, so we can't calculate a percentile, so it's not-a-number.  In 7.0 it'll be a `null` in the JSON, but same idea).

It appears that `NaN`s are [explicitly ignored in the sub-agg comparator](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/TermsAggregator.java#L273-L275).  @colings86 looks like you reviewed the PR that added this functionality (waaaaay long ago), do you happen to remember if there's a reason for always pushing `NaN`s to the bottom?  Or was it just the way it's implemented and no particular reason?

Another approach could be using `bucket_sort` to do the sorting post-hoc, but it appears that `bucket_sort` strips out empty sort values so you end up removing the `NaN` bucket... :(

**Comment by colings86** [comment]
There is no technical reason for sorting the NaN values last but they need to be sorted to some position and I think last makes the most sense to me since if you are sorting buckets by a particular metric having the buckets with no value go to the end seems more convenient then having them sort to the beginning where they will get in the value of the value that most users are likely to want first. 

I am happy to change this so that adjusting the sort order surfaces these values to the top but I would strongly prefer that NaNs are sorted last when sort order is "desc" (the default) and I am also a little concerned that changing this may not be favourable to other use cases so it might be worth trying to solicit more feedback both for and against changing this before we proceed

**Comment by itaydvir** [comment]
@colings86 @polyfractal - after your comments and link to comparator source code, I realized your solution is the correct one. since we have no data, it will be wrong to sort them, and yes, changing it might cause problems (even to me) because actual results might not show up because the NaN's pushed them outside the result size limit.

Thank you for your time & clarification, and sorry for opening a bug which is not a bug.
Best,
Itay

**Comment by colings86** [comment]
> Thank you for your time & clarification, and sorry for opening a bug which is not a bug.

I think this was an important discussion to have to check that we are taking the right approach on this situation so please don't feel bad for opening this issue, I think it was great to have this discussion

**Comment by polyfractal** [comment]
Agreed, it's good to discuss behaviors like this since they very well could be bugs :)

I suspect we'll still want to fix how the `bucket_sort` behaves... it feels odd that trying to sort buckets will also have the side-effect of removing "empty" buckets.  And including `NaN` in the `bucket_sort` comparison feels like the correct thing to do, since the goal of the pipeline agg is to sort the final list of buckets.

I'll open an issue so we can track that particular bug/oddity.  Going to close this issue now if that's OK, then link to it from the new issue re: `bucket_sort`

Thanks all!
