### ISSUE TITLE
Provide a way to create RefreshListeners at the tip of the Translog

### ISSUE THREAD

**Issue by clandry94** [elastic/elasticsearch#36541]
**Describe the feature**:

Currently, the `addRefreshListener` method in the `IndexShard` class is publicly exposed, but expects to receive a `Translog.Location` and `Consumer` to add a new `RefreshListener`. This is fine in the context of indexation where the `Translog` is readily available, but as a plugin developer there is no way to publicly retrieve the `Translog`, especially when extending an `IndexModule` to react to different state changes of shards such as `void afterIndexShardStarted(IndexShard indexShard)` and `void beforeIndexShardClosed(ShardId shardId, @Nullable IndexShard indexShard, Settings indexSettings)`

I'm proposing one of two changes within the `IndexShard` class:

1) Publicly expose the `Engine` from within `IndexShard`. This used to be the case, but was changed in previous commits a while back. This would allow plugins to grab the `Translog` as well as the last write location and thus build their own `RefreshListeners`. 

-or-

2) Add a new public method within `IndexShard` which would look something like this
```
public void addRefreshListenerAtLatestWriteLocation(Consumer<boolean> listener) {
  Translog.Location latestLocation = getEngine().getTranslogLastWriteLocation();
  addRefreshListener(latestLocation, listener);
}
```
This method would be safer than option 1 since it keeps the `Engine` accessor package private. Since it is read only, I don't think this would introduce any synchronization issues. 

Making either of these changes would enable plugin developers to make use of `RefreshListeners` within a cluster and fulfill a couple of use-cases:
1) Retrieve metrics on refresh rates at a shard level rather than an average of all shard refreshes at an index level. This is nice for those of us that maintain clusters with hundreds of shards and the average refresh rate is not particularly useful for us. 

2) Build plugins that make use of shard level refresh data and perform actions such as application level cache invalidation based on when data on a specific shard is available for search

**Comment by clandry94** [comment]
Thanks for the info @s1monw. I didn't notice that refresh stats are available per shard. I'm guessing that the `IndexShard#refreshStats` are external refreshes? If thats the case, I think that will fulfill my needs and be a cleaner way to do what I'm trying to accomplish. 

Regarding the cache invalidation, I think we are speaking about different things. By cache invalidation, I meant invalidating caches on something external to ES like a web application. For example, larger clusters with a high indexation rate generally need higher refresh intervals for optimal performance (30s to 1m) and minimizing the time between a document being created in the web application and visible for search in ES is tough to do without some sort of signal to know when to bust caches within the web application. This could be done using the `wait_for` flag on indexation, but that amounts to a sad attempt of making ES synchronous and does not scale well. Large, multi-tenant ES clusters might have deterministic routing in ES based on some kind of key, so I've been experimenting with invalidating the web application's caches based on the latest refresh that happened on the shard which maps to the previously mentioned key. 

Does your comment about caching based on refresh callbacks still seem like a bad idea in this case since the cache is external to ES?

**Comment by s1monw** [comment]
>  I didn't notice that refresh stats are available per shard. I'm guessing that the IndexShard#refreshStats are external refreshes? If thats the case, I think that will fulfill my needs and be a cleaner way to do what I'm trying to accomplish.

no these stats are the actual refreshes done on the lower level. I don't think we have stats that are on the outer level. This doesn't mean we can add them

>  This could be done using the wait_for flag on indexation, but that amounts to a sad attempt of making ES synchronous and does not scale well.

I have a question why you think that is is the case. ES will asynchronously wait for the refresh to happen, it's done in an efficient way. your client can also wait without blocking. Maybe you mean you will have a higher latency due to the response is coming back later?

> Does your comment about caching based on refresh callbacks still seem like a bad idea in this case since the cache is external to ES?

I can't say yes or now at this point. I would like to understand your usecase better to give better advice. Can you elaborate on your problem a bit more what the cache is used for?

**Comment by s1monw** [comment]
@clandry94 ping

**Comment by s1monw** [comment]
@clandry94 thanks for the insights. I personally think building cache invalidation based on refreshes will be a very tricky and error prone construct. I would try hard to not go down that path. One thing that I can see being tricky is that whenever you get a callback on a refresh you can't tell if the change is visible on all replicas. This guarantee is different with `wait_for`. If you need to know when to invalidate a cache I would run a refresh manually ahead of the cache invalidation, is this something that you explored? I mean calling occasional refreshes will not have a big impact on ingest performance?

Another options is to set the `wait_for` only on selected indexing requests because once it returns you can be sure that all docs acked before this document will be visible. That way you don't run into issue of making things _synchronous_. not sure if that helps?

**Comment by clandry94** [comment]
> Another options is to set the wait_for only on selected indexing requests because once it returns you can be sure that all docs acked before this document will be visible.

I really like this approach, but we use Kafka to have a resilient indexation pipeline an unfortunately won't work for me. 

On the other hand, 
> If you need to know when to invalidate a cache I would run a refresh manually ahead of the cache invalidation, is this something that you explored? 

I'm going to explore this more. I think it could be a pretty resilient way to invalidate the caches since the cluster will fallback to its original refresh interval if whatever job/system/etc that forces refreshes fails. 

Anyway, thank you for the help! I have a lot of new insight from this discussion. I still think that exposing external refresh stats at a shard level would be useful from a monitoring standpoint. I can take a look at implementing that if you think its worthwhile?

**Comment by clandry94** [comment]
Sure, I'll make a new issue
