### ISSUE TITLE
Automatic config reload

### ISSUE THREAD

**Issue by Erik-Lamers1** [elastic/elasticsearch#36638]
Currently ES needs a full restart whenever elasticsearch.yml is edited. Which is not ideal. Basically it would be a great feature if ES had some option like Logstash now has: https://github.com/elastic/logstash/issues/4513 [docs](https://www.elastic.co/guide/en/logstash/current/reloading-config.html).

**Comment by jasontedor** [comment]
> Which is not ideal.

This requires quite some unpacking to help us understand the request. When listening to a feature request, we also want to hear the *why*; it might be that we are missing something in the experience and having that feedback is important to us.

Pipeline configuration reloading in Logstash is driven by a need that does not apply to Elasticsearch. Namely, it is due to the fact that a common workflow on the configuration of a pipeline in Logstash is iterative in nature. As a user is iterating on their configuration, it is a significantly improved experience to have Logstash automatically pick up these changes. Additionally, changing one pipeline should not require shutting down all pipelines and pipeline configuration reloading gives that.

This does not apply to Elasticsearch though, and there are significant technical reasons why we are unlikely to invest in complete reloading as you propose (e.g., the security manager, we are not going to open ourselves up to the possibility of having to dynamically grant new privileges that we have previously dropped). We make settings dynamic when it makes sense for the them to be.

If you have a specific setting that is not currently dynamic that you think it is onerous to have to restart a cluster to change (frequency is important), we would be happy to hear about it and consider whether or not it can be dynamic.
