### ISSUE TITLE
Search: add "bulk" format 

### ISSUE THREAD

**Issue by fbaligand** [elastic/elasticsearch#36980]
Currently, when we execute a search query, we can specify the `format` query parameter to indicate if the response should be in `json` or `yaml` format.

It would be great to add `bulk` format!
With this format, the response would be in the same format than the [official bulk API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html).

This is particularly interesting to export data and then import this data at any moment in any other cluster.

I know that reindex API provides similar feature, but it works only if "dest" cluster can join "source" cluster, and it implies that export and import are executed at the same moment.

In some companies, production cluster is isolated and cannot join other clusters. Furthermore, you might want to export data at some precise time in "integration" environment and then import data later in production environment.
It is also a nice mean to export some data that you want to share with other people (tutorial, Elastic support, example data, ...)

That's why, adding support for "bulk" format would be great!

**Comment by jimczi** [comment]
We discussed this internally and we agreed that exporting data from a cluster should be doable in a few lines of code with any official language client. You can just move the search hits of the response into a bulk request on the client side exactly like `reindex` would do. The issue with the `bulk` format is that it wouldn't reflect all the informations that are present in a search response (number of hits, aggregations, highlighting, ...). You can also use the snapshot/restore functionality to export an index from one cluster to another. If a full snapshot is too big to transfer from one cluster to another you can also use a [`source-only`]( https://www.elastic.co/guide/en/elasticsearch/reference/6.4/modules-snapshots.html#_source_only_repository) snapshot and then reindex the `_source` in the remote cluster like any local index. For these reasons we don't think that adding a `bulk` format would be really helpful since we have enough alternatives to export data with a few lines of client code.

**Comment by fbaligand** [comment]
Sad to hear this :(
