### ISSUE TITLE
Script processor params not accessible within Painless script function

### ISSUE THREAD

**Issue by ycombinator** [elastic/elasticsearch#36993]
Tested with `master` @ 7580d9d.

I am defining an Ingest pipeline that contains a `script` processor. The script is in Painless. The script defines a function and the function body references the `params` variable. However, it seems like this variable is not in scope.

## Sample pipeline

```json
POST _ingest/pipeline/_simulate
{
  "docs": [],
  "pipeline": {
    "processors": [
      {
        "script": {
          "lang": "painless", 
          "source": """
            void getIndex(def i) { i = params.index; }
            """,
          "params": {
            "index": "foo"
          }
        }
      }
    ]
  }
}
```

### Error
```json
{
  "error": {
    "root_cause": [
      {
        "type": "script_exception",
        "reason": "compile error",
        "processor_type": "script",
        "script_stack": [
          "... id getIndex(def i) { i = params.index; }",
          "                             ^---- HERE"
        ],
        "script": "            void getIndex(def i) { i = params.index; }",
        "lang": "painless"
      }
    ],
    "type": "script_exception",
    "reason": "compile error",
    "processor_type": "script",
    "script_stack": [
      "... id getIndex(def i) { i = params.index; }",
      "                             ^---- HERE"
    ],
    "script": "            void getIndex(def i) { i = params.index; }",
    "lang": "painless",
    "caused_by": {
      "type": "illegal_argument_exception",
      "reason": "Variable [params] is not defined."
    }
  },
  "status": 400
}
```

**Comment by jdconrad** [comment]
@ycombinator Functions aren't well documented currently; however, this behavior is intentional.  Functions in Painless were meant to be independent of the main body, so any variables available as part of the main body would need to be passed into the function to operate correctly.

Example:
```
int test(def params, int value) {return params.update + value;} int i = test(params, 2);
```

The main body in Painless is like a main method in Java where the ```String[] args``` parameter is not a global variable.  It's just the method signature for the main body in Painless is hidden for simplicity for the user.

**Comment by ycombinator** [comment]
Thanks for the explanation @jdconrad.

Sounds like, at minimum, we should document this behavior of functions and variable scope.

> I am open to a behavioral change here if it would be better for the users in the long-term.

I assume there's some downside to changing the behavior to be more ergonomic, which is why it wasn't done to begin with?

**Comment by jdconrad** [comment]
@ycombinator YW! The downside is having any notion of global variables in this way could make changes in the future more difficult since that's a change you can't really take back once it's done do to backcompat, and it doesn't really match the behavior of other similar languages so it could be non-intuitive.

**Comment by ycombinator** [comment]
Gotcha. I don't think there's any particular rush to change the behavior then. If this starts to become a major issue for lots of users, perhaps we can consider it then.

For now, I'd be happy with adding docs; that alone will save time and confusion for users. Thanks!

**Comment by ike-mowgli-mor** [comment]
If anyone was wondering - params are passed by reference

**Comment by jdconrad** [comment]
I don't think there should be a behavioral change here. Closing.
