### ISSUE TITLE
SQL: could support SUM(IF(KPI='1',Number_Value,0))

### ISSUE THREAD

**Issue by ighack** [elastic/elasticsearch#37133]
Elasticsearch version:6.5.4

we can use SUM(IF(KPI='1',Number_Value,0)) in mysql.
I want to know how can I use that in elasticsearch-sql?

select sum(Number_Value) - 1 as 件数 from operator_warehouse_data where KPI='件数'
I get a error.

> {
>   "error": {
>     "root_cause": [
>       {
>         "type": "parsing_exception",
>         "reason": "line 1:33: no viable alternative at input '件'"
>       }
>     ],
>     "type": "parsing_exception",
>     "reason": "line 1:33: no viable alternative at input '件'",
>     "caused_by": {
>       "type": "no_viable_alt_exception",
>       "reason": null
>     }
>   },
>   "status": 400
> }

Alias can not be chinese

**Comment by ighack** [comment]
```
{
	"size": 0,
	"query": {
		"bool": {
			"filter": []
		}
	},
	"aggregations": {
		"14bb868d": {
			"filter": {
				"bool": {
					"must": [
						{
							"term": {
								"KPI": "条目数"
							}
						}
					]
				}
			},
			"aggregations": {
				"agg_value": {
					"sum": {
						"field": "Number_Value"
					}
				}
			}
		},
		"f1a4e828": {
			"filter": {
				"bool": {
					"must": [
						{
							"term": {
								"KPI": "件数"
							}
						}
					]
				}
			},
			"aggregations": {
				"agg_value": {
					"sum": {
						"field": "Number_Value"
					}
				}
			}
		}
	}
}
```
I want translate this to SQL

**Comment by astefan** [comment]
@ighack `SUM(IF(KPI='1',Number_Value,0))` is not currently supported in ES-SQL and it's not on our near roadmap.

Regarding the `no viable alternative at input` error you get, this is because you need to escape those characters with double quotes: `select sum(Number_Value) - 1 as "件数" from operator_warehouse_data where KPI='件数'`.

Also, while we appreciate the feedback provided in this issue, github is reserved for confirmed bugs or enhancement requests and your questions would have been better handled in our [forum](https://discuss.elastic.co/). Thank you for your understanding.

**Comment by astefan** [comment]
For your reference, I've created [this feature request](https://github.com/elastic/elasticsearch/issues/37271) for conditional scripted metrics support.
