### ISSUE TITLE
Allow MIN/MAX aggregation over keyword fields

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#37198]
Currently, MIN and MAX work on numeric-like values, not just values but also dates and IPs.
It would be nice to extend these aggs to support keywords as well and return the first/last value based on lexical order.

**Comment by vivekprm** [comment]
Would like to work on it.

**Comment by polyfractal** [comment]
A note for anyone working or thinking about working on this.  It's not clear if we should extend the existing min/max aggs, or create a new set of aggs (`min_keyword` or similar).  Ordering by keyword might have need some additional parameters, like are special characters included?  Is it alpha-numeric or just alpha?  Should the order be scripted/configurable somehow?  etc.

It'll also likely need a different internal implementation since it needs to return a string rather than a double.

**Comment by f3l1xss** [comment]
Guys, has there been any progress on this? AFAIK we can't currently perform any metric aggregation on keyword field and then use the result for sorting. I have tried using scripted metric aggregation to produce string result but in the end unable to use that result for sorting.

**Comment by costin** [comment]
Actually this has been resolved a few versions back - see the docs at:
https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-functions-aggs.html#sql-functions-aggs-max

**Comment by f3l1xss** [comment]
> Actually this has been resolved a few versions back - see the docs at:
> https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-functions-aggs.html#sql-functions-aggs-max
> 
> Essentially instead of extending MAX or MIN, SQL rewrite them into LAST/FIRST aggregations. There is a downside unfortunately which is that it cannot be used for filtering (`HAVING` clause).

Does it mean that instead of using term aggregation, I would have to use the sql equivalent? (Group by). We are currently using AWS elastic search and AFAIK they dont support XPack. Would there be any other out of the box solution to sort term bucket based on keyword field?

**Comment by polyfractal** [comment]
@f3l1xss Could you describe the type of sort you're wanting to perform?  E.g. `terms` agg on one keyword field, but sort based on a different keyword field?

The [`bucket_sort` pipeline agg](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline-bucket-sort-aggregation.html) may provide the functionality you need, by sorting the buckets on the coordinating node.  It's not quite the same as sorting on the shard, but sorting by sub-aggregations is dodgy in general due to accuracy issues (see [warning in docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-order))

**Comment by f3l1xss** [comment]
> @f3l1xss Could you describe the type of sort you're wanting to perform? E.g. `terms` agg on one keyword field, but sort based on a different keyword field?
> 
> The [`bucket_sort` pipeline agg](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline-bucket-sort-aggregation.html) may provide the functionality you need, by sorting the buckets on the coordinating node. It's not quite the same as sorting on the shard, but sorting by sub-aggregations is dodgy in general due to accuracy issues (see [warning in docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-order))

Hi @polyfractal Thank you for your reply.
What I would like to do is to use terms agg on numeric field but sort the buckets by keyword field as described here: https://stackoverflow.com/questions/59752351/how-to-perform-metric-aggregation-on-keyword-field

Now I understand that it doesnt make sense to sort by single keyword field since each terms bucket could have one(or many) doc count with different keyword field value. However, since in my use case I can be sure that each terms bucket would return documents with the same keyword field value, I can simply pick any documents and get its keyword field value.

So far, I've come up with scripted metric aggs to simply pick keyword field value from any doc and then trying to sort terms buckets using this scripted metric aggs result but found out that sorting using scripted metric aggs value is not supported.

**Comment by aniezurawski** [comment]
> @f3l1xss Could you describe the type of sort you're wanting to perform? E.g. `terms` agg on one keyword field, but sort based on a different keyword field?

Hi. This is exactly what I need. I have a `terms` agg on field A and I want to sort buckets by max/min sub aggregation on field B. Where B is a keyword, not a number. Is it possible to achieve?

**Comment by gkozyryatskyy** [comment]
Hello guys!
I read whole the issue, but still does not understand how can I use min\max aggregation for `keyword` field and next use this result to bucket sorting.. Can you please help me understand?

@costin What aggregation should I use for first\last results? None of the single bucket (metrics) aggregations are providing this https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics.html or I missing something?

@polyfractal How `bucket_sort` aggregation can help me? Here is some problems with it
 1. It is sorting just resulted buckets. From the docs https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline-bucket-sort-aggregation.html#search-aggregations-pipeline-bucket-sort-aggregation `if the parent aggregation is terms and its size is set to 10, the bucket_sort will only sort over those 10 returned term buckets.`.
 2. it is still requires other aggregation path, to sort with. And looks like 'other' aggregation cant point to `keyword` field.

@f3l1xss @aniezurawski did you achieve somehow `terms` bucket sorting sorting based on other `keyword` field?

I will be very grateful for any help!

**Comment by aosrc** [comment]
> > @f3l1xss Could you describe the type of sort you're wanting to perform? E.g. `terms` agg on one keyword field, but sort based on a different keyword field?
> > The [`bucket_sort` pipeline agg](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline-bucket-sort-aggregation.html) may provide the functionality you need, by sorting the buckets on the coordinating node. It's not quite the same as sorting on the shard, but sorting by sub-aggregations is dodgy in general due to accuracy issues (see [warning in docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-order))
> 
> Hi @polyfractal Thank you for your reply. What I would like to do is to use terms agg on numeric field but sort the buckets by keyword field as described here: https://stackoverflow.com/questions/59752351/how-to-perform-metric-aggregation-on-keyword-field
> 
> Now I understand that it doesnt make sense to sort by single keyword field since each terms bucket could have one(or many) doc count with different keyword field value. However, since in my use case I can be sure that each terms bucket would return documents with the same keyword field value, I can simply pick any documents and get its keyword field value.
> 
> So far, I've come up with scripted metric aggs to simply pick keyword field value from any doc and then trying to sort terms buckets using this scripted metric aggs result but found out that sorting using scripted metric aggs value is not supported.
> 
> Regarding Bucket sort, if you look at the example in the link, SUM of price is being used as the metric aggregation which supports only numeric field. I simply would need metric aggregation like that for keyword field (can be mix/max, doesnt matter as I can get the keyword field value from any docs)

@f3l1xss Hi, I got the same problem like yours, could you please tell me how you finally resolve the problem?
