### ISSUE TITLE
Remote _reindex don´t transfer all original data from indices

### ISSUE THREAD

**Issue by Grashee** [elastic/elasticsearch#37219]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.5.1

**Plugins installed**: [no plugins installed]

**JVM version** (`java -version`):
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

**OS version** (`uname -a` if on a Unix-like system): Linux (CentOs) (and on the other server, which receives the data Windows 7)

**Description of the problem including expected versus actual behavior**:
I want to transfer the data from my first server (Linux-Server) to my second server (which runs on windows 7). But _reindex command don´t transfer all the data which I should receive. 

I also created a post in the elastic forum, but the elastic team members have no idea what the problem is. As reference to my post look here: https://discuss.elastic.co/t/how-to-transfer-index-from-1-node-to-a-different-node/162917

**Steps to reproduce**:

 1. Add both servers to there reindex.remote.whitelist
 2. Run _reindex?wait_for_completion=false command 
```
POST {
  "source" : {
     "remote":{
        "host" : "hostaddress"
      }, 
      "index": "myremoteindex-2018.12.*"
  }, 
  "dest" : {
    "index": "mylocalindex-2018.12"
  }
}
```
 3. Wait for transfer (but not all the data is transferred

**Provide logs (if relevant)**:
Please look into my post at the elastic forum.

**Comment by jakelandis** [comment]
@Grashee - I am going to close this Github issue in favor of the discuss post you reference. The latest comment over there suggests that your remote cluster is rejecting the search requests. I believe your issue is local to your deployment and Github is for issues with Elasticsearch itself. 

If you believe that there is an issue with Elasticsearch please re-open and add relevant logs.
