### ISSUE TITLE
centos6.5 use elasticsearch can't start falied

### ISSUE THREAD

**Issue by zhizhi555555** [elastic/elasticsearch#37252]
env: centOS 6.5  sonar7.5   os:X64
 Hi 
    I use sonarqube-7.5 deploy on my machine,it contains the elasticsearch component, while I run the command sonar.sh start ,there have below issues, and I have try to solve it after edit the elasticSearch.yml, but also can't solved current issue. 

error.log

![image](https://user-images.githubusercontent.com/7861163/50887276-bdafa700-142d-11e9-9bb0-3a2b6baf8cbc.png)

I edit the elasticSearch.yml
 bootstrap.memory_lock: false
 bootstrap.system_call_filter: false
also cant' solved the issue.

**Comment by zhizhi555555** [comment]
> env: centOS 6.5 sonar7.5 os:X64
> Hi
> I use sonarqube-7.5 deploy on my machine,it contains the elasticsearch component, while I run the command sonar.sh start ,there have below issues, and I have try to solve it after edit the elasticSearch.yml, but also can't solved current issue.
> 
> error.log
> 
> ![image](https://user-images.githubusercontent.com/7861163/50887276-bdafa700-142d-11e9-9bb0-3a2b6baf8cbc.png)
> 
> I edit the elasticSearch.yml
> bootstrap.memory_lock: false
> bootstrap.system_call_filter: false
> also cant' solved the issue.
elastichSearch.yml like below
![image](https://user-images.githubusercontent.com/7861163/50887364-f2bbf980-142d-11e9-91b8-a2bebfe620a8.png)

**Comment by matriv** [comment]
Hello @zhizhi555555,

The configuration under `<sonarqube-dir>/elasticsearch/config` is not used for the elasticsearch that sonarqube runs. If you check out the `<sonarqube-dir>/temp/conf/es/elasticsearch.yml` you will see which is the actual configuration that is picked up. As far as I see you cannot edit this file since on every restart is overriden, and sonarqube says you can edit only some specific settings for elasticsearch in the `sonarqube-dir/conf/sonar.properties` file but it uses different names for them (e.g.: `sonar.search.httpPort` instead of es' `http.port`.

You would need to ask help from sonarqube on how to change the settings of their underlying elasticsearch.

Since this is not an issue with Elasticsearch itself I hope you don’t mind if I close this issue.
