### ISSUE TITLE
Add to index_stats the sum of all index/delete operations as a reliable metric for index processing load 

### ISSUE THREAD

**Issue by yaronp68** [elastic/elasticsearch#37260]
**Feature description**:
Add to index_stats the sum of all translog operations as a reliable metric for index processing load 

**Feature value**:
Having this metric reported at the index level will help users trace how active their index is during a period of time. This measure is reliable as it includes all type of changes processed

**Comment by yaronp68** [comment]
@jakelandis - I guess this satisfies the need, I didn't see this metric in the monitoring index and hence I have requested it. But is see it now in the documentation

**Comment by ywelsch** [comment]
@jakelandis `indices.foo.primaries.translog.operations` gives you the number of operations that are currently held in the translog. What @yaronp68 was after (maybe not clear from the request here) is the total number of operations that have made it into the shards of this index (which is based on the max sequence number or global checkpoints of the shards, depending on whether you're interested in the fully completed operations or those that might still be in the process of being replicated). The word "translog" is perhaps a bit misleading here, given that these operations are not retained forever in the translog.

This new metric would be probably closest to `index_stats.primaries.indexing.index_total + index_stats.primaries.indexing.delete_total`, but those metrics are volatile (i.e. reset to 0 when the node with the primary is restarted or goes to an incomparable value when primary relocates or fails and a replica is promoted as primary). Finally, to get the stats at the index (instead of shard level) it is just summing up the individual measures, so if individual values can erratically change, the overall sum is pretty meaningless.

The new metric (something like `changes_total`) would be based on the max sequence number, local checkpoint, or global checkpoint, which represent a measure of change on a shard (i.e. how many successful operations, whether index or delete, where done against the shard). This metric is also persisted and directly based on the data in the shard. We can even lift this to the index level (currently only available at the shard level in the stats, but we could sum up these values to get a measure of “changes_count” at the index-level).

**Comment by dakrone** [comment]
Internal monitoring has been deprecated for quite a while, and we're no longer doing any active development on it. I'm going to close this issue.
