### ISSUE TITLE
Disable SslNullCipher tests

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#37403]
JDK11.0.2 and JDK12 [remove support for NULL and anon ciphers](https://bugs.openjdk.java.net/browse/JDK-8212823) for TLS. 

Do we need to support NULL ciphers for TLS on the transport layer (offers authentication and integrity but no confidentiality) ? If not, we can adjust documentation and remove `SslNullCipherTests`. Otherwise we should conditionally run the tests for JDK versions < 11.0.2

**Comment by jaymode** [comment]
> Do we need to support NULL ciphers for TLS on the transport layer (offers authentication and integrity but no confidentiality) ?

I think we should just delete the test to be honest. It was added when we made TLS required, since some users may not want encrypted transport because they're monitoring all the traffic. I don't think we need tests for specific ciphers; we know our defaults work and we expect that others should work based on the JDK.
