### ISSUE TITLE
achieve unlimited bucket size aggregation

### ISSUE THREAD

**Issue by jehutywong** [elastic/elasticsearch#37598]
#27447 
I am also facing the issue above, a limit on buckets number not seem to be an acceptable solution. Is there a way to achieve an unlimited bucket size aggregation, if i can accept a very long time running time?

**Comment by polyfractal** [comment]
If you need _all_ the buckets of an aggregation, you can use the [composite aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-composite-aggregation.html).  That allows "paging" over the results of an aggregation in a memory-friendly manner.

We can't allow unlimited buckets for non-composite aggregations because they have to store their working state in-memory...and "unlimited" is a very large number :)  Composite agg works around this by breaking the agg up over multiple requests (one per "page") and having the client buffer the information client-side. 

Also in the future, please open questions like this on the [discuss forums](https://discuss.elastic.co/c/elasticsearch).  We try to keep the github issues for things like bug reports.  Thanks!

**Comment by jehutywong** [comment]
Thanks for your advice @polyfractal, i have tried composite aggregation but facing this failure prompt:
“The first aggregation in buckets_path must be a multi-bucket aggregation”

I think my problem now is linked to this one #32692

**Comment by polyfractal** [comment]
Yeah, pipeline aggs don't work with composite right now.  But do note that pipeline aggs are all operations that can be done client-side, so you could re-implement that functionality in your application (until we support pipelines + composite)
