### ISSUE TITLE
esplugin to expose plugin build_hash in descriptor file

### ISSUE THREAD

**Issue by lukas-vlcek** [elastic/elasticsearch#37605]
When using **esplugin** the descriptor file is generated automatically (and that is very nice). It would be useful if build_hash was exposed in the descriptor file as well. It can be useful information for both the plugin authors and users. Of course it would make sense to expose this information in relevant ES rest API too.

**Comment by polyfractal** [comment]
At least on the REST side, you can get that from the base cluster info endpoint:

```
curl -XGET "http://localhost:9200/?pretty" -H 'Content-Type: application/json' 
{
  "name" : "node-162",
  "cluster_name" : "distribution_run",
  "cluster_uuid" : "LcoYII9iQnWzrnnyPga4IQ",
  "version" : {
    "number" : "6.7.0",
    "build_flavor" : "default",
    "build_type" : "zip",
    "build_hash" : "6205a9c",
    "build_date" : "2019-01-07T20:42:09.546844Z",
    "build_snapshot" : true,
    "lucene_version" : "7.6.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by rjernst** [comment]
The build hash is already part of the plugin's jar file (this is how we get it for the main rest endpoint  @polyfractal mentioned above). I think it would be out of place in the plugin descriptor, as it is something constantly changing, while the descriptor can still be (and is) written by hand.

I'm also unsure of including it in any api. The key name used within the jar manifest is not part of any standard. We only rely on it for the main rest api because we build the elasticsearch jar ourselves, so we can trust and test what keys to expect and output.

**Comment by rjernst** [comment]
@lukas-vlcek Yes, the `esplugin` gradle plugin generates the descriptor. However, it is not required to use that (or gradle) to build an Elasticsearch plugin. Many plugin authors have a static plugin descriptor in their codebase.

While I disagree with adding this, I will mark it for discussion with the broader team.

**Comment by lukas-vlcek** [comment]
@rjernst Anything that can be done to improve life of 3rd party plugin authors and users is welcome. Trust me.

**Comment by atorok** [comment]
We discussed this with the team. Since the information is already present in jar metadata, we wouldn't want to maintain it in an additional location. We are considering solutions to reduce the use of the build hash and other changing information in general to be able to make better use of the [Gradle build cache](https://docs.gradle.org/4.10/userguide/build_cache.html) , so this change would go against the general direction we want to move to.

**Comment by lukas-vlcek** [comment]
@atorok Since which version of ES is the build_hash part of jar metadata? I was able to find it in ES 6.x plugin but not in ES 5.x.
Anyway, thanks.
