### ISSUE TITLE
Be more lenient when remotely hosted SAML IdP metadata is unavailable

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#37608]
Currently, if Elasticsearch is configured for SAML but can't fetch the metadata, it bails because it can't authenticate users. However, it might still be possible to authenticate users via another realm (native, LDAP, etc).

Would it be possible to be more lenient or resilient here? Perhaps disable the realm and poll for metadata in the background?

**Comment by tvernum** [comment]
This isn't really something that Elasticsearch can do anything about.
If Kibana is specifically requesting a SAML login, then that's what ES does - it doesn't have a username or password to authenticate with, it just has a request from Kibana to initiate SAML authentication.

I think this needs to be driven as a Kibana issue to provide a choice of login methods (either always, or if SAML is unavailable).
If Kibana needs additional features/APIs from ES to support that then we can build them, but this issue is not solvable by ES.

**Comment by tvernum** [comment]
Ah, I see this is specifically about starting the node if the URL is unavailable.
I'm hesitant to do that - it means we will (fairly quietly) accept an incorrect configuration and leave the admin to work out why things are broken.

I understand that is makes node start up fragile, but it's impossible for us to reliably know whether the URL is _wrong_ or just not currently available.  This is why the ES docs encourage local metadata files rather than fetching from a URL - it is a much more reliable option.

**Comment by jkakavas** [comment]
I think we should do this. The `HttpMetadataResolver` can keep on attempting to get metadata every `refresh` interval, until the URL (and thus the SAML realm in Elasticsearch) is available 

> it means we will (fairly quietly) accept an incorrect configuration 

It's true, but isn't this the case also for LDAP, AD realms? We validate neither that we can reach the ldap URL, nor that the bind credentials are correct when provided. We just fail authentication attempts against this realm until the configuration is fixed. 

> and leave the admin to work out why things are broken.

we should of course print a  `WARN` on startup and an appropriate error message on authentication failure

>  This is why the ES docs encourage local metadata files rather than fetching from a URL - it is a much more reliable option.

No matter what we decide, that is a valid point - I brought it up with @pugnascotia also when we first discussed the issue.

**Comment by tvernum** [comment]
> It's true, but isn't this the case also for LDAP, AD realms? We validate neither that we can reach the ldap URL, nor that the bind credentials are correct when provided

True, although I think this case might be more likely.

I'm happy to go ahead with this. I do think it will bite some users, but it will also benefit other users. Realistically, anyone who _can_ should use a local file for the metadata and sync it from the remote source as needed.
That's harder to do well in a container/immutable environment, so I'm happy to change this behaviour to target the needs of those users.

**Comment by zez3** [comment]
I also hit this and think that it should nicely fail instead of majestically error out.
In my case state that the saml configuration is valid, worked and was not changed. It's the dns resolution that failed :expressionless: 
I know we should not be depend on network but still this should nicely fail and not bring the whole cluster down.

**Comment by zez3** [comment]
What I am saying is that things in general break or are taken offline for updates(dns resolutions, networks, etc.) and we should not depend on them exclusively. The ES cluster should still stand during such an event and allow admins or locally define users to authenticate.
I see this as a bug, Can we please tag it accordingly?

**Comment by tvernum** [comment]
> I see this as a bug, Can we please tag it accordingly?

Tagging this as a bug won't change the priority - we're not consciously refusing to make this change, it's simply more complex than it sounds, and it hasn't been a high enough priority relative to other work.

I don't agree that it's a bug. It a conscious design choice that doesn't suit everyone's needs, but arguing about that classification won't increase (or decrease) the likelihood of it being changed.

If someone submits a PR that resolves the problem in an acceptable way, then we would merge it. Otherwise it's subject to priorities, like every other change is.

**Comment by zez3** [comment]
I see.
But you agree that the local user auth realm should work regardless of the of the saml/oidc/ldap etc. server reach?

**Comment by zez3** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/file-realm.html
"
The file realm is very useful as a fallback or recovery realm. For example in cases where the cluster is unresponsive or the security index is unavailable, or when you forget the password for your administrative users. In this type of scenario, the file realm is a convenient way out - you can define a new admin user in the file realm and use it to log in and reset the credentials of all other users.
"
Otherwise why do we call this fallback?

**Comment by tvernum** [comment]
I'm not sure what outcome you're looking for here.

We agree that the behaviour should change. We're happy for someone to pick up that work, but based on our estimate of the work involved vs the available engineering time we have, we don't expect to have the capacity to change ourselves in the near future.

Local user authentication _does_ work when a SAML realm cannot load its metadata, the issue that is described here is that you cannot start a node when a SAML realm has configuration that cannot be resolved.  
That was intentional so that nodes would not start if they had configuration errors, and the setting for the metadata was intentionally named `idp.metadata.path` rather than `.url` to reflect the fact that we intend and recommend that the metadata be loaded from a file not a https resource.
On reflection, we believe that a different set of tradeoffs are justified.

**Comment by zez3** [comment]
I see.
But would you still agree that the local or native users should still work?

https://www.elastic.co/guide/en/elasticsearch/reference/current/file-realm.html
"
The file realm is very useful as a fallback or recovery realm. For example in cases where the cluster is unresponsive or the security index is unavailable, or when you forget the password for your administrative users. In this type of scenario, the file realm is a convenient way out - you can define a new admin user in the file realm and use it to log in and reset the credentials of all other users.
"
Otherwise why do we call this fallback?

That way I learned AAA and perhaps I can find some RFCs in this regard, if one failing auth method was down it was never affecting the second or third auth mechanism.

Imagine that some big SAML IDP provider is taken down for some reason(maintenance, attack,etc.). All ES clusters using that will be take also offline. DDoS like.
Perhaps we need the insights of a CISO on this...

**Comment by tvernum** [comment]
> Imagine that some big SAML IDP provider is taken down for some reason(maintenance, attack,etc.). All ES clusters using that will be take also offline. DDoS like.

That's not accurate.
What is accurate is that _if_ you configure a SAML realm to load its metadata directly from the IdP, rather than following the recommendation to load the metadata from a file _and_ you shut down a node,  _then_ you will not be able to restart that node while the metadata is unavailable.

An IdP going offline does not cause running ES clusters to stop.  
And if node restart is an issue for you, then there is the simple option to load metadata from a file.

**Comment by zez3** [comment]
Correct. I have actually tested this.

**Comment by albertzaharovits** [comment]
I'll try to get this done this week.

**Comment by jaymode** [comment]
@tvernum @albertzaharovits @jakelandis is there any way that we can get this issue bumped up in priority? Being unable to start an instance due to an unavailable network resource is problematic for ESS and our customers.
