### ISSUE TITLE
Require order setting for each realm

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#37614]
Security has always allowed an order to be specified for realms, but it has never been required. I am wondering if we should consider making this a mandatory setting for each realm so that the user has to explicitly define the order they want and not rely on having a order based on the alphabetical sorting of realm names.

To be specific the behavior I am suggesting would be:

* order is mandatory for each realm definition
* no realms can have the same order value

**Comment by tvernum** [comment]
+💯

With `type` no longer being a field on the realm (it's implied by the key) some realm types no longer have any mandatory settings (in some cases no settings at all) so `order` has become _de facto_ required for those realms (e.g. native & file) because a realm has to have at least 1 setting.

Making that official for all realms would be so much better.

**Comment by tvernum** [comment]
A few notes on this:
- This is a breaking change, so it should be 8.0 only.
- We should add an equivalent deprecation in 7.x
- The code changes are likely to be small, but there will be a lot of docs to update.
