### ISSUE TITLE
Enhancement Request: Amend Circuit Breakers Discussion To Include A Discussion of Maximum Cluster Operating Limits

### ISSUE THREAD

**Issue by MorrieAtElastic** [elastic/elasticsearch#37664]
It is possible for an Elasticsearch cluster to grow too big. When a cluster grows too big it effectively stops functioning because every single operation returns a circuit breaker failure. Users whose production clusters have been functioning perfectly well can suddenly find themselves dead in the water with little or no warning.

It turns out that the fact that a cluster can grow to be too big is not documented clearly anywhere that I can find, and I certainly don't recall any discussion of this in any of the Training classes which I have taken or taught. This is an especially serious concern as users increasingly operate large clusters which are potentially susceptible to operating limit failures.

I suggest the documentation should include the following points:

- that every cluster has a maximum operating limit in terms of the amount of indexed data it can support. That when this limit is reached all operations will fail with circuit breaker exceptions and that the cluster will effectively be down.

- that the exact limit is difficult to determine and depends on the size of node JVMs, the amount of data being indexed, the nature of the index keys, the amount of field data associated with each index and other factors. The documentation should emphasize that the maximum operating limit is in terabytes of indexed data per node.

- what can be done proactively to anticipate reaching a cluster's maximum operating limit, specifically by checking various entries in node statistics

**Comment by jpountz** [comment]
I suspect this kind of issue became more common as a result of #27116: because we never fail opening segments, it is possible that the accounting circuit breaker ends up using all memory of the parent circuit breaker, preventing any new allocations.

I haven't thought about it much yet but I wonder whether we could have allocation rules based on memory usage of segments similarly to what we are already doing with disk usage already?

**Comment by hpandeycodeit** [comment]
@colings86 I can work on this one. Correct me if I am wrong, this file needs to be updated 
```
docs/reference/modules/indices/circuit_breaker.asciidoc 
```

Is there an exact text that needs to be put in?

**Comment by MorrieAtElastic** [comment]
Suggested wording: 

"
**Operating Limits of Elasticsearch Clusters**
Every Elasticsearch cluster has a limit to the amount of data it can store. When this limit is exceeded, the cluster will become inoperable and every attempted data operation will fail with some kind of circuit-breaker exception. This is not just a question of having so much data stored on disk that every query becomes unacceptably slow: when the operational limit is exceeded, the cluster will be unable to perform any kind of query, ingestion or indexing operation. Every attempted user operation - and also many administrative operations will fail with circuit-breaker exceptions.

Essentially the operating limit is reached when the amount of indexed data causes various internal data mapping structures to consume so much of the node’s memory that any additional operation would cause the node’s Java Virtual Machine (JVM) to crash with an out- of-memory condition. Circuit-breakers are tripped to prevent the JVM from reaching the out-of-memory point. When the cluster’s operating limit is reached every single attempted operation trips at least one circuit breaker , causing the operation to fail with a circuit-breaker exception. The elasticsearch logs may show thousands of circuit-breaking exceptions generated in a short period of time.

The exact size of each  cluster’s operational limit depends on several factors including the amount of RAM allocated to each node’s JVM, the amount of data stored in the cluster, the nature of index document keys, the number of shards in each index, the amount of field data mapped to fields in an index, and other factors. There is no way to exactly calculate a given cluster’s operational limit. As a general approximation: for nodes with 30 gigabyte (gb) JVM’s, a cluster’s operating limit will come at some point greater than 10 terabytes (tb) of indexed data per node. 

Customers with clusters having terabytes of data per node - and where the total index load is growing -  should be especially aware that they may be approaching their cluster's operating limit. They may wish to check the value of various circuit breakers through node statistics calls. 
"

- we may also wish to show examples of circuit breaker, storage , field data , segments and other values which can be obtained through node-statistics calls.

**Comment by wchrisdean** [comment]
[doc issue triage]

**Comment by jasontedor** [comment]
I don't think we should add any documentation along these lines. I think it's too vague and not actionable for users. I think it's understood that every system has finite capacity, and we try to expose to users in various stats endpoints some of the ways in which capacity can fill up (exposing queue depths, rejected executions, circuit breaker stats, memory usage, etc.) and also to push back on users when they are exceeding capacity. We advocate through various blog posts sound architectures where we advocate scaling horizontally at the cluster level rather than vertically (i.e., multiple not large clusters versus a single large cluster). If there are specific places where we aren't exposing the right information, then we can consider additions to Elasticsearch in those regards, but documentation along the lines of what is suggested here I don't think is going to be useful to our users.
