### ISSUE TITLE
SQL: Consider adding the columnar option for the returned results

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#37702]
At the moment ES-SQL adopts a row based approach for returning the results, meaning a list of lists where each sub-list contains one value for each column/field.

The columnar approach, on the other hand, returns all values of a certain column in a single list. Still to be decided if all the variants of clients (ODBC, JDBC, REST etc) and formats (json, yaml, txt, csv etc) make sense for this feature.

**Comment by monfera** [comment]
Kibana Canvas functions involving common renderers that use column JSONs themselves would benefit, as there'd be no need to expensively transpose big arrays in the browser, besides the all-around gain of better compressibility (due to negligible `[ ]` and lower `,` noise; serially adjacent data likely having the same format; common parts or, in the case of ordered output, identical values)

**Comment by astefan** [comment]
master (8.0.0): https://github.com/elastic/elasticsearch/commit/5b7e0de237fb514d14a61a347bc669d4b4adbe56
7.x (7.1.0): https://github.com/elastic/elasticsearch/commit/4deb69e9e4bf2b85ae0bb5b138762a92c8e052c8

@monfera this is merged with the soonest available version - 7.1.0.
