### ISSUE TITLE
Replace toArray(new T[size]) with toArray(new T[0])

### ISSUE THREAD

**Issue by hc-codersatlas** [elastic/elasticsearch#37744]
Hi, noticed many occurrences of toArray that could be made faster with a find and replace.

Performance: replace toArray(new T[size]) with toArray(new T[0])

https://shipilev.net/blog/2016/arrays-wisdom-ancients/#_conclusion (also contains benchmarks).

Could provide some simple performance improvements thanks!

**Comment by jasontedor** [comment]
Thanks for raising this for discussion. In the vast majority of cases, these sorts of changes will amount to micro-optimizations; only a few nanoseconds here and there when most requests process on the order of milliseconds or more. We prefer that we spend our limited development and review time carefully. If there are specific call sites where this optimization would give us a meaningful improvement, we would be happy to consider it. For that, we would look for a targeted pull request rather than a large pull request that sweeps over the whole codebase. Let us know if you're interested in investigating this further.
