### ISSUE TITLE
Highlighting could be made to produce larger fragments if there aren't as many fragments

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#3776]
Our current search system supports returning either one big fragment or two half sized ones.  It'll return one big fragment only if all the highlighting fits into fragment.  Elasticsearch could do that too, except letting the user pick maximum number of fragments.  Something like this:

``` javascript
"highlight": {
  "fields": {
    "foo": {
      "number_of_fragments": 2,
      "total_fragment_size": 150
    }
  }
}
```

I don't really know how important this is and I haven't thought through exactly how you'd do it.  I don't have any plans to implement this soon but if anyone is interested I could make time.

**Comment by jimczi** [comment]
This feature request is an interesting idea but since its opening we have not seen enough feedback that it is a feature we should pursue. We prefer to close this issue as a clear indication that we are not going to work on this at this time. We are always open to reconsidering this in the future based on compelling feedback; despite this issue being closed please feel free to leave feedback on the proposal (including +1s).
