### ISSUE TITLE
[CCR] Feature request-Replication between clusters 

### ISSUE THREAD

**Issue by zhangmeihui123** [elastic/elasticsearch#37854]
**Describe the feature**: 
Now  Cross-cluster replication is active-passive, it can't replicate from follower index to leader index.
Can you provide a function that can replicate between the clusters ,not just replicating one way?
Image this, we have two clusters, data is bidirectional replicating. One cluster is primary site, the other is standby.
Daily, we sent request to primary cluster, and backup in standby cluster.
And one day if the primary cluster is down, we sent request to standby cluster, and also standby cluster can replicate date to primary cluster. 
Once the primary cluster is up, it can recovery from standby cluster.

**Comment by jasontedor** [comment]
At this time we have no intention of implementing active-active replication. It might be that we change this someday but it is not on our current roadmap. It would require fundamental changes to our replication model and we are not investing in them at this time. I prefer to close this issue as a clear indication of our current stance on it.

>And one day if the primary cluster is down, we sent request to standby cluster, and also standby cluster can replicate date to primary cluster.
>Once the primary cluster is up, it can recovery from standby cluster.

It’s possible that we can address this someday without implementing active/active replication. However, we are also currently not investing in this. Again, I prefer to close this issue so that our current feature set and its limitations, as well as our roadmap, are clear.
