### ISSUE TITLE
Allow Bucket Script aggregation to reference on null

### ISSUE THREAD

**Issue by larrycinnabar** [elastic/elasticsearch#37862]
related to #36642

related to #31920

Example:
```
  "some-items":{  
    "aggregations":{  
      "averaged":{  
        "avg":"field"
      }
    },
    "children":{  
      "type":"child"
    }
  },
  "some-metric":{  
    "bucket_script":{  
      "buckets_path":{  
        "a":"some-items>averaged.value"
      },
      "script":{  
        "source":"params.a + 100"
      }
    }
  }
```

If, in this example, number of `child` elements are zero, the AvgAggregation can't be performed (as averaging of zero elements is impossible). That `averaged` aggregation will return `null`.
But this null will silentry break the `some-metric`. In the final result, `some-metric` won't just appear (without any error).

I think it's a good thing to be able to handle these case inside the script. For example:
```
"source":"if (params.a == null) {return 100} else {return params.a + 100}"
```
In case if this null is not handled - elastic can just return an error

**Comment by polyfractal** [comment]
Yep, this is definitely a bug.  I'm going to close though since it's being tracked in https://github.com/elastic/elasticsearch/issues/27377, and in particular there's a plan that was discussed here: https://github.com/elastic/elasticsearch/issues/27377#issuecomment-347238853

The tl;dr: is that we would like to start passing the raw value to the script, but also pass in the `doc_count`.  Both are important to provide, so that the user knows if the value is actually `null`, or if it's just `null` because there were no documents.

Thanks for opening the issue, and sorry you're running into this :(  There are several related pipeline issues that revolve around missing docs / null values, so hopefully we can start tackling them soon.
