### ISSUE TITLE
[DOCS] Improve Enabled Documentation to refer types other than object

### ISSUE THREAD

**Issue by bphenriques** [elastic/elasticsearch#37941]
Hello,

The documentation regarding the [`enabled`](https://www.elastic.co/guide/en/elasticsearch/reference/current/enabled.html) can be improved by telling that is possible to use it on types other than `object` (`boolean`, `float`, etc). From the docs (including the examples), we are led to believe that it can only be used on fields of type `object`. See quote below.

> The enabled setting, which can be applied only to the mapping type and to object fields, causes Elasticsearch to skip parsing of the contents of the field entirely. The JSON can still be retrieved from the _source field, but it is not searchable or stored in any other way:

I tested. See Kibana screenshot below:
![upload](https://user-images.githubusercontent.com/4727729/51860973-f1963200-2332-11e9-8747-538a3e7d754f.png)

**Edit**: With a more careful reading, it seems that there is something missing in the phrase `only to the mapping type <something> and to object fields`

**Edit2**: It is possible but thinking this through Elasticsearch should throw an error given that am I doing an aggregation over `enabled: false` field (`disabled`).

**Comment by jtibshirani** [comment]
Hi @bphenriques, I think that the documentation is correct in stating that only `object` mappings support the `enabled` parameter. In your example, the `disabled` mapping implicitly has type `object`. You can see that the `enabled` parameter is not supported for other mapping types like `boolean` by trying out the following:

```
PUT test
{
  "mappings": {
    "_doc": {
      "properties": {
        "field": {
          "type": “boolean”,
          "enabled": true
        }
      }
    }
  }
}
```

This returns the error `"Failed to parse mapping [_doc]: Mapping definition for [field] has unsupported parameters:  [enabled : false]”`.

When an object field is disabled, it is possible to add non-object data to it because the field parsing is skipped entirely. This is why you are able to pass longs to the `disabled` field in the example.

I opened to #40989 update the documentation -- maybe you’d be able to take a look to see if it helps clarify these points? I also tried to improve the wording around "only to the mapping type and to object fields".

> It is possible but thinking this through Elasticsearch should throw an error given that am I doing an aggregation over enabled: false field (disabled).

In general, elasticsearch will not throw an error if a user attempts to query or aggregate on an object field, and instead treats it as an 'unmapped' field. I think the current behavior around using disabled fields in searches is consistent with that, and that we wouldn't want to throw an error just in the case that `enabled: false`.

**Comment by bphenriques** [comment]
Hey @jtibshirani ! Thank you for the clarification both here on the pull request. It is far more clear to me now! :+1:

**Comment by jtibshirani** [comment]
Great, I am closing this out now that #40989 merged.
