### ISSUE TITLE
During recovery, log the amount of time left until automatic recovery

### ISSUE THREAD

**Issue by ahazelwood** [elastic/elasticsearch#38106]
**Describe the feature**:
Whenever a cluster is restarted completely, it will start issuing log messages of:  ClusterBlockException[blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized]. 

It would be nice if the message would state when recovery will automatically take place if the system knows this.  This would help with newer Elasticsearch admins to know what is happening.  For example, if recovery is set to 10 minutes, then a countdown should take place in subsequent messages if automatic recovery will take place.   A possible example would be:  

ClusterBlockException[blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized.  Automatic Recovery in 9min 31s]

**Elasticsearch version** (`bin/elasticsearch --version`):  6.6.0

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_201

**OS version** (`uname -a` if on a Unix-like system):  4.15.0-45-generic

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.  Completely restart a cluster.
 2.  Log onto a master node and tail the log file.
 3.  You will see ClusterBlockException messages appear

**Provide logs (if relevant)**:

**Comment by DaveCTurner** [comment]
We discussed this, and generally agreed that periodically logging a message indicating why the cluster has not recovered its state yet would be good. We [already emit a periodic log message when there is no master](https://github.com/elastic/elasticsearch/blob/bda591453cc4cfc076eb2bccc4b96877f27f393c/server/src/main/java/org/elasticsearch/cluster/coordination/ClusterFormationFailureHelper.java) and we think that something similar would work well here too.

> A possible example would be:
> `ClusterBlockException[blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized. Automatic Recovery in 9min 31s]`

I think we wouldn't include this information in the `ClusterBlockException` message itself. It'd be an API change, and those messages can be sent over the wire so we could be reporting remote state rather than the local state which would be rather confusing. The preferred approach is to construct these log messages independently of the `ClusterBlockException`.

We have no plans to work on this ourselves, but a PR to add this feature would be welcome.

**Comment by vishnugt** [comment]
I would like to work on a PR to add this feature.

**Comment by DaveCTurner** [comment]
We've not heard any more on this idea for a few months, so I'm closing this issue as an indication that we're not intending to take any further action here. Feedback (or a PR) is still welcome.
