### ISSUE TITLE
Monitoring HTTP exporter should allow users to customize bulk size

### ISSUE THREAD

**Issue by ycombinator** [elastic/elasticsearch#38119]
Sometimes users have a HTTP proxy (e.g. nginx) in front of their Monitoring Elasticsearch cluster. The proxy might have a default request size limit, e.g. `1MB`. This means that if another Elasticsearch cluster — configured to use the HTTP exporter to send data to the Monitoring Elasticsearch cluster via the proxy — sends a bulk request more than the limit, the proxy will reject it with a HTTP 413. 

It would be nice if we could expose an HTTP exporter setting that would allow users to tune the maximum size of their bulk request.

/cc @jordansissel @elastic/stack-monitoring

**Comment by jordansissel** [comment]
This issue was experienced by infosec in production with this configuration:

Monitoring http exporter -> nginx -> elasticsearch cluster

nginx's default max body size appears to be 1MB, and our nginx was found to be rejecting these requests:

```
[2019-01-31T19:44:36,280][WARN ][o.e.x.m.e.h.HttpExportBulkResponseListener] bulk request failed unexpectedly
org.elasticsearch.client.ResponseException: method [POST], host [https://xyz:443], URI [/_bulk?pipeline=xpack_monitoring_6&filter_path=errors%2Citems.*.error], status line [HTTP/1.1 413 Request Entity Too Large]
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.14.0</center>
</body>
</html>
```

I can correct for this on our side with an nginx configuration, but the failure mode of this scenario is very interesting:

* Some documents make it (node_stats), but others do not (cluster stats?)
* Monitoring page claims that monitoring is not enabled.

Computers are fun :)

**Comment by dakrone** [comment]
Internal monitoring has been deprecated for quite a while, and we're no longer doing any active development on it. I'm going to close this issue.
