### ISSUE TITLE
elasticsearch-setup-passwords problem

### ISSUE THREAD

**Issue by chenjienn** [elastic/elasticsearch#38261]
when i try to use `./elasticsearch-setup-passwords auto` to set password, it always failed in setting the password for [apm_system] user

![setpass-error](https://user-images.githubusercontent.com/13412289/52166914-5c3dd800-274e-11e9-8e4e-70e6dc25c52a.png)
![es-exception](https://user-images.githubusercontent.com/13412289/52166916-61028c00-274e-11e9-8569-29055de5286b.png)

my config file:
[elasticsearch.txt](https://github.com/elastic/elasticsearch/files/2824634/elasticsearch.txt)

**Elasticsearch version** (`bin/elasticsearch --version`):
6.5.4
**JVM version** (`java -version`):
1.8.0_162
**OS version** (`uname -a` if on a Unix-like system):
CentOS 7

**Comment by jasontedor** [comment]
Sorry that you're having trouble here. In general we reserve GitHub for verified bug reports and feature requests and ask that you use the [forum](https://discuss.elastic.co) for troubleshooting and user questions. I can help you quickly here.

This is because you have configured your node to not hold any index data (`node.data` is set to `false). As such, the write to the `.security-6` index for the new user passwords can not succeed as there are no shard copies available. You either need to add a data node to your cluster so the primary shards can be allocated, or you need to allow your single node to be a data node too.

If you have follow-up, please use the forum.

**Comment by chenjienn** [comment]
thank you for your reply ! Next time i will use the forum for my questions

**Comment by NCNIK25** [comment]
> Sorry that you're having trouble here. In general we reserve GitHub for verified bug reports and feature requests and ask that you use the [forum](https://discuss.elastic.co) for troubleshooting and user questions. I can help you quickly here.
> 
> This is because you have configured your node to not hold any index data (`node.data` is set to `false`). As such, the write to the `.security-6` index for the new user passwords can not succeed as there are no shard copies available. You either need to add a data node to your cluster so the primary shards can be allocated, or you need to allow your single node to be a data node too.
> 
> If you have follow-up, please use the forum.

What about if we want dedicated master node, we can't make it as data node correct.
I'm having a dedicated master and two other data master eligible node and getting same error.
