### ISSUE TITLE
Deserialize timeZone with DateUtils in RangeQueryBuilder

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#38449]
as spotted in this review https://github.com/elastic/elasticsearch/pull/38415#discussion_r253927699
`DateUtil` should be used when serialising/deserializing timezones to allow deprecation logging

**Comment by gwbrown** [comment]
Looks like the place that actually needs to be changed to use `DateUtils.dateTimeZoneToZoneId` is:

https://github.com/elastic/elasticsearch/blob/95582da9a57086c1bf519b300ffc420d03448e28/server/src/main/java/org/elasticsearch/index/query/RangeQueryBuilder.java#L95

**Comment by pedrochamberlain** [comment]
Hello, is this issue still open? I'd like to give it a shot. This would be my first issue.

**Comment by LeeTgk** [comment]
Hi. is this issue still open? I would like to try it as my first issue. 🤨:mag:

**Comment by josephkois** [comment]
I attempted to fix this issue. I created a pull request and tried to make the commit as clear as possible.

**Comment by timDINOS** [comment]
Hello is this issue still open? I would like to fix this issue.

**Comment by happyCupcake** [comment]
@gwbrown @williamrandolph @pgomulka  I am new to open source and to elasticsearch and with some guidance I can help. I reviewed all comments and previous PR's. 

Here, the call in.readOptionalZoneId() needs to be replaced with DateUtils.dateTimeZoneToZoneId(DateTimeZone) , but its not clear to me how because dateTimeZoneToZoneId takes as input timezone and returns zone id but the current code is reading zoneId and storing as timezone.

Any guidance will help :-)

>  public RangeQueryBuilder(StreamInput in) throws IOException {
> ..
> 
> timeZone = in.readOptionalZoneId();
>

**Comment by ayushrawat99** [comment]
HI I am new and want to give it a shot. Can I pick this up ?

**Comment by ldematte** [comment]
Not needed anymore since https://github.com/elastic/elasticsearch/pull/40647
