### ISSUE TITLE
[Feature Request] More-Like-This-Query by Query

### ISSUE THREAD

**Issue by eydin** [elastic/elasticsearch#38467]
**As a developer, I want to be able to specify a query, instead of a distinct set of documents, within a More-Like-This Query so that I can make a single call to find documents related to some undefined set.**

The problem is this... my customer has a lot of uncategorized news articles that they're slowly tagging with categories. My customer wants me to produce a news feed of articles for each category and include in that feed the uncategorized articles that are similar to the already categorized set, which are growing and changing as my customer tags unmarked articles.

Using the MLT query to do this work pretty well, but I'm having to make two requests in order to produce the news feed. First, I'm having to search for all the articles marked with a given category, and then I have to run a search and pass that set of documents in to the MLT query.

Making two requests and passing hundreds or thousands of document ids is pretty inefficient, and truthfully, I expected MLT to support what I need it to do, it seems to be natural extension of the existing behavior.

**Comment by jimczi** [comment]
> Making two requests and passing hundreds or thousands of document ids is pretty inefficient, and truthfully, I expected MLT to support what I need it to do, it seems to be natural extension of the existing behavior.

I don't think it's a "natural" extension. The MLT query is designed to be efficient when a few ids are passed, it would be the same with a query. If the query matches a lot of documents, we'd need to extract the term vectors for each document and merge them into the global statistics for the query. 
Accessing the term vectors of a few documents is acceptable but this doesn't scale if we apply the logic to a live query. Note that I am not saying that we should not handle classification tasks in Elasticsearch, I just think that MLT is not the right entry point for this.

**Comment by markharwood** [comment]
I'd suggest looking at the [significant_text](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-aggregations-bucket-significanttext-aggregation.html) aggregation for this type of work. Unlike termvectors API it can skip duplicate sections of texts which otherwise skew keyword suggestions badly.

Example use in classification tasks: https://youtu.be/OmMXuT9qsV4
Deep dive on the de-dup feature: https://youtu.be/zH7bizwjj20?t=234

**Comment by svola** [comment]
@eydin You could have a look at this technique for text classification with the MLT query.  

https://www.elastic.co/blog/text-classification-made-easy-with-elasticsearch

**Comment by jimczi** [comment]
We discussed this internally and we think that there are multiple ways to achieve this kind of classification task, the link above is one example. Since this is difficult to choose one way or another (it will depend on the data and the use case) we think that this kind of task should be done client side.
I am also curious of what the @elastic/ml-core team think here considering that classification is something we discussed before.

**Comment by stevedodson** [comment]
This sort of use-case is one of several we have in mind as we investigate adding support for supervised and unsupervised classifiers to Elastic ML. Nothing to announce at this time, but thank you for opening this issue - it helps confirm our understanding of the needs here.

**Comment by markharwood** [comment]
Closing as we consider this a client-side task which could take various approaches
