### ISSUE TITLE
S3 Repository Plugin Fails with S3 Object lock

### ISSUE THREAD

**Issue by Alsheh** [elastic/elasticsearch#38699]
**Elasticsearch version**: `docker.elastic.co/elasticsearch/elasticsearch:6.6.0`
**Plugins installed**: [S3 repository plugin]
**Description of the problem including expected versus actual behavior**:
The S3 repository plugin fails to snapshot indices for an S3 bucket when enabling Object lock with Governance or Compliance mode.

**Reason**: 
```
Missing Content-MD5 HTTP header for Put Object requests with Object Lock parameters.
```

**Steps to reproduce**:
1. Create S3 bucket.
2. Enable Object lock setting in Compliance mode.
3. Take snapshot of indices using the created S3 bucket.

**Actual error log message**:
```
{
   "error":{
      "root_cause":[
         {
            "type":"repository_verification_exception",
            "reason":"[repo-2019.02.05] path [repo-2019.02.05] is not accessible on master node"
         }
      ],
      "type":"repository_verification_exception",
      "reason":"[repo-2019.02.05] path [repo-2019.02.05] is not accessible on master node",
      "caused_by":{
         "type":"i_o_exception",
         "reason":"Unable to upload object [repo-2019.02.05/tests-H2Ibd9geTV-kMrWddbucZg/master.dat] using a single upload",
         "caused_by":{
            "type":"amazon_s3_exception",
            "reason":"amazon_s3_exception: Content-MD5 HTTP header is required for Put Object requests with Object Lock parameters (Service: Amazon S3; Status Code: 400; Error Code: InvalidRequest; Request ID: <request-id>; S3 Extended Request ID: <s3-extended-request-id>)"
         }
      }
   },
   "status":500
}
```

**Comment by original-brownbear** [comment]
I commented on this in the PR the issue author opened here: https://github.com/elastic/elasticsearch/pull/38830

I'm not sure what we would support for object lock want to look like. Simply allowing to upload objects by setting the `Content-MD5` does not seem to be enough to make for useful functionality and would merely allow one to force their snapshots into a bucket with compliance enabled while restoring a previous state (of the bucket) would still require a lot of trickery since the objects making up the snapshot are versioned individually instead of in unison (so you'd have to figure out what set of object versions actually makes up the state of the repo at a given time).

Also somewhat relates #33948 that points out the lack of usefulness of versioning an S3 repository bucket.

**Comment by original-brownbear** [comment]
@Alsheh is this still something you're interested in discussing?

**Comment by Alsheh** [comment]
@original-brownbear thanks for the follow up. You raised good points about the complexity of having ES snapshots in a versioned S3 bucket. The functionality I was hoping to implement was easily achieved with a non-versioned S3 staging bucket before pushing to the compliance bucket.

**Comment by original-brownbear** [comment]
@Alsheh alright, thanks for getting back to me on this :) Closing here then.
