### ISSUE TITLE
Support "Intelligent Tiering" storage class for S3 snapshots

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#38836]
In November 2018 [AWS announced a new "Intelligent Tiering" storage class](https://aws.amazon.com/about-aws/whats-new/2018/11/s3-intelligent-tiering/):

> S3 Intelligent-Tiering stores objects in two access tiers: one tier that is optimized for frequent access and another lower-cost tier that is optimized for infrequent access. For a small monthly monitoring and automation fee per object, S3 Intelligent-Tiering monitors access patterns and moves objects that have not been accessed for 30 consecutive days to the infrequent access tier. [...] If an object in the infrequent access tier is accessed later, it is automatically moved back to the frequent access tier.

This sounds like it would be appropriate for snapshots. To support this we would need to upgrade the AWS SDK to a version supporting this storage class, add tests showing that setting `storage_class: intelligent_tiering` works, and adjust the docs.

**Comment by ywelsch** [comment]
I think this would also require clearly documenting our file access patterns during snapshot, snapshot listing and restore. The risk is that this will tie us to a particular storage pattern, optimized for the above usage.

**Comment by original-brownbear** [comment]
@ywelsch I think this is in all likelihood a good idea regardless of the access pattern when it comes to S3.

My reasoning would be: S3 is our "least consistent" blob store, we probably don't ever want to move to an access pattern that would update old blobs in any way because updates are where the danger lies in the first place => without updates to old (large > 1MB) blobs this is a win in every scenario that keeps snapshots longer than a month imo.

Maybe we should still make this an option though since it would increase cost in scenarios where no snapshot lives for more than a month (not sure how frequent that is but still ...)?

**Comment by pedrostil** [comment]
Hey, can I work on this?

From what I understood this is just for supporting intelligent tiering, not changing the default storage level, correct?

**Comment by DaveCTurner** [comment]
Sure @pedrostil, go ahead. Your understanding is correct.

**Comment by akashsingh-aps** [comment]
- In our [documentation](https://www.elastic.co/docs/deploy-manage/tools/snapshot-and-restore/s3-repository#repository-s3-storage-classes) it is advised to use **intelligent_tiering** storage class, but not with `Archive Access` or `Deep Archive Access` tiers. 

- But there is one more [tier](https://docs.aws.amazon.com/AmazonS3/latest/userguide/storage-class-intro.html#sc-dynamic-data-access) `Archive Instant Access` which is not explicitly mentioned in the doc.

Any pointers/suggestions etc ? 

cc: @pedrostil @DaveCTurner @original-brownbear @ywelsch
