### ISSUE TITLE
ERROR: X-Pack Security is disabled by configuration

### ISSUE THREAD

**Issue by liuhamglin** [elastic/elasticsearch#39028]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --6.6.0`):

**Plugins installed**: [
**JVM version** (`java -8`):

**OS version** (`windows-10` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 

- 
 1. Execute the command  “ elasticsearch-setup-passwords interactive”
 2. There is an error  ERROR: X-Pack Security is disabled by configuration.
 3. But “xpack.security.enabled: true”  has been set

**Provide logs (if relevant)**:

**Comment by tvernum** [comment]
@liuhamglin Thank you very much for your interest in Elasticsearch.

It is hard to reach an exact diagnosis of your issue from the information you have provided but I believe this functionality is working correctly, and there is likely to be a configuration issue in your local setup.

We prefer to direct these kinds of things to the [forums](https://discuss.elastic.co/), as those discussion forums are beter suited to these sorts of troubleshooting and problem diagnosis conversations.
If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question.
As such, I hope you don't mind that I close this. If it turns out that there is a real bug, then we can re-open this issue.

Thank you.

**Comment by liuhamglin** [comment]
elasticsearch-setup-passwords auto

Unexpected response code [404] from calling GET http://127.0.0.1:9200/_xpack/security/_authenticate?pretty
It doesn't look like the X-Pack security feature is enabled on this Elasticsearch node.
Please check if you have enabled X-Pack security in your elasticsearch.yml configuration file.

ERROR: X-Pack Security is disabled by configuration.

**Comment by liuhamglin** [comment]
![7tch5m b 9o1qlhu hi_wa](https://user-images.githubusercontent.com/18131476/52936264-989c4580-3396-11e9-8d4c-71eca560469f.png)
I've configured xpack security to be enabled in the configuration file, but I don't see it in kibana
