### ISSUE TITLE
[ML] File Data Visualiser - only use a single shard

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#39084]
**Describe the feature**:
When Data Visualiser creates a new index, it should use one shard.

Given the 100MB limit, it doesn't make sense to use the default of 5. I know we are changing the default in Elasticsearch as well, but it still makes sense to be explicit.

**Comment by droberts195** [comment]
@jgowdyelastic I think this would be a UI side change - basically instead of defaulting the index settings to `{}` when importing default them to `{ "number_of_shards": 1 }`.

As @markwalkom says, the biggest benefit of doing this would be in 6.6.2 and 6.7.x.  That would actually cause us to put less burden on customer clusters.  Given how simple the change is I think it's worthwhile.  It's not great that someone who messes about with the file data visualizer and imports 10 small files ends up with 50 extra shards in their cluster in 6.x.  From 7.0 onwards the default is 1 anyway so the change would just be cosmetic.
