### ISSUE TITLE
Index Lifecycle Management does not have a lower bound on poll_interval

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#39163]
Index Lifecycle Management has a polling interval that is configurable. The default is 10 minutes but may be changed via the dynamic `indices.lifecycle.poll_interval` setting. 

Currently there is no lower bound, which if set too low could consume more compute resources that are reasonably required. We should enforce a lower bound of 1000ms (1s).

To reproduce:
```
PUT /_cluster/settings
{
  "persistent": {
    "indices.lifecycle.poll_interval": "1ms",
    "logger.org.elasticsearch.xpack.indexlifecycle": "TRACE"
  }
}
```
(watch the log file)

**Comment by ppf2** [comment]
I wonder if we will want to set the lower bound to something higher than 1s.  Do we see potential issues with ILM triggers as frequent as 1s for clusters that have frequent state changes that might have a fairly busy master node?

**Comment by gwbrown** [comment]
If we were basing a lower bound on what we expect to be useful in the wild, a minimum of something like 1m might be reasonable, but one thing that's prevented us from using a higher minimum than 1s in the past is that we set the `poll_interval` very low in tests to speed up how long it takes to run the tests, and in many cases it makes tests possible that would not be possible otherwise (within a reasonable time frame per test).

Having a 1s minimum poll interval makes sense.  While being able to set this setting lower has been occasionally useful in the past for more quickly reproducing race conditions, if we need to do that, it can always be done in a custom build with the lower limit disabled.

**Comment by ApolloTheDeveloper** [comment]
Hello all,
I am a new developer and I would really like to contribute to this project. May I work on this? Thank you.

**Comment by dakrone** [comment]
@ApolloTheDeveloper there's currently already a PR open for it at #39593

**Comment by gwbrown** [comment]
Just merged https://github.com/elastic/elasticsearch/pull/39593, which adds the lower bound of 1 second.
