### ISSUE TITLE
More descriptive error message for upper-case keys in keystore

### ISSUE THREAD

**Issue by eskibars** [elastic/elasticsearch#39324]
**Describe the feature**:
I can't think of a valid reason to have upper-case key names in the keystore, but the error message when you try could use some cleanup.

```
$ ./elasticsearch-keystore add FOO
Enter value for FOO:
ERROR: String value must contain only ASCII
```

It seems we should reject before the user has a chance to enter the value with an exception that relates to the key name rather than the value.

**Comment by jasontedor** [comment]
There is a related issue here. Today it is possible for a setting to contain uppercase letters. Because of the limitation here that we imposed on the keystore, it is not possible for such a setting to be in the keystore. I think that we should remove the ability for settings to contain uppercase names, for settings in the configuration file and settings in the cluster state.
