### ISSUE TITLE
Support for automatic release of index block once disk frees up

### ISSUE THREAD

**Issue by Bukhtawar** [elastic/elasticsearch#39334]
### The Problem
The `DiskThresholdMonitor` in Elasticsearch monitors for disk utilization across nodes periodically based on `cluster.info.update.interval` and ends up putting a `INDEX_READ_ONLY_ALLOW_DELETE_BLOCK` on every index that has atleast one shard on a node that breaches `cluster.routing.allocation.disk.watermark.flood_stage` but leaves those indices in the same state even after disk frees up, putting the onus on the end user to manually unblock those indices. This issue has been initiated as a part of #24299([comment](https://github.com/elastic/elasticsearch/issues/24299#issuecomment-465707036)) 

### Proposed Solution
The master is already checking for disk utilization across nodes to see if nodes are going over the `flood` threshold. So if we find any index block in the cluster state that should no longer be blocked based on the latest run of the disk monitor we should go ahead unblock those indices. The solution should mark index block which breach the threshold as `INDEX_READ_ONLY_ALLOW_DELETE_BLOCK` and the unblock the ones which already have blocks based on `state.getBlocks().indexBlocked(ClusterBlockLevel.WRITE, index)` but no longer match the indices. The only challenge would be to distinguish a customer requested block for `SETTING_READ_ONLY_ALLOW_DELETE` vs the one added by the disk monitor. To solve this we can either introduce a parameter in the request and a separate block to mark the indices from monitor differently.

**Comment by DaveCTurner** [comment]
We discussed this today and it seems like a reasonable change to make. The `INDEX_READ_ONLY_ALLOW_DELETE_BLOCK` was introduced purely to support the `flood_stage` watermark so we don't think there's a need for another kind of block.

We are concerned about flapping, i.e., being in a state where the block is added and removed and then added again in a loop, and the solution to this is not to remove the block as soon as the disk usage drops below the watermark itself. We think the block should be removed only when the disk usage is at least 5% below the `flood_stage` watermark _and_ below the `high` watermark.

Marking this as `help wanted` because we do not anticipate working on this as a priority, but we welcome contributions from the community.

**Comment by alex101101** [comment]
Hi @DaveCTurner,
Could I look into this?

**Comment by DaveCTurner** [comment]
Sure @alex101101, go ahead.

**Comment by alex101101** [comment]
Thanks @DaveCTurner, I have just raised a pull request.  Could you please review it when you have time?

**Comment by Bukhtawar** [comment]
@DaveCTurner would be great if you could spare sometime for the review

**Comment by Bukhtawar** [comment]
@DaveCTurner can you please review this

**Comment by DaveCTurner** [comment]
> can you please review this 

I'm not wholly sure what you mean by "this". If you are talking about #40338, it's better to add comments like this to the PR itself rather than here on this issue.

Also I left a review of #40338 three weeks ago and none of my comments have been addressed yet. I have nothing more to add at this time.

> you mean with low/high/flood at 85/90/95 respectively release should happen at 5% less from 95 i.e below 90(which is also where high disk watermark is)

That sounds like a better interpretation than the one proposed in #40338 right now, but only makes sense if the watermarks are given as percentages. If given as absolute values, we'll need to do something else.

**Comment by Bukhtawar** [comment]
@alex101101 I can take over the PR to address the comments left by @DaveCTurner.  Please let me know if you wish to continue.

**Comment by vigyasharma** [comment]
+1 for clearing blocks when cluster goes `below high watermark`.

This keeps it configurable while also telling users that some reasonable space needs to be cleared. I don't think people would set high watermark very far from flood stage, so it should not delay unblocking by a lot.

The default settings anyway provide 5% buffer. And if high watermark is explicitly set too close to flood stage, then it's a conscious risk we've taken.

**Comment by alex101101** [comment]
Hi. Sorry that I haven't been able to revise my original dev, haven't had the time in the last few weeks to properly look into the options. Yes it's definitely fine for you to take over @Bukhtawar, thanks for asking.
