### ISSUE TITLE
Permission problem on Centos 7 when using Elasticsearch 6.6.1 RPM

### ISSUE THREAD

**Issue by DanRoscigno** [elastic/elasticsearch#39461]
**Elasticsearch version** 6.6.1

**Plugins installed**: ingest-geoip and ingest-user-agent

**JVM version** openjdk version "1.8.0_191"

**OS version** `Linux external-elastic-one 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

I downloaded the RPM from elastic.co/downloads and installed from the commandline (rpm -i ).  The install reported no issues.  When I started Elasticsearch it did not come up.  I expected it to come up.
**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.6.1.rpm
 2.  sudo yum install java-1.8.0-openjdk.x86_64
 3.  sudo rpm -i elasticsearch-6.6.1.rpm 
 4.  sudo systemctl daemon-reload
 5.  sudo systemctl enable elasticsearch.service
 6.  sudo systemctl start elasticsearch.service
 7.  sudo systemctl status elasticsearch.service

**Provide logs (if relevant)**:
```
journalctl -u elasticsearch
Feb 26 23:55:51 external-elastic-one systemd[1]: Started Elasticsearch.
Feb 26 23:55:54 external-elastic-one elasticsearch[4708]: 2019-02-26 23:55:54,365 main ERROR Unable to create file /usr/share/elasticsearch/logs/elasticsearch.log java.io.IOException: Could not create directory /usr/share/elasticsearch/logs
```

Here is what I did next:

The `could not create directory` suggested a permission problem, and the parent dir /usr/share/elasticsearch was owned by root.
```
cd /usr/share/
sudo chown -R elasticsearch:elasticsearch elasticsearch/
```

After making the permission change I restarted Elasticsearch and everything is fine.  I did this on three systems to setup a three node cluster.

**Comment by rjernst** [comment]
@DanRoscigno Do you have any other configuration for elasticsearch already set? Perhaps path.logs in  an existing elasticsearch.yml? The rpm package uses `/var/log/elasticsearch` as the logs path. So the fact elasticsearch is trying to write to `/usr/share/elasticsearch/logs` indicates you have something changing that.

Since we have tests for all our packages and one of the many checks is this log file location, I'm going to close this issue. If you are still having issues, please post a thread in the [forums](https://discuss.elastic.co). There's an active community in the  that should be able to help debug issues like this. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.
