### ISSUE TITLE
Add documentation on how to deal with pre-ILM indices when ILM is used

### ISSUE THREAD

**Issue by andrershov** [elastic/elasticsearch#39526]
Currently, we're missing the documentation on how to deal with indices created before ILM, when the user starts to use ILM.
It looks like ILM can only be used by new users or by existing users but only for new index types.
I think the following case is super usual among existing users. The user is storing logs in logs-MM.YY indices. He somehow managed to roll over these indices himself, but that's it (no copying to warm storage, no auto-index deletion).
Now, one year later, the user decides to use ILM feature. And defines a policy for rollover, migrating to warm storage, cold storage and deletion. He also wants to apply this policy for previously created indices.
But it's not that easy to do.
I think we can document best-practices on what to do with old indices.

**Comment by shlok007** [comment]
Hey @andrershov , Can you help me out with the way to apply ILM policy to existing indexes until we have the proper documentation in place? I am struggling on how to do that. Thanks.

**Comment by gwbrown** [comment]
@shlok007 Please post questions like this to [the Discuss forums](https://discuss.elastic.co/c/elasticsearch) rather than asking on GitHub issues, and please don't ping individuals directly. If you post your question to the forums, someone will help you out when they can.

**Comment by gwbrown** [comment]
We discussed this in the weekly team sync, and decided to cover two primary use cases:
1. How leverage ILM for old periodic indices when transitioning to fully ILM-managed indices
2. How to reindex data into fully ILM-managed indices. This is more niche, but it can be useful when the periodic indices are either very small or very large and breaking them into more appropriately sized indices is useful, and we've seen several users going this route, but there are some important points to be aware of.

There were some more details discussed, but rather than effectively writing the documentation here, I'll take those details into consideration in writing https://github.com/elastic/elasticsearch/pull/43667 and continue the discussion there.

**Comment by gwbrown** [comment]
We've added these docs in  #43667, so I'm closing this issue.
