### ISSUE TITLE
Enable code snippet testing with only "copy as curl"

### ISSUE THREAD

**Issue by lcawl** [elastic/elasticsearch#39594]
https://github.com/elastic/elasticsearch/blob/master/docs/README.asciidoc describes how to test examples with the //CONSOLE option.

There is also a // KIBANA option, which omits the Console link and only shows the "Copy as curl" link.  For example, see its use in https://www.elastic.co/guide/en/kibana/master/spaces-api-post.html and all the other Kibana APIs that don't work in the Kibana Console.

There are other circumstances where we might want to *only* show the "Copy as curl" link.  For example, I am seeking that sort of behaviour in 
https://github.com/elastic/elasticsearch/pull/39530 and https://github.com/elastic/elasticsearch/pull/39583
... since the DELETE examples in the invalidate token API currently fail in the Console due to https://github.com/elastic/kibana/issues/13245

When I switch the occurrences of `// CONSOLE` to `// KIBANA`, however, I received gradle errors like this:

Execution failed for task ':x-pack:docs:buildRestTests'.
> // TEST[continued] cannot be on first snippet in a file: en/rest-api/security/invalidate-tokens.asciidoc[86:91](js)// TEST[continued]

Ideally we can test examples successfully irrespective of whether we have console or curl links following them.

**Comment by colings86** [comment]
@lcawl Given that the only "copy as curl" is relevant to Kibana APIs and not Elasticsearch APIs I think this issue needs to be raised either in the Kibana repo so the Kibana build can be modified to test these snippets, or in the docs repo so the docs infrastructure can be modified to accommodate this (though I think the docs infrastructure ignores the `//CONSOLE stuff`). I'm not sure there is anything to do in the Elasticsearch build itself?

**Comment by colings86** [comment]
@lcawl I think we need to be a bit careful here, for a few reasons:
1. I think we should avoid using `// KIBANA` for any calls against the Elasticsearch APIs (e.g. https://github.com/elastic/elasticsearch/pull/39583/files#diff-5fa81aa90baa4f03546357926caee588R80). I think the intention is that we only want to show the cURL form of the API call in these security instances because the user will not yet have access to Console and labelling these as `// KIBANA` is quite confusing IMO as it mixes "only show cURL" with "this is something relevant to Kibana". It is likely to cause confusion to people looking at the raw asciidoc and it prevents 2 below.
2. We need to be able to differentiate between Kibana API calls and Elasticsearch API calls. The docs snippet testing cannot currently be used against Kibana APIs because the tests only set up an Elasticsearch cluster and makes calls against that. So we need to be able to  differentiate between things that need to be tested against Elasticsearch APIs in the Elasticsearch build and things that need to be tested against the Kibana APIs (we need to determine where these ones should be tested and how)

**Comment by nik9000** [comment]
I think using `// KIBANA` is a quick and dirty fix that might be appropriate temporarily. It renders how we want it to render if though it does it for the wrong reasons. That isn't great but I can live with it in the short run if we have to.

Personally I'd prefer Kibana fix the DELETE APIs soon. I know HTTP doesn't particularly like DELETE-with-a-body, but Elasticsearch has them and Kibana *is* Elasticsearch's dev console so it should support them. Or Elasticsearch should stop using them. I'd prefer that, actually, but I don't image it'll happen. Either way, I don't think we should build an entirely new concept in the docs because of a bug in Kibana.

**Comment by bmcconaghy** [comment]
I think we should call the option `CURL_ONLY`, then the semantics are clear and we're not using the `KIBANA` option on ES APIs.

**Comment by jrodewig** [comment]
Closing.

Superseded by https://github.com/elastic/docs/issues/1238
