### ISSUE TITLE
SolrToES schema migration tool

### ISSUE THREAD

**Issue by wisienka91** [elastic/elasticsearch#39696]
It would be great to have a schema migration tool from Solr to ElasticSearch. Tool features required:

- take Solr schema.xml and solrconfig.xml files as input,
- handle (at least some basic) Solr analyzers,
- generate .json mappings file out of provided input,
- basically every functionality more than described above would be great.

**Comment by jimczi** [comment]
I doubt that we should provide this as part of the official distribution. Maybe this can be done as a plugin where you generate a mapping file from a schema.xml but this require to know Solr in depth which I doubt is the case here ;).

**Comment by scherziglu** [comment]
@jimczi I could support on this. I worked with Solr a couple of years

**Comment by wisienka91** [comment]
Hi there! How to read the `team-discuss` label removed without no further notice? Any updates on the issue?

**Comment by giladgal** [comment]
Thank you for raising this suggestion. 

While we acknowledge this tool will be useful to customers migrating to Elastic from Solr, we would rather have the community develop something like that. The reason is that there could potentially be multiple configurations, versions, etc. to support. Since there is probably a wide variety of cases, we may end up either supporting just a small subset of cases that are similar to some default that we assume or constantly firefighting edge cases that we were not aware of, because, at the end of the day, we only control one side of this equation.

If you or others in the community will develop such a tool, we will happily assist in advice or in answering questions on the forum. You may also consider the option to develop SolrToES migration documentation in addition or even instead of a migration tool. Such documentation will for sure help professionals performing SolrToES migration while allowing them to find specific solutions for their unique data, configuration, version, etc.
