### ISSUE TITLE
[Feature Request] - Reinstate delete index by alias / add alias to alias

### ISSUE THREAD

**Issue by JulianRooze** [elastic/elasticsearch#39818]
I'm working on upgrading our Elasticsearch 5 cluster to Elasticsearch 6 and I'm running into an issue with the changes to what you are allowed to do with an alias and I'd like to make the case for this to be reinstated to how this used to work (at least opt-in). The [changes](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/breaking_60_indices_changes.html#_indices_aliases_api_resolves_indices_expressions_only_against_indices) I'm referring to are:

- No longer being able to delete one or more indices using an alias.
- No longer being able to add an alias to an alias.

The fact that an alias behaved transparently like an index in nearly every way was one of the great things about them. This change will, at least for us, only result in a bunch of extra checks and corner cases without any benefit. The way this worked in ES5 was intuitive and simple, the logic of determining whether something was an index, an alias or multiple indices was left to Elasticsearch, but ES6 makes it your problem again.

Moreover, I would argue that this change is not internally consistent, as doing a `GET my_alias` is a valid operation, that still behaves the same as doing a `GET my_index` in every way, like it is in ES5, but following that up with a `DELETE my_alias` results in a Bad Request. The only way to know that this seemingly valid operation results in an error is either knowing that `my_alias` is an alias (our code doesn't know because it doesn't care about this) or by comparing the name of what the `GET` returned to what you sent in. The same goes for doing a `HEAD my_alias` which still returns OK. From a REST point of view, if you can `GET` a resource then you should be able to `DELETE` that resource too, but this is not the case, the `DELETE` operation for *some* cases (aliases) actually lives on a *different* resource (`_aliases/`). 

While this change can be worked around, it still feels bad because before the code felt elegant, but now I have to add a bunch of checks in places where we delete an index, but where I frankly don't know or care (before) if it's an alias or an actual index. 

Some use cases have become non-trivial because of this change. One example is where we add a `indices_to_delete` alias to an index right before we delete it. This was a nice solution to the problem of transient errors with deleting an index (such as an index being snapshotted at the time of deletion) whereby a scheduled task (or the Curator) can periodically clean up indices that couldn't be deleted before with a simple `DELETE indices_to_delete`.  Now, this involves at least two roundtrips and the involvement of a JSON parser. 

Being able to use aliases as flexibly as you could in ES5 was part of what put the *Elastic* into Elasticsearch for us. I would like to see the behavior reverted to the old behavior, if necessary by a YAML setting.

**Comment by jasontedor** [comment]
Thanks for the well-written feature request @JulianRooze. I empathize with your position, but ultimately we will not implement either of these requests. I will explain.

> No longer being able to delete one or more indices using an alias.

We considered deleting aliases to be trappy, and we removed the functionality. The reason that this is trappy is because does `DELETE /alias` delete the alias, or delete the concrete index behind the alias? Some users reason that it would delete only the alias, and not the index (or indices!) behind the alias. That made this API trappy. And if you try to argue that it should delete the index, what happens if the alias is a *filtered alias* on top of some index? Would we do a delete-by-query behind the scenes, or delete the index, or reject the request? Again, this is trappy. See #2318.

> No longer being able to add an alias to an alias.

I could be wrong (please, correct me if I am!), but I don't think this was ever a feature. The reason that I think this was never a feature is because of how aliases are implemented in Elasticsearch. Namely, aliases are attached metadata attaches to indices. For an alias on an alias, where would we attach the second alias? We can not attach it to the first alias (that is not how they work), and we would not attach it to the underlying index (for then how would we know it was attached to the first alias). 

>Being able to use aliases as flexibly as you could in ES5 was part of what put the Elastic into Elasticsearch for us. I would like to see the behavior reverted to the old behavior, if necessary by a YAML setting.

Over the years we have tried to remove trappy features, and we do not favor hiding trappy features behind configuration flags. That leads to a complex feature set and a complex codebase. We are preferring to keep our APIs simpler, and our implementations as simple as possible. That makes our system easier to reason about for us, and our users, which gives us a nimbler codebase on which to build more exciting features.

**Comment by JulianRooze** [comment]
Thanks for the quick and elaborate reply. I understand and respect your decision and I expected as much, but I wanted to argue in favor if it regardless :)

> The reason that this is trappy is because does DELETE /alias delete the alias, or delete the concrete index behind the alias?

Personally, I've never considered the possibility that `DELETE my_alias` would only delete the alias itself and not the underlying indices. When you do that DELETE, it's on the "index" resource and to me it's always been entirely expected that doing a DELETE on an index resource deletes an index and an alias is just a name for one or more indices, so to me it makes sense that it deletes indices.

I can see that doing a delete on an alias could be dangerous, but then again, all deletes are inherently dangerous. 

> And if you try to argue that it should delete the index, what happens if the alias is a filtered alias on top of some index?

In the end, all abstractions are leaky, but it feels like throwing out the baby with the bathwater. 

> I could be wrong (please, correct me if I am!), but I don't think this was ever a feature. 

What I mean is that when you do `PUT _aliases`, you could specify an alias as the index on which to apply the alias. So:

```
PUT _aliases
{
    "actions": [
       {
          "add": {
             "index": "my_alias1",
             "alias": "my_alias2"
          }
       }
    ]
}
```

And if `my_alias1` is an alias for `my_index`, it would receive a second alias, `my_alias2`.
