### ISSUE TITLE
Change pre_filter_shard_size default to 1 for frozen index searches

### ISSUE THREAD

**Issue by timroes** [elastic/elasticsearch#39835]
We have currently an open issue in Kibana (https://github.com/elastic/kibana/issues/32742) about setting `pre_filter_shard_size` to `1` for all requests in case you want to query frozen indexes. This caused a couple of questions I am copying over from the other issue:

> As far as I understand the documentation, the pre-filtering phase does not have any "significant overhead". Why is this value 128 by default, and not by 1? If there is no significant overhead, but we know that especially when including frozen index, we'll gain a lot of performance benefit, what's the reason of not enabling that phase by default? Since we would set this to 1 in every request (since we don't know if it includes a frozen index or not), once you enabled querying frozen indexes in the advanced setting, I would really like to understand the drawbacks of setting this to 1.

Would it potentially make more sense, setting this by default to `1` on the Elasticsearch side once `ignore_throttled=false` is set. Or maybe ES would even be possible to determine if an frozen index will be hit by a query and then using that appropriate value? Or (much of the question on top): Could that potentially be `1` for all requests, what are the drawbacks there?

**Comment by jimczi** [comment]
Since we reverted #42510 I think it makes sense to re-evaluate a simple solution to automatically execute the can match phase despite the default. This shouldn't be an issue going forward in Kibana since they plan to use the new async search which sets the `pre_filter_shard_size` to  1 by default but we should make the change in blocking `_search` nevertheless. We've improved the handling of queries on frozen indices that didn't run the can match phase by avoiding the usage of the throttled [search thread pool](https://github.com/elastic/elasticsearch/pull/51708) on shards that cannot match the date range filter so it shouldn't be required to run the can match phase for these indices anymore. However the `can_match_phase` is now also used to [pre-sort shards on sorted queries](https://github.com/elastic/elasticsearch/pull/49092) so we could automatically run this phase if it can [optimize the query phase](https://github.com/elastic/elasticsearch/pull/51852) significantly.
@javanna WDYT ?

**Comment by javanna** [comment]
heya @jimczi what do you mean with "automatically execute the can match phase despite the default"?

**Comment by jimczi** [comment]
Defaulting to a static value of `128` is not flexible enough so today we require our users to set this value correctly. What I meant is that we should consider the default (`pre_filter_shard_size` is not present in the request) dynamic in order to be able:
- Automatically run the can_match phase if frozen indices are part of the query
  - or if a primary field sort is used (sort by a field).
  - ... (we can add more conditions here)

Users would be able to opt-out by setting `pre_filter_shard_size` to a static value in their requests but that shouldn't be needed in the majority of cases.

**Comment by javanna** [comment]
++ to having a more dynamic default, good idea @jimczi . We could then probably open a discussion on the need for the request parameter, and whether it still needs to be a threshold based on number of shards. Maybe it should become something to force enabling/disabling the execution of the can match phase.
