### ISSUE TITLE
Stopwords not filtered in simple_query_string with default operator AND and multiple analyzers

### ISSUE THREAD

**Issue by xrammit** [elastic/elasticsearch#39905]
I use the official docker image: `docker.elastic.co/elasticsearch/elasticsearch:6.6.1`

**Elasticsearch version** (`bin/elasticsearch --version`): 
```
Version: 6.6.1, Build: default/tar/1fd8f69/2019-02-13T17:10:04.160291Z, JVM: 11.0.1
```

**Plugins installed**: nothing besides the default ones (`[ingest-geoip, ingest-user-agent]`)

**JVM version** (`java -version`):
```
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system):
```
Linux d76a7dabcb27 4.18.0-16-generic #17-Ubuntu SMP Fri Feb 8 00:06:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Description of the problem including expected versus actual behavior**:

Related issues described in #34708, #28855 and #33009. When I execute a simple_query_string query with the following conditions

* the queried index is configured to analyze the documents with language-specific stopword filters depending on the document field names via dynamic templates (e.g. fields `*_text_en` -> analyzed with English stopword filter; fields `*_text_de` -> analyzed with German stopword filter); the `search_analyzer` equals to the `analyzer`
* the queried index contains at least one document analyzed by each (language-specific) analyzer
* the query has fields of both analyzers configured (e.g. `['*_text_*']` or `['*_text_en', '*_text_de']`)
* the `default_operator` is AND

the document is found when searching without a stopword (cf. query for "Frankfurt Main" in step 3 of the following sample) but it's not found when adding a stopword to the query (cf. query for "Frankfurt am Main" in step 4 of the following sample) although the `search_analyzer` should filter the stopword and the query should return the same documents as without the stopwords.

**Steps to reproduce**:

Minimal sample:

 1. Create new index `mytest` with template

```
curl -XPUT -H "Content-Type: application/json" localhost:9200/mytest -d '{
  "settings": {
    "analysis": {
      "filter": {
        "english_stop": {
          "type": "stop",
          "stopwords": "_english_"
        },
        "german_stop": {
          "type": "stop",
          "stopwords": "_german_"
        }
      },
      "analyzer": {
        "my_english_analyzer": {
          "tokenizer": "standard",
          "filter": ["english_stop"]
        },
        "my_german_analyzer": {
          "tokenizer": "standard",
          "filter": ["german_stop"]
        }
      }
    }
  },
  "mappings": {
    "_doc": {
      "dynamic": true,
      "dynamic_templates": [
        {
          "english_text": {
            "match": "*_text_en",
            "mapping": {
              "type": "text",
              "analyzer": "my_english_analyzer",
              "search_analyzer": "my_english_analyzer"
            }
          }
        },
        {
          "german_text": {
            "match": "*_text_de",
            "mapping": {
              "type": "text",
              "analyzer": "my_german_analyzer",
              "search_analyzer": "my_german_analyzer"
            }
          }
        }
      ]
    }
  }
}'
```

 2. Add two documents 

```
curl -XPUT -H "Content-Type: application/json" localhost:9200/mytest/_doc/1 -d '{
  "title_text_de": "Frankfurt am Main",
  "content_text_de": "Frankfurt am Main ist die fünftgrößte Stadt Deutschlands."
}'
```

```
curl -XPUT -H "Content-Type: application/json" localhost:9200/mytest/_doc/2 -d '{
  "title_text_en": "London",
  "content_text_en": "London is the capital city of the United Kingdom."
}'
```

 3. Search for "Frankfurt Main" with `default_operator` AND on all fields (`*_text_*`)

```
curl -XPOST -H "Content-Type: application/json" localhost:9200/mytest/_search -d '{
  "query": {
    "simple_query_string" : {
      "query": "Frankfurt Main",
      "fields": ["*_text_*"],
      "default_operator": "and"
    }
  }
}'
```

The response contains the document with id 1 as expected.

 4. Search again but add the (German) stopword "am" to the query

```
curl -XPOST -H "Content-Type: application/json" localhost:9200/mytest/_search -d '{
  "query": {
    "simple_query_string" : {
      "query": "Frankfurt am Main",
      "fields": ["*_text_*"],
      "default_operator": "and"
    }
  }
}'
```

Now the response contains no document although I expected to find the document with id 1 again as the stopword "am" should be filtered in the search query. The search result is empty as well when using other German stopwords instead of "am" (e.g. "im", "über" etc) or re-ordering the search terms (e.g. "Frankfurt Main am").

Now the response contains the document with id 1 as expected. The same holds for searches with other German stopwords or re-ordering the search terms.

**Provide logs (if relevant)**:
no relevant logs

**Comment by jporzelt** [comment]
This bug also affects me in a customer project. 
Thank you for the detailed description!

**Comment by jimczi** [comment]
While the other issues you linked were actual bugs I don't think that this one should be labelled as such. Let me explain why. The `simple_query_string` treats whitespaces as operator by default, this means that the query `Frankfurt am Main` is splitted into `Frankfurt`, `am`, `Main` prior to analysis. 
The analysis part consists of building one query for each field using the analyzer defined on the field. These queries are then merged in a disjunction (e.g.: `title_en:frankfurt OR title_de:frankfurt) and finally the disjunctions are combined to create the root query (e.g.:  `(title_en:frankfurt OR tile_de:frankfurt) AND (title_en:am OR tile_de:am) ...`). Since you're searching on different languages I don't think you should mix the fields based on whitespace but rather build one query per analyzer. That's what we call the `cross_fields` mode in the `multi_match` query:
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html#type-cross-fields
Switching to this mode will create one query per analyzer (language) resulting in something like:
````
((+(title_text_en:Frankfurt | content_text_en:Frankfurt) +(title_text_en:am | content_text_en:am) +(title_text_en:Main | content_text_en:Main)) | (+(title_text_de:Frankfurt | content_text_de:Frankfurt) +(title_text_de:Main | content_text_de:Main)))
````
which is what I'd expect from a query that targets different languages ?

**Comment by jporzelt** [comment]
Thank you @jimczi  for the explanation. 
So is this then the same if I would split up the query in should clauses of a boolean query like (using the example from above):
```
curl -XPOST -H "Content-Type: application/json" localhost:9200/mytest/_search?pretty -d '{
  "query": {
    "bool": {
      "should": [
        {
          "simple_query_string": {
            "query": "Frankfurt am Main",
            "fields": [
              "content_text_de"
            ],
            "default_operator": "and"
          }
        },
        {
          "simple_query_string": {
            "query": "Frankfurt am Main",
            "fields": [
              "content_text_en"
            ],
            "default_operator": "and"
          }
        },
        {
          "simple_query_string": {
            "query": "Frankfurt am Main",
            "fields": [
              "title_text_de"
            ],
            "default_operator": "and"
          }
        },
        {
          "simple_query_string": {
            "query": "Frankfurt am Main",
            "fields": [
              "title_text_en"
            ],
            "default_operator": "and"
          }
        }
      ]
    }
  }
}'
```

This seems to work. This still supports the Boolean operators (that's why I'm using the `simple_query_string`) and handle stop words correctly. 

Do you see any problem with this approach?

**Comment by jimczi** [comment]
Yes this approach would work, the other solution if you still want to use a single `simple_query_string` with multiple fields is to disable the whitespace operator by setting the [`flag` option](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html#supported-flags) like this:
````
"simple_query_string" : {
            "query" : "Frankfurt am Main",
            "flags" : "OR|AND",
            "fields": ["*_text_*"],
        }
````

**Comment by xrammit** [comment]
Thanks @jimczi and @jporzelt for the explanation and the suggested solutions!

**Comment by tinhte96** [comment]
if i remove whitespace operator like @jimczi mentionned above, the prohibited clause seems not work anymore, even i add an extra (+) before (-). There are a closed issue about this, but the problem seems still there https://github.com/elastic/elasticsearch/issues/9633 . I also posted my question in elastic forum https://discuss.elastic.co/t/simple-query-string-minus-doesnt-work-if-whitespace-not-specified-in-flags/237347
