### ISSUE TITLE
[ML] Handle large number of DataFrame transforms in internal logic

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#39994]
There are certain interactions within the new `data-frame` plugin that looks for ALL transforms. This will cause pain in the future without paginating, scrolling, or aggregating the results. 

One location in particular is `DataFrameFeatureSet#Usage`. 

The rest of the `data-frame` plugin code needs to be explored to verify there are no other trip-ups that would cause an issue where we have >10k DataFrameTransformConfigs.

Interactions via the API will require paginating parameters (with sane defaults) to avoid similar issues with external user interactions.

**Comment by hendrikmuhs** [comment]
This is not a bug (already per definition of an unreleased feature), we should disallow requesting a large number of transforms. There is simply no usecase to get 10k configs using 1 request.

The number of transforms of per page should be limited. Even if possible, it's bad from a design as the memory requirement for returning this large number puts the rest of the system at risk to go out of memory. If you really have a lot of transforms you can use paging, a page should not return more than 500 configs per page. 

I agree that `DataFrameFeatureSet#Usage` is broken at the moment, but the fix is to rewrite stats gathering and not introduce paging for it. `Usage` accumulates stats, we can use aggregations to retrieve those.
