### ISSUE TITLE
[DOCS] Update docs for routing & seq no 

### ISSUE THREAD

**Issue by kunisen** [elastic/elasticsearch#40027]
Currently we have `routing` documented here.
https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-routing-field.html

Which describes that `shard_num` depends on this formula.
`shard_num = hash(_routing) % num_primary_shards`

IIRC, it is coded in this src.
https://github.com/jpountz/elasticsearch/blob/38a384de5c31ed594ddc79b31e431c0eb73d0d17/src/main/java/org/elasticsearch/cluster/routing/operation/plain/PlainOperationRouting.java#L284

However, after having Seq_no introduced, the above src changed and no longer could I find the "hash and %".
https://github.com/elastic/elasticsearch/commit/d896886973660785aac45275ddb110c1a6babc57

But more likely to be a hash related to `indexMetaData.getRoutingNumShards()) / indexMetaData.getRoutingFactor()`, which is described in the folllowing src.
https://github.com/elastic/elasticsearch/blob/6.6/server/src/main/java/org/elasticsearch/cluster/routing/OperationRouting.java#L312
https://github.com/elastic/elasticsearch/blob/6.6/server/src/main/java/org/elasticsearch/cluster/metadata/IndexMetaData.java#L1450

I couldn't find documentation regarding this.
Could we have this update getting documented in somewhere please?

**Comment by ywelsch** [comment]
This generalization of the formula related to the [shrink](https://www.elastic.co/guide/en/elasticsearch/reference/6.7/indices-shrink-index.html) / [split](https://www.elastic.co/guide/en/elasticsearch/reference/6.7/indices-split-index.html) functionality. 

Shrinking is efficiently implemented by directly combining and merging Lucene segments from different shards. When shrinking an index from 10 to 5 primary shards, for example, shards 0 and 1 from the old index get merged into shard 0 of the new index, shards 2 and 3 of the old index are merged into shard 1 of the new index, etc. This way of combining old shards into new shards, while extremely efficient, means however that the documents no longer belong to the right shard if you were to apply the simple `shard_num = hash(_routing) % num_primary_shards` formula to this new index with only 5 primary shards. If document "xyz" was previously routed to shard 3 in the old index, it now needs to route shard 1 in the new index. To achieve this, the routing is now calculated as if the new index would still have 10 shards (this is the `num_routing_shards` value), which gives you a number between 0 and 9, and then we account for the factor by which we shrunk the original index, by dividing by 2 (`routingFactor`, which is 10 / 5 = 2), giving us a number between 0 and 4. The original formula therefore becomes `shard_num = (hash(_routing) % num_routing_shards) / routing_factor`.

Splitting is also efficiently implemented again using similar tricks (see split docs). When splitting an index from 5 to 10 primary shards, for example, shard 0 from the old index is split into shards 0 and 1 of the new index, shard 1 of the old index is split into shards 2 and 3 of the new index, etc. This way of splitting shards into new shards, while extremely efficient, means however that the documents no longer belong to the right shard if you were to apply the simple `shard_num = hash(_routing) % num_primary_shards` formula to this new index with 10 primary shards (same story as for shrinking). If document "xyz" was previously routed to shard 1 in the old index, it now needs to route to shard 2 or shard 3 in the new index. We need it to be either 2 or 3, though, using a deterministic formula. This is achieved with the following trick. Assume that the shard that we are splitting from 5 to 10 shards had previously been shrunk from 10 to 5 shards. In that case the shrunken index would be using `num_routing_shards = 10` and `routing_factor = 2`. By adapting the `routing_factor` from 2 to 1, the split index with 10 shards would map documents again in the same way as the original index with 10 shards. The key observation here is that if we have a large enough `num_routing_shards` value, we can easily split shards by adapting the `routing_factor`.

While Elasticsearch 6.x requires you to specify a high enough `num_routing_shards` value at index creation time in order to do splitting for that index, Elasticsearch 7.x [chooses a large default value](https://github.com/elastic/elasticsearch/blob/83e9d0b9c63589f1dc5bda8abb6b10b27502ef71/server/src/main/java/org/elasticsearch/cluster/metadata/MetaDataCreateIndexService.java#L820-L836) for this at index creation time that is designed to allow you to split this index by factors of 2 up to a maximum of 1024 shards (see docs for split in 6.x and 7.x).

This means that for an ES 7.x index with 10 primary shards and default settings, the document "xyz" will possibly be mapped to a different shard than for an ES 6.x index with 10 primary shards and default settings, as 6.x indices use `num_routing_shards = num_primary_shards` as the default, which allows the formula `shard_num = (hash(_routing) % num_routing_shards) / routing_factor` to be a generalization of the original `shard_num = hash(_routing) % num_primary_shards` formula.

@kunisen I hope this explanation helps with understanding the formula in the code (I've tried to keep it as concise as I could, and am happy to elaborate on some of these parts more if you want). I'm not sure yet how and where to document this generalization of the formula, given that the additional complexity of the generalized formula might cause more confusion to a reader than the simplified one and requires a bit more context to explain.

**Comment by kunisen** [comment]
Very clear explanation and no any doubts now!
Thanks for the great write up!
I think it’s important to have experts explained this but not just I read something from code, and now my goal is achieved.
Really appreciate your help! @ywelsch

**Comment by debadair** [comment]
[docs issue triage]

**Comment by kunisen** [comment]
thanks again and close the ticket
