### ISSUE TITLE
Rollup jobs disappeared after data nodes disk resize

### ISSUE THREAD

**Issue by jasondu168** [elastic/elasticsearch#40066]
**Elasticsearch version** (`bin/elasticsearch --version`):
```Version: 6.5.2, Build: default/rpm/9434bed/2018-11-29T23:58:20.891072Z, JVM: 1.8.0_201```
**Plugins installed**: []
```xpack```
**JVM version** (`java -version`):
```
openjdk version "1.8.0_201"
OpenJDK Runtime Environment (build 1.8.0_201-b09)
OpenJDK 64-Bit Server VM (build 25.201-b09, mixed mode)
```
**OS version** (`uname -a` if on a Unix-like system):
```
OS:CentOS Linux release 7.6.1810 (Core) 

uname:Linux 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64
libc:glibc 2.17 NPTL 2.17 
```
**Description of the problem including expected versus actual behavior**:
Some rollup jobs disappeared after server data nodes disks resized to larger size on AWS. 
Where are these rollup jobs saved? Will disk resize cause this issue? Is there anyway to back rollup jobs? By the way, no index data lost.

**Steps to reproduce**:
Resize the disks on the fly on AWS, ES was running all the time while this was happening.

**Provide logs (if relevant)**:
N/A

**Comment by polyfractal** [comment]
Were these active and running jobs, or archived/deleted jobs?  How did you determine they were lost (`tasks` API?  get rollup jobs API?  Kibana UI?).

And was this the AWS ES service, or your own nodes on EC2 that you resized?

To answer your questions, jobs are persisted in two locations.  All active jobs are recorded in the cluster state as a persistent task, so that we can keep the task alive between node restarts, etc.  This is basically a record of the job's config, it's current position/status, the node running the task, etc.

The data generated by a job (including jobs that are no longer running) are stored in `rollup_index` as configured by the job.  So if you configured `rollup_index: foo`, all the data generated by the job will be stored in the `foo` index.  If that index is deleted for some reason, you'll lose the data stored there just like any other index.

Regarding backups, normal snapshot/restore mechanisms will backup rollups (both the data in indices, and the cluster state).

**Comment by jdu-mydevices** [comment]
Were these active and running jobs, or archived/deleted jobs? How did you determine they were lost (tasks API? get rollup jobs API? Kibana UI?).
  -> `These are active, started and rollup finished jobs. Disappeared from Kibana UI -> Management -> Rollup jobs`

And was this the AWS ES service, or your own nodes on EC2 that you resized?
  ->  `my own nodes on EC2`

To answer your questions, jobs are persisted in two locations. All active jobs are recorded in the cluster state as a persistent task, so that we can keep the task alive between node restarts, etc. This is basically a record of the job's config, it's current position/status, the node running the task, etc.

The data generated by a job (including jobs that are no longer running) are stored in rollup_index as configured by the job. So if you configured rollup_index: foo, all the data generated by the job will be stored in the foo index. If that index is deleted for some reason, you'll lose the data stored there just like any other index.

Regarding backups, normal snapshot/restore mechanisms will backup rollups (both the data in indices, and the cluster state).
  ->  `Thanks! We didn't loss rollup indices this time. For those rollup jobs, they are finished jobs. It's not a problem for me, I just want to report this issue.`

**Comment by wchaparro** [comment]
With the 8.7 release of Elasticsearch, we have made a [new downsampling capability](https://www.elastic.co/guide/en/elasticsearch/reference/current/downsampling.html) associated with the new [time series datastreams](https://www.elastic.co/guide/en/elasticsearch/reference/current/tsds.html) functionality generally available (GA). This capability was in tech preview in ILM since 8.5.  Downsampling provides a method to reduce the footprint of your time series data by storing it at reduced granularity. The downsampling process rolls up documents within a fixed time interval into a single summary document. Each summary document includes statistical representations of the original data: the min, max, sum, value_count, and average for each metric. Data stream time series dimensions are stored unchanged. 

Downsampling is superior to rollup because:

- Downsampled indices are searched through the _search API
- It is possible to query multiple downsampled indices together with raw data indices
- The pre-aggregation is based on the metrics and time series definitions in the index mapping so very little configuration is required (i.e. much easier to add new time serieses)
- Downsampling is managed as an action in ILM
- It is possible to downsample a downsampled index, and reduce granularity as the index ages
- The performance of the pre-aggregation process is superior in downsampling, as it builds on the time_series index mode infrastructure

Because of the introduction of this new capability, we are deprecating the rollups functionality, which never left the Tech Preview/Experimental status, in favor of downsampling and thus we are closing this issue. We encourage you to migrate your solution to downsampling and take advantage of the new TSDB functionality.
