### ISSUE TITLE
Multi Match Query documentation points to a dead end

### ISSUE THREAD

**Issue by Ingramz** [elastic/elasticsearch#40091]
On [Multi Match Query](https://www.elastic.co/guide/en/elasticsearch/reference/6.6/query-dsl-multi-match-query.html) page, there's a line:

Also, accepts `analyzer`, `boost`, `lenient`, `slop` and `zero_terms_query`  as explained
in [Match Query](https://www.elastic.co/guide/en/elasticsearch/reference/6.6/query-dsl-match-query.html).

However when navigating to the Match Query page, there is no mention of either `boost` or `slop`.

**Comment by martijnvg** [comment]
So phrase queries are performed with [match phrase query](https://www.elastic.co/guide/en/elasticsearch/reference/6.6/query-dsl-match-query-phrase.html) and not with the match query. The `boost` parameter is missing from the documentation page of match query (also match phrase and match phrase prefix query documentation).

**Comment by matriv** [comment]
Backported to `7.x` with eab88354f20f9a93f02ee350ab1dcec0c09fc4e1
to `7.2` with b257a18349885536eed67482b7e673ce43494bad
to `7.1` with 22541f6b4d2fed1f13798525991b22b65c9f932e
to `6.8` with 30150b4e89a7d06d7d275533807edccbec90c6e3

**Comment by andreidiaconescu** [comment]
- this issue is about "Multi Match Query documentation" and that "boosting documentation points to a dead end";
 - this issue is still true today: 
 - in the Multi Match documentation: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html it is written more than once: "Also, accepts analyzer, boost, lenient and zero_terms_query as explained in [Match](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query.html)" but the Match documentation does not mention boost at all

**Comment by abdonpijpelink** [comment]
Thanks for reporting this @andreidiaconescu . I've opened https://github.com/elastic/elasticsearch/issues/97441 to improve the documentation.
