### ISSUE TITLE
HEAD variant of get indices aliases api hangs/blocks indefinitely

### ISSUE THREAD

**Issue by floragunncom** [elastic/elasticsearch#40114]
**Elasticsearch version** (`bin/elasticsearch --version`):
6.5.1+6.5.4 (and possibly others)

**Plugins installed**: []

**JVM version** (`java -version`):
n/a

**OS version** (`uname -a` if on a Unix-like system):
n/a

**Description of the problem including expected versus actual behavior**:
```curl -XGET http://localhost:9200/myindex/_alias``` works as expected but 
```curl -XHEAD http://localhost:9200/myindex/_alias/*``` hangs/blocks indefinitely.

Documentation says that HEAD should also be working -> https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html

**Steps to reproduce**:
```curl -XHEAD http://localhost:9200/myindex/_alias/*``` or ```curl -XHEAD http://localhost:9200/myindex/_alias``` against a cluster where a non-empty index ```myindex``` exists and at least one alias is defined for an index ```myindex```

**Comment by floragunncom** [comment]
Seems more like a glitch in the docs. After more investigation adding ```-I``` or ```--head``` to curl seems to make it work.

**Comment by jasontedor** [comment]
Thanks for reporting!

This is unfortunate but known behavior for `curl`. When you send a `HEAD` request for `curl` via `-X HEAD` curl sends the `HEAD` method, but it acts like a `GET` so it sits there waiting for `Content-Length` bytes to arrive`. Since the server saw a `HEAD` request though, it would never send these bytes and `curl` will hang indefinitely waiting for them. As you've discovered, the correct way to send a `HEAD` request via `curl` is with `-I` or `--head`.

That said, there is a bug in our docs here which is that copy-as-curl functionality should treat `HEAD` specially, like `curl` needs it to be. I have opened elastic/docs#731. Since there is nothing actionable on this repository that can be taken, I will close this issue. If you want to track progress of us fixing our docs, you can do so on elastic/docs#731. We will have the fix deployed soon.

**Comment by jasontedor** [comment]
Also, note the warning here:

```
Warning: Setting custom HTTP method to HEAD with -X/--request may not work the 
Warning: way you want. Consider using -I/--head instead.
```
