### ISSUE TITLE
SQL: CAST failures for float value

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#40282]
The following CASTs of a float value lead to failures:
* `SCALED_FLOAT`:
```
sql> select cast('0.' as SCALED_FLOAT);
Bad request [line 1:22: Does not recognize type [SCALED_FLOAT]]
```
* same for `HALF_FLOAT`;
* any integer type:
```
sql> select cast('0.0' as long);
Server error [Server encountered an error [cannot cast [0.0] to [long]]. [SqlIllegalArgumentException[cannot cast [0.0] to [long]]; nested: NumberFormatException[For input string: "0.0"];
```

**Comment by costin** [comment]
There are two issues here:
1. Indeed CAST accepts some ES data types but not all and that's inconsistent, I've got a fix for this already.
2. There are two issues here:

2a. one that the underlying exception gets propagated without being checked (this is a bug)
2b. not sure whether '0.0' to long should succeed or not since 0.0 is not an int. Basically the command implies two conversions - 0.0 (string to float) and then float to int. Checking quickly indicates that postgres does not support this and I propose we do the same.

Thoughts @astefan @matriv ?
