### ISSUE TITLE
Remove explicit non needed deps from generated pom.xml

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#40308]
In the `x-content` module we have explicitly declared a dependency on `snakeyaml`. See https://github.com/elastic/elasticsearch/blob/ddddbdfe6dffbac458d4d6997931271cf6d8fa85/libs/x-content/build.gradle#L37

But we are never using that library explicitly in our source code. That's a transitive dependency needed by `jackson-dataformat-yaml` I guess. 

The problem I'm facing is that in my project I'm depending on `elasticsearch-rest-high-level-client:7.0.0-beta1`:

```
+-fr.pilato.elasticsearch.crawler:fscrawler-elasticsearch-client-v7:2.7-SNAPSHOT
  +-org.elasticsearch.client:elasticsearch-rest-high-level-client:7.0.0-beta1
    +-org.elasticsearch:elasticsearch:7.0.0-beta1
      +-org.elasticsearch:elasticsearch-x-content:7.0.0-beta1
        +-org.yaml:snakeyaml:1.17
```

In the generated `pom.xml` (see https://search.maven.org/artifact/org.elasticsearch/elasticsearch-x-content/7.0.0-beta1/jar), we are explicitly depending on `snakeyaml`:

```xml
    <dependency>
      <groupId>org.yaml</groupId>
      <artifactId>snakeyaml</artifactId>
      <version>1.17</version>
      <scope>compile</scope>
    </dependency>
```

If I want to depend in my project on another jackson version (2.9.8), I must explicitly set as well `snakeyaml` dependency manually which IMHO breaks the transitive dependency management principe.

If we remove this explicit dep, my project dependency tree could become then:

```
+-fr.pilato.elasticsearch.crawler:fscrawler-elasticsearch-client-v7:2.7-SNAPSHOT
  +-org.elasticsearch.client:elasticsearch-rest-high-level-client:7.0.0-beta1
    +-org.elasticsearch:elasticsearch:7.0.0-beta1
      +-org.elasticsearch:elasticsearch-x-content:7.0.0-beta1
        +-com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.8.11
          +-org.yaml:snakeyaml:1.17
```

And if I decide to depend on jackson 2.9.8 instead, that will become automatically:

```
+-fr.pilato.elasticsearch.crawler:fscrawler-elasticsearch-client-v7:2.7-SNAPSHOT
  +-org.elasticsearch.client:elasticsearch-rest-high-level-client:7.0.0-beta1
    +-org.elasticsearch:elasticsearch:7.0.0-beta1
      +-org.elasticsearch:elasticsearch-x-content:7.0.0-beta1
        +-com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.9.8
          +-org.yaml:snakeyaml:1.23
```

Can we exclude in the generated `pom.xml` this dependency?

**Comment by mark-vieira** [comment]
> But we are never using that library explicitly in our source code. That's a transitive dependency needed by jackson-dataformat-yaml I guess.

Then it should actually be declared as `runtimeOnly` since we don't need this at compile time.

> If I want to depend in my project on another jackson version (2.9.8), I must explicitly set as well snakeyaml dependency manually which IMHO breaks the transitive dependency management principe.

If this is the case then I assume you are using Maven, which has different transitive dependency semantics than Gradle. It is preferring the "nearest" dependency rather than the newest one.

> Can we exclude in the generated pom.xml this dependency?

Unfortunately no, as this would then break anyone that depends on this library that _doesn't_ also explicitly bring in snakeyaml through some other means.

Could a workaround for you be to simply exclude snakeyaml in your POM when depending on `x-content`?

```xml
<dependency>
  <groupId>org.elasticsearch</groupId>
  <artifactId>elasticsearch-x-content</artifactId>
  <version>7.0.0-beta1</version>
  <exclusions>
    <exclusion>
      <groupId>org.yaml</groupId>
      <artifactId>snakeyaml</artifactId>
    </exclusion>
  </exclusions>
</dependency>```

**Comment by dadoonet** [comment]
Thanks @mark-vieira for your answer.

> Unfortunately no, as this would then break anyone that depends on this library that doesn't also explicitly bring in snakeyaml through some other means.

Which is a bad practice IMHO.
I mean that in someone has in its code an `import` using `xyz` library, then he should always declare it explicitly. ie. let say the lib maintainer decides to remove completely using this lib and use its own implementation, the project won't compile anymore as soon as you're upgrading the lib.

> Could a workaround for you be to simply exclude snakeyaml in your POM

Of course. By no mean, I said it is a blocker.
I'm definitely working around that but I find weird having to declare a dependency I'm not using explicitly. I can of course change the order of the libs I'm using in the maven pom which IIRC would "solve" the "problem".

So feel free to close this issue if we don't intend to fix that for Maven users at least.

**Comment by mark-vieira** [comment]
> I mean that in someone has in its code an import using xyz library, then he should always declare it explicitly.

This is exactly what we are doing, which is what is causing this issue to begin with. We don't rely on transitive dependencies in any of our projects. We explicitly declare all dependencies. So rather than rely on Jackson bringing in snakeyaml we exclude all transitive dependencies (thus the excludes in our generated POM) and explicitly declare snakeyaml as a direct dependency. 

The problem you are running into is the way that Maven prefers versions when encountering a conflict. It chooses the version for the dependency it encounters _closest_ in the dependency graph. FWIW, you would still encounter this problem of yours even if we excluded our snakeyaml dependency and relied on transitive dependency management depending on _where_ the conflicting dependency was found in your dependency graph Maven might still prefer the version we brought in.

Due to this inherit ambiguity in the way Maven performs conflict resolution its inevitable you will run into conflict issues like this and have to either (a) exclude the conflicting dependency you don't want (b) add an explicit dependency on the version or (c) use something like a `<dependencyManagement>` declaration to tell Maven you prefer a certain version.

> Of course. By no mean, I said it is a blocker.
I'm definitely working around that but I find weird having to declare a dependency I'm not using explicitly.

I agree completely. As mentioned above though, tweaking our generated POM would not _completely_ eliminate this problem, although it would fix it for your specific case. The underlying problem is that often times declaring an "unneeded" dependency is the best or only way to influence Maven dependency resolution. It's inherently wrong, as you indicate, which is why there are other mechanisms to solve this kind of problem with more robust dependency management engines like Gradle ;)

**Comment by dadoonet** [comment]
> This is exactly what we are doing, which is what is causing this issue to begin with. We don't rely on transitive dependencies in any of our projects. We explicitly declare all dependencies. So rather than rely on Jackson bringing in snakeyaml we exclude all transitive dependencies (thus the excludes in our generated POM) and explicitly declare snakeyaml as a direct dependency.

That's something I kind of disagree with. I mean that if the code does not explicitly declare an `import` on `snakeyaml` in its code, then we don't really depend on `snakeyaml`. I'd say it's like an implementation detail. Although I agree that we depend on it because it needs to be in the classpath to work. But for my own projects, I let the dependency manager (Maven) solve that for me.
But I guess it's the way it works in Gradle land vs. Maven land. 😃 

> or (c) use something like a `<dependencyManagement>` declaration to tell Maven you prefer a certain version.

That's exactly what I'm doing.

> which is why there are other mechanisms to solve this kind of problem with more robust dependency management engines like Gradle ;)

Haha! I don't want to enter that debate 😄 

So let me close this issue then as `won't fix`. 
Thanks for looking at it.

**Comment by mark-vieira** [comment]
> That's something I kind of disagree with.

That's fair. We are simply trying to make our resolved dependencies explicit. There are other ways to do this, like relying on dependency resolution rules to include resolved versions. This has it's own issues though, as these things don't get published in a POM so consumers won't use the same versions as us.

>  I mean that if the code does not explicitly declare an import on snakeyaml in its code, then we don't really depend on snakeyaml. I'd say it's like an implementation detail. Although I agree that we depend on it because it needs to be in the classpath to work.

Which is why it should really be `runtime` scoped dependency, but it's a dependency nonetheless. And changing the scope doesn't solve the conflict issue either.

Thanks for the discussion. There's no simple solution here. In the end dependency conflicts will arise and need to be resolved, either explicitly, or via some implicit ruleset that may or may not align with the requirements of all your included dependencies. In the end this generally falls in the lap of the consumer (you) ;)
