### ISSUE TITLE
Mongolian stop words needed

### ISSUE THREAD

**Issue by hurelhuyag** [elastic/elasticsearch#40434]
Last few years I had collected mongolian stop words. If elasticsearch has built in mongolian stop word support it is nice to mongolian users.

```
aa
аанхаа
алив
ба
байгаа
байдаг
байна
байсаар
байсан
байх
байхаа
бас
бий
бишүү
бол
болно
болоо
болох
болсон
бөгөөд
буй
бусад
бүр
бэ
вэ
гэж
гэжээ
гэлтгүй
гэсэн
гэтэл
гэх
даа
доо
дөө
дээ
дараа
даг
дог
дөг
дүнд
дэг
за
заа
л
маань
минь
мөн
мэт
нь
оо
өө
руу
рүү
сан
сон
сөн
сэн
та
талаар
тийм
тэг
тэд
тэр
уг
уруу
уу
учраас
үрүү
үү
харин
хө
хэд
хэн
ч
чинь
шүү
энэ
юм
юмаа
юу
юү
яг
ын
ийн
```

**Comment by jimczi** [comment]
Hi @hurelhuyag ,
Usually we don't add analysis resources directly in Elasticsearch. The stop word lists for all supported languages are defined in Lucene or another libraries (snowball). However since we don't have an analyzer for the Mongolian language I wonder how we could expose this. Are you using another resources to analyze Mongolian in Elasticsearch ? A Mongolian stemmer for instance would add great value and would be a good reason to add a Mongolian analyzer in Lucene but I am not aware of any.

**Comment by jimczi** [comment]
@hurelhuyag I am going to close this issue because I think that such resource should be added to Lucene first. Please open an issue in [Lucene](https://issues.apache.org/jira/projects/LUCENE/summary) if you want to contribute this list as a first step for a Mongolian analyzer and we can continue the discussion there.

**Comment by Tsovinar1986** [comment]
> Hi @hurelhuyag , Usually we don't add analysis resources directly in Elasticsearch. The stop word lists for all supported languages are defined in Lucene or another libraries (snowball). However since we don't have an analyzer for the Mongolian language I wonder how we could expose this. Are you using another resources to analyze Mongolian in Elasticsearch ? A Mongolian stemmer for instance would add great value and would be a good reason to add a Mongolian analyzer in Lucene but I am not aware of any.

Need the same thing for an omdena project on mongolian langauge
