### ISSUE TITLE
CCS: control cross cluster search with Index privileges in individual role support

### ISSUE THREAD

**Issue by chenjienn** [elastic/elasticsearch#40500]
When i want to control the CCS privileges in custom individual role , it was not support. It seems that only the super_user role can use the CCS.

Could you please consider adding the support that control CCS privileges in custom individual role ? For example : add an Index privileges like `test-dev:test-*` to control role can only search `test-*` indices in cluster `test-dev`

**Comment by tvernum** [comment]
@chenjienn 
I'm not sure that I understand exactly what the issue is here.

Have you read our docs on configuring CCS with security?
- https://www.elastic.co/guide/en/elastic-stack-overview/6.6/cross-cluster-configuring.html

Cross cluster search does not require superuser roles, you can absolutely use CCS with individual, low privileged roles.
Perhaps this is something we can work through on our [discussion forums](https://discuss.elastic.co/c/elasticsearch)?
