### ISSUE TITLE
Default to the bundled JDK for integration tests in CI

### ISSUE THREAD

**Issue by alpar-t** [elastic/elasticsearch#40531]
Right now we only test with the bundled JDK version in the packaging tests but for other integration tests  when `RUNTIME_JAVA_HOME` is not set.
Since we always set the lather in CI we don't get any coverage with respect to integration tests for the bundled JDK there. 

We should move to default to the bundled JDK in CI for everything other than the specific java matrix testing. Since the integ test distribution does not bundle the jdk ( and we don't want it to ) we need a way in the build to provision and use the same jdk as the one we bundle for those tests.

**Comment by atorok** [comment]
I have been thinking about how to get to a consistent setup here. 
We used to have `runtimeJavaHome` extra property on the project that would get configured up-front. This worked well until we added the jdk to the distribution and we ended up with  situations where we don't have to configure anything, unless we are specifically testing for other java versions in CI. 
The best way to model this is to allow the property to be null and pass it on conditionally on a case by case basis. Mostly for test clusters we'll pass `JAVA_HOME` to the cluster while for unit tests we'll provision the same JDK as we bundle to run them. 
This implies that the runtime jdk for these will be changing from the one defined in `.ci/java-version.proeprties` to the one we bundle. 

The rule will be simple: we test everything with the same JDK we bundle ( or the actual bundled JDK when testing a distribution ), except for when a specific system property points to a different one, in which case that one will be used. 
CI will be configured so that the Java matrix job will be the only one to pass that.  

We also have system properties for java versions which we use in the reproduction line printer to possibly raise awareness that  some java version is relevant for the reproduction. 
This doesn't fit very well and requires additional setup to work which we would like to  avoid as part of #47796 , so the proposal is to simply  drop them. 
We don't have reproduction lines for OS specific tests, encryption at rest, and other setups we have in CI. 
We could replace it with the name of the job just to have the information there on the command line and spark the possibility that it might have something to do with it. 

There's quite a few places that use runtime java directly,  so we'll have to look at all of them, and we'll need the ability to have a branch specific  CI setup since we can't  back-port this all the way.

**Comment by atorok** [comment]
We need to update CI to no longer pass `RUNTIME_JAVA_HOME` except for the JDK test matrix. 
When this variable is not set, we'll just use the bundled JDK, either from the distribution or the same version that was provisioned as part of #48561.
The `runtime.java` system property will be supported as a number only, and it will work with provisioned version only, as a semi correct reproduction. It will work for provisioning the same version from a specific vendor, but the exact same vendor will not be guaranteed.

**Comment by mark-vieira** [comment]
With #51505 I think we can revisit this and remove usages of `RUNTIME_JAVA_HOME` for most everything in CI.

**Comment by pugnascotia** [comment]
@mark-vieira is this issue still value? If so, what needs to be done?

**Comment by mark-vieira** [comment]
I think we might still be setting `RUNTIME_JAVA_HOME` unnecessarily in some places. I'll take a look.

**Comment by mark-vieira** [comment]
We've cleaned up all remaining instances of us not using the bundled JDK.
