### ISSUE TITLE
Add array support for sql PERCENTILE function

### ISSUE THREAD

**Issue by bputt** [elastic/elasticsearch#40760]
**Describe the feature**:

It would be helpful if I could ask for multiple percentile values via the ```PERCENTILE``` function.

For example:

```
SELECT username, PERCENTILE(duration, [ 0.95, 0.90, 0.50 ]) FROM x GROUP BY username

// Would yield

username, percentile
abc, [ 140.42, 49.41, 12.23 ]
def, [ 49, 94.42, 10.2 ]
ghi, [ 104.24, 94.6, 5.3 ]
```

**Comment by costin** [comment]
SQL deals best with single value (row/column) and does not favor multiple-values or arrays simply because they break this abstraction.
Hence why `PERCENTILE` is implemented as a single and not multi-value.

The same query can be easily be written as:
```
SELECT username, PERCENTILE(duration, 0.95) AS p1,  PERCENTILE(duration, 0.90) AS p2 PERCENTILE(duration, 0.50) AS p3 FROM x GROUP BY username
```
The same results are being returned while being able to select (and filter) each individual value. Also behind the scene the optimizer automatically combines the SQL percentiles into one.

**Comment by bputt** [comment]
@costin do you plan on being postgresql compliant? If so, they have aggregate functions which accept an array of double[]

https://www.postgresql.org/docs/9.4/functions-aggregate.html

**Comment by costin** [comment]
Hi,

Ideally we'd like to be as compatible with the others DB however that's not always possible - as in this case due to the issues surrounding arrays.
