### ISSUE TITLE
Flag for preventing fallback to default field when using quote_field_suffix

### ISSUE THREAD

**Issue by slumx** [elastic/elasticsearch#40778]
As default "quote_field_suffix" falls back to the default field if the field generated by 
adding the "quote_field_suffix" does not exist.

When you have a multi field like: 
`"title": {
      "fields": {
          "exact": {},
          "folded": {}
      }
}
`
it will search both title.exact and title.folded which is probably not what we want. 

Could we have a flag for ignoring fields not found instead of using the original field?

**Comment by jimczi** [comment]
I am not sure I understand what the issue is. If you provide `quote_field_suffix` as `exact` and your search targets the `title` field the `query_string` will use `title.exact` for the quoted parts of the query. If `title.exact` does not exist the original field is used so I don't see what multi fields has to do with this. Can you provide an example (mappings + query) that would benefit from this feature ?

**Comment by slumx** [comment]
Sorry forgot to mention that I'm using `QueryStringQuery` and I have set `fields` to `["title", "title.exact", "title.folded"]` so when not searching for a phrase all three fields will be queried

**Comment by slumx** [comment]
Here is a comple example

**mapping**
```
{
  "mappings": {
    "_doc": {
      "properties": {
        "title": { 
          "type": "text",
          "fields": {
            "exact": { 
              "type": "text",
              "analyzer": "english"
            },
            "folded": {
              "type": "text",
              "analyzer": "custom_folded"  
            }
          }
        }
      }
    }
  }
}
```
**query**
```
{
  "query": {
    "query_string" : {
      "fields" : ["title", "title.exact", "title.folded"],
      "query" : "\"john doe\"",
      "quote_field_suffix": ".exact"
    }
  }
}
```
When the parser adds `qoute_field_suffix` we get `title.exact` and `title.folded.exact` because `title.folded.exact` doesn't exist it falls back to `title.folded` and searches in `title.exact` and `title.folded` which is not what is expected.

**Comment by jimczi** [comment]
Thanks for explaining. However I am not sure that `quote_field_suffix` should be used to ignore fields in the query. Currently it can be used to redirect fields to an alternative that is better suited for a phrase query (with shingles for instance) so I don't understand why you need to use `title.exact` on non-phrase queries. Couldn't you set `fields` to `["title", "title.folded"]` only ? The other alternative is to use a field query `"query":  "title:\"john doe\""` that ignores the provided `fields`.

**Comment by slumx** [comment]
Thanks for a quick response. 
The `title.exact` is not the problem but instead all the multi fields which doesn't match the name of the root field +  `qoute_field_suffix`. If I set `fields` to `["title", "title.folded"]` and `qoute_field_suffix = ".exact"` it would still search `title.exact` (which is correct) but also `title.folded` because there is no `title.folded.exact`. If it should be acceptable that `quote_field_suffix` will fall back to the original field if the field could not be found the usecase described at https://www.elastic.co/guide/en/elasticsearch/reference/current/mixing-exact-search-with-stemming.html seems misleading?

**Comment by jimczi** [comment]
Well the issue here is that you have more than 2 fields. I don't think that the documentation is misleading but it doesn't take into account the fact that you can have more than two variations on the same field. What should be the behavior if you search for `"fields": ["title", "body"], "quote_field_suffix": ".exact"` and only `title.exact` exists ? Should we ignore the `body` field if the query is quoted ? It might be more confusing than the current behavior but I got your point so I'll leave the issue open for others to comment. IMO we should not rely on a flag but rather ignore the field entirely if we think that it's the correct behavior for this feature.

**Comment by slumx** [comment]
Seems reasonable. In my opinion it should ignore the field if it doesn't exist. By maybe a mention in the documentation about the fallback to the default field could help. It is only mentioned in the javadoc. From reading the documentation I a least got the idea that it would only match the fields it could find, but I understand your example as well. 
My fix for now is to create a dummy field called `title.folded.exact` with no content.

**Comment by jimczi** [comment]
@slumx we discussed internally and opened https://github.com/elastic/elasticsearch/issues/40975 to simplify the boosting/filtering of exact matches. It is complicated to do it right today especially when searching on multiple fields so we'd like to propose a better solution to hanlde scoring and filtering more efficiently. In the mean time I marked this issue with the `:Docs` label because I agree that the behavior of the `quote_field_suffix` is unclear in the documentation.

**Comment by slumx** [comment]
Thank you that sounds great

**Comment by slumx** [comment]
In regards to the #40975 discussing "[... I'm not sure whether searching the same field with several analyzers is the best approach scoring-wise.]".
What I do right now is having different boosts for exact, stemmed and folded fields.

**Comment by slumx** [comment]
With the deprecation of nested multifield #41926 (removal in v8.0) it will not be possible to ad a nested ".exact" field to an already nested field. Will this handled by #40975 as well?
