### ISSUE TITLE
Allow index aliases to target non existent indexes

### ISSUE THREAD

**Issue by lmtjalves** [elastic/elasticsearch#40896]
**Describe the feature**: 

Support for creating index aliases whose target index(s) don't yet exist.

**Comment by jasontedor** [comment]
What is the use-case for this? Implementing this will be quite difficult because of the way that aliases are currently managed. Today, aliases get attached to indices; so indices have aliases on them, it's not that aliases are first-class citizens to support a feature request like this. So, barring a compelling use-case, given the difficulty of supporting it, I don't think we would be implementing this.

**Comment by jasontedor** [comment]
No additional feedback, closing.
