### ISSUE TITLE
Monitoring emits many scary log messages on a freshly-installed cluster

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#40898]
When a new cluster starts up with monitoring enabled it emits multiple messages of the following form:

`waiting for elected master node ... to setup local exporter [default_local] (does it have x-pack installed?)`

This message is shown on nodes other than the elected master each time (except the first) they receive a cluster state update from the elected master in which monitoring is not completely set up (i.e. a template or an ingest pipeline is missing).

One explanation for this is that the elected master is not configured to set up monitoring, perhaps because it does not have X-pack installed (hence the `does it have x-pack installed?`). However when a cluster is first forming the master has quite a few things to do, and may not get around to setting up monitoring for some time.

I think we should not emit this message until the node has been waiting an unreasonably long time for the master to set these things up.

I'm moving this comment from #28974 into its own issue because that issue appears to be about docs rather than about suppressing this warning.

**Comment by kiawin** [comment]
@DaveCTurner Any thought on how much time is considered "an unreasonably long time"?

I can work on this ticket, if that's ok with you :)

**Comment by DaveCTurner** [comment]
Great!

Let's default to 30 seconds, starting from the cluster forming (i.e. the first call to `clusterChanged()` in which `event.state().blocks().hasGlobalBlock(GatewayService.STATE_NOT_RECOVERED_BLOCK)` is false). This time should be configurable via a `Setting.timeSetting` rather than hard-coded.

**Comment by mariaral** [comment]
Hey @kiawin are you still interested in this issue? If not, I could work on this.

**Comment by kiawin** [comment]
@mariaral thanks for your interest. please proceed 😄

**Comment by mariaral** [comment]
Hello @DaveCTurner ,
I had a look at this issue and tried to understand the code. I like your idea of waiting a configurable amount of time before warning the users. From what I understand, this cannot be done inside the `resolveBulk` method and we will have to create a `Future` that will check after x seconds if the exporter is set up by the master and prints the warning otherwise. Does this sound reasonable?

**Comment by DaveCTurner** [comment]
@marial I think it'd be simpler to record the time at which the cluster forms (i.e. the first time that `clusterChanged()` is called for a cluster state without `GatewayService.STATE_NOT_RECOVERED_BLOCK`) and then only emit the warning if enough time has elapsed after that.

The current (relative) time is available in this class from `client.threadPool().relativeTimeInMillis()`.

**Comment by mariaral** [comment]
@DaveCTurner thank you for taking a look. I initially tried your suggestion but since the ``resolveBulk()`` is called only at cluster updates, if no more cluster updates happen after 30 seconds (i.e. the nodes have joined the cluster before that time elapses), the warning will not be printed even though the master may not have x-pack installed. That’s why I suggested checking this asynchronously. Do you have any other suggestions for that?

**Comment by DaveCTurner** [comment]
That's not unreasonable, although in practice there'll always be more cluster state updates. Maybe `resolveBulk()` is the wrong place to log this. How about logging this warning in `openBulk()` if `state` is not `RUNNING` and more than 30 seconds have elapsed since the cluster formed?

**Comment by mariaral** [comment]
Great suggestion @DaveCTurner! It seems to solve the issue. I will prepare a PR asap.

**Comment by mariaral** [comment]
@DaveCTurner I just created a PR. Please take a look.

**Comment by DaveCTurner** [comment]
Thanks @mariaral and @danhermann for closing this :grin:
