### ISSUE TITLE
Unexpected search result on query with field missing in documents

### ISSUE THREAD

**Issue by biolds** [elastic/elasticsearch#41022]
**Elasticsearch version** (`bin/elasticsearch --version`):
6.7.1 (debian package)

**Plugins installed**: []

**JVM version** (`java -version`):

```
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-1~bpo8+1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode
```

**OS version** (`uname -a` if on a Unix-like system):

Linux host1 3.16.0-8-amd64 #1 SMP Debian 3.16.64-2 (2019-04-01) x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

Doing a query string search on a missing field returns unexpected results in ES 6.7.1, working correctly on 6.5.

**Steps to reproduce**:

In Kibana, "Discover tab", in the filter bar:
- Searching for `unknown_field:test` correctly returns no value on a field not present in records
- Adding a matching term returns records: searching for `my_field:existing_value AND unknown_field:test` returns documents as if the query was `my_field:existing_value`

**Comment by mayya-sharipova** [comment]
@biolds  Thanks for filing the issue

I indeed confirm that on master  we have a different behaviour from 6.5

On 6.5 the query `my_field:existing_value AND unknown_field:test` is translated to `"+(+my_field:existing_value +MatchNoDocsQuery(\"unmapped field [unknown_field]\")) #*:*"`

While on master it is translated to `"+my_field:existing_value #*:*"`, where `MatchNoDocsQuery` is not present.

I think the bug is related to the this [PR](https://github.com/elastic/elasticsearch/pull/35726)

@cbuescher I wanted to confirm with you, have you considered this case when you were remove `MatchNoDocsQuery`? Is this case really a bug or unintended result of your PR?

**Comment by cbuescher** [comment]
> have you considered this case when you were remove MatchNoDocsQuery

@mayya-sharipova not conciously since it seems to be another edge case. I think we need to discuss this other edge case to see how we want to treat `AND` conjunctions where one part of the clause targets a non-existing field before considerung this a bug. Expectations might differe here.

**Comment by jimczi** [comment]
IMO this is a bug so I opened https://github.com/elastic/elasticsearch/pull/41062 to ensure that we ignore unmapped fields only if they are mixed in a disjunction with other mapped fields.
