### ISSUE TITLE
Log, but still service requests larger than max_result_window

### ISSUE THREAD

**Issue by clandry94** [elastic/elasticsearch#41078]
**Describe the feature**: 

The `index.max_result_window` setting, found [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html), fails the search request when the `max_result_window` is larger than expected. It would be nice to have a less aggressive feature similar to this which only logs when the `max_result_window` is larger than a threshold. 

For example, setting `index.max_result_window` to 10,000 and `index.log_result_window_threshold` to 5,000 will log at the `WARN` level all queries with more than 5,000 results while still returning a http 200 code and the search results. 

A potential use-case for this is where elasticsearch cluster admins are working to move usage to search after/scroll API and pinpointing existing queries which aren't using the scroll API.

**Comment by colings86** [comment]
We discussed this in FixItFriday. Whilst we can understand the use case we are struggling to find a way to expose this that would work across all soft limits. If this is useful on this soft limit it is sensible to assume that a similar mechanism would be useful across all soft limits to find users who are nearing the limits and direct them to alternatives. However adding a warn setting for every soft limit would not scale well as it would vastly increase the number of settings and present a difficult user experience. We had something similar with settings for which types of scripts to allow in which APIs (file/stored/inline) previous and it lead to a lot of confusion. 

We also wonder whether another more flexible option in these use cases would be to log every query (maybe using the slow log or audit log) and inspect the requests to find instance where users need to be directed to better approaches (e.g. requests with a size > 5,000, queries that use leading wildcards, etc.). This would provide more flexibility to the user since they could inspect whatever criteria int he requests they wish.

**Comment by clandry94** [comment]
Thanks for looping this issue through the team @colings86. I think that using the slow log would be a decent way to accomplish this and understand why it would be tough to add this feature directly to elasticsearch. I'm going to go ahead and close this issue now.
