### ISSUE TITLE
Improve translog durability against JVM crashes without impacting throughput by eliminating fsyncs

### ISSUE THREAD

**Issue by itiyamas** [elastic/elasticsearch#41081]
ES translog flush does the following things:
1. Flush the heap buffer to FileChannel.
2. Fsync the file contents to disk.
3. Write checkpoint file and flush it to disk.

For durability against JVM crashes, which are more frequent than hardware crashes etc., flushing the heap buffers(both translog and checkpoint) to page cache is sufficient. Fsync is primarily needed for protection against hardware failures.
Because of the tight coupling between the above 3 steps, I cannot choose to have a per request sync to page cache and an asynchronous fsync to disk. Hence, I can either get durability against both types of crashes or none of them, even though the probability of both is different.

I am proposing a new flush type that ensures the flushes to page cache and not to disk so that the guarantees are decoupled. The disk flushes can continue to happen asynchronously. Users can choose to use any of the flush depends depending on the durability requirements. 

Since time taken to write to page cache is negligible, we can gain significant indexing performance and reduce disk I/O costs without an impact to durability against more frequent JVM crashes.

**Comment by dnhatn** [comment]
Thanks very much for your interest in Elasticsearch.

The proposing option can make translog unrecoverable in a scenario where the checkpoint is fsynced but the content file. With the new option, after a write operation is processed, we (1) append an operation to the content file, (2) flush the content file, (3) update and flush the checkpoint (write a new file then rename it). If operating system fsync the checkpoint then crashes before it can persist the content file then translog is broken. The problem is that OS can freely choose to fsync the checkpoint before the content file regardless of the flushing order.

**Comment by itiyamas** [comment]
We can work out ways to implement it, given you agree with the overall idea. Please note that this is heavily dependent on the type of filesystem and OS. Hence, the new option shouldn't mention durability against JVM restarts, just that it doesn't do an fsync but ensures that the writes to page cache are successful.

Write checkpoint to 2 files- the older one continues to be written the same way as earlier while the new one is written at the end of every request. The checkpoint stores the total number of operations and translog offset that is expected. During recovery, you ensure that translog is written up to that offset- else fallback to the periodically fsynced checkpoint file.

I hope this will solve the problem for cases where filesystem ensures atomicity and consistency, leading to translog entries not being corrupted, but only lost- which can be easily verified by the offset in the file.

Berkley DB gives similar guarantees: http://www.mathematik.uni-ulm.de/help/BerkeleyDB/api_c/env_set_flags.html

Check options: DB_TXN_NOSYNC(if the application or system fails ) and DB_TXN_WRITE_NOSYNC (if system fails)

**Comment by itiyamas** [comment]
Pinging @dnhatn

**Comment by dnhatn** [comment]
> Write checkpoint to 2 files
> else fallback to the periodically fsynced checkpoint file.

This approach is quite complicated and error-prone for we have to guess and recover the checkpoint.

We prefer to keep translog simple and easy to reasoning/test because it is crucial for the consistency and resiliency of the system. Therefore, I don't think this is the right direction at least for now.
