### ISSUE TITLE
Field datatype mapping on insert

### ISSUE THREAD

**Issue by riteable** [elastic/elasticsearch#41334]
As far as I know, we have to either rely on dynamic mapping, or create mapping templates before inserting documents. But it would be nice if we could define mapping on insert.

Dynamic mapping is a "best guess" type of mapping which is not what you want if you want to make sure that you have absolutely the correct type. For example, a value of `1.1` will map to a `float`, while you might want it to be a `double`, etc.

Also, having the ability to set other mapping options (format, analyzer, etc) on insert, would be pretty nice.

**Comment by jasontedor** [comment]
Thanks for your interest.

There are a few alternatives that were left out here:
 - you can add the mapping when [creating the index](https://www.elastic.co/guide/en/elasticsearch/reference/7.0/indices-create-index.html#mappings)
 - you can update the mapping using [put mapping](https://www.elastic.co/guide/en/elasticsearch/reference/7.0/indices-put-mapping.html) API
 - you can use [dynamic templates](https://www.elastic.co/guide/en/elasticsearch/reference/7.0/dynamic-templates.html) for control over how dynamically added fields are mapped (maybe this is what you meant by create mapping templates, but that could also be referring to [index templates](https://www.elastic.co/guide/en/elasticsearch/reference/7.0/indices-templates.html) so I include both here for completeness)

To me, this gives sufficient control already to mappings, and even enables you to submit a mapping update before executing an indexing request. Rather than complicating the index API by inlining this, the primitives are there in other APIs already. That is, combining them would add almost nothing at the risk of overly-complicating our APIs leaving more surface area for bugs and maintenance.
