### ISSUE TITLE
Allow ILM Rollover step to copy settings/mappings from source index

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#41389]
Right now ILM implicitly assumes an index that rolls over uses an index template, and so when rolling over it relies on templates to supply the new mapping/settings.

This is problematic for indices that _are not_ managed by an index template.  It would be useful if ILM could (optionally) use the existing mappings and settings from the source index when executing the Rollover.

This seems like a generally useful feature, but for context, I'm looking to see how Rollup can be made to work with ILM.  Rollup creates its own indices, and uses the `_meta` of the index's mapping to store long term details about the rollup job. This setup means that if Rollup is rolled over, the new index will lose the `_meta`, dynamic mapping template, etc.

Rollup could proactively create a template when the index is created, but this is tricky because it could match off-target indices.  And it's yet another thing that needs to be managed, upgraded between versions, etc.

**Comment by dakrone** [comment]
We discussed this today and brainstormed some ideas.

In the past, ILM was against this because it meant that in order to make switch
policies the user can't change the template and have it take effect on the next
rollover, rather the user would have to let the index roll over, then use the
remove policy API, then set a new policy with the update index settings API.

One solution that we discussed was adding a flag to the `rollover` action that
would copy the settings to newly rolled over indices, this flag would default to
`false` (the current behavior).

It's also important to understand exactly what we want copied, for the rollup
case it sounds like both the settings and mappings should be copied over, but
it's not clear whether this is desirable for everyone.

More discussion is needed, in particular getting some feedback from @colings86
about the historical decision making regarding the current behavior is necessary
before we make a final decision.

**Comment by colings86** [comment]
The concern previous centred around users being confused where settings (particular in our discussions the policy name) would ultimately come from; the index template or the previous index.

If we imagine we have an index `index-00005` which is using `old_policy` as defined in an index template, at the moment the user knows that in order to change the policy for new indexes they need to change the `index.lifecycle.name` in the index template to `new_policy`. If the rollover action copies over index settings this now may or may not be true and depends on the policy the index was using before. If the new `copy_settings` flag on the `rollover` action is `false` the user needs to update the index template to get new indexes to use a different policy, but if `copy_settings` is set to `true` the user needs to update the current index `index-00005` changing the policy used for that index which will then be used for subsequent indexes. 

What we struggled with here is where does this leave the index template? New indexes are being create which match the template but the template isn't being used. Although this doesn't present a technical challenge it is something thats harder to explain to users. This will possibly lead to us saying that the `copy_settings` flag should only be set to `true` if you are not configuring index settings in an index_template (since it renders the index settings from the template useless) but this is hard to explain (since the template is still very much useful for mappings and aliases), easy for users to get wrong and lead to confusion and hard to enforce (not sure how we could easily warning the user if they are using index settings in a template and the index is using a policy with `copy_settings: true` on the `rollover` action). 

One other weird thing about this `copy_settings` flag in the instance that the user wants to change the policy name is that it applies to the OLD policy. If the `old_policy` has `copy_settings: true` then the settings will be copied to create the new index and the new index will use the NEW policy (since we don't change the currently executing phase when the policy name changes), but the `new_policy` may or may not use `copy_settings: true`. The reverse is also true, the `old_policy` may not use `copy_settings` meaning the change for the new index needs to be made with an index template but the `new_policy` then might use `copy_settings` making the template obsolete. Whilst again there are procedural ways to get things as the user wants them in these situations, explaining what the user needs to do could get tricky.

To be clear, I'm not against a change like this, in fact I can see why it's useful. My intent here is to describe the issues we came across when we discussed this before and why we ultimately decided to stick with a model where the settings were applied only by the normal create index mechanisms (i.e. index template and then defaults). Of course at that stage we did not have a use case in front of us that could not use an index template.

Happy to discuss this more, as I'd like to find some way forward here.

**Comment by polyfractal** [comment]
Related to https://github.com/elastic/elasticsearch/issues/33065 (for my own notekeeping)

**Comment by dakrone** [comment]
Closing this as with the transition to data streams this has become less necessary, as data streams must always be backed by a template.

**Comment by ewolfman** [comment]
Thanks for sharing this discussion.

The current ILM rollover behavior _forces us_ to define an Index Template. But why? I would prefer to enjoy ILM without defining an Index Template. 

Without an Index template, the ILM rollover creates an index without mapping - what is the point? Maybe I am wrong, but I imagine that there is no use-case where you would want an empty mapping following a rollover. 

I am relatively new to Elasticsearch so please correct me if I am wrong.
Thanks.
