### ISSUE TITLE
Turn the class RestClient into an interface

### ISSUE THREAD

**Issue by stephanebastian** [elastic/elasticsearch#41443]
Hi, 
We mainly interact with ES through the java RestClient or the java RestHighLevelClient. 
For information, we use Vertx as our primary framework and would like to provide our own RestClient implementation to make sure that all ES requests are sent through the Vertx worker pool. However, the RestClient is not an interface.

It would be great to make RestClient an interface to support use cases where people provide their own implementation. Something like this would be enough:

```
RestClient {
    public Response performRequest(Request request) throws IOException;
    public void performRequestAsync(Request request, ResponseListener responseListener);
}

```
What do you think ?
If you guys are ok with this, let me know, I can provide a pull request
Thanks,

Stéphane

**Comment by hub-cap** [comment]
Hey @stephanebastian,

Is there any reason this has to be an interface? Im not terribly familiar w/ Vertx, but if you just subclass the `RestClient` you should be able to override both of those methods and replace them with whatever you like, all without an extra interface. Is it something about Vertx that makes you use interfaces instead?

**Comment by stephanebastian** [comment]
Hey @hub-cap,
Sorry for the late reply.

To answer your question, no, there is nothing special about Vertx and Vertx doesn't mandate that is has to be an interface. Sorry I should I have been better at explaining the problem.
We currently do subclass the RestClient and we are able to perform requests via our own http client running in the worker thread pool provided by Vertx.

However, it only works because the current constructor support a null CloseableHttpAsyncClient (which seems odd by the way ;).
So, we feel that our current solution is more of a hack than anything else, even though it gets the job done. If in subsequent releases, you modify your constructor to forbid null CloseableHttpAsyncClient then we are doomed. 
Therefore, we are proposing to turn the class RestClient into an interface. This would make it clear that  the intention is to support others implementations than the one you provide out-of-the-box and be a future-proof solution

Does it make sens to you ?

**Comment by hub-cap** [comment]
Well, I do agree that not checking for null is odd here, and we may certainly add a not null check in the future. But it is also entirely valid to pass in a dummy object, like the following example. It would never be used since you are overriding the `performRequest` & `performRequestAsync` methods.  

```
new CloseableHttpAsyncClient() {

            @Override
            public void close() throws IOException {

            }

            @Override
            public boolean isRunning() {
                return false;
            }

            @Override
            public void start() {

            }

            @Override
            public <T> Future<T> execute(HttpAsyncRequestProducer requestProducer, HttpAsyncResponseConsumer<T> responseConsumer, HttpContext context, FutureCallback<T> callback) {
                return null;
            }
        };
```

We are working on a plan for generating as much of this code as possible, so some of this will be subject to change, so Id like to reduce the changes here and in the high level client as much as possible until I know the path forward. But Ill be helping to design the new client, so I will definitely try to ensure the High Level client is more composable for your use case.

Do you think this would suffice for now? Such that if you need to new a dummy `CloseableHttpAsyncClient`, you can do so in a way that does not harm what you are doing.

**Comment by stephanebastian** [comment]
Great to hear that the new client might be more composable.
Short term, we can definitely pass-in a dummy client. Thanks for your time

Stephane
