### ISSUE TITLE
Fix aggregation  documentation

### ISSUE THREAD

**Issue by fpompermaier** [elastic/elasticsearch#41902]
The value of sum_other_doc_count in the example of [search-aggregations-bucket-terms-aggregation page](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-approximate-counts) is inconsistent with the sample data. Am I wrong?

In the reported responses **sum_other_doc_count is 79** but from my counts **should be 81**.
sum_other_doc_count should be the sum of all doc counts after the 6th row of the top terms per shard table, i.e.:

  6 | Product F (2) | Product H (14) | Product H (28)
  7 | Product G (2) | Product I (10)  | Product Q (2)
  8 | Product H (2) | Product Q (6)  | Product D (1)
  9 | Product I (1)   | Product J (8)  |  
10 | Product J (1)  | Product C (4)

Sum other doc count of Shard(A) = 2 + 2 +2 +1 +1 = 8
Sum other doc count of Shard(B) = 14 + 10 +6 +8+4 = 42
Sum other doc count of Shard(C) = 28+2+1 = 31
And thus sum_other_doc_count = 8 +42 +31 = 81.

Is it correct? Or am I wrong?

**Comment by astefan** [comment]
@fpompermaier I think you are correct and there may be another small issue in the example: for shard B these are the last 3 elements in the ordered list of terms:
```
Product Q (6)
Product J (8)
Product C (4)
```
`Product J` cannot have 8 documents because the elements should be sorted. This combined with the sum that doesn't add up, I'd say `Product J` should have 6 documents instead of 8.
I'll leave this to the appropriate team to comment and evaluate.

**Comment by fpompermaier** [comment]
Anyone on this? The documentation is still wrong..

**Comment by polyfractal** [comment]
I don't believe it has been fixed yet.  We'd happily accept a PR to fix if you have some time!

**Comment by fpompermaier** [comment]
Here it is the PR that fix this issue

**Comment by polyfractal** [comment]
Closed by #45028 :tada:
