### ISSUE TITLE
Add a way to convert date field value to single type in Painless script

### ISSUE THREAD

**Issue by Hohol** [elastic/elasticsearch#41936]
It's required for https://github.com/elastic/kibana/pull/25379
I need to access a date field in a Painless script, but I don't know what its type is.
I know there are at least two possible types - `Long` (epoch milliseconds) and `JodaCompatibleZonedDateTime`. Probably there are more.
So I need some way to convert date from one of possible types to a single type.
The method `WatcherDateTimeUtils#convertToDate` does similar thing, but it's not available inside a Painless script.

Of course I can do it right in the script, but it will be very ugly. And easily available method can be used for other purposes.

If such functionality already exists, please tell me and I'll just use it.

**Comment by Hohol** [comment]
If someone from Elastic team confirms that it should be done, I can work on this.

**Comment by jdconrad** [comment]
@Holol This isn't currently possible due to possible different date formats available that would make any single value ambiguous.  As an example _source could have a long to represent a date, but that value alone wouldn't tell us whether that is milliseconds since epoch or nanoseconds since epoch so more user information would be necessary.  If _source contains a String, the user would need to provide information about the date's format.  And in the case of using doc['some_date_field'], at this time JodaCompatibleZonedDateTime is always returned as the value, so a utility method wouldn't be necessary at the type is known.

**Comment by Hohol** [comment]
@jdconrad I totally forgot to mention that date field in question is a scripted field (probably you already figured it out from linked PR).

>  And in the case of using doc['some_date_field'], at this time JodaCompatibleZonedDateTime is always returned as the value, so a utility method wouldn't be necessary at the type is known.

Are you talking about scripted fields here? If so, I disagree. It's exactly where the problem comes from.
If you perform steps specified in https://github.com/elastic/kibana/issues/24891, type of `doc['some_date_field']` will be `Long`, not `JodaCompatibleZonedDateTime`. Although field type is `date` and Kibana perceives it correctly as date.

**Comment by Hohol** [comment]
Wait, I'm wrong. In https://github.com/elastic/kibana/issues/24891 I used `doc['some_date_field'].value`, not `doc['some_date_field']`.
Will the type always be `JodaCompatibleZonedDateTime` if I use `doc['some_date_field']`?
(Can't check it myself right now)
Anyway, I think we need to support field definitions of type `doc['some_date_field'].value` as well.
For example, if there was some date math in a field script and the result of is Long type.

**Comment by jdconrad** [comment]
@Hohol I didn't check the version that the issue was related to in Kibana.  I believe as of 7.0 ```doc['some_date_field'].value``` will return a JodaCompatibleDateTime.  You are correct that in 6.4 it depends on the field type.  If the field is a date field then ReadableDateTime is returned.  If it's a long field ```doc['some_date_field'].value`` will return a long, but ```doc['some_date_field'].date``` will return a ReadableDateTime.  Either way, given the user should be aware of the field type coming from doc, there shouldn't be a need for a utility method on the Painless side for this specific case unless I'm misunderstanding something.

**Comment by Hohol** [comment]
Kibana knows how to interpret a scripted date field, even when it is of `Long` type internally. I just want to do the same in a consistent with Kibana way.
The question is, does Kibana get an actual date from Elasticsearch or determines it itself?
@ppisljar, @Bargs, probably you can answer?

**Comment by jdconrad** [comment]
Field mappings determine the type of field available as part of the doc variable.

**Comment by Hohol** [comment]
Thank you, @jdconrad. We discussed it in PR thread and decided we can always assume the type to be `JodaCompatibleDateTime`.
