### ISSUE TITLE
CCS issue 

### ISSUE THREAD

**Issue by cjw0202** [elastic/elasticsearch#41999]
Hi, 
I have two es clusters, and the network is unreachable, so i use CCS with haproxy, but it's does work, the cluster use another cluster's IP to connect,not haproxy's IP.
How to do?
forgive my  pool english

**Comment by javanna** [comment]
Hi @cjw0202 may I ask you to ask you question in our forums at discuss.elastic.co please? We reserve github issues for feature requests and verified bug reports. Thanks.

**Comment by mynameiscode** [comment]
I also encountered this problem, I think this is a good issue, there will be more and more people need to support such features. When I configure cross cluster seeds, I expect communication to use this IP. Instead of getting the IP of the elasticsearch cluster node itself. In the scenario of using HAproxy, seeds and ip and elasticsearch node ip may be different.

**Comment by javanna** [comment]
Ok, I think I understand what you mean. Seeds are not necessarily the nodes that will be used for cross-cluster communications though. They are only contacted to retrieve the list of nodes belonging to the remote cluster, so that some (by default 3) nodes out of those in the list are selected (based on their version, role and possibly node attributes) and will be used for CCS requests.

I would suggest to configure node attributes so that you can determine exactly which nodes are used for CCS communications. This is explained in our docs: https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-remote-clusters.html#gateway-nodes-selection .
