### ISSUE TITLE
Documentation for ILM move to step

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch#42080]
[Docs](https://github.com/elastic/elasticsearch/blob/6.6/docs/reference/ilm/apis/move-to-step.asciidoc) note an example, but they do not tell what the `name` parameter should be...

I guessed for example that to move from one stuck with an error in warm/shrink to delete, I would need to do this:

```
POST _ilm/move/test-index
{
  "current_step": { 
    "phase": "warm",
    "action": "shrink",
    "name": "ERROR"
  },
  "next_step": { 
    "phase": "delete",
    "action": "delete",
    "name": "delete"
  }
}
```

But it took me a while because given the existing example I presumed that it would be `"name":"shrink"` not `"name":"ERROR"`.

**Comment by fkelbert** [comment]
:+1: Please add additional explanations to the docs. Parameter `name` seems to be completely undocumented.

Together with a customer, we just spent a significant amount of time on this, until we found this issue.

Also, is there actually a technical reason to require `current_step`? Shouldn't this information be implicit and unknown by the cluster? Is this some safety net?

**Comment by ppf2** [comment]
Another example:

```
      "action" : "rollover",
      "action_time" : "2019-07-05T01:25:31.240Z",
      "action_time_millis" : 1562289931240,
      "step" : "ERROR",
      "step_time" : "2019-07-11T15:45:29.730Z",
      "step_time_millis" : 1562859929730,
      "failed_step" : "check-rollover-ready",
      "step_info" : {
        "type" : "illegal_argument_exception",
        "reason" : "index [logstash-appname] is not the write index for alias [logstash-appname-2019.07.05-000043]",
        "stack_trace" : "java.lang.IllegalArgumentException: index [logstash-appname] is not the write index for alias [logstash-appname-2019.07.05-000043]\n\tat org.elasticsearch.xpack.core.indexlifecycle.WaitForRolloverReadyStep.evaluateCondition(WaitForRolloverReadyStep.java:100)\n\tat org.elasticsearch.xpack.indexlifecycle.IndexLifecycleRunner.runPeriodicStep(IndexLifecycleRunner.java:133)\n\tat org.elasticsearch.xpack.indexlifecycle.IndexLifecycleService.triggerPolicies(IndexLifecycleService.java:270)\n\tat org.elasticsearch.xpack.indexlifecycle.IndexLifecycleService.triggered(IndexLifecycleService.java:213)\n\tat org.elasticsearch.xpack.core.scheduler.SchedulerEngine.notifyListeners(SchedulerEngine.java:168)\n\tat org.elasticsearch.xpack.core.scheduler.SchedulerEngine$ActiveSchedule.run(SchedulerEngine.java:196)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\n"
      },
```

You would think that the current step name is `check-rollover-ready`.  But it's not because in order for the move step API to work, we actually have to reference "ERROR" as the step name when using the move API:

```
POST _ilm/move/<index-name>
{
  "current_step": {
    "phase": "hot",
    "action": "rollover",
    "name": "ERROR"
  },
  "next_step": { 
    "phase": "warm",
    "action": "set_priority",
    "name": "set_priority"
  }
}
```

Which is not consistent with the explanation of `current_step.name` being the step the index is "expected to be in":

![image](https://user-images.githubusercontent.com/7216393/61676205-f28b9900-acaf-11e9-9e23-1f515bdd7493.png)

I like the idea of having ILM determine the current_step information itself so that the user will only have to specify the next_step (with corresponding documentation on all the possible step names, etc..)

**Comment by dakrone** [comment]
> Also, is there actually a technical reason to require current_step? Shouldn't this information be implicit and known by the cluster? Is this some safety net?

> I like the idea of having ILM determine the current_step information itself so that the user will only have to specify the next_step (with corresponding documentation on all the possible step names, etc..)

This is done on purpose so that people *don't* use the move-to-step API. This API is extremely dangerous since it allows execution of ILM steps out of order and potentially lead to worse situations that when ILM regularly encounters an error. For this reason, we require the current step to ensure that:

1. the user is on the step they think they are moving *from* (ILM has not moved to a different step while they were in the middle of invoking the command).
2. the user is aware of exactly what they are doing, in order words, they *have* to check the ILM explain output rather than indiscriminately using this API.

**Comment by jrodewig** [comment]
[docs issue triage]

Leaving open. This is still relevant.
