### ISSUE TITLE
Add reason to elastic health check endpoint

### ISSUE THREAD

**Issue by remmeier** [elastic/elasticsearch#42168]
In the Internet one can find countless questions about elastic having "yellow" and "red" health check status. It would be great to see this service providing the reason(s). Or maybe a second service that list the various performed checks with their individual health. This one may look similar to the Spring Boot Actuator health check service.

**Comment by polyfractal** [comment]
Hi @remmeier.  The health status is driven by the state of the shards in the cluster.  E.g.

- Green: all shards allocated
- Yellow: all primaries allocated, one or more replicas missing
- Red: One or more primaries missing

You can use the `level` flag to refine the status to see which index or shard is having problems.  And the [Cluster Allocation Explain](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-allocation-explain.html) will give more detailed information about why a particular shard is not allocating (no disk space, no free nodes based on filtering criteria, etc).

In the future, questions like this are best asked on the [forums](https://discuss.elastic.co/) rather than Github.  We try to reserve this repo for bug reports.  Thanks! :)

**Comment by remmeier** [comment]
yes that has cleared up how it works. The purpose of the ticket would have been to make it slightly more obvious to newbies like just me. So maybe add a second field given the health status in english words. Maybe follow HATEOAS and link the other rest endpoint. (HATEOAS  would in general be nice BTW to navigate the entire endpoint).
