### ISSUE TITLE
Clarify the policy on fixing severe bugs introduced in patch releases

### ISSUE THREAD

**Issue by rightaway** [elastic/elasticsearch#42170]
A severe bug was introduced in a patch release https://github.com/elastic/elasticsearch/issues/41934 that totally breaks search functionality in certain cases rendering it useless. This bug was introduced in a patch release 7.0.1 which is meant to be a painless upgrade and affected multiple people as seen in the links I've provided.

If a patch release introduces a severe bug, it would be expected that the next patch release after the bug is fixed would included the fix. But in the pull request for the fix https://github.com/elastic/elasticsearch/pull/41938 it seems like ElasticSearch isn't interested in that.

They don't want to offer the fix in 7.0.2 which would be the reasonable thing to do. Not even 7.1.0 (which is far too late anyway), but in 7.2.0! @jimczi claims "It's too late for 7.1.0". What does "too late" even mean? I commented in that issue but nobody has responded.

> Why is this not being put into the very next patch release? The very point of a patch release is to fix bugs.
> 
> Including this severe bug that has made search completely unusable for us. This bug was introduced in a patch release and has no good reason not to be fixed in a patch release.
> 
> What was supposed to be a painless upgrade to 7.0.1 has literally broken search for us and we are supposed to wait for 2 more minor releases?
> 
> Forget 7.2.0 and even 7.1.0, this needs to be a priority to make it into 7.0.2!

What is the ElasticSearch policy on when a patch release completely breaks something? If this ridiculous stance is supported by the whole company and fixes to a severe bug **that are already fixed** won't be included as soon as available we will be rethinking what role this product has in our future.

**Comment by jasontedor** [comment]
@rightaway We are sorry that a bug was introduced that seriously impacts your usage of Elasticsearch.

> This bug was introduced in a patch release 7.0.1 which is meant to be a painless upgrade and affected multiple people as seen in the links I've provided.

I do want to manage expectations here that while our intent in patch releases is to fix bugs, there is always a risk that new bugs can be introduced.

> If a patch release introduces a severe bug, it would be expected that the next patch release after the bug is fixed would included the fix.

I will try to offer some transparency on how we handle bugs, and their relationship to releases. This is not to be taken as a guaranteed policy, only offer some insight into our current processes that you can take into consideration.

We qualify some bugs and issues as ["blockers"](https://github.com/elastic/elasticsearch/labels/blocker) for releases, and for bugs labeled as "blockers" would hold a release until the bug is fixed. We do not and can not qualify every bug as a blocker, or we would never successfully ship; we will always have bugs. Whether a bug is qualified as a blocker depends on the nature of the bug (e.g., data loss issues) and the impact of the bug (e.g., bugs with no workaround that completely break a feature used by a majority of users). While this bug is bad for users of `cross_field` search and is clearly bad for you, it does not qualify as a blocking bug.

> @jimczi claims "It's too late for 7.1.0". What does "too late" even mean? I commented in that issue but nobody has responded.

It means that we had finalized the release artifacts for 7.1.0 and the fix was not integrated in time to be included in those release artifacts, and instead the fix would be included in a later release. We do not rebuild release artifacts for non-blocking bugs.

That said, due to another blocking bug, we have internally re-built the final 7.1.0 artifacts and picked up additional bug fixes that had been committed in the meantime. That means the fix for the issue here will be included in 7.1.0.
