### ISSUE TITLE
Add more flexibility to MovingFunction window alignment

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#42181]
Today, the moving function pipeline aggregation operates in a "left-aligned" exclusive mode; the window that is offered for calculation is the last `n` values excluding the current bucket.

It's not uncommon to want the window to be inclusive (include the current bucket's value in the window).  Other alignments are also useful, such as center (`n/2` values before and after the current bucket) and right (`n` values after the current bucket).

I'm not entirely sure how we should expose these options in the API, but it would be helpful if we can provide more flexibility here.

Relates to https://github.com/elastic/elasticsearch/issues/20667

**Comment by jcornez** [comment]
Thanks for this.

I'd also like to refer to https://github.com/elastic/elasticsearch/issues/23874.  That issue is strictly speaking distinct.  But they are related in that you often want to use bucket_selector when you are using a moving function.  So if your moving window is 10 days (assuming date_historgram with 1d interval), then you want to skip the first 9 (if the moving_fn is inclusive) or 10 (if not) days of the window.  Referring to the bucket_key would be one way to do this.  Another would simply be to index the buckets.

Like I say, not related to window alignment, but more generally to the ease and utility of moving_fn - which is a common them for both.  Thanks.

**Comment by Hohol** [comment]
I'd like to take this.
