### ISSUE TITLE
Add API to simplify ILM initial setup

### ISSUE THREAD

**Issue by gwbrown** [elastic/elasticsearch#42245]
## Problem

Now that ILM has been in the wild for a while, we've seen that one of the biggest issues users have with it is the [initial setup step](https://www.elastic.co/guide/en/elasticsearch/reference/7.0/getting-started-index-lifecycle-management.html), which can be quite unintuitive for users that are not experts in Elasticsearch - in order for things to work as expected, you need to:
1) Create an ILM policy
2) Create an index template which includes both the policy setting and the alias name (which does not yet exist)
3) Create the first index manually with the alias used in the template with `is_write_index` set to true
4) Write to that alias, rather than the index you've just created

This isn't insurmountably difficult, but it does require understanding how templates and aliases work well enough to understand what `is_write_index` means, and that it can't be set in the template, but must be set in the separate request to create the first index. This is especially unintuitive given that our typical workflow with templates in the past has been "set up the template, then just issue index requests and let the index get created automatically".  Even I've forgotten this once or twice.

## Proposed Solution

We can add an API that would greatly simply the setup for the typical use case that would allow users to get the benefits of ILM-managed indices without needing to have a deep understanding of templates or aliases.

Here's a sketch of what such an API could look like for a simple logging use case:
```
POST _ilm/bootstrap/mylogs
{
  "settings": {
    "index.lifecycle.name": "mylogs-policy",
    "number_of_shards": 3
  },
  "mappings": {
    "properties": {
      "message": {
        "type": "text"
      }
    }
  }
}
```

If this looks similar to the Create Index API, that's intentional - with this API, the workflow would be:
1) Create an ILM policy
2) Use this API with the name you want to write to, and the body you would use to create an index
3) Write to the name you used

Under the covers, this would do the following:
1) Create a template from the index creation request, but merging in the `index_patterns` and the `index.lifecycle.rollover_alias` setting:
```
PUT _template/mylogs-template
{
  "index_patterns": ["mylogs-*"],
  "settings": {
    "index.lifecycle.name": "mylogs-policy",
    "number_of_shards": 3,
    "index.lifecycle.rollover_alias": "mylogs"
  },
  "mappings": {
    "properties": {
      "message": {
        "type": "text"
      }
    }
  }
}
```
2) Create the first index with the appropriate alias with `is_write_index` set to `true`:
```
PUT mylogs-000001
{
  "aliases": {
    "mylogs": {
      "is_write_index": true
    }
  }
}
```

This is somewhat similar to the Rollover API in that it simply combines existing operations into a single API call with a small piece of extra logic.  This is not intended to replace the existing workflow for power users who need the additional flexibility, but to streamline the setup for the most common use, especially for less experienced users for whom this seems to be a particular pain point.

## Alternative API

Alternatively, the API could optionally include a policy definition if `index.lifecycle.name` is not provided. This would probably require nesting the index definition and the policy definition under two top-level keys, like so:
```
POST _ilm/bootstrap/mylogs
{
  "index": {
    "settings": {
      "number_of_shards": 3
    },
    "mappings": {
      "properties": {
        "message": {
          "type": "text"
        }
      }
    }
  },
  "policy": {
    "phases": {
      "hot": {
        "actions": {
          "rollover": {
            "max_size": "50GB",
            "max_age": "30d"
          }
        }
      },
      "delete": {
        "min_age": "90d",
        "actions": {
          "delete": {}
        }
      }
    }
  }
}
```

This would behave very similar to the first proposed API, but does not include the `index.lifecycle.name` setting in the index definition, and includes a full ILM policy definition.  This would then create the policy with the name `mylogs-policy` and inject the `index.lifecycle.name` setting in addition to `index.lifecycle.rollover_alias` as described above.  Here, the policy definition would be optional if `index.lifecycle.name` is provided on the index definition.

This adds some complexity to the API, but allows it to be a "one-stop shop" for setting up ILM.  This may or may not be worth the extra complexity, as I've seen fewer users having issues setting up the policy, especially since if an index is set to use a policy that does not exist, and the policy is later created, the index will immediately begin to use that policy.

Which of these two API options do folks like better?

**Comment by gwbrown** [comment]
@polyfractal Would this help with the issues you raised in https://github.com/elastic/elasticsearch/issues/41389, or no? I don't know the details of those issues, but this might prevent rollup from having to manage index templates.

**Comment by gwbrown** [comment]
I've added a sketch of an alternate version of this API that includes both the index and policy definitions to make it the only call needed to set up both a policy and an index.

**Comment by polyfractal** [comment]
@gwbrown sorry for the delay.  Just had a look, and I think this would mostly satisfy the needs of Rollup.  The main issue for Rollup is that we store configuration details in the `_meta` mapping field, which is added when the index is created (by Rollup, not the user).

So we need to either copy that data from index-to-index during rollover, or create a template to manage the details so it plays nicely with ILM.  If this API were implemented, we could use it instead of a normal index creation request when the user specifies an ILM policy.  And wouldn't have to generate a template ourselves.

I think the only outstanding concern, which applies generally I think, is that the template creation might be surprising.  E.g. the template is created with a wildcard that could potentially catch "off-target" indices.  This is a concern for any template pattern, but less obvious when it's done automatically behind the scenes.

I don't see any solution to that other than good documentation, but thought I'd raise the point :)

Overall ++ to this plan from Rollup's perspective, if it existed we'd probably use it.  

> Which of these two API options do folks like better?

For Rollup, I'm leaning towards the first version.  I'd prefer to leave the complexity/error handling of setting up an ILM policy to a different API, rather than having the user specify it in addition to the Rollup config and then trying to debug problems.

Not a strong opinion, I could be convinced either way, but the simpler first API would have my tentative vote :)

**Comment by jordansissel** [comment]
> Here's a sketch of what such an API could look like for a simple logging use case:

A bootstrap/setup API would be lovely!

For my use case (infosec@elastic), for all cases where we need to capacity plan more deeply, these cases are logging.

One scenario we are rolling out can be simplified, I believe, to a few small inputs:
* The "index" name (this becomes the alias as well as the prefix for the rollover indices)
* Index settings: Number of shards and max shards per node[1]
* Rollover: What size index to rollover

With ILM supporting deletion, we'd probably add another input for number of days to keep data.

[1] max shards per node is to prevent [massive shard evacuations](https://github.com/elastic/elasticsearch/issues/45177) seen in production over the past year.

cc @ajrios33 who's been working on this with me.

**Comment by jordansissel** [comment]
Oh one other feedback is that these steps listed above are for every beat on every version of beat that we anticipate ingesting. At present, we run `beats setup` on one cluster 80+ times (one for every version of filebeat, auditbeat, and metricbeat since v6.3.0). It's likely out of scope for this issue, but I'd still like to mention it specifically as a maintenance burden and an area ripe for mistakes (which we make with some frequency).

**Comment by ericsampson** [comment]
I really like the first version of the API that you laid out @gwbrown .

**Comment by gwbrown** [comment]
This use case is being addressed in a well-designed and much more comprehensive way by data streams (see https://github.com/elastic/elasticsearch/issues/53100).  As such, I'm going to close this issue.  We can reopen if necessary.
