### ISSUE TITLE
add  wildcards for [json remove processor]

### ISSUE THREAD

**Issue by binnn6** [elastic/elasticsearch#42486]
Hello, I need to add  wildcards for [json remove etc. processor]? Something like this.
`{
    "processors":[
        {
            "json":{
                "field":"string_*"
            }
        }
    ]
}`
Is there any solution now ? or a pr is welcomed?

**Comment by martijnvg** [comment]
I think in order to support this we need to add wildcard support to field lookup in ingest, which doesn't support today. So unfortunately that isn't a trivial change.

**Comment by martijnvg** [comment]
We discussed this and the easiest way to support this is adding the ability to iterate over multiple fields for the `foreach` processor. We could add `field_prefix` option to the `foreach` processor that allows running arbitrary processors over multiple fields. This way other processors can also benefit from wildcard support. Labelled this as a high hanging fruit, because this change isn't very trivial.

**Comment by abhiroj** [comment]
can I take this up?

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
