### ISSUE TITLE
BulkProcessor hangs instead of timeout

### ISSUE THREAD

**Issue by lin-ye** [elastic/elasticsearch#42528]
The problem described at https://discuss.elastic.co/t/bulkprocessor-hangs-instead-of-timeout/147737 doesn't seem resolved yet, and we got the same problem on the Java High Level Rest Client 6.5.4. Any plan on a fix for it?

**Comment by zhaomoran** [comment]
I also encountered this problem in 6.3.1，I found this problem occurs when the cluster is busy.
BulkProcessor.builder(consumer, new BulkProcessor.Listener()) will occurs this problem.
BulkProcessor.builder(client, new BulkProcessor.Listener()) will throw RemoteTransportException、EsRejectedExecutionException

**Comment by henningandersen** [comment]
@lin-ye and @zhaomoran , thanks for reporting this. Are you able to reproduce this in a standalone test case? If so, can you either share the code or describe what the test does?

I suspect you may have run into #36770, which is fixed in 6.6+. Is an upgrade to a newer version possible to see if this resolves the issue?

**Comment by astefan** [comment]
No further feedback received. @lin-ye @zhaomoran if you have the requested information please add it in a comment and we can look at re-opening this issue.
