### ISSUE TITLE
type_missing_exception from elasticsearch on mapping request

### ISSUE THREAD

**Issue by nguedon** [elastic/elasticsearch#42594]
Hello,

I use ELK on my server. I have index (created by logstash).

When we request for mapping (with http) => "logstash-2019.05.27/_mapping"

We have response:
`{"error":{"root_cause":[{"type":"type_missing_exception","reason":"type[[logstash-2019.05.27]] missing","index_uuid":"_na_","index":"_all"}],"type":"type_missing_exception","reason":"type[[logstash-2019.05.27]] `missing","index_uuid":"_na_","index":"_all"},"status":404}``

Elasticsearch release 6.7.0

Pipeline output of logstash may be need more parameters (i didn't find type parameter):
`output {
        stdout { codec => rubydebug }
        elasticsearch {
            hosts => "elasticsearch:9200"
            index => "logstash-%{+YYYY.MM.dd}"
            document_type => "_doc"
            manage_template => false
        }
}`

Example of problem on grafana [https://imgur.com/a/kjEjqbw]

Except that mapping error all funcitonalities are working fine.

Thanks

**Comment by cbuescher** [comment]
Hi @nguedon, your question looks like is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. There is an Elasticsearch and a Logstash section, since you are unsure where this problem belongs. One thing to note: [types are in the process of being removed](https://www.elastic.co/guide/en/elasticsearch/reference/6.7/removal-of-types.html) but it looks like your logstash output is still using "_doc" as a type, so [I think you need it to request the mapping still](https://www.elastic.co/guide/en/elasticsearch/reference/6.7/indices-get-mapping.html). You can try this an ask any further advice in the forums please. Many thanks.

**Comment by nguedon** [comment]
Ok thanks for your answer i will go on support forum so ;)
