### ISSUE TITLE
Support comments in ingest pipelines?

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#42592]
Our JSON parser supports C-style block comments, but we only document this in the documentation of index templates.

@ruflin just mentioned to me that they would like to use comments in ingest pipeline definitions in order to document GROK patterns, and switched to Yaml in order to have support for comments.

Should we document that comments are allowed in `docs/reference/api-conventions.asciidoc` and then repeat this information in the documentation of APIs where having comments might be useful such as ingest pipelines and mappings?

**Comment by jimczi** [comment]
We discussed this in FixItFriday and were worried by the fact that some APIs will preserve the comments while other will rewrite the input and comments will be removed internally. For instance `mappings` do accept comments but a GET _mappings will return the schema without the comments while the comments in `_source` documents are preserved in search response if the source is not filtered. However it can be useful for users to have their comments in the original file, for instance in version control, so we agreed that we could document this support with the current limitation. We also said that comments are not in the JSON specification so being lenient is acceptable but we don't want to have an official support for it since it would complexify the handling in lot of places (order of fields in json, ...).

**Comment by jrodewig** [comment]
[docs issue triage]

Closing this issue. Please re-open if you feel more discussion or action is needed.
