### ISSUE TITLE
ILM support @timestamp

### ISSUE THREAD

**Issue by cdenneen** [elastic/elasticsearch#42683]
Currently `max_age` is based on index creation date or `rollover` date.

What happens when you have say 30 daily indexes and need to `_reindex` them all for new mappings. Now all new indexes are based on the newly created date rather than the events in them. Need a way to filter max_age based on a field like `@timestamp` that should be consistent across all events.

**Comment by Ravindranath2511** [comment]
@cdenneen , Are you saying that the lifetime of individual document should be controlled? If this is the case, i think there is no use of controlling the lifetime of a single document while controlling the lifetime of whole index.

**Comment by cdenneen** [comment]
No I’m saying that when you `_reindex` from logs-000011 -> logs-000011-1 for mapping updates. The index creation time changes from original, for example 30 days ago to today. Now if you have 50 indices you are reindexing then they all change from 1-50 day creation dates in the past to 50 today.

**Comment by cdenneen** [comment]
Instead of triggering lifecycle on a field like `@timestamp` maybe the `_reindex` API could allow for copying the creation date from source index to destination?

The issue is if you think about cluster with 90 days retention (20 hot, 40 warm, 20 cold) and there is approximately 1 index per day `logs-000001` -> `logs-000090` and you `_reindex` to `logs-000001_1` -> `logs-000090_1` all new indexes are **hot** with a creation date of today. If there is a way to force the index creation date to be overwritten on the destination index then I think this would allow for the newly created indexes to move to their corresponding `phases` and `node_type`

**Comment by cdenneen** [comment]
Tried to create index with `creation_date` as per: https://www.elastic.co/guide/en/elasticsearch/reference/2.3/indices-create-index.html#_creation_date

```
PUT logs-000068.1_2
{
    "creation_date" : 1407751337000,
    "settings" : {
        "index" : {
            "number_of_replicas" : 0,
            "refresh_interval": -1
        }
    }
}
```

but didn't seem to work:

```
GET logs-000068.1_2/_settings
{
  "logs-000068.1_2" : {
    "settings" : {
      "index" : {
        "routing" : {
          "allocation" : {
            "require" : {
              "node_type" : "hot"
            }
          }
        },
        "mapping" : {
          "total_fields" : {
            "limit" : "1000"
          }
        },
        "refresh_interval" : "-1",
        "number_of_shards" : "6",
        "translog" : {
          "flush_threshold_size" : "1024mb"
        },
        "provided_name" : "logs-000068.1_2",
        "merge" : {
          "scheduler" : {
            "max_thread_count" : "1"
          }
        },
        "creation_date" : "1559664454606",
        "number_of_replicas" : "0",
        "uuid" : "Lr4fP62QRtuV7qQHrEMnKg",
        "version" : {
          "created" : "6080099"
        }
      }
    }
  }
}
```

**Comment by dakrone** [comment]
We discussed this today and decided that the complexity of its introduction (not only of implementation, but also of conception) was not something we want to undertake. It's an eventual goal to lower the time between rollovers to reduce the cognitive load required when reasoning about the age of the index, and this would further complicate that goal. With that in mind I am going to close this for now.

**Comment by bro-adm** [comment]
Hey @dakrone  @Ravindranath2511, is there any update about this concept.

I support the reindex logic shown above and why its an issue for data based retention.
Additionally, ES support updates on data and indices, therefore such an operation to not lose the retention ideals on such occasions is important.
I have a couple of more reason I encountered that would seem to support such a feature.

## Initial Exportation Data

I have textual data (updateable) that contains about 40GB per day.
I want to start working within a new ES cluster so I export the relevant data to it, about 2 months of actual data based retention.
The exportation can be done in less than a day but in the long run I will have a index a day with one or 2 shards, so that is how I will configure my template and main index.
That hurts me when dealing with the initial exportation that will be written into multiple indices according to data size, but it will be deleted by index creation timestamp, making me have about 4 months of data retention up till the first indices deletions.
That is a big problem regarding my actual cluster size.

Exportation does not always happen from another ES cluster nor does it include per say the same rollover configuration.

## Cron Exportation Failures

I export a batch of data each x amount of time, in our case lets make it once a day.
One day my the cluster where my exporter sits is down, it can happen for that lone day, multiple days or even a single hour, but it can be just enough time to make the exportation be a part of a different day than its original required one.
Now my data will be rollover into a new index in a day that does not match the actual time of the data, making multiple indices from different data time ranges exists under the same ILM retention scope (because of the index creation timestamp).
This time I will lose after 2 months of "retention" those indices, therefore leaving me with less then a 2 months data based retention.
Obviously in this case because of the exportation delay I will be missing newer data for a couple of days or hours but that is a different issue not having anything to do with elastic.

BTW, the same thing can be said in reverse if my ES cluster is down and when it gets back up after a certain amount of time (not immediatly) the older data will be part of the new "batch" and the retention accordingly.

Note -> I have ont talked about rollover shard decisions because I believe they are a non-issue because of the max size rollover condition.

--------------------------------------------------------------------------------------------------------------------------------------------

The point is, data based retention and even data based timestamp rollovers are key for consistency and usability of the ES cluster  without just asking for a humongous buffer of disk size and just for easier control over the data.

I would like to know if I am missing a new feature or something that would help me in that manner to control rollover and retention created since the origin issue or what are the plans for the future.
