### ISSUE TITLE
Mislead documentation with regards to deprecated flags : _retry_on_conflict

### ISSUE THREAD

**Issue by ksceriath** [elastic/elasticsearch#42690]
The documentation for breaking changes (migration : https://github.com/elastic/elasticsearch/blob/7.0/docs/reference/migration/migrate_7_0/api.asciidoc) is not consistent with regards to the change in deprecated flags.

 The documentation is misleading and conveys that flags such as _retry_on_conflict should be replaced by retryOnConflict. However, that is not correct, at least as far as the bulk api is concerned:
https://www.elastic.co/guide/en/elasticsearch/reference/7.0/docs-bulk.html#bulk-update

**Comment by jkakavas** [comment]
Hi there @ksceriath , the breaking changes doc mentions: 

> Instead of these removed parameters, use their non camel case equivalents without starting underscore, e.g. use version_type instead of _version_type or versionType.

The `or` there applies to the latter argument, so it's 
```
   use version_type instead of ( _version_type or versionType ) 
```
and not 
```
   (use version_type instead of _version_type) or versionType.
```

Since in the same document, a few lines above, we do mention that camel case parameters ( and we use `versionType` as example)  and all parameters starting with underscore are removed, I believe that the message is conveyed clearly.

**Comment by ksceriath** [comment]
Okay, I stand corrected. Possibly I misread it.
