### ISSUE TITLE
CLI tools output errors on stdout

### ISSUE THREAD

**Issue by nkakouros** [elastic/elasticsearch#43260]
**Elasticsearch version** (`bin/elasticsearch --version`): `Version: 7.1.1, Build: default/deb/7a013de/2019-05-23T14:04:00.380842Z, JVM: 12.0.1`

**Plugins installed**: none

**JVM version** (`java -version`):
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.18.04.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system): `Linux earth-elk 4.15.0-1033-gcp #35-Ubuntu SMP Fri May 17 13:27:54 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:
When running `elasticsearch-setup-passwords` twice, the error is output on stdout.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. `echo y | bin/elasticsearch-setup-passwords auto`
 2. `bin/elasticsearch-setup-passwords auto 2>/dev/null`

You can still see the error message `.

**Comment by tvernum** [comment]
I've re-titled this issue because it applies to all Elasticsearch CLI tools, for example:
```
$ ES_PATH_CONF=/does/not/exist ./bin/elasticsearch-keystore list 2> /dev/null
ERROR: Elasticsearch keystore not found. Use 'create' command to create one.
```

The problem is that we default to using the Java `Console` class for CLI tooling, because it provides better support for things like reading passwords. However, it does not provide support for writing to stderr.

I suspect we could build a hybrid `Terminal` that wrote primary output to the Console, but sent errors to `System.error`, however I have no idea if that would do The Right Thing :tm: on every supported platform.
