### ISSUE TITLE
SQL CSV results fail with null_pointer_exception

### ISSUE THREAD

**Issue by 35penguins** [elastic/elasticsearch#43327]
**Elasticsearch version** 7.1.1

**Plugins installed**: sql

**JVM version**: 1.8.0_131

**OS version**: 2.6.32-754.10.1.el6.x86_64

**Description of the problem**:

When paging over SQL results using CSV format, querying subsequent pages will result in 500 error with reason null_pointer_exception. Other formats, such as YAML, do not fail in this way.

We first encountered the issue in 6.6.1, but I just tested 7.1.1 and the problem still exists.

The only time it doesn't fail is if only a single page is returned.. i.e. no cursor to continue.

**Steps to reproduce**:

Add some data:
```
curl -X PUT "localhost:9200/test/_doc/1" -H 'Content-Type: application/json' -d'{"foo": 1}'
curl -X PUT "localhost:9200/test/_doc/2" -H 'Content-Type: application/json' -d'{"foo": 2}'
```

Select first page as CSV (with 1 row per page):
```
curl -v -X POST "localhost:9200/_sql?format=csv" -H 'Content-Type: application/json' -d'{"query": "SELECT * FROM test", "fetch_size": 1}'
```

Find the Cursor in the headers. E.g.:
```
Cursor: l++rAwFzQERYRjFaWEo1UVc1a1JtVjBZMmdCQUFBQUFBQUNnWTRXTUU1aFkwZzRNRmRVUjNGeVVsOVlORmhDYzA1WGR3PT3/////DwEBZgNmb28BBGxvbmcBWgEAAAEB
```

Use that cursor in another request:
```
curl -X POST "localhost:9200/_sql?format=csv" -H 'Content-Type: application/json' -d'{"cursor":"l++rAwFzQERYRjFaWEo1UVc1a1JtVjBZMmdCQUFBQUFBQUNnWTRXTUU1aFkwZzRNRmRVUjNGeVVsOVlORmhDYzA1WGR3PT3/////DwEBZgNmb28BBGxvbmcBWgEAAAEB"}'
```

It will fail with:
```
{"error":{"root_cause":[{"type":"null_pointer_exception","reason":null}],"type":"null_pointer_exception","reason":null},"status":500}
```

**Comment by astefan** [comment]
@35penguins thank you for reporting this.
It's now fixed in:
master (8.0.0): https://github.com/elastic/elasticsearch/commit/0ef7bb0f8b07cd0392d37f96ca9360821b19315a
7.x (7.3.0): https://github.com/elastic/elasticsearch/commit/fe0f9055d8de4626b2eb83ece4b63cdcadfdad75
7.2 (7.2.1): https://github.com/elastic/elasticsearch/commit/023441990607ccb59edd750e4d7e08ead6a75f32
7.1 (7.1.2): https://github.com/elastic/elasticsearch/commit/b6189083d9e51c0edb604044c1eb01cbf951d6fc
6.8 (6.8.2): https://github.com/elastic/elasticsearch/commit/3fcd2812d5f591bbab540b217bc43ef8a1c06656
