### ISSUE TITLE
The launch of Elasticsearch as a Windows Service should use the bundled JDK

### ISSUE THREAD

**Issue by ZeTo12** [elastic/elasticsearch#43375]
From version 7 Elasticsearch is available with a bundled JDK.

The installation as Windows Service using 'elasticsearch-service.bat' still assumes that the environment variable %JAVA_HOME% is set.

After the service installation the path of the JVM to start Elasticsearch as a Windows Service is '%JAVA_HOME%\bin\server\jvm.dll'. When starting the variable %JAVA_HOME% is resolved. In most cases this will probably point to an already installed JDK. This will then be used to run the Elasticsearch Windows Service.

The currently scripts are using the bundled JDK to install the Elasticsearch Windows Service in case that %JAVA_HOME% is not set. But '%JAVA_HOME%\bin\server\jvm.dll' is used when starting the installed Elasticsearch Windows Service.

In my view this does not really make sense if the JDK is bundled with Elasticsearch.

The scripts to install Elasticsearch as a Windows Service should always use the bundled JDK. 
**The launch of Elasticsearch as a Windows Service should use the bundled JDK.**

**Elasticsearch version** 
Version: 7.1.1, Build: oss/tar/7a013de/2019-05-23T14:04:00.380842Z, JVM: 12.0.1

**JVM version**
bundled JVM: 12.0.1

**OS version**
Windows

**Comment by jasontedor** [comment]
@rjernst Can you take a look?

**Comment by rjernst** [comment]
JAVA_HOME should be set at the beginning of the service script, where we call elasticsearch-env.bat. In there, we look for JAVA_HOME, but fall back to setting it to the bundled jdk.

However, it looks like this intended behavior may not have worked before 7.2.0. Before that, we used to resolve JAVA_HOME at service start time, instead of install time (fixed in https://github.com/elastic/elasticsearch/pull/39714).

Can you upgrade to 7.2.0 and confirm this works for you? We do have tests for this, and I just doubled checked they are currently passing, so I am fairly confident this works as intended in 7.2.0+.

**Comment by rjernst** [comment]
Oops, 7.2.0 isn't quite released yet. Let's wait until that is done and then hopefully you can try it out to confirm it fixes your issue.

**Comment by ZeTo12** [comment]
OK I can confirm in version 7.2.0 the installed Windows Service is using the bundled JDK in case that the JAVA_HOME environment variable is not already set.
The warning when installing the service with a unsupported JDK is also very helpful.
Thank you.
