### ISSUE TITLE
[ML] Make source checks more lax for dataframe transforms

### ISSUE THREAD

**Issue by andrewvc** [elastic/elasticsearch#43439]
It would be nice to loosen up the checks around Data Frames, even if only optionally.

In beats we create the dataframe as part of process startup, but don't start indexing events till after that, creating a bit of a chicken and egg problem. The exact amount of time can vary due to the fact that events may not come in right away.

It would be useful to define the DataFrame first, before any indices are created. Having it run as a noop before then is a fine outcome. Otherwise, client code needs to be more concerned with order of operations. As-is, creating a dataframe where the source index pattern matches nothing yields the following error:

```
Source index [heartbeat-8.0.0-*] does not exist
```

**Comment by andrewvc** [comment]
FYI, our workaround is going to be to always create an empty index matching the pattern.

**Comment by davidkyle** [comment]
The check for the source index existence has to be repeated on Data Frame start not just at creation in case the index has disappeared between `PUT` and `_start`, so I do think there is room to relax the check on PUT. However, we do strongly prefer to validate early rather than let the user take multiple steps before returning an error which may have been due to a simple typo in step 1. This applies to API and UI users but for the UI in particular deferring the check would complicate the flow.

> even if only optionally.

The only way I can see this is with an optional `don't_validate_at_creation_because_you_will_do_it_all_again_at_start` parameter which feels a little clunky but is probably better than the work around.

**Comment by andrewvc** [comment]
@davidkyle hmmm, well given that the primary concern is the UI use case, would it be a problem to move the check to the UI, and remove it from the backend in ES?

**Comment by hendrikmuhs** [comment]
API-1st: I do not think we should move complex logic into the UI, the UI is great to get started but we do not aim to be UI-only, direct API support is as important, be it dev console are interacting with data frames using a language client (e.g. python).

@davidkyle suggestion sounds good to me, skipping validation sounds like a special case. We only need better parameter naming. `validate=false`?

alternative: we could ignore validation errors in case of a special parameter: `ignore_validation_errors`

But I prefer the skipping idea.

**Comment by dimitris-athanasiou** [comment]
I am not a huge fan of adding that flag. Having a `validate` flag is very confusing as it is not that we will skip all validations. We'll just skip some of them. Perhaps we can call it `force` instead, though it still suffers from ambiguity.

**Comment by davidkyle** [comment]
`?soft_validation`

I'm not a huge fan of the flag either but if there is a pressing need..

**Comment by andrewvc** [comment]
It would be a problem if the transform stopped working, or become unstartable because a user purged their indices to start fresh for instance. We could enter a half-broken state where the time series data is coming in, but the data-frame isn't started. That would mean we'd need to create a watchdog process ensuring that the frame is always started.

Given that we have two use cases a flag seems best. We don't particularly care as to the naming since we'll be hiding this from users, but we want to declaratively state "data from this index pattern should be transformed continuously into this other index", and we want that rule to hold whether the data source disappears temporarily or not.

**Comment by davidkyle** [comment]
The team discussed this and there was widespread agreement that we should add the flag and much debate about naming it. Suggestions included `ensure` or `force` but the favourite was `defer`.

`?defer_validation=true`

**Comment by davidkyle** [comment]
Here's a list of validations we make on PUT and those I suggest are deferrable

Validation | Deferrable
----------|-----------
Licensing check |  No
Simple regex check that source and destination indices do not overlap | No
Check for missing source index | Yes
Expanded source index expression contains destination index | Yes
Check destination index expression resolves to at most 1 index | No
User has privilege to read source index | Yes
User has privilege to create dest index | Yes
PivotConfig check aggregation types are supported | No
Run a test query | Yes


The validations on starting the data frame aren't as rigorous because the data frame will fail pretty quickly anyway. For example there isn't a check that the source index is present because if it is missing the destination index mapping cannot be calculated causing the the data frame to fail with a `Failed to deduce dest mappings` _caused by_ `no such index [foo]`

Of those checks that are deferrable some should be repeated on data frame start

Validation | Deferrable | Repeat check on start
----------|-------------|-----------------------
Check for missing source index | Yes | No this is caught by the deduce mappings function
Expanded source index expression contains destination index | Yes | Yes 
User has privilege to read source index | Yes | Yes
User has privilege to create dest index | Yes | Yes
Run a test query | Yes | No the data frame will fail quickly

**Comment by andrewvc** [comment]
Thanks for the comprehensive list @davidkyle. One question, if using the deferred setting, can the dataframe still be started without the source index being in existence, or does that cause the start command to fail due to the failed test query?

**Comment by davidkyle** [comment]
If the checks have been deferred and the source index is missing the data frame will fail on start in one of 2 ways:

1. If the destination index does not exist it is created with mappings deduced from the source index mappings. If the source index is missing the deduction will fail, this is the `Failed to deduce dest mappings` error mentioned above.

2. The destination index exists but the source index has disappeared. The data frame will run encountering errors and retry with back off. Eventually the data frame will fail after a max number of retries. 

That is the situation in 7.2 I'd recommend to ensure the existence of the source index before start. 7.3 has continuous data frames which may be more tolerant to errors, I'll look into how continuous data frames react and update here.

**Comment by andrewvc** [comment]
Thanks @davidkyle . We do have a workaround, which is a dummy empty index that always matches the source, but it'd be nice not to have to use that.
