### ISSUE TITLE
DocsClientYamlTestSuiteIT.test {yaml=reference\cluster/stats/line_10} failing on Windows

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#43501]
This test checks for the `using_bundled_jdk` field which is not available on Windows. 

https://scans.gradle.com/s/obq3ujfdlcl4o/tests/jbm2x6tnwtxku-i7d2m4u2kx2m4

**Comment by mark-vieira** [comment]
This should be addressed by #43502.

**Comment by williamrandolph** [comment]
I checked build-stats and we haven't seen `DocsClientYamlTestSuiteIT test {yaml=reference\cluster/stats/line_10}` fail with `stashed value not found for key [body.nodes.jvm.versions.0.using_bundled_jdk]` since June 24th (when #43502 was merged). Prior to that, it was often failing 2-4 times per day. I'm going to go ahead and close this.
