### ISSUE TITLE
Prevent fielddata loading for _id

### ISSUE THREAD

**Issue by jpcarey** [elastic/elasticsearch#43599]
**Describe the feature**: Need a way to prevent fielddata memory issues due to aggregating / sorting on `_id`

**Comment by martijnvg** [comment]
I ran into this today too. There is no way to disable loading of field data in the jvm heap. Because `_id` field is not configurable and doesn't have doc values enabled, this can cause a large part of the jvm heap be taken if someone sorts or aggregates on the `_id` field.

Either field data should be allowed to be disabled via configuration or field data should always never be loaded for the `_id`. The latter maybe a better choice when #46523 has been completed, because then there is no need to sort by `_id` with search after in order to get consistent sort order.

**Comment by AndrewMcQuerry** [comment]
Thanks to @jasontedor and @SpeechlessWick (and others!) for discussing this with us yesterday at the AMA booth.

Just adding this note here to echo the need for some sort of protection against the _id field causing fielddata Heap consumption.  There have been multiple instances in both Test and Prod clusters where some user has performed some action (we assume this to be a sort or aggregation) which has caused all of our Data nodes in the cluster to consume large amounts of Heap for fielddata.  Our only solution at this time is to simply check or audit the fielddata usage for "_id" and then manually clear the cache when/if we see it consuming large amounts.

**Comment by jimczi** [comment]
I opened https://github.com/elastic/elasticsearch/pull/49166 to disallow the loading of the `_id` field through a cluster setting. The goal is to get ride of the fielddata entirely but we're not there yet so the setting could be useful to prevent loading in 7x.
