### ISSUE TITLE
Search validation dependents on cluster having documents

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch#43870]
Asserted this on `7.0.0` and `7.2.0` might be true for previous releases as well.

On a cluster with no indices:

```json
GET /_cat/indices

HTTP/1.1 200 OK
content-type: text/plain; charset=UTF-8
content-length: 0

<Response body is empty>

Response code: 200 (OK); Time: 20ms; Content length: 0 bytes
````

```json
POST /_search
{
  "size" : 10000000
}
```

returns:

```json

HTTP/1.1 200 OK
content-type: application/json; charset=UTF-8

{
  "took": 0,
  "timed_out": false,
  "_shards": {
    "total": 0,
    "successful": 0,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 0,
      "relation": "eq"
    },
    "max_score": 0.0,
    "hits": []
  }
}
```

As soon as you index a document however:

```json
PUT http://172.18.0.1:9200/index/_doc/1
{}
```

```json
HTTP/1.1 201 Created
Location: /index/_doc/1
content-type: application/json; charset=UTF-8

{
  "_index": "index",
  "_type": "_doc",
  "_id": "1",
  "_version": 1,
  "result": "created",
  "_shards": {
    "total": 2,
    "successful": 1,
    "failed": 0
  },
  "_seq_no": 0,
  "_primary_term": 1
}

````

The same search:

```json
POST /_search
{
  "size" : 10000000
}
```

now returns:

```json
POST /_search

HTTP/1.1 400 Bad Request
content-type: application/json; charset=UTF-8

{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Result window is too large, from + size must be less than or equal to: [10000] but was [10000000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "index",
        "node": "kffPdOMaTPCJIeNxM8UHnw",
        "reason": {
          "type": "illegal_argument_exception",
          "reason": "Result window is too large, from + size must be less than or equal to: [10000] but was [10000000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."
        }
      }
    ],
    "caused_by": {
      "type": "illegal_argument_exception",
      "reason": "Result window is too large, from + size must be less than or equal to: [10000] but was [10000000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.",
      "caused_by": {
        "type": "illegal_argument_exception",
        "reason": "Result window is too large, from + size must be less than or equal to: [10000] but was [10000000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."
      }
    }
  },
  "status": 400
}
```

If you then delete the `index` again you will get a `200` for the same search once again.

**Comment by jaymode** [comment]
I'm going to remove the Core/Infra REST API label here as the validation is handled within search and I think the @elastic/es-search team would be best to discuss the issue for a resolution.

**Comment by cbuescher** [comment]
This is still happening on the current `main` branch. We would like to fix this in a way that always runs the validation regardless of the index size.

**Comment by cbuescher** [comment]
Note that this *only* seems to happen on a fully empty cluster, i.e. even when you add an empty index via `PUT /index`, the error is thrown as expected.

**Comment by cbuescher** [comment]
We cannot validate the from/size parameters already in parsing the rest request because the size limit this is checked against is an index parameter. We currently do this when creating the SearchContext (DefaultSearchContext#preProcess()), and this happens correctly with even empty indices. The problem when querying a totally empty cluster is that we shortcut to return an empty response when starting the search action after index name resolution (AbstractSearchAsyncAction#start()). When there are no shards to search, we simply return an empty response. 
I think adding validation at this point would be very odd, given that this is an extremely rare case in practice. Also, as mentioned earlier, the setting we are checking here (index.max_result_window, default 10000) is an index setting, so if there are no indices at all, it is not clear to me why we would want to check (even against the default). 
@Mpdreamz this has been opened for a while, so it seems like more of an observation than something really posing a problem. I'm inclined to leave this as-is and not fix it for the reasons mentioned above. Would that be okay for you?

**Comment by cbuescher** [comment]
@Mpdreamz I'm going ahead and close this issue, but please reopen if you find the current state of things really doesn't work for you.
