### ISSUE TITLE
HLRC rest_total_hits_as_int

### ISSUE THREAD

**Issue by brackxm** [elastic/elasticsearch#43925]
Add rest_total_hits_as_int by default to the HLRC search requests in 6.8.x
Or add a way to set it (per request or globally).
This to allow the 6.8 - 7.x transition with 6.8 clients connecting to both 6.8 and 7.x servers.

**Comment by talevy** [comment]
We discussed this in our team's FixItThursday and believe the HLRC search request objects should be able to set this. Currently, it seems like this functionality would only be added to 7.x since it planned on being removed in 8.0. I will let @jimczi follow-up whenever he gets the chance. thanks for sharing this gap in the HLRC vs. low-level client @brackxm!

**Comment by javanna** [comment]
This was reported also in our forums, I marked it as a bug as currently it is not possible to use search API on 7.x from a client on 6.x, which we say in our docs it is supported.

**Comment by jimczi** [comment]
Fixed by https://github.com/elastic/elasticsearch/pull/46076 which will be available in 6.8.3 when it released. Thanks for reporting @brackxm !
