### ISSUE TITLE
index.routing.allocation.initial_recovery._id split after shrink

### ISSUE THREAD

**Issue by laf-rge** [elastic/elasticsearch#43955]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.1.1

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

 1. Create an index
 2. Shrink an index
 3. remove the node the shrink occurred on from the cluster
 4. Wait for index to recover
 5. attempt to split the index

**Provide logs (if relevant)**:
Split fails on allocation. Decider says all primary shards must be on the dead node. Can not remove index.routing.allocation.initial_recovery._id setting from index.

**Comment by laf-rge** [comment]
Similar to #31787

**Comment by laf-rge** [comment]
You might be asking yourself: why would you split a node after a shrink? Short answer: bad ILM policy.

**Comment by DaveCTurner** [comment]
Thanks for the report @laf-rge. Splitting an index after a shrink is a legitimate thing to do so this does look wrong. I opened #44053 to address this.

**Comment by laf-rge** [comment]
This is great. Is there a fix for the current version? Will the updated version also fix this?

**Comment by DaveCTurner** [comment]
One possible workaround is to use reindex instead of simply splitting the index. This will take longer, unfortunately, but seems likely to work. Another idea, assuming you haven't already shrunk this index down to a single shard, is to shrink it again (which will overwrite the `index.routing.allocation.initial_recovery._id` setting) and then split it from there.
