### ISSUE TITLE
Support KMS in Google Cloud Storage Repository plugin

### ISSUE THREAD

**Issue by chilang** [elastic/elasticsearch#43962]
Please add support for Cloud KMS/Customer-Managed-Key encrypted Google Cloud Storage bucket in GCS Repository plugin.

**Elasticsearch version** (`bin/elasticsearch --version`):
5.2.2

**Plugins installed**: []
GCS Repository 5.2.2
GCE Discovery 5.2.2

**JVM version** (`java -version`):
openjdk version "1.8.0_212"

**OS version** (`uname -a` if on a Unix-like system):

Linux xxx 3.10.0-957.12.1.e17.x86_64 #1 SNP Wed Mar 20 11:34:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

Currently, attempt to initialize repository with a CMK encrypted bucket 
```
curl XPUT $HOST:9201/_snapshot/my_gcs_repository -d 
{
  "type": "gcs"
  "settings": {
     "bucket": "my-bucket",
     "service_account": "_default_"
  }
}
```
fail with the following

```
{
   "error" : {
     "root_cause": [
        "type": "repository_verification_exception",
        "reason": "[my_gcs_repository] path is not accessible on master node"
     ],
     "type": "repository_verification_exception",
     "reason": "[my_gcs_repository] path is not accessible on master node",
     "caused_by": {
        "type": "i_o_exception",
        "reason": "400 Bad Request\n{\n \"code\" : 400, \n \"errors\" : [ {\n \"domain\" : \"global\", \n, \"message\" : \"Operation with Cloud KMS is not supported.\", \"reason\" : \"invalid\"\n }], \n \"message\": \"Operation with Cloud KMS is not supported.\" \n}"
     }
   }
}
```

The same operation works fine with a Google-managed-key GCS bucket.

**Comment by ywelsch** [comment]
[Elasticsearch 5 is EOL](https://www.elastic.co/support/eol). The reason this is not working is because the “Copy Object" method is used by the snapshot functionality in ES 5, which is incompatible with CMK (see https://cloud.google.com/storage/docs/encryption/customer-managed-keys). This has been changed in ES versions >=6.4.0 (see https://github.com/elastic/elasticsearch/pull/31100). This might make CMK with default key work with newer ES versions (it's not tested and therefore not officially supported though).

**Comment by chilang** [comment]
Upgraded to 6.8 and it's working now
