### ISSUE TITLE
elasticsearch not getting started

### ISSUE THREAD

**Issue by Lakshay-Awasthi** [elastic/elasticsearch#43973]
**Elastic Search not getting started**:

**7.2.0 version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**"1.8.0_202** (`java -version`):

**Windows** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

Exception in thread "main" java.lang.NullPointerException
        at org.elasticsearch.tools.launchers.JvmErgonomics.extractHeapSize(JvmErgonomics.java:126)
        at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:58)
        at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:89)

**Comment by andrewjames0304** [comment]
It works on Java 12. Install JDK12 and retry

**Comment by jvwilge** [comment]
I have the same problem with java OpenJ9 11.  Corretto and OpenJDK 11 work without problems

Non-working version :
```
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.14.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20190418_204 (JIT enabled, AOT enabled)
OpenJ9   - bad1d4d06
OMR      - 4a4278e6
JCL      - 5cc996a803 based on jdk-11.0.3+7)
```

**Comment by rjernst** [comment]
> "1.8.0_202 (java -version):

@Lakshay-Awasthi It is difficult to diagnose this startup failure without more info. In particular, the version of java alone isn't enough. How you installed java and where it came from would also be useful. However, since we have tests with java 8 with all our support jdk vendors, it is highly likely this is an issue with your java vendor. Additionally, it is better to start discussions about possible bugs on [our forums](https://discuss.elastic.co/c/elasticsearch). There is a vibrant community there that can help with diagnosing your issue. We try to keep github reserved for feature requests and confirmed bug reports.

> I have the same problem with java OpenJ9 11

@jvwilge We [do not currently support](https://www.elastic.co/support/matrix#matrix_jvm) J9. Please use a supported jdk.
