### ISSUE TITLE
elasticsearch-setup-passwords auto： Failed to determine the health of the cluster

### ISSUE THREAD

**Issue by OPSTime** [elastic/elasticsearch#43999]
**Error：**

> \# /usr/local/elasticsearch/bin/elasticsearch-setup-passwords auto
> 
> Failed to determine the health of the cluster running at http://10.0.0.1:9200
> Unexpected response code [503] from calling GET http://10.0.0.1:9200/_cluster/health?pretty
> Cause: master_not_discovered_exception
> 
> It is recommended that you resolve the issues with your cluster before running elasticsearch-setup-passwords.
> It is very likely that the password changes will fail when run against an unhealthy cluster.
> 
> Do you want to continue with the password setup process [y/N]y
> 
> Initiating the setup of passwords for reserved users elastic,apm_system,kibana,logstash_system,beats_system,remote_monitoring_user.
> The passwords will be randomly generated and printed to the console.
> Please confirm that you would like to continue [y/N]y
> 
> 
> 
> Unexpected response code [503] from calling PUT http://10.0.0.1:9200/_xpack/security/user/apm_system/_password?pretty
> Cause: Cluster state has not been recovered yet, cannot write to the security index
> 
> Possible next steps:
> * Try running this tool again.
> * Try running with the --verbose parameter for additional messages.
> * Check the elasticsearch logs for additional error details.
> * Use the change password API manually. 
> 
> ERROR: Failed to set password for user [apm_system].
> 

**Network Interface:**

> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
>     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
>     inet 127.0.0.1/8 scope host lo
>        valid_lft forever preferred_lft forever
> 2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
>     link/ether 00:16:3e:10:08:9b brd ff:ff:ff:ff:ff:ff
>     inet 172.17.183.98/20 brd 172.17.191.255 scope global dynamic eth0
>        valid_lft 315355664sec preferred_lft 315355664sec
> 3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
>     link/ether 02:42:e4:e4:d0:2e brd ff:ff:ff:ff:ff:ff
>     inet 172.18.0.1/16 brd 172.18.255.255 scope global docker0
>        valid_lft forever preferred_lft forever
> 4: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default 
>     link/ether be:f6:10:c9:cb:87 brd ff:ff:ff:ff:ff:ff
>     inet 10.244.0.0/32 scope global flannel.1
>        valid_lft forever preferred_lft forever
> 5: cni0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default qlen 1000
>     link/ether 52:a8:37:28:e4:51 brd ff:ff:ff:ff:ff:ff
>     inet 10.244.0.1/24 scope global cni0
>        valid_lft forever preferred_lft forever
> 6: vethd2ec8964@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default 
>     link/ether 3e:e0:b5:fd:08:f6 brd ff:ff:ff:ff:ff:ff link-netnsid 0
> 7: veth1f4eb9c2@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default 
>     link/ether 0e:27:0c:ee:e2:cb brd ff:ff:ff:ff:ff:ff link-netnsid 1
> 8: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 100
>     link/none 
>     inet 10.0.0.1 peer 10.0.0.2/32 scope global tun0
>        valid_lft forever preferred_lft forever
> 

**Listen Port:**

> \# netstat -tnlp |grep java
> tcp        0      0 0.0.0.0:9200            0.0.0.0:*               LISTEN      8876/java           
> tcp        0      0 0.0.0.0:9300            0.0.0.0:*               LISTEN      8876/java  

**Version:**
**Elasticsearch: elasticsearch-6.8.1
jdk: openjdk version "1.8.0_212"**

**the cluster running at http://172.17.183.98:9200, not  http://10.0.0.1:9200**

**Comment by tvernum** [comment]
@OPSTime There doesn't appear to be any bug here.

> Cause: master_not_discovered_exception

Your cluster isn't in a healthy state, so it is not possible for the tool to set the user passwords.

If you need assistance working out what is going with your cluster, please visit our [discussion forums](https://discuss.elastic.co/C/elasticsearch/) and provide a copy of your elasticsearch logs.

**Comment by OPSTime** [comment]
the cluster running at http://172.17.183.98:9200, not http://10.0.0.1:9200

**Comment by OPSTime** [comment]
How to specify parameter connection  cluster http://172.17.183.98:9200

**Comment by tvernum** [comment]
Please ask user questions on the forums, or consult the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/setup-passwords.html).
We reserve GitHub issues for bug reports and feature requests only. The forums are the appropriate place to handle these questions.

**Comment by OPSTime** [comment]
This is a bug，the cluster running at http://172.17.183.98:9200, not http://10.0.0.1:9200

**Comment by ollydixon** [comment]
Also stuck with this. Installing ElasticSearch is painful, to say the least.

**Comment by KishanP-protean** [comment]
it is giving error on latest version of elastic search for password reset. 
[user@web elasticsearch-8.4.1]$ bin/elasticsearch-reset-password -u elastic
warning: ignoring JAVA_HOME=/usr/local/jdk-11.0.0; using bundled JDK

ERROR: Failed to determine the health of the cluster.

do you know where the default password are stored or how can we reset this we installed this with tar.gz

**Comment by ultraalkaline** [comment]
Why was this closed? Clearly people are still facing this issue

**Comment by ladung** [comment]
same issue! anyone help me please?

**Comment by tvernum** [comment]
:wave: Hello visitors.

This issue is closed because the original problem description was not a fault in the "elasticsearch-setup-passwords" tool. The reporter's cluster had not formed correctly (`master_not_discovered_exception`) and it is impossible for the tool to configure passwords on a cluster that does not have an elected master node because it is impossible to make any changes to the data on such a cluster. The issue with cluster needs to be resolved before the setup-passwords tool can be used.

 If you have landed on this issue because you have the same situation, commenting here won't help. But here's what you can do...

Firstly, if you are using Elasticsearch 8 or higher, you should try to use `elasticsearch-reset-password` instead of `elasticsearch-setup-passwords`. That has similar error conditions, so the resolution steps below may be still be relevant.

If you use `elasticsearch-setup-passwords` and have the error message:
```
Failed to determine the health of the cluster running at <<your node's URL>>
Unexpected response code [503] from calling GET <<your node's URL>>
```
Then your cluster was not able to form correctly, and you need to try and work out why.  
It will not be due to password problems (the nodes in a cluster do not use password to authenticate with each other), and you cannot fix the problem by running the "elasticsearch-setup-passwords" tool (or the newer "elasticsearch-reset-password" tool).  
Instead, you should first inspect your Elasticsearch logs. If you don't know how to find your log files, then check the [information in the Elasticsearch docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/logging.html) based on your platform and the type of Elasticsearch package you installed. Then follow the [troubleshooting guidance in the Elasticsearch docs](https://www.elastic.co/guide/en/elasticsearch/reference/master/discovery-troubleshooting.html), and if, after reading and following those docs, you cannot resolve the problem, then ask in the [Elasticsearch discussion forums](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6).

Alternatively, if you have the error message:
```
Your cluster health is currently RED.
```
Then your cluster has formed correctly, but is not healthy. Again, you should check your [Elasticsearch logs](https://www.elastic.co/guide/en/elasticsearch/reference/current/logging.html), and then follow the [troubleshooting guides](https://www.elastic.co/guide/en/elasticsearch/reference/master/diagnose-unassigned-shards.html).

The message:
```
Connection failure to: <<your node's URL>>/_security/_authenticate?pretty failed: Connection refused
```
means that the tool cannot find a node to connect to. There are 2 likely causes:
1. Your node isn't actually running. Check your [Elasticsearch logs](https://www.elastic.co/guide/en/elasticsearch/reference/current/logging.html) to see if you have a running node, or if it was shutdown for some reason.
2. Your node is running, but the URL that the tool picked isn't correct. That can happen sometimes if you have an unusual networking setup. You can use the `-u` option to the tool to specify the correct URL.

 Finally, the message:
```
Failed to authenticate user 'elastic' against <<your node's URL>> 
```
mean that the tool is trying to use the [_bootstrap password_](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/built-in-users.html#bootstrap-elastic-passwords) but the password does not work. Typically this is because you have already run `elasticsearch-setup-passwords` on this cluster, and the bootstrap password is no longer in use. You cannot use `elasticsearch-setup-passwords` to _reset_ the cluster's passwords after they have been set. This tool in only for setting up the passwords for the first time. In Elasticsearch 8 (and later), you can use `elasticsearch-reset-password` to reset an existing password that you have lost/forgotten.
