### ISSUE TITLE
ILM:  _retry using wildcard should skip indices that are not managed by ILM

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#44188]
6.7.0

When using POST */_ilm/retry to retry on all indices, ILM will throw the following illegal argument exception:

```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "cannot retry an action for an index [.monitoring-kibana-6-2019.07.10] that has not encountered an error when running a Lifecycle Policy"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "cannot retry an action for an index [.monitoring-kibana-6-2019.07.10] that has not encountered an error when running a Lifecycle Policy"
  },
  "status": 400
}
```

The reason statement indicates that it is because `.monitoring-kibana-6-2019.07.10` does not have a step error.

But `.monitoring-kibana-6-2019.07.10` is not even an index managed by ILM to begin with:

```
{
  "indices" : {
    ".monitoring-kibana-6-2019.07.10" : {
      "index" : ".monitoring-kibana-6-2019.07.10",
      "managed" : false
    }
  }
}
```

The retry API should skip over indices that are not managed by ILM .

**Comment by joegallo** [comment]
I talked with @dakrone about this one, and we think that given that automatic retries should be much more effective from 7.13.0 on (because of https://github.com/elastic/elasticsearch/issues/48183 and its **many** associated PRs), that this is probably no longer necessary and can be skipped. Of course, feel free to reopen this if we've missed something.
