### ISSUE TITLE
.ml-config mappings are not updated on cluster upgrade

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#44263]
When .ml-config index is created in the old version (say, 6.8), cluster is upgraded to a new version (say, 7.3) and the first config document with a new field is indexed (e.g: DataFrameAnalyticsConfig), the default mapping type (i.e. type "keyword") is applied for this new field as implemented in ElasticsearchMappings::addDefaultMapping. This default behavior is usually not desirable.

**Comment by droberts195** [comment]
This is critical to fix before anyone who previously used ML in 6.6-7.2 uses data frame analytics.  Otherwise their `.ml-config` mappings will be wrong and the only way to recover is a complicated reindex into an index with the correct mappings while care is taken not to use any ML functionality in the meantime.
