### ISSUE TITLE
Please change default GC config with G1GC

### ISSUE THREAD

**Issue by teahyuk** [elastic/elasticsearch#44321]
**Describe the feature**:
Default GC config is 'CMS' but this feature is using imbedded jdk with 'openjdk 12'

 #36828

**Elasticsearch version** (`bin/elasticsearch --version`):
7.2.0

**Plugins installed**: []

**JVM version** (`java -version`):

```
[root@localhost /]# /elasticsearch-7.2.0/jdk/bin/java -version
openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment (build 12.0.1+12)
OpenJDK 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)
```

**OS version** (`uname -a` if on a Unix-like system):

- It probably does not matter.

``
[root@localhost /]# uname -a
Linux localhost.localdomain 2.6.32-696.el6.x86_64 #1 SMP Tue Mar 21 19:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
``

**Description of the problem including expected versus actual behavior**:
 - same with #36828
```
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
```
1. So I must have change config using GC or using jdk
2. Can I Use ZGC?

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Just extract 'tar.gz'  (banilla)
 2. Start %EXTRACTED_ELASTIC_HOME%/bin/elasticsearch
 3. It is a little inconvenient. (must have change config)

**Provide logs (if relevant)**:

**Comment by danielmitterdorfer** [comment]
Thanks for your interest in Elasticsearch. We still think that the CMS garbage collector is the best option for the majority of deployments at this point but we do support now G1GC as well since Elasticsearch 6.5.0 (if running on JDK 11 or better). There is currently an open PR (https://github.com/elastic/elasticsearch/pull/44145) which will improve our documentation here.

> So I must have change config using GC or using jdk

No, that is not required. This message is informational and means that the CMS garbage collector is deprecated, i.e. it might be removed in a future JDK.

> Can I Use ZGC?

At this point the only garbage collectors that are supported by Elasticsearch are CMS and G1GC. To be clear: From a purely technical perspective you can use ZGC with Elasticsearch but that's not something that we test and hence it's not a supported configuration.

**Comment by teahyuk** [comment]
thank you
