### ISSUE TITLE
Can Elasticsearch calculate the "weight" of a shard?

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#4434]
Can Elasticsearch calculate the "weight" of a shard?  It'd be nice just to be able to look at which shards are hot.  Also, it could be useful to rebalance hot shards away from one another.

This seems like it'll be likely in my deployment because my indexes all have very different sizes and usage patterns.

**Comment by markharwood** [comment]
@nik9000 We were discussing this on FixItFriday - do you have an updated viewpoint?

Our thoughts were that the allocation decider is currently pretty black or white in it's rule evaluation (this needs to be here because this rule says so). If I understand correctly this introduces shades of grey into the rule evaluation which starts to take us down the path of being less easily explainable as to why certain decisions were made. Given all the existing factors that go into the mix of allocation decisions it might be challenging to add this sort of fuzziness?

**Comment by nik9000** [comment]
Ah, man, this one is ancient! At this point I imagine allocation deciders based on runtime conditions are too contentious.

This PR is so out of date its really only useful from an archaeological standpoint, but if I were to revive it I'd just try to get the weights calculated and fetch-able via `_cat` and friends. At that point it'd mostly be useful for detecting hotspots of various sorts.

The idea is that things like "time spent searching" and "time spent indexing" aren't particularly useful measures to _look_ at and make decisions about. But their derivative is. And we can get a decent estimate of it using load average style calculations quite cheaply. This is all stuff you can do in marvel with a derivative aggregation but that requires storing the data and having marvel, both of which make it not something elasticsearch can rely on having at all times.

Here is what I'll do: I'll close this. If we ever want to do smart stuff based off of the relative activity on the shards we can use this as a reference point.
