### ISSUE TITLE
secondOfDay Date Field API not working v7.2.0

### ISSUE THREAD

**Issue by markwheal** [elastic/elasticsearch#44411]
**Elasticsearch version** (`bin/elasticsearch --version`):
v7.2.0

**Plugins installed**: []
**JVM version** (`java -version`):
**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

Since upgrading to 7.2.0 my scripted field of *doc['timestamp'].date.secondOfDay* has stopped working, and no data shows up in Discover mode!

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

*doc['field_name'].date.secondOfDay* is given as an example in documentation - https://www.elastic.co/guide/en/elasticsearch/reference/7.2/modules-scripting-expression.html

I have also tried *doc['@timestamp'].date.secondOfDay* - note the different field name; *timestamp* is our own field that we populate.

**Comment by albertzaharovits** [comment]
@pgomulka Maybe you have an idea on hand? I have found https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#_scripting_with_dates_should_use_java_time_based_methods but I didn't managed to make it work.

**Comment by rjernst** [comment]
@markwheal Your script example was:

```doc['timestamp'].date.secondOfDay```

This uses the `.date` accessor on long fields, but this was removed in https://github.com/elastic/elasticsearch/pull/30690 for 7.0. Date fields are now accessed through `.value`, and the type is now ZonedDateTime. Additionally for 7.0, we have switched to java time as our backend, which means the `.secondOfDay` access is deprecated (this was something specifically in joda). You will need to make sure your timestamp field is a date field, and not just a long field. Long term, you should use `doc['timestamp'].value.get(ChronoField.SECOND_OF_DAY)`. However, investigating this issue made me realize the get method is missing from our compatibility layer, so I opened #44829.

Given the issue here is use of `.date`, which was removed, I'm going to close this issue.
