### ISSUE TITLE
XPackInfoRequest doesn't call StreamInput super ctor

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#44634]
The XPackInfoRequest does not currently call the StreamInput super constructor. This means it will not have the parent task id deserialized. This is ok since the writeTo also does not call super, but this is contrary to the normal pattern for requests. Effectively this does not matter since the request never will have a parent task (I don't think?), but we should probably fix this to call super.

**Comment by williamrandolph** [comment]
This looks like a small effort, with backwards compatibility as the main implementation concern. I can pick this up.

**Comment by williamrandolph** [comment]
I took another look at the code, and I think we might be better off leaving this class as it is and, if we need parent task IDs, handling them explicitly rather than calling the superclass constructor and writeTo method.

Here's my thinking: in the constructor of a Java class, if you want to call the superclass constructor, `super()` must be the first statement in your constructor. You can't wrap it in a conditional, so we can't use `in.getVersion()` to decide whether we need to read a parent task ID or not. (The writeTo method doesn't have the same limitation.)

Now, we _could_ go up the trail of superclass constructors and make sure that this class's constructor conditionally executes all the statements that the `super(in)` constructor executes, but that seems really brittle.

What we could do for safety is override the `getParentTask()` method in `XPackInfoRequest` so that it throws an error if someone tries to use it.

**Comment by rjernst** [comment]
@williamrandolph I think we can migrate the class to handling the parent task Id by conditional reading/writing in XPackInfoRequest, then in `master` switching to use the super ctor. I don't think we should leave the class as it is, since that means any other changes/improvements to the base class would be silently lost on this subclass. We really shouldn't be avoiding the upset class. It is unfortunate, but this is a side effect of expecting two different constructors to exist for each request/response. We should be using the StreamInput super here, but are implicitly using the ctor meant for normal construction.
