### ISSUE TITLE
Add packaging tests for Debian 10 “Buster”

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#44657]
[Debian 10 “Buster”](https://wiki.debian.org/DebianBuster) is [released](https://wiki.debian.org/DebianBuster#Release_and_updates) as of 2019-07-06. We should create a debian-10 image and packaging tests on it.

We have open elastic/infra issues to address this:

- [x] [Create Debian 10 images for CI #14314](https://github.com/elastic/infra/issues/14314)
- [x] [Add debian 10 CI jobs #15289](https://github.com/elastic/infra/pull/15289)

**Comment by atorok** [comment]
We'll also need CI images and need to add it to os compatibility matrix in ci.

**Comment by atorok** [comment]
We are about to add the testing to CI for unix compatibility and new style packaging tests. 

We still need to add this to the Vagrant based tests and if we don't see any issues to the  `general purpose` pool.

**Comment by droberts195** [comment]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+packaging-tests-unix-next/os=debian-10-packaging/44 found a couple of problems:

1. `PackageTests.test50Remove` failed because `systemctl --version` apparently returns `systemd 241 (241)` but we're trying to match that using the regex `^systemd (\d+)\n`.  See https://gradle-enterprise.elastic.co/s/2pyo5k2zrvrta/tests/tf5flfhasytje-igloddw7ln7vw?openStackTraces=WzBd for details.
2. `DebMetadataTests.test05CheckLintian` failed because `lintian --fail-on-warnings` says `Unknown option: fail-on-warnings`.  See https://gradle-enterprise.elastic.co/s/2pyo5k2zrvrta/tests/tf5flfhasytje-slutvg55r3ade for details.

**Comment by atorok** [comment]
The packaging tests are now part of the matrix jobs and passing.
We don't have vagrant images yet, we'll have those once the work to generate them from the same source as the CI ones completes in the mean time, @rjernst @mark-vieira and I agreed we can consider a platform covered as long as we have the CI matrix tests running.
