### ISSUE TITLE
Fix type inconsistencies in 6.x docs examples

### ISSUE THREAD

**Issue by cjcenizal** [elastic/elasticsearch#44670]
For example, the [Index Templates 6.0 docs](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/indices-templates.html) have an example that suggests using a type:

```
PUT _template/template_1
{
  "index_patterns": ["te*", "bar*"],
  "settings": {
    "number_of_shards": 1
  },
  "mappings": {
    "type1": {
      "_source": {
        "enabled": false
      },
      "properties": {
        "host_name": {
          "type": "keyword"
        },
        "created_at": {
          "type": "date",
          "format": "EEE MMM dd HH:mm:ss Z YYYY"
        }
      }
    }
  }
}
```

However, the [Index Templates 6.5 docs](https://www.elastic.co/guide/en/elasticsearch/reference/6.5/indices-templates.html) suggest using the `_doc` type.

```
PUT _template/template_1
{
  "index_patterns": ["te*", "bar*"],
  "settings": {
    "number_of_shards": 1
  },
  "mappings": {
    "_doc": {
      "_source": {
        "enabled": false
      },
      "properties": {
        "host_name": {
          "type": "keyword"
        },
        "created_at": {
          "type": "date",
          "format": "EEE MMM dd HH:mm:ss Z YYYY"
        }
      }
    }
  }
}
```

I suggest we reconcile these types of inconsistencies throughout 6.x so that users have an easier time understanding and accommodating the types deprecation change.

**Comment by DaveCTurner** [comment]
Thanks @cjcenizal, I think the particular discrepancy you highlight is somewhat deliberate, because `_doc` wasn't a legal type name until https://github.com/elastic/elasticsearch/pull/27816 (i.e. 6.2.0), so we can't use `_doc` in the 6.0 reference documentation. That PR adjusts quite a lot of the docs, and there were a few followup PRs to deal with things it missed which did not all get backported all the way to 6.2. The case you highlight was fixed in #29667 (i.e. 6.4.0). Would you be interested in back porting that to 6.3 and 6.2?

As a user, the best bet is to upgrade to 6.8 (which is compatible with earlier 6.x releases) and then use the 6.8 docs.

**Comment by cbuescher** [comment]
+1 to what @DaveCTurner said. Using "_doc" as the "dummy" type in later 6.x documentation is necessary, but at the same time we cannot use it going backwards. I understand the irritation but the docs are in sync with what each of the minor versions requires in this case I think.
@cjcenizal does this explanation make sense to you and would you mind if we close this issue?

**Comment by cjcenizal** [comment]
@cbuescher Yes, this makes sense. Thanks for the explanation. I'll close this issue and backport https://github.com/elastic/elasticsearch/pull/29667 to 6.3 and 6.2 per @DaveCTurner's request.
