### ISSUE TITLE
transport.netty.worker_count

### ISSUE THREAD

**Issue by laijianbin** [elastic/elasticsearch#44890]
ES version 6.8.0

How to set "transport.netty.worker_count" 

`public static RestHighLevelClient createHighLevelClient(String host, int port) {
		RestHighLevelClient client = new RestHighLevelClient(RestClient.builder(new HttpHost(host, port)));
		Sniffer.builder(client.getLowLevelClient()).build();
		return client;
	}`

**Comment by tvernum** [comment]
Thanks very much for your interest in Elasticsearch.

There seems to be some confusion here - the Rest clients do not use "transport" or netty, so that setting is not relevant to the code you have provided.

This is the sort of topic that we like to direct to our [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. The discussion forums are beter suited to these sorts of troubleshooting and problem diagnosis conversations.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

Thank you.

**Comment by laijianbin** [comment]
Ok,thanks for your help
