### ISSUE TITLE
WARN logging of "all shards failed" at startup

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#45082]
A user raised a concern [on the forums](https://discuss.elastic.co/t/all-shards-failed-for-phase-query-on-elasticsearch-7-2-0/193270) about a `WARN`-level log indicating `all shards failed` due to an attempt by Kibana to search the `.kibana_task_manager` index while their one-node cluster is still starting up. I can see their point. I think we should contemplate making the logging around this situation less dramatic: we already return an error response to the caller in this case, so a `WARN`-level log is perhaps excessive.

**Comment by jimczi** [comment]
We discussed this in our team meeting and were wondering why the log is showed at the `WARN`   level. Looking at the code, any error during a rest request should be logged in `ERROR` and returned to the user as a `500` (internal server error). We have the same behavior for bulk requests that fail at the coordination level for instance so if we decide to change the level of logging it should be for every request. However since the request failed with an error we find it consistent to also log the error in the node even if this is a recoverable error.

**Comment by javanna** [comment]
There was no action on this, and plans on making changes three years later. Closing.
