### ISSUE TITLE
Surrogate pair characters cannot be registered in [Pattern Replace Char Filter]

### ISSUE THREAD

**Issue by yoshidahiroaki** [elastic/elasticsearch#45229]
**Elasticsearch version** (v7.3.0):

Surrogate pair characters cannot be registered in [Pattern Replace Char Filter]

 1.Try creating the following index
```
PUT test_indx
{
  "settings": {
    "index": {
      "analysis": {
        "char_filter": {
          "surrogate_stop":{
            "type": "pattern_replace",
            "pattern": "[\uD840-\uD87F][\uDC00-\uDFFF]",
            "replacement": ""
          }
        },
        "analyzer": {
          "test_analyzer": {
            "type": "custom",
            "char_filter": [
              "surrogate_stop"
            ],
            "tokenizer": "standard"
          }
        }
      }
    }
  },
  "mappings": {
    "properties": {
      "test": {
        "type": "text",
        "analyzer": "test_analyzer"
      }
    }
  }
}
```

 2.Receive a response
 ```
{
  "statusCode": 504,
  "error": "Gateway Time-out",
  "message": "Client request timeout"
}
```

**Comment by javanna** [comment]
hi @yoshidahiroaki it looks like you get a timeout. How are you sending your request? I am asking because I am not sure that what you provided is the response you get from Elasticsearch. It would be good to know how your client timeouts are configured, and see whether you can find any error in the server logs at the time of your request.

**Comment by markharwood** [comment]
No further feedback received. @yoshidahiroaki if you have the requested 
information please add it in a comment and we can look at re-opening 
this issue.
