### ISSUE TITLE
Rollup index not recognized as such

### ISSUE THREAD

**Issue by kandelon** [elastic/elasticsearch#45387]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.3.0

**Plugins installed**: []

**JVM version** (`java -version`): cloud

**OS version** (`uname -a` if on a Unix-like system): cloud

**Description of the problem including expected versus actual behavior**:
In working around a different issue I have spun up a fresh cluster, put in some data and templates and created a rollup job via kibana. The job was successfully created and the rollup index started filling with data. However, _rollup_search returns no data (sum/max/etc all come back as null) and on investigation the rollup index has no rollup meta data and GET /*/_rollup/data returns an empty object. I've created other simple indexes and rollup jobs on the cluster and they all come out the same. It seem like the rollup indexes is not being recognized as such, even though the task is running and adding rollup data.

**Comment by polyfractal** [comment]
Do you happen to have index templates in the cluster that might match the `rollup_index` itself?

There was a bug (just fixed in https://github.com/elastic/elasticsearch/pull/43943) which doesn't merge existing index templates into the rollup settings/mappings correctly.  The side-effect is that the existing index template "wins" and the `_meta._rollup` fields aren't added to the new index.  The job itself works fine, but anything relying on the `_meta` field (like index caps API, or `_rollup_search` which needs the config for validation)

**Comment by kandelon** [comment]
Ah, I do indeed! Thanks. I think I can get by without the template for now.

**Comment by polyfractal** [comment]
:+1: That bugfix should be part of the next release (7.4), and at least in the mean time you can add important settings/mappings into the rollup index manually after creation.  A pain, but should work until 7.4 is released :)
