### ISSUE TITLE
Parent is not getting set, using UpdateRequest in JavaAPI

### ISSUE THREAD

**Issue by sandy6jain** [elastic/elasticsearch#4538]
I found a similar bug https://github.com/elasticsearch/elasticsearch/issues/3444, but it is not fixed in JavaAPI with requesting using UpdateReuest.
To resolve this, "UpdateRequest.java" should have property "parent" & it should be used while generating upsertRequest. (I am using version 0.90.5)
Test with the following code : 

curl -XPOST 'http://localhost:9200/123'
curl -XPOST 'http://localhost:9200/123/TableWithParent/_mapping' -d '
{"TableWithParent" : {"_parent" : { "type" : "Table1" }}}'

Inserting data using JavaAPI:
--
public static void main(String[] args) {
		Client client = NodeBuilder.nodeBuilder().node().client();
		Map<String, Object> data = new HashMap<String, Object>();
		data.put("column1", "colVal1");
		UpdateRequest updateRequest = new UpdateRequest();
		updateRequest.index("123");
		updateRequest.docAsUpsert(true);
		updateRequest.routing("123");
		updateRequest.parent("parentID");
		updateRequest.id("123|8|627110220645727|662022187154530");
		updateRequest.type("TableWithParent");
		updateRequest.doc(data);
		client.update(updateRequest);
	}

Below query, should return parent object:
curl -XGET 'http://localhost:9200/123/TableWithParent/123|8|627110220645727|662022187154530?routing=123&pretty&fields=\_parent,\_source'

Thanks

**Comment by martijnvg** [comment]
I misunderstood what had to be done for this issue. The `parent` option should not have been removed instead the parent option shouldn't update the parent of an existing document. This was already the case as the update logic ignores the parent option (and routing option too).

The issue here is that although in normal use case the parent option is ignore and just a place holder for routing, in the case a document doesn't exist the parent option should be delegated to the upsert document.

I'll do the following changes:
* Revert the commit on master.
* Make sure that if parent has been set on update request that it delegates this to the parent option on upsert request or doc request if `doc_as_upsert` option has been set to true.

**Comment by lukens** [comment]
Any timeline as to when this might get resolved?

After spending a morning trying to figure out why my `has_child` query wasn't working, I tracked it down to the Java API not setting the parent when inserting on an upsert.

This has left me a bit scuppered.

Any suggestions for a workaround would also be appreciated.

**Comment by martijnvg** [comment]
@lukens #9612 fixes the issue. It has been targeted to 2.0,  but I think it can be included in 1.x branch, which means it make it in 1.5 release.

**Comment by lukens** [comment]
Thanks, I've copied in the changes to `UpdateRequest` and `UpdateHelper` from the pull request into the 1.4.4 versions of those classes, and have managed to get it working.

I believe I found an issue with the changes though, and have added a comment: https://github.com/elasticsearch/elasticsearch/pull/9612/files#r25503572
