### ISSUE TITLE
[Feature Request] execution hint map to composite term aggregation

### ISSUE THREAD

**Issue by sdba9914** [elastic/elasticsearch#45490]
adding  execution hint map to composite term aggregation in order to improve preformance

Liat

**Comment by henningandersen** [comment]
@sdba9914 thanks for your interest in elasticsearch. In order to process this issue we need to know more about why this feature is necessary and what kind of performance improvement you think can be achieved by it. Also, if this concerns specific use cases, a description of those is relevant.

**Comment by sdba9914** [comment]
we need to scroll search on buckets and we want to avoid loading global ordinals

thank you , Liat

**Comment by polyfractal** [comment]
Hi @sdba9914, I'm going to close this in favor of https://github.com/elastic/elasticsearch/issues/45490 since @jimczi opened that with some technical ideas how to implement it (e.g. avoiding global ords entirely instead of just adding an execution mode).

Thanks for the enhancement request!  Subscribe to #45490 if you'd like to receive updates if/when progress is made :)

**Comment by sdba9914** [comment]
Hi ,

45490 is the closed git issue
what is the number of the new one ?

Liat

‫בתאריך יום ד׳, 2 באוק׳ 2019 ב-18:53 מאת ‪Zachary Tong‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by polyfractal** [comment]
Sorry about that!  The issue I _meant_ to type was: https://github.com/elastic/elasticsearch/issues/47452

I'll edit the above post to reflect that.
