### ISSUE TITLE
Histogram is not starting at the right min even filter added

### ISSUE THREAD

**Issue by Hearen** [elastic/elasticsearch#45595]
### The Mapping

```
          "eventTime": {
            "type": "long"
          },
```

### The Query

```
POST some_indices/_search
{
  "size": 0,
  "query": {
    "constant_score": {
      "filter": {
            "range": {                   
              "eventTime": {
                "from": 1563120000000,
                "to": 1565712000000,
                "format": "epoch_millis"
              }
        }
      }
    }
  },
  "aggs": {
      "min_eventTime": { "min" : { "field": "eventTime"} }, 
      "max_eventTime": { "max" : { "field": "eventTime"} }, 
      "time_series": {
        "histogram": {
          "field": "eventTime",
          "interval": 86400000, 
          "min_doc_count" : 0,
          "extended_bounds": {            
            "min": 1563120000000,
            "max": 1565712000000
          }
        }
      }
  }
}
```

### The Response

```
"aggregations": {
    "max_eventTime": {
      "value": 1565539199997
    },
    "min_eventTime": {
      "value": 1564934400000
    },
    "time_series": {
      "buckets": [
        {
          "key": 1563062400000,
          "doc_count": 0
        },
        {
          "key": 1563148800000,
          "doc_count": 0
        },
        {
        ...
```

### Question

As the reference clearly mentioned

> For filtering buckets, one should nest the histogram aggregation under a range filter aggregation with the appropriate from/to settings.

I set the filter properly (as the [demo][1] does) and the `min` and `max` is also providing the evidence. 

But why still the **first** `key` is *SMALLER THAN* than the *from* (or min_eventTime)?

### References

- https://www.elastic.co/guide/en/elasticsearch/reference/5.5/search-aggregations-bucket-histogram-aggregation.html#search-aggregations-bucket-histogram-aggregation

  [1]: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/search-aggregations-bucket-histogram-aggregation.html#_minimum_document_count

I hacked out a solution for now, but I kind of think it's a bug in Elastic Search. 

I am using [`date_histogram`][2] instead though the field itself is a long type and via `offset` I moved the starting point forward to the right timestamp. 

```
  "aggs": {
    "time_series": {
      "date_histogram": {
        "field": "eventTime",
        "interval": 86400000,
        "offset": "+16h",
        "min_doc_count": 0,
        "extended_bounds": {
          "min": 1563120000000,
          "max": 1565712000000
        }
      },
      "aggs": {
        "order_amount_total": {
          "sum": {
            "field": "order_amount"
          }
        }
      }
    }
  }
```

  [2]: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/search-aggregations-bucket-datehistogram-aggregation.html#_offset

**Comment by polyfractal** [comment]
Hi @Hearen :)  This is an interaction between the `extended_bounds.min`, the `interval` and where the data actually lands in the histogram.  The process works like this:

1. All the shards collect buckets about where the data lands, rounding each value to the correct bucket
2. Shard results are sent to coordinator node, coordinator merges all the results together for a single set of buckets
3. If `extended_bounds` is configured, the buckets are extended from the min/max of the data.  It adds buckets backwards (according to the `interval`) until it hits the `extended_bounds.min` value.  Notably, due to the interval rounding, the bucket's `key` could be "past" the min value.
4. Finally, empty buckets between data points are filled in.

So basically, the `extended_bounds` parameter doesn't guarantee a specific cutoff... it guarantees that buckets will reach to at least that point.  The exact end points are dependent on the interval.  The histogram by default begins at `0` and generates buckets from there.  You can see that the min bucket is `1563062400000`, which is evenly divisible by `86400000` (`1563062400000 / 86400000 == 18091` to be precise)

Histogram offers an `offset` like date_histo, which allows you to shift how buckets are rounded: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-histogram-aggregation.html#_offset_2

I'm going to close as this is expected behavior and not a bug.  There's not really anything we can do: if we cut the aggregation off right at the `extended_bounds.min/max`, we would generate buckets that are not the full interval and that would break many assumptions about how the histogram works.
