### ISSUE TITLE
Don't index geo points by default, use doc values instead

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#4562]
Today, geo points are indexed as a single token `<latitude>,<longitude>`. This index is later uninverted into field data which is in-turn used for geo-distance computations. In practice, we never do term-based search on geo points so we should rather use doc values instead of the inverted index: we wouldn't waste time inverting and later uninverting the data, and this would be more space efficient.

In order to keep the experience consistent with previous versions, by default field data is going to be loaded into memory from doc values. In order to leave data on disk, the `doc_values` field data format will need to be configured explicitely.

**Comment by clintongormley** [comment]
No longer relevant with the new geo fields coming in 2.1

**Comment by sumesh-agarwal** [comment]
What is the status of this in 2.0? If doc_values for a 'geo_point' type field is set to true, does it mean that it will be stored in disk? I ask because, my 'fielddata' size doesn't seem to go down even after setting doc_values to true (and re-indexing ofcourse). Could someone please help?

**Comment by jpountz** [comment]
@sumesh-agarwal when you break down fielddata usage per-field,a are the fields using most memory storing geo points? Also note that geo point fields are getting completely revamped in the upcoming 2.2 release.

**Comment by sumesh-agarwal** [comment]
@jpountz Yes. Of around 1.2 GBs of field data used per node, around 700 MBs is being used by a geo point field. I don't understand this. If geo point fields get their field data stored on disk by default, shouldn't it not appear in the usage? I read somewhere that we see non-analyzed strings in the field data usage because of the global ordinals built for them, and I too see a few non-analyzed string fields in my cluster appearing under the usage (a few KBs only). But geo point appearing there seems quite unsettling. On heavy load, my nodes go out of memory and I can't seem to get around this problem. On analyzing a heap dump I found that Long objects are taking the maximum space there, so I figured doc_values could solve this problem. Could you please throw some light on this?

**Comment by nknize** [comment]
@sumesh-agarwal I'm assuming you're on a 2.0 or 2.1? Are you using `lat_lon : true` in the `geo_point` mapping? And are you using any geohash aggregators?

**Comment by sumesh-agarwal** [comment]
@nknize I am on 2.0, and no, I have not set lat_lon : true in the geo_point mapping. Yes, I am using geohash aggregators with precision value - 5 and size - 1000.
