### ISSUE TITLE
Don't overwrite existing fields in GeoIP processor

### ISSUE THREAD

**Issue by jderose9** [elastic/elasticsearch#45752]
Please allow GeoIP processor to run without blowing away existing property values. This would be consistent with the logstash plugin which merges the objects. Perhaps a config setting to toggle overwrite/merge would be best.

I am trying to store all values in the appropriate ECS fields (for example, client.geo), and would like the client application to persist any of the geo data that it may have since it is likely more accurate.

**Comment by martijnvg** [comment]
Thanks for opening this issue @jderose9. 

> Perhaps a config setting to toggle overwrite/merge would be best.

Yes, I think so too. We properly need to default to overwrite in order to need break bwc and we can consider to default to merge in the next major version (8.0 and later). Perhaps `merge_on_overwrite` is a good name, as the some processors support `overwrite` setting that controls whether a field should overwritten if it already exists.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
