### ISSUE TITLE
Elasticsearch 7.3.0: _cat/count?h=dc&local throws a 400

### ISSUE THREAD

**Issue by demudrol** [elastic/elasticsearch#45843]
**Elasticsearch version** (`7.3.0`):

**Repo**: (`docker.elastic.co/elasticsearch/elasticsearch:7.3.0`)

**Plugins installed**: none

**JVM version** (`12.0.1`):

**OS version** (`4.17.2-1.el7.elrepo.x86_64`):

**Description of the problem including expected versus actual behavior**:

Calling _cat/count?h=dc&local should return total count of documents on local node, as it says in [cat count API](https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-count.html#cat-count):

> local
(Optional, boolean) If true, the request retrieves information from the local node only. Defaults to false, which means information is retrieved from the master node.

Instead, it returns a 400:

```
 {
   "error": {
     "root_cause": [
       {
         "type": "illegal_argument_exception",
         "reason": "request [/_cat/count] contains unrecognized parameter: [local]"
       }
     ],
     "type": "illegal_argument_exception",
     "reason": "request [/_cat/count] contains unrecognized parameter: [local]"
   },
   "status": 400
 }
```

**Steps to reproduce**:

 1. Navigate to /_cat/count?h=dc&local, e.g. http://localhost:9200/_cat/count?h=dc&local
 2. Get a 400
 3. Go to nearest corner
 4. Assume fetal position
 5. Cry a little

Can we restore this functionality please? There is also hint in Kibana with local value, but it fails

**Comment by dakrone** [comment]
I'm pretty sure this is a documentation bug, the `?local` flag usually refers to a request that retrieves something from the cluster state (retrieving it locally instead of issuing an internal redirect to the master node). For the 'count' endpoint it doesn't make any sense since document count isn't something retrieved from the cluster state.

My inclination would be to "fix" it by fixing the documentation.
