### ISSUE TITLE
Support for extended_bounds in composite aggregation histograms

### ISSUE THREAD

**Issue by awj** [elastic/elasticsearch#46034]
**Describe the feature**:

Add support for `extended_bounds` to the `histogram` and `date_histogram` sources of `composite` aggregations, to match the expectation from the same functionality in regular `histogram`/`date_histogram` aggregations.

**Comment by ndemasie** [comment]
This would be a fantastic feature to have.
It is confusing to the user when the composite bucket `date_histogram` has different supported options than the aggregate `date_histogram` with the same name.

**Comment by jimczi** [comment]
I am not sure I understand how that could be useful ? Could you provide an example or a use case where that would be helpful to support this option. I failed to see what should be the behavior if you have more than a single source (e.g.: `date_histogram` + `terms` ... in any order).

**Comment by ndemasie** [comment]
@jimczi Thanks for the quick response.

Currently, I have a query like...
```
body: {
      query: {
        match: { campaign_id }
      },
      aggregations: {
        breakdowns: {
          composite: {
            size: 10000,
            sources: [
              { ['operating_system']: { terms: { field: 'operating_system', order: 'asc' } } },
              { ['date']: { date_histogram: { field: 'date', calendar_interval: 'day', format: 'yyyy-MM-dd' } } },
              ...
            ]
          },
          aggregations: {
            total: { sum: { field: 'foobar' } }
          }
        }
      }
    }
```

Each of the composite sources is dynamically loaded via a UI "breakdowns" multi-select. The returned data is transformed and returned in a [Google Chart](https://developers.google.com/chart/interactive/docs/gallery).

The business department has introduced a requirement that date breakdowns should include all dates of the campaign. However, since a campaign can have end dates in the future, there is never data within the index docs to query (populated nightly via python scripts).

I was expecting the `date_histogram` to support `extended_bounds` since [it seemed possible](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html) but had to attempt, fail, and google around for some time before discovering that option is not supported for composite buckets.

Perhaps I need to rewrite a new approach to this query but not sure how to approach multi-bucket aggregations with a date field that should include dates within a range regardless of data existing for each date or not.

**Comment by subwai** [comment]
I'd like to chime in on this. We're having similar issues where we're using a composite aggregation to paginate a large amount of date histogram buckets + sub aggregations. Similar to the previous commenter we want to display results for the entire date range, because that's the range our user selects.
The current solution is to generate 0 value results for the missing keys.

I realize that if elastic started returning empty buckets, it could lead to extra requests instead. But in our case it'd be so rare that it's negligible. Being able to add an extended_bounds is a lot simpler than generating 0 results that has to match on key.

**Comment by rbansal9148** [comment]
Hi, Is there any progress on this? I need to use `min_doc_count` and `extended_bounds` to date_histogram.

I am using `composite` sources like sql's `group by A,B,C`.

```
GET resource/_search
{
  "size": 0,
  "aggs": {
    "buckets": {
      "composite": {
        "sources": [
          {
            "dateKey": {
              "date_histogram": {
                "field": "date",
                "calendar_interval": "month",
                "format": "yyyy-MM-dd",
                "min_doc_count": 0,
                "extended_bounds": {
                  "min": "now/d",
                  "max": "now/d"
                }
              }
            }
          },
          {
            "terms": {
              "terms": {
                "field": "author"
              }
            }
          }
        ]
      }
    }
  }
}
```

**Comment by wchaparro** [comment]
This can be done client side, closing as not planned.
