### ISSUE TITLE
network.publish_host ignored

### ISSUE THREAD

**Issue by yonixw** [elastic/elasticsearch#46234]
**Elasticsearch version** (`bin/elasticsearch --version`): elasticsearch   7.1.1 docker

**Plugins installed**: []

**JVM version** (`java -version`): elasticsearch   7.1.1 docker

**OS version** (`uname -a` if on a Unix-like system): docker under ubuntu 18.04

**Description of the problem including expected versus actual behavior**:

`network.publish_host` in config is ignored If my config contains ( I know it is a redundancy of 0.0.0.0 ):
```
network.host: 0.0.0.0
http.host: 0.0.0.0
transport.host: 0.0.0.0
transport.bind_host: 0.0.0.0 
```
If my config contains `network.bind_host: 0.0.0.0` alone instead, the `network.publish_host` is used. I couldn't find any docs that explain this behavior. Why should the published host care what I bound to and how?

For now `network.bind_host: 0.0.0.0` fix it for me. But one day I can split binding across interfaces. Thank in advance!

**Steps to reproduce**:

Use problematic config.

**Comment by martijnvg** [comment]
Hey, thanks for opening this issue. This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there next time, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

I think the reason that `network.*` are not picked up here, is because you also specify *`.host` settings for the http and transport specifically. If `transport.bind_host` is not specified then it defaults to `network.bind_host` and if that isn't specified it defaults to `network.host`.

The way to look at this is, that `network.*host` settings are kind of a default for both transport and http. But in your case your have configured these settings for the transport and http components specifically and therefor `network.*` settings are not used.

I think you should just use `network.host` for now and if you like the split binding across interfaces then you should also use `network.bind_host` setting. If you like that http and transport (for node to node communication) are split on different interfaces then you should just only use `transport.host*` and `transport.host*` settings.

Relevant docs:
* https://www.elastic.co/guide/en/elasticsearch/reference/7.3/modules-network.html#advanced-network-settings
* https://www.elastic.co/guide/en/elasticsearch/reference/7.3/modules-transport.html#_transport_settings
* https://www.elastic.co/guide/en/elasticsearch/reference/7.3/modules-http.html#_settings
