### ISSUE TITLE
MlMappingsUpgradeIT.testMappingsUpgrade fails with testclusters

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#46262]
I'm working in porting bwc tests to run with testclusters and can't get this one to pass:
https://gradle-enterprise.elastic.co/s/oqrlvw6evjqa4/tests/q3vpzt4orcdaq-vgix7kzieu2xs

I'm going to mute this since it's the only one that fails with this conversion and kindly ask someone from the team to take a look.

**Comment by atorok** [comment]
The PR that implements the conversion is #46265

**Comment by droberts195** [comment]
For the record, this test is muted in 7.5 through to master.

**Comment by droberts195** [comment]
The problem is this:

```
[2019-12-12T15:40:11,596][ERROR][o.e.x.m.p.l.CppLogMessageHandler] [v7.6.0-0] [controller/4715] [CDetachedProcessSpawner.cc@184] Child process with PID 4863 was terminated by signal 9
[2019-12-12T15:40:11,733][INFO ][o.e.x.m.j.p.a.AutodetectProcessManager] [v7.6.0-0] Successfully set job state to [failed] for job [ml-mappings-upgrade-job]
```

The test clusters code is killing the ML jobs before it kills the ES JVM.

**Comment by droberts195** [comment]
The code that causes the problem is https://github.com/elastic/elasticsearch/blob/d442ff9223d3fab8ab8aa7e2dd2a494d43adf81f/buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java#L840-L841

It needs to kill the ES JVM before the ML processes.  Otherwise the ES JVM thinks the ML processes have crashed, records them as failed and then they don't start again automatically during the rolling upgrade.
