### ISSUE TITLE
max_snapshot_bytes_per_sec setting on a shared filesystem repository

### ISSUE THREAD

**Issue by hulkk** [elastic/elasticsearch#46305]
As per documentation regarding to the snapshot repository

> You can take a snapshot of individual indices or of the entire cluster and store it in a repository on a **shared filesystem**...

And available settings

> max_restore_bytes_per_sec | Throttles **per node** restore rate. Defaults to 40mb per second.
> max_snapshot_bytes_per_sec | Throttles **per node** snapshot rate. Defaults to 40mb per second.

The throttle setting should be for the repository and not for single nodes that read or write that **shared filesystem**. The available throughput is an attribute of the shared filesystem.

Let's assume that I have a 6 node cluster which has shared filesystem for backups that can provide 240MBps (6*40) throughput.

Everything works well **only** when reads or writes are evenly distributed for every node for this size of cluster.

But if any one of the following changes, there is negative impact:
- more nodes in cluster (8*40 = 320MBps which the storage can't handle)
- load is not evenly distributed (reads or writes are not using the capacity available)

**Comment by original-brownbear** [comment]
@hulkk I don't think that kind of feature is something we can implement in any kind of efficient way. That would require synchronizing the throughput across all the nodes via some mechanism which would require frequent communication between the nodes to give accurate rate limiting since all the nodes would have to constantly acquire permission (and then wait for those permissions) for writing data before doing any writes?

This kind of throttling is probably better handled via the shared file system setup instead. I don't see a way for ES to provide it in an efficient manner given that multiple ES nodes write to the shared FS simultaneously but maybe I'm misunderstanding the feature request?

**Comment by hulkk** [comment]
Could this repository setting be improved in a way that it could be updated dynamically?

**Comment by original-brownbear** [comment]
I think that's something we could do probably. The use case would then be to lower the rate limit when adding more nodes to the cluster?

**Comment by original-brownbear** [comment]
@hulkk though I guess you could just create a new repository (or recreate the one you're using) with a new limit pointing at the same data path and get a dynamic update of the throughput setting that way already?
