### ISSUE TITLE
ILM Hot Phase - Not able to set node filter on hot nodes

### ISSUE THREAD

**Issue by medcl** [elastic/elasticsearch#46302]
**Elasticsearch version** (`bin/elasticsearch --version`): v7.3.1

**Description of the problem including expected versus actual behavior**:

Currently The ILM UI allows you to specify each phrase's setting, it is also possible to specify node filter on warm and cold phase, but for hot phase, there is no way to control shard allocation by specify node attribute, that means, the newly created index are not always allocated on `hot` nodes, which is not a desired behavior, as a work around, it is ok to specify a template to let the new index allocate on hot nodes:

```
PUT _template/ilm-default
{
  "settings":
  {
    "index.routing.allocation.require.tag":"hot"
  }
}
```
but If the ILM UI can handle this seamless that will be perfect. Thanks team.

**Comment by cjcenizal** [comment]
Moved to Kibana: https://github.com/elastic/kibana/issues/44746

**Comment by dakrone** [comment]
We discussed this today and decided against this. There are multiple reasons:

- Configuration should be specified in as few places as possible, so specifying it both in a template AND in an ILM policy duplicates the settings and introduces potential for a mismatch in behavior (expecting it to follow one way and finding that it doesn't)
- ILM enforces its allocation rules, so if a user configured a policy in the `hot` phase that couldn't be conformed, then indices created with that policy would not be able to proceed. This is very dangerous in scenarios where rollover can't happen because the index hasn't transitioned past the allocation step. They could end up filling up a single index without knowing it.
- By putting the allocation in the ILM policy, we'd allocate shards to a random node and then immediately move them. Instead, when the allocation goes into the template, the shards are allocated according to the policy when they are first created, rather than immediately triggering a relocation.

Because of these reasons, we're going to close this issue.

**Comment by cjcenizal** [comment]
@dakrone Can you confirm that using index templates as @medcl outlined would be the right way to control shard allocation during the hot phase?

I created https://github.com/elastic/kibana/issues/53621 so that we can add hints to the UI to make it easier for users to adopt this tactic.

**Comment by dakrone** [comment]
@cjcenizal that's correct. Using index templates or manually setting the settings while creating the index is the correct way to control this.
