### ISSUE TITLE
search threadpool might be necessary to limited as index/bulk did

### ISSUE THREAD

**Issue by rpgmakervx** [elastic/elasticsearch#46360]
**question**: **threadpool.search.size** config may cause oom if someone put a large size on it by accident。

**Elasticsearch version**: found in 5.4.1

**Plugins installed**: []

**JVM version** :1.8

**Description of the problem including expected versus actual behavior**:

In the beginning I try to make capacity expansion for my cluster(version 5.4.1), but where this done, the new nodes’s memory usage increases even more than other old nodes, soon cames a lot of fgc。  finally I found this cause by  many search thread(jstack pid|grep search) ，and found that this property**threadpool.search.size** was set to 256 by developer by accident。

So I saw source code and found that index/bulk's core thread count could be limited no more than 32, but search thread count, if you set your own number, it can read Integer.MAX_VALUE.

code in **org.elasticsearch.threadpool.ExecutorBuilder**
```java
protected int applyHardSizeLimit(final Settings settings, final String name) {
        if (name.equals("bulk") || name.equals(ThreadPool.Names.WRITE)) {
            return 1 + EsExecutors.numberOfProcessors(settings);
        } else {
            return Integer.MAX_VALUE;
        }
    }
```
this method is called by **FiexedExecutorBuilder**(current version search threadpool use **AutoQueueAdjustingExecutorBuilder**)

```java
public FixedExecutorBuilder(final Settings settings, final String name, final int size, final int queueSize, final String prefix) {
        super(name);
        final String sizeKey = settingsKey(prefix, "size");
        this.sizeSetting =
                new Setting<>(
                        sizeKey,
                        s -> Integer.toString(size),
                        s -> Setting.parseInt(s, 1, applyHardSizeLimit(settings, name), sizeKey),
                        Setting.Property.NodeScope);
        final String queueSizeKey = settingsKey(prefix, "queue_size");
        this.queueSizeSetting = Setting.intSetting(queueSizeKey, queueSize, Setting.Property.NodeScope);
    }
```
As applyHardSizeLimit method shown that fiexedthreadpool size is ulimit, not like index/bulk max is 32.  

In current version search threadpool use **AutoQueueAdjustingExecutorBuilder** but thread count also  un limit.  maybe this should be limited to protect human error

**Comment by rpgmakervx** [comment]
I there anybody can discuss about this question?

**Comment by rpgmakervx** [comment]
@jasontedor

**Comment by williamrandolph** [comment]
I'm not sure what the status of this issue is. If we do the same thing with the `search` thread pool that we currently do with the bulk and write thread pools, we will limit the number of threads available for search to "available processors plus one." The default value for the size of the search thread pool is currently `int((# of allocated processors * 3) / 2) + 1`. If there are eight processors, this would mean a default thread pool size of 13 and a maximum thread pool size of 9, which doesn't make much sense.

Is there hard limit that would make sense here? In general, I would hope that if users are tweaking thread pool sizes, they are monitoring the performance impacts of their changes.

I will wait for a little bit of feedback on whether there is a "hard size limit" for the search thread pool that makes sense, but otherwise I may close this ticket as something we don't have a specific plan for doing.

**Comment by williamrandolph** [comment]
We discussed this issue with the team today. One reason that it might make sense to have more threads for search than processors is that search threads often sleep while waiting for I/O from other nodes. We don't see this pattern with the bulk and write thread pools.

Since we don't have a reason to choose a particular formula for an upper limit, we think it is better to give our users the freedom to experiment and see what works for their own search patterns.

I am closing this issue, but we are open to further feedback from the community on this issue.
