### ISSUE TITLE
BUG: use a single trie for all methods

### ISSUE THREAD

**Issue by suikammd** [elastic/elasticsearch#46482]
ES 6.x version use a single trie for all methods which results to covering the already registered handler params. ex
I have two methods : `POST /events/{id}`, `GET /events/{name}`, after registering the `POST` becomes `/events/{name}`.
check `insertOrUpdate` in [https://github.com/elastic/elasticsearch/blob/5436581f696ce27513266090965afc824df76175/server/src/main/java/org/elasticsearch/common/path/PathTrie.java](url)
ES 5.x use different trie for different methods, more reasonable?

**Comment by henningandersen** [comment]
Hi @suikammd ,

you are right, this looks suspect. It can be worked around by using the same wildcard name (which would typically also be desirable?).

I think a check that the namedWildcard is identical should be established (and throw if not), let me know if you have comments to this?

**Comment by suikammd** [comment]
yes, you can avoid these problems by checking the wildcard name conflicts.
I just think the practice in es 5.x is more elegant and reasonable, different methods different tries.

**Comment by henningandersen** [comment]
Hi @suikammd ,

it relates to #25459 and #24437, where options and error handling was changed to suggest the valid HTTP methods. It also cements that the same resource should be the same resource and use same parameter naming. I think that is a good thing, since using different names could be confusing. The parameter names are documented in the rest-specs (.json) and are likely used in client side code generation.

Unless there are compelling reasons to allow different wildcard-names for the same path, I think this should be left as is (but with the proposed check).

**Comment by suikammd** [comment]
thanks, I understand. The current practice seems more restful...
