### ISSUE TITLE
NativeRealmIntegTests tests failed with OutOfMemoryError Direct buffer memory

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#46803]
All the tests in `NativeRealmIntegTests` failed today on `7.x` branch:
https://gradle-enterprise.elastic.co/s/q3qkmolurbooa

Something went wrong when allocating direct buffer memory in the Transport layer:
```java
WARNING: Uncaught exception in thread: Thread[Thread-51,5,TGRP-NativeRealmIntegTests]
java.lang.OutOfMemoryError: Direct buffer memory
	at __randomizedtesting.SeedInfo.seed([7168F60F3A169301]:0)
	at java.nio.Bits.reserveMemory(Bits.java:694)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
	at org.elasticsearch.transport.CopyBytesSocketChannel.lambda$static$0(CopyBytesSocketChannel.java:65)
	at java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:284)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
	at java.lang.ThreadLocal.get(ThreadLocal.java:170)
	at org.elasticsearch.transport.CopyBytesSocketChannel.getIoBuffer(CopyBytesSocketChannel.java:141)
	at org.elasticsearch.transport.CopyBytesSocketChannel.doReadBytes(CopyBytesSocketChannel.java:121)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:597)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:551)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)
```

It does not reproduce locally:

```
./gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.xpack.security.authc.esnative.NativeRealmIntegTests.testUpdatingUserAndAuthentication" -Dtests.seed=7168F60F3A169301 -Dtests.security.manager=true -Dtests.locale=mk-MK -Dtests.timezone=Asia/Damascus -Dcompiler.java=12 -Druntime.java=8
```

**Comment by tlrx** [comment]
@original-brownbear as discussed via another channel, I'm assigning this issue to you.

**Comment by original-brownbear** [comment]
The problem is this:

We create a 1Mb direct buffer as a `ThreadLocal` for each Netty IO thread that we use (and that could be a few depending on the set of tests we run). Reclaiming the memory from these might take a while.

Since this is a pretty unlikely thing to happen (first time I'm seeing it) since we introduced that code, I'm wondering if we should just up the `-Xmx` (or just the allowed direct memory in case we're low on memory) for the test JVMs that use Netty to 2x what it is right now and be happy?

@atorok wdyt, do we have some room for more direct memory here or should we try to fix this by limiting the Netty thread count? (currently we use the default of `2 * processors` in tests)

**Comment by atorok** [comment]
@original-brownbear We could definitely allow internal cluster tests to use more memory.. There's no telling how many nodes are actually running as part of those in general and we don't have that many of them. 
I would be careful to allow for more for rest clusters since we have more instances of those. 

I don't think we need a bigger worker at this time, we could just go ahead and increase it. I think we are doing fine even including the ramdisk.  Also we allow over-commit in CI so OOM will be late to the game, and if we do get it we'll just up the RAM on the workers.

**Comment by original-brownbear** [comment]
@atorok yea, we're just talking about a small subset of tests (no REST tests) here. I'll open a PR with a suggested fix shortly and will ping you there.

**Comment by original-brownbear** [comment]
I looked through the build stats again and this really only happens for the tests the original issue mentions.
I opened https://github.com/elastic/elasticsearch/pull/46816 to lower the worker count just for these now via the settings. 

Sorry for the noise @atorok, I think one test suit doesn't justify messing with the memory settings here in hindsight. My bad

**Comment by original-brownbear** [comment]
This unfortunately happened again: https://gradle-enterprise.elastic.co/s/rv4veifcuahus

The fix in #46816 doesn't improve the situation enough it seems. In hindsight just limiting the Netty worker (and hence number of concurrently allocated buffers) might not be enough of a solution here. These tests create clusters of multiple nodes in rapid succession so even if we only allow 3 workers per node, that's still 15 MB for each cluster (and that is not counting all the other buffers needed by encryption and whatnot). I'll try to come up with a better way to limit direct memory use here.

**Comment by original-brownbear** [comment]
Update: the deeper issue here seems to be that we're tracking direct byte buffers via an actual thread local while in the NIO networking we track them via a field that is effectively a thread local but does not use a weak reference. This seems to create situations where many nodes + low-heap-pressure means that the weak references for the thread local buffers aren't cleaned up quickly.

**Comment by ywelsch** [comment]
This means that transport-netty4 without direct buffers is unusable with our ESIntegTestCase infrastructure as it's not properly cleaning resources up after a node is shut down. We see this with security tests as that this is the only place where are we using transport-netty4.

I think we should explore ways to clean up these resources when the transport is shut down.

**Comment by tbrooks8** [comment]
> This means that transport-netty4 without direct buffers is unusable with our ESIntegTestCase infrastructure as it's not properly cleaning resources up after a node is shut down. We see this with security tests as that this is the only place where are we using transport-netty4.

Isn't this just the scenario that we used to have in production where there is not enough heap pressure to trigger a GC? I think setting MaxDirectMemory would fix this, although maybe we don't know what to set it to because there is not as simple of a heuristic (1/2 heap size) as there is in production? Probably a combination of Armin's PR and setting MaxDirectMemory would fix this.

Also the Nio transport uses 256KB buffers opposed to the Netty transport's 1MB. So 1/4 the memory.

There is no way to manually "clean" direct buffers without enabling Unsafe or casting to internally JDK packages.

**Comment by original-brownbear** [comment]
@ywelsch 

> This means that transport-netty4 without direct buffers is unusable with our ESIntegTestCase infrastructure as it's not properly cleaning resources up after a node is shut down. We see this with security tests as that this is the only place where are we using transport-netty4.

I wouldn't quite put it like that. I think security just uses a bunch of instances of the transport and gets very unlucky here. The issue got super rare after I lowered the transport thread count already. I think a slight reduction in the buffer size will get us to a stable place for good.

> I think we should explore ways to clean up these resources when the transport is shut down.

As Tim points out, there's no hard/deterministic way of doing that. We could somehow collect the thread-locals in the treansport threads and clear them out to have `MaxDirectMemory` kick in and not get killed by the `WeakReference` in the `ThreadLocal` holding on to the buffer instance and preventing the off-heap "GC" from eventually dealing with the buffer.
I think the big difference between the normal NIO (which never showed this problem) and Netty is simply the use of actual `ThreadLocal` which brings the weak reference and worse cleanup behavior when in `NIO` we use our own "effective threadlocal" in the `NioSelector`.
