### ISSUE TITLE
Elasticsearch fails to build with java13 

### ISSUE THREAD

**Issue by sunny868** [elastic/elasticsearch#46851]
now I have a error like this :

[root@controller elasticsearch]# ./gradlew build

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':buildSrc'.
> Could not open proj remapped class cache for b77l8t95aaoyzfmksgahn0fs3 (/root/.gradle/caches/5.5/scripts-remapped/build_cdyim6u0g6fd58j8wki77wji9/b77l8t95aaoyzfmksgahn0fs3/proj74e694b976d6abaa826c8abac43e9de8).
   > Could not open proj generic class cache for build file '/home/server195/elasticsearch/buildSrc/build.gradle' (/root/.gradle/caches/5.5/scripts/b77l8t95aaoyzfmksgahn0fs3/proj/proj74e694b976d6abaa826c8abac43e9de8).
      > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 57

now my version is :
Gradle 5.5
java13

**Comment by atorok** [comment]
Thanks for the report @sunny868 

Indeed this is not expected to work. 
No released Gradle version as of this writing  support Java 13. 
According to  gradle/gradle#8681 this will be fixed in [6.0](https://github.com/gradle/gradle/milestone/80) Due in early October as of this writing. 

The Elasticsearch build supports setting a different compiler if you must compile with version `13` , run Gradle itself with `12` and configure the compiler to `13` with  `-Dcompiler.java=<<path to hava 13 home>>`

**Comment by sunny868** [comment]
@atorok thank you
