### ISSUE TITLE
[Feature request] Enable possible third value for terms aggregation on boolean

### ISSUE THREAD

**Issue by EmilBode** [elastic/elasticsearch#46877]
**Describe the feature**:
When doing a terms aggregation on a boolean value, I'd like to see three buckets, `true`, `false` and a bucket for missing values.
The way I was trying to accomplish this was by the following query:
```
GET myindex/_search
{
  "aggs": {
    "booleans": {
      "terms": {
        "field": "mybool",
        "missing": "<missing>"
      }
    }
  }
}
```
But this fails, as `<missing>` is not an acceptable value for a bucket that is expecting a boolean.

I can see why it fails, but would it be possible to change this behaviour? E.g. cast the boolean to a string when a missing value of class String is supplied, or allow a third boolean value such as `null`?
The workaround I'm using now is a seperate missing aggregation, but it isn't as easy to work with.

**Elasticsearch version**: 6.8.1 and 7.3.1

**Comment by polyfractal** [comment]
Hmm...I think the `missing` bucket is probably the way to go.  I haven't looked to see the technical impact, but at least philosophically, we might be treading into dangerous waters if we allow "casting" values to unexpected data types.  E.g. numeric fields return numeric buckets, and so `missing` needs to be numeric.  Ditto to strings, booleans, etc.

Allowing non-datatype values could be unexpected for a client that is expecting all data types to be the same.  We've slowly been trying to remove leniency from APIs since they often cause subtle issues, and this feels like it might go the other direction.

I'll mark this as team-discuss and see what the wider team thinks.  Thanks for raising the issue!

**Comment by polyfractal** [comment]
We talked about this a long time ago but I forgot to update: we chatted and decided not to implement this.  We definitely saw the  utility, but the way things are handled internally means it is a nightmare to deal with technically (since different shards can potentially have different types, it gets very difficult quickly when dealing with different types on the fields and unmapped/missing/scripts).  

Since then, we've actually been putting a lot of work into _removing_ leniency, since that's a big source of subtle edge-case bugs.  So this would be a bit of a step backwards in that regard.

On the upside, this can be handled with the `missing` aggregation as previously mentioned, so the functionality is there just in a different part of the response.

Going to close, apologies again for the long delay!
