### ISSUE TITLE
Range filter - Documents with null range values are returned

### ISSUE THREAD

**Issue by Hemric** [elastic/elasticsearch#46977]
**Elasticsearch version** : 7.3.2
**Plugins installed**: []
**JVM version**: -
**OS version**: -
I'm using the docker image available at **docker.elastic.co/elasticsearch/elasticsearch:7.3.2**

**Description of the problem including expected versus actual behavior**:

Actual behavior : I have document with a field mapped as **integer_range**, when i submit a query using a range filter with **gte** and **lte** it returns me documents intersecting this range but also those with null values.

Query:
```
GET stuff/_search
{
  "query": {
    "bool": {
      "filter": {
        "range": {
          "myRangeField": {
            "gte": 10,
            "lte": 20
          }
        }
      }
    }
  }
}
```
Result:
```
...,
"myRangeField" : {
  "gte" : null,
  "lte" : null
},
...
```
I would have expect that these documents would not be returned as gte/lte stands for greater/lower than or equal and not greater/lower than or equal or null. 

Unfortunately i can't always provide a value for this field at indexing unless a default one (that's what i do at the moment with a value out of my search scope)

**Comment by jtibshirani** [comment]
Hello @Hemric, I first wanted to check I understand the set-up for your question. I assume you've added a document like the following, and are not expecting your search above to match it?

```
PUT stuff/_doc/1
{
  "myRangeField": {
    "gte": null,
    "lte": null
  }
}
```

Specifying `null` for `gte` or `lte` indicates that the range is unbounded in that direction. So the document's range field should be thought of as `(-infinity, infinity)`, which certainly matches against the provided range query.

If you don't want the document to be included in the result, you could omit the field `myRangeField` completely (instead of just setting its bounds to `null`).

**Comment by Hemric** [comment]
Hi @jtibshirani, thanks for answering !

That is exactly what i did.

I wasn't aware *null* should be though here as *-infinity, infinity*. I thought i should keep records close to the mapping. i'll follow your advice then. Thank you !

**Comment by jtibshirani** [comment]
Great -- I will close this out then, as this behavior doesn't indicate a bug.
