### ISSUE TITLE
Add action that checks whether a specific ILM policy is compatible with indices

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#47240]
### Proposal

new endpoint like `_ilm/check` that takes in a policy, index-template, and writing index and checks that all the alias setup is correct.

### Reason
Documentation has been added to help debug issues, but it would be nice to help popular clients of ILM like APM, Beats, Logstash to verify that things are set up correctly before continuing to index.

It is common to run into errors mentioning that the `rollover_alias` is incorrectly set for a managed index

```
illegal_argument_exception: index.lifecycle.rollover_alias [ilm-alias] does not point to index [ilm-managed-index-2020.01.01] 
```

Since there are a few moving pieces (index templates + bootstrapped index setting) that are required to get exactly write for things to operate well, it may be nice to have an endpoint that can sanity check the setup so clients can leverage this to determine whether to continue using the index expecting it will be properly managed by ILM.

For example, Beats with ILM enabled can verify that the indices are properly set up and prevent beats from starting up until things are fixed. The endpoint can provide details of why things were incorrect, etc.

**Comment by gwbrown** [comment]
A few thoughts off the top of my head:
- I think something like this would be super useful
- It's a little awkward, because if you're using an index template, the policy is already set for the index in question (if you used a correct index template to create it)
- I think we can infer the index template(s) to check based on the provided index (so that the user doesn't have to supply a specific template, although having it as an optional field might be useful)
- Including the policy allows us to check more than just rollover setup - for example, we could also check whether the number of shards will work with any shrink configurations in the policy
- A version of this API could (optionally?) add the policy name to the index/index template if the alias/etc. is set up properly, making this a safer version of just adding the policy name index setting
- Wild idea: could we add this as a setting versifier when you try to set the policy name setting? Would that even be a good idea?

**Comment by talevy** [comment]
> Wild idea: could we add this as a setting versifier when you try to set the policy name setting? Would that even be a good idea?

I have been dreaming of the ability to do something like this for a while and never got around to it. Setting verifies do not have any additional context beyond the value, as far as I remember.

**Comment by dakrone** [comment]
This sounds a bit related to #42245, perhaps we could combine the ideas from both?

**Comment by dakrone** [comment]
This will be superseded with the work for datastreams in #53100, so I'm going to close this.
