### ISSUE TITLE
Plain highlighter is crazy slow for fuzzy queries

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#4744]
I don't have consistent reproduction steps but could probably put something together if you need it.  Essentially a query like "fuzzythin~" will match and properly highlight "fuzzything" but the highlighter will take ~100ms chewing on it.  I'm not sure if this is a bug or maybe just something that should be documented.

**Comment by NoelKennedy** [comment]
This problem is affecting us as well.  It does seem to be the '~1' Levenshtein edit distance matches that slows it down.  Prefix searches are unaffected.  This problem is a bit odd because string edit distance searches are several orders of magnitude faster on 120m documents (in 203ms) than they are when the document highlighter runs on 50 docs (in 26 seconds).

**Comment by clintongormley** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/issues/11442
