### ISSUE TITLE
Consider renaming number_of_shards + number_of_replicas

### ISSUE THREAD

**Issue by n0othing** [elastic/elasticsearch#47513]
**Describe the feature**:

Today, users configure primaries + replica shard counts via `number_of_shards` and `number_of_replicas` respectively.

The naming can lead to a bit of ambiguity, and it's not always clear how many shards the resulting index will have.

It might be better to rename the settings to something like:

* `number_of_primary_shards`
* `number_of_replica_sets`

**Comment by ywelsch** [comment]
The main problem I see is that we are not consistent in our terminology when talking about these concepts, in particular with the word *shard* being often times ambiguously used. The [official documentation](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/_basic_concepts.html#getting-started-shards-and-replicas) provides a little bit of guidance, but if you look beyond this linked paragraph, it also shows inconsistent use of this word. **Shards** are a horizontal partitioning of an index. Shards are also replicated, which means that there can be multiple *copies* of the same data. The confusion arises once these **shard copies** are colloquially just referred to as shards. 

It becomes even more confusing when we start talking about *primary shards* and *replica shards*.  In Elasticsearch, one of the copies of a shard is called the **primary**, and all other copies are called **replicas** (while in most other systems, the word replica is used to denote any shard copy). Note that the property of being a primary or replica is something that can change, as a shard copy can be promoted from replica to primary for example, so it's more of a qualifier word. Associating the qualifiers *primary* or *replica* with the word *shard* (which is a horizontal partitioning) therefore does not make sense, it's a qualifier for the individual shard copies. We should always talk about **primary shard copies** and **replica shard copies**, instead of the colloquial primary shard / replica shard. Even better, users should not concern themselves with whether shard copies are primary or replica, which is why we should greatly deemphasize the use of those words.

This brings us finally to the names of these index settings with which you can configure the number of shards and the number of replica shard copies per primary shard copy. As you pointed out, the `number_of_replicas` terminology is confusing here. 

If I was to design this system from scratch, I would probably opt for the following index settings:
- `split_factor` or `partition_factor` to replace `number_of_shards`, as shard seems to be too confusing for many people.
- `replication_factor` to replace `number_of_replicas`, as it's less ambiguous.
- Finally I would move away from the primary/replica terminology, just call all these copies of the data *replicas* (like most other systems do). If further qualification is needed (which normally should not unless you concern yourself with the internals of the system), those can be called *primary* replicas and *secondary* replicas.

OK, enough day-dreaming. Completely switching up the vocabulary isn't really something that we can realistically do at this point, but perhaps try towards more consistent use of the different terms. As you have pointed out, the `number_of_replicas` setting, with its ambiguous meaning, is definitely not helping in this regard. The same problem exists, by the way, with master-eligible nodes, which are often times simply referred to as master nodes, whereas in other places we use that same word to denote the currently elected master, i.e., one of those master-eligible nodes that's currently acting as master of the cluster.

**Comment by jasontedor** [comment]
I agree that there are some places in our documentation where don't use this terminology in a coherent and consistent way. However, the actual [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html) for these settings is fairly clear:

>`index.number_of_shards`: The number of primary shards that an index should have.

>`index.number_of_replicas`: The number of replicas each primary shard has.

Changing the name of these settings would be massively breaking.

**Comment by jpountz** [comment]
We discussed this in FixitFriday and agreed not to change the setting names due to how invasive this would be. However we agreed with you that the terminology we use is ambiguous, so will work on improving it in our documentation, request parameters and response formats.

**Comment by debadair** [comment]
[docs issue triage]

**Comment by jrodewig** [comment]
Closing this as there are no plans to rename `number_of_primary_shards` or `number_of_replica_sets`.

We've also since updated our intro docs to make what's meant by "primary shard," "replica," and "shards" clearer: https://www.elastic.co/guide/en/elasticsearch/reference/master/scalability.html

If there are other specific areas to address, please re-open this issue or open another. Thanks!
