### ISSUE TITLE
Percolator search is way too slow

### ISSUE THREAD

**Issue by Larrik** [elastic/elasticsearch#47602]
Our company has a large number of users, and we use percolators for "saved searches" to compare new "gigs" against.

So upon the addition of a new gig, in order to get all of the ids of the matching searches, we have this elasticsearch-dsl-py code currently:
```
search = indexes.percolator.search.query('percolate', field='query', document=doc)
agg = A('terms', field='_id', size=100000)
search.aggs.bucket('es_ids', agg)
resp = search[0:0].execute()
return [item['key'] for item in resp.aggregations.es_ids.buckets]
```

This feels like a brittle abuse of a feature, but it runs in 15 seconds. Conversely, the apparent "right" way to do this:
```
search = indexes.percolator.search.query('constant_score', filter=Q('percolate', field='query', document=doc))
resp = search.scan()
results = [item.meta.id for item in resp]
```
takes _almost 2 minutes!_

It's possible I'm just not doing this right, but "get all the ids of matching searches" has precious little documentation for such an obvious feature.

**Comment by jasontedor** [comment]
@martijnvg Could you take a look, or should this be a forum topic?

**Comment by martijnvg** [comment]
Hey @Larrik, the percolator is a slow query compared to other queries. This gets very noticeable in a scroll search, because the query gets re-executed on each round trip. What can help here is to increase the `size` to something like 1000 to reduce round trips and sort by a special field named `_doc` (sorting by index order). If you open [a forum topic](https://discuss.elastic.co/c/elasticsearch) and ping me there (and provide additional information, like ES version and information about the type of percolator queries), then I'm happy to provide additional help there. Then if there a changes need to be made (for example doc changes) then we can open another issue in GitHub.

**Comment by Larrik** [comment]
@martijnvg I haven't been able to jump into the forums just yet, but I did want to point out that when I tried using the size parameter, ES gave me an error that you can't set size on a percolator query. Which means it's using 10 as i ts value, which is brutal.

**Comment by martijnvg** [comment]
@Larrik Can you open a forum topic and share the search request that you tried to send to ES?

**Comment by klimchuk** [comment]
Percolate introduced in 5.x has much worse performance than it's predecessor. I don't know what's ElasticSearch as a company thinking providing subpar replacement but that's the way it is. We opened tickets with ElasticSearch support and it went nowhere. Basically it's just not possible to achieve percolate latency comparable with ES 2.x

**Comment by klimchuk** [comment]
Just small update: I ended up writing my own percolate service because ElasticSearch performance was unbearable.
My service is approximately 6 times faster and that means 6 times cheaper to run in AWS.

**Comment by Larrik** [comment]
@klimchuk I'd love to hear more about that service!

**Comment by klimchuk** [comment]
I ended up writing my own implementation of percolate using Go. For exact match it works fine.

**Comment by gbarsky** [comment]
Hello @klimchuk 
Do you mind to share your Go solution for percolate functionality 
Thanks in advance
