### ISSUE TITLE
Make it easier to get started with building ES and importing it to the IDE

### ISSUE THREAD

**Issue by alpar-t** [elastic/elasticsearch#47796]
Right now we require multiple `JAVA<n>_HOME` env variables to be present despite the fact that we have the ability to provision JDKs ourselves. 
We are also lacking some validation in case one of these is not configured correct ( e.x. set to a missing folder or set to a JRE instead of a JDK ).

We should revisit this to make sure that we don't really need anything else than running Gradle with a supported version of the JDK.

**Comment by rjernst** [comment]
While we provision the jdk used within packaging tests, I don't think we do this for tests? AFAIR we still use RUNTIME_JAVA_HOME to control the java used for running tests. If we want to remove the JAVA<n>_HOME that seems fine, but then we need to also remove the alternative sysprops for specifying the java version number to internally select the java N.

**Comment by atorok** [comment]
We do default  `RUNTIME_JAVA_HOME` to `JAVA_HOME` so we can run some tests if it's not set, or use the bundled jdk, so that's fine from a getting started perspective. 
  
We will have to keep the possibility of setting the runtime java home since it's probably not feasible to expect that we will be ale to provision all JDKs we want to test against.  

While we are simplifying, we should remove the env vars and keep the system properties only. There's not much reason to have both.

**Comment by rjernst** [comment]
> keep the system properties

The system property we are discussing is like `-Druntime.java=N` right? How would that work if `JAVA<N>_HOME` is not present?

**Comment by atorok** [comment]
yes, I was thinking about properties such as `runtime,java`. 
My thinking is that it could take either a path, similar to the env var, or a number, which could work without `JAVAN_HOME` if we provision that version of Java instead of relying on  `JAVAN_HOME` being present.

**Comment by mark-vieira** [comment]
> Right now we require multiple JAVA<n>_HOME env variables to be present despite the fact that we have the ability to provision JDKs ourselves.

The only places I'm aware of where this is _required_ is for BWC builds (where we require the Java versions necessary for that branch) and [this particular fixture](https://github.com/elastic/elasticsearch/blob/8f7855464a5c95a738b443f18ae48390fd99128e/modules/reindex/build.gradle#L119). In any case we provide a [pretty descriptive error message](https://github.com/elastic/elasticsearch/blob/55f4988f8d76aa803cd04e9ffbadf1dc906a1b66/buildSrc/src/main/groovy/org/elasticsearch/gradle/BuildPlugin.groovy#L307).

> We are also lacking some validation in case one of these is not configured correct ( e.x. set to a missing folder or set to a JRE instead of a JDK ).

We do [validate these variables](https://github.com/elastic/elasticsearch/blob/02286e9d3d259b6e484da6527eaf2f8f4dd87a83/buildSrc/src/main/java/org/elasticsearch/gradle/info/GenerateGlobalBuildInfoTask.java#L196-L214). We ensure they are pointing to a proper Java install folder for the correct versions. So setting `JAVA9_HOME` to a random folder, or a Java 8 JDK would both result in a build error. I believe we implicitly validate this is a JDK vs JRE via the dependence on `jrunscript` since that's only available in the JDK.

That said, I would like us to make some improvements to our current JDK download plugin before we make the build "self-provisioning" by default. The main one being the unnecessary extracting of the JDK after every `clean`. There are a few ways to solve this but so far it's not been too annoying, but if we use it for _all_ test execution it might get a bit annoying.

**Comment by mark-vieira** [comment]
Closing this as it was addressed by #52606.
