### ISSUE TITLE
The testfixtures plugin should use the reaper to make sure containers are stopped

### ISSUE THREAD

**Issue by alpar-t** [elastic/elasticsearch#47798]
We currently rely on `finalizedBy` to ruin `compose-down`. 
We should switch to the new reaper functionality.

**Comment by rjernst** [comment]
The reaper is specifically for cases where the build dies abruptly. Registering this command in the reaper seems fine, but whatever is run in finalizedBy should then be moved to a doLast (and unregistered from the reaper once it is done), so that normal operation does not leave this running until the build completes.

**Comment by mark-vieira** [comment]
The test fixtures plugin is effectively deprecated. We are slowly removing usages of it so I don't think we'll spend time on improving it.
