### ISSUE TITLE
Packaging-sample-* tests are flaky

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#47961]
I've noticed that packaging-sample and packaging-sample-matrix CI jobs fail quite often with failures that are unrelated to the PR changes. 

Examples: 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+packaging-tests-sample-next/339/
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+packaging-tests-sample/8370/
https://gradle-enterprise.elastic.co/s/vvaikv4d4qxha

Links to CI jobs:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+packaging-tests-sample/
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+packaging-tests-sample-next/

What's more, these jobs seem to be triggered by non-code changes to PRs ( i.e. adding a comment in the PR ) - not sure if this is intentional but while these are flaky, it adds to the frustration :)

**Comment by rjernst** [comment]
It looks like there are several issues there.

 The first example failure appears to be the branch being out of sync with master, where we added the `.ci/os.sh` script, so a transient issue that was resolved naturally by updating.

The second issue is unrelated to packaging tests; the system ran out of memory while compiling java, and so looks like an infrastructure issue.

The last example I have not seen before:
```
error: An action 'destroy' was attempted on the machine 'centos-7',
--
\| but another process is already executing an action on the machine.
\| Vagrant locks each machine for access by only one process at a time.
```

It seems impossible from the gradle perspective, since we only run one gradle task within a project (ie for the vagrant machine) at a time, so a simultaneous vagrant command should not be possible.  I wonder if there was some cleanup on the box on the infra side? I know in the past they have had eg their own destroy that runs after the tests finish.  Alternatively, this might happen if the reaper was somehow triggered, so there could be something there to investigate, but I think we need better logging from the reaper (it has its own log file, which we probably need to dump).

While I understand the frustration as we have been working on the packaging tests a lot lately, I don't see these sample issues as indication the tests themselves are flaky.

**Comment by jkakavas** [comment]
@mark-vieira  asked me to open an issue so that we keep track of these. I'm fine with closing the issue or concluding the tests are not flaky but I'm under the impression more folks are experiencing this. @csoulios mentioned seeing packaging failures often a couple of days back.

**Comment by jkakavas** [comment]
case in point: https://github.com/elastic/elasticsearch/pull/47499

**Comment by mark-vieira** [comment]
Regardless of the tests themselves being flaky, if these builds are frequently failing for folks in their PRs we need to investigate the problems, whether they be infra-related or the tests themselves.

**Comment by rjernst** [comment]
Apologies for my murky response. The concern I have is with a catch all issue like this. There are clearly still some issues that we need to address, but I think those need individual tracking. Having a generic issue that devs start posting their packaging test failures on will not help them be addressed any faster, or possibly at all given it would be difficult to tell what was being worked on and what was not.

**Comment by mark-vieira** [comment]
That makes sense. Thanks @rjernst. Let's close this in favor of specific issues if it's clear there's a existing issue that needs addressing.

**Comment by mark-vieira** [comment]
So I think removing the "legacy" vagrant packaging tests from PR checks will effectively sort this out.
