### ISSUE TITLE
Maps: Add Vector Layer for Country of Liechtenstein 

### ISSUE THREAD

**Issue by BFLB** [elastic/elasticsearch#48024]
I am working on a project where I need to get geo-information in and around switzerland, namely get iso_3166_2 codes of certain areas. I have imported vector layer shapes from https://maps.elastic.co/#file/world_countries for Switzerland, Germany, Austria, Italy and France and it works very well.
Unfortunately there is no map available yet for Liechtenstein (https://en.wikipedia.org/wiki/Liechtenstein). This leads to a blind spot between Switzerland and Austria. Please add a Liechtenstein Layer as soon as possible to close that gap.
Thank you very much in advance.

**Elasticsearch version** : 7.4.0

Sincerly
Bernhard

**Comment by tlrx** [comment]
@BFLB Thanks for using the Elastic Maps Service. As this is the Elasticsearch repository, we focus on issues and bugs that directly concern the search engine. Can you please open a new issue in https://github.com/elastic/ems-file-service ? You should get more feedback there. If you don't mind, I'll close the issue here.

**Comment by BFLB** [comment]
Hi tlrx,
Thank you for your fast reply. I' m fine with that and create a new issue at the suggested place

**Comment by tlrx** [comment]
Thank you!
