### ISSUE TITLE
Facilitate adding new fields to existing indices

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#48063]
One use-case we would like to better support at the stack level is the ability to introduce new fields in time-based indices. The way it is done today consists of adding fields to the index template and maybe an ingest processor so that future indices would pick it up. One issue with this approach is that the field only becomes really available after some time, when all indices in common time ranges have this new field indexed. These couple hours/days during which the field is not yet available on enough historical data are sometimes problematic.

Could we support adding field views to existing indices to better support this use-case, e.g. by supporting scripted fields? Performance would obviously be bad for some time, but this is sometimes a better trade-off than having to wait for a long time before being effectively able to use the new field in Kibana.

Probably depends on #48058

**Comment by colings86** [comment]
The mapping of this field will probably need to contain the type of result expected by the script so we can apply it correctly. For example this could be used to determine which aggregations are applicable to the field and could be returned by field caps API as the field type so client applications can treat the field as if it were an indexed field of the relevant type

**Comment by jpountz** [comment]
@colings86 Agreed. I think it's also important so that these fields can work in the case that some indices have fields mapped as `double` (for instance) and other indices have the field mapped as a script. One option is to have an option in the mapping like you suggested, another one would be to have one field type for each return type.

**Comment by kimchy** [comment]
My suggestion is to break it out into two different features, better support for "runtime" fields, schema on read, however you call it across the board, and the other is to potentially take one and make it indexed.

The idea that someone might decide on a field, add it to the mapping, and then need to wait for data to be able to visualize it is true for some cases. But others, users just want the flexibility and will never index these runtime fields. I think focusing this issue on this aspect creates the wrong set of prioritization towards the end goal.

I think the first end goal is to create runtime fields, that act and behave as natively as much as possible to "regular" mapping fields. Note I intentionally call it runtime fields since we might be constraining ourself with the current script fields capability, and it actually need to be similar to Kibana scripted fields and beyond.

**Comment by javanna** [comment]
Now that we have support for runtime fields as well as data streams, I would lean towards closing this issue in favor of #https://github.com/elastic/elasticsearch/issues/72142 . Feel free to reopen if you think otherwise.
