### ISSUE TITLE
Analytics audit message tests failing

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#48085]
audit message assertions are failing due to a new message now being written to notifications index.

**Comment by romseygeek** [comment]
This is still causing failures in `RegressionIT`, now because the `Stored trained model with IT` message does not always appear.

Build stats link for recent failures is here: https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:'2019-10-18T17:30:38.623Z',mode:absolute,to:'2019-10-23T11:00:00.000Z'))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:e58bf320-7efd-11e8-bf69-63c8ef516157,key:branch,negate:!t,params:(query:pull-request-2,type:phrase),type:phrase,value:pull-request-2),query:(match:(branch:(query:pull-request-2,type:phrase))))),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:RegressionIT),sort:!(time,desc))
