### ISSUE TITLE
Enable build cache for packaging tests 

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#48226]
Now that we only have the new matrix tests for packaging in PRs, it would be nice to think of caching for these. 

We might not want to do anything about it since these have the distributions as input so we would only see a benefit for PRs  that don't change it, e.x. docs and tests. 

We would probably also have to add  a job to intake to run the packaging sample tests if we want to populate the cache.

**Comment by mark-vieira** [comment]
> We would probably also have to add a job to intake to run the packaging sample tests if we want to populate the cache.

Exactly. Since PR builds don't push to the cache, _something_ would have to. We should still enable the cache for these jobs, even if it doesn't cache _tests_.

We'd have to look into how this would all work as well. I suspect we aren't tracking the distribution as an input (since we just pass its _location_ as a system property), and the bats tests are a whole other animal.
