### ISSUE TITLE
Add cutoff_frequency to more query types

### ISSUE THREAD

**Issue by grantr** [elastic/elasticsearch#4839]
`cutoff_frequency` seems really useful for eliminating stopword filters and increasing relevance, but it's only available in the `common_terms` and `match` queries right now. If you're using a query string query, you still need stopword filters.

Can `cutoff_frequency` be supported in other query types like `query_string` or `simple_query_string`?

/cc @dakrone

**Comment by dan-blanchard** [comment]
I was very surprised to see that `more_like_this` doesn't support `cutoff_frequency`, since that seems like it would be one of the places where this could be very helpful.

**Comment by clintongormley** [comment]
@dan-blanchard MLT already has `min_term_freq` and `max_query_terms`.  Not sure what benefit cutoff freq would bring?

**Comment by dan-blanchard** [comment]
@clintongormley `cutoff_frequency` supports relative document frequency, which is really nice feature.

I'm using analyzers that include stopwords, because that is the current recommendation.  To have faster searches it seems like `max_doc_freq` would be closer to `cutoff_frequency`, but again, that is just an integer rather than a relative frequency.

**Comment by mayya-sharipova** [comment]
cc @elastic/es-search-aggs

**Comment by jimczi** [comment]
We want to deprecate this [option](https://github.com/elastic/elasticsearch/issues/37096) because we have optimizations in Elasticsearch 7.0 that knows how to handle high frequency terms efficiently. For this reason I am closing this issue, removing stop words at index or query time should not be required in 7.0.
