### ISSUE TITLE
Range queries logs inconsistent with documentation

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#48538]
At the moment, `range` queries are [documented ](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/query-dsl-range-query.html) as using `gte`/`lte`/`gt`/`lt` format.

At code level though, there is `from` and `include_lower` and their pair - `to` and `include_upper`. These seemed to have been around some time ago - https://github.com/elastic/elasticsearch/issues/9266 and https://www.elastic.co/guide/en/elasticsearch/reference/0.90/query-dsl-range-query.html - but not quite removed. While the documentation talks about `gte` & co. when slow logs are printed for a `range` query the result contains `from`/`to` format.

Relates to https://github.com/elastic/elasticsearch-net/issues/4110 and https://github.com/elastic/elasticsearch/issues/48327.

**Comment by jtibshirani** [comment]
It looks like `from`, `to`, `include_lower`, and `include_upper` were deprecated in 0.90.4 (d6ecdecc19d54b4a37b033a2237a4c76601e9a2d). I think it would be good to perform the following changes:
1. Improve the deprecation notice in 7.x, making sure to issue deprecation warnings and mark query builder methods with `@Deprecated`. In 0.90.4 we added a deprecation note the docs, but didn't go through our current deprecation procedure. In 8.0 we would remove support for the old parameters.
2. Start to use the suggested `gte`/ `lte`/ `gt`/ `lt` parameters in `RangeQueryBuilder#toXContent`. 

Unless we use API versioning, item (2) would be a breaking change in terms of response format. So far I haven't found places other than the SQL translate API that return query definitions as part of their response. Also, perhaps we would consider this a bugfix instead of an API break?

**Comment by cbuescher** [comment]
> Also, perhaps we would consider this a bugfix instead of an API break

+1 on this being treated as an internal  fix, not as breaking. The deprecation was in 0.90.4, the fact that we didn't remove support completely up until now should not keep us from removing it as fast as possible.

**Comment by jtibshirani** [comment]
We re-discussed as a team and decided that this should be considered a bugfix instead of a break. It's a bug that Elasticsearch outputs a query using notation considered deprecated, that has not been documented/ recommended for many years. As far as we know, it should only affect what is logged, and the output of the SQL translate API. We don't consider it a break in either of these cases to update the notation used to represent the range query.

I opened #81276 to update the output of `RangeQueryBuilder#toXContent`. This issue should still be kept open to track adding deprecation warnings for from, to, include_lower and include_upper.

**Comment by javanna** [comment]
> This issue should still be kept open to track adding deprecation warnings for from, to, include_lower and include_upper.

Sounds like we did not get to that and it is kind of late to do it now, closing.

**Comment by mayya-sharipova** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/81276

**Comment by jamshid** [comment]
This fix was only made in Java REST Client 8.x? What about Java REST Client SDK 7.17 users who need application compatibility with both elasticearch 7.17 and 8.x servers (using Compatibility Mode with 8)? 

As of elasticearch 8.16.1 we now get flooded with deprecation warnings like below, even when using the new `RangeQueryBuilder.lte()`/`gte()` methods instead of the deprecated `from()`/`to()`.

Any chance of either making a Java REST Client SDK 7.17 release with this fix? Or if that's not going to happen, making the next elasticearch 8.17 release not log the deprecation warning when it sees that the client is **Elastic's own** 7.17 SDK?

```
{"@timestamp":"2025-02-03T22:32:04.712Z", "log.level": "WARN",  "data_stream.dataset":"deprecation.elasticsearch","data_stream.namespace":"default","data_stream.type":"logs","elasticsearch.event.category":"api","elasticsearch.http.request.x_opaque_id":"CG-BDC99B93A40177D1","event.code":"deprecated_field_from","message":"Deprecated field [from] used, this field is unused and will be removed entirely" , "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"deprecation.elasticsearch","process.thread.name":"elasticsearch[21bb4a83630c][transport_worker][T#7]","log.logger":"org.elasticsearch.deprecation.xcontent.ParseField","elasticsearch.cluster.uuid":"MPje9ZxbQT2epBJfuS6h4w","elasticsearch.node.id":"x9weErivTpSPD1apmUmf5Q","elasticsearch.node.name":"21bb4a83630c","elasticsearch.cluster.name":"mycluster"}
{"@timestamp":"2025-02-03T22:32:04.712Z", "log.level": "WARN",  "data_stream.dataset":"deprecation.elasticsearch","data_stream.namespace":"default","data_stream.type":"logs","elasticsearch.event.category":"api","elasticsearch.http.request.x_opaque_id":"CG-BDC99B93A40177D1","event.code":"deprecated_field_to","message":"Deprecated field [to] used, this field is unused and will be removed entirely" , "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"deprecation.elasticsearch","process.thread.name":"elasticsearch[21bb4a83630c][transport_worker][T#7]","log.logger":"org.elasticsearch.deprecation.xcontent.ParseField","elasticsearch.cluster.uuid":"MPje9ZxbQT2epBJfuS6h4w","elasticsearch.node.id":"x9weErivTpSPD1apmUmf5Q","elasticsearch.node.name":"21bb4a83630c","elasticsearch.cluster.name":"mycluster"}
{"@timestamp":"2025-02-03T22:32:04.712Z", "log.level": "WARN",  "data_stream.dataset":"deprecation.elasticsearch","data_stream.namespace":"default","data_stream.type":"logs","elasticsearch.event.category":"api","elasticsearch.http.request.x_opaque_id":"CG-BDC99B93A40177D1","event.code":"deprecated_field_include_lower","message":"Deprecated field [include_lower] used, this field is unused and will be removed entirely" , "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"deprecation.elasticsearch","process.thread.name":"elasticsearch[21bb4a83630c][transport_worker][T#7]","log.logger":"org.elasticsearch.deprecation.xcontent.ParseField","elasticsearch.cluster.uuid":"MPje9ZxbQT2epBJfuS6h4w","elasticsearch.node.id":"x9weErivTpSPD1apmUmf5Q","elasticsearch.node.name":"21bb4a83630c","elasticsearch.cluster.name":"mycluster"}
{"@timestamp":"2025-02-03T22:32:04.713Z", "log.level": "WARN",  "data_stream.dataset":"deprecation.elasticsearch","data_stream.namespace":"default","data_stream.type":"logs","elasticsearch.event.category":"api","elasticsearch.http.request.x_opaque_id":"CG-BDC99B93A40177D1","event.code":"deprecated_field_include_upper","message":"Deprecated field [include_upper] used, this field is unused and will be removed entirely" , "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"deprecation.elasticsearch","process.thread.name":"elasticsearch[21bb4a83630c][transport_worker][T#7]","log.logger":"org.elasticsearch.deprecation.xcontent.ParseField","elasticsearch.cluster.uuid":"MPje9ZxbQT2epBJfuS6h4w","elasticsearch.node.id":"x9weErivTpSPD1apmUmf5Q","elasticsearch.node.name":"21bb4a83630c","elasticsearch.cluster.name":"mycluster"}
```
