### ISSUE TITLE
version 1.0 for older version of R

### ISSUE THREAD

**Issue by csetzkorn** [elastic/elasticsearch#48621]
I tried to install version 1.0 on our sql server box like so:

install.packages('C:/DataScience/elastic_1.0.0.zip', repos = NULL, type = "win.binary")

but get:

Error in readRDS(pfile) :
  cannot read workspace version 3 written by R 3.6.1; need R 3.5.0 or newer

I think the reason is that v 1.0 is build for 3.6.1. Is there a chance to get v1.0 build for R 3.5.0? Thanks!

**Comment by danielmitterdorfer** [comment]
Thanks in your interest in Elasticsearch. You are probably referring to the Elasticsearch client for the R language. This client is not maintained by Elastic but rather at https://github.com/ropensci/elastic so I hope you don't mind that I close this issue here. I suggest you rather open an issue in https://github.com/ropensci/elastic.

**Comment by csetzkorn** [comment]
apologies - i sorted it in the end as well
