### ISSUE TITLE
Unified Highlighter ignores offsets when fuzziness is enabled

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#48660]
A user reported on our [discuss forum](https://discuss.elastic.co/t/unified-highlighting/205653/5) that turning on fuzziness in match queries prevents the unified highlighter from using postings. I was able to simplify the reproduction of the issue with the document provided by this user. 

In the following reproduction if I don't specify `index_options` both searches take about 6 seconds. With offsets, the first search takes 60ms and the second search still takes 6 seconds. To reproduce you need to have russian hunspell dictionary files in config directory and download [`voina-i-mir.json`](https://drive.google.com/drive/folders/1tLbnDPlTMRAvHj-izXPiKyyVJJ5NOIEB).

```
curl -XDELETE "http://localhost:9200/test?pretty"

curl -XPUT "http://localhost:9200/test?pretty" -H 'Content-Type: application/json' -d'
{
  "settings": {
    "index.highlight.max_analyzed_offset": 10000000,
    "analysis": {
      "analyzer": {
        "ru": {
          "tokenizer": "standard",
          "filter": [
            "lowercase",
            "ru_RU"
          ]
        }
      },
      "filter": {
        "ru_RU": {
          "type": "hunspell",
          "locale": "ru_RU",
          "dedup": true
        }
      }
    }
  },
  "mappings": {
    "properties": {
      "body3": {
        "type": "text",
        "analyzer": "ru",
        "index_options": "offsets"
      }
    }
  }
}'

curl -XPUT "http://localhost:9200/test/_doc/1?pretty&refresh=true" -H 'Content-Type: application/json' -d "@voina-i-mir.json"

curl -XPOST "http://localhost:9200/test/_search?pretty" -H 'Content-Type: application/json' -d'
{
  "_source": "",
  "query": {
    "match": {
      "body3": {
        "query": "корректор"
      }
    }
  },
  "highlight": {
    "fields": {
      "body3": {}
    }
  }
}'

curl -XPOST "http://localhost:9200/test/_search?pretty" -H 'Content-Type: application/json' -d'
{
  "_source": "",
  "query": {
    "match": {
      "body3": {
        "fuzziness": 1,
        "query": "корректор"
      }
    }
  },
  "highlight": {
    "fields": {
      "body3": {}
    }
  }
}'

```

**Comment by mkhludnev** [comment]
[Is it](https://github.com/apache/lucene-solr/blob/22b681755c00731bb30645c708d00555ac8f70e6/lucene/highlighter/src/java/org/apache/lucene/search/uhighlight/UnifiedHighlighter.java#L869) what happens there? 

``` 
   switch (offsetSource) {
      case POSTINGS:
        if (mtqOrRewrite) { // may need to see scan through all terms for the highlighted document efficiently
          return OffsetSource.ANALYSIS;
        }
```

**Comment by jimczi** [comment]
That's the current behavior yes, any multi-term query (fuzzy, prefix, wildcard) forces the unified highlighter to re-analyze the content. Note that this behavior is inherited from the removed `postings` highlighter so it should behave the same in previous versions. The reason is that we don't know how many terms the multi-term can match so if we use the entire dictionary of terms we might match thousands of terms while the document that we're highlighting contains none. Re-analyzing the text ensures that we can work on the dictionary of terms that belong to the document we're highlighting. The [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/7.4/search-request-body.html#offsets-strategy) is light on this matter but for optimal performance it is advised to index the field with `term_vector` instead of using the postings. This way the highlighter has access to all terms that appear in the document without re-analyzing the field.

**Comment by greenx** [comment]
@jimczi 
Trying to understand and don't understand.

> "The reason is that we don't know how many terms the multi-term can match so if we use the entire dictionary of terms we might match thousands of terms while the document that we're highlighting contains none. 
> 
> Re-analyzing the text ensures that we can work on the dictionary of terms that belong to the document we're highlighting."

Here it is written that the elastic [rewrites](https://www.elastic.co/guide/en/elasticsearch/reference/master/query-dsl-multi-term-rewrite.html) such requests.
So we know an extended list of terms.

**Comment by jimczi** [comment]
> Here it is written that the ElasticSearch rewrites such requests.
So we know an extended list of terms.

The highlighter works on the original query, not the rewritten one. Currently `multi_term` queries are handled in the `unified` highlighter without taking into account the `rewrite` option. So for instance a `fuzzy` query that uses a `top_terms_N` rewrite will be fully evaluated in the highlight so  terms that appear after the top N would still be highlighted. This is a choice and I agree that it is debatable but this also avoids a performance bug since we always compute the dictionary of terms (or retrieve it through `term_vector` if available) instead of trying to match in the main dictionary.
However I agree that queries using a `top_terms` rewrite could probably avoid the re-analysis and we could simply rewrite the query in the highlighter to retrieve these best terms. We cannot simply rewrite the entire query since some them use a private class that is not accessible for introspection so we'd need to add a special path for `fuzzy` queries for instance.

**Comment by jrodewig** [comment]
[docs issue triage]

**Comment by lockewritesdocs** [comment]
This issue hasn’t been updated in 3+ years so I’m closing it. We can revisit if needed.
