### ISSUE TITLE
[Rollup] cannot create Rollup job with fixed_interval=1s

### ISSUE THREAD

**Issue by njam** [elastic/elasticsearch#48680]
**Elasticsearch version**: v7.4.1

**Plugins installed**: [repository-s3]

**JVM version**: not sure, it's on Elastic Cloud

**OS version**: not sure, it's on Elastic Cloud

**Description of the problem including expected versus actual behavior**:
I'm unable to create a Rollup Job with `"fixed_interval": "1s"`.
When PUTting a Rollup Job with `"fixed_interval": "1s"`:
```
{
  "groups": {
    "date_histogram": {
      "field": "@timestamp",
      "fixed_interval": "1s",
      "delay": "60s"
    },
[...]
```
It will be created with `"calendar_interval": "1s"`:
```
[...]
    "groups": {
      "date_histogram": {
        "calendar_interval": "1s",
        "field": "@timestamp",
        "delay": "60s",
        "time_zone": "UTC"
      },
[...]
```

I _can_ create it with `"fixed_interval": "2s"` though.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Create a rollup job with `"fixed_interval": "1s"` (`PUT /_rollup/job/<ID>`)
 2. Check the created job (`GET /_rollup/job/<ID>`)
 3. The job has `"calendar_interval": "1s"`

**Comment by not-napoleon** [comment]
@csoulios @giladgal I don't think we should fix this for the experimental rollup branch, but for the GA version, we should decide on and document a minimum rollup interval.

**Comment by csoulios** [comment]
@not-napoleon I agree.  There is no reason we can't support this in the GA version, although I don't see real value from having 1 sec resolution in rollups. Perhaps in cases that a deployment has millions of event per second and the user wants to report with precision of 1 sec.

Howerver, I wonder if there is the same problem with setting `"fixed_interval": "1h"`. I will verify this at least works properly.

As a workaround, I guess instead of  setting`"fixed_interval": "1s"`, the user could use `"fixed_interval":"1000ms"`.

**Comment by wchaparro** [comment]
With the 8.7 release of Elasticsearch, we have made a [new downsampling capability](https://www.elastic.co/guide/en/elasticsearch/reference/current/downsampling.html) associated with the new [time series datastreams](https://www.elastic.co/guide/en/elasticsearch/reference/current/tsds.html) functionality generally available (GA). This capability was in tech preview in ILM since 8.5.  Downsampling provides a method to reduce the footprint of your time series data by storing it at reduced granularity. The downsampling process rolls up documents within a fixed time interval into a single summary document. Each summary document includes statistical representations of the original data: the min, max, sum, value_count, and average for each metric. Data stream time series dimensions are stored unchanged. 

Downsampling is superior to rollup because:

- Downsampled indices are searched through the _search API
- It is possible to query multiple downsampled indices together with raw data indices
- The pre-aggregation is based on the metrics and time series definitions in the index mapping so very little configuration is required (i.e. much easier to add new time serieses)
- Downsampling is managed as an action in ILM
- It is possible to downsample a downsampled index, and reduce granularity as the index ages
- The performance of the pre-aggregation process is superior in downsampling, as it builds on the time_series index mode infrastructure

Because of the introduction of this new capability, we are deprecating the rollups functionality, which never left the Tech Preview/Experimental status, in favor of downsampling and thus we are closing this issue. We encourage you to migrate your solution to downsampling and take advantage of the new TSDB functionality.
