### ISSUE TITLE
test {p0=mixed_cluster/70_ilm/Test Set Policy On Index}  test failure

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#48749]
It looks as if there is some issue with the timed creation of `my_mixed_index`.

Build URLs:

- https://gradle-enterprise.elastic.co/s/xagwbfkpecer4/tests/jhzkod6eb6kxo-dlyeczfvxzv2i
- https://gradle-enterprise.elastic.co/s/4trwqzgrvefvm/tests/jhzkod6eb6kxo-dlyeczfvxzv2i

**Comment by martijnvg** [comment]
Another instance: https://gradle-enterprise.elastic.co/s/zyckzijnlcpxs/tests/5y2avk3ewmmmq-dlyeczfvxzv2i

It looks to be failing frequently, all recent failures are caused by this test: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+fast+bwc/

I think we should mute this test?
