### ISSUE TITLE
Windows service uses incorrect value for `MaxDirectMemorySize`

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#48796]
A [user on the forums reported](https://discuss.elastic.co/t/node-shutdown-due-to-outofmemoryerror-direct-buffer-memory/205994/16?u=davidturner) an issue with their 7.3.0 nodes hitting `java.lang.OutOfMemoryError: Direct buffer memory` frequently. The nodes were being run with `-XX:MaxDirectMemorySize=536870912` despite a 6GB heap. It turned out the heap size was being set twice:

![](https://aws1.discourse-cdn.com/elastic/original/3X/e/9/e9b1506dd907e88ca36668f96ca6f0dfa6351f42.png)

`-XX:MaxDirectMemorySize=536870912` would be consistent with `JvmErgonomics` incorrectly picking up that the heap is `1GB` rather than `6GB`. I don't have a way to reproduce this to investigate further but this feels like a bug somewhere along the way.

**Comment by DaveCTurner** [comment]
Thanks @russcam, I've moved this to the main Elasticsearch repo.

**Comment by williamrandolph** [comment]
It looks like the setup here is controlled by an invocation in `bin\elasticsearch-service.bat`. We're parsing Xmx and Xms values out of the java options string and feeding them into the Commons Daemon service setup, but we're not then removing those values from the options string, leading to the redundancy and potential for drift we see above.

Conceptually, the fix is simple — remove the Xmx/Xms settings from the options string after parsing them — but the work will be figuring out how to make that happen in a Windows batch script.
