### ISSUE TITLE
Elasticsearch 7.4.2 unable to start with openjdk 13.0.1

### ISSUE THREAD

**Issue by rehannali** [elastic/elasticsearch#48859]
**Elasticsearch version** (`bin/elasticsearch --version`):

7.4.2 installed through homebrew tap elastic/tap

**Plugins installed**: []

**JVM version** (`java -version`):

> openjdk version "13.0.1" 2019-10-15 
> OpenJDK Runtime Environment (build 13.0.1+9)
> OpenJDK 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)

**OS version**

> Darwin 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behaviour**:

I install elastic search from homebrew using guide mentioned on the website. After installation I tried to run using `elasticsearch` and it crashes every time.

**Provide logs (if relevant)**:
<details>
<p>
Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
output:
[0.003s][error][logging] Error opening log file 'logs/gc.log': No such file or directory
[0.003s][error][logging] Initialization of output 'file=logs/gc.log' using options 'filecount=32,filesize=64m' failed.
error:
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Invalid -Xlog option - 'Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m', see error log for details.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
	at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:111)
	at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:79)
	at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:57)
	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:89)
</p>
</details>

**Comment by jasontedor** [comment]
@rehannali Sorry for the trouble. I think that the problem here is that you have a jvm.options file in `/usr/local/etc/elasticsearch` that isn't being updated when you install Elasticsearch via Homebrew, likely because you've made modifications to it from a previous installation.

I think that your `jvm.options` file currently has a line that reads like `9-:-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m`

but it should read:

`9-:-Xlog:gc*,gc+age=trace,safepoint:file=/usr/local/var/log/elasticsearch/gc.log:utctime,pid,tags:filecount=32,filesize=64m`

You could make this edit yourself manually, or we can re-install Elasticsearch to ensure that you pick up all of the latest modifications to jvm.options.

To address this, please follow these steps:
1. If you have modifications to `/usr/local/etc/elasticsearch/jvm.options`, make note of those somewhere.
2. `brew uninstall elasticsearch-full`
3. `rm /usr/local/etc/elasticsearch/jvm.options`
4. `brew install elasticsearch-full`
5. Re-apply your modifications to `/usr/local/etc/elasticsearch/jvm.options` 

I hope this helps.

**Comment by rehannali** [comment]
@jasontedor **Big Thanks**. Manually perform steps fixed my issue and now it is working.
