### ISSUE TITLE
How to delete custom analyzer in index settings?

### ISSUE THREAD

**Issue by freesinger** [elastic/elasticsearch#48877]
**Elasticsearch version** (`bin/elasticsearch --version`): v7.3.0

**Plugins installed**: [IK]

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system): Win 10

**Description of the problem including expected versus actual behavior**:

I've added my custom analyzer `ik_term` to my index `com_info`'s `settings`, but I found I had no idea how to delete `analysis` in `settings`. Documents have mentioned how to [reset](https://www.elastic.co/guide/en/elasticsearch/reference/7.3/indices-update-settings.html) index settings, but somehow it won't work in my case.
Though `analysis` in `settings` won't cause any trouble as long as I care nothing about it, I still want to know how to delete it or set index settings to default.
Any help will be appreciated.

**Provide logs (if relevant)**:
Add custom analyzer to settings **successfully**.
```JSON
PUT /com_info/_settings
{
  "analysis": {
    "analyzer": {
      "ik_term": {
        "type": "custom",
        "tokenizer": "ik_max_word",
        "char_filter": [
          "html_strip"
        ],
        "filter": [
          "asciifolding"
        ]
      }
    }
  }
}
```
Reset:
```JSON
PUT /com_info/_settings
{
  "index": null
}
```
Error log:
```JSON
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "unknown setting [index.index] did you mean [index.codec]?"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "unknown setting [index.index] did you mean [index.codec]?"
  },
  "status": 400
}
```

**Comment by cbuescher** [comment]
Hi @freesinger, the short answer is you cannot simply delete an existing index analyzer. Resetting index settings only works for settings that have a default, but the analyzer section in the settings is entirely user defined and therefore cannot be reset easily. You can add new analyzers to existing ones like [described in the settings update API](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-update-settings.html#update-settings-analysis) and you can even overwrite tokenizers and/or filters this way (this is dangerous though and should maybe considered a bug more than a feature, since it silently changes the way text fields are stored for an existing index). All these are merginge operations though, removing and entire analyzer isn't possible. 
I understand why this isn't ideal if you never used that analyzer on a field, but this should mostly happen in development situatiosn where re-creation of the entire index isn't a big problem. Just to confirm: is this mostly a cosmetic issue (cleaning up those erroneous old settings) or are you facing this problem in a real production situation where you really need this ability?

**Comment by freesinger** [comment]
Thanks a lot @cbuescher , I am setting ES in develpment situation, so whether I am capaple to delete my custom analyzer or not does not matter too much. I list some of my solutions to my issue below:
An index's analyzer [can't be changed(or set default)](https://discuss.elastic.co/t/change-analyzer-of-specific-property/99012), which can be solved by [reindex](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html). Some [mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html#change-existing-mapping-parms) settings are the same.
Thank you for your comment :)

**Comment by cbuescher** [comment]
Great to hear, also looks like you found the forum helpfull. We generally try to use Github issues only for bug reports and feature requests. I'm closing this as an issue here, but encourage you to ask further question in the forum.
