### ISSUE TITLE
Allow to pass system properties to testscluster

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#48998]
at the moment system properties passed with `tests.es.someproperty` are not being passed to testclusters when running integration tests (yaml, rest)
These are also not passed to a cluster runned with `./gradlew run`
it would make the testing/development easier if these was possible.

**Comment by atorok** [comment]
The way to pass system properties is `tests.jvm.argline` which gets added to the JVM running both the tests and testclusters. So one can add `-D` to pass system properties to the test cluster. 
`tests.es.*` is used to pass elasticsearch setting and only works with the `run` task and not any test cluster. This was done so that we don't rely on passing in these settings to change the behavior of tests. Ideally we wouldn't have the former either be we need it to test different GC algorithms. 

@pgomulka  is it ok with you to close this issue and open another one  focused on what you are trying to achieve ? I assume sending settings or system properties would be part of some development workflow, but there might be better ways to achieve that.

**Comment by pgomulka** [comment]
you are right, `tests.jvm.argline` is exactly what I meant by this issue. Thank you
Closing
