### ISSUE TITLE
Support auto_date_histogram in composite aggregation

### ISSUE THREAD

**Issue by wylieconlon** [elastic/elasticsearch#49005]
I can see why this aggregation might be more complex than the regular date histogram, but it's not clear why it isn't currently supported. When I try to use it, I get this error: `"reason": "invalid source type: auto_date_histogram",`

**Comment by imotov** [comment]
@wylieconlon I am trying to figure out how it would look like and how it will help. So, if we use the example below:

```
    "comp1": {
      "composite": {
        "sources": [
          {
            "hist1": {
              "auto_date_histogram": {
                "field": "date",
                "buckets": 100000
              }
            }
          }
        ],
        "size": 10000
      }
```

We will automatically split the date histogram into 100,000 buckets but return only first 10,000? If this is the case, I am not sure how having this in composite agg will help us since the way auto_date_histogram is working is it will have to keep these 100,000 bucket through the entire execution in case we will end up with an outlier that will cause us to shrink all these buckets into under 10,000. Since it doesn't look like we can save a memory footprint here. It doesn't seem to make much sense to implement it as a composite agg. Not sure if I missed something.

**Comment by imotov** [comment]
No feedback is provided. Closing.
