### ISSUE TITLE
Add details on snapshot deletions to snapshot status.

### ISSUE THREAD

**Issue by stejacks** [elastic/elasticsearch#49201]
**Describe the feature**:

A snapshot cannot run when a snapshot deletion is in progress.  There are details on snapshot deletions available in the cluster state through GET /_cluster/state?filter_path=snapshot_deletions.

It would be ideal if this also showed up in the _status endpoint for snapshots.

**Comment by original-brownbear** [comment]
@stejacks 

Is the only intended use-case for adding this information to the `_status` endpoint so that new snapshot creation can be orchestrated efficiently? 
We would still need to (or get anything out of doing so) adjust the `_status` endpoint if we allowed parallel snapshot deletion and creation?

**Comment by stejacks** [comment]
> Is the only intended use-case for adding this information to the _status endpoint so that new snapshot creation can be orchestrated efficiently?

Correct, specifically for ESS clusters.

> We would still need to (or get anything out of doing so) adjust the _status endpoint if we allowed parallel snapshot deletion and creation?

No, if we allowed parallel snapshot deletion and creation that would also solve this issue.

**Comment by original-brownbear** [comment]
> No, if we allowed parallel snapshot deletion and creation that would also solve this issue.

Perfect, thanks :) That's on the road-map for right after #49060 is merged -> closing here.
