### ISSUE TITLE
TDigestState serialisation might produce different histogram sketch for low compression values

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#49225]
The following test fails when precision of TDigestState is <= 1:

```
public void testTDigestStateSerialization() throws Exception {
        int compression = 1;
        int numDocs = 1000000;
        TDigestState histogram = new TDigestState(compression);
        for (int i =0; i < numDocs; i ++) {
            histogram.add(random().nextDouble() * 10);
        }
        BytesStreamOutput out = new BytesStreamOutput();
        TDigestState.write(histogram, out);
        TDigestState copy = TDigestState.read(out.bytes().streamInput());
        for (int i = 1; i <= 100; i++) {
            assertEquals(histogram.quantile(i / 100.), copy.quantile(i / 100.), 0.0);
        }
    }
``` 

The reason is that serialisation does not include the min/max values for the sketch. For low precision histograms (low compression value) the min/max values can be different to the min.max values of the centroids and therefore the sketch produces different values.

**Comment by jpountz** [comment]
I ran the test to see what happens: deserialization does not try to reconstruct the histogram as-is, but instead just adds the set of (centroid,count) pairs to a new instance. In some cases, the resulting instance will be different because some centroids will get merged during deserialization.

I don't think this is a problem we should care about: even though both histograms don't return the same quantiles, they are both "correct" in the sense that they both respect TDigest's invariants given the compression?

TDigest already makes significant efforts to retain better accuracy for extreme quantiles by enforcing that the count of a centroid can't be greater than `4 * value_count * q * (1-q) / compression` where `q` is the quantile of the current centroid. This weighing function returns much higher values for inner centroids than for extreme centroids.

Very low compression values like `1`, combined the high number of values that you add to the histogram forces TDigest to start having counts greater than 1 for extreme centroids, which is something that never happens with more common values of the `compression`. It feels expected to me that accuracy gets worse when the compression gets very low, I don't think we should try to work around it?

**Comment by iverase** [comment]
The problem I see is the following: If we print the percentiles of the original sketch and the deserialised sketch they look the same except that the second one get saturated at some point, so it is not accurate at high percentiles.

On the other hand this only happen for compressions <=1 so not sure if there is a need to work around it. For the histogram field introduced in #48580, if users provide very sparse histograms (e.g Prometheus), in order to be able to get meaningful values for the histogram, they might need to use this order of compression.
  

![image](https://user-images.githubusercontent.com/29038686/69072826-8ede6600-0a2c-11ea-881e-17f86da69ed8.png)

**Comment by iverase** [comment]
I had a look into the t-digest library and this behaviour does not appear in the master branch of the project. It seems this is changed in this [commit](https://github.com/tdunning/t-digest/commit/8f080168e78d1da722c44981fcdbced33050315). I wonder if this is an actual bug of the current t-digest version elasticsearch is using?

**Comment by talevy** [comment]
@iverase is there an option to use a different version of the library?

**Comment by iverase** [comment]
@talevy it seems the latest release version of t-digest is `t-digest-3.2` which is the one we are using.

**Comment by not-napoleon** [comment]
Closing in favor of #73928 - upgrading to t-digest 3.3 should fix this issue.
