### ISSUE TITLE
Update Netty in 6.8.x

### ISSUE THREAD

**Issue by joshbressers** [elastic/elasticsearch#49396]
As of 6.8.5 we are shipping Netty 4.1.32. The current version is 4.1.43.

Netty version 4.1.42 fixed a potential security issue around header parsing
https://nvd.nist.gov/vuln/detail/CVE-2019-16869
https://github.com/netty/netty/issues/9571

I do not believe this issue poses a substantial practical threat to Elasticsearch at this time. This CVE ID is being flag by security scanners, upgrading Netty would help avoid situations where customer deployments are delayed due to security scans.

cc/ @tbrooks8

**Comment by mightycoco** [comment]
7.x should then be updated, as well

**Comment by seang-es** [comment]
We're updating to 4.1.45 in our latest releases (https://github.com/elastic/elasticsearch/pull/51689).  We're seeing interest in a backport to the 6.8.x stream as well, as there are known vulnerabilities in earlier versions (including 4.1.43).  I don't think they're likely to actually affect Elasticsearch, but they do show up on security scans.

**Comment by tbrooks8** [comment]
We discussed this on the Elasticsearch team and decided to not move forward with the upgrade. Upgrading Elasticsearch from Netty 4.1.32 would involve non-trivial behavioral changes. We found it difficult to assess the risk that these changes would pose to 6.8 stability. However, we came to the conclusion that it was dangerous to make these larger changes. 

Additionally we evaluated the security risk posed by not upgrading Netty. Our understanding of this issue is that the security risk is low. The problem would arise when Elasticsearch is combined with a piece of middleware that sends different user requests over a persistent connection. This combination is difficult to exploit and can be mitigated when required on the middleware / proxy side.

@jasontedor @ywelsch @tomcallahan

**Comment by seang-es** [comment]
@tbrooks8 Thanks, does this apply to only the 6.8.x branch, with 7.x and 8.0 being updated to Netty 4.1.45?

**Comment by ywelsch** [comment]
yes, this upgrade limitation only applies to 6.8. Newer ES versions (7.x/8.0) are being updated to Netty 4.1.45 (see also #51689). The network implementation in 7.x is significantly different from 6.8, allowing us to safely proceed with the upgrade.
