### ISSUE TITLE
SQL: the result of ROUND of an INTEGER is a floating point number

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#49391]
`SELECT ROUND(salary,0) FROM test_emp` returns `.0` values even if `salary` is not a floating point field.

**Comment by costin** [comment]
Note this applies to aggregations as well, where integer types (like `SUM`) still return double due to the underlying infrastructure.
While in this case the function itself can be modified, it's worth pursuing this further and check whether we can do better preserve the type when returning the results.

**Comment by matriv** [comment]
@elastic/es-ql
