### ISSUE TITLE
[CI] DocsClientYamlTest regularly fails due to suite timeout

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#49579]
DocsClientYamlTest ran into the suite timeout: https://gradle-enterprise.elastic.co/s/zepwthumo2am2/

Further investigation shows that timeout happened 12 times in the last 7 days, while there is no offending test that took a very long time:

https://gradle-enterprise.elastic.co/s/zepwthumo2am2/tests?test=DocsClientYamlTest

Conclusion: The sum of executed tests got big over time. The timeout is already set to 30 minutes which is quite high, increasing the limit might be a simple fix but maybe it's time to consider other options like splitting the suite into smaller parts.

**Comment by droberts195** [comment]
Also worth noting that the docs suite was the one timing out in https://github.com/elastic/elasticsearch/issues/48148#issuecomment-552896746

That was found to be because the docs suite happened to run in parallel with the server suite on the Mac CI workers - see https://github.com/elastic/elasticsearch/issues/48148#issuecomment-553496064

So it may be that on some other combinations of hardware/OS, the scheduling works out that the docs suite runs at the same time as the server suite.

**Comment by hendrikmuhs** [comment]
Since 20/01/13 the number of failures increased:

![image](https://user-images.githubusercontent.com/7126422/72592985-27e20e00-3904-11ea-8add-d2cbbd3cc6e3.png)

**Comment by hendrikmuhs** [comment]
Closing this issue in favor of #49753, although its a younger duplicate but the more interesting investigations and discussions happen there.
