### ISSUE TITLE
enhancement: provide an API to manually rollover an index that currently has an ILM policy

### ISSUE THREAD

**Issue by tarp2699** [elastic/elasticsearch#49650]
Reason: Mappings or index settings are changed in templates and an index rollover is necessary to pick up the change. The change needs to be immediate and you can't wait for the index to roll normally. 
Process: 
Currently I do the following. 
1. Create a new index with an incremented number 
2. API call to _alias to set is_write_index to false on the current one and true on the new one. 
3. Update _settings on the original index to index.lifecycle.indexing_complete: true 
Those 3 steps are kind of pain to do by hand or lookup. I wrote a wrapper python script that does this, but it seems like it would be easy just to create a new API call to perform this.

**Comment by gwbrown** [comment]
I have good news: This is already implemented! See https://github.com/elastic/elasticsearch/pull/47324 - as of 7.5, you'll be able to just call the rollover API manually and ILM will figure it out and continue working as you would expect.

Because this has already been addressed, I'm going to close this issue.  Please comment further if the above feature does not address your needs and we can discuss further.
