### ISSUE TITLE
[RFE] extended_stats aggregation should allow for requesting a specific stat

### ISSUE THREAD

**Issue by aakarshg** [elastic/elasticsearch#49663]
**Describe the feature**:
Just like with percentiles we can do something like

```
GET latency/_search
{
    "size": 0,
    "aggs" : {
        "load_time_outlier" : {
            "percentiles" : {
                "field" : "load_time",
                "percents" : [95, 99, 99.9] 
            }
        }
    }
}
```

Where we can request for a specific percentile, same should apply for extended_stats:

```
GET /exams/_search
{
    "size": 0,
    "aggs" : {
        "grades_stats" : { 
            "extended_stats" : { 
                "field" : "grade",
                "stats": ["std_deviation","variance"]
            } 
        }
    }
}
```

This will allow users to just query what they'd like to see in this case std_deviation and variance

**Comment by polyfractal** [comment]
Hi @aakarshg, thanks for the ticket! We chatted about this today in our team meeting and decided not to implement this feature request.

Ultimately, we decided it is mostly a cosmetic improvement for the user, but would have an additional maintenance burden for us.  There wouldn't be any performance improvement because most values need to be computed anyway (e.g. sum of squares, variance, etc are used for other calculations).

As far as responses go, it isn't too large of JSON response to work with, and `filter_path` can be used to prune elements if you want, so we don't think the cosmetic improvement is worth the maintenance tradeoff in this case.

Thanks for the feature request though!

As an aside, the `percentiles` aggregation has that syntax because internally the percentiles are represented by an "opaque" data sketch.  If we could return the full cumulative probability chart to the user without any selection criteria, we would.  But the sketch works by asking for certain percentiles and it approximates those.  So we have to have the user provide which percentiles they are interested in so we can interrogate the sketch.
