### ISSUE TITLE
Proposal: change default time key from @timestamp to @ingestionTime

### ISSUE THREAD

**Issue by naseemkullah** [elastic/elasticsearch#49739]
To distinguish between [event time, processing time and ingestion time](https://ci.apache.org/projects/flink/flink-docs-release-1.2/dev/event_time.html#event-time--processing-time--ingestion-time), where the former two can be added by other parts of the logging pipeline (logger may add event time, log aggregator may add processing time).

**Comment by cbuescher** [comment]
@naseemkullah thanks for the suggestion. Are you thinking about a particular way of ingesting data into Elasticsearch? I'm asking this because Elasticsearch itself doesn't have any particular notion of what an "@timestamp" field should be. Its the ingestion processes like Beats or Kibana that add the field and visualizations in Kibana that presuppose its existence, so this issue might better suited for any of those repos.

**Comment by naseemkullah** [comment]
That is true! Thanks for pointing that out @cbuescher :)
