### ISSUE TITLE
TLS does not work on Elasticsearch 7.4.2 and Java 8

### ISSUE THREAD

**Issue by nathanrstacey** [elastic/elasticsearch#49780]
Java 8 under 7.4.2 does not work with client and server certificates in TLS. Upgrading to Java 11 with the same configuration resolves the issue
Request other Java versions to compatible with TLS

**Comment by danhermann** [comment]
@nathanrstacey, can you provide details on the TLS configuration you attempted that did not work with Java 8?

**Comment by tvernum** [comment]
@nathanrstacey Can you provide any further details?

We test Elasticsearch 7 with TLS on Java 8.
If there is a configuration that worked for you on Java 11 but not Java 8, then we'd like to know the details.

Note: Java 11 supports TLS1.3 but Java 8 does not, so it is possible to configure a node so that it will only work on Java 11 (e.g. by restricting it to TLS1.3 cipher suites) but you would have to go out of your way to make such a change.

**Comment by danhermann** [comment]
No further feedback received. @nathanrstacey, if you have the requested information please add it in a comment and we can look at re-opening this issue.
