### ISSUE TITLE
Document that SAML supports IdP & SP initiated login

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#49894]
Our [SAML IdP docs](https://www.elastic.co/guide/en/elasticsearch/reference/7.5/saml-guide-idp.html) don't explicitly mention that we support both SP & IdP initiated login (we do).

It would be good to include this.

**Comment by kunisen** [comment]
do we have update on this ticket?

**Comment by jkakavas** [comment]
@kunisen we were actually just discussing about this! In general, when we address issues we reference them in the PR and close them. 

Here, I just want to point out that the issue is _only_ about explicitly mentioning in our docs somewhere that IDP initiated single sign on is supported as well as SP initiated single sign on. Both the flows are already supported.

**Comment by kunisen** [comment]
thanks a lot for the super quick pointers!! @jkakavas ^ ^

**Comment by lockewritesdocs** [comment]
This issue hasn't been updated in 3+ years so I'm closing it. We can revisit if needed.
