### ISSUE TITLE
Elasticsearch cluster in swarm mode choose wrong network for discovery

### ISSUE THREAD

**Issue by eoli3n** [elastic/elasticsearch#49916]
**Elasticsearch version** :
docker image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1

**Configuration**
https://github.com/deviantony/docker-elk/compare/master...eoli3n:master

**Description of the problem including expected versus actual behavior**:
I'm trying to configure ELK in Swarm mode.
Since Docker 19.03.5, ingress overlay network changed from ``10.255.0.0/16`` to ``10.0.0.0/24``.
When i start the stack, i get ( [complete logs](http://ix.io/23E5) )
```
"elk_elasticsearch.1", "message": "master not discovered yet, this node has not previously joined a bootstrapped (v7+) cluster, and this node must discover master-eligible nodes [elk_elasticsearch.1, elk_elasticsearch.2, elk_elasticsearch.3] to bootstrap a cluster: have discovered [{elk_elasticsearch.1}{t9sUKAuxQcWo5ydcTyeC2Q}{qhiAgtpmS-miMmuMdwAOKA}{10.0.0.8}{10.0.0.8:9300}{dilm}{ml.machine_memory=4092379136, xpack.installed=true, ml.max_open_jobs=20}]; discovery will continue using [10.0.1.8:9300, 10.0.1.9:9300, 10.0.1.10:9300] from hosts providers and [{elk_elasticsearch.1}{t9sUKAuxQcWo5ydcTyeC2Q}{qhiAgtpmS-miMmuMdwAOKA}{10.0.0.8}{10.0.0.8:9300}{dilm}{ml.machine_memory=4092379136, xpack.installed=true, ml.max_open_jobs=20}] from last-known cluster state; node term 0, last-accepted version 0 in term 0" }
```
I can fix discovery by setting 

```
network.host: "_eth0_"
```
But then i can't reach es because it doesn't listen on ingress network (internal routing/load balancing network of swarm).

I was wondering if i could fix order by explicitly setting list of interfaces.
```
network.host: [ _eth0_ , _eth1_ , _lo_ ]
```
But i get the same problem...

**Steps to reproduce**:

Please take a look at this issue, everything is already clearly explained
[https://github.com/deviantony/docker-elk/issues/455](https://github.com/deviantony/docker-elk/issues/455)

**Fix**

It would be great to be able to set the discovering interface or network.

**Comment by eoli3n** [comment]
Here's the workaround
Just after initializing the swarm
```
docker network rm ingress
docker network create --driver overlay --ingress --subnet=10.255.0.0/16 ingress
```

**Comment by DaveCTurner** [comment]
Compatibility with Docker Swarm isn't something that we test or support, but it sounds like you want to configure Elasticsearch to listen for external HTTP traffic on a different interface from internal transport traffic. This is possible today using [the HTTP config settings, particularly `http.host`](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html#_settings). Alternatively you might be interested in [Elastic Cloud on Kubernetes](https://www.elastic.co/products/elastic-cloud-kubernetes).

I am closing this since I don't think there's any action to be taken here. If you need more help configuring Elasticsearch for your environment then the best place to ask is [the discussion forums](https://discuss.elastic.co/c/elasticsearch).

**Comment by mrajcok** [comment]
In case anyone else ends up here and doesn't examine the #455 issue link above, eoli3n later came up with a better fix: 
`network.publish_host: _eth0_ `
Reference: https://github.com/deviantony/docker-elk/issues/455#issuecomment-564927203
