### ISSUE TITLE
ConnectionOptions in Connection.d.ts is not exposed 

### ISSUE THREAD

**Issue by peter-borgstedt** [elastic/elasticsearch#50020]
A feature request for Typescript users:

**export the ConnectionOptions interface in Connection.d.ts**:

Extending the class Connection is kinda strange at the moment. Solution is either copy paste the interface or use any (or similar) as type for the opts in the extending class constructor.

`class MyConnection extends Connection {
  constructor(opts: any) {
    super(opts);
  }
}`

The ConnectionOptions should be exported.

**Comment by cbuescher** [comment]
Hi @peter-borgstedt, I'm not quite sure which project the class you are refering to lives in. It's most likely not the elasticsearch repo (couldn't find anything in the code with a quick search), but since you mention Typescript it might be either the Kibana repo or some other javascript client? I hope you don't mind me closing this, let me know if I missed something obvious.
