### ISSUE TITLE
[CI] 6.x periodic failing due to buildSrc

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#50075]
The build for 6.x fails due to elasticsearch gradle tools requiring Java 11 on Java 8 build:

```
11:23:35 * Where:
11:23:35 Build file '/var/lib/jenkins/workspace/elastic+elasticsearch+6.8+periodic-next/buildSrc/build.gradle' line: 71
11:23:35 
11:23:35 * What went wrong:
11:23:35 A problem occurred evaluating project ':buildSrc'.
11:23:35 > At least Java 11 is required to build elasticsearch gradle tools
```

Looks like a backport that did not pay attention to the JVM requirements.
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.8+periodic-next/26/console

**Comment by mark-vieira** [comment]
This is an experimental build and is actually broken in _all_ branches. We need not triage experimental build failures so we can safely ignore this.

**Comment by davidkyle** [comment]
I came across the same errors on test triage duty today and it took me a little while to find this issue. I'm sure Costin and I will not be the last people to end up here after spending some time investigating the failures. Test triage is time consuming and these failures add noise, is there any chance these experimental builds you expect to fail could be sent to a different distribution list e.g. experimental-build-elasticsearch@elastic.co instead of build-elasticsearch@elastic.co. @mark-vieira

**Comment by mark-vieira** [comment]
Apologies for the noise. I've disabled the trigger on this build so we shouldn't be running it anymore unless we manually trigger it.
