### ISSUE TITLE
[Rollup] Rollup search ignores rolledup data in weird case

### ISSUE THREAD

**Issue by kandelon** [elastic/elasticsearch#50155]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.3.0

**Plugins installed**: []

**JVM version** (`java -version`): cloud

**OS version** (`uname -a` if on a Unix-like system): cloud

**Description of the problem including expected versus actual behavior**:
When running a rollup search query against a rollup index and a non-rollup index the resulting aggregation may only included data from the non-rollup index, giving a very inaccurate number. Experimentation has revealed that the issue only happens in very specific conditions.

1) The non-rollup index must return a result on its own (testing with a random unrelated index did not reproduce the error)
2) The query must include a "term" on one of the fields configured in the rollup to filter the results.
3) The aggregations must include a "terms" aggregation on the same field, or a field that lines up (such as a hierarchy where for a given value in one of the terms, all of the values in the other are the same. Can go either way with the aggregation being a "parent" or a "child". It seems like entirely unrelated fields don't hit the issue though?)

**Steps to reproduce**:

 1. Create an index with a timestamp and at least one term and one metric
 2. Create a rollup that groups on the term and rolls up the metric
 3. Start the rollup and wait for completion
 4. Remove the old data from the original index or create a new one
 5. Add new different records to the new or cleared index
 6. Run a rollup search on the rollup and newer index together that has a term query and an aggregation that sums the numeric field, then a second aggregation that does a "terms" aggregation on the same term field from the query and put a copy of the same sum aggregation under it
 7. Notice how the value under the term aggregation is smaller than the top level sum, even though with only the one bucket all records should have been included
 8. You can also remove the non-rollup index from the query or drop the term query and see the aggregation under the term jump up to match the top level one, even if all of the new records have been rolled up and they all matched the term anyways.

**Provide logs (if relevant)**:

**Comment by polyfractal** [comment]
Hi @kandelon, thanks for the detailed report! I suspect I know what's happening here.

> - Remove the old data from the original index or create a new one
> - Add new different records to the new or cleared index

When you add the new data, how are the timestamps configured?  Does the new data exclusively have timestamps after the old data that was cleared, or do the timestamps overlap with the old, cleared data?

Rollup assumes that data is always moving "forward" in time.  E.g. rolled-up indices are either mirroring the data in a "live" index, or strictly older than the live index.  This follow the workflow of append-only style logs/metrics which periodically are rolled up and the raw data is deleted.

Because of this workflow assumption, when RollupSearch encounters shard responses from both a rollup and a live index which share the same key, Rollup [uses the values from the live index](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/RollupResponseTranslator.java#L469) (because it is presumed to be the same data and at a higher granularity, being the original data).

This behavior only happens when multi-bucket aggregations (terms, histogram, etc) encounter the same key from rollup and non-rollup shard responses, which is why you don't see it with a simple sum metric.

This works well for time-based aggregations, but I can see a simple top-level terms agg might get confused... especially if the timestamps being added back into the index overlap with the rolled time period.

**Comment by kandelon** [comment]
Hey @polyfractal ,
I'm pretty sure the new data has more recent timestamps. The live situation I ran into is being fed by logstash. I've got daily indexes that are deleted over time and an hourly rollup that keeps the summary forever. There would be overlap between the rollup and the raw index from the last time the rollup triggered, but the newer records would have newer dates on them.
Since the query being run is not a date aggregation (I have tried both with and without specifying a date range in the query), it sounds like I'll only get the live data because the keys are flat across the time range? Does this also happen with date aggregation if the interval spans rolled up and live data? I think I can work around this for now by drawing a line between the analytics queries that are looking for the most recent data, and those that are looking further in the past, but It would be nice to be able to just throw queries at the rollup and live indexes without worrying about this behavior. It also means there's no real way to get a current live grand total since the rollup is missing the most recent, and the live index only has a fraction of the timerange.

**Comment by rtyley** [comment]
We at the Guardian are also running into this issue -specifically, the issue that when we execute a rollup search query against rollup & non-rollup indicies with an overlap in time-based data, only the data from the non-rollup index is used. This is problematic for us because we always have a small amount of late-arriving data (data that is uploaded to us _days_ after the event occurred) - this late-arriving data, still held in our non-rollup index, clobbers the rollup data we would _want_ to be seeing for the same time period.

You can see this in the graphs below:

### Querying across both rollup & non-rollup indicies

Here, the Thursday-Saturday period on the left should be populated with lots of rolled-up data - but all that's there is the small amount of late-arriving data - from Monday onwards, you can see the data that's still in our non-rollup indicies that haven't been deleted yet:

![image](https://user-images.githubusercontent.com/52038/74834121-b5a18680-5312-11ea-9381-85886422a028.png)

### Querying on just the rollup index (note different y-scale)

By not querying on the non-rollup indicies, we can finally retrieve our rolled-up data (rollups have only been generated up to Wednesday)
![image](https://user-images.githubusercontent.com/52038/74834177-d36eeb80-5312-11ea-9026-de22d2c4e537.png)

## How to fix this?

Could a rollup-threshold field be added to the _rollup_search API? When we make the search query, we'd like to specify that raw non-rollup data should only be used up to a specified point in time - before that, only rollup-data should be used, even if there's non-rollup data available.

**Comment by polyfractal** [comment]
> Could a rollup-threshold field be added to the _rollup_search API? When we make the search query, we'd like to specify that raw non-rollup data should only be used up to a specified point in time - before that, only rollup-data should be used, even if there's non-rollup data available.

Hmm... I haven't looked too closely, but I suspect this would be doable.  The boundary would have to "snap" to the bucket nearest the threshold to keep code complexity down... but I think it should be possible.  

Will need to dig a bit more to say for sure.  I'll try to take a closer look next week!

**Comment by wchaparro** [comment]
With the 8.7 release of Elasticsearch, we have made a [new downsampling capability](https://www.elastic.co/guide/en/elasticsearch/reference/current/downsampling.html) associated with the new [time series datastreams](https://www.elastic.co/guide/en/elasticsearch/reference/current/tsds.html) functionality generally available (GA). This capability was in tech preview in ILM since 8.5.  Downsampling provides a method to reduce the footprint of your time series data by storing it at reduced granularity. The downsampling process rolls up documents within a fixed time interval into a single summary document. Each summary document includes statistical representations of the original data: the min, max, sum, value_count, and average for each metric. Data stream time series dimensions are stored unchanged. 

Downsampling is superior to rollup because:

- Downsampled indices are searched through the _search API
- It is possible to query multiple downsampled indices together with raw data indices
- The pre-aggregation is based on the metrics and time series definitions in the index mapping so very little configuration is required (i.e. much easier to add new time serieses)
- Downsampling is managed as an action in ILM
- It is possible to downsample a downsampled index, and reduce granularity as the index ages
- The performance of the pre-aggregation process is superior in downsampling, as it builds on the time_series index mode infrastructure

Because of the introduction of this new capability, we are deprecating the rollups functionality, which never left the Tech Preview/Experimental status, in favor of downsampling and thus we are closing this issue. We encourage you to migrate your solution to downsampling and take advantage of the new TSDB functionality.
