### ISSUE TITLE
[API Key] Return base64 encoded API key when creating API key

### ISSUE THREAD

**Issue by fkelbert** [elastic/elasticsearch#50235]
**Describe the feature**: `_security/api_key` API should return the ready-to-use base64 encoded API key. This would many significantly more user-friendly. Currently, users need to manually create the base64 encoded API key from the `id` and and the `api_key` field.

**Elasticsearch version** (`bin/elasticsearch --version`): 7.5

**Comment by albertzaharovits** [comment]
Thanks for bringing this to our attention @fkelbert !
We've discussed this before, and agreed this is desirable, but we didn't follow-up: https://github.com/elastic/elasticsearch/pull/38291#issuecomment-511711079

**Comment by aterreno** [comment]
That's a nice change, if anyone else was confused and came here googling from the documentation, you need to base64 the id and the api key appending the two separated by a ':'

like base64(id + ":" + apiKey)

**Comment by albertzaharovits** [comment]
Given our bwc goals, we have to maintain the existing fields in the response body. My proposal is to extend the response to add another field, named `authorization`, that contains the `ApiKey` authn scheme concatenated with the value of `base64(id + ":" + api_key)`.
As an example, the current response for `_security/api_key` is :
```
{
  "id" : "Yw6PvXIBDLw0heIvcMR4",
  "name" : "my-api-key-3",
  "api_key" : "dvcZAa3LQe2RmyVcjLEpDw"
}
```
and I would propose we extend it to:
```
{
  "id" : "Yw6PvXIBDLw0heIvcMR4",
  "name" : "my-api-key-3",
  "api_key" : "dvcZAa3LQe2RmyVcjLEpDw",
  "authorization": "ApiKey WXc2UHZYSUJETHcwaGVJdmNNUjQ6ZHZjWkFhM0xRZTJSbXlWY2pMRXBEdw=="
}
```
The "authorization" field name is a bit funky. It is inspired on the HTTP request header name, which is how you'd utilize the API Key, eg `curl -H "Authorization: ApiKey WXc2UHZYSUJETHcwaGVJdmNNUjQ6ZHZjWkFhM0xRZTJSbXlWY2pMRXBEdw=="`.

I would also say we remove the `api_key` field in the next major version (8).

@elastic/es-security what do you think about this proposal?

**Comment by ywangd** [comment]
I'd suggest something like: 
```
{
  ...
  "credentials": "WXc2UHZYSUJETHcwaGVJdmNNUjQ6ZHZjWkFhM0xRZTJSbXlWY2pMRXBEdw=="
}
```

A few reasons:
* It's easy for user to add the `ApiKey` part. If user is parsing for this specific field, s/he is already aware this is for API keys.
* It is simpler to document this new field without the extra `ApiKey` prefix, which is already documented in the current documentation when explaining how to use the credentials into a curl call.
* The field name `credentials` is consistent with [current documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-create-api-key.html#security-api-create-api-key-example), specifically:
> The API key returned by this API can then be used by sending a request with a Authorization header with a value having the prefix ApiKey followed by the credentials, where credentials is the base64 encoding of id and api_key joined by a colon.

I am more inclined to keep the `api_key` field: 
* It seems to add unnecessary bwc burnden for users. It is like: we will add a new "convenient" field at the cost that your "inconvenient" way of working will break one day and have to update.
* The opposite of the current issue could happen, i.e. it is not friendly to have to decode the `api_key` from the base64 encoded value.

**Comment by jkakavas** [comment]
I only have a weak preference over this but I can't think of a valid use for the api key id or the api key value/secret on its own. I know that the `get api key` info or `invalidate api key` expects the id part but I don't remember why we did this and it doesn't make much sense now that I think about this. I expect callers of the get api key API to store either the base64 encoded concatenation string that they can then use, or store both the id and the secret in the same place eithe rway. What's more, it feels like the fact that we have an id and a value part is an implementation detail that we force to the users. 

- It's trivial for us to parse the base64 encoded string and get the id part when api keys are used api key related APIs so we can handle the change easily
- Should we keep the `api_key` value and return the base64 encoded value there ? And deprecate and remove the `id` field , adjusting the other api key related APIs for 8 ?

**Comment by bytebilly** [comment]
I agree we should avoid the `ApiKey` prefix, since it makes it very related to the raw HTTP header value.
There are use cases (e.g. adding credentials to config files) that don't require the prefix, and users may be confused and copy&paste the entire string.

I also think that we should keep the `api_key` field. Users may use it in some scenarios (e.g. Elasticsearch language clients allow to specify separate values for `id` and `api_key`, and we may create an unnecessary change here. Also, users may think that we just renamed `api_key`, doing an incorrect double-encoding of `base64(id:credentials)`.

We should find a good name for the new value, and even if being consistent with the docs makes some sense, I'd prefer to not consider it a requirement since we can change docs accordingly to the new name. The current mention in docs is not a JSON name, just a verbal term.

Said that, I'm not against using `credentials`. Other possible candidates may be `token` or `auth`, with the advantage of being shorter.

**Comment by jkakavas** [comment]
The more I think about this the stronger my preference gets I think.. 

> I also think that we should keep the api_key field. Users may use it in some scenarios (e.g. Elasticsearch language clients allow to specify separate values for id and api_key, and we may create an unnecessary change here

My point is that these clients only do this because we forced them to do this by returning an id and a value in our API (and they opted in making it easier for the users as opposed to mandating that the users do the `base64(id:key)` ). I see this as a simplification that makes sense for 8 and not as an unnecessary change. 

> Other possible candidates may be token or auth, with the advantage of being shorter.

I would steer away from `token` as it can cause additional confusion ( relevant to our Token service and the tokens we create there ). Also, while I don't dislike the `credentials` or `auth` , the base64 encoded representation _is_ the api key for all intents and purposes and I think we're trying to find ways around a decision we made in 6.x. Does anyone remember if there was a use case or a requirement that dictated the use/knowledge of 2 values on the client side ( apart from the implementation details on the server side ) ? Is the only argument in favor of maintaining and id and a value, to not make a breaking change in 8 ?  ( Not saying this is not a valid argument on its own, I'm just not persuaded it is sufficient )

**Comment by bytebilly** [comment]
> I see this as a simplification that makes sense for 8 and not as an unnecessary change.

I understand your point, but since we forced developers to deal with the initial choice, forcing them to change their code in 8.x is something that could create development effort (on their side).

I'm not sure the benefit (simplify the API) is higher than the cost (force users to change their code), even if I agree it would have been probably my first choice. I'm curious to get more context on the initial decision 🙂 

If we'll go with removing the `api_key` field, I'd see just `key` as the right name for the new value. However in 7.x we would have `api_key` and `key` that is not that easy to decrypt from a user perspective.

**Comment by tvernum** [comment]
>  Does anyone remember if there was a use case or a requirement that dictated the use/knowledge of 2 values on the client side

Our APIs, by design, don't require that you know the credential in order to reference an API key. 

We use Key Ids in:
1. The GET (list) api keys endpoint - we need something to return that uniquely identifies a key for which the secret is no longer retrievable
2. The DELETE api key endpoint - we need to be able to delete keys even if the owner does not  has access to the secret
3. The SetSecurityUserProcessor - like (1), we need a unique id here
4. (Not yet) In [audit logs](https://github.com/elastic/elasticsearch/issues/52551#issuecomment-642942995), similarly to (3).

I feel strongly that we should not remove the identifier from create API Key response. It is the id that we will (& need to) use elsewhere and it should be explicit from the start.

**Comment by jkakavas** [comment]
> Our APIs, by design, don't require that you know the credential in order to reference an API key.

Sure, but this is explaining our decision, by referring the decision itself. I don't remember the discussions around this and the reasons why we elected to do so. 

> The SetSecurityUserProcessor - like (1), we need a unique id here
> (Not yet) In audit logs, similarly to (3).

I understand why we need a unique ID to identify a key, and (maybe) why we need to return it as one of the values of the call to create one, but not why we need to mandate that people deal with this implementation decision and need to think/use API keys similar to username/password credentials.  

What I'm trying to say is, rethinking this now, I'm arguing against the usability of splitting the api key in two things and having to "worry" about what happens when a user doesn't have access to one of these two. I'm not arguing that we should re-implement any of this, but we could make the connection between the id and the api key value that the users need to handle use more opaque.  
Instead of an api key id and an api key secret that you need to concatenate with a `:` and then base64 encode in order to use, we could give an api key that is a base64 string that folks can use as-is and an api key id that uniquely identifies that api key. (id is still the first half of the base64 string value but users need not know or care about this )

**Comment by tvernum** [comment]
Your earlier comment was
> I can't think of a valid use for the api key id

Which is what I was pointing out. We definitely have valid uses for a public id for API Keys. It is intentional and by design that the key-id is an explicit part of the API.  
REST API design would strongly encourage (dictate?) that if an API creates a new object that has a unique, public id on which other API endpoints rely, then that id should be returned in the response to the create API.

By necessity, _that dictated the use/knowledge of 2 values on the client side_ one for the public part and one for the secret part.
I am not particularly fussed by whether the secret part is just the "key" as currently returned, or the proposed "credential" field, but the need for 2 values is real.

My personal complaint about the response is that the current field is named `api_key`. It is most definitely a weakness of the response that you ask to create an API key, and you get back a response with a field named `api_key` _that is entirely useless on its own_.

**Comment by albertzaharovits** [comment]
We held an extensive team meeting on this topic, but we couldn't reach a consensus on the solution, yet. I'll try to briefly summarise the discussion, but expect more debates on the topic.

The `api_key` response field is appropriately named, but its value (the API Key secret) is incorrect. We cannot change the field name in a minor release, and even in a major it would be a bit of a stretch because we should be mindful of the amount of breaking changes imposed on users. Adding a new field, to avoid introducing a breaking change, is also contentious, because again the existing `api_key` name is a very good name and anything along side it is bound to create confusion.

We floated some ideas for changing the value of the `api_key` response field, in a minor release. The new value can sit behind a request flag, or could simply replace the existing value. If we automatically replace the existing value we must be able to determine which value (new vs. old) is being used when authenticating with the key.

In addition, we might rely on API versioning or even possible changes to API Key APIs in general (to accommodate other requirements such as API Key templates).

I glanced over a lot of details, but I hope this is still useful.

**Comment by tvernum** [comment]
@elastic/es-security I'd like to open this topic back up for discussion.

I've come around to the idea that it's worth adding the encoded key somewhere in the response even if we can't make the API perfect.

While there are still issues, I think a response of:
```
{
  "id": "vdpCUnsByErwCzEOw2uZ",
  "name": "my-api-key",
  "api_key": "fzfxIjyxQc2cXkKcc3K11A",
  "encoded": "dmRwQ1Vuc0J5RXJ3Q3pFT3cydVo6ZnpmeElqeXhRYzJjWGtLY2MzSzExQQ"
}

``` 
is progress, and I'm not sure we're going to find anything significantly better.

**Comment by albertzaharovits** [comment]
@tvernum Sounds great to me!!!

**Comment by bytebilly** [comment]
I agree it's useful to add.

The `encoded` field name is actually the value to use in requests, so would `value` be a better name? If not, I'm fine with `encoded`. It may sound strange if we'll ever remove `api_key`, but I'm wondering if it will ever happen.

**Comment by ywangd** [comment]
I am fine with a new field. I am also wondering whether we should re-consider Albert's previous proposal about changing the existing `api_key` field to be the encoded value and in runtime we have a small leniency to accept either `$id:$api_key` or just `$api_key`. My original concerns for this approach were:
* It's an implicit leniency (unlike rest compat which is explicit)
* Minor overhead on processing the header
* Not entirely clear about the security implication of two different headers ending up to be the same authentication

Now I don't think any of the concerns is major (or even valid?). What does the team think?

**Comment by tvernum** [comment]
I'm not opposed to doing something more complex than adding a new field.

However, we've been stuck without a decision for more than 18 months, and it hurts users. I really just want to do something that makes it easier for our users, and if we have to go through another round of ideas and (non)decision making, then there's a good chance we'll miss the opportunity to deliver something in 7.x

**Comment by ywangd** [comment]
> I'm not opposed to doing something more complex than adding a new field.
> 
> However, we've been stuck without a decision for more than 18 months, and it hurts users. I really just want to do something that makes it easier for our users, and if we have to go through another round of ideas and (non)decision making, then there's a good chance we'll miss the opportunity to deliver something in 7.x

FWIW, I did a [prototype](https://github.com/ywangd/elasticsearch/commit/70f36f438b219f0dc8c59865cb09d4c50668eadc#diff-b2fee23c35e84dd344aab373c0fd03e9c0ab086126332cbf015470cbd222d491) on it. I thougt though having a redundant `id` is more complex in server code logic but may be justified by less work on client code (e.g. HLRC) and documentation. It is true to a certain degree. But there is no easy way to avoid based64 decoding twice on the Authorization header when extracting the credentials because it has the format of `base64($id,base64($id,$secret))`. An extra base64 decoding has overhead on both runtime and code. Though it works, it's a bit too much for my liking. So I'd go with the extra field approach. The name `encoded` is fine with me (naming is hard). I'll get it done for 7.16 if everyone is happy with Tim's proposal.
