### ISSUE TITLE
[Docs] Provide best practices for upgrading large clusters

### ISSUE THREAD

**Issue by rwaight** [elastic/elasticsearch#50242]
**Describe the feature**:  
In addition to the best practices provided in [elastic/elasticsearch#47028](https://github.com/elastic/elasticsearch/issues/47028), the upgrade documentation should be improved to include guidance around performing "batch" restarts when upgrading a large cluster.

We should provide guidance to only upgrade nodes in small batches at a time (maybe a percentage of the node count? 5% or 10%?). For a 100 node cluster, our recommendation would be to bring up 10 nodes, wait for the upgraded nodes to join the cluster (or a minimum time of 3-5 minutes) then bring up 10 more nodes; this process would be repeated until all nodes were upgraded.

The reason for this request is due flooding master nodes when upgrading large clusters. At a high level, this can occur if a batch restart is performed when upgrading a cluster with 100-150 nodes. When all of the nodes are brought back online at the same time, they end up DDOSing the master nodes. This can cause the master nodes to become unresponsive, which can cause any nodes that have already joined the cluster to be kicked from the cluster due to communication timeouts.

**Comment by DaveCTurner** [comment]
@rwaight are you talking about in a rolling upgrade or in a full-cluster restart?

If the master can be overloaded by too many nodes all joining simultaneously then I think we should consider that a bug that we should try and fix rather than working around it as you describe. Please would you give more details (pointers to logs etc) for further investigation?

In the case of a rolling upgrade I think it's pretty tricky to describe the batches of nodes you can safely restart concurrently without some kind of unavailability. Instead I think I would prefer to run the process one-node-at-a-time as documented. This might not have been possible in older versions due to the speed of shard recoveries, but there have been improvements in this area in recent versions that should make it much more reasonable.

**Comment by DaveCTurner** [comment]
We discussed this in a separate channel. The specific cluster in question was running 7.1 and had ≥5000 initialising shards but only 10 pending tasks and the CPU on the master was ≤30%, which doesn't sound like "DDOSing the master". It's fixed now and we don't seem to have diagnostics from when it was broken. This might have been a case of setting `cluster.routing.allocation.node_concurrent_recoveries` too high, perhaps hitting https://github.com/elastic/elasticsearch/issues/36195. We're waiting on more detail.

**Comment by nik9000** [comment]
Its been a few months and we haven't heard back so I'm going to close this issue and hope that @DaveCTurner is right. @rwaight if you'd like to leave more feedback please reply and reopen the issue.
