### ISSUE TITLE
Disk usage doubled when upgrading from 5.4 to 5.6

### ISSUE THREAD

**Issue by jmwilkinson** [elastic/elasticsearch#50323]
**Elasticsearch version** (`bin/elasticsearch --version`): 5.6.16

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_201

**OS version** (`uname -a` if on a Unix-like system): Centos 7.4 (Docker)

**Description of the problem including expected versus actual behavior**:

*Expected behavior*: After full cluster upgrade & green status, all old data would be removed, releasing disk space. Even better, after a single successful node upgrade, old disk usage would be released.

*Actual behavior*: After a full cluster upgrade from 5.4 -> 5.6, every node's disk usage doubled and was not released.

**Steps to reproduce**: Upgrade a cluster from 5.4 -> 5.6

**Comment by jtibshirani** [comment]
Hello @jmwilkinson, this seems like a troubleshooting question related to your stack upgrade. We usually try to direct those questions to our [discussion forums](https://discuss.elastic.co/), as we reserve GitHub issues for bug reports and development discussions. Would you be able to post the question in the forums instead? We can loop back to file an issue if we find that the problem is due to a bug in Elasticsearch.

**Comment by jmwilkinson** [comment]
@jtibshirani Sure, done.

Discussion topic here: https://discuss.elastic.co/t/cluster-upgrade-from-5-4-5-6-doubled-disk-usage/212539
