### ISSUE TITLE
Specifying the standard analyzer silently ignores filters

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#50356]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.5.0

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

I just tried to configure a mapping and accidentally did not specify the analyzer type as `standard`. This led to filters being ignored without any error message. This feels to me like a bug, but I'm not a hundred percent sure.

```
PUT test
{
  "settings": {
    "analysis": {
      "filter": {
        "min-length-token": {
          "type": "length",
          "min": 2
        }
      },
      "analyzer": {
        "my_analyzer": {
          "filter": [
            "min-length-token"
          ],
          "tokenizer" : "standard"
        }
      }
    }
  }
}

# works as expected, no terms returned
GET test/_analyze
{
  "analyzer": "my_analyzer",
  "text": "A"
}
```

This however returns terms

```
PUT test
{
  "settings": {
    "analysis": {
      "filter": {
        "min-length-token": {
          "type": "length",
          "min": 2
        }
      },
      "analyzer": {
        "my_analyzer": {
          "filter": [
            "min-length-token"
          ],
          "type" : "standard"
        }
      }
    }
  }
}

# a is returned despite being shorter than length of two
GET test/_analyze
{
  "analyzer": "my_analyzer",
  "text": "A"
}
```

no errors though. To add some more confusion. When you do not use a custom token filter, but a standard one like trim, it seems as if that one is applied despite using `type` standard. See this example

```
PUT test
{
  "settings": {
    "analysis": {
      "analyzer": {
        "my_analyzer": {
          "filter": [
            "trim"
          ],
          "type" : "standard"
        }
      }
    }
  }
}

# term is trimmed and lowercase from the standard analyzer
GET test/_analyze
{
  "analyzer": "my_analyzer",
  "text": "  A  "
}
```

**Comment by gaobinlong** [comment]
@spinscale, the filter is really ignored when the `type` parameter is specified in analyzer. The `tokenizer` parameter must be specified when we define a custom analyzer, if the `type` parameter is set to `standard`, the result is a standard analyzer. In the last example, `my_analyzer` is still be a standard analyzer, term will also be trimmed by standard tokenizer.

**Comment by cbuescher** [comment]
I dug into this issue for a bit and think it would make to close it and fold it under the general issue for analysis validation that has been open for a while at https://github.com/elastic/elasticsearch/issues/41299.

The problem described here is similar to https://github.com/elastic/elasticsearch/issues/16451 which describes how when using e.g. the "standard" analyzer we ignore all other unknown parameters on that analyzer definition level. In terms of internal code execution this is due to the fact that as soon as we have an AnalysisProvider when building the mapping in the registry, we push all the IndexSettings for that analyzer down to the constructor (in this case the StandardAnalyzer one) which usually doesn't complain about any settings it doesn't need. 

Just some forther remarks:

> To add some more confusion. When you do not use a custom token filter, but a standard one like trim, it seems as if that one is applied despite using `type` standard. See this example

This happens only because "standard" analyzer already does whitespace filtering in its tokenizer. Were you to user some other filter like "uppercase" here, you would also see that the filter section gets ignored.

I'm closing this as a duplicate of #41299 where I will add a short example of this case for consideration when we work on it.
