### ISSUE TITLE
ILM: shrink action silently skipped

### ISSUE THREAD

**Issue by fpompermaier** [elastic/elasticsearch#50434]
**Elasticsearch version**: 7.5.0

**Bug report**
When you provide a **shrink** step in the warm phase but the target number of shards has the same cardinality of the index shards, the shrink phase is silently skipped and the index is not renamed as shrink-XXX. To me this is a bug because I want to be able to mark an index as "deletable" when its name starts with shrink-XXX, and I don't want to configure a number of shards > 1 only because this limitation of the shrink action. Moreover, this behaviour is not documented anywhere and it's not logged at all in the elasticsearch logs.

**Comment by dakrone** [comment]
I can see how someone would want to filter out indices starting with `shrink-`, however, by skipping the shrink it does mean that we sidestep any potential search exceptions that arise with creating a new index and deleting the old one while a search is in progress.

Additionally, as it stands right now, we have no way to rename an index outside of creating a new one (the actual shrink/split process), so we would have to change the shrink process to use the [clone](https://www.elastic.co/guide/en/elasticsearch/reference/7.5/indices-clone-index.html) API under the hood instead of shrinking.

I've marked this as something we can discuss.

**Comment by fpompermaier** [comment]
A rename API would be REALLY awesome for Elasticsearch indices

**Comment by dakrone** [comment]
There is more discussion about renaming in #37880

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
