### ISSUE TITLE
Reload search analyzers does not work correctly with multiplexer filter (showstopper)

### ISSUE THREAD

**Issue by zdeseb** [elastic/elasticsearch#50554]
**Elasticsearch version**: Version: 7.5.1

**Plugins installed**: []

**JVM version**: 13.0.1

**OS version**: Windows 10 Pro

**Description of the problem including expected versus actual behavior**: When the synonym_graph filter is not used directly in an analyzer but is included in multiplexer filter (for example to allow combination with word_delimiter_graph), _reload_search_analyzers does not correctly find and reload appropriate analyzer.

**Steps to reproduce**:

 1. Create index
```
PUT /my_index
{
  "settings": {
    "index": {
      "analysis": {
        "analyzer": {
          "my_synonyms_only": {
            "tokenizer": "whitespace",
            "filter": [
              "synonym"
            ]
          },
          "my_synonyms": {
            "tokenizer": "whitespace",
            "filter": [
              "multiplexer"
            ]
          }
        },
        "filter": {
          "synonym": {
            "type": "synonym_graph",
            "synonyms_path": "analysis/synonyms.txt",
            "updateable": true
          },
          "delimiter": {
            "type": "word_delimiter_graph",
            "preserve_original": true
          },
          "multiplexer": {
            "type": "multiplexer",
            "filters": [
              "delimiter",
              "synonym"
            ]
          }
        }
      }
    }
  }
}
```
 2. Try to reload search analyzers
```
POST /my_index/_reload_search_analyzers
```

 3. Only the analyzer which uses synonym filter directly is updated. Analyzer with multiplexer is not.
```
  "reload_details" : [
    {
      "index" : "my_index",
      "reloaded_analyzers" : [
        "my_synonyms_only"
      ],
      "reloaded_node_ids" : [
        "ex70i64yRtar5gMPncOUTw"
      ]
    }
  ]
```
**4.  I would expect the my_synonyms analyzer to be reloaded also**

**Comment by cbuescher** [comment]
Seems like the reloading action doesn't trigger the reload on the analyzer containing the multiplexer because as a filter in itself, that one isn't "updateable" (that is, it doesn't inherit the updateable property of the synonym filter it contains. I think we can try making the multiplexer search-time only if any of the filters it uses is search-time (i.e. updateable). I'll have a WIP as a proposal shortly, not however that there seem to be some [general, documented restrictions on using synonym filters in multiplexers](https://www.elastic.co/guide/en/elasticsearch/reference/7.5/analysis-multiplexer-tokenfilter.html#analysis-multiplexer-tokenfilter) that are unrelated to this issue,
