### ISSUE TITLE
Issue with parsing the logs(Dissect filter)

### ISSUE THREAD

**Issue by raVi1629** [elastic/elasticsearch#50584]
Hi People,

we are parsing .csv log files and using grok and dissect filtering mechanisms for some events but sometimes the field called event_type is showing wrong/falsy names which should actually show the original event name. If anybody could help i can share the log, filer configuraiton and output we got in the kibana.

Thanks in advance:)

Ravi.

**Comment by albertzaharovits** [comment]
Hi @raVi1629 !
We prefer to reserve the GitHub issue tracker for verified problems. If you are working on something and you have questions about why it's not working the way you expect it to, please head over to https://discuss.elastic.co/c/elasticsearch . There is a much bigger crowd over there that can help you figure it out. If it turns out it's a bug, we'll open a Github issue and discuss fixes/mitigation. Please also post as much detail as possible to make the issue reproducible and highlight the expected vs the actual results.
