### ISSUE TITLE
Improve build efficiency of iterating on integration tests

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#50604]
Would it be possible to make the tasks that set up the node cache-able in the build? I sometimes find myself tweaking integration test case logic without tweaking code and in that case most of the time to run the test seems to come from spinning extracting the tar distribution and installing plugins. Since these haven't changed and I have a copy on disk it might be ok reuse them. I'm not *sure* it is ok, but it'd be nice if it were.

**Comment by mark-vieira** [comment]
@nik9000 I've reworded this issue to better capture what we want to achieve here I think. This might get split off into a number of different things, one of which is what you've encountered which is packaging and extracting the Elasticsearch test distribution is costly.

That said, we shouldn't be repeatedly extracting the tar if all you are doing is working on test code. Do you mind sharing some build scans of instances where we are doing unnecessary expensive work?

**Comment by nik9000** [comment]
> @nik9000 I've reworded this issue to better capture what we want to achieve here I think.

Thanks! That is much better!

> Do you mind sharing some build scans of instances where we are doing unnecessary expensive work?

[Here](https://gradle-enterprise.elastic.co/s/iszbmqjlcrpb2/timeline?details=jbm2x6tnwtxku) is a build scan. To be honest it is pretty hard to tell what is up here. Most the time for that integTestRunner task is spent cracking open the tar and running the plugin installer. Waiting for the node to boot all the way was only a few seconds. The tests took maybe 20 seconds. Just installing plugins took something like two minutes.

**Comment by rjernst** [comment]
Testclusters doesn't know anything about previous runs which may be able to be reused. It just says "This cluster is needed before this task runs, let me do all the setup and run it". It would certainly be better for us to be smarter here, I am just confirming this is currently not implemented and what you see is expected, at the moment.

**Comment by mark-vieira** [comment]
> Most the time for that integTestRunner task is spent cracking open the tar and running the plugin installer.

We don't actually extract anything in the test runner task, that's actually done by [this](https://gradle-enterprise.elastic.co/s/iszbmqjlcrpb2/timeline?details=ds4qbsn2q2esc&taskFilter=extra) task, which you can see is correctly UP-TO-DATE. Instead we hardlink the distribution, then do some other minimal copying of things like config.

As Ryan mentions, there's not a whole lot we can avoid here, that overhead is the cost of setting up the cluster. We do this on every run because we don't want any state left over from previous runs. I'm wondering why installing the plugins took so long. I'm not familiar enough with that process to know if we can optimize it better (other than no installing them at all if they are unneeded).

**Comment by mark-vieira** [comment]
I think we've mostly addressed this. Running integration tests (including BWC tests) now no longer performs and intermediary pack/unpack step. We simply copy the distribution directly and hardlink. This is about as efficient as we can make this process. Folks should observe that kicking off rest tests is considerably more efficient.
