### ISSUE TITLE
BaseNodesRequest default timeout is null, but MasterNodeRequest masterNodeTimeout default is 30s; 

### ISSUE THREAD

**Issue by GeChenxin** [elastic/elasticsearch#50641]
Some request extends BaseNodesRequest, such as "/_cat/nodes", "/_nodes/stats", not return whether some node occurred exception.
I think the timeout in BaseNodesRequest should have default value 30s.

**Comment by DaveCTurner** [comment]
We discussed this as a team today. The default of no timeout is deliberate: there are some requests that might take a very long time to complete, so there is no way to choose a sensible finite time limit that would apply to them all. The `masterNodeTimeout` is not a timeout on the whole request, only on the time it takes to find the master: once the request has reached the master it might run there for arbitrarily long before returning.

In general we expect clients to implement their own timeouts, because a client-side timeout is robust to network problems that would prevent Elasticsearch from reporting a server-side timeout to the client. Clients can cancel a timed-out request by closing the connection to Elasticsearch before receiving the response, and Elasticsearch uses TCP keepalives to periodically verify that the client is still waiting for its response.

The promptness with which work is cancelled varies from endpoint to endpoint; #55550 links to some recent improvements in this area for heavier stats requests, although this work does not directly affect the relatively lightweight `GET /_cat/nodes` or `GET /_nodes/stats` endpoints. If we see that improvement is needed to either of those then we can now do so relatively easily; we would welcome PRs that do so if you would like to contribute them.

Since there's no action needed here, I am closing this.
