### ISSUE TITLE
[Feature Request] provide OIDC integration feature for free

### ISSUE THREAD

**Issue by Hokwang** [elastic/elasticsearch#50847]
**Describe the feature**:

I think many open source projects have auth feature
and provide LDAP integration, OIDC integration
natively or plugin way.

But now, elasticsearch and kibana provide basic auth for free,
LDAP and OIDC is gold or platinum subscription needed.

How about provide these auth feature for free?
That would be welcomed from all open source community users.

Thanks,

**Comment by skearns64** [comment]
Thanks for being part of the Elastic community @Hokwang - we welcome open conversations like this. 

Since the beginning of Elasticsearch, we've been clear about our belief that we need a balance of OSS / free and paid features to allow us to invest in moving Elasticsearch and the whole stack forward. It sounds like you're already aware that we made the [core security features of the stack free](https://www.elastic.co/blog/security-for-elasticsearch-is-now-free) in version 6.8 and above, including authentication, RBAC, and Kibana Spaces. While we're always trying to re-evaluate and strike the right balance, at the moment we don't have any plans to change the license level of our OIDC integration. 
I'll close the issue, as it's not something that we plan to do now, but we’ll take your request into account going forward.
