### ISSUE TITLE
[Code cleanup] Removal of java-version-checker tool

### ISSUE THREAD

**Issue by septimit** [elastic/elasticsearch#50888]
**Code cleanup**: Validation of the java version is currently done in the java-version-checker tool. This validation would more naturally fit into the respective elasticsearch-env[.bat] scripts, since java provides command line arguments to retrieve the runtime version. This is  a rather trivial cleanup that would reduce the build time and project loc

**Comment by jasontedor** [comment]
We deliberately use a Java application because it's easier to make it work cross-platform rather than putting more logic into the shell scripts, and parsing the output of a `java -version`. Over time, we are aiming to move even more the logic that is currently in shell scripts into cross-platform Java code (see also the `jvm.options` parser).

The Java version checker hardly contributes to the build time. As for the lines of code, it already a small number of lines of code, and having to rewrite that logic in shell and batch would negate some of the savings anyway.

Thanks for the feedback, but we are going to leave this as-is.
