### ISSUE TITLE
Darwin build fails with "Failed to ping owner of lock for file hash cache"

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#50954]
According to build-stats data, we have seen consistent test failures every day since Dec 15, 2019. The following diagram shows the number of builds that contained the log message `"Failed to ping owner of lock for file hash cache"`:

![build-failure](https://user-images.githubusercontent.com/1699576/72324301-e276d400-36aa-11ea-9617-92656e697ed1.png)

This happens for [Darwin builds](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/). Here are the links to the three most recent build scans:

* https://gradle-enterprise.elastic.co/s/7qx2rlwo3fdgk
* https://gradle-enterprise.elastic.co/s/7yawrwsbwipcq
* https://gradle-enterprise.elastic.co/s/mans526aqqd5y

Error message:

```
Could not resolve all files for configuration ':x-pack:plugin:watcher:testCompileClasspath'.
> Could not resolve org.subethamail:subethasmtp:3.1.7.
  Required by:
      project :x-pack:plugin:watcher
  > Could not resolve org.subethamail:subethasmtp:3.1.7.
    > Failed to ping owner of lock for artifact cache (/private/var/lib/jenkins/.gradle/caches/modules-2) (lock id: 5776685224069435609, port: 54317)
      > No route to host
```

There is an open Gradle issue (https://github.com/gradle/gradle/issues/2257) about this error message and a [comment](https://github.com/gradle/gradle/issues/2257#issuecomment-417393557) indicates that this might happen because of multiple Gradle processes attempting to use the same Gradle cache (this may or may not be true in our case but I wanted to offer this as a data point).

Reproducability: Reproduces always since Dec 15, 2019 on our CI infrastructure.

**Comment by mark-vieira** [comment]
This will be fixed in Gradle 6.1.

**Comment by danielmitterdorfer** [comment]
Ah, great! :) Out of interest, is there a Gradle issue for this that I did not find yesterday?

**Comment by mark-vieira** [comment]
The error is a bit esoteric but this is the core issue: https://github.com/gradle/gradle/issues/11426

What's ends up happening is that a Gradle daemon opens a lock on some file cache or registry. Because these file system locks require IO, Gradle defaults to holding this locks optimistically until another daemon requests it to avoid having to release and reaquire the lock over and over. The other daemon requests the lock via TCP, but this issue above results in the daemon incorrectly advertising wrong addresses. The workaround I put in place didn't seem to solve the issue on our MacOS workers but since we're now on Gradle 6.1 this issue can be closed.
