### ISSUE TITLE
Add the functionality to explicitly specify a printer for dates

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#51156]
When a user wants to be able to insert both numeric values, as for example `epoch_millis` and string values parsed using for example `strict_optional_time` and use the following in the index mapping:
```
"format": "strict_date_optional_time||epoch_second"
```
Then, negative numeric values with >= 4 digits and positive values with 4 digits will be successfully parsed as years, where any other numeric values will be parsed as `epoch_millis`.
To avoid this incorrect behaviour for this use case, the user can invert the formats:
```
"format": "epoch_second||strict_date_optional_time"
```
This would solve the parsing problem, so every number will be parsed as millisecond and the string values like `2020-01-17[T10:11:22.123]` would be parsed as full timestamps. The issue that rises is that the printer used is the first format defined, in this case: `epoch_second`, which will show all query results on this index as milliseconds.

It might be helpful to be able to define explicitly a date printer to solve this situation.
 
Relates to #51080

**Comment by pgomulka** [comment]
it  is doable, but I wonder if the effort is worth  it. Seems like a not the most common scenario (to have a separate printer)
adding  team-discuss to chat with core-infra

**Comment by rjernst** [comment]
As @pgomulka noted, this is a pretty rare scenario. In a year of this issue being open we have not seen any other asks for it. Since we try to limit the surface area of features we must maintain, we must be selective in new features we take on, however small they are. Give that, we do not plan to implement this feature, and will close.

If anyone in the future comes across this issue and feels they have additional need for the feature, please leave a comment or open a new issue and we can reopen/reprioritize as the need arises.
