### ISSUE TITLE
Ingest: Align syntax to use `_ingest._value` across ingest processors

### ISSUE THREAD

**Issue by fkelbert** [elastic/elasticsearch#51162]
Different ingest processors require different syntax to access the value of `_ingest._value` (`"_ingest._value"` vs `"{{_ingest._value}}"`).

Instead, syntax across different processors should be the same for better user experience.

E.g., `append` vs `uppercase`:

```
POST /_ingest/pipeline/_simulate
{
  "pipeline": {
    "processors": [
      {
        "foreach": {
          "field": "recipients",
          "processor": {
            "append": {
              "field": "test",
              "value": [ "{{_ingest._value}}" ]
            }
          }
        }
      }
    ]
  },
  "docs": [
    {
      "_source": {
        "recipients": [
          "Bar@foo.com"
        ]
      }
    }
  ]
}
```

vs

```
POST /_ingest/pipeline/_simulate
{
  "pipeline": {
    "processors": [
      {
        "foreach": {
          "field": "recipients",
          "processor": {
            "uppercase": {
              "field": "_ingest._value"
            }
          }
        }
      }
    ]
  },
  "docs": [
    {
      "_source": {
        "recipients": [
          "Bar@foo.com"
        ]
      }
    }
  ]
}
```

**Comment by danhermann** [comment]
@fkelbert, the uppercase processor takes only a field name and not literal values (it would make no sense to uppercase a literal value) and therefore does not require the template snippet syntax. The append processor, on the other hand, accepts a _value_ rather than a field name. The template snippet syntax is available should you wish the append processor to use the value of a field. These are intentionally different behaviors (and their parameters are intentionally named `field` and `value`).

**Comment by fkelbert** [comment]
@danhermann Thanks for the clarification. The difference does make sense.

And yet, I am wondering if this can be simplified for users. At the very least, we should provide documentation explaining the difference and in which context which syntax needs to be used.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
