### ISSUE TITLE
Ingest pipeline is parsing date wrong

### ISSUE THREAD

**Issue by Jens-H-Eriksen** [elastic/elasticsearch#51212]
### Bug report 
**Description of the problem including expected versus actual behavior**:

When ingesting logs with filebeats using an elasticsearch pipeline, the year in the loglines timestamp is being parsed as the _actual year_, instead of the year in the logged line. 
This is a major bug as logs are ending up at a wrong date.

![2020-01-20_09h51_34](https://user-images.githubusercontent.com/26311915/72712088-acce6100-3b6a-11ea-9ad2-b6aceb95b121.png)

**Steps to reproduce**:

 1. Add the pipepline I've attached 
 2. Simulate the Pipelinebehaivor by POST'ing the attached logline example
 3. Notice the @timestamp will end up as the same datetime, but with the year 2020 not 2018 as it should be.

[pipeline.txt](https://github.com/elastic/elasticsearch/files/4085282/pipeline.txt)
[logline.txt](https://github.com/elastic/elasticsearch/files/4085283/logline.txt)

**Elasticsearch version** 
    "number" : "7.4.1",
    "build_flavor" : "unknown",
    "build_type" : "unknown",
    "build_hash" : "fc0eeb6e2c25915d63d871d344e3d0b45ea0ea1e",
    "build_date" : "2019-10-22T17:16:35.176724Z",
    "build_snapshot" : false,
    "lucene_version" : "8.2.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"

**Plugins installed**: 
none

**JVM version** 
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

**OS version** 
OS Name:                   Microsoft Windows Server 2012 R2 Standard
OS Version:                6.3.9600 N/A Build 9600
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Server
OS Build Type:             Multiprocessor Free
BIOS Version:              Phoenix Technologies LTD 6.00, 19-09-2018

**Comment by Jens-H-Eriksen** [comment]
Just found out that the year part in the pipeline is casesensetive ?.... so changing from _YYYY_ to _yyyy_ makes the pipeline work as expected.

**Comment by dadoonet** [comment]
Yeah. Year should be `yyyy`. Have a look at https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html#strict-date-time

**Comment by Jens-H-Eriksen** [comment]
And this is fair... but it should then fail if you use capital letters, not just parse it as the actual year. Otherwise it will lead to wrong data.

**Comment by jasontedor** [comment]
`YYYY` means something too (week-based year), just not what you thought it meant. The distinction has [caused some infamous trouble in the past](https://www.firstpost.com/tech/news-analysis/twitter-suffers-massive-outage-on-all-online-platforms-back-now-3660631.html).

**Comment by jasontedor** [comment]
I don't think there are any changes to make here, so I am closing this issue. Please feel free to comment if you think that I have closed this in error, closing is by no means final.

**Comment by Jens-H-Eriksen** [comment]
@jasontedor  I surely think this is an issue that should be adressed. Even though YYYY means week-based year, it should _not_ change the year to the actual year, thus changing the date completly.

In my example the date **2018**-01-18 is changed to **2020**-01-18.  
This can not just happen becourse of the conversion to week-based year. I've tested with different dates (1912, 2017 ect.) and they are all changed to the actual year (=2020) 
Please give this another roll.

**Comment by jasontedor** [comment]
@pgomulka Can you investigate exactly what is happening here?

**Comment by pgomulka** [comment]
@Jens-H-Eriksen from java.time point of view, Year and Week-Based-Year are two separate date fields. 
The Ingest logic is relying on the presence of Year field, and since when parsing `2018-01-18` with `YYYY-MM-dd` with fields WeekBasedYear, Month and Day it cannot find the Year fields and it then tries to default to current year.
This is needed as some logs (sys logs) are missing the Year part and the intention is to default to current year.
See the code here https://github.com/elastic/elasticsearch/blob/7.4/modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/DateFormat.java#L101

Also see the definition of week based year field https://docs.oracle.com/javase/8/docs/api/java/time/temporal/WeekFields.html#weekBasedYear--

I would recommend changing your pattern to `uuuu-MM-dd` where `u` stands for year and is what you neeed. `y` is for year of era and you don't specify an era in your dates. 
We enabled Strict mode in 7.5, but we won't reject patterns with `yyyy` without and Era. I expect this would be a major inconvenience for users, so we relaxed this for this specific usecase. 
Using `uuuu` is correct as per https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html and I would recommend it.
relates https://github.com/elastic/elasticsearch/issues/41797

**Comment by pgomulka** [comment]
another question is what if a user is intentionally sending dates with week based year and the pattern is allowing us to recalculate a Year part.
for instance `STRICT_BASIC_WEEK_DATE` -> `YYYY'W'wwe`. Should be enough to recalculate the Year basing on WeekBasedYear.

**Comment by pgomulka** [comment]
closed as per lack of feedback
