### ISSUE TITLE
SQL: ORDER BY field and function will order by field only

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#51224]
The following query: 
`SELECT YEAR(birth_date) as year, emp_no FROM test_emp ORDER BY year, emp_no ASC LIMIT 2` 
(run over the [employees.csv](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/sql/qa/src/main/resources/employees.csv) data) returns:
```
     year      |    emp_no     
---------------+---------------
1952           |10097          
1952           |10009          
```
while the correct result would have ordered the rows the other way.

ES/SQL fetches the `birth_date` docvalue in the requested top two docs and applies the `YEAR` extraction, but doesn't proceed in this case to reordering the results for the docs where the function result is not unique.

Potentially related to #50355.

**Comment by matriv** [comment]
This is not related to: #50355
It's a behaviour that pops up when there are further ORDER BY arguments that resolve the ties.
It has to do with the YEAR() function only which instead of producing a script to be used in ORDER BY it falls to the underlying date field (in our case birth_date) as an optimisation.

**Comment by matriv** [comment]
`master`: f41efd6753dc3650a7eabb3e07b02b3b32c5704c
`7.x`: f373020349a7d3ab2a7fefa7ebe07f69b64d5f5a
`7.6`: af456dcc318f90db53be4f64ccd737f5fe420375
`6.8`: ea4504c495a87ddf95939027e882330c946f58c3
