### ISSUE TITLE
Should the write queue size be a byte size rather than a number of items?

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#51336]
Sizing the `write` queue is tricky: our default size of 200 feels huge if clients are sending bulk requests that are 10MB each, but small if we consider the case of single-document requests. This makes me wonder whether a byte size would be a better way to configure the size of the write queue?

**Comment by tbrooks8** [comment]
Related: https://github.com/elastic/elasticsearch/issues/50807

**Comment by jasontedor** [comment]
Thanks for raising this issue for discussion @jpountz. I discussed this idea last week with @tbrooks8 in the context of #50807 and also with @henningandersen in the context of autoscaling. It comes up in the latter as we think about adding ingest triggers to autoscale. For example, suppose that we were to consider an ingest trigger based on the write thread pool queue being full for a "extended" period of time. This doesn't necessarily mean that we should autoscale though, because it could mean that the user is inefficiently using the bulk API, by stuffing the queue with many tiny bulk requests at a high rate; autoscaling here would be a mistake. If however, the queue was sized by bytes instead of by count with a default related to the heap size, then a consistently stuffed queue would more reliably signal a capacity issue instead of an efficiency issue. For me, the main open question is not whether to do this, but how to default size the queue by bytes. I would consider a plan here along the lines of:
 - introduce the possibility of having a byte-sized write queue in 7.x
 - for users that are not customizing the size (count) of the write queue, default to using a byte-sized write count
 - deprecate in 7.x the ability to have a count-based write queue
 - remove in 8.0.0 the ability to have a count-based write queue

**Comment by ywelsch** [comment]
For write requests, byte size is a better measure of "amount of work required" than just  the number of top-level requests, as such requests could be either a single-index request or a bulk request with 10k items, both of which are currently treated the same way when estimating amount of work. A simpler (but a bit more imprecise) alternative to the byte-size-based approach would be to take the count of items in the bulk request into account.

In any case, I wonder if moving the queue to byte count will get us to a happy place. To understand this, it should be noted that, in a certain way, this will have the write executor queue fulfil a similar role to the in-flight request circuit breaker, but limited to write activity. A key difference, however, is that the in-flight request breaker tracks memory usage from receival of request to sending response, whereas the executor stops tracking the request as soon as processing has stopped. In many cases, the request (and memory usage) still lingers around on the node (think for example about a request that's been processed on a primary shard, and that is awaiting replication to the replicas, or a request that's been processed on the coordinator node, and that has been sent to the primary), and consumes memory. Tracking this memory is crucial to get better breaker behavior and to ensure healthy nodes (with a fair search/index load). In particular, this shows that the lifecycle of a request, at least for write activity, is only partly tied to the executor. 

The queue of the write executor is a good estimator for expected CPU activity on the node, but less so for memory consumption related to the full lifecycle of the request on the node. I wonder if estimating the expected CPU activity is important for write requests, given that most times you can't do anything else except retry at a later time, as you can't route around those shards that carry the indexing load (like for example adaptive replica selection). I think we should improve the breaker architecture, and introduce a proper breaker for write activity, which is taking the actual lifecycle of write requests into account. The executor can then have a much simpler model, using either an unbounded queue (or a bound counting the request subitems, see above, assuming a model of minimum constant amount of work per sub-item).

Finally we should investigate unifying the concepts of queue rejections and breakers, currently throwing two kinds of exceptions, `EsRejectedExecutionException` vs `CircuitBreakingException`, both of which indicate "can't handle this right now".

**Comment by DaveCTurner** [comment]
I think this is resolved by the work related to #59263 so I am closing it.
