### ISSUE TITLE
Lower required permission for _analzye when calling it without an index

### ISSUE THREAD

**Issue by pheyos** [elastic/elasticsearch#51391]
It's possible to use the `_analyze` endpoint without an index, example taken from our [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-analyze.html):
```
GET /_analyze
{
  "analyzer": "standard",
  "text": "Quick Brown Foxes!"
}
```

When doing this as a user without `cluster:manage` or `cluster:all`, an error is returned:
```
action [cluster:admin/analyze] is unauthorized for user [USER]
```

In a slack discussion @romseygeek pointed out that if you use `_analyze` with an index and use a field that doesn't exist, it falls back to the default analyzer, potentially leaking data. So the required high privileges are justified for this use case.
But when calling the endpoint without an index, there is no such danger, so this request does not necessarily need to be restricted that strong. @jasontedor suggested to `use a separate (virtual) transport action for that one so that it doesn’t require such elevated privileges`.

**Background**: We have a new ML UI functionality in 7.6 that uses the `_analyze` API (with strings in the request body only) in order to show how categorization would tokenize a message. The `cluster:manage` would be a higher privilege than required for the rest of ML and we would like to avoid it if possible.

cc @droberts195

**Comment by droberts195** [comment]
The other possibility would be that we introduce an ML analyze endpoint that:

* Only works on supplied strings, never a field in a named index
* Defaults to ML's default categorization analyzer if no analyzer is specified
* Is secured by the `manage_ml` cluster privilege

For example, `GET /_ml/anomaly_detectors/_categorization/analyze` or something like that.  Then anyone who has permission to create an ML job will be able to use it.

If there's a wider need for a lower privilege analyze endpoint that only works on strings, not index fields, then the ML UI could certainly use that instead of a new ML endpoint.  (The ML UI can find out what the default categorization analyzer from the ML info endpoint.)  But if ML would be the only user of the lower privilege analyze endpoint then there are some benefits to having a slightly more specialised ML endpoint.

We probably shouldn't do both though, so let us know whether there's a wider need for a lower privilege analyze endpoint.

**Comment by jimczi** [comment]
Another possibility could be to authorize `cluster:admin/analyze` directly in the `manage_ml` privilege ? We already have the distinction for requests that contain an index and use `indices:admin/analyze` rather than the [cluster privilege](https://github.com/elastic/elasticsearch/blob/17581f2f6f52369b93d15fa534ce9c1fa6d0846a/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/action/SecurityActionMapper.java#L41) so this change wouldn't expose the API with indices to ml users.

**Comment by droberts195** [comment]
> Another possibility could be to authorize `cluster:admin/analyze` directly in the `manage_ml` privilege ?

Yes, true.  That would certainly be the path of least effort - just a one line in the core code and maybe a couple more in tests.  I can make that change if nobody objects or has a good reason to go with one of the other options.

**Comment by jasontedor** [comment]
Ah, I didn't realize that we already did that @jimczi, thanks for pointing it out. It's a little sneaky that it happens in security rather than in core, IMO.

**Comment by albertzaharovits** [comment]
Thank you for pitching in @droberts195 @jimczi and @jasontedor .

I see that the analyze API can generate both "index" and "cluster" wide transport actions (from the authz point of view). I was not aware of the hack in the `SecurityActionMapper` which authorizes the same action in different ways, depending on the request. I agree with @jasontedor that the REST handler should instead delegate to two different transport actions, one for index-scope analyzers and the other one for general, cluster wide analyzers; in this way Security code avoids making assumptions about how ES core interprets different request formats. I think we should remediate this for version 8.

Even if we were to have this separation today, I don't see any better options for an existing privilege under which we should group the analyze transport actions. That is, given the potential DoS of the analyzer (both using index or general analyzers) we don't have a non-`manage` better option.

Given this, I see two courses of actions:

- Create a new API as @droberts195 suggests, under the `cluster:admin/xpack/ml/*` namespace, which internally uses the analyze transport action. I don't like adding the analyze action under the `manage_ml` privilege as @jimczi suggested because a privilege should have a consistent "story" about what it allows for (privileges are not a set of permitted actions, their strength is that they allow to a set of closely related actions). We have "built-in" roles for privileges that should go together for certain stack features/components, which segues to the other course of action:
- Add the analyze action to the `kibana_system` built-in reserved role and make the ML UI component use the ES client of the `kibana` itself (instead of the client associated with the privileges of the end user).

I don't have any preference among the two options, and I'm willing to help with either (but I'm probably not the best person to write the ML action that does a particular form of analyze or to adjust the ML UI component). @droberts195 @pheyos let me know if this makes sense, and if I can help with anything.

**Comment by droberts195** [comment]
Thanks for the suggestions @albertzaharovits.

I think we should go with:

> * Add the analyze action to the `kibana_system` built-in reserved role and make the ML UI component use the ES client of the `kibana` itself (instead of the client associated with the privileges of the end user).

This is similar to what we'll be doing for all ML UI calls to Elasticsearch in 8.0 when the ML in Spaces project reaches its conclusion.  So we might as well start with this single call in 7.7.

**Comment by droberts195** [comment]
Although we worked around this in a way that worked for the ML UI, #56994 is a case of a user suffering from the same problem.
