### ISSUE TITLE
transport client configurable via settings

### ISSUE THREAD

**Issue by brackxm** [elastic/elasticsearch#5153]
Allow the transport client to be configurable via settings.
Currently hosts & ports need to added via addTransportAddress().
It would be more flexible to also allow hosts & ports to be configured via settings.

For example, this could be done via a comma separated list
```
client.transport.address: host1:9300,host2:9300
```
Or with separate lists for hosts & ports.

Or map style
```
client.transport.address.a.host: host1
client.transport.address.a.port: 9300
client.transport.address.b.host: host2
client.transport.address.b.port: 9300
```

**Comment by dakrone** [comment]
@spinscale can you comment on this? Is the need for this removing with transport profiles?

**Comment by spinscale** [comment]
@dakrone unsure about your question here, would rather say no. This looks to me as an abbreviation for the `TransportClient` configuration, that has nothing to do with the profiles on the server side. It's just about specifying the destination addresses as part of the settings instead of calling `TransportClient.addTransportAddress`

**Comment by dakrone** [comment]
@spinscale ahh okay, I misunderstood this to be on the server side instead of the client (duh, I see "client" in the title now), thanks for the clarification.

**Comment by clintongormley** [comment]
Transport client no longer loads the config file at all.  Closing
