### ISSUE TITLE
Designate "system" ILM policies with a dot prefix

### ISSUE THREAD

**Issue by matschaffer** [elastic/elasticsearch#51589]
**Describe the feature**:

System indices have the convention of starting with a dot (`.`). This makes isolation of stack indices from user indices quick and simple.

We don't do the same with ILM policies (or other stack managed resources), for example https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/core/src/main/resources/watch-history-ilm-policy.json

I'd like to propose that we extend the dot convention to ILM policies or potentially other elasticsearch resources that may contain a mix of both stack and user managed entries.

**Comment by dakrone** [comment]
We discussed this and decided that we don't want to designate system-provided ILM policies with a dot. Rather, we expect (and encourage) users to change the policies that are put in place by ES (or other tools), and we don't want to confuse the idea of system indices (starting with a dot) that are reserved, since these policies are not reserved.
