### ISSUE TITLE
Safely register rest handlers outside of constructor

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#51622]
The common pattern used by the RestHandler objects within the codebase is to have a constructor which registers the handler with the RestController for a set of paths and methods, such as:

```java
public MyRestHandler(RestController controller) {
    controller.registerHandler(Method.GET, "/_my_endpoint", this);
}
```

This is publishing the `this` reference before the object is fully constructed, which violates the JLS. This is similar to issues we have with registering cluster state listeners within constructors, see #38560.

**Comment by rjernst** [comment]
Thanks for opening this @jaymode! This has long bugged me. In addition to the JLS violation, this makes the handlers more complicated to initialize, when they could mostly have empty ctors, and more error prone to write since you may forget to actually register yourself.

WDYT about having BaseRestHandler have a method for returning a `Map<String, List<RestRequest.Method>>` and doing the registering from ActionModule after all the rest handlers have been collected?

**Comment by jaymode** [comment]
@rjernst that's exactly my plan and the change I will be working on. It is necessary for part of the approach I plan to take for the initial system indices implementation
