### ISSUE TITLE
Support `monitoring.*` config settings to ship directly to the monitoring cluster

### ISSUE THREAD

**Issue by chrisronline** [elastic/elasticsearch#51763]
In line with other stack products, we need to introduce consistent settings in Elasticsearch to allow users to configure where to send their monitoring data. 

Right now, this is configured through exporters (which is fine) but the naming is inconsistent with planned changed across the rest of the stack. For consistency, we should introduce `monitoring.*` settings that would "replace" the existing `xpack.monitoring.exporters.<exporter_name>`.

For reference, here are the other stack products open issues:

- Logstash https://github.com/elastic/logstash/issues/11403
- Kibana https://github.com/elastic/kibana/issues/52639
- Beats has had this configuration GA since 7.2

**Comment by chrisronline** [comment]
@jakelandis It sounds like ES isn't on board with these changes, but I can't recall if we made any concrete decisions. Do you happen to know the state of this?

**Comment by jakelandis** [comment]
@chrisronline I think this issue can probably be closed since if I understand correctly the new naming pattern is in part to help disambiguate where and how to send monitoring data. 

if new pattern 
 then send document directly to monitoring cluster (and ensure document is formatted correctly) 
else if old pattern 
 then send document to ES custom monitoring bulk endpoint (and ensure document is format is the same it always has been)

In this case ES is special since it has always shipped directly to the monitoring cluster and never routed documents back through the custom monitoring bulk endpoint. So we don't have a need to disambiguate. Further, since local exporters are going away in favor of beats/fleet based monitoring in 8.0 changing the name provides minimal value in 7.x since the setting will be going away in 8.0. 

Did I misunderstand anything here ?

**Comment by chrisronline** [comment]
Sounds good. Closing
