### ISSUE TITLE
Making delete, close and update-settings index IMMEDIATE in pending tasks

### ISSUE THREAD

**Issue by garyelephant** [elastic/elasticsearch#51781]
For now, close, delete and update-setting index is **URGENT** in pending tasks, as same as shard-failed and shard started, which means It always get stuck in closing and deleting indices when the cluster is in recovery.
However, close or delete or update-setting indices making elasticsearch recovery more faster, so is it possible to make Delete, Close Index **IMMEDIATE** in pending tasks ?

ES Version : 5.4.3
OS Version: CentOS 7

**Comment by DaveCTurner** [comment]
I think we should apply similar reasoning to [my comment](https://github.com/elastic/elasticsearch/issues/50778#issuecomment-572625336) on another issue about promoting priorities across the board:

I do not think these should be IMMEDIATE tasks. There's something very wrong with the cluster if the master does not get around to lower priority tasks in a reasonably short amount of time, and the solution to that is definitely not to promote things to IMMEDIATE.

Note that we split up the historically-expensive shard-started task into a cheap URGENT part and a more expensive NORMAL part in #44433, and batched the more expensive parts together to avoid duplicate work. If we are still seeing URGENT-level tasks running unduly slowly then I would like more details so we can continue in this direction.

I am closing this as I think it is fixed in more recent versions; if you are still seeing issues with inappropriate priorities or slowly-running tasks in versions ≥7.4.0 then please get back in touch and we can reopen this.
