### ISSUE TITLE
top_metrics stabilization

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#51813]
We're getting pretty close to merging the new `top_metrics` aggregation (#51155). It'll be marked "experimental" because we will be looking into a few features soon that, if we can't implement them, will change the response format:
* Support a `size` parameter to return the top *few* metrics. Not many though.
* Support returning more than a single metric field.

**Comment by nik9000** [comment]
Another question: should top_metrics preserve the type of the metrics or continue to cast them all to `double`? It *does* preserve the type of the sort, but not the metrics.

**Comment by polyfractal** [comment]
Hmmmm.  That's a good question.  

#### Preserve type
- Most equivalent to top_hits (e.g. you want the original value from the doc), albeit it potentially a little different due to docvalues vs source

#### Cast to Double
- Plays nice with pipeline aggs
- Consistent with rest of aggs

Perhaps we could have something similar to "_as_string" but for the type?  `foo_as_original_type` or whatever, alongside with the value cast to a double?  Then pipeline aggs could fetch the double value, and consumers of the response could choose?

**Comment by nik9000** [comment]
The pipeline agg can fetch the double either way, I think. The trick is whether we preserve the type when we accumulate them and when we render them. Without that, for example, dates will look like millis since epoch. OTOH, no other agg does this. But it *sounds* like a good thing to do.

I'm happy to wait some on that too, but I figure it'd be nice to decide while we've got the experimental label.

**Comment by nik9000** [comment]
> I'm happy to wait some on that too, but I figure it'd be nice to decide while we've got the experimental label.

I talked to folks a bit and decided that, yes, I should return variables in their original type. In this case that means preserving their "formatter" and deciding between `double` and `long`. I don't support `keyword` fields so there is nothing to do there.

**Comment by nik9000** [comment]
I've opened #53288 for preserving types. If we're good with that I think all that is left for this is for me to take a fresh eye to the docs.
