### ISSUE TITLE
[CI] Windows Packaging tests fail with Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by albertzaharovits** [elastic/elasticsearch#52047]
Several cases of
```
13:02:31 Recording test results
13:02:33 [PostBuildScript] - [INFO] Executing post build scripts.
13:02:33 [windows-2019] $ powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File C:\Users\JENKIN~1.PAC\AppData\Local\Temp\jenkins3936774459098441880.ps1
13:02:34 Invoke-WebRequest : The response content cannot be parsed because the Internet Explorer engine is not available, or 
13:02:34 Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again. 
13:02:34 At C:\Users\jenkins.PACKER-5DA3F2D9\AppData\Local\Temp\jenkins3936774459098441880.ps1:2 char:1
13:02:34 + Invoke-WebRequest -Method Post -ContentType "text/plain" -Body "$env: ...
13:02:34 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
13:02:34     + CategoryInfo          : NotImplemented: (:) [Invoke-WebRequest], NotSupportedException
13:02:34     + FullyQualifiedErrorId : WebCmdletIEDomNotSupportedException,Microsoft.PowerShell.Commands.InvokeWebRequestComman 
```
Where the build is successful but it then fails.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob+packaging-tests-windows-gcp/os=windows-2012-r2/315/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob+packaging-tests-windows-gcp/os=windows-2019/315/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.6+multijob+packaging-tests-windows-gcp/os=windows-2012-r2/69/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.6+multijob+packaging-tests-windows-gcp/os=windows-2019/69/console

**Comment by mark-vieira** [comment]
This looks to be an issue with how the build is reporting it's exit code to Jenkins. Ironically the build has been failing for awhile now, yet Jenkins has been reporting it as passing incorrectly. Since I recently muted some failing tests these builds are now "passing", yet Jenkins is reporting the opposite 🤦‍♂ 

I've backported 73cd9e0c1bcc3ee4869f2ed9f79816055e694396 which fixed this in `master` but was never backported to `7.x` or `7.6`. That should sort this out.
