### ISSUE TITLE
Accessing document _source using Painless script is returning incorrect field value

### ISSUE THREAD

**Issue by tilan7663** [elastic/elasticsearch#52103]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.5.2

**Plugins installed**: []

**JVM version** (`java -version`): java 13.0.2

**OS version** (`uname -a` if on a Unix-like system):Ubuntu 18.04

**Description of the problem including expected versus actual behavior**:
Painless script is returning incorrect value when accessing document _source

**Steps to reproduce**:
1. Create index with single shard
```
PUT /test
{
    "settings" : {
        "number_of_shards" : 1,
    }
}
```
2. Create documents
```
PUT test/_doc/1
{
    "field" : 1
}
```
```
PUT test/_doc/2
{
    "field" : 2
}
```
3. Query
```
GET test/_search
    {
        "script_fields" : {
            "test1" : {
                "script" : "params['_source']"
            }
        }
    }
```
Expected Result
```
[
  {
    "_index": "test",
    "_type": "_doc",
    "_id": "1",
    "_score": 1,
    "fields": {
      "test1": [
        {
          "field": 1
        }
      ]
    }
  },
  {
    "_index": "test",
    "_type": "_doc",
    "_id": "2",
    "_score": 1,
    "fields": {
      "test1": [
        {
          "field": 2
        }
      ]
    }
  }
]
```
Actual Result
```
[
  {
    "_index": "test",
    "_type": "_doc",
    "_id": "1",
    "_score": 1,
    "fields": {
      "test1": [
        {
          "field": 2
        }
      ]
    }
  },
  {
    "_index": "test",
    "_type": "_doc",
    "_id": "2",
    "_score": 1,
    "fields": {
      "test1": [
        {
          "field": 2
        }
      ]
    }
  }
]
```
Both documents return the same value for script field test1

**Provide logs (if relevant)**:

**Comment by rjernst** [comment]
@tilan7663 Thank you for the report and detailed analysis. The underlying issue is SearchLookup uses a shared object across documents for source (and doc values). This object should not be held onto across documents, yet we may hold onto it if returning from a script field (note that this could happen in other contexts that return Object as well). Unfortunately I don't think the associated PR will completely fix the issue, as it would only catch the case of a root object being a source lookup, but the script could return eg a Map containing the source lookup as a value.

I'm not sure of a better solution right now, but we plan to discuss this in our scripting triage over the next week.

**Comment by tilan7663** [comment]
@rjernst Thanks for looking into it. I will close my PR.

**Comment by jdconrad** [comment]
This should be fixed by https://github.com/elastic/elasticsearch/pull/56831
