### ISSUE TITLE
bulk of thread_pool should also limit memory usage

### ISSUE THREAD

**Issue by kkewwei** [elastic/elasticsearch#52105]
**ES_VERSION**: 5.6.8
**JVM version**: java 1.8.0_112
**Description of the problem including actual versus:**
we know that ES limits bulk by limiting the size of thread pools regardless of memory usage, this is not perfect. sometimes content of bulk is so big that it  causes OOM.

In product, we set the bulk of thread_pool is 5000, and there comes a source data, in which average size of every document is 70kb, when the source data is written in batches, memory usage of the some data node will soon reach 90%+, and ES will become unavailable. Even if we use the default value of 200, It can also occur this case.

**expected versus:**
If we could add checking memory usage of bulk thread pools, not only the count of bulk thread pools.

**Comment by jasontedor** [comment]
The queues here are about absorbing variable demand when the threads that works on these task queues are busy executing other tasks. When the rate of queueing exceeds the rate of de-queueing for an extended period of time, it's an indication that demand on the system is higher than the capacity of the system, and we need to push back. That's why these queues are finite in size, and eventually throw rejected execution exceptions.

A problem that we have today is that the measure of counting items in the queue is not an accurate reflection of the work that a thread is going to have to do when it picks up a queued task. This is because a bulk request could contain a single small document, or many large documents, yet today they're counted the same. We have been thinking about changing the way we count items in the queue, so that it's more reflective of the amount of work that needs to be done. See #51336.

The purpose of these queues is not to directly limit memory usage though. That's a job for our circuit breakers.
