### ISSUE TITLE
Transform support for top_metrics

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#52236]
#51155 is adding a `top_metrics` aggregation which is similar to `top_hits` but trades flexibility for memory consumption and a little speed. This tracks transform's usage of it, as requested by [this](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/transforms/pivot/AggregationsTests.java#L94-L101) exception message.

**Comment by hendrikmuhs** [comment]
I gave this a try, but run into problems:

### NumericMetricsAggregation.MultiValue not suitable as generic interface

Transform uses the interfaces derived from `Aggregation`, e.g `NumericMetricsAggregation.SingleValue`. `TopMetrics` is a multi value aggregation and extends `NumericMetricsAggregation.MultiValue`. But `NumericMetricsAggregation.MultiValue`. But there are no generic members for multi value aggregations in contrast to single value which provide `value()` and `getValueAsString()`. The single value interface allows transform to support any single value aggregation without specialization.

As a workaround transform does not use `NumericMetricsAggregation.MultiValue` but its derived interfaces, e.g. `Percentile`.

`TopMetrics` misses such an interface. However, even if such an interface would exist:

### Dependency to analytics

Top metrics isn't shipped with elasticsearch but part of the analytics plugin. In order to use any classes/interfaces `transform` must depend on it. Trying so creates dependency problems even if transform would depend on analytics. But this dependency does not seem to be a good idea anyway.

So even, if `TopMetrics` adds the missing interface, it wouldn't be usable for transform if the interface is part of analytics.

### Options

I see 3 options:

 - a key-value based generic interface for `NumericMetricsAggregation.MultiValue`
   - this would avoid the need to use derived interfaces in transform
 - add a `TopMetrics` interface, however this interface must not be placed in analytics but e.g. in x-pack core
 - parse results from json(x-content) output: the only generic interface available is `toXContent`, so transform could extract results from x-content
    - I do not think this is a good idea and hope everyone agrees, just mentioning this possibility for completeness

@nik9000 what do you think?

**Comment by nik9000** [comment]
Wow `MultiValue` is terrible! Do you think something like adding `double value(String field)` to the interface would help? That feels like the key-value based interface you were talking about.

**Comment by hendrikmuhs** [comment]
> Wow `MultiValue` is terrible! Do you think something like adding `double value(String field)` to the interface would help? That feels like the key-value based interface you were talking about.

This would help, however requires me to know valid values for `field`. Therefore it would be good if I can retrieve the values for `field`, too.

Another alternative could be something similar to `Percentiles`, for example:

```
interface MultiValue extends NumericMetricsAggregation {
    interface NamedValue {
      String name();
      double value();
      String getValueAsString();
    }

    Iterable<NamedValue> namedValues();
}
```

**Comment by nik9000** [comment]
Would something like this do?

```
interface MultiValue extends NumericMetricsAggregation {
    Iterable<String> valueNames();
    double value(String name);
}
```

I feel weird wrapping the value in a name/value pair thing.

**Comment by hendrikmuhs** [comment]
> Would something like this do?
> 
> ```
> interface MultiValue extends NumericMetricsAggregation {
>     Iterable<String> valueNames();
>     double value(String name);
> }
> ```

That's looks good, too. No strong feelings, either will do.
