### ISSUE TITLE
Update Dataframe API docs reference SHAP feature importance 

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#52268]
https://www.elastic.co/guide/en/elasticsearch/reference/current/ml-update-datafeed.html

Contains the paragraph:
> Advanced configuration option. If set, feature importance for the top most important features will be computed. Importance is calculated using the SHAP (SHapley Additive exPlanations) method as described in Lundberg, S. M., & Lee, S.-I. A Unified Approach to Interpreting Model Predictions. In NeurIPS 2017..

This should be in the update data frame analytics docs but not here. This isn't an option for Datafeeds

**Comment by droberts195** [comment]
I think this is caused by a mistake in the definition of the`tag::indices[]` tag in [`ml-shared.asciidoc`](https://github.com/elastic/elasticsearch/blob/6b62ec53db825a7510f6a40bbca3a139a1bcae47/docs/reference/ml/ml-shared.asciidoc).  The definition of `tag::num-top-feature-importance-values[]` comes before `end::indices[]`.

**Comment by lcawl** [comment]
Yes, I added a fix in https://github.com/elastic/elasticsearch/pull/52246 but will separate it out so I can do a quick merge.
