### ISSUE TITLE
Missing text from highlighted searched response when field contains exclamation mark

### ISSUE THREAD

**Issue by andreiniculescu86** [elastic/elasticsearch#52333]
**Bug report** 

When highlighting a searched text the resulted highlighted text does not contain all the text from the queried field.

(I apologise if this is as expected or I am missing something)

**Elasticsearch version**: 7.1.1

**Plugins installed**: []

**JVM version** : 1.8.0_221

**OS version**: Linux XPS 5.3.0-28-generic #30~18.04.1-Ubuntu SMP Fri Jan 17 06:14:09 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
When searching for a text and requesting results query highlight, if the matched document field contains exclamation mark, then the returned highlighted text does not contain part of the text that contains the exclamation mark

document: `{ "name" : "Yahoo! Inc [Please refer to Altaba Inc and Verizon Communications Inc]"}`
searching with highlight for "inc" wildcard

_expected:_
highlighed text should be:
`"Yahoo! <em>Inc</em> [Please refer to Altaba <em>Inc</em> and Verizon Communications <em>Inc</em>]"`

_actual:_
"Yahoo!" is missing from the response. Got:
`"<em>Inc</em> [Please refer to Altaba <em>Inc</em> and Verizon Communications <em>Inc</em>]"`

I think this was something to do with the ! mark. If I remove that then everything is OK.

**Steps to reproduce**:

 1. Add document to a new index
 `  
POST test/_doc/
{
  "name" : "Yahoo! Inc [Please refer to Altaba Inc and Verizon Communications Inc]"
} `

 2. no other settings / mapping
 3. Run the query
`GET test/_search
{
  "query": {
    "bool": {
      "should": [
        {
          "wildcard": {
            "name": {
              "wildcard": "inc*"
            }
          }
        }
      ]
    }
  },
  "highlight": {
    "fields": {
         "name" : {}
    }
  }
}`

4. Got following results:
`"hits" : [
      {
        "_index" : "test",
        "_type" : "_doc",
        "_id" : "511tP3ABoqekxkoUshVf",
        "_score" : 1.0,
        "_source" : {
          "name" : "Yahoo! Inc [Please refer to Altaba Inc and Verizon Communications Inc]"
        },
        "highlight" : {
          "name" : [
            "<em>Inc</em> [Please refer to Altaba <em>Inc</em> and Verizon Communications <em>Inc</em>]"
          ]
        }
      }
    ]`

5. expecting highlight:
`"Yahoo! <em>Inc</em> [Please refer to Altaba <em>Inc</em> and Verizon Communications <em>Inc</em>]"`

I managed to make it run as expected only by setting the `"number_of_fragments" : 0`
Which was enough for my use case.

**Provide logs (if relevant)**:

**Comment by williamrandolph** [comment]
Thanks very much for your interest in Elasticsearch.

There are [fine-grained controls for highlighting](https://www.elastic.co/guide/en/elasticsearch/reference/7.1/search-request-highlighting.html#highlighting-settings) that might help with your use case. Your report matches [the expected behavior of the default highlighter](https://www.elastic.co/guide/en/elasticsearch/reference/7.1/search-request-highlighting.html#unified-highlighter), which uses characters like `!` or `.` to determine sentence boundaries.

This appears to be a user question rather than a bug, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
