### ISSUE TITLE
CLI heap size settings can be trampled

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#52368]
By default, the Elasticsearch CLI tools run with different heap settings via `elasticsearch-cli`. This script still allows the heap settings to be customized via the `ES_JAVA_OPTS` environment variable, so that users can run the CLI tools with a different heap if necessary.

When using Docker to run Elasticsearch, one of the routes for specifying the heap size is to set the appropriate JVM flags in `ES_JAVA_OPTS`. If a user later wants to run a CLI tool under `docker exec`, this potentially creates a problem because the `ES_JAVA_OPTS` flag that configured the server's heap size will also be respected by `elasticsearch-cli`.

A user that configures the heap settings via bind-mounting `jvm.options` won't experience this problem. Also, if a user executed a CLI tool by running `docker run` and bind-mounting the same mounts as the Elasticsearch server container, they wouldn’t have this problem, but that's not ideal.

I haven't checked how far back this issue goes. Given the lack of issues, it seems reasonable to assume that most users of Docker + Elasticsearch are unaffected.

**Comment by pugnascotia** [comment]
I'm struggling to get a CLI to actually abort from lack of memory, but in theory it could happen. That said, given:

   * 4GB Docker VM, and
   * ES with a 4GB heap

...then running a CLI tool under `docker exec` took much longer to execute, which in itself is a poor experience.

**Comment by pugnascotia** [comment]
If we can't think of a better way of handling this in the image, we can always update the docs to describe the problem here, and offer alternatives.

**Comment by jasontedor** [comment]
While thinking about this over the weekend, I realized that this problem is not specific to the Docker images. It applies to any case where a user has set `ES_JAVA_OPTS` in their environment, not only for the execution of a single command (e.g., `export ES_JAVA_OPTS`...). A concrete way in which this can arise is in the context of the Debian/RPM packages where we install an environment file in `/etc/(default|sysconfig)/elasticsearch`. If a user sets `ES_JAVA_OPTS` there, we source that file in `elasticsearch-env`, meaning that both the server and CLI scripts will see any common values set there.

Given this, I'm not sure that we need to do anything specific other than document, which I think we already do comprehensively, that JVM options are sourced from `ES_JAVA_OPTS`.

**Comment by mark-vieira** [comment]
I think auto heap determination helps here as well, as now we are recommending folks _not_ set heap settings for server which would be inadvertently used by the CLI tools.

Do we still need clarifying docs here or can we close this?

**Comment by pugnascotia** [comment]
But can the auto-heap sizing take account of what tool is running? A typical CLI tool doesn't need a huge heap. We even set pick the serial GC in e.g. `elasticsearch-cli`.

**Comment by mark-vieira** [comment]
The auto heap sizing stuff doesn't come into play for the CLI tools I don't believe. The JVM ergonomics code is only utilized when running Elasticsearch itself so unless otherwise specified, CLI tools would use JVM defaults.

**Comment by pugnascotia** [comment]
In that case, we can close this.
