### ISSUE TITLE
Lots of deprecation logging from DateIntervalWrapper.interval()

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#52473]
I'm currently looking at logfiles that contain quite a huge number of deprecation messages with "[interval] on [date_histogram] is deprecated, use [fixed_interval] or [calendar_interval] in the future.". Looking at the implementation in DateIntervalWrapper.interval() I wonder it would make sense to at least use "deprecatedAndMaybeLog()" here to reduce the amount of noise, but I'm missing context on why this was put there so raising as a question.

**Comment by polyfractal** [comment]
++ this would be a good candidate for `deprecatedAndMaybeLog()` I think.  No good reason it isn't today... just don't think I was aware of the option at the time.

We just want people to move off `interval()` and friends, since they are ambiguous and will go away at some point.  But there's nothing critically wrong with using them either.

I'll try to get a PR up for this shortly
