### ISSUE TITLE
[ML] Data Frame Analytics could fail to read stored state

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#52476]
The native code has a static limit on the size of documents it will write back to the process handler. 

https://github.com/elastic/ml-cpp/blob/6750684c0d10116f06afeac7735938c21d661287/lib/api/CSingleStreamDataAdder.cc#L15

There is a chance that regression or classification state documents exceed this limit. 

If the documents exceed this limit, the analytics process does not read in each one. Instead it assumes the state fit within one document. 

Data frame analytics should be able to read in numerous documents when restoring previous state.

It appears as if writing the state works fine. I tested with a much smaller `MAX_DOCUMENT_SIZE` and saw multiple state documents written with the appropriate doc names.

**Comment by droberts195** [comment]
The pattern for handling multiple state documents can be copied from the way categorizer state is managed.  Categorizer state is like data frame analytics state in that each persist overwrites the previous one.  (Anomaly detector state is different in that each persist is indexed as a separate model snapshot, so the pattern for handling multiple documents cannot be copied from anomaly detector state.)

**Comment by dimitris-athanasiou** [comment]
> Categorizer state is like data frame analytics state in that each persist overwrites the previous one.

For this to work for data frame analytics we have to be certain that the newer state can never be less documents than a prior state. Is that a correct assumption @tveasey ?

**Comment by tveasey** [comment]
As discussed offline, we can't guaranty that the state grows monotonically during training.

**Comment by droberts195** [comment]
> For this to work for data frame analytics we have to be certain that the newer state can never be less documents than a prior state.

This isn’t true. The last document ends with `”eos”: true` and the C++ stops reading after this. That functionality was added in the Prelert days for this exact case of the number of state documents going down. The extra document will still exist in the index, but won’t be decompressed by the C++.

We might need to change the C++ to read and discard everything after the `”eos”: true` to avoid blocking the Java thread (if that’s not done already). In the Prelert days the documents were pulled from the C++ rather than pushed from the Java, so the C++ just wouldn’t pull the leftover document.
