### ISSUE TITLE
ILM: revise and enhance error handling in the ILM loop

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#52485]
We iteratively trigger the ILM policies by parsing the ILM cluster state for every index that has a policy attached (as indicated by the `index.lifecycle.name` setting).
We addressed a scenario where the trigger of polices was suspended when a policy for an index encountered an error while trying to trigger in [#49128
](https://github.com/elastic/elasticsearch/pull/49128) but there might be an opportunity to widen the scope of the try/catch block we added to include the initial cluster state parsing.

As a side note, it'd be interesting to try and devise a testing framework that'd wreak havoc during the policy execution (skip some policy steps, wipe out some/all of the cluster state we hold for the ilm execution state for example) and make sure ILM continues running for the indexes that have a healthy state.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.

We have, however, made some progress in separate issues around this, so I don't think this is necessary any more.
