### ISSUE TITLE
Index exists API with wildcard returns true even when no index exists

### ISSUE THREAD

**Issue by cdalexndr** [elastic/elasticsearch#52534]
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 7.6.0, Build: default/docker/7f634e9f44834fbc12724506cc1da681b0c3b1e3/2020-02-06T00:09:00.449973Z, JVM: 13.0.2

**Plugins installed**: []

**OS version** (`uname -a` if on a Unix-like system):
Linux 406d050fe126 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

Checking if index exists with `HEAD /twitter-*` returns `200 - OK` when no index exists.

**Steps to reproduce**:

 1. No index exists.
 2. `HEAD /twitter-*`

**Comment by cdalexndr** [comment]
After more playing around, it seems that adding `?allow_no_indices=false` query param does what I need.

In [Index exists API docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-exists.html), there is no default value for `allow_no_indices`, so it's not clear what is the default behavior when calling without this param.

Even more, from the current doc info:
`(Optional, boolean) If true, the request does not return an error if a wildcard expression or _all value retrieves only missing or closed indices. `
one can imply that the default value is `false` because it only says the behavior when it is set to `true` (adding an optional param should change the default behavior), but actually it's default value is `true`.

**Comment by matriv** [comment]
The default value of `allow_no_indices` is clarified in the docs with #52635.

Imho though, the current behaviour of `HEAD /<index-pattern>` seems weird, since a `200` status is returned even if no index is matched (since `allow_no_indices` is by default `true` for this API) and differs from the behaviour of the `HEAD /<index-pattern>/_alias/<alias>` API which returns `404` if no index is found. To clarify the alias exists API still considers `allow_no_indices` with default value `true`, but when no aliases are found (since no indices are found) returns `404`.

**Comment by matriv** [comment]
After discussion, we decided to keep the behaviour as is.

The strong arugment is that it keeps a consistent behaviour with the [`GET /<index>`](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-index.html)
and moreover the documentation has already been updated so that [the default value of `allow_no_indices` is described](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-exists.html#indices-exists-api-query-params).
