### ISSUE TITLE
Support for AWS IAM Kubernetes service account permissions

### ISSUE THREAD

**Issue by ErikvanDuren** [elastic/elasticsearch#52625]
Amazon EKS recently supports IAM permissions for Kubernetes service accounts.

I would be nice to have support for service account permissions implemented in (at least) the S3 repository plugin so it is possible to create snapshots to an S3 repository without having to update  access keys and tokens on a regular basis.

**Comment by DaveCTurner** [comment]
I had a quick check and this looks to be implemented by the `WebIdentityTokenCredentialsProvider` which is in the SDK version we're already using. The tricky bit will be to construct a test fixture that sets up an environment similar enough to EKS to show that it does integrate properly.

**Comment by chonton** [comment]
What are the security concerns with using system properties, environment variables, or profiles to store credentials?  A web search reveals many opinions both for and against each method.  Should Elastic be enforcing a particular security policy or should Elastic make deployers aware of the pros/cons of each method?

In Kubernetes, mapped files holding the credentials seems to be one of the recommended practices at this time.  (Profile method)

**Comment by chonton** [comment]
Elasticsearch team please chime in on which methods will be acceptable.

**Comment by jim-barber-he** [comment]
For this to work this file needs changing: https://github.com/elastic/elasticsearch/blob/master/distribution/src/bin/elasticsearch-env-from-file

When I try to use IAM Roles for Service accounts it currently errors with:
```
ERROR: File ..data/token (target of symlink /var/run/secrets/eks.amazonaws.com/serviceaccount/token from AWS_WEB_IDENTITY_TOKEN_FILE) must have file permissions 400 or 600, but actually has: 640
```
The token gets created with the following permissions:
```
$ ls -l /var/run/secrets/eks.amazonaws.com/serviceaccount/..data/token
-rw-r----- 1 root 1001 1001 May 21 23:49 /var/run/secrets/eks.amazonaws.com/serviceaccount/..data/token
```
By default this file has permission 600 and owned by root:root, but when this is set:
```
podSecurityContext:
  fsGroup: 1001
  runAsUser: 1001
```
Then the group ownership of the token is changed to match `fsGroup` and the group read bit set so that the token can be read.
Without that change, the token wouldn't be readable, so the hard check for permission 400 or 600 enforced in the `elasticsearch-env-from-file` script isn't suitable for this case.

**Comment by jim-barber-he** [comment]
The `distribution/src/bin/elasticsearch-env-from-file` file was fixed for version 7.6.1 of ElasticSearch and so that is no longer a blocker.
I've been able to get ElasticSearch to work with IAM Roles for Service Accounts.
Once version 7.8.1 or later of the Helm chart is released, then it'll contain my changes to allow the needed ServiceAccount annotations to be applied.
In the meantime you can create your own ServiceAccount with the appropriate annotations and configure ElasticSearch to use that one instead via `rbac.serviceAccountName` and making sure `rbac.create: false` is used.

**Comment by hamishforbes** [comment]
Has there been any progress on this issue?
I've not been able to get Elasticsearch 7.9.2 to use EKS IAM roles for S3 snaps even though the pod is correctly authenticated.

I'd very much like to not have to inject static credentials as this would be a step backwards from my current non-k8s deployment.
So far elasticsearch seems to be the only application i've found that doesn't correctly support web identities for AWS

What's the reasoning behind not just using the default AWS SDK credential chain here?

**Comment by fculpo** [comment]
Hi,

ES is also one of the last application in our infrastructure not being able to use EKS IRSA (OIDC).

ES does not tries to read EKS IRSA token mounted in the pods:

ServiceAccount has the following annotation:
```
Annotations:   eks.amazonaws.com/role-arn: arn:aws:iam::xxx:role/ekssa-es-snapshots
```

Which results in these env vars to be mounted in the pods:
```
Environment:                                                                                                                
AWS_ROLE_ARN: arn:aws:iam::xxx:role/ekssa-es-snapshots
AWS_WEB_IDENTITY_TOKEN_FILE:  /var/run/secrets/eks.amazonaws.com/serviceaccount/token
```

But ES keeps trying to use EC2 Metadata:
```
curl -X PUT -H 'Content-Type: application/json' "localhost:9200/_snapshot/s3_backup_bucket/backup-1" -d '{
    "include_global_state": true,
    "include_aliases": true
  }'
{"error":{"root_cause":[{"type":"repository_exception","reason":"[s3_backup_bucket] could not read repository data from index blob"}],"type":"repository_exception","reason":"[s3_backup_bucket] could not read repository data from index blob","caused_by":{"type":"i_o_exception","reason":"Exception when listing blobs by prefix [index-]","caused_by":{"type":"sdk_client_exception","reason":"The requested metadata is not found at http://169.254.169.254/latest/meta-data/iam/security-credentials/"}}},"status":500}
```

Any way to make this working ?

**Comment by TheRealDwright** [comment]
For anyone who stumbles upon this, there is a workaround posted [here](https://github.com/elastic/cloud-on-k8s/issues/4225).

First, create a secret containing AWS credentials.
`kubectl create secret generic aws-credentials --from-literal=s3.client.default.access_key=YOUR_ACCESS_KEY --from-literal=s3.client.default.secret_key=YOUR_SECRET_KEY`

Then refer to the secret in the manifest.
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: TheRealDwright-testing
spec:
  version: 7.13.0
  secureSettings:
    - secretName: aws-credentials
  nodeSets:
    - name: default
      count: 1
      podTemplate:
        spec:
        initContainers:
          - name: install-plugins
            command: ["/bin/sh", "-c"]
            args:
              - |
                bin/elasticsearch-plugin install --batch repository-s3```

I hope this saves someone a couple of hours googling and we can merge #65923 soon.

**Comment by Aloshi** [comment]
+1, we just ran into this today :(

**Comment by pedro-brentan** [comment]
@TheRealDwright the question is that it should use the service account, there are a lot of ways using access key and secret key, this isn't a problem at all. But service accounts are way more secure than credentials.

Is there any ETA for this issue?

**Comment by TheRealDwright** [comment]
> @TheRealDwright the question is that it should use the service account, there are a lot of ways using access key and secret key, this isn't a problem at all. But service accounts are way more secure than credentials.
> 
> Is there any ETA for this issue?

I agree and I also would like to use [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) also. I posted this as a _workaround_ as I had assumed (incorrectly) the service account approach would work.

**Comment by andronux** [comment]
🆙 
will it be possible to have the ability to use IRSA in the future?

**Comment by DaveCTurner** [comment]
That's unrelated to this issue @aydasraf, this message is just noise. By default Elasticsearch hides it (see https://github.com/elastic/elasticsearch/pull/56346) but it seems you've adjusted your logging config to show it anyway.

**Comment by xco-sk** [comment]
Are there any plans on backporting the @arteam change to 7.x?

**Comment by hamishforbes** [comment]
So either I'm doing something wrong or the latest changes in 8.0 make this worse.
Posting a comment here as I assume most people who are interested are watching this issue.

My setup still had the role mapping enabled (and therefore the `AWS_WEB_IDENTITY_TOKEN_FILE` env var in the container), with no other changes this causes Elasticsearch to crashloop when upgraded to 8.0.1.
Because the S3 plugin sees the env var, doesn't find a matching symlink and throws an error, rather than just falling back to the existing static creds that have been working for the last x years this issue has been open.

Be aware when upgrading!

I added the symlink as per the doco
```
mkdir -p "/usr/share/elasticsearch/config/repository-s3";
ln -s $AWS_WEB_IDENTITY_TOKEN_FILE "/usr/share/elasticsearch/config/repository-s3/aws-web-identity-token-file"
```
This lets Elasticsearch start correctly with the s3 plugin installed and the env var injected.

Of course if I remove the old secureSettings workaround I still can't access S3 with IAM roles.

**Comment by arteam** [comment]
Hey @hamishforbes. 

There's apparently a bug with Java Security Manager permissions which was introduced in #81255 (the change that added support for web identity tokens). I've submitted #84585 to fix it. In the meantime, could you try running ES with this system property `-Dcom.amazonaws.sdk.stsMetadataServiceEndpointOverride=https://sts.amazonaws.com` as a workaround? This should prevent the AWS SDK from looking up the AWS region implicitly and crashing because it doesn't have file permissions on `config/.aws`.

**Comment by arteam** [comment]
Hi @hamishforbes! 

Thank you very much for the report! It's indeed a bug: Elasticsearch shouldn't crash if the user didn't create a symlink to `AWS_WEB_IDENTITY_TOKEN_FILE` and should fallback to the static credentials in that case. It was fixed in #84697 which will be shipped in 8.0.2, 8.1.1 and 8.2.0.

**Comment by hamishforbes** [comment]
Ok after *much* banging of heads against walls I think i've made this work

You **must** manually set an additional env var that is *not* set by the [EKS / IAM integration automatically](https://github.com/aws/amazon-eks-pod-identity-webhook/blob/0d254eee1537e0745679252ca60f020fa1a461f0/pkg/handler/handler.go#L136)
The s3 repository code requires `AWS_ROLE_SESSION_NAME` to be set in addition to the automatic `AWS_WEB_IDENTITY_TOKEN_FILE` and `AWS_ROLE_ARN` env vars.

The session name is not required by the SDK normally, it just makes up a [default value](https://github.com/aws/aws-sdk-java/blob/7fb97fabc5b1258473751d725b62a5c391e6034d/aws-java-sdk-core/src/main/java/com/amazonaws/auth/WebIdentityTokenCredentialsProvider.java#L49).
Not so the elastic [S3 plugin](https://github.com/elastic/elasticsearch/blob/v8.1.3/modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Service.java#L319) 

Depending on how you look at it, there's either a key piece of information missing from the documentation or this is just the incorrect implementation.
IMO the s3 plugin should mirror the default SDK behaviour as closely as possible and generate a default session name

@arteam thoughts?

**Comment by jerryguowei** [comment]
It's surprising that this feature is not backport to 7.17. 😞
