### ISSUE TITLE
Support for alias health

### ISSUE THREAD

**Issue by Bukhtawar** [elastic/elasticsearch#52644]
For log analytics datasets there are use cases where only the index pointed to by the read and write alias are of paramount importance and it may make sense to track their health separately. Older indices going RED can mean there is a possibility it can be restored from a back up and may not reflect a state where writes are failing or reads are returning partial data if using alias. 

Another column in `_cat/aliases` with optional health might be helpful

**Comment by jasontedor** [comment]
We discussed this in our team discussion meeting. We do not think that we should add this information to an Elasticsearch API, new or existing. We think it's an unusual concept to measure the health of an alias in this way, on the basis of the read/write index. In general, we think it's unusual to measure the health on the basis of write indices only, because any availability issue should be considered a health issue for the cluster as it can signal that data is missing for searches, or that there is potential for data loss. While we do not want to add an API for this, you can use primitives that exist in Elasticsearch to compute this information from existing APIs (get the alias, extract the write index, get the health of the write index).
