### ISSUE TITLE
ShardLockObtainFailedException debugging on 6.8, and backport?

### ISSUE THREAD

**Issue by henryptung** [elastic/elasticsearch#52657]
We're running into `ShardLockObtainFailedException` errors in the wild running 6.8, of unclear origin; a review of past tickets seems to indicate multiple possible causes for this. We have some custom internal plugins, which may certainly be related to a cause in some way, but it's just difficult to tell what the nature of the lock contention is without the ability to reproduce in a test environment, and difficult to distinguish different failure modes from each other.

Came across https://github.com/elastic/elasticsearch/pull/38807, which seems to be a great tool for diagnosing such errors (by recording/reporting previous locker). Would it be possible to backport that to the 6.8 branch, help out with diagnosing these errors?

**Comment by dakrone** [comment]
Hi @henryptung, I did the orginal work, and at this time we aren't considering backporting it. This change would have to be rewritten for the 6.x code, since there were drastic changes between the two branches. Additionally, it doesn't actually fix any bugs, so it doesn't meet our criteria for backporting.

I'm going to close this for now, but feel free to comment and we can always re-open it.
