### ISSUE TITLE
[CI] MlBasicMultiNodeIT.testMiniFarequoteWithDatafeeder failed to delete job

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#52695]
`MlBasicMultiNodeIT.testMiniFarequoteWithDatafeeder` failed on the 6.8 branch in https://gradle-enterprise.elastic.co/s/oqx2watqao2ba

The error was:

```
> Throwable #1: org.elasticsearch.client.ResponseException: method [DELETE], host [http://[::1]:44455], URI [/_xpack/ml/anomaly_detectors/mini-farequote-with-data-feeder-job], status line [HTTP/1.1 409 Conflict]	
> {"error":{"root_cause":[{"type":"status_exception","reason":"Cannot delete job [mini-farequote-with-data-feeder-job] because datafeed [bar] refers to it"}],"type":"status_exception","reason":"Cannot delete job [mini-farequote-with-data-feeder-job] because datafeed [bar] refers to it"},"status":409}	
   > 	at __randomizedtesting.SeedInfo.seed([21E321799CFFA4C2:F8ED82516658D8AA]:0)	
   > 	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:936)	
   > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:233)	
   > 	at org.elasticsearch.xpack.ml.integration.MlBasicMultiNodeIT.testMiniFarequoteWithDatafeeder(MlBasicMultiNodeIT.java:166)	
   > 	at java.lang.Thread.run(Thread.java:748)	
   > Caused by: org.elasticsearch.client.ResponseException: method [DELETE], host [http://[::1]:44455], URI [/_xpack/ml/anomaly_detectors/mini-farequote-with-data-feeder-job], status line [HTTP/1.1 409 Conflict]	
   > {"error":{"root_cause":[{"type":"status_exception","reason":"Cannot delete job [mini-farequote-with-data-feeder-job] because datafeed [bar] refers to it"}],"type":"status_exception","reason":"Cannot delete job [mini-farequote-with-data-feeder-job] because datafeed [bar] refers to it"},"status":409}	
   > 	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:552)	
   > 	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:537)	
   > 	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)	
   > 	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)	
   > 	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)	
   > 	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)	
   > 	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)	
   > 	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)	
   > 	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)	
   > 	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)	
   > 	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)	
   > 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)	
   > 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)	
   > 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)	
   > 	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)	
   > 	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)	
   > 	... 1 more
```

The code around line 166 on the 6.8 branch is https://github.com/elastic/elasticsearch/blob/f3cbeeab33fb7041adfd132380ea8e5e54eb49c7/x-pack/plugin/ml/qa/basic-multi-node/src/test/java/org/elasticsearch/xpack/ml/integration/MlBasicMultiNodeIT.java#L165-L166

There were no errors from line 165.  Therefore the implication is that there is a window of opportunity after a delete_datafeed request returns where subsequent calls think the datafeed still exists.  This is bad - delete_datafeed should not return a success response until all its side effects have been made visible.

**Comment by benwtrent** [comment]
This has not happened since Feb 25: [buid-stats](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-5y,mode:quick,to:now))&_a=(columns:!(build.branch),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:b646ed00-7efc-11e8-bf69-63c8ef516157,key:build.project,negate:!f,params:(query:elasticsearch,type:phrase),type:phrase,value:elasticsearch),query:(match:(build.project:(query:elasticsearch,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:e58bf320-7efd-11e8-bf69-63c8ef516157,key:branch,negate:!t,params:!(pull-request,pull-request-1,pull-request-2,pull-request-bwc),type:phrases,value:'pull-request,%20pull-request-1,%20pull-request-2,%20pull-request-bwc'),query:(bool:(minimum_should_match:1,should:!((match_phrase:(branch:pull-request)),(match_phrase:(branch:pull-request-1)),(match_phrase:(branch:pull-request-2)),(match_phrase:(branch:pull-request-bwc))))))),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testMiniFarequoteWithDatafeeder),sort:!(time,desc)))

Looking at all the commits between then and now, I cannot draw a line directly between the test not failing again since that date. 

Looking at the code, it seems to me that this could only happen if:

- A datafeed is in the cluster state AND the index. In this case we only delete from the cluster state. Then the job stills sees it in the index. 
- There was some internal bug in ES that got fixed somewhere along the line. 

I vote to close this issue since it has not failed since.
