### ISSUE TITLE
EQL: Add IN functionality

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#52939]
With #52870 merged, this functionality should be enabled in EQL as well, at grammar level (parsing) and execution phase.

**Comment by rw-access** [comment]
Specifically, this issue is referring to using the `In` QL nodes, instead of compiling `In` down to an Or of `Equals` which is done now:
https://github.com/elastic/elasticsearch/blob/a462700f9c8e1fb977d62d42eb0077403b8fa98b/x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/parser/ExpressionBuilder.java#L141-L147

**Comment by costin** [comment]
See https://github.com/elastic/elasticsearch/issues/53482
