### ISSUE TITLE
ILM and unallocated shards

### ISSUE THREAD

**Issue by sherry-ger** [elastic/elasticsearch#53209]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.6

**Plugins installed**: []

**JVM version** (`java -version`):
1.8

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

I am uncertain this is a bug as per documentation ES did just that.  Also, the ES cluster configs don't follow best practice.

 1. Create an ES cluster in elastic cloud with 1 node in 1 hot zone and 1 node in 1 warm zone
 2. Use filebeat to ingest some data with default shard settings (1 primary shard + 1 replica)
 3. when the index is first created, the cluster will become yellow as there is no where to allocate the replica shard
4. change the ilm policy on the filebeat index to have 1 day hot and 1 day warm without specifying how many replica shard the index should have when it moves to the warm phase. (it defaults to 1 replica as it was from the filebeat index template.)
4. when the index is aged out of the hot node, the primary shard is moved to the warm node
5. it appears the replica shard is created on the hot node but it does not show up on `_cat/shards` nor as a part of index store size even though there are files or footprint of the replica shard on disk. the cluster remains in the yellow state.

The problem is the replica shard files quietly take up disc space.  (We discovered this as the hot node ran out of disk space.) Is this the desirable behavior? Should es raise an error?

**Comment by DaveCTurner** [comment]
This is a consequence of Elasticsearch refusing to delete copies of shards that are not fully replicated. Deleting shard copies is a risky business and requires caution when there are fewer copies of the data than needed. The default is to have 2 copies (one primary and one replica) which is the minimum required for any kind of resilience; a 1-hot-1-warm cluster doesn't support even this minimal level of replication so should only be used where reliability is not needed.

Elasticsearch today uses the following mechanisms to encourage you to address the orphaned  files before the consequences become too severe:

- it immediately reports that there is an allocation problem via its `yellow` health. It is a good idea  to take action whenever the cluster health is not `green`, since there are a number of things that Elasticsearch can only safely clean up in a fully healthy cluster.

- it exposes statistics showing the real disk usage, which includes any files belonging to replicas that are not currently allocated.

- it emits log messages when disk space starts to get uncomfortably tight. These messages start out mild, but if not addressed then they eventually rise to a warning every 60 seconds indicating that problems are imminent.

- if the disk space problem is still not addressed after all this feedback then as a last resort it has  no choice but to start to reject indexing of new documents.

In the case you describe, the `yellow` cluster health should tell you that there are things that need addressing in your cluster long before disk space becomes a concern.

I don't think that the consequences of a long-term non-`green` cluster is officially documented anywhere. @elastic/docs what do you think would be a good way to document that?

**Comment by debadair** [comment]
I think there should be mention of this in the context of ILM, but also should be documented more generally in the context of cluster formation and resiliency. I can add the reference in the ILM context as part of #53894, and create a more general topic to cross reference.
