### ISSUE TITLE
low disk watermark [85%] exceeded - wrong count?

### ISSUE THREAD

**Issue by nk111** [elastic/elasticsearch#53233]
**Elasticsearch version** (`bin/elasticsearch --version`):
6.8.0
**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):
Windows Server 2016
**Description of the problem including expected versus actual behavior**:

We are running a sonarqube 7.9.1 instance inside an azure app service. In the elastic search log we see this warning:

2020.03.06 05:11:32 INFO  es[][o.e.c.r.a.DiskThresholdMonitor] low disk watermark [85%] exceeded on [mOZe_6AITSK9KsY6VMg76g][sonarqube][D:\home\site\wwwroot\sonarqube-7.9.1\data\es6\nodes\0] free: 3.4gb[10.8%], replicas will not be assigned to this node

Problem is that 3.4gb is NOT the free disk space at that directory level but on the disk root. We have about 50gb free at the application dir.

So D:\ is a system drive of the app service instance and D:\home is our user space.

Note the screenshots for exact numbers.

![free_d_home](https://user-images.githubusercontent.com/155322/76100837-acc8da00-5fcd-11ea-8cfc-655fdf2f39ca.png)

![free_d](https://user-images.githubusercontent.com/155322/76100855-b9e5c900-5fcd-11ea-9636-204d823291db.png)

I'm not sure if this is a bug or if there is setting where we could tell the monitor where to check free disk space?

**Comment by DaveCTurner** [comment]
@nk111 that's surprising indeed. What does `GET _nodes/stats/fs` return?

As far as I can see Elasticsearch is asking the JDK to tell us the free space for the filesystem  containing `D:\home\site\wwwroot\sonarqube-7.9.1\data\es6\nodes\0`, and the version of the JDK I checked does seem to pass that request verbatim along to the OS. What JDK are you using?

Note that 3,902,238,270 free bytes would be rendered as `3.6gb` not `3.4gb` so I wonder if these numbers are actually unrelated. You've shared the free space at `D:\home` but could you check at `D:\home\site\wwwroot\sonarqube-7.9.1\data\es6\nodes\0`?

**Comment by nk111** [comment]
i must confess i'm a total java noob...

java.home | D:\Program Files\Java\zulu11.29.3-jre11.0.2-win_x64
-- | --

How would i call the api for _nodes/stats/fs? Is there any default port?

The 3.4gb was not the most recent warning line from the log. Atm we are at 3.5gb in the warning and 3,849,793,536 bytes free at drive d. Does that fit?

**Comment by nk111** [comment]
oh and for everything below D:\home
like
D:\home\site\wwwroot\sonarqube-7.9.1\data\es6\nodes\0
i get 11,380,551,680 bytes free 

confusing

**Comment by DaveCTurner** [comment]
How do you normally interact with Elasticsearch @nk111? If you're using Kibana, then you should just be able to type `GET _nodes/stats/fs` into the [dev console](https://www.elastic.co/guide/en/kibana/current/console-kibana.html). Other HTTP clients will also work. By default it listens on `localhost` port 9200, so http://localhost:9200/_nodes/stats/fs is the default URL for these stats, but there's lots of things you can't do in a browser so I recommend setting up a client like Kibana.

I'm relabelling this as a stats issue, although as I say I can't see anything that would cause us to see disk stats for the root directory. I traced this down through the JDK to a call to [`GetVolumePathNameW`](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getvolumepathnamew) to get the filesystem root directory of `D:\home\site\wwwroot\sonarqube-7.9.1\data\es6\nodes\0` which should be returning `D:\home\` in your setup. Maybe it's not. I'm going to leave this for someone with more Windows expertise than me to take further.

**Comment by nk111** [comment]
I'm not interacting directly with elasticsearch at all @DaveCTurner . It's part of an application called sonarqube. So i guess i don't have the possibility to make api calls directly.

**Comment by DaveCTurner** [comment]
I think Sonarqube incorporates a fairly standard Elasticsearch installation, so you should be able to access its HTTP API directly. I would be amazed if not, because it's really quite hard to debug problems like this without it. Maybe you can talk to Elasticsearch via some advanced options in the Sonarqube UI?

At startup, Elasticsearch should be logging a line like this one indicating where the HTTP API is bound:

```
[2020-03-07T17:26:28,869][INFO ][o.e.h.AbstractHttpServerTransport] [BUBBLES] publish_address {127.0.0.1:9200}, bound_addresses {127.0.0.1:9200}, {[::1]:9200}
```

It should also log something like this, normally the very first `INFO` log line at startup:

```
[2020-03-07T17:25:38,375][INFO ][o.e.e.NodeEnvironment    ] [BUBBLES] using [1] data paths, mounts [[Removable Disk (C:\Users\David\Desktop\elasticsearch-7.6.1\data)]], net usable_space [93.2mb], net total_space [104.9mb], types [NTFS]
```

Can you share that?

**Comment by nk111** [comment]
i see this:
<pre>
2020.03.09 08:07:24 INFO  es[][o.e.e.NodeEnvironment] using [1] data paths, mounts [[Windows(D:)]], net usable_space [3.2gb], net total_space [31.6gb], types [NTFS]
</pre>

**Comment by nk111** [comment]
A little bit later i see that that the config path is changed via startup parameter. This config file seems to be generated dynamically by sonarqube and it contains the data path
<pre>
path.data: D:\home\site\wwwroot\sonarqube-7.9.1\data\es6
</pre>
Could it be that the directory info is being read at the very startup and not changed when we set the data path later?

**Comment by DaveCTurner** [comment]
> A little bit later i see that that the config path is changed via startup parameter.

What _exactly_ do you see to suggest that? The data path is determined at startup and cannot be changed later, so I think you are misinterpreting what you're seeing.

> `mounts [[Windows(D:)]]`

Good, that is at least consistent with the issue you're reporting, although it doesn't explain why the OS is telling us the wrong filesystem root. Please continue to try and work out how to run `GET /_nodes/stats/fs` on your installation, maybe by calling on some Sonarqube expertise.

**Comment by seantomlins** [comment]
We're in the same boat as you @nk111

Are you per chance deploying as an app service from this template? https://github.com/vanderby/SonarQube-AzureAppService/issues/35

And, are you using a shared app service plan too?

We suspect it's because we're using a shared app service plan S2 but after searching around it seems that dedicated plans like B1 are required.

Btw @DaveCTurner the elasticsearch rest api is definitely running but it is firewalled off by default

**Comment by DaveCTurner** [comment]
Thanks for the link @seantomlins, yes, that looks similar to this issue in that Windows is telling Elasticsearch that the filesystem root is `D:` rather than wherever it really is and this is throwing all its free space calculations off. I don't think there's any action we can take in Elasticsearch to deal with this differently so I am closing this. It may help to report this to the Azure folks since it sounds like it depends on your Azure configuration; if they need more technical details then we can provide them.

**Comment by vanderby** [comment]
I added a work around for this in https://github.com/vanderby/SonarQube-AzureAppService/issues/40#issuecomment-624414812 that is mentioned above.

You need to enable ES http port through a SonarQube setting, then using the Azure Web App's Kudu PowerShell debugging window invoke web requests to disable disk allocation threshold checks for ES.

**Comment by zaheershk26** [comment]
**Failed tasks during reindexing**

During Elasticsearch reindexing due to disaster recovery or an upgrade, you may have a failed tasks in your branches or Pull Requests. If you only have a few failed tasks, you can reanalyze your branch or Pull Request. You may want to use web services to remove branches and Pull Requests that can't be reanalyzed because they have been removed from version control. If you have many failed tasks, you may want to delete your Elasticsearch directory and reindex again. To delete your Elasticsearch directory:

- Stop SonarQube
- Delete the data/es7 directory
- Restart SonarQube
