### ISSUE TITLE
SQL: introduce WEEK interval

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#53282]
INTERVALs in SQL do not have a notion of a week period. While there is support for `year`, `month`, `day` it is useful to specify an interval of one WEEK, rather than `7 DAYS`.

The introduction of `WEEK` will also help with scenarios similar to https://github.com/elastic/elasticsearch/issues/40162 and https://github.com/elastic/elasticsearch/issues/52713 where a `calendar_interval` is used. In this specific case, it will be a `date_histogram` using `"calendar_interval" : "1w"`.

**Comment by erickmp07** [comment]
I'd like to try.

**Comment by erickmp07** [comment]
Can I?

**Comment by erickmp07** [comment]
I opened a PR (#59335) that implements this feature.

**Comment by matriv** [comment]
After discussion some more investigation we came up with the following:

- WEEK interval is not supported by standard SQL
- Handling it with java.time is also tricky
- WEEK interval can lead to problematic semantics:
  - Is 7 DAYS interval equivalent of 1 WEEK? (and 14 DAYS 2 WEEKS and so on)
  - When does a WEEK start? Monday? Sunday? Do we have to introduce 2 different intervals? Do we need to add locale in the SQL query params so it's taken from there?

Therefore, since we don't have any substantial demand for this feature, we'll go ahead and close this issue and revisit it in the future if we receive user requests to have it implemented.
