### ISSUE TITLE
filtering on _timestamp field (with custom format) not working

### ISSUE THREAD

**Issue by karol-gwaj** [elastic/elasticsearch#5328]
run the example below:
```
DELETE test

POST test

PUT test/test/_mapping
{
    "test" : 
    {
        "_timestamp" : { "enabled" : true, "store" : true, "format": "yyyyMMddHHmmssSSS"}
    }
}

POST test/test/1?timestamp=20140301101010123
{
    "id" : 1
}

POST test/_search
{
    "fields": [
       "_timestamp"
    ], 
    "query": {
        "range": {
           "_timestamp": {
              "from": 20140301101010000,    
              "to": 20140301101010999
           }
        }
    }
}
```
i wll expect that last query will return created document (as the timestamp falls into specified range)
also after inserting, timestamp on document is not this same as the one specified in the request (it is  in fact **20140301101010124** when it should be **20140301101010123**)

context:
- es: 1.0.0
- jvm: 1.7.0_51
- hosted in EC2

**Comment by rjernst** [comment]
As Igor said before, part of the problem is date fields have this dual behavior, where it can accept a formatted date, but also an epoch timestamp. However, in this case, the value being searched is passed as a json number. The only way we could interpret that with the original supplied format would be to write the number as a string and then try to parse. I don't think we should do this.

We could however make a couple improvements:
* Add a flag to disable interpreting as an epoch time
* Throw an error if a number is passed in when this feature is disabled

**Comment by clintongormley** [comment]
Another possibility would be to add `epoch` as a format, then users can control the order in which the epoch format is tried, eg:

     "format": "epoch|YYYY-mm-dd"

vs

     "format": "YYYY-mm-dd|epoch"

**Comment by rjernst** [comment]
@clintongormley I really like that idea! I think we should do that, and change the docs to describe the default format to match the current behavior? Should we have a way to specify whether it is seconds or milliseconds epoch? We currently use the first example you gave, with milliseconds epoch.

**Comment by clintongormley** [comment]
@rjernst yes, i think supporting epoch seconds would be an excellent idea, eg Perl uses floating point seconds.  So perhaps `epoch_seconds` and `epoch_ms`?
