### ISSUE TITLE
Add shard data to _nodes/stats, _nodes/_local/stats, and _stats endpoints

### ISSUE THREAD

**Issue by chrisronline** [elastic/elasticsearch#53308]
The `_nodes/_local/stats`, `_nodes/stats`, and `_stats` API endpoints do not return any information about shards, specifically shards that live on either the node or compose an index. Shard data is exposed by the `_cluster/state/routing_table` API endpoint.

I'm proposing we modify the above mentioned `stats` endpoints to include the shard data as well. I don't have an opinion on where the data should live in the structure, but it needs to include the following fields (which can all be found in the `_cluster/state/routing_table` response):
```
{
  'index': <number>,
  'state': <string>,
  'primary': <boolean>
}
```

For the `_stats` endpoint, it should also include some simple aggregations as well, specifically `shards.total` and `shards.totalUnassigned` (where `unassigned` is any shard that is `state: "UNASSIGNED"` or `state: "INITIALIZING"`).

This change will alleviate some issues on the Stack Monitoring UI in Kibana with the queries we need to execute to show the shard data alongside the node or index data.

This will be a breaking change so 8.0 is the goal of this work.

**Comment by jakelandis** [comment]
@chrisronline 

We discussed this in person today.  We currently have `GET _nodes/stats?level=shards` however, it has a lot more information then you are requesting and am unsure of the cost of repeated calls for monitoring or if the format is amendable to what you need. 

There was also a question raised if metricbeat could do the combining of data from two different sources. e.g. could the beat call 2 end points and combine them as needed before sending up for indexing ?

> This change will alleviate some issues on the Stack Monitoring UI in Kibana with the queries we need to execute to show the shard data alongside the node or index data.

Can you expand on the motivations here abit ?  

cc: @ycombinator

**Comment by chrisronline** [comment]
@jakelandis I wasn't aware of that api, but yes that will work for the `_nodes/*` endpoints, but what about for the `_stats` endpoint?

To better explain the end goal here, we want to change the data inside of `.monitoring-es-*` monitoring indices. We want to deprecate `type: "shards"` from this index, and put that same data into `type: 'node_stats'` and `type: 'index_stats`. 

We currently have two GA collection paths for monitoring data, internal and Metricbeat. We are deprecating internal, but it's likely we still support it throughout 8.x so we need to think of the changes above working for both collection paths.

I don't know the specifics of how ES does this work for internal collection, but Metricbeat calls two different api endpoints to collect ES monitoring data: `_nodes/_local/stats` and `_stats` (for node and index data respectively). If we want to achieve the above goal, we'd need to go down one of two paths:

1. Ensure the ES apis return all necessary shard data
2. Make multiple calls from Metricbeat to collect for node/index data and shard data.

The issue with the latter is that the two calls would be done at slightly different times, and the resulting data may potentially be out of sync. The other issue is the code that does the merge needs to be identical between ES and Metricbeat which leads to potential issues down the road if one changes and not the other.

I'm not against either approach, but the first one seems like the better long-term solution.

**Comment by jasontedor** [comment]
>To better explain the end goal here, we want to change the data inside of `.monitoring-es-*` monitoring indices. We want to deprecate `type: "shards"` from this index, and put that same data into `type: 'node_stats'` and `type: 'index_stats`. 

For me, this is where the disconnect is. Shards are...shards. Nodes are...nodes. They are distinct first-class citizens in the system, whose characteristics we want to monitor. They deserve a separate representation in monitoring.

**Comment by jakelandis** [comment]
I believe the motivation for the which data is persisted via monitoring is almost solely driven by the requirements of the Kibana UI monitoring application. i.e. Our data persistence requirements are that which best serve the Kibana monitoring app. In that context, I am not sure if I agree that shards deserve separate representation in monitoring, rather they deserve representation that best suites the Kibana app's requirements.

With respect to the node stats api, we currently expose  `attributes, indices, os, process, jvm, thread_pool, fs, transport, http, breakers, script, discovery, ingest, adaptive_selection` as top level stats, and additional indices stats (including shards) with additional parameters. Arguably not all of these concepts are node specific, and also arguably which shards are on a node is indeed a node stat. 

I believe that there are 3 places where you can source the shard information 

a) _cat/shards - Not an option since we want don't API's calling _cat APIs since they are intended for human consumption
b) cluster state - How it is currently read -  Reading cluster state directly from a beat seems pretty low level, and not sure we have the x-content serialization guarantees there as we do with the stats apis (also requires a separate call) 
c) `_nodes/stats?level=shard` and `_stats?level=shards`  - How it could be read, but provide alot of information per index per shard and unsure how expensive to call this every 10s.

I would like to suggest for us (me) to review how expensive `?level=shards` (+ filter_path) is to call from monitoring, and if need be introduce something like `?level=shards_basic` that only provides the information needed for monitoring. 

thoughts ?

**Comment by chrisronline** [comment]
> They deserve a separate representation in monitoring.

I don't disagree with you, but that's not it is currently setup. Nodes and indices are first-class citizens in the UI, but shards are just accompanying data points. We don't have any sort of "shards" only page in the UI (currently at least).

> _nodes/stats?level=shard and _stats?level=shards - How it could be read, but provide alot of information per index per shard and unsure how expensive to call this every 10s.

I think this will work fine. It's probably okay if Metricbeat needs to do a little manipulation of the data before indexing it into `.monitoring-es-*` documents. The downside is ES will need to this same manipulation internally as well.

> I would like to suggest for us (me) to review how expensive ?level=shards (+ filter_path) is to call from monitoring, and if need be introduce something like ?level=shards_basic that only provides the information needed for monitoring.

That sounds fine. Ensuring these two endpoints contain this shard data will allow us to remove the `type: 'shards'` monitoring documents, which will benefits the monitoring UI.

**Comment by jakelandis** [comment]
related: #53311 
I will still take the todo to examine how expensive these level parameters are to call from monitoring (by default every 10s). However, I think this also warrants a further discussion about APIs that better match what you are looking for and/or dedicated monitoring APIs. I will start another conversation thread on that subject.

**Comment by chrisronline** [comment]
Per an offline chat with @jakelandis, we are going to go in a different direction and will not need this work.
