### ISSUE TITLE
Add index count data to _nodes/stats and _nodes/_local/stats endpoints

### ISSUE THREAD

**Issue by chrisronline** [elastic/elasticsearch#53311]
Related to https://github.com/elastic/elasticsearch/issues/53308

The `_nodes/_local/stats` and `_nodes/stats` endpoints should also include the number of indices that live on the node (or more specifically, how many indices contain shards that live on this node). 

Something like:
```
{
  "indexCount": <number>
}
```

We currently show this figure in the Stack Monitoring UI, but we need to make multiple queries to determine it. If we can return this data from the `stats` endpoints listed above, we could simplify the code, and ensure it is more efficient too.

**Comment by jakelandis** [comment]
We discussed this today much like #53308 this is available via `level=indices` parameter. However, also like #53308, not sure if this should be recommended since it gathers much more information than you desire. 

You can also deduce the index count from `level=shards`.  

```
GET _nodes/stats?level=indices&filter_path=nodes.*.indices.indices
GET _nodes/stats?level=shards&filter_path=nodes.*.indices.shards
```

I will still take the todo to examine how expensive these level parameters are to call from monitoring (by default every 10s). However, I think this also warrants a further discussion about APIs that better match what you are looking for and/or dedicated monitoring APIs. I will start another conversation thread on that subject.

**Comment by chrisronline** [comment]
Per an offline chat with @jakelandis, we are going to go in a different direction and will not need this work.
