### ISSUE TITLE
ILM:  Ability to trigger one-off actions

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#53321]
There are certain situations where users will want to run one-off actions for ILM-managed indices.  

To do this using ILM, it's not that straightforward.  You will have to create a new policy with just the actions desired and make sure that the rest of the lifecycle flow can continue smoothly (i.e. any duplicate actions being run again are not disruptive).  Alternatively, create a new policy, update the policy reference in index settings and use the advanced move step API (with the same caution).

Example 1:

- User have hundreds of indices managed by ILM where they had an ILM policy with no shrink option in place.  Now they want to run shrink against these indices due to oversharding (which are now in cold/completed phase but still have weeks to go before they will enter the delete phase).

It will be nice if there's a way to instruct ILM to simply run shrink (including all the substeps to prepare it for shrink, etc..) against the indices as a one-off action.

Example 2:

- Force merge can be expensive for large indices.  With ILM, you can't tell ES to only trigger force merge during a specific time period for it will always be based on min_age.  

It will be nice if there's a way to instruct ILM to simply run force-merge as a one-off action.

Related: https://github.com/elastic/elasticsearch/issues/37325

**Comment by dakrone** [comment]
We discussed this today, for the first example (shrinking), we are wary of adding an API to expose any sort of ILM execution, rather, the work should go into making a separate API (or enhancing the existing one) to be more friendly in terms of doing what ILM is already doing.

Shrink is really the exception, other ILM operations can be done by simply doing the operation manually (force merging in the second case). For the underlying issue of doing it during a specific period, we already have an issue open for that: https://github.com/elastic/elasticsearch/issues/37325

I'm going to close this issue since we would prefer not to do the first example, and already have an issue open for the second one.
