### ISSUE TITLE
Parse user type hints directly to ValuesSourceTypes

### ISSUE THREAD

**Issue by not-napoleon** [elastic/elasticsearch#53424]
In the current implementation, user type hints (specified via the `value_type` field on aggregations) get parsed leniently through the `ValueType` enum.  The `ValueType` enum doesn't really add anything however, and we immediately turn that input into a `ValuesSourceType`.  Ideally, we should just parse the user's input directly into a `ValuesSourceType`

While just getting parity with the current parsing would be sufficient, ideally we would tie into the `ValuesSourceRegistry` to allow for users hinting VSTs from plugins.

Relates to #42949

**Comment by RobertoMiyoshi** [comment]
@not-napoleon May I try to solve this issue?

**Comment by RobertoMiyoshi** [comment]
#65916

**Comment by not-napoleon** [comment]
@RobertoMiyoshi see my comments on the PR.  There's a surprising amount of complexity in this issue due to our backwards compatibility policies.

**Comment by RobertoMiyoshi** [comment]
Hi Mark, thank you for your review and feedback. In this new approach, I worried about the backwards compatibility policies. The previous mapping of user type hints to the ValuesSourceType was based on a Surjective function, i.e., several of ValueTypes can be mapped to the same ValuesSourceType. In order to maintain compatibility with previous version, the PR #66662 is proposing a new mapping through a Bijection, covering the parsing and output the same json that is currently accepted, and also serializing and deserializing the same bytes.

**Comment by wchaparro** [comment]
Closing as something we're not planning on doing.
