### ISSUE TITLE
Painless: List<Long> is converted to List<Integer>

### ISSUE THREAD

**Issue by dawi** [elastic/elasticsearch#53536]
**Elasticsearch version** (`bin/elasticsearch --version`):
Docker Image: elastic/elasticsearch:7.6.1

**Plugins installed**: []

**JVM version** (`java -version`):
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Darwin mac1192 17.7.0 Darwin Kernel Version 17.7.0: Fri Jul  6 19:54:51 PDT 2018; root:xnu-4570.71.3~2/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:

We are using a script function to order a search result by a given list of ids.
Therefore we have to pass the ids as parameters to the sort script.
Painless converts the List that contains Longs into a List that contains Integers.
Therefore `params.ids.indexOf(id);` in the script below always return `-1`.

```java
private static FunctionScoreQueryBuilder orderByIds(QueryBuilder queryBuilder, List<Long> orderedIds) {

    final Script script = new Script(

        ScriptType.INLINE, "painless",

        "Long id = doc['id'].value;" +

        "int idx = params.ids.indexOf(id);" + // does not work because params.ids contains Integers instead of Longs
        "int count = params.ids.size();" +
        "return idx == -1 ? 0 : count - idx;",

        singletonMap("ids", orderedIds)
    );

    return functionScoreQuery(queryBuilder, scriptFunction(script));
}
```

**Steps to reproduce**:

A minimal snippet to show the issue using `Debug.explain`.

```java
private static FunctionScoreQueryBuilder sortFunctionExample(QueryBuilder queryBuilder) {

    final List<Long> ids = List.of(666L);
    System.out.println(ids.get(0).getClass()); // Long

    final Script script = new Script(
        ScriptType.INLINE, "painless",
        "Debug.explain(params.ids.get(0));" + // Integer
        "return 0;",
        singletonMap("ids", ids)
    );
    // "painless_class":"java.lang.Integer","to_string":"666","java_class":"java.lang.Integer"

    return functionScoreQuery(queryBuilder, scriptFunction(script));
}
```

**Comment by jdconrad** [comment]
I have added an issue to discuss possible solutions for this problem in #53825.

This is similar to https://github.com/elastic/elasticsearch/issues/23763.

I'm pulling the relevant parts from the issue noted above:

The ids as part of the params list is being parsed where the smallest available type starting with int will be applied to the number. That means params.ids ends up being a List of Integers and Longs (note the difference here is they are boxed types since Java forces them to be so as part of a List)

and

In Painless 1L == 1 is a true statement; however, for boxed types this is not the case (and it's not the case in Java either). We are left with few reasonable options here other than to follow the Java model since Painless is built on the JVM and for performance reasons. When indexOf is called on the values List the type is implicitly boxed meaning that int becomes Integer or long becomes Long, and Long(1) == Integer(1) is a false statement, unfortunately.

**Comment by stu-elastic** [comment]
We're gonna explore implementing the JSON parsed values as their own Numeric class and handling the conversions.

Local changes, such as adding a `long` to a parameter list should not convert the entire `List` to `List<Long>`.  Modelling JSON's data type directly is the least surprising path forward.

**Comment by rjernst** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. The situation is unfortunate, but it's ultimately a limitation of Java itself. Perhaps someday that will change when Project Valhalla makes boxed types value types. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
