### ISSUE TITLE
EQL: EqlActionIT improvements

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#53598]
`EqlActionIT` runs multiple queries against an ES instance however:

1. Each test does not use a name but instead posts the actual query run making most, if not all tests, have invalid names thus no individual test can be tested individually.
A solution which would require modifying the toml would be adding names to each individual queries to indicate what they actually try to test.

2. Despite the `@ClusterScope` annotation, the suite creates one cluster per test (and all the setup that comes with it, such as setting up the index and destroying it). This might be caused by the `@ParametersFactory` annotation which trips the test runner.

Since the cause is unclear, so is the solution - if `ParametersFactory` is the cause then trying to figure out how to improve the underlying test runner or use a `@ClassRule` or something similar to keep the cluster around.

**Comment by aleksmaus** [comment]
@costin I didn't add the names because they were not defined in the original spec and I wanted to preserve the original .toml file from the EQL python implementation so it can be just copied over without any additional postprocessing to keep in sync with the python EQL project.
The spec toString is used for the test name, and the individual test can be rerun, for example:
```
./gradlew ':x-pack:plugin:eql:internalClusterTest' --tests "org.elasticsearch.xpack.eql.action.EqlActionIT" -Dtests.method="test {1.test -> query: process where serial_event_id = 1, expected_event_ids: [1]}" -Dtests.seed=845FB787E266FAC2 -Dtests.security.manager=true -Dtests.locale=lv -Dtests.timezone=Africa/Asmara -Dcompiler.java=13
```
I can shorten that by using the just the query or the query/spec hash.
Agree, that it is convenient if you want to type some user friendly name instead.
Let me know if you still prefer to change the original queries file and define the user friendly names instead.

As for the cluster scope it survives in the suite scope fine but the parent classes define after actions that cleans up the data after each test. So need to figure out how to refactor this whole thing or maybe create some custom base initializers to avoid data clean up after each test. 
In general it's not a great idea to hide bunch of junit tests hooks in the base classes imho.

**Comment by aleksmaus** [comment]
After conversation over zoom agreed on moving this to qa rest tests, and improve the naming convention for tests.

**Comment by aleksmaus** [comment]
Closing as done.
