### ISSUE TITLE
CI `:distribution:docker:composeUp` failure

### ISSUE THREAD

**Issue by dliappis** [elastic/elasticsearch#53678]
[Observed on 6.8 with sles-12](https://gradle-enterprise.elastic.co/s/4p4jk6g725fgg) but history shows several similar issues, mostly related to SLES:

- [6.8, Corretto 11](https://gradle-enterprise.elastic.co/s/775phhrowenhs)
- [6.8, SLES-15-SP1](https://gradle-enterprise.elastic.co/s/l5u2uzgxqeb7o)
- [7.6, SLES-12-SP4](https://gradle-enterprise.elastic.co/s/xikbwgugegiw6)
- [7.x - SLES-12-SP4](https://gradle-enterprise.elastic.co/s/ihvns4u2ea274)

Failure is always related to inability to remount dir as readonly:

```

Building elasticsearch-default |  
-- | --
  | Building elasticsearch-oss |  
  | Creating network "f03b5b08539357b2f575668265e33039_docker__default" with the default driver |  
  | Creating f03b5b08539357b2f575668265e33039_docker__elasticsearch-default_1 ... |  
  | Creating f03b5b08539357b2f575668265e33039_docker__elasticsearch-oss_1     ... |  
  | Creating f03b5b08539357b2f575668265e33039_docker__elasticsearch-oss_1     ... error |  
  |   |  
  | ERROR: for f03b5b08539357b2f575668265e33039_docker__elasticsearch-oss_1  Cannot start service elasticsearch-oss: unable to remount dir as readonly: mount tmpfs:/var/lib/docker/containers/23e305b86608738251500317e10a4853fdc59bca0b846d1af78bace78687f535/mounts/secrets, flags: 0x21, data: uid=0,gid=0: device or resource busy |  
  | Creating f03b5b08539357b2f575668265e33039_docker__elasticsearch-default_1 ... done |  
  |   |  
  | ERROR: for elasticsearch-oss  Cannot start service elasticsearch-oss: unable to remount dir as readonly: mount tmpfs:/var/lib/docker/containers/23e305b86608738251500317e10a4853fdc59bca0b846d1af78bace78687f535/mounts/secrets, flags: 0x21, data: uid=0,gid=0: device or resource busy |  
  | Encountered errors while bringing up the project.


```

**Comment by dliappis** [comment]
@mark-vieira Not sure if we should expand the exclusion list introduced in https://github.com/elastic/elasticsearch/pull/52736

**Comment by mark-vieira** [comment]
The 6.8 failures are due to the recent Docker changes not being backported. Doing so would be... involved unfortunately.

The one for later branches are a little odd. We should not have any builds running on SLES 12.4 anymore. The latest images are 12.5, which is in the exclusion list. March 8th was the last failure on a non-6.8 branch so perhaps that has worked its way through the system.

**Comment by rjernst** [comment]
I found 2 cases of this failure back in July, one on 6.8 and one on 7.x. I'm inclined to close this since there doesn't seem to be anything really investigable at this point. @mark-vieira wdyt?

https://gradle-enterprise.elastic.co/s/tq2krsfzdwvuk
https://gradle-enterprise.elastic.co/s/qm2ghr53364vu

**Comment by mark-vieira** [comment]
The second example you show is actually a completely different error. It was just a transient network issue trying to build an image. The 6.8 error is similar to the ones we saw before on certain operating systems, but yeah, I say we close it.
