### ISSUE TITLE
Searcher acquired on transport thread

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#53985]
Today `SearchService#rewriteShardRequest` runs on a transport thread (`Names.SAME`) and calls `Engine#acquireSearcher`. If the engine is a frozen engine then this may involve opening a directory reader, which does a fair amount of IO and therefore should not happen on a transport thread.

**Comment by ywelsch** [comment]
I think this is caused by the changes in https://github.com/elastic/elasticsearch/pull/51708 where we now always rewrite the request, even in later phases. FrozenEngine has special handling for the case where the acquired searcher has source type "can_match", but the searcher acquired here is used for more than just rewriting.

@jimczi How should we fix this?
