### ISSUE TITLE
Term query for _parent doesn't work for grandchild

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#5399]
With a Parent > Child > Grandchild relationship, you can use a `term` query on the `_parent` field to find children with a particular `$parent`, but not grandchildren with parent `$Child`:

    DELETE /myindx

    PUT /myindex
    {
      "mappings": {
        "Parent": {
          "properties": {
            "name": {
              "type": "string",
              "index": "analyzed"
            }
          }
        },
        "Child": {
          "_parent": {
            "type": "Parent"
          },
          "properties": {
            "name": {
              "type": "string",
              "index": "analyzed"
            }
          }
        },
        "GrandChild": {
          "_parent": {
            "type": "Child"
          },
          "properties": {
            "name": {
              "type": "string",
              "index": "analyzed"
            }
          }
        }
      }
    }

    POST /_bulk 
    { "index" : { "_index" : "myindex", "_type" : "Parent", "_id" : "alice" } }
    { "name" : "Alice" }
    { "index" : { "_index" : "myindex", "_type" : "Child", "_id" : "bob", "parent" : "alice" } }
    { "name" : "Bob"}
    { "index" : { "_index" : "myindex", "_type" : "GrandChild", "_id" : "gc1", "parent" : "bob", "routing" : "alice" } }
    { "name" : "grand child 1" }
    { "index" : { "_index" : "myindex", "_type" : "GrandChild", "_id" : "gc2", "parent" : "bob", "routing" : "alice" } }
    { "name" : "grand child 2"}
     
    GET /_search?fields=_parent,_routing

This query works:

    POST /myindex/Child/_search
    {
      "query": {
        "term": {
          "_parent": "alice"
        }
      }
    }

This query doesn't:

    POST /myindex/GrandChild/_search
    {
      "query": {
        "term": {
          "_parent": "bob"
        }
      }
    }

But performing the same lookup with `has_parent` does work:

    POST /myindex/GrandChild/_search
    {
      "query": {
        "has_parent": {
          "parent_type": "Child",
          "query": {
            "filtered": {
              "filter": {
                "term": {
                  "_id": "bob"
                }
              }
            }
          }
        }
      }
    }

**Comment by kaliseo** [comment]
Ohhh !! Thanks a lot for this tip ! It helped me a lot !

**Comment by clintongormley** [comment]
Rethinking this..  The `has_parent` query does the right thing.  I think we should deprecate the use of the `_parent` field for search, unless something has changed in the new parent-child functionality in 2.0? /cc @martijnvg

**Comment by martijnvg** [comment]
Agreed, I think we should remove support to refer to the `_parent` field in the dsl. It allows us to clean things up a bit more (mapping code).

The only reason this field still exists is because the `_parent` lucene field is used in the fetch phase and get api to as source to include the parent id.

The pre 2.x parent/child join impl. relied on this field in the Lucene index, the 2.x parent/child join impl. doesn't use the `_parent` lucene field. The `_parent` mapping creates docvalues field for the join support depending on the name of the parent type.

My idea is (and was) to no longer use the `_parent` Lucene field and solely rely on the doc values fields for the join and retrieving the parent id in the fetch phase. 

I think there are still use cases for being able to return all child docs with a certain parent id, but I think we can create a separate query for it that uses the doc values fields? (instead of just using `_parent` field in queries like we do today)

A while back I started to do this for a bug fix in the `_parent` mapping for one of the 2.0 betas/rcs. Code for relying on doc values join fields for the fetch phase: https://github.com/martijnvg/elasticsearch/commit/26e2e5d95d2b3a3f778a759ed7a7ea2de9b09842#diff-b633d10e30dc0e0a476eb1e1a40736b7R41

And code for a `_parent_id` query to retrieve docs with a certain parent id value:
https://github.com/martijnvg/elasticsearch/commit/26e2e5d95d2b3a3f778a759ed7a7ea2de9b09842#diff-2be3c59879d9d984bd9a33fc42c1c940R32

**Comment by timeu** [comment]
I ran into this issue today when I upgraded from 1.7.3 to 2.1.1. 
I need to fix the queries in my application code. The question if I should switch to the `has_parent`  query or just use the workaround with `"_parent":"type#id"` ? As far as I understand it, the use of `_parent` in a query will be deprecated right ?

**Comment by martijnvg** [comment]
Closing this issue as this has been fixed as part of #16045. From 3.0 there will be a `parent_id` query in the dsl that allows to easily query for child docs that refer to a specific parent id.

**Comment by martijnvg** [comment]
@timeu The workaround you mention will remain to work in all 2.x versions. From 3.0 you should switch to the `parent_id` query instead.
