### ISSUE TITLE
[Feature Request] Prevent unnecessary Indexing

### ISSUE THREAD

**Issue by simlu** [elastic/elasticsearch#54140]
**Feature / Improvement**

Reduce load by not re-indexing documents when only non-indexed fields are modified.

Similar to how `noop` currently works, but instead of a `noop`, this would be a `noindex` update.

**Background**

We have large, nested documents which are expensive to reindex. We want to update meta information for these documents (without reindexing them).

Since separate meta information on a per document level is not supported, our best bet is write the information into fields on the document itself. However even if only fields are changed that are not indexed, the document is reindexed.

Related 
- https://github.com/elastic/elasticsearch/issues/6822
- https://discuss.elastic.co/t/document-level-metadata-noop/222532/8

**Comment by markharwood** [comment]
Hi @simlu,
Thanks for the update. 
That's certainly a nice feature to have but like most things nested docs was a design trade off to make search fast at the expense of more costly updates. In-place updates are not possible in Lucene and the principle of immutable files is central to its design which has given us such a fast search capability.
So in many respects costly nested updates is a known "issue" and one I've tried to document this vs parent/child docs using [this flowchart](https://discuss.elastic.co/t/a-question-on-whether-to-use-a-nested-datatype/208394/4)

If you have a detailed suggestion on how we can make fast search AND cheap updates I can re-open this issue but otherwise I'm afraid I'll have to close this as "working as designed".
