### ISSUE TITLE
cat thread_pool size enum empty string value

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch#54478]
The cat thread_pool rest API spec defines a `"size"` param of type `enum` with possible values:

https://github.com/elastic/elasticsearch/blob/6fcb51dafcd5519937e7169aaec5b499aa88de36/rest-api-spec/src/main/resources/rest-api-spec/api/cat.thread_pool.json#L35-L46

This param is the only example within all the rest API specs with an empty string enum value. An empty string value may require special handling by clients generating source code from the specs, specifically in cases where the client language may represent the possible values as an enum, for example, [the C# (.NET) client](https://github.com/elastic/elasticsearch-net/blob/a0f69f2f93ca446d57926f15af9ba37e053feb85/src/Elasticsearch.Net/Api/Enums.Generated.cs#L290-L305):

```c#
[StringEnum]
public enum Size
{
    [EnumMember(Value = "")]
    Raw,
    [EnumMember(Value = "k")]
    K,
    [EnumMember(Value = "m")]
    M,
    [EnumMember(Value = "g")]
    G,
    [EnumMember(Value = "t")]
    T,
    [EnumMember(Value = "p")]
    P
}
```

[The documentation for size units](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#size-units) doesn't mention empty string, and it _looks_ like the absence of a size unit value returns sizes in their raw, unmultiplied, values.

With the introduction of a json schema in #54252, the empty string enum value fails validation. Of course, the json schema can be changed to accommodate an empty string value, but since it is the only example and _seems_ to operate the same as specifying no size param, I'm opening this issue to discuss whether the empty string value can be removed.

**Comment by jakelandis** [comment]
The schema needs to support "" (empty string) for any "size" parameters since it does actually make a difference [1] vs. the default. However, this particular API does not even need the "size" parameter, since there is nothing that would be impacted by it. So I will remove the "size" from the cat.thread_pool spec. 

Note - All _cat api's accept the "size" param and won't error, but will only get used if the value added to a column has internal type "SizeValue". This API is not backed by any "SizeValue". (The queueSize is close, but it converts to a long before it returned.)

[1]
The default display value for any SizeValue is the human readable version, e.g. 1.3k. The only way to get a "SizeValue" to show the raw form e.g. 1312 in a cat API is to use any empty string (a missing `=` value) in the param. A quick look at the code and we don't actually use this "SizeValue" for any of the cat APIs, so this is probably a moot point once I remove this remove this one.
