### ISSUE TITLE
Elastic Search update by query not reflecting correctly updated number of documents

### ISSUE THREAD

**Issue by HighOnWater** [elastic/elasticsearch#54484]
Java version: 1.8.0_151
ES Version: 7.4
I am running an update by query call using the java rest [client](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/master/java-rest-high-document-update-by-query.html)

This is my code: (extracted only the relevant part and updated some fields in the painless script)

```
UpdateByQueryRequest queryRequest = new UpdateByQueryRequest(indexName);
Script script = new Script(ScriptType.INLINE, "painless", "if (ctx._source.someKey == someVal) {ctx._source.someKey = someOtherVal;}",Collections.emptyMap());
queryRequest.setScript(script);
BulkByScrollResponse bulkResponse = aesClient.updateByQuery(queryRequest, RequestOptions.DEFAULT);
```

The above code works fine, with the relevant documents getting updated. However, whenever I execute the following:
```
long updatedDocs = bulkResponse.getUpdated();
```

The value stored in ```updatedDocs``` doesn't reflect the actual number of documents getting updated. The value stored in it is the number of documents that it processed.

According to the  [documentation](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/master/java-rest-high-document-update-by-query.html#java-rest-high-document-update-by-query-response) it should return the number of documents updated. 

Can this be looked into.
Thanks.

**Comment by swallez** [comment]
The [update by query doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update-by-query.html) states: "Updates documents that match the specified query. If no query is specified, performs an update on every document in the data stream or index".

What happens here is that the request has no query part, so the script is run for every document in the index, unconditionally. Since we do not do a document diff after running the script to know whether it has changed or not, all documents are updated.

The docs have an [example showing a query and a script](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update-by-query.html#docs-update-by-query-api-source).

The corresponding Java code would be:

```java
UpdateByQueryRequest queryRequest = new UpdateByQueryRequest("test")
queryRequest.setQuery(new TermQueryBuilder("foo", someVal));
    
Script script = new Script(ScriptType.INLINE, "painless", "ctx._source.foo = 2;", Collections.emptyMap());
queryRequest.setScript(script);

BulkByScrollResponse bulkResponse = esClient.updateByQuery(queryRequest, RequestOptions.DEFAULT);
```

And then the result of `getUpdated()` will be the number of documents matching the query.

Hope this helps!
