### ISSUE TITLE
When I tried to upsert using UpdateRequest object with type as "UPDATE", I met reject message.

### ISSUE THREAD

**Issue by 9ins** [elastic/elasticsearch#54483]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):
7.5.1

**Plugins installed**: []

**JVM version** (`java -version`):
1.8.0_242

**OS version** (`uname -a` if on a Unix-like system):
Windows 10

**Description of the problem including expected versus actual behavior**:
First of all, I did tried to upsert to Elastic Search with document. So I used org.elasticsearch.action.update.UpdateRequest object to upsert process. 
The code is blow.
>String type = map.remove("<%=UPDATE%>")+"";
>String index = map.remove("<%=INDEX%>")+"";
>String id = map.remove("<%=ID%>")+"";
><%=cid%>_request.add(new org.elasticsearch.action.update.UpdateRequest(index, type, id).doc(map, org.elasticsearch.common.xcontent.XContentType.JSON).docAsUpsert(<%=DOC_AS_UPSERT%>));

The problem is that when I had put the document without index mapping, it was so successfully working but what if index mapping was exist before or created, it put out message 
as "ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=Rejecting mapping update to [test-es1] as the final mapping would have more than 1 type: [_doc, UPDATE]]]" and failed to upsert.

When I had been removing second parameter(type-"UPDATE") of UpdateRequest object, everything was so good working.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:
ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=Rejecting mapping update to [test-es1] as the final mapping would have more than 1 type: [_doc, UPDATE]]]

**Comment by cbuescher** [comment]
Hi @9ins! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and it's more likely this is a question than a bug report. In this case you are trying to put documents with differing types into the same index, which isn't supported any more since 6.x, see https://www.elastic.co/de/blog/removal-of-mapping-types-elasticsearch). I'm closing this as an issue here, but encourage you to ask this question in the forum instead where somebody surely can dig into your specific programming question more deeply. Many thanks.
