### ISSUE TITLE
Error HTTP 504 Gateway timeout

### ISSUE THREAD

**Issue by cb29** [elastic/elasticsearch#54561]
Hello,

Inside a react app, i have several requests to my ES cluster.
These requests use _search and/or _msearch to fetch datas from different index.

My cluster is on ES 7.3.2, CORS are enabled, and have 4GB of memory.

Sometimes, when I load a page with the react app, I get HTTP 504 errors Gateway Timeout and only a part of the react app is rendered. If I reload the page all is ok...strange behavior.

How can I resolve this problem? Do I make a specific setting on my ES cluster? Or do I need to set more memory on my instance?

Thanks.

**Comment by original-brownbear** [comment]
Hi @cb29 

Elasticsearch itself does not return `504` errors. This is a problem with your react application (or some other part of your infrastructure). Maybe it's handling a slow response from ES improperly (that would be my best guess)?

I'm closing here since we limit Github to feature requests and bug reports and this isn't an Elasticsearch issue.
