### ISSUE TITLE
add min_doc_count for cardinality aggregation 

### ISSUE THREAD

**Issue by karussell** [elastic/elasticsearch#54649]
Returning the unique values for an aggregation is nice and works well. Now it would be an improvement to exclude entries that have a too low document count. See [discussion](https://discuss.elastic.co/t/225753).

**Comment by polyfractal** [comment]
Hm interesting.  So I think this would end up needing a change to all metric aggs, not just cardinality.  Today, the only aggregations that support `min_doc_count` are bucketing aggs.  To some degree this is an artifact of history: `min_doc_count` was added so that certain pipeline aggs (like a derivative) would function correctly because "gaps" in buckets start to introduce weird effects.

That said, I don't see why metric aggs couldn't support the property either.  But we'd probably want to implement it universally and not just for cardinality.

I'm going to mark this as team-discuss to see what other folks think.

**Comment by karussell** [comment]
Thanks for the quick update. I'm also open for any suggestion how one could implement this via existing tools like the scripted metric. 

Is this the right approach?
```json
    "vehicle_count": {
      "scripted_metric": {
        "init_script":    "state.vehicles = [:]",
        "map_script":     "if(doc['vrp.vehicle_ids'].size()==0) /*ignore missing values*/return 0; String key = doc['vehicle_id']; if(state.vehicles.containsKey(key)) { state.vehicles[key]++; } else { state.vehicles[key] = 1; }",
        "combine_script": "double vehicles=0; for (v in state.vehicles.values) { if(v.value>10) { vehicles += v.value; } } return vehicles",
        "reduce_script" : "double vehicles=0; for (v in states) { vehicles += v; } return vehicles"
      }
    }
```
I'm currently getting a NPE but if I know that I'm on the right track I'll continue investigating.

**Comment by polyfractal** [comment]
Will reply over at the Discuss thread :+1:

**Comment by thekofimensah** [comment]
Surprized this isn't supported, seems to be a pretty necessary use case!

**Comment by not-napoleon** [comment]
After discussing this, we have decided not to implement it.  Bucket selectors are the correct solution to do this type of operation.  Min doc count is intended to be only a count of matching documents, not a count of unique values.  It would be confusing to have a special case for cardinality.  In general, we favor doing this type of post processing client side when possible.

There's a larger discussion of if we should continue to support `min_doc_count` at all, even for bucketing aggregations (vs. favoring bucket selector and client side filtering).

**Comment by BrandNewLifeJackie26** [comment]
Should we also close #61591 if we are not going to implement this? If it's still worth working on, please let me know, thanks! @not-napoleon
