### ISSUE TITLE
_update_by_query sometimes not effect

### ISSUE THREAD

**Issue by bigshans** [elastic/elasticsearch#54781]
**Elasticsearch version** (`bin/elasticsearch --version`):7.6.1

**Plugins installed**: [ik]

**JVM version** (`java -version`):1.8.0_242

**OS version** (`uname -a` if on a Unix-like system): Debian 9

I met a stange thing, that `_update_by_query` sometimes fails to update but return sucess. There is no problem with a single request but there is a problem online. I suspected that it was a multi-process problem, but adding process locks did not solve the problem. I asked the community for help, but it didn't respond, so I asked for help here. Can you tell me why not update and how to make it update?

**Comment by cbuescher** [comment]
> I asked the community for help, but it didn't respond, so I asked for help here.

Hi @bigshans! Unfortunately that is exactly the right way to ask this kind of more general usage questions. This question is initially better suited to the support forums over at https://discuss.elastic.co since we want to keep using Github issues only for bug reports and feature requests only.

Reading your description above I think you might want to try adding a little more detail to you question like what your exact update request looks like, what your use-case is, maybe some index settings and mapping that apply to the field that are being updated and the way you issue these updates. All this will allow anybody reading your question to easier see if they know the answer or even to start digging further.

Hope this helps, I'm closing this issue here for above reasons, but encourage you to ask this question in the forum again.
