### ISSUE TITLE
[Transform] add throttling based on configuration parameter

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#54862]
Running transform can increase load on the cluster. Especially in _batch_ mode and for the _first checkpoint_ of a continuous transform this can have bad side effects on the cluster.

Transform should support throttling similar to [reindex](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html#docs-reindex-throttle). Throttling is configured _in reindex_ with the setting `requests_per_second`.

Because transform works as a reducer (reindex is conceptually a mapper), transform should throttle differently:

  - we be base the calculation on the number of _input_ documents
  - most runtime is spend for search/aggregations
  - the number of _output_ documents can differ, even within one transform due to data and configuration

**For transform we decided to go for `docs_per_second`.**

Setting `docs_per_second` to `null` disables throttling, setting `docs_per_second` to `0` is disallowed.

Configuration:
```
{
  "source": {...},
  "dest": {...}
  "pivot": {
      "group_by": {...},
      "aggregations"" {...}
  },
  "settings": {
      "max_page_search_size": XX,
      "docs_per_second": XX
  }
}
```

`docs_per_second` is located under a new object: `settings`.

The setting `max_page_search_size` which is part of `pivot` will be moved there, too (the old place is deprecated but kept for BWC). If both are specified, the one under settings win, because it could be a leftover after updating an old configuration.

The whole settings object will be update-able with the [update](https://www.elastic.co/guide/en/elasticsearch/reference/master/update-transform.html) API.

Update will be 
 - **immediate** for settings
 - **delayed** until the next checkpoint for the rest

**Comment by russcam** [comment]
> Setting `docs_per_second` to `null` disables throttling

@hendrikmuhs In other APIs where behaviour can be "disabled", `-1` has typically been used as a special value to signal this e.g. 

- [Reindex disable throttling](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html#docs-reindex-throttle)
- [Disable refresh interval on indices](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#index-refresh-interval-setting)
- [All tasks by Parent Task Id](https://www.elastic.co/guide/en/elasticsearch/reference/current/tasks.html#tasks-api-query-params)
- [`TimeValue` MINUS_ONE for infinite timeout](https://github.com/elastic/elasticsearch/blob/e9bc3e8234b4f1a3785101481a46e01541f8fdaf/libs/core/src/main/java/org/elasticsearch/common/unit/TimeValue.java#L31).

Would there be scope to disable throttling on `docs_per_second` by setting it to -1? 

I can't speak for other language clients, but for the .NET high level client, it typically omits sending `null` values in a request because a `null` value for a property on a request type is usually one that hasn't been set by the user. We would need to write additional behaviour to be able to send an explicitly set `null` value in the request, to be able to distinguish it from a `nullable int` default value in the `docs_per_second` case. 

Looks like the Java client sends a `-1` in the case of `null`? https://github.com/elastic/elasticsearch/blob/e177a385044884ffb530a157cb7224631178d92c/client/rest-high-level/src/main/java/org/elasticsearch/client/transform/transforms/SettingsConfig.java#L132-L144

(/cc @elastic/es-clients)

**Comment by karmi** [comment]
Agreed that `null` values are hard to implement (and semantically somewhat empty), and that `-1`, especially for numerical values, makes more sense.

**Comment by hendrikmuhs** [comment]
@russcam 

Both is possible `null` _or_ -1. I will update the description above.

In the stack we have both versions, `null` defaults are used e.g. for [cluster settings](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-update-settings.html).

**Comment by russcam** [comment]
Thanks for clarifying 👍 I'll document to send `-1` for the client to disable
