### ISSUE TITLE
Proposal for Introducing s390x and ppc64le Packages

### ISSUE THREAD

**Issue by james-crowley** [elastic/elasticsearch#54930]
I wanted to start a discussion about introducing packages for `s390x` and `ppc64le` architectures. 

I saw a couple of amazing PRs by @jasontedor, #53914, #53926, #53936, #54856, which outlined the process for adding a new architecture in this case it was `arm64`.

From my brief scan of the changes @jasontedor made, it seems like the code is extendable to allow other architectures.

https://github.com/elastic/elasticsearch/blob/3cd858c8dfc77f1c68b2dd2a0f5a8f4b6fffe393/buildSrc/src/main/java/org/elasticsearch/gradle/Jdk.java#L36

Here we would need to append the additional architectures onto the list.

https://github.com/elastic/elasticsearch/blob/3cd858c8dfc77f1c68b2dd2a0f5a8f4b6fffe393/buildSrc/src/main/java/org/elasticsearch/gradle/Architecture.java#L29-L35

Also, in this snippet we would need to add additional case statements for the additional architectures.

There are couple other key areas we would also need to change, but overall the changes @jasontedor made were very well done! 

Most of these changes stated above are currently how we are building `s390x` binaries to run internally and I would love to see them get merged. 

I have worked with a couple other open source communities to add support for `s390x` and `ppc64le`. One of the challenges communities face is access to `s390x` and `ppc64le` hardware, fortunately IBM does offer free resources for both platforms for open source communities. I am happy to assist the Elasticsearch team in getting setup with these resources, which you could pull into your own CI/CD pipelines.

Tagging a couple of elastic team members I saw helping out with the PRs mentioned above. @mark-vieira @pugnascotia

**Comment by rjernst** [comment]
Thanks for your interest in contributing. While Jason's PRs do show how one would add another architecture to the Elasticsearch build, the decision on when to add such support is more complicated. We prefer to not take on contributions that we do not intend to support because it can end up being confusing to our users, and it's difficult for us to maintain. In the case of ARM, while we do not yet officially support it, we are looking at doing so, and thus made the change to enable further testing. However, at this time we still do not intend to support `s390x` or `PPC`.
