### ISSUE TITLE
SQL: Implement FORMAT function

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#54965]
Implement `FORMAT` according to the SQL Server spec: https://docs.microsoft.com/en-us/sql/t-sql/functions/format-transact-sql?view=sql-server-ver15#ExampleD by translating to the java.time patterns used in `DATETIME_FORMAT`.

Follows: #54832

**Comment by binu-r** [comment]
Hi, Can I start working on this?

**Comment by matriv** [comment]
@binu-r You' re welcome to do so, thank you!

**Comment by aarush00** [comment]
hi mu name is Aarush Chopra and I use elastic search bundled with Redis, because I want to learn internal of es I want to contribute to the project. Please assign me some task and some guidance will be appreciated.

**Comment by matriv** [comment]
@aarush00 Please pick another issue labeled as `good first issue`, as this has already been picked up by another contributor.

**Comment by binu-r** [comment]
By referring  to [DotNet Date Format Strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings), here are the list of replacements in [Java Date Format Strings](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html)


**Description** | **Dot Net** | **Java**
-- | -- | --
AM/PM| “tt” | "a"
AM/PM| "t" | "a"
Day of week (Saturday)| "dddd" | "eeee"
Day of week (Sat)|"ddd" | "eee"
Time Zone ID|"K" | "v"
era(AD) |"g" | "G"
fraction-of-second |"f" | "S"


Remaining strings will be used as such from input 
Shall I proceed with that conversion.

**Comment by matriv** [comment]
@binu-r 
Please check the patterns for date and time as defined in MS SQL Server and not .net:
https://docs.microsoft.com/en-us/sql/t-sql/data-types/date-transact-sql?view=sql-server-ver15
https://docs.microsoft.com/en-us/sql/t-sql/data-types/time-transact-sql?view=sql-server-ver15

**Comment by binu-r** [comment]
@matriv 
Thanks for sharing the links. They particularly mention about how to convert strings to date or time. But we want to convert date/time to string format.

I checked DotNet format because it is mentioned in the format function specification by Microsoft.

> Arguments
value
Expression of a supported data type to format. For a list of valid types, see the table in the following Remarks section.
format
nvarchar format pattern.
The format argument must contain a valid .NET Framework format string, either as a standard format string (for example, "C" or "D"), or as a pattern of custom characters for dates and numeric values (for example, "MMMM DD, yyyy (dddd)"). Composite formatting is not supported. For a full explanation of these formatting patterns, consult the .NET Framework documentation on string formatting in general, custom date and time formats, and custom number formats. A good starting point is the topic, ["Formatting Types."](https://docs.microsoft.com/en-us/dotnet/standard/base-types/formatting-types?redirectedfrom=MSDN#custom-format-strings)
culture
Optional nvarchar argument specifying a culture.
If the culture argument is not provided, the language of the current session is used. This language is set either implicitly, or explicitly by using the SET LANGUAGE statement. culture accepts any culture supported by the .NET Framework as an argument; it is not limited to the languages explicitly supported by SQL Server. If the culture argument is not valid, FORMAT raises an error.

**Comment by binu-r** [comment]
@matriv  please review PR #55454

**Comment by matriv** [comment]
`master` : da511f4e033db6e8a6aa2a54b23e906b5e026845
`7.x` : 1f612cccbb1be786989db99369d99b846e29d9ac
