### ISSUE TITLE
Restore-Rename does not adjust provided_name

### ISSUE THREAD

**Issue by Elias481** [elastic/elasticsearch#55101]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): Version: 7.6.2, Build: default/rpm/ef48eb35cf30adf4db14086e8aabd07ef6fb113f/2020-03-26T06:34:37.794943Z, JVM: 13.0.2

**Plugins installed**: []

**JVM version** (`java -version`): OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.2+8, mixed mode, sharing [bundled]

**OS version** (`uname -a` if on a Unix-like system): 4.18.0-147.5.1.el8_1.x86_64 (EL8)

**Description of the problem including expected versus actual behavior**: when renaming indexes with snapshot-restore the provided_name is not updated - this can for example disturb the _rollover api.
It is possible to just skip this index setting on restore, but a) this is not mentioned in documentation and b) for consitency it would be fine to not skip it but to set it to the index name - which is not possible with skip and not with simple overwrite on restore if doing mass-rename

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. make a snapshot of an index
 2. restore the index with different name according to documentation (for example using "rename_pattern": "(.+)", "rename_replacement": "$1-000204" parameters)
 3. try to make a rollover and/or check the provided_name of the restored renamed index

**Provide logs (if relevant)**:

**Comment by ywelsch** [comment]
Can you expand on the use case here? Why are you renaming on restore? Is this to ultimately work around an ILM issue?

I'm not sure if the solution you're suggesting is feasible, given that the provided_name might contain date math expressions, and the rename pattern / replacemen that applies to the actual index name might not apply to the provided_name.

**Comment by yamanoj** [comment]
You can restore with ignore_index_settings

**Comment by Elias481** [comment]
@yamanoj yes this is what we did then, but it should be documented in the section where rename is documented. This mostly only a problem with ILM which for some reason checks that name if it exists. But anyway it is not fine to have inconsistent names as per default this name is often set to the index name which was just renamed.

@ywelsch yes the use case has something to do with ILM. First we wanted to consolidate indexes from mutiple instances on a single instance - and need a prefix on the index name then to distungish the system/user that has access to these indexes. After renaming them the ILM (_rollover) fails because of the non-changed provided_name.

**Comment by DaveCTurner** [comment]
We (the @elastic/es-distributed team) discussed this again today. It's a tricky one, but fundamentally this is the expected behaviour. `index.provided_name` is intentionally the name of the index as it was created, and that's what rollover uses to name the result of rolling over to a new index. It's not a literal index name, for instance it potentially has date math expressions in it, so there's no reasonable way to update it automatically based on the new index name at restore time.

We also discussed the possibility of letting you update the `index.provided_name` property at restore time, so that you can effectively specify the names of all future indices in the sequence. But we eventually decided that this isn't needed: you can achieve the same effect by doing the restore and then creating a new empty index with the right name, manually simulating the first rollover.

We also noted that instead of rolling over explicitly you could use [data streams](https://www.elastic.co/guide/en/elasticsearch/reference/7.14/data-streams.html) which do permit renames at restore time.

We concluded that we won't be taking any action here, and decided to close this.

**Comment by Elias481** [comment]
You know, still bug needs to be fixed, the bulks... but soon we have it. and as we say at google: fix not feasible for android..
