### ISSUE TITLE
Heap memory issue during cardinality request

### ISSUE THREAD

**Issue by Yv-o-rL** [elastic/elasticsearch#55240]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.2.1

**Plugins installed**: []

**JVM version** (`java -version`): OpenJDK 11

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 18.04.3 LTS

**Description of the problem including expected versus actual behavior**:
I've got a large daily index where sometimes I need to perform an unfiltered cardinality query. I already noticed that the filtered ones are a lot slower than before. When I load a line visualization in Kibana, check the past 30 minutes for the unique values, aggregate by time (auto), and add the top 5 instances as sub-buckets, the cluster crashes for 5-10 minutes. When I check the graphs, I see a couple of nodes hitting the max heap memory. 6 out of 8 nodes had a heap memory jump 4-9 GB (a total of ~46GB of heap memory spike). While I'm far from being an expert, I would say that if there were more memory available the 3 nodes which hit the heap limit would try to hog more.
I understand that cardinality isn't that easy but I didn't experience this issue before and I'd expect that this much HW resources can handle that one query without crashing.

**Steps to reproduce**:

 1. Index dimensions (at query time):
- 300/150GB (primary/store)
- 20 shards (10 primary and 10 replica)
- ~277 million documents
- indexing rate 15300/7650 (primary/total)
- unique values of the field: ~20-25M
- unique instances: ~40K
- 500K documents per minute

 2. Cluster dimensions:
- 8 nodes
- 32 vCPU and 120GB memory per node
- all in the same DC

 3. Elasticsearch settings:
- JVM: G1GC 
- heap memory set to 30GB

 4. Perform the high cardinality query:
- unique count of high cardinality field
- past 30 minutes
- buckets: date histogram (30-second buckets); sub-bucket: terms: TOP 5 instances

**Provide logs (if relevant)**:
First, the Logstash instances are reporting 429:

> retrying failed action with response code: 429 ({"type"=>"circuit_breaking_exception", "reason"=>"[parent] Data too large, data for [<transport_request>] would be [30618130228/28.5gb], which is larger than the limit of [30601641984/28.5gb], real usage: [30618128352/28.5gb], new bytes reserved: [1876/1.8kb]", "bytes_wanted"=>30618130228, "bytes_limit"=>30601641984, "durability"=>"PERMANENT"})

Than ES errors pile up:

> [myelastic-1] failed to execute on node [k2pz-cp-XXXXXXXXXXXXX]
> org.elasticsearch.transport.RemoteTransportException: [myelastic-3][10.0.0.3:9300][cluster:monitor/nodes/info[n]]
> Caused by: org.elasticsearch.common.breaker.CircuitBreakingException: [parent] Data too large, data for [<transport_request>] would be [30651686876/28.5gb], which is larger than the limit of [30601641984/28.5gb], real usage: [30651682792/28.5gb], new bytes reserved: [4084/3.9kb]
> 	at org.elasticsearch.indices.breaker.HierarchyCircuitBreakerService.checkParentLimit(HierarchyCircuitBreakerService.java:343) ~[elasticsearch-7.2.1.jar:7.2.1]
> 	at org.elasticsearch.common.breaker.ChildMemoryCircuitBreaker.addEstimateBytesAndMaybeBreak(ChildMemoryCircuitBreaker.java:128) ~[elasticsearch-7.2.1.jar:7.2.1]
> 	at org.elasticsearch.transport.InboundHandler.handleRequest(InboundHandler.java:173) [elasticsearch-7.2.1.jar:7.2.1]
> 	at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:121) [elasticsearch-7.2.1.jar:7.2.1]
> 	at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:105) [elasticsearch-7.2.1.jar:7.2.1]
> 	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:660) [elasticsearch-7.2.1.jar:7.2.1]
> 	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:62) [transport-netty4-client-7.2.1.jar:7.2.1]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
> 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [netty-codec-4.1.35.Final.jar:4.1.35.Final]
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) [netty-codec-4.1.35.Final.jar:4.1.35.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
> 	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) [netty-handler-4.1.35.Final.jar:4.1.35.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
> 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1478) [netty-handler-4.1.35.Final.jar:4.1.35.Final]
> 	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1227) [netty-handler-4.1.35.Final.jar:4.1.35.Final]
> 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1274) [netty-handler-4.1.35.Final.jar:4.1.35.Final]
> 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) [netty-codec-4.1.35.Final.jar:4.1.35.Final]
> 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) [netty-codec-4.1.35.Final.jar:4.1.35.Final]
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) [netty-codec-4.1.35.Final.jar:4.1.35.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:582) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:536) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) [netty-common-4.1.35.Final.jar:4.1.35.Final]
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.35.Final.jar:4.1.35.Final]
> 	at java.lang.Thread.run(Thread.java:835) [?:?]

**Comment by javanna** [comment]
hi @Yv-o-rL would it be possible for you to post your request?

**Comment by Yv-o-rL** [comment]
It' ls the default Kibana line visualization with the parameters I provided above.

**Comment by Yv-o-rL** [comment]
```
{
  "aggs": {
    "2": {
      "date_histogram": {
        "field": "@timestamp",
        "interval": "30s",
        "time_zone": "UTC",
        "min_doc_count": 1
      },
      "aggs": {
        "3": {
          "terms": {
            "field": "instance.keyword",
            "order": {
              "1": "desc"
            },
            "size": 5
          },
          "aggs": {
            "1": {
              "cardinality": {
                "field": "highcardfield"
              }
            }
          }
        }
      }
    }
  },
  "size": 0,
  "_source": {
    "excludes": []
  },
  "stored_fields": [
    "*"
  ],
  "script_fields": {},
  "docvalue_fields": [
    {
      "field": "@timestamp",
      "format": "date_time"
    }
  ],
  "query": {
    "bool": {
      "must": [
        {
          "match_all": {}
        },
        {
          "range": {
            "@timestamp": {
              "format": "strict_date_optional_time",
              "gte": "2020-04-16T07:00:00.000Z",
              "lte": "2020-04-16T07:30:00.000Z"
            }
          }
        }
      ],
      "filter": [],
      "should": [],
      "must_not": []
    }
  }
}
```

**Comment by polyfractal** [comment]
I think we should probably move this discussion to the [Discuss forums](https://discuss.elastic.co/), since I think Elasticsearch is "working as intended" in this case.  E.g. the circuit breaker is tripping because something/multiple somethings are requesting too much memory.  It's not a very friendly behavior for the user, but it is doing it's job: protect the node from an actual hard OOM crash. :)

The action that tripped the breaker was `transport_request`, meaning that some kind of node-to-node communication tried to reserve more memory than was available in the breakers.  Breakers are hierarchical and share space, so it's not to say the transport request was actually using all that memory... just the tipping point.  But it also means that it's unclear what was actually eating all the memory.  If it was purely the aggregation itself, a different cause would be listed in the breaker (usually `reused_arrays`).

The query/agg don't look too abusive to me, which makes me suspect there are other issues.  Memory being eaten by multiple parallel queries, memory going to the indexing, very large bulk requests eating memory, background queries from Kibana, etc etc.

Generally debugging would involve looking at the node_stats and breaker status across nodes, the slow-log to see what's flowing through the cluster, threadpools, etc.  But that's better done in the forums than here I think :)

**Comment by Yv-o-rL** [comment]
My issue isn't with the circuit breaker, I'm happy that it's there. The problem is that the behavior described above is experienced **only** with the high cardinality query which - as you said too- isn't abusive. The whole cluster is working steadily using 19-23GB of the heap memory and when I run this query I get this:
![image](https://user-images.githubusercontent.com/42407721/79465566-ca8d5400-7ffb-11ea-9f18-8895ab9f404d.png)

This is a production cluster and the indexing rate goes up to 30K/s during peak time. It's receiving a ton of various requests but only crashes when I try to run the query mentioned above. So generally ES takes the heat but somehow that cardinality request triggers something and starts hogging memory until the CB stops it. Then the cluster goes down for 5-10 minutes.

**Comment by Yv-o-rL** [comment]
@colings86 I saw your comments on [#24359](https://github.com/elastic/elasticsearch/issues/24359), but since that, there were 2 major version change and a lot of other ones. Do you have any insights on the issue I have?

**Comment by polyfractal** [comment]
Hiya @Yv-o-rL, sorry, I probably worded my comment poorly.  I didn't mean to suggest it wasn't a problem, just that it'd be easier/better if we moved this discussion to the forums.  We try to keep github reserved for confirmed bugs and feature requests, so the back-and-forth debugging that we need to do (to collect node-stats, threadpools, PMs so we can share sensitive details or a heap dump, etc etc) is better there.

If/when we find a bug we can transition back to github for a bug report and work on a fix.  

You can ping me (or drop a link here) on the forum thread and I'll happily help out. :)

**Comment by polyfractal** [comment]
@Yv-o-rL So as it turns out, @jimczi noticed a detail that I missed: the terms agg is sorted by the cardinality agg:

```
"order": {
  "1": "desc"
},
```

Which actually puts the query into the "abusive" category, even though it looks pretty innocent.  What happens is that sorting by sub-agg means we _have_ to execute the terms aggregation in `depth_first` mode.

Normally, terms aggs execute `breadth_first`, meaning it collects the list of terms and their counts, finds the `top-n` and prunes away all the rest of the terms.  It then executes the next layer of aggregations on those `top-n` buckets.  We can do this pruning because the `top-n` is determined by count.

But when you sort by a sub-aggregation, there is no way to know which buckets to prune because it's dependent on not-yet-calculated quantity.  This means we have to switch to `depth_first`, where we fully process the entire aggregation tree before we can do any pruning of results.

In the above query, this means we actually collect `instance.keyword` number of buckets (for each 30s interval), with a corresponding HLL sketch for the cardinality.  This can get very expensive very quickly if `instance.keyword` has a moderate cardinality, and will quickly trip the circuit breaker as you're seeing.

So I think this really is a case of "expensive query" tripping the breaker, even though it looks very innocent to a user.

I'll chat with the Kibana folks and see if there is some way to proactively warn users about sorting by sub-agg, particularly by `cardinality` which is relatively expensive (~kilobytes per bucket, rather than ~bytes).  Or perhaps Kibana can default to a lower precision when it sees the user is sorting by cardinality.  We might also want to trip the agg circuit breaker faster than 70-80% to help make this less impactful on nodes.

Apologies for missing this detail earlier!
