### ISSUE TITLE
[Data Visualizer] timestamp doesn't support Kibana CSV export format

### ISSUE THREAD

**Issue by blookot** [elastic/elasticsearch#55586]
**Describe the feature**: Add the format of Kibana CSV export in data visualizer

I suggest we add `MMM dd, yyyy @ HH:mm:ss.SSS` to the list of supported timestamp formats in the Data Visualizer File import.

So that when you export a CSV from Kibana you can reimport it via Kibana ;-)

Thank you!

**Comment by droberts195** [comment]
@blookot since the basic ask was so simple I've added it for 7.8 in #55609.  The initial file analysis now finds the time format.

However, I found that round-tripping a file through the Discover view's CSV export back to ML's file upload still required a bit of manual intervention because the export contains fields `_id` and `_index` which are not permitted in ingested documents, so these need to be renamed in the column name overrides.

So there's still a question about what we should do when importing a file that already has `_id` and/or `_index` fields.

**Comment by blookot** [comment]
Thank you @droberts195 !
just a quick comment: the way we usually export CSV is by creating a saved search having only a few columns selected (out of all the fields), so _id and _index are not exported.
Still there is an issue on numeric fields export, see https://github.com/elastic/kibana/issues/64170
But indeed, my goal is to easily export in csv and share the csv for others to reimport via data visualizer ;-)
