### ISSUE TITLE
CCR: unfollow API without close and pause index

### ISSUE THREAD

**Issue by hackerwin7** [elastic/elasticsearch#55638]
relates #33931

Currently before unfollow index in CCR, we need to close and pause the follower index, then unfollow the index, and re-open the follower index as a regular index.

If index is huge besides with high number of shards. the close and re-open until the index is completely green maybe continue a little bit long time due to create index service or create shard.

Can we add a functionality to enable unfollow API only switch the FollowingEngine to InternalEngine dynamically without close and re-open index, and stop persistent follow shard task.

In the future, we only need to call one API of **unfollow**, the follower index will directly convert to regular index.

**Comment by jasontedor** [comment]
Swapping out the engine dynamically is unlikely to be an area where we invest any effort, as it will be difficult to do correctly, and could have unexpected consequences.

That means that the index will need to continue to be closed, so that we can do the engine swap safely. That the user has to go through a pause/close/unfollow/open workflow is a deliberate choice as it puts in the forefront the consequences of this API: operations will no longer be replicated, the index will be closed (and therefore unavailable to for searches!), the following relationship will be permanently broken, and then the index can be made available for reads/writes.

**Comment by hackerwin7** [comment]
@jasontedor 
> Swapping out the engine dynamically is unlikely to be an area where we invest any effort
could we make `FollowingRegularEngine` instead of `FollowingEngine`. 
`FollowingRegularEngine` have two mode : 1. following mode  2. regular mode

Initially `FollowingRegularEngine` is in **following mode** , some methods such as `indexingStrategyForOperation` and `deletionStrategyForOperation` etc. use original `FollowingEngine` methods.

When we call unfollow API, FollowingRegularEngine is in **regular mode**, some methods such as `indexingStrategyForOperation` and `deletionStrategyForOperation` etc. use `InternalEngine` methods.

In this way. we do not need to switch engine dynamically but convert follower index to regular index dynamically.

**Comment by jasontedor** [comment]
@hackerwin7 I would not be in favor of implementing it in this way because it could allow for the introduction of subtle bugs, and also makes it harder for to reason about the engine, and its future maintenance (it's a rather complex piece of code). It's a far simpler model for us to think about: if an index is a regular index it uses an internal engine, and if it's a follower index it uses a follower engine.
