### ISSUE TITLE
Add support for a "warning" logger

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#55699]
We current have our regular logger and the deprecation logger, however, it would be really nice if there were a way we could return warnings back to clients about something that wasn't necessarily deprecated. Something like:

```
warnLogger.warn("your [foo] references [bar] by id [baz], but no bar with the id \"baz\" exists");
```

Or something like that.

**Comment by dakrone** [comment]
Another neat thing (and I have heard folks from the UI recommend this also), would be to be able to collect and return those warnings back in the actual body of the response itself also, rather than just in the response headers.

**Comment by pgomulka** [comment]
thanks for the details @dakrone 
The first part will likely be resolved by this PR https://github.com/elastic/elasticsearch/pull/55608
- it generalises deprecation logger so that we could create more loggers that deprecate/warn.

I will look into the second part where warnings are back in the body.

**Comment by jasontedor** [comment]
I'm not sure about adding these to the response body. Can someone explain to me the benefit?

**Comment by pgomulka** [comment]
since the original ask is already implemented I am tempted to close this. https://github.com/pgomulka/elasticsearch/commit/08d6f63e7542a034acd4025eb3a84038325fa7e5#diff-5081302eb39033199deb1977d544d1cd7867212a92b8d77e0aa0ded361272b11

@dakrone would you be able to add more details on the second [ask](https://github.com/elastic/elasticsearch/issues/55699#issuecomment-618690873) ? Wouldn't just response header be enough?

**Comment by rjernst** [comment]
Closing this as we haven't seen any strong reasons for the change in serveral years. We can reopen if thinking changes.

**Comment by jakelandis** [comment]
Actually, this was implemented a while ago in https://github.com/elastic/elasticsearch/pull/55941. See `HeaderWarning.addWarning(`for current usages.
