### ISSUE TITLE
[Ingest Node Pipelines] New description field for processors

### ISSUE THREAD

**Issue by jloleysens** [elastic/elasticsearch#56000]
**Describe the feature**:

Building UI for the managing processors in Kibana has shown how the `tag` field may be used to serve dual purposes:

1. A unique identifier for a processor instance
2. A descriptive name for the processor instance

It would be really useful to have an extra (optional) `description` field when creating a processor so that the tag can be more singular in its concern. 

CC @jakelandis @talevy

**Comment by jethr0null** [comment]
To add a bit of context here, this would greatly improve the Ingest Nodes Pipeline UI that the team is currently working on. When displaying a list of processors within a pipeline visually, it becomes much more difficult to determine which processor is responsible for which changes. [Here is an example](https://github.com/elastic/elasticsearch-team-planning/issues/65#issuecomment-628688441) mockup that highlights where these descriptions would be used in order to make it easier for users to quickly see information about the processor beyond the processor name and identify the specific processor they intend to edit/delete/etc.
