### ISSUE TITLE
Intellij Idea 2020.1.1 Gradle reimport results in wrong project language and compiler target levels

### ISSUE THREAD

**Issue by breskeby** [elastic/elasticsearch#56173]
The elasticsearch project does not work with Idea 2020.1.1 as a Gradle reimport causes the language levels to fall back to wrong values instead of the desired. 

This has been raised as an issue to jetbrains (https://youtrack.jetbrains.com/issue/IDEA-240086)

This ticket here is used to track that issue within the es team till its fully resolved

**Comment by ywelsch** [comment]
This looks to not have been fixed in IDEA's newest 2020.1.2 release.

I've been using the workaround (mentioned [here](https://youtrack.jetbrains.com/issue/IDEA-240086#focus=streamItem-27-4153350.0-0)) successfully for the past few weeks. Perhaps we should let the team upgrade with the above workaround.

**Comment by breskeby** [comment]
@ywelsch yeah, that's probably the right way to go. I hoped the proper fix would make it into 2020.1.2 as they promised it is scheduled with high priority. let me verify that workaround again with 2020.1.2 again and then we probably sent out an email regarding the idea update on monday.

**Comment by mark-vieira** [comment]
This was fixed in IntelliJ 2020.2.
