### ISSUE TITLE
Do not allow breaking v2 index templates by removing in-use component templates

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#56314]
A major design goal of v2 index templates is to allow us to perform more thorough validation at template creation time. Such templates are composed of explicit component templates, so we can validate the resulting template. However, removing a component template that is used by a v2 index template would break any v2 index templates using that component template, thus ruining our plan for more thorough validation of v2 index templates. We should prevent the breakage by not allowing removing component templates that are in use by any v2 index template.

**Comment by cjcenizal** [comment]
Should we also disallow creating/updating an index template with a component template that doesn't exist? This currently returns a 200:

```
PUT _index_template/test
{
  "index_patterns": ["test"],
  "composed_of": ["does_not_exist"]
}
```

Even though this index template isn't "broken", I think it's logical for this request to fail the same way the originally described request would fail, since they both end up in the same state: an index template referring to a nonexistent component template.

**Comment by dakrone** [comment]
> Should we also disallow creating/updating an index template with a component template that doesn't exist?

I think we should, at least to avoid the case where someone typos a component template name and has an unintended consequence.

**Comment by jasontedor** [comment]
> Even though this index template isn't "broken"

I think it is broken.

> I think we should, at least to avoid the case where someone typos a component template name and has an unintended consequence.

I agree, the goal is that v2 index templates should be unbreakable.
