### ISSUE TITLE
RequestError: 'No handler for type [dense_vector]

### ISSUE THREAD

**Issue by hegebharat** [elastic/elasticsearch#56555]
RequestError: RequestError(400, 'mapper_parsing_exception', 'No handler for type [dense_vector] declared on field [title_vector]')
I got above error. So what could be the issue?
I am using 7.4 version elastic search and
my index file look link
{

"settings": {

"number_of_shards": 2,

"number_of_replicas": 1
},

"mappings": {

"dynamic": "true",

"_source": {

  "enabled": "true"

},

"properties": {

  "type": {

    "type": "keyword"

  },
"title_vector": {
"type": "dense_vector",
"dims": 512
}

}
}

}

**Comment by cbuescher** [comment]
@hegebharat are you using x-pack or the pure OSS version? Asking because the [dense_vector](https://www.elastic.co/guide/en/elasticsearch/reference/master/dense-vector.html) datatype is an x-pack feature. In general, question like this are better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
