### ISSUE TITLE
IO hangs on Leader can cause publications to get stuck indefinitely

### ISSUE THREAD

**Issue by Bukhtawar** [elastic/elasticsearch#56707]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.7.0

**Plugins installed**: []

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system): Linux

**Description of the problem including expected versus actual behavior**:
At the start of the publication the leader schedules a timeout handler and info handler to run at the end of the publish timeout. When the leader tries to commit the state locally, it acquires a mutex which is released only after local commit goes through. Now at this point if the node encounters an IO freeze at the persistence layer `PersistedClusterStateService#commit`, the mutex is not released that restricts the timeout behaviour from cancelling publication. 

The scheduler schedules the timeout at publication timeout but its prevented from cancelling the publication by the mutex that has been held up. I'm not quite sure if that is the intended behaviour since the scheduler starts at the start of publication and not at the end of local state commit success. The leader as a result steps down only after it recovers from IO freeze when the timeout handler finally runs and cancels publication. The master operations during this time is stuck.

This also impacts the `infoTimeoutHandler` from running and logging the slow publication responses.

**Steps to reproduce**:
I have tried to simulate IO hang by adding a sleep in the code at `PersistedClusterStateService#commit` (apologies in advance, but will try a command that mimics the same).

**Comment by DaveCTurner** [comment]
Thanks @Bukhtawar, I think this is a good observation.

I don't think we can reasonably cancel the IO on which the publication is waiting, nor can we safely take much further action (e.g. standing down as leader) while waiting for that IO to complete.

The thing that concerns me is that the leader continues to report itself as healthy throughout, so the other nodes don't have an opportunity to ditch the faulty leader and elect a healthy one in its place. I think we should strengthen these health checks to account for this failure mode.

I [still think there's something wrong with your underlying system](https://github.com/elastic/elasticsearch/issues/40326#issuecomment-477193977) that causes IO to hang for such long periods rather than returning an error.

**Comment by DaveCTurner** [comment]
> I don't think we can reasonably cancel the IO on which the publication is waiting

I've changed my mind, I think I can see a way to impose a timeout on this IO that's not too invasive. I think we might also need #52680, or else the failing node will cause disruption by repeatedly trying in vain to rejoin.

**Comment by Bukhtawar** [comment]
Thanks @DaveCTurner once #52680 is reviewed, I'll start to work on this proposal, which is also what makes it super important.

**Comment by DaveCTurner** [comment]
We've discussed this internally and once again we feel that your problems with IO that hangs indefinitely are most likely a bug in your infrastructure and not something that Elasticsearch should be working around. This doesn't seem to be a problem we experience in practice on a wide variety of production systems, and we still cannot find evidence that any other software has needed to implement protections against indefinitely unresponsive disks either. Therefore I am closing this issue to indicate that we won't be working on it.
