### ISSUE TITLE
Latest version is 6.8.9 (not 7.7.0)

### ISSUE THREAD

**Issue by brainix** [elastic/elasticsearch#56738]
Hello folks, and congratulations on releasing 7.7.0!

Minor note... On the [GitHub releases page](https://github.com/elastic/elasticsearch/releases), 6.8.9 is marked as the current release, not 7.7.0. Could someone update the current release?

Thanks, and keep up the great work.

**Comment by tvernum** [comment]
Unfortunately as far as I can tell we have no real control over this.

GitHub assigns the "latest release" tag to the release that points to the most recent (chronological) commit. Which in effect means when the tag was created.

```
tag v6.8.9
Tagger: ElasticMachine <elasticmachine@users.noreply.github.com>
Date:   Wed May 13 14:55:03 2020 +0000
tag v7.7.0
Tagger: ElasticMachine <elasticmachine@users.noreply.github.com>
Date:   Wed May 13 14:14:59 2020 +0000
```

We created the v6.8.9 tag about 40 minutes after the v7.7.0 tag, so GitHub thinks it is the "latest release" which is true in a way - it was the most recent thing we released, but it's not the highest version.

In theory we could try and sequence our release tagging steps so that higher releases are tagged last, but that assumes (incorrectly) that we will always release a 7.x version simultaneously with a 6.x version. We often do, but not always. If we decide to release a 6.8.10 next week to fix a problem that only exists in the 6.x series, then GitHub will decide it is the "latest release" unless we schedule a 7.x release straight afterwards (which we wouldn't want to do).

I'm going to leave this open for a few days in case someone else on the team has an idea of what we could/should do, but I think it's out of our hands and GitHub needs to make it possible to assign the "latest release" instead of inferring it from Git timestamps.

**Comment by jasontedor** [comment]
As @tvernum points out, "latest" is chronological, not semantic. From the [GitHub API docs](https://developer.github.com/v3/repos/releases/#get-the-latest-release):

>The latest release is the most recent non-prerelease, non-draft release, sorted by the `created_at` attribute. The `created_at` attribute is the date of the commit used for the release, and not the date when the release was drafted or published.

There is nothing that we can do about this. I sent a mail to GitHub about this on September 5, 2019. Here is the content of that mail:

>The [latest release][0] for a repository is defined by the date of the commit used to create the release. The problem with this approach is that it doesn’t respect versioning. So imagine a repository that releases a patch release and the next minor release: 7.3.2 and 7.4.0. If the date of the commit used to create 7.3.2 so happens to be after the date of the commit used to create 7.4.0, then GitHub treats 7.3.2 as the latest release. I think this is surprising to users, and doesn’t aid in discovery of newer versions of products. This can also happen in cases when a repository is maintaining two or more major versions, and a release is performed for one of the earlier major versions (e.g., a previous major version that is in maintenance mode).

>I think that developers should have the ability to control which release is considered the current latest release (e.g., via a separate API to change the latest pointer).

Here is there standard reply:

>Jason,

>Thank you for contacting GitHub Developer Support. We wanted to let you know that we've received your message and will get to it as quickly as possible.

>Ticket ID: 374221

>If you have any additional information or would like to add anything to your initial message, now would be a great time to do so, feel free to reply to this email. If not, then rest assured your request is in the right hands :)

>Thank you!
>The GitHub Developer Support Team

Followed by an actual reply a few days later:

>Hi Jason,

>Thanks for taking the time to reach out and share your thoughts and suggestions. I think I see your point and why you expected more options here regarding the latest release. I'd be happy to pass that along to the product team working on releases to consider for the future, but can't make any promises.

>Thanks again and if there's anything else you'd like to see improved -- please let us know.

>Best,
>Ivan

Given that there is nothing that we are going to do here without proper support from built-in GitHub functionality, I'm going to close this issue.

[0]: https://developer.github.com/v3/repos/releases/#get-the-latest-release

**Comment by brainix** [comment]
Thank you all for following up. I'll modify my scripts to check for the highest version by relying on semver instead of GitHub's latest release tag. :-)
