### ISSUE TITLE
ActiveDirectoryRealmTests#testRealmMapsUsersToRoles failed

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#56756]
**Build scan**:

https://gradle-enterprise.elastic.co/s/d5gdrf7aowncw/console-log?task=:x-pack:plugin:security:test

**Repro line**:

```
  | REPRODUCE WITH: ./gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.xpack.security.authc.ldap.ActiveDirectoryRealmTests.testRealmMapsUsersToRoles" -Dtests.seed=988FA6B9DFD220F8 -Dtests.security.manager=true -Dtests.locale=sk -Dtests.timezone=Indian/Chagos -Dcompiler.java=14 -Druntime.java=8
```

**Reproduces locally?**:

No (tried 10 times on bec6821fe61503051bf4024c303dd26d9f782f4d)

**Applicable branches**:

One failure on 7.x, nothing else over the last 90 days.

**Failure excerpt**:

```

org.elasticsearch.xpack.security.authc.ldap.ActiveDirectoryRealmTests > testRealmMapsUsersToRoles FAILED |  
-- | --
  | java.lang.AssertionError: |  
  | Expected: is not null |  
  | but: was null |  
  | at __randomizedtesting.SeedInfo.seed([988FA6B9DFD220F8:5996457F47F88EE3]:0) |  
  | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
  | at org.junit.Assert.assertThat(Assert.java:956) |  
  | at org.junit.Assert.assertThat(Assert.java:923) |  
  | at org.elasticsearch.xpack.security.authc.ldap.ActiveDirectoryRealmTests.testRealmMapsUsersToRoles(ActiveDirectoryRealmTests.java:370) |  
  | REPRODUCE WITH: ./gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.xpack.security.authc.ldap.ActiveDirectoryRealmTests.testRealmMapsUsersToRoles" -Dtests.seed=988FA6B9DFD220F8 -Dtests.security.manager=true -Dtests.locale=sk -Dtests.timezone=Indian/Chagos -Dcompiler.java=14 -Druntime.java=8


```

**Comment by ywangd** [comment]
This failure is probably caused by the in-memory directory server being slow on launching. The authentication request was sent to the directory server before it is fully ready. This resulted into user lookup failure. This is rare enough, this exact error only happened [once](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-1y,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'%22ActiveDirectoryRealmTests%22%20AND%20%22is%20not%20null%22'),sort:!(process.time-start,desc))) in last year. If I search for all failures of this class, I got [3 of them](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-1y,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:%22ActiveDirectoryRealmTests%22),sort:!(process.time-start,desc))) (including this one). Though the error message is different:
> "java.lang.AssertionError: \nExpected: is <SUCCESS>\n     but: was <CONTINUE>",
>
I suspect they are caused by the same underlying issue, i.e. user not found. The different error message is just because of assertions were against different attributes (of the same object).

Three failures in last year are still pretty rare. But if we want a fix, it could be either adding Time.sleep or retrying authenticate. However, all these are still just best guess, because the current message just shows `user` is `null` and it does not tell you why it is null, i.e. the complete `AuthenticationResult` object. So for now, I'll be adding more details in error messages. Afterwards, if it fails again in the future, we will have a better understanding about what is going on and also fix it with more confidence.

**Comment by ywangd** [comment]
This [test has not failed](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:'2020-05-13T12:55:31.394Z',mode:absolute,to:'2021-07-12T05:09:40.301Z'))&_a=(columns:!(_source),filters:!(),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testRealmMapsUsersToRoles),sort:!(process.time-start,desc))) since it's reported over a year ago. I added some more message to help debugging the failure in https://github.com/elastic/elasticsearch/pull/65043. But since it does not fail anymore, no new investigation can be conducted. Given the failure is rare enough, I am closing this without further action.
