### ISSUE TITLE
EQL: implement case sensitivity for match and wildcard string functions

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#56752]
Following a similar approach in #56404, implement case sensitivity based on request parameter for `match` and `wildcard` string functions.

**Comment by caiomelo22** [comment]
Hi! Can I try to solve this issue?

**Comment by rw-access** [comment]
Hey, @caiomelo22. I appreciate the enthusiasm, but unfortunately I forgot to close this issue back in 7.10, since it's no longer needed.

Thanks for the unintentional nudge. If you're looking for issues to help with I would recommend looking for "help wanted" + "good first issue." Here's the [filtered list](https://github.com/elastic/elasticsearch/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+label%3A%22good+first+issue%22)
