### ISSUE TITLE
[Documentation] - Document inability to manually update index multi-fields

### ISSUE THREAD

**Issue by michaelborn** [elastic/elasticsearch#56781]
I added a new `keyword` subfield so I can search using an exact `term` restriction:

```js
{
    "cars" : {
        "properties" : {
            "items" : {
                "properties" : {
                    "name" : {
                        "type" : "text",
                        "fields" : {
                            "keyword" : {
                                "type" : "keyword",
                                "ignore_above" : 256
                            }
                        }
                    }
                }
            }
        }
    }
}
```

Then I attempted to run a migration which updated the `cars.items.name.keyword` field to the `cars.items.name` field. I get an "illegal argument exception" when I run this. 

```js
{
    "lang" : "painless",
    "source" : "
        for ( car in ctx._source.cars ){
            if ( car.items != null ){
                for ( item in car.items ){
                    item.name.keyword = item.name; // <-- Illegal argument exception
                }
            }
        }
    "
}
```

The only way I got this to work was setting `item.name = item.name`.

As far as I can tell, the ability to manually set subfields using an `updateByQuery` script has been removed in ES7. This should be noted on this page: https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-fields.html

**Comment by jimczi** [comment]
You don't need to set values of multi-field in the original source. Multi-fields are equivalent to a copy field, they take the input of their parent and index it with the associated type. 
Your script tries to add a field inside a leaf field (`item.name`), that's why you get the IAE, you cannot change a string into an object automatically. 
So the solution if you add a new multi-field is to simply reindex the document, you don't need to change the `_source`, the multi-field will be populated when documents are reindexed (using reindex or a simple update).
I hope you don't mind if I close this issue, please use the [forum](https://discuss.elastic.co/c/elasticsearch/6) if you have further questions on the topic since we reserve github for bugs and feature requests.
