### ISSUE TITLE
Modernise release tooling

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#56788]
We currently rely on some Perl scripts in the `dev-tools` directory to perform a couple of release-related activities:

   1. Relabelling PRs at feature-freeze
   2. Generating release notes from PRs

These scripts are barely maintained, and out-of-step with most of the tooling in the repository. We need to rewrite these scripts to make them easier to maintain.

We could, for example, rewrite them as Gradle tasks, given that most other activities are performed through Gradle.

(Note that there's also the `atomic_push.sh` script, but I don't know if we want to do anything about that right now.)

**Comment by mark-vieira** [comment]
Even if we don't integrate these into the build in the form of Gradle tasks, I think we _should_ integrate them into CI for _execution_. This is a pattern I've used heavily in the past where these automation tasks are modeled as manually triggered CI jobs. This has a few advantages:

1. They are easily discoverable, since there's a clearly documented thing folks can see in CI.
2. The execution environment is standard and controlled. No need to install Perl, Python, etc to run this stuff manually.
3. We can model more complex workflows here, such as simply hit "release", which bumps versions, relabels PRs, generates release notes, sends and email/slack message to the team, etc.
4. Execution results are visible to the whole team. This means we can easily see _who_ ran this, or even if it had been run at all. 

What I'm describing is maybe orthogonal to this issue (which focuses on implementation) but I think we should move away from script or tools that a developer needs to run locally, to having this tooling run in a controlled environment with greater team-wide visibility.

**Comment by rjernst** [comment]
> The execution environment is standard and controlled. No need to install Perl, Python, etc to run this stuff manually.

I agree on having controlled environments for these tasks. However, I think using gradle tasks here actually helps that controlled environment. By using gradle as the execution environment, CI needs to have nothing more than java. If we use other toolings like python or perl, we quickly have dependency problems when we want to utilize any kind of existing library. With a gradle task, dependencies are easily handled within our environment, instead of needing to declare dependencies in CI.

**Comment by pugnascotia** [comment]
I’m working on replacing these scripts with Gradle tasks right now.
