### ISSUE TITLE
EQL: Tie breaker response and ECS mapping

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#56824]
In EQL for events that have the same timestamp there needs to be user defined tie breaker.
In particular this means that:
- [ ] name said field in our request. Based on the naming conventions in #49634, I've came up with `tie_breaker`. Any other suggestions?
- [ ] extend the EQL request to allow for such a parameter to be specified if needed, otherwise it should have a default value.
- [ ] what should it map into ECS? ~Maybe `event.id`?~ `event.sequence`

**Comment by costin** [comment]
Pinging @tsg for awareness.

**Comment by rw-access** [comment]
> what should it map into ECS? Maybe event.id?

It looks like `event.sequence` is going to be the way to go. Since it's ECS core and not extended, there's a chance it might not be populated. I think this is okay, because users can still override.
![image](https://user-images.githubusercontent.com/31489089/82067860-80e16900-968e-11ea-9f46-a850cccf118b.png)
