### ISSUE TITLE
Error "the system property [es.path.conf] must be set"  when starting the service registered using batch

### ISSUE THREAD

**Issue by kasa-taku** [elastic/elasticsearch#56977]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.7.0

**JVM version** (`java -version`): openjdk version "11.0.6" 2020-01-14 LTS

**OS version** (`uname -a` if on a Unix-like system): Windows Server 2016 Standard

**Description of the problem including expected versus actual behavior**:
An error occurs when starting the service registered using "elasticsearch-service.bat"
`"the system property [es.path.conf] must be set"`

**Steps to reproduce**:
 1. unzip
 2. Execute a command 
"bin\elasticsearch-service.bat install"
 3. Start the elasticsearch-service-x64
"sc start elasticsearch-service-x64"
4. Error occurs

**Workaround**:
Add the following to ES_JAVA_OPTS in elasticsearch-service.bat
`-Des.path.home=%ES_HOME%;-Des.path.conf=%ES_PATH_CONF%;`

**Comment by williamrandolph** [comment]
I tracked down what the bug is. Our JVM options parser is supposed to emit a string of white-space separated java options. The batch script is expecting single white-spaces, converting them to semi-colons, and feeding that into the service registration command. But the options parser is emitting a double whitespace, which we convert into double semicolons, and the service installation is choking on that and dropping most of our JVM options, including some crucial ones.

I'm going to look at fixing up the output of the JVM options parser and making the batch script more robust, if possible.

**Comment by williamrandolph** [comment]
### Cause

The "missing" option is a setting that only gets inserted on JDK 14 and newer, so this problem should only occur on JDK 13 and earlier. This was added in ticket #54853. It's only an issue with the Windows service; the other startup commands can tolerate an extra whitespace just fine.

### Workaround

The workaround in the original issue isn't ideal because it still drops a lot of JVM options. The better workaround would be to add a line to `elasticsearch-service.bat` that will remove the double semicolon. There is already a line that translates spaces to semicolons:

```
if not "%ES_JAVA_OPTS%" == "" set ES_JAVA_OPTS=%ES_JAVA_OPTS: =;%
```

Immediately after this, insert:

```
if not "%ES_JAVA_OPTS%" == "" set ES_JAVA_OPTS=%ES_JAVA_OPTS:;;=;%
```

**Comment by alitoca** [comment]
> if not "%ES_JAVA_OPTS%" == "" set ES_JAVA_OPTS=%ES_JAVA_OPTS:;;=;%

This solution is not working.

**Comment by williamrandolph** [comment]
@alitoca Can you provide any more details or steps to reproduce? What is the output if you `echo` the `ES_JAVA_OPTS` variable after this substitution?

**Comment by alitoca** [comment]
@williamrandolph 
1. [Failed] Java installed prior to zip install instruction didn't work with error mentioned here. 
2. [Failed] Java installed prior to MSI didn't work either.
![msi installer error](https://user-images.githubusercontent.com/35346639/93792677-d2cd6900-fc03-11ea-97b6-cd5f9f0732f4.png)
3.[Worked] No java installed prior, MSI install worked for me.

**Comment by williamrandolph** [comment]
@alitoca If a Java installation is affecting the Elasticsearch installation, you may be having issues with the `JAVA_HOME` environment variable. Consider setting `JAVA_HOME` so that it points to the `jdk` directory within the Elasticsearch home directory: https://www.elastic.co/guide/en/elasticsearch/reference/7.9/setup.html

Another option is to upgrade your installed JDK to JDK 14 or newer. However, we recommend using the JDK that is distributed with Elasticsearch.

**Comment by paksboda** [comment]
@williamrandolph 
I am facing same issue and I applied your workaround but still its giving same error. Not sure what I am missing here as I can see system property properly appended and separated by semicolons in command line echo.

C:\Software\elasticsearch-7.7.0\bin>elasticsearch-service.bat install
Installing service      :  "elasticsearch-service-x64"
Using JAVA_HOME (64-bit):  "C:\Software\openjdk-11+28_windows-x64_bin\jdk-11"
-Des.networkaddress.cache.ttl=60;-Des.networkaddress.cache.negative.ttl=10;-XX:+AlwaysPreTouch;-Xss1m;-Djava.awt.headless=true;-Dfile.encoding=UTF-8;-Djna.nosys=true;-XX:-OmitStackTraceInFastThrow;;-Dio.netty.noUnsafe=true;-Dio.netty.noKeySetOptimization=true;-Dio.netty.recycler.maxCapacityPerThread=0;-Dio.netty.allocator.numDirectArenas=0;-Dlog4j.shutdownHookEnabled=false;-Dlog4j2.disable.jmx=true;-Djava.locale.providers=SPI,COMPAT;-Xms1g;-Xmx1g;-XX:+UseConcMarkSweepGC;-XX:CMSInitiatingOccupancyFraction=75;-XX:+UseCMSInitiatingOccupancyOnly;-Djava.io.tmpdir=C:\Users\user\AppData\Local\Temp\elasticsearch;-XX:+HeapDumpOnOutOfMemoryError;-XX:HeapDumpPath=data;-XX:ErrorFile=logs/hs_err_pid%p.log;-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m;-XX:MaxDirectMemorySize=536870912;-Des.path.home=C:\Software\elasticsearch-7.7.0;-D**es.path.conf**=C:\Software\elasticsearch-7.7.0\config;
The service 'elasticsearch-service-x64' has been installed.

When starting service it gives error and in elasticsearch-service-x64-stderr.2020-10-16.log file I can see below error.
2020-10-16 15:20:52 Commons Daemon procrun stderr initialized
ERROR: the system property [es.path.conf] must be set


Not sure why it is still complaining as es.path.conf is there in system properties now.

**Comment by paksboda** [comment]
@williamrandolph 
I tried solution provided by @haedri in below issue and its working for me.
https://github.com/elastic/elasticsearch/issues/61333

**Comment by williamrandolph** [comment]
@paksboda I'm sorry for failing to respond to your comment until now. I am glad that you were able to use the workaround in #61333.

I made a change in https://github.com/elastic/elasticsearch/pull/64254 that I think would also address this issue. This code was released in 7.9.4 and 7.10.0. Please let me know if you find that you have to use the workaround from 61333 in those newer versions of Elasticsearch.

**Comment by paksboda** [comment]
Sounds good @williamrandolph. I will update here once I try latest version and face any issue.

**Comment by zkkis** [comment]
Elasticsearch version (bin/elasticsearch --version): \elasticsearch-8.1.0

JVM version (java -version): openjdk version  jdk-17.0.2

Windows environment : Windows 11

Description of the problem including expected versus actual behavior:
An error occurs when starting the service registered using "elasticsearch-service.bat"
"the system property [es.path.conf] must be set"

![image](https://user-images.githubusercontent.com/93116677/159159216-9b818914-094d-4818-b72f-c47f6c3226cc.png)

I tried to change ES_JAVA_OPTS , but it didn't work
`if not "%ES_JAVA_OPTS%" == "" set ES_JAVA_OPTS=%ES_JAVA_OPTS:;;=;%   `
