### ISSUE TITLE
Per-node rate limits for snapshots

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#57023]
Today you can set a rate limit on a snapshot repository to prevent snapshot/restore operations from causing overload. However, in a hot/warm deployment the different tiers may have drastically different performance (for both disks and network) so a limit that makes sense for the faster hot nodes may be high enough to harm the slower warm nodes.

Possible ideas:

- for _restores_ I think it would be reasonable for `indices.recovery.max_bytes_per_sec` to apply in addition to the repository-level limit, since restores are recoveries.

- for _snapshots_ it's harder to justify using this specific setting since snapshots are not recoveries, but I do think it makes sense to have a node-wide "bulk transfer" rate limit which would cover both recoveries and snapshots.

Other thoughts welcome.

**Comment by original-brownbear** [comment]
+1 to having a global limit per node. If your disks can only handle X b/s then we should have the ability to throttle ES enough to not completely exhaust that via recoveries+snapshots.

Much less important:
I think it may still be nice to have a separate (more granular) setting for the snapshot repository interaction to override the global bulk limit. Snapshot repository interaction at times is subject to different constraints than recoveries (may run on a different network than inter-node communication, NFS may not be able the write throughput that snapshotting generates and so on).

**Comment by kkewwei** [comment]
I think if we should add Segment Merge should also add disk-level limit. It's easy to

**Comment by kkewwei** [comment]
Not only at the node-level, I think it also should add limit at disk-level.

**Comment by original-brownbear** [comment]
We discussed this during out team meeting today.

There was general agreement that using the same limit for restores and recoveries is a reasonable thing to do since my mainly try to protect disks and not the network with the setting. Yannick mentioned that if someone wanted to protect network resources rather than disks, having the ability to separately set the restore rate from something like an S3 repository that is using different network resources might be helpful (similar to my point in https://github.com/elastic/elasticsearch/issues/57023#issuecomment-632059130).

There was also alignment on the issue of having per-node limits instead of per repository limits for snapshotting. This would be helpful to hot-warm architectures in many cases where the hot nodes are able to snapshot at a higher rate than the warm nodes.
We will solicit feedback on what useful settings would look like for snapshots from a wider audience as a next step here.

**Comment by DaveCTurner** [comment]
Never really got any further feedback on this, we should discuss it again to decide what to do about it.

**Comment by repantis** [comment]
https://github.com/elastic/cloud/issues/43998 currently captures the discussion @DaveCTurner mentioned above.
