### ISSUE TITLE
Spring boot with ElasticsearchRepository and RestHighLevelClient parameters query

### ISSUE THREAD

**Issue by alezzix** [elastic/elasticsearch#57079]
I'm using Spring boot with ElasticsearchRepository and RestHighLevelClient. I have this query in mt repository class:

public interface BillingCycleRepository extends ElasticsearchRepository {

List<BillingCycle> findByUserIdOrderByStartDateDesc(String userId);
}

In my console, I can see this:

org.elasticsearch.client.RestClient : request [POST http://localhost:9200/dev-billing-cycle/_doc/_search?rest_total_hits_as_int=true&typed_keys=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&ignore_throttled=true&search_type=query_then_fetch&batched_reduce_size=512]

It generates a lot of parameters, like "rest_total_hits_as_int" and "typed_keys"

Is it possible to configure these parameters and add any others, like "filter_path", "preference"?

**Comment by nik9000** [comment]
This is probably better asked on discuss.elastic.co but I'll answer anyway in case someone finds it on google: the high level client won't use `filter_path` because its job is to parse the response. `preference` is available in the `SearchRequest`. How you get that from Spring Boot's `ElasticsearchRepository` is a question for the spring boot folks. The other parameters like `rest_total_hits_as_int` and `typed_keys` are kind of implementation details of the high level client. They make Elasticsearch emit data in a way that the high level client prefers.
