### ISSUE TITLE
Hidden indices are not included in the snapshots

### ISSUE THREAD

**Issue by lucabelluccini** [elastic/elasticsearch#57208]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.7.0

**Description of the problem including expected versus actual behavior**:

Triggering a full snapshot will not include hidden indices.
This can be critical as some of the hidden indexes contain data from ML jobs

**Steps to reproduce**:

 1. Spawn a cluster in ES 7.7.0
 2. Try to trigger a snapshot
 3. Compare the list of indices in the snapshots vs those in the cluster

**Provide logs (if relevant)**:

```
> GET */_settings?expand_wildcards=all&filter_path=*.settings.index.hidden
{
  ".watcher-history-11-2020.05.27" : {
    "settings" : {
      "index" : {
        "hidden" : "true"
      }
    }
  },
  ".watcher-history-11-2020.05.25" : {
    "settings" : {
      "index" : {
        "hidden" : "true"
      }
    }
  },
  ".slm-history-2-000001" : {
    "settings" : {
      "index" : {
        "hidden" : "true"
      }
    }
  },
  "ilm-history-2-000001" : {
    "settings" : {
      "index" : {
        "hidden" : "true"
      }
    }
  },
  ".watcher-history-11-2020.05.26" : {
    "settings" : {
      "index" : {
        "hidden" : "true"
      }
    }
  }
}
```

```
> GET _snapshot/found-snapshots/test
{
  "snapshots" : [
    {
      "snapshot" : "test",
      "uuid" : "WLjeWJDdSdmB4i6sulM-qg",
      "version_id" : 7070099,
      "version" : "7.7.0",
      "indices" : [
<REDACTED - But none of the indices above is present>
      ],
      "include_global_state" : true,
      "state" : "SUCCESS",
      "start_time" : "2020-05-27T13:44:13.047Z",
      "start_time_in_millis" : 1590587053047,
      "end_time" : "2020-05-27T13:44:55.891Z",
      "end_time_in_millis" : 1590587095891,
      "duration_in_millis" : 42844,
      "failures" : [ ],
      "shards" : {
        "total" : 65,
        "failed" : 0,
        "successful" : 65
      }
    }
  ]
}
```

## Workaround

To include hidden indices prefixed with `.`, it is possible to use:
```
POST _snapshot/found-snapshots/test
{
  "indices": "*,.*"
}
```

To snapshot hidden indices not prefixed with `.` (e.g. `ilm-history...`), we would need to add a prefix explicitly (e.g. `ilm*`), which is not so straightforward as we need to know all the possible names of the hidden indices.

**Comment by gwbrown** [comment]
Thanks for finding this. Looking at the code, it's immediately apparent why this happens and the fix should be straightforward.

**Comment by gwbrown** [comment]
In looking into this more deeply, I've discovered an undocumented feature of the Snapshot API: It supports `expand_wildcards` in the body of the snapshot request. So to take a snapshot of all indices (including hidden ones), the following request will work in 7.7.0:

```
POST _snapshot/testrepo/test-snap
{
  "indices": "*",
  "expand_wildcards": "all"
}
```

Because the parameter is in the body of the request, this approach will work for SLM as well (with no code changes, in 7.7.0).

Clearly we need to document this, as it is currently not documented at all - I'll put a PR up soon. I'll also add some test cases for this scenario.  What I'm less clear on is if this is a satisfactory solution: do we believe that this is behavior is unexpected enough to make a change to the default behavior? I could see this being risky default behavior. If we want to change the default, I have code changes to do so basically ready to go, and will put up a PR soon (separate from the docs one).

@rjernst, would you mind weighing in on whether it's worth changing the default here?

**Comment by gwbrown** [comment]
@rjernst and I discussed this briefly.  We do think that we need to make a change in the short term to avoid surprising users, but we also want to preserve the consistency of index resolution.  What makes this weird is that hidden indices were introduced in a minor version, and administrators are likely to consider a change that leads to some indices not being included in an "all indices" snapshot to be a breaking change (even if it may not formally meet our criteria for a breaking change, as only new functionality was introduced).

Here's the solution we propose:
- Document the `expand_wildcards` field for snapshot creation.
- For 7.x releases, update the default value of `expand_wildcards` to include hidden indices, but make it emit a deprecation warning explaining that including hidden indices in snapshots will need to be explicit in the next major version.
- In 8.0, revert to the behavior used by 7.7.0, so that index resolution is consistent with other APIs.
- Make a note in the 8.0 breaking changes docs explaining the change necessary to continue snapshotting hidden indices.

**Comment by gwbrown** [comment]
Update for those following this issue: The defaults change (https://github.com/elastic/elasticsearch/pull/57325) and docs change (https://github.com/elastic/elasticsearch/pull/58016) have been merged and backported as appropriate. The deprecation warning will be added in a follow-up PR.

**Comment by gwbrown** [comment]
I've opened https://github.com/elastic/elasticsearch/issues/63448 to cover the deprecation warnings and defaults changes in 8.0 (if necessary). As the original behavior described in this issue has long since been addressed, I'm going to close this issue.
