### ISSUE TITLE
Allow elastic-keystore to optionally show values.

### ISSUE THREAD

**Issue by maihde** [elastic/elasticsearch#57261]
Debugging issues related to the keystore are very difficult because `elastic-keystore` has no option to show the values in the keystore.  In my situation, I was trying to debug why the S3 repository wasn't working and it ultimately turned out that the keystore had blank values in it.  Had I been able to quickly confirm the contents of the keystore a significant amount of time would have been saved.

Presumably this was done as a "security" feature but the primary security of the keystore comes from two sources: (a) access control mechanisms on the file and (b) encrypting the keystore with a password. If an adversary has access to the keystore file and knows the password, then reading the secure values can be easily accomplished with about 40 lines of Java

```
    public static void main( String[] args )
    {
        try {
            if (args.length == 0) {
                System.err.println("Path to config folder must be provided");
                return;
            }

            final Path path = Paths.get( args[0] );
            char[] password = new char[0];
            // IMPORTANT - Passing a password via command-line isn't secure
            // because it can be read by others with the 'ps' command.
            if (args.length >= 2) {
                password = args[1].toCharArray();
            }

            KeyStoreWrapper ksw = KeyStoreWrapper.load(path);
            if (ksw != null) {
                ksw.decrypt(password);
            }

            for (String k : ksw.getSettingNames()) {
                SecureString v = ksw.getString(k);
                System.out.println(k + " : " + v);
            }
        } catch ( Exception e) {
            System.err.println("Unhandled error: " + e);
        }
    }
```

As such, limiting the functionality of `elastic-keytool` doesn't appear to provide significant security benefits.

That said, I can see the value in the default mode of operation not printing values because someone may be capturing output the output or have shoulder surfers, but the risk of an _opt-in_ capability to display the values using `elastic-keystore` does not appear to materially affect the security of the keystore itself.

I appreciate your consideration of this feature request and welcome feedback.

**Comment by w39hh** [comment]
maihde thanks for the convincing recommendation, and the code. Had the same issue and made a quick Java utility jar using your code to inspect the contents of the keystore to debug the accessing a S3 bucket.  Works great.

**Comment by rjernst** [comment]
We discussed this issue with core/infra today. We have discussed it before several times before over the last couple years. The original choice to omit a read function for the keystore was for security reasons, but not those described here. Instead, the concern was that output could be unintentionally captured by a sloppy shell script. At the time, we were modeling the ES keystore after the java keystore, which similarly does not have the ability to dump key material from the command line.

However, since then we have seen the need for this feature several times. We acknowledge the importance of being able to verify the contents of the keystore. And we accept that other tools, like gpg, do allow outputting the key material via explicit commands. Thus, we have changed our position on this from our previous thinking, and are now ok with adding a new subcommand to the keystore cli which will output the value of a single key (note that we do not want to try to support batch reading since eventually the key values may be binary, and even in the case of file values right now there could be newlines).

I'm going to mark this as `adoptme`. If someone wants to add the feature, it shouldn't be that difficult, but we don't have the cycles right now to focus on it.

**Comment by jkakavas** [comment]
@rjernst Is the summary in https://github.com/elastic/elasticsearch/issues/57261#issuecomment-824434329 a representation of our current position on this ? I realize that there has been some concerns raised after this decision was communicated but I am not sure if there has been a reconsideration or a new stance. Do we need to have a round of discussions around this or are we ok to move forward with  implementation ?

We'd like to take this up withing the es-security team and implement this functionality as it resolves a requirement of a use case for Security ON by default. We will be generating password protected PKCS#12 keystores on behalf of the users and we will be storing said passwords in the elasticsearch keystore. It would be helpful if users can read passwords in order to see/change the contents of the PKCS#12 keystores if they wish to do so.

**Comment by rjernst** [comment]
@jkakavas The summary above is still valid; we are in support of adding limited support as described.
