### ISSUE TITLE
ES reindex remote timeout, need pagination feature

### ISSUE THREAD

**Issue by vrcsekhar** [elastic/elasticsearch#57376]
HI all,

i whitelisted a remote host and trying to reindex from remote host to my local ES,
However each time the request is failing with 502 gateway timeout with only pulling 5000 docs. 
how can i proceed and is the remote host reindex api supports pagenation? so i can loop through and get all the remote host indices.

I tried with socket_timeout option still it time out.
Error i get in kibana:
```
{"statusCode":502,"error":"Bad Gateway","message":"Client request timeout"}
```
I'm posting below query in Kibana.
```
POST /_reindex?pretty
{
  "source": {
    "remote": {
      "host": "http://xyz:9200",
       "socket_timeout": "1m",
      "connect_timeout": "60s"
    },
    "index": "xxx"
  },
  "dest": {
    "index": "xxx"
  },

}
```

**Comment by vrcsekhar** [comment]
@nik9000 I opened a new issue for reindex api gateway timeout for remote host with huge indices. Can you please suggest any latest api fixes. Also, is there pagenation available where i can reindex from and to and proceed with reindex even with timeouts

**Comment by nik9000** [comment]
Is that an error message from Kibana or from Elasticsearch? Like, if you do the reindex with `curl` do you get the same thing?

**Comment by vrcsekhar** [comment]
@nik9000 Thanks for the response, yes with curl i'm able to reindex from remote host , but it is only pulling 10000 docs from remote and stopping, is there a scroll option in reindex api.? is default size 10000?

**Comment by nik9000** [comment]
> @nik9000 Thanks for the response, yes with curl i'm able to reindex from remote host , but it is only pulling 10000 docs from remote and stopping, is there a scroll option in reindex api.? is default size 10000?

The reindex API scrolls by default and runs all documents by default. It shouldn't be stopping.

If it works with curl but times out in kibana then it is kibana timing out waiting for it. I believe your choices are to use [wait_for_completion=false](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html#docs-reindex-task-api) and poll for the results or to leave kibana. Keep in mind, though, that if you connect to Elasticsearch through a firewall it is likely to chop your connection in 10 minutes or something like that.

So far these seems like the kind of thing we'd prefer be on discuss.elastic.co because it isn't so much a bug with reindex as it is confusion about how to use it. That being said, if you have any ideas for how to make the docs more clear I'm all ears.

**Comment by vrcsekhar** [comment]
Sure Nik closing the issue, i don't have any issue with the reindex api it's the client connection i'm unable to keep (curl\kibana\ powershell invoke_webrequest etc). 
Basically reindex api is get and post from remote to dest and i'm able to achieve it with a workaround solution using .net code.
