### ISSUE TITLE
Infer date field format during indexing.

### ISSUE THREAD

**Issue by itiyamas** [elastic/elasticsearch#57394]
Parsing a stricter format is much more efficient than the optional formats for date-fields using DateTimeFormatter. For time-series use-cases, the format for a date rarely changes over time- hence it would be easier to infer the right format during parsing and then use it with a fallback on user provided/default formats. This would really help improve the parsing overhead during indexing.

The stricter could be adaptively inferred whenever a optional format is used and can be auto-corrected when the date parsing fails with the optional format, with some limit on auto-correction count over time.

I saw close to 5% improvement in indexing throughput on http_logs benchmark just by changing the format from optional to stricter.

**Comment by pgomulka** [comment]
@itiyamas If I understand correctly you are using a default date field format `strict_date_optional_time||epoch_millis` where `strict_date_optional_time` itself is containing a lot of optionals. These optionals were necessary because of flexibility we want to allow when parsing partial dates (skipping parts of the date like minutes, hour etc). You suggest to infer a format during ingestion and keep it in order to speed up parsing of future data.
I am afraid that enhancement is not possible with current state of date parsing in elasticsearch.

However I think you can easily work around by providing a custom date format when creating mapping which will not contain an optional part.

Let me know if this would be sufficient.

**Comment by pgomulka** [comment]
closing as no feedback was provided
