### ISSUE TITLE
Index settings object is parsed on every document update

### ISSUE THREAD

**Issue by itiyamas** [elastic/elasticsearch#57395]
[Parsing index settings for every doc update](https://github.com/elastic/elasticsearch/blob/97de3064b289549e447e288da675adf957b89314/server/src/main/java/org/elasticsearch/index/mapper/ParseContext.java#L335) is inefficient and redundant. Instead of parsing the settings object to get the `maxAllowedNumNestedDocs`, we could just get the cached value and change it via settings applier.  Else, we could just get this once per shard bulk request.
I saw close to 2% improvement in indexing throughput of nyc_taxis just by changing this on ES version 7.4.

**Comment by jasontedor** [comment]
It wouldn't feel great to me to treat this setting special. I'd prefer that we do something more general like parse once and cache the parsed and validated value internal to the `Settings` object, so that the next time we get the setting value we can use the internal cache and skip parsing and validation there. That will involve some boxing for settings of primitive type, but I suspect that will be okay, and there's ways around it if it proves to be a problem. What do you think of this idea @rjernst?

**Comment by rjernst** [comment]
I wonder why this isn't parsed in the IndexSettings ctor like other index settings? It seems like this should be a member there, then no parsing is necessary here.

**Comment by itiyamas** [comment]
Agreed, a new member should be added that will be updated via settings consumer.

**Comment by jasontedor** [comment]
The problem that I have with this approach is that it doesn’t work for index settings registered in X-Pack.
