### ISSUE TITLE
ES Kuromoji Tokenizer removes (株) if present in katakana writing system

### ISSUE THREAD

**Issue by HarshadRanganathan** [elastic/elasticsearch#57614]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.1.1

**Plugins installed**: [analysis-icu, analysis-kuromoji, discovery-ec2, repository-s3]

**JVM version** (`java -version`): 12.0.1 (bundled jdk)

**OS version** (`uname -a` if on a Unix-like system): Linux amzn2.x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

ES Kuromoji Tokenizer removes (株) if present in katakana writing system.

Sample text: （株）巴商会
Expected tokens: （株）, 巴商会
Actual tokens: 巴商会

**Steps to reproduce**:

1. Create an index e.g. kuromoji with below settings to use kuromoji_tokenizer in search mode:

```
{
	"settings": {
		"analysis": {
			"analyzer": {
				"kuromoji_analyzer_search_mode": {
					"type": "custom",
					"tokenizer": "kuromoji_tokenizer_search_mode"
				}
			},
			"tokenizer": {
				"kuromoji_tokenizer_search_mode": {
					"type": "kuromoji_tokenizer",
					"mode": "search"
				}
			}
		}
	}
}
```

 2. Send below request to analyze API for the index created previously
```
GET /kuromoji/_analyze
{
 "text": ["（株）巴商会"],
 "analyzer": "kuromoji",
 "explain": true
}
```

3. Analyse API returns one token where (株) in the input text is missing

```
{
  "detail" : {
    "custom_analyzer" : false,
    "analyzer" : {
      "name" : "kuromoji",
      "tokens" : [
        {
          "token" : "巴商会",
          "start_offset" : 3,
          "end_offset" : 6,
          "type" : "word",
          "position" : 0,
          "baseForm" : null,
          "bytes" : "[e5 b7 b4 e5 95 86 e4 bc 9a]",
          "inflectionForm" : null,
          "inflectionForm (en)" : null,
          "inflectionType" : null,
          "inflectionType (en)" : null,
          "keyword" : false,
          "partOfSpeech" : "名詞-固有名詞-組織",
          "partOfSpeech (en)" : "noun-proper-organization",
          "positionLength" : 1,
          "pronunciation" : "トモエショーカイ",
          "pronunciation (en)" : "tomoeshokai",
          "reading" : "トモエショウカイ",
          "reading (en)" : "tomoeshōkai",
          "termFrequency" : 1
        }
      ]
    }
  }
}
```

4. Provide the same text as input at https://www.atilika.org/ where you can test kuromoji analyzer.

It provides two tokens （株）, 巴商会.

Seems the kuromoji analyzer is working as expected but the corresponding ES plugin is having an issue processing this text.

Other text samples for testing:
栃木金属工業（株）
ミマスクリーンケア（株）

**Comment by jimczi** [comment]
> Provide the same text as input at https://www.atilika.org/ where you can test kuromoji analyzer.
It provides two tokens （株）, 巴商会.
Seems the kuromoji analyzer is working as expected but the corresponding ES plugin is having an issue processing this text.

The `unidic` dictionary that is used internally by Lucene contains an entry for `（株）`. This means that it considers the full-width parenthesis as part of the token. The Kuromoji tokenizer is setup to remove punctuations by default (discard_punctuation is true) so the token is removed because it starts with a full-width parenthesis. However the expectation in the code is that punctuations are separated from other tokens  which is why the check is done only on the first character. This dictionary entry breaks this assumption so the fix should be in Lucene.
I opened https://issues.apache.org/jira/browse/LUCENE-9390 to discuss the possible mitigations so I hope you don't mind if I close this issue.  In the meantime, the workaround is to use a custom user dictionary that overrides the tokenization for  `（株）`.
