### ISSUE TITLE
"updating number_of_replicas" log messages for ILM-enabled but non-existent index

### ISSUE THREAD

**Issue by pmuellr** [elastic/elasticsearch#57706]
Starting in Kibana 7.8, we're creating a new index with an ILM policy associated with it.  We're seeing the following message logged every 10 minutes, which seems excessive, references a non-existent index, and it's not clear if there's some action that needs to be taken:

```
[o.e.c.r.a.AllocationService] updating number_of_replicas to [0] for indices [.kibana-event-log-7.8.0-000002]
```

A `cat/indices` only shows an index `.kibana-event-log-7.8.0-000001` - the `000002` version does not exist (AFAICT).

Some info on our index / ILM:

- the code to create the ILM policy and index template are here (hopefully it's easy to following; linked primarily just to show the JSON): https://github.com/elastic/kibana/blob/master/x-pack/plugins/event_log/server/es/documents.ts

- the initial index is created empty with the following options:

```
{
        aliases: {
          ".kibana-event-log-7.8.0": {
            is_write_index: true,
          },
        },
```

- everything seems to be operating fine
- there will be at least one document indexed into the index, shortly after it's created, and then in many cases won't have any documents indexed after that for some time - the messages start getting logged immediately after ES starts though

This issue was first posted in the Kibana repo: https://github.com/elastic/kibana/issues/68121

**Comment by dakrone** [comment]
I don't think this is ILM-related, the `AllocationService` is reacting to the `auto_expand_replicas: '0-1'` setting in the Kibana template. This indicates something with the allocation code, not ILM.

**Comment by ywelsch** [comment]
This is caused by https://github.com/elastic/elasticsearch/pull/53965 I think, which now  precomputes the new cluster state before simulating the rollover (which is triggered every 10 minutes by ILM). The logging which is referred to here happens while that cluster state is being computed. I'm not sure why we need to call `AllocationService.reroute` on that temporarily created cluster state, but that triggers this logging.

@henningandersen can you have a look? Two options here: 1) Move the logging elsewhere 2) Not use AllocationService for these kind of simulation steps.

**Comment by ywelsch** [comment]
Another issue to investigate here is that `TransportRolloverAction` is executing on `ThreadPool.Names.SAME`, and computing a new cluster state update incl. computing balancing of shards etc. can in a large cluster take seconds.
