### ISSUE TITLE
Provide a mechanism for securely indexing internally irrespective of license

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#58117]
I need to write some data that Elasticsearch generates internally to an index. This needs to be possible in both OSS and with Security. I talked to @albertzaharovits and he advised that this scenario isn't really supported right now.

Context:

I want to be able to write the deprecation logs that Elasticsearch generates into a data stream. Under OSS, this will of course just work, but I also need this to work under Security, without intervention or configuration from the user.

**Comment by pugnascotia** [comment]
Related: https://github.com/elastic/elasticsearch/issues/46106

**Comment by tvernum** [comment]
I think this should be entirely possible if it follows the same pattern as Tasks - see https://github.com/elastic/elasticsearch/pull/35667

**Comment by albertzaharovits** [comment]
Thanks @tvernum for pointing to the tasks example. I understand that you mean using the `OriginSettingClient` with some appropriate origin (probably a new one).

I failed to point @pugnascotia to this class during our discussion. My recommendation was to using `ClientHelper` which, unlike `OriginSettingClient` sits in `xpack` not in `server`, which made it not viable in this case. At first though I did not realise it is trivial to use "origins" outside of `xpack`, but my excuse is that I was thrown off by
> We’re thinking that other parts of the Stack will also write to this data stream, and they’ll do so with the normal ES APIs e.g. no dedicated API

because origins outside of `xpack` won't help in this case.

@pugnascotia Given the description of the issue, I understand that internal ES indexing is sufficient in this stage?

For indexing outside of ES, my thoughts were to discuss making the particular index accessible either:
- to some/all built-in users/roles
- to all authenticated users
- to unauthenticated users

**Comment by pugnascotia** [comment]
Thanks both, `OriginSettingClient` looks perfect. I'll use the existing `deprectation` origin, since that's the subject of my changes.

Regarding external indexing, the data stream should definitely require an authenticated user. I hadn't considered requiring a particular role, but since the data stream is intended for a particular purpose, that sounds like a good idea. I don't know how indexing monitoring data works, but there are similarities with this work.

**Comment by jaymode** [comment]
Monitoring utilizes a dedicated endpoint. The users need roles that grant permission to the monitoring API and internally the monitoring code uses an internal user for the actual indexing into the monitoring index.

**Comment by pugnascotia** [comment]
Closing this issue as `OriginSettingClient` does what I need.
