### ISSUE TITLE
Randomize codecs per field 

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#5830]
today we don't randomize the codecs when we run the tests. We should randomize them using our random index template.

**Comment by s1monw** [comment]
we removed this feature really so I am closing this one.

**Comment by rmuir** [comment]
I have a simple solution for this, can be solved as part of #10656, or after it, that adds an internal "lucene_default" to CodecService. This just uses Codec.getDefault() for the raw unfiltered lucene default codec, which is randomized by LuceneTestCase.

Some tests rely on the custom postings format in ES (the completion suggester tests and rest tests), and a few other tests wire the lucene default codec, but these can all be simplified to just use `SuppressFileSystems("*")`. 

Otherwise, i think let LuceneTestCase do it, it will only find bugs because of things like AssertingCodec that we have.

**Comment by rmuir** [comment]
I hooked this in here: https://github.com/elastic/elasticsearch/commit/b09d236fc0bf2763dd69140e4b7f5fa0cc22a48b

For now we just use AssertingCodec: it found several bugs immediately: #10660, #10661. I had to mark 3 tests with AwaitsFix for those issues.
