### ISSUE TITLE
Snapshot repo security_exception / SocketPermission

### ISSUE THREAD

**Issue by LucaWintergerst** [elastic/elasticsearch#58409]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.8.0

**Plugins installed**: []

**JVM version** (`java -version`): Elastic Cloud

**OS version** (`uname -a` if on a Unix-like system): Elastic Cloud

**Description of the problem including expected versus actual behavior**:
Reading from a snapshot repository that was created a few days ago fails:
```
GET _snapshot/manual-test2/_all
```
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "security_exception",
        "reason" : "access denied (\"java.net.SocketPermission\" \"metadata.google.internal:80\" \"connect,resolve\")"
      }
    ],
    "type" : "security_exception",
    "reason" : "access denied (\"java.net.SocketPermission\" \"metadata.google.internal:80\" \"connect,resolve\")"
  },
  "status" : 500
}
```

Trying to re-create that repo with a key from a few days ago fails: 
```
PUT _snapshot/manual-test5
{
  "type": "gcs",
  "settings": {
    "bucket": "foobar-snapshots",
    "base_path": "path/to/bucket"
  }
}
```
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "blob_store_exception",
        "reason" : "Unable to check if bucket [eden-snapshots] exists"
      }
    ],
    "type" : "repository_exception",
    "reason" : "[manual-test5] cannot create blob store",
    "caused_by" : {
      "type" : "blob_store_exception",
      "reason" : "Unable to check if bucket [foobar-snapshots] exists",
      "caused_by" : {
        "type" : "security_exception",
        "reason" : "access denied (\"java.net.SocketPermission\" \"metadata.google.internal:80\" \"connect,resolve\")"
      }
    }
  },
  "status" : 500
}
```

These repositories use a json key, added to the clusters using the Cloud UI or API.  
The keys are definitely valid. Re-adding the same key under a different name fixes it for new repositories. 

**Steps to reproduce**:
We _think_ that this starts to fail after a while. From @original-brownbear `I think it tries to eventually refresh some information from the metadata endpoint and then fails to do so with the permissions we allow`

**Comment by original-brownbear** [comment]
This is quite confusing to me. I'm wondering if this really is an issue with the plugin and not a result of some orchestration removing the key again behind the scenes (thus causing the plugin to fall back to some metadata auth path). I could not reproduce this so far and I have not seen this happen in the logs for our own default repo+credentials. I'll bring it up during todays snapshot resiliency sync so we can track down the root cause of this.
Regardless, maybe it's fine to allow the `resolve` permission for the plugin so we can at least get an easier to interpret error message in this case. I'll look into that and will open a PR once the deeper issue has been identified.

**Comment by paulcoghlan** [comment]
@original-brownbear - as discussed, you can look for `manage-keystore.sh` (wrapper around keystore binary) in the allocator service logs:  https://aws-eu-central-1-logging-staging-cloud.elastic.co/goto/e9fde89186ead7b0266ec5e628cae095

This will tell you if/when the keystore got updated.

**Comment by ywelsch** [comment]
Can we close this?

**Comment by original-brownbear** [comment]
Yea let's close it this was fixed in Cloud.
