### ISSUE TITLE
Support for GC Collection usage stats

### ISSUE THREAD

**Issue by Bukhtawar** [elastic/elasticsearch#58522]
## Problem Description

JVM stats published today represents the point in time usage of the heap across pools. While 
`MemoryPoolMXBean#getCollectionUsage` based on [docs](https://docs.oracle.com/javase/8/docs/api/java/lang/management/MemoryPoolMXBean.html#getCollectionUsage--) 

"_Returns the memory usage after the Java virtual machine most recently expended effort in recycling unused objects in this memory pool_" 

provides a better indicator of GC throughput. This would typically be of interest for Old gen. If the collection usage increases it most likely indicates some trouble.

**Comment by Bukhtawar** [comment]
If this changes sounds reasonable @nik9000 I would want to work on a PR plan for the same. Please let me know

**Comment by nik9000** [comment]
> If this changes sounds reasonable @nik9000 I would want to work on a PR plan for the same. Please let me know

I'm probably not the right person to ping on this. There are folks who work more consistently on the cure/infra stuff all the time that *should* respond to this. I think I accidentally removed the team tag so they didn't get pinged properly. Sorry!

**Comment by pgomulka** [comment]
@Bukhtawar we discussed this within the team and decided that we won't be picking up this work.
We use `MemoryPoolMXBean#getusage` which is an estimate of the current memory usage. If you feel you need to investigate GC (and looks like that's what you want as you want getCollectionUsage) our advice would be to look int oG logs instead of metrics exposed via JMX.

I will therefore close the issue.
