### ISSUE TITLE
_routing without hash function / with custom hash function

### ISSUE THREAD

**Issue by halaei** [elastic/elasticsearch#58634]
Currently, the following formula is used to compute the shard number base on _routing param:

    shard_num = hash(_routing) % num_primary_shards

In which the hash function seems not be configurable. It is desirable to be able to disable hash function, provided _routing param is a valid integer.
### My use case
We have ~1 million documents, half of which are visible to all the users, and the other half only searchable by admin users. Since we have a lot more end-users than admin users, it is not efficient to put all the documents in the same shard, which is a waste of CPU for search operations. So the documents should be somehow separated for end users, so that they search only within ~500k documents while occasional admin searches being done in both partitions.
I have 2 implementation options for this use-case:
1. Use _routing parameter: the problem with this approach is that I don't know how to set _routing parameter to be sure that the documents are really stored in 2 different shards. So there is always a chance of having 1 shard on 1 million documents while the other shard is empty.
2. Store documents in 2 different indices: the problem with this approach is that this change is not as transparent to my client code as option 1. I have to make more changes to my queries, and make sure to delete document from 1 index and insert it into the other when the public visibility of document is changed; the details which have already been handled by Elasticsearch if _routing was possible without hash function.

So any chance to a configuration in future releases to have a custom hash function / disable it for routing? Or maybe I must stick to option 2 or other alternative?

**Comment by nik9000** [comment]
>     2\. Store documents in 2 different indices

When I had a similar problem many years ago that is what I did. In my case, though, documents could never "move" from one partition to the other. They were forever "public" or "admin". "Moving" a document from on index to another isn't something you can do atomically so it would have been sad.

For what it is worth I'm against allowing folks to directly control the target shard because I think it is likely to be surprisingly "breaky". It'd be fairly incompatible with the work we've done to split and join shards. 

If documents frequently change from public to private and back then you probably should use a flag on the document. Anything else is not going to be atomic. And you shouldn't try to route based on public or private because `_rounting` can't change. If you change the routing for a document then you'll end up with two copies and a sad index.

If you are super concerned about keeping the statistics for those indices separate (I was) then two indices still might be the best approach here.

I guess the problem with trying to set the routing is that if you did you'd *still* have to send a `delete` and reindex with the new routing. You'd still have to change your application. I don't think it'd end up much simpler than just having two indices.

**Comment by jtibshirani** [comment]
Because of the concerns that @nik9000 has highlighted, I plan to close out the issue.

@halaei please feel free to reopen or file a new issue if you we think missed something important. The [discuss forums](https://discuss.elastic.co/) could also be a good place to gather more feedback on your use case.
