### ISSUE TITLE
Tests in fips mode fail with JDK15

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#58644]
**Build scan**: https://gradle-enterprise.elastic.co/s/ttilod4hhmvje ( indicative example ) 

**Repro line**: N/A

**Reproduces locally?**: yes

**Applicable branches**: all

Since we started using build29 of JDK15 ea, tests fail in fips mode since an exception is thrown when attempting to get an instance of SecureRandom. This is reported in http://bouncy-castle.1462172.n4.nabble.com/Default-SecureRandom-issue-in-BCFIPS-and-latest-JDK15-td4659964.html and https://mail.openjdk.java.net/pipermail/security-dev/2020-June/022157.html

**Comment by jkakavas** [comment]
This is tracked upstream in https://bugs.openjdk.java.net/browse/JDK-8248505

**Comment by rjernst** [comment]
@jkakavas The upstream JDK bug has been fixed (build 31) and we should be using a newer build (I see at least build 34 in our CI). Can you check if fips will work with jdk15 to close this issue?

**Comment by tvernum** [comment]
@ywangd If you get time, do you want to look at this while @jkakavas is out?

**Comment by ywangd** [comment]
@tvernum Yes I'll take a look. Thanks

**Comment by ywangd** [comment]
I can confirm that a previously failed test now passes locally with JDK 15 b33 and FIPS enabled. So I think we are in position to re-enable the tests for JDK 15. However, there are a few issues:

1. Although the test passed, the Gradle build itself failed because [`fips.gradle`](https://github.com/elastic/elasticsearch/blob/master/gradle/fips.gradle#L29) uses a deprecated Gradle feature. The warning message is something like:
> The configuration :modules:aggs-matrix-stats:extraFipsJars was resolved without accessing the project in a safe manner.  This may happen when a configuration is resolved from a different project. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.5/userguide/viewing_debugging_dependencies.html#sub:resolving-unsafe-configuration-resolution-errors for more details.
>
I checked the above link briefly, but it is not obvious to me how it can be fixed. @rjernst Could you please help out here? If I specify `--warning-mode none` on the CLI, everything works, but I don't think it's the correct way to fix things :)

2. The periodic fips [projects](https://elasticsearch-ci.elastic.co/view/Elasticsearch%20master/job/elastic+elasticsearch+master+matrix-java-periodic-fips/) currently always fail on the CI. As far as I can tell, they fail very early on when configuring the projects and complain about
```
18:17:25 FATAL: No such property: openjdk15 for class: groovy.lang.Binding
18:17:25 groovy.lang.MissingPropertyException: No such property: openjdk15 for class: groovy.lang.Binding
18:17:25 	at groovy.lang.Binding.getVariable(Binding.java:63)
18:17:25 	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:270)
18:17:25 	at org.kohsuke.groovy.sandbox.impl.Checker$7.call(Checker.java:353)
18:17:25 	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:357)
18:17:25 	at org.kohsuke.groovy.sandbox.impl.Checker$checkedGetProperty.callStatic(Unknown Source)
18:17:25 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56)
18:17:25 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:194)
18:17:25 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:230)
18:17:25 	at Script1.run(Script1.groovy:2)
18:17:25 	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runScript(GroovySandbox.java:162)
18:17:25 	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.run(GroovySandbox.java:269)
18:17:25 	at hudson.matrix.FilterScript.evaluate(FilterScript.java:45)
18:17:25 	at hudson.matrix.FilterScript.apply(FilterScript.java:85)
18:17:25 	at hudson.matrix.Combination.evalGroovyExpression(Combination.java:101)
18:17:25 	at hudson.matrix.Combination.evalGroovyExpression(Combination.java:91)
18:17:25 	at hudson.matrix.MatrixProject.rebuildConfigurations(MatrixProject.java:658)
18:17:25 	at hudson.matrix.MatrixProject.getRunConfiguration(MatrixProject.java:691)
18:17:25 	at hudson.matrix.MatrixBuild$MatrixBuildExecution.doRun(MatrixBuild.java:370)
18:17:25 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
18:17:25 	at hudson.model.Run.execute(Run.java:1880)
18:17:25 	at hudson.matrix.MatrixBuild.run(MatrixBuild.java:323)
18:17:25 	at hudson.model.ResourceController.execute(ResourceController.java:97)
18:17:25 	at hudson.model.Executor.run(Executor.java:428)
```
So if I understand it correctly, we haven't had any FIPS enabled tests for a while (> 1 month). I compared the configurations with the non-fips projects and I did not find any difference that could cause the problem. So is it hardware (test workers) related?

3. I don't have permission to edit the configurations. Or are the configurations managed in another code base?

**Comment by ywangd** [comment]
Linking it here for context: @breskeby raised #60802 to fix the Gradle usage deprecation issue.

**Comment by rjernst** [comment]
The error in (2) is due to a misconfiguration when the fips job was disabled. The configuration is indeed in another repro. Now that the tests should work, we will get that re-enabled. Since the original failure mentioned here is now fixed, I'm going to close this issue. Thanks for the help @ywangd and @breskeby.
