### ISSUE TITLE
SQL: IN operator incorrectly handling specified date format

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#58932]
Given a field with the mapping:
```
"datetime0" : {
    "type" : "date",
    "format" : "yyyy-MM-dd' 'HH:mm:ss"
}
```
and a query with the `IN` filtering: `SELECT datetime0 FROM idx WHERE datetime0 IN ('2000-11-11 11:11:11'::timestamp)` will raise an exception:
```
"root_cause" : [
      {
        "type" : "parse_exception",
        "reason" : "failed to parse date field [2000-11-11T11:11:11Z] with format [yyyy-MM-dd' 'HH:mm:ss]: [failed to parse date field [2000-11-11T11:11:11Z] with format [yyyy-MM-dd' 'HH:mm:ss]]"
      }
    ]
```
The query executes correctly with the equality operator.
Data in the index is irrelevant (the index can contain no documents).

**Comment by bpintea** [comment]
The equality will generate a `range` query, that accepts a `format` while the `IN` operator will generate a `terms` query, which doesn't support a format-describing parameter.
`'2000-11-11 11:11:11'::timestamp` converts the literal to `2000-11-11T11:11:11Z`, which can't be parsed according to the specified (ES) `date` mapping. A solution might be to rather translate `IN` with dates to `bool` with `should` `range`s?

**Comment by wuyinan0126** [comment]
In `IN` operator, the ExpressionTranslator<In> translates expression into terms query, but when the expression is date format, the terms query get unexpected results. This commit changes the terms query into bool should query when data type is `DATETIME`.

The original translation of `IN ('2000-11-11 11:11:11'::timestamp)` was below, which got the error `failed to parse date field [2000-11-11T11:11:11Z] with format [yyyy-MM-dd' 'HH:mm:ss]: [failed to parse date field [2000-11-11T11:11:11Z] with format [yyyy-MM-dd' 'HH:mm:ss]]`, beacause the terms format is not the same as defined:

```
{
  "query" : {
    "terms" : {
      "datetime0" : [
        "2000-11-11T11:11:11.000Z"
      ],
      "boost" : 1.0
    }
  }
}
```

In this commit, the `IN ('2000-11-11 11:11:11'::timestamp)` translates to:
```
{
  "query" : {
    "range" : {
      "datetime0" : {
        "from" : "2000-11-11T11:11:11.000Z",
        "to" : "2000-11-11T11:11:11.000Z",
        "include_lower" : true,
        "include_upper" : true,
        "time_zone" : "Z",
        "format" : "strict_date_time",
        "boost" : 1.0
      }
    }
  }
}
```

And the `IN ('2000-11-11 11:11:11'::timestamp, '2000-11-11 22:22:22'::timestamp)` translate to:
```
{
 "query" : {
    "bool" : {
      "should" : [
        {
          "range" : {
            "datetime0" : {
              "from" : "2000-11-11T11:11:11.000Z",
              "to" : "2000-11-11T11:11:11.000Z",
              "include_lower" : true,
              "include_upper" : true,
              "time_zone" : "Z",
              "format" : "strict_date_time",
              "boost" : 1.0
            }
          }
        },
        {
          "range" : {
            "datetime0" : {
              "from" : "2000-11-11T22:22:22.000Z",
              "to" : "2000-11-11T22:22:22.000Z",
              "include_lower" : true,
              "include_upper" : true,
              "time_zone" : "Z",
              "format" : "strict_date_time",
              "boost" : 1.0
            }
          }
        }
      ],
      "boost" : 1.0
    }
  }
}
```

Finally, the problem is solved:

```
SELECT datetime0 FROM idx WHERE datetime0 IN ('2000-11-11 11:11:11'::timestamp)

       datetime0        
------------------------
2000-11-11T11:11:11.000Z
```
