### ISSUE TITLE
[CI] Vagrant problems in opensuse-42 distroTests

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#59144]
Various instances of what looks like startup issues of vagrant to me.
Not sure if this is limited to the opensuse-42 distroTests, but here are some samples from
resent history:

https://gradle-enterprise.elastic.co/s/2vego3qd5mzk6/console-log#L1157
https://gradle-enterprise.elastic.co/s/bv4ax5o77vp22/console-log#L9901
https://gradle-enterprise.elastic.co/s/j6r6r3hn7vzky/console-log?anchor=800

I'm not sure if they are related, point to infrastructural issues, thus opening for further investigation.

**Comment by rjernst** [comment]
We've seen these problems before, and they seem squarely in the realm of infrastructure related. One possibility is our vagrant images being so out of date: https://github.com/aidanns/vagrant-reload/issues/4. Note that we have already removed support for opensuse-42 in master, but it would be good to get these stable since 7.x will live for quite a while longer. But I don't think there is anything we can do from the Elasticsearch side, as this occurs just trying to launch the VM in vagrant.

**Comment by mark-vieira** [comment]
Vagrant jobs have been removed.
