### ISSUE TITLE
admin/shards/search_shard "disconnected"

### ISSUE THREAD

**Issue by Guruhbk** [elastic/elasticsearch#59207]
**Elasticsearch version** (`bin/elasticsearch --version`):5.6.0

**Plugins installed**: []

**JVM version** (`java -version`):11

**OS version** (`uname -a` if on a Unix-like system): windows 12 server

**Description of the problem including expected versus actual behavior**:
I'm trying to hit the kibana URL in the browser. While doing that I'm getting **admin/shards/search_shard "disconnected"** Error in the red banner. After sometimes. shards recover automatically. This happening regularly. 

PS: Our clusters are communicating via the firewall. 

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Not using kibana for a while
 2. Hitting the URL in the browser
 3. Could see the red banner error in kibana.

Any help would be appreciated. 

**Provide logs (if relevant)**:

**Comment by DaveCTurner** [comment]
This sounds like an issue with your network rather than an Elasticsearch bug so I am closing this. Additionally, 5.6.0 is well over a year past the [end of its supported life](https://www.elastic.co/support/eol). It's possible that some on the [community forums](https://discuss.elastic.co) can help you investigate this further.
