### ISSUE TITLE
Regression when an API key has no name

### ISSUE THREAD

**Issue by tylersmalley** [elastic/elasticsearch#59481]
https://github.com/elastic/elasticsearch/pull/58156 introduced a regression causing the following errors within Kibana:

```
   │ info [o.e.x.s.a.AuthenticationService] [desktop] Authentication using apikey failed - apikey authentication for id NB-BSnMBuA9FcpEJrQtR encountered a failure
   │      org.elasticsearch.common.xcontent.XContentParseException: [1:532] [api_key_doc] name doesn't support values of type: VALUE_NULL
```

These failures are being tracked in https://github.com/elastic/kibana/issues/71559, https://github.com/elastic/kibana/issues/71558 and https://github.com/elastic/kibana/issues/71555

**Comment by ywangd** [comment]
@tylersmalley I raised #59485 to fix this issue.

We consider API keys with `null` names as a bug and raised an issue (#59484) for it. Creating API keys always require a name to be specified. However, when grant API key action is added, this requirement is missed out. We plan to fix it in a future release (post v7.9). For backwards compatibility, we will continue to support API keys without names internally. But the API will be updated so that the API key name is mandatory for granting API keys. Please note Kibana's usage of granting API keys needs to be updated when #59484 is fixed. Thanks!
