### ISSUE TITLE
Change Password API - support password_hash?

### ISSUE THREAD

**Issue by mjwhale** [elastic/elasticsearch#59500]
Why is password hash not supported when changing a password?
https://www.elastic.co/guide/en/elasticsearch/reference/7.x/security-api-change-password.html

https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-put-user.html

When adding a user, one of password or password_hash is required.  password_hash allows the client to pre-hash the password for performance and/or confidentiality reasons.

Thanks

**Comment by bytebilly** [comment]
Thanks for the proposal.
Do you have a specific use case where this additional parameter would be useful?

In general, we are not against that. However, this is not a trivial change and we need to understand if this could be prioritized.

**Comment by mjwhale** [comment]
Thanks for the update.

I may have misunderstood the purpose of password_hash when creating a new user: its to protect the password, improve security and performance? wouldn't 'change password' warrant the same kind of protection?

Wouldn't/shouldn't users change their password on first use and therefore render ineffective the benefit of using the password_hash during user creation?

Using password_hash on password change would allow good security principles to be followed by applications that manage user access to ElasticSearch.  

I am not particularly saying that this is a major requirement, it just appears to be contradictory to suggest password_hash is to improve security and performance, but is only available on user creation.

Many thanks

Mike

**Comment by bytebilly** [comment]
As said, we do think that it would be helping in some cases, but we just don't see it as a priority since the required changes are not trivial. That's why, even if it may come in the future, it has not been scheduled yet.

From a security perspective, I'd expect password changes to be performed via tools (like Kibana), where there is no support for `password_hash` and it could not be used anyway. Adding support in other tools is an option, but it requires even additional effort.

From a performance perspective, bulk creation of users via config management tools (e.g. during initial setup) is a pretty common scenario, while massive password changes are probably not. Performance impacts are relevant mainly in the former case.

I hope this clarifies that it is just a matter of priorities, not being against the improvement.

**Comment by mjwhale** [comment]
Thank you both for the comments.  I am happy with the responses.
