### ISSUE TITLE
Delete Replica with ILM on Hot Nodes

### ISSUE THREAD

**Issue by contrerasgm** [elastic/elasticsearch#59580]
Currently if you have an index that has been rolled over but still on the hot tier with a Primary and Replica I cannot use ILM to drop the replica after a specified period of time. It seems you would either have to reindex into a new index with no replicas or you would have to migrate to a warm/cold node to be able to do this. 

For example if I have two nodes that I do daily indexes with 1 Primary and 1 Replica and I keep these indexes for 30 days. After 10 days I don't really search them much and don't necessarily care if data becomes unavailable. With my two nodes I can easily fit 10 days of indexes with a replica and 20 more days of indexes without a replica and have great performance. Without this feature I have to have a 3rd node just so I can drop a replica. I don't need that node for performance, or storage space or anything else but just so I can drop a replica. It is very inefficient. While reindexing would cause a lot of unnecessary IO just so I could drop a replica. Both current options are very inefficient while adding this feature to ILM could easily simplify things.

**Comment by dakrone** [comment]
We discussed this today and decided that there isn't enough interest in this, especially as there are a number of workarounds, first, there is no need to add a node to move to a different ILM phase, so moving to `warm` and dropping the replica is a valid alternative. Additionally, for this behavior immediately after rolling over the `searchable_snapshot` action exists in the `hot` phase so that the index can be converted to using 0 replicas (using a snapshot repo as a replica) immediately after writes are complete. With those in mind, we are going to close this.
