### ISSUE TITLE
Bug of Term Suggester

### ISSUE THREAD

**Issue by letrungtrung** [elastic/elasticsearch#5967]
Suggester wills return fail results if suggest mode is missing. 

I have example: 

 #analyzer
        index:
        analysis:
        analyzer:
        vi_analyzer:
        type: custom
        tokenizer: whitespace
        filter: [trim, lowercase, hunspell_vi]
        filter:
        hunspell_vi:
        type: hunspell
        locale: vi_VN

  
 # delete the index
 curl -XDELETE localhost:9200/test

  # insert a document
  curl -XPUT localhost:9200/test/test/1?refresh=true -d '{
   "title": "bong bay"
  }'

  curl -XPUT localhost:9200/test/test/2?refresh=true -d '{
   "title": "ba bong bong"
  }'

  curl -XPUT localhost:9200/test/test/3?refresh=true -d '{
   "title": "ba bong bay"
  }'

# Refresh
 curl -XPOST 'http://localhost:9200/test/_refresh'

 # Suggest
 curl -XPOST 'localhost:9200/_suggest' -d '{
  "_suggestion" : {
    "text" : "ba",
    "term" : {
      "field" : "title",
      "suggest_mode": "missing",
      "sort" : "score",
      "min_word_length" : 1	
    }
  }
 }'

 # Results
{"_shards":{"total":10,"successful":10,"failed":0},"_suggestion":[{"text":"ba","offset":0,"length":2,"options":[{"text":"bay","score":0.5,"freq":1}]}]}

**Comment by dakrone** [comment]
@areek can you follow up with this?

**Comment by areek** [comment]
In `missing` mode, the suggested term is only checked for existence at the local shard. The document(s) with the token `bay` are present only in certain shards.
In order to use the `missing` mode correctly in this situation, all the relevant document(s) should reside in the same shard (e.g. adding `routing=xyz` to all the index requests will do the right thing)
