### ISSUE TITLE
geoShapeQuery constructor supports new fields

### ISSUE THREAD

**Issue by zhongweikang** [elastic/elasticsearch#59825]
I want to use geoshape filter to retrieve the currently indexed polygon from another indexed polygon

I saw the prototype of GeoShapeQuery looks like this
`public static GeoShapeQueryBuilder geoShapeQuery(String name, String indexedShapeId, String indexedShapeType);`

It seems that the two fields indexedShapeIndex and indexedShapeFieldName are missing. If these two fields are supported, then I can use the following query.
```json
curl -X POST http://localhost:9200/someindex_1/_doc/_search
{
  "query": {
    "geo_shape": {
      "location_shape": {
        "relation": "intersects",
        "indexed_shape": {
          "index": "someindex_2",
          "type": "_doc",
          "id": "1111",
          "path": "location"
        }
      }
    }
  }
}
```

my version is 6.8.10

**Comment by nik9000** [comment]
It looks like this issue is about adding the other ctors for the GeoShapeQueryBuilder into the QueryBuilders class for the clients. I've never been a huge fan of QueryBuilders but I think we should add them to be consistent. In the mean time, you can work around this by calling the constructor directly.
