### ISSUE TITLE
invalid JAR packaging of high-level rest client by delivering com.sun.jna with elasticsearch jar 

### ISSUE THREAD

**Issue by remmeier** [elastic/elasticsearch#59830]
**Elasticsearch version** 5.8

![image](https://user-images.githubusercontent.com/8008853/87860807-bdf10280-c940-11ea-9e9f-6d342540bdb2.png)

we have a project where two third-party components make use of jna. Because elastic uses a custom distribution in an own JAR, Gradle cannot resolve the conflict and bundles both versions into the application, which in turn causes errors when attempting to actually use the classes

Elasticsearch should make proper use of https://github.com/java-native-access/jna rather than attempting  to bundle it on its own.

**Comment by jasontedor** [comment]
Re-packaging JNA for distribution in our artifacts is a deliberate choice, so that we only package native libraries for platforms that we support. The underlying problem here is not the re-packaging, but that a server dependency so easily leaks into client applications. For that, we want to eventually separate the client from the server: #41228. Therefore, I'm closing this issue in favor of that one.
