### ISSUE TITLE
[CI] Active monitoring task still active after Rest tests

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#60003]
**Build scan**:

https://gradle-enterprise.elastic.co/s/mjl3zjba3apcy

**Repro line**:

./gradlew ':x-pack:plugin:integTestRunner' --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=ml/jobs_crud/Test job with categorization_analyzer and categorization_filters}" \
  -Dtests.seed=7BC21AB0D777E7C1 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-AR \
  -Dtests.timezone=EST5EDT \
  -Druntime.java=8 \
  -Dtests.rest.blacklist=getting_started/10_monitor_cluster_health/*

**Reproduces locally?**:

No

**Failure excerpt**:

java.lang.AssertionError: 1 active tasks found:
cluster:monitor/health         P7VSfHgSTUOhe7KGIPB_Mg:40214 -                            transport 1595348305874 16:18:25 10.2s       127.0.0.1 integTest-0 
 expected:<0> but was:<1>
	at __randomizedtesting.SeedInfo.seed([7BC21AB0D777E7C1:F396256A798B8A39]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.elasticsearch.test.rest.ESRestTestCase.lambda$waitForPendingTasks$3(ESRestTestCase.java:415)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:951)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:924)
	at org.elasticsearch.test.rest.ESRestTestCase.waitForPendingTasks(ESRestTestCase.java:391)
	at org.elasticsearch.xpack.test.rest.XPackRestIT.cleanup(XPackRestIT.java:210)

**Comment by davidkyle** [comment]
The problem is not limited to the ml test there have been several failures recently due to a leaking monitoring task in the 7.9 and 7.x branches. 

The error message is the same as above 
```
java.lang.AssertionError: 1 active tasks found:
cluster:monitor/health BLAH BLAH TASK ID
```

@elastic/es-core-infra Could these Rest Test failures (leaking monitoring task) on the 7.x branch be related to the Rest Test changes in #56841


https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-60d,mode:quick,to:now))&_a=(columns:!(_score,build.branch,branch,test,message,class,build_url,build-id),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:e58bf320-7efd-11e8-bf69-63c8ef516157,key:class,negate:!f,params:(query:org.elasticsearch.xpack.test.rest.XPackRestIT,type:phrase),type:phrase,value:org.elasticsearch.xpack.test.rest.XPackRestIT),query:(match:(class:(query:org.elasticsearch.xpack.test.rest.XPackRestIT,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:e58bf320-7efd-11e8-bf69-63c8ef516157,key:branch,negate:!f,params:!('7.9','7.x',master),type:phrases,value:'7.9,%207.x,%20master'),query:(bool:(minimum_should_match:1,should:!((match_phrase:(branch:'7.9')),(match_phrase:(branch:'7.x')),(match_phrase:(branch:master))))))),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:waitForPendingTasks),sort:!(time,desc))

**Comment by cbuescher** [comment]
I'm seeing similar looking issues again today:

https://gradle-enterprise.elastic.co/s/dpl5qkagdqw52

https://gradle-enterprise.elastic.co/s/dpl5qkagdqw52/tests/:x-pack:plugin:integTestRunner/org.elasticsearch.xpack.test.rest.XPackRestIT/test%20%7Bp0=transform%2Ftransforms_update%2FTest%20alias%20scenarios%7D#1

The tests in error are:

XPackRestIT » test {p0=ml/calendar_crud/Test get calendar events for job}
XPackRestIT » test {p0=transform/transforms_update/Test alias scenarios}

The errors look like:
```
java.lang.AssertionError: 1 active tasks found:
cluster:monitor/health         dxZoiv4RToiuKbRNg_7VYw:73620 -                            transport 1600225891039 03:11:31 11.2s       127.0.0.1 integTest-0 
 expected:<0> but was:<1>
	at __randomizedtesting.SeedInfo.seed([22A12C53C17B5157:AAF513896F873CAF]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.elasticsearch.test.rest.ESRestTestCase.lambda$waitForPendingTasks$3(ESRestTestCase.java:415)
```

I'm adding the monitoring lable although this might be a test infra issue after all, maybe @elastic/es-core-infra can direct this in the right direction.

**Comment by hendrikmuhs** [comment]
another failure: https://gradle-enterprise.elastic.co/s/nd4kpc7c35pbg

**Comment by jbaiera** [comment]
This might be misclassified as monitoring. It doesn't seem to be related to the monitoring plugin but rather to the cluster health action.

This is quite an old issue though. Did a search through build stats and found that this hasn't been a problem for a while now: https://build-stats.elastic.co/goto/45496f850579336dd2435f8c7b1444f8

I think it's safe to close this out. We can reopen or create a new issue if it rears its head again.
