### ISSUE TITLE
Expose constant fields used by script

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#60001]
This will allows runtime fields to validate that scripts only use fields available and facilitate cycle detection.

* One advanced feature here is users only see doc as part of the "main" method in Painless. If doc is passed into a user-defined function this must be tracked and the parameter in the function must also add constant fields used as part of doc.

* Handle doc aliasing (`def foo = doc`).

Related: https://github.com/elastic/elasticsearch/issues/59332

**Comment by jdconrad** [comment]
Some notes based on @stu-elastic first PR: this covers simple doc usage in the main method only. This needs to be extended to track doc into user-defined methods. However, one very important note is we still need to check for cycles at runtime unless we prevent doc from assignment and restrict it to only methods we know are not using assignment. Otherwise, we can lose track if the user decides to assign doc to a data structure such as a List or Map. We must also only allow doc to be referenced by String constants.

**Comment by stu-elastic** [comment]
Next tasks:
* Remove ability to assign `doc` to anything, we lose track of doc access if so
* Allow "read only" variables to be used as doc accessors, `String a = "foo"; return doc[a];" should still work as long as `a` is never updated.

Pending optional compiler phases: https://github.com/elastic/elasticsearch/issues/59647

**Comment by stu-elastic** [comment]
@javanna is there anything runtime fields needs here beyond https://github.com/elastic/elasticsearch/pull/60158?

**Comment by javanna** [comment]
@stu-elastic we should be good for now, thanks!
