### ISSUE TITLE
Composite aggs should support missing

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#60043]
Composite aggs allows the user to specify `"missing_bucket":true` which has been implemented for rollup to handle sparse data. 

For transform it would be good to support `missing` in addition, see #48243

### missing_bucket

 - maps non-existing fields to a bucket with key null
 - its not possible to collapse the bucket into the bucket of the same value, e.g. if you want a default

### missing

 - maps non-existing fields to a bucket with a given key, key must not be null
   - the key can clash on purpose with an existing bucket, so you can collapse buckets, e.g. "missing":0 in a histogram
 - allowing `"missing": null` would be possible as it is valid json, however for high-level clients this is problematic as some default to remove the whole entry if the value is `null`, therefore it's better to keep disallow `null` and handle this specific case with `"missing_bucket":true`

### Solution

Composite aggs should support `missing`(+ it would be good if aggregations support `missing_bucket` for feature parity).

From a user perspective the 2 parameters might cause some confusion, because it's not clear whether you have to set `missing_bucket` to `true` if you set `missing`. Therefore it seems best to ignore `missing_bucket` if `missing` is set or make both parameters mutually exclusive.

**Comment by markharwood** [comment]
A user reported today that while upgrading from 6.x to 7.x they noticed the `missing` parameter had gone missing.

It turns out this was a feature of the composite agg but was deprecated with [this change](https://github.com/elastic/elasticsearch/commit/e33d107f840602344774d1b71774d04f834c74e0#diff-704dcd25b7f87c6dd8cad4be6000efce6e23867fecf864e669542352db1e498cR244). I don't know what the rationale was for removing, just adding a note here as it's likely relevant.

**Comment by markharwood** [comment]
>I don't know what the rationale was for removing, 

I spoke to Jim today. Apparently the reason for originally removing the `missing` option from composite was that there were complications related to roll ups involving multiple indices.  Best to ask Jim for more details on that.

**Comment by wchaparro** [comment]
closing as not planned.
