### ISSUE TITLE
Wrong publish_address format in ipv6 network

### ISSUE THREAD

**Issue by chengyang14** [elastic/elasticsearch#60115]
Elasticsearch version (bin/elasticsearch --version): 7.6.0

On an ipv6 network, `network.host` is set to `_local`_, and `network.publish_host` is not configured.

network.host will be  parsed as: 
```
"[::1]:9200",
"127.0.0.1:9200"
```
```
GET /_nodes/http?pretty
```

```
"http": {
  "bound_address": [
    "[::1]:9200",
    "127.0.0.1:9200"
  ],
  "publish_address": "0:0:0:0:0:0:0:1%lo/[::1]:9200",
```

In this scenario, publish_address is better to use `ip：port` format then `hostname/ip:port` because` 0:0:0:0:0:0:0:1%lo` is not an
avalible hostname.

The rest client sniffer needs to parse publish_address to obtain the IP address, `"0:0:0:0:0:0:0:1%lo/[::1]:9200"` will cause sniffing exceptions.

**Comment by original-brownbear** [comment]
Right this is broken. The problem is in this check:

https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/http/HttpInfo.java#L68

```
        if (InetAddresses.isInetAddress(hostString) == false) {
            publishAddressString = hostString + '/' + publishAddress.toString();
        }
```

Our `isInetAddress` utility doesn't understand the scope ID on the address and thinks it's a host name. I think we can just fix that method to understand scope IDs here.

**Comment by chengyang14** [comment]
@original-brownbear   Thanks for your analysis,I will solve this problem.
