### ISSUE TITLE
Can we make scripts less error-prone with missing values?

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#60148]
This problem was shared with me by @timroes.

A common source of errors with search scripts is when some documents miss a value. For instance if your script is `doc['foo'].value.length()` and one document that matches the query doesn't have a value for `foo`, you'll get an exception. Where this hurts is that even users that tests their scripts on subsets of their data are subject to this problem if only a minority of documents doesn't have a value for a field.

I wonder if there is anything we could do to make this less trappy. One thing that came to mind is updating examples in our docs to make more general use of the null-safe operator when applicable, but I wonder if there are other things we could do to make this less trappy?

**Comment by stu-elastic** [comment]
Null-safe operator as currently defined is not relevant, the array is empty.

`.value` returns the zero index value.

For a field that has no values, this what we return
```json
  "caused_by": {
    "type": "illegal_state_exception",
    "reason": "A document doesn't have a value for a field! Use doc[<field>].size()==0 to check if a document is missing a field!"
  }
```

The other place where this comes up is no mappings in which case the map lookup will fail with a key error.  The user needs to check `containsKey`.
```json
  "caused_by": {
    "type": "illegal_argument_exception",
    "reason": "No field found for [<field>] in mapping with types []"
  }
```

**OR** we could fix `getByPath` to avoid this error:

```
{
  "script": {
     "inline": "return doc.getByPath('def.0', -1);", 
     "lang": "painless"
  }
}
```

We have `getByPath` allows a default value passed in, let's extend that concept for handling doc, which only have one depth of keys.

Two options moving forward:
* Augment `Map` to provide `get(<field>, <default>)` and `get(<field>, <default>, <index>)` where the former returns the first DocValue if it exists, or it returns the default.  The later has the same behavior but allows you to specify an index other than first.  In that case, if there would be an `ArrayIndexOutOfBounds`, we'd return the default.
This would look like `doc.get('foo', 1)` and would handle missing mappings and missing values.

* Create a class binding such as `docValue(<field>, <default>)/docValue(<field>, <default>, <index>)` that does the same but lets us access `LeafDocLookup` directly which would ensure we're only doing this for a `doc` rather than all maps.

That would look like `docValue('foo', 1)`.  Main problem is it's a weird special function rather than looking like something that's using `doc`.

I vote for the former.

**Comment by stu-elastic** [comment]
We can also add an `doc.exists` that checks for both `containsKey` and `length > 0`
eg
`doc.containsKey('foo') && doc['foo'].length`.

Punting that for another time.

**Comment by stu-elastic** [comment]
> I wonder if there is anything we could do to make this less trappy.

The only problem with requiring a default is, if this is in an agg, the user probably wants the document skipped rather than averaging in a zero, say.  So `get` with default is still a _little_ trappy.  However an enhanced `exists` could help them in that case.

**Comment by wmelton** [comment]
This is not specific to scripts. For example, bool queries using 'should' clauses can blow up or blow up silently by returning only a subset of results because it stopped executing when it reached a null value without returning an error (which makes it nearly impossible to debug). However, If you add a 'must':'exists' clause to it, runs as expected. 

Seems like too much expectation is put on users to understand that there is a missing field that has snuck in rather than just skipping null/empty/length=0 values for those documents, especially in scenarios where partial results sets (and not errors) are being returned. 

I know this issue is specifically about scripting, but it seems like this problem bleeds in to more traditional query execution too.

**Comment by rjernst** [comment]
> Seems like too much expectation is put on users to understand that there is a missing field that has snuck in rather than just skipping null/empty/length=0 values for those documents

The "skipping" behavior used to exist in scripting, in a way, as using the `.value` when no values existed would return a "default" value for the type of that field. The value chosen was completely arbitrary, and created confusion (for example, aggregating that default value, and conflating with docs that actually contained that value). This is why we moved in late 6.x to being explicit about this error.

While it is true we are putting the expectation to handle this on users, I don't think it is something that Elasticsearch can reasonably do on its own.  "Skipping" is very context dependent; if you have a filter script in a conjunction, should skipping mean a match, or not a match? To the search code, the filter script just returns a boolean as to whether a match exists. Painless would then have to not only not error when `.value` is called with no values, but turn this into returning `false` from the script (assuming you wanted it to not be a match). What if the code was in the middle of a loop? Or what if the script had several fields it was inspecting to determine if a match exists, yet by accessing a field with no values, we would silently fail the match. There are too many plausible scenarios for the behavior a user may want that painless and the scripting api cannot make this determination. This is why we elevated this case to an error, so that the user is forced to make a decision, rather than it being trappy with implicit behavior that they may not be aware of.

That being said, one thing I think we could do is improve the way doc values (and source) are accessed. If the methods to retrieve a value from the doc were to require a second argument with a default value, we could enforce at compile time that the user has made a choice. We could also simply add such an accessor, and improve the error message in the case of no values so that we suggest using the alternate method taking a default.

**Comment by jdconrad** [comment]
I definitely like allowing a user to specify a default value here in some way for scripting. It's just a matter of deciding where/how is the appropriate way to do this.

**Comment by wmelton** [comment]
> This is why we elevated this case to an error, so that the user is forced to make a decision, rather than it being trappy with implicit behavior that they may not be aware of.

@rjernst I definitely get what you are saying there for sure. Challenge in my mind is that in the examples I've come across where this creates heartburn is that results are returned up until a null field or missing field is encountered and then execution stops and docs found up to that error are returned. 

However, the heartburn is that the response does not indicate an error has occurred, so a query with a `size: 5` clause on it that returns `1` result looks like thats all that was found, when in fact, there were a lot of documents that matched, but an error occurred silently.

So I guess my main point is that if a null value is encountered, and no filter logic has been applied, shouldn't default just be to skip it? 

I get that ES can't handle every scenario, but if a null value or missing value is encountered, it seems like either an error should be thrown and that error returned (instead of a partial result set and the error suppressed) OR the doc should just be skipped and as many matching documents with fields that were populated should be returned with their score. 

Exists/Filters/Etc would still do their job in this case.

**Comment by rjernst** [comment]
> However, the heartburn is that the response does not indicate an error has occurred,

This seems like a bug. If a script encountered an error, that should fail the request, or rather it fails the shard request, which should be viewable in the collated response.

**Comment by stu-elastic** [comment]
This relates to fields API.

**Comment by rjernst** [comment]
The fields API provides a new way to handle missing values explicitly by providing a default when accessing a field. I do not think we would want to change the existing behavior of .value, so I'm going to close this issue as complete.
