### ISSUE TITLE
Aggregations order

### ISSUE THREAD

**Issue by gitterhh** [elastic/elasticsearch#60180]
It will be helpful to have possibility to specify in which order to return the aggregations, for example to return aggregations in same order they were added in the request.
May be as a solution it will be to receive and return aggregations as a list.

**Comment by nik9000** [comment]
We've traditionally thought of the results that come back from a search as small enough that you can buffer them in memory and order them however you like. We buffer them in memory before we send them. Could you explain why this is a thing you need?

We did allow you to order highlighters years and years ago because I built a highlighter plugin that would skip highlighting if the last result matched. So we have precedent for this sort of thing.

**Comment by wchaparro** [comment]
Closing, no specified use case.
