### ISSUE TITLE
Perform OR operation using two or more script tag

### ISSUE THREAD

**Issue by Mamta92** [elastic/elasticsearch#60304]
I have a use case where a user can perform >=,<=,= operations and their corresponding values using a dropdown.
I want to see results where (SubjectId = 1002 OR SubjectId= 1001) or may be (Grades >= 1 OR Grades <=3).
I have tried the following using ES:-

`{
  "size": 0,
  "from": 0,
  "query": {
    "bool": {
      "must": [
        {
          "script": {
            "script": {
              "source": "InternalSqlScriptUtils.nullSafeFilter(InternalSqlScriptUtils.eq(InternalSqlScriptUtils.cast(InternalSqlScriptUtils.docValue(doc,params.v0),params.v1),params.v2))",
              "lang": "painless",
              "params": {
                "v0": "SubjectId.keyword",
                "v1": "DOUBLE",
                "v2": 1002
              }
            }
          }
        }
      ],
      "should": [
        {
          "script": {
            "script": {
              "source": "InternalSqlScriptUtils.nullSafeFilter(InternalSqlScriptUtils.eq(InternalSqlScriptUtils.cast(InternalSqlScriptUtils.docValue(doc,params.v0),params.v1),params.v2))",
              "lang": "painless",
              "params": {
                "v0": "SubjectId.keyword",
                "v1": "DOUBLE",
                "v2": 1001
              }
            }
          }
        }
      ]
    }
  }
}`

Adding a JSON link of query also for reference:- https://jsoneditoronline.org/#left=cloud.6e6573ae5dd14d04ab2132944bb37e19&right=local.rafosu

Using the above query returns only results with SubjectId 1002 and not 1001(OR operation should return both). Suppose 1002 SubjectId has total 100 results and 1001 has total 50 results. It only returns 100 results.

How can the query be modified to return the addition of both the results?

**Comment by jimczi** [comment]
I am surprised that you use these internal script functions that should only be used internally by SQL. 
Is there a specific reason why you ended up using them in a normal query ?
They are not intended to be used directly, instead you should switch to a `match` or a `term` query rather than a `script`.
We reserved github for verified bugs and feature requests so I hope you don't mind if I close this issue. The [forum](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6) is better suited for this kind of question so I suggest you to open a topic there next time. 

Regarding your question, the `must` clauses are mandatory so your query will match documents that "must" contain the term `1002`. If you want to perform a real `OR`, you'll need to put the clauses under the `should` section.
