### ISSUE TITLE
Freedman-Diaconis histogram

### ISSUE THREAD

**Issue by GopherJ** [elastic/elasticsearch#60312]
Sometimes it can be hard to choose histogram interval, Freedman-Diaconis rule is a good example to calculate number of bins to have better distributions, sadly it's not supported in elasticsearch

**Comment by polyfractal** [comment]
Would be nice I agree!

Similar to https://github.com/elastic/elasticsearch/issues/50386 and https://github.com/elastic/elasticsearch/issues/50120, I think this would require [multi-pass agg support](https://github.com/elastic/elasticsearch/issues/50863) because we'd need a single pass over the data to determine the IQR first, then a second pass to bucket the documents.

Could expose a parameter if the user provides the IQR and count, but that's not very user-friendly.

Side note: the new [variable width histogram](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/search-aggregations-bucket-variablewidthhistogram-aggregation.html) might interest you, and we're planning to do an "auto-histogram" (https://github.com/elastic/elasticsearch/issues/31828) similar to auto-date-histo which merges together buckets using some kind of deterministic scheme (powers of 10 or something).  Not as nice as something like Freedman-Diaconis, but possible to do in a single pass.

Cheers for the request!  Will keep this in mind as we consider multi-pass aggs!

**Comment by wchaparro** [comment]
This is not something we plan to implement in the near future in aggregations, and has been superceded by our focus on ESQL. Closing as not planned. If your feel strongly about this one, please let us know.
