### ISSUE TITLE
LICENSE.txt file should be renamed as LICENSE

### ISSUE THREAD

**Issue by AjitTK** [elastic/elasticsearch#60711]
Hi, 
As per open source standard project license details should be in "LICENCE" file not in "LICENSE.txt" file.
https://www.freecodecamp.org/news/how-open-source-licenses-work-and-how-to-add-them-to-your-projects-34310c3cf94/

**Comment by tvernum** [comment]
The article you link to says:
> You need to add a LICENSE, LICENSE.txt or LICENSE.md in the root directory of your repository.

If you go the [root project](https://github.com/elastic/elasticsearch) for Elasticsearch and look at the links on the right, the "View license" link shows the `LICENSE.txt`.

Based on the above, it doesn't seem like there's any sort of problem here. Is there a specific reason you think something is wrong?

**Comment by AjitTK** [comment]
Hi @tvernum  

LICENSE is valid file to specify license not a license.txt , if we scan elastic search jar with any oss review software it fail to detect the license.

**Comment by tvernum** [comment]
> LICENSE is valid file to specify license not a license.txt

I don't understand why you believe this to be true. The article you linked to says that `LICENSE.txt` is valid, as does the [GitHub documentation](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#determining-the-location-of-your-license), and the filename is also used by other Open Source projects such as [WordPress](https://github.com/WordPress/WordPress/blob/master/license.txt) and [TypeScript](https://github.com/microsoft/TypeScript/blob/master/LICENSE.txt).

> if we scan elastic search jar with any oss review software it fail to detect the license.

Since you haven't named the software that your using, it's hard to give an exact answer, but my guess is that you are incorrectly interpreting the results of the scan.
Thus repository uses 2 main licenses - some of the repository is under the Open Source "Apache 2.0 license", and some is under our custom "Elastic license". Therefore our license file is not a standard OSS license - it's actually just an explanation of which license applies to which code.
Software scanners cannot detect the license type because we don't have a single, standard licence. Renaming the license file wouldn't help - it still won't be a standard license that the scanner can detect and analyse.

**Comment by AjitTK** [comment]
ok @tvernum ,What I assume is artifact of this repo should contain OSS license , as of now artifact contains LICENSE.txt file . So I am thinking if we rename LICENSE.txt to LICENSE then artifact of this repo would contain LICENSE file and they would be OSS compliance .

**Comment by rjernst** [comment]
@AjitTK As Tim pointed out, the article you referenced notes that both `LICENSE` and `LICENSE.txt` are mentioned as acceptable. However, there is no standard. That is simply based on the expectations of github in order to properly show a project's license automatically. In Elasticsearch's case, a link for "View License" can be seen on the main project page, since we have a complex license that depends on the file/directory within the source. For something like Apache Lucene, it also shows a message "Apache-2.0 License".

However, it sounds like you are not talking about the source code, but instead the jars we produce. We embed the license, whether the apache 2.0 license for oss code, or the Elastic license for commercial code, in each relevant jar. This license file, as you have noted, is named LICENSE.txt. The name of the file does not determine if a license is oss, but instead the contents do. If you are using a tool to inspect jars to find their license, I suggest you go back to that tool's author and ensure both that common license file names can be found (since both the mentioned filenames are common), and that custom licenses can be configured, such as Elastic's license.

Given that our project uses very common naming for this file, I am going to close this issue, as we do not plan to change it.
