### ISSUE TITLE
EQL: multiple indices with commas not working

### ISSUE THREAD

**Issue by rw-access** [elastic/elasticsearch#60793]
Docs say we supporting multiple indices
https://github.com/elastic/elasticsearch/blob/dca46c29fff1f77ba4c27f07a33d2895a96a1bba/docs/reference/eql/eql-search-api.asciidoc#L45-L51

**no results found when searching two patterns with a comma**
![image](https://user-images.githubusercontent.com/31489089/89465044-b4cca780-d72e-11ea-803a-16bbd0ae7666.png)

**just one index pattern**
![image](https://user-images.githubusercontent.com/31489089/89465089-c57d1d80-d72e-11ea-90be-4b23dddbc50b.png)

**Comment by rw-access** [comment]
There also seems to be this peculiar bug
```javascript
// 1 result found
GET logs-endpoint.alerts-default/_eql/search
{
  "query": """
    any where true
  """
  ,
  "size": 1
}
```
```javascript
// Unknown index [logs-endpoint.process-default]
GET logs-endpoint.process-default/_eql/search
{
  "query": """
    any where true
  """
  ,
  "size": 1
}
```
```javascript
// no error, no results
GET logs-endpoint.alerts-default,logs-endpoint.process-default/_eql/search
{
  "query": """
    any where true
  """
  ,
  "size": 1
}

**Comment by dgieselaar** [comment]
I'm running into (probably) the same issue. But the bug seems to trigger in slightly different scenarios:

**Returns results:**
`GET apm-8.0.0-span/_eql/search` (alias, matches 3 indices)
`GET apm-8.0.0-span-2020.07.31-000001/_eql/search` (index)
`GET apm-8.0.0-span-2020.07.31-*/_eql/search` (matches 1 index)

**Does not return results:**
`GET apm-8.0.0-span-*/_eql/search` (matches 3 indices)
`GET apm-*/_eql/search` (matches all APM data indices)
`GET _all/_eql/search` (matches all indices)

FWIW, I've added a `filter` that should exclude any data that is not in the `apm-8.0.0-span` indices.
