### ISSUE TITLE
Support audit ignore policy by action

### ISSUE THREAD

**Issue by wutingbupt** [elastic/elasticsearch#60877]
We have lots of bulk write operations which will produce around 500-600GB audit log events and we think that is too much since most of them are related (90% of them):

`{"type":"audit", "timestamp":"2020-08-10T10:02:18,036+0200", "node.id":"VflKv3IKT1iL5rre6PGOOw", "event.type":"transport", "event.action":"access_granted", "user.name":"elastic", "user.realm":"reserved", "user.roles":["superuser"], "origin.type":"rest", "origin.address":"127.0.0.1:54454", "request.id":"514DjCkJQfmnoxjQIZ30lw", "action":"indices:data/write/index:op_type/create", "request.name":"BulkItemRequest", "indices":["2020-08-07"]}"
`

We want to get rid of this logs from the audit systems (Which will help us save more 90% of the disks), I have read the corresponding audit filters and policy provided by Elastic, but I don't see there is an option we can filter out by the "action" field. It would be even better if it can filter by the combination of request.name, action, and index.

----- 
### Original Report:

**Elasticsearch version** (`bin/elasticsearch --version`):
7.7.1

**Plugins installed**: []

**JVM version** (`java -version`):
1.8.0_232

**OS version** (`uname -a` if on a Unix-like system):
#56~18.04.1-Ubuntu

**Description of the problem including expected versus actual behavior**:
I would like to filter out some audit activities by the log4j regex filter, however, it seems there is some problem to filter out.

Here is the audit log produced:
`{"type":"audit", "timestamp":"2020-08-10T10:30:41,681+0200", "node.id":"VflKv3IKT1iL5rre6PGOOw", "event.type":"transport", "event.action":"access_granted", "user.name":"elastic", "user.realm":"reserved", "user.roles":["superuser"], "origin.type":"rest", "origin.address":"127.0.0.1:55202", "request.id":"5so0C_m9SJSw3J1EbMUbMQ", "action":"indices:data/write/index:op_type/create", "request.name":"BulkItemRequest", "indices":["2020-08-07"]}
`
I can see the regex works well if I only want to filter by the content of any json filed, such as .*indices:data/write/index:op_type/create.* or .*request.name.*

However, if I want to filter it out with more precise regex, such as .*"action":"indices:data/write/index:op_type/create".*

Then nothing will happen.

It seems the double quote and colon are not identified properly.

**Steps to reproduce**:
1. Download fresh elastic 7.7.1 and unpack it
2. Update elaticsearch.yml to enable json based audit log
`xpack.security.enabled: true
xpack.security.audit.enabled: true
`
3. Config audit log log4j regex filter: such as:

```
appender.audit_rolling.filter.regex.regex = .*"action".*
appender.audit_rolling.filter.regex.onMatch = DENY
appender.audit_rolling.filter.regex.onMismatch = ACCEPT
```
4. Run the elastic and produce some audit log:
`curl -u elastic:123456 -X POST "localhost:9200/_bulk?pretty" -H 'Content-Type: application/json' -d'
{ "create" : { "_index" : "2020-08-07", "_id" : "1" } }
{ "field1" : "value1" }
{ "create" : { "_index" : "2020-08-07", "_id" : "2" } }
{ "field1" : "value3" }
{ "create" : {"_id" : "1", "_index" : "2020-08-07"} }
{ "doc" : {"field2" : "value2"} }
`
5. We can monitor from audit log file that none of audit log is filtered because the regex contains double quote.
6. If we try to update the regex like this:
`appender.audit_rolling.filter.regex.regex = .*action.*
`
Then it works. The similar problem also happens for the colon.

If we define the regex like this:
`appender.audit_rolling.filter.regex.regex = .*request\\.name\.*:.*BulkItemRequest.*`

This will not work.

However, if I remove the colon, it works again.
`appender.audit_rolling.filter.regex.regex = .*request\\.name\.*BulkItemRequest.*`

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1.To run the following to create the audit log behavior
`curl -u elastic:123456 -X POST "localhost:9200/_bulk?pretty" -H 'Content-Type: application/json' -d'
{ "create" : { "_index" : "2020-08-07", "_id" : "1" } }
{ "field1" : "value1" }
{ "create" : { "_index" : "2020-08-07", "_id" : "2" } }
{ "field1" : "value3" }
{ "create" : {"_id" : "1", "_index" : "2020-08-07"} }
{ "doc" : {"field2" : "value2"} }
`

 2.No mapping is needed
 3.special setting for log4j:
```
appender.audit_rolling.filter.regex.regex = .*"action".*
appender.audit_rolling.filter.regex.onMatch = DENY
appender.audit_rolling.filter.regex.onMismatch = ACCEPT
```
4. special setting for elaticsearch.yml
```
xpack.security.enabled: true
xpack.security.audit.enabled: true
```

**Provide logs (if relevant)**:

**Comment by tvernum** [comment]
As far as I can tell this is due to the fact that the formatting of the audit log is actually handled as a layout on the appender, and log4j filters act on events not formatted messages.

That is, what log4j sends through the filter is a `LogEvent` that has a message with a map of Key-Values (a log4j `StringMapMessage`).  It does not pass the JSON formatted output to the regex filter.

If you _really_ want to use log4j to filter on the audit messages you need to filter on the message map.

The question though, is _why_ you want to do this. We offer a range of supported audit filters already, why do you want to filter by regex?
Attempting to make this work at the log4j level is dangerous - we make no commitments about the stability of that method. Anything you do there could break on any upgrade.

**Comment by wutingbupt** [comment]
Hi Tim,

Thanks for your quick response. Here is the reason why we want to do it like this way:

We have lots of bulk write operations which will produce around 500-600GB audit log events and we think that is too much since most of them are related (90% of them):
`{"type":"audit", "timestamp":"2020-08-10T10:02:18,036+0200", "node.id":"VflKv3IKT1iL5rre6PGOOw", "event.type":"transport", "event.action":"access_granted", "user.name":"elastic", "user.realm":"reserved", "user.roles":["superuser"], "origin.type":"rest", "origin.address":"127.0.0.1:54454", "request.id":"514DjCkJQfmnoxjQIZ30lw", "action":"indices:data/write/index:op_type/create", "request.name":"BulkItemRequest", "indices":["2020-08-07"]}"
`
We want to get rid of this logs from the audit systems (Which will help us save more 90% of the disks), I have read the corresponding audit filters and policy provided by Elastic, but I don't see there is an option we can filter out by the "action" field. It would be even better if it can filter by the combination of request.name, action, and index.

Pls let me know if you have a better suggestion.

Br,
Tim

**Comment by tvernum** [comment]
I'm going to remove the `>bug` label and change this to a feature request for filtering on action.

I don't think it should be classified as a bug because everything is working as intended. I also don't think we will make any changes specifically to facilitate log4j based filtering of audit messages.

That said, you can probably filter this with a [Map filter](https://logging.apache.org/log4j/2.x/manual/filters.html), but I haven't tried.

**Comment by wutingbupt** [comment]
Hi Tim,

Thanks for your suggestion and quick response.

I will close it as you suggested.

**Comment by tvernum** [comment]
I've reopened this because I think it's a useful description of the problem you need solved.

**Comment by wutingbupt** [comment]
Thanks very much.

**Comment by albertzaharovits** [comment]
@wutingbupt We've discussed this issue inside the team. We are reluctant to expand the field list that we support audit filtering on.

The `action` audit entry field is internal in comparison to the `user`, `realm`, `index` and `roles` fields which we currently allow filtering on. Defining exclusion rules on such internal fields is brittle, as the names can technically change and the predictability of the namespace structure is not a hard guarantee. Moreover it requires some knowledge of the internals to set up right. Your example of filtering out `"action":"indices:data/write/index:op_type/create"` is quite unreasonable because writes are usually the most important thing to include in the audit log. What I believe you're really after is to audit only a single event from the multitude of audit events that the bulk ingest trails. I've suggested we explicitly investigate how we can trim down the audit events for bulks, and I'll report back on this.

Alternative options, if reducing bulk auditing hits a snag, are to actually implement the requested filtering on the `action` field, as the dev effort is minimal, but **not** actually document it, for the same woes about it expressing internal behaviour. (Similarly to how roles can express permissions over actions).
Another alternative is to improve the guarantees that we offer about action names, or introduce a new similar field with the desired publicly exposed characteristics (like a "privilege" in the role context, that groups related actions).

**Comment by wutingbupt** [comment]
Hi Albert,

Thanks very much, we are using log4j so far to disable the BulkItemReqeust for a temp solution to avoid disk problem.

It would be great if could trim down a little bit the size of bulk writes related audit logs.

Br,
Tim

**Comment by tvernum** [comment]
Sorry, I missed the team discussion, so I'll add thoughts here.

I think filtering by conceptual action make sense alongside index.
That is, if we can filter by index, then there's a logic to saying that you care about what was done on the index. A user creating documents in the index might be normal, and not something that needs to be audited, but updating or deleting is exceptional and should be audited.

We can decide that this is not a good use of filters and should be done in post processing, and/or we can decide that `action` is a difficult field to filter by, but the idea makes sense to me (particularly within bulk requests).

**Comment by BBQigniter** [comment]
more audit filter options are definitely needed, please. for example I only need to know if someone deletes or updates something. also combinations of filters wouldn't be a bad idea, like "if a defined user name produced some defined action from a list of ips it should not be logged".

@wutingbupt you were writing about 500-600G - was that per day? and can you please perhaps post your log4j example, please. that would be great.

**Comment by BBQigniter** [comment]
is it maybe somehow possible to write those logs to a named pipe via this log4j stuff? I then would write a python-script which filters out only the things we need.

**Comment by albertzaharovits** [comment]
> is it maybe somehow possible to write those logs to a named pipe via this log4j stuff?

I _think_ this is achievable, if you can settle for a socket instead of a named pipe. The approach requires some tinkering with the `log4j2.properties` file we're shipping with, which means you'll have to take extra care during upgrades to ensure you reapply any changes to the file that comes with the upgrade to your local custom config file.

Starting from the `log4j2.properties` file of the docker build, I think you should be able to replace the `ConsoleAppender` https://github.com/elastic/elasticsearch/blob/16c795e049a80fe9f805917754853cb0a563a5eb/distribution/docker/src/docker/config/log4j2.properties#L46 with a `SocketAppender` (https://logging.apache.org/log4j/2.x/manual/appenders.html#SocketAppender). The `log4j2.properties` file of the archive build appends to a rolling file, so the change is slight bigger, but still possible.

@BBQigniter I haven't tested it. Please let us know if you've tried it, and if and how it works for you.

**Comment by BBQigniter** [comment]
@albertzaharovits thanks for the hint with the socket. I must say that I'm not a log4j-pro ;) and I tried yesterday a little bit around with the socketappender - but the results were not satisfying. 

I just quickly set up some simple listener with nc and tried to configure the audit-appender to send the logs via socket appender to that port on localhost. The first try showed me after a few seconds in the elasticsearch-logs that there was some permission (something with connect, resolve) problem. googleing around, I found that I have to add this permission into some security config - so i did in  `/usr/share/elasticsearch/jdk/conf/security/java.policy`. After that I had no error message anymore about the socketappender but it also didn't send logs for whatever reason.

As we will in future use ECK I don't want to invest too much time into this issue, and if the containers are sending the logs to console it should be fine. we can than get those auditlogs via filebeat/logstash.

for our test-servers (which are not running containers atm) I'll now have a "new" approach as I found this https://github.com/elastic/logstash/issues/7482 and I now configured in the `log4j2.properties`

```
appender.audit_rolling.filePattern = ${sys:es.logs.base_path}${sys:file.separator}${sys:es.logs.cluster_name}_audit-%i.json
appender.audit_rolling.policies.type = Policies
appender.audit_rolling.policies.size.type = SizeBasedTriggeringPolicy
appender.audit_rolling.policies.size.size = 100MB
appender.audit_rolling.strategy.type = DefaultRolloverStrategy
appender.audit_rolling.strategy.max = 5
```

so with this i can create some filtering-script or whatever which looks at the `_audit.log` and just get the most important stuff. as there should be a maximum of 5 files, each having a max of about 100mb, the log-partition also shouldn't get too full.

**Comment by BBQigniter** [comment]
On test-servers this works pretty well in combination with Filebeat and its Elasticsearch-module as we do not have that much traffic there - BUT on our current productive system Filebeat cannot keep up with the mass of auditlogs Elasticsearch is writing. Our ELK then was ddosing itself with logs (Java logs like: `Caused by: java.io.IOException: No space left on device` + the dozens of Java log-lines such logs create) after the system thought there is not enough space left as we hit this https://www.elastic.co/guide/en/beats/filebeat/master/faq-deleted-files-are-not-freed.html

This gets the whole system into a uber-FUBAR state - Elasticsearch complaining about it cannot write logs, sent via rsyslog to our Logstashes; Elasticsearch writing millions of `data/write`s into audit-logs, which then are scraped by filebeat...

This means that Filebeat is never able to keep up with scraping all needed logs from that audit.json.

We need to be able to filter events **before** they get written to the logfile easily. Also I observed high CPU usage by Filebeat already, only with this meager `processors`:

```
  - drop_event:
      when:
        and:
          - contains:
              log.file.path: "audit.json"
          - or:
              - regexp:
                  message: '"action":".*data/write'
              - regexp:
                  message: '"action":".*data\/read'
              - regexp:
                  message: '"action":".*monitor'
```

As we are on the way to move our ELK to ECK I fear we hit there the same problem, that the Filebeat Pods just cannot handle the mass of audit-logs. And on ECK the Filebeat Pods must handle even much, much more different types of logs from all the different containers.

**Comment by BigPandaToo** [comment]
[This change](https://github.com/elastic/elasticsearch/pull/67477)
will allow to filter out events by their type of actions by
creating a new audit ignore policy - privileges.

To avoid ambiguity (as cluster and index policies may
have the same name, for example - monitor) we will
 have two separate policies for index_privileges and
cluster_privileges:

xpack.security.audit.logfile.events.ignore_filters:   example1:     index_privileges: ["read", "delete"]

xpack.security.audit.logfile.events.ignore_filters:   example2:     cluster_privileges: ["read", "delete"]

Note: only one of the above filters can be created
for the same policy, if both filters are required, they
can be created with different policy names.
If both filters are created for the same policy
the IllegalArgumentExceptionwe is thrown .
