### ISSUE TITLE
fields API and docvalue_fields output get merged

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#61029]
Given the test setup from https://github.com/elastic/elasticsearch/issues/61028, for a query like

```
{
    "size": 1000,
    "_source": false,
    "fields": [
        {
            "field": "text_field"
        },
        {
            "field": "text_field.keyword_subfield"
        }
    ],
    "docvalue_fields": ["text_field.keyword_subfield"]
}
```

The output of `foo` document has `foo` duplicated and I can only assume that the outputs of `docvalue_fields` and `fields` API was merged, since the element they populate in the response is the same - `fields`:

```
        "hits": [
            {
                "_index": "test",
                "_id": "Zq3O4nMBFdprR7a5qr4z",
                "_score": 1,
                "fields": {
                    "text_field.keyword_subfield": [
                        "1234567890 asdlkfjasdf"
                    ],
                    "text_field": [
                        "1234567890 asdlkfjasdf"
                    ]
                }
            },
            {
                "_index": "test",
                "_id": "Z63O4nMBFdprR7a5qr40",
                "_score": 1,
                "fields": {
                    "text_field.keyword_subfield": [
                        "foo",
                        "foo"
                    ],
                    "text_field": [
                        "foo"
                    ]
                }
            }
        ]
```

**Comment by astefan** [comment]
@jtibshirani

**Comment by jtibshirani** [comment]
This is not surprising behavior to me, since we also merge the output of `docvalue_fields` and `stored_fields`. @astefan from your perspective, what would be a more intuitive/ useful behavior? To me it's hard to explain why one would override the other -- we don't have a concept of precedence for the 'fetch' parts of the request.

**Comment by astefan** [comment]
@jtibshirani I didn't know we also merge `docvalue_fields` and `stored_fields` outputs. The surprise (and the first thing that jumped at me as unusual) came from the duplicated data that one gets when using `fields` and `docvalue_fields`... isn't this a confusing result for a field? Is that field made of two values `foo` and `foo` , or is the data coming from duplicated fields output? I'm thinking of scenarios/situations where the duplicated output can be mistaken with a list of terms (not sure if this is possible though).

What if one uses `fields` API (which does extraction from _source for a field) and `docvalue_fields` for a `_source` with the content `FOO`. The combined output of `fields` will be `foo` (from `docvalue_fields`, assuming this is a keyword field with a lowercase normalizer) and `FOO` (from _source). Isn't this a confusing output for the same field content?

There is also the question of using two different APIs and getting a single combined result... I would have expected to get them in two separate sections in the result.

**Comment by jtibshirani** [comment]
> The combined output of fields will be foo (from docvalue_fields, assuming this is a keyword field with a lowercase normalizer) and FOO (from _source). Isn't this a confusing output for the same field content?

We actually decided to apply `keyword` normalizers to the value, so `foo` will simply appear twice. In general we try to have the output of `fields` match that of `docvalue_fields`. However I do agree it's confusing that we merge the output -- the user doesn't know if the field was an array with two values, or if we retrieved once from `fields` and once from `docvalue_fields`.

> There is also the question of using two different APIs and getting a single combined result... I would have expected to get them in two separate sections in the result.

I can definitely see how this behavior is confusing. I think the reasoning is that you might want to use different retrieval strategies for different fields (like `docvalue_fields` for one, `script_fields` for another, etc.) and have a convenient combined response. Despite the existing behavior being a bit confusing, I do think we should keep returning the response under the `fields` key, since it's the most natural place for it. 

Here are the options I see moving forward:
1. Keep the current behavior. We've talked about deprecating `docvalue_fields` and `script_fields` in favor of just using `fields`, so in the (pretty far?) future we will no longer have multiple responses combined together. 
2. Have any fields from `docvalue_fields` overwrite those from `fields` (or vice versa). The reasoning is that the user only wants to retrieve each field once, instead of merging the outputs of `fields` and `docvalue_fields`.
3. Throw an error if the same field is requested in both `fields` and `docvalue_fields`. I'm afraid this is too limiting, since both `fields` and `docvalue_fields` accept wildcard patterns and these could easily overlap.

I'm in favor of option 2: it is simple and consistent with our approach of always returning field data in `fields`. It also avoids a confusing situation where we append field values together.

@astefan @nik9000 @jimczi do you have thoughts on the options above?

**Comment by nik9000** [comment]
My first instinct is option 3, throwing an error. It feels like the least
surprising option to me.

**Comment by jimczi** [comment]
I have a slight preference on option 1, mainly because I don't think `fields` and `docvalue_fields` should be used on the same request. The long term goal is to deprecate the `docvalue_fields`, `script_fields` and `stored_fields` all together but I am also not sure that we should change anything in the meantime. So far `docvalue_fields` is mainly used for bad reasons (formatting of the field) so the fix here is that users can switch to the new API, not use it in conjunction with `docvalue_fields`.

**Comment by jtibshirani** [comment]
We recently merged a refactor to the fetch phase that actually changed the behavior (#60907). Now the entire 'fetch doc values' subphase is execute before 'fetch fields', which means we follow behavior (2) above: any fields from `fields` completely overwrite those from `docvalue_fields`.

This seems like okay behavior to me and I don't feel we need to make a change. The reasoning:
* It's good to not have special logic around preferring `fields` vs. `docvalue_fields`. This is simple and consistent with our view that `fields` and `docvalue_fields` shouldn't really be used together.
* There's no longer a confusing situation where we return the same field value twice, as in @astefan's [original example](https://github.com/elastic/elasticsearch/issues/61029#issue-677694372).

Let me know if you have remaining comments/ concerns. Otherwise I plan to close out the issue soon.
