### ISSUE TITLE
Boolean field accepts an empty string, does not index as `null`

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#61038]
**Elasticsearch version** (`bin/elasticsearch --version`): Latest `elasticsearch-8.0.0-SNAPSHOT-darwin-x86_64.tar.gz`

**Plugins installed**: []

**JVM version** (`java -version`):
openjdk version "14" 2020-03-17
OpenJDK Runtime Environment AdoptOpenJDK (build 14+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14+36, mixed mode, sharing)

**OS version** (`uname -a` if on a Unix-like system):
Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:
`boolean` fields accept an empty string (`""`).  However, it's not clear whether this should be treated as a `null` value (it's not currently). Regardless, this behavior is not documented.

**Steps to reproduce**:

### Index an empty string in a boolean field
Map a boolean field:

```
PUT my-index
{
  "mappings": {
    "properties": {
      "my-bool": { "type": "boolean" }
    }
  }
}
```

Index an empty string to the boolean field:
```
POST my-index/_doc/?refresh=wait_for
{
  "my-bool": ""
}
```

Use an `exists` query to search for `null` values:
```
GET my-index/_search
{
  "query": {
    "bool": {
      "must_not": {
        "exists": {
          "field": "my-bool"
        }
      }
    }
  }
}
```

Results:

```
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  }
}
```

### Index a null value in a boolean field

Delete the index:

```
DELETE my-index
```

Map a boolean field:

```
PUT my-index
{
  "mappings": {
    "properties": {
      "my-bool": { "type": "boolean" }
    }
  }
}
```

Index a null value to the boolean field:
```
POST my-index/_doc/?refresh=wait_for
{
  "my-bool": null
}
```

Use an `exists` query to search for `null` values:
```
GET my-index/_search
{
  "query": {
    "bool": {
      "must_not": {
        "exists": {
          "field": "my-bool"
        }
      }
    }
  }
}
```

Results:

```
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : 0.0,
    "hits" : [
      {
        "_index" : "my-index",
        "_id" : "l3tA43MB9vB44i3ki4fq",
        "_score" : 0.0,
        "_source" : {
          "my-bool" : null
        }
      }
    ]
  }
}
```

**Comment by cbuescher** [comment]
I took a look at the code, and most interestingly we currently treat an empty string as a "false" value, which can be confirmed searching for:
```
GET /my-index/_search
{
  "query": {
    "match": {
      "my-bool": false
    }
  }
}
```
The code that parses the value uses [AbstractXContentParser#booleanValue](https://github.com/elastic/elasticsearch/blob/master/libs/x-content/src/main/java/org/elasticsearch/common/xcontent/support/AbstractXContentParser.java#L98) which sets a default of `false` for both null values and empty Strings in [Booleans#parseBoolean](https://github.com/elastic/elasticsearch/blob/master/libs/core/src/main/java/org/elasticsearch/common/Booleans.java#L35).
I personally find this very counter-intuitive and would like a system to either reject an empty string or treat it as null. However, changing this behaviour now would require some extended thinking about bwc since some odd client out there might rely on the current behaviour.
