### ISSUE TITLE
Add ability to yield values in scripting contexts

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#61052]
In contexts where users can return multiple values, being able to emit a value without terminating execution could be useful and more efficient.

1) It's more concise

```
long[] doubled = new long[doc.abc.length];
for (int i = 0; i < doc.abc.length; i++) {
    doubled[i] = doc.abc[i] * 2;
}
return doubled;
```
becomes, with `yield`
```
for (int i = 0; i < doc.abc.length; i++) {
    yield doc.abc[i] * 2;
}
```

2) The calling environment can reduce allocations.  The caller may have a pre-allocated array that it fills with the `yield`ed values.  So several small array allocations, or worse, collections that require primitive type boxing to use, become one large array allocation and an occasional expansion of the array.

There are complications.

A) `yield` is not appropriate in contexts where a single value is returned, such as filter scripts.  

B) The interaction between `yield` and `return` (both bare return and return value) is messy.  Should a user be able to `yield` AND `return` in the same script?  If not, then how do they terminate early after their done `yield`ing?

@jimczi @nik9000 @jdconrad @rjernst please add anything I missed

**Comment by rjernst** [comment]
Some additional complications:
* yield has very specific semantics in other languages, specifically it implies an iterable object is returned by the function, which is fully captured. This is not possible with scripts since moving the next doc would invalidate any previously built captures.
* The return type would still be either an array or list, but nothing would stop incorrect use of stashing this object, which for the same reasons the lifetime must end at the next execution of the script
