### ISSUE TITLE
Datasketches HllSketch aggregation for ElasticSearch is actually NOT same with Cardinality Aggregation

### ISSUE THREAD

**Issue by nooneuse** [elastic/elasticsearch#61136]
hi,@polyfractal, thanks for reply!
I also use cardinality aggregation very often, and i think this hllsketch aggregation is completely not the same thing between cardinality aggregation.
hllsketch is based on apache Datasketches which is a pre-aggregation hll container can be seriralized into binary data.
hllsketch aggregation is use binary data that user generated.
To use this plugin. User needs generate their own hllsketch binary data and write to a binary data field.
On contrary, To use cardinality aggregation, User just put data to a keyword, long...etc field.

This function is not coverd by cardinality aggregation.
This plugin is used for pre-aggregation situation.(Pre-aggregation sketch data is generated by user themselves)
Please reconsider this pr. Thank you very much.

_Originally posted by @nooneuse in https://github.com/elastic/elasticsearch/pull/61006#issuecomment-673926596_

**Comment by pgomulka** [comment]
@nooneuse this I think you wanted to be a comment in #61006 (you can comment even if it is closed)
Can you please comment there and close the issue afterwards?

**Comment by nooneuse** [comment]
> @nooneuse this I think you wanted to be a comment in #61006 (you can comment even if it is closed)
> Can you please comment there and close the issue afterwards?

hello, @pgomulka . thanks for reply！
I replied @polyfractal who closed my pr, that i think my change is not as same as cardinality aggregation. But he haven't reply me.
I don't know what to do next so i opened this issue.
Please help me review my code, and reconsider my pr. thx

**Comment by polyfractal** [comment]
Hi @nooneuse, I'm going to close this ticket and we can continue the conversation over in #61006 :)  It's better to keep the conversation all in one place rather than opening multiple issues/PRs.  E.g. the discussion is about #61006 so it should take place on that PR rather than here :)

Also, we all live in different time zones, and have various work/responsibilities/schedules, so replies will likely not be immediate in general.  E.g. you replied on Friday and I was out of the office that day :)  Thanks for understanding!
