### ISSUE TITLE
Can not install Windows Service : "the system property [es.path.conf] must be set"

### ISSUE THREAD

**Issue by haedri** [elastic/elasticsearch#61333]
**Elasticsearch version** (`bin/elasticsearch --version`): Version: 7.9.0, Build: default/zip/a479a2a7fce0389512d6a9361301708b92dff667/2020-08-11T21:36:48.204330Z, JVM: 1.8.0_92

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_92

**OS version** (`uname -a` if on a Unix-like system): Windows 10

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Trying to install ElasticSearch 7.9.0 on a fresh Windows VM and the service fails to start.

1. Fresh Windows 10 VM install from Microsoft (WinDev2007Eval) + jvm
2. Download, and extract ElasticSearch 7.9.0 zip for Windows
3. Install service 
```
 cd C:\elasticsearch-7.9.0\bin
 elasticsearch-service.bat install es
```
4. Start service

An error popup "Error 1067: The process terminated unexpectedly"
In the es-stderr.2020-08-19 log file there is this error :
```
2020-08-19 07:23:29 Commons Daemon procrun stderr initialized
ERROR: the system property [es.path.conf] must be set
```

The fix provided here https://github.com/elastic/elasticsearch/pull/57769 doesn't help since the culprit is not the same variable, I had to add the line 
`if not "%OTHER_JAVA_OPTS%" == "" set OTHER_JAVA_OPTS=%OTHER_JAVA_OPTS:;;=;%`
before calling "%EXECUTABLE%" (after line 205) to file elasticsearch-service.bat

**Comment by rjernst** [comment]
@williamrandolph Can you take a look at this? At least when looking at 8.0 I see we always set es.path.conf in ES_PARAMS, but perhaps 7.9.0 had slightly different logic.

**Comment by williamrandolph** [comment]
@haedri I deeply apologize for the delay in responding to this issue. I managed to reproduce what you reported using 7.9.0 and a Java 8 JVM.

I fixed a bug in the `elasticsearch-service.bat` script in https://github.com/elastic/elasticsearch/pull/64254, which was release in 7.9.4 and 7.10.0. I believe this will fix the problem (I couldn't reproduce it with 7.10.0), and that the patch in the PR would fix your issue here as well. If you find that you still have to use your workaround in those versions, please let me know and I will reopen this issue.
