### ISSUE TITLE
When elasticsearch is running on mips64el, the value of MAX_SIZE_VIRTUAL_MEMORY is different on x86/arm.

### ISSUE THREAD

**Issue by Panxuefeng** [elastic/elasticsearch#61406]
**Elasticsearch version** (`bin/elasticsearch --version`): `all version`

**JVM version** (`java -version`): `openjdk version "1.8.0_242"
OpenJDK Runtime Environment (Loongson 8.1.4-loongson3a-Fedora) (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)`

**OS version** (`uname -a` if on a Unix-like system): 
`Linux localhost.localdomain 3.10.84-23.fc21.loongson.8.mips64el #1 SMP PREEMPT Thu Mar 5 17:56:57 CST 2020 mips64 mips64 mips64 GNU/Linux
`

**Description of the problem including expected versus actual behavior**:
 `I am a mips platform developer,  when we run elasticsearch on mips, the value of MAX_SIZE_VIRTUAL_MEMORY is different on x86/arm. The value on mips is 65536, but on x86/arm is -1.`

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 I found the reason, in the elasticsearch/server/src/main/java/org/elasticsearch/bootstrap/JNACLibrary.java, RLIMIT_AS is set to 5 when elasticsearch run on MAC_OS_X, otherwise RLIMIT_AS is set to 9. RLIMIT_AS is the system marco definition in resource.h. In resource.h of mips, the RLIMIT_AS is 6, but on x86/arm, the RLIMIT_AS is set to 9. In elasticsearch/server/src/main/java/org/elasticsearch/bootstrap/JNACLibrary.java, we don't have to consider the characteristics of the mips platform. In other words, the default value of RLIMIT_AS has been modify on mips, on x86/mips, RLIMIT_AS is run by default. 
so, how should we fix this problem?

**Comment by Panxuefeng** [comment]
I think this is a bug in elasticsearch, we don't have to consider the characteristics of the mips platform. All versions have this problem, So we should slove this problem as soon as possible.

**Comment by DaveCTurner** [comment]
Your analysis looks absolutely correct to me, MIPS does indeed have a different set of resource constants from x86/64:

https://github.com/torvalds/linux/blob/da2968ff879b9e74688cdc658f646971991d2c56/arch/mips/include/uapi/asm/resource.h#L19

https://github.com/torvalds/linux/blob/da2968ff879b9e74688cdc658f646971991d2c56/include/uapi/asm-generic/resource.h#L39

However the only [supported](https://www.elastic.co/support/matrix) processor architecture today is x86/64, not x86/mips, so incompatibilities like this are to be expected. Adding support for additional processor architectures is not something we [undertake lightly](https://github.com/elastic/elasticsearch/issues/54930#issuecomment-610690848) since it entails a good deal of ongoing effort in testing and maintenance. If we were to add support for x86/mips then we would consider this a bug, but as things currently stand it's an expected incompatibility. As there is no action for us to take here, I am closing this.

**Comment by xidiandb** [comment]
How to skip the check

**Comment by mark-vieira** [comment]
> How to skip the check

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question.
