### ISSUE TITLE
Support from/to directly in the new Histogram Aggregation

### ISSUE THREAD

**Issue by fbuecklers** [elastic/elasticsearch#61410]
First of all nice to see, the ES has implemented the Histogram Aggregation.

Our use case is that we store many timer values in pre-aggregated histogram fields in our indices. 
Over this aggregated histogram data we want to visualize the distribution of those timers for a given time range.
The new Histogram Aggregation fits well here to get the results for the visualization except that we want to view only a specific range of the timers. The documentation states that we should prefilter our data by a range aggregation with the from/to filter. 
But these do not work in our case if we use pre-aggregated histogram values as a source for the aggregation.

Therefore it should be possible to define a min/from - max/to range in the aggregation directly get only a specific range of the data.

We can't do this in the visualization step since the returned JSON by the histogram aggregation becomes too large to handle that properly in the frontend.

**Comment by imotov** [comment]
@fbuecklers in 7.10.0 we are adding a new feature called [`hard_bounds`](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/search-aggregations-bucket-histogram-aggregation.html#_minimum_document_count). I wonder if this will work for your needs.

**Comment by fbuecklers** [comment]
Wow, that is exactly the missing piece, if it works on preaggregated histogram fields.

I don't know if I should open another ticket, but will the histogram aggregation also be supported in roll-up indices in the future? We want to reaggregate our preaggregated histograms in a rolling fashion to span larger time ranges. The resulting index should contain then a new histogram field as a result of the histogram aggregation.

**Comment by polyfractal** [comment]
> I don't know if I should open another ticket, but will the histogram aggregation also be supported in roll-up indices in the future? 

@fbuecklers that's roughly the plan :)  We added the new histogram field specifically so that we could [support histograms/percentiles/etc in Rollup](https://github.com/elastic/elasticsearch/issues/33214) eventually.  It'll probably be landing in the [refactored form](https://github.com/elastic/elasticsearch/issues/42720) of Rollups rather than the existing form, but one way or another we'll be adding support to rollups

We're still hammering out details about _how_ exactly it will be implemented/used.  E.g. I'm not sure if the particular scenario you mentioned (rolling up rollups) will be supported or not because we haven't quite gotten there, but the general idea is indeed to have this functionality available :)

**Comment by imotov** [comment]
I opened #62124 to avoid confusion. Closing this one.

**Comment by fbuecklers** [comment]
@polyfractal No, we definitely do not want to rollup rolled-up indices. We are putting already pre-aggregated histogram values directly to our time-based index. Putting the raw data directly into it will not work because of the huge amount of raw data. Therefore we have a real-time based preprocessor, which does some preaggregation stuff on our raw data. That's the reason why we have already pre-aggregated histogram fields in our index.

We only want to roll-up the data afterward to day-based buckets.

Is there a roadmap or an ETA, when this feature will be available? We are currently in the process to decide whenever we can use the rollup indices for our task or that we must implement our own rollup process externally.
