### ISSUE TITLE
Allow exact matching on wildcard types w/o asterisk 

### ISSUE THREAD

**Issue by aleph-zero** [elastic/elasticsearch#61435]
The new wildcard data type forces the user to construct queries containing the wildcard '*' character, even when no expansion is desired. This feels counter-intuitive, especially since the wildcard type is described in the documentation as providing "grep-like" functionality. 

Take the following log line as an example: 
**"Aug 20 07:16:24 damascus dnsmasq[1768]: using nameserver 127.0.0.53#53"**. 

Using grep I could find the string **"nameserver"** by issuing this command: **_grep nameserver logfile_**. Of course I could also use: **_grep nameserver\* logfile_**, but that would be extraneous since I don't require right-side expansion. 

However, in Elasticsearch the wildcard type requires the extraneous '*', even if the user only wants an exact match. If I want to find the exact string "nameserver", I need to construct a query like this:

`"query": {
    "wildcard": {
      "message": {
        "value": "*nameserver*"
      }
    }
  }`

A better user experience would be to allow the query to be constructed without the leading and trailing wildcard, e.g.:

`"query": {
    "wildcard": {
      "message": {
        "value": "nameserver"
      }
    }
  }`

**Comment by markharwood** [comment]
Thanks for the feedback, Andrew.

>A better user experience would be to allow the query to be constructed without the leading and trailing wildcard, e.g.:
> "query": { "wildcard": { "message": { "value": "nameserver" } } }

Less typing is generally good but in this case there are some downsides:

* That would be inconsistent with the wildcard query logic used on other fields (being a 100% compatible replacement for `keyword` fields is a design goal).
* It would leave us without a syntax for stating that "n" must be found out the start of the string or "er" is the end.

This may be the thin end of the wedge. Pattern matching options like this invariably require cryptic characters to separate search content from match options. That's especially true of regex. Arguably it is the responsibility of the GUI to simplify this task e.g. 
<img width="209" alt="Untitled_4" src="https://user-images.githubusercontent.com/170925/91023858-ff836600-e5ee-11ea-902f-47bf17ecb484.png">

The challenge in Kibana is that as long as we AND/OR clauses together using a text-based editor like KQL we can't use graphical editors like the example above to hide the complexity behind individual clauses. For example, I'd like to build a [graphical editor](https://regexper.com/#%28foot%7Cnet%29ball) to simplify building of regex clauses but [we can't ](https://github.com/elastic/kibana/issues/46855#issuecomment-663023402)

In my opinion the way to put more power in people's hands is for the backend to focus on exposing capability via formal APIs and the GUI to focus on the job of making that simple for more users.

**Comment by markharwood** [comment]
Closing, purely because consistency of query behaviour across field types (wildcard and keyword) is a design goal. We can't  change wildcard query behaviour just for wildcard field.

**Comment by markharwood** [comment]
Reopening - after some discussion with @jimczi there was the suggestion a `wildcard_text` field might be able to support `match` or `query_string` queries with asterisk-free terms that search within content.
We can discuss that further here.

**Comment by markharwood** [comment]
Some thoughts on these sloppier matching options:

We have to consider the 2 main users we target:
* Admins set default matching policies through query template and/or mapping choices
* End users type search terms which are fed into search templates

Each user has a range of options open to them to move the slider from strict to sloppy matching:

User | Sloppy choices | Strict choices
-----|-------|-----
Admin|**Mappings**: ngrams, synonyms, stemming, normalizers <br> **Query templates:** default operator = OR, fuzzy matching, multi-field search |**Mappings**: keyword field, , no normalizer<br> **Query templates:** default operator = AND, templates with `term` queries
End-user| foo~<br> foo* <br>foo **OR** bar, | "foo bar"<br>foo **AND** bar<br> myfield.keyword:foo

The two users can wrestle with each other's choices so there's a need for end users to override the default choices made by admins. Some form of escape hatch is required. 

Today, if an admin opted for a strict `keyword` mapping (or wildcard field), the end user can use the `*` syntax to go sloppy and match anywhere in the string rather than having to match whole values. This is a widely understood syntax.

However, if we introduce a new field type or query flag where admins can make searches sloppy by default (so they match anywhere in the string) there is currently no end-user syntax to override this. End users would need a special character to denote the start or end of a field in order to prevent a search for `red` matching `grey-coloured`. 
One way out is if the sloppy matching was a new `wildcard_text` field (as opposed to a new default query flag) the end-user could use fieldname syntax eg. `myfield.keyword:red` to have stricter, whole-word matching. Unfortunately this would require a `keyword` field to be indexed in addition to the `wildcard` one used for the sloppy search. The end user would have to know the name of this field.

Given the above, I think the existing `*nameserver*` syntax is the least-worst scenario.

**Comment by benwtrent** [comment]
I may be doing something wrong. But from what I can tell `wildcard` works just fine without any asterisks or simple patterns.

I tested the original scenario, and `wildcard` worked just fine when searching only for `nameserver` and returned the expected doc.
