### ISSUE TITLE
[DOCS] Link in Elastic documentation of SAML to  Blogpost on elasticsearch-saml-authentication-with-adfs 

### ISSUE THREAD

**Issue by InbarShimshon** [elastic/elasticsearch#61668]
For SAML single-signing for Elastic Stack the request is to add within our general elastic documentation for SAML with ADFS (e.g.: https://www.elastic.co/guide/en/elasticsearch/reference/6.8/security-troubleshooting.html ) a link to the following blogs:

https://www.elastic.co/blog/how-to-configure-elasticsearch-saml-authentication-with-adfs 

Since this blog goes into detail on troubleshooting I think it would be beneficial to refer to this our documentation.

**Comment by jkakavas** [comment]
Hi there @InbarShimshon ! Which part specifically do you refer to? I see the "In case of issues" which basically links to the troubleshooting page that you suggest er add this to. 

If there are troubleshooting details that you feel are useful, it's probably more helpful to add those to the troubleshooting doc themselves so that we can maintain and update them ( as opposed to just linking to the blogpost)

**Comment by InbarShimshon** [comment]
The main request is to have within our official SAML ADFS documentation a linkage to this blogpost as it just goes in a very structured manner over how to set it up while our current doc remains very general. 

Small things are explained here in the blogpost like the  importance of creating the group in ADFS to associate it on the Elastic role. So a link to this post could help people looking at our doc get clarify and additional reference

**Comment by jkakavas** [comment]
Gotcha, we can add the link to the blog in our saml guide doc rather than the troubleshooting doc then, I think it makes more sense. Thanks for the suggestion

**Comment by InbarShimshon** [comment]
@jkakavas  Yes, that works as well, as long as there is a clear reference to this blog - thank you for picking this suggestion up!
