### ISSUE TITLE
Provide a java client api (maven) package without external dependencies

### ISSUE THREAD

**Issue by benjamin84** [elastic/elasticsearch#6170]
The standard elasticsearch package on maven central has a lot of lucene dependencies which are not generally needed for using the java client api (TransportClient/Client-Node).
Excluding all lucene dependencies is also not possible because TransportClient needs lucene-core for reading the Lucene version.

**Comment by YuriKap** [comment]
We are trying to move from an older version of Lucene to ElasticSearch. We would like for our app to communicate with ElasticSearch via TransportClient but can't (without shading or doing classloader magic) since we currently have dependencies on an older version of the Lucene library. It would be really nice if we could have a TransportClient without the lucene-core dependency. 

Is there any chance that the dependency will be removed at some point?

**Comment by dakrone** [comment]
We discussed this and think this is a good idea, maybe we can perform this using some kind of Maven shading to make sure we have a clean cut between the internal and client APIs.

**Comment by YuriKap** [comment]
:+1:

**Comment by sureshg** [comment]
:+1:

**Comment by dadoonet** [comment]
Note that anyone can build his own shaded version. Read this: https://www.elastic.co/blog/to-shade-or-not-to-shade

Not sure if we still need to keep this issue opened.

**Comment by sureshg** [comment]
@dadoonet IMHO this issue is for creating a thin Java client for Elasticsearch with minimal dependencies. Shaded version still has all the same dependencies.

**Comment by massfords** [comment]
I think the issue description sums it up nicely. The maven shade plugin is a viable solution but it's hardly elegant. At a minimum, I would hope ES would provide a client only dependency that allowed users to interact with the Client interface (Transport or otherwise) without bringing in all of the Lucene dependencies. The big win here is that ES does the packaging and it's one less thing we need to maintain locally in our own source repo. 

Whether this new module uses the Shade plugin to hide Lucene or perhaps removes Lucene is largely an implementation detail. We could debate the merits of a smaller dependency tree as a separate issue. As it stands now, if you have a component like Apache Jackrabbit then you're unable to use ES in your application in any capacity without the shade plugin. Again, I can roll my own (which I have) but I don't want to have to continue to do this.

I think this issue is worth addressing.

**Comment by dadoonet** [comment]
May be it's the same issue as https://github.com/elastic/elasticsearch/issues/7743?

**Comment by matt-blanchette** [comment]
+1 for Java client with few dependencies

**Comment by dakrone** [comment]
I don't think we are planning on doing this with a transport client. Instead, we are working on an HTTP client for Java that will be part it this, see: https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/index.html

**Comment by jaromor** [comment]
> I don't think we are planning on doing this with a transport client. Instead, we are working on an HTTP client for Java

tbh 11MB still sounds like a lot for a REST-client
