### ISSUE TITLE
ILM history indices are not pre-pended with a dot 

### ISSUE THREAD

**Issue by eddieturizo** [elastic/elasticsearch#61829]
It seems like `ilm-history` should be a system index prepended with a `.`, `.ilm-history`. The goal here is to discuss if these indices should become a system index prepended with a dot.

**Comment by gwbrown** [comment]
There is currently an open PR, https://github.com/elastic/elasticsearch/pull/60280, to switch `.ilm-history` to a data stream, which I believe resolves this, as data streams do not currently have an analogous construct to `hidden indices` or `system indices` (in part because they are implemented using hidden indices).

Will that resolve your concerns?

**Comment by eddieturizo** [comment]
> to switch .ilm-history to a data stream

This seems to suggest it was changed to a dot (system) index and will be updated to be a data stream? Please let me know if I am missing something. 

> Will that resolve your concerns?

It does, thank you.

**Comment by gwbrown** [comment]
Sorry - that was a typo, I shouldn't have included the dot in that. It should read:
> to switch `ilm-history*` to a data stream

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
