### ISSUE TITLE
query templates reusable

### ISSUE THREAD

**Issue by joropito** [elastic/elasticsearch#61822]
Hi all!

Please I would like to see query teamplates to be reusable on any query like this

> {
>   "template_search": {
>     "params": { ....... these params will be used by defaults, child params supercedes this ones ..... },
>     "query": { "id": "some_query_template", "params":  { ... } },
>     "_source": { "id": "some_source_template", "params": { ... } },
>     "aggs": { "id": "some_aggs_template", "params": { ... } }
>   }
> }

Where only "query" section of some_template_name will be used.

Same feature could apply for any _search section like _source, aggs, etc

It would help developers and administrators to manage less templates and avoid duplicate templates just for small differences

**Comment by joropito** [comment]
So, could be availiable in future releases?

**Comment by javanna** [comment]
hey @joropito sorry about getting back to you after all this time. Are you familiar with the  [search templates](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html) that Elasticsearch already supports? I was wondering if those would cover your needs, otherwise could you expand on your requirements please?

**Comment by javanna** [comment]
Closing for lack of feedback.
