### ISSUE TITLE
Change elasticsearch-certutil default to keep the CA private key

### ISSUE THREAD

**Issue by bytebilly** [elastic/elasticsearch#61884]
We discussed in https://github.com/elastic/elasticsearch/issues/61087 that the default current behavior of the `elasticsearch-certutil` tool is to discard the generated CA private key when running in `cert` mode.

If you want to retain it, you should explicitly add the `--keep-ca-key` parameter.

We could change the default to keep the CA private key, and introduce a new option to delete it.
Or simply always keep it, and users can easily delete it if needed.

**Comment by ywangd** [comment]
Just wanan clarify a few things before making the changes:

Currently, the `cert` command by default generates a single p12 file because it does not need to keep the CA key file. This is explicitly stated in the code:
https://github.com/elastic/elasticsearch/blob/f505591c0c67a81d9ac52d05d322242943b48d32/x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/CertificateTool.java#L672-L682

So if we remove `--keep-ca-key` option and make it default, this means the above default behaviour will change as well, i.e. the default output will be a zip file with following content:
```
ca/
ca/ca.p12
instance/
instance/instance.p12
```

I guess the current default of **not** keeping CA key is mainly for simplicity. Since it is easier for users to understand what's going on if the output is a single p12. So changing the behaviour could incur extra cognitive load. 

We can add a new `--discard-ca-key` option so users can explicitly choose to **not** keep the CA file. But I am not sure how necessary this new option is. Other than toy examples, there is no valid use case for generating certs without keeping the CA. The only benefit of not keeping the CA is the output file can be simplified to be a single p12 instead of a zip bundle. However, any real use cases for the `cert` command are likely already generating zip file:
https://github.com/elastic/elasticsearch/blob/f505591c0c67a81d9ac52d05d322242943b48d32/x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/CertificateTool.java#L689

_So I'd prefer to not adding the new `--discard-ca-key` option_. There are still ways to generate a single P12 file, e.g. when an existing CA key is specified. From learning perspective, I'd say the two step process of 1) generating CA and 2) generate cert with exisitng CA is easier to follow than doing the two things in one go. 

I am not sure what's the decprecation process for command line tools. For `elasticsearch-certgen` tool, there is an [deprecation message](https://github.com/elastic/elasticsearch/blob/7.9/x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/CertificateGenerateTool.java#L511-L515) added to the preamble text. And this tool is still available even though it is deprecated (`v8.0`). So does that mean other than adding a deprecation message to the `--keep-ca-key` [help message](https://github.com/elastic/elasticsearch/blob/7.9/x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/CertificateTool.java#L221), there is not much that we can do for now? When can we actually remove this option or at least change it to an no-op? Right before v8.0 goes out?

**Comment by tvernum** [comment]
I don't think this is an easy change to make. I'd be more inclined to just ditch the option to run the `cert` command without an existing CA.

Generating a CA on the fly is an attempt at workflow optimisation (that was inherited from certgen) that ends up doing more harm than good.

**Comment by ywangd** [comment]
So the deprecation path is to have a `elasticsearch-certutil-2`? 😉 

But seriously, I like the idea of getting rid of mode entirely. It is a breaking change, but breaks loudly instead of subtle behaviour changes. Maybe we can keep the existing behaviour in a compat mode which is triggered by setting an environment variable? So how about the following plan?
* Change the Java code, so it defaults to not allow "on-the-fly" CA.
* If an Environment variable is set, the Java code runs in compat mode and supports the "on-the-fly" CA.
* For 7.x, change the shell wrapper script to set above environment variable, and also prints a deprecation message as warning.
* For 8.0, no change to the shell script. But user can still explicity set it to achieve the legacy behaviour.

**Comment by tvernum** [comment]
That seems overly complicated.

Why not:
- In 8.0 make `--keep-ca-key` report an error that explains to pre-generate a CA using the `ca` command.
- In 8.0 make `--ca` (or `--ca-cert`/`-key`) mandatory 
- In 7.x print warning if the `cert` command is used without an existing CA.

**Comment by ywangd** [comment]
> That seems overly complicated.
> 
> Why not:
> 
> * In 8.0 make `--keep-ca-key` report an error that explains to pre-generate a CA using the `ca` command.
> * In 8.0 make `--ca` (or `--ca-cert`/`-key`) mandatory
> * In 7.x print warning if the `cert` command is used without an existing CA.

This sounds good to me. I was trying too hard to preserve the existing behaviour, which is probably not necessary. @bytebilly If you are also happy with this approach, I'll go ahead and make the changes.

**Comment by bytebilly** [comment]
The general approach works for me.

Other tools do the same (e.g. `easy-rsa`) and require the user to provide (or generate with a separate command) a valid CA keypair if they want to build certs.

> In 8.0 make --keep-ca-key report an error that explains to pre-generate a CA using the ca command.

I'd see it more useful to show this message if users don't provide the required `--ca` option. 
The `--keep-ca-key` could just be deprecated, but it is a no-op if we require the CA key to be provided (and clearly we don't delete it).

What do you think?

**Comment by ywangd** [comment]
> I'd see it more useful to show this message if users don't provide the required --ca option.
>
I think this is pretty much the same as what Tim suggested "In 8.0 make --ca (or --ca-cert/-key) mandatory".

The important bit here is to error out (with help messages) when CA is not specified (v8.0). I think we all agree on this.

So the only different view is about `--keep-ca-key` in 8.0. The difference is between "removing it (with error message if specified)" or "deprecate it as no-op". I personally prefer to just remove it. My reasonsings are: 

* It is simpler and the semantic is subtly more correct because semantically "--keep-ca-key" and "explicitly specifyed CA" do not make sense to be together.
* It is a breaking change anyway and we'd better take the chance to break it more cleanly with no leniency.
