### ISSUE TITLE
SecurityNetty4HttpServerTransportTests.testNoClientAuth fails on CI

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#61919]
**Build scan**:
https://gradle-enterprise.elastic.co/s/oubicbcds7faq

**Repro line**:
```
./gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.xpack.security.transport.netty4.SecurityNetty4HttpServerTransportTests.testNoClientAuth" \
  -Dtests.seed=C46BCB3CA134ACEC \
  -Dtests.security.manager=true \
  -Dtests.locale=be-BY \
  -Dtests.timezone=Europe/Tallinn \
  -Druntime.java=8
```

**Reproduces locally?**:
No

**Applicable branches**:
7.x

**Failure history**:
No history in the last 30 days.

**Failure excerpt**:

org.elasticsearch.xpack.security.transport.netty4.SecurityNetty4HttpServerTransportTests > testNoClientAuth FAILED

>     java.lang.IllegalStateException: availableProcessors is already set to [32], rejecting [32]
>         at __randomizedtesting.SeedInfo.seed([C46BCB3CA134ACEC:D248E314CBCC157D]:0)
>         at io.netty.util.NettyRuntime$AvailableProcessorsHolder.setAvailableProcessors(NettyRuntime.java:51)
>         at io.netty.util.NettyRuntime.setAvailableProcessors(NettyRuntime.java:87)
>         at org.elasticsearch.transport.netty4.Netty4Utils.setAvailableProcessors(Netty4Utils.java:61)
>         at org.elasticsearch.http.netty4.Netty4HttpServerTransport.<init>(Netty4HttpServerTransport.java:152)
>         at org.elasticsearch.xpack.security.transport.netty4.SecurityNetty4HttpServerTransport.<init>(SecurityNetty4HttpServerTransport.java:43)
>         at org.elasticsearch.xpack.security.transport.netty4.SecurityNetty4HttpServerTransportTests.testNoClientAuth(SecurityNetty4HttpServerTransportTests.java:125)

**Comment by probakowski** [comment]
Similar failures in https://gradle-enterprise.elastic.co/s/d5v22jx5blekc and https://gradle-enterprise.elastic.co/s/cm6n47465avuq

**Comment by ywangd** [comment]
Similar faliures
* 7.x - https://gradle-enterprise.elastic.co/s/ihryhrnwlgnxw
* master - https://gradle-enterprise.elastic.co/s/o5unmgomdd4rq

Do not reproduce locally for me.

Since the actual faliure is in `@Before`, the error can be reported for any of the test methods of `SimpleSecurityNetty4ServerTransportTests`. The failure started to happen fairly recently. [Build-stats](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-90d,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'%22SimpleSecurityNetty4ServerTransportTests%22%20AND%20%22availableProcessors%22'),sort:!(process.time-start,desc))) says it is from 2020-09-05. However the original issue was dated as 2020-09-03. Not sure why the mismatch. In any case, this is a relatively new failure.

**Comment by hendrikmuhs** [comment]
another one today: https://gradle-enterprise.elastic.co/s/r7oetik7tqgey

I wonder if the failure is connected to the CI worker which reports:

Specs | 32 CPUs, 94.41GB RAM

If so, it's no wonder that this can't be reproduced locally, at least I do not have a 32 CPU system to test.

@elastic/es-core-infra have the CI workers been recently upgraded to 32 cpus?
