### ISSUE TITLE
Introduce search_before 

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#62118]
If one needs `search_before`-like functionality, the workaround is to use `search_after` but "flip" the query, by reverting its order.
This is problematic if the query has been constructed elsewhere as the caller now has to identify the sort in order to change it and thus ends up with two queries - the initial one plus the `search_before` one.
With a `search_before` parameter, the consumer can keep the initial request and get the desired behavior without having to modify the query itself.

P.S. Not sure whether it makes sense to have both `search_after` and `search_before` inside the same request.
P.P.S. A similar request was made before https://github.com/elastic/elasticsearch/issues/29449

**Comment by chillenious** [comment]
Another problem with `search_after` when using it for paging is that it lacks to option to include the 
cursor, which is a problem when paging backwards.

Consider data:

`1,2,3,4,5,6,7,8`

Say we pick '5' as our cursor and select 2 rows 'after' the cursor:

`search_after(5)(2) -> 6,7`

So now the clients would have 6 and 7 and a cursor based on 5. If we'd page backwards for 2 rows, we'd 
reverse the sort and search_after the cursor, which gives us:

`search_before(5)(2) -> 4,3`

besides the fact that we'd want the order reversed (not a big deal, but if search_before would ever be
consider, this may also have to be considered to be automatic), for backwards paging we'd expect the
cursor rows to be included so that we'd end up with rows `4,5`.

**Comment by GiBot2** [comment]
I am interested in implementing it, can someone guide me to a starting point?

I tried looking at the SearchAfterBuilder.java and SearchService.java files but wasn't able to understand where the time checking logic is located.

**Comment by javanna** [comment]
There are no plans to work on this issue. Closing.
