### ISSUE TITLE
[CI] SimpleSecurityNetty4ServerTransportTests.testTransportProfilesWithPortAndHost failure

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#62298]
**Build scan**: https://gradle-enterprise.elastic.co/s/nkhbl2wmi46ty

**Repro line**: 

```
./gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.xpack.security.transport.netty4.SimpleSecurityNetty4ServerTransportTests.testTransportProfilesWithPortAndHost" -Dtests.seed=8284FAC74D6A0554 -Dtests.security.manager=true -Dtests.locale=es-ES -Dtests.timezone=SystemV/PST8PDT -Druntime.java=11
```

**Reproduces locally?**: No

**Failure excerpt**:

```
org.elasticsearch.xpack.security.transport.netty4.SimpleSecurityNetty4ServerTransportTests > testTransportProfilesWithPortAndHost FAILED
09:28:03     java.lang.IllegalStateException: availableProcessors is already set to [32], rejecting [32]
09:28:03         at io.netty.util.NettyRuntime$AvailableProcessorsHolder.setAvailableProcessors(NettyRuntime.java:51)
09:28:03         at io.netty.util.NettyRuntime.setAvailableProcessors(NettyRuntime.java:87)
09:28:03         at org.elasticsearch.transport.netty4.Netty4Utils.setAvailableProcessors(Netty4Utils.java:61)
09:28:03         at org.elasticsearch.transport.netty4.Netty4Transport.<init>(Netty4Transport.java:106)
09:28:03         at org.elasticsearch.xpack.core.security.transport.netty4.SecurityNetty4Transport.<init>(SecurityNetty4Transport.java:67)
09:28:03         at org.elasticsearch.xpack.security.transport.netty4.SecurityNetty4ServerTransport.<init>(SecurityNetty4ServerTransport.java:39)
09:28:03         at org.elasticsearch.xpack.security.transport.netty4.SimpleSecurityNetty4ServerTransportTests$1.<init>(SimpleSecurityNetty4ServerTransportTests.java:36)
09:28:03         at org.elasticsearch.xpack.security.transport.netty4.SimpleSecurityNetty4ServerTransportTests.build(SimpleSecurityNetty4ServerTransportTests.java:36)
```

This somehow implies that the protection against setting available processors twice in `Netty4Utils.setAvailableProcessors` is not catching all cases?

**Comment by dimitris-athanasiou** [comment]
Same failure in `SimpleSecurityNetty4ServerTransportTests.testHostOnMessages`.

Build scan: https://gradle-enterprise.elastic.co/s/t7qp3irnwdjvq

**Comment by jakelandis** [comment]
Had a failure from the the same class, but different test. I suspect similar root causes across the different tests, so documenting here instead of creating a new issue.  

Here is the scan: https://gradle-enterprise.elastic.co/s/vg5asrz3uyiwg

[90 failures](https://gradle-enterprise.elastic.co/scans/tests?list.size=50&list.sortColumn=startTime&list.sortOrder=desc&search.buildToolTypes=gradle&search.buildToolTypes=maven&search.relativeStartTime=P28D&search.timeZoneId=America/Chicago&tests.container=org.elasticsearch.xpack.security.transport.netty4.SimpleSecurityNetty4ServerTransportTests&tests.sortField=FAILED&tests.unstableOnly=true) from this class in the past 28 days. 


<img width="1898" alt="image" src="https://user-images.githubusercontent.com/976291/93264018-27886400-f76c-11ea-9bb5-4f0031259275.png">

**Comment by cbuescher** [comment]
Another similar looking one today on master, this time in `SimpleSecurityNetty4ServerTransportTests.testBlockingIncomingRequests`:

https://gradle-enterprise.elastic.co/s/qo4epsr4q4lc6

```
java.lang.IllegalStateException: availableProcessors is already set to [32], rejecting [32]
	at io.netty.util.NettyRuntime$AvailableProcessorsHolder.setAvailableProcessors(NettyRuntime.java:51)
	at io.netty.util.NettyRuntime.setAvailableProcessors(NettyRuntime.java:87)
	at org.elasticsearch.transport.netty4.Netty4Utils.setAvailableProcessors(Netty4Utils.java:61)
	at org.elasticsearch.transport.netty4.Netty4Transport.<init>(Netty4Transport.java:106)
	at org.elasticsearch.xpack.core.security.transport.netty4.SecurityNetty4Transport.<init>(SecurityNetty4Transport.java:67)
	at org.elasticsearch.xpack.security.transport.netty4.SecurityNetty4ServerTransport.<init>(SecurityNetty4ServerTransport.java:39)
	at org.elasticsearch.xpack.security.transport.netty4.SimpleSecurityNetty4ServerTransportTests$1.<init>(SimpleSecurityNetty4ServerTransportTests.java:36)
```

**Comment by cbuescher** [comment]
Another one, this in `testTcpHandshakeConnectionReset`: https://gradle-enterprise.elastic.co/s/okvfiuzojb3v6

**Comment by cbuescher** [comment]
Three times is a charm: https://gradle-enterprise.elastic.co/s/xb2wcesocc7e4
Muting the entire test for now.

**Comment by cbuescher** [comment]
Muted with f5f72648d4a844147a2f2eef6affdd3d9aa404e2 and  f8634e5beabbf4f4d1e7eafd8491593ef7ecdc36 on master and 7.x

**Comment by cbuescher** [comment]
@elastic/es-security please reenable the test if this muting feels too crude, I muted the whole tests since several methods seem to fail but if its clear that these are only a couple the muting might possibly be more fine grained.

**Comment by droberts195** [comment]
The same `availableProcessors is already set to [N], rejecting [N]` message was seen in `IPFilterTests.testThatNodeStartsWithIPFilterDisabled` in https://gradle-enterprise.elastic.co/s/em5noqiaekl7o

As with all the other failures, it's nothing really to do with the exact test that failed, but with something more generic in the mock node setup.

There is code in `Netty4Utils.java` that is supposed to prevent this, and comments about how the special setting is only required for tests:

```
        // we set this to false in tests to avoid tests that randomly set processors from stepping on each other
        final boolean set = Booleans.parseBoolean(System.getProperty("es.set.netty.runtime.available.processors", "true"));
        if (!set) {
            return;
        }

        /*
         * This can be invoked twice, once from Netty4Transport and another time from Netty4HttpServerTransport; however,
         * Netty4Runtime#availableProcessors forbids settings the number of processors twice so we prevent double invocation here.
         */
        if (isAvailableProcessorsSet.compareAndSet(false, true)) {
            NettyRuntime.setAvailableProcessors(availableProcessors);
```

So it seems that the solution is just to set `es.set.netty.runtime.available.processors: false` in many security tests.  It's probably best to do this sooner rather than later because muting `SimpleSecurityNetty4ServerTransportTests` just seems to have moved the problem to different tests, so eventually masses of tests will end up getting muted if it's left unfixed.

**Comment by droberts195** [comment]
`IPFilterTests.testThatNodeStartsWithIPFilterDisabled` has failed 3 times today because of this. I have muted it on master and 7.x:

- master: 352b2c39b1c6c0b42d61ce09ebd5dd4482a8cb92
- 7.x: 453756169252157a61ef6ae55ff7037f5f66f1d0
