### ISSUE TITLE
Unexpected interaction between synonym_filter and lowercase filter in custom analyzer

### ISSUE THREAD

**Issue by cjcenizal** [elastic/elasticsearch#62586]
To reproduce this strange behavior, create a `config/synonyms.txt` file containing this line:

```
foo => bar
```

Then execute these requests in order. If doing this in Console you'll have to execute them one at a time (otherwise the search results are incorrect):

```
PUT /x
{
  "mappings": {
    "properties": {
      "text_field": {
        "type":"text",
        "fields":{
          "raw":{
            "type":"keyword"
          }
        },
        "analyzer":"synonym_analyzer"
      }
    }
  },
  "settings":{
    "analysis":{
       "filter":{
          "synonym_filter":{
             "type":"synonym_graph",
             "synonyms_path":"synonyms.txt"
          }
       },
       "analyzer":{
          "synonym_analyzer":{
             "filter":[
                "synonym_filter",
                "lowercase"
             ],
             "type":"custom",
             "tokenizer":"letter"
          }
       }
    }
  }
}

PUT x/_doc/1
{
  "text_field":[
    "Foo"
  ]
}

# Returns a result, which is expected
POST x/_search
{
  "_source": [
    "text_field"
  ],
  "size": 200,
  "query": {
    "simple_query_string": {
      "query": "Foo",
      "fields": [
        "text_field"
      ]
    }
  }
}

# Returns no results, which is unexpected
POST x/_search
{
  "_source": [
    "text_field"
  ],
  "size": 200,
  "query": {
    "simple_query_string": {
      "query": "foo",
      "fields": [
        "text_field"
      ]
    }
  }
}
```

For the last request, I would expect to get back the same result as the second-to-last request. I can "fix" this by doing one of two things:

1. Remove the line from the synonyms file
2. Or reverse the order of the filters so it's `["lowercase", "synonym_filter"]`.

Is this expected behavior or have I found a bug? Thanks!

**Comment by cbuescher** [comment]
@cjcenizal This is expected behaviour. If you index the term "Foo", the synonym filter doesn't match and the lowercase converts it to "foo", which is indexed. You can check this by using the "_analyze" endpoint:
```
POST /x/_analyze
{
  "text" : "Foo",
  "field": "text_field"
}
```

The first search for "Foo" uses the same analysis chain so leads to "foo" which matches. The second search "foo" matches the synonym rule and is changed to "bar", which doesn't match. You can again check this using the "_analyze" endpoint. You would also find a document containing "bar" with that search if you index it.

The solution of reversing the analysis filters makes most sense to me. For this particular case it would also work if the rule "foo => bar" would be changed to foo => foo, bar" to retain the original form. 
Hope this helps.
