### ISSUE TITLE
Create or update users API docs incorrectly state that you cannot change user password

### ISSUE THREAD

**Issue by daleckystepan** [elastic/elasticsearch#62759]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.9.0

**Plugins installed**: [none]

**JVM version** (`java -version`): bundled with Ubuntu 20.04 ES package

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 20.04

**Description of the problem including expected versus actual behavior**:
https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-put-user.html
Actual behavior:
"Create or update users API" can update password which is not allowed according to documentation.
Expected behavior:
Password will not be changed.

**Steps to reproduce**:

 1. Create user using POST or PUT API reuquest according to  https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-put-user.html
 2. Use same query asi in 1) and also supply password field with different password than in step 1)
 3. Password of the user has been changed to password from step 2)

**Provide logs (if relevant)**:

**Comment by tvernum** [comment]
Changing the password via the Put User API has been possible since at least 5.2 and probably earlier.  
I suspect that line in the documentation is a carry over from Shield 2.

Note the docs are contradictory here. They say:

> When updating a user, you can update everything but its `username` and `password`.

and

>  When updating an existing user, the password is optional

The latter is a correct description of the current behaviour.

We discussed this internally and agreed that it is a documentation bug, and the leading sentence under **Description** should be corrected.

**Comment by jrodewig** [comment]
Relates to #62800

**Comment by lockewritesdocs** [comment]
Opened #63292 to close this issue.
