### ISSUE TITLE
Does test framework for randomising queries need to be made version-aware?

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#62783]
#### Problem
I hit an [issue in a PR](https://github.com/elastic/elasticsearch/pull/62764#issuecomment-696884845) where the new query syntax I was introducing in my `AbstractQueryTestCase.doCreateTestQueryBuilder()` implementation could not be tested adequately.
If I included use of the new syntax in in this method then the test `ClusterSearchShardResponseTests` failed because it creates random Alias filters for use in random versions of elasticsearch. The randomly-generated new syntax was not supported in these older versions.

#### Solution?
The randomisation performed in `doCreateTestQueryBuilder()` implementations should ideally be Version-aware so maybe the target version should be passed as a parameter?

**Comment by javanna** [comment]
The random queries generated by `RandomQueryBuilder` only pick from a few very common queries: match_all, term, ids, and some multi term queries. I think you were just unlucky to end up making changes to these queries which I could bet don't change so often, hence we got away with not having to carry the version around for those randomizations.

**Comment by markharwood** [comment]
Thanks @javanna. Do you think it's worth introducing a Version then?

**Comment by javanna** [comment]
I think introducing version is what we need if we want to keep randomizing versions in tests that use "random" queries. It may be that `ClusterSearchShardResponseTests` is the only one that randomizes the version today, in which case we could even adapt the test, but I am not too sure this is the best option.

**Comment by jimczi** [comment]
I don't think we should keep the randomization of the version in the generic case. When changing a query or an aggregation we cannot change how the random instance is created based on versions since that would mean creating different paths for equality (with or without the new param). IMO we should ensure that there is a rest test that checks the bwc of the new parameters and test the serialization of the aggregation on the current version in the integration tests.

**Comment by javanna** [comment]
>  IMO we should ensure that there is a rest test that checks the bwc of the new parameters and test the serialization of the aggregation on the current version in the integration tests.

I wonder what that means in practice. You mentioned integration tests but the problem here is in a unit test, which I think is a much better way to test serialization. Like I hinted above, maybe randomizing version in `ClusterSearchShardResponseTests` is not a good idea, and it worked only up until no changes were made that could affect the response being tested. From a quick look, other tests that use random queries only test against the current version, which is reasonable. We should probably adapt `ClusterSearchShardResponseTests` then to do the same and have specific bwc serialization unit tests for the query that have been changed.

**Comment by jimczi** [comment]
+1 to adapt `ClusterSearchShardResponseTests` to test the current version. IMO the yml tests are enough to check bwc at all levels including the transport serialization but I wouldn't object if you add more unit tests ;). It's just that each query needs to plug its logic regarding the equality between versions.

**Comment by javanna** [comment]
> the yml tests are enough to check bwc at all levels including the transport serialization 

While  bwc tests through yaml tests are needed and test the real scenarios, they can't be extensive and take time to write, execute and debug. Testing serialization in unit tests guarantees more coverage and allows to quickly and easily spot mistakes. I think both should be required when making changes that affect compatibility with previous versions; relying on integration tests only is not enough in my opinion.

**Comment by javanna** [comment]
Closing this issue as it did not have activity in more than a year and it seems it has been worked around.
