### ISSUE TITLE
EOF exception while creating ComposableIndexTemplate from file

### ISSUE THREAD

**Issue by charlieKmus** [elastic/elasticsearch#62810]
**Elasticsearch version** 7.9

**Plugins installed**: [ingest-attachment]

**JVM version** : 1.8

Os : Ubuntu 18.04

Hello,

I'm actually trying to instantiate a ComposableIndexTemplate from an existing file. Here is my code :
```
// Here templateFile is a readable java.io.File
byte[] stringBytes = FileUtils.readFileToByteArray(templateFile);
StreamInput stream = StreamInput.wrap(stringBytes);
ComposableIndexTemplate composableIndexTemplate = new ComposableIndexTemplate(streamInput);
```
Here is my template file :
```
{
	"index_patterns": ["content*"],
	"priority" : 104,
	"template" : {
		"mappings": {
			"dynamic_templates": [
				{
					"usercode": {
						"match_mapping_type": "string",
						"match": "user_code",
						"mapping": {
							"type": "keyword",
							"index": false
						}
					}
				},
				{
					"userid": {
						"match_mapping_type": "long",
						"match": "user_id",
						"mapping": {
							"type": "long"
						}
					}
				},
				{
					"userbirthday": {
						"match_mapping_type": "date",
						"match": "user_birthday",
						"mapping": {
							"type": "date",
							"format": "strict_date_optional_time||epoch_millis"
						}
					}
				}
			]
		}
	}
}
```
The file uses the LF line separator type.

The code send me this error :
```
java.io.EOFException: null
	at org.elasticsearch.common.io.stream.InputStreamStreamInput.readBytes(InputStreamStreamInput.java:69)
	at org.elasticsearch.common.io.stream.StreamInput.readString(StreamInput.java:477)
	at org.elasticsearch.common.io.stream.StreamInput.readCollection(StreamInput.java:1209)
	at org.elasticsearch.common.io.stream.StreamInput.readList(StreamInput.java:1159)
	at org.elasticsearch.common.io.stream.StreamInput.readStringList(StreamInput.java:1170)
	at org.elasticsearch.cluster.metadata.ComposableIndexTemplate.<init>(ComposableIndexTemplate.java:122)
```
It seams that the InputStreamStreamInput can't read my file for some reason. Is this bug known ?

Thank you

**Comment by charlieKmus** [comment]
Just for the record, I found a workaround by using the XContentParser:
```
// String templateContent = Files.readFile(templateFile);
XContentParser xContentParser = XContentType.JSON.xContent().createParser(NamedXContentRegistry.EMPTY, null, templateContent);
Template template = Template.PARSER.apply(xContentParser, null);
ComposableIndexTemplate composableIndexTemplate = new ComposableIndexTemplate(Arrays.asList("compTemplate1", "compTemplate2"), template, componentTemplatesName, indexTemplateReference.getPriority(), null, null);
```
Thanks

**Comment by jakelandis** [comment]
The `ComposableIndexTemplate(StreamInput in)` constructor is intended to be used internally with Elasticsearch's custom wire searlization/deserialization which is not interchangeable with the JSON representation (which I assume is contents of that file) and thus can't stream the contents of the file in to inflate that object. This is admittedly a bit confusing since we are re-using server side objects in the client code and part of a much bigger discussion of de-coupling client and server code. (which is is on the roadmap).

Your workaround, I would consider the correct way to do this if you are loading directly from disk, otherwise the expectation is to fully construct from code. 

Closing since we don't generally directly support loading resources from disk directly.
