### ISSUE TITLE
Missing register of `/_cluster/stats/nodes` in RestClusterStatsAction

### ISSUE THREAD

**Issue by chengyang14** [elastic/elasticsearch#62908]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.6.0

```
GET _cluster/stats/nodes

{
  "error" : {
    "root_cause" : [
      {
        "type" : "index_not_found_exception",
        "reason" : "no such index [_cluster]",
        "resource.type" : "index_expression",
        "resource.id" : "_cluster",
        "index_uuid" : "_na_",
        "index" : "_cluster"
      }
    ],
    "type" : "index_not_found_exception",
    "reason" : "no such index [_cluster]",
    "resource.type" : "index_expression",
    "resource.id" : "_cluster",
    "index_uuid" : "_na_",
    "index" : "_cluster"
  },
  "status" : 404
}

```

`/_cluster/stats/nodes ` should be registered in the RestClusterStatsAction to ensure that `/_cluster/stats/nodes` can be resolved correctly

**Comment by howardhuanghua** [comment]
We could add `filter_path` to retrieve nodes info only: `GET /_cluster/state?filter_path=nodes`.

**Comment by jakelandis** [comment]
`GET _cluster/stats/nodes` is intended be used as filtering function for how the values returned are calculated. `GET _cluster/stats/nodes/*` is equal to `GET _cluster/stats` since it uses all of the nodes to calculate the return values. If for example, you wanted only include specific nodes in the calculation you can use the nodes/<nodeId1,nodeId2> to only use those nodes to calculate the results. 

For example, given a 3 node cluster with each node having 2 processors. I want to calculate the results for only 2 of 3 nodes I could call something like this: 
```
GET _cluster/stats/nodes/7wBFewxETiaiab1x80ALZQ,EtAn3OuPQiuVpPq2BuMp1Q?filter_path=**.os.*processors

returns
{
  "nodes" : {
    "os" : {
      "available_processors" : 4,
      "allocated_processors" : 4
    }
  }
}
```
and (same cluster, but use all of the nodes)
```
GET _cluster/stats?filter_path=**.os.*processors
or
GET _cluster/stats/nodes/*?filter_path=**.os.*processors

returns

{
  "nodes" : {
    "os" : {
      "available_processors" : 6,
      "allocated_processors" : 6
    }
  }
}
```

This API allows you to get the same result set for part of the cluster vs. the whole cluster.  I would assume this is helpful to for troubleshooting or capacity planning. 

Closing the issue. In summary use `_cluster/stats` to use all nodes for the calculations returned, and use `_cluster/stats/nodes/<nodeId1,nodeId2>` to filter results to only include the named nodes by nodeId

**Comment by chengyang14** [comment]
hi @jakelandis  @howardhuanghua ,thanks for your replay.
The documentation for the [`Cluster Stats API`](https://www.elastic.co/guide/en/elasticsearch/reference/7.9/cluster-stats.html) is as follows
```
Requeste
GET /_cluster/stats
GET /_cluster/stats/nodes/<node_filter>

Path parameters
<node_filter>
(Optional, string) Comma-separated list of node filters used to limit returned information.
 Defaults to all nodes in the cluster.
```

`GET _cluster/stats/nodes/* `is equal to `GET _cluster/stats/nodes/` in the document. 

So i think we shoud add ` new Route(GET, "/_cluster/stats/nodes/"));` in `RestClusterStatsAction`
```
    @Override
    public List<Route> routes() {
        return List.of(
            new Route(GET, "/_cluster/stats"),
            new Route(GET, "/_cluster/stats/nodes/{nodeId}"));
    }
```
