### ISSUE TITLE
EQL: Clarify and document event category check quoting

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#62933]
All EQL queries start as follows:

`eventType where condition` where `eventType` is a shortcut for `event.category == eventType`.

Most of the examples assume the actual value inside `eventType` doesn't need any kind of quoting yet what happens if quoting is needed?
The grammar declares the `eventType` as an `identifier` but that is incorrect - it's actually a value which means in case of string values that need escaping one would need to use `"` not `` ` ``.
That is:
`"eventType" where condition` and *not* `` `eventType` where condition`` and by translation, in case of raw strings:
`"""eventType""" where condition `.

That said, since in most queries the value is not quoted, a dedicated grammar declaration is required to allow declaration without `"` though my recommendation for generated queries is to always use that.

Further more the notion of identifier inside the grammar needs cleaning up. It is currently used for:
a. event category checks (as mentioned above)
b. actual identifiers (which raises the question of escaping backticks)
c. function names 

There is too much overloading and while there is a common base between these types, their characteristics and not separated. This can lead to a case where a function declaration can use backticks which is invalid.

**Comment by matriv** [comment]
`master` : 306e1d76da3db652db57f11f847705b3995609ff
`7.x` : 3cac996373a539d3027624a7987281f56fe0df46

**Comment by rw-access** [comment]
(Looks like this comment never got submitted to GitHub. Posting it now.)

I'm not sure that I agree with the premise of the issue, I think if you look at EQL in Elasticsearch within a vacuum, then yes, the event type is purely an alias for `event.category == "<eventType>"`.

However, I don't think you can or should look at it in a vacuum. At the most basic level, an identifier is just a name for something. For EQL in Endgame, each event type actually had a separate schema. So if you did `process where X` then the condition X is validated against the `process` event schema. Also, for those implementations, the event type actually lives outside and inside the event data.

When we were first exploring EQL, we actually had a length discussion (https://github.com/elastic/elasticsearch/issues/49462) about how the "event type" concept will translate into Elasticsearch. It wasn't an obvious choice and there were pros and cons for several possible approaches. That just emphasizes how choosing to use `event.category` as the matched field is purely an implementation detail and not a property of the language or specification itself.

Since the `event.category` alias is an implementation detail of EQL in Elasticsearch, then what should be the syntax that's captured in the specification? I think an identifier (since it's just a name anyway) actually makes sense. "I'm looking for <eventType> events that match <condition>". You're naming the type of event that you're looking for.  EQL has pipe identifiers, function name identifiers and field name identifiers. I'm not sure why the syntax for event type identifiers should be special and look like strings, instead of using the `` `<escaped event type>` `` notation, which already represents an escaped identifier that may contain special characters
