### ISSUE TITLE
NullPointException occurs if extendedBounds is not set and minBound/maxBound is called

### ISSUE THREAD

**Issue by GeorgeAp** [elastic/elasticsearch#62934]
**Elasticsearch version** : 8.0.0

**JVM version** : 11.0.8

**OS version** : 18.04.1-Ubuntu

**Description of the problem including expected versus actual behavior**:
The methods `minBound()` and `maxBound()` in `HistogramAggregationBuilder` return double which leads to `NullPointException` if the optional `extendedBounds` is not set and these methods are called. A possible fix is to set the return type to Double.
https://github.com/elastic/elasticsearch/blob/bd8701da4fa7731ceb55cd80b70f712b42902181/server/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/HistogramAggregationBuilder.java#L196-L203

**Steps to reproduce**:

 1. Create a test that does not set the `extendedBounds`.
 2. Check for the values of `minBound` and `maxBound`.
 3. `NullPointException` occurs since the return type is primitive and `extendedBounds.getMin()`/`extendedBounds.getMax()` is null.

**Comment by alishahusain** [comment]
May I go ahead and set the return type to Double and create a PR to fix this issue?

**Comment by polyfractal** [comment]
Hi @alishahusain :)  I think this would be a good first issue, although I'm not sure the exact behavior we want.  @imotov would probably have an opinion on this issue but he's currently on vacation (back next week).  I think we probably have two options:

- Change the return signature to Double as suggested, although that might just move the NPE somewhere else
- Check to see if extendedBounds is `null`, and if it is, return -/+ `Infinity` for min/max bounds.  E.g. if the bounds aren't set, then that is comparable to having the bounds == positive and negative infinity.  I suspect that's a better option since we won't be returning nulls, although `Infinity` has it's own strange issues too :)

Feel free to work up a PR, we can review it and see what @imotov thinks when he gets back :)  Or you can wait and see what he thinks before getting started.

**Comment by alishahusain** [comment]
Thanks! I went with the second option in my pull request here: #64091

**Comment by imotov** [comment]
@polyfractal yes I think it is +/- infinity because we want extended bounds to have no effect instead of extending to the entire range of double. I left some comments on PR.
