### ISSUE TITLE
Failure in saving percolate query with date type function score 

### ISSUE THREAD

**Issue by ajhalani** [elastic/elasticsearch#6340]
When I try to save a query in percolate which has function score on a date field, it fails with error Failed to parse NullPointerException. If function score is on another data type field like number, it works fine. 

```
PUT testindex

PUT testindex/document/1
{
  "actionDate" : "2014-05-01",
  "score" : 5
}

PUT testindex/.percolator/1
{
  "query" : {
    "function_score" : {
      "functions" : [
        {
          "exp" :{ 
              "actionDate" : {
                "origin" : "now",
                "scale" : "10d"
              }
          }
        }
      ],
      "query" : {
        "match_all": {}
      }
    }
  }
}

{
   "error": "RemoteTransportException[[nylxdev1.node][inet[/172.17.9.175:9301]][index]]; nested: PercolatorException[[testindex] failed to parse query [1]]; nested: QueryParsingException[[testindex] Failed to parse]; nested: NullPointerException; ",
   "status": 500
}
```

**Comment by martijnvg** [comment]
Fixing the NPE that is occurring is relatively easy, but there is a bigger problem with this percolator query.

The `now` usage in this function score function is problematic, because it is resolved at percolate query register time and after that for each percolate request the now time will stay the same. This is similar to date ranges issue in percolator queries and alias filters, which was fixed only recently: #8534

Fixing this will add additional logic similar as was added via #8534, do we want this extra complexity?

**Comment by clintongormley** [comment]
@martijnvg i think so - it makes sense for the same reasons as #8534

**Comment by clintongormley** [comment]
With the new query parsing coming in 3.0, it should be possible to handle dates correctly.

@martijnvg there's nothing to do before 3.0, is there?

**Comment by martijnvg** [comment]
This has been fixed some time ago, I think I just forgot to close this issue:
https://github.com/elastic/elasticsearch/commit/7cc2bc8a145456297e7e33a2c22f5ea4b778e04e

If `now` is used in range queries we resolve that at lucene query rewrite time. In case of the percolator that happens at percolate time and the current time should therefor not be stale any more.
