### ISSUE TITLE
[ML] Reassigned datafeeds should skip time to past latest results

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#63400]
I will try to explain the issue here with the following scenario.

![image](https://user-images.githubusercontent.com/9351617/95331372-9449d680-08b2-11eb-8d35-44d45a4d7e1d.png)

A datafeed has been running on a node. The last model snapshot was stored a couple of buckets ago. Since then some more buckets have been finalized. We have seen a record some time in the current bucket.

Then the node disconnects. The datafeed task is assigned to another node. The model snapshot is loaded.

We define the datafeed's starting point as `max(latest_final_bucket_end_time, latest_record_time)`. Let's call this `checkpoint`.

As things currently work, the datafeed task has the original `start` parameter stored in the task params. We check whether that `start` time is after the `checkpoint`. If it is, we skip time in the model to the `checkpoint`. If not we do not.

The problem is that after we send enough data to finalize the current bucket (orange in the picture) the model will calculate results for all buckets since the model snapshot was taken. The new results will overwrite the old ones.

**Comment by droberts195** [comment]
One more thing to note is that the impact of this bug is _much_ worse for count and sum detectors than for min/max/mean detectors.  The reason is that count and sum detectors will likely raise anomalies for buckets with no data (depending on whether 0 is atypical), whereas min/max/mean detectors will not raise anomalies when no data is seen.
