### ISSUE TITLE
Text fields should not expose internal field types

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#63446]
When `text` fields has `index_prefixes` or `index_phrases` enabled, they create subfields of the form `field._index_prefixes`. These fields are only meant for internal optimizations and shouldn't be searched on directly.

However the text mapper exposes these hidden fields as if they were configured as multi-fields. This means that field caps includes the hidden fields, as when requesting all fields through `fields=*`. The search 'fields' option will also match against them, which can add duplication to the output.

Perhaps we should stop exposing these fields, keeping them an implementation detail. Note that the same consideration applies to `search_as_you_type`.

**Comment by romseygeek** [comment]
The index-time analyzer for a MapperService needs to know about all index-time fields, and it currently learns about them via the `iterator()` method on Mapper, which is the same way that the MappingLookup learns about field types.  I've wanted to change this for a while - if we can instead register analyzers and field types separately, then we don't need to have full-blown Mapper implementations for these subfields and can instead handle everything in the parent `parseCreateField`.

`search_as_you_type` is slightly different because it works by letting users search directly on the subfields.  It would be nice to hide this implementation detail behind a specialised query instead.

**Comment by romseygeek** [comment]
Thinking about this more, separating the registration of Mappers and MappedFieldTypes wouldn't actually help here, because we still need the MappedFieldType to be set up so that it can be searched.  Perhaps a better move would be to make MappedFieldType responsible for building IndexFieldCapabilities, so that an implementation can choose to not make itself visible to field caps by returning `null`?
