### ISSUE TITLE
Expose only a subset of precommit tasks to 3rd party developers

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#63697]
The `precommit` task enforces Elasticsearch specific constraints that don't always apply to 3rd party developers. We should not (by default) expose all the `precommit` tasks for plugin developers. Rather, we should differentiate between `internal` and `external` precommit task. 

easy repro:

install https://github.com/spinscale/cookiecutter-elasticsearch-ingest-processor
cookiecutter gh:spinscale/cookiecutter-elasticsearch-ingest-processor
accept all defaults
cd ingest-awesome
./gradlew tasks --all

```
Build tasks
-----------
assemble - Assembles the outputs of this project.
build - Assembles and tests this project.
buildDependents - Assembles and tests this project and all projects that depend on it.
buildNeeded - Assembles and tests this project and all projects it depends on.
classes - Assembles main classes.
clean - Deletes the build directory.
jar - Assembles a jar archive containing the main classes.
javadocJar - Assembles a jar containing javadocs.
sourcesJar - Assembles a jar containing source files.
testClasses - Assembles test classes.

Build Setup tasks
-----------------
init - Initializes a new Gradle build.
wrapper - Generates Gradle wrapper files.

Documentation tasks
-------------------
javadoc - Generates Javadoc API documentation for the main source code.

ES cluster formation tasks
--------------------------
listTestClusters - Lists all ES clusters configured for this project

Help tasks
----------
buildEnvironment - Displays all buildscript dependencies declared in root project 'ingest-awesome'.
components - Displays the components produced by root project 'ingest-awesome'. [incubating]
dependencies - Displays all dependencies declared in root project 'ingest-awesome'.
dependencyInsight - Displays the insight into a specific dependency in root project 'ingest-awesome'.
dependentComponents - Displays the dependent components of components in root project 'ingest-awesome'. [incubating]
help - Displays a help message.
model - Displays the configuration model of root project 'ingest-awesome'. [incubating]
outgoingVariants - Displays the outgoing variants of root project 'ingest-awesome'.
projects - Displays the sub-projects of root project 'ingest-awesome'.
properties - Displays the properties of root project 'ingest-awesome'.
tasks - Displays the tasks runnable from root project 'ingest-awesome'.

IDE tasks
---------
cleanIdea - Cleans IDEA project files (IML, IPR)
idea - Generates IDEA project files (IML, IPR, IWS)
openIdea - Opens the IDEA project

Publishing tasks
----------------
generateMetadataFileForNebulaPublication - Generates the Gradle metadata file for publication 'nebula'.
generatePomFileForNebulaPublication - Generates the Maven POM file for publication 'nebula'.
publish - Publishes all publications produced by this project.
publishNebulaPublicationToMavenLocal - Publishes Maven publication 'nebula' to the local Maven repository.
publishToMavenLocal - Publishes all Maven publications produced by this project to the local Maven cache.

Verification tasks
------------------
check - Runs all checks.
precommit - Runs all non-test checks
test - Runs the unit tests.

Other tasks
-----------
bundlePlugin
checkstyle
checkstyleMain - Run Checkstyle analysis for main classes
checkstyleTest - Run Checkstyle analysis for test classes
cleanIdeaModule
cleanIdeaProject
cleanIdeaWorkspace
compileJava - Compiles main Java source.
compileTestJava - Compiles test Java source.
copyCheckstyleConf
copyPluginPropertiesTemplate
copyRestApiSpecsTask
copyYamlTestsTask
dependenciesInfo - Create a CSV file with dependencies information.
dependencyLicenses
extract-linux-x64-jdk-adoptopenjdk-8u242+b08
extractElasticsearch7.9.2
filepermissions - Checks java source files for correct file permissions
forbiddenApis - Runs forbidden-apis checks.
forbiddenApisMain - Runs forbidden-apis checks on 'main' classes.
forbiddenApisResources
forbiddenApisTest - Runs forbidden-apis checks on 'test' classes.
forbiddenPatterns - Checks source files for invalid patterns like nocommits or tabs
generateNotice - Create a notice file from dependencies
generatePom
ideaModule - Generates IDEA module files (IML)
ideaProject - Generates IDEA project file (IPR)
ideaWorkspace - Generates an IDEA workspace file (IWS)
integTest
integTestRunner
jarHell - Runs CheckJarHell on the configured classpath
licenseHeaders - Checks sources for missing, incorrect, or unacceptable license headers
loggerUsageCheck - Runs LoggerUsageCheck on output directories of all source sets
pluginProperties
prepareKotlinBuildScriptModel
processResources - Processes main resources.
processTestResources - Processes test resources.
run
testingConventions - Tests various testing conventions
thirdPartyAudit
thirdPartyAuditResources
updateShas - Updates the sha files for the dependencyLicenses check
validateNebulaPom
validatePom

```

**Comment by rjernst** [comment]
I don't think `precommit` itself is a problem, but many (maybe most) of the precommit tasks we have are to ensure Elasticsearch coding guidelines. There are some, though, that are crucial for external plugin authors as well. For example, jarHell is important because it checks something we check at runtime when loading plugins. So if this task fails, the plugin would later fail anyways when run with Elasticsearch.

**Comment by jakelandis** [comment]
Thanks Ryan. I updated the title and description to reflect exposing only a subset of the `precommit` tasks.

**Comment by mark-vieira** [comment]
@breskeby do you mind following up on this. We had an issue now where for 7.10 external plugin developers are seeing errors trying to run the `loggerUsageCheck` task related to #63631. Realistically we simply don't want to apply that precommit plugin for external authors.

**Comment by breskeby** [comment]
I'm not 100% sure which precommit checks to expose to external and which not. I started working on splitting things up at https://github.com/elastic/elasticsearch/pull/65102 and for now I have kept:

- JarHellPrecommitPlugin
- ThirdPartyAuditPrecommitPlugin

in the precommit checks for external plugins. I understand the need that every plugin needs to avoid JarHell, but what was the original motivation for definition of forbidden apis. is that also to prevent plugins working as expected? Therefore I would keep `ThirdPartyAuditPrecommitPlugin` in the external checks as well. 

Given this list these precommit checks will be considered internal precommit checks only applied for our elasticsearch build:

- CheckstylePrecommitPlugin
- ForbiddenApisPrecommitPlugin
- ForbiddenPatternsPrecommitPlugin
- LicenseHeadersPrecommitPlugin
- FilePermissionsPrecommitPlugin
- TestingConventionsPrecommitPlugin

This change also brings in a change in behaviour for external plugin authors as we just remove some of those plugins from external builds. E.g. the cookie cutter template listed above disables checkstyle tasks. With this change those templates would fail as they references tasks that are not existing anymore. Likely similar breaking changes will happen to most other third party plugin builds. 

Should we instead of introducing this breaking change straight ahead have instead some sort of deprecation lifecycle for this? We could emit a warning for now when apply the BuildPlugin externally. 

Also is there any documentation around using our plugins for external builds? If not I think it would make sense to introduce something. It can be lightweight and grow over time but having a goto place for plugin users might be useful for our community. Thoughts? // cc @rjernst @mark-vieira

**Comment by mark-vieira** [comment]
The `ThirdPartyAudit` is effectively just forbidden apis but for binary dependencies. I'm not sure to what degree we should do these checks for plugins. In the end if a plugin dependency is doing something naughty won't it get blocked by security manager?

@rjernst what's the intention of the forbidden apis stuff, really? Is it more code conventions or do we strictly want to ensure folks to don't third-party libraries that use certain internal APIs. And if so, even w/o that check that stuff would fail at runtime due to the security manager, yes?

**Comment by mark-vieira** [comment]
> Should we instead of introducing this breaking change straight ahead have instead some sort of deprecation lifecycle for this? We could emit a warning for now when apply the BuildPlugin externally and mention that this will be removed in a later release.

We've been pretty cavalier with this in the past so I don't think so, but we want to do better starting with 8.0 and this work is part of that effort. That is, minimizing the surface area of our build code we expose to external plugin authors such that breaking changes are much less likely. Since this is iterating towards that goal I say we move forward.

**Comment by mark-vieira** [comment]
> Also is there any documentation around using our plugins for external builds?

Yes, and this is a must have for 8.0 IMO. Right now the example plugins effectively are the documentation.

**Comment by rjernst** [comment]
The intention of the forbidden apis stuff is just to prohibit our own developers from using trappy and poorly engineered APIs. 

I think jar hell is the only one we should add for external plugin authors.

**Comment by mark-vieira** [comment]
Thanks @rjernst. Let's go with Ryan's suggesting @breskeby and consider only jar hell checks to be "external".
