### ISSUE TITLE
EQL: Correctness test queryNo=10 fails

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#63742]
```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:eql:qa:correctness:javaRestTest' --tests "org.elasticsearch.xpack.eql.EsEQLCorrectnessIT.test {10}" -Dtests.seed=27931E54C551C5D1 -Dtests.security.manager=true -Dtests.locale=ar-EG -Dtests.timezone=Africa/Juba -Druntime.java=15

org.elasticsearch.xpack.eql.EsEQLCorrectnessIT > test {10} FAILED
    java.lang.AssertionError: Failed to match event ids for query No: 10 : sequence by hostname with maxspan=1m
      [network where hostname == "newyork" and destination_port in (135, 139, 445, 3389)] by source_port, source_address
      [security where hostname == "newyork" and event_id == 4624] by source_port, ip_address
    | tail 10
     expected:<3940731> but was:<3866512>
        at __randomizedtesting.SeedInfo.seed([27931E54C551C5D1:AFC7218E6BADA829]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.elasticsearch.xpack.eql.EsEQLCorrectnessIT.test(EsEQLCorrectnessIT.java:205)
```
The subqueries involved yield the correct number of events but the sequence query fails.
The query is currently commented out in the `queries.toml` of the `eql/qa/correctness` module on `master`, `7.x` and `7.10` branches.

**Comment by astefan** [comment]
This is indeed a bug. And it comes from how we handle the events in one of the secondary sequence queries (that is any of the queries after the first one). In case of a `tail` sequence of events, the bug is that we double revert the limits (in time) of a window of events resulting from the first query. For `tail` the first query is executed with a descending sorting (on timestamp and tiebreaker field) and any of the subsequent queries in the sequence have an ascending sorting (on timestamp and tiebreaker field).
And instead of discarding the events that are before the first event in the window, we discard the events after. And this includes all events in this case. Thus, instead of building the most recent set of sequences, we build some that are earlier. Code-wise, the double reverting happens [here](https://github.com/elastic/elasticsearch/blob/7.10/x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/execution/sequence/TumblingWindow.java#L219)

```
        log.trace("Querying (secondary) stage [{}] {}", criterion.stage(), request);
        client.query(request, wrap(r -> {
            Ordinal boundary = reversed ? window.begin : window.end;
            List<SearchHit> hits = searchHits(r);
            // filter hits that are escaping the window (same timestamp but different tiebreaker)
            hits = trim(hits, criterion, boundary, reversed);
```

and [here](https://github.com/elastic/elasticsearch/blob/7.10/x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/execution/sequence/TumblingWindow.java#L293).

```
    private List<SearchHit> trim(List<SearchHit> searchHits, Criterion<BoxedQueryRequest> criterion, Ordinal boundary, boolean reversed) {
        int offset = 0;

        for (int i = searchHits.size() - 1; i >=0 ; i--) {
            Ordinal ordinal = criterion.ordinal(searchHits.get(i));
            boolean withinBoundaries = reversed ? ordinal.afterOrAt(boundary) : ordinal.beforeOrAt(boundary);
            if (withinBoundaries == false) {
```

I'll wait for the work that's part of https://github.com/elastic/elasticsearch/issues/58646 that will most likely fix this issue as well and will re-test these queries then. The issue will be closed when that fix is confirmed.
