### ISSUE TITLE
CoordinatorTests.testUnresponsiveLeaderDetectedEventually reproducible failure:

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#63918]
This fail in one PR but I seem to be able to reproduce it in master.

**Build scan**:

https://gradle-enterprise.elastic.co/s/d5pmmsn5fz3bi

**Repro line**:

```
 ./gradlew ':server:test' --tests "org.elasticsearch.cluster.coordination.CoordinatorTests.testUnresponsiveLeaderDetectedEventually" -Dtests.seed=5C32928A3DFC7F15 -Dtests.security.manager=true -Dtests.locale=bg-BG -Dtests.timezone=Mexico/General -Druntime.java=11

```
**Reproduces locally?**:

yes

**Applicable branches**:

Only tried on master

**Failure history**:

Seems not to have fail in a long time.

**Failure excerpt**:

```
  1> [2020-10-20T04:56:15,000][INFO ][o.e.c.c.CoordinatorTests ] [testUnresponsiveLeaderDetectedEventually] after test
  2> REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.cluster.coordination.CoordinatorTests.testUnresponsiveLeaderDetectedEventually" -Dtests.seed=5C32928A3DFC7F15 -Dtests.security.manager=true -Dtests.locale=bg-BG -Dtests.timezone=Mexico/General -Druntime.java=11
  2> java.lang.AssertionError: node1 has applied its state 
    Expected: <10L>
         but: was <9L>
        at __randomizedtesting.SeedInfo.seed([5C32928A3DFC7F15:265B95CAD8EEBC04]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.elasticsearch.cluster.coordination.AbstractCoordinatorTestCase$Cluster.stabilise(AbstractCoordinatorTestCase.java:537)
        at org.elasticsearch.cluster.coordination.CoordinatorTests.testUnresponsiveLeaderDetectedEventually(CoordinatorTests.java:532)
  2> NOTE: leaving temporary files on disk at: /Users/ivera/forks/elasticsearch-fork/server/build/testrun/test/temp/org.elasticsearch.cluster.coordination.CoordinatorTests_5C32928A3DFC7F15-003
  2> NOTE: test params are: codec=Asserting(Lucene87): {}, docValues:{}, maxPointsInLeafNode=984, maxMBSortInHeap=7.724307660680699, sim=Asserting(RandomSimilarity(queryNorm=false): {}), locale=bg-BG, timezone=Mexico/General
  2> NOTE: Mac OS X 10.15.6 x86_64/N/A 11.0.8 (64-bit)/cpus=12,threads=1,free=506481344,total=536870912
  2> NOTE: All tests run in this JVM: [CoordinatorTests]
```

**Comment by original-brownbear** [comment]
@DaveCTurner or @fcofdez I think this needs a look from one of you. I must admit I don't fully understand how https://github.com/elastic/elasticsearch/pull/62954 actually drains all the disruptions to begin with (all the `rarely()` restarting and disconnecting confuses me) so I'd just be guessing here :)

**Comment by DaveCTurner** [comment]
Thanks @fcofdez; FWIW I don't think this is to do with #62954. It stabilises ok, then calls `originalLeader.blackhole()`, then does another `stabilise()` (without a `runRandomly()`) and it's this second stabilisation that's failing apparently because the new leader is still waiting for a response from the original leader before applying its cluster state.

The problem seems to be that the election at the start of the second stabilisation phase is very messy: `node0` and `node3` both trigger elections concurrently, twice, each of which fails before finally settling down and electing `node1`. I think this is just incredibly unlucky timing that isn't accounted for in the test, made slightly more likely by having 5 nodes in this cluster. It looks to be enough to extend the timeout by a couple of minutes to allow for this kind of mess.

**Comment by fcofdez** [comment]
Sorry for the delay, It took me longer than expected to fully understand what was going on on this scenario.

As @DaveCTurner pointed out, this is a messy scenario:
1. `node0` and `node3` starts an election concurrently
2. `node0` becomes leader on term 4
3. `node3` starts a new election with proposed term 5
4. `node0` becomes candidate as a newer term is proposed
5. `node0` starts a new election with proposed term 6
6. `node3` becomes leader on term 5
7. `node3` steps down as candidate as a newer term is proposed 
8. `node3` starts a new election with proposed term 7 after the cluster state publication
9. `node3` election scheduler triggers a new election with term 8 as it learns about the term 7 proposed by `node3` during the pre voting round
10. `node3` becomes leader on term 8
11.  `node2` starts a new election on term 9
12. `node3` steps down as candidate
13. `node1` and `node3` start a new concurrent election proposed term 10
14. `node1` wins the election on term 10, but since it missed the Join vote from `node3` it bumps its term to 11
15. `node1` becomes candidate again and triggers a new election with term 12
16. `node1` election scheduler triggers a new election on term 13
17. `node1` is elected as leader on term 13, and things stabilize at this point
18. The stabilization phase fails before `node1` has noticed that the old leader is unreachable, so there's still cluster state publications in flight.

I've opened https://github.com/elastic/elasticsearch/pull/64462 to tackle this. Adding the time for an additional election seems to fix the issue, but maybe that can hide problems for smaller clusters?
