### ISSUE TITLE
Request to support quota ratelimit

### ISSUE THREAD

**Issue by calm4wei** [elastic/elasticsearch#64102]
### Situation
Write and query requests are configured with corresponding thread pool and queue size. When the request queue is full, the server adopts a rejection strategy to reject new requests in order to achieve the purpose of request flow limitation.

### Problem
However, when the bulk thread pool or query thread pool is running at full capacity, the CPU utilization may continue to maintain at 100% and the system is running under high load, resulting in a corresponding increase in request delay. The way to deal with this situation is very limited. First, you can adjust the number of cores and queue size of the thread pool to limit the request to reduce the system load, but this requires modifying the thread pool configuration parameters in elasticsearch.yml and restarting the node. I think this is a very serious operation. In addition, the pressure on the cluster can be relieved by expansion, but not all resources are available for expansion. Therefore, ES still lacks an effective protection mechanism to prevent the cluster from being overwhelmed by requests.

### Solution
I think a dynamic current limiting mechanism can be added to realize the protection mechanism on the server side. Through the `index.bulk.ratelimit` and `index.query.ratelimit` in the index settings, dynamically adjust the limit on the specified index request.

### Related issues
- Configure `search.allow_expensive_queries` per role ([#53607](https://github.com/elastic/elasticsearch/issues/53607#issue-582354989))

**Comment by mayya-sharipova** [comment]
@calm4wei Thank you for submitting a feature request.

I would like to let you know what we already have in terms of throttling indexing:

1. Throttling indexing if merging can't catch up. This depends on the number of current merges.

2. Introduced in 7.9 [indexing back pressure]( https://www.elastic.co/guide/en/elasticsearch/reference/7.9/index-modules-indexing-pressure.html), this allows to back pressure indexing if too much memory is going to be consumed by it.

Lastly, we have a plan to introduce back pressure related to the [CPU cost of indexing](https://github.com/elastic/elasticsearch/issues/59263#issue-653666735).


---
I am interested in your use case: is your indexing involve a lot of CPU utilization? Is this because of ingest processing?  Have you checked what causing  this CPU utilization?  Have you looked at our [suggestions](https://www.elastic.co/guide/en/elasticsearch/reference/current/tune-for-indexing-speed.html) to tune for indexing speedup?

**Comment by henningandersen** [comment]
@calm4wei thanks for your interest in improving Elasticsearch. In addition to Mayya's questions, I would like to be sure I understand correctly the symptom/consequences you are faced with:

> system is running under high load, resulting in a corresponding increase in request delay

I think you mean that each bulk request will be delayed so much that you think it was better to reject it? Or does this concern the impact on other requests like searches? Can you elaborate on the symptoms as well as include information on the concrete delays you see?

> pressure on the cluster can be relieved by expansion, but not all resources are available for expansion

Can you elaborate on the specific issue you are dealing with here? Adding more nodes and increasing `number_of_shards` should normally be able to distribute the indexing load.

About the proposed solution:

> dynamic current limiting mechanism ... dynamically adjust the limit on the specified index request.

is the intention to start rejecting requests when the rate limiter kicks in? Or queue them up, i.e., not fully utilize the thread pool to try to balance CPU usage such that other requests (search maybe) can get more resources?

**Comment by calm4wei** [comment]
> @calm4wei Thank you for submitting a feature request.
> 
> I would like to let you know what we already have in terms of throttling indexing:
> 
> 1. Throttling indexing if merging can't catch up. This depends on the number of current merges.
> 2. Introduced in 7.9 [indexing back pressure](https://www.elastic.co/guide/en/elasticsearch/reference/7.9/index-modules-indexing-pressure.html), this allows to back pressure indexing if too much memory is going to be consumed by it.
> 
> Lastly, we have a plan to introduce back pressure related to the [CPU cost of indexing](https://github.com/elastic/elasticsearch/issues/59263#issue-653666735).
> 
> I am interested in your use case: is your indexing involve a lot of CPU utilization? Is this because of ingest processing? Have you checked what causing this CPU utilization? Have you looked at our [suggestions](https://www.elastic.co/guide/en/elasticsearch/reference/current/tune-for-indexing-speed.html) to tune for indexing speedup?

Thank you for providing solutions related to merge and indexing current limiting, which is very helpful to us.
Indexing has not been found to cause 100% of the cpu usage, but the large number of indexing we encountered often produces frequent jvm gc and port no response.
A large number of queries will cause the CPU usage to continue to be maintained at 100%, such as termes queries, range queries, simple aggregate queries, etc.

**Comment by calm4wei** [comment]
@henningandersen 

> I think you mean that each bulk request will be delayed so much that you think it was better to reject it? Or does this concern the impact on other requests like searches? Can you elaborate on the symptoms as well as include information on the concrete delays you see?

I don't mean to directly reject the request when the request delay is high. I think it is necessary for the request that cannot be processed in time to be placed in the request queue.
A situation I encountered:
The ES cluster has 10 nodes, the machine is configured with RAM 128G/CPU 20*2cores, and each node is configured with 30G heap memory
When the write request reaches 10w/s and the query request reaches 5w/s, the load of some nodes will be very high, the CPU utilization rate will continue to remain at 100%, the request queue will continue to accumulate, and the request delay will increase from about 100ms to 1 second the above.

> Can you elaborate on the specific issue you are dealing with here? Adding more nodes and increasing number_of_shards should normally be able to distribute the indexing load.

Yes, expanding the number of nodes and shards is very helpful to reduce the high load of the cluster.
The situation we encountered is that there are no additional machines for timely expansion, so we want to add other current limiting mechanisms to protect the stability of the cluster.

> is the intention to start rejecting requests when the rate limiter kicks in? Or queue them up, i.e., not fully utilize the thread pool to try to balance CPU usage such that other requests (search maybe) can get more resources?

I think that when the speed limiter is activated, the request can be rejected instead of being queued again. However, this rate limiting configuration is based on tps or qps at the index level, rather than classifying according to the request type.

**Comment by henningandersen** [comment]
@calm4wei thanks for an elaborate response. I want to follow-up with a few more questions and comments:

It sound like you have two sets of indices, one set that you want to protect from being disturbed by the activity on another set? Can you elaborate a bit on the use case here? Is it time-based indexing or a classic search use case? Do you have multiple separate sets of data in the same cluster?

There are two ways (at least) to partition the workload:

1. To have multiple clusters if data is truly separate.
2. Use [index allocation filters](https://www.elastic.co/guide/en/elasticsearch/reference/current/shard-allocation-filtering.html#index-allocation-filters) to designate a set of machines for specific indices.

If indexing uses too much heap you can limit the [indexing buffer](https://www.elastic.co/guide/en/elasticsearch/reference/current/indexing-buffer.html), this could help reduce the impact on search. This also implies an automatic throttle mechanism, which was fixed in 7.10 (#61768).

Also, it does sound like in your case that adjusting the number of threads in the write and search thread pool could make sense to avoid a cpu overload situation. ES might use too many threads for a workload that is both write and search heavy and at the same time fits entirely into available RAM. If possible, a diagnostic dump could help us gain a bit more understanding of the kind of workload.

**Comment by henningandersen** [comment]
@calm4wei do you have any input to above?

**Comment by danielmitterdorfer** [comment]
No further feedback received. @calm4wei if you have the requested information please add it in a comment and we can look at re-opening this issue.
