### ISSUE TITLE
Long tail shard query inference

### ISSUE THREAD

**Issue by calm4wei** [elastic/elasticsearch#64101]
A search request will be forwarded to all independent shards, but sometimes because a certain shard query takes too long, resulting in high latency for the entire request.
If when distributing requests to specific shards, first determine the load status and gc status of the node where the shard is located, and then choose to forward the request to the shard copy on the node with low load, which will be an effective way to avoid the long tail of the query means.
Of course, when the request is forwarded to the shard copy of the low-load node, the long tail of the query may also occur. We define a metric value to clearly distinguish the state of the long tail of the query under what circumstances. Assuming that a query request involves a distributed query of n shards, the time to forward the shard query is t1, and the query time after receiving `n-1` shard request results is t2. If the query time of the `nth` shard exceeds `(t2-t1)*2`, it is regarded as a long tail node. Therefore, this metric value can use `(t2-t1)*2` as the basis for judgment.

**Comment by jimczi** [comment]
Have you heard of adaptive replica selection  ? It is explained [here](https://www.elastic.co/fr/blog/improving-response-latency-in-elasticsearch-with-adaptive-replica-selection) and is now the default strategy for search requests in Elasticsearch. 
So I hope that you don't mind if I close this issue since the feature you're asking is already implemented.
