### ISSUE TITLE
Support unsigned long field type in painless

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#64361]
The casting model needs to be overhauled to support the `unsigned long` field type, added in [60050](https://github.com/elastic/elasticsearch/pull/60050), as this type can return a `BigInteger`.

Type promotion in the casting model works well for primitive types, String and `def`.

The `def` type is tricky to handle with boxed types and type promotion, the current model has limited support for boxed types.

As this is a major rework on a subtle subsystem, we should look toward interim support for unsigned long.

@jimczi @mayya-sharipova what do you think about having `unsigned long` field return `double`s for `ScriptDocValues`?

Relates: https://github.com/elastic/elasticsearch/issues/64347

**Comment by jdconrad** [comment]
There are two major issues with unsigned long fields in scripting as it stands.
1. As pointed out here, our casting model does not have good support for Big* types. We discussed this in the weekly core-infra meeting, and it's something we do want to add to Painless, but it's a large change to the casting model.
2. unsigned long can return two different types - long or BigInteger. This works because we happen to return def form doc access, but it makes any currently possible work around more difficult because this means a user has to do an instanceof check to see if the field returned BigInteger to get a useful value out of it to do operations on.

**Comment by mayya-sharipova** [comment]
> what do you think about having unsigned long field return doubles for ScriptDocValues?

It depends what precision a user expects. Conversion to double leads to loss of precision on last  digits. For aggregations it doesn't much matter, as they already work on doubles, but for something like `script_fields` I think this loss of precision can be significant.

>  it's something we do want to add to Painless, but it's a large change to the casting model

I would suggest before this is ready,  to leave things as they are and just to add a warning in the documentation for `unsigned_long` about implicit casts. PR #64422 already provides examples how `unsigned_long` should be used in scripts, we can enhance the documentation even futher.

**Comment by jdconrad** [comment]
@mayya-sharipova I took a look at #64422 and the documentation is good. My two main concerns noted above remain, however.

Here's what I would propose instead:

1. For any conversions to other types use ```doubleValue``` or ```longValue``` instead off of casting here. In Painless, when a method is called on a primitive type, we actually implicitly box the primitive type on behalf of the user. This means an unsigned long field can return either a BigInteger or a long and this method can be called on either one with the same result.

Now a script looks like ```double x = doc['my_ul_field'].value.doubleValue();```

2. We can add bigIntegerValue and bigDecimalValue as augmentations of each of the boxed numeric types so if a user wants a BigInteger out of the unsigned long field, it's returned in a consistent way.

Now a script looks like ```BigInteger x = doc['my_ul_field'].value.bigIntegerValue();```

3. We remove the implicit/explicit casting for BigInteger from defTodoubleExplicit and defTodoubleImplicit since this is inconsistent with casting for all other types.

These changes allow for strong consistency in how unsigned long fields are accessed.

**Comment by rjernst** [comment]
I have a different proposal, not better or worse, just another alternative. Unsigned longs fit into a normal `long` in Java, it is just how one interprets the bytes. Thanks to two's complement, basic operations like addition, subtraction and multiplication work. And for other operations, Java has intrinsic methods like [`Long.compareUnsigned`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Long.html#compareUnsigned(long,long)). So instead of creating an object (BigInteger) or having complexity with sometimes returning an object or a primitive, we could return a `long` and tell the user to use the special intrinsics for certain operations.

**Comment by mayya-sharipova** [comment]
Current problems with unsigned_long in scripts:

- incorrect implicit casting to `Long` when running some math operations. 
For example, a script `doc['my_ul_field'].value+1` for a value `18446744073709551614` incorrectly returns `0` instead of the correct answer: BigInteger `18446744073709551615`.

- for proper math operations a need to use `instanceof` in script

- poor performance when running script on all documents as a lot of BigInteger objects need to be created:
   -  sort on _script (they are used only to be converted to double)
   - script_score query (they are used only to be converted to double)
   - scripted aggs 

**Solution options**:
1. Do nothing. Only update documentation with a warning about the implicit cast and examples of proper usage with `instanceOf`

2.  ScriptDocValues always return `double` 
    - doc['my_ul_field'].value is double
    - what if a user needs a precise BigInteger?  

3.  Disable implicit and explicit casts. 
    -  As it is currently, `ScriptDocValues` returns `Long` or `BigInteger`
    -  A user needs to explicitly specify in script what type they need: `doc['my_ul_field'].value.doubleValue()`, `doc['my_ul_field'].value.longValue()`, `doc['my_ul_field'].value.bigIntegerValue()`
    -  no need for `instaceOf` method, as these methods work both `Long` and `BigInteger` types.

4. Return `long` in the unsigned_long format, where the first bit represents not a sign, but the most important digit. 
     - It is user's job to interpret bytes properly
    -  Different from how sort values are returned
    -  What about internal handling of this format?  How we can get  implicit `doubleValue()` from this format necessary for script_score and scripted sort?

**Comment by mayya-sharipova** [comment]
We had a team discussion and decided we would like to return ScriptDocValues for unsigned_long always return the same type. This type could be:

- BigInteger
   - pluses: no loss of precision
   - minuses: potentially creating a lot of BigInteger objects that could discarded immediately (for example for double conversation)
- `long` in `unsigned_long` format with introduction of some helper functions (doubleValue(), bigIntegerValue())
   - pluses: performance
   - minuses: 
        - inconsistency  with other search requests (e.g. sort fields, docvalue fields) 
        - potential difficulties  handling this type for a user. A user would need to explicitly convert to doubleValue(), otherwise most scripts (sort, score, aggs) are not usable.

**Comment by mayya-sharipova** [comment]
I had an idea of a different proposal:

1) make `value` (getValue, get(index)) unsupported operation. 
2) introduce two operations: `getDoubleValue() and getBigIntegerValue()`.  We can also support corresponding functions for multiple values : `double[]: getDoubleValues()` and `BigInteger[]: getBigIntegerValues()`

I can see several pluses for this proposal:
- As `value` function is not supported, we don't expose our internal format by presenting `long` unsigned values to a user.
- We don't create unnecessary BigInteger objects if a user needs double values
- All documents will return consistent types (either BigInteger or Double)

@jimczi @rjernst @jdconrad @stu-elastic What do you think of this proposal?

**Comment by bpintea** [comment]
I wanted to briefly ask if we possibly see this added in 7.12, for scheduling the SQL support for it. Cheers!

**Comment by stu-elastic** [comment]
Leaking the internal representation will be a really sharp edge for users.  We'll block this work pending the universal api work's `as{T}Field()` type coercion. https://github.com/elastic/elasticsearch/issues/61388

**Comment by mayya-sharipova** [comment]
Just to add besides type coercions, we've made a decision that: 
- `getValue` itself will return a `long` that is representing unsigned long where all 64 bits are used for a value.

**Comment by jonathanl-telenav** [comment]
I don't know if this would help to address this problem, but I might be tempted to add a new class UnsignedLong and hide all the representation details of two's complement etc... that would be fast and it wouldn't violate encapsulation. Btw, java.lang.Long does provide divideUnsigned(long, long).
