### ISSUE TITLE
SunJSSE in FIPS mode TLS1.3 issues

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#64379]
TLS1.3 is backported to 8 in the latest release ( openjdk8u-272 ) and adoptopenjdk picked it up too https://blog.adoptopenjdk.net/2020/10/adoptopenjdk-8u272-1109-and-1501-available/

This means that we are now hitting the issue [we hit with zulu8](https://github.com/elastic/elasticsearch/issues/61316#issuecomment-685482708) a few weeks back, for the same reasons. 

[adoptopenjdk-8 jobs in our periodic fips matrix](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.9+matrix-java-periodic-fips/ES_RUNTIME_JAVA=adoptopenjdk8,nodes=general-purpose/213/) started failing already since we upgraded to u272 and our java8 jobs will start failing soon too. 

We should

- Raise an issue upstream with the Bouncy Castle folks
- (Potentially) raise an issue upstream with JDK
- Temporarily change our CI setup to use BCJSSE even in Java 8 in FIPS mode, in order not to lose too much test coverage until we
- Set up one (or two, one for oracle java and one for adoptopenjdk) job in the fips matrix that uses a jdk 8 version that is pinned to the last one before u272

**Comment by tvernum** [comment]
> For the time being, change our CI setup to use BCJSSE even in Java 8 in FIPS mode ( i.e. sunset SunJSSE entirely for our FIPS CI testing )

Doesn't the effectively mean that we'd drop any real support for SunJSSE-FIPS, without warning, in a minor release, just because it doesn't work on the most recent JDKs, even though it does work on older JDKs and we technically still support them.

An alternative would be to decide to maintain a CI job that uses the last non-TLS1.3 JDK8 release in the same way that we maintain testing on old Operating Systems. Our assumption in CI had been that new JDK builds (within the same version) have relatively minor changes and we get the best testing outcome by being on the latest build. I think in this case that assumption is no longer true. The latest JDK8 builds have a big difference (as far as we're concerned) and we should at least consider what that means for CI.

**Comment by jkakavas** [comment]
Good points Tim. "For the time being" meant to denote a temporary solution for our CI until we can get a fix merged upstream. But that "temporary" might take a long time and your suggestion makes total sense. I updated the issue description to reflect that

**Comment by hendrikmuhs** [comment]
Probable Failure: https://gradle-enterprise.elastic.co/s/kwpmchxcrn6ri

T13 == TLS1.3??

```
08:36:41   1> javax.net.ssl.SSLHandshakeException: No available authentication scheme
08:36:41   1> 	at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
08:36:41   1> 	at sun.security.ssl.Alert.createSSLException(Alert.java:117) ~[?:?]
08:36:41   1> 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:311) ~[?:?]
08:36:41   1> 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:267) ~[?:?]
08:36:41   1> 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:258) ~[?:?]
08:36:41   1> 	at sun.security.ssl.CertificateMessage$T13CertificateProducer.onProduceCertificate(CertificateMessage.java:972) ~[?:?]
08:36:41   1> 	at sun.security.ssl.CertificateMessage$T13CertificateProducer.produce(CertificateMessage.java:961) ~[?:?]
08:36:41   1> 	at sun.security.ssl.SSLHandshake.produce(SSLHandshake.java:421) ~[?:?]
08:36:41   1> 	at sun.security.ssl.ClientHello$T13ClientHelloConsumer.goServerHello(ClientHello.java:1152) ~[?:?]
08:36:41   1> 	at sun.security.ssl.ClientHello$T13ClientHelloConsumer.consume(ClientHello.java:1088) ~[?:?]
08:36:41   1> 	at sun.security.ssl.ClientHello$ClientHelloConsumer.onClientHello(ClientHello.java:725) ~[?:?]
08:36:41   1> 	at sun.security.ssl.ClientHello$ClientHelloConsumer.consume(ClientHello.java:693) ~[?:?]
08:36:41   1> 	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:377) ~[?:?]
08:36:41   1> 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444) ~[?:?]
08:36:41   1> 	at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:968) ~[?:?]
08:36:41   1> 	at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:955) ~[?:?]
08:36:41   1> 	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_272]
```

**Comment by gwbrown** [comment]
Per @tvernum's comment [here](https://github.com/elastic/elasticsearch/pull/77671#issuecomment-919162399):
> We intentionally only support Java 11 for FIPS.
> If the PR CI checks still run on Java8, then they're wrong.

It seems like this issue is exclusively related to FIPS on Java 8, which is not supported. I'm going to close this, please feel free to reopen it if I'm wrong and clarify what needs to be done.
