### ISSUE TITLE
SQL: wrong result on literal selection with condition

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#64567]
While 
`SELECT * FROM test_emp WHERE languages = 0` correctly returns nothing (there's no match for the filter), 
`SELECT true FROM test_emp WHERE languages = 0` wrongly returns one row/column result: `true`.  Noteworthy, 
`SELECT true FROM test_emp WHERE false` returns nothing, es expected.

**Comment by Luegg** [comment]
I've found a related inconsistency when using literal selection:

`SELECT gender, 1 FROM test_emp WHERE gender = 'F'` retrieves 

```
    gender     |       1       
---------------+---------------
F              |1              
F              |1              
F              |1              
...
```

and `SELECT 1 FROM test_emp` retrieves

```
       1       
---------------
1              
1              
1   
...
```

but `SELECT 1 FROM test_emp WHERE gender = 'F'` only retrieves a single record like `SELECT 1` would:

```
       1       
---------------
1              
```

I think the expected behaviour is to retrieve a `1` for every document matching the condition.

**Comment by matriv** [comment]
Yep, that's correct it should return as many rows as if a field from a table was selected, so the last one with the filter `WHERE gender = 'F'` is incorrect behaviour.
