### ISSUE TITLE
[DOCS] Document all possible logging options

### ISSUE THREAD

**Issue by Gunnerva** [elastic/elasticsearch#64669]
We should document the available loggers and their uses.  

Examples:
logger.org.elasticsearch.common.NodeConnectionsService -- Supports: Info, Debug, Trace -- Purpose:  Useful for debugging if a node is having issues connecting to other nodes.

logger.org.elasticsearch.xpack.security.authc -- Supports: Info, Debug, Trace -- Purpose: Useful for troubleshooting authentication issues especially with LDAP auth. 

logger.org.elasticsearch.transport 

We have a ton of logger.org.* options, and it would help to have the various supported options and an explanation available.

**Comment by jrodewig** [comment]
This topic is already covered at a high level here: https://www.elastic.co/guide/en/elasticsearch/reference/current/logging.html#configuring-logging-levels

However, those docs don't make it clear that each logger corresponds to an individual ES module: https://github.com/elastic/elasticsearch/tree/master/server/src/main/java/org/elasticsearch

Rather than documenting each module, we may want to make that relationship a bit more clear to users. We could also do a better job explaining the built-in log levels.
