### ISSUE TITLE
Silently hangs when not able to connect to node

### ISSUE THREAD

**Issue by benmccann** [elastic/elasticsearch#6468]
If you create a client which connects to one good node and a few bad nodes it will take a very long time to connect. Our production application server was taking several minutes to come up every time it was restarted and we couldn't figure out why for quite some time. It would be extremely helpful to log that one of the nodes is unreachable so that the issue can be addressed.

One thing that's odd is that is seems to take exponentially longer the more nodes you add.

Example for reproducing the issue:

```
TransportClient transportClient = new TransportClient(settings.build());
transportClient.addTransportAddress(new InetSocketTransportAddress("127.0.0.1", 9300));
transportClient.addTransportAddress(new InetSocketTransportAddress("11.22.33.44", 9300));
transportClient.addTransportAddress(new InetSocketTransportAddress("22.33.44.55", 9300));
transportClient.addTransportAddress(new InetSocketTransportAddress("33.44.55.66", 9300));
```

I'm using the following client:

```
"org.elasticsearch"             % "elasticsearch"             % "1.0.1"
```

**Comment by clintongormley** [comment]
@bleskes do you have any thoughts about this?

**Comment by bleskes** [comment]
we people add nodes to the list of a client we try to connect to them and validate that they are there. The connection timeout is 45s by default. Maybe the connection hangs?

At the moment we log this under debug, because we use the standard sniffing mechanism to validate the new nodes and that one runs frequently so you don't want to spam the logs:

```
                        logger.debug("failed to connect to node [{}], removed from nodes list", e, listedNode);
```

However, if we do succeed to connect/are already connected but fail to get a response from our (recently added) liveness ping, we log it in info:

```
                    logger.info("failed to get node info for {}, disconnecting...", e, listedNode);
```

Looks to me like we should report on a connection failure in info as well.
