### ISSUE TITLE
Disable searching across all indices

### ISSUE THREAD

**Issue by avleen** [elastic/elasticsearch#6470]
Hitting `/_search` causes elasticsearch to search all types, all indices.
With very large indices this is a problem.
We currently have ~30Tb of data across multiple logstash indices.

If someone talks to ES (eg, using sense or a other method) and doesn't specify the index name, the cluster effectively grinds to a half until we restart it.

Can we have an option to require specifying at least one index name to the search endpoint?

Thanks!

**Comment by tomryanx** [comment]
I'm also looking to enforce well formed queries by disabling _all and wildcard expansion on the index name.  I've disabled creation of _all on the index level, but over-eager queries are still able to search every index (when they should be restricted by date range and specify all relevant indices).  Any update on this one?

**Comment by clintongormley** [comment]
I'm on the fence about this one. It seems simple to add, but then everybody has a different policy that they want to enforce, so a tiny feature becomes complex.  This is already easily solved by putting a proxy like nginx in front of ES and specifying the exact rules that you want to implement.  I'm not sure that we should go down this road...

**Comment by nik9000** [comment]
> It seems simple to add, but then everybody has a different policy that they want to enforce, so a tiny feature becomes complex.

I'm not sure the slippery slope argument applies here - its probably a bad idea to query *all* indexes in a decently large cluster and if that is simple to make an option then its probably worth it. Anyone with any more complex set of requirements can break out nginx.

OTOH if it isn't a simple option to implement just telling people to break out nginx if they want any filtering isn't that bad. Its not like Elasticsearch _needs_ to be the one to enforce this. It'd just be convenient if it did.

**Comment by avleen** [comment]
I would agree with Nik.
This is a pain point currently, and even with nginx in place, it is *easy*
to directly access elasticsearch (eg on localhost) and accidentally query
all indices.

Note that I'm not talking about malicious actors, but actual accidents and
those are otherwise hard to protect. It would be most appropriate I think
for this single toggle to be in elasticsearch.

**Comment by tomryanx** [comment]
I find it sickening that it's not possible to limit ES to *only* being reachable through nginx (or something else which can control access in complex ways), even on localhost, but that being the case I have to say I find the answer "use nginx for that", even for something as simple as preventing _all indices being queried, to be consistent and therefore satisfactory.

**Comment by jpountz** [comment]
Could it be considered superseded by the soft limit on the number of queried shards at once? #17396

**Comment by clintongormley** [comment]
@jpountz i think the soft limit does the job better than disabling querying on all indices - it get to the root of the problem

**Comment by aides** [comment]
Hello, 

I have the following case for disabling querying on all indices. I have a multi-tenant ElasticSearch cluster, where tenant1 data is in "index1" and tenant2 data is in "index2". There are two instances of client applications for tenant1 and tenant2 respectively. 

It is strictly forbidden to mix search results for these tenants, i.e. if people of tenant1 see some data that doesn't belong them and find out it is some other tenant data they will go crazy about that.

So right now all search queries are written so they specify the exact index the need to search against. But it happened a couple of times that someone forgot to specify index and some queries would return mixed data. Luckily this was caught early enough. 

So i thinking having some switch that just prevents searching against all indices makes a lot of sense due to the above scenario. 

P.S. If there is another way of tenant bulletproof isolation within a cluster I would really like to know it. Thanks!

**Comment by takwas** [comment]
I currently have the same case as @aides, and would love to know how to go about this in Y2020.

**Comment by tvernum** [comment]
Hi @takwas, thanks very much for your interest in Elasticsearch.

You appear to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch).  
It is not feasible for us to manage these sorts of questions on GitHub - particular when they are posted on long-closed issues.
