### ISSUE TITLE
Rename QueryShardContext

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#64740]
As QueryShardContext is used more often instead of SearchContext, and is used beyond query phase, we think we should come up with a more appropriate name for this class: 

Some suggestions: 

1. `ShardContext` as opposed to SearchContext

2. ` ShardRequestContext` to emphasize that this shard context for or within a particular search request

any other suggestions?

**Comment by jtibshirani** [comment]
Some other ideas:
* Rename QueryShardContext -> SearchExecutionContext. This clarifies its purpose is to help with executing all parts of the search request.
* Rename SearchContext something like SearchState (or ShardSearchState). This is inspired by the javadoc "This class encapsulates the state needed to execute a search..."
* Or we could rename SearchContext -> ShardSearchContext, to keep the 'search context' concept but clarify it applies to a particular shard.

**Comment by kaliljoao** [comment]
Hello guys, can I get this issue to resolve?

**Comment by jtibshirani** [comment]
We discussed as a team and decided to rename `QueryShardContext` to `SearchExecutionContext` (or something similar). We wanted to hold off on naming `SearchContext`, since it will probably undergo a refactor that clarifies/ reduces its scope. It's also tied to other concepts like `ReaderContext` and `ShardSearchContextId`, so we'll want to think through those names at the same time.

@kaliljoao we're not quite ready to make the change, we're waiting for some large features to be merged to avoid conflicts. To find issues to contribute to, you could look for ones with the label 'help wanted' or 'good first issue'.
