### ISSUE TITLE
Running Runtime.exec() in Elasticsearch Plugin error

### ISSUE THREAD

**Issue by communityexplorer** [elastic/elasticsearch#64755]
elasticsearch version:  7.3.1

I am writing a plugin for Elasticsearch which process a cmd like this:
Process p = Runtime.getRuntime().exec("id -u gssuser");
but I got this error:
[2020-11-09T09:12:21,369][ERROR][c.h.i.e.e.h.SslNettyHttpTransport] [node_10.243.226.117] error:
java.lang.IllegalArgumentException: get process user uid failed: execute id -u failed : id -u gssuser, Cannot run program "id": error=13, Permission denied
java.io.IOException: error=13, Permission denied
java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
java.lang.Runtime.exec(Runtime.java:621)
java.lang.Runtime.exec(Runtime.java:451)
java.lang.Runtime.exec(Runtime.java:348)

can you help?

**Comment by martijnvg** [comment]
[Elasticsearch is sandboxed ](https://www.elastic.co/guide/en/elasticsearch/reference/7.9/modules-scripting-security.html#modules-scripting-other-layers) (this is about scripts, but applies to custom plugins too) in Java itself and in the OS level. These security/sandbox measurements by default disallow spawning other processes, this to ensure the safety and stability of an Elasticsearch cluster. Please ask questions like this in the [forums](https://discuss.elastic.co/), so that we can use Github for verified bug reports, feature requests and pull requests.

**Comment by communityexplorer** [comment]
@martijnvg can you tell me how to config?
