### ISSUE TITLE
Search API: Allow callers to determine both 'aggregated total' and 'post-filter total' hit counts

### ISSUE THREAD

**Issue by jayaddison** [elastic/elasticsearch#64836]
NB: I've searched through existing GitHub issues and couldn't find this as an existing feature request, though #16021 touches on some similar ground.

**Context**
A search application which uses aggregations to provide 'faceted search' over a set of documents - in particular aggregations are used to bucket the website domains (terms) that each document was retrieved from.

Users are able to select/deselect individual domains to be displayed, and each time they do, the application invokes a new search.  In order to keep the aggregations 'stable' (meaning: the list of domains still includes entries the user has chosen to exclude), domain filtering is applied by [`using a post_filter`](https://github.com/openculinary/api/blob/95b3745d8b623d65d1a5df21cb53e345117ad693/reciperadar/search/recipes.py#L96-L108).

This works great, and in isolation meets the search requirements for the use case.

However the application has one conflicting behaviour - it performs ['query rewriting'](https://hughewilliams.com/2012/03/19/query-rewriting-in-search-engines/) when a search returns an low number of hits.

This is implemented by inspecting the `hits.total.value` in the [Search API](https://www.elastic.co/guide/en/elasticsearch/reference/7.9/search-search.html) response - a total value that reflects the document count post-filtering.

**Feature Request**
The feature request here is for an additional `hits.prefilter.count` (or better-named) field in the search response that would represent the *pre-filter* hit count -- or, to put it another way: the count of documents involved in the aggregation phase.

NB: One alternative approach could be to add a raw `count` metric aggregation.  Callers could add that to the `aggs` in their search request, and it would include the aggregation-time document count.  I did look for a way to achieve this using existing metric aggregations, but I don't _think_ it's currently possible in an efficient manner.

**Comment by nik9000** [comment]
You might find it better to issue two search requests - one for the top hits and one for the aggs with size=0. The "with aggs" request can take better advantage of request caching. That'll get you both counts. OTOH you might end up with a super long tail and the caching isn't all that useful. Then you'd need something like what you are asking for. I just think it is worth double checking if splitting the request on your side is a good idea.

For what it is worth we never added a raw counting aggregation because all of our bucketing aggregations count on their own. 

I'll set a label on this so a few of us can talk about it more.

**Comment by jayaddison** [comment]
Thanks @nik9000.  In the hope that it might save you and the team a bit of discussion time, I can add that there's a workaround for this use case that also neatly avoids the need for a two-query round-trip.

The application is using a [`terms` aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/search-aggregations-bucket-terms-aggregation.html) that produces a `doc_count` for each corresponding response [bucket](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/search-aggregations-bucket.html#search-aggregations-bucket) in the aggregation results.

The application can sum these `doc_count` values -- being careful only to sum across one aggregate dimension, so as not to double-count -- and use the resulting total as a 'pre-filtered' document count.  It's early days, but that approach is looking good so far.

NB: I'm aware that bucket counts may be approximate; in this case, I think that's fine - it seems unlikely to be incorrect for small document counts, and even if it is, as long as it is *consistently* incorrect then the application behaviour (and user experience) will be consistent, too.

**Comment by jayaddison** [comment]
Closing this issue since it's resolved and workaround-able in a fairly reasonable manner.

**Comment by polyfractal** [comment]
Another sorta-hacky workaround is to wrap your agg tree with a match-all `filter` agg.  The filter agg will tell you the number of docs that flowed through the agg tree, and the interior aggs will partition the docs into their various buckets for normal analysis.

The filter agg will add a bit of a performance penalty since it's doing unnecessary work, but it should be pretty lightweight in the scheme of things since the match-all is essentially a noop here.

E.g.

```js
GET test/_search
{
  "aggs": {
    "doc_count": {
      "filter": {
        "match_all": {}
      },
      "aggs": {
        "colors": {
          "terms": {
            "field": "color"
          }
        }
      }
    }
  }
}
```

Returns a result like:

```js
{
  "aggregations" : {
    "doc_count" : {
      "doc_count" : 6,  <-- all docs seen by the agg tree
      "colors" : {
        "doc_count_error_upper_bound" : 0,
        "sum_other_doc_count" : 0,
        "buckets" : [
          {
            "key" : "blue",
            "doc_count" : 3
          },
          {
            "key" : "red",
            "doc_count" : 3
          }
        ]
      }
    }
  }
}
```

**Comment by jayaddison** [comment]
Thanks @polyfractal - making the pre-filtered doc count accessible at a single, fixed key path in the response is a nice property of that approach.

Do you know if the performance impact is a constant / scales with doc count / scales with aggregates / other?  When time allows I'll try to test it out.
