### ISSUE TITLE
Enabling Transfer acceleration

### ISSUE THREAD

**Issue by ricardo-chaves-movile** [elastic/elasticsearch#64831]
I'm trying to use the transfer acceleration service by setting the url *bar.s3-accelerate.amazonaws.com* as shown in the json below:

```
curl -XPUT 'http://localhost:9200/_snapshot/foo?pretty' -H 'Content-Type: application/json' -d'
{
  "type": "s3",
  "settings": {                                             
    "bucket": "bar",
    "endpoint": "bar.s3-accelerate.amazonaws.com"
  }
}
'
```

I got the error:
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_state_exception",
        "reason" : "To enable accelerate mode, please use AmazonS3ClientBuilder.withAccelerateModeEnabled(true)"
      }
    ],
    "type" : "illegal_state_exception",
    "reason" : "To enable accelerate mode, please use AmazonS3ClientBuilder.withAccelerateModeEnabled(true)"
  },
  "status" : 500
}
```
I'm following the documentation:
https://www.elastic.co/guide/en/elasticsearch/plugins/current/repository-s3-repository.html

Any suggestion ?

**Elasticsearch version** (`bin/elasticsearch --version`):
6.8.12

**Plugins installed**: []
repository-s3

**JVM version** (`java -version`):
11.0.8+10-LTS

**OS version** (`uname -a` if on a Unix-like system):
CentOS 7.5

**Comment by DaveCTurner** [comment]
This is a bit tricky. The claims that you just set the endpoint and that ["no other configuration changes are necessary"](https://aws.amazon.com/blogs/aws/aws-storage-update-amazon-s3-transfer-acceleration-larger-snowballs-in-more-regions/) are sadly not true when it comes to the official Java SDK. Using transfer acceleration requires us to set the region and then explicitly enable accelerate mode. Today we set the endpoint directly rather than the region, which proscribes the use of transfer acceleration even if we were to expose the `withAccelerateModeEnabled()` setter. Fixing this would be messy and involve some breaking changes.

This is the first time I've seen a request for support for S3 transfer acceleration, so I'm leaving this open to gauge the level of interest in supporting this S3 feature.

**Comment by danielmitterdorfer** [comment]
No further feedback received. @ricardo-chaves-movile if you have the requested information please add it in a comment and we can look at re-opening this issue.

**Comment by DaveCTurner** [comment]
There was no specific information needed from the OP on this issue. Instead, I marked this as `feedback_needed` to indicate that we're looking for community feedback on how important this issue is. Closing it after a month is ok with me, we didn't get any such feedback yet so there's nothing actionable here. I just want to clarify that we're still open to feedback on the importance of this issue to the community and we can re-open this if we decide to pursue it.
