### ISSUE TITLE
Max response size option

### ISSUE THREAD

**Issue by delvedor** [elastic/elasticsearch#64879]
Hello team!

Elasticsearch can be configured to reject HTTP requests that are too big with the [`http.max_content_length`](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html) configuration, which defaults to 100MB.
Some platforms have limits on the biggest string/buffer they can handle. Node.js, for instance, can handle 1GB or 512MB based on the version.
It would be great to have a new configuration option in Elasticsearch to configure the biggest allowed size for a response.
What do you think?

/cc @elastic/es-clients

**Comment by nicopaes** [comment]
Hi @delvedor,

I took a shot at this new setting and submitted a PR.

It's not done yet since I need a better direction on where to reference the maximum value and compare to response being created and block the creation of new response if the size is larger then the current cluster setting set by the user.

I'm new to the project so my guess guess was the DefaultRestChannel class.

```
//Checks if response size is larger then the clusters settings max
if(restResponse.content().length() < settings.getMaxResponseSize())
{
    //
}

contentLength = String.valueOf(restResponse.content().length());
setHeaderField(httpResponse, CONTENT_LENGTH, contentLength, false);

```

So, to summarize:

- Where is the elastic response being created? 
- If the response is currently larger then the max, what is the best procedure (ex. throw an error, cancel the creation, divide it..) ?
   
   
Anyone is welcome to help me and provide feedback!

**Comment by rjernst** [comment]
The max content length for requests is handled within the http networking layer (http transport). Given the naming of the existing setting, I wonder if it could be used for both requests and responses, rather than creating a new setting. But I'm going to relabel this for the distributed team to look at given the networking layer is owned by them.

**Comment by rudolf** [comment]
This would be really useful for Kibana. When doing migrations we read batches of documents which are transformed and then indexed again. Since documents can vary in size (from a few kb to > 10mb) it makes it very difficult to choose a good `size` parameter with which to limit search requests.

Receiving an HTTP error code instead of a response which crashes the Node processes would be useful protection. Although client's would still have to guess with how much they need to reduce the `size` to not exceed this limit.

Having an option like `maxSizeInBytes` (or whatever name) which could limit the response body to a certain length but still return the results that fit would significantly simplify writing robust code. If this worked with PIT then a client could easily iterate through results in a memory safe way, without having to choose an overly small `size` parameter.

**Comment by original-brownbear** [comment]
I don't think this is something that necessarily should happen in Elasticsearch. The client should give up if it exceeds its memory resources. Especially in the context of APIs now moving to chunked encoding, this might even become impossible for us to do for some APIs. See #88311 
Putting team-discuss on this to validate with the team

**Comment by DaveCTurner** [comment]
> Putting team-discuss on this to validate with the team

I agree with this thinking. With chunked-encoding we won't know the response will exceed N bytes until we've already sent N-(chunk-size) bytes by which point it doesn't really make much difference whether the abort comes from us or the client, and different clients may have wildly different limits anyway.

Additionally we are working to add pagination to APIs that today might yield unboundedly-large responses. Memory-conscious clients should use those paginated APIs rather than relying on Elasticsearch-side protections.
