### ISSUE TITLE
_sql/translate only includes subset of fields when "SELECT *" is used on alias

### ISSUE THREAD

**Issue by jmwilkinson** [elastic/elasticsearch#65029]
**Elasticsearch version** (`bin/elasticsearch --version`):

7.9.3

**Plugins installed**: []

**JVM version** (`java -version`):

15

**OS version** (`uname -a` if on a Unix-like system):

Docker on Centos 7

**Description of the problem including expected versus actual behavior**:

Expectation: when executing the SQL statement, all fields are properly included in the response.

Reality: when running sql translate on certain aliased indices, only some of the fields are included in the translated query, even when `SELECT *` is used.

**Steps to reproduce**:

*Note: I tried to recreate this with a substantially simpler example, but couldn't replicate it. There is something to do with more complex indices that causes this, I think*

1. Create an index.
```
PUT _index_template/bug-index
{
  "index_patterns": [
    "bug-index-*"
  ],
  "template": {
    "settings": {
      "index": {
        "number_of_shards": "1",
        "number_of_replicas": "2"
      }
    },
    "mappings": {
      "properties": {
        "Condition": {
          "ignore_above": 256,
          "type": "keyword",
          "fields": {
            "text": {
              "type": "text"
            }
          }
        },
        "Category": {
          "ignore_above": 100,
          "type": "keyword"
        },
        "Message": {
          "type": "text",
          "fields": {
            "keyword": {
              "ignore_above": 256,
              "type": "keyword"
            }
          }
        },
        "Stacktrace": {
          "type": "text",
          "fields": {
            "keyword": {
              "ignore_above": 256,
              "type": "keyword"
            }
          }
        },
        "Index": {
          "type": "long"
        },
        "Type": {
          "type": "keyword"
        },
        "Timestamp": {
          "type": "date"
        },
        "ingestId": {
          "type": "keyword"
        },
        "ParentID": {
          "type": "long"
        },
        "ingestedAt": {
          "type": "date"
        },
        "ElementID": {
          "ignore_above": 50,
          "type": "keyword"
        },
        "Run": {
          "properties": {
            "Path": {
              "type": "keyword",
              "fields": {
                "text": {
                  "type": "text"
                }
              }
            },
            "UniqueID": {
              "type": "keyword"
            },
            "StartDateTime": {
              "type": "date"
            },
            "ID": {
              "type": "long"
            },
            "Node": {
              "type": "keyword",
              "fields": {
                "text": {
                  "type": "text"
                }
              }
            },
            "Name": {
              "type": "keyword",
              "fields": {
                "text": {
                  "type": "text"
                }
              }
            }
          }
        },
        "Session": {
          "properties": {
            "ID": {
              "type": "long"
            },
            "UniqueID": {
              "type": "text",
              "fields": {
                "keyword": {
                  "ignore_above": 256,
                  "type": "keyword"
                }
              }
            },
            "User": {
              "ignore_above": 256,
              "type": "keyword"
            },
            "Name": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword"
                }
              }
            }
          }
        },
        "Value": {
          "properties": {
            "Integer": {
              "type": "long"
            },
            "Float": {
              "type": "double"
            },
            "Type": {
              "type": "keyword"
            },
            "String": {
              "ignore_above": 256,
              "type": "keyword",
              "fields": {
                "text": {
                  "type": "text"
                }
              }
            },
            "Boolean": {
              "type": "boolean"
            },
            "Key": {
              "ignore_above": 200,
              "type": "keyword",
              "fields": {
                "text": {
                  "type": "text"
                }
              }
            },
            "DateTime": {
              "type": "date"
            }
          }
        },
        "IssueID": {
          "type": "long"
        },
        "ID": {
          "type": "long"
        }
      }
    },
    "aliases": {
      "bug-index": {}
    }
  }
}
```

2. Create an index that will use the template
```
PUT bug-index-1
```

3. Translate a SQL query, noting the `includes` value that is returned. It is missing a bunch of fields, such as `Value.String`, `Run.Name`, `Run.Path`, etc. This is despite the fact that all fields are present in `docvalue_fields`.
```
POST /_sql/translate
{
  "query": "SELECT * FROM \"bug-index\" WHERE Run.ID = 1212"
}

Response:
{
  "size" : 1000,
  "query" : {
    "term" : {
      "Run.ID" : {
        "value" : 12501,
        "boost" : 1.0
      }
    }
  },
  "_source" : {
    "includes" : [
      "@version",
      "ID",
      "Index",
      "IssueID",
      "Message",
      "ParentID",
      "ResultType",
      "Run.ID",
      "Session.ID",
      "Session.Name",
      "Session.UniqueID",
      "Stacktrace",
      "Value.Boolean",
      "Value.Float",
      "Value.Integer"
    ],
    "excludes" : [ ]
  },
  "docvalue_fields" : [
    {
      "field" : "@timestamp",
      "format" : "epoch_millis"
    },
    {
      "field" : "Category"
    },
    {
      "field" : "Condition"
    },
    {
      "field" : "ElementID"
    },
    {
      "field" : "Run.Name"
    },
    {
      "field" : "Run.Node"
    },
    {
      "field" : "Run.Path"
    },
    {
      "field" : "Run.StartDateTime",
      "format" : "epoch_millis"
    },
    {
      "field" : "Run.UniqueID"
    },
    {
      "field" : "Session.User"
    },
    {
      "field" : "Timestamp",
      "format" : "epoch_millis"
    },
    {
      "field" : "Type"
    },
    {
      "field" : "Value.DateTime",
      "format" : "epoch_millis"
    },
    {
      "field" : "Value.Key"
    },
    {
      "field" : "Value.String"
    },
    {
      "field" : "Value.Type"
    },
    {
      "field" : "ingestId"
    },
    {
      "field" : "ingestedAt",
      "format" : "epoch_millis"
    }
  ],
  "sort" : [
    {
      "_doc" : {
        "order" : "asc"
      }
    }
  ]
}
```

4. Execute the sql statement normally. Note that all fields are included.
```
POST /_sql?format=txt
{
  "query": "SELECT * FROM \"bug-index\" WHERE Run.ID = 1212"
}

Respose:
   Category    |   Condition   |   ElementID   |      ID       |     Index     |    IssueID    |    Message    |   ParentID    |    Run.ID     |   Run.Name    |   Run.Node    |   Run.Path    |Run.StartDateTime| Run.UniqueID  |  Session.ID   | Session.Name  |Session.UniqueID| Session.User  |  Stacktrace   |   Timestamp   |     Type      | Value.Boolean |Value.DateTime |  Value.Float  | Value.Integer |   Value.Key   | Value.String  |  Value.Type   |   ingestId    |  ingestedAt   
---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+-----------------+---------------+---------------+---------------+----------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------
```

**Comment by costin** [comment]
If I understand correctly the ticket, your expectation is to have a result for all fields specified. If that is the case, this is incorrect.

The translate API returns the query DSL to retrieve results back. Which it does.
Since ES is a *document* store, meaning each entry can vary in content - as such it will return only the fields that match and *contain* values, there is no notion of a schema across all entries. That is a document might or not, have the field requested - and that is perfectly fine.
Since in SQL there is a notion of a schema across all results, Elasticsearch SQL handles that by inferring it across the results and maps the returned results into in.

See the documentation chapter on mapping, n particular the sections on missing value and exists query.

**Comment by jmwilkinson** [comment]
@costin I don't think your understanding is correct.

The fields do exist in the underlying documents. Not only that, but when _executing_ the sql query everything is returned as expected. It's only when _translating_ it that fields are missing- though not for all index mappings.

**Comment by tvernum** [comment]
@jmwilkinson 

There seems to be some confusion here about what translate does, and what `_source` and `docvalue_fields` do.

Current versions of Elasticsearch lack a general purpose way of retrieving fields. There a new [`fields` section of the Search API](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-fields.html#search-fields-param) in ES 7.10 but it's still beta.

That means that (for now) in order to get selected fields from a document, the caller needs to decide [how to retrieve the field](https://www.elastic.co/guide/en/elasticsearch/reference/7.9/search-fields.html#search-fields).

That can be from `_source`, `docvalue_fields` or `stored_fields` (or `script_field`, but that's a bit different).

The SQL translate API does that for you.  
Based on a field's mapping type it determines whether the field supports doc_values, and if it does it will list that field name in `docvalue_fields`.
For other fields it will rely on the `_source`.
But each field will be listed in only 1 place. There is no value in returning `Run.Name` from both _source and doc values. It just increases the size of the response and forces the caller to decide which field to use. The SQL engine has decided that the doc values field is the best one to use, so it is returned there.

Your bug report amounts to _I expect SQL translate to build a search query that will return all selected fields as part of the `_source` section of the response_ . That is an incorrect assumption. SQL translate will return each field in the best manner it can, which may be `_source`, but may be `doc_values`.

To take a shorter example using your index:

```
POST /_sql/translate
{
  "query": "SELECT Run.ID, Run.Name FROM \"bug-index\" WHERE Run.ID = 1212"
}

===
{
  "size": 1000,
  "query": {
    "term": {
      "Run.ID": {
        "value": 1212,
        "boost": 1.0
      }
    }
  },
  "_source": {
    "includes": [
      "Run.ID"
    ],
    "excludes": []
  },
  "docvalue_fields": [
    {
      "field": "Run.Name"
    }
  ],
  "sort": [
    {
      "_doc": {
        "order": "asc"
      }
    }
  ]
}
```
 
`Run.ID` is retrieved from _source, but `Run.Name` is retrieved from `doc_values`.

If we ingest a document, and then run that search:

```
PUT bug-index-1/_doc/1
{
     "Run": { "ID": 1212 , "Name": "foo"}
}
```

```
GET /bug-index/_search
{
  "size": 1000,
  "query": {
    "term": {
      "Run.ID": {
        "value": 1212,
        "boost": 1.0
      }
    }
  },
  "_source": {
    "includes": [
      "Run.ID"
    ],
    "excludes": []
  },
  "docvalue_fields": [
    {
      "field": "Run.Name"
    }
  ],
  "sort": [
    {
      "_doc": {
        "order": "asc"
      }
    }
  ]
}

===
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 1,
      "relation": "eq"
    },
    "max_score": null,
    "hits": [
      {
        "_index": "bug-index-1",
        "_type": "_doc",
        "_id": "1",
        "_score": null,
        "_source": {
          "Run": {
            "ID": 1212
          }
        },
        "fields": {
          "Run.Name": [
            "foo"
          ]
        },
        "sort": [
          0
        ]
      }
    ]
  }
}
```

Every field that was selected is included in the response. `Run.ID` is in the `_source`, and `Run.Name` is in the `fields` because the SQL engine has determined the best way to retrieve each field.

I don't see any bug here. Everything is working as designed - though perhaps not what you expect or want.

**Comment by jmwilkinson** [comment]
@tvernum Thank you so much for the detailed explanation! That clarifies things immensely.

A huge missing piece for me was the code I have to experiment with this was printing the `_source` value from the hit expecting it to contain the entire document, and so I wasn't even seeing the rest of it. Also, I should have looked more closely at `docvalue_fields` in the returned query, and read the docs on what that meant. Sorry.

To cement my understanding, when you say

> Every field that was selected is included in the response. Run.ID is in the _source, and Run.Name is in the fields because the SQL engine has determined the best way to retrieve each field.

By "best" you mean most performant? Is that correct?

I'm very glad this wasn't a bug, and hope I haven't wasted too much of your time. I also hope this is useful for anyone else who runs across this while switching from Open Distro to elastic.
