### ISSUE TITLE
Categorise device type (phone/tablet/bots/etc) from User Agent String

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/elasticsearch#65057]
In RUM (within Observability), we already take advantage of the User Agent ingest processing to define the device itself (e.g. iPhone, Samsung etc.), however these can sometimes be too granular, and it is useful to slice the RUM data based on the device type, for example **all phones**, or **all tablets**, or **bots** so that users can focus their analysis on these larger groupings, then further filter the data in other ways.

This feature request is to enhance the user agent parsing, to also add **device type**, extracted from the user agent.

This requirement is needed to be able to implement https://github.com/elastic/apm-server/issues/3912.

**Comment by andrewvc** [comment]
It seems that there's a couple options here:

1. Look into using a new library like Udger
2. Add our own algorithm for device type detection on top in ES directly
3. Do our own device type detection at query type using `filter` queries.
4. Add a special ingest processor that calculates device type at ingest time.

The advantage of switching libraries is that someone else would maintain it, the downside is that the parsed data would change under user's feet, and the transition may be rough. Additionally, a proprietary solution may present licensing issues.

I think we should spend some time to explore options 2, 3 and 4, probably starting with 3 since it's the easiest to experiment with. We might want to reference https://github.com/ua-parser/uap-core/issues/354#issuecomment-713831356 for a starting point in terms of categorizing devices.

Another argument in favor of 3, which is more dynamic, is that it would let us easily change the buckets things go in. The only downside is that it makes dashboarding more difficult since there's no device type field.

**Comment by paulb-elastic** [comment]
Categories we need to be able to capture:
- Phone
- Tablet
- Desktop/Laptop
- Bot
- Elastic (Synthetics)
- Other

**Comment by nemphys** [comment]
Any news on this one? I suppose a lot of use cases would benefit from a more generic "device type" field instead of the "device name", which produces too many buckets when aggregating and does therefore not offer much help in categorising stuff.
It's a shame to have to revert to using an external library just for this, when the user_agent ingest processor does a pretty nice job otherwise.

**Comment by danhermann** [comment]
@nemphys, there are some folks exploring ways we might be able to extract a device type, but it's too early to know when or if they will come up with something that will work.

**Comment by danhermann** [comment]
This feature was completed by https://github.com/elastic/elasticsearch/pull/69322.
