### ISSUE TITLE
[DOCS] make it clearer there is no forward compatibility for remote reindex in all doc versions

### ISSUE THREAD

**Issue by jguay** [elastic/elasticsearch#65192]
2 doc enhancement issues : 
1- https://github.com/elastic/elasticsearch/pull/60425 added useful note but unfortunately this was only added from [7.8](https://www.elastic.co/guide/en/elasticsearch/reference/7.8/reindex-upgrade-remote.html#reindex-upgrade-remote) documentation `Elasticsearch does not support forward compatibility across major versions. For example, you cannot reindex from a 7.x cluster into a 6.x cluster.`, can the note be added for all versions of the doc ?
2- [Reindex from remote](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/docs-reindex.html#reindex-from-remote) documentation currently is lacking the same note for all versions, can it be added at least since 6.8 branch, maybe something like this :
```
NOTE : Elasticsearch does not support forward compatibility across major versions. For example, you cannot reindex from a 7.x cluster into a 6.x cluster.
```

**Comment by jrodewig** [comment]
Thanks for raising this @jguay.

> 1- #60425 added useful note but unfortunately this was only added from 7.8 documentation Elasticsearch does not support forward compatibility across major versions. For example, you cannot reindex from a 7.x cluster into a 6.x cluster., can the note be added for all versions of the doc ?

Per our [backport policy](https://github.com/elastic/elasticsearch/tree/master/docs#backporting-doc-fixes), we typically only backport doc changes to the current ES version branch. That's why #60425 was only added to the 7.8+ docs. However, I made an exception in this case and backported the #60425 changes to all 7.x branches and 6.8.

> 2- Reindex from remote documentation currently is lacking the same note for all versions, can it be added at least since 6.8 branch, maybe something like this :

Good catch! I opened #65207 to add the same note to the remote reindex docs.
