### ISSUE TITLE
Provide unique user identifier in authentication response

### ISSUE THREAD

**Issue by legrego** [elastic/elasticsearch#65277]
When a single authentication realm is configured in Elasticsearch, we can be _reasonably_ certain that the `username` will uniquely identify a specific user.

When multiple realms are configured, it's possible for different users in different realms to have a matching `username`.

While this is likely a bit of an edge case for most deployments, it's something we'd like to solve for. @elastic/kibana-security will be iterating on Object Level Security in the near future (https://github.com/elastic/kibana/issues/82725), and a big part of this involves saved object "ownership", where only the owner will be allowed to access or modify the object.

In order to effectively secure access to these objects, we would like to have a stable, unique identifier for each user that authenticates. In recent discussions, we've thought about taking the combination of realm type + realm name + username to uniquely identify a user, but changing realm names has not historically had many consequences. If an administrator changes the realm name after we've started relying on it, then users will lose access to their "owned" saved objects, since they would be coming from a different realm, and therefore would be treated as a different user altogether.

This is not strictly related to the "user entity" discussions we've been having. We'll need OLS even if we don't leverage it for the "user entity"

**Comment by ywangd** [comment]
Have an unique identifier for each user is tricky and probably not well defined. For `file` and `native` realms, it is more straightforward because there can only be a single one for each of them. So effectively, the combination of username and realm_type can be considered as the unique ID regardless of the realm_name. There are edge cases when an user is deleted from native realm and then added back, or if the file realm is removed and then added back, one could argue whether they are still the same user. But in general, I feel it is probably less controversial to consider them as the same user.

For external realms, e.g. LDAP, things become unclear. Like you said, a realm can be renamed and, IIUC, you seem to suggest that the same username from the two realms (one before the rename and the other after the rename) should be considered as the same user for OLS. But how should we handle the opposite, i.e. the realm name remains the same but the LDAP url is changed. Also what if the LDAP url change is just a proxy change and underlying still points to the same server? What if both LDAP url and realm name change? It feels that we could be trying too hard to cater for these different situations. Therefore, I wonder whether the simpler approach of just using "username + realm_type + realm_name" as the unique identifier is acceptable and we just need to clearly document it (technically realm name is unique in recent versions, so it can possibly be reduced to "username + realm_name"). It has flaws, but a perfect solution seems to be unlikely.

**Comment by tvernum** [comment]
@ywangd - I'm assigning this to you to you because I think it's superseded by profiles. Can you review & close it if appropriate?

**Comment by ywangd** [comment]
I am closing this issue because the main ask is taken care by the User Profile project.

The User Profile project will be providing a stable ID for each individual interactive user and it works across realms (when configured). This should suffice the main ask of this issue. But we don't plan to expose the ID in the authentication response (`GET _security/_authenticate`) because doing it would make the otherwise lightweight authentication API heavier. 

I think the new ActivateProfile API (#82400) will become the endpoint that applications use for getting the unique ID. The workflow that I understand is that Kibana will likely call the new API after each user login and get ahold of the ID afterwards. The new API provides many of the same information as the existing Authenticate API and more. It is likely more appropriate for Kibana's usage.

That said, the ActivateProfile API is a "write" operation. We have [GetProfile API](https://github.com/elastic/elasticsearch/pull/81910) that gets profile by ID. We might also need a way to get profile for currently authenticated user. This can be either a new API or have Authenticate API optionally return the profile ID. But we should have a dedicate issue specfically for it when we need it.
