### ISSUE TITLE
Range Aggregation on float values not giving proper results

### ISSUE THREAD

**Issue by smanjunatha-aie** [elastic/elasticsearch#65283]
**Elasticsearch version** (`bin/elasticsearch --version`):7.6.0

**Plugins installed**: [NA]

**JVM version** (`java -version`): 1.8.0_271

**OS version** (`uname -a` if on a Unix-like system): Windows 10

**Description of the problem including expected versus actual behavior**: 
The Range aggregation is not returning the proper count in the buckets. This is happening only for float values. 
We have values ranging from 0.1 to 5.0 (Ratings). We have to group these values under 5 buckets, starting from 
0.1 to 1.0, 1.1 to 2.0, 2.1 to 3.0, 3.1 to 4.0, 4.1 to 5.0. 
As per the documentation, the range aggregation includes the "from" value and excludes the "to" value.

**Steps to reproduce**:
Schema:
PUT /ratings_test
{
  "mappings": {
    "properties": {
      "productid": {
        "type": "keyword"
      },
      "ratings": {
        "type": "float"
      }
    }
  }
}

Input Data:
POST /ratings_test/_doc/1
{
	"productid":"227126",
	"ratings":0.1
}

POST /ratings_test/_doc/2
{
	"productid":"247105",
	"ratings":0.5
}

POST /ratings_test/_doc/3
{
	"productid":"228880",
	"ratings":1.0
}

POST /ratings_test/_doc/4
{
	"productid":"238143",
	"ratings":1.1
}

POST /ratings_test/_doc/5
{
	"productid":"240631",
	"ratings":1.5
}

POST /ratings_test/_doc/6
{
	"productid":"235747",
	"ratings":2.0
}

POST /ratings_test/_doc/7
{
	"productid":"240553",
	"ratings":2.1
}

POST /ratings_test/_doc/8
{
	"productid":"227124",
	"ratings":2.5
}

POST /ratings_test/_doc/9
{
	"productid":"237758",
	"ratings":3.0
}

POST /ratings_test/_doc/10
{
	"productid":"227166",
	"ratings":3.1
}

POST /ratings_test/_doc/11
{
	"productid":"240555",
	"ratings":3.5
}

POST /ratings_test/_doc/12
{
	"productid":"235770",
	"ratings":4.0
}

POST /ratings_test/_doc/13
{
	"productid":"235748",
	"ratings":4.1
}

POST /ratings_test/_doc/14
{
	"productid":"216961",
	"ratings":4.5
}

POST /ratings_test/_doc/15
{
	"productid":"221483",
	"ratings":5.0
}

Query :
GET /ratings_test/_search
{
  "size": 0, 
  "aggregations": {
    "ratings": {
      "range": {
        "field": "ratings",
        "ranges": [
          {
            "key": "5",
            "from": 4.1,
            "to": 5.1
          },
          {
            "key": "4",
            "from": 3.1,
            "to": 4.1
          },
          {
            "key": "3",
            "from": 2.1,
            "to": 3.1
          },
          {
            "key": "2",
            "from": 1.1,
            "to": 2.1
          },
          {
            "key": "1",
            "from": 0.1,
            "to": 1.1
          }
        ],
        "keyed": true
      }
    }
  }
}

Out put: Please check the ranges 2 and 5
"aggregations" : {
    "ratings" : {
      "buckets" : {
        "1" : {
          "from" : 0.1,
          "to" : 1.1,
          "doc_count" : 3
        },
        "2" : {
          "from" : 1.1,
          "to" : 2.1,
          **"doc_count" : 4**
        },
        "3" : {
          "from" : 2.1,
          "to" : 3.1,
          "doc_count" : 3
        },
        "4" : {
          "from" : 3.1,
          "to" : 4.1,
          "doc_count" : 3
        },
        "5" : {
          "from" : 4.1,
          "to" : 5.1,
          **"doc_count" : 2**
        }
      }
    }
  }

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by polyfractal** [comment]
This is unfortunately an issue with floating point rounding error inherent to IEEE-754 floats :(

For example, the value `2.1` is actually stored as `2.099999904632568359375` in an IEEE-754 float, because it can't represent `2.1` exactly.  And that means it matches the range because 2.09999.... is less than 2.1.

There's an interactive calculator for floats which you can play with here: https://www.h-schmidt.net/FloatConverter/IEEE754.html

It's definitely confusing to the user, but it's just the nature of limited precision data-types like floats.  You could switch over to doubles to get a greater dynamic range and less conversion errors (although it'll still be present).  Or you could switch to `scaled_float` if you have a known dynamic range and have a desired number of decimal places of accuracy (https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html#scaled-float-params).  That stores the decimal as a long internally so you won't get these kinds of conversion errors... but they have limited significant figure precision, so conversion errors are just different.  Namely rounding up/down to nearest number of sig-figs, rather than rounding to nearest encodable value.

I'm going to close this because, while it's a deeply unsatisfying answer, it's also not something we can fix.  Just the practicalities of dealing with floating points in computers unfortunately :(
