### ISSUE TITLE
int based count for histogram type is too limiting. should support long

### ISSUE THREAD

**Issue by drunkirishcoder** [elastic/elasticsearch#65330]
**Elasticsearch version** (`bin/elasticsearch --version`):

7.9.2

**Description of the problem including expected versus actual behavior**:

When using the `histogram` type, the counts array is defined as `int`. If you have counts exceed the size of a signed int, you will not be able to use the type.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

```
POST /metricz-test/_doc
{
  "@timestamp": "2020-11-20T18:55:52.492385636Z",
  "metric": {
    "histogram": {
      "count": 2843983851,
      "sum": 427410.616277754,
      "value": {
        "counts": [
          2836151156,
          5617135,
          2097410,
          115357,
          2403,
          250,
          140,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "values": [
          0.005,
          0.01,
          0.05,
          0.1,
          0.25,
          0.5,
          0.75,
          1,
          2,
          3,
          4,
          5,
          10,
          20
        ]
      }
    },
    "kind": "absolute",
    "labels": {
      "application_name": "publish",
      "component": "process",
      "env": "production"
    },
    "name": "process_hiccups_seconds"
  }
}
```

you get this error

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "mapper_parsing_exception",
        "reason" : "failed to parse field [metric.histogram.value] of type [histogram]"
      }
    ],
    "type" : "mapper_parsing_exception",
    "reason" : "failed to parse field [metric.histogram.value] of type [histogram]",
    "caused_by" : {
      "type" : "i_o_exception",
      "reason" : "Numeric value (2836151156) out of range of int (-2147483648 - 2147483647)\n at [Source: (org.elasticsearch.common.bytes.AbstractBytesReference$MarkSupportingStreamInputWrapper); line: 1, column: 142]"
    }
  },
  "status" : 400
}
```

**Comment by polyfractal** [comment]
Hiya @drunkirishcoder!  We chatted about this recently, and wanted to get some more info about your usecase.  Would it be possible to explain what you're using the histo field for, and what the values represent that you're "overflowing" past the limits of an int?

Does your use-case have a known min/max range, or is it unknown/unbounded?

From our side, we agreed that this limit is unfortunate from a user's perspective.  Today the workaround would be indexing multiple documents (each with a histogram) for the same time point.  But this has some difficulties, logistically and when trying to query/aggregate (doc counts will be off, value counts for keyword/tags will be off, etc)

There are some technical aspects that make it tricky though.  From a compression point of view, expanding to a `long` would increase the field's size considerably.  And internally, it's nice to know these are integers since it means we can sum them into longs and (mostly) ignore overflow issues, without having to resort to doubles and start losing precision.

There might be an opportunity to introduce a "double histogram" which allows very large dynamic range at the expense of some precision, but we're not sold on that idea yet.  Alternatively, we might be able to internally index a "multi-valued" histogram, e.g. generate multiple internal histograms on the document whenever the counts overflow. 

In any case, wanted to get some feedback from your use-case before we dived in too deep :)

**Comment by drunkirishcoder** [comment]
@polyfractal what I'm testing is archiving some histogram data from prometheus into elasticsearch. And the problem here is exactly what you outlined, on the prometheus side, the cumulative histogram count of each bucket is tracked as an u64 I believe so it can get quite large. I can see the problem you are pointing out that it's not just the storage but also the overflow when dealing with aggregation on this field.

**Comment by polyfractal** [comment]
@drunkirishcoder  Cheers, I'll take this back to the team after the holidays and we'll discuss it again :)

**Comment by not-napoleon** [comment]
@imotov - Is this something we're still interested in picking up?

**Comment by imotov** [comment]
@not-napoleon I would keep it open for now. I don't think we will address it now, but we might be able to get there as part of another effort. It would work as a good reminder about this use case.

**Comment by wchaparro** [comment]
We're going to need to address this as part of the TSDB project, because this is a use case we need to support. We'll close this issue and create a new task it to the [TSDB meta project](https://github.com/elastic/elasticsearch/issues/74660).
