### ISSUE TITLE
output part-of-speech value

### ISSUE THREAD

**Issue by freebiesoft** [elastic/elasticsearch#65480]
when you input kanji to the kuromoji analyzer as in the example here https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-kuromoji-baseform.html , it would be nice to output the part-of-speech value as well.

**Comment by cbuescher** [comment]
Hi @freebiesoft, the [`explain` setting](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-analyze.html#explain-analyze-api) on the probably already has what you are after. When I tried it with the example you linked it gave me:
```
"tokens" : [
        {
          "token" : "飲み",
          "start_offset" : 0,
          "end_offset" : 2,
          "type" : "word",
          "position" : 0,
          "baseForm" : "飲む",
          "bytes" : "[e9 a3 b2 e3 81 bf]",
          "inflectionForm" : "連用形",
          "inflectionForm (en)" : "conjunctive",
          "inflectionType" : "五段・マ行",
          "inflectionType (en)" : "5-row-cons-m",
          "partOfSpeech" : "動詞-自立",
          "partOfSpeech (en)" : "verb-main",
          "positionLength" : 1,
          "pronunciation" : "ノミ",
          "pronunciation (en)" : "nomi",
          "reading" : "ノミ",
          "reading (en)" : "nomi",
          "termFrequency" : 1
        }
      ]
```
I don't know Japanese so I cannot judge the quality but maybe this is what you are looking for, so I'll close this issue. In general I don't think we want to add linguistic details like POS to the `_analyze` default output since I believe there are better ways of doing deeper linguistical analysis outside the ES analysis chain if needed. I suggest discussion options and best practices around that in the support forums over at https://discuss.elastic.co.
