### ISSUE TITLE
EQL: documentation ease of use

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#65487]
Currently, our great EQL documentation is using a style that promotes sharing a big subject (for example, [EQL syntax reference](https://www.elastic.co/guide/en/elasticsearch/reference/master/eql-syntax.html#eql-syntax)) in a single, large page where all the sub-aspects (sub-chapters) are highlighted with bold characters ([Sequences](https://www.elastic.co/guide/en/elasticsearch/reference/master/eql-syntax.html#eql-sequences) is an example). But there are also sub sub-chapters (like the [until keyword](https://www.elastic.co/guide/en/elasticsearch/reference/master/eql-syntax.html#eql-until-keyword) from Sequences) which is also highlighted in the documentation page and has an anchor to it that can be shared and made easily accessible.

What I feel it's missing, from my point-of-view and looking at the documentation as a regular user, is an easier way of reaching certain sub sub-chapters. As an user looking for how to use `until` and what I can specify as values to `until` I'd have to go to EQL page by clicking on the right-hand side column that allows the docs reference browsing:

![image](https://user-images.githubusercontent.com/893749/100209045-11d4af00-2f12-11eb-98b7-25dfe7e0c5ba.png)

then assuming `until` is somewhere in `Syntax reference`:

![image](https://user-images.githubusercontent.com/893749/100209891-0f268980-2f13-11eb-88b7-44d0f2a37b91.png)

then going to `Sequences` (since I already know `until` is about sequences):

![image](https://user-images.githubusercontent.com/893749/100210030-2ebdb200-2f13-11eb-8a9c-f5ab0b5d9649.png)

But in the Sequences section (which is somewhere in the middle of a very large page about syntax) I'd have to scroll and try to pinpoint with my eyes something about `until`. When I found it, is somewhat easily visible, but not that much.

Having worked on the SQL documentation and, inevitably, comparing the two, I find the right-hand side of the reference documentation of great help in more easily browsing through sub-chapters and sub sub-chapters. For example (from SQL docs) - the right hand side has a tree like structure:

![image](https://user-images.githubusercontent.com/893749/100210629-dfc44c80-2f13-11eb-9dce-a0438dfa1d4d.png)

If I go to [Lexical Structure](https://www.elastic.co/guide/en/elasticsearch/reference/master/sql-lexical-structure.html), the page that opens has on the top right hand side "On this page" (just like EQL), but what's different in SQL page's case is what I believe is a sub sub-chapter from EQL docs (for example the [Special characters](https://www.elastic.co/guide/en/elasticsearch/reference/master/sql-lexical-structure.html#sql-syntax-special-chars) sub sub-chapter).

![image](https://user-images.githubusercontent.com/893749/100211029-4ea1a580-2f14-11eb-867d-745d11d07327.png)

What I would have loved to see in EQL's case is something similar to SQL's documentation:
- a more detailed tree structure on the right-hand side of the page where the Reference documentation shows all the major sections/projects. For example, we could expand "Syntax reference" and have there the "Sequences" section.
- when clicking on Sequences from the right-hand side tree, the page that opens has only Sequences section in it
- the Sequences page has at the top right-hand side of the page the "On this page" summary where I can find, among others, the `until` sub sub-chapter. I can click on it and it takes me right to the `until` sub-section.

**Comment by jrodewig** [comment]
Thanks for the feedback @astefan!

I chose the current "one page" approach/layout for a few reasons:

- Based on user surveys, most of our users prefer longer pages that they can use `cmd-f/ctrl-f` to search locally.
- Most users get to a docs page from an external search (e.g., Google) rather than the TOC nav. A single page provides those search users with more context.
- Our new docs redesign will focus on longer pages that cover a single topic. This layout will be easier to migrate into the new system.

While I'd prefer not to break this page up, I think I can improve the UX by better populating the "On this page" nav:

<img width="214" alt="Screen Shot 2020-11-25 at 8 37 50 AM" src="https://user-images.githubusercontent.com/40268737/100234744-87805100-2ef9-11eb-9d46-4decc780efb0.PNG">

Unfortunately, this makes the page's heading hierarchy a bit less clear. Several child H4s must become sibling H3s to populate the nav. But I think that's a sacrifice we can make.
