### ISSUE TITLE
Allow highlighting of runtime fields

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#65556]
Runtime fields currently don't work with highlighting, for two reasons:

1) The Unified and Plain highlighters re-analyze their source data using the Analyzer configured on the index's IndexWriter.  This is currently set up to throw an error if we apply it to an unmapped field, which will trip on runtime fields.  We can fix this by allowing an optional `unmapped field analyzer` to be configured on the QueryShardContext - this will also help in a few other places, such as the percolator, which have more lenient restrictions on what can be tokenized.

2) The fast vector highlighter directly loads its data from source; the unified and plain highlighters are a bit cleverer here and load data via ValueFetchers, but the way things are currently set up this only actually works for SourceValueFetchers.  DocValueFetchers (which runtime fields expose) need to be positioned correctly before the data is loaded, and the highlighters don't have the right API access to do this.

The first problem can be solved through a fairly targeted change, but the second is more complicated and involves some more thinking on how ValueFetchers are configured.  One option would be to change the signature of ValueFetcher.fetchValues() to take a LeafSearchLookup, rather than a SourceLookup, and read data directly from the various data structures there.  This has the advantage of centralising docvalues/stored fields/source access in a single place, and unifying query-time and fetch-time access to these values.

cc @jtibshirani @nik9000

**Comment by jimczi** [comment]
That always felt wrong to me that we "re-analyze" or try to load fast vectors to simply highlight a keyword field.
So one simplification here could be to generalize the execution for keyword field (doesn't depend on the highlither type) and just check if the highlight query matches ? We don't need the offsets here since we want to highlight the entire value ? 
Regarding runtime fields, I don't think we need to care about the FVH, it's a specialized highlighter for fields indexed with terms vector so it's out of scope here. I still have hope that we can remove it entirely someday since most of its functionalities are available in the unified one.

**Comment by jtibshirani** [comment]
@romseygeek can this be closed now that #65560 is merged? Also checking we aren't missing required refactors/ new functionality in `ValueFetcher`?

**Comment by romseygeek** [comment]
I think it's worth exploring changing the ValueFetcher to take a LeafSourceLookup, but that's a separate issue so I'll close this one.
