### ISSUE TITLE
[8.0.0] `node.processors` is no longer allowed to exceed number of available processors

### ISSUE THREAD

**Issue by jloisel** [elastic/elasticsearch#65569]
I saw that `node.processors` is no longer allowed to exceed number of available processors. What if the number of available processors is wrongly detected by the JVM?

It's the case on our kubernetes cluster running on Rancher v2.x.x:

```
#! Deprecation: setting [node.processors] to value [12] which is more than available processors [1] is deprecated
```

We have 6 cores / 12 threads Xeon machines, yet Elasticsearch which runs inside from your official docker image only detects `1` available processor. 

I think it's valuable to allow setting a value higher than available processors in that case, because otherwise we have to figure out how to run Elasticsearch without docker. 

We haven't found yet why the number of available processors is wrongly detected within Elasticsearch. There is no CPU / memory quota.

We are using Elasticsearch `7.4.2` for now.

**Comment by henningandersen** [comment]
@jloisel newer versions of java do try to calculate the available processors within a container correctly, at least if using quota and not shares. When using cpu shares java divides shares by 1024, which can lead to issues like the above. I believe you have at least 3 options for improving this:

1. Use [--cpus=12](https://docs.docker.com/config/containers/resource_constraints/) when starting docker to make the quota explicit
2. Use [--cpu-shares=12288](https://docs.docker.com/config/containers/resource_constraints/) when starting docker to have the shares be compatible with how java derives number of processors from it.
3. Use -XX:ActiveProcessorCount=12 as a jvm option.

Notice that even if ES were more lenient and accepted a `node.processors` above the current set of processors, more configuration would still be necessary, since java has several other thread-pools that will be sized wrongly too, like GC threads, hotspot compilation threads and more.

I think above is sufficient for this issue and will therefore close this. Feel free to reopen if none of the solutions work out.

**Comment by jloisel** [comment]
Thanks for the clarification. We're not using any quota setting. We have other java containers based on openjdk which detect the CPU count well. Elasticsearch is the only container which only detect 1 cpu. I thought it would be worth investigating why, given no quotas / limitation is in place, the CPU count is detected wrongly. 

The solutions will work, but I don't understand why I have to do that specifically for Elasticsearch (as said before, other java containers running within the same cluster don't experience this issue).

**Comment by jloisel** [comment]
I should mention that "nproc" command inside the container returns the right number of CPU cores (`12` in our case).

**Comment by ebuildy** [comment]
@jloisel nproc will always return all host available processors (if you dont specify container ``ulimit``).

With ``cat /sys/fs/cgroup/cpuset/cpuset.cpus`` you should get exactly how many CPUs the container have.

With k8s, it's possible there is a namespace default limit range, that override container resources. I would recommend to always specify pod containers resources CPU/memory (both request/limit).

**Comment by jloisel** [comment]
@ebuildy Thanks for your Insight Thomas :)
