### ISSUE TITLE
Set the start checkpoint time when starting a Data Transform

### ISSUE THREAD

**Issue by mbudge** [elastic/elasticsearch#65570]
Hi, 

We are starting to use Data Transforms to aggregate data we display in dashboards. However, when we first start the transform it starts processing data from the start of the index. The indexes store large columns of event data and most are frozen. When we create the transform it takes 1 hour for the transform to appear in the UI (after validation has finished). The first checkpoint takes ages as the transform tries to process months of event data.

I've applied to new transform alias to the index, but this is a bit of a hacky way to fix the problem as we need to remove the alias after X weeks. Instead we need to be able to set the start checkpoint so we can limit where the transform starts processing data from. Setting the end date would only be useful for batch transforms.

This is similar to setting the start time when setting up an ML job. We need something similar for transforms so they don't process old and frozen indexes. We need to be able to set the checkpoint via the API as well as the user-interface, as we copy the transforms to the clipboard so we can make future changes via Dev Tools (after deleting the original transform).

Thanks.

**Comment by hendrikmuhs** [comment]
@mbudge The recommended way for this problem is defining a query with a lower boundary, e.g. a `range` query with `gte {timestamp}` as part of the `source` definition.

When elasticsearch runs the query it will prune shards from the requests in the "can match" phase. Best to my knowledge it does not forward search requests to cold tiers in that case, meaning shards that hold data that is older than the defined lower bound.

**Comment by mbudge** [comment]
Hi, 

The frozen indexes are in the code phase, but they were still unfreezing when we started the transform. 

We have a bunch of transforms which use the range query to do sliding window, and the transforms work great for those use cases. 

However, when the range query is in the transform the first seen timestamp is always at the start of the sliding window. If we don't want the first seen/minimum @timestamp to get overwritten we have to remove the range query. But when we do this the transform starts crunching data from the start of the index.

Thanks

**Comment by hendrikmuhs** [comment]
> However, when the range query is in the transform the first seen timestamp is always at the start of the sliding window. If we don't want the first seen/minimum @timestamp to get overwritten we have to remove the range query. But when we do this the transform starts crunching data from the start of the index.

Transform by design re-creates and overwrites documents, but does not upsert them. That means, if an entity changes, transform queries _all_ data points again.

You are right that transform could conceptually upsert instead, e.g. updating the document by only changing the changed fields. An existing `min(@timestamp)` does not need to be recreated, _in theory_.

_In practice_ transform is a generic framework, it has to work for many use cases, it supports many aggregations. To illustrate the "Update instead of Re-compute" problem:

   - min/max/sum are easy
   - for average we could store sum and count to make it update-able
   - to update a median you need a histogram, fortunately we have that now (histogram datatype)
   - for cardinality we have to store the sketch, e.g. the hyperloglog data structure, we do not have such a data type yet
   - for scripted metric we need the user to write the update method

This doesn't mean we do not want to support update at all, we have plans to implement this in future. Due to the challenges explained, we likely will not support every aggregation/data type to be update-able or at least add support step by step over time.

Is `min(@timestamp)` the only problematic one?
What else are you using in your transform?

I could imagine that in future transform could detect certain configurations and optimize execution internally. We already do something similar for _continuous mode_. Continuous applies filters based on certain configuration options.

**Comment by mbudge** [comment]
Thanks for taking the time to explain all that. 

"That means, if an entity changes, transform queries all data points again."

That's the bit I was missing. 

For some of our use cases it's just the min@timestamp. This will allow us to track when an entity is first seen in an index. It sounds like we are asking for an option to freeze the field the first time the entity is processed. 

We could probably test this out by periodically reindexing the new entities to a second index, and include the second index in the transform source indexes. If we set the reindex to create/noop the first entity create which stores the first minimum @timestamp won't get overwritten. Though this wouldn't be fun to maintain with too many transforms.

I have one more question we have been trying out work out. How is the index operation configured so the continuous transforms can overwrite documents with the same ID (hash of the entity) without causing the destination index to store loads of deleted/tombstoned documents? We are trying to work out if it's possible to configure an index operation so new documents overwrite documents with the same ID without causing elastic to do a delete/index operation. 

Thanks

**Comment by hendrikmuhs** [comment]
> I have one more question we have been trying out work out. How is the index operation configured so the continuous transforms can overwrite documents with the same ID (hash of the entity) without causing the destination index to store loads of deleted/tombstoned documents? We are trying to work out if it's possible to configure an index operation so new documents overwrite documents with the same ID without causing elastic to do a delete/index operation.

Transform uses deterministic document ids, so it can overwrite docs without creating duplicates. Overwrite always means a _delete_ and a _create_, that's by design of lucene indexes. There is no way to update a document, even if it's a trivial change like incrementing a counter. Immutability of Lucene segments have pros and cons.

Despite most transform use cases don't have a problem with that. What transform does is using "smart" queries to prevent excessive updates. For the entity case imagine that you have millions of them, but just a few hundreds retrieve updates. Transform only updates those, so continuous transform is not a starting from scratch every time. If all your entities change, you will not make use of this optimization.
