### ISSUE TITLE
QueryBuilders query wants to add lamba expressions

### ISSUE THREAD

**Issue by zundaren** [elastic/elasticsearch#65712]
like this

QueryBuilders<Entity>.matchQuery(Entity::id, "123")

**Comment by pgomulka** [comment]
can you please provide more details on how this will be used and what will be the benefit?

**Comment by cbuescher** [comment]
@zundaren I don't see us wanting to extend the capabilities of `QueryBuilders`, which is a convenience wrapper for constructing some basic query, significantly. I don't quite understand what `Entity` stands for here, but assume it might be a string supplier, since that's what the current match queries first argument requires. I don't see huge benfits specifying this with a lambda though. I will close this issue for now but please re-open if there is anything I missed or if you think this would be an important addition. In this case please specify a bit more detailed why you need this.
