### ISSUE TITLE
addr is of illegal length

### ISSUE THREAD

**Issue by kender1314** [elastic/elasticsearch#65865]
elasticsearch version: 7.9.1
elasticsearch command:

```
POST /_search?rest_total_hits_as_int=true
{
	"index": [
		"ip_mac_merge_*"
	],
	"ignore_unavailable": true
}
{
	"size": 0,
	"query": {
		"bool": {
			"must_not": [],
			"must": [
				{
					"query_string": {
						"query": "*",
						"analyze_wildcard": true
					}
				},
				{
					"range": {
						"date": {
							"gte": "2020-11-03 00:00:00",
							"lte": "2020-12-02 23:59:59"
						}
					}
				}
			]
		}
	},
	"fielddata_fields": [
		"e_date",
		"s_date",
		"create_date",
		"date"
	],
	"from": 0,
	"_source": {
		"excludes": [
			"@timestamp",
			"link_id"
		]
	},
	"fields": [
		"*",
		"_source"
	],
	"aggs": {
		"ip2": {
			"terms": {
				"field": "ip2",
				"size": 10
			}
		},
		"ip1": {
			"terms": {
				"field": "ip2",
				"size": 10
			}
		}
	}
}
```
error repose:

```
{
	"error": {
		"root_cause": [
			{
				"type": "illegal_argument_exception",
				"reason": "encoded bytes are of incorrect length"
			}
		],
		"type": "illegal_argument_exception",
		"reason": "encoded bytes are of incorrect length",
		"caused_by": {
			"type": "illegal_argument_exception",
			"reason": "addr is of illegal length"
		}
	},
	"status": 400
}
```
The field type of ip1 and ip2 is ip type.

I conducted some tests. When I shorten the time range to query, the query results can be returned normally, but the ipv6 values in the ip1 and ip2 fields are garbled.
This is part of the result

```
"ip2": {
  "doc_count error_upper bound": 12442,
  "sum_other_doc_count": 1870188，
  "buckets":[ 
     {
        "key": \u0000\u0000\u0000\u0000 \u0000\u0000\u0000\u0000\u0000\u0000??\tR",
        "doc_count": 29738
    }
    {
        "key": "192.168.9.237",
        "doc_count": 29362
    }
  ]
}
```
Our last version used 7.6.2, and there is no problem with this msearch query itself.

I suspect that there is a bug in elasticsearch 7.9.1, but I am not sure if this error is due to ipv6.

How should this problem be solved? thank you very much.

**Comment by cbuescher** [comment]
The "encoded bytes are of incorrect length" exception is thrown by Lucenes `InetAddressPoint#decode` method when decoding an input bytes value doesn't succeed.
In order to dig into this further it would be good to narrow the cause down. Ideally it would be great to get to a few single documents that when searched are causing this problem.
@kender1314 can you try narrow down the time range to maybe just a few or even just a single document with wich you can reproduce the error? Also, is there a longer stack trace showing up in the logs that leads to this error? This would help narrowing down the code path taken. Lastly: can you take out individual parts of the query (e.g. the aggs, fields parts) to see if any of these might be responsible for the error?

**Comment by danielmitterdorfer** [comment]
No further feedback received. @kender1314 if you have the requested
information please add it in a comment and we can look at re-opening
this issue.
