### ISSUE TITLE
Missing `store.size` and `pri.store.size`'s unit in the response of cat indices API

### ISSUE THREAD

**Issue by gaobinlong** [elastic/elasticsearch#65911]
**Elasticsearch version**: master

**Plugins installed**: []

**JVM version (java -version)**: 14.0.1

**OS version (uname -a if on a Unix-like system)**: Mac OS 10.13.6

**Description of the problem including expected versus actual behavior**:

By default, the `store.size` and `pri.store.size` columns contain unit like 'kb','mb' in the response of `cat indices` and `cat shards` API.
However, when we specify the query parameter `bytes` in the `cat indices` or `cat shards` API, the unit of `store.size`& `pri.store.size` columns in the response is missing.

**Steps to reproduce**:

1. GET _cat/indices/test?v

```
health status index   uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   test   DkpOxA80Q-eWkVooYILMWQ   1   0    6761501            0    317.5mb        317.5mb
```

2. GET _cat/indices/test?v&bytes=mb

```
health status index   uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green open test DkpOxA80Q-eWkVooYILMWQ 1 0 6761501 0 317 317
```

**Comment by DaveCTurner** [comment]
This is deliberate, and IMO is the right thing to do. If you don't ask for a specific size unit then we write the units after every size because it's ambiguous otherwise. If you do ask for a specific size unit then there's no ambiguity, all the sizes are in the unit you requested so there's no need to mention the units.

The effect of removing the unit is also desirable if you're piping these results into other tools. Removing a trailing `b` or `mb` or whatever would be a pain.

This isn't just in `master` either, this behaviour is documented all the way back to [1.3](https://www.elastic.co/guide/en/elasticsearch/reference/1.3/cat.html#numeric-formats).

**Comment by gaobinlong** [comment]
Thanks for your explanation @DaveCTurner .
