### ISSUE TITLE
_cat/plugins does not list quota-aware-fs plugin

### ISSUE THREAD

**Issue by mieciu** [elastic/elasticsearch#66107]
**Elasticsearch version**: `8.0.0-SNAPSHOT`, `7.11.0-SNAPSHOT` (possibly `6.8.14-SNAPSHOT` as well)

**Description of the problem including expected versus actual behavior**: 

The `_cat/plugins` API endpoint does not list `quota-aware-fs` plugin. The plugin gets installed successfully and is visible via `/bin/elasticsearch-plugin` tool:
```
bash-4.4# ./bin/elasticsearch-plugin list
quota-aware-fs
repository-s3
```
but the `_cat/plugins` endpoint response looks like this:
```
_cat/plugins?v
name                  component     version
instance-0000000000   repository-s3 8.0.0-SNAPSHOT
instance-0000000001   repository-s3 8.0.0-SNAPSHOT
tiebreaker-0000000002 repository-s3 8.0.0-SNAPSHOT
```

**Steps to reproduce**:
1) Install `quota-aware-fs` plugin
2) Shoot `GET _cat/plugins?v`

---

Related PRs: https://github.com/elastic/elasticsearch/pull/63620 https://github.com/elastic/elasticsearch/pull/64850

**Comment by pugnascotia** [comment]
Right now, this is intentional behaviour. `quota-aware-fs` is a `bootstrap` plugin, meaning that it is specifically not loaded into Elasticsearch when it runs. However, we could tweak the loading so that the existence of the plugin can still be known, while still skipping the loading of its libraries.
