### ISSUE TITLE
[CI] InternalDistributionBwcSetupPluginFuncTest failing on Windows

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#66372]
**Build scan**:
https://gradle-enterprise.elastic.co/s/pglyaiimstr7q/tests/failed

**Applicable branches**:
Looks specific to master

**Failure history**:
https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.rootProjectNames=elasticsearch&search.tags=CI&search.timeZoneId=America/Los_Angeles&tests.container=org.elasticsearch.gradle.internal.InternalDistributionBwcSetupPluginFuncTest&tests.sortField=FAILED&tests.unstableOnly=true

**Failure excerpt**:
```
java.io.FileNotFoundException: Source 'C:\Program%20Files\teamcityagent\buildAgent\work\54260db9f28b416\buildSrc\build\resources\integTest\org\elasticsearch\gradle\internal\fake_git\remote' does not exist 
```

**Comment by mark-vieira** [comment]
@breskeby this has been failing pretty consistently on windows. Mind taking a look?

**Comment by mark-vieira** [comment]
This looks to still be failing. I have a fix incoming.

**Comment by breskeby** [comment]
As discussed with @colings86 we should avoid spaces in our ci working dir. I'm also running out of ideas what the actual problem is here given there was another attempt on fixing this with #66626. One thought was we run into path length limitations but that doesn't seem the case. One potential fix that might work is to use 8.3 filenames as suggested by @bytebilly which I personally would try to avoid and instead ditch the space in the working dir at all

**Comment by mark-vieira** [comment]
> As discussed with @colings86 we should avoid spaces in our ci working dir.

I can look into doing this, especially for windows.

**Comment by breskeby** [comment]
have you checked the tc agents path setup @mark-vieira

**Comment by mark-vieira** [comment]
So I had to update the _temp_ dir on those builds to get these tests to pass but they now do (and others fail), so we can close this for now.
