### ISSUE TITLE
Add ability to snapshot to file system of a single node.

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#6638]
Add new "local" snapshot repository type that would be similar to shared filesystem repository but will allow storing all snapshot file on a local file system of a single node.

**Comment by clintongormley** [comment]
@imotov do you still think this is something that we should implement?  My inclination would be to say: just set up an NFS mount or similar.

**Comment by imotov** [comment]
@clintongormley we should definitely implement that. It will help users in several important use cases, including simplifying sharing of marvel data with support.

**Comment by ashish-kumar-goel** [comment]
I am facing a similar issue. I have placed my cluster nodes on EC2 instances and when I try to take a snapshot on a local FS repository, it gives an error saying that the target location for snapshot is not shared. 
Then, I made use of a S3 repository for taking snapshots. It works well, the only problem is that when it is taking snapshots, the process blocks any updates over ES. I read something regarding this which mentioned that ES needs to take into account the details of the previous snapshots taken (figuring out the segments involved) and due to this it takes some time in creating the new one. I already have a cron job setup which deletes a week old snapshots but even after that it takes some time to create the new snapshots. 
So, I was wondering if there is a way I can move out of S3, make use of a local repository. Please not that these nodes are not having any shared mount space.

**Comment by tsmall888** [comment]
Additionally, encrypted snapshots to nfs share - it's more secure. If it's impossible, we have only one way - make snapshots to local server, compress and encrypt them and  then move to nfs share.

Can you add on-the-fly encryption in AES mode to nfs share or add local snapshots type?

**Comment by shaharmor** [comment]
Is this being worked on?

**Comment by imotov** [comment]
I am not working on it at the moment. If somebody wants to take over, I will be glad to provide any assistance.

**Comment by erdarun** [comment]
Is anyone working on this feature?

**Comment by DaveCTurner** [comment]
[This user](https://discuss.elastic.co/t/synced-flush-and-keep-indexing-on-primary/166197/3?u=davidturner) would benefit from this feature. Rather than setting up a shared filesystem they have instead invented a backup strategy that seems a little delicate.

@erdarun no, I do not know of anyone working on this right now.

**Comment by DaveCTurner** [comment]
We discussed this again today and feel that there are now a decent number of third-party options that would let you achieve the goals of this feature request without needing any changes in Elasticsearch. For example, Minio will accept snapshots onto a single node, or indeed onto a completely independent cluster. Implementing this feature would, in effect, require us to duplicate all the work that has gone into systems like Minio. We therefore agreed to close this issue.

**Comment by AnyCPU** [comment]
I would like to see this feature built-in, otherwise it is at least not user friendly. It is very good to have built-in alternative to 3rd party plug-ins. Maybe we should wait for another 6 years to get this feature.

**Comment by webmstr** [comment]
> We discussed this again today and feel that there are now a decent number of third-party options that would let you achieve the goals of this feature request without needing any changes in Elasticsearch. For example, Minio will accept snapshots onto a single node, or indeed onto a completely independent cluster. Implementing this feature would, in effect, require us to duplicate all the work that has gone into systems like Minio. We therefore agreed to close this issue.

According to wikipedia, "MinIO is an Amazon S3 compatible server-side software storage stack".  You're saying that's the solution for a local filesystem backup??
