### ISSUE TITLE
Elastic Java client: RequestOptions.DEFAULT.toBuilder() not supporting method setRequestConfig

### ISSUE THREAD

**Issue by David-Lor** [elastic/elasticsearch#66441]
**Elasticsearch Java client version**: `org.elasticsearch:elasticsearch:7.10.1` ; `org.elasticsearch.client:elasticsearch-rest-high-level-client:7.10.1`

**JVM version** (`java -version`): `openjdk version "11.0.8-internal" 2020-07-14`

**Description of the problem including expected versus actual behavior**:

On Elastic Java client docs for version 7.10, on Timeouts section (https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/_timeouts.html), it's said that `Timeouts also can be set per request with RequestOptions, which overrides RestClient customizeRequestConfig`, and the following code snippet is given:

```
RequestConfig requestConfig = RequestConfig.custom()
    .setConnectTimeout(5000)
    .setSocketTimeout(60000)
    .build();
RequestOptions options = RequestOptions.DEFAULT.toBuilder()
    .setRequestConfig(requestConfig)
    .build();
```

However, when using that snippet, compilation fails because the `setRequestConfig()` method does not exist on the Builder object returned by `RequestOptions.DEFAULT.toBuilder()`.

Output of `gradle build`:

```
error: cannot find symbol
                .setRequestConfig(requestConfig)
                ^
  symbol:   method setRequestConfig(RequestConfig)
  location: class Builder
```

**Comment by cbuescher** [comment]
Hi @David-Lor, thanks for opening this issue. For all that I can see, the snippet is okay. We pull these Java examples [from classes that we also compile](https://github.com/elastic/elasticsearch/blob/master/client/rest/src/test/java/org/elasticsearch/client/documentation/RestClientDocumentation.java#L331) as part of our build, so I assume the way this was used in your code is the actual problem. It would be good to get a better look at what an how you are compiling your client code, however I'd like to encourage you doing this over in our support forums at https://discuss.elastic.co because we would like to use Github issues only for bug reports and feature requests. Many thanks.
