### ISSUE TITLE
Query String with default operator is not working properly

### ISSUE THREAD

**Issue by aalmir** [elastic/elasticsearch#66472]
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 7.7.0, Build: default/zip/81a1e9eda8e6183f5237786246f6dced26a10eaf/2020-05-12T02:01:37.602180Z, JVM: 15

**Plugins installed**: []
none

**JVM version** (`java -version`):
openjdk version "14" 2020-03-17
OpenJDK Runtime Environment AdoptOpenJDK (build 14+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14+36, mixed mode, sharing)

**OS version** (`uname -a` if on a Unix-like system):
Windows 10, Windows 2016

**Description of the problem including expected versus actual behavior**:
This stackoverflow post explains the problem:
https://stackoverflow.com/questions/57904019/elasticsearch-and-in-query-string-vs-default-operator-and

	query_string: {
		query: searchString,
		default_operator: "AND",
	},

word1 word2 => no results
word1 AND word2 => 2 results
or
word1 +word2 => 2results

The default operator is not working properly.
Word1 and word2 are not in the same field, if the words are in the same field its working.

**Comment by jimczi** [comment]
Whitespaces are not considered as operators in the `query_string` query , see the example in https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-string-query-ex-request. In short, you need to add explicit boolean operators to indicate where the cross-fields analysis should take place. The query `word1 word2` expects that these  two terms are both matching in a single field. On the contrary, doing `word1 AND  word2` indicates that the two terms are mandatory but they can  match on different  fields.
Since this behavior is documented I  hope you don't mind  if close the issue.
