### ISSUE TITLE
[Fields API] Discrepancy between timestamp field in _source and in fields 

### ISSUE THREAD

**Issue by majagrubic** [elastic/elasticsearch#66693]
**Elasticsearch version**:
8.0.0. Snapshot (https://storage.googleapis.com/kibana-ci-es-snapshots-daily/8.0.0/archives/20201214-194211_7011cba/elasticsearch-oss-8.0.0-SNAPSHOT-darwin-x86_64.tar.gz)

**Plugins installed**: []

**JVM version** (`java -version`):
12.0.2

**OS version** (`uname -a` if on a Unix-like system):
MAC OS 10.14.6

**Description of the problem including expected versus actual behavior**:
I noticed this behavior when running functional tests in Kibana. When timestamp is defined as `date_nanos` type in the mapping, it looks like `@timestamp` field is correctly returned in` _source` part of the response, but truncated in the `fields` part of the response:
```
{
        "_index" : "date-nanos",
        "_id" : "AU_x3-TaGFA8no6QjiSJ",
        "_score" : 1.0,
        "_source" : {
          ...
          "@timestamp" : "2019-09-22T23:50:13.253123345Z",
          ...
        },
        "fields" : {
          ...
          "@timestamp" : [
            "2019-09-22T23:50:13.253Z"
          ],
          ...
        }
}
```

(I've left out non-relevant fields from the response)

`@timestamp` is defined as date_nanos type:
https://github.com/elastic/kibana/blob/953930be49ceba32fe1755d4172a67034c8be6d8/test/functional/fixtures/es_archiver/date_nanos/mappings.json#L8

and the document is defined here:
https://github.com/elastic/kibana/blob/a33201cf39ac3e43c0d862715222d0ddb2ddd1d9/test/functional/fixtures/es_archiver/date_nanos/data.json#L65

**Steps to reproduce**:
I used Kibana's devtools console to create an index / put a document / query the document.
1. Create an index with `date_nanos` timestamp:
```
PUT /my-test-index 
{
  
  "mappings": {
    "properties": {
      "@timestamp": {
          "type": "date_nanos"
      }
    }
  },
  "settings": {
    "index": {
      "number_of_replicas": "0",
      "number_of_shards": "1"
    }
  }
}
```

2. Put a document with timestamp in nanoseconds:
```
PUT /my-test-index/_doc/1
{
   "id": "AU_x3-TaGFA8no6QjiSJ",
   "@message" : "5",
   "@timestamp": "2019-09-22T23:50:13.253123345Z",
   "referer": "http://twitter.com/error/takuya-onishi",
   "request": "/uploads/dafydd-williams.jpg",
   "response": "200",
   "type": "apache",
   "url": "https://media-for-the-masses.theacademyofperformingartsandscience.org/uploads/dafydd-williams.jpg"
}
```

3. Query with fields option set:
```
GET my-test-index/_search
{
  "query": {
    "match_all": {}
  },
  "fields": ["*"]
}
```

Response:

```
 {
        "_index" : "my-test-index",
        "_id" : "1",
        "_score" : 1.0,
        "_source" : {
          "id" : "AU_x3-TaGFA8no6QjiSJ",
          "@message" : "5",
          "@timestamp" : "2019-09-22T23:50:13.253123345Z",
          "referer" : "http://twitter.com/error/takuya-onishi",
          "request" : "/uploads/dafydd-williams.jpg",
          "response" : "200",
          "type" : "apache",
          "url" : "https://media-for-the-masses.theacademyofperformingartsandscience.org/uploads/dafydd-williams.jpg"
        },
        "fields" : {
          "request" : [
            "/uploads/dafydd-williams.jpg"
          ],
          "referer" : [
            "http://twitter.com/error/takuya-onishi"
          ],
          "request.keyword" : [
            "/uploads/dafydd-williams.jpg"
          ],
          "type" : [
            "apache"
          ],
          "@message.keyword" : [
            "5"
          ],
          "url" : [
            "https://media-for-the-masses.theacademyofperformingartsandscience.org/uploads/dafydd-williams.jpg"
          ],
          "url.keyword" : [
            "https://media-for-the-masses.theacademyofperformingartsandscience.org/uploads/dafydd-williams.jpg"
          ],
          "@message" : [
            "5"
          ],
          "response.keyword" : [
            "200"
          ],
          "id.keyword" : [
            "AU_x3-TaGFA8no6QjiSJ"
          ],
          "@timestamp" : [
            "2019-09-22T23:50:13.253Z"
          ],
          "type.keyword" : [
            "apache"
          ],
          "response" : [
            "200"
          ],
          "id" : [
            "AU_x3-TaGFA8no6QjiSJ"
          ],
          "referer.keyword" : [
            "http://twitter.com/error/takuya-onishi"
          ]
        }
      }
    ]
  }
```

**Comment by jtibshirani** [comment]
Thanks @majagrubic for raising this. This is indeed confusing behavior, but expected given our strategy for formatting `date_nanos`. By default, we parse `date_nanos` fields using `strict_date_optional_time`. When returning data, the `fields` option makes sure to format the results using this same default formatter. Unfortunately `strict_date_optional_time` will accepts and parses dates with nanosecond precision, but when it formats it drops the nanosecond precision.

A quick fix for those tests would be to specify an explicit format which always preserves nanosecond precision:
```
  "fields": [
    {
      "field": "@timestamp",
      "format": "strict_date_optional_time_nanos"
    }
  ]
```

I think we should also address the underlying confusing behavior. A couple options I see:
* Change the default formatter for `date_nanos` to one that always preserves nanoseconds.
* Change the `fields` option to pass through dates untouched by default, instead of always parsing + formatting.

**Comment by rjernst** [comment]
@jtibshirani I agree we should fix the underlying behavior. A couple thoughts on the options proposed.

> Change the default formatter for date_nanos to one that always preserves nanoseconds.

This seems like a good idea on it's own. It is confusing that a date nanos field would ever print without nanos precision.

> Change the fields option to pass through dates untouched by default, instead of always parsing + formatting.

I think this should be considered independently. It may be a good idea, it just depends on what the "view" of fields is supposed to be (original values, or formatted values). I see the parsing + formatting as necessary to ensure consistency, since there could be multiple input formats, so doing a parse + format results in the same output format.

**Comment by jtibshirani** [comment]
> This seems like a good idea on it's own. It is confusing that a date nanos field would ever print without nanos precision.

I filed with #67063 this proposal.

> Change the fields option to pass through dates untouched by default, instead of always parsing + formatting... I see the parsing + formatting as necessary to ensure consistency, since there could be multiple input formats, so doing a parse + format results in the same output format.

I agree and would prefer not to go this direction, since the 'fields' option is currently focused on returning formatted values.

I'll close this in favor of tracking #67063, but feel free to reopen or add more thoughts.
