### ISSUE TITLE
Update profiler docs with info about build_leaf_collector, build_leaf_collector_count, post_collection, and post_collection_count

### ISSUE THREAD

**Issue by cjcenizal** [elastic/elasticsearch#66709]
We added this debugging info in https://github.com/elastic/elasticsearch/pull/62317. A Kibana user saw these being surfaced in Search Profiler and asked what they were (https://github.com/elastic/kibana/issues/77372) and I found that they're missing from our docs: https://www.elastic.co/guide/en/elasticsearch/reference/master/search-profile.html#_all_parameters_2.

**Comment by jrodewig** [comment]
Thanks @lockewritesdocs. I opened #66717 but didn't merge the PR. I don't think my initial approach is the one we'll take. As @nik9000 notes in one of the comments:

> These aggregations debugging things have a fairly limited audience and I'm not sure how useful it is to document them super thoroughly. We're adding more and more of these specifically so we can ask for them when folks are having trouble and we can see deep into the guts of the system.

Each of these properties corresponds to a method. We should probably rewrite the relevant sections of the docs to mention that relationship rather than documenting each individual property.
