### ISSUE TITLE
Elastic search query using a list

### ISSUE THREAD

**Issue by shantanuo** [elastic/elasticsearch#66731]
How do I pass a list as query string to match_phrase query?

This works:

`{"match_phrase": {"requestParameters.bucketName": {"query": "auditloggingnew2232"}}}`

This does not:

```
        {
            "match_phrase": {
                "requestParameters.bucketName": {
                    "query": [
                        "auditloggingnew2232",
                        "config-bucket-123",
                        "web-servers",
                        "esbck-essnap-1djjegwy9fvyl",
                        "tempexpo",
                    ]
                }
            }
        }
```

There are other ways to achieve this. But this is the most concise and logical way to express.

**Comment by shantanuo** [comment]
As discussed at stack overflow: https://stackoverflow.com/questions/63091114/elastic-search-query-using-python-list

**Comment by polyfractal** [comment]
The Stack Overflow comments are correct: to use a `match_phrase` with multiple phrases, you should combine them with a `bool` query.  The query DSL is configured in this manner because there is a lot of nuance to combining multiple different queries.  How should the scores be combined? Are all phrases/queries required, or optional?  If they are optional, are they all optional, or do a certain threshold need to match? Should the queries affect scoring, and if so do the different phrases affect scoring differently?  Are these all non-scoring and just filters? etc etc

That's why most queries in the DSL are designed around one "logical query", and you combine these with different compound queries like Boolean. 

In the future, we prefer questions like this to be asked over at the forums :) https://discuss.elastic.co/
