### ISSUE TITLE
Completion Suggester taking up more than 90% of jvm memory allocated.

### ISSUE THREAD

**Issue by jalal-fw** [elastic/elasticsearch#66740]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.9.1

**Plugins installed**: []  None

**JVM version** (`java -version`):  1.8.0_262

**OS version** (`uname -a` if on a Unix-like system): 4.19.12-1.el7.elrepo.x86_64

**Description of the problem including expected versus actual behavior**:

Completion Suggester utilizes more than 90% of the heap allocated to Elasticsearch on a single node cluster.
We have a constraint that we can't go to a multi-node setup.

Below is the stats for completion, this node has 17GB of RAM allocated to it.

"_all": {
  "primaries": {
    "completion": {
      "size_in_bytes": 16747507839
    }
  },
  "total": {
    "completion": {
      "size_in_bytes": 16747507839
    }

Is there a way to disable Completion suggester without going for a re-index.

**Comment by jimczi** [comment]
There's  no way to disable or remove a field so a reindex is needed. Although the completion fields are loaded lazily (only when they are used in queries or requested in stats) so you could also restart the node and stop requesting these completion fields. I hope you don't mind if I close this issue since we don't provide ways to remove field from the mapping. Reindexing with a modified mapping should be preferred in order to ensure that the memory cannot be reclaimed on random requests.
