### ISSUE TITLE
[Transform]  _preview endpoint for latest method always returns empty mappings properties

### ISSUE THREAD

**Issue by darnautov** [elastic/elasticsearch#66812]
**Elasticsearch version** (`bin/elasticsearch --version`):
`Version: 8.0.0-SNAPSHOT, Build: default/tar/cd72f45c3358139d717392924260657ddf835055/2020-12-23T22:33:11.944357Z, JVM: 11.0.6`

**Description of the problem including expected versus actual behavior**:
`_preview` endpoint for latest method always returns empty mappings properties. Expecting to receive appropriate mappings for the dest index deduced from the source index. 

**Steps to reproduce**:

 1. Call the preview endpoint with a valid configuration, e.g. 
```
POST _transform/_preview
{
  "source": {
    "index": [
      "gallery-*"
    ]
  },
  "latest": {
    "unique_key": [
      "clientip"
    ],
    "sort": "@timestamp"
  }
}
```
 2. Check `generated_dest_index.mappings.properties` field of the response body. It's always an empty object.

**Comment by przemekwitek** [comment]
As copying mappings from source to dest index turned out to be problematic for automation (think about all the fields properties, like text analyzers, that are unavailable when fetching field capabilities), the decision was *not* to copy the mappings as part of the `latest` transform.
Instead, it's the user that is responsible for creating destination index (or providing an index template) with right mappings.

In order to handle `preview` case, the UI code could look into source index mappings in order to format the `preview` columns properly. @darnautov is already on that, so I'm transferring the issue to him.

**Comment by darnautov** [comment]
Resolved on the Kibana side in https://github.com/elastic/kibana/pull/87168
