### ISSUE TITLE
Plugin registry

### ISSUE THREAD

**Issue by tobiasstadler** [elastic/elasticsearch#66817]
It would be nice if there exists a registry where community members could upload there elasticsearch plugins. In addition to that one should be able to download/install the plug-in via Kibana. The registry enables the community to promote/explore/use existing plugins.

**Comment by rjernst** [comment]
We have a registry of sorts already, in the list of plugins of different types (eg https://www.elastic.co/guide/en/elasticsearch/plugins/7.10/analysis.html), which includes community plugins. These are not downloadable, but it at least is a resource users can look at for finding what may be available.

While we understand the desire to have easier plugin installation, installing plugins through Kibana is a *long* way off. Plugin installation requires system permissions, and cannot be done from within Elasticsearch itself. So any type of integration through Kibana is simply not possible with the current architecture. Additionally, there are much higher priority asks around plugins, for example having a stable plugin API so that plugins do not need to be rebuilt for every Elasticsearch release.

Given the technical challenges mentioned and competing priorities, I hope you don't mind that I close this issue. While it may be something we look at in the future, we are likely years away from this being a remote possibility.
