### ISSUE TITLE
Rollup Search does not support value_count metric aggregations

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#67405]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.10.0

**Description of the problem including expected versus actual behavior**:

using a `value_count` aggregation on fields within a rollup index that specified `value_count` 
as a supported metrics is broken. The code is not aware of such values and throws an unsupported
exception. This is a bug and support for IntervalValueCount should be added.

**Steps to reproduce**:

 1. run ES
 2. create rollup job such as this example

```
PUT _xpack/rollup/job/test2021-1
{
    "index_pattern": "kibana_sample_data_log*",
    "rollup_index": "logs_rollup",
    "cron": "*/30 * * * * ?",
    "page_size" :1000,
    "groups" : {
      "date_histogram": {
        "field": "timestamp",
        "interval": "10m"
      }
    },
    "metrics": [
        {
            "field": "bytes",
            "metrics": ["value_count"]
        }
    ]
}
```

 3. run a search such as 

```
GET logs_rollup/_rollup_search
{
  "size": 0,
  "aggregations": {
    "count": {
      "value_count": {
        "field": "bytes"
      }
    }
  }
}
```

**Exception**:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "runtime_exception",
        "reason" : "Unable to unroll metric.  Aggregation [count] is of type [InternalValueCount] which is currently unsupported."
      }
    ],
    "type" : "runtime_exception",
    "reason" : "Unable to unroll metric.  Aggregation [count] is of type [InternalValueCount] which is currently unsupported."
  },
  "status" : 500
}
```

**Comment by polyfractal** [comment]
This turns out to be a tricky bug to fix. Rollup has to do an agg-rewrite thing, like we do with averages: when the user sends a ValueCount, we can't use that ValueCount on the underlying rollup field because it'll tell us how many values are in the rollup docs.  We instead use a Sum to extract the stored values, then rewrite that into a ValueCount for the response.  

The tricky bit is that v1 differentiates "real Sum" aggs from "avg agg using a Sum" in a terrible manner, and it now needs to include "value_count using a Sum".  There is a tentative WIP fix here: https://github.com/polyfractal/elasticsearch/commit/4ee4481eb5ac296841f59a7ca9c2499e0654878d which stores the "originating" agg in the meta of the aggregation, and uses that to decide how to treat the Sum object later when unrolling the response.

That said, this will become a non-issue with v2 so it is likely to remain unfixed.

**Comment by not-napoleon** [comment]
I'm closing this - rollup is experimental, and this is fixed in the (in progress) GA version.
