### ISSUE TITLE
The performance of  Script Based Sorting in  ES 7.4.2 verison

### ISSUE THREAD

**Issue by BigdataEdison** [elastic/elasticsearch#67441]
```       
   Hello, all, 
        Recently ,  We compare the query performance of two versions of ES cluster. One is 5.3.2, and the other is 7.4.2.
The index settings, mapping  and the amout of data , is exactly the same.I find that the query performance of script sort on 7.42 is very poor.
        From a single query request, the performance of script sort is particularly poor in version 7.4.2，much worse than that in version 5.3.2. 
       For the same two requests, there is a big difference in response time, as shown in the figure below.
       We can share  the changes have taken place in the underlying structure of script sort， and how do we optimize the performance of this sort.
```

* in ES 7.4.2,  the response time is  178ms.
![图片](https://user-images.githubusercontent.com/17466742/104540626-cfe70000-565a-11eb-9354-8f766cba159d.png)

* in ES 5.3.2, ths response time is 29ms
![图片](https://user-images.githubusercontent.com/17466742/104545098-3f152200-5664-11eb-86e4-80fcc9ef82cc.png)

* Through the profile analysis, we can see the location of the collector, which consumes a lot of time in 7.4.2.
![图片](https://user-images.githubusercontent.com/17466742/104467352-31728480-55f1-11eb-8b46-17eb3ff4d8fc.png)

**Comment by BigdataEdison** [comment]
@gwbrown dear brown，  Have you ever encountered a similar problem ？If you have , please share your opinion

**Comment by BigdataEdison** [comment]
Hardware Configuration bewteen ES 5 and ES 7 :

* 5.3.2
  * cpu cores and memory: 40C/128G
  * Hard Disk: 2*150G,SSD(1)
1*900G,10K(JBOD)


* 7.4.2
    *  cpu cores and memory:40C/128G
    *  Hard Disk:2*150G,SSD(1)
       1*480G,SSD(JBOD)

**Comment by rjernst** [comment]
Thanks very much for your interest in Elasticsearch.

There have been an enormous number of changes between 5.3.2 and 7.4.2. Identifying a particular change would be difficult, especially since you implied the scripts are not exactly the same between the two versions.

We recommend you start by asking questions like this on our [forum](https://discuss.elastic.co). There are many knowledgable users of scripts there that can help you improve the efficiency of your code. If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. As such, I hope you don't mind that I close this issue.

As a side note, when posting to the forums or on GitHub, please don't post images of text as they are hard to read, may not display correctly for everyone, and are not searchable. Instead, paste the text and format it with </> icon or pairs of triple backticks (```), and check the preview window to make sure it's properly formatted before posting it. This makes it more likely that your question will receive a useful answer.

**Comment by BigdataEdison** [comment]
@rjernst  ok, thank you!
