### ISSUE TITLE
RestGetAliasesActionTests failures

### ISSUE THREAD

**Issue by joegallo** [elastic/elasticsearch#67545]
**Build scan**: https://gradle-enterprise.elastic.co/s/5mihtfdkcxka4 (my machine), https://gradle-enterprise.elastic.co/s/mp56dimbgyk4o, https://gradle-enterprise.elastic.co/s/ljmyx42y466go

**Repro line**: ```./gradlew ':server:test' --tests "org.elasticsearch.rest.action.admin.indices.RestGetAliasesActionTests.testAliasWildcardsIncludeAndExcludeSome" -Dtests.seed=FA876308D81E4E55 -Dtests.security.manager=true -Dtests.locale=sk-SK -Dtests.timezone=Europe/Tallinn -Druntime.java=15```

**Reproduces locally?**: Not with the above, but it seems pretty deterministic (or at least quite frequent) for me with just `./gradlew ':server:test'`.

**Applicable branches**: `master`

**Failure history**: https://build-stats.elastic.co/goto/3a837e6a1f9f002ea6e70bca9e6c257d

**Failure excerpt**:

```
org.elasticsearch.rest.action.admin.indices.RestGetAliasesActionTests > testAliasWildcardsIncludeAndExcludeSome FAILED
    java.lang.AssertionError:
    Expected: "application/json"
         but: was "application/json;charset=utf-8"
        at __randomizedtesting.SeedInfo.seed([FA876308D81E4E55:731102B1343B21F5]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.rest.action.admin.indices.RestGetAliasesActionTests.testAliasWildcardsIncludeAndExcludeSome(RestGetAliasesActionTests.java:101)
```

Looks like it's probably related to #67409, /cc @pgomulka

**Comment by pgomulka** [comment]
great find @joegallo . This was failing because by accident I made ParsedMediaType mutable. It was meant to be immutable from the start.
The failure was occurring when some test was modifying `XContentType.mediaType` instance by adding a `charset=utf-8` (any test that is using AbstractRestChannel could do this). The RestGetAliasesActionTests was then using XContentType.JSON which is not meant to return charset=utf-8 anymore
