### ISSUE TITLE
Otherwise-successful build failed to generate tarball of output files, missing a gc.log.

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#67596]
**Build scan**: https://gradle-enterprise.elastic.co/s/dppt5odp5n75y/console-log?anchor=3256

**Repro line**: Not available.

**Reproduces locally?**: Not sure how I'd even try, this looks to be CI-specific.

**Applicable branches**: Seen on `master`.

**Failure history**: No idea how to search for this in build stats, it's not a failing test.

**Failure excerpt**:

```

build complete, generating: /dev/shm/elastic+elasticsearch+master+multijob+fast+part2/build/4017.tar.bz2 |  
-- | --
  |   |  
  | FAILURE: Build failed with an exception. |  
  |   |  
  | * What went wrong: |  
  | Execution failed for task ':x-pack:plugin:repositories-metering-api:qa:azure:integTest'. |  
  | > java.nio.file.NoSuchFileException: /dev/shm/elastic+elasticsearch+master+multijob+fast+part2/distribution/archives/linux-tar/build/install/elasticsearch-8.0.0-SNAPSHOT/logs/gc.log.09
```

**Comment by DaveCTurner** [comment]
For the record I feel bad submitting such an information-free bug report, I just don't know what else to include 😕

**Comment by mark-vieira** [comment]
Interesting, we shouldn't be writing _any_ log files to that folder as it's the original distribution location which we hardlink from. I think the gc log location is configured special though, since it's a JVM bootstrap type deal. It's possible we aren't correctly overriding this in test clusters.

This looks to be the first time this has ever happened ([failure history](https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=all_failures&failures.failureMessage=Execution%20failed%20for%20task%20%27*%27.%0A%3E%20java.nio.file.NoSuchFileException:%20*/logs/*&search.relativeStartTime=P28D&search.timeZoneId=America/Los_Angeles)) so let's keep an eye on this for now.

**Comment by mark-vieira** [comment]
This has only happened the one time so I'm apt to close this issue and blame it on sunspots.
