### ISSUE TITLE
[6.8] Support ES7.x get the totalHits

### ISSUE THREAD

**Issue by daishuai** [elastic/elasticsearch#67963]
Our project has many sites, some sites use ES6.x, some sites use ES7.x. It is a lot of work to upgrade all the site ES to a unified version. We tried to use 6.8ES client To be compatible with ES6.x and ES7.x. But we found a problem is that the ES6.8 client can not get the total number of matches to query ES7.x. So I hope you can be compatible.

**Comment by DaveCTurner** [comment]
This feature already exists, so no action is needed: the change to the hits object is [documented as a breaking change](https://www.elastic.co/guide/en/elasticsearch/reference/7.0/breaking-changes-7.0.html#hits-total-now-object-search-response) and those docs include instructions for recovering the 6.x behaviour in 7.x.

Since this is more of a user question than a feature request we'd rather not discuss it further here, but please feel free to continue this conversation on the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). As no action is needed I am closing this issue.
