### ISSUE TITLE
Dirty reads in elasticsearch

### ISSUE THREAD

**Issue by niladriforu** [elastic/elasticsearch#68031]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.3

**Plugins installed**: [] Kibana

**JVM version** (`java -version`): Dont know

**OS version** (`uname -a` if on a Unix-like system): Dont know

**Description of the problem including expected versus actual behavior**:
We have eleasticsearch as our primary data store. We write data into elasticsearch by reading a AWS SQS through lambda.
Once we get a 200 response to a post call, we prepare and send out AWS SNS notification. The notification contains a message ( what values changed ) and then a callback URL. 
Our refresh_interval is set as 1 sec at the index level. 
Recently, we have seen that when the consumers are doing this call back, they are reading the message within 1 sec ( < 1sec ) timeframe which is why, elasticsearch is sending them dirty reads. This is not happening all the time , it is difficult to reproduce it as well.  But it is happening only when the users are calling the endpoint and it is within that less than 1 second timeframe.

We have put a delay before sending the SNS notification and it is equal to 1 sec ( same as refresh interval ) for now. 
My question is  : 1. Is there a better way to confirm ES does not send stale data when consumers do a call back?

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Insert a record in elasticsearch.
 2. Instantenously send out a SNS event containing the call back URL.
 3. Add a SQS to this SNS , add a lambda to the SQS to read the message and call back the URL.

**Provide logs (if relevant)**:

**Comment by jtibshirani** [comment]
Hello @niladriforu, it's possible to force a refresh to be triggered as part of the actual write using the [`?refresh` parameter](https://www.elastic.co/guide/en/elasticsearch/reference/6.3/docs-refresh.html). The docs for that parameter describe some  trade-offs to consider when choosing if/ how to use it. (As a side note, I don't think these are 'dirty reads', since that usually means you've read uncommitted data? The readers just aren't seeing the latest document updates immediately.)

Hopefully that helps -- if you have more questions, I suggest you post to the [discussion forums](https://discuss.elastic.co/), since we try to reserve GitHub issues for development-related topics like bug reports.

**Comment by DaveCTurner** [comment]
As @jtibshirani says, this is more of a user question than a bug report, so the discussion forums are a better place to ask further questions. Therefore I am closing this.
