### ISSUE TITLE
[CI] PackageTests test90DoNotCloseStderrWhenQuiet on debian 9 on master

### ISSUE THREAD

**Issue by albertzaharovits** [elastic/elasticsearch#68043]
```
java.lang.AssertionError:
    Expected: a string containing "Failed to load settings from [elasticsearch.yml]"
         but: was "-- Logs begin at Wed 2021-01-27 09:04:57 UTC, end at Wed 2021-01-27 09:11:02 UTC. --"
        at __randomizedtesting.SeedInfo.seed([7E631C65A66D4D36:A155FE0A10CBB237]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.packaging.test.PackageTests.lambda$test90DoNotCloseStderrWhenQuiet$1(PackageTests.java:366)
        at org.elasticsearch.packaging.test.PackagingTestCase.withCustomConfig(PackagingTestCase.java:451)
        at org.elasticsearch.packaging.test.PackageTests.test90DoNotCloseStderrWhenQuiet(PackageTests.java:357)
```

Fails very rarely:
* [latest failure](https://gradle-enterprise.elastic.co/s/nlxn4z2gpwhdi)
* [all failures](https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Europe/Bucharest&tests.container=org.elasticsearch.packaging.test.PackageTests&tests.sortField=FAILED&tests.test=test90DoNotCloseStderrWhenQuiet&tests.unstableOnly=true)

**Comment by mark-vieira** [comment]
@pugnascotia I think this is another issue with us not waiting.

https://github.com/elastic/elasticsearch/blob/0cd4863585c593f97e0d2759d67b865014b58f53/qa/os/src/test/java/org/elasticsearch/packaging/test/PackageTests.java#L352

Would a fix here be to run w/o daemonization (since we expect it to exit on its own when it hits the error)?

**Comment by mark-vieira** [comment]
Nvm, that won't work in this instance since this is a deb package test so we can only run w/ daemon. I think we'll need to restructure this test somehow. There's no simple way to guarantee that the server attempted to start then died as we execute this now.

@breskeby This is where async stuff like the `waitFor` assertions used in Geb would be super useful. Is there any kind of standalone library that provides that kind of functionality that can be used in Java unit tests?

**Comment by pugnascotia** [comment]
We have `assertBusy` and others in `ESTestCase` already. While that isn't currently visible to the packaging tests, we could make it visible or copy/paste.

**Comment by mark-vieira** [comment]
Yeah, I think specifically for very asynchronous service stuff like this it would be helpful to have such a utility. @pugnascotia do you mind picking this one up?
