### ISSUE TITLE
Packaging test failures QuotaAwareFsTests.test30ElasticsearchStartsWhenSystemPropertySet

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#68436]
it looks like it is failing once every second day, every 3days..

**Build scan**:
https://gradle-enterprise.elastic.co/s/4ga2g62zrnigq

**Repro line**:

**Reproduces locally?**:
I did not managed to reproduce this locally. I had vagrant issues..

**Applicable branches**:
master
7.x
7.11

**Failure history**:
https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-1y,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:test30ElasticsearchStartsWhenSystemPropertySet),sort:!(process.time-start,desc))

failing sporadically since creation

**Failure excerpt**:
10:34:09   2> org.elasticsearch.packaging.util.Shell$ShellException: Command was not successful: [bash -c kill -SIGTERM 37218 && tail --pid=37218 -f /dev/null]
10:34:09        result: exitCode = [1] stdout = [] stderr = [bash: line 0: kill: (37218) - No such process]
10:34:09         at __randomizedtesting.SeedInfo.seed([D30AF9179FF8783A:7B3E75CF124D93E]:0)
10:34:09         at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:147)
10:34:09         at org.elasticsearch.packaging.util.Shell.run(Shell.java:73)
10:34:09         at org.elasticsearch.packaging.util.Archives.lambda$stopElasticsearch$9(Archives.java:386)
10:34:09         at org.elasticsearch.packaging.util.Platforms.onLinux(Platforms.java:63)
10:34:09         at org.elasticsearch.packaging.util.Archives.stopElasticsearch(Archives.java:386)
10:34:09         at org.elasticsearch.packaging.test.PackagingTestCase.stopElasticsearch(PackagingTestCase.java:309)
10:34:09         at org.elasticsearch.packaging.test.QuotaAwareFsTests.test30ElasticsearchStartsWhenSystemPropertySet(QuotaAwareFsTests.java:139)

**Comment by mark-vieira** [comment]
Indeed, this is happening nearly [once a day it seems](https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.rootProjectNames=elasticsearch&search.tags=CI&search.tags=not:pull-request&search.timeZoneId=America/Los_Angeles&tests.container=org.elasticsearch.packaging.test.QuotaAwareFsTests&tests.disabledDistributions=WyJvdXRjb21lOnBhc3NlZCIsIm91dGNvbWU6c2tpcHBlZCJd&tests.sortField=FAILED&tests.test=test30ElasticsearchStartsWhenSystemPropertySet&tests.unstableOnly=true).

@pugnascotia Are we not waiting long enough before trying to kill the process or are we otherwise using the wrong pid here?

**Comment by pugnascotia** [comment]
I'm not entirely sure what's going on here, but I've created #68515 to try to make the test more robust. Hopefully if it continues to fail, we'll have more insight about why.
