### ISSUE TITLE
whitelist domainSplit function in the Ingest Context

### ISSUE THREAD

**Issue by immon** [elastic/elasticsearch#68510]
[domainSplit](https://www.elastic.co/guide/en/elasticsearch/painless/7.11/painless-api-reference-field.html#_static_methods) painless method is available in Field Context only.

Could we expose it in the Ingest context?

**Comment by jdconrad** [comment]
Moving this to the discuss category. This is harder than it seems because the code for domainSplit is a whitelist extension from the MachineLearning plugin. I see our options as the following:
1. Move domainSplit into the PainlessPlugin (I didn't see it used anywhere outside of Painless in the ML Plugin.)
2. Add the whitelist to the ingest context from the ML Plugin.

**Comment by stu-elastic** [comment]
This is the same as: https://github.com/elastic/elasticsearch/issues/71946, we agreed to add it to the core whitelists.
