### ISSUE TITLE
Extend data transform max frequency to 24 hours

### ISSUE THREAD

**Issue by mbudge** [elastic/elasticsearch#68511]
Hi,

Any chance we can increase the max frequency to 24 hours?

The way we use transforms the buckets always change, so the transform re-computes a lot of data every time they run. 

This isn't a massive issue, but it would be good if we could run the transform less often.

Thanks

**Comment by hendrikmuhs** [comment]
@mbudge

This is definitely planned, but more than just opening the parameter. The so-called transform scheduler right now serves 2 purposes:

 - scheduling when to run the transform next, aka `frequency`
 - retry in error cases

That's unfortunate, if we allow `frequency` to be set to `24h`, it would also mean that transform will wait 24 hours until it retries after a failure. We don't want this and that's why we limited `frequency`.

So the 1st task to implement better scheduling is decoupling retry and scheduling. This will open a lot of other possibilities, e.g. we want to allow users to schedule transform e.g. to run at offline hours. It seems like this could be interesting for you as well.

I can't give you a concrete timeline, but can only say: we have it on the radar, its one of the top asks.

**Comment by mbudge** [comment]
@hendrikmuhs

No rush, sounds like these features will be worth the wait. 

Running transforms during offline hours would be really cool. 

Thanks
