### ISSUE TITLE
[CI] CachingUsernamePasswordRealmTests testReadsDoNotPreventCacheExpiry

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#68661]
**Build scan**:
https://gradle-enterprise.elastic.co/s/ipe6wa4eqlnbu

**Repro line**:
```
./gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.xpack.security.authc.support.CachingUsernamePasswordRealmTests.testReadsDoNotPreventCacheExpiry" \
  -Dtests.seed=1676BE1899CEFFAF \
  -Dtests.security.manager=true \
  -Dtests.locale=ro \
  -Dtests.timezone=Asia/Kabul \
  -Druntime.java=8
```

**Reproduces locally?**:
No

**Applicable branches**:
7.x

**Failure history**:
First occurrence 

**Failure excerpt**:
```
java.lang.AssertionError: 
Expected: not sameInstance(<User[username=the-user,roles=[testRole1,testRole2],fullName=null,email=null,metadata={}]>)
     but: was <User[username=the-user,roles=[testRole1,testRole2],fullName=null,email=null,metadata={}]>
	at __randomizedtesting.SeedInfo.seed([1676BE1899CEFFAF:29A5126E116B6447]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.security.authc.support.CachingUsernamePasswordRealmTests.testReadsDoNotPreventCacheExpiry(CachingUsernamePasswordRealmTests.java:348)
```

**Comment by ywangd** [comment]
This is a very rare failure. Only [failed once in the last year](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-1y,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testReadsDoNotPreventCacheExpiry),sort:!(process.time-start,desc))). It is probably a very edge-case timing issue with the test code. 

The cache TTL is 250 ms. So the 3rd read (authentication) at 300 ms should not read from the cache but instead perform the actual authentication again. However, in this very edge-case scenario, the cache didn't expire in time. I am not entirely clear on how it could happen. But since there is a mixed usage of `System.nanoTime`, `System.currentTimeMillis`, `Thread.sleep` between the main code and test code, it might be possible that somewhere timing is not aligned. 

We could bump the TTL to make the test a bit more robust(while also take longer). But since this failure is rare enough, I am closing it without further action.
