### ISSUE TITLE
YamlRestCompatTestPluginFuncTest failures

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#68973]
**Build scan**:
https://gradle-enterprise.elastic.co/s/b2piszuxr2vay

**Repro line**:
./gradlew :build-tools:integTest

**Reproduces locally?**:
no

**Applicable branches**:
master

**Failure history**:
https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:YamlRestCompatTestPluginFuncTest),sort:!(process.time-start,desc))

fails since 11.02

**Failure excerpt**:
Condition not satisfied:

result.task(transformTask).outcome == TaskOutcome.UP_TO_DATE
|      |    |              |       |  |
|      |    |              SUCCESS |  class org.gradle.testkit.runner.TaskOutcome
|      |    :transformV7RestTests  false
|      :transformV7RestTests=SUCCESS
<org.gradle.testkit.runner.internal.FeatureCheckBuildResult@699c1f0 delegateBuildResult=org.gradle.testkit.runner.internal.DefaultBuildResult@629bbdc9 outputFeatureCheck=org.gradle.testkit.runner.internal.feature.BuildResultOutputFeatureCheck@482cd4c3>
Stacktrace

**Comment by jakelandis** [comment]
I bumped the log level over on #69000, and found [this](https://gradle-enterprise.elastic.co/s/dujmgkt57f6jy/tests/:build-tools:integTest/org.elasticsearch.gradle.YamlRestCompatTestPluginFuncTest/transform%20task%20executes%20and%20works%20as%20configured?focused-output-line=0-154#1) as the reason for the not up-to-date:
```
> Task :transformV7RestTests	
Caching disabled for task ':transformV7RestTests' because:	
  Build cache is disabled	
Task ':transformV7RestTests' is not up-to-date because:	
  Value of input property 'transformations.org.elasticsearch.gradle.test.rest.transform.headers.InjectHeaders$0.headers' has changed for task ':transformV7RestTests'	
:transformV7RestTests (Thread[Execution worker for ':' Thread 16,5,main]) completed. Took 0.103 secs.
```

Since headers is Map<String, String> I would wager that the serialization between invocations doesn't equal each other properly in some cases.

**Comment by jakelandis** [comment]
PR submitted #69011

Also, any [tests failures](https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=America/Chicago&tests.container=org.elasticsearch.gradle.YamlRestCompatTestPluginFuncTest&tests.expandedTests=WzBd&tests.sortField=FAILED&tests.test=transform%20task%20executes%20and%20works%20as%20configured&tests.unstableOnly=true) since this #69000 has been merged should show the reason for failure.
