### ISSUE TITLE
[CI] TransformInternalIndexIT.testUpdateDeletesOldTransformConfig

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#69057]
**Build scan**: https://gradle-enterprise.elastic.co/s/qvjg4l7qfqdxq 

**Repro line**: 
```
./gradlew ':x-pack:plugin:transform:internalClusterTest' --tests "org.elasticsearch.xpack.transform.integration.TransformInternalIndexIT.testUpdateDeletesOldTransformConfig" \
  -Dtests.seed=180F5806D3F6A363 \
  -Dtests.security.manager=true \
  -Dtests.locale=hi \
  -Dtests.timezone=Europe/Volgograd \
  -Druntime.java=11 \
  -Dtests.fips.enabled=true
```

**Reproduces locally?**: no

**Applicable branches**: `7.12`

**Failure history**:

**Failure excerpt**:

```
java.lang.AssertionError: test leaves indices that were not deleted: .transform-notifications-000002
Expected: []
     but: was [".transform-notifications-000002"]
	at __randomizedtesting.SeedInfo.seed([180F5806D3F6A363:75F6F23A53C81E91]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.elasticsearch.test.ESSingleNodeTestCase.tearDown(ESSingleNodeTestCase.java:134)
```

**Comment by hendrikmuhs** [comment]
This seems to be a weakness in `ESSingleNodeTestCase`

When teardown is run, an index is initializing, so the delete call does _not_ include it:

This message shows the shard initialization:
```
16:28:09   1> [2021-02-16T19:28:08,465][INFO ][o.e.c.r.a.AllocationService] [node_s_0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[.transform-notifications-000002][0]]]).
```

but this message is _after_ the test is already deleting indices:

```
16:28:09   1> [2021-02-16T19:28:08,238][INFO ][o.e.c.m.MetadataDeleteIndexService] [node_s_0] [.transform-internal-001/yG-HhVHuSp-OdgPQskwkIg] deleting index
16:28:09   1> [2021-02-16T19:28:08,239][INFO ][o.e.c.m.MetadataDeleteIndexService] [node_s_0] [transform-index-deletes-old/tIb4lwATTmijfRYNxL73kg] deleting index
16:28:09   1> [2021-02-16T19:28:08,239][INFO ][o.e.c.m.MetadataDeleteIndexService] [node_s_0] [.transform-internal-006/BNu6CXqJSbeFm3nK3uch1w] deleting index
```

`ESRestTestCase` has a method called `ensureNoInitializingShards` for that reason, it is called before running the teardown. I think we should add the same to `ESSingleNodeTestCase`.

**Comment by dimitris-athanasiou** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/pvyzesawuecto

**Comment by matriv** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/sthnt7j7vleza

**Comment by matriv** [comment]
7.x failure: https://gradle-enterprise.elastic.co/s/y7g4tjnrvekuw

**Comment by henningandersen** [comment]
Looks like this still fails with same error in:

https://gradle-enterprise.elastic.co/s/pysgbxwlswsqq

```
java.lang.AssertionError: test leaves indices that were not deleted: .transform-notifications-000002
```

based on commit: 1430e5266989e4afdbe27fac2802c7e78a5439c9, which includes #69419.

**Comment by droberts195** [comment]
I have an idea for what this is.  In the REST tests we wait for pending tasks before deleting indices: https://github.com/elastic/elasticsearch/blob/26eef892df98e66e4f2fbe61674d92a8c065fee6/x-pack/plugin/src/test/java/org/elasticsearch/xpack/test/rest/AbstractXPackRestTest.java#L207

One of the reasons we had to add that was because of the way an async side effect of deleting an ML job is to write a notification to the notifications index, and that could end up creating the index after it had been deleted by the end-of-test cleanup.

I expect the same is true of deleting a transform.  If so what's happening is that `.transform-notifications-000002` _is_ getting deleted by the end-of-test cleanup, but then sometimes gets recreated in between that and the check of whether the test left indices behind.

So when I moved `testUpdateDeletesOldTransformConfig` from being a REST test to being an internal cluster test I needed to copy the "wait for pending tasks" bit to the internal cluster test cleanup, but didn't.  However, since this single test seems to be the only one that actually needs this functionality, it's probably better to add it as a bespoke `@After` method for this particular test file, so that it doesn't slow down other tests.  I will try that.

**Comment by droberts195** [comment]
> I expect the same is true of updating a transform.

Yes, it's in: https://github.com/elastic/elasticsearch/blob/9d681937d5ad2afe94291ca3f5af43c1cb01e1ec/x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportUpdateTransformAction.java#L331
