### ISSUE TITLE
The components on which ElasticSearch depends may contain vulnerabilities. If yes, fix them.

### ISSUE THREAD

**Issue by crazyinner** [elastic/elasticsearch#69247]
In ElasticSearch 7.3.1 contains apache-httpclient(version: 4.5.3/4.5.8) elasticsearch(version: 7.3.1) and cryptacular(version:1.1.). There are many vulnerabilities, like CVE-2020-13956,CVE-2020-7009,CVE-2020-7014,CVE-2020-7019,CVE-2020-7020,CVE-2019-7619,CVE-2020-7226 etc. please confirm these version and fix. thx

**Comment by jasontedor** [comment]
Please email security@elastic.co.

**Comment by Archcry** [comment]
I am having the same issue and I think it's hard to track this issue for people like me because we don't know whether the email was actually send to security@elastic.co. May I ask why this is necessary? I cannot find it in the [contributing guidelines](https://github.com/elastic/elasticsearch/blob/ef24722b11efee33f28a747740fba03c8dcd186a/CONTRIBUTING.md).

**Comment by fengnian7** [comment]
In 2021, there are some vulnerabilities, like CVE-2019-7614,CVE-2021-22132,CVE-2021-22134,CVE-2021-22135,CVE-2021-22137.
