### ISSUE TITLE
The clone index API is not truly a clone from a metadata perspective

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#69490]
Currently the clone index API does hard links of segment files while also copying the settings from an index into an entirely new index. From an outside perspective this is indeed a clone (since the data is all the same), however, it is not actually a clone of the index's metadata.

We do not copy the metadata (especially the `custom` index metadata) when cloning an index. For example, if an index is currently has the `hot/rollover/check-rollover-ready` execution state in its metadata, when the index is cloned, this information is missing, meaning that the newly created index starts over at the `new/init/init` ILM execution step.

We should either do a full clone of an index including its full metadata, or document this¹ as a byproduct of the clone process.

----------
¹ there are probably things outside of ILM that differ as well, it was just an easier one to think about, so if we choose documentation then we'll need to figure out exactly how else it can differ.

**Comment by DaveCTurner** [comment]
You're correct that a clone is not an exact copy, there are various things that need to be changed (e.g. the index UUID and the in-sync allocation IDs) so we definitely don't aim for a 100% faithful copy. We do copy things like mappings and settings, except of course those marked as `NotCopyableOnResize` since a clone is just a special kind of resize. That leaves a few other things:

- Aliases
- Rollover info
- System index flag
- Custom metadata

There's some facility for setting aliases during the clone, I'd need to dig deeper to see exactly what gets copied there.

I don't think we copy rollover info or the system index flag at all, I hold no opinion about whether it makes sense to copy that or not, but if it does make sense then that can be added. It probably makes sense for the folks who look after these features to look into this.

Custom metadata is used today by CCR and ILM. By dropping the CCR metadata the clone will not be a CCR follower even if the source index was, which feels to me like the right thing to do, although I agree this deserves a note in the docs.

I don't hold any opinion about cloning the ILM custom metadata either - it sounds like you would like this to be copied, and that's definitely something that can be done. Should it be an exact copy or does it need any manipulation on the way through?

**Comment by dakrone** [comment]
> I don't hold any opinion about cloning the ILM custom metadata either - it sounds like you would like this to be copied, and that's definitely something that can be done. Should it be an exact copy or does it need any manipulation on the way through?

I think the ILM metadata is only useful if we also copy the aliases and probably the rollover info (since those can affect how ILM manages the index).

I'm not 100% sure that we should copy the ILM things, it may be entirely valid to just document it. I guess in order to tell we need to determine what the goal of the clone API is, is it just to copy the "form" of the index into a new index along with its data? Is it intended to be closer to a clone so that a user can clone an index and perform operations on it that would behave similar to the original index?

**Comment by DaveCTurner** [comment]
Sorry for the delay in responding @dakrone, I missed your subsequent reply, but then we (@elastic/es-distributed) discussed this today in our team sync.

We think of the clone API as a fairly low-level primitive that lets you cheaply capture the contents of an index at a point in time, isolating it from changes to the original index. As a primitive, we don't expect it to have much intelligence of its own, and therefore we think it makes sense to drop various bits of the index metadata and in particular to detach the resulting clone from the ILM and CCR config of the original. Spelling that out in the docs would be good.

**Comment by dakrone** [comment]
Sounds good, I'll remove the 'bug' label and mark this as 'docs' then. Thanks for discussing as a team so we have clarification on this.
