### ISSUE TITLE
Support GETing a document from an alias

### ISSUE THREAD

**Issue by mitar** [elastic/elasticsearch#69649]
I am trying to [get](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-get.html) a document from an alias which contains multiple indices. I am surprised to get error:

```
alias [pipelines] has more than one indices associated with it [[pipelines_20200304, pipelines_202002, pipelines_20200527, pipelines_20200702]], can't execute a single index op
```

I can understand that this can be a problem if document with same ID exists in multiple indices, but I would suggest only then an error is raised. But if document exists in only one index in an alias, please just return that document. This is now what I have to manually do.

The reason why this is useful is because then I can easily use ES as a simple HTTP GET API to fetch documents by ID. Otherwise I have to do a search which does not just return the document. In fact, I am mostly interested in `_source` GET request, to get the source of the document by ID.

**Comment by pgomulka** [comment]
I feel you already have a workaround and your reasoning why we don't support is correct.
But I will ask the Search team to find out if that enhancement would be considered at all

**Comment by javanna** [comment]
The problem here is that Elasticsearch cannot know that only one index contains that document that you are looking for. Rather, the get API is a single index operation, meaning that it goes to a single shard. Which shard it goes to is determined by the index and the id of the document. If the index is an alias that points to multiple indices, simply the get cannot be executed to start with, because Elasticsearch does not know which specific node/shard to direct the request to.

**Comment by javanna** [comment]
I think that using search instead of get is the right solution, or rather get directly from a single index or an alias pointing to a single index. I could not follow the reasoning around _source, as documents and their _source are also returned by  the search API. I think we could help with this in our forums at https://discuss.elastic.co/

**Comment by mitar** [comment]
> I feel you already have a workaround and your reasoning why we don't support is correct.

The workaround does not work. I cannot do `<a href` to link to the document. I have to manually inspect the list I get in an error. Why this cannot be done automatically?

> If the index is an alias that points to multiple indices, simply the get cannot be executed to start with, because Elasticsearch does not know which specific node/shard to direct the request to.

So it could do a search and return if and only if one document is found?

> I think that using search instead of get is the right solution

But you cannot get only `_source` of the document using search. Like you can with the `_source` GET request.

> and their _source are also returned by the search API

But `_source` is nested among `_index`, `_type`, `_id` and `_score` fields. Others have [the same issue](https://stackoverflow.com/questions/28303134/return-only-source-from-a-search).
