### ISSUE TITLE
elastic rollup jobs are not triggered periodically

### ISSUE THREAD

**Issue by Amruta54** [elastic/elasticsearch#69647]
This is my post_job request: and start job request: job has to be scheduled for every 2 m to rollup 2m

PUT _rollup/job/rollup2try4
{
    "index_pattern": "enrichedflowmetricsdb-*",
    "rollup_index": "rollupflowmetricsdb-2min-fourthtry",
    "cron": "* */2 * * * ?",
    "page_size": 10000,
    "groups": {
        "date_histogram": {
            "field": "timestamp",
            "interval": "2m"
        },
        "terms": {
            "fields": [
                "flowId"
            ]
        }
    },
    "metrics": [
        {   
            "field": "rdMaxECTPerIO",
            "metrics": [
                "max"
            ]
        },
        {   
            "field": "wrMaxECTPerIO",
            "metrics": [
                "max"
            ]
        },
        {   
            "field": "rdAvgIOPs",
            "metrics": [
                "avg"
            ]
        },
        {   
            "field": "wrAvgIOPs",
            "metrics": [
                "avg"
            ]
        }
    ]
    }

POST _rollup/job/rollup2try4/_start

Rollup happened only once with older timestamp. Unable to debug issue

Snapshot of rolled up entry:
        "_source": {
          "flowId.terms._count": 217,
          "flowId.terms.value": 116,
          "rdAvgIOPs.avg._count": 217,
          "wrAvgIOPs.avg._count": 217,
          "timestamp.date_histogram.time_zone": "UTC",
          "wrAvgIOPs.avg.value": 0,
          "timestamp.date_histogram.timestamp": 1614240000,
          "rdMaxECTPerIO.max.value": 0,
          "rdAvgIOPs.avg.value": 0,
          "_rollup.version": 2,
          "wrMaxECTPerIO.max.value": 0,
          "timestamp.date_histogram.interval": "2m",
          "timestamp.date_histogram._count": 217,
          "_rollup.id": "rollup2try4"
        }
Snapshot of current entry timestamp:
        "_source": {
          "flowId": 116,
          "rdAvgDALPerIO": 40169243,
          "rdAvgECTPerIO": 44479989,
          "rdAvgThput": 42100122,
          "rdMaxDALPerIO": 0,
          "rdMaxECTPerIO": 0,
          "rdPeakIOThput": 8216,
          "timestamp": 1614315113,

**Comment by wchaparro** [comment]
With the 8.7 release of Elasticsearch, we have made a [new downsampling capability](https://www.elastic.co/guide/en/elasticsearch/reference/current/downsampling.html) associated with the new [time series datastreams](https://www.elastic.co/guide/en/elasticsearch/reference/current/tsds.html) functionality generally available (GA). This capability was in tech preview in ILM since 8.5.  Downsampling provides a method to reduce the footprint of your time series data by storing it at reduced granularity. The downsampling process rolls up documents within a fixed time interval into a single summary document. Each summary document includes statistical representations of the original data: the min, max, sum, value_count, and average for each metric. Data stream time series dimensions are stored unchanged. 

Downsampling is superior to rollup because:
Downsampled indices are searched through the _search API
It is possible to query multiple downsampled indices together with raw data indices
The pre-aggregation is based on the metrics and time series definitions in the index mapping so very little configuration is required (i.e. much easier to add new time serieses)
Downsampling is managed as an action in ILM
It is possible to downsample a downsampled index, and reduce granularity as the index ages
The performance of the pre-aggregation process is superior in downsampling, as it builds on the time_series index mode infrastructure

Because of the introduction of this new capability, we are deprecating the rollups functionality, which never left the Tech Preview/Experimental status, in favor of downsampling and thus we are closing this issue. We encourage you to migrate your solution to downsampling and take advantage of the new TSDB functionality.
