### ISSUE TITLE
Provide per-analyzer "matched_queries" results in cross_fields hits

### ISSUE THREAD

**Issue by nemphys** [elastic/elasticsearch#69664]
As explained here https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html#cross-field-analysis, when the specified fields in a cross_fields mutli-match query have different analyzers, they are divided into groups according to their analyzer under the hood.

This is fine and saves the user the trouble of hand-crafting the separate per-analyzer queries (which is what I was doing for the past few years until today, when I realized that this is now built in).

The thing is, in my use case, I need to know which analyzer-group was matched against each hit. I have been achieving this using named queries (providing names to each of the already uses per-analyzer query). It would be great if I could somehow keep this functionality while greatly simplifying the final query.

The "matched_queries" field in the hits (or some new hit field maybe?, though I guess that would be an overkill) could include the main query name (if provided), with the analyzer (or analyzers) that were matched as a suffix, eg:
If the main query has a name of "x" and analyzers "a" and "b" were both matched for a hit, the "matched_queries" field could be [ "x.a", "x.b" ].

This also applies to the new combined_fields multi_match queries (https://github.com/elastic/elasticsearch/pull/69482).

**Comment by jtibshirani** [comment]
Thanks @nemphys for raising this and taking a look at our work on combined-field scoring. We discussed this as a team and decided not to support it. We consider the automatic analyzer grouping to be a lenient 'workaround' and may not support it by default in new modes/ queries. For this reason, I think it's best not to add enhancements to it, especially since (as you mentioned) there's a way to accomplish this behavior already by performing the grouping manually and adding named queries.
