### ISSUE TITLE
Provide means for running "initialization scripts" in Docker container

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#69840]
While having discussions with the Cloud team we encountered a number of places where custom logic is needed for Cloud deployments. Some of these things are fairly Cloud-specific and don't necessarily need to be "owned" by the stack teams or be handled by the vanilla Docker image. Instead we need a more standard approach for injecting these customization into the container. I'll quote what I said in the email thread below.

What we really want is a clear defined interface with which Cloud can integrate with. Right now these things aren't clear, and as a result, we break things. So something along the lines of:

1. If you want something to run before ES starts, drop it in this location and the docker entrypoint script will ensure it's executed.
2. These scripts should only touch certain stuff, and we should enforce that to the degree which is practical.
3. The utilities we expose should have certain compatibility guarantees, at least within minor versions.

This capability should be considered a first-class citizen, which means we'll want to publicly document it as well as potentially have some level of BWC testing here to confirm we don't break these guarantees.

**Comment by alpar-t** [comment]
Relates to https://github.com/elastic/dev/issues/1578

**Comment by alpar-t** [comment]
Could we make the location of the script configurable e.g via an ENV var? Or maybe that could be the means to enable the functionality. This way we could e.g. re-use an existing bind mount for passing it in.

**Comment by pugnascotia** [comment]
I have a proof-of-concept on a branch:

https://github.com/elastic/elasticsearch/compare/master...pugnascotia:docker-initd-support?w=1

**Comment by jasontedor** [comment]
I concerned about a general mechanism for providing initialization scripts.  I see that you allude to some of the potential issues here:

>These scripts should only touch certain stuff, and we should enforce that to the degree which is practical.

>The utilities we expose should have certain compatibility guarantees, at least within minor versions.

I think that we need to put really strict limits on what the scripts can do, otherwise the scripts will end up depending upon the internals of the container, which has already caused us some specific problems as dependencies inside the container change (e.g., `wget`). I don't want to encourage nor support that kind of dependency. I also don't want to limit our ability to evolve.

I am aware that the initialization script proposal is inspired by some existing mechanisms that are out there, for example I see that the Docker Library (but not necessarily the official) MongoDB, MySQL, and [Postgres](https://github.com/docker-library/docs/blob/bb33862471fefcaf863f7c5eb6bdf61148d70e72/postgres/README.md#initialization-scripts) images offer support for this. However, by my reading, those scripts are largely intended for initializing the database which is not really the case here.

I still find it to be a weird usage, since it implies the containers aren't immutable.

**Comment by alpar-t** [comment]
++ to not depend on container internals, that's something we discussed with Mark too. (e.g. doing something like `PATH=$ES_HOME/bin` for these scripts).  Permissions can also be set in the image in a way which would encourage container immutability to make sure that scripts can't write to locations that are not meant to be written to (these would be the same ones for which we would suggest using volumes of bind mounts). 

I'm not trying to argue in favor of the approach, just adding data points. I think that the "degree to which is practical"  is along the lines of encouraging the usage we want, but enforcing it will be a more difficult problem to solve. E.g. the script could still change PATH, add permissions etc to circumvent that so I can understand if it's still not something we feel comfortable with.

**Comment by pugnascotia** [comment]
Is this issue still valid? We're tending towards building support into the image for specific use-cases that we actually want to support.

**Comment by mark-vieira** [comment]
I'm apt to say "no" here. We want to provide declarative means for these use cases. I'm going to close this for now. If we need to open it again we should start with a new issue that's more use-case driven.
