### ISSUE TITLE
Field caps api - return `format` for date fields

### ISSUE THREAD

**Issue by mattkime** [elastic/elasticsearch#69892]
Addressing https://github.com/elastic/kibana/issues/93401

There are cases where kibana needs to format queries involving dates in the `format` stored in the mapping. Unfortunately right now kibana doesn't have a way to get this info. Can it be provided?

**Comment by jimczi** [comment]
I think it should be the other way around. Kibana translates dates coming from the mapping into a common format so any query that uses this output should be provided with the translated format. So instead of building a match_phrase query for date fields, Kibana should build a range query that specifies the format of the date that was used to format the value in Kibana.
That's how it works currently since range query wouldn't work otherwise but this needs to be consistent even when you filter on an exact match on a date field.

**Comment by jimczi** [comment]
Closing as the solution is to always provide the format in the range query directly.
