### ISSUE TITLE
[CI] ApiKeyServiceTests > testAuthenticateWhileCacheBeingPopulated FAILED

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#70160]
**Build scan**:

https://gradle-enterprise.elastic.co/s/liad6qmj46k7k

**Repro line**:

./gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.xpack.security.authc.ApiKeyServiceTests.testAuthenticateWhileCacheBeingPopulated" -Dtests.seed=E213CEE870B914B1 -Dtests.security.manager=true -Dtests.locale=mt -Dtests.timezone=Etc/Universal -Druntime.java=8

**Reproduces locally?**:

No

**Applicable branches**:

7.x

**Failure history**:

Found similar looking timeouts two times in January on 7.x and 7.10
https://gradle-enterprise.elastic.co/s/uhjyjjtowngzm
https://gradle-enterprise.elastic.co/s/xxzuf2mgb7rco

**Failure excerpt**:

```
org.elasticsearch.xpack.security.authc.ApiKeyServiceTests > testAuthenticateWhileCacheBeingPopulated FAILED
    ElasticsearchTimeoutException[java.util.concurrent.TimeoutException: Timeout waiting for task.]; nested: TimeoutException[Timeout waiting for task.];
        at __randomizedtesting.SeedInfo.seed([E213CEE870B914B1:743856BB2F6D0B29]:0)
        at org.elasticsearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:67)
        at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:50)
        at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:44)
        at org.elasticsearch.xpack.security.authc.ApiKeyServiceTests.testAuthenticateWhileCacheBeingPopulated(ApiKeyServiceTests.java:702)
```

**Comment by ywangd** [comment]
This is likely a genuine flaky timeout issue. All threee failures are at the following line
```java
assertThat(future2.actionGet(TimeValue.timeValueMillis(100)).isAuthenticated(), is(true));
```
where it tries to assert that the 2nd authentication is successful. When that happens, it means the 1st authentication is confirmed to be successful. In theory, the 2nd authentication should be almost immediate once the 1st either passes or fails. But computers (or JVM) are hard. It might decide to do something else, e.g. GC, and paused the execution for a short time. Since we wait for only 100ms, in rare cases, it could time out. 

The [build-stats](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-1y,mode:quick,to:now))&_a=(columns:!(build.branch),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testAuthenticateWhileCacheBeingPopulated),sort:!(process.time-start,desc))) shows only 7 failures in the last year. So it is pretty rare. But it is interesting that it failed for the first time in November 2020, almost 10 months after it is introduced and since then it failed almost once every month. Maybe there was some change that made the "auth-with-cache" slower than before? But I cannot think of anything has been directly done to this cache around that time.

I think the simple fix is to just bump the wait time a bit more, maybe 2 seconds as the 1st auth. 99.99% time it will not wait for that long and if the long waiting time help eliminating this flakeness, I'd say it is a reasonable trade-off.
