### ISSUE TITLE
Refactor cat nodes api to use cgroups stats rather than getSystemCpuLoad

### ISSUE THREAD

**Issue by geekpete** [elastic/elasticsearch#70200]
A current JDK bug seems to sometimes affect the correctness of cat nodes api output for cpu usage in containerized environments, resulting in 100% cpu usage according to cat nodes API where OS metrics and nodes stats cpu metrics don't show cpu usage as 100%.

JDK bug: "OperatingSystemMXBean.getCpuLoad reports wrong numbers in containers"
https://bugs.openjdk.java.net/browse/JDK-8248215

For both consistency and to sidestep this particular JDK bug, could the cat nodes API be reimplemented to instead use cgroup CPU stats directly as other parts of the codebase already do:
https://github.com/elastic/elasticsearch/blob/feab123ba400b150f3dcd04dd27cf57474b70d5a/server/src/main/java/org/elasticsearch/monitor/os/OsProbe.java

rather than `getSystemCpuLoad`

Symptoms seem most prevalent on "busy" nodes in the cluster or nodes doing some sufficient amount of workload to trigger the problem in cat nodes output. Often seen where there are busy hot nodes in a hot/warm cluster where warm and other types of nodes don't show the 100% cpu usage in the cat nodes output.

**Comment by swallez** [comment]
This issue has been reported to the support team a number of times. Are there any plans to prioritize it?

**Comment by danhermann** [comment]
> This issue has been reported to the support team a number of times. Are there any plans to prioritize it?

It's not currently prioritized. If the JDK bug is not fixed for the JDK17 release, we may need to consider raising its priority.

**Comment by geekpete** [comment]
It appears this bug didn't make it into JDK17?
Would we now consider our own workaround for this or potentially wait a bit longer?

**Comment by stefnestor** [comment]
bump? 🙏🏼

**Comment by pugnascotia** [comment]
Do we know exactly how we'd use the cgroup stats here as a replacement? It wasn't obvious to be from reading the history.

**Comment by pugnascotia** [comment]
@henningandersen do you have any guidance for how we can use e.g. `cpu.stats` to compute a more accurate system load value?

**Comment by henningandersen** [comment]
@pugnascotia 

We could periodically grab an `OsStats.Cgroup` object (or parts of it), keeping the last two around. When asked for system load, we can calculate the load as:

`c2.cpuAcctUsageNanos - c1.cpuAcctUsageNanos / (period * cpuCfsQuotaMicros / 100000) / 1000000000`

The `period` could be 1s or 5-10s, might be worth measuring the overhead to come to that number.

**Comment by jigar82** [comment]
@henningandersen  I am sorry to ping this way but let me know if i confirm this some another way.  We have this issue open because of Java bug , Now i see that java bug has  below comment which mentions it should have fixed with Java 17 with two different ticket they implemented

https://bugs.openjdk.org/browse/JDK-8248215?focusedCommentId=14509980&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14509980

One of my customer was following this and just asked that is it safe to say its fixed ( node API) , they have observation that they do see now right CPU when they compare against container environment with ES 8.2 and Java 17

**Comment by masseyke** [comment]
Yes, the bug is fixed as of java 17.0.1. So it ought to work with the prepackaged JDKs in Elasticsearch versions 7.15.2+, 7.16.0+, and 8.0.0+ (and in other versions with a recent user-supplied JDK). I tested it out on a recent snapshot and it appears to be working as you'd expect. I'll leave this ticket open for the moment in case someone wants to make a case for changing the way we do this, but it's probably not worth it at the moment.
