### ISSUE TITLE
elasticsearch-oss images missing for 7.11.x+

### ISSUE THREAD

**Issue by dmivankov** [elastic/elasticsearch#70840]
```sh
docker pull docker.elastic.co/elasticsearch/elasticsearch-oss:7.11.2
Error response from daemon: manifest for docker.elastic.co/elasticsearch/elasticsearch-oss:7.11.2 not found: manifest unknown: manifest unknown
```
latest available is 7.10.2 https://www.docker.elastic.co/r/elasticsearch/elasticsearch-oss
while latest elasticsearch release is now 7.12.0 https://github.com/elastic/elasticsearch/releases

**Comment by mark-vieira** [comment]
Thanks for the issue @dmivankov, with recent [licensing changes](https://www.elastic.co/blog/licensing-change) to Elasticsearch beginning with the 7.11 release, we no longer publish an "oss" distribution. I suggest using the default distribution instead.

**Comment by xxorax** [comment]
The default distribution includes the not-free-for-use X-Pack (and maybe others ? I don't know it's all [blurry](https://github.com/elastic/elasticsearch/blob/v7.11.2/distribution/docker/build.gradle#L75)).

I like to know what I'm using.

Can we have a clear free-for-use version ?

**Comment by mark-vieira** [comment]
Everything included in the default distribution is free-for-use. Any non-free features will require you to provide a license as outlined in the [subscription model](https://www.elastic.co/subscriptions).

**Comment by xxorax** [comment]
I don't see in the doc what are precisely the features (API) I can use and what I cannot use without a license.

All the pages taggeg with X-Pack (like [this one](https://www.elastic.co/guide/en/elasticsearch/reference/current/authorization.html)) make me remember not so long time ago when we got an ES instance crashed because a trial license for X-Pack was **automaticaly generated**, and so expired after 30 days (even we didn't use X-Pack at all).

That's why we only use the oss version.

From the [Set up X-Pack page](https://www.elastic.co/guide/en/elasticsearch/reference/7.12/setup-xpack.html) :
> If you want to try all of the X-Pack features, you can start a 30-day trial. At the end of the trial period, you can purchase a subscription to keep using the full functionality of the X-Pack components. 

For exemple, in the subscription model page, any SAML feature is not included for free, however I see [no indication about this in the doc](https://www.elastic.co/guide/en/elasticsearch/reference/7.12/saml-guide-stack.html), no difference with [an other feature like File and native authentication](https://www.elastic.co/guide/en/elasticsearch/reference/7.12/file-realm.html), which is included for free.

Do all these clouds are intentional ? If not I think it needs clarifications.

After deep research I finaly end-up [with this](https://www.elastic.co/guide/en/elasticsearch/reference/7.12/license-settings.html) :
> xpack.license.self_generated.type
(Static) Set to basic (default) to enable basic X-Pack features.
If set to trial, the self-generated license gives access only to all the features of a x-pack for 30 days. You can later downgrade the cluster to a basic license if needed.

So I guess by default I have only access to the well free X-Pack features, which will remain free ? I'm just looking for the most stable thing as possible.

**Comment by mark-vieira** [comment]
> So I guess by default I have only access to the well free X-Pack features, which will remain free ? I'm just looking for the most stable thing as possible.

You are correct. By default you'll get the "basic" tier, which in the link I shared is everything under "Basic - free and open".
