### ISSUE TITLE
Increase `UnicastZenPing.LIMIT_PORTS_COUNT` to `2`

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#7090]
As described in https://github.com/elasticsearch/elasticsearch-cloud-aws/issues/99, we should increase `UnicastZenPing.LIMIT_PORTS_COUNT` to `2` instead of `1` today.

It should be a modifiable setting in case of users needs to run more instances on the same physical box, for example 2 data nodes on a 128gb RAM machine, one client node and one master only node.

**Comment by jerry4** [comment]
Is there any progress on merging this change in? I'm in a scenario where I want to run several staging clusters on the same box. The first one is the only one that can be discovered since it takes the default first port. Seems like this change would allow me to specify the number of clusters running on a single box so my clients can check multiple ports.

**Comment by dadoonet** [comment]
Closing in favor of #8833.
