### ISSUE TITLE
Request to maintain maven repo for analysis-kuromoji and analysis-icu

### ISSUE THREAD

**Issue by JinIgarashi** [elastic/elasticsearch#71089]
We are trying to use `analysis-kuromoji` and `analysis-icu` in [komoot/photon](https://github.com/komoot/photon) geocoder which relies on `Elasticsearch v5.6.16`. However, those two plugins maven repositories seem not to be maintained since version `5.0.0-alpha5`.

- Maven repo for `analysis-kuromoji` and `analysis-icu`
  - https://mvnrepository.com/artifact/org.elasticsearch.plugin/analysis-kuromoji
  - https://mvnrepository.com/artifact/org.elasticsearch.plugin/analysis-icu

Because there is no v5.6.16's plugin in maven repo, we are currently using `mvn install` to install the plugins manually. Could you start to maintain those plugins' maven repository again? It would be so helpful for Japanese community if there are all versions of plugins in maven repo.

**Comment by tlrx** [comment]
Hi @JinIgarashi ! Version 5.6.1 is EOL since almost two years now (see https://www.elastic.co/support/eol), so we are not likely to maintain external Maven repositories for these version.

Instead, we maintain these artifacts on https://artifacts.elastic.co/. If you look at the [documentation of the Kuromoji plugin in version 5.6.16](https://www.elastic.co/guide/en/elasticsearch/plugins/5.6/analysis-kuromoji.html), you'll see that you can install the plugin manually using the artifacts provided by Elastic at https://artifacts.elastic.co/downloads/elasticsearch-plugins/analysis-kuromoji/analysis-kuromoji-5.6.16.zip.

You should be able to define your own Maven repository to download artifacts from https://artifacts.elastic.co/.
