### ISSUE TITLE
Add shard balance function that tries to equalize similarly sized (on disk) shards

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#7155]
It'd be nice to have a balance function that tries to equalize the number of similarly sized shards on each node.  This would have several advantages for clusters with unevenly sized indexes:
- Help prevent #6168 by making it less likely that lots of large shards end up on a single node, pushing its disk space much much higher then the rest.
- Help balance disk IO load by keeping the large shards away from each other.
- Prevent one node from ending up fallow because it only contains small shards just by luck.

**Comment by DaveCTurner** [comment]
This is an interesting idea but since its opening we have not seen enough feedback that it is something we should pursue. We prefer to close this issue as a clear indication that we are not going to work on this at this time. We are always open to reconsidering this in the future based on compelling feedback; despite this issue being closed please feel free to leave feedback (including +1s).
