### ISSUE TITLE
Should we support `epoch_seconds`?

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#71638]
Should we support `epoch_seconds` to be consistent with `epoch_millis`?

https://github.com/elastic/elasticsearch/blob/a92a647b9f17d1bddf5c707490a19482c273eda3/server/src/main/java/org/elasticsearch/common/time/FormatNames.java#L56-L57

The inconsistency upsets me a little....

**Comment by pgomulka** [comment]
++ to this, we could deprecate this format in 7.x and have it consistent in 8.0

**Comment by pgomulka** [comment]
we discussed this on core infra sync on 21April
We concluded that we will add `epoch_seconds` in addition to `epoch_second` in version 7 and 8
However we will not plan on removing `epoch_second` soon-ish. It has to stay until version 9 at minimum, because of index backwards compatibility. 
Users should be creating new indicies with `epoch_seconds`, and `epoch_second` will be deprecated. 
We hope that `epoch_second` will get stale and not used thanks to data retention - indices created with that format will be removed by users themself.

**Comment by rjernst** [comment]
`epoch_seconds` was unfortunately never added. Given the move to bring more stability, I'm not sure such a change would be favored at this point without a compelling reason. I'm closing this issue, but we can can reopen if necessary.
