### ISSUE TITLE
[Docs or Feature Request] Enforce consistent position_increment_gap in multi-fields for multi-values

### ISSUE THREAD

**Issue by speedplane** [elastic/elasticsearch#71659]
Hi ES Community,

I recently found some confusing behavior with a mapping and multi-fields, and it would be nice if Elasticsearch would prevent you from shooting yourself in the foot (like I did).

The issue arises when you use a `position_increment_gap` in a multi-field inconsistently. Apparently, the `position_increment_gap` on an outer field is not automatically applied to the inner fields. So, in the example mapping below, the inner `unstemmed` field will have a different `position_increment_gap`. When you index multi-value docs on this multi-field, the term vectors for the two fields are inconsistent, and `span_near` queries will not work across the fields.

```
      "properties": {
          "text": {
            "analyzer": "main_analyzer", 
            "type": "text", 
            "position_increment_gap": 1000,
            "fields": {
              "unstemmed": {
                "analyzer": "unstemmed_analyzer", 
                "type": "text"
              }
            }
          }
     }
```

This type of mistake could have been avoided if one of the following was fixed:

- Set the  `position_increment_gap` of any inner multi field to the parent's value
  - note: this may break mappings, but it's really the only behavior that makes sense for multi-fields.
- Require all multi-fields that use a `position_increment_gap` to explicitly set it on each field.
- Emit some sort of warning somewhere.
- At least acknowledge this gotcha in the docs on `position_increment_gap` and/or multi-fields.

Thanks for listening!

**Comment by jtibshirani** [comment]
Hello @speedplane, thanks for raising this. I definitely see why this is confusing and an easy place to make errors.

I don't think we'd want to automatically set `position_increment_gap` on the child fields or enforce consistency with the parent. This is because multi-fields are considered to be totally separate mappings from the parent field. They aren't meant to share any mapping logic, they just take in the same field value from the document _source. To help clarify this, we could add a note in the multi-fields docs emphasizing that the child and parent fields are totally separate mappings. I marked the issue as 'docs' to reflect this.

On a related note, we've been brainstorming how to make it easier define fields with both exact and stemmed analysis. We might move away from multi-fields for this use case, introducing a simpler and less error-prone way to accomplish it.

**Comment by speedplane** [comment]
Hi @jrodewig and @jtibshirani thanks for adding the note!
