### ISSUE TITLE
Move this variable to static scope

### ISSUE THREAD

**Issue by Lupo00** [elastic/elasticsearch#71687]
This variable contains only constants which creates and deletes (redundant work for GC), you could move it to be static variable.
 
https://github.com/elastic/elasticsearch/blob/f491af65c0946301a85ff0589f24e79dff3d2341/client/rest-high-level/src/main/java/org/elasticsearch/client/core/TermVectorsRequest.java#L268

**Comment by jasontedor** [comment]
That's not necessarily the case since `filterSettingNames` never escapes the method, and therefore escape analysis could lead to this array being stack allocated instead of heap allocated. Arguably that's better than a static reference since the latter will always occupy memory for the allocated array, and would be an additional GC root. Either way, I would consider addressing this point a micro-optimization and unlikely to be worth the time.
