### ISSUE TITLE
Runtime field doesn't work correctly with range query when emitted value is 0.0

### ISSUE THREAD

**Issue by josefschiefer27** [elastic/elasticsearch#71786]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.12.0

**Plugins installed**: []

**JVM version** (`java -version`): java version "16" 2021-03-16

**OS version** (`uname -a` if on a Unix-like system): MacOS Catalina, Version 10.15.7

**Description of the problem including expected versus actual behavior**:
When emitting the value 0.0 for a runtime time field of type double, a range query with lt (less equal) returns the wrong result.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Create an index with a runtime field of type double. The runtime field emits always the value 0.0.
```
 PUT my-index
 {
   "mappings": {
     "runtime": {
       "field1": {
         "type": "double",
         "script": {
           "source": "emit(0.0)"
         }
       }
     }
   }
}
```

 2. Insert a document to the index
```
PUT my-index/_doc/1
{}
```

 3. Search for the document using this range query
```
GET my-index/_search
{
  "query": {
    "range": {
      "field1": {
        "lt": 0
      }
    }
  }, 
  "docvalue_fields": ["field1"]
}
```
This range query returns the inserted document which is a wrong result. Please note that the range query condition is <0 - hence this query shouldn't return any documents. I noticed that this problem only occurs when emitting the value 0. Other  values (e.g. 1.0, 2.0, 3.0...) work as expected.

**Comment by cbuescher** [comment]
Because of the excluding the upper bound 0.0 the query is translated to an "field1:[-Infinity TO -0.0]" query. The "-0.0" upper value is included because its the next smallest value below 0.0 for the double type. While this is respected on the regular "double" field, the impelentation in DoubleScriptFieldRangeQuery uses a simple Java double comparison (i.e. a <=b) where apparently -0.0 == 0.0. Fortunately we can switch to Double.compare that seems to handle this case correctly. I'll open a PR shortly.
