### ISSUE TITLE
Update opensaml dependency to 4.1.0

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#71983]
opensaml 4.1.0 was released on 23/04/21. We should look into upgrading our dependencies for the SAML realm and the Identity Provider implementations

- [x] Investigate major API changes between 3.4.5 and 4.1.0
- [x] Look into release notes for bugs resolved and major functionality additions

**Comment by tvernum** [comment]
OpenSAML 4.0 requires Java 11.
We cannot upgrade in the 7.x development tree.

**Comment by tvernum** [comment]
I've started work on this in https://github.com/elastic/elasticsearch/pull/77012

There's a few issues to work out, but most of them seem to be solvable _except_ OpenSAML4 seems to have a hard dependency on the standard (non-FIPS) distribution of BouncyCastle.
It requires `org.bouncycastle.jce.ECNamedCurveTable` which doesn't exist in BCFIPS.  
This makes it very difficult for us, because we want to support SAML when running in FIPS mode, and we can't do that (at least, not easily) if the BC jars are also on the classpath.

**Comment by tvernum** [comment]
We've upgraded to v.40 in #77012, but could not upgrade to v4.1 due to an incompatibility with FIPS.
I'm leaving this issue open so that we can look at it again in the future.

**Comment by gwbrown** [comment]
A few more versions of OpenSAML are out - as of this comment they're up to 4.3.0. Perhaps we should check whether OpenSAML is still incompatible with bc-fips or if this problem has been addressed somehow.

**Comment by albertzaharovits** [comment]
I can confirm that OpenSAML 4.3.0 still requires bouncy castle as a runtime dependency.
Here is an excerpt of the dependency graph:
```
|    +--- org.opensaml:opensaml-security-api:4.3.0
|    |    +--- org.opensaml:opensaml-core:4.3.0 (*)
|    |    +--- org.opensaml:opensaml-messaging-api:4.3.0 (*)
|    |    +--- commons-codec:commons-codec:1.15
|    |    +--- com.google.code.findbugs:jsr305:3.0.2
|    |    +--- com.google.guava:guava:31.1-jre (*)
|    |    +--- org.cryptacular:cryptacular:1.2.5
|    |    |    \--- org.bouncycastle:bcprov-jdk18on:1.71 -> 1.72
|    |    +--- org.bouncycastle:bcprov-jdk18on:1.72
|    |    +--- org.bouncycastle:bcpkix-jdk18on:1.72
|    |    |    +--- org.bouncycastle:bcprov-jdk18on:1.72
|    |    |    \--- org.bouncycastle:bcutil-jdk18on:1.72
|    |    |         \--- org.bouncycastle:bcprov-jdk18on:1.72
```
Here's a sample failure https://gradle-enterprise.elastic.co/s/26awfttvvkagg from my incomplete attempt at an upgrade https://github.com/elastic/elasticsearch/pull/95633 . The opensaml initialization code builds a map of supported EC curve params, presumably to be later used to validate signatures.

As I understand it, we don't want to supply a runtime dependency of `org.bouncycastle:bcprov-jdk18on:1.72` because we cannot claim (and truthfully so) FIPS compatibility if such a non-FIPS provider is on the classpath.

**Comment by albertzaharovits** [comment]
PS Look for references of `ECNamedCurveTable` or `ECNamedCurveParameterSpec` in `GlobalNamedCurveRegistryInitializer`.
