### ISSUE TITLE
Skip rollover action on non write indices

### ISSUE THREAD

**Issue by Bernhard-Fluehmann** [elastic/elasticsearch#71984]
A manual rollover on a ilm controlled alias or datastream can result in additional rolled over indices. The reason is that the ilm job will roll the already rolled over index again once the rollover time is elapsed. IMO ilm should not roll over if an index twice. One solution would be to automatically complete (skip) rollover actions o. Indices which are not the write index. This would solve the problem and make the ilm rollover meghanism more robust.

**Comment by dakrone** [comment]
@Bernhard-Fluehmann we do have a mechanism for preventing this already in place:

https://github.com/elastic/elasticsearch/blob/95c2431c9d8145293463e30265f1da33ab9d4bee/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/RolloverStep.java#L74-L79

Can you be more specific in what you mean? Are you perhaps hitting a bug with Elasticsearch that has since been fixed?

**Comment by Bernhard-Fluehmann** [comment]
@dakrone Thank you very much for the fast response. We are using datastreams and this is the fix: #67778. The cluster with the issue is still on 7.9. Problem solved.

**Comment by dakrone** [comment]
Great, thanks for confirming! I'm going to close this since it's been resolved.
