### ISSUE TITLE
query_string can't use index_prefix default 

### ISSUE THREAD

**Issue by jiamo** [elastic/elasticsearch#72076]
latest elasticsearch. The last query can't work:

    PUT my-index-000002
    {
      "mappings": {
        "properties": {
          "full_name": {
            "type": "text",
            "index_prefixes": {
              "min_chars" : 1,
              "max_chars" : 10
            }
          }
        }
      }
    }
   
    PUT my-index-000002/_doc/1
    {
      "full_name": "Quick Brown Fox"
    }
    
    POST my-index-000002/_refresh
    
    GET my-index-000002/_search
    {
      "query": {
        "prefix" : { "full_name" : {
          "value": "Qui",
          "case_insensitive": true} }
        
      }
    }
   
    GET my-index-000002/_search
    {
      "query": {
        
        "query_string" : {
         "query":  "qui",
         "default_field": "full_name"
        }
      }
    }

the query_string can't work until using `"qui*"`
At the end of  document  https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html

    Query string query can be internally be transformed to a prefix query

It seem I can achieve the same result like `prefix query` without using wildcard.
But it can't.

**Comment by cbuescher** [comment]
> the query_string can't work until using "qui*"

This is working as expected. I think you are misunderstanding the documentation you mentioned here. Your quote appears in a part about allowing or disallowing expensive queries and only means that a query_string query can potentially be rewritten to a prefix query, not that this is always the case, especially without wildcards. 
I'm closing this issue since I think the documentation on this point is clear enough, let us know if you disagree.
