### ISSUE TITLE
Rollup: Improve error message with invalid index pattern on job creation

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#72545]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.12.0

**Description of the problem including expected versus actual behavior**:

Adding the following rollup job returns a indescriptive error message

```
PUT _rollup/job/test
{
  "id": "test",
  "index_pattern": "*sample*",
  "rollup_index": "rollup-sample",
  "cron": "0 * * * * ?",
  "page_size": 1000,
  "groups": {
    "date_histogram": {
      "interval": "1m",
      "delay": "1d",
      "time_zone": "UTC",
      "field": "customer_birth_date"
    },
    "terms": {
      "fields": [
        "customer_gender"
      ]
    },
    "histogram": {
      "interval": "60",
      "fields": [
        "products.min_price"
      ]
    }
  },
  "metrics": [
    {
      "field": "products.base_price",
      "metrics": [
        "max"
      ]
    }
  ]
}
```

returns

```json
{
  "error" : {
    "root_cause" : [
      {
        "type" : "x_content_parse_exception",
        "reason" : "Failed to build [xpack/rollup/jobconfig] after last required field arrived"
      }
    ],
    "type" : "x_content_parse_exception",
    "reason" : "Failed to build [xpack/rollup/jobconfig] after last required field arrived",
    "caused_by" : {
      "type" : "illegal_argument_exception",
      "reason" : "Index pattern would match rollup index name which is not allowed"
    }
  },
  "status" : 400
}
```

Running this with `?error_trace=true` enabled reveals the following as part of the response

```json
"stack_trace" : "[Failed to build [xpack/rollup/jobconfig] after last required field arrived]; nested: XContentParseException[Failed to build [xpack/rollup/jobconfig] after last required field arrived]; nested: IllegalArgumentException[Index pattern would match rollup index name which is not allowed];\n\tat org.elasticsearch.ElasticsearchException.guessRootCause..."
```

The useful error message as part of the response is swallowed `Index pattern would match rollup index name which is not allowed` - also the Kibana UI indicates that the invalid index pattern is actually ok.

**Comment by wchaparro** [comment]
With the 8.7 release of Elasticsearch, we have made a [new downsampling capability](https://www.elastic.co/guide/en/elasticsearch/reference/current/downsampling.html) associated with the new [time series datastreams](https://www.elastic.co/guide/en/elasticsearch/reference/current/tsds.html) functionality generally available (GA). This capability was in tech preview in ILM since 8.5.  Downsampling provides a method to reduce the footprint of your time series data by storing it at reduced granularity. The downsampling process rolls up documents within a fixed time interval into a single summary document. Each summary document includes statistical representations of the original data: the min, max, sum, value_count, and average for each metric. Data stream time series dimensions are stored unchanged. 

Downsampling is superior to rollup because:

- Downsampled indices are searched through the _search API
- It is possible to query multiple downsampled indices together with raw data indices
- The pre-aggregation is based on the metrics and time series definitions in the index mapping so very little configuration is required (i.e. much easier to add new time serieses)
- Downsampling is managed as an action in ILM
- It is possible to downsample a downsampled index, and reduce granularity as the index ages
- The performance of the pre-aggregation process is superior in downsampling, as it builds on the time_series index mode infrastructure

Because of the introduction of this new capability, we are deprecating the rollups functionality, which never left the Tech Preview/Experimental status, in favor of downsampling and thus we are closing this issue. We encourage you to migrate your solution to downsampling and take advantage of the new TSDB functionality.
