### ISSUE TITLE
 Ignore allow_explicit_index when accessing root /_bulk URL

### ISSUE THREAD

**Issue by fizmat** [elastic/elasticsearch#7256]
When url-based access control is used for bulk requests

rest.action.multi.allow_explicit_index: false

http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/url-access-control.html
It forbids explicitly setting the index in the request body regardless of the bulk url used.

Would it be possible to allow setting explicit indexes when the URL accessed is the /_bulk root, with no index specified in the URL?

This way if a user is allowed to access /_bulk, he can work as if allow_explicit_index is false, while if a user is only allowed to access specific {index}/_bulk urls, he is effectively contained.

With the current rules, the only way to allow bulk access with explicit index to one user is to set allow_explicit_index to true and thus allow full access to everybody with bulk access.

Maybe this feature is not that high-priority, I see that access control in general does not seem to be the focus of elasticsearch. But if this is an easy change, would this work?

**Comment by malpani** [comment]
+1 - this feature will be pretty useful to have for _bulk, _mget and _msearch APIs as it provides means to have secure URL based access control and not restrict other users who have complete access from hitting multiple indices

**Comment by clintongormley** [comment]
I'd really prefer not to add silent exceptions here.  Either explicit indices are allowed or they aren't.  Otherwise we'd have to rename the setting to `rest.action.multi.allow_explicit_index_unless_no_index_specified: false`...

For the Logstash issue, i'd suggest opening an issue on https://github.com/logstash-plugins/logstash-output-elasticsearch/ to add support for including the index name at the top level of the bulk request.
