### ISSUE TITLE
esplugin is not compatible with Gradle 7.0

### ISSUE THREAD

**Issue by cliu123** [elastic/elasticsearch#72604]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.10.2
**Plugins installed**: []

**JVM version** (`java -version`):
14
**OS version** (`uname -a` if on a Unix-like system):
MacOS
**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
With Gradle 6.8, `./gradlew build` succeeded.
But with Gradle 7.0, `./gradlew build` failed. The following is the error message:
`* What went wrong:
A problem occurred evaluating root project 'opensearch-security'.
> Failed to apply plugin class 'org.opensearch.gradle.info.GlobalBuildInfoPlugin'.
   > Could not create plugin of type 'GlobalBuildInfoPlugin'.
      > Could not generate a decorated class for type GlobalBuildInfoPlugin.
         > org/gradle/jvm/toolchain/JavaInstallation
`

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by mark-vieira** [comment]
Version 7.10.2 of build-tools only supports Gradle 6.8 (Gradle 7.0 hadn't been released at the time). The upcoming 7.13 release will include support for Gradle 7.0 (in fact, it will be required) so I suggest for now you stick with Gradle 6.8 for building your plugin.

Closing this issue since we won't be retroactively patching that release.
