### ISSUE TITLE
[DOCS] File authentication docs present conflicting information on the necessity of realm configuration

### ISSUE THREAD

**Issue by Angelin01** [elastic/elasticsearch#72770]
The [File-based user authentication page](https://www.elastic.co/guide/en/elasticsearch/reference/master/file-realm.html) at the same time states:

> When you configure realms in elasticsearch.yml, only the realms you specify are used for authentication. **To use the file realm you must explicitly include it in the realm chain.** While it is possible to define multiple instances of some other realms, you can define only one file realm per node.

And

> The file realm is added to the realm chain by default. **You don’t need to explicitly configure a file realm.**
> 1. **(Optional)** Add a realm configuration to elasticsearch.yml under the xpack.security.authc.realms.file namespace. At a minimum, you must set the realm’s order attribute.

Obviously these snippets are contradictory. I am unaware of which one is correct, but the documentation needs updating anyway. 
It seems the new information (the second snippet) was added on [version 7.4](https://www.elastic.co/guide/en/elasticsearch/reference/7.4/file-realm.html).

**Comment by ywangd** [comment]
@Angelin01 Thanks for reporting the issue. You are right that our docs need clarification for this particular topic. In the meantime, let me try to clear the confusion since the behaviour is slightly involved and we are changing it for 8.0.

**For 7.x**, both `file` and `native` realms are _implicitly_ added to the realm chain when:
* No realms are configured
* All configured realms are not allowed for current license

Otherwise, you need to explicitly add them to the realm chain in order to use them. The doc page of [realm chains](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/realm-chains.html) are more accurate on this behaviour.

Note the `7.x` behaviour is being deprecated.

**For 8.0+**, we have [changed](https://github.com/elastic/elasticsearch/pull/69096) it to: Unless explicilty disabled, both `file` and `native` realms are always added to the realm chain:
* When they are implicitly added, they are always added at the beginning of the chain
* When they are explicitly added (by configuring `elasticsearch.yml`), their associated order values are respected.

Again, the 8.0 doc page of [realm chains](https://www.elastic.co/guide/en/elasticsearch/reference/master/realm-chains.html) are more accurate about it.

**Comment by lockewritesdocs** [comment]
The behavior of the realm configuration has changed in 8.0+, so I'm closing this issue. We can reopen if needed.
