### ISSUE TITLE
Add search_after parameter to new terms_enum api

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#72910]
To allow client applications to page through many autocomplete suggestions we should offer a `search_after` parameter. Calling applications would pass the last term value from the previous set of results and the returned results would be all those matching the provided prefix `string` param but after the supplied `search_after` parameter.  An example might be:

#### Request 1
```
localhost:9200/myindex/_terms_enum
{
"field" : "url",
"string" : "www."
}}
```
#### Result 1
```
{
   "terms": [
    "www.aa.com",
    "www.abc.com",
    ...
    "www.bbc.com"
    ]
```
#### Request 2 (with new search_after param)
```
localhost:9200/myindex/_terms_enum
{
"field" : "url",
"string" : "www.",
"search_after" : "www.bbc.com"
}}
```
#### Result 2
```
{
   "terms": [
    "www.breitling.com",
    "www.bt.com",
    ...
    "www.cnn.com"
    ]
```
It would be a client error to pass a `search_after` string that does not start with the provided `string` prefix.
#### Example invalid request that would produce an error
```
   "search_after": "www.bbc.com",
   "string": "some_other_prefix"
```

Related to https://github.com/elastic/elasticsearch/issues/71550

**Comment by jimczi** [comment]
The IntersectTermsEnum takes the `startTerm` as an argument in the constructor. That's also expose in `Fields`: 
```
public TermsEnum intersect(CompiledAutomaton compiled, final BytesRef startTerm) throws IOException {
```

**Comment by jtibshirani** [comment]
We've had discussions on a general approach to support paging in our REST APIs: https://github.com/elastic/elasticsearch/issues/64099. I wonder if this aligns with what we're been planning for other APIs, maybe we're standardizing on using `search_after`? Tagging @ywangd and @cjcenizal in case they're interested.

**Comment by ywangd** [comment]
> We've had discussions on a general approach to support paging in our REST APIs: #64099. I wonder if this aligns with what we're been planning for other APIs, maybe we're standardizing on using `search_after`? Tagging @ywangd and @cjcenizal in case they're interested.

Thanks @jtibshirani We haven't really settled on an approach for user interface on the other issue. I have a separate document about search API key metadata where I also talked about pagination. The basic idea is to have a more generic parameter, I call it `resumption_token`, instead of `search_after`. The main reason is to hide implementation details about how the data is searched and where they come from:
1. For termsEnum, just a single `search_after` is sufficient because there is no variation on how search is done.
2. But sometimes (often times?) we want to iterate the results with a Point-In-Time reader. But instead of having both `search_after` and `pit` parameters, we can have a single `resumption_token` to encode both information and let the server handle it transparently for users.
3. There are use cases where `search_after` may not make most of sense or won't maintain its canonical meaning. For example, the list of snapshots does not come from an index at all (@henningandersen), so `search_after` is somehow a misuse. But `resumption_token` is generic and the handler can decide how it should be handed out and handled. (Does termsEnum fall into this category as well? It's lucene data but does not from the actual "search"?)

Personally I feel it's easier for users to consume our APIs if they provide consistent interfaces for simliar concept, e.g. pagination, instead of similar unerlying implementations.

@albertzaharovits also suggested we could have this `resumption_token` provided by the search infrastructure itself. But since pagination is needed for places where index search is not required, I think it is also reasonable to have it outside of the search itself.

**Comment by henningandersen** [comment]
I too would like to not have our generic pagination named `search_after`. I prefer just `after`, I think that is short and concise. Other necessary names is the parameter for the limit of how many results to include in a page and the value in the response to use to get the next page. I think `limit` and `next` can work out here.

Another choice is whether `limit` and `after` should go in the body or as query-params. We could opt to support both.

**Comment by henningandersen** [comment]
@jtibshirani provided input through another channel that she prefers `size` over `limit`, I tend to agree that is more in line with previous conventions. We also need a `sort` parameter though I suppose it is implicit in the `terms_enum` api, since there is only one (?).

**Comment by markharwood** [comment]
>We also need a sort parameter though I suppose it is implicit in the terms_enum api, since there is only one (?).

In the interests of maximum performance we don't support anything other than the sort order used internally to arrange terms in the index

**Comment by markharwood** [comment]
Closed in https://github.com/elastic/elasticsearch/pull/72933
