### ISSUE TITLE
Enhancement: fuzziness above 2 edits

### ISSUE THREAD

**Issue by jguay** [elastic/elasticsearch#73083]
Currently elasticsearch support fuzziness of up to two edits per [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/7.12/common-options.html#fuzziness)

Requested feature is for fuzziness of 3 (or more) edits

Example with `ALEJANDRO` is indexed but returned when `ALEXANDER` or `ALEJATYPO` is searched with fuzziness of 3 Edits.

Side notes : 
- Synonyms which would be a valid/cheaper solution in some cases which is outside the scope of the feature request
- ~With async search elasticsearch currently supports better running long queries.~ Fuzziness of 3 will obviously be much more costly than 2 edits (potentially doc update needed if the feature for 3 or more max edits is implemented)

**Comment by markharwood** [comment]
I wasn't close to the development of the fuzzy implementation but it was [notoriously complex](http://blog.mikemccandless.com/2011/03/lucenes-fuzzyquery-is-100-times-faster.html) getting beyond just one edit distance. That suggests it's not as simple as raising a setting.
It's worth mentioning that a common and perhaps simpler solution to fuzzy matching is to index with ngrams and search those.
Or did you mean that for edit distance > 2 we should only use async search and revert to a slower brute force scan of indexed terms (using Levenshtein string comparisons) rather than adding to the complex automaton-based matching exclusively used today?

**Comment by jguay** [comment]
thank you @markharwood for confirming this was investigated before and found to be very difficult feature to implement, the ngram solution is in fact good solution although in this case it isn't suitable because mostly it will cause a lot of false positive and the requirement in this case is to always use 3 Edits for the search
Example `ALEJANDRO` is indexed with `"min_gram" : 3` will not match `ALZJAZDRZ` with 3 Edits which should match and will match `ALEZZZZZZ` which should not match as this is 6 Edits

I strike that side note on async search, with the expected exponential costs of adding the 3rd Edits, I just wanted to highlight async search might help because the search would run slower if we ever implement max Edit of 3 (when compared to current 2 Edits)

**Comment by javanna** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
