### ISSUE TITLE
[Deprecation info API] Support for requires_restart field

### ISSUE THREAD

**Issue by alisonelizabeth** [elastic/elasticsearch#73091]
Related to https://github.com/elastic/kibana/issues/36919.

In Upgrade Assistant, it would be helpful if we could identify any deprecations that can only be resolved offline.

We've received similar feedback for displaying Kibana deprecations, and support for this is being tracked in https://github.com/elastic/kibana/issues/98476.

**Proposal:**
```
{
   "cluster_settings": [],
   "node_settings": [
           {
            "level":"critical",
            "message":"Security realm settings structure changed",
            "url":"/docs",
            "details":"these settings must be updated to the new format while the node is offline during the upgrade to 7.0",
            // name is only a suggestion
            "requires_restart": true
         }
   ],
   "index_settings": {
      "logs:apache": [
         {
            "level":"warning",
            "message":"Index name cannot contain ':'",
            "url":"https://www.elastic.co/guide/en/elasticsearch/reference/7.0/breaking-changes-7.0.html#_literal_literal_is_no_longer_allowed_in_index_name",
            "details":"This index is named [logs:apache], which contains the illegal character ':'.",
            // name is only a suggestion
            "requires_restart": false
         }
      ]
   },
   "ml_settings": []
}
```

**Comment by martijnvg** [comment]
@alisonelizabeth So this new flag is for deprecation issues that can only be resolved during rolling upgrading to a new version when a node is offline for the upgrade?

In that case I'm not sure whether the name `requires_restart` doesn't fully encapsulate this, because this name to me means that a deprecation issue can also be resolved when just stopping a node, updating the config and then starting it back up (without upgrading). Side question: Is this something we would like to highlight as well as part of a deprecation issue?

I don't know a better name yet for a field like this. Maybe `resolve_during_rolling_upgrade`? I'm not sure...

**Comment by alisonelizabeth** [comment]
That's correct and you bring up a good point. I think `resolve_during_rolling_upgrade` might be more clear.

> Side question: Is this something we would like to highlight as well as part of a deprecation issue?

Do you mean as part of the `message` or `details` field of the deprecation? I'm not sure it's necessary, but I guess it doesn't hurt either. With the flag, I had planned to either add some sort of filter or badge in the Upgrade Assistant to highlight these type of deprecations. I imagine there would be some additional copy/help text in the UI explaining it as well.

**Comment by martijnvg** [comment]
> That's correct and you bring up a good point. I think resolve_during_rolling_upgrade might be more clear.

👍 Then I will rename it to `resolve_during_rolling_upgrade`

> Do you mean as part of the message or details field of the deprecation?

No, I was thinking another field next to `resolve_during_rolling_upgrade`, for example `requires_node_restart`. Which would indicate that in order to resolve the deprecation issue on or more nodes need to be restarted. I think would apply to most node level deprecations. On the other hand, maybe this isn't needed, because changing a node level setting always requires a node restart for the change to take into effect.
