### ISSUE TITLE
Index shard corruption check does not play well with partially mounted searchable snapshots

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#73147]
In order to perform a corruption check during recovery, it is possible to configure the index setting `index.shard.check_on_startup` with the values `checksum`, `true` or `false` (default). If this setting is set to `true` or `checksum` the entire Lucene directory files will be read and this does not play well with partially mounted searchable snapshots: it fills up the shared cache and can slow down shard recoveries.

Note that ILM overrides this setting to `false` when mounting a snapshot in the `MountSnapshotStep` but the default Mount API does not override it.

I'm opening this issue on behalf of @joegallo to discuss what we should do when a snapshot is mounted for an index with a non false check_on_startup setting. Should we reject, warn or just document this behavior?

**Comment by DaveCTurner** [comment]
IMO we should default this to `false` for all mount operations but allow it to be overridden in the request, similarly to how we handle `number_of_replicas` and `auto_expand_replicas` today. Checking all the checksums is not a totally silly thing to want to do, and being able to do it without needing the disk space for a full restore may actually be useful sometimes.

We already call out this setting as "expert only" and note that it can take a lot of time. As well as the effect on the shared cache for searchable snapshots it also interacts very badly with the page cache on standard shards since it likely evicts a lot of pages unnecessarily. Perhaps we can expand the warning in the docs a bit to clarify just how harmful it can be.

**Comment by tlrx** [comment]
We discussed this in team and we agreed to follow David's suggestions to improve documentation (#74233) and to set a default value for the `index.shard.check_on_startup` setting to `false` when mounting a snapshot, but still allow this setting to be overridden if needed in the `_mount` request (#74235).
