### ISSUE TITLE
Setting to disable rewrite-to-filters optimization

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#73426]
It turns out that *sometimes* my [beautiful date_histogram optimizations](https://www.elastic.co/blog/how-we-made-date-histogram-aggregations-faster-than-ever-in-elasticsearch-7-11) aren't always optimizations. Sometimes they make the `date_histogram` super ultra slow. We've known that and have heuristics that disable the optimization. Those heuristics generally work because, like, we worked on them. But it turns out that they don't work for everyone. Sometimes folks have queries or data or *something* that doesn't work well with the heuristics we have. I'll be filing a separate issue with the cases we've heard about and fix the heuristics. But I think this is a forever problem. We just won't cover all cases in our tests. So we're going to need an escape hatch to disable the optimization entirely. I believe a cluster level setting is the most sensible thing here. Its a "big hammer", but its one that you can easily modify if you hit the issue without restarting anything and you can disable once you've upgraded to a version that includes the fix.

**Comment by markharwood** [comment]
The big question I had in my mind was over the default for the switch - whether folks would explicitly choose to opt in for the whizzy date optimisation or opt out of scenarios when it goes wrong.

**Comment by nik9000** [comment]
> The big question I had in my mind was over the default for the switch - whether folks would explicitly choose to opt in for the whizzy date optimisation or opt out of scenarios when it goes wrong.

I talked to @markharwood about this earlier. I *think* the right thing is to give folks an out, but try to be fairly aggressive about turning on the optimizations. We benchmark and stuff, but we'll never hit all the cases. And this'd give us an out.

I've got the makings of a cluster setting you can use to disable the optimization when the top level query contains some kind of query. You can specify the kind of query. You specify `Query` and its everything. You specify `AutomatonQuery` and it'll turn off the optimization for wildcard and regex queries. Its a bit more precise than what I was originally thinking, but it feels right. Its hard for non-contributors to know the right values to set this to, but I think that's ok because its to work around bugs and if you report a bug we'll suggest the right value for the setting.

**Comment by kenoir** [comment]
We just hit a situation where we had to disable this option to keep query performance up. Is it useful to share our configuration somewhere?

**Comment by nik9000** [comment]
Probably! I've been working on a change.to better detect the bad cases up
front but I'd love to see what you hit.

You can post here or email me directly if you'd like. My email is in my
commit metadata.

If you send the _search request or an anonymized copy of it that is
*probably* enough for me to figure out if my later work was enough.

Sorry for all this!

**Comment by saschaarthur** [comment]
https://github.com/elastic/elasticsearch/pull/73620#issuecomment-890804864 should have been maybe placed here

**Comment by aj7** [comment]
@nik9000 so we've had the same issue which caused quite a lot of panick! Upgraded from 7.9 to 7.13.3 , but actually the slowness almost "only" affected spatial queries which is why we didn't detect at the beginning. Non-spatial queries seem to work fine but spatial queries (using the geospatial type) would take forever and cause our ES to crash. Our index is > 200GB in size, mostly due to geospatial data.

And of course, we would want our spatial queries to work much faster, so I wonder if it's something you can investigate?

**Comment by iverase** [comment]
Hi @aj7,
I gladly try to help you. Still we would like to keep Github for verified bug reports, feature requests, and pull requests.  Therefore I would like to direct you to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) and start a thread there. 

In order to help you can you please add information about the mapping of the geospatial field and a query example where you have experience the slowdown.

Thanks!

**Comment by aj7** [comment]
hi @iverase , of course, I will aim to do this; but also thought of mentioning it here since this i didn't see any mention of spatial queries being affected specifically, and therefore could be something for the ES team to check out....
