### ISSUE TITLE
SQL: Pagination in ES SQL using "OFFSET {from} ROWS FETCH NEXT {size} ROWS ONLY"

### ISSUE THREAD

**Issue by brunoanasofia** [elastic/elasticsearch#73464]
Hello,

In DSL we could paginate using from and size:

**DSL**
`GET process/_search
{
  "from" : 10, "size" : 20,
  "query": {
    "match_all": {}
  }
}
`
But in ES SQL doesn't exist "from".

**SQL**
`GET /_sql?format=json
{
  "query":"""SELECT * FROM process """,
  "fetch_size":"20"
}`

With _OFFSET {from} ROWS FETCH NEXT {size} ROWS ONLY_ we could paginate to backwards and forewards without using the cursor.

`SELECT id 
   FROM process 
   ORDER BY id 
   OFFSET {from} ROWS FETCH NEXT {size} ROWS ONLY`

**Comment by astefan** [comment]
Hi @brunoanasofia. The use of `from` and `size` in Elasticsearch does have a drawback (which is also documented) - a too deep  pagination can become problematic, resource usage wise, for an Elasticsearch cluster due to the way this feature works. Thus, the reason why we are reluctant to provide a similar functionality in ES SQL.

Is this issue in some way different from the already existent feature request here https://github.com/elastic/elasticsearch/issues/31549 (where you also added a question)?

**Comment by brunoanasofia** [comment]
Hi @astefan. These issues are similar but not identical.  In this issue I suggested to user this construction "OFFSET {from} ROWS FETCH NEXT {size} ROWS ONLY" o SELECT instruction.  Thanks.  👍

**Comment by matriv** [comment]
I don't understand how your proposal differs from:
```
SELECT id FROM process ORDER BY id OFFSET {offset} LIMIT {limit}
```
where you skip the first `{offset}` number of records and you return the next `{limit}` number of records.

We don't want to promote this kind of pagination because to accomplish pagination this way you need to execute multiple queries, and there is no guarantee that you have the same "view" ("snapshot") of the data between them. So there is a  chance when you do something like:
```
SELECT id FROM process ORDER BY id OFFSET 100 LIMIT 100
```
and then
```
SELECT id FROM process ORDER BY id OFFSET 200 LIMIT 100
```
and so on, that the subsequent queries could return the same rows as the previous, if in between there are updates in the index that have inserted, or (in our case since we order by the id) removed.

**Comment by wchaparro** [comment]
Superceded by ES|QL
