### ISSUE TITLE
FunctionScoreQuery have a direct reference to QueryShardContext

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#73925]
`FunctionScoreQuery` can be cached on a per-segment basis in the Lucene query cache. However a recent [refactoring](https://github.com/elastic/elasticsearch/issues/64017) made them depend on the `QueryShardContext` so the query cache can now keep references to old index readers.
That should be considered as a leak since this memory is not taken into account in the cache size.

**Comment by jimczi** [comment]
One additional comment here is whether we should allow FunctionScoreQuery to be cached. They are meant to produce a score so seeing them in the query cache would be surprising.

**Comment by romseygeek** [comment]
I think we have two options here:
* add an `isCacheable()` method on score functions so that we can choose whether or not to cache a score function query depending on what function it's using
* just disable cacheing entirely

Note that we already have some tests for whether or not this is cacheable at the request layer, but that checks for things like whether `NOW` has been accessed on the execution context so is at a different level.
