### ISSUE TITLE
If java logs a warning then jvm options process gets very confused

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#74158]
**Elasticsearch version** (`bin/elasticsearch --version`): any

**Plugins installed**: none

**JVM version** (`java -version`): 16

**OS version** (`uname -a` if on a Unix-like system): 7.13.1 docker distribution

**Description of the problem including expected versus actual behavior**:
If you can get the jvm to log a warning while its running the `JvmOptionsParser`, like, say, [this one](https://github.com/openjdk/jdk/blob/jdk-16+36/src/hotspot/os/linux/cgroupSubsystem_linux.cpp#L310-L318) then our startup script interprets that warning as a part of the JVM arg line. The JVM doesn't like that. It logs stuff like:
```
[0.001s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /mnt/data/docker/overlay/biglonghash/merged/sys/fs/cgroup/cpuset.
Error: Could not find or load main class [0.001s][warning][os,container]
Caused by: java.lang.ClassNotFoundException: [0/001s][warning][os,container]
```

**Steps to reproduce**:

I'm not sure how to get docker into a state where it'll log that warning, but folks sure seem to be able to do it.

**Comment by pugnascotia** [comment]
Presumably though this isn't specific to Docker? It's just been observed there?

**Comment by nik9000** [comment]
Sorry, yes. I think any jvm log is enough.

**Comment by framsouza** [comment]
does anyone have any updates?

**Comment by ChrisHegarty** [comment]
Here's a straightforward way to reproduce this, i.e. trigger the JVM to log something.

Enable JVM GC logging through the JDK launcher environment variable, e.g.

```
$ export JDK_JAVA_OPTIONS=-Xlog:gc
```

Then run elasticsearch 

```
$ ./distribution/archives/darwin-aarch64-tar/build/install/elasticsearch-8.0.0-SNAPSHOT/bin/elasticsearch --version
warning: ignoring JAVA_HOME=/Users/chegar/binaries/jdk-17.jdk/Contents/Home/; using bundled JDK
NOTE: Picked up JDK_JAVA_OPTIONS: -Xlog:gc
Picked up JAVA_TOOL_OPTIONS: 
[0.003s][info][gc] Using G1
NOTE: Picked up JDK_JAVA_OPTIONS: -Xlog:gc
Picked up JAVA_TOOL_OPTIONS: 
NOTE: Picked up JDK_JAVA_OPTIONS: -Xlog:gc
Picked up JAVA_TOOL_OPTIONS: 
NOTE: Picked up JDK_JAVA_OPTIONS: -Xlog:gc
Picked up JAVA_TOOL_OPTIONS: 
[0.003s][info][gc] Using G1
Error: Could not find or load main class [0.003s][info][gc]
Caused by: java.lang.ClassNotFoundException: [0/003s][info][gc]
```

**Comment by ChrisHegarty** [comment]
There are a number of potential ways to improve things, here's a couple of thoughts / ideas:

1) `JvmOptionsParser` could be updated to emit a PREFIX/SUFFIX around its output. Then `bin/elasticsearch` could use this to filter the output.
2) The `bin/elasticsearch` script could try to temporarily set the various env variables that could affect the java process running `JvmOptionsParser`, in order to prevent it from emitting any JVM logging to stdout.

Both options add some small level of complexity, but generally seem worth it. Option 2 above is likely more fragile than option 1, since it depends on determining all possible (and future) ways to affect JVM logging.

**Comment by nik9000** [comment]
Could it write it's output to a file or a named pipe or something?

**Comment by ChrisHegarty** [comment]
> Could it write it's output to a file or a named pipe or something?

@nik9000 Indeed, that would also be a reasonable way to resolve this.

**Comment by rjernst** [comment]
A named pipe is difficult because it's not easily constructed on Windows. An output file might be possible, to something in ES_TMP_DIR.

**Comment by Hythloday-zero** [comment]
I've still got it occurring in the wild.  IHAC whose 7.16.3 Logstash started/ran just fine on RHEL 7 environment.  Tried upgrade to LS 7.17 and 8.4 but both kicked out the duplicate cpuset error at startup.

Only workaround I've found so far is to `umount /dev/cpuset` (since /sys/fs/cgroup/cpuset is busy (and is the one Picked vs. Skipped).  LS 8.4.2 works fine now, but I'd definitely like to know a graceful way to avoid this in the future.

**Comment by rjernst** [comment]
@Hythloday-zero Please ask questions on [our forum](https://discuss.elastic.co). Closed issues are not normally tracked by developers and your comments can easily be overlooked. More importantly, your issue looks related to Logstash. I suggest you ask there.
