### ISSUE TITLE
Use ES_TMPDIR instead of java.io.tmpdir

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#74163]
We should ignore java.io.tmpdir and override it with ES_TMPDIR. I think that variable should be taken into account from the beginning of startup scripts (including JavaVersionChecker) and the value should be applied as java option to all java processes.

Java processes started before ES_JAVA_OPTS are parsed (JavaVersionChecker, TempDirectory, JvmOptionParser) can also create temporary files in /tmp if not provided with java.io.tmpdir
Most notably `TempDirectory` if ES_TMPDIR is not set will create a temporary dir in that directory - trying to find out system default tmp dir.
`JavaVersionChecker` and TempDirectory are run before JvmOptionParser is executed, hence these cannot know if java.io.tmpdir was set in jvm.options.

**Comment by srisatya1197** [comment]
@pgomulka @rdnm Can I work on this issue?

**Comment by oscarmparedes** [comment]
Hi, could someone explain how can we set the ES_TMPDIR parameter?, where is that value stored? is it only a environment variable, if so, this variable should be set as environment variable for the Elasticsearch user?, thanks. I am asking this because we found that our elastic environments could not start after setting /dev/shm and /tmp dirs to noexec. Setting this parameter in jvm.options to an Elasticsearch owned dir fixed the issue, but I think setting the environment variable is a better solution. Thanks.

**Comment by sankalpawadhiya** [comment]
can I start working on it?

**Comment by pugnascotia** [comment]
We also need to keep in mind #77014, which is very relevant here.

**Comment by tejassinghsital** [comment]
Hi Can i work on this issue or is it already assigned?

**Comment by pugnascotia** [comment]
I don't believe anyone is working on this issue right now.

**Comment by bitNcode** [comment]
@pugnascotia I went through #77285 and its waiting for the pull request to be merged into the master. Can you please advise if this issue is resolved or still open to be resolved. If so then, I would like to look into it and resolve it. Between, I'm looking to contribute to this project for the first time and am very excited to resolve any open issue/bug on this product as a first time contrbutor.

**Comment by pugnascotia** [comment]
#77285 is just about changing the documentation, so the issue here is still valid.

I'm not sure whether we're fully scoped out the required work here - @pgomulka did you do any thinking about what code changes are required? From a brief glance, I'm guessing startup scripts and maybe the CLI launcher classes?

**Comment by bitNcode** [comment]
@pugnascotia Thank you for letting me know about #77285. While going through the comments on this issue, I went through #77014 and #77053 and they are connected to this issue. So, if we solve this issue, then we solve the other 2 issues as well, though #77014 activity log says that it needs libffi library to be at 3.4.2. But, the latest version of JNA is using libffi-3.3.0.  
I'll further study the code and go through the startup script, while the required work is fully scoped out.

**Comment by Quarkspeed** [comment]
Hello!

Is there any way to find the given issue in the master branch?
I am new to Github and can't find the file or module which has to be worked on.

Thanks!

**Comment by mananmehta3** [comment]
Is this issue still open?
I would like to work on it.

**Comment by ridvanenis** [comment]
I think this issue is not valid anymore. There is a block in the **jvm.options** file as below:

`## JVM temporary directory
-Djava.io.tmpdir=${ES_TMPDIR}`

Better to close the issue.

**Comment by pugnascotia** [comment]
@ridvanenis This issue concerns using `ES_TMPDIR` throughout the entire startup process, not just when Elasticsearch starts. The options in `jvm.options` and `jvm.options.d` aren't applied right at the start of the initialisation scripts.

**Comment by rjernst** [comment]
This has been addressed through moving the CLI code to Java. As long as we don't load JNA in the CLI (which we dont' currently do), we should not trigger any tmp dir creation or usage.
