### ISSUE TITLE
HLRC build in master doesn't enforce Java 8 compatibility

### ISSUE THREAD

**Issue by swallez** [elastic/elasticsearch#74289]
**Description of the problem including expected versus actual behavior**:

The Java clients [should be compatible with Java 8](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high-compatibility.html). The work in #73910 introduced the use of `Optional.isEmpty()` in the HLRC code, which was added in Java 11. The build and CI tests accepted this.

When backporting to `7.x` in #74272, the build failed because this method doesn't exist in Java 8 (see commit 1345a05 that fixed it).

So Java 8 compatibility in HLRC isn't enforced in `master` while it is in `7.x`. Comparing `build.gradle` in the two branches did not show anything obvious that could explain this difference.

**Steps to reproduce**:

Add a usage of `Optional.isEmpty()` in `RestHighLevelClient.java`: it compiles in `master` when it should not, and rightly fails to compile in `7.x`.

**Comment by mark-vieira** [comment]
The clients code in Elsaticsearch is targetting Java 11 in `master` because that's the target Java version for _all_ code. There was never any explicit exception for the clients. @costin brought up a good point that the HLRC is mostly a moot point since we intend to replace it with the new client in 8.0. The question remains what we should do about the low level client, since even the new client depends on it. It's not really a lot of code, so we definitely _could_ keep it on Java 8 w/o too much effort. Question is if that's really worth it.

**Comment by swallez** [comment]
Good point regarding HLRC. I opened #74610 to fix the docs.

Regarding LLRC we should indeed keep Java 8 as the baseline since it's also the baseline of the new Java client. 7 years after its release, Java 8 is still widely used and is still an LTS version for several OpenJDK distributions.

**Comment by mark-vieira** [comment]
> Regarding LLRC we should indeed keep Java 8 as the baseline since it's also the baseline of the new Java client. 7 years after its release, Java 8 is still widely used and is still an LTS version for several OpenJDK distributions.

Looks like the LLRC [already targets Java 8](https://github.com/elastic/elasticsearch/blob/b2a183baf00d685c2bcebce28bcbe06a4816cdae/client/rest/build.gradle#L25-L26), so I think we're all good there.

Given the intention to remove the existing HLRC and the fact that the new one supports Java 8 I think we can close this issue.
