### ISSUE TITLE
indices.memory.index_buffer_size is spread evenly across active shards

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#7441]
Right now ```indices.memory.index_buffer_size``` is divided evenly on all active shards on the node.  It'd be more useful for those of us with many shards if we could have more control over how its divided up or if it were just a single pool.  I imagine single pool would be difficult but giving us a knob for weight or minimum size or something on the index level might be more doable.

I'm actually not super sure how important this is from a performance standpoint - but my gut says raising this on my larger, hotter shards will make fewer segments.  Maybe its not that big a deal because the segments stay small any way....

**Comment by l15k4** [comment]
Hey, I have set this setting in [many ways](http://stackoverflow.com/questions/29390654/some-of-elasticsearch-yml-configuration-is-not-taking-effect) but it doesn't seem to be reflected in `_cluser/settings` or in `_settings` for individual indices. Any idea how to do that? Or how to check it's value on a running instance?

**Comment by clintongormley** [comment]
@mikemccand any thoughts about this?

**Comment by mikemccand** [comment]
I agree the static "divide equally on all active shards" is not great since a shard receiving very low docs/sec is unreasonably getting as much IndexWriter buffer as a shard under intense indexing.

Ideally, the allowed RAM would somehow be dynamically shared/tracked across N IndexWriters such that once the total RAM used is too high, Lucene would pick the largest in-memory segment (across all N IndexWriters) and move it to disk.  But this would be a tricky/invasive change to Lucene's APIs...

Maybe in the mean-time we should open up an [expert] setting in Elasticsearch to "bias" how the allowed RAM is divided?  It could be a linear weight, defaulting to 1, and we assign RAM in proportion to that weight divided by the sum of all weights for all shards on this node?

**Comment by clintongormley** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/pull/14121
