### ISSUE TITLE
Support ISO Durations for sum aggregation

### ISSUE THREAD

**Issue by lasiltan** [elastic/elasticsearch#74534]
Durations are often described as [ISO Durations](https://en.wikipedia.org/wiki/ISO_8601#Durations). They are much better than an arbitrary number whose context must be represented in the field name or simply be known.

I often have a need to run sum/histogram aggregations on durations as well as some range queries. I am currently running these queries in Postgres where ISO Duration is supported natively. As I'm moving some of the APIs to use Elasticsearch, I'm finding this lack of ISO Duration support increasingly annoying.

**Comment by lasiltan** [comment]
I could work around this if only Elasticsearch supported a simple script token filter where I could run `Duration.parse(ctx.duration).getSeconds() * 1000`.

**Comment by imotov** [comment]
@lasiltan I would like to better understand your requirements. First of all, I am not quite sure I understand why you formulated this as a "sum aggregation" support issue. From the description and the examples that you have provided, it seems like it spans beyond that and you are looking for additional functionality that also includes histogram aggregations and range support. We do have this support for long fields. So, a typical solution for this problem is to simply convert duration into a number of seconds on ingest and perform the rest of the calculations with seconds instead. For example, you can do it with an indexed runtime field in 7.14:
```
DELETE my-index-000001

PUT my-index-000001/
{
  "mappings": {
    "properties": {
      "duration": {
        "type": "keyword"
      },
      "duration_sec": {
        "type": "long",
        "on_script_error": "fail", 
        "script": {
          "source": """
        emit(java.time.Duration.parse(doc['duration'].value).getSeconds())
        """,
          "params": {
            "multiplier": 4
          }
        }
      }
    }
  }
}

PUT my-index-000001/_doc/1
{
  "duration": "PT30M5S"
}

PUT my-index-000001/_doc/2
{
  "duration": "PT1H"
}

POST my-index-000001/_search
{
  "size": 0,
  "aggs": {
    "total_duration_sec": {
      "sum": {
        "field": "duration_sec"
      }
    }
  }
}
```

**Comment by imotov** [comment]
@lasiltan does this answer satisfies your use case? Should we close the issue?

**Comment by imotov** [comment]
No feedback for a week, closing.
