### ISSUE TITLE
Are there any plans to support collapse in rescore

### ISSUE THREAD

**Issue by yanchaoguo** [elastic/elasticsearch#74595]
currently, Rescore does not support Collapse

**Comment by jtibshirani** [comment]
Hello @yanchaoguo, there were previous requests to support collapsing with rescore: https://github.com/elastic/elasticsearch/issues/27243. We closed this issue as "won't fix" because the way rescoring is designed makes it difficult to integrate with collapsing. It's not likely we'll revisit the decision, but it'd be helpful to for you to give a 'thumbs up' or comment on the original issue to show your interest. I'll close this issue in favor of that one.
