### ISSUE TITLE
Frozen Tier as Alternative Bulk Ingestion

### ISSUE THREAD

**Issue by egalpin** [elastic/elasticsearch#74637]
One of the pain points with maintaining Elasticsearch on time-series data is the need to backfill or reindex large amounts of data if a data model changes or similar. The reindex API is highly useful for this type of work, but in some cases it's much more preferable, or possibly required, to use an external compute engine (Flink, Spark, Dataflow) to compute new doucments and re-transmit to the cluster.  However, in this case, the rate of indexing can become a blocker for large datasets–especially if the cluster is being actively used for other use cases.

With the advent of GA Frozen tier (and Cold tier with partially mounted indices), could it be possible to expose client libraries to create segments externally (ex. via compute engine) and write them to a repository (AWS S3, Google Cloud Storage), then mount or otherwise discover the segments such that they become searchable (either for an index as a whole which never previously existed, or new segments for an existing index)?  Ideally, there would be a workflow for making indexes created this way `fully mountable` such as with Cold Tier data, but even partially mountable would be highly useful for supporting rapid and decoupled reprocessing of data.

**Comment by henningandersen** [comment]
This has come up a few times in the past, see for instance #69769.

A solution that works today is to have a separate cluster for producing such indices/snapshots and then mounting them on the live cluster. Not exactly what you asked for but thought I would mention anyway. Be aware that you have to manage the life time of the snapshots yourself.

We would like to hear back from more users needing this, describing their use case for such a feature in order to help us prioritize this against other important work.

**Comment by original-brownbear** [comment]
No feedback received, closing.
