### ISSUE TITLE
FrozenEngine not working with ES caches

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#74753]
`FrozenEngine` is the engine implementation that we use for the old-style "frozen indices" feature, as well as for the newer searchable snapshots frozen tier. It opens up the Lucene index on demand, i.e., whenever a search comes in, and closes it whenever the index isn't used anymore. This does not play nicely together with the existing cache infrastructure in Elasticsearch. The reason is that request cache, query cache, as well as fielddata cache are using a cache key that's tied to the opened reader object. When the reader is closed, the entries are evicted from the cache, as the cache key is tied to the lifecycle of the reader.

**Comment by tlrx** [comment]
The request cache works with `FrozenEngine` since 7.16.0 (#77694).

The current implementation of the query cache in Lucene is tightly coupled with the `IndexSearcher` which is created and released for every search phase to execute in `FrozenEngine`, causing all cache entries to be evicted after each phase execution. Looking at this more deeply the LRU cache relies on cache keys that are generated by Lucene, per reader, and over which we cannot have control without reimplementing large parts of `LRUQueryCache` and `CachingWrapperWeight`. It's also very questionnable to allow the  `LRUQueryCache` to survive after the `IndexSearcher` is closed in Lucene. 

For the fielddata cache, we think it is less important since segments are likely to be force merged in searchable snapshots.

After discussing with Yannick we agreed on closing this issue as non-fixed.
