### ISSUE TITLE
Transform sets the checkpoint time using current time

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#75035]
When using continous transforms, after the transform is started all new documents should have timestamps (field used on sync) greater then the previous run of the transfrom. Wheras I would expect the date from the timestamp field (used on sync) would be used in next query.

ES version 7.10 and 7.13 (have not checked others)

STEPS TO REPRODUCE
```
POST source_index/_doc
{
          "code" : "123",
          "client_id" : "444",
          "date" : "2021-05-24T10:00:00.000Z",
          "timestamp" : "2021-05-24T10:00:00.000Z"
}
```
```
POST source_index/_doc
{
          "code" : "123",
          "client_id" : "444",
          "date" : "2021-05-25T10:00:00.000Z",
          "timestamp" : "2021-05-25T10:00:00.000Z"
}
```

```
PUT _transform/transformation_1
{
  "source" : {
        "index" : [
          "source_index*"
        ]
  },
      "dest" : {
        "index" : "dest_index"
      },
      "frequency" : "5s",
      "sync" : {
        "time" : {
          "field" : "date",
          "delay" : "5s"
        }
      },
      "pivot" : {
        "group_by" : {
          "client_id.keyword" : {
            "terms" : {
              "field" : "client_id.keyword"
            }
          },
          "date" : {
            "date_histogram" : {
              "field" : "date",
              "calendar_interval" : "1d"
            }
          }
        },
        "aggregations" : {
          "code.keyword.value_count" : {
            "value_count" : {
              "field" : "code.keyword"
            }
          }
        }
      },
      "settings" : {
        "max_page_search_size" : 500
      }
}
POST _transform/transformation_1/_start
```

checking the stats - all fine. two documents are processed. See timestamps translated
```
GET _transform/transformation_1/_stats
#! Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.13/security-minimal-setup.html to enable security.
{
  "count" : 1,
  "transforms" : [
    {
      "id" : "transformation_1",
      "state" : "started",
      "node" : {
        "id" : "ZyBWmsiuQvqAJCalkFqfyA",
        "name" : "xxx",
        "ephemeral_id" : "D0hLKQVnSv-HoDkI7px3Zw",
        "transport_address" : "127.0.0.1:9300",
        "attributes" : { }
      },
      "stats" : {
        "pages_processed" : 2,
        "documents_processed" : 2,
        "documents_indexed" : 2,
        "documents_deleted" : 0,
        "trigger_count" : 6,
        "index_time_in_ms" : 66,
        "index_total" : 1,
        "index_failures" : 0,
        "search_time_in_ms" : 2,
        "search_total" : 2,
        "search_failures" : 0,
        "processing_time_in_ms" : 0,
        "processing_total" : 2,
        "delete_time_in_ms" : 0,
        "exponential_avg_checkpoint_duration_ms" : 251.0,
        "exponential_avg_documents_indexed" : 2.0,
        "exponential_avg_documents_processed" : 2.0
      },
      "checkpointing" : {
        "last" : {
          "checkpoint" : 1,
          "timestamp_millis" : 1625660198751, // GMT: Wednesday, 7 July 2021 12:16:38.751
          "time_upper_bound_millis" : 1625660193751
        },
        "changes_last_detected_at" : 1625660198750, // GMT: Wednesday, 7 July 2021 12:16:38.750
        "last_search_time" : 1625660223767 // GMT: Wednesday, 7 July 2021 12:17:03.767
      }
    }
  ]
}

```

dest_index contains 2 hits

when a new document is inserted and it does not have a `date` field greater then `changes_last_detected_at` then it won't be used in transform.
**Maybe the date `changes_last_detected_at` should be taken from `sync.field`?**
```
POST source_index/_doc
{
          "code" : "123",
          "client_id" : "444",
          "date" : "2021-05-26T10:00:00.000Z",
          "timestamp" : "2021-05-26T10:00:00.000Z"
}      

GET _transform/transformation_1/_stats

{
  "count" : 1,
  "transforms" : [
    {
      "id" : "transformation_1",
      "state" : "started",
      "node" : {
        "id" : "ZyBWmsiuQvqAJCalkFqfyA",
        "name" : "xxx",
        "ephemeral_id" : "D0hLKQVnSv-HoDkI7px3Zw",
        "transport_address" : "127.0.0.1:9300",
        "attributes" : { }
      },
      "stats" : {
        "pages_processed" : 2,
        "documents_processed" : 2,
        "documents_indexed" : 2,
        "documents_deleted" : 0,
        "trigger_count" : 54,
        "index_time_in_ms" : 66,
        "index_total" : 1,
        "index_failures" : 0,
        "search_time_in_ms" : 2,
        "search_total" : 2,
        "search_failures" : 0,
        "processing_time_in_ms" : 0,
        "processing_total" : 2,
        "delete_time_in_ms" : 0,
        "exponential_avg_checkpoint_duration_ms" : 251.0,
        "exponential_avg_documents_indexed" : 2.0,
        "exponential_avg_documents_processed" : 2.0
      },
      "checkpointing" : {
        "last" : {
          "checkpoint" : 1,
          "timestamp_millis" : 1625660198751,
          "time_upper_bound_millis" : 1625660193751
        },
        "operations_behind" : 1,
        "changes_last_detected_at" : 1625660198750,
        "last_search_time" : 1625660463862
      }
    }
  ]
}
```

A dest_index still has 2 hits

However when a new document has a date > last checkpoint it is used in transformation
```
POST source_index/_doc
{
          "code" : "123",
          "client_id" : "444",
          "date" : "2021-07-07T12:18:00.000Z",
          "timestamp" : "2021-05-26T10:00:00.000Z"
}            
```

There is a workaround by using an ingest pipeline when indexing docs

```
PUT _ingest/pipeline/indexed_at
{
  "description": "Adds indexed_at timestamp to documents",
  "processors": [
    {
      "set": {
        "field": "_source.indexed_at",
        "value": "{{_ingest.timestamp}}"
      }
    }
  ]
}
```
and using the field `indexed_at` in the `source.field`

**Comment by hendrikmuhs** [comment]
> When using continous transforms, after the transform is started all new documents should have timestamps (field used on sync) greater then the previous run of the transfrom. Wheras I would expect the date from the timestamp field (used on sync) would be used in next query.

Documentation for the continuous tranform can be found in the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/transform-checkpoints.html).

The field specified in `sync` is used for synchronizing the source and the destination index. The field values are used at for detecting changes using a `range query` with the range `(oldCP, newCP]`.

> when a new document is inserted and it does not have a `date` field greater then `changes_last_detected_at` then it won't be used in transform.

`changes_last_detected_at` is **not** part of checkpointing.

This is not the purpose of the `changes_last_detected_at` stats output. [From](https://www.elastic.co/guide/en/elasticsearch/reference/current/get-transform-stats.html):

```
changes_last_detected_at
    (date) The timestamp when changes were last detected in the source indices. 
```

`changes_last_detected_at` tells you when transform found changes the last time. On purpose this is based on system time.

In similar fashion `last_search_time` tells you when transform _searched_ - tried to find changes - the last time.

The purpose of both fields is to provide users information about proper functioning of transform.

What you are looking for is checkpoiting:

```
      "checkpointing" : {
        "last" : {
          "checkpoint" : 1,
          "timestamp_millis" : 1625660198751, // GMT: Wednesday, 7 July 2021 12:16:38.751
          "time_upper_bound_millis" : 1625660193751
        },
```

Have a look at the 2 timestamp fields:

`timestamp_millis` contains the creation timestamp of the checkpoint.
`time_upper_bound_millis` is the upper bound of the checkpoint. 

You configured:

```
      "sync" : {
        "time" : {
          "field" : "date",
          "delay" : "5s"
        }
```

`time_upper_bound_millis` = `timestamp_millis` - `delay`

-> `1625660198751 - 1625660193751 = 5`

`delay` specifies how far of the timestamp can be due to ingest delays, e.g. if the timestamp is created in an application, you have to think about the worst case time delay that can happen, starting from network transmission, bundling as bulk, queuing, ingest processing and last but not least the lucene refresh interval (default `1s`). The default for default for delay is `60s`.

> There is a workaround by using an ingest pipeline when indexing docs

This is **not** a workaround, but that's what we recommend, see the docs for `sync` [here]( https://www.elastic.co/guide/en/elasticsearch/reference/master/put-transform.html).

Ingest timestamps have the benefit that they reduce the risk of missing data. Imagine a problem in the queue or a network outages, with `delay` on `timestamp` transform can miss data, by using `event.ingested` instead this isn't a problem.

Still timestamp based synchronization is error prone and hard for users. Long term we want to use sequence id's.

I think transform works as designed and this issue is just a misunderstanding. I happily answer follow up questions either here or in slack. We are also open regarding documentation improvements.

Keeping the issue open for now.

**Comment by pgomulka** [comment]
thank you for explanation @hendrikmuhs 

The documentation you directed me and your explanation on ingest timestamps makes it clear to me

I guess we can close the issue
