### ISSUE TITLE
Option for considering shard size for shard distribution 

### ISSUE THREAD

**Issue by A-Hall** [elastic/elasticsearch#75660]
In smaller cluster with indices that have shards of different sizes (consider system indices with small shard sizes), it's possible to get quite lopsided disk utilization per node.  For example, while the shards are evenly distributed across the nodes in the cluster, the disk utilization is quite different on the most utilized and least utilized node.

![image](https://user-images.githubusercontent.com/19538614/126810045-a6e83f23-617d-4b6a-8d8f-08725c5e893c.png)

It would be useful to have an option to distribute the shards based on the shard size vs just distributing the number of shards evenly across the nodes.

**Comment by DaveCTurner** [comment]
This is correct, and indeed it's [documented](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-cluster.html#disk-based-shard-allocation):

> **TIP**: It is normal for the nodes in your cluster to be using very different amounts of disk space...

However, this needs more explanation:

> It would be useful to have an option to distribute the shards based on the shard size vs just distributing the number of shards evenly across the nodes.

Why would this be useful?

**Comment by deckkh** [comment]
One other aspect of this. We have some clusters which are fairly big , going from 20 to 40 nodes. The shards in most of these clusters range from small to large , typical we aim for 30GB , but some small log sources will never reach. Frequently we add more capacity to these clusters.  Fx on the warm phase , we are using around 11 TB of  storage on warm nodes.

However when we add fx 2 more warm nodes , the clusters will always prefer the biggest shards first and move those to the new empty nodes. And eventually we will end up with a cluster that is not in balance , because all the biggest shards are moved first. So the new nodes can end up with 500 GB free, while the remaining warm nodes can have 3-5 TB of free space. And shard count will not be in sync. We are using forced shard allocation awareness to spread the data in our 2 datacenters.

So in order to fix this , we manually exclude the new nodes from the biggest indices/shards so they eventually will get a nice range of small to big shards. Once the clusters ends up in an acceptable state, we remove our manual overrrides.

We have been in contact with support , but we get the answer , that there is is currently no other way to fix. 

We would love tp see that new nodes get a nice workload of randon size shards , not only the biggest shards as it seems now.

**Comment by DaveCTurner** [comment]
> the clusters will always prefer the biggest shards first and move those to the new empty nodes

I don't think there's any preference for moving larger shards first today. I think we just consider shard movements in the order the shards appear in the routing table.

Nor does it answer the question of why you want Elasticsearch to put extra effort in to achieve an even mix of shard sizes on the nodes. Is it just because it's "nice" or are there tangible benefits? Can you quantify them?

**Comment by deckkh** [comment]
It doesn't have to be a perfect mix of shard size. We just strive for our clusters to be more or less in balance in regards to shard count. Adding new nodes frequently lands us in a situation , that is worse than before we added the extra nodes, where we have to make sure , that not all the biggest shards end up up  on the new nodes. 

We will get alerts from the cluster about disk usage and alarms about cluster not being in balance. So this is a real world problem for us.


I am not sure about the routing table , that you mention. can we check the routing table somehow?

Its quite hard to understand , why new nodes gets a lot of big shards , causing them to run out of space , whereas the older nodes have plenty of space. 

Or if we should address problem in a different way , whenever we add capacity.

**Comment by DaveCTurner** [comment]
> We will get alerts from the cluster about disk usage and alarms about cluster not being in balance. So this is a real world problem for us.

Are these alerts built into Elasticsearch or are they something you've developed? What actions do you take when you get an alert about an unbalanced cluster? What bad things happen if you don't take that action?

**Comment by deckkh** [comment]
Its partly Elasticstack disk usage alarms and some checks , we perform every 6 hours., that we wrote ourselves.

When we see this occur , we have a dashboard , that lets us identify disk usage per groups of indices per node. 

Suppose you have these indices

dns-2021.07.20-000028 << rollover
dns-2021.07.25-000029
dns-2021.07.27-000030
firewall-2021.07.27-000330
mydatasource-2021.29 << weekly

we will aggregate into index groups

dns
mydatasource'
firewall

and build a dashboard/table on usage of those per node. So we are able to see total usage and we can bill our customers for disk usage based on this. Bur we can also see how much of an index group is on hot,warm,cold.

We will take top 2-3 of the indices that take up most space on the new nodes. We will then exclude the new nodes from these indices. Cluster will start to move those away onto the older nodes and then smaller shards will be allocated to the new nodes. 

Eventually we will reach a nice balance of shard count and we can remove our exclusions again.

If we dont do this , our clusters will be running unbalanced. With pending disk usage alarms.

**Comment by DaveCTurner** [comment]
> If we dont do this , our clusters will be running unbalanced. With pending disk usage alarms.

I'm struggling to understand the point you're making. Elasticsearch is _designed_ to run with unbalanced disk usage, see the docs I linked earlier, so that's not in itself a problem. It sounds like if you deleted all your alarms then your cluster would still work just fine and you would no longer have any alarms to worry about, which seems like a worthwhile thing to do?

**Comment by deckkh** [comment]
well , I was just hoping/trying to understand the algorithm that Elasticsearch uses to populate new nodes.

Sorry for explaining our problems poorly, appreciate your time :)

**Comment by DaveCTurner** [comment]
Gotcha, we can help you understand this more, but not here on Github which we prefer to use for concrete action items (bug reports etc.). More general questions like that are best asked on the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it.

**Comment by DaveCTurner** [comment]
The OP gave no further details after several weeks so I'm closing this. @A-Hall if you come back with answers to [my earlier question](https://github.com/elastic/elasticsearch/issues/75660#issuecomment-887379186) and we identify some actions to take then we can re-open this.
