### ISSUE TITLE
combined_fields cannot be used be in query_string query. Can we add this functionality

### ISSUE THREAD

**Issue by lasagar** [elastic/elasticsearch#75909]
Per the below posts, combined_fields is introduced to solve the negative IDF in cross_fields. Currently we are using query_string with cross_fields, similar to that can we have combined_fields to be used as a type in query_string.

https://github.com/elastic/elasticsearch/pull/71213

https://github.com/elastic/elasticsearch/issues/41106

**Comment by heebj** [comment]
Are there any plans for this? It would be very helpful in our use case where cross_fields leads to wrong scoring.

**Comment by heebj** [comment]
Any news on this @lasagar ?

**Comment by jtibshirani** [comment]
When designing the `combined_fields` query, we decided that it should only work when all fields have the same analyzer. This is because when fields have different analyzers, there's not a single good way to tokenize the query and compute the combined field score.

For this reason, it doesn't seem like `combined_fields` is a good fit for use in `query_string`. By default, `query_string` searches over all fields. But `combined_fields` can't handle fields with different analyzers (or any non-text based field!) so it would often throw an error. We are thinking about better ways to handle fields with different analyzers, but it's still early.

Are you using `combined_fields` mostly because of the `cross_fields` scoring bug? We actually just fixed this bug (https://github.com/elastic/elasticsearch/pull/89016), maybe that already unblocks you?
