### ISSUE TITLE
multi search REST API endpoint is sensitive to trailing new line

### ISSUE THREAD

**Issue by michaelklishin** [elastic/elasticsearch#7601]
Consider the following multi-search request body:

``` json
{"index":"articles","type":"article"}
{"query":{"match_all":{}},"size":1}
{"index":"people","type":"person"}
{"query":{"match_all":{}},"size":1}
```

If it includes a new line at the end, there will be 2 results returned but if it does not, there will be only 1.

While it is not a major issue, it is fairly counter-intuitive and just took a good couple of hours of my time.

**Comment by pvgoddijn** [comment]
i just found this bug due to a related 'error'

When doing a bulk update with only one record (without the trailing newline) there a error is thrown.
(not very clear this is about a missing newline but it is)

{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: no requests added;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: no requests added;"},"status":400}

This made me realize i was not indexing the final document of my batch updates.

I think the current situation is dangerously misleading and either a warning should be thrown or a newline should be 'assumed' on the end of the input.

Coming from the (Java) RestClient side of this issue i would prefer the assumption of newlines because the JacksonObjectMapper doesnt support adding a newline after every root object, but does support a 'RootValueSeparator' (which is why i fell into this trap and i would assume more Java users will  / would)
