### ISSUE TITLE
Upgrade process requires manual intervention for any installed plugin packages

### ISSUE THREAD

**Issue by jbuchbinder** [elastic/elasticsearch#76317]
**Elasticsearch version** `7.14.0`

**Plugins installed**: `repository-s3`

**JVM version** `openjdk-16`

**OS version** `CentOS 8`

Upgrading from one version of elasticsearch to another will fail if any plugins are installed if the plugins are not manually uninstalled and reinstalled individually. There is no "upgrade" action for plugins, and official plugins need to match the version of elasticsearch.

**Steps to reproduce**:

 1. Install `s3-repository` plugin using `elasticsearch-plugin install s3-repository`
 2. Upgrade elasticsearch via tarball or package
 3. Attempt to start up elasticsearch via systemctl or sysv script. Service will fail to start.

**Comment by jbuchbinder** [comment]
I'm fine with the design requirement that plugins match the version number -- but it seems like a design flaw to require a manual intervention task *by design* for an upgrade which is otherwise automated by package management systems. It's also a serious deficiency that an upgrade requires two separate steps (uninstall and reinstall) with additional user confirmation in between, to be iterated throughout for each plugin.

It's not a "redesign of plugins" issue, but rather a "management of plugins" issue.

**Comment by rjernst** [comment]
Management of plugins is essentially what the linked declarative plugin management issue is about. The redesign of plugins is necessary to break the requirement that version numbers match. As long as they must match, the uninstall/reinstall must happen in order to bring the plugin up to date with the current version of Elasticsearch. So you are right, they are two separate issues, and we are addressing them separately.

**Comment by jbuchbinder** [comment]
I feel as if I'm not explaining the issue properly.

I'm not asking for the plugin architecture to be rethought, but one of several relatively simple solutions to be considered:

1. There should be an "upgrade" or "reinstall" options for `elasticsearch-plugin`. Two commands required to upgrade a single plugin is pretty crazy.
2. An `elasticsearch-plugin` command to upgrade or reinstall *all* plugins wouldn't be the worst idea. Iterate through all plugins, and perform an uninstall and reinstall.
3. Potentially automating the second one in RPM or DEB package upgrades.

**Comment by rjernst** [comment]
> There should be an "upgrade" or "reinstall" options for elasticsearch-plugin. Two commands required to upgrade a single plugin is pretty crazy.

That is implicitly asking for a re-architecture (though different than what I was referring to above). Plugins can come from URLs, or even zip files directly. We do not keep the original location a plugin was installed from, and even if we did, we can't always figure out what the location would be for the new version of Elasticsearch (only official plugins can be depended on to match Elasticsearch's version scheme). However, this is exactly what the declarative plugin management I linked above is meant to solve (in a limited way).

> An elasticsearch-plugin command to upgrade or reinstall all plugins wouldn't be the worst idea. Iterate through all plugins, and perform an uninstall and reinstall.

Tthis can only work for official plugins, and declarative plugin management will essentially solve this. But from the low level, plugins still must be removed and installed (note that I did not use reinstalled here because it is not the same plugin, it is a new version).

> Potentially automating the second one in RPM or DEB package upgrades.

This might be possible in the future, once declarative plugin management is available, though I have not thought through the implications.

**Comment by jbuchbinder** [comment]
Looking back on this ticket, it wouldn't be the worse idea to have an "upgrade" command which attempts to upgrade official plugins and simply skips or ignores ones that it cannot resolve. If the behavior falls back to skipping upgrades (which is essentially what we're seeing now), it would at least automate away the majority of use-cases for a semi-automated upgrade (which are official plugins which need to be upgraded as they will not work with revisions of the product which are different that their version number, AFAIK).

**Comment by williamrandolph** [comment]
We've implemented declarative plugin management for our official Docker images: https://www.elastic.co/guide/en/elasticsearch/plugins/8.3/manage-plugins-using-configuration-file.html

The configuration file allows users to specify where new versions of non-official plugins should come from. As far as I know, we aren't planning to make this available for deb/RPM or archive installations, but I think we would prefer a solution like this to a tool option that is only capable of partial upgrades when there is a custom or third-party plugin.

We are actively working on a new architecture for plugins that will get rid of the requirement that plugins have the same version as Elasticsearch. In the long term, this will mean not only that plugin users won't need to remove old plugins and install new versions, but that plugin developers won't need to recompile their plugins for every minor release of Elasticsearch.
