### ISSUE TITLE
SQL: Cannot use multiple date math expression filters in disjunction

### ISSUE THREAD

**Issue by Luegg** [elastic/elasticsearch#76336]
The following SQL query works as expected up to Elasticsearch 7.10.0:

```
POST _sql
{
  "query":"SELECT COUNT(*) FROM testindex WHERE (timestamp='now-1d/d' OR timestamp='now-2d/d')"
}
```

However, starting with 7.11.0 it fails with:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "ql_illegal_argument_exception",
        "reason" : "cannot cast [now-1d/d] to [datetime]: Text 'now-1d/d' could not be parsed at index 0"
      }
    ],
    "type" : "ql_illegal_argument_exception",
    "reason" : "cannot cast [now-1d/d] to [datetime]: Text 'now-1d/d' could not be parsed at index 0",
    "caused_by" : {
      "type" : "date_time_parse_exception",
      "reason" : "Text 'now-1d/d' could not be parsed at index 0"
    }
  },
  "status" : 500
}
```

The issue has most likely been introduced with https://github.com/elastic/elasticsearch/pull/65353

**Comment by costin** [comment]
A workaround for this issue is to do the string computation with SQL directly through the [date time functions](https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-functions-datetime.html#sql-functions-current-date):
`WHERE timestamp= 'now-1d/d' ` becomes `WHERE timestamp = TODAY() - INTERVAL 1 DAY`
