### ISSUE TITLE
[ML] Incorrect mappings for `model_bytes_memory_limit` and `model_bytes_exceeded` fields

### ISSUE THREAD

**Issue by darnautov** [elastic/elasticsearch#76404]
**Elasticsearch version** (`bin/elasticsearch --version`):
latest master

**Description of the problem including expected versus actual behavior**:

Default index for storing results `.ml-anomalies-shared*` contains incorrect `keyword` type for `model_bytes_memory_limit` and `model_bytes_exceeded` fields instead of `long`. Might be some other fields need mappings adjustments as well.

**Comment by dimitris-athanasiou** [comment]
Note those fields are part of the `model_size_stats` object.

**Comment by droberts195** [comment]
We cannot fix the mapping type because there will be indices in production that have these mappings and it's impossible to change the mappings for an existing index.

For system indices we are now protected against this problem of forgetting to add mappings, but not for the hidden indices like our results indices for example.

In our results indices any fields we forget to add mappings for in the version where they are first added have to be mapped as `keyword` forever.  This doesn't really matter if users retrieve the data via ML APIs or by getting `_source` from search hits, and don't reference the fields in search query conditions.  For `model_bytes_memory_limit` and `model_bytes_exceeded` this is likely as they should be retrieved via the ML anomaly detection job stats API, not by direct search.
