### ISSUE TITLE
Missing Javadocs

### ISSUE THREAD

**Issue by CoolKangaroo2022** [elastic/elasticsearch#76602]
Hello! I find in your [CONTRIBUTING.md](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#javadoc) that 
> New classes and interfaces must have class-level Javadoc that describes their purpose. 
> New public methods must have Javadoc, because they form part of the contract between the class and its consumers.

However, I still witness some public classes without Javadocs, and even public methods without Javadocs, e.g.,
* server/src/internalClusterTest/java/org/elasticsearch/snapshots/CustomMetadataSnapshotIT.java
* server/src/main/java/org/elasticsearch/monitor/MonitorService.java
* server/src/main/java/org/elasticsearch/index/warmer/WarmerStats.java
...

Would you like to add Javadoc for these methods or classes, or they are just not that important?
If there is anything I can help with?

**Comment by pugnascotia** [comment]
@CoolKangaroo2022 The guidelines around Javadoc were added relatively recently in the history of the Elasticsearch project, so there is a large amount of code that lacks Javadoc. If you feel that you understand a part of the codebase well enough to write useful Javadoc, then your contribution would be most welcome. However for many classes, it probably wouldn't be worth your time to learn the code well enough to document. This is also true for tests, since although it is valuable to have Javadoc that succinctly describes each test case, you need to confident that you understand each case.

A better approach would be to find another issue, e.g. a bug fix or small enhancement, and add Javadoc to the code that has to be changed to address the issue.

I hope you don't mind if I close this issue, since there's no specific action that we want to take around Javadoc at this time.
