### ISSUE TITLE
Design Grid for Dashboard Edits

### ISSUE THREAD

**Issue by jesse-ECS** [elastic/elasticsearch#77135]
Pease add a ruled grid in the design view so that visualizations and tables can be resized to a measured specification.

**Comment by not-napoleon** [comment]
Hi!  Thanks for your interest in the Elastic Stack.  This looks to me like an issue for Kibana, not Elasticsearch, since it deals with the visualization layer and not the data storage layer.  Please open this over in the [Kibana repo](https://github.com/elastic/kibana) instead.  I'm going to close this here because we can't actually address this on the Elasticsearch side.
