### ISSUE TITLE
QueryBuilders.termsQuery Compile error

### ISSUE THREAD

**Issue by LukLau** [elastic/elasticsearch#77223]
**Elasticsearch Client version** (`elasticsearch-rest-high-level: 7.2.0`):

**Plugins installed**: []

**JVM version** (`jdk1.8`):

**OS version** (`centOs` ):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 0. param: fieldName: "merchantId" value: Object
 1.  use BoolQueryBuilder boolQueryBuilder = QueryBuilders.boolQuery();
 2. use boolQueryBuilder.must(QueryBuilders.matchQuery(fieldName, value));
 3. es-server tell client compile error
 4. "type":"parsing_exception","reason":"[terms] unknown token [END_ARRAY] after [goodsInfo.merchantId]"

**my question**
By **TermsQueryBuilder this(fieldName, values != null ? Arrays.asList(values) : null)**,

I find that if it thinks value! =null, the client will directly use asList to generate a list, and if the value itself is a list type, it will generate a two-dimensional list,
I think this step is missing a layer of judgment.

As the ES query client, can the ES-client perform a layer conversion within term/terms for specific value types? As an application access party, I think our application should not make specific type judgment, but be considered and transformed by the es-Client layer

**Provide logs (if relevant)**:
1. method param pic
![image](https://user-images.githubusercontent.com/20536583/131945405-2622ddb5-c3e8-4647-b983-4444078ac5eb.png)

2. real param value pic
![image](https://user-images.githubusercontent.com/20536583/131945458-e0bc21b1-3cd5-4757-ba3e-c83a6daed15b.png)

3. the final sql 

![image](https://user-images.githubusercontent.com/20536583/131945516-50073b73-152e-4b7d-80f1-1b32bcfac9b8.png)

4. the error pic
![image](https://user-images.githubusercontent.com/20536583/131945740-67b994f8-e50e-4164-9e07-562ae4cd4bc1.png)

**Comment by cbuescher** [comment]
The underlying issue here is that that a `terms` query with an array as value doesn't make sense and won't work, but we didn't use to error on it but simply treated the stringified verion of that array list as the term to search (which obviously is not giving the desired results). The immediate solution here would be to unpack the list on the client side and search for the individual values instead. For the underlying problem we have https://github.com/elastic/elasticsearch/issues/71972 that tracks removing the ability to use the terms query builder in such a way. I think we can close this and track the work in that issue. Please let me know if there are further questions.
