### ISSUE TITLE
Allow default (dynamic) time for date mappings

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#7732]
It would be convenient if the date field could be configured to provide a default time (likely `now()`).  It would make sense if this was an extension to `null_value` which has specific, dynamic functionality for a date field.

**Comment by bobbyhubbard** [comment]
With `_timestamp` being deprecated this is a must have moving forward. We have usecases were we can't trust (or more likely dont have) the timestamp of the original document. We want the timestamp when ES last indexed it.

Maybe instead of adding confusion to `null_value`, maybe you could add a new type? For example, a new type called `timestamp` would always default the current timestamp into a stored field outside of the `_source`

This would update the stored field whenever the document is indexed. Another possible usecase might be to insert the timestamp only the FIRST time the document is indexed...which means if its set, dont update it on subsequent updates of the document. No idea how to name that...maybe `timestamp_once`?

**Comment by martijnvg** [comment]
@bobbyhubbard I think the way forward is by using the ingest node (#14049) when it gets available.

Adding a timestamp to a document would look like this:
1) Setup a pipeline with a `set` processor that uses the ingest timestamp:

```
PUT _ingest/pipeline/1
{
  "processors" : [
    {
      "set" : {
        "your_timestamp_field" : "{{_ingest.timestamp}}"
      }
    }
  ]
}
```

2) Make index/bulk requests use this pipeline:

```
PUT /index/type/id?pipeline_id=1
{
...
}
```

**Comment by PhaedrusTheGreek** [comment]
+1

**Comment by clintongormley** [comment]
Closing in favour of #14049
