### ISSUE TITLE
_terms_enum not supporting fields by alias for non-super user

### ISSUE THREAD

**Issue by bhavyarm** [elastic/elasticsearch#77508]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.14.1 /7.15.0

**OS version** (`uname -a` if on a Unix-like system): darwin_x86_64

**Description of the problem including expected versus actual behavior**: _terms_enum stopped supporting fields by alias.

This bug is the result of an SDH and discuss post - https://discuss.elastic.co/t/kibana-filter-window/283522

**Steps to reproduce**:
 1.  Create an alias to index pattern
 2. Create a user with a role with all privileges to the alias from the first step.
 3. Login with that user and try to create a filter - filter values are not getting populated. 

This works in 7.13.4 and in 7.15.0 - this works if I change autocomplete:valueSuggestionMethod to terms_agg from terms_enum (default) in Kibana advanced settings.

Here is the Kibana bug -  https://github.com/elastic/kibana/issues/111642

**Comment by markharwood** [comment]
From the terms_enum design docs:

>we do not plan to support Document-Level-Security or other forms of doc-level filtering

The issue with the new (fast) implementation is that it relies on quickly reading terms directly from Lucene's alphabetically sorted index without checking if the docs that contain those terms are accessible to the end user. Based on this "unfiltered" assumption, things like document-level security or filters associated with aliases can't be supported and no results are returned in these scenarios.

**Comment by LeeDr** [comment]
@markharwood this isn't a doc level security or filtering issue.  

The issue is that the _terms_enum endpoint when called with an alias, seems to check the user's privs first on that alias, and then also on the index.  And in these cases (SDH's from upgrades, etc.) the users only had privs on the alias.

@bhavyarm has some logs she could post here from Elasticsearch audit logging which shows access_granted on the alias and then access_denied on the index.  From the Kibana query log, we only see Kibana querying using the alias.

**Comment by bhavyarm** [comment]
I updated the headline. Sorry. 

Here are the logs when user has privileges only on alias and not on index for which alias is created:

```
tail -f logs/elasticsearch_audit.json | grep -v kibana_system
{"type":"audit", "timestamp":"2021-09-09T13:19:10,327-0400", "node.id":"LmlU7USXTdGwFxyJl-70Dg", "event.type":"transport", "event.action":"access_granted", "authentication.type":"REALM", "user.name":"telefonica", "user.realm":"default_native", "user.roles":["telefonica"], "origin.type":"rest", "origin.address":"127.0.0.1:56028", "request.id":"wcpSesdoR1y6rj64vTU1yQ", "action":"cluster:admin/xpack/security/user/authenticate", "request.name":"AuthenticateRequest"}
{"type":"audit", "timestamp":"2021-09-09T13:19:10,331-0400", "node.id":"LmlU7USXTdGwFxyJl-70Dg", "event.type":"transport", "event.action":"access_granted", "authentication.type":"REALM", "user.name":"telefonica", "user.realm":"default_native", "user.roles":["telefonica"], "origin.type":"rest", "origin.address":"127.0.0.1:56028", "request.id":"2tomDDQyTTiDS_UqJvWrbA", "action":"indices:data/read/xpack/termsenum/list", "request.name":"TermsEnumRequest", "indices":["indextest"], "opaque_id":"c72d3312-7d32-4ccf-af7c-d0e1e545071e"}
{"type":"audit", "timestamp":"2021-09-09T13:19:10,332-0400", "node.id":"LmlU7USXTdGwFxyJl-70Dg", "event.type":"transport", "event.action":"access_denied", "authentication.type":"REALM", "user.name":"telefonica", "user.realm":"default_native", "user.roles":["telefonica"], "origin.type":"rest", "origin.address":"127.0.0.1:56028", "request.id":"2tomDDQyTTiDS_UqJvWrbA", "action":"indices:data/read/xpack/termsenum/list[s]", "request.name":"NodeTermsEnumRequest", "indices":["aliasindex"], "opaque_id":"c72d3312-7d32-4ccf-af7c-d0e1e545071e"}

```

Logs when user has all privileges on both alias and index:
```
tail -f logs/elasticsearch_audit.json | grep -v kibana_system
{"type":"audit", "timestamp":"2021-09-09T13:20:59,456-0400", "node.id":"LmlU7USXTdGwFxyJl-70Dg", "event.type":"transport", "event.action":"access_granted", "authentication.type":"REALM", "user.name":"telefonica", "user.realm":"default_native", "user.roles":["telefonica"], "origin.type":"rest", "origin.address":"127.0.0.1:56022", "request.id":"bPI9HYmaTCqNvbtJnBI0Zw", "action":"cluster:admin/xpack/security/user/authenticate", "request.name":"AuthenticateRequest"}
{"type":"audit", "timestamp":"2021-09-09T13:20:59,459-0400", "node.id":"LmlU7USXTdGwFxyJl-70Dg", "event.type":"transport", "event.action":"access_granted", "authentication.type":"REALM", "user.name":"telefonica", "user.realm":"default_native", "user.roles":["telefonica"], "origin.type":"rest", "origin.address":"127.0.0.1:56022", "request.id":"m9rb1C2DQ0OqF0d4OpDU2w", "action":"indices:data/read/xpack/termsenum/list", "request.name":"TermsEnumRequest", "indices":["indextest"], "opaque_id":"00b275ff-32f8-432e-bf69-3f2ca57dad38"}
{"type":"audit", "timestamp":"2021-09-09T13:20:59,459-0400", "node.id":"LmlU7USXTdGwFxyJl-70Dg", "event.type":"transport", "event.action":"access_granted", "authentication.type":"REALM", "user.name":"telefonica", "user.realm":"default_native", "user.roles":["telefonica"], "origin.type":"rest", "origin.address":"127.0.0.1:56022", "request.id":"m9rb1C2DQ0OqF0d4OpDU2w", "action":"indices:data/read/xpack/termsenum/list[s]", "request.name":"NodeTermsEnumRequest", "indices":["aliasindex"], "opaque_id":"00b275ff-32f8-432e-bf69-3f2ca57dad38"}
^C
```

**Comment by markharwood** [comment]
Fundamentally the terms_enum API relies on how the security framework behaves. 

>when called with an alias, seems to check the user's privs first on that alias, and then also on the index.

I do recall the security team contemplating dropping aliases at one point due to the potential for conflicting rules on aliases and underlying indices. This may be an example. The TermsEnum api implementation calls the security framework for targeted indices and only if the security framework returns with the response that _all_ documents are accessible will it then attempt to return field value suggestions.
I can take a closer look tomorrow.

**Comment by lukasolson** [comment]
Just wanted to add a follow-up here:

I've configured an index alias that points to specific indices. I created a role that has access to the alias (but not the underlying indices themselves).

I am able to do a terms aggregation against the alias and get results, but when I try to do a `_terms_enum` call to that alias, no results are returned.

Just wanted to clarify the issue here 😄

**Comment by markharwood** [comment]
>I am able to do a terms aggregation against the alias and get results, but when I try to do a _terms_enum call to that alias, no results are returned.

Incidentally, note that this is the expected behaviour if you happen to have DLS enabled on an index - aggs will work, terms_enum will not. Regardless of any aliases. I'm not saying that DLS rules are behind this issue here - just a heads up.

Do we have a minimal reproduction of the index/alias/role definitions/example doc and terms enum request that can be shared here?
Just want to make sure I'm testing the right thing.

**Comment by markharwood** [comment]
@jimczi has kindly looked into this and identified that we can resolve the issue with a code change (taking alias names as well as physical index names in requests sent down to data nodes).

In terms of interim workarounds for current versions we have two:
1) Use the Kibana switch to use the old terms-agg based completion or
2) Replicate the permissions assigned to the alias to any of its underlying indices

**Comment by lukasolson** [comment]
@markharwood Do we have any sense of when this work will be prioritized? Is this something we could try to squeeze into 7.15?
