### ISSUE TITLE
ES 7.10.2 doesn't supports TLSv1.3

### ISSUE THREAD

**Issue by mitct23** [elastic/elasticsearch#78157]
I've installed Elasticsearch v7.10.2 in an environment with Java11.
In the documentation, it's mentioned that [TLS v1.3](https://www.elastic.co/guide/en/elasticsearch//reference/7.x/jdk-tls-versions.html) is supported on JDK11. But the [jdk.tls.client.protocols](https://github.com/elastic/elasticsearch/blob/v7.10.2/gradle.properties#L15) is configured to support only TLSv1.2.
While I'm trying to connect ES with TLSv1.3, it throws this error.

**curl "${CURL_OPTIONS[@]}" https://localhost:9200/ -v --tlsv1.3**

**O/P:**

* Trying ::1:9200...
* TCP_NODELAY set
* Connected to localhost (::1) port 9200 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /ca.crt
* CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS alert, protocol version (582):
* error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version
* Closing connection 0
* curl: (35) error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version

**javax.net.ssl.SSLHandshakeException: The client supported protocol versions [TLSv1.3] are not accepted by server preferences [TLS12]**

**Comment by tvernum** [comment]
> In the documentation, it's mentioned that TLS v1.3 is supported on JDK11.

The documentation is correct. All builds of JDK11 that Elasticsearch supports include TLS v1.3 
- https://www.oracle.com/java/technologies/javase/11-relnote-issues.html#JDK-8145252

> But the jdk.tls.client.protocols is configured to support only TLSv1.2.

What you are pointing to is a Gradle build, with configuration about which TLS version gradle should use when it makes network connections. It has no impact on the version of Elasticsearch you download.

---

I can run Elasticsearch 7.10.2 on JDK11 with TLS1.3 with only the most basic of configuration changes (to enable SSL)

- I am running the latest Temurin/Adoptium release of Java 11
   > [2021-09-23T12:17:41,278][INFO ][o.e.n.Node               ] [nodename] version[7.10.2], pid[76579], build[default/tar/747e1cc71def077253878a59143c1f785afa92b9/2021-01-13T00:42:12.435326Z], OS[Mac OS X/10.15.7/x86_64], JVM[Eclipse Foundation/OpenJDK 64-Bit Server VM/11.0.12/11.0.12+7]

- My elasticsearch.yml is as simple as possible (http.p12 was generated by `elasticserch-certutil http`)
   ```
   xpack.security.enabled: true
   xpack.security.http.ssl.enabled: true
   xpack.security.http.ssl.keystore.path: "http.p12"
   ```
- I can curl using TLSv1.3
   ```
    curl https://localhost:9200/ -v --tlsv1.3 -k
    *   Trying 127.0.0.1:9200...
    * Connected to localhost (127.0.0.1) port 9200 (#0)
    * ALPN, offering h2
    * ALPN, offering http/1.1
    * TLSv1.3 (OUT), TLS handshake, Client hello (1):
    * TLSv1.3 (IN), TLS handshake, Server hello (2):
    * TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
    * TLSv1.3 (IN), TLS handshake, Certificate (11):
    * TLSv1.3 (IN), TLS handshake, CERT verify (15):
    * TLSv1.3 (IN), TLS handshake, Finished (20):
    * TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
    * TLSv1.3 (OUT), TLS handshake, Finished (20):
    * SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
    * ALPN, server did not agree to a protocol
    * Server certificate:
    *  subject: CN=localhost
    *  start date: Sep 23 02:12:30 2021 GMT
    *  expire date: Sep 23 02:12:30 2026 GMT
    *  issuer: CN=Elasticsearch HTTP CA
    *  SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
    > GET / HTTP/1.1
    > Host: localhost:9200
    > User-Agent: curl/7.78.0
    > Accept: */*
    >
    * TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
    * Mark bundle as not supporting multiuse
    < HTTP/1.1 401 Unauthorized
    < WWW-Authenticate: Basic realm="security" charset="UTF-8"
    < WWW-Authenticate: Bearer realm="security"
    < WWW-Authenticate: ApiKey
    < content-type: application/json; charset=UTF-8
    < content-length: 459
    <
    * Connection #0 to host localhost left intact
    {"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer realm=\"security\"","ApiKey"]}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer realm=\"security\"","ApiKey"]}},"status":401}%
   ```

---

Whatever issue you're running into, it appears to be specific to your environment.
I don't think there is an Elasticsearch bug here, and I think we simply need to walk through your configuration and determine what it is that is preventing TLSv1.3 from working for you.

GitHub isn't the right place for those diagnosis conversations, so if you want to open a topic on our [discussion forums](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6), we can help you out and if it turns out there is a bug, or some documentation we can improve then we can reopen this issue to track those changes.
