### ISSUE TITLE
[CI] CompositeAggregatorTests testRandomLongs failing

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#78919]
**Build scan:**
https://gradle-enterprise.elastic.co/s/uqiesaacvzq7g/tests/:server:test/org.elasticsearch.search.aggregations.bucket.composite.CompositeAggregatorTests/testRandomLongs

**Reproduction line:**
`./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.bucket.composite.CompositeAggregatorTests.testRandomLongs" -Dtests.seed=DB61B511F6F236FA -Dtests.locale=de-CH -Dtests.timezone=Antarctica/Casey -Druntime.java=11`

**Applicable branches:**
master

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.search.aggregations.bucket.composite.CompositeAggregatorTests&tests.test=testRandomLongs

**Failure excerpt:**
```
java.lang.OutOfMemoryError: Java heap space


```

**Comment by ywangd** [comment]
This failure for `CompositeAggregatorTests.testRandomStrings` is likely due to the same underlying issue. Error message is: 
> java.lang.OutOfMemoryError: Java heap space

Build scan: https://gradle-enterprise.elastic.co/s/y2zillkv3lvw6/tests/:server:test/org.elasticsearch.search.aggregations.bucket.composite.CompositeAggregatorTests/testRandomStrings?top-execution=1

Reproducible locally with : 
> ./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.bucket.composite.CompositeAggregatorTests.testRandomStrings" -Dtests.seed=8E4872DF11193E13 -Dtests.locale=it -Dtests.timezone=Asia/Qatar -Druntime.java=11
