### ISSUE TITLE
Highlighting - snippets too long for phrase queries on fields using english analyzer

### ISSUE THREAD

**Issue by jurgc11** [elastic/elasticsearch#7944]
I've found an issue which is very similar to https://github.com/elasticsearch/elasticsearch/issues/4605 (which I can confirm is fixed in Elasticsearch 1.3.4).

If I set the field to use the english analyzer the snippet is far longer than it should be when using a phrase with a query_string query. 

I've modified the test case from #4605 here: https://gist.github.com/jurgc11/139b6ae8a177dfd8a2f2.

**Comment by lukhnos** [comment]
I ran into the same issue with ElasticSearch 1.5. There is a recently reopened Lucene bug ([LUCENE-2229](https://issues.apache.org/jira/browse/LUCENE-2229)) that should be the root cause – a boundary condition in `SimpleSpanFragmenter`. Since the setup above [requires `SimpleSpanFragmenter` to be used](https://github.com/elastic/elasticsearch/blob/c6182cbd3799c9ea25cf0716be541e01f101b025/core/src/main/java/org/elasticsearch/search/highlight/PlainHighlighter.java#L81) and since `PlainHighlighter` in master still hits the same code path, I believe the bug still manifests itself in the latest version of ElasticSearch.

**Comment by clintongormley** [comment]
This is still broken with the unified highlighter in #21621
