### ISSUE TITLE
`ClusterHealthRequestTests.testBwcSerialization` shouldn't be a unit test

### ISSUE THREAD

**Issue by arteam** [elastic/elasticsearch#79454]
There is a specific set of tests which deals with BWC according to the backward compatibility guarantees of ES as a product. `testBwcSerialization` manually checks the compatibility all the way back to 7.2.0.

**Comment by DaveCTurner** [comment]
I'm relabelling this as `>test-failure` since it represents a muted test that needs further action, and adding an area label. That way it'll be tracked in the team's test failures report. (I see why `>test-mute` looked like the right choice in this case but actually this label is just for PRs that mute tests).
