### ISSUE TITLE
Users are confused by disconnected remote clusters

### ISSUE THREAD

**Issue by cjcenizal** [elastic/elasticsearch#80146]
If a local cluster connected to a remote cluster, and the remote cluster goes down and is then recovered, the local cluster's [Remote cluster info API](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-remote-info.html) shows the remote cluster as disconnected until:

* Either a node disconnects and some other node is available at the time of disconnection
* Or there are no connected nodes and a cross-cluster request is send from the local cluster

It seems users expect to use the Kibana Remote Clusters UI as an overview of the status of remote clusters, which is an unmet expectation due to this behavior. We can attempt to clarify/address the behavior in the UI (https://github.com/elastic/kibana/issues/116961), but I wonder if there's a way to address this on a fundamental level? Can a local cluster and remote cluster "reconnect" as they are brought offline and back online without requiring the above events?

CC @DaveCTurner

**Comment by kingherc** [comment]
We briefly took a look at this with @tlrx . We saw there is a [`cluster.remote.<cluster_alias>.transport.ping_schedule` setting](https://www.elastic.co/guide/en/elasticsearch/reference/8.3/remote-clusters-settings.html) that defaults to -1 because of TCP keep-alives. But even this setting might not understand if a remote cluster becomes connectable again after some time. We may need to investigate if we can implement some periodic connection retry method.

**Comment by mbarretta** [comment]
I'm also seeing this issue among our users. Progress here and on the linked Kibana issue would be welcome!

**Comment by DaveCTurner** [comment]
> We may need to investigate if we can implement some periodic connection retry method.

I wonder if we should call `org.elasticsearch.transport.RemoteClusterService#ensureConnected` during the execution of `GET _remote/info`. It'd need to time out reasonably quickly (10s? 30s?) in case the remote cluster is still unresponsive, but that would make the response less surprising in the case that the remote cluster is available again.

**Comment by tylerperk** [comment]
A customer mentioned this today in a call: "Is there a CCS keep-alive built into the product? For instance, we ran into issues where the networking changed but CCS status still showed healthy. Which indicates the status isn't an active status.  So two things...
1) Monitor TCP/IP keep-alives
2) Build in a application level poll mechanism to ensure status is accurate"

**Comment by DaveCTurner** [comment]
> the networking changed but CCS status still showed healthy

Not really sure what this means. Elasticsearch already sends TCP keepalives by default, so it will detect a lost connection reasonably quickly, and it will also auto-reconnect on a disconnect, so we would expect it to notice a change in the network and remain healthy.

There is also an application-level polling mechanism but the facilities provided by the OS (especially TCP keepalives and [proper retransmission config](https://www.elastic.co/guide/en/elasticsearch/reference/current/system-config-tcpretries.html)) are always going to do a better job than anything we can do in userspace.

**Comment by naj-h** [comment]
@cjcenizal To determine the "Remote clusters" status, Kibana now (https://github.com/elastic/kibana/pull/183593) leverages [the /_resolve/cluster API](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-resolve-cluster-api.html) instead of GET /_remote/info. This should ensure that the status is always the latest without requiring a search query to be ran. You are welcome to test this out in an 8.15 cluster and share any comments you might have!
