### ISSUE TITLE
Improve deprecation log traceability

### ISSUE THREAD

**Issue by cjcenizal** [elastic/elasticsearch#80232]
## Problem

Upgrade Assistant surfaces ES deprecation logs, but it's a guessing game to figure out which requests are triggering them, and which part of a codebase is sending those requests.

## Solution

If I could wave a magic wand, I'd like to see the API request which triggered the deprecation warning. If we could also show the headers that were sent with the request we could specify custom headers to be precisely pinpoint where the request originates in the application code.

**Comment by sebelga** [comment]
From my testing of the Upgrade assistant UI this looks like a bug. The Upgrade assistant UI job is to help our users upgrade to `8.0` and we are failing to do so as we don't provide enough information to the user to fix a deprecation.

In my current testing I am receiving the following critical warning:

```
[deprecation.elasticsearch][CRITICAL] this request accesses system indices: [.tasks], but in a future major version, direct access to system indices will be prevented by default
```

This is the detailed deprecation in the UI

<img width="880" alt="Screenshot 2021-11-04 at 16 03 47" src="https://user-images.githubusercontent.com/2854616/140375498-3dad387a-2ee7-423e-af19-3c4f5e2808b0.png">

<img width="847" alt="Screenshot 2021-11-04 at 16 04 03" src="https://user-images.githubusercontent.com/2854616/140375503-3b50d727-3cbc-4b37-9cdc-54fe8ed7447d.png">

Unfortunately our user don't have enough information to fix that problem and trace back to their application code that needs to be updated in order to fix the problem and upgrade to `8.0`.

**Comment by williamrandolph** [comment]
I took a quick look at the code around the deprecation warning in the example here. It would take some work to add the request itself to the log message, but the deprecation code already supports the `X-Opaque-Id` header. We have some public documentation around that header. For example: https://www.elastic.co/guide/en/elasticsearch/reference/7.15/tasks.html#_identifying_running_tasks

```
$ curl -ski --user elastic:password -H 'X-Opaque-Id: 123' 'localhost:9200/.security-7'
[...]

$ cat logs/elasticsearch_deprecation.json
{
  "@timestamp": "2021-11-04T18:02:28.330Z",
  "log.level": "CRITICAL",
  "data_stream.dataset": "deprecation.elasticsearch",
  "data_stream.namespace": "default",
  "data_stream.type": "logs",
  "ecs.version": "1.7",
  "elasticsearch.event.category": "api",
  "elasticsearch.http.request.x_opaque_id": "123",    <---- OPAQUE ID in deprecation log
  "event.code": "open_system_index_access",
  "message": "this request accesses system indices: [.security-7], but in a future major version, direct access to system indices will be prevented by default",
  "service.name": "ES_ECS",
  "process.thread.name": "elasticsearch[Williams-MacBook-Pro.local][system_critical_read][T#1]",
  "log.logger": "org.elasticsearch.deprecation.cluster.metadata.IndexNameExpressionResolver",
  "event.dataset": "deprecation.elasticsearch",
  "elasticsearch.cluster.uuid": "sSqwo5FTSXmASQ88wxGIHQ",
  "elasticsearch.node.id": "gyCLSR7PT_mNzkIpwo1Ocw",
  "elasticsearch.node.name": "Williams-MacBook-Pro.local",
  "elasticsearch.cluster.name": "elasticsearch"
}
```

**Comment by pgomulka** [comment]
Just to be clear. The issue is about finding out which part of the "User app" called a deprecated api?

I think traceparent/trace.id in addition to x-opaque-id could help to achieve that. 
X-opaque-id - being used as a "call site" in the user app, or just an app Id
trace.id being a uuid which will can be used to correlated requests. 


https://www.elastic.co/guide/en/elasticsearch/reference/7.17/api-conventions.html

**Comment by cjcenizal** [comment]
@pgayvallet Could you please provide input here, particularly regarding the feasibility of @pgomulka's suggestion, above? I see from https://github.com/elastic/kibana/issues/123737 that Core team has been thinking through how to use x-opace-id and trace.id, and this seems related.

**Comment by pgayvallet** [comment]
@cjcenizal 

We're already sending a `traceparent` header to ES (via the APM agent instrumentation)  which `trace.id` matches the value in kibana logs. This is used for log correlation.

Now, about using that header for traceability, I'll set @mshustov answer, as I don't think that's the direction we're taking (from my understanding, the end goal for traceability was the usage of the `baggage` header)

**Comment by mshustov** [comment]
> I think traceparent/trace.id in addition to x-opaque-id could help to achieve that.

right, traceparent/trace.id would help to trace a call to an origin in the Kibana server.  If a request is triggered from the Kibana application, the only way to trace it is to an origin is to rely on `x-opaque-id` value. 
The problem is that we have `execution_context` set for a few most popular apps https://github.com/elastic/kibana/issues/102629 Thus, it can't be used as a reliable value for deduplication.

**Comment by cjcenizal** [comment]
@mshustov Sorry I'm just trying to figure out on a high-level whether this issue is worth keeping open. Do we need more features from ES to improve tracing in Kibana, or are the existing features sufficient? If they're sufficient I'll close this. Thanks. :)

**Comment by mshustov** [comment]
@cjcenizal I don't think there is anything else for the ES team to improve right now. All the remaining work (https://github.com/elastic/kibana/pull/123197) seems to be on the Kibana side.

**Comment by cjcenizal** [comment]
Thanks @mshustov!
