### ISSUE TITLE
bin/elasticsearch -p is not creating pidfile in provided relative  path

### ISSUE THREAD

**Issue by WindyGao** [elastic/elasticsearch#80258]
**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:
```
cd ./bin
./elasticsearch -d -p pidfile
```
`But the pidfile file is created in the es_home directory instead of bin directory`

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by pugnascotia** [comment]
This behaviour is intentional, because the `elasticsearch-env` script (which the `elasticsearch` script calls) changes the current directory to `$ES_HOME`. This allows other scripts to make assumptions about the current working directory.

What problem are you experiencing with the PID file being created in `$ES_HOME`?

**Comment by WindyGao** [comment]
Well, I know what you mentioned above, so I submitted a PR #80259 so that beginners can understand the design principles

**Comment by mark-vieira** [comment]
Closing as we don't intend to change this behavior.
