### ISSUE TITLE
WARNING: A terminally deprecated method in java.lang.System has been called

### ISSUE THREAD

**Issue by michaelgarde** [elastic/elasticsearch#80344]
I'm running elasticsearch 7.15.1 from a docker-compose setup and get the following warnings

```
elasticsearch  | WARNING: A terminally deprecated method in java.lang.System has been called
elasticsearch  | WARNING: System::setSecurityManager has been called by org.elasticsearch.bootstrap.Elasticsearch (file:/usr/share/elasticsearch/lib/elasticsearch-7.15.1.jar)
elasticsearch  | WARNING: Please consider reporting this to the maintainers of org.elasticsearch.bootstrap.Elasticsearch
elasticsearch  | WARNING: System::setSecurityManager will be removed in a future release
(kafka.utils.Log4jControllerRegistration$)
elasticsearch  | WARNING: A terminally deprecated method in java.lang.System has been called
elasticsearch  | WARNING: System::setSecurityManager has been called by org.elasticsearch.bootstrap.Security (file:/usr/share/elasticsearch/lib/elasticsearch-7.15.1.jar)
elasticsearch  | WARNING: Please consider reporting this to the maintainers of org.elasticsearch.bootstrap.Security
elasticsearch  | WARNING: System::setSecurityManager will be removed in a future release
```

I'm not seeing this with version 7.15.0.

This was also raised in https://discuss.elastic.co/t/warnings-when-service-starts/286928 but i could not find an issue here on GitHub, as requested.

**Comment by williamrandolph** [comment]
Thank you for reporting this. It's something that we've been seeing, but it is good to have a public issue for user awareness and discussion.

Elasticsearch has used the Java Security Manager for many years now in order to limit the actions the server and the plugins can make.

The JDK maintainers proposed in JEP 411 to deprecate and remove the Security Manager. The warnings you see here are part of the deprecation message. We (Elasticsearch) are aware that the Security Manager emits such warnings starting Java 17 (which is used by elasticsearch 7.15.1).

This warning is safe to ignore. We are working on a plan to replace the deprecated methods. We are also considering ways to convey the same information but make the warning look less dire.

**Comment by Mollyss725** [comment]
I have the same issue in 7.15.2 and my system ram is 99%.I have to stop it.Pls check. @elastic/es-core-infra (Team:Core/Infra)

**Comment by ChrisHegarty** [comment]
@Mollyss725 The warning is emitted by the JDK runtime, when running with JDK 17. You are running with JDK 17, right? (the warning is not emitted for any JDK release prior to JDK 17)

The fix for #80462 has the affect of suppressing (or otherwise avoiding or bypassing) the warning when Elasticsearch is starting up, when running on JDK 17 (or greater). The fix for #80462 has been integrated into 7.16, 8.0, and 8.1. It is not in 7.15.2, and there are no plans to backport it to that release.

**Comment by Mollyss725** [comment]
Dear Chris
Thanks for letting me knowing the solution.I'll try the new version of docker image in the future.


However,when this error happened,I use JDK 1.8.0_121，and I run it in docker desktop.It will use up all my ram.
Then I give up the docker and install windows version ES directly,then I update my Java as it suggested JDK 11 and above.Now it is JDK 17.


PS:After I update to JDK17 and try to run in docker again,it still ate up all my ram.Can't be used in docker.
So I now use the ES I installed on windows directly which can work correctly.



Here's the pic I took by my cellphone as the machine is not running then.













------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "elastic/elasticsearch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月24日(星期三) 下午5:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [elastic/elasticsearch] WARNING: A terminally deprecated method in java.lang.System has been called (Issue #80344)





 
@Mollyss725 The warning is emitted by the JDK runtime, when running with JDK 17. You are running with JDK 17, right? (the warning is not emitted for any JDK release prior to JDK 17)
 
The fix for #80462 has the affect of suppressing (or otherwise avoiding or bypassing) the warning when Elasticsearch is starting up, when running on JDK 17 (or greater). The fix for #80462 has been integrated into 7.16, 8.0, and 8.1. It is not in 7.15.2, and there are no plans to backport it to that release.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tutengdihuang** [comment]
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.elasticsearch.bootstrap.Elasticsearch (file:/usr/share/elasticsearch/lib/elasticsearch-7.15.2.jar)
WARNING: Please consider reporting this to the maintainers of org.elasticsearch.bootstrap.Elasticsearch
WARNING: System::setSecurityManager will be removed in a future release

**Comment by karenlarkina** [comment]
I got a similar issue with JDK 19.0.1 today.

WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by edu.umd.cs.findbugs.ba.jsr305.TypeQualifierValue
WARNING: Please consider reporting this to the maintainers of edu.umd.cs.findbugs.ba.jsr305.TypeQualifierValue
WARNING: System::setSecurityManager will be removed in a future release
