### ISSUE TITLE
Elastic Search 7.9.0 Not Starting in Cpanel

### ISSUE THREAD

**Issue by ebofi** [elastic/elasticsearch#80466]
Hi, 

I'm new to Elastic Search and I want to install the Specific version 7.9 of ES, in my Cpanel server, so I did the below steps.

wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.9.0-x86_64.rpm
wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.9.0-x86_64.rpm.sha512
shasum -a 512 -c elasticsearch-7.9.0-x86_64.rpm.sha512 
sudo rpm --install elasticsearch-7.9.0-x86_64.rpm

yum clearall
yum makecache

 systemctl enable --now elasticsearch

But the above command results to an error like below. 

`
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sun 2021-11-07 06:24:08 CET; 11s ago
     Docs: https://www.elastic.co
  Process: 5308 ExecStart=/usr/share/elasticsearch/bin/systemd-entrypoint -p ${PID_DIR}/elasticsearch.pid --quiet (code=exited, status=1/FAILURE)
 Main PID: 5308 (code=exited, status=1/FAILURE)
   CGroup: /system.slice/elasticsearch.service

Nov 07 06:24:08 server2 systemd-entrypoint[5308]: at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:106)
Nov 07 06:24:08 server2 systemd-entrypoint[5308]: at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:88)
Nov 07 06:24:08 server2 systemd-entrypoint[5308]: at org.elasticsearch.node.Node.close(Node.java:989)
Nov 07 06:24:08 server2 systemd-entrypoint[5308]: at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:106)
Nov 07 06:24:08 server2 systemd-entrypoint[5308]: at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:64)
Nov 07 06:24:08 server2 systemd-entrypoint[5308]: at org.elasticsearch.bootstrap.Bootstrap$4.run(Bootstrap.java:192)
Nov 07 06:24:08 server2 systemd[1]: elasticsearch.service: main process exited, code=exited, status=1/FAILURE
Nov 07 06:24:08 server2 systemd[1]: Failed to start Elasticsearch.
Nov 07 06:24:08 server2 systemd[1]: Unit elasticsearch.service entered failed state.
Nov 07 06:24:08 server2 systemd[1]: elasticsearch.service failed.
`

My Elastic Search Log

**Comment by romseygeek** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.

In your case I think you need to include more of the log failure to debug
this properly; it looks as though you have the tail end of a stack trace
there but we'd really need to whole thing in order to work out what
has gone wrong.
