### ISSUE TITLE
Parent/child: Eager global ordinal loading should be the default

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#8053]

**Comment by clintongormley** [comment]
@martijnvg With the new implementation of parent/child, should we still default to eager global ordinal loading for p/c?

**Comment by martijnvg** [comment]
@clintongormley I'm actually unsure if we should do this. In heavy read use cases it makes perfect sense, but heavy write and irregular searches (logging use case) the eager loading that happens during each refresh is useless and wasteful, because most of the times the global ordinal data structure is not being used.

**Comment by jpountz** [comment]
This "should we perform operations eagerly on refresh" discussion happens all the time for the timeseries use-case. Since the goal of the refresh operation is to make changes searchable, maybe what we need is a different way to refresh for the timeseries use-case? For instance instead of running asynchronously every X seconds, it could run when calling the `_search` API if the last refresh occurred more than X seconds ago? This way users might achieve better write performance and on our end it would be easier to decide to perform costly operations on refresh since we would know that the things that we build are likely to be used.

**Comment by jpountz** [comment]
Closing: the _parent field loads ordinals eagerly in recent versions of Elasticsearch.

**Comment by nezda** [comment]
docs don't reflect this https://www.elastic.co/guide/en/elasticsearch/reference/5.2/mapping-parent-field.html#_global_ordinals

**Comment by clintongormley** [comment]
@martijnvg @jpountz does the _parent field load ordinals eagerly in 5.x?  If so we should update the docs

**Comment by martijnvg** [comment]
@clintongormley Yes, the _parent field does load global ordinals eagerly. I think since 5.0, it was changed as part of #17148. I'll update the docs.
