### ISSUE TITLE
Add Linux-only native library

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#80903]
As per https://github.com/elastic/elasticsearch/issues/80066 we'd like to make the low-level details of our network connections more visible: things like congestion, retransmissions, keepalive timers etc. are aspects of connection health that we need to see to diagnose connectivity problems, but today we rely on folks running `netstat` or `ss` from the command line in order to capture this data.

As mentioned in https://github.com/elastic/elasticsearch/issues/80066#issuecomment-974171695 on Linux I'd like to use the `sock_diag` interface to capture this info, but a JNA-based implementation would be ugly and brittle. It'd be much preferable to have a C library that does the work, built against libc so that it has access to all the right constants and macros. I believe Gradle has the facility to build shared libraries written in C, but I don't know exactly how nor do I know how best to package it up so that Elasticsearch could use it.

I'm opening this issue to ask for help. Are there any reasons we definitely shouldn't do such a thing? If not, could someone help me by making a module that includes a library written in C for use only on Linux? I can implement the actual `sock_diag` interaction myself, it's the supporting infrastructure on which I'm stuck.

**Comment by pugnascotia** [comment]
I did a little digging into the current state-of-play.

   * Gradle has a page about [building native software](https://docs.gradle.org/current/userguide/native_software.html)
   * But that page says the above approach is deprecated, and points you to their [C++ application support](https://docs.gradle.org/current/userguide/building_cpp_projects.html)
   * There's a [sample application for a C application](https://github.com/gradle/native-samples/tree/master/c/application), which uses the C++ application model but configures the compiler for C. The example says that a C application will exist eventually, but that comment is 3 years old now

It would be useful if we were able to use a cross-compiler, because then I could still build a complete Linux distro and Docker image, and run tests of it, all from my Mac. I don't know how good the cross-compiling landscape is at present, but I understand it's a first-class concern in [Zig](https://ziglang.org/).

**Comment by droberts195** [comment]
> It would be useful if we were able to use a cross-compiler, because then I could still build a complete Linux distro and Docker image, and run tests of it, all from my Mac.

Be careful here.  You need to make sure that the glibc that gets linked against when we build the distribution we release to end users is the oldest one we support, i.e. glibc version 2.17 for Elasticsearch 8.x, as used by RHEL/CentOS 7.  One way to achieve this is to always build for release inside a CentOS 7 Docker container.

**Comment by pugnascotia** [comment]
FWIW, I was told today that you can target specific C libs and versions, like so:

    zig cc -target x86_64-linux-gnu.2.17

**Comment by mark-vieira** [comment]
> As mentioned in #80066 (comment) on Linux I'd like to use the sock_diag interface to capture this info, but a JNA-based implementation would be ugly and brittle. It'd be much preferable to have a C library that does the work, built against libc so that it has access to all the right constants and macros. I believe Gradle has the facility to build shared libraries written in C, but I don't know exactly how nor do I know how best to package it up so that Elasticsearch could use it.

How would we integrate this into elasticsearch? Would we just build an executable and shell out to it from ES to get the data we need?

**Comment by mark-vieira** [comment]
In terms of the build infrastructure here, I don't think I'd make any attempt to integrate this into the Elasticsearch build, so I think we'd probably be best off doing something similar to https://github.com/elastic/jna-build and build/publish this out of band. I'd suggest this for a few reasons:

1. Integrating this into https://github.com/elastic/elasticsearch would mean that anyone wanting to build Elasticsearch would then have to have a native toolchain installed. We have the benefit now that basically the only dependency of our build that isn't self-provisioning is a JDK. This would just complicate getting a working development environment and make contributing to ES unnecessarily difficult.
2. If you wanted to build the Linux variant on a different platform, we'd have to deal with all the complexities of cross-compile. For example, building the Docker image requires building the Linux archive so any Docker-based tests on Windows/Mac would require a toolchain capable of Linux cross compilation. On Windows this likely means something like gcc installed via Cygwin or Mingw.
3. We probably won't change this a lot so no need to have folks rebuild it all the time, just fetch it as a prebuilt binary dependency like we do for ML.

**Comment by DaveCTurner** [comment]
> How would we integrate this into elasticsearch? Would we just build an executable and shell out to it from ES to get the data we need?

No, we don't permit any of the syscalls (`fork` and friends) that would allow this. We'd need it to be a library that gets invoked with JNA, but as a one-shot function call with a sensible interface rather than the terrible sequence of calls that's needed today.

**Comment by DaveCTurner** [comment]
> build/publish this out of band

Ok, I see the advantages of treating this like we do with the ML artefacts. I'd rather avoid making it like `jna-build`, for instance it'd be good to use the same versioning scheme and release cycle as the rest of the stack. Could we still have the source for the library in the ES source tree? What would the build/publish process look like and how would it be automated?

**Comment by droberts195** [comment]
> Ok, I see the advantages of treating this like we do with the ML artefacts. I'd rather avoid making it like `jna-build`, for instance it'd be good to use the same versioning scheme and release cycle as the rest of the stack. Could we still have the source for the library in the ES source tree? What would the build/publish process look like and how would it be automated?

One slightly radical way to do it would be to put the code in the ml-cpp repo.  It could be a separate library under [`lib`](https://github.com/elastic/ml-cpp/tree/main/lib) that didn't depend on anything else in that repo.  The nice things about this is are:

1. If you later wanted the same functionality for macOS and Windows then you'd benefit from all the existing infrastructure to build different code for different platforms.
2. You'd have the option to build Java and C++ changes together locally before committing if you ever needed to iterate fast debugging some complicated interaction.
3. Things like ensuring it was linked against the oldest version of glibc needed for the support matrix for a given release would be taken care of by the ML team.

The nasty things about this are:

1. If it were published with the rest of the ML libraries then core server would have to download the ML bundle instead of just the ML module.
2. It would complicate the licensing, because the ml-cpp repo is all Elastic license v2 only.  But I guess you'd want this new code to be dual SSPL/ELv2.

Maybe that second disadvantage kills the idea, but I thought I'd still mention it.

**Comment by DaveCTurner** [comment]
We discussed this in another channel. We could reasonably make this library available by an ELv2-only plugin since it needs to be optional for other reasons too (e.g. it's only for Linux). Still, `ml-cpp` seems like the wrong place for it, @pugnascotia is thinking about adding another dependent build to `release-manager`.

**Comment by DaveCTurner** [comment]
We've discussed this some more and are looking again at doing a pure JNA implementation instead. It seems like it might be possible, albeit ugly, but less ugly than introducing an external library. Therefore I'm closing this. Thanks everyone for your input.

**Comment by DaveCTurner** [comment]
I've investigated this further and have sketched out a pure JNA implementation for the functionality I was seeking - it isn't pretty but it does at least work. However it does cause me some concerns about how we are using JNA in general. Calling into libc like this requires us to specify the exact ABI for the functions that we're calling. Today we're relying on those ABIs being the same across platforms, and not changing over time. Glibc doesn't actually guarantee this kind of ABI stability so I believe we're doing something pretty unsafe even if in practice we seem to have got away with it so far. You only get ABI stability guarantees if using versioned symbols, but JNA [uses `dlsym`](https://github.com/java-native-access/jna/blob/7dbbf4b447674182e5752ac9b1eba91d9bffc22e/native/dispatch.c#L88) rather than `dlvsym` so there's no facility to specify the ABI version. We also have no way to handle any differences in ABI between `x86_64` and `aarch_64` although we fortunately haven't encountered any of those yet.

I think we should move away from calling directly into `libc` for these reasons. Therefore I'm reopening this: I think it would be much safer to call into a thin wrapper library whose ABI we control, compiled on the right platform.

Relates https://github.com/elastic/elasticsearch/pull/80437#discussion_r760022317 in which I have the same concerns.

**Comment by mark-vieira** [comment]
@DaveCTurner is this still something we are looking into or can we close this for now? I think more long-term, the improvements in Project Panama are likely to be our best way forward for this type of native integraiton.

**Comment by DaveCTurner** [comment]
Panama does promise to solve these concerns, let's go that way instead.
