### ISSUE TITLE
[ML] upgrade model snapshot is not autoscaling-friendly

### ISSUE THREAD

**Issue by wwang500** [elastic/elasticsearch#81012]
Steps to reproduce: 
1. In a 7.6 cloud cluster, create and start a machine learning AD job. 
2. After job finished and stopped, upgrade the job to 7.16
3. Enable the autoscaling
4. Wait several minutes, and make sure there is no jobs running and no ml node in the plan (because of autoscaling ON)
5. In kibana, go to upgrade assistant, you should see warning about obsolete minimum version of model snapshot
6. In dev tools, fire an upgrade snapshot request: `POST _ml/anomaly_detectors/<job>/model_snapshots/<snapshot id>/_upgrade` 

Observed:
an error message says: `Could not open job because no ML nodes with sufficient capacity were found`. Also,  no ml node is provisioned after several minutes waiting.

Expected:
Upgrade model snapshot should be autoscaling-aware, ml node should be provisioned.

**Comment by benwtrent** [comment]
This is because we don't treat the snapshot upgrade tasks the same as anomaly detection tasks. 

Honestly, I am not 100% sure we should autoscale in this scenario. If they have zero ML nodes, that means they are not running ML at all and probably just have an old snapshot that they forgot about and need to delete. It seems weird to autoscale to me.

The change isn't too difficult (simply catch the upgrade snapshot tasks with the anomaly detection tasks).

**Comment by droberts195** [comment]
> Honestly, I am not 100% sure we should autoscale in this scenario.

The situation of needing to scale from 0 to 1 for model snapshot upgrade is extreme - really just a way to test the scenario of needing to autoscale.

But I think needing to scale to a bigger node definitely needs to work.  The model snapshot upgrade processes are going to need about as much memory as the corresponding job, as they're instantiating the same object structure in memory.  So if autoscaling has made the cluster as small as it can be to run the current jobs then it's highly likely that a model snapshot upgrade won't also fit.

> The change isn't too difficult (simply catch the upgrade snapshot tasks with the anomaly detection tasks).

I'm just working through this now.
