### ISSUE TITLE
snapshot should work when cluster is in read_only mode.

### ISSUE THREAD

**Issue by webmstr** [elastic/elasticsearch#8102]
I was trying to make a full, consistent backup before an upgrade.  Snapshots are at a moment of time, which doesn't work if clients are still updating your indexes.

I tried putting the cluster into read_only mode by setting cluster.blocks.read_only: true, but running a snapshot returned this error:

    {"error":"ClusterBlockException[blocked by: [FORBIDDEN/6/cluster read-only (api)];]","status":403}

Please consider allowing snapshots to provide a consistent backup by running when in read-only mode.

**Comment by colings86** [comment]
@imotov we discussed this issue but were unclear on what the differences are between the index.blocks.* options are and why the snapshot fails with read_only set to false?

**Comment by imotov** [comment]
@colings86 there is an ongoing effort to resolve this issue in #9203

**Comment by imotov** [comment]
After discussing this with @tlrx it looks like the best way to address this issue is by moving snapshot and restore cluster state elements from cluster metadata to a custom cluster element where it seems to belong (since information about currently running snapshot and restore hardly qualifies as metadata).
