### ISSUE TITLE
Enterprise Search source code

### ISSUE THREAD

**Issue by baseely** [elastic/elasticsearch#81233]
Hello Community,

I tried to locate the source code repository for the Enterprise Search product but I couldn't. Same for the embedded Web Crawler.
Are there any future plans to make it open source ?

**Comment by cbuescher** [comment]
According to [this post in the forums](https://discuss.elastic.co/t/is-workplace-search-open-source/246726) Enterprise Search is closes source and  there are no foreseeable plans to convert it to open source. This might have changed since last year though, so I would ask you to post that question there in the Enterprise Search forums again if you like a more up-to-date answer. We prefer to use this Github repo issues only for bug reports and feature requests for the core Elasticsearch project, so I'm closing this as an issue here.
