### ISSUE TITLE
[DOCS] Document action order in ILM

### ISSUE THREAD

**Issue by Leaf-Lin** [elastic/elasticsearch#81567]
I have been looking at this code everytime when I fee I need to understand the order of actions getting executed in ILM.  Perhaps the order or a summary table like this should be documented in the doc? 

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-5dc257c8-7fff-c122-4431-94e1038a33c1"><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:11pt;"></p><div dir="ltr" style="margin-left:0pt;" align="left">

Hot | SetPriority → Unfollow → Rollover → ReadOnly → Rollup → Shrink → ForceMerge → SearchableSnapshot
-- | --
Warm | SetPriority → Unfollow → ReadOnly → Allocate → Migrate → Shrink → ForceMerge
Cold | SetPriority → Unfollow → ReadOnly → SearchableSnapshot → Allocate → Migrate → Freeze → Rollup
Frozen | SearchableSnapshot

</div></b>
https://github.com/dakrone/elasticsearch/blob/master/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/TimeseriesLifecycleType.java#L54-L84

**Comment by joegallo** [comment]
This is relatively near to a conversation I had earlier today: I'd like to make `GET _ilm/policy/some-policy` return the policy json such that the phases **and** actions are returned in execution order.

The amount of cycles I've put into mentally reordering policy json so that I can think about what it would actually do in order is too dang high! 😄
