### ISSUE TITLE
Inconvenient behaviour of ES_JAVA_OPTS in Systemd Override

### ISSUE THREAD

**Issue by gitpel** [elastic/elasticsearch#81602]
**Elasticsearch version** (`bin/elasticsearch --version`):
elasticsearch/stable,now 7.16.0 amd64 [installed] (latest)

**OS version** (`uname -a` if on a Unix-like system):
Debian GNU/Linux 11 (bullseye)

**Description of the problem including expected versus actual behavior**:
The **systemd override file** `/etc/systemd/system/elasticsearch.service.d/override.conf` should override **systemd service file** and environment variables like ES_JAVA_OPTS - it does, but behaviour of elasticsearch modifies ES_JAVA_OPTS so the result is inconvenient
```
.... -Xlog:gc*,gc+age=trace,safepoint:file=/var/log/elasticsearch/gc.log:utctime,pid,tags:filecount=32,filesize=64m ... -Xlog:all=warning ...
```
but should be only
```
-Xlog:all=warning
```

**Steps to reproduce**:
1. Create the override file `/etc/systemd/system/elasticsearch.service.d/override.conf` with the content:
  ```text
  [Service]
  Environment=ES_JAVA_OPTS="-Xlog:all=warning"
  ```
2. Reload service files with the `systemd daemon-reload`
3. Start the Elasticsearch service `systemd start elasticsearch`
4. Check the parameters `systemd status elasticsearch |  grep -i xlog`

**Relevant documentation:**
Systemd Override > https://www.elastic.co/guide/en/elasticsearch/reference/current/setting-system-settings.html#systemd
ES_JAVA_OPTS > https://www.elastic.co/guide/en/elasticsearch/reference/7.16/advanced-configuration.html#set-jvm-options

**Comment by grcevski** [comment]
Hi @gitpel,

The `-Xlog:gc*...` command line option comes from our `jvm.options` file in the Elasticsearch `config` directory. If you'd like to not have GC logs enabled by default, you can simply comment out that line in the jvm.options file.

The reason why the ES_JAVA_OPTIONS environment variable doesn't override this command line switch is because the `-Xlog` JVM option is additive, meaning, specifying more than one on the command line won't override the previous, but instead add to it. This is very much unlike other JVM options like `-Xmx`, where if you had multiple on the command line the last one would win.

If you'd like to override the `-Xlog` option we have on by default in our jvm.options file (without modifying the file), you can set ES_JAVA_OPTS to the following:

```
 -Xlog:disable -Xlog:all=warning
```

The above sequence will turn off all logging previously set, including warnings and errors, and then enable JDK messages tagged with 'warning' level.

For more info on the -Xlog option you can simply run `java -Xlog:help`.

**Comment by pugnascotia** [comment]
We also cover this in the documentation, with examples:

https://www.elastic.co/guide/en/elasticsearch/reference/8.0/important-settings.html#gc-logging
