### ISSUE TITLE
New .monitoring-8 templates need to be automatically cleaned over time

### ISSUE THREAD

**Issue by jbaiera** [elastic/elasticsearch#81839]
With https://github.com/elastic/elasticsearch/pull/81744 we introduced new default templates for Metricbeat which are installed at cluster start up. These new templates make use of the data streams features, which means that the indices they create are not subject to the cleaner service that is present in the monitoring plugin.

As such, these templates will likely require an ILM policy to be deployed with them to clean up the older indices over time.

Furthermore, since these resources will be data stream oriented, the ILM policy will likely be needed to roll over the data streams. The current format for the matching pattern on the template includes a wildcard at the end of the data stream name. We should ensure that this wildcard is not being used for dates. The process for creating new backing indices should be managed by the data stream rollover functionality instead of using new names.

== 
EDIT: Summary of planned change for retention of stack monitoring data with Metricbeat 8.0 

* Stop using the legacy Cleaner service
* Use the ILM policy below [1] that will ship by default and be associated via the stack monitoring index templates
* The ILM policy is essentially a 3-6 day default (it is not expected to ever hit the 50gb size)
* The ILM policy will rollover every 3 days and move it to the warm tier (if it exists), force merge the index, then wait 3 more days till it is deleted.
* We will carry forward the `xpack.monitoring.history.duration` if it was set in a prior version for use as the min_age for delete
* Ideally this ILM policy will be presented as the default ILM policy for the Fleet stack monitoring integrations.
* Normal ILM tooling can be used to control retention and behavior. 

[1]
```json
{
  "policy": {
    "phases": {
      "hot": {
        "actions": {
          "rollover": {
            "max_primary_shard_size": "50gb",
            "max_age": "3d"
          }
        }
      },
      "warm": {
        "actions": {
          "forcemerge": {
            "max_num_segments": 1
          }
        }
      },
      "delete": {
        "min_age": "<VALUE_TO_BE_SET_FROM_xpack.monitoring.history.duration_OR_3_DAYS_IF_UNCONFIGURED>",
        "actions":{
          "delete": {}
        }
      }
    }
  }
}
```

**Comment by ravikesarwani** [comment]
I feel we should create an ILM policy with 50GB rotation and delete matching current xpack.monitoring.history.duration setting to avoid potential breaking change from customer perspective. This should work in self-managed, ESS, GovCloud etc. environment otherwise we will run into the risk of cluster getting fill after upgrade and/or very large index getting created (without any rollover). 

Since the delete phase of the ILM should match the current xpack.monitoring.history.duration setting should this really be created in Elasticsearch?

I know we are currently adding date in the end of the data stream name that we are planning to research and change potentially as a separate issue.

cc: @klacabane @matschaffer

**Comment by ravikesarwani** [comment]
If creating a default ILM policy is something really difficult to do then adjusting the cleaner service is also an option.

Using a default value in 8.0 without recognizing the current value will break every upgrade case where user is not using the default value and I feel will result in many unhappy customer in both self-managed and cloud environment.
I think we need some solution here to recognize the current xpack.monitoring.history.duration setting and delete based on that.

**Comment by jakelandis** [comment]
I have some reservations about configuring an ILM policy based based on the setting `xpack.monitoring.history.duration`. It would be difficult and error prone to ensure that these two values are kept in sync in perpetuity and sets a precedence of ILM configuration via cluster settings. 

I also have reservations about continued support for the Cleaner service since it is a predecessor to ILM and once Legacy monitoring is no longer supported the Cleaner service will also no longer be supported. 

However, I do understand that it can be jarring for a client to upgrade and we no longer honor the history duration that they configured. 

As a compromise to avoid trying to define ILM policies via cluster settings, not carrying forward the Cleaner service and still honor the spirit of client's duration... I propose that we choose intelligent default for which default ILM policy gets applied by default in the index template. We currently have 7,30,90,180, and 365 day retention default policies that ship with Elasticsearch. I propose that we introduce a 3 day retention default ILM policy and then based on the setting for `xpack.monitoring.history.duration` we choose the closest default ILM policy. 

For example if a user set :
`xpack.monitoring.history.duration` : 30 days -> use the 30 day ILM policy
`xpack.monitoring.history.duration`  : 1 day -> use the 3 day ILM policy

It won't be exact 1:1, but will honor the spirit of value the user set and easily updated via the ILM policy.  
cc: @dakrone

**Comment by ravikesarwani** [comment]
Thanks Jake, I am good with this approach.
It covers the main defaults in many places we are using (3, 7, 90, 365) so users won't have any impact at all. 
In very custom use cases we will match to one of the most common and closest retention values.
The great thing is that we are not relying on cleaner service and users will have much greater flexibility to configure retention further, if needed, via the ILM policy.

**Comment by dakrone** [comment]
I think setting a different policy based on a cluster setting is almost the same as creating a brand new policy based on a cluster setting, and would still have a slight assumption about synchronization. Additionally, since this installation would be automatic, it would be very action-at-a-distance-y, and can lead to a lot of confusion since one cluster's ILM policy (let's say a user tested a configured in a dev environment) could not match the policy used for a different environment. My preference would be for consistency over unexplained (to the user) differences.

> Using a default value in 8.0 without recognizing the current value will break every upgrade case where user is not using the default value and I feel will result in many unhappy customer in both self-managed and cloud environment

We're already switching things around by making the monitoring data a data stream, and the duration setting is currently deprecated in 7.x, I think it's reasonable to ship a default value for 8.0 and enhance the deprecation check for the `xpack.monitoring.history.duration` setting to explicitly mention changing the ILM policy to point a user towards making that change. I think we're in for the potential for confusion either way, as setting a different policy based on a setting is just as confusing as reverting to a default, but it seems easier to justify the default behavior given that we're transitioning to a data stream and it is a major release.

The default value for the `xpack.monitoring.history.duration` setting is 7 days in the code, could we simply use the existing 7 day default policy that we ship, and allow a user to swap it by either setting up a custom policy or switching to one of the other 30, 90, etc built-in policies?

**Comment by matschaffer** [comment]
@jakelandis I think I might be with @dakrone that we should have an stack-monitoring-specific policy.

If we use select https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/core/src/main/resources/30-days-default.json and set that on https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/core/src/main/resources/monitoring-es-mb.json the user will need to update the index template to change stack monitoring retention policies later.

Not sure we want people feeling comfortable customizing the template since an accidental mapping change could break the stack monitoring UI.

**Comment by jakelandis** [comment]
We discussed this today and others shared Lee's concerns about the use of  `monitoring.default.ilm.retention` and the action-at-distance.  Thinking on this a bit more and with @matschaffer 's point I wonder if we should do the following:

* Use a custom Monitoring ILM policy with a well established name so that Fleet can default to that policy
* Introduce a new setting like `monitoring.default.ilm.retention` that defaults to the value of `xpack.monitoring.history.duration`
* Template the custom Monitoring ILM policy so that it reads from `monitoring.default.ilm.retention`

I think addresses most concerns ... there is still some action at a distant, but I think it mostly mitigated by the introduction of a new setting. 

Thoughts ?

**Comment by jbaiera** [comment]
If this setting is updated, is it expected that we republish the ILM policy to reflect the change?

**Comment by dakrone** [comment]
I think we may still run into the same problems with this setting. Unless we made it have some sort of synchronization, it is going to be almost exactly the same as the `history.duration` setting in that it is used once and then ignored. 

Additionally, introducing the new setting only makes sense for users of the existing monitoring, a user coming into monitoring fresh from 8.x wouldn't (and shouldn't) be expected to know about this setting, since it's a departure from the way that ES usually sets up retention for any of our other built-in pieces. I think this shifts the problem and introduces another setting that would have to be deprecated again in the future (this is an anti-pattern for ES, since we don't want any other index retention settings encapsulated into cluster settings, we have ILM for that).

For that reason, I think my preference is still a clean break for the transition to data stream and ILM, though I totally understand that this may cause a little unintended behavior. Unintended behavior is going to be almost impossible to avoid in this case, it's a question of which unintended behavior we think is the best (I could be totally wrong on which unintended behavior is the "least worst", which I think is what we're trying to nail down in this issue). If we want to mitigate the unintended behavior I think we'll have to raise that concern to the user either at the Cloud UI or out-of-band deprecation API inside of Kibana as we discussed earlier today.

**Comment by jakelandis** [comment]
> If this setting is updated, is it expected that we republish the ILM policy to reflect the change?

No, the name and documentation of the new setting would need to be clear that it is only for the default and only used initially then ignored. 

>  in that it is used once and then ignored.

I think that is fine. Historically we allowed systems to preset the retention via the `xpack.monitoring.history.duration` , the new setting would carry forward the ability to preset the retention while still allowing the use of ILM. I think it is special case given the history and passivity concerns. 

> and introduces another setting that would have to be deprecated again in the future 

The proposal here would have the setting would remain around indefinitely. Once  `xpack.monitoring.history.duration` is removed a new default will need to be chosen. 

> this is an anti-pattern for ES, since we don't want any other index retention settings encapsulated into cluster settings; we have ILM for that

Agreed, and I share that concern. However, I think this is the least worst option when compared to either marginally adding more (i.e. 1 days -> 7 days) or greatly removing (i.e. 365 days -> 7 days) the amount of monitoring data retained especially in Cloud where the user may not be aware these changes behind the scenes. (In all cases the amount of data retained will marginally change due to the differences in how the Cleaner service works vs. ILM)

**Comment by ravikesarwani** [comment]
Do we have some finalization of the solution?
From requirements perspective I would like us to consider the following points:
- We should carry forward the current retention is some way for upgraded clusters. Setting a fixed 7 days retention does not work for all environments (self-managed, ESS, GovCloud etc.) and changes the users environment too drastically (3 to 7 for all ESS default clusters OR 365 to 7 for GovCloud clusters) where they could end up with cluster running out of disk or not meeting compliance etc. requirements.
- We should use ILM to manage retention going forward. There is no requirement to sync with the old setting or even use setting at all. We will simple state that retention management needs to be done using ILM moving forward. For new installation or where we cannot read the setting etc. I would propose we create an ILM policy with 3 days retention (to match ESS default) with our Cloud first approach.

**Comment by dakrone** [comment]
It sounds like there is a lot of concern about reverting to a setting that doesn't match what a user may have configured. I still have concerns about the action at a distance, but I understand it may be worth it to allow users to be closer to what they have with the `xpack.monitoring.history.duration` (no setting will be exactly the same, due to the way ILM rollover works).

I think everyone agrees that ILM should be what we use for this, and to try and move away from the custom cleaner as quickly as possible. I don't think this point has any contention.

> I would propose we create an ILM policy with 3 days retention (to match ESS default) with our Cloud first approach.

This seems like a reasonable default to me; and we should try to introduce a default that matches whatever we use in Cloud. **So, when `xpack.monitoring.history.duration` is not set, we default to an ILM policy with 3 day retention**. (Note that this will be a breaking change because on-prem users will go from 7 days of retention by default in 7.x to 3 days in 8.x assuming a user hasn't configureded the `xpack.monitoring.history.duration` setting. We'll need to document this similar to the way we document other breaking changes).

---------

As far as carrying forward a customization to the duration setting to an ILM policy (as in, read it and use that to change the particulars for an ILM policy), I think we should use a custom ILM policy for the monitoring data (not using the built-in 7, 30, 60, etc ILM policies) so that it can be clear that it is specific to monitoring data only. Since we would use a custom policy, we can read directly from the `xpack.monitoring.history.duration` setting for the initial retention configuration, ignoring the setting thereafter as long as the policy already exists.

This has the following benefits:
- Allows us to match the existing retention for a user in the new ILM policy exactly (i.e., if they had a duration of 12897 hours configured, their ILM policy would have a retention of 12897 hours).
- Does not introduce a new setting and layer of indirection.
- Is not synchronized, the value is read only when the ILM policy is created.
- Can be documented heavily as part of the deprecation information for the `xpack.monitoring.history.duration` setting.
- Does not tie the monitoring ILM policy into the policy for any other data—it is specific and tailored for monitoring data only.
- Allows us to document in the policy metadata what exactly the policy is for, where it comes from, and even that the `xpack.monitoring.history.duration` setting was used in its initial creation.

I don't think we need a particularly complex policy, I would recommend the following (not that we have to nail down a specific policy in this issue, we can handle that elsewhere):

```json
{
  "policy": {
    "phases": {
      "hot": {
        "actions": {
          "rollover": {
            "max_primary_shard_size": "50gb"
          }
        }
      },
      "warm": {
        "actions": {
          "forcemerge": {
            "max_num_segments": 1
          }
        }
      },
      "delete": {
        "min_age": "<VALUE_TO_BE_SET_FROM_xpack.monitoring.history.duration_OR_3_DAYS_IF_UNCONFIGURED>",
        "actions":{
          "delete": {}
        }
      }
    }
  }
}
```

This is still a layer of action-at-a-distance and is not perfect, but I hope this is a good compromise that meets the requirements set forward. @jakelandis @ravikesarwani does this sound reasonable to you?

**Comment by ravikesarwani** [comment]
This sounds perfect from my side!

**Comment by jakelandis** [comment]
I am +1 to most any strategy that allows us to preserve the general intent of custom retention. I agree a custom a ILM policy for monitoring is best and ideally Fleet based monitoring would default to this one. Also I think we will need to specify a time for the rollover as well (see below). We could keep doing daily rollovers, but I think perhaps defaulting to 3 days rollovers with 3 day delete (or custom retention) would mean that there is always 3-6 days worth of monitoring data..or if they had a custom retention of 90 days there would always be 90-93 days worth of monitoring data. 

Below is the metricbeat monitoring data on Cloud for a decent sized cluster with ES and Kibana monitored. Added up, for 3 days, ES requires ~ 2.1 GB and Kibana .1 GB worth of primary shard data. A policy with only a size based rollover (once it reaches steady state) for Kibana and ES (at worst) will consume over 100GB of space and end up retaining ~50days for ES and ~2y for Kibana. 

```
health status index                              uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   .monitoring-kibana-7-mb-2022.01.09 K_TP7at0Tf6bt9iSDw3Cyg   1   1      17280            0     18.3mb          9.1mb
green  open   .monitoring-kibana-7-mb-2022.01.11 S_7M3wIvQLujvGK9RoFgJw   1   1      10218            0     20.1mb         11.5mb
green  open   .monitoring-kibana-7-mb-2022.01.10 nxIXI8owTcC-I8wU2eCmLA   1   1      17280            0     18.4mb          9.1mb
green  open   .monitoring-es-7-mb-2022.01.09     TPNRW2ocSQ-0x_8wa7edWg   1   1    1149894            0      1.6gb        828.2mb
green  open   .monitoring-es-7-mb-2022.01.10     3xRTGlb4TIuVBE19bbZYSg   1   1    1182162            0      1.6gb          848mb
green  open   .monitoring-es-7-mb-2022.01.11     Gabv6lzqSwqm56hpCr-9NA   1   1     677105            0        1gb        502.4mb
```

so...
```json
 "hot": {
        "actions": {
          "rollover": {
            "max_primary_shard_size": "50gb",
            "max_age": "3d"
          }
        }
...
```

**Comment by ravikesarwani** [comment]
cc: @Kushmaro Omer, can you please include any other folks from the cloud team for awareness.
Nothing needs changing from Cloud side but needs awareness that ILM will be used for data retention in 8.0 when using metricbeat 8.0.

@jakelandis It would be great to update the main issue description with the final decision and what we ultimately deliver. Thanks!

**Comment by Kushmaro** [comment]
Thanks for the ping @ravikesarwani 
/cc @andrew-moldovan , this is something the applications team needs awareness of due to the "logs & metrics" feature using metricbeat.

**Comment by jbaiera** [comment]
This is completed
