### ISSUE TITLE
[VSphere]: Auto configuration failed on running elasticsearch.bat while setting up self-managed 8.0 Snapshot.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elasticsearch#82073]
**Kibana version:**  8.0.0-SNAPSHOT

**Host OS:** Windows.

**Preconditions:**
1. 8.0 Snapshot artifacts should be available.

**Steps to reproduce:**
1. Navigate to VSphere VM.
2. Extract elasticsearch and kibana artifacts in `C:\elk\` folder.
3. Open cmd admin and navigate to bin location of elasticsearch extracted folder.
4. Run `elasticsearch.bat`.
5. Observe below error: 
`Error: Aborting AUTO Configuration.`

**Expected Result:**
Elasticsearch and kibana should auto configure on running `elasticsearch.bat` and `kibana.bat` respectively.
- Below details should be available on running elasticsearch.bat
**_Sample:_**
![7](https://user-images.githubusercontent.com/77374876/146495314-1c340152-7032-4e36-9738-fb5f62badce4.JPG)

**Screenshot:**
![2](https://user-images.githubusercontent.com/77374876/146754237-d8707c16-008e-4ea8-9967-e0220147921c.JPG)

**NOTE:**
- This issue is **not observed on AWS Windows VMs** and we are successfully able to install 8.0 Snapshot using auto-configuration feature with the same artifacts.
- This issue is specific to VSphere Windows VMs.

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & mention to @jkakavas

CC: @jlind23

**Comment by jkakavas** [comment]
Thank you for reporting this. This is not related to Vsphere in anyway but it is caused by the way you are trying to run elasticsearch : You unzipped the archive as the local account `zeus` so the installation directory is owned by this `zeus` user, and then you try to run elasticsearch as the built-in `Administrator` user. 

When doing the auto-configuration, we have this check that if the user that runs elasticsearch is not the same as the user who owns the configuration directory, we don't attempt to do auto-configuration, mainly because we don't want to change the owner of the files we write to from what is already and we don't want to have different groups/owners for the configuration files. 
We can probably try to be more clever about it but the underlying assumption is that the user that installs elasticsearch ( unzips the archive in this case ) is the same user that runs elasticsearch. 

Is there a particular reason that you run elasticsearch as Administrator and not as `zeus` in this setup ?

**Comment by amolnater-qasource** [comment]
Hi @jkakavas 
We usually login to the VSphere VMs with `zeus` user. 
Our elasticsearch and kibana is extracted under same `C:\elk\`.

Earlier we were running admin cmd instance to run elasticsearch.bat

As per feedback we attempted to run the same with non-admin cmd instance and we are successfully able to auto-configure elasticsearch and kibana now.

We are **closing** this issue as **resolved**.
Thanks for helping.
