### ISSUE TITLE
[DOC] Document ES Loggers for Troubleshooting

### ISSUE THREAD

**Issue by stefnestor** [elastic/elasticsearch#82172]
👋🏼 hiya, team! Will you kindly validate how-to pull & add the following "how-to debug problematic features further via ES logging"? 

Current mock up here (I'm not sure where this'd add into the docs): https://gist.github.com/stefnestor/c508c23f305258723d49b915d684456d

**Comment by DaveCTurner** [comment]
Apart from the list of packages this is covered at https://www.elastic.co/guide/en/elasticsearch/reference/current/logging.html#configuring-logging-levels already. It's deliberate that no list of packages is included in the docs: functionality moves around fairly freely between packages between different versions, and enumerating the packages in the docs would give a misleading impression of stability.

Rather than adding this list to the docs I think we should continue to consider cases where extra logging was required for diagnostic purposes to be a bug in the default logging setup. See e.g. https://github.com/elastic/elasticsearch/pull/73128 for an example of fixing such a bug.

**Comment by stefnestor** [comment]
> It's deliberate that no list of packages is included in the docs

Good to know.

> We might also want to document an appropriate diagnostics logger for certain specific features for which we do want to offer some kind of stability guarantees for its logging (e.g. Watcher) but that's very different from maintaining a list of all available loggers.

I'll walk this further instead.

Cheers!
