### ISSUE TITLE
Rollup Index Search Date Filter :: Not working as expected 

### ISSUE THREAD

**Issue by vvvprabhakar** [elastic/elasticsearch#82336]
ES Details 
   ```  number" : "7.10.0",
    "build_flavor" : "oss",
    "build_type" : "rpm",
    "build_hash" : "51e9d6f22758d0374a0f3f5c6e8f3a7997850f96",
    "build_date" : "2020-11-09T21:30:33.964949Z",
    "build_snapshot" : false,
    "lucene_version" : "8.7.0"```
    
  Created a rolled-up target index, where data gets rolled up every and pushed into the target index 
    
  Query (for Last seven days) Date Histogram Search 
  `{
	"size": 0,
	"query": {
		"bool": {
			"filter": [{
				"range": {
					"startTimeMillis": {
						"gte": 1640669080936,
						"lte": 1641273880937,
						"format": "epoch_millis"
					}
				}
			}]
		}
	},
	"aggs": {
		"2": {
			"date_histogram": {
				"fixed_interval": "1d",
				"field": "startTimeMillis",
				"min_doc_count": 0,
				"format": "epoch_millis"
			},
			"aggs": {}
		}
	}

}
`   

Response 
`"buckets" : [
        {
          "key_as_string" : "2021",
          "key" : 1640736000000,
          "doc_count" : 1
        },
        {
          "key_as_string" : "2021Z",
          "key" : 1640822400000,
          "doc_count" : 28891
        }
      ]
` 
**I am not getting all seven days data here**
But if I don't use the filter on query I am getting all the results 
Query without filter 
`{
	"size": 0,
	"aggs": {
		"2": {
			"date_histogram": {
				"fixed_interval": "1d",
				"field": "startTimeMillis",
				"min_doc_count": 0,
				"format": "epoch_millis"
			},
			"aggs": {}
		}
	}}
`

**Comment by vvvprabhakar** [comment]
@not-napoleon can you help

**Comment by not-napoleon** [comment]
Thanks for reporting this.  As a reminder, [Rollup is an experimental feature](https://www.elastic.co/guide/en/elasticsearch/reference/current/xpack-rollup.html) so we take a best effort approach to fixing issues.  That said, in order for us to do anything with this, we need more information.

Please provide the following:

 - Elasticsearch version you are running this on
 - Rollup Configuration
 - Base index configuration
 - Sample data to demonstrate the issue

Ideally, you would send a sequence of `curl` commands (or Kibana Dev Console inputs) that will show the problem from a fresh install.  That is the easiest for us to debug, and our first step will be building such a script from your examples.

**Comment by wchaparro** [comment]
With the 8.7 release of Elasticsearch, we have made a [new downsampling capability](https://www.elastic.co/guide/en/elasticsearch/reference/current/downsampling.html) associated with the new [time series datastreams](https://www.elastic.co/guide/en/elasticsearch/reference/current/tsds.html) functionality generally available (GA). This capability was in tech preview in ILM since 8.5.  Downsampling provides a method to reduce the footprint of your time series data by storing it at reduced granularity. The downsampling process rolls up documents within a fixed time interval into a single summary document. Each summary document includes statistical representations of the original data: the min, max, sum, value_count, and average for each metric. Data stream time series dimensions are stored unchanged. 

Downsampling is superior to rollup because:

- Downsampled indices are searched through the _search API
- It is possible to query multiple downsampled indices together with raw data indices
- The pre-aggregation is based on the metrics and time series definitions in the index mapping so very little configuration is required (i.e. much easier to add new time serieses)
- Downsampling is managed as an action in ILM
- It is possible to downsample a downsampled index, and reduce granularity as the index ages
- The performance of the pre-aggregation process is superior in downsampling, as it builds on the time_series index mode infrastructure

Because of the introduction of this new capability, we are deprecating the rollups functionality, which never left the Tech Preview/Experimental status, in favor of downsampling and thus we are closing this issue. We encourage you to migrate your solution to downsampling and take advantage of the new TSDB functionality.
