### ISSUE TITLE
Undocumented breaking change when moving from Rest High Level Client 7.15 to 7.16

### ISSUE THREAD

**Issue by rdehuyss** [elastic/elasticsearch#82357]
**Elasticsearch version** (`bin/elasticsearch --version`): not relevant

**Plugins installed**: []  not relevant

**JVM version** (`java -version`): not relevant

**OS version** (`uname -a` if on a Unix-like system): not relevant

**Description of the problem including expected versus actual behavior**: not relevant

**Steps to reproduce**:

 1. Use XContentBuilder from elasticsearch-rest-high-level-client version 7.15
 2. Upgrade elasticsearch-rest-high-level-client to version 7.16
 3. Breaking imports

**Provide logs (if relevant)**:
See https://www.elastic.co/guide/en/elasticsearch/reference/current/migrating-7.16.html#breaking-changes-7.16. There is nothing mentioned regarding XContentBuilder.

**Comment by rdehuyss** [comment]
See also https://github.com/jobrunr/jobrunr/issues/291

**Comment by costin** [comment]
Hi @rdehuyss 
Sorry to hear about your troubles. This is indeed a breaking change that should be documented appropriately.

@ChrisHegarty In general, outside the REST endpoints I'm not aware of any guarantees around the internal Elasticsearch classes and packages with the notable exception of the plugin API.
XContent is highly used internally and due to historical reasons (such as the high level client depending on the server initially) it started being used within our examples which, as @rdehuyss points out, made it a user facing API.

Note that in ES 8.0, the high level rest client is rewritten from scratch and has no dependency from ES to prevent the problem mentioned above.

**Comment by ChrisHegarty** [comment]
I think that the general situation is worse than ( I ) initially thought. There are java types in public accessible members in the HLRC from server, core, xcontent, to name but a few. Maintaining binary compatibility (as defined and understood in the Java Language Specification) across even minor versions requires that all those types, from the aforementioned modules and libraries, remain effectively frozen and unchanged. Otherwise, a linkage error may occur at runtime. I'm unsure of the requirements or constraints in this area relating to source compatibility, if any.

Given that xcontent was primarily moved so solve a split package issue in 8.x, the motivation for the backport to 7.x was to keep the code in sync. Unfortunately, [the change](https://github.com/elastic/elasticsearch/pull/78831) is already in a shipping 7.16 release, so if it is reverted now in 7.17 this could be even more disruptive. But of course, it is possible to restore the xcontent package to its original name in 7.17 if that is deemed necessary. Otherwise, it should be documented as a "breaking change" - if we consider the xcontent API a public supported artefact.

Input will be needed from the Data Management Team on the above options.

**Comment by ChrisHegarty** [comment]
Given that the change is already in a shipping release 7.16 we feel it too disruptive to revert the package name change. The change will be document as a breaking change introduced in 7.16.

**Comment by lockewritesdocs** [comment]
@ChrisHegarty, what are the impacts of this change and what actions can they take? Can users [migrate to the Java API](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/migrate-hlrc.html) to avoid this issue? Or is their main option to upgrade to Elasticsearch 8.0, where the high level rest client is rewritten from scratch and has no dependency from ES to prevent the problem as @costin mentioned?

**Comment by ChrisHegarty** [comment]
The best long term solution is to consider [migrating from the High Level Rest Client](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/migrate-hlrc.html). However, that is a larger effort which in some cases could be postponed until a later time. So in the shorter term ...

Deveopers/Users maintaining a Java Client application (likely also using the High Level Rest Client API), need to update and recompile their source code to work with 7.17. This is the minimal change that is required.

The source code change required is to simply update the _import_ statements at the top of the Java source code file,
from:
  `import org.elasticsearch.common.xcontent.xxx`
to:
  `import org.elasticsearch.xcontent.xxx`
