### ISSUE TITLE
clear cache api do not reset hit count/ miss count

### ISSUE THREAD

**Issue by RobertoHuang** [elastic/elasticsearch#82455]
when i call clear cache api: POST _cache/clear?query=true

then call get query cache: 
{
  "primaries": {
    "query_cache": {
      "memory_size": "0b",
      "memory_size_in_bytes": 0,
      "total_count": 3210258,
      "hit_count": 2432203,
      "miss_count": 778055,
      "cache_size": 0,
      "cache_count": 16362,
      "evictions": 16362
    }
  }
}
total_count hit_count miss_count cache_count evictions do not reset to zero.

**Comment by romseygeek** [comment]
I don't think we'd expect them to reset to 0? They're giving you a history of what's happened with the cache since the node has been up, rather than a snapshot of the current state.  The snapshot entries are `memory_size` and `cache_size`, which are both set to `0` indicating that the cache is currently empty.

**Comment by benwtrent** [comment]
closing as won't do. We will keep the values as they are. Resetting to `0` on a manual cache clear doesn't make sense as it doesn't reflect what the statistics actually represent.
