### ISSUE TITLE
Elasticsearch 8 should emit structured logs with ECS 8

### ISSUE THREAD

**Issue by yaauie** [elastic/elasticsearch#82490]
ECS 8 is set to be released along-side Elastic Stack 8. I would expect to see an 8.x version in the structured logs emitted by Elasticsearch 8 snapshots, but I am still seeing `"ecs.version": "1.2.0"`:

~~~
{"@timestamp":"2022-01-11T22:02:37.530Z", "log.level": "INFO", "message":"version[8.1.0-SNAPSHOT], pid[9], build[default/docker/0ca3db6d66a483f6377ca6eb4d0142c895cf693d/2022-01-10T16:05:39.811971724Z], OS[Linux/5.11.0-1023-gcp/amd64], JVM[Eclipse Adoptium/OpenJDK 64-Bit Server VM/17.0.1/17.0.1+12]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.node.Node","elasticsearch.node.name":"25ec142c5879","elasticsearch.cluster.name":"docker-cluster"}
~~~

I suspect this is because Elasticsearch relies on `elastic/ecs-logging-java`, which hard-codes `1.2.0` in its [latest release](https://github.com/elastic/ecs-logging-java/blob/v1.3.2/ecs-logging-core/src/main/java/co/elastic/logging/EcsJsonSerializer.java). The scope of changes from 1.last to 8.0 is small, and is gathered in https://github.com/elastic/ecs/issues/839

**Comment by pgomulka** [comment]
@yaauie as you mentioned. We rely on ecs-logging-java which is using `1.2.0` as `ecs.version`. The reason is that the `ecs-logging-java` do not use fields added after 1.2.0, so should only indicated the "minimum version supported"
see the discussion on this here https://github.com/elastic/ecs-logging/issues/44
I will close the issue for now
