### ISSUE TITLE
Please publish ElasticSearch Java modules to Maven Central

### ISSUE THREAD

**Issue by dantran** [elastic/elasticsearch#82513]
ElasticSearch currently only push core artifact to maven central, but relies on codelib to publish  'module' jars.  Due to license change,  codelib no longer doing so. [1]

Please help to ease this ES integration

[1] https://github.com/codelibs/elasticsearch-module/issues/12

**Comment by mark-vieira** [comment]
>  but relies on codelib to publish 'module' jars. Due to license change, codelib no longer doing so. [1]

I'm not sure we are _relying_ on codelibs to publish those JARs, in fact, I wasn't aware they were. Elasticsearch modules aren't really meant to be depended on. They are simply a way of modularizing Elasticsearch functionality and are only meant to be bundled in Elasticsearch itself. We have no intention of publishing these artifacts for external consumption. If you need those JARs you can a) build them from source or b) extract them from published Elasticsearch distributions and of course, usage would still have to align with the terms of the applicable license.

Can I ask what your use case is here? How exactly are you using these modules, and which modules are you using?

**Comment by dantran** [comment]
@mark-vieira  my company using both elasticsearch  and codelib's  analasys-common + lang-painless. They are pulled into maven build as compile dependencies (ie direct reference in code). 

so you are saying those modules are not supported?

**Comment by mark-vieira** [comment]
> so you are saying those modules are not supported?

They aren't supported for this use case. These aren't public APIs so they aren't intended to be stable so expect breakages across versions. As mentioned these "modules" are just a means of breaking up Elasticsearch into more composable pieces. There's no intention of these things be externally consumed. You're certainly free to do so assuming your usage of the code is not in violation of the SSPL or Elastic v2 licenses. We'd stop short of publishing them though, since as I said, their not intended to be used outside of Elasticsearch itself so making them externally available in Maven Central would give a false impression of their purpose.
