### ISSUE TITLE
Incorrect response when manually creating security indices

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#82596]
In ES 8.0, when creating the security token index manually with
```
PUT .security-tokens-42
```

We get the following response:
```
{
  "acknowledged": true,
  "shards_acknowledged": true,
  "index": ".security-tokens-42"
}
```

The response says `.security-tokens-42` is created. But that is not true and ES actually created `.security-tokens-7` instead. This happens because the requested index name matches name pattern of the security token system index. The system index framwork  thus intercepts the request and makes sure the index creation follows what is defined by the system index descriptor. 

Though it is arguable that the request interception and the index creation are desired behaviours, the response is incorrect and potentially misleading. The example uses security token index. But I suspect the same issue can happen for any system indices that claims index name namespaces with wildcards.

**Comment by ywangd** [comment]
Similarly, if the security token index alreay exists, you get the following error when trying to create `.security-tokens-42`. I think it is not ideal either.

```
PUT .security-tokens-42

===
{
  "error": {
    "root_cause": [
      {
        "type": "resource_already_exists_exception",
        "reason": "index [.security-tokens-7/vsuxZJTkTUu3jVsCfkVGxQ] already exists",
        "index_uuid": "vsuxZJTkTUu3jVsCfkVGxQ",
        "index": ".security-tokens-7"
      }
    ],
    "type": "resource_already_exists_exception",
    "reason": "index [.security-tokens-7/vsuxZJTkTUu3jVsCfkVGxQ] already exists",
    "index_uuid": "vsuxZJTkTUu3jVsCfkVGxQ",
    "index": ".security-tokens-7"
  },
  "status": 400
}
```

**Comment by gwbrown** [comment]
We discussed this in the Core/Infra sync yesterday.

Part of this behavior is that when a System Index is registered, it can (sometimes must) register a "primary index", and if any index creation request comes in for that system index's pattern (`.security-tokens-[0-9]+*`), it gets replaced with the primary index (in this case, `.security-tokens-7`).

This behavior seems counterintuitive to me and I don't recall why it's this way - maybe @pugnascotia can fill in some of the background (if he remembers)?

Anyway, assuming this is the behavior we want, if we see a request trying to create an index in the pattern other than the primary index, we should throw an exception rather than silently replace it. If for some reason that's a bad idea, we should make sure the response is correct.

I'm not sure exactly when we'll have someone with bandwidth to address this, we've got some other system index related issues we're working through.

**Comment by pugnascotia** [comment]
I don't remember the specifics here - I remember that we were concerned with attempts to create system indices from outwith the cluster, which is why there are various places where we attempt to detect creation or modification of system indices, and forcing the indices to have the expected configuration. It's quite possible that the behaviour in this issue is simply an interaction that we didn't anticipate.

I feel like it would make more sense here to reject the request if the name of the index being created isn't correct. I don't know if there's additional complexity from this name varying by major release.

**Comment by williamrandolph** [comment]
I'm going to look at whether we can do a bugfix for this by throwing an error in the case where the user tries to create an "invalid" system index.

**Comment by williamrandolph** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/86707
