### ISSUE TITLE
GET /_resolve/index should identify system indices

### ISSUE THREAD

**Issue by sabarasaba** [elastic/elasticsearch#82671]
**Elasticsearch version** 8.1

**Kibana version**: 8.1

When creating an SLM policy, kibana currently calls the `GET /_resolve/index` to allow the users to select which indices they want to backup (this API includes system indices). It seems that there's no way right now of making this API resolve only non-system indices. And if a user were to select one of these system indices the following error would be returned from ES:

```
the [indices] parameter includes system indices [.kibana_8.1.0_001]; to include or exclude system indices from a snapshot, use the [include_global_state] or [feature_states] parameters
```

<details>
<summary>API calls for testing</summary>

```
# create repository
PUT /_snapshot/my_backup
{
  "type": "fs",
  "settings": {
    "location": "/tmp/es-backups",
    "chunk_size": "10mb"
  }
}

# create policy
PUT _slm/policy/test-policy
{
  "name": "test-snapshot",
  "schedule": "0 30 1 * * ?",
  "repository": "my_backup",
  "config": {
    "indices": [
      ".kibana_8.1.0_001",
      "kibana_sample_data_flights"
    ]
  }
}

# executing the previous policy should fail
POST _slm/policy/test-policy/_execute
GET _slm/policy/test-policy
```
</details>

**Comment by yuliacech** [comment]
cc @elastic/platform-deployment-management for visibility as this would change the UI for creating an SLM policy

**Comment by williamrandolph** [comment]
The `_resolve/index/<index expression>` API will resolve matching system indices if and only if the user making the request is allowed to view those indices. It would be a breaking change to simply remove system indices from the output, so I think we have a few options:

1. Add a flag `exclude_system_indices=true`.
2. Add a `"system"` attribute for indices, aliases, and data streams, which will allow clients to filter out system resources.

The second option looks like it would be trivial to implement, and that's what I would prefer. If there is an important reason to use a request flag rather than adding an attribute to the response, please let me know.

**Comment by sabarasaba** [comment]
Filtering out system resources would work just fine for our use case in kibana, it would be quite trivial to implement on our end as well.
