### ISSUE TITLE
Core: filter cache heap usage should include RAM used by the cache keys (Filter)

### ISSUE THREAD

**Issue by mikemccand** [elastic/elasticsearch#8268]
I looked at the heap dump from #8249 and it looks like the majority of the heap is consumed by filter cache keys (TermFilter in that case, where each term was quite large: ~200 bytes long).  There were ~5.5 M such entries, I suspect most of which matching 0 docs.

We don't track cache key RAM usage today in Elasticsearch, because it's tricky.  E.g. Lucene's Filter doesn't implement Accountable, so we can't (easily) ask it how much RAM it's using.  In general there can be sharing between Filters so the RAM used across N filters is less than the sum of each, though I'm not sure Elasticsearch does this. Also, ideally we'd avoid over-counting when the same Filter is cached across N segments.

It's tricky, but I think we need to do something here...

Maybe a separate improvement we could make here is to not bother caching a filter that matched 0 docs?  Such filters are usually (?) fast to re-execute...

**Comment by s1monw** [comment]
@mikemccand what's the status of this issue?

**Comment by rmuir** [comment]
This is bounded to 100k currently in master. I don't much like this number, its ridiculously large, but other changes address the real problems (overcaching). For example only caching on large segments and only when reuse has been noted and so on.

**Comment by jpountz** [comment]
I don't think this issue is relevant anymore now that we are on the lucene query cache:
 - keys are taken into account (the result of ramBytesUsed() if the query implements Accountable and a constant otherwise)
 - the cache has a limit on the number of filters that can be added to the cache to limit issues that would be caused by ram usage of keys being underestimated
 - also we require that segments have at least 10000 docs for caching so it should be less likely to have cache keys that are much larger than the values than before

**Comment by jpountz** [comment]
Robert, you are right it's 100k currently, nor 10k. I agree we should reduce this number to a more reasonable value.
