### ISSUE TITLE
Exclude doc-values-only fields from '*' field expansion queries

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#82710]
#82602 and #82409 allow searching on fields with doc-values but no index.  These fields would previously have been excluded from queries against all fields as they would throw an exception when queried, but instead they will now effectively do a full-table scan.  We should add another check to `QueryParserHelper.resolveMappingFields()` to exclude these fields from all-field queries as well.

**Comment by javanna** [comment]
I believe that this is not only a problem around expanding `*`. If users have default_field set, even without wildcard patterns but explicitly referring to fields that have no index, they would previously get skipped while they are now queried. On one hard these fields are referred to explicitly hence we are just doing what the user asked, on the other hand they were skipped before and those queries will be much slower now. Also, the default field could be set in the index settings and the users sending queries may not be aware or even have the rights to change it.

**Comment by javanna** [comment]
>  If users have default_field set, even without wildcard patterns but explicitly referring to fields that have index set to false, they would previously get skipped while they are now queried.

That is the case only when the lenient flag is set to true, while its default is false when the fields are set explicitly. On the other hand the lenient flag is set to true whenever `*` is used to search all fields, and the default field when not specified anywhere is exactly `*`.

**Comment by javanna** [comment]
We have discussed this with the team and concluded that we are not going to exclude doc_value only fields from the existing expansion logic. We have embraced slower queries over time and it feels wrong that `*` may expand to a subset of the fields only (the faster ones). The user is asking to query all fields, hence all searchable fields will be queried, and runtime fields have also been included since they were introduced. If users are not happy with the perfomance of their query, they should restrict the fields that get queried by setting default_field either at the query level or at the index settings level.

Also, doc_value only queries are currently rejected whenever `search.allow_expensive_queries` is set to `false`, same as what happens for queries against runtime fields.
