### ISSUE TITLE
Switch doc_values=true to be the default for non-analyzed string fields

### ISSUE THREAD

**Issue by gibrown** [elastic/elasticsearch#8312]
We recently started doing a lot of sorting  by dates and integer fields on subsets of our 5 billion documents. We are mostly running queries that filter to a few thousand docs and then sorting that subset. Needing to load 5 billion dates into memory for this seemingly common use case make ES feel broken. :)

Heap memory management can be very painful and I think represents a difficult point for new users. Search engines are all about preprocessing data (indexing) so that querying can be fast. In my opinion doc_values accomplishes this better than the current default even if it can be slower in some cases.

FWIW, doc_values is MUCH faster in our use case using 1.3.4.

**Comment by bharvidixit** [comment]
@clintongormley what i enable doc_values=true for the metadata _id field? Will i have some effect?  "_id": {
          "store": true,
          "index": "not_analyzed",
          "doc_values": true,
          "path": "id"
        }

**Comment by jpountz** [comment]
@bharvidixit Actually we are also thinking about having doc values enabled on `_uid` too. This way, random sorting (which mostly merges a seed with a hash of the _uid to be reproducible) would not need to load fielddata on the _uid field (which takes a lot of memory all the time since this field is unique by definition). And it could also help have consistent pagination by tie-breaking on the `_uid` instead of the internal lucene doc ids (since they are not the same on all copies of a shard).

**Comment by gibrown** [comment]
Awesome, Thanks!

**Comment by bobrik** [comment]
:+1:

**Comment by jknewman3** [comment]
Is it possible to set eager loading, or something like that, for doc_values? 
It would be helpful for us to always have the most recently added data in cache.

**Comment by rjernst** [comment]
@jknewman3 See discussions on #8693

**Comment by jknewman3** [comment]
Ah, that helps a lot. Thanks!

**Comment by bolee** [comment]
how to set doc_value=true, via api to set every field?

**Comment by clintongormley** [comment]
@bolee please ask questions like that in the forum: https://discuss.elastic.co/
