### ISSUE TITLE
Provide observability via Micrometer 2.0.0 & Micrometer Tracing

### ISSUE THREAD

**Issue by marcingrzejszczak** [elastic/elasticsearch#83780]
### Description

# Introduction

With Micrometer 2.0.0 we're introducing a concept of an `Observation` ([you can read more about it here](https://micrometer.io/docs/tracing)). An `Observation` wraps an action that we would like to measure. A measurement can be wrapping it in a `Timer` (metrics), creation of a `Span` (tracing) or any other custom behavior such as e.g. logging. 

Let's check the following example

```java
ObservationRegistry registry = new SimpleMeterRegistry();
Observation observation = Observation.start("my.operation", registry);
try {
    observation.scoped(() -> doSomeWorkHere());
} finally {
    observation.stop();
}
```

Depending on the configuration of the `ObservationRegistry` there might be various outcomes when `doSomeWorkHere()` gets executed.

# Benefit

Using the Observation API makes you instrument your code once but you get multiple benefits out of it (e.g. metrics & tracing). Since Micrometer Tracing works with Micrometer we also bridge the span creation to such tracer implementations as OpenZipkin Brave and OpenTelemetry.

# Feature request

We would like to suggest that such instrumentation using Micrometer would happen in this project. Doing so would allow us to transparently continue any traces that occurred on the client side and have consistency in terms of used metrics. You could also emit metrics and traces (and whatever you want really) on the server side.

**Comment by rjernst** [comment]
Thanks very much for you interest in Elasticsearch.

Whilst we are grateful for ideas on how to improve Elasticsearch, those ideas do not always align with our own long term goals for the project. In this case, the change you are proposing would require an immense effort since the Elasticsearch codebase is quite large. Additionally, if we were to commit to such a large change, we would likely utilize Elastic's own APM library directly.

As such, we do not plan to make the suggested change, so I hope you don't mind that I close this issue.
