### ISSUE TITLE
Side param in edge_ngram token filter is deprecated long back even in 2.X but code cleanup is not done

### ISSUE THREAD

**Issue by amitmbm** [elastic/elasticsearch#83934]
### Elasticsearch Version

8.0

### Installed Plugins

none

### Java Version

_bundled_

### OS Version

macos

### Problem Description

`side` param in edge-n gram token filter is removed even in [2.x version](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/analysis-edgengram-tokenfilter.html)  but still code cleanup is not done, we should remove it completely from code as better alternatives are already mentioned in official doc.

### Steps to Reproduce

Refer edge [n-gram token filter in 8.X](https://www.elastic.co/guide/en/elasticsearch/reference/8.0/analysis-edgengram-tokenfilter.html) and [the master branch code](https://github.com/elastic/elasticsearch/blob/master/modules/analysis-common/src/main/java/org/elasticsearch/analysis/common/EdgeNGramTokenFilterFactory.java#L52) for the same.

**Comment by amitmbm** [comment]
@cbuescher I would like to work on this bug, I've previously worked on this class, as part of my PR https://github.com/elastic/elasticsearch/pull/55766/

**Comment by cbuescher** [comment]
@amitmbm thanks for the offer, I just looked at the code and indeed the documentation says this parameter is long deprecated. However, since we never really went ahead and removed it, the problem we are facing now is that there might be users out there still using the parameter. This makes this issue more complex than simply removing the old code. We need some way to ensure that before removal, we add some deprecation warning logic first and also need to make sure that whatever older supported index that is using this option is still functional. We're currently in the process of re-working our deprecation strategy, so I will put this up for team discussion but it might be a bit until we have a clear way of doing removals like this for future versions.

**Comment by benwtrent** [comment]
We need to move forward to deprecate applying these parameters. We should return a warning via a header like all other deprecation actions and in Elasticsearch 9, remove it. 

Note, this would be on new index creations.

**Comment by benwtrent** [comment]
Ah, this is now actually deprecated. It will be removed eventually now that its actually been deprecated.
