### ISSUE TITLE
Deprecate code when changing packages

### ISSUE THREAD

**Issue by hmottestad** [elastic/elasticsearch#83980]
### Description

I'm developing an application using Spring-Boot and Eclipse RDF4J. RDF4J is stuck on 7.8.1 and the Spring-Boot version I'm using is stuck on 7.15.2. Because of at least two breaking changes between 7.8.1 and the latest 7.17.0 there is no way to upgrade to 7.17.0.

 - https://github.com/elastic/elasticsearch/issues/82357
 - https://github.com/elastic/elasticsearch/pull/73909
 
The documentation for breaking changes in minor versions says:

> Breaking changes introduced in minor versions are normally limited to security and bug fixes. Significant changes in behavior are deprecated in a minor release and the old behavior is supported until the next major release."

Neither of the two breaking changes that I have come up against are security or bug fixes.

I would really appreciate if the classes could be moved back and deprecated and removed in the next major release.

**Comment by nik9000** [comment]
This has been fixed by building a client that doesn't rely on Elasticsearch's internal code: https://github.com/elastic/elasticsearch-java It was a mistake to try and use Elasticsearch's server in client for the reasons that you mentioned - we really didn't know what bit of the server landed in the client.

We're not going to move the classes back. Sorry.

**Comment by hmottestad** [comment]
:(
