### ISSUE TITLE
Ensure uncaught exceptions from executors are asserted and logged

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#84075]
### Description

If a Runnable is executing in Executor and throws an an exception, that exception can be silently ignored. The uncaught exception is almost certainly a bug, but one that can be difficult to see due to no log events. This is particularly bad if an exception is thrown, not caught AND a listener's onFailure() method is never invoked (possibly a memory leak without any errors in the log). Ideally all uncaught exceptions would be asserted to not happen via the testing and logged in case the test coverage is not complete. 

related: https://github.com/elastic/elasticsearch/pull/82002 - fixes a memory leak bug, but is very difficult to troubleshoot since there are no guarantees that the exception which triggers the leak will be in the log

**Comment by rjernst** [comment]
Since we control all executor creation through ThreadPool, I wonder if we can solve this there. We could wrap every executor we create with a delegating one, so that we can wrap the runnable/callables passed in and catch them ourselves, instead of bubbling up to oblivion.

Another possibility is to fix this in EsThreadPoolExecutor. `afterExecute` is already overriden, which is intended to handle uncaught exceptions in executions, but right now we rethrow that error. Perhaps we should instead handle asserting/logging there.

**Comment by jakelandis** [comment]
Apologizes for the noise here ... closing as not an issue.

While trying to provide a patch and reproduction scenario I found a flaw in my original assessment.  I had originally thought the exception that can trigger https://github.com/elastic/elasticsearch/pull/82002 went uncaught, but after further review it is indeed caught just logged at debug level.   Additional testing proves this issue as logged is not an issue and truly uncaught exceptions will be logged.
