### ISSUE TITLE
Add [indices:admin/rollover] permission for remote_monitoring_user

### ISSUE THREAD

**Issue by dnhatn** [elastic/elasticsearch#84161]
### Elasticsearch Version

8.0

The built-in `remote_monitoring_user` has [remote_monitoring_agent, remote_monitoring_collector] roles, which can't perform a rollover on metricbeat indices.

`
[org.elasticsearch.xpack.ilm.IndexLifecycleRunner] [instance-0000000001] policy [metricbeat] for index [metricbeat-7.15.2-2022.01.24-000001] failed on step [{"phase":"hot","action":"rollover","name":"check-rollover-ready"}]. Moving to ERROR step
org.elasticsearch.ElasticsearchSecurityException: action [indices:admin/rollover] is unauthorized for user [remote_monitoring_user] with roles [remote_monitoring_agent,remote_monitoring_collector] on indices [metricbeat-7.15.2,metricbeat-7.15.2-2022.01.24-000001], this action is granted by the index privileges [manage_follow_index,manage,all]
`

**Comment by tvernum** [comment]
@elastic/stack-monitoring Can someone have a look at this?
We can change the role definition, but since we don't manage the index creation or the ILM policy it's impossible for us to track which privileges these roles should have.

**Comment by matschaffer** [comment]
`metricbeat-*` won't be a monitoring index once 8.1 is out as well. In 8.0 it should contain only the entsearch metrics, I'd guess the metricbeat handling that collection is what's setting up with ILM policy.

Is this just a standard ESS cluster with ent search & monitoring enabled? Self or dedicated? Any details are appreciated.

**Comment by matschaffer** [comment]
So it looks like this case had a 7.16 enterprise search instance that was downscaled prior to the upgrade to 8.0.

It's still a little confusing to me how we wound up with an ILM policy created by `remote_monitoring_user` but I'd guess we can sort out how that happened by looking at ESS behavior. It's possible that's the norm too, I'm only directly familiar with the ES-managed ILM policies (https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/core/src/main/resources/monitoring-mb-ilm-policy.json) or internal collection indices which don't use ILM.

**Comment by dnhatn** [comment]
Per @dakrone

> ILM performs the actions as whichever user last updated the policy, so in this case, remote_monitoring_user was the last user that changed the policy.

**Comment by matschaffer** [comment]
@dnhatn indeed. What I'm fuzzy on is which component created the policy in this case. I presume it was metricbeat running as the `remote_monitoring_user` but it'd be nice to observe ESS start up to be sure.

It also might present a point of confusion if the metricbeat that collects ES metrics (ESS managed) is creating that policy, which might be relied on by other metricbeats, like those running in an external data center reporting back to ESS.

**Comment by matschaffer** [comment]
@s-nel or @gigerdo - can you cross check the user & roles given to the allocator-launched metricbeat?

I wonder if maybe it's a user that's given only the `remote_monitoring_user` which is what's leading the ILM issues.

**Comment by matschaffer** [comment]
Okay, so a few notes after DMing with @joegallo and @s-nel :

On ESS, metricbeat runs as a different user with manage privileges over the `metricbeat-*` index space, as well as logging (code is internal, noting for later reference if needed https://github.com/elastic/cloud/blob/1092e472d143cef136a46763887fa64d7b71aee6/scala-services/runner/src/main/scala/no/found/runner/allocation/common/observability/ObservedDockerContainer.scala#L686-L711)

On a reference cluster of my own (8.1) I can confirm from cluster state (`jq '.metadata.index_lifecycle.policies.metricbeat'` then decode the `_xpack_security_authentication`) that the policy is running as the expected user.

So ESS should be fine.

What it looks like probably happened here is that something outside ESS re-pushed the `metricbeat` ILM policy as the `remote_monitoring_user` (built-in https://www.elastic.co/guide/en/elasticsearch/reference/current/built-in-users.html).

But that user lacks the appropriate permissions to preform rollover.

What I still don't know is if this is intentional or not. Just from reading the docs I don't get the impression `remote_monitoring_user` is supposed to be able to make pipeline changes.

> The user Metricbeat uses when collecting and storing monitoring information in Elasticsearch.

I wouldn't put pipeline changes under the heading of "collecting and storing". But it does have the `manage_ingest_pipelines` permission so maybe it is? 

https://github.com/elastic/elasticsearch/blob/bc3154869a86b15eaf7de527b53e9e723aaf14bf/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/store/ReservedRolesStore.java#L136

It's had that permission for a long time though, so I'm still poking around git to see if there's some original author we can check with. In the mean time I'll reach out in beats slack to see if someone can confirm.

**Comment by matschaffer** [comment]
K, looks like `manage_pipeline` got added to `remote_monitoring_agent` in [0d1f3da3530544f94f52c4265aa049b602c056de](https://github.com/elastic/elasticsearch/commit/9e08579d4f3e118c56e6c7ef8c2ca2822890a313#diff-a03f59258f2be020c94552690e566f7e2f9e5ddbbeddefcc32e8656bbbe15149R126) back in 2016 by @jaymode - kind of along shot if he recalls, but I get the impression it wasn't intentional.

Might be better to remove the `manage_pipeline` permission so a user attempting to push ILM using `remote_monitoring_user` gets an upfront error.

Hopefully we can find a beats SME to comment.

**Comment by matschaffer** [comment]
To be clear, we still need a decision. @ruflin recommended that @elastic/elastic-agent-data-plane is probably the best team.

Should we:

### A: remove the `manage_pipeline` permission from `remote_monitoring_agent ` (and thereby `remote_monitoring_user`)? 

This should lead to any similar case causing a metricbeat failure as soon as it tried to update the ILM policy. Operators would have to use a different user/role to allow metricbeat to set up pipelines.

### B: add the `indices:admin/rollover` permission to `remote_monitoring_agent ` (and thereby `remote_monitoring_user`)?

This would allow ILM management and rollover for that user. Operators would be able to use this user for _both_ ILM management and data ingest.

cc @kvch @sayden @jasonrhodes

**Comment by matschaffer** [comment]
If I'm free to make the decision, I'll pick A. But I'm not clear if that's the case here.

**Comment by tvernum** [comment]
I would content that **A** is a breaking change. Users with that role would end up with less privileges, which may cause things to break unexpectedly.

**Comment by jasonrhodes** [comment]
I think both are breaking changes. In one case we're removing privileges, in the other we're "secretly" escalating privileges of a user. I'd prefer A in that case, to be honest, but this sounds like it needs a product decision. @ravikesarwani @nimarezainia can you weigh in here?

@matschaffer this is likely an edge case, right? Still worth fixing but would be helpful to know a very rough gut-feel on how often we'd see this, so the product folks can use that as part of their decision here.

**Comment by matschaffer** [comment]
I've only ever seen it once, but it's possible we'll see it more as more indices (like monitoring in 8.0) move to ILM.

It'd be great if we had some sort of telemetry data on if people actively use `remote_monitoring_user` or something else when configuring metricbeat.

**Comment by matschaffer** [comment]
Ah, another thought I had on this @tvernum is that while A is breaking, it's breaking earlier in the process: Immediately when launching metricbeat rather than during a rotation N days later.

**Comment by matschaffer** [comment]
Well I just found https://www.elastic.co/guide/en/elasticsearch/reference/8.2/collecting-monitoring-data.html, so I guess the answer is:

B: add the indices:admin/rollover permission to remote_monitoring_agent (and thereby remote_monitoring_user)?

**Comment by jasonrhodes** [comment]
Did you mean in this doc? https://www.elastic.co/guide/en/elasticsearch/reference/8.2/configuring-metricbeat.html

In the one you linked, it's referring to internal collection -- are we also running into this ILM problem for internal collection users in 8.0+?

Either way, I think you're probably right that it sounds like making sure the user we recommend can handle the index management is the right/simplest choice. Is the ILM privilege scoped to just the indices the role has access to manage?

**Comment by matschaffer** [comment]
I'm pretty sure if we add it to this section it'll be scoped to just the indices in question

https://github.com/elastic/elasticsearch/blob/bc3154869a86b15eaf7de527b53e9e723aaf14bf/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/store/ReservedRolesStore.java#L143-L148

similar to what happens here for `kibana_system`:

https://github.com/elastic/elasticsearch/blob/bc3154869a86b15eaf7de527b53e9e723aaf14bf/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/store/ReservedRolesStore.java#L743-L755

**Comment by jasonrhodes** [comment]
That sounds safe to me, then. 👍
