### ISSUE TITLE
Set default node name to hostname

### ISSUE THREAD

**Issue by printercu** [elastic/elasticsearch#8470]
I can't find any discussion on it. Can this be done? It would be convenient.

**Comment by AndreKR** [comment]
Please do so. :)

**Comment by clintongormley** [comment]
I think all we need to do here is to export `HOSTNAME` as a real environment variable, then users can use it easily in their config

**Comment by harisekhon** [comment]
How about just setting the node name to ```$HOSTNAME:<port>``` by default - that will account for multiple instances per host.

This is similar to what SolrCloud does (they actually do ```<ip>:<port>``` which is also unique but much less useful unless you only have a few servers and know all their IPs off by heart or enjoy doing DNS lookups - I changed those to hostname:port).

The Marvel names are interesting but were starting to make debugging more tedious so I've set them to hostnames too since I only have one instance per server.

In order to work around the
```
node.name ${HOSTNAME}
```
variable not being available you can put this in /etc/sysconfig/elasticsearch
```
export HOSTNAME=$(hostname -s)
```
which is easier to auto-manage across a cluster of nodes than say ```HOSTNAME=$HOSTNAME bin/elasticsearch``` if you're using automation and not starting nodes by hand. Note that the ```export``` keyword is required in /etc/sysconfig/elasticsearch unless you want to go around editing/copying your init scripts to do an explicit ```export HOSTNAME``` afterwards after sourcing that file. Most decent automation folks will already be managing elasticsearch.yml and sysconfig/elasticsearch anyway.
