### ISSUE TITLE
Improved Doc Routing 

### ISSUE THREAD

**Issue by drewinin** [elastic/elasticsearch#8472]
Currently if you want to take control of routing ES does a typical hash & mod operation on the routing parameter to determine which shard to rout data to. One would typically rout by userId, but a large user would of course cause issues with hotspotting a shard. I think this could be improved. 

If you could actually specify a shard # when indexing/searching then one could design their own data partitioning algorithm to split a user's data across a subset of the total shards in an index. 

Alternatively the ES API could 1st class this capability by accepting 2 additional routing parameters. EG take in a secondary routing param (for hashing) to determine which of x# shards the user's data is split across. If you had 10 shards, x = 3, then user's data is split across 3 shards with consistent hashing on the 2ndary routing param to pick which of the 3 holds that document. Searches need only provide the 1st routing param and x = 3, and all 3 shards would get lit up.

**Comment by ddorian** [comment]
Any recommendation on how(if possible) to do this on the client-side ? Meaning how to make sure "user:1shard:1" is not on the same shard as "user:1:shard:2" ?

**Comment by drewinin** [comment]
@ddorian We reverse engineered the routing mechanism to do it client side for the time being. You can check it out here https://github.com/MyPureCloud/elasticsearch-lambda/blob/master/src/main/java/com/inin/analytics/elasticsearch/index/routing/ElasticsearchRoutingStrategyV1.java

**Comment by s1monw** [comment]
your reply brought up my attention to this ticket - I wonder why you don't simply use multiple indices and make the decisions yourself client side? I mean you have full control over where a document goes, full control on how many shards the docs are distributed across and you can even put them on stronger machines. The last point is what makes me think we shouldn't implement this feature. You will get in-balanced shards if you use routing in a way you use it which is tricky since shard balancing doesn't take this into account (it's hard to do that really) if you have this on an index level as I suggested you have all the control over it yourself which you would lose on a shard level. Yet, if you feel this won't work for you can you please explain why?

**Comment by ddorian** [comment]
@s1monw Do 2-indexes made of 1-shard have the same overhead as 1-index made of 2-shards ? I assume the 2-shards-index has less overhead on the cluster.

**Comment by s1monw** [comment]
@ddorian there is certainly overhead here but what are we talking about, like some MB of heap space for data-strucutures to hold the metadata? From a search/indexing perspective there is no overhead at all.

**Comment by ddorian** [comment]
@s1monw 
In my case, I have monthly indexes. And having many monthly indexes for many big clients may have more overhead compared to 1-monthly-index with many shards ?

From a search-index perspective, having per-client indexes will actually be faster since you don't have to maintain a "client_id" indexed field.

Interested how the big log-as-a-service users do this. Maybe they do 1-client-index and maintain multiple clusters (so not all customers on 1 cluster) ?

**Comment by s1monw** [comment]
I think it depends on your distribution of customers you don't need an index per customer. You can have like 3 indices `small, medium, large` where you can use routing in the `small` index distribute over 3 shards int the `medium` and over 6 shards in the `large` one and you classify your customers into these categories. It's also easier to move customers from one to another in the next month and you might even end up with less shards eventually?

**Comment by s1monw** [comment]
> Interested how the big log-as-a-service users do this. Maybe they do 1-client-index and maintain multiple clusters (so not all customers on 1 cluster) ?

that is a good idea in general - you won't loose all customers on an incident, it's likely easier to migrate to new versions, etc.

**Comment by ddorian** [comment]
@s1monw 
Won't the small,medium,large situation be better by just having 1 index with the same number of shards as small,medium,large combined ?

By per-customer-index, I'm talking only about large customers. Small ones will go into shared indexes.

> 
It's also easier to move customers from one to another in the next month and you might even end up with less shards eventually?
I can't delete old-indexes (like log companies do) so probably not.

**Comment by s1monw** [comment]
> Won't the small,medium,large situation be better by just having 1 index with the same number of shards as small,medium,large combined ?

the entire issue is about that it can be problematic since if you use routing you get in-balanced shards? Why don't you just not use one big index without routing then? as far as I can tell you need to do more research on what is really your bottleneck. I am waiting for @drewinin before I close this issue

**Comment by ddorian** [comment]
@s1monw 
I don't use 1 big index without routing because ALL my queries filter on user_id, so I want to route on the those shard(s) and not scatter-gather on 30 shards(size of the shared index) for big clients but to keep on 2-3-4 etc shards depending on their size.

**Comment by s1monw** [comment]
see that is exactly why I recommend multiple indices for customers that don't fit into one shard

**Comment by drewinin** [comment]
@s1monw That'd work if we had predictable usage patterns. We have a lot of customers that ramp up usage 100x without warning. So they might be "small customer" for most of the year and then explode for a couple days. We do daily log indexes btw. We'd get caught by surprise having them in the "small customer index". It seemed simpler to have 1 index per day and balance customers across shards than trying to predict who's going to have a busy day.

**Comment by clintongormley** [comment]
Closing in favour of #21585
