### ISSUE TITLE
Extract actions for the shard availability health indicator

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#84797]
Once we've identified the most common unassigned shards situations where we know what the solution is (ie. elasticsearch *knows* where the shards should go) extract these scenarios into `actions` in the `shards availability` health indicator.

Each action should have a stable id / code that remains the same across releases, an explanation (for unassigned shards we can probably use the [allocation explanations](https://github.com/elastic/elasticsearch/blob/master/server%2Fsrc%2Fmain%2Fjava%2Forg%2Felasticsearch%2Fcluster%2Frouting%2Fallocation%2FExplanations.java), and a link to a troubleshooting doc.

**Comment by jbaiera** [comment]
### Brain storming response format for the actions. 

Actions should contain the following information:
1. A stable id to identify the action that should be taken (Always)
2. A text description that explains the actions to be taken (Always)
3. A list of indices/shards that the action should be taken on (Optional)
4. A troubleshooting URL to documentation pages (Optional)

Item 1 would be useful to use in concert with item 3 (if present) to allow the UI to customize how it would like to present the information for the action, with item 1 defining the action to be taken in unambiguous terms and 3 providing optional additional info for things that the action should be taken on.

Item 2 would allow for straightforward display of action information directly in the response. This allows humans executing the response to see human readable information, as well as a good default message to display in UI's. 

Item 4, if present, should be an evergreen stable link to a help page of some kind that gives additional depth of information for the action to perform. Help URL's should not be assumed to be unique for each action. URL's are likely to change between releases, but any previously returned URL should continue to point to a valid help page.

#### Action formatting options:

```json
"user_actions": [
  {
    "id": "migrate_data_tiers",
    "indices": ["hot_index_1", "warm_index_7", "cold_index_99"]
    "message": "[40] shards could not be allocated because their allocation filtering rules clash with their tier requirements. Try migrating indices to official data tier support. Indices affected [hot_index_1, warm_index_7, cold_index_99]"
    "help_url": "https://........"
  }
]
```

Alternatively:
```json
"user_actions": {
  "migrate_data_tiers": {
    "indices": ["hot_index_1", "warm_index_7", "cold_index_99"]
    "message": "[40] shards could not be allocated because their allocation filtering rules clash with their tier requirements. Try migrating indices to official data tier support. Indices affected [hot_index_1, warm_index_7, cold_index_99]"
    "help_url": "https://........"
  }
}
```

Concerns: Assuming that a large number of indices can be listed under an action, we should redact the number up to a maximum in the action text. Instead of "indices" or "shards" perhaps we could use the field name "index_sample" or "shard_sample"?

#### Where the actions fit into the response. 

We could make it a part of the details body:
```json
"shards_availability": {
  "status": "green",
  "summary": "This cluster has all shards available.",
  "details": {
    "started_replicas": 0,
    "initializing_primaries": 0,
    "restarting_replicas": 0,
    "restarting_primaries": 0,
    "unassigned_replicas": 0,
    "creating_primaries": 0,
    "started_primaries": 1,
    "unassigned_primaries": 0,
    "initializing_replicas": 0,
    "user_actions": [....]
  }
}
```

Alternatively, if we want actions to be something any indicator can suggest, maybe we make it part of the root indicator response?
```json
"shards_availability": {
  "status": "green",
  "summary": "This cluster has all shards available.",
  "user_actions": [....],
  "details": {
    "started_replicas": 0,
    "initializing_primaries": 0,
    "restarting_replicas": 0,
    "restarting_primaries": 0,
    "unassigned_replicas": 0,
    "creating_primaries": 0,
    "started_primaries": 1,
    "unassigned_primaries": 0,
    "initializing_replicas": 0
  }
}
```

**Comment by dakrone** [comment]
> Alternatively, if we want actions to be something any indicator can suggest, maybe we make it part of the root indicator response?

Is there going to be a case now or in the future where we want the `details` without the `user_actions`, or we want `user_actions` without the details? I think for that reason having it be a sibling rather than child of `user_actions` sounds better to me.

**Comment by Leaf-Lin** [comment]
> I think for that reason having it be a sibling rather than child of `user_actions` sounds better to me.

I think you mean ... rather than child of `details`? 😉 

----
1. I prefer the original action format with `id` and `action_name`.  The reason being `key:value` are easier to parse in jq or other json parsing (like kibana ml function) than having the nested structure.  

2. I'm in favour of the following structure because the `user_actions` may be overlooked in the `details` (and for some other health indicator, details may contain much more information.  Having `user_actions` at the root level also indicate its importance and surface visibility to users:
```json
"shards_availability": {
  "status": "green",
  "summary": "This cluster has all shards available.",
  "user_actions": [....],
  "details": {
    "started_replicas": 0,
    "initializing_primaries": 0,
    "restarting_replicas": 0,
    "restarting_primaries": 0,
    "unassigned_replicas": 0,
    "creating_primaries": 0,
    "started_primaries": 1,
    "unassigned_primaries": 0,
    "initializing_replicas": 0
  }
}
```
3. I'm just wondering if `clash` is a bit too casual? Maybe `conflict`? 
4. What happens if there are thousands of indices in the array, do we still want to report the full list or a truncated list of all indices affected?

**Comment by andreidan** [comment]
Thanks for putting this together @jbaiera It's great to visualise some of the available options.

> Is there going to be a case now or in the future where we want the details without the user_actions, or we want user_actions without the details?

I don't think so. The user actions will be displayed/actionable once we expand a component that has issues (the drill down call). On that premise, I'd say it's fine for it to be under `details` however a top level field would also work as long as it's only computed on drill down (the non-drilled API call will be polled so it'd need to be light and slim). I think the user actions will be the more heavyweight compute part of the indicators as it requires RCA.

On point 4.  I share @Leaf-Lin 's concerns about many indices. I'd also like to mention that this might be something we'll want to display later on as part of the health items (where we'd maybe have one item per index or such). 
As these user actions will be computed on drill-down (if we're all in agreement that should be the case?) I'd say it could work to display all the affected resources where we can identify them, but I wouldn't duplicate their listing in the message and in a separate field. Maybe an `affected_resources` field that lists the indices/data streams and a message stating the identified `cause` without the resources could work across indicators?

**Comment by masseyke** [comment]
If we have `actions` as a child of `details`, they won't come back in the response unless we drill down to the component or indicator (see #85234). I think that's probably the desired behavior but I'm mentioning it in case for some reason the UI is expected to show actions before drilling down. If we  have `actions` as a sibling of `details` we'll need to update the logic in #85234 to not compute/show the actions until drilling down.
Also for what it's worth, whenever we show indices in the `impacts` section (#84899), we're limiting it to no more than 10 indices (based on number of indices, not string length). That was a fairly arbitrary decision I made. We probably ought to be consistent and do the same thing in both places.

**Comment by jbaiera** [comment]
> If we have actions as a sibling of details we'll need to update the logic in https://github.com/elastic/elasticsearch/pull/85234 to not compute/show the actions until drilling down.

I think we'll need to detect if we're drilling down generally across all indicators so we know how much to compute for the status. I think if we're not drilling down, the code should just skip the diagnosis methods and carry on with an empty user_action field

> I'm just wondering if clash is a bit too casual? Maybe conflict?

Yeah, I'm not tied to any of the current wording, just a quick example sentence to show the structure of the response

>What happens if there are thousands of indices in the array, do we still want to report the full list or a truncated list of all indices affected?

> Also for what it's worth, whenever we show indices in the impacts section (https://github.com/elastic/elasticsearch/pull/84899), we're limiting it to no more than 10 indices (based on number of indices, not string length). That was a fairly arbitrary decision I made. We probably ought to be consistent and do the same thing in both places.

We can clamp it down to at max 10 items to put on the action. One of the suggestions I had was to change the `indices` field to be "index_samples" or "shard_samples", but that might be a bit confusing too? Not sure.

> On point 4. I share @Leaf-Lin 's concerns about many indices. I'd also like to mention that this might be something we'll want to display later on as part of the health items (where we'd maybe have one item per index or such).
As these user actions will be computed on drill-down (if we're all in agreement that should be the case?) I'd say it could work to display all the affected resources where we can identify them, but I wouldn't duplicate their listing in the message and in a separate field.

I think we're all in agreement that the actions should only display as part of a drill down. I fully agree that we shouldn't duplicate the affected resources in the message, and I like the idea of using `affected_resources` instead of `indices` or `shards`.

**Comment by elastichelix** [comment]
> I think that's probably the desired behavior but I'm mentioning it in case for some reason the UI is expected to show actions before drilling down. 

The UI has no plans to show actions until after drill-down. I have no preference on whether it is presented as a sibling or in the details block. However, if there is significant benefit in your perspective to putting it as a child of details, that should not be an issue from the UX that I have seen. (and makes sense to me -- it is a part of a detailed analysis of the issue and not part of the overview of the issue)

> I prefer the original action format with id and action_name. The reason being key:value are easier to parse in jq or other json parsing (like kibana ml function) than having the nested structure.

++ - I prefer this format as well. It will make it easy to display a list of actions to the user without dissecting the object. 

**Question**: is this list going to be ordered in anyway? I.e. Is this a sequential list or is it just a list of possible actions to take in no particular order?

**Comment by jbaiera** [comment]
> Question: is this list going to be ordered in any way? I.e. Is this a sequential list or is it just a list of possible actions to take in no particular order?

These will likely be unordered, though we may order them in the future based on what we think is most important. I think for now let's not assume any inherent ordering on the actions.

Additionally, after a discussion today at sync: There is still some details we would like to iron out before exposing ID's for all these new impacts and user actions. For now the user actions will not include any ID fields so that when we do settle on the final approach for them it wont be a breaking change to update them if there are changes.
