### ISSUE TITLE
[DOCS] Incorrect version in dependencies version doc

### ISSUE THREAD

**Issue by eedugon** [elastic/elasticsearch#84863]
### Elasticsearch Version

7.16.3

### Java Version

_bundled_

### OS Version

irrelevant

### Problem Description

The following doc shows `7.16.4` as the version, and that version is not even planned.
https://www.elastic.co/guide/en/elasticsearch/reference/7.16/dependencies-versions.html

<img width="574" alt="image" src="https://user-images.githubusercontent.com/25320357/157647909-a7ef4420-0dea-42f4-a6a6-21a0bd98a431.png">

cc: @DaveCTurner 

### Steps to Reproduce

open https://www.elastic.co/guide/en/elasticsearch/reference/7.16/dependencies-versions.html

**Comment by pugnascotia** [comment]
I'm wondering whether page is auto-generated. I tagged the docs folks in case they have thoughts here.

**Comment by mark-vieira** [comment]
This whole page seems... odd. It basically just https://github.com/elastic/elasticsearch/blob/7.16/build-tools-internal/version.properties which is in no way intended to be user facing and it's not an exhaustive list of our dependency by any stretch.

We also generate a "full" dependency report that I thought was used to link to from the download page but it seems to be missing now.

**Comment by geekpete** [comment]
This is the related PR I believe:
https://github.com/elastic/elasticsearch/pull/67962

The idea was to surface the versions of library/tool dependencies like the JDK, Lucene and others in the docs for an easy way to find those versions that allows for checking if a bug or issue in a dependency might be affecting how Elasticsearch is operating.
Before we had this doc it you'd need to go and find the file in the source and the location of that file has changed at least once so wasn't easy to keep track of.

It seems the approach taken has issues with accuracy with just surfacing the build file that contained all of this detail in one place. One big issue is that the docs can only dynamically reference a major.minor version in the URL and not maintenance versions where dependency versions might change within the same minor version, such as with Log4J.

It'd be great to:
- keep this in the docs and fix it so that it lists some kind of matrix or full list of differing dependency versions per maintenance version
- ensure it doesn't display non-released versions

but it might also be an interesting feature to have as a CLI parameter or API to be able to surface this information which might provide more accuracy than documentation by dumping out the actual dependencies a particular binary was built against.

In the short term, this is likely to be dangerous if we leave it as is if users trying to confirm some particular security bug against versions we might document here and are reading it wrong thinking we've updated to some later library version when it's not correct.

**Comment by debadair** [comment]
@geekpete Is correct about the motivation/genesis of this page. It was a low-overhead way to provide this information without having to manually keep it up to date. If it shows incorrect information, however, that completely defeats the purpose. Not sure without looking, but this might be a case of unintended consequences from updating version attributes.

Providing this information through an API would be a vastly better solution--doc "workarounds" like this are always problematic.

**Comment by debadair** [comment]
This dropped off the radar, but the version bump process makes this current "solution" a poor choice. @mark-vieira where is the full dependency report published? Linking to that would be preferable.

**Comment by mark-vieira** [comment]
> This dropped off the radar, but the version bump process makes this current "solution" a poor choice. @mark-vieira where is the full dependency report published? Linking to that would be preferable.

That's a great question. We used to link to it from the downloads page but that has been lost when it was redesigned. @mgreau do you know where we publish the dependency report?

**Comment by mgreau** [comment]
The full report is available here https://artifacts.elastic.co/reports/dependencies/dependencies-current.html and accessible from https://www.elastic.co/third-party-dependencies

**Comment by mgreau** [comment]
If you need a specific version then it's `https://artifacts.elastic.co/reports/dependencies/dependencies-<VERSION>.html` like https://artifacts.elastic.co/reports/dependencies/dependencies-7.16.3.html

**Comment by geekpete** [comment]
For now, could we just link from the main Dependencies appendix page to all the maintenance release version pages and do this in some autogenerated way?

From here: 
https://www.elastic.co/guide/en/elasticsearch/reference/7.16/dependencies-versions.html

Link to these:
https://artifacts.elastic.co/reports/dependencies/dependencies-7.16.0.html
https://artifacts.elastic.co/reports/dependencies/dependencies-7.16.1.html
https://artifacts.elastic.co/reports/dependencies/dependencies-7.16.2.html
https://artifacts.elastic.co/reports/dependencies/dependencies-7.16.3.html

We'd need some variable (or docs loop function) containing all the maintenance releases for a given major.minor to be able to loop through and generate the list of link urls?

What would be better but outside the scope of this issue is a matrix table (if it can fit on the page in some sensible navigation way) that shows all the dependency versions against maintenance release versions with some color/highlight where there's differences between maintenance versions for a given dependency with multiple versions to make it easier to visually diff the versions or quickly get an idea of when some dependency changed over time.

Or simpler again might just be a single color/highlight to indicate a dependency version changed in a particular release, the point-0 releases will likely have lots of these highlights potentially.
Another angle might just be a filterable dependency specific changelog that you can search for dependencies of particular matches between some version range.

**Comment by debadair** [comment]
Thanks @mgreau!
