### ISSUE TITLE
Bug: Add alias to missing index gives 403 instead of 404

### ISSUE THREAD

**Issue by buergimi** [elastic/elasticsearch#85020]
Hi

Thank you for your exceptional product. I'd like to inform you of a bug I encountered when I was turning on user authentication and authorization in my elasticsearch server.

tested with Elasticsearch v8.1

```
		$index_name = 'foo1';
		$alias_name = 'bar';
		$request =
			[
				'actions' => [
					[ 'add' => [ 'alias' => $alias_name, 'index' => $index_name ] ],
				],
			];
		$code = $this->send_request('POST', '/_aliases', $request, $response);
```

The index `foo1` in this example does not exist.

This code is from our own abstraction of the elasticsearch api, but it should be sufficient to unterstand what is going on.

`$code` contains the http status code returned by the api. 

If I run this query as a non-superuser that is allowed to access the indexes "foo*" only, it returns the status code 403. If I run this query as superuser, I get a 404.

I think the status code 404 is correct (for both superuser and non-superuser). 

A 404 would conform with this request:

```
$code = $this->send_request('HEAD', '/' . $this->escape_index_name($index_name), null, $response);
```

This request returns a 404 for both superuser and non-superuser.

**Comment by ywangd** [comment]
This behaviour is expected. IIUC, what is happening with your abstraction of ES API is equivalent to the following:
```
POST _aliases
{
  "actions": [
    {
      "add": {
        "index": "foo1",
        "alias": "bar"
      }
    }
  ]
}
```

And you said
> If I run this query as a non-superuser that is allowed to access the indexes "foo*" only, it returns the status code 403. 

The user does not have access to the name `bar`. That's why you got 403. This check is done before the code can goes further to decide whether `foo1` exist or not (which is what happened for a `superuser`)

You should also be able to see the exact cause in the error response which is along the line of
> action [xxx] is unauthorized for user [xxx] with roles [xxx] on indices [bar] ...

Note the error message lists `bar` as the reason for `403`. I hope this helps.

**Comment by buergimi** [comment]
Thank you very much, Wang Yang. Very quick and precise. And sorry for my mistake.
I definitely should have checked the response body…
