### ISSUE TITLE
Add token location to exceptions thrown when parsing documents

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#85083]
Today in many places where we throw exceptions while parsing documents we use `MapperParsingException`. This exception does not hold the token location, which would be good to include in the error message, usually done by using `XContentParseException` which accepts the token location as a constructor argument.

We should either switch exception (would that have side effects?) or add the token location to the existing exception. It is a shame that it is possible to provide information back about where the parsing problem occurred, yet we don't take advantage of this.

**Comment by romseygeek** [comment]
I don't think we should be using `MapperParsingException` at all for document parsing - as its name suggests, it should be for errors found while parsing mappings, and because we realise mappings into Java Maps before parsing them there's no token location information to be had.  Instead we should use either a new DocumentParsingException or one of the existing XContent parsing exceptions which *do* preserve token location information.

Related: https://github.com/elastic/elasticsearch/issues/53106

**Comment by pgayvallet** [comment]
Just FYI: this change led to failures in the Kibana integration tests during the latest ES promotion: https://github.com/elastic/kibana/issues/154278. 

The failures were not false positives, and the changes from this PR would have led to real bugs on the Kibana side if said changes weren't caught by our integration test suites.

The fix was fairly trivial to implement (just properly interpreting the new/changed error type, https://github.com/elastic/kibana/pull/154411), however:

I see the PR is just labeled as enhancement, not as breaking change, which seems potentially wrong to us:

The API's behavior (here, the return value in case of a given scenario) changed for a predefined state and input, which is ,technically speaking, considered breaking.  What do you think about it?

cc @elastic/kibana-core

**Comment by romseygeek** [comment]
@pgayvallet that's fair, I will adjust the labels to mark this as a breaking change.
