### ISSUE TITLE
Aggregations: give information about accuracy in the response from cardinality

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#8508]
This is a feature request that has come up a couple of times on the [mailing list](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/elasticsearch/zx9UFt2JPNY/6RWURKQMhR8J) and from the Kibana team: it would be useful to get a sense of how accurate responses from the cardinality aggregations are, similarly to what we are doing with the terms aggregation.

**Comment by polyfractal** [comment]
Thinking out loud:

- We can provide theoretical estimates, since those are well defined

- If all the HLL sketches are still in linear counting mode, and the union of all sketches doesn't upgrade to HLL mode, the error can safely be reported as 0%

- When collecting values, we can increment a counter whenever the HLL sketch changes due to an update.  This would provide a mostly accurate per-shard cardinality*.  The counts could then be summated to provide a worst-case upper error bound, which assumes all shards have unique sets of values.

**Note: will under-count due to collisions.  Maybe needs a "long range" correction when collisions start to accumulate at high cardinality?*

**Comment by wchaparro** [comment]
Closing this out after our team discussion on this. No straightforward way to provide this information, and not frequently requested enough.
