### ISSUE TITLE
Aggregations: SingleBucketAggregation should create a single bucket 

### ISSUE THREAD

**Issue by brwe** [elastic/elasticsearch#8510]
`SingleBucketAggregations` (like filter aggregation) have no method `getBuckets()` and also the json response contains no buckets array. This saves some space but also makes it harder to traverse the aggregation tree because when looking at the result one always has to know if the aggregation that produced the current level was a `SingleBucketAggregation` or a `MultiBucketAggregation` (like terms agg).

Example for json:

Request with top level multi bucket agg:

```
POST testidx/_search?size=0
{
  "aggs": {
    "terms": {
      "terms": {
        "field": "label",
        "size": 10
      },
      "aggs": {
        "histogram": {
          "histogram": {
            "field": "num",
            "interval": 1
          }
        }
      }
    }
  }
}
```

Request with top level single bucket agg:

```
POST testidx/_search?size=0
{
  "aggs": {
    "terms": {
      "filter": {
        "term": {
          "label": "label_a"
        }
      },
      "aggs": {
        "histogram": {
          "histogram": {
            "field": "num",
            "interval": 1
          }
        }
      }
    }
  }
}

```

multi bucket yields:

```
"aggregations": {
      "terms": {
         "doc_count_error_upper_bound": 0,
         "sum_other_doc_count": 0,
         "buckets": [
            {
               "key": "label_a",
               "doc_count": 3,
               "histogram": {
                  "buckets": [
                     {
                        "key": 1,
                        "doc_count": 1
                     },
                    ...

```

single bucket yields:

```

"aggregations": {
      "terms": {
         "doc_count": 3,
         "histogram": {
            "buckets": [
               {
                  "key": 1,
                  "doc_count": 1
               },
               ...

```

although the two requests have the same level of "nestedness". If I was to post process the result I would have to change whichever application is consuming it when I change the top level aggregation from single to multibucket or the other way round.

The following would be more convenient for the second request:

```
"aggregations": {
    "terms": {
      "doc_count": 3,
      "buckets": [
        {
          "key": "some_key_that_makes_sense",
          "histogram": {
            "buckets": [
              {
                "key": 1,
                "doc_count": 1
              },
            ...

```

This also affects the coming soon `getProperty` method for aggregations which is currently implemented to be consistent with the different behavior of single and multi buckets: https://github.com/elasticsearch/elasticsearch/pull/8421#discussion_r20424480

**Comment by javanna** [comment]
Looking at the discussion that happened on this ticket, I would say that there was no consensus on making this change hence we may want to close it. Or should we discuss it again on the next FixItFriday @clintongormley ?

**Comment by clintongormley** [comment]
@javanna Should probably be a discussion for the aggs team - part of the decision about whether we need to refactor the aggs framework and how we'd do it.  Marking has high hanging fruit

**Comment by javanna** [comment]
cc @colings86

**Comment by colings86** [comment]
We spoke about this in the aggs team meeting and although there was almost a consensus feeling that this would be good to fix, there currently isn't a way to change the response format of an aggregation without making a hard braking change with no period of deprecation which makes this change very tricky and we didn't feel the current arguments for this change warrant such a harsh break int eh product on a major version or not. If/When we implement https://github.com/elastic/elasticsearch/issues/11184 we should revisit this since it would provide a path for this change to be made but until then this is effectively stalled

**Comment by colings86** [comment]
After discussing this again I am closing this issue because there is not a definitive argument for why this would be better and after the format being set for this long we should only change the format if there is a very compelling reason. In this case there are good arguments on both sides and there is no definitive argument for this.
