### ISSUE TITLE
Provide more information about autoscaling policy decisions to improve debugging

### ISSUE THREAD

**Issue by fcofdez** [elastic/elasticsearch#85243]
In some contexts is unclear why an autoscaling policy decides to request
more resources, i.e. if there's an unassigned shard that remains unassigned
even after adding more resources. It would be help to have more information
around the decisions taken by the deciders so it is easier to understand and
track them.

**Comment by henningandersen** [comment]
Reopening this, since we only implemented one part of this: listing the shard-ids involved. We also want to add allocation explain information. I imagine the following:

1. If there are any shards in the unassigned list in the reason, let us pick the first one and add an allocation explain to the output.
2. Likewise, if there are any shards in the assigned list in the reason, let us pick the first one and add an allocation explain to the output.

Those would be two different fields.
