### ISSUE TITLE
Batched cluster state executors can leak deprecation info across response threads

### ISSUE THREAD

**Issue by jbaiera** [elastic/elasticsearch#85506]
Discovered this issue in some of our tests where indexing a new document that creates a new index results in a deprecation log meant for a completely unrelated index. This seems to be a wider problem with `TaskBatcher` and its management of thread contexts when calling executors.

#### AutoCreateIndex example:
When indexing a document to an index that does not exist, the `TransportBulkAction` forwards requests to create new indices to `AutoCreateAction.TransportAction`. This action maintains a cluster state executor instance that applies multiple create index requests in one operation. The create request is submitted to the master service where it is batched together with other index auto creation tasks using the executor instance as a batching key. When the state is meant to be applied, the executor is called from the cluster state update thread and iterates over the indices, creating each one. After each index is created, the executor calls the listener that is waiting on that index creation and moves on to the next create call in the batch.

The problem arises if one of the indices in a batch generates a deprecation log of some sort. An example would be using a dot-prefixed index name on a non-hidden/non-system index. This deprecation log is stored in the ThreadContext of the current thread so that it may be surfaced to remote clients through an HTTP header. After the index is created, the next index to be auto-created in the batch is processed but the ThreadContext is not cleared out from the previous task. When this unrelated index is created, the listener picks up the same deprecation log from the previous index in the batch, thus leaking the deprecation notice into a response that may be unrelated to the original deprecation message.

This problem is seen in a number of test failures where a document is being written but returns an unrelated deprecation log in the response, which fails the test as it was not expecting a deprecation warning. Examples include #83366, #84993, and #84885. I was able to reproduce the error with a client program that submits a number of index requests for indices that do not exist, half of which generate a deprecation log. Deprecation logs for unrelated indices were present on responses for valid index names:

<pre><code>WARNING: request [POST http://localhost:9200/<b>index-298753</b>/_doc] returned 2 warnings: [299 Elasticsearch-8.2.0-SNAPSHOT-d2d87578150e215d08a9a8ae896168f07b822895 "index name [<b>.index-384428</b>] starts with a dot '.', in the next major version, index names starting with a dot are reserved for hidden indices and system indices"],[299 Elasticsearch-8.2.0-SNAPSHOT-d2d87578150e215d08a9a8ae896168f07b822895 "index name [<b>.index-81812</b>] starts with a dot '.', in the next major version, index names starting with a dot are reserved for hidden indices and system indices"]</code></pre>

The request references `index-298753` but receives warnings for indices `.index-384428` and `.index-81812` which are not present in that request, but were submitted around the same time. This happens reliably even over a relatively small number (40) of asynchronously submitted requests (in my test, one thread using the new async java rest client).

Notably, the CreateIndexAction [does not submit cluster state updates in a batched manner][normal]. In my recreation attempts I was not able to reproduce the problem when creating the indices directly. The problem only arises when indexing a document that would create a new index.

[normal]: https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexService.java#L312-L315

**Comment by jbaiera** [comment]
I think the above issue is a good example of a wider problem with task batching in that executors are implicitly responsible for keeping thread context clean between each task execution in a batch but there is currently no single thing that enforces that. From what I can tell, this is the responsibility of each executor implementation to handle correctly, but it would be great if there were a way to guarantee this invariant in one place, perhaps within the TaskBatcher itself. I looked through a couple instances of batch executors and their structures look largely the similar: `for each task context, possibly modify cluster state, end, return cluster state`. Perhaps a refactoring can remove some boilerplate across the implementations and isolate each task execution with a fresh/restored ThreadContext.

**Comment by DaveCTurner** [comment]
The trouble with a general solution is that there is no general pattern for how these executors run. The pattern you mention is actually something of an antipattern (vs updating lower-level things) because of the expense of repeatedly constructing a whole cluster state on each iteration:

https://github.com/elastic/elasticsearch/blob/13bee123ff65419de2e805726ad8d23dfb8d4769/server/src/main/java/org/elasticsearch/cluster/ClusterStateTaskExecutor.java#L28-L31

Executors like `ShardStartedClusterStateTaskExecutor`, `ShardFailedClusterStateTaskExecutor` and `SnapshotsService#SHARD_STATE_EXECUTOR` don't really fit this pattern. But then these executors are unlikely to want to emit any deprecation warnings either.

We can at least detect this kind of leak and give the executor better tools to deal with it, see https://github.com/elastic/elasticsearch/pull/85525.

**Comment by DaveCTurner** [comment]
Turns out this is trickier than it first appeared. For instance `AllocationService#reroute()` may emit deprecation warnings but we only typically call this once per batch. Which listeners should get those warning headers? Similarly, when opening indices we deduplicate the list of indices first, then iterate over the deduplicated list, so each iteration may correspond with many different task contexts.
