### ISSUE TITLE
[DOCS] Split the page Fix common cluster issues into separate pages

### ISSUE THREAD

**Issue by alaudazzi** [elastic/elasticsearch#85610]
The page [Fix common cluster issues](https://www.elastic.co/guide/en/elasticsearch//reference/master/fix-common-cluster-issues.html) is one of the [troubleshooting links](https://github.com/elastic/cloud/issues/92183#issuecomment-1017303716) that are going to be created on the deployment health banner to link error messages to relevant doc pages.

This page is too long and requires lots of scrolling. We can get a better user experience if we:
- link from the UI to the specific sections of this page
or
- split the page into separate pages (better for SEO)

CC @debadair 

Relates to https://github.com/elastic/cloud/issues/92183

**Comment by debadair** [comment]
Discussed with @alaudazzi.  While there is a benefit to being able to see all the issues in one place, one large page is less than optimal for cross referencing a specific item as well as SEO. Plan is to create separate topics/pages for each entry, and include those individual entries on the main troubleshooting page. We can exclude the invidual pages from the TOC so that they do not appear twice.

**Comment by kilfoyle** [comment]
When the "Common cluster issues" page is split up will the following URL still be available, perhaps as a parent to the sub-pages?
`https://www.elastic.co/guide/en/elasticsearch/reference/current/fix-common-cluster-issues.html`

The Cloud API has a hardcoded link to the above URL. It was added recently via https://github.com/elastic/cloud/pull/101302
