### ISSUE TITLE
Lack of validation of the path in the shared filesystem snapshot repository leads to unexpected behavior

### ISSUE THREAD

**Issue by masseyke** [elastic/elasticsearch#85934]
### Elasticsearch Version

8.1.2

### Java Version

_bundled_

### OS Version

N/A

### Problem Description

A user reported creating a local FS repository with a leading ` ` in the location, like:
```
curl -X PUT "localhost:9200/_snapshot/my_repository" -H 'Content-Type: application/json' -d'
{
  "type": "fs",
  "settings": {
    "location": " /tmp/my_repo"
  }
}
'
```
They had set `path.repo` to `/tmp` so they had expected the repository to be located at `/tmp/my_repo`. However it actually gets created at `/tmp/ /tmp/my_repo` because of the way we resolve the path at https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/repositories/fs/FsRepository.java#L94. We probably ought to either trim leading whitespace there, or throw an exception on leading whitespace.

### Steps to Reproduce

See above

**Comment by DaveCTurner** [comment]
Today's behaviour is as intended, although I do see how it might not be what the user expected in this case. By design the `location` of a shared filesystem repository may be an absolute or a relative path, and a single space is a perfectly valid directory name, so `"location":" /tmp/my_repo"` is an acceptable way to specify a repository located at `/tmp/ /tmp/my_repo` using a relative path. I do agree that this seems to be a bit of an odd thing to want, but that's not a good enough reason to forbid it. In general it's risky to apply extra constraints on paths on top of the restrictions imposed by the OS itself: leading whitespace is ok with the OS and so it should be ok with us too.

Once the mistake is noticed it should be relatively straightforward to fix by using the [repository backup/restore process](https://www.elastic.co/guide/en/elasticsearch/reference/current/snapshots-register-repository.html#snapshots-repository-backup) to relocate the repository to the right location.
