### ISSUE TITLE
The maximum number of clauses automatically gets set to 1024 when heap size is less than 1GB

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#86136]
The code to compute the maximum number of clauses looks like this:

```java
    public static int calculateMaxClauseValue(ThreadPool threadPool) {
        int searchThreadPoolSize = threadPool.info(ThreadPool.Names.SEARCH).getMax();
        long heapSize = JvmStats.jvmStats().getMem().getHeapMax().getGb();
        return calculateMaxClauseValue(searchThreadPoolSize, heapSize);
    }

    static int calculateMaxClauseValue(long threadPoolSize, double heapInGb) {
        if (threadPoolSize <= 0 || heapInGb <= 0) {
            return DEFAULT_MAX_CLAUSE_COUNT;
        }
        // In a worst-case scenario, each clause may end up using up to 16k of memory
        // to load postings, positions, offsets, impacts, etc. So we calculate the
        // maximum number of clauses we can support in a single thread pool by
        // dividing the heap by 16k (or the equivalent, multiplying the heap in GB by
        // 64k), and then divide that by the number of possible concurrent search
        // threads.
        int maxClauseCount = (int) (heapInGb * 65_536 / threadPoolSize);
        return Math.max(DEFAULT_MAX_CLAUSE_COUNT, maxClauseCount);
    }
```

@nkhristinin reported the following surprising behavior. Say you have 1 vCPU and 2 search threads,
 - If you have 1GB of heap to the JVM then `maxClauseCount` will be 32,768.
 - But if you give slightly less than 1GB to the heap, e.g. 1023MB, then `long heapSize` will be 0 because of the cast performed by the `getGB()` call, and `maxClauseCount` will be set to 1,024 because ef the `heapInGb <= 0` condition.

It might not be a bad thing to be more careful with small heaps, but the code doesn't suggest that this behavior is intentional.

**Comment by saernz** [comment]
Thanks for this post, it helped me solve an issue I was having. I have ran into issues due to this. It happened when trying to enable the "Threat Intel Module" alert rule on Kibana which is installed by filebeat. It kept running into errors saying:

`Bulk Indexing of signals failed: index: ".blankidy-blank-index" reason: "maxClauseCount is set to 1024" type: "too_many_clauses" name: "Threat Intel Filebeat Module (v8.x) Indicator Match`

Even though my `indices.query.bool.max_clause_count` was set to the default of 4096 it continued to give the above error.

After increasing the memory to over 2Gb the problem was solved and the rule ran.
