### ISSUE TITLE
Using runtime fields as fallback rather than shadowing mapped fields

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch#86536]
### Description

Today runtime field at query time always overwrite any mapped values. 

https://www.elastic.co/guide/en/elasticsearch/reference/current/runtime-override-values.html

Quite often you might actually want to do the reverse:

Introduce a new field to be index say `myfield` in the mapping and start ingesting documents containing `myfield` explicitly. 

We now want to query and aggregate based on `myfield` and use runtime fields to provide a fallback for `myfield`. 

This would allow us to phase in a new field and only pay for the runtime field execution on older documents that do not contain `myfield`.

**Comment by javanna** [comment]
Now, one problem I see with what I suggested above is something that we've been aware of for some time but I tend to forget: there is currently no way to access the indexed variant of the field from a script if it is shadowed, as referring to it will always load the runtime field, and in this case it would even cause an error around trying to access the same field that you're defining a script for. If the path I am suggesting makes sense, we need to work on making it possible to access a shadowed field explicitly.

**Comment by javanna** [comment]
I've been thinking about this and I have a couple of questions. A runtime field can be defined in the mappings or in the search request. At query time, search request defined runtime fields have the precedence over runtime fields or ordinary fields with the same name defined in the mappings. At the same time, runtime fields defined in the mappings have the precedence over fields defined under properties.

Runtime fields defined in the search request are transient and can only be defined globally, meaning they will be applied to all indices that the query targets and will end up shadowing any existing field with same name defined in the mappings.

Runtime fields defined in the mappings are permanent (although they can be removed), and are defined at the index level.

I made an assumption on my above comment, but maybe you can confirm this @Mpdreamz . When you opened this issue, did you have a scenario in mind where you wanted to create a transient runtime field fallback across multiple indices (presumably the most recent index has the field indexed, while it is computed as a runtime field for previous indices), or was the issue around returning the computed value for individual documents that don't have a value for a certain field, while using the indexed field when present, but within the same index?

The high-level usecase  that we had in mind for shadowing when we introduced it was correcting existing fields indexed with wrong values, which is why runtime fields currently take the precedence. I am not sure that we can simply change the precedence as that would make correcting existing fields not possible, but there are other ways that we could address the  scenario that you brought up and I am keen on discussing that with the team.

**Comment by felixbarny** [comment]
I think there are good use cases for both options - runtime fields take precedence and indexed fields take precedence.

> I am not sure that we can simply change the precedence as that would make correcting existing fields not possible

What about a parameter for runtime fields that let you define the precedence? The default would be the same behavior as today but then there's a mode where indexed fields take precedence.

**Comment by felixbarny** [comment]
The use cases I and AFAIK @Mpdreamz has in mind are to introduce new fields that the UI can rely on in a backwards compatible way.

A concrete example:

Currently, in APM, we store the duration of a transaction in the field `transaction.duration.us`. However, we'd like to transition to the official ECS field `event.duration`. We can start populating the new field in new versions of APM Server and make new versions of the APM UI/Kibana read from `event.duration`. However, there will still be a lot of historical data in the `traces-*` data stream that was ingested by older versions of the stack so that the documents only have the `transaction.duration.us` field, not `event.duration`. We were thinking of using runtime fields to add a layer of backwards compatibility: The UI would be able to always use the field `event.duration` for queries and to display the transaction duration. For new data, the indexed field `event.duration` would be used for that. For old data, we'd use a runtime field definition for `event.duration` that returns values from `transaction.duration.us`.

I suppose a workaround would be to create a runtime field for `event.duration` to existing backing indices of a data stream, then roll over the data stream after APM Server has been updated. The downside is that it would potentially create more shards due to the rollover. But if we only roll over at most once when updating the stack, and only if new fields have been introduced, it shouldn't be too frequent. @Mpdreamz do you think that would be feasible?

**Comment by javanna** [comment]
Thanks for providing more context. The need to rollover was what we initially envisioned when we were thinking of the "add a new field to a data stream" scenario. If you add the field to the index mappings, old indices can have a script that computes its value. The lack of a high-level API to easily do this remains, but Elasticsearch should already have the needed low-level primitives to get this done.

Issues arise if you 1) try to create a transient runtime field fallback from the search request, as you can't control which indices the runtime field gets applied to, 2) add a new field without rolling over as the runtime field will override the indexed field. Both of these can be solved one way or another, but I want to first clarify what it is that we want to achieve high-level.

**Comment by javanna** [comment]
I opened #89093 that would make it possible to have a runtime field expose the original value for the indexed field that it shadows, so that its script can have logic that pulls the indexed value when present or compute it otherwise. This should help introducing a new indexed field without requiring a rollover. Based on the conversation we had in this issue, I believe that that is all that's needed to achieve the desired goal to introduce a new indexed field and leverage its speed while computing values for older documents that don't have the field, hence I am closing this issue in favour of #89093 .
