### ISSUE TITLE
Instead of top_terms_N, no rewrite method exists to get first_terms_N

### ISSUE THREAD

**Issue by makam** [elastic/elasticsearch#8658]
There are multiple rewrite methods present. 
Scoring/Constant boolean will hit maxClauseLimit if terms expanded are more than 1024 (default). The only possible expansion (which i can use to extract terms) is top_terms_N. But this iterates through every term to find the "top" terms. There should be an alternative to get the first N expanded terms (irrespective of how good the match is). This way the query execution time improves when the number of possible terms are way too huge (in my case).

**Comment by clintongormley** [comment]
Two years have passed since this issue was opened and it hasn't gained traction.  I'm hoping you figured out a way to do this yourself.  If not, you may want to look at the new unified highlighter (#21621) which seems to handle wildcards etc efficiently.  Perhaps there are clues to be gained there about how to implement this.

If you still feel that this rewrite method should be provided, feel free to reopen.
