### ISSUE TITLE
Import specific users, roles, watches, ingest pipelines, etc

### ISSUE THREAD

**Issue by A-Hall** [elastic/elasticsearch#86583]
### Description

Currently there is no way to migrate security objects nor watches, pipelines, etc from one cluster to another without interacting with the system indices.  It would be nice to be able to "import" specific users, roles, watches, ingest pipelines, etc, from a snapshot, rather than just "restoring" the system indices and cluster state or if there were APIs that made it possible to migrate or import/export those object.   The specific use-case for this would be consolidating multiple clusters into one.

**Comment by original-brownbear** [comment]
We discussed this during our team sync and think this issue is too general. Adding the ability to import specific bits of data from a feature is something specific to a feature.
If you're still interested in this, we'd suggest opening issues for the specific feature (e.g. restoring a specific ingest pipeline) with the relevant team.
-> closing here for now since this is too broad for us to act on.
