### ISSUE TITLE
Modify attributes for existing API keys

### ISSUE THREAD

**Issue by bytebilly** [elastic/elasticsearch#86668]
## Problem description

[Elasticsearch API keys](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-create-api-key.html) have attribute that can be set on creation, like `name`, `role_descriptors`, `expiration`, or `metadata`.

Once created, an API keys is immutable and there is no way to modify it. The only possible workaround is to invalidate it and recreate another API key with the updated information, but in this case it's not possible to preserve the API key value.

If the API key needs to be updated frequently, for example to update its permissions or metadata, this may create problems when API keys are already in use on remote endpoints or other places where it's complex to automate key rotation.

### Example use case

Enterprise Search Solution users can use API keys to access a specific list of Engines. When a new Engine is configured, users can be granted access to it. It would be useful to "enable" their existing API key to access the new Engine, rather than creating a new one and replacing all occurrences of the old value.

## Proposed solution

Allow modifying existing API key attributes via an API call.

### Open questions

- Which attribute can be modified?
- Do we need to create a new API, or can we reuse the existing one?
- Which permissions are needed to modify an existing API key?
- Should we allow "partial" updates for fields that are explicitly specified in the payload, since it's not possible to retrieve all existing attributes?

**Comment by bytebilly** [comment]
cc @elastic/es-security @ioanatia @ruflin

**Comment by dbrimley** [comment]
My knowledge of this area is admittedly limited, but I have a few questions.

1. Are API Keys immutable by design?  Should they be editable?
2. Also should the key itself hold context?  Wouldn't it be better for the key to relate back to data held centrally?  Then this removes the problem of changing the key?

**Comment by bytebilly** [comment]
> 1. Are API Keys immutable by design?  Should they be editable?

They are by design, but just because there was no requirement to implement them differently when they were introduced. We already discussed and there was no security concern in allowing changes.

> 2. Also should the key itself hold context?  Wouldn't it be better for the key to relate back to data held centrally?  Then this removes the problem of changing the key?

I'm not sure what you mean by "data held centrally", however the AP key that is used in clients doesn't bring information (e.g. like JWT), but it's just a "credential" to access the API key related information that are stored in Elasticsearch.
The problem is that if you regenerate the key, the "client" part (id and secret) will be different.

**Comment by ywangd** [comment]
> Are API Keys immutable by design? Should they be editable?

I think we have historically used the term "immutable" to mean two slightly different things:
1. Dynamic - This is how user role works. The actual definition of a role with name `admin` is resolved for each incoming request. If the definition changes, a user with the `admin` role will automatically get the updated definition applied. We do **not** want this for API keys. Also technically we cannot have API keys to be fully dynamic because if the owner user gains or loses a role, there is no reliable way for ES to know about it. So instead, API keys snapshot owner user's privileges at creation time and stick to the snapshot.
2. Editable - This is what this issue is asking for. As long as we maintain the 1st point, I feel less stressed about relaxing on this one. An API key authentication can be serialised for things like alerts. An update to the key itself will _not_ affect these serialised authentications. Is it acceptable? 

> Wouldn't it be better for the key to relate back to data held centrally?

This is the case today. But so far we don't allow changing (editing) that "centrally held" data. 

For this ask, the most outstanding question to me is "_Who is allowed to update an API Key_"? My current thinking is only the "owner user" is allowed to update an API key (I assume `role_descriptors` is a must for editable).

API keys need to capture owner user's privileges. If we allow other users to update it, we have to either:

1. Keep reusing the same snapshot which might be outdated and makes the whole update feature pointless. Many keys are created with just a name which means they inherit all privileges of the owner at creation time. So if the owner user is not available at update time, the key's privileges just cannot be updated.
2. Snapshot the new user's privileges to replace the old snapshot. This basically changes the owner of an API key. I don't like this option since it updates more than what is really necessary for the use case. It could also have many implications in other areas, e.g. auditing. 

Therefore, my conclusion is that we should only allow "owner user" to update a key. This also has its own implicaitons:
1. It means even a `superuser` is not able to update other user's keys. Conceptually I think it is OK. There are other resources, e.g. async search result, work similarly.
2. A "granted" API key most likely won't be updatable. "Granting" API key is used when the owner user does not have the permission to manage API keys. This means even if the user is the owner of a key, it likely does not have necessary privileges to invoke that action. We could make it editable for the "Granter" if we address #69777 first. But given today's use case of granting API keys, it does not seem necessary or at least not a priority.

Conceptually, allowing only "owner user" to updating an API key is very close to creating a new API key. The new key just reuses the same ID and secret of the old key. I think this model is simplier to understand and implement.

Note:
* I intentionally leave details such as which API to use, what privileges, and how old key is preserved for auditing out for now.
* Once API key becomes updatable (editable), there will likely be more need to show its privileges. We don't have a good way to show two intersecting role descriptors. We might need to think more about it if we decide work on this issue. But it should be a separate task.
* I don't know all the details on Enterprise search's use case. It would be great if we could sync in a different channel so that my comments could be more accurate.

**Comment by ruflin** [comment]
This might also be interesting for the fleet-server case as we initiate new api keys each time a policy with changed permissions is rolled out. One of the challenges for us in the case that permissions are reduced, some events might be still in flight. @ph @scunningham This could help with scaling?

**Comment by scunningham** [comment]
> This could help with scaling?

Perhaps; if updating the key is less expensive from a processing standpoint than creating a new key.  Most of Fleet scale issues around api keys are due to large number of agents having to do validations.  The regeneration of the keys, while expensive, does not happen as often.

**Comment by tvernum** [comment]
> It means even a superuser is not able to update other user's keys.

A `superuser` can _run-as_ any user, so as long as the "Modify API key" endpoint works correctly with run-as, we're probably OK.

The other question is what this would mean for `grant`-ed API keys. Who edits them - the key's user or the granting user?

**Comment by n1v0lg** [comment]
One other thing to consider once we are further along is whether to involve Kibana for a UI update to the API keys management page. Not necessary for the initial release of this since target is internal use but could be a nice to have for customers in the future.
