### ISSUE TITLE
Upgrading to 8.2.0 requires extra memory

### ISSUE THREAD

**Issue by raihankhan** [elastic/elasticsearch#87192]
### Elasticsearch Version

8.2.0

### Java Version

_bundled_

### OS Version

Linux 5.10.0-14-cloud-amd64 #1 SMP Debian 5.10.113-1 x86_64 GNU/Linux

### Problem Description

I was trying to upgrade my elasticsearch cluster deployed in LKE from version 7.17.3 to version 8.2.0.  Kubernetes client version is: v1.22.4 and server version is: v1.23.6. I have deployed elasticsearch with 1.5Gib of memory requests in `spec.podTemplate. spec.resources` field of my deployment. I have witnessed some strange scenarios while upgrading.

- After upgrading, the memory usage of elasticsearch containers immediately jumps from 1-1.3 Gi to 2-2.5 Gi. After a little while, the memory usage starts reducing and becomes stable at 1-1.3 Gi again. Here are the Grafana real-time stats of the scenario:

![Screenshot from 2022-05-27 16-47-08](https://user-images.githubusercontent.com/25270629/170685355-dca05227-1fca-4074-855b-87e601849eb1.png)

- If I deploy elasticsearch version 7.17.3 or 8.2.0, they work fine if I set the memory limit and memory request to 1 Gi. But, the problem arises while upgrading. Suppose, I have a pod running elasticsearch 7.17.3 with a memory request of 1Gi and a memory limit of 1Gi in `podTemplate.spec.resources` field of my deployment. If I try to upgrade now to 8.2.0, the pod gets OOMKILLED and falls into `crushloopbackoff`. I have tried setting the memory request and limit to 1.2, 1.3, 1.4, and 1.5 Gi before upgrading. I found that I can successfully upgrade without any issue if I set it to at least 1.4 Gi. So, the question is - why do I need to set extra memory requests in my podTemplate if I want to upgrade to version 8.2.0? 

### Steps to Reproduce

.

**Comment by mark-vieira** [comment]
Perhaps someone in @elastic/es-distributed can provide some insight here. Intuition tells me that there would be some background migrations that happen after an upgrade that use additional memory beyond normal operating requirements but I'd like some else to confirm that suspicion.

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, because a properly configured Elasticsearch installation should never experience the OOM killer. We'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
