### ISSUE TITLE
Build source in Apple M1 fails if not using MacOs Monterey

### ISSUE THREAD

**Issue by jcbages** [elastic/elasticsearch#87426]
### Elasticsearch Version

8.4

### Java Version

_bundled_

### OS Version

Darwin kpl3x4j763.kalpatarugroup.com 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64

### Problem Description

# Description
When running `./gradlew` in my Mac M1 with Big Sur I get an error from `sysctl` mentioning that `hw.perflevel0.physicalcpu` is an unknown property. When listing all properties using `sysctl -A` there's no `hw.perflevel*.*` properties at all.

Looking into this forum https://githubhot.com/repo/seanmonstar/num_cpus/issues/104 it seems the property is not displayed on versions before Monterey. I went ahead and changed this https://github.com/elastic/elasticsearch/blob/master/build-conventions/src/main/java/org/elasticsearch/gradle/internal/conventions/info/ParallelDetector.java#L67-L69 to always use the `"hw.physicalcpu"` property and was able to get a clean build.

I think we should either specify somewhere that MacOS Monterey is required for building Elasticsearch in M1 macs or change the code in `ParallelDetector.java` such that it uses `"hw.physicalcpu"` for versions older than Monterey. I personally prefer the second option and I'll be happy to take the PR for fixing it if you all agree.

### Steps to Reproduce

N/A

**Comment by mark-vieira** [comment]
Thanks for the report @jcbages! I would have expected the existance of those properties to be based on architecture and not OS version as Big Sur supports Apple Silicon but hey, it's Apple. For context, the intent here is to limit test parallellism to the number of _performance_ cores available since you get much lower performance from the efficiency cores. I'm good with falling back to the generic `hw.physicalcpu` property for Big Sur. We'd happily accept a PR for this since I don't have a Big Sur machine using Apple Silicon locally available to me to test this on.

**Comment by jcbages** [comment]
Hi @mark-vieira, thanks for your reply! I just created the PR if you want to take a look here https://github.com/elastic/elasticsearch/pull/87430.

Let me know if there's anything I should change or do differently, thanks!
