### ISSUE TITLE
indices.query.bool.max_clause_count behavior in 8.1+ 

### ISSUE THREAD

**Issue by vkras** [elastic/elasticsearch#88281]
### Description

It seems that indices.query.bool.max_clause_count setting is deprecated with 8.1 in favor of dynamic settings based on RAM/CPU (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-settings.html is not updated yet). It creates issues with protecting servers from non intelligent searches (abuse). For example, a wildcard search (*) takes 7+ minutes vs. just few seconds for a "normal" search. I checked profile for the query and the effective number of Boolean statement was 20k (number of different words the * was expanded to). The server becomes very slow when processing other requests at the same time.
It would be nice if the "dynamic" behavior was configurable, so we can set indices.query.bool.max_clause_count to something reasonable like 10000 and make queries that exceed it to be rejected right away (the way 7.x used to do it). If somebody wants to open servers to process anything they can set it to "dynamic".

**Comment by romseygeek** [comment]
Hi, thanks for opening this issue! The max boolean clause limit is a bit of a blunt instrument for dealing with abusive queries.  In particular, it's a static per-JVM setting in lucene which means that it is set per-node in elasticsearch, which doesn't fit very well with our operating model.  There are various other options you can use here:
* using a client-side query timeout will interrupt a search if it takes longer than the timeout, meaning that you don't waste resources on long-running queries.
* doing some client-side query validation to intercept obviously abusing queries such as '*'
* setting `search.allow_expensive_queries` to `false` will disable all wildcard queries - again something of a blunt instrument, but it is at least a per-index rather than a per-node setting

**Comment by javanna** [comment]
With this said, we discussed with the team decided not to make changes to the current max_clause_count behaviour. Thanks again for reporting this, it was a good discussion to have regardless of the outcome.
