### ISSUE TITLE
[CI] MlDistributedFailureIT testClusterWithTwoMlNodes_StopsDatafeed_GivenJobFailsOnReassign failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#88337]
There have been two instances of this today (both in PR builds) that blew up due to an OOME.

**Build scan:**
https://gradle-enterprise.elastic.co/s/ryfsljqpbyjlm/tests/:x-pack:plugin:ml:internalClusterTest/org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT/testClusterWithTwoMlNodes_StopsDatafeed_GivenJobFailsOnReassign

**Reproduction line:**
`./gradlew ':x-pack:plugin:ml:internalClusterTest' --tests "org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.testClusterWithTwoMlNodes_StopsDatafeed_GivenJobFailsOnReassign" -Dtests.seed=A3E13461A939BDF6 -Dtests.locale=ar-IQ -Dtests.timezone=America/Porto_Velho -Druntime.java=17`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT&tests.test=testClusterWithTwoMlNodes_StopsDatafeed_GivenJobFailsOnReassign

**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([A3E13461A939BDF6]:0)

```

**Comment by grcevski** [comment]
Oh that's unexpected. I guess I have a bug there, it should be only one object at the moment. It appears that the ILM plugin would reload many times and we add that immutable state handler many many times. I'll take this over to fix.

**Comment by davidkyle** [comment]
Different test in the same suite and failure is a `ResourceNotFoundException` but looking at the logs the JVM is spending nearly all the time garbage collecting so I'm guessing the root cause is the same.

ttps://gradle-enterprise.elastic.co/s/i4badycr5nt5k/tests/:x-pack:plugin:ml:internalClusterTest/org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT/testClusterWithTwoMlNodes_StopsDatafeed_GivenJobFailsOnReassign?anchor=eyJvdXRwdXRMaW5lIjoiMC0yOTgifQ&focused-execution=1&top-execution=1
