### ISSUE TITLE
mGet doesn't honour filter condition

### ISSUE THREAD

**Issue by achakhaiyar** [elastic/elasticsearch#88425]
### Elasticsearch Version

8.2.2

### Java Version

_bundled_

### OS Version

Elastic Cloud

### Problem Description

Hi ,

I am trying to use _mget to retrieve documents from an alias that has been created by applying  filters against an index. In this case, _mget fetches documents that reside outside of this alias, meaning, search is happening within entire index.
For an example, if I have one index that contains all recipes created in English language for countries UK and US. Two aliases have created by applying filter based on one each for UK and US so that all recipes related to UK and US should be isolated from each other and contained within separate alias. However, when a recipe (document) belonging to UK is searched against the alias that has filter only to US recipes, match becomes successful instead of flagging no match. So this gives the impression that _mget doesn’t honour filter condition and searches a document against the index that is associated with alias. Please let me know if this behaviour of _mget is as expected or if it’s a bug. If it’s bug then where is log it.
Index name : recipe_en
Alias for UK : recipe_en_uk
Alias for US : recipes_en_us;

Below is the snippet of UK alias
"aliases" : {
"recipe_en_uk" : {
"filter" : {
"bool" : {
"must" : [
{
"term" : {
"countries" : "UK" } } ] } } }
}
Recipe document Id:
For UK : 1001UKRecipe
For US : 1001USRecipe

When both UK and US recipes are searched against UK alias using mget, US recipe (1001USRecipe) is also retrieved along with UK recipe
GET / recipe_en_uk /_mget
{
"ids" : [ "1001UKRecipe ","1001USRecipe " ]
}

Please revert to me if it’s a bug against _mget or if it’s expected behaviour.

Best regards

Ashutosh

### Steps to Reproduce

Please use mget to search for a document id that is outside of alias having filter condition against associated index.

**Comment by n1v0lg** [comment]
@achakhaiyar thanks for reporting this, and for the thorough description! 

We have an open issue tracking this ([#3861](https://github.com/elastic/elasticsearch/issues/3861)). I'll mention your issue there for reference, and close it as duplicate. 

Also wanted to mention our [forums](https://discuss.elastic.co/) -- these are super useful for questions like this. If you run into other issues, definitely worth posting there first since we have a very knowledgeable and active community that'll be able to help.
