### ISSUE TITLE
Unnecessary rebalancing

### ISSUE THREAD

**Issue by bobrik** [elastic/elasticsearch#8851]
```
# curl -s 'http://web605:9200/_cat/recovery?v' | fgrep -v done
index                         shard time   type       stage source_host target_host repository snapshot files files_percent bytes       bytes_percent
statistics-20140411           1     2928   relocation index web606      web607      n/a        n/a      24    75.0%         1062084500  15.3%
statistics-20131102           1     3520   relocation index web607      web606      n/a        n/a      23    65.2%         1659082665  14.1%
```

```
web605 ~ # curl -s 'http://web605:9200/_cat/recovery?v' | fgrep -v done
index                         shard time   type       stage source_host target_host repository snapshot files files_percent bytes       bytes_percent
statistics-20140121           0     37722  relocation index web607      web606      n/a        n/a      25    96.0%         1550947887  87.2%
statistics-20140311           0     19029  relocation index web606      web607      n/a        n/a      27    81.5%         919161526   76.2%
```

This doesn't make any sense. Each node has ~1.56/3.57TB of data, why move shards between equal nodes back and forth?

> Previously, the allocation decider only took into account the size of shards currently on the node when deciding whether to move a shard to another node or not. Now, it also takes into account shards that are in the process of being moved away. This reduces the amount of shard movement to the minimum required. (#8569).

http://www.elasticsearch.org/blog/elasticsearch-1-4-1-released/

I'm on 1.4.1 and it's happening. Probably started after removal of a couple of indices.

cc @s1monw

**Comment by rtkmhart** [comment]
I've been seeing very similar behaviour in 1.4.1, where shard0 of an index is moving from node1 to node2 and shard1 is moving from node2 to node1. In my case we noticed because are shards are too big for sane movement, but that this happens at all is a bit bizarre. We're in the process of upgrading to 1.5.1 but if we see this again I'll bump this issue and open a support case.

**Comment by lokeshhctm** [comment]
I see the same issue while keep indexes for last 30 day and delete previous days of indexes.
Whenever we delete indexes, rebalance starts and it takes a lot of time.
Can we stop rebalancing while we delete indexes?

**Comment by clintongormley** [comment]
So many allocation improvements have been made since 1.4 (eg https://github.com/elastic/elasticsearch/pull/14678, https://github.com/elastic/elasticsearch/pull/14652, https://github.com/elastic/elasticsearch/pull/14259, https://github.com/elastic/elasticsearch/pull/13512, https://github.com/elastic/elasticsearch/pull/12947, https://github.com/elastic/elasticsearch/pull/12551) that I'm going to close this one.  Please reopen if you're seeing the same problems on 2.1.0 or above.
