### ISSUE TITLE
Provide an access function to map _id to shard number.

### ISSUE THREAD

**Issue by linker-c** [elastic/elasticsearch#88661]
### Description

Please provide an API to translate document ID (_id) to the corresponding shard location.
This is very useful when I am reading a document directly instead of searching.  The "getResponse" should be able to provide a function like GetShard(int _id) that returns the shard this document resides.

There are some application side optimizations we are thinking about doing only if we know the shard of every document read.
As of today, I can't find an easy way to make this association.

**Comment by linker-c** [comment]
https://discuss.elastic.co/t/is-there-an-easy-way-to-get-the-shard-of-a-document/310191
FYI...

**Comment by DaveCTurner** [comment]
We (the @elastic/es-distributed team) discussed this idea today. We wouldn't want to add an API which exposes this calcluation, because to do so would be to commit to having this notion of an `_id` which maps to a shard number that we may want to relax in future versions (see e.g. https://github.com/elastic/elasticsearch/issues/48699). We also feel it doesn't make sense to do this calculation via a remote call to an API on Elasticsearch. Instead, since it's just for an optimization, you can just do the calculation within your client. I'm linking to a [discuss forum thread](https://discuss.elastic.co/t/what-is-the-index-number-of-routing-shards-setting-how-can-i-calculate-it-based-on-the-number-of-shards/297540) from another user that was trying to do the same sort of thing, where we went into some depth about how the calculation is done today.

Since there's no action to take on the Elasticsearch side here, I'm closing this.

**Comment by linker-c** [comment]
Thanks for the feedback.
But can it at least be an option for direct access to a document?  You won't be exposing the algorithm.  You are simply displaying which shard a document is stored.

**Comment by DaveCTurner** [comment]
I'll probably not reply to this issue again now it's closed. If you need further help, the community discussion forum is the best place to ask. Hopefully someone there will be able to help.
