### ISSUE TITLE
Remove the ability to delete mappings

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#8877]
Currently, a user can delete a `type` entirely, which deletes the type, all documents of that type, and removes the associated fields.  Unfortunately, if any documents of that type have already been indexed, then the fields are part of the index.  Adding fields with the same name but a different data type will cause conflicts later on. (See https://github.com/elasticsearch/elasticsearch/issues/8530#issuecomment-64393335)

We should remove the ability to delete types/mappings.

Relates to #8870

**Comment by jasisz** [comment]
Just digged to that PR from the annoucment about removing delete by query and delete mapping in Elasticsearch 2.0. As far as I understand the problem is that the field name is stored directly in index and it is not possible to use it later with different type settings.

So how it will behave if in one index I have two types with mappings that have different types for the field named e.g. `height` in both? It would also give the same errors?

**Comment by clintongormley** [comment]
@jasisz in 2.0 we explicitly forbid creating fields of the same name with conflicting mappings, for the same reason
