### ISSUE TITLE
Count API doesn't obey terminate_after parameter 

### ISSUE THREAD

**Issue by shahzad31** [elastic/elasticsearch#89035]
### Elasticsearch Version

8.4.0

### Java Version

_bundled_

### OS Version

Mac

### Problem Description

Count API on the index doesn't obey the terminate_after parameter , it returns doc_count more then what's specified 

`GET /heartbeat-8*%2Cheartbeat-7*%2Csynthetics-*/_count?terminate_after=1`

result 

```
{
  "terminated_early": true,
  "count": 2000,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  }
}
```

expected

```
{
  "terminated_early": true,
  "count": 1,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  }
}
```

This started failing recently in kibana API tests in CI https://github.com/elastic/kibana/issues/136412. Triggered by some es change. It seems like it doesn' work on older data on a fresh index it works as expected 

### Steps to Reproduce

Described above

**Comment by ywelsch** [comment]
I think this change is in line with how the feature is documented (see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-your-data.html), and is related to a recent Lucene change, see https://github.com/apache/lucene/pull/964.

I see nowhere indicated in the docs that `count` can't be larger (or more accurate) than `terminate_after`? I'm inclined to close this as won't fix rather than reinstating undocumented behavior. @jpountz WDYT?

**Comment by javanna** [comment]
This is due to a [change](https://issues.apache.org/jira/browse/LUCENE-10620) in lucene that makes it possible to quickly retrieve the total hit count from each segment stats instead of counting docs in them, when applicable.

There were already cases in lucene where asserting on the returned doc count is not a guarantee, for instance in case concurrent searches are used, and this is an additional case. The fact that terminate_after is set to `1` does not necessarily mean that the doc count will be exactly `1` in the response.
