### ISSUE TITLE
What is the right way for `_sql` to handle a combination of `min` and `max` on the same field?

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#89067]
### Description

@astefan pointed out to me that our SQL support uses a `stats` aggregation when both the `min` and the `max` value are requested on the same field. E.g. `SELECT MIN(field), MAX(field) FROM my_index` creates a `stats` aggregation on `field` under the hood.

The stats aggregation misses some optimizations that the `min` and `max` aggregations have, e.g. it cannot get these values from the points index without iterating over all matches, because it also needs to compute the `sum` and `count`, which requires visiting all matching documents. But switching to a `min` and `max` aggregation may trigger a performance degradation in the case when optimizations are not applicable, since it requires decoding field values twice.

What is the right way for `_sql` to handle this case?

**Comment by astefan** [comment]
@jpountz thank you for raising this issue.
To make the picture complete, ES SQL "promotes" at least two aggregations to `stats` or `extended_stats` depending on which ones are used. For example, `min(languages), stddev_pop(languages), max(languages), avg(languages)` uses `extended_stats` (because it needs the standard deviation). `min(languages), max(languages), avg(languages)` will get promoted to `stats` because this aggregation is enough for the min, max and avg values.

**Comment by nik9000** [comment]
This does feel like something we might should manage in aggs to be honest. but I don't know when we'd get to it.

**Comment by jpountz** [comment]
To make sure I parsed your recommendation correctly: `_sql` shouldn't try to be too smart, tell Elasticsearch that it needs `min` and `max` aggregations, and if we want to better optimize the case when both are requested on the same field, then it should happen in the aggregation framework?

**Comment by nik9000** [comment]
Yeah. I think it should. But it sure doesn't right now.

**Comment by nik9000** [comment]
Given the ESQL is coming, I don't think this is worth worrying about. At some point we'd want to point SQL to ESQL or the compute engine. And in that case it'd just write `STATS MAX(a), MIN(a) BY foo` and ESQL will already take care of the "load once" optimizations.
