### ISSUE TITLE
Default APM tracing configuration wastes CPU on exception throwing

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#89107]
Since the APM tracing was merged I see lots of exception/error throwing in profiles for nodes that have no configuration for APM set up.
I think something needs to be fixed here to make the APM calls noops without configuration or so.

![image](https://user-images.githubusercontent.com/6490959/182830081-44b40d42-9b75-4436-958d-b67578fe27e3.png)

**Comment by ChrisHegarty** [comment]
The underlying root cause of this issue has been fixed [upstream](https://github.com/open-telemetry/opentelemetry-java/pull/4663) (in Otel), and we have a good [workaround](https://github.com/elastic/elasticsearch/pull/89135) in ES code.

If there is nothing remaining, then this issue can be closed. 

Caveat, we can likely remove the workaround in ES once the upstream fix gets into a release which ES can leverage. This can be tracked as a separate ES issue.

**Comment by original-brownbear** [comment]
Alright then, closing here for now.
