### ISSUE TITLE
Indices stats: Add counter for failed indexing requests

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#8938]
Currently, the indexing.index_total shows the count of documents that are successfully indexed.  In other words, if a document reaches a shard and fails indexing (eg. due to concurrency control, other conditions), it is not counted towards the total.  It will be nice to add a metric to provide a count of failed indexing requests for admins (for those requests that actually reached the shard, eg. not blocked by the cluster state).

```
      "primaries" : {
        "indexing" : {
          "index_total" : 32283250,
          "index_time" : "2d",
          "index_time_in_millis" : 180763935,
          "delete_total" : 0,
```

**Comment by markharwood** [comment]
This looks like it should be easy to add into the existing ShardIndexingService here:

    public void postIndex(Engine.Index index, Throwable ex) {
        totalStats.indexCurrent.dec();
        typeStats(index.type()).indexCurrent.dec();
    }

We would just need to increment a new counter which is for indexing failures

**Comment by andrestc** [comment]
I will take a shot at this one.

**Comment by andrestc** [comment]
@markharwood, @clintongormley I think i got this one almost finished but I'm having a hard time figuring out how to write a test for this and also how to manually test. Any tips on how to generate a failure that should increment the counter?

I found some related tests on [IndexStatsIT](https://github.com/elastic/elasticsearch/blob/71a3bdb8e8c89b8a17f6828ac4dcba73a99d6637/core/src/test/java/org/elasticsearch/indices/stats/IndexStatsIT.java#L383), which im going to change and add some assertions, but I wasn't able to find any related to exceptions occurring during the indexing, probably because I'm not familiar with the codebase.

Any help is really appreciated.

**Comment by clintongormley** [comment]
@andrestc try indexing a document with eg a string where an integer should be, or using ?version= which should result in a conflict exception
