### ISSUE TITLE
Updating logged in user profile without granting manage_security privilege

### ISSUE THREAD

**Issue by AzharUddinSheikh** [elastic/elasticsearch#89508]
### Description

I was trying to update the logged-in `user` profile using **Flask** `API` but getting failed it throws an error
`unauthorized user` because this user needs **cluster privilege** `manage_security `

But once I provide this `privilege` which is `manage_security` to a logged-in `user` not only does he/she can update her profile but can also update others' profiles too.

which makes no sense right?
I believe there should be an `endpoint` so that the logged-in `user` can update fields like `full name` and `email` only (should not be able to update `roles` )

I have gone through each `method` of [SecurityClient](https://elasticsearch-py.readthedocs.io/en/v8.3.3/api.html#security) 
but I have found no such way, also been confirmed [on elastic discussion](https://discuss.elastic.co/t/how-to-update-user-profile-using-api-without-manage-security-privilege/312545)

**Comment by ywangd** [comment]
Thanks very much for your interest in Elasticsearch.

Existing APIs of the user profile feature are _not_ meant to be called by end-users directly. This is by design. They are intended to be called by a service user (e.g. `kibana_system`) on behalf of the end-user. When an end-user updates any part of the profile in Kibana, the actual action is proxied by the `kibana_system` user. The end-user is not required to have any privilege for it. As such, letting end-users directly manipulate their profiles is against the design and not recommended. 

Also, you only need `manage_user_profile` to call user profile APIs. `manage_security` is way to powerful for this purpose. In fact, `kibana_system` user does _not_ have `manage_security` privilege.

As explaine above, I hope you don't mind that I close this.
