### ISSUE TITLE
Replace hand parsing of requests/queries/mappings/etc with a grammar

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#8965]
Requests/queries/etc currently have custom parsers, which make it more difficult to be certain that they are error free.  We should replace all this hand parsing with some form of grammar, which defines exactly what syntax is allowed. This will also benefit those implementing clients, as they will have a grammar that can be interrogated programmatically.

Any unknown parameters should throw a parsing exception.

We can add custom rules where needed (eg to disallow certain combinations of parameters like using `fuzzy` in the `multi_match` query with type `cross_fields`).

**Comment by clintongormley** [comment]
I've had a go at spec'ing out the `match` query using JSON-schema.  The result is not 100% accurate, but not bad:

```javascript
    {
      "id": "http://schema.elasticsearch.org/query",
      "title": "Schema for all queries",
      "type": "object",
      "default": {
        "match_all": {}
      },
      "max_properties": 1,
      "properties": {

        // list all query names here, plus their { "field": "query"} vs 
        // the more advanced { "field": { "query":..}} forms
        "match": {
          "type": "object",
          "min_properties": 1,
          "max_properties": 2,
          "properties": {
            "_name": {
              "$ref": "#/definitions/params/query_name"
            }
          },
          "pattern_properties": {
            "^\\S+$": {
              "one_of": [
                {
                  "$ref": "#/definitions/params/query"
                },
                {
                  "$ref": "#/definitions/queries/match_query"
                }
              ]
            }
          }
        }
      },

      "definitions": {
        "queries": {

          // Advanced form of match query defined here
          "match_query": {
            "one_of": [
              {
                "type": "object",
                "required": [
                  "query"
                ],
                "properties": {
                  "query": {
                    "$ref": "#/definitions/params/query"
                  },
                  "type": {
                    "enum": [
                      "boolean"
                    ]
                  },
                  "operator": {
                    "$ref": "#/definitions/params/operator"
                  },
                  "minimum_should_match": {
                    "$ref": "#/definitions/params/minimum_should_match"
                  },
                  "analyzer": {
                    "$ref": "#/definitions/params/analyzer"
                  },
                  "boost": {
                    "type": "number"
                  },
                  "cutoff_frequency": {
                    "$ref": "#/definitions/params/int_or_float"
                  },
                  "fuzziness": {
                    "$ref": "#/definitions/params/fuzziness"
                  },
                  "fuzzy_rewrite": {
                    "$ref": "#/definitions/params/rewrite"
                  },
                  "lenient": {
                    "$ref": "#/definitions/params/bool"
                  },
                  "max_expansions": {
                    "$ref": "#/definitions/params/max_expansions"
                  },
                  "prefix_length": {
                    "$ref": "#/definitions/params/postive_int"
                  },
                  "zero_terms_query": {
                    "$ref": "#/definitions/params/zero_terms"
                  }
                }
              },
              {
                "type": "object",
                "required": [
                  "query"
                ],
                "properties": {
                  "query": {
                    "$ref": "#/definitions/params/query"
                  },
                  "type": {
                    "enum": [
                      "phrase",
                      "phrase_prefix"
                    ]
                  },
                  "analyzer": {
                    "$ref": "#/definitions/params/analyzer"
                  },
                  "boost": {
                    "type": "number"
                  },
                  "fuzziness": {
                    "$ref": "#/definitions/params/fuzziness"
                  },
                  "fuzzy_rewrite": {
                    "$ref": "#/definitions/params/rewrite"
                  },
                  "lenient": {
                    "$ref": "#/definitions/params/bool"
                  },
                  "max_expansions": {
                    "$ref": "#/definitions/params/max_expansions"
                  },
                  "prefix_length": {
                    "$ref": "#/definitions/params/postive_int"
                  },
                  "slop": {
                    "$ref": "#/definitions/params/postive_int"
                  },
                  "zero_terms_query": {
                    "$ref": "#/definitions/params/zero_terms"
                  }
                }
              }
            ]
          }
        }
      },

      // Each query param defined here (and reused by all other queries)
      "params": {
        "analyzer": {
          "type": "string",
          "pattern": "^\\S+$"
        },
        "bool": {
          "any_of": [
            {
              "type": "boolean"
            },
            {
              "enum": [
                "true",
                "false",
                "TRUE",
                "FALSE",
                "0",
                "1",
                ""
              ]
            },
            {
              "type": "integer",
              "minimum": 0,
              "maximum": 1
            },
            {
              "type": "null"
            }
          ]
        },
        "fuzziness": {
          "any_of": [
            {
              "type": "string",
              "pattern": "^(0|1|2|AUTO|1.0|0.\\d+)$"
            },
            {
              "type": "integer",
              "minimum": 0,
              "maximum": 2
            },
            {
              "type": "numeric",
              "minimum": 0,
              "maximum": 1
            }
          ]
        },
        "int_or_float": {
          "any_of": [
            {
              "type": "string",
              "pattern": "^\\d+(\\.\\d+)?$"
            },
            {
              "type": "number",
              "minimum": 0
            }
          ]
        },
        "max_expansions": {
          "default": 50,
          "any_of": [
            {
              "type": "string",
              "pattern": "^(\\d+)$"
            },
            {
              "type": "integer",
              "minimum": 0
            }
          ]
        },
        "minimum_should_match": {
          "any_of": [
            {
              "type": "string",
              "pattern": "^((100|\\d\\d)%|\\d+)$"
            },
            {
              "type": "integer",
              "minimum": 1
            }
          ]
        },
        "operator": {
          "enum": [
            "or",
            "and",
            "OR",
            "AND"
          ]
        },
        "positive_int": {
          "default": 0,
          "any_of": [
            {
              "type": "string",
              "pattern": "^(\\d+)$"
            },
            {
              "type": "integer",
              "minimum": 0
            }
          ]
        },
        "query": {
          "type": "string",
          "pattern": "\\S"
        },
        "query_name": {
          "type": "string",
          "pattern": "^\\S+$"
        },
        "rewrite": {
          "any_of": [
            {
              "enum": [
                "constant_score_auto",
                "constant_score_boolean",
                "constant_score_filter",
                "scoring_boolean"
              ]
            },
            {
              "type": "string",
              "pattern": "^top_terms_(boost_)?\\d+"
            }
          ]
        },
        "zero_terms_query": {
          "enum": [
            "none",
            "all"
          ]
        }
      }
    }
```

Issues:
---------
* The `match` query accepts a single field name (defined as a pattern) and an optional key called `_name`.  It is not possible to enforce this in JSON schema (currently)
* It'd be nice to say "you can't set `max_expansions` unless you're using `fuzziness` - can't do that either
* While we can express that eg `minimum_should_match` only applies when `type` == `boolean`, I can see that it'd be difficult to throw an error message explaining that the reason `minimum_should_match` is being rejected is because of the `type` setting.
* We'd like to be able to mark certain parameters as accepted-but-deprecated, which currently isn't possible.
* It'd be nice to extend a definition overriding just (eg) the `default` value, rather than repeating the whole defn.

Ideas:
--------
* Perhaps a `dependencies` keyword which allows us to specify certain post-validation rules (like `type: phrase` doesn't accept `minimum_should_match`, or `max_expansions` only makes sense if you use `fuzziness`).  This could be extended to include nice error messages.
* Add a `deprecated` flag, with an error message, eg "Deprecated in favour of Foo"
* While eg the `fuzziness` parsing could be implemented in generic JSON-schema style, we could also provide an optimized Java-friendly parser for some or all parameters

**Comment by tikitu** [comment]
I've a wee bit of experience with JSON-schema in python: you may indeed find that it's difficult to get quality error reporting, especially as you get into complex constraints. (You can express a lot with combinations of anyOf and allOf, but once you use anyOf the failure reports aren't much good.) I don't know if the same holds for implementations in other languages, but I would expect it. (The problem is quite general with `anyOf`: the grammar gives you no way to say "once we've seen this structure, commit to this alternative: if we fail deeper in the structure, report that *this alternative* failed." Instead, it has to backtrack and can only report that none of the alternatives succeeded.)

**Comment by tikitu** [comment]
I did some thinking a while back about approaching this from the opposite end. If you annotated the fields on an XXX(Query/Filter)Builder you could generate a good portion of the code of the corresponding Parser, and similar annotation processors could spit out e.g. Haskell code, or a JSON-schema spec, or whatever was needed for a different client or use case. (I was thinking of the Sense autocomplete database; obviously docs work from here too.) You can even mix in custom code, if the annotation processor is a bit smart. In that approach you aim for say 80% coverage in the annotations, and catch the more complex validation requirements in custom code. But because the annotations are java code, if you've got repeating patterns you're free to extract and name them, no matter how complex they are.

**Comment by clintongormley** [comment]
@tikitu yeah - your comment about error reporting is the thing that makes me most nervous.  Also i was thinking that we don't just want to validate the input JSON, we actually want to extract the values and add them to a settings object for the query/filter/endpoint etc.

I think JSON schema as it is today is not sufficient, but it probably gives us the starting point for our own custom grammar.

**Comment by tikitu** [comment]
I'm not convinced that what you want is a grammar. I think maybe what you want is something *from which you can auto-derive* a grammar, but which also makes it easier to auto-derive other things. Seems likely to me that if you have a grammar you won't use it directly in java code, but rather use it to (mostly-semi-)generate code that gets checked in (and maybe tweaked, for performance or for whatever validation the grammar can't express). Same sort of story for client libraries: if I'm writing a library for a strongly typed language I want intermediate-structure type-safety which the JSON spec won't give me, so I'll use the spec to generate code but add my own type information rather than feeding the spec directly into a json-parsing library.

**Comment by lukas-vlcek** [comment]
@tikitu +1

**Comment by hydrogen18** [comment]
I took a look at this recently. The parsers are neatly organized into separate parsers. For the 'query phase' there is a parser for each possible type of query (match, fuzzy, regexp, etc.) that identifies itself and exposes its parsing logic through a simple interface.

The problem is that between the dependency injection and the massive context objects that are passed around it is a very difficult to work on the parsers in isolation. I tried, but could not manage to construct an environment that would allow me to just throw a query at a collection of parsers and see if it accepted it as valid or invalid. 

This is caused by the fact the query parsers combine both the syntactic and semantic validation into the same code. For example, I'm looking at a head of bf5a2c779c12e5ef5c52d1da5b. If we look at `org.elasticsearch.index.query.QueryMatchParser` lines 98-103

```
     98                     } else if ("analyzer".equals(currentFieldName)) {
     99                         String analyzer = parser.text();
    100                         if (parseContext.analysisService().analyzer(analyzer) == null) {
    101                             throw new QueryParsingException(parseContext.index(), "[match] analyzer [" + parser.text() + "] not found");
    102                         }
    103                         matchQuery.setAnalyzer(analyzer);
```

The `parseContext` object is an instance of `QueryParseContext`. In this example snippet the parser identifies that a specific analyzer is being requested by name for use with this match query. It then goes and validates that the analyzer actually exists.  This sort of validation absolutely must happen, but by combining it with the parsing logic it results in the heavyweight context objects that must be passed around. Instead, we could consider the problem as two separate questions 

1. Is this query possibly a valid match query?
1. Is this query a valid match query against the given indice(s) and field(s)?

Logically, you'd wind up with two tightly coupled classes. We'll call them a `QueryMatchParser` and a `QueryMatchValidator`. The parser would answer the first question, the validator the second. There would be some sort of data structure that the parser would emit that the validator would consume. It looks like this is pretty much already there in the form of the `MatchQuery` object. However, constructing separate classes for each of these is probably overcomplicating the problem. Realistically it looks like you just need associate a static method for parsing and perhaps an instance method on the generated object for validation.

As @tikitu indicated while a grammar is a desirable artifact, it may not be the most flexible starting point. If there was a way to annotate the `MatchQuery` object to associate the parsing and validation code with  the various setters of the object it'd probably be easier to develop and read. It seems that parsing a query in ElasticSearch is basically the task of consuming from an `XContentParser` to produce domain specific objects. For queries, validation is basically checking that the query makes sense in the environment it is to be executed against. My guess is you'd wind up with a `MatchQuery` class that had a bunch of nested objects to model the individual components of a match query.

**Comment by clintongormley** [comment]
@hydrogen18 worthwhile comments. You may be interested in this prototype which, i think, addresses some of your concerns? https://github.com/elasticsearch/elasticsearch/pull/9901

**Comment by hydrogen18** [comment]
@clintongormley Thanks for the heads up. It looks promising.

**Comment by bitemyapp** [comment]
Coming from - https://github.com/elastic/elasticsearch/issues/11500#issue-85240264

Want to highlight:
https://github.com/bitemyapp/bloodhound/blob/master/src/Database/Bloodhound/Types.hs#L536-L544

https://github.com/bitemyapp/bloodhound/blob/master/src/Database/Bloodhound/Types.hs#L601-L629

https://github.com/bitemyapp/bloodhound/blob/master/src/Database/Bloodhound/Types.hs#L823-L832

https://github.com/bitemyapp/bloodhound/blob/master/src/Database/Bloodhound/Types.hs#L1729-L1742

I think there's valuable in separating a datatype that accurately describes the component of the API from its JSON representation. To that end, just as I use [typeclasses to generate the JSON needed for each type](https://github.com/bitemyapp/bloodhound/blob/master/src/Database/Bloodhound/Types.hs#L1729-L1742) one could make a similar thing for the JSON schema. Hell, one could generate a random sampling of 100 examples using [QuickCheck](http://hackage.haskell.org/package/QuickCheck) and then use a function to reconcile those into a JSON schema. Unit tests could act as explicit examples of, "this is what this should look like as JSON".

JSON examples and datatypes are both a lot more readable than JSON Schema.

It's worth considering that the [client library](https://github.com/bitemyapp/bloodhound) I am linking can be *validated* with [the spec tests](https://github.com/bitemyapp/bloodhound/blob/master/tests/tests.hs) to know that the spec is correct. I am not saying Bloodhound is ideal for, nor it is designed for, use as a spec of Elasticsearch but I would submit that there are far less manual and more readable ways to describe an API than JSON Schema.

**Comment by Mpdreamz** [comment]
[NEST](http://nest.azurewebsites.net/), the official high level C# client for elasticsearch, has types for all API [requests](https://github.com/elastic/elasticsearch-net/tree/develop/src/Nest/DSL) and [responses](https://github.com/elastic/elasticsearch-net/tree/develop/src/Nest/Domain/Responses) and all of the [domain objects](https://github.com/elastic/elasticsearch-net/tree/develop/src/Nest/Domain) they might contain. 

That said the way we currently are writing it down is not very terse due to the fact that we have to support two different C# DSL's. This makes it less then ideal as reference implementation.

For our 2.0 version we are exploring the idea of porting these types to a more isolated location (separate repos) written in a terser (but still strict) fashion in typescript and writing a node command line tool that can be used to generate C# classes and interfaces. Hopefully this can also be used to generate types for other languages. 

Similarly we also completely refactored our unit tests/integration tests and documentation [to be all self contained](https://github.com/elastic/elasticsearch-net/blob/2.0/src/Tests/Nest.Tests.Literate/SearchAPIs/RequestBodySearch/FromAndSize.cs) in something we dubbed literate tests. If anything it will provide for each type anywhere in the DSL one or more example usages that show how each fits in to the greater scheme of things. Again NEST already does this for most types but with the baggage of 5 years worth of ever changing coding patterns. 
The current design forces us to always rewrite everything in a uniform manner and write documentation and integration tests for them at the same time. 

Have not explored the idea of writing these not in C# but first in a custom DSL that can be used to generate our C# literate tests instead. This might again also help clients in different typed languages to generate serialization/deserialization tests, documentation and basic integration tests. Not sure this is worthwhile just a brainfart as I'm writing this down while I should be enjoying my vacation :smile:

This is all very preliminary and explorative and we might hit some dead ends but the way we (the .NET team) currently feel is that this is a very pragmatic approach to get to something real fast.

**Comment by bitemyapp** [comment]
@Mpdreamz I'm not trying to jockey for position here, but

```
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Haskell                          4            395            379           1831
-------------------------------------------------------------------------------
SUM:                             4            395            379           1831
-------------------------------------------------------------------------------
```

```
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C#                            1976          35051          50885         158333
JSON                           375              7              0          11043
MSBuild script                  14              0             98           5251
HTML                             1            232              2           3323
Razor                           20             55             73            710
ASP.Net                          5              0              0            455
-------------------------------------------------------------------------------
SUM:                          2391          35345          51058         179115
-------------------------------------------------------------------------------
```

Seems pretty stark.

Bloodhound has been used for awhile at a few different companies without needing more API coverage, there's no reason to believe the LOC would go up by 100 or even 10x to complete the coverage. (Tests are another 500 lines, the source includes the [doctests](http://hackage.haskell.org/package/bloodhound-0.5.0.1/docs/Database-Bloodhound-Client.html))

The C# code isn't very meaning dense. I won't presume to be able to say if this is intrinsic to the language or the constraints of the project, but it is what it is.

Constrast:

https://github.com/elastic/elasticsearch-net/blob/develop/src/Nest/Domain/DSL/Query.cs
(Plus a bunch of these: https://github.com/elastic/elasticsearch-net/blob/develop/src/Nest/DSL/Query/MatchAllQuery.cs )

With: https://github.com/bitemyapp/bloodhound/blob/master/src/Database/Bloodhound/Types.hs#L601-L629
and
https://github.com/bitemyapp/bloodhound/blob/master/src/Database/Bloodhound/Types.hs#L823-L832

Then if you want to look at what JSON gets generated, it's pretty easy to just fire up a REPL and find out or look at the `ToJSON` instances for the datatype you want.

I can grep `instance ToJSON MatchQuery` in the same file [and it takes me where I wanted to go](https://github.com/bitemyapp/bloodhound/blob/master/src/Database/Bloodhound/Types.hs#L1729).

I know people who don't use Haskell at all in their 9-5 that read Bloodhound's code or type stuff into a REPL[2] to get JSON that they know will work. Reading the source of a foreign programming language *known for being difficult to learn*[1] is *easier* for them than reading the docs. I don't think the C# client library would work as well for this purpose.

Consider this [EBNF example](http://en.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_Form#Examples) and [this bit of source](https://github.com/bitemyapp/bloodhound/blob/master/src/Database/Bloodhound/Types.hs#L268-L274).

This is a *real* library for *real* work that happens to have *real* integration tests (not just unit), it covers most of what people need with Elasticsearch *and* the source serves as readable documentation for people that don't even use the language.

I don't expect any particular outcome, but I would suggest there are opportunities for scalable, readable documentation of APIs that are executable that are not being considered.

[1]: A reputation I am doing my best to undermine.
[2]: Check out this REPL session and see how I can drill-down into the types interactively http://imgur.com/vyYKKq7

**Comment by Mpdreamz** [comment]
Sorry if you took my comment as an attack/commentary on your Haskell client that was not my intent. 

I was explaining what we are doing as the .NET team and how its output might be very beneficial. All preliminary, all unofficial. 

As **already** explained and mentioned in my original post: the current C# implementation is **nowhere near** an ideal reference implementation due to it being overly verbose to support not one but two DSL's. 

We will move all our interfaces out of our project and write them down into a much terser fashion, we are currently thinking typescript because of its excellent compiler api. But nothing set in stone. Granted this doesn't come close to the expressiveness of Haskell but it will get a great deal of (readable (as suppose to c# not haskell ;)) contracts out there fast.  Again this is a pragmatic choice from us to get somewhere fast while we also revalidate all our mappings again against elasticsearch (see if we have missing bits).

It helps us and we hope its results will help others too.

I've been wanting to do a F# stricter type mappings for Elasticsearch for a while now and having the above contracts would help me for instance. I hope we do get a 100% coverage API types described in Haskell and fully agree its the most pragmatic thing to get close to a grammar'esque(?) description of the Elasticsearch API. 


PS: Comparing line numbers is a bad metric even more so between languages without quantitive numbers on coverages or indicating whether repositories contain auxiliary projects or not that do not end up in the client. Also: the insinuation NEST is not a *real* project with no integration tests (we have loads!) nor real world users (again we have loads!) not appreciated and not beneficial to the discussion.

Im going back to enjoying my vacation now :smile:

**Comment by bitemyapp** [comment]
@Mpdreamz It's all good, I think I understood your intent!

>because of its excellent compiler api.

What do you need on this front that you're getting from TypeScript?

>Also: the insinuation 

That's not what I meant, I was making the point that Bloodhound *has* tests. It's quite clear to me that the C# project is quite complete, I was making the point that Bloodhound is less distant from that than one would think based on the LOC. I was taking it as a given that NEST is quite stable, my point is that if you use good tools, you get further and faster with even less but that can be hard to see when it has limited labor investment.

> Comparing LOC is a bad metric even more so between languages

I mean, sure, but 100x is 100x when they're both client libraries talking to the same search engine and I was using it to provide a quantitative form of the qualitative readability comparison I was trying to drive home. The qualitative readability bit is really more my point.

My goal was to get people to look at the code snippets I was linking and think about what it means for source code to be so readable and compact that it serves as better documentation than some existing written documentation, with the benefits of tests and executability to boot. I believe when you introduced NEST, I may not have made that clear yet.

Hope your vacation is restful and fun :tada: 

Cheers!

**Comment by clintongormley** [comment]
We haven't replaced parsing with a grammar - after much research, that just isn't going to happen.  We've done a major year-long refactoring of the search API, so I'm going to close this issue.
