### ISSUE TITLE
Elasticsearch cluster status is GREEN despite one node being unresponsive

### ISSUE THREAD

**Issue by erolatreston** [elastic/elasticsearch#89916]
### Elasticsearch Version

7.17.1

### Installed Plugins

prometheus-exporter

### Java Version

_bundled_

### OS Version

centos 7

### Problem Description

`CircuitBreakingException` occurred on one of the 3-node ES cluster. After this exception, the node became unresponsive. The JVM was alive but no response was returned on all requests including periodic metrics requests. However, during this time, the cluster status was still GREEN.

```
 [2022-08-28T08:20:22,907][DEBUG][org.elasticsearch.action.admin.cluster.node.info.TransportNodesInfoAction] [esn-2] failed to execute on node [Ekqvf6IwR4a5AK-cLG6hUg]
 org.elasticsearch.transport.RemoteTransportException: [pcaobus][172.17.184.157:9300][cluster:monitor/nodes/info[n]]
 Caused by: org.elasticsearch.common.breaker.CircuitBreakingException: [parent] Data too large, data for [cluster:monitor/nodes/info[n]] would be [2981923416/2.7gb], which is larger than the limit of [2958183628/2.7gb], real usage: [2981921960/2.7gb],    new bytes reserved: [1456/1.4kb], usages [request=0/0b, fielddata=15169/14.8kb, in_flight_requests=18500/18kb, accounting=170576/166.5kb]
```

The cluster status should have been YELLOW so that an alert can be generated to take corrective action on the node.

### Steps to Reproduce

No known ways to reproduce the problem.

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

Specifically, a health status of `GREEN` indicates that there are no unassigned shards. It does not account for any other measures of health. See [the reference documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-health.html#cluster-health-api-response-body) for more information.

Since there's no action needed by the Elasticsearch team here, I'm closing this. If you have any further questions on this topic, please raise them in the [forum](https://discuss.elastic.co/c/elasticsearch) instead.
