### ISSUE TITLE
Allow type:object at root level for backwards compatibiilty

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#8995]
The change here (https://github.com/elasticsearch/elasticsearch/pull/6093) appears to be causing a backwards compatibility issue:

```
{
   "error": "MapperParsingException[mapping [tweet]]; nested: MapperParsingException[Root type mapping not empty after parsing! Remaining fields:   [type : object]]; ",
   "status": 400
}
{
  "mappings": {
    "tweet": {
      "type":"object",  # <---- no longer allowed somewhere between 1.1 and 1.2
      "properties": {
        "person": {
```

Would be nice to still allow type:object at the root level even if it is the only option available.

**Comment by brwe** [comment]
It seems to me that setting "type":"object" in the root mapper was never persisted in the mapping anyway (tested 1.0.0). 
So I wonder how this breaks bwc? Old indices can still be loaded I think because they do not contain the "type": "object" anymore even if it was defined when creating the index. 
Also, I do not understand what the effect of setting the root mapper to type "object" should be but I might be missing something here.
Sorry for getting to this so late.

**Comment by clintongormley** [comment]
@brwe previously the root mapping accepted `type: object`, even if it didn't persist it.  Really the root mapping is a special object.  It broke things for me in a module which generated mappings automatically, because i had to treat the top level as different from any inner objects, but then the fix was trivial (delete that property).

It's pretty minor.  I'd be leaning slightly towards adding it back in for consistency's sake.

**Comment by brwe** [comment]
@clintongormley hm. I would feel a little awkward writing a commit message that says "This setting has no effect whatsoever and will be removed from the mapping immediately but Clinton has this module...." . So, I am more leaning towards not adding it.

**Comment by kimchy** [comment]
Just a note regarding persisting back the object mapping, we don't write the type object in the mappings most of the times (to try and save space, at least that was the initial thought behind it), since `properties` is enough to know its an object (if there weren't properties, we do write type object, see `ObjectMapper#toXContent`). This happens on any object mapping.

**Comment by clintongormley** [comment]
@brwe :D  - I just mean that I ran into the same thing as the OP...  The one thing is that today it is inconsistent.  It is accepted at field level, but not at root level.

**Comment by clintongormley** [comment]
Given that nobody else has complained about this in the last year, I think it is fine to close
