### ISSUE TITLE
Get Index API returns hidden indices even with expand_wildcards=open explicitly set

### ISSUE THREAD

**Issue by j-bennet** [elastic/elasticsearch#90171]
### Elasticsearch Version

8.5.0-SNAPSHOT

### Java Version

_bundled_

### OS Version

docker

### Problem Description

According to the API documentation, hidden indices should not be retrieved by default, or when expand_wildcards is set to `open`:

https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-index.html

However, a request like this returns hidden indices:

```
> curl -u elastic:changeme -XGET 'http://localhost:9200/_all?features=aliases,settings&filter_path=*.aliases,*.settings.index.hidden&expand_wildcards=open&pretty'
{
  ".ds-logs-enterprise_search.api-default-2022.09.19-000001" : {
    "aliases" : { },
    "settings" : {
      "index" : {
        "hidden" : "true"
      }
    }
  },
  ".ds-logs-enterprise_search.audit-default-2022.09.19-000001" : {
    "aliases" : { },
    "settings" : {
      "index" : {
        "hidden" : "true"
      }
    }
  },
  ".elastic-connectors-v1" : {
    "aliases" : {
      ".elastic-connectors" : { }
    },
    "settings" : {
      "index" : {
        "hidden" : "true"
      }
    }
  },
  "foo" : {
    "aliases" : {
      "foo-alias" : { },
      "search-foo" : { }
    }
  },
  "search-test" : {
    "aliases" : { }
  }
}
```

This is a snapshot version of Elasticsearch running in Docker.

```
> curl -u elastic:changeme -XGET 'http://localhost:9200'
{
  "name" : "92064acd49d3",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "KNGIXZZgRuOAVb75eRhc2w",
  "version" : {
    "number" : "8.5.0-SNAPSHOT",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "34471b1cd233496b6f8dab41bbc3e85564ae7389",
    "build_date" : "2022-09-19T12:19:57.187949399Z",
    "build_snapshot" : true,
    "lucene_version" : "9.4.0",
    "minimum_wire_compatibility_version" : "7.17.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

### Steps to Reproduce

1. Create a hidden index.
2. Use the above GET query.

Hidden indices show up, even though they shouldn't.

**Comment by parkertimmins** [comment]
This is actually the correct behavior (though it is pretty confusing). This is because the datastreams and aliases are not hidden. Though the underlying indices are hidden, they can be accessed through the associated visible datastream or alias. Since this is expected we're closing this issue.

For a bit longer explanation:
The [GET /index api](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-index.html) can be used to look up indices, data streams, or aliases. But only indices are actually returned by the endpoint; for data streams, the indices will be the backing indices, for aliases the indices are those pointed to by the alias.

When `/_all` is called, all indices, aliases, and datastreams are checked to see if they match the `expand_wildcards` arguments. If they match, they are then resolved to concrete indices, deduplicated, and returned. For a hidden index with a visible alias, both the index and the alias will be tested against the `expand_wildcards=open` argument. Since the index is hidden it will be filtered out. But then the alias, being visible, will be found to match the `expand_wildcards` filter. It will then be resolved to the index and returned. 

On the other hand, if both an index and all its aliases are hidden, the index will not be returned for `expand_wildcards=open`.

This behavior can be seen below: 
```
# make hidden index without an alias
curl $AUTH -XPUT "$ES_URL/index-hidden-no-alias" -H 'Content-Type: application/json' -d'
{
	"settings": {
		"index": {
			"hidden":true
		}
	}
}
' 

# make hidden index with an alias
curl $AUTH -XPUT "$ES_URL/index-hidden" -H 'Content-Type: application/json' -d'
{
	"aliases": {
		"alias-to-index-hidden": {}
	},
	"settings": {
		"index": {
			"hidden":true
		}
	}
}
'

# make hidden index with a hidden alias
curl $AUTH -XPUT "$ES_URL/index-hidden-with-hidden-alias" -H 'Content-Type: application/json' -d'
{
	"aliases": {
		"hidden-alias-to-index-hidden": {
			"is_hidden": true
		}
	},
	"settings": {
		"index": {
			"hidden":true
		}
	}
}
'

# return open indices
curl $AUTH -XGET "$ES_URL/_all?features=aliases,settings&filter_path=*.aliases,*.settings.index.hidden&expand_wildcards=open&pretty"
```
This outputs the following:
```
  "index-hidden" : {
    "aliases" : {
      "alias-to-index-hidden" : { }
    },
    "settings" : {
      "index" : {
        "hidden" : "true"
      }
    }
  }
```
Only  `index-hidden` was returned, because `index-hidden-no-alias` was not accessible through an alias, and `index-hidden-with-hidden-alias` had an alias which was also hidden.
