### ISSUE TITLE
Wildcard expansion on `_update_by_query` for data streams

### ISSUE THREAD

**Issue by Anaethelion** [elastic/elasticsearch#90272]
### Elasticsearch Version

8.4.1

### Java Version

_bundled_

### OS Version

Any

### Problem Description

Data streams can be individually targeted by update by query but wildcards don't seem to work.

ie: `/my-data-stream-*/_update_by_query` doesn't work while `/my-data-stream-1,my-data-stream-2/_update_by_query` does.

### Steps to Reproduce

Following the [basic setup for datastreams](https://www.elastic.co/guide/en/elasticsearch/reference/current/set-up-a-data-stream.html):

```

PUT /my-data-stream-1/_bulk
{ "create":{ } }
{ "@timestamp": "2099-05-06T16:21:15.000Z", "message": "192.0.2.42 - - [06/May/2099:16:21:15 +0000] \"GET /images/bg.jpg HTTP/1.0\" 200 24736" }
{ "create":{ } }
{ "@timestamp": "2099-05-06T16:25:42.000Z", "message": "192.0.2.255 - - [06/May/2099:16:25:42 +0000] \"GET /favicon.ico HTTP/1.0\" 200 3638" }

PUT /my-data-stream-2/_bulk
{ "create":{ } }
{ "@timestamp": "2199-05-06T16:21:15.000Z", "message": "192.0.2.42 - - [06/May/2199:16:21:15 +0000] \"GET /images/bg.jpg HTTP/1.0\" 200 24736" }
{ "create":{ } }
{ "@timestamp": "2199-05-06T16:25:42.000Z", "message": "192.0.2.255 - - [06/May/2199:16:25:42 +0000] \"GET /favicon.ico HTTP/1.0\" 200 3638" }

POST /my-data-stream-*/_update_by_query
{
  "query": {
    "term": {
      "@timestamp": {
        "value": "2099-05-06T16:21:15.000Z"
      }
    }
  }
}
```
Total number of documents is 0.

```
POST /my-data-stream-1,my-data-stream-2/_update_by_query
{
  "query": {
    "term": {
      "@timestamp": {
        "value": "2099-05-06T16:21:15.000Z"
      }
    }
  }
}
```
Total number of documents is now 1.

**Comment by weslambert** [comment]
Hi, I was wondering if there has been any movement on this issue? This prevents us from fully leveraging data streams. Thanks!

**Comment by weslambert** [comment]
Hi, I just wanted to check in again. Is there any way we could help work towards a solution for this issue?

**Comment by tvernum** [comment]
It appears this is simply due to the fact that [`UpdateByQueryRequest`](https://github.com/elastic/elasticsearch/blob/3506d5e7382aa0a393bfcb202cf776a5c25dfcec/server/src/main/java/org/elasticsearch/index/reindex/UpdateByQueryRequest.java#L29) doesn't override `includeDataStreams` and inherits the [default implementation](https://github.com/elastic/elasticsearch/blob/3506d5e7382aa0a393bfcb202cf776a5c25dfcec/server/src/main/java/org/elasticsearch/action/IndicesRequest.java#L37-L39) from `IndicesRequest` (i.e. `return false`).  
[`DeleteByQueryRequest`](https://github.com/elastic/elasticsearch/blob/3506d5e7382aa0a393bfcb202cf776a5c25dfcec/server/src/main/java/org/elasticsearch/index/reindex/DeleteByQueryRequest.java) seems to have the same issue.

Assuming we want to support datastreams here (and I haven't done anything thinking about what the implications might be) then the change itself should be simple.

**Comment by weslambert** [comment]
Thanks for looking into it, @tvernum! Let me know how I can help.

**Comment by weslambert** [comment]
Hi, I just wanted to check in on this to see if there is anything I can do to help. Thanks!

**Comment by dakrone** [comment]
@weslambert I've opened a PR for fixing this at #92717

**Comment by weslambert** [comment]
> @weslambert I've opened a PR for fixing this at #92717

Awesome! Thank you!
