### ISSUE TITLE
[HealthAPI] Shards availability indicator doesn't report diagnosis when disk is out of space

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#90327]
### Elasticsearch Version

8.4, 8.5, 8.6

### Java Version

_bundled_

### OS Version

Darwin

### Problem Description

The shards availability indicator should always be reporting diagnosis when its status is RED/YELLOW.
However, when an index is on a data node that runs out of disk space it will report RED but no diagnosis.

### Steps to Reproduce

Have multi-node cluster where a data (non-master) node that hosts an index runs out of disk space (the index cannot relocate somewhere else).
Call the Health API and the output will be something along these lines:
```
    "shards_availability": {
      "status": "red",
      "symptom": "This cluster has all shards available.",
      "details": {
        "initializing_primaries": 1,
        "started_replicas": 0,
        "initializing_replicas": 0,
        "unassigned_primaries": 0,
        "started_primaries": 1,
        "creating_primaries": 0,
        "unassigned_replicas": 0,
        "restarting_primaries": 0,
        "restarting_replicas": 0
      },
      "impacts": [
        {
          "id": "elasticsearch:health:shards_availability:impact:primary_unassigned",
          "severity": 1,
          "description": "Cannot add data to 1 index [test_index]. Searches might return incomplete results.",
          "impact_areas": [
            "ingest",
            "search"
          ]
        }
      ] 
    }
```

**Comment by gmarouli** [comment]
A short update with my observations and theories so far.

By taking a closer look to response above we see the following inconsistencies:
- Status is `red` indicating that a primary shard is unavailable.
- The impacts report that one primary shard is unassigned: `primary_unassigned`.
However,
- The symptoms report that all shards are available.
- The details report that all replicas are assigned, with one`STARTED` and one`INITIALIZING`.
- No diagnosis indicated a healthy cluster.

I believe that this can be reproduced by any shard with the status `INITIALIZING` (unit test coming soon :)). What lead me to this conclusion are the different ways to calculate status & impact vs details, symptoms & diagnosis:

**Symptom**
For the symptom we check if any of the following counters is greater than 0: (`primaries.unassigned`, `primaries.unassigned_new`, `primaries.unassigned_restarting`, `replicas.unassigned`, `replicas.unassigned_restarting`). Since there are no unassigned shards all the counts are 0.

**Details**
- The details indicate that there are 2 shards, one either `STARTED` or `RELOCATING` and one that is `INITIALIZING`.

**Diagnosis**
In order to get a diagnosis we need at least one unassigned shard, but we do not have any unassigned shards so we have no diagnosis.

**Impact**
To have the impact `primary_unassigned` it means that the set `primaries.indicesWithUnavailableShards` is not empty. 

**Status**
The status checks the `primaries.available` flag.

Both the status and the impact use the following condition `(routing.active() || isRestarting || isNew) == false`. From the following code snippet:
```
            boolean isNew = isUnassignedDueToNewInitialization(routing);
            boolean isRestarting = isUnassignedDueToTimelyRestart(routing, shutdowns);
            available &= routing.active() || isRestarting || isNew;
            if ((routing.active() || isRestarting || isNew) == false) {
                indicesWithUnavailableShards.add(routing.getIndexName());
            }
```

I believe this is where the problem is, it doesn't account for an initializing shard. The shard is not active and it's not unassigned so the condition results to `false` while it shouldn't. Assuming having an shard that is `INITIALIZING` is part of the happy flow and the user cannot do anything, I propose to take this into consideration and to not consider it as a health problem.

Next steps:
1) Write a test that reproduces it.
2) If there are no objections with my proposal, fix it. This would mean that the health response will change to this:
```
"shards_availability": {
      "status": "green"
      "symptom": "This cluster has all shards available.",
      "details": {
        "initializing_primaries": 1,
        "started_replicas": 0,
        "initializing_replicas": 0,
        "unassigned_primaries": 0,
        "started_primaries": 1,
        "creating_primaries": 0,
        "unassigned_replicas": 0,
        "restarting_primaries": 0,
        "restarting_replicas": 0
      }
    }
```
