### ISSUE TITLE
Discussion: should removing alias on wildcard honor destructive_requires_name?

### ISSUE THREAD

**Issue by faxm0dem** [elastic/elasticsearch#9082]
Currently, even if `action.destructive_requires_name == true` we can still remove aliases on multiple indices, *e.g.*:

```json
☠ curl 0:9200/_cluster/settings\?pretty
{
  "persistent" : {
    "action" : {
      "destructive_requires_name" : "true"
    }
  },
  "transient" : { }
}
☠ curl 0:9200/_aliases\?pretty -d '{"actions":[{"remove":{"index":"syslogng*","alias":"foo"}}]}'
{
  "acknowledged" : true
}
```

IMHO this should be prohibited

**Comment by javanna** [comment]
Hi @faxm0dem I just marked this for discussion, sorry it took a while to get to it.

I do see your point, although I am not sure since removing aliases is not that destructive...well it depends on how you look at it I guess. You don't lose any data by removing an alias, but you might cause problems to applications and users relying on aliases. The thing is that the request does contain the explicit name of the alias that you want to delete; imagine you are performing a destructive operation on that same alias, like a delete foo, that is going to work fine since you didn't have wildcards in your request. I think that the current behaviour is ok, but we can open this up for discussion and see what other folks think.

**Comment by clintongormley** [comment]
No more comments on this issue, so guessing this isn't widely needed. Closing

**Comment by faxm0dem** [comment]
:-P
