### ISSUE TITLE
Composite + Nested + Scripted Metric can fail in Lucene when evaluating scores

### ISSUE THREAD

**Issue by not-napoleon** [elastic/elasticsearch#90955]
### Elasticsearch Version

7.17, 8.6

### Java Version

_bundled_

### OS Version

NA

### Problem Description

When running an aggregations tree that looks like Nested -> Composite -> Scripted Metric, it is possible for the query to fail when some of the nested sub-documents don't match a top level query.  It may be the case that there is a more minimal reproduction than what I have below, but this should be enough to show the error.  The scripted metric is an essential component of the reproduction, as it forces us into `needsScores==true` path in this loop:

```java
           while ((docID = docIdSetIterator.nextDoc()) != DocIdSetIterator.NO_MORE_DOCS) {
                if (needsScores) {
                    assert scorerIt != null && scorerIt.docID() < docID;
                    scorerIt.advance(docID);
                    // aggregations should only be replayed on matching documents
                    assert scorerIt.docID() == docID;
                }
                collector.collect(docID);
            }
```

(from `CompositeAggregator`, starting on line 555 in main).

### Steps to Reproduce

```
PUT /index1
{
  "mappings": {
    "properties": {
      "@timestamp": {
        "type": "date"
      },
      "lines": {
        "type": "nested",
        "properties": {
            "@timestamp": {
                "type": "date"
            },
            "name": {
                "type": "keyword"
            },
            "value": {
                "type": "double"
            }
        }
      }
    }
  }
}


POST /index1/_doc
{
  "@timestamp": "2022-09-01",
  "lines": [
    {
      "@timestamp": "2022-10-01",
      "name": "foo",
      "value": "1.2"
    },
    {
      "@timestamp": "2022-09-01",
      "name": "bar",
      "value": "2.3"
    },
    {
      "@timestamp": "2022-10-01",
      "name": "foo",
      "value": "1.2"
    },
    {
      "@timestamp": "2022-09-01",
      "name": "bar",
      "value": "2.3"
    },
    {
      "@timestamp": "2022-10-01",
      "name": "foo",
      "value": "1.2"
    },
    {
      "@timestamp": "2022-09-01",
      "name": "bar",
      "value": "2.3"
    },
    {
      "@timestamp": "2022-10-01",
      "name": "foo",
      "value": "1.2"
    },
    {
      "@timestamp": "2022-09-01",
      "name": "bar",
      "value": "2.3"
    }
  ]
}



POST /index*/_search
{
  "size": 0,
  "query": {
    "bool": {
      "filter": [
        {
          "range": {
            "@timestamp": {
              "from": "2022-09-01",
              "to": "2022-09-30",
              "include_lower": true,
              "include_upper": true,
              "time_zone": "Europe/Paris",
              "boost": 1
            }
          }
        }
      ],
      "adjust_pure_negative": true,
      "boost": 1
    }
  },
  "_source": true,
  "track_total_hits": -1,
  "aggregations": {
    "data": {
      "nested": {
        "path": "lines"
      },
      "aggregations": {
        "my_buckets": {
          "composite": {
            "size": 20,
            "sources": [
              {
                "prod_name": {
                  "terms": {
                    "field": "lines.name"
                  }
                }
              }
            ]
          },
          "aggregations": {
            "catalog_price": {
              "scripted_metric": {
                "init_script": {
                  "source": "state.transactions = []"
                },
                "map_script": {
                  "source": "state.transactions.add(doc['lines.value'].value)"
                },
                "combine_script": {
                  "source": "double sum = 0; for (t in state.transactions) { sum += t } return sum"
                },
                "reduce_script": {
                  "source": "double sum = 0; for (a in states) { if (a != null) { sum += a } } return sum"
                }
              }
            }
          }
        }
      }
    }
  }
}

```

### Logs (if relevant)

Here's the key section of the failure stack trace (from 7.17.  Main has slightly different line numbers):

```
Caused by: java.io.EOFException: read past EOF: MMapIndexInput(path="/Users/marktozzi/code/elastic/elasticsearch-7.x/build/testclusters/runTask-0/data/nodes/0/indices/zaLHu-waQmGgDL-1cLbcMw/0/index/_0.cfs") [slice=_0_Lucene80_0.dvd] [slice=docs]
        at org.apache.lucene.store.ByteBufferIndexInput.readByte(ByteBufferIndexInput.java:85) ~[lucene-core-8.11.1.jar:8.11.1 0b002b11819df70783e83ef36b42ed1223c14b50 - janhoy - 2021-12-14 13:46:43]
        at org.apache.lucene.store.DataInput.readShort(DataInput.java:95) ~[lucene-core-8.11.1.jar:8.11.1 0b002b11819df70783e83ef36b42ed1223c14b50 - janhoy - 2021-12-14 13:46:43]
        at org.apache.lucene.store.ByteBufferIndexInput.readShort(ByteBufferIndexInput.java:163) ~[lucene-core-8.11.1.jar:8.11.1 0b002b11819df70783e83ef36b42ed1223c14b50 - janhoy - 2021-12-14 13:46:43]
        at org.apache.lucene.codecs.lucene80.IndexedDISI.readBlockHeader(IndexedDISI.java:426) ~[lucene-core-8.11.1.jar:8.11.1 0b002b11819df70783e83ef36b42ed1223c14b50 - janhoy - 2021-12-14 13:46:43]
        at org.apache.lucene.codecs.lucene80.IndexedDISI.advance(IndexedDISI.java:387) ~[lucene-core-8.11.1.jar:8.11.1 0b002b11819df70783e83ef36b42ed1223c14b50 - janhoy - 2021-12-14 13:46:43]
        at org.apache.lucene.codecs.lucene80.Lucene80DocValuesProducer$SparseNumericDocValues.advance(Lucene80DocValuesProducer.java:474) ~[lucene-core-8.11.1.jar:8.11.1 0b002b11819df70783e83ef36b42ed1223c14b50 - janhoy - 2021-12-14 13:46:43]
        at org.apache.lucene.index.SingletonSortedNumericDocValues.advance(SingletonSortedNumericDocValues.java:58) ~[lucene-core-8.11.1.jar:8.11.1 0b002b11819df70783e83ef36b42ed1223c14b50 - janhoy - 2021-12-14 13:46:43]
        at org.apache.lucene.search.ConjunctionDISI.doNext(ConjunctionDISI.java:211) ~[lucene-core-8.11.1.jar:8.11.1 0b002b11819df70783e83ef36b42ed1223c14b50 - janhoy - 2021-12-14 13:46:43]
        at org.apache.lucene.search.ConjunctionDISI.advance(ConjunctionDISI.java:242) ~[lucene-core-8.11.1.jar:8.11.1 0b002b11819df70783e83ef36b42ed1223c14b50 - janhoy - 2021-12-14 13:46:43]
        at org.elasticsearch.search.aggregations.bucket.composite.CompositeAggregator.runDeferredCollections(CompositeAggregator.java:555) ~[elasticsearch-7.17.7-SNAPSHOT.jar:7.17.7-SNAPSHOT]
        at org.elasticsearch.search.aggregations.bucket.composite.CompositeAggregator.buildAggregations(CompositeAggregator.java:175) ~[elasticsearch-7.17.7-SNAPSHOT.jar:7.17.7-SNAPSHOT]
```

**Comment by martijnvg** [comment]
This are forum threads that look similar to what has been reported in this issue:
* https://discuss.elastic.co/t/query-composite-top-hits-exception/227225
* https://discuss.elastic.co/t/index-128-out-of-bounds-for-length-128/287971

In these cases the error occurred when using a `top_hits` aggregation that sorts by score instead of `scripted_metric` aggregation. Note that the stacktrace reported in the latter issue is different, I'm not sure why yet. But I think this array out of bounds exception is also occurring with other sub aggregations, not just scripted_metric.

**Comment by not-napoleon** [comment]
@gemaliano found that you can repro this with an even simpler data set:

```
POST /index1/_doc
{
  "@timestamp": "2022-09-01",
  "lines": [
    {
      "@timestamp": "2022-09-01",
      "name": "foo",
      "value": "1.2"
    },
    {
      "@timestamp": "2022-09-01",
      "name": "foo",
      "value": "1.2"
    },
    {
      "@timestamp": "2022-09-01",
      "name": "bar",
      "value": "2.3"
    }
  ]
}
```

Using the same query I posted above.  In this case, it looks like all of the child documents should match the top level query, so that's not actually the cause of this error.

**Comment by martijnvg** [comment]
> Using the same query I posted above. In this case, it looks like all of the child documents should match the top level query, so that's not actually the cause of this error.

I think in this case no child documents did match. The main query with a `range` query is on the `@timestamp` field and no child documents have this field. (They do have the `lines.@timestamp` field)

I think this points out what is wrong here. The main query will never emit child docids as matches, yet we replay the main query during composite aggregation's execution and assume that for the docids we want to run deferred collection that the docids are they same with the scorer of the main query. This isn't true when a composite aggregation has a nested aggregation as parent.

In the example of the simple data set, the child docids are 0, 1 and 2 and the parent docid is 3. When the composite agg runs deferred collection then when the first docid is pulled from `docIdSetIterator`, which is 0, then the `scorerIt` is advanced to `3`, because that is the only docid that matches with the main query (the parent doc). The second time a docid is pulled from `docIdSetIterator`, `1` is returned, the `scorerIt` is advanced to `1`, but it is already at `3` and because there are no more docids the scorer returns `DocIdSetIterator.NO_MORE_DOCS`. The third time a docid is pulled from `docIdSetIterator `, `2` is returned and we advance `scorerIt` again this time with `2`. However `scorerIt` has been exhausted, yet we do it anyway. This triggers undefined behaviour in Lucene (using a scorer iterator or docid set iterator that has been exhausted)  and in this case an array out of bounds exception is thrown.

What are we doing wrong here? First we never check the return value of `scorerIt.advance(docID);`, so we never know whether `scoreIt` has been exhausted. But more importantly the scorer that we advance will only emit parent docids of the docids that are emitted by `docIdSetIterator`. When the scorer is used by sub aggregations, then the `score()` method returns score for the parent docid and not the (child) docid that is being processed.

Now the array out of bounds exception doesn't always happen. It depends on whether the scorer has been exhausted and in cases when `scorerIt` has many more matches beyond the docids that are in `docIdSetIterator` then the error doesn't occur. Which depends on the data, the query and aggregation. But the score being reported is always wrong for nested/child docids (even if a `nested ` query is used in the main query).

The only workaround I see here is ensuring that the leaf aggregation doesn't need score. With the `top_hits` aggregation not sorting by _score will do that. However for the `scripted_metrics` aggregation, we forcefully enable scoring, because we don't know whether scores are being accessed in the scripts defined in this aggregation. So I don't see a workaround for this.

As for a potential fix. I think we need to overwrite the `scoreMode()` method in `NestedAggregator` and return `ScoreMode.COMPLETE_NO_SCORES`. I think this is ok, since we aren't able to access this the score of the child documents anyway (and often the `nested` query isn't even used as main query, so the score would always be 1).  This avoids the creation of a Weight and Scorer in `CompositeAggregation#runDeferredCollections()` and therefor avoids this bug. Alternatively, at minimum we should check whether the `scoreIt` has been exhausted in the case a parent is a nested aggregation to avoid errors like array out of bounds exception.
