### ISSUE TITLE
Painless def equality comparison optimization - use constant .equals

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#91235]
In an equality comparison between a def and a String literal, painless can use the literals `.equals(Object other)` method to check the equality to avoid the cost of resolving the def values equals method.

`ctx.foo == 'abc'` -> `'abc'.equals(ctx.foo)`

**Comment by thecoop** [comment]
So, there's two different ways to do this:

1. Do it in ASM generation. Replace the comparison with an ASM call to Objects.equals, using `swap` opcode when we want to call `b.equals(a)`
2. Modify the IL tree to change the comparison to a method call. The issue here is getting a way to call `b.equals(a)` without changing the execution order of a and b. You could do a variable swap, but that is very tricky to do in the middle of an expression. Or you could use a method defined in `Utility`, but then you need to make that accessible from painless.

**Comment by jdconrad** [comment]
@thecoop

This should be done as part an IR tree modification. Our goal is to have the fewest possible customizations as part of asm generation. This could be added to the `DefaultStringConcatenationOptimizationPhase`. An example of updating the tree on the fly is in `DefaultConstantFoldingOptimizationPhase` where we do constant folding. Or we could add another phase that simply does this change. 

My understanding is because we are moving a guaranteed `String` constant, the order of operations can be reversed without any side effects. The second expression will always be evaluated. The only change is we guarantee LHS null values will not cause an NPE. While possible someone is catching an NPE as control-flow I would consider this a bug as they should do an if check beforehand instead. In the case a user is doing an if check beforehand, nothing else changes.

**Comment by thecoop** [comment]
But execution order could matter, with something like `(var1 = obj.toString()) == (var2 = obj.toString())`. (you could imagine the expressions being more complicated so that order does actually matter)

**Comment by jdconrad** [comment]
In the case you presented we would not do the optimization. We should make this tightly constrained to only work on `expr == 'constant'` as a first pass. We can detect this exact pattern as part of the tree and skip out otherwise.

**Comment by thecoop** [comment]
Implemented in #91362
