### ISSUE TITLE
Add capability to configure total fields limit at specific path within an index mapping

### ISSUE THREAD

**Issue by geekpete** [elastic/elasticsearch#91440]
### Description

A feature to put a total fields limit at a particular path point in the mapping.

Like under a particular path there can be no more than `x` fields created nested or otherwise below this mapping path as an index setting. 

Provides a finer control than the more blunt total index fields limit, preventing more specific field explosion occurring at a particular mapping path/location and still not impacting the overall mapping from increasing fields within the index level limit.

Especially useful for scenarios where mapping explosion is occurring under a particular level in the mapping rather than explosions occurring at top level in the mapping.

Examples might be APM custom labels being created in error with high cardinality field names (eg timestamp, username or other high cardinality value added to label field name) or any general "attributes" type field where the values could be high cardinality and all occur at that one level.

This feature might also be useful even if not directly for preventing mapping explosion but just creating a mapping level limit of how many fields can exist under a particular level as a limit that can be enforced at mapping for example you only want a possibility of 20 fields under some label/attribute section.

This could be implemented as part of the dynamic mapping functionality and have an additional total mapping configuration that can be specified as part of a field config.

**Comment by javanna** [comment]
We have been discussing the vision around the current total fields limit with the team, its goal and the fact that we would like to make it less visible to users, see #89911.

The current total fields limit is there to prevent users with dynamic mappings from using many unique keys by mistake in their documents. This could happen anywhere in a document, and that explains why the limit is rather high (ideally it would be even higher so that users never hit it). The total fields limit is not there to control the number of fields in the mappings and eventually limit mappings resource usage.

In the context of preventing mappings explosion, I don't see how finer granularity would help. The total fields limit would catch user mistakes anyways, and what is the value of configuring the limit per field over the complexity and overhead it brings for users as well as for the codebase?

Do you have a real-life situation where the feature you are proposing would have helped?

**Comment by geekpete** [comment]
A real world example was APM labels but it was a misuse of labels that affected the mapping. The total fields increased to 10k per index as each index hit the limit, but after rolling over a sufficient amount of indices, the total number of fields for the index pattern returned by the field caps API started to hammer Kibana performance, since Kibana has to parse a massive JSON payload with each Field Caps response using a single thread.
We also warn about too many labels and field explosion in the APM docs and have fixes coming to reduce this impact specifically with custom labels by storing them as a flattened field so that some vast amount of labels won't cause any large field count increase in the mapping.

So as a feature specifically to guard against that it's probably down the list from other things you can do to avoid that particular impact and there's other things specific to APM that will address it. 

I guess your point is that we're less in the business of general widgets that might be useful and more focused on building super specific features that if they can force multiply with multiple specific use cases the one feature can help with then this is a better measure of a general feature benefit?

In general the granularity can help when you hit some very specific field explosion at a particular point in your mapping where reducing the total fields limit to something much smaller could break multiple functionalities (eg 10k limit was working but didn't prevent the impact overall once enough indices summed to 200k unique fields) and where reducing the limit at one point in the mapping can address a specific cause of mapping explosion (eg label or attribute type field receiving high cardinality field names) and still allow other more organic field count to grow as normal.

This might not only help as a workaround after you detect mapping explosion, where you could limit the particular mapping path then roll the index over giving you some mitigation until you can get a maintenance window to address the overall issue or get code changes made and tested, but can also be preventative like with APM you could have a default limit of some small amount of labels to guard against the problem in the first place that you could override later as needed, being that we know lablels are likely a point of explosion since we already warn about this in the APM docs.

**Comment by javanna** [comment]
I better understand where this is coming from, thanks for the additional context. I think that your proposal goes more into the territory of limiting resource usage though, which is not the goal of the total fields limit. There's also complexity caused by the impact of the number of fields not being a factor alone, but only combined with the number of indices, which makes setting a limit hard in my opinion.

I can see how field_caps may be the bottleneck when many indices with many fields are targeted. I think it would be useful to collect more info about what you have observed and what we can do about that specifically, rather than jumping straight to general solutions at the mappings level. We recently made improvements to the field_caps execution against many indices which all have the same mappings. Could you open a separate issue to share more info on the field_caps slowdown you have observed, which version was it on, how many indices, how many fields per index, did all indices have the same mappings etc? I'd bet we have already improved this and if not we should focus on that and iterate on field_caps performance further.

Also, using the flattened field for labels sounds like the right solution to me. It is exactly the scenario that the flattened field was introduced for.
