### ISSUE TITLE
new write option to enable datastore-like durability

### ISSUE THREAD

**Issue by agirbal** [elastic/elasticsearch#9151]
Typical datastore (e.g. SQL) define durability in ACID as the fact that the data must be written to persistent storage before acknowledgement is sent back to the client.
It looks like today ES stops short of providing such an option even though implementation is said to be easy.
The translog is only written out every 5s and since there is no builtin support for WAN replication, there is a good chance that a power loss event would reboot all replicas at once and data from last 5s is lost.
Typically in datastore the exact equivalent of translog is a write-ahead log that gets written out to disk (by itself) every 100ms or so (ensuring less than 100ms of data can be lost) but also allows client write acknowledgment to wait for it.

Ideally there would be a "tl_sync" write option which would wait for TL sync to happen before acknowledging back to client.
If used, it should cut down on the delay to flush the TL from 5s to say 5ms, or a maximum delay could be specified "tl_sync=5" after which time the sync would be initiated.
Each index op has increased latency (e.g. up to 5ms each) but those can be bulked, and by using more connections the perf is still pretty good since ES does not actually do more work.
This setting can either just apply to the primary shard's translog or also the replicas, but former is enough to match SQL's durability which is what people usually look for.

**Comment by kimchy** [comment]
Note that one can already configure the periodic timeframe in which fsync (and flushing the translog) is called, all the way down to "0", which means it gets fsync'ed on each operation done on the translog. 

A batch option while delaying the response might be an optimization that is worth discussing, would be interesting to run tests to see how much we gain perf wise compared to the "0" option.

Also, a power loss on a single machine should not be a problem, since we do sync replication, and the same translog behavior happens on the replica(s) side (its not async replication, at least not by default). A power loss on multiple machines at the same time holding all the copies of the data will suffer though from the periodic behavior.

**Comment by jpountz** [comment]
Closed via https://github.com/elastic/elasticsearch/pull/11011
