### ISSUE TITLE
more_this_like Similarity query with different scores

### ISSUE THREAD

**Issue by zhouixi** [elastic/elasticsearch#91532]
![QQ截图20221112165048](https://user-images.githubusercontent.com/25605651/201466752-52c2fbab-21cf-4062-ab14-39a7713269e5.png)
For the same text, the calculated scores are different.
![QQ截图20221112165117](https://user-images.githubusercontent.com/25605651/201466772-a284ad5e-04f6-48d4-bb99-1bcc183465d6.png)
For the same text, the calculated scores are the same. Why does this happen.

**Comment by cbuescher** [comment]
Hi @zhouixi ! Your question is better suited to the support forums over at https://discuss.elastic.co/. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Make sure to include your query and a reproducible example in order to make it easier for folks to respond quickly. Many thanks.
