### ISSUE TITLE
Do we need to update azure-storage-common-12.9.0.jar?

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#91573]
This was raised here - https://discuss.elastic.co/t/repository-azure-for-7-17/318845. It looks like we are using azure-storage-common-12.9.0.jar with a few known issues, and the recommendation is to upgrade to 12.10.1+ as per https://learn.microsoft.com/en-gb/java/api/overview/azure/storage?view=azure-java-stable#known-issues.

Is this something we need to address, and can address in a future 7.17 point release?

**Comment by ehinkle27** [comment]
Was this ever addressed or is something we can patch on the existing version of ES? We are currently running 7.16.3 and have received a similar notification from MS about use of the older sdk.
Shows we are using 
SDK: azsdk-java-azure-storage-blob 
**SDK version: 12.9.0** 


There are issues with older Azure Storage Java v12 SDK versions
You're receiving this notification because you've used an impacted version of Azure Storage Java v12 SDK in the past 30 days. 
You've been identified as using one or more impacted SDKs. The Account Information section of this email lists storage accounts in your subscriptions found to have usage from the impacted SDKs. 

Recommended action 
Please update the Azure Storage Java v12 SDK to the latest version as soon as possible and stop using any older versions. 

SDK 	Versions impacted 	Minimum safe version 	Recommended action 
**Blob SDK 	12.0 to 12.10.0 	12.10.1 	Update to latest version** 
Data Lake SDK 	12.0 to 12.7 	12.8.0 	Update to latest version 
File SDK 	12.0 to 12.4.1 	12.5.0 	Update to latest version 
Queue SDK 	12.0 to 12.6.0 	12.7.0 	Update to latest version 
Blob Cryptography SDK 	12.0 to 12.16.1 	12.17.0 	Update to latest version

**Comment by joegallo** [comment]
It looks to me like this was fixed via #92120 which shipped in `v7.17.9`.
