### ISSUE TITLE
Provide a way of creating snapshots to Azure Storage Accounts secured by network filter from elastic cloud

### ISSUE THREAD

**Issue by iuriikhrystiuk** [elastic/elasticsearch#91835]
### Description

**Use-case**: As an administrator of the elastic cloud clusters deployed to Azure I want to store snapshots of my clusters on Azure Storage Accounts, which are different from the default one provided by Elastic cloud and are protected by the traffic filter, so that the traffic is routed through Azure VNets and files are accessible finely defined set of infrastructure components and not accessible from the global internet.

**Problem**: there is current implementation of securing ingress traffic to Elastic Cloud clusters trough the use of Private Links. When talking about securing egress traffic initiated by the Elastic Cloud clusters - there are no available tools.

**Existing Solution**: none.

**Impact**: although Azure Storage Accounts have security keys that are of sufficient complexity - there is always a possibility of someone gaining access to data, which would result in data breach. The impact is *high*, probability is *low*.

**Suggested Solution**: Implement tools to set up Private Endpoints inside Elastic Cluster VNets, attach Private DNS Zones and connect those to the provided Private Link Services, which would have Azure storage accounts. Essentially this is existing Private Link functionality in reverse order.

**Comment by ywangd** [comment]
@iuriikhrystiuk Thanks very much for your interest in Elasticsearch.

It appears that the feature is not something that should be implemented directly within Elasticsearch. It is more at the level of platform and infrastructure. Since the environment you are interested is Elastic Cloud, I encourage you to leverage the support contract to have your request escalated via the support team. As such, I hope you don't mind that I close this.

**Comment by iuriikhrystiuk** [comment]
@ywangd, funny thing: I was directed here from elastic cloud support team... I will talk with them, sure.
