### ISSUE TITLE
In the Alias of data streams filter on only one data_stream ends up applying to all others

### ISSUE THREAD

**Issue by mpakoupete** [elastic/elasticsearch#92050]
### Elasticsearch Version

8.5

### Java Version

_bundled_

### OS Version

any

### Problem Description

The use of alias of data streams behaves differently from the alias of indices.
When trying to apply filter to only one data_stream in the Alias, the result is that It ends up applying to both.

### Steps to Reproduce

```json
POST _aliases
{
    "actions": [
        {
            "add": {
                "index": "data_stream_1",
                "alias": "alias_1",
                "filter": {
                    "bool": {
                        "filter": [
                            {
                                "term": {
                                    "reaction": "report"
                                }
                            }
                        ]
                    }
                }
            }
        },
        {
            "add": {
                "index": "data_stream_2",
                "alias": "alias_1"
            }
        }
    ]
}
```
Per the above request, I’m trying to apply filter to only one data stream in the Alias but the result is that It ends up applying to both.

### result

```json
GET _alias/alias_1
{
  "data_stream_2": {
    "aliases": {
      "alias_1": {
        "filter": {
          "bool": {
            "filter": [
              {
                "term": {
                  "reaction": "report"
                }
              }
            ]
          }
        }
      }
    }
  },
  "data_stream_1": {
    "aliases": {
      "alias_1": {
        "filter": {
          "bool": {
            "filter": [
              {
                "term": {
                  "reaction": "report"
                }
              }
            ]
          }
        }
      }
    }
  }
}
```

**Comment by dakrone** [comment]
I looked into this a little bit. Here's a quick reproduction that includes creating the data streams from `./gradlew run`:

```json
POST /logs-foo-bar/_doc
{
  "@timestamp": "2022-01-01"
}

POST /logs-foo-baz/_doc
{
  "@timestamp": "2022-01-01"
}

POST _aliases
{
    "actions": [
        {
            "add": {
                "index": "logs-foo-bar",
                "alias": "alias_2",
                "filter": {
                    "bool": {
                        "filter": [
                            {
                                "term": {
                                    "reaction": "report"
                                }
                            }
                        ]
                    }
                }
            }
        },
        {
            "add": {
                "index": "logs-foo-baz",
                "alias": "alias_2"
            }
        }
    ]
}

GET /_alias/alias_2
```

The output includes the filter duplicated for both data streams, instead of only for the `logs-foo-bar` data stream.

------

Looking into where this is happening in the code, this is due to a couple of blocks of code:

This first is:

https://github.com/elastic/elasticsearch/blob/c43571bbb63ba464bcb92f94b5471eeba7545e87/server/src/main/java/org/elasticsearch/cluster/metadata/DataStreamAlias.java

Where the issue is the `filterUpdated` ends up not being updated if the newly passed in filter is `null` but the previous filter was non-null.

The second part is this function:

https://github.com/elastic/elasticsearch/blob/c43571bbb63ba464bcb92f94b5471eeba7545e87/server/src/main/java/org/elasticsearch/cluster/metadata/DataStreamMetadata.java#L102-L126

Where the data stream aliases are being stored in an `ImmutableOpenMap<String, DataStreamAlias>`, where the key is the alias name. Unfortunately this means that one alias (`alias_2` in the example above) can only refer to a single `DataStreamAlias` instance, and they end up clobbering each other. We'll need to figure out a different way to store this so that we can have multiple `DataStreamAlias` instances (with separate filters) for a single alias name.
