### ISSUE TITLE
[INGEST] New ECS V1 Grok Patterns are Not Available in Elasticsearch

### ISSUE THREAD

**Issue by bvader** [elastic/elasticsearch#92072]
### Elasticsearch Version

8.5.2

### Installed Plugins

None

### Java Version

_bundled_

### OS Version

All

### Problem Description

The new ECS V1 versions of Grok Patterns are not available in Elasticsearch and should be.

https://github.com/elastic/elasticsearch/blob/8.4/libs/grok/src/main/resources/patterns/ecs-v1/java

### Steps to Reproduce

Install 8.5.2 (8.x)

Go to Dev Tools -> Grok Debugger 

Put a sample log 
Sample Log:
`2022-Nov-07 10:15:56 INFO  ADProviderImpl:145 - GetADUser _ start`

Put In Grok Pattern 
`%{CATALINA8_DATESTAMP:log_timestamp}%{SPACE}%{LOGLEVEL:log.level}%{SPACE}%{JAVACLASS:java.log.origin.class.name}:%{INT:java.log.origin.file.line:int} - %{JAVALOGMESSAGE:message}`

Simulate:
Fails with 
`Unable to find pattern [CATALINA8_DATESTAMP] in Grok's pattern dictionary`

That grok pattern exists [here](https://github.com/elastic/elasticsearch/blob/8.4/libs/grok/src/main/resources/patterns/ecs-v1/java#LL18-L18C77) 

The other new Grok patterns such as `CATALINA8_LOG` etc.. etc.. are not available either

If you add the pattern into the custom patterns section the pattern will work 

`CATALINA8_DATESTAMP %{MONTHDAY}-%{MONTH}-%{YEAR} %{HOUR}:%{MINUTE}:%{SECOND}`

Result
```
{
  "log_timestamp": "22-Nov-07 10:15:56",
  "java": {
    "log": {
      "origin": {
        "file": {
          "line": 145
        },
        "class": {
          "name": "ADProviderImpl"
        }
      }
    }
  },
  "message": "GetADUser _ start",
  "log": {
    "level": "INFO"
  }
}
```

The Expected result would be that the Grok Pattern should already exist without having to add it to the custom patterns

**Comment by HiDAl** [comment]
Hi @bvader 

The `ecs-v1` patterns are disabled by default in the Grok Processor. They can be enabled using [the `"ecs_compatibility": "v1"`](https://www.elastic.co/guide/en/elasticsearch/reference/master/grok-processor.html#using-grok) option in the processor (if you use the "Dev Tools > Console"):

> `ecs_compatibility = v1 (enabled)`
<img width="1176" alt="Screenshot 2022-12-22 at 12 26 31" src="https://user-images.githubusercontent.com/284537/209124506-29ef14da-131b-4b7d-ac92-960950672947.png">

> `ecs_compatibility = default (=disabled)`
<img width="1485" alt="Screenshot 2022-12-22 at 12 39 36" src="https://user-images.githubusercontent.com/284537/209126709-ddb2238e-196c-41ae-8100-2824b34f83ba.png">

Since you're using the Grokdebugger, I've checked the Kibana project and [it looks like they neither use the `ecs_compatibility` option](https://github.com/elastic/kibana/blob/main/x-pack/plugins/grokdebugger/server/models/grokdebugger_request/grokdebugger_request.js#L26-L30), when calling the upstream service (our `_ingest/pipeline/_simulate` endpoint) or provide the option within their UI. 

I'll close this issue since we're not the owners of that UI.

thanks
