### ISSUE TITLE
dense vector/embeddings dimension size 

### ISSUE THREAD

**Issue by aykutfirat** [elastic/elasticsearch#92458]
### Description

The latest Open AI embeddings (text-embedding-ada-002) has size 1536. Open AI embeddings are perceived as state of the art and offered at a very good price.

Can you increase the dense vector size so that we can use these kind of models?

Thank you!

**Comment by carloslfu** [comment]
I just got into this limit. For people facing the same limitation [AWS OpenSearch supports 10.000 floats](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/knn.html). Love Elasticsearch Cloud because of its UX but going to AWS for now because my use case, the same as @aykutfirat, requires 1536 floats.

**Comment by carloslfu** [comment]
After digging through the code, I found [https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/index/mapper/vectors/DenseVectorFieldMapper.java#L63] that is a bit confusing. Also, just tried it with version `8.5` and it works like a charm. So, I think this is a documentation mistake, right?

PR: https://github.com/elastic/elasticsearch/pull/46895/files

![Screen Shot 2022-12-29 at 9 38 24 PM](https://user-images.githubusercontent.com/5993168/210028954-28744a02-3ae5-44e8-9f26-2c2d21250d19.png)

**Comment by carloslfu** [comment]
The limit is because Elasticsearch uses the Lucene implementation of it:
```java
  /** The maximum length of a vector */
  public static final int MAX_DIMENSIONS = 1024;
```
Code here: https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/index/VectorValues.java#L33

There is an ongoing discussion on apache/lucene#874 and apache/lucene#11507, but the maintainers look very reluctant to that change.

Elasticsearch can do what OpenSearch did, they implemented multiple engines and let people decide, [docs here](https://opensearch.org/docs/latest/search-plugins/knn/approximate-knn/). This way OpenSearch supports up to 10000 dimensions with the Faiss or nmslib engines, so people can still use the 1024-dims-limited Lucene engine and make their own tradeoffs.

**Comment by mayya-sharipova** [comment]
Addressed by https://github.com/elastic/elasticsearch/pull/95257

**Comment by lubobill1990** [comment]
Elasticsearch's KNN feature is a good choice for query the nearest embedding. Since embedding is the trend, it will be critical to support it in elasticsearch.

**Comment by nik13** [comment]
How to use 2048? Do I need to update my elasticsearch version?

**Comment by benwtrent** [comment]
@nik13 when 8.8 is released, you can specify your dimensions in the mapping up to the limit of 2048.

So, upgrade to 8.8 when it is released.

**Comment by The-Redhat** [comment]
@benwtrent sorry to bother you. Do you know the timeline for the 8.8 release?

**Comment by benwtrent** [comment]
@maxwill9457 https://github.com/elastic/elasticsearch/pull/96850

8.10
