### ISSUE TITLE
Cannot apply index settings when there are no indices

### ISSUE THREAD

**Issue by juergenStuermer** [elastic/elasticsearch#92678]
### Elasticsearch Version

7.10.0

### Java Version

openjdk 11.0.11 2021-04-20

### OS Version

Windows 11

### Problem Description

When applying settings on a cluster which has no indices, I get the following response:
```
$ curl -XPUT "http://localhost:9200/_settings/?pretty=true" -H "Content-Type: application/json" -d '{"index" : {"number_of_replicas" : 0}}'
{
  "error" : {
    "root_cause" : [
      {
        "type" : "index_not_found_exception",
        "reason" : "no such index [null] and no indices exist",
        "resource.type" : "index_expression",
        "resource.id" : "_all"
      }
    ],
    "type" : "index_not_found_exception",
    "reason" : "no such index [null] and no indices exist",
    "resource.type" : "index_expression",
    "resource.id" : "_all"
  },
  "status" : 404
}
```

And therefore, the settings are not stored:
```
$ curl -XGET "http://localhost:9200/_settings"
{}
```
Is this expected?

Apparently, this should be fixed with https://github.com/elastic/elasticsearch/issues/38964 

### Steps to Reproduce

1. have an empty cluster
2. try to apply `curl -XPUT "http://localhost:9200/_settings/?pretty=true" -H "Content-Type: application/json" -d '{"index" : {"number_of_replicas" : 0}}`

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This is the expected behaviour so appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
