### ISSUE TITLE
Does Authentication still need to reference version 6.7.0?

### ISSUE THREAD

**Issue by thecoop** [elastic/elasticsearch#92700]
The `Authentication.VERSION_AUTHENTICATION_TYPE` field references ES version 6.7.0. This is used in the stream protocol.

Do we still need to reference & take account of such an old version?

**Comment by ywangd** [comment]
Unfortunately yes. The authentication header can be serialised as part of job configuration. There can be jobs, e.g. transform, created in an old cluster (6.x) and users expect they keep working after the cluster is upgraded to 8.x. Ideally this should be handled by the migration assistance, e.g. rewrite the header with a newer format before upgrading. But since it is not currently possible, the current decision is to handle the older format in 8.x.

**Comment by thecoop** [comment]
OK, thanks for the info
