### ISSUE TITLE
Gracefully Handle a Node leaving and rejoining a cluster during a snapshot

### ISSUE THREAD

**Issue by BenB196** [elastic/elasticsearch#92728]
## Context

Today, if an Elasticsearch node leaves and rejoins a cluster during a snapshot, any indices on that node that weren't already "completed" in the backup will be marked as "failed", with the error `INTERNAL_SERVER_ERROR: node left the cluster during snapshot`.

## Request

It would be a nice if Elasticsearch could better gracefully handle scenarios where a node leaves a cluster during a snapshot, but then rejoins before the snapshot finishes. While it's not ideal in the first place to have a node leave during a snapshot, there are some cases where it happens, and having the ability for the snapshot to handle this scenario would be nice.

**Comment by DaveCTurner** [comment]
Hi @BenB196, thanks very much for the suggestion. I think you can already achieve this via the `partial` flag - see [these docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/create-snapshot-api.html#create-snapshot-api-request-body) for more information.

Since this is more of a user question than something which needs action here, we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
