### ISSUE TITLE
Invalid call to TransportMessage#decRef in InboundHandler

### ISSUE THREAD

**Issue by scampi** [elastic/elasticsearch#92734]
### Elasticsearch Version

8.7.0 bbb557b2a15f6340c74644785c6f78cf149e6977

### Java Version

_bundled_

### OS Version

Linux 6.1.1

### Problem Description

The `#decRef` method of a request in `InboundHandler` is called one more time than expected. The consequence is that a resource that is closed by a call to `#decRef` may get into an invalid state.

### Steps to Reproduce

See unit test in PR.

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This looks to be a bug in the test you propose rather than anything wrong in the implementation: a `RefCounted` starts with a refcount of 1, but in this test you start from 0. The following assertion verifies that there are never too many `decRef` calls for inbound transport messages that implement meaningful ref-counting, for instance `org.elasticsearch.cluster.coordination.ValidateJoinRequest`:

https://github.com/elastic/elasticsearch/blob/eb8cb109a4cd9f15f046ede132d01c54c5f5ac5a/libs/core/src/main/java/org/elasticsearch/core/AbstractRefCounted.java#L51

Since there's no action for us to take here this appears to be more of a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by scampi** [comment]
@DaveCTurner Do you know of a unit test that access the code below ? I'd like to better understand its usage first before starting a post on the forum (if I still see a need for it!). Thanks

https://github.com/elastic/elasticsearch/blob/bbb557b2a15f6340c74644785c6f78cf149e6977/server/src/main/java/org/elasticsearch/transport/BytesTransportRequest.java#L29-L33
