### ISSUE TITLE
Enable on_script_error on defining runtime fields in a search request.

### ISSUE THREAD

**Issue by tmitanitky** [elastic/elasticsearch#92968]
I'm using 7.14.3 and sorry I'm not sure it is still the case with newer version.

When I tried `on_script_error` on runtime fields in a search request, I got "unknown parameter [on_script_error] on runtime field [xxx] of type [double]".
I suppose it is useful if we can use `on_script_error` parameter also in a search request to ignore errors and get quick view for the runtime field.

related:
https://github.com/elastic/elasticsearch/pull/92380

**Comment by tmitanitky** [comment]
```
GET /some_index/_search
{
  "runtime_mappings": {
    "my_duration": {
      "type": "double",
      "script": {
        "source": """emit(doc['OP_DATE'].value-doc['DEL_DATE'].value)"""
      },
      "on_script_error":"fail"
    }
  }
}
```

**Comment by cbuescher** [comment]
Hi, @tmitanitky the `on_script_error` parameter added in https://github.com/elastic/elasticsearch/pull/92380 will also work for runtime fields defined in a search request. We are not planning on backporting any of this to the 7.x versions though. I'm closing this since its already implemented and will be available with the next minor release.

**Comment by tmitanitky** [comment]
Thank you. I'm planning to update.
