### ISSUE TITLE
Update tcp handshake for transportversion compatibility

### ISSUE THREAD

**Issue by thecoop** [elastic/elasticsearch#93225]
Currently, initial TCP handshakes are done using [version N-1, allowing max compatibility of N-2](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/transport/InboundDecoder.java#L211), before initial version comparisons is done. At the moment, TransportVersion just [calls into the same logic in Version](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/TransportVersion.java#L265), which is not great.

With TransportVersion, on-prem version compatibility is not the only concern, and there really won't be 'minimum compatible versions' in the same way.

What do we do about this? From what I can see, there are several options:

1. Leave it as-is using Version. This will only really matter for on-prem deployments anyway.
2. Lock it off at the first separated TransportVersion (10_000_000), and leave the initial reported version as that forever more. This might make it tricky if we want to change the handshake in the future.
3. Remove the concept of initial handshake version entirely, use a fixed protocol
4. Define some rolling compatibility within TransportVersion itself that is updated when new on-prem versions come out, and use that instead.

Relates #93098
FYI @rjernst @DaveCTurner

**Comment by DaveCTurner** [comment]
My preference is 4.

1. involves an inappropriate relationship between `Version` and the way that bytes are sent over the wire.
2&3. lacks flexibility and I expect it will bite us at some future date. We won't be running tests across versions going all the way back to the first separated `TransportVersion`, and we _will_ want to change this.
4. is explicit, which means we can change it, but also means that any such change would have to be a conscious choice.

In practice I suspect there's not much difference between 3 & 4, because the protocol is effectively fixed today and if ever we did want to change it we'd just be introducing a new "fixed" protocol along with whatever compatibilities shims are needed. But I prefer the explicitness of 4.

**Comment by rjernst** [comment]
I spoke with @Tim-Brooks and we came up with a variation on 3. That is, we think we should have handshake be its own protocol, but we can version it independently of TransportVersion/Version, so that it can still change in the future.

At its core all the handshake protocol is trying to do is send a version. In the past that has been a Version, in the future it will be a TransportVersion. The trickiness is in the format that version is sent through. The current handshake relies on the transport protocol itself, faking out the stream version to be that of an older node. If we fix the handshake format, we can eliminate both the the complexity of determining the version of the stream (that is, no more version picking logic) and simplify what the handshake sends (no need for headers, action name, etc).

@Tim-Brooks please correct anything I misstated.

**Comment by DaveCTurner** [comment]
> we should have handshake be its own protocol ... no need for headers, action name, etc

That sounds good to me too.

**Comment by thecoop** [comment]
We'll need to re-do the handshake protocol then, with backwards-compatibility for connecting to v8/7.17 nodes too

**Comment by DaveCTurner** [comment]
I think we don't really need to do anything to make BwC hard in this area. Here's what a handshake looks like today:

```
45 53                   -- 'ES' marker
00 00 00 31             -- total message length
00 00 00 00 00 00 00 01 -- request ID
08                      -- status flags (0x08 == handshake request)
00 6d 68 33             -- handshake protocol version (0x6d6833 == 7170099)
00 00 00 1a             -- total header length including variable portion of headers
00 00 00                -- variable portion of headers: no request headers, no response headers, no features
16                      -- action string size
69 6e 74 65 72 6e 61 6c }
3a 74 63 70 2f 68 61 6e }- ASCII string `internal:tcp/handshake`
64 73 68 61 6b 65       }
00                      -- parent task ID (no parent task)
04                      -- payload length
c3 f9 eb 03             -- proposed protocol version (vInt: 00000011 11101011 11111001 11000011 == 8060099)
```

The important bit is the `proposed protocol version` in the last few bytes. The `handshake protocol version` bit is the part I think we should explicitly declare rather than computing it from some other inputs. The request ID needs to be copied over into the response. Everything else I think is effectively constant. We could drop it I suppose but that would be quite some work, and I think it'd also be fine to just leave these constant bytes as they are.

This is always the first message received on an inbound channel, so we can know we're reading a handshake just from that fact. At some future point we would then need to split out the parsing of this message so we remain able to read version 7170099 _handshakes_ even though we no longer understand the version 7170099 _transport protocol_. But that doesn't need doing right away I think, only if/when the header format changes, or when we drop support for this transport protocol version.

**Comment by DaveCTurner** [comment]
> Is that in core/infra or distributed?

IMO formalising the notion of "handshake version" (i.e. making it independent of the node version and the transport protocol version) belongs to the project you're currently working on. Adapting the transport layer to parse handshakes differently from other transport messages is more of a distrib-team task, but it doesn't need doing right away.

**Comment by DaveCTurner** [comment]
> This is always the first message received on an inbound channel

Ah actually that's not true. When we open a bundle of channels we only handshake on one of them:

https://github.com/elastic/elasticsearch/blob/416bfcbaed0d3cb878546a0113da33216967671d/server/src/main/java/org/elasticsearch/transport/TcpTransport.java#L1117

Not sure this matters tho, we can still deal with this in the transport layer.

**Comment by DaveCTurner** [comment]
I spotted another wrinkle: today if we fail to process a handshake for some reason and we speak the appropriate protocol version then we send an exception back over the wire. This is tricky because the protocol version in question is the _handshake_ protocol version. This works today because it just so happens that this is the same as the transport protocol today, but when we separate them that won't necessarily work any more. I don't think we should put effort into supporting exceptions in the handshake protocol. Instead, IMO we can drop this functionality and say that if we ever see an exception while processing the handshake we just close the connection and log something.

**Comment by rjernst** [comment]
> Instead, IMO we can drop this functionality and say that if we ever see an exception while processing the handshake we just close the connection and log something

+1. Tim and I also discussed this and I failed to note it above. We could also consider a fixed set of errors in the protocol, but that can be figured out later.

**Comment by Tim-Brooks** [comment]
Generally what Ryan and I discussed yesterday as essentially freezing the handshake with it's own (un-varying) serialization logic and as David pointed out slightly adjusting how handshake errors are propagated (either with a basic exception whose serialization never changes or just closing and logging). 

The biggest outstanding issue for me was if the security team is going to what to auth this request. And that impacts the changes to the headers component. 

Finally, it is fine to either freeze the action name or set the action name to 0 chars as the request itself is dispatched on the status bit and not the action name.

**Comment by DaveCTurner** [comment]
> if the security team is going to what to auth this request

I would rather we didn't. We can protect against some abuse (e.g. bound its size, and reject handshakes sent not as the first message on a channel) but it's going to make things a lot simpler if we can negotiate the protocol version before we start doing security-related things.

**Comment by thecoop** [comment]
Thanks all, I think we have a plan for this now.

**Comment by thecoop** [comment]
Started work on remove transport version from handshakes in https://github.com/elastic/elasticsearch/pull/93312

**Comment by thecoop** [comment]
Work switched to https://github.com/elastic/elasticsearch/pull/93376
