### ISSUE TITLE
Upgrade jna to 5.13.0

### ISSUE THREAD

**Issue by Panxuefeng-loongson** [elastic/elasticsearch#93341]
This issue want to upgrade JNA to 5.10.0. The primary reason for this upgrade is to suppport LoongArch. JNA supports LoongArch from 5.12.0: https://github.com/java-native-access/jna/commit/0066b080d665dc51a41d52263d011f03c7eac9ea. Currently, using elasticsearch on LoongArch results in an error that JNA does not support LoongArch.

**Comment by DaveCTurner** [comment]
> The primary reason for this upgrade is to suppport LoongArch.

This will not in itself add support for a new architecture.

We choose to support particular platforms with care. We test the platform on our CI with our full suite of tests, we create platform specific tests, and our team ensures that every Elasticsearch release works correctly on that platform. Additionally we need to spend time investigating failures on that platform, and making sure performance is acceptable, etc.

Because of the above we generally will not make changes that only target an untested and unsupported platform because we cannot guarantee that the change works, and will continue to work in future releases and we aren't prepared to have code in the repository that we cannot maintain, because it's not tested. It would be a very bad experience for our users if Elasticsearch suddenly stopped working on a particular platform after an upgrade.

Given the above I will close this issue.
