### ISSUE TITLE
Inconsistency in Java time migration guide and documentation

### ISSUE THREAD

**Issue by st4r-fish** [elastic/elasticsearch#93489]
### Elasticsearch Version

8.0

### Java Version

_bundled_

### OS Version

Ubuntu 22.04

### Problem Description

During reading release notes and breaking changes, I stumbled upon this guide: [Java time migration guide | Elasticsearch Guide [8.0] | Elastic](https://www.elastic.co/guide/en/elasticsearch/reference/8.0/migrate-to-java-time.html)

At the [bottom](https://www.elastic.co/guide/en/elasticsearch/reference/8.0/migrate-to-java-time.html#java-time-migrate-update-mappings), it says that the format:
 `yyyy/MM/dd HH:mm:ss||yyyy/MM/dd||epoch_millis`

Should be updated to:
`uuuu/MM/dd HH:mm:ss||uuuu/MM/dd||epoch_millis`

I checked the [current doc](https://www.elastic.co/guide/en/elasticsearch/reference/8.6/date.html#multiple-date-formats) on date formats, I still saw the first format. While the yoda time was deprecated from 7.0, I'm confused if I need to change my mappings and reindexing before the upgrade or not.

[Mark Walkom](https://discuss.elastic.co/u/warkolm) suggested opening a bug report ([discuss link](https://discuss.elastic.co/t/java-time-migration-guide-upgrading-to-es-8-x/323942)).

### Steps to Reproduce

Reading both guides that contradict.

**Comment by abdonpijpelink** [comment]
Thanks for reporting @st4r-fish !

`y` and `u` are both valid literals in Java time. `y` indicates "year of era" and `u` indicates "year". This Stackoverflow answer has a good explanation of the difference between the two: https://stackoverflow.com/questions/29014225

The [recommendation](https://www.elastic.co/guide/en/elasticsearch/reference/8.0/migrate-to-java-time.html#java-time-migration-incompatible-date-formats) is that if you were using `Y` in Joda time to indicate "year of era", you should now use `y` in Java time. And if you were using `y` in Joda time to indicate "year", you should now use `u`.

Nonetheless, because `u` and `y` are both valid in Java time, and behave similar for most use cases, I think the documentation is correct, and I will close this issue.
