### ISSUE TITLE
Will Elasticsearch survive leap second on Jun 30th 2015?

### ISSUE THREAD

**Issue by rtoma** [elastic/elasticsearch#9348]
Jun 30th 2015 will be 1 second longer to correct the clocks.
See http://en.wikipedia.org/wiki/Leap_second

Google and https://github.com/elasticsearch/elasticsearch/issues/1940 tell me the Elasticsearch had issues last time (2012).

I cannot fix a reference to this being fixed.

What will happen? Do we need to shutdown Elasticsearch as a precaution?

Redhat is working on patches tzdata package for the 2015 leapsecond: https://access.redhat.com/articles/15145

**Comment by clintongormley** [comment]
Hi @rtoma 

It wasn't a bug in Elasticsearch, but there was a bug in the JVM and in the Linux kernel which caused problems.  I don't know the status of these bugs, but I would hope they have been fixed by now?

**Comment by jprante** [comment]
@rtoma shutting down Elasticsearch will not help. Here are my recommendations: please take care to use the latest Linux kernel available at the end of June 2015. If you use ntpd, stopping ntpd before leap second insertion and starting ntpd after leap second insertion might help, in case the patched tzdata is not applied. In all cases, rebooting the server will also help to remedy high JVM CPU load.

**Comment by clintongormley** [comment]
Probably the easiest way to test this is to set the time to just before the leap second is supposed to be added, and see what happens.  This of course requires your system to already have an updated tzdata, which I think will not be the case for most systems until closer to the time.

**Comment by jpjp** [comment]
@jprante I think the information you posted is incorrect. If a system uses ntpd, it will receive the leap second from higher stratum servers automatically. If it is not using ntpd, the tzdata update is required. There is no need to stop and start ntpd unless you are running a very old kernel.

**Comment by jprante** [comment]
@jpjp ntpd will only signal the kernel to apply a leap second. The bug is that some kernels do instantaneously perform the system clock change when the leap second event arrives.

I do not know what you mean by "very old kernel". The correct tzdata 2015a appeared in February 2015. Most systems are affected that run unpatched RHEL 6, and also RHEL 7, where a fix is still under development, as noted in https://access.redhat.com/solutions/1379783 

For Debian (Ubuntu), you must run a system which is patched with this tzdata update from February https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=775161 and I think many systems are not patched yet.

Restarting ntpd will always help in case you do not know what to do else to remedy the situation. See also Red Hat leap second guide at https://access.redhat.com/articles/15145 for an overview how systems are affected.

**Comment by jpjp** [comment]
@jprante Yep. Kernels before RHEL6.3's 2.6.32-279.5.2.el6 have the deadlock problem (this kernel is two and a half years old), but anything newer than that doesn't. Newer tzdata is not necessary if you are running ntpd - check the red hat article you link to.

**Comment by jprante** [comment]
If you are unsure, simply run the script at https://access.redhat.com/labs/leapsecond/

It will check for Kernel version and tzdata-2105a, so it covers all conditions.

**Comment by jpjp** [comment]
Yes, that script will check for both: with ntpd and without. But if you run ntpd, you don't need a new tzdata.

**Comment by markwalkom** [comment]
We've now got a blog post with some guidance on this issue - https://www.elastic.co/blog/elasticsearch-2015-leap-second
