### ISSUE TITLE
function score query custom score mode

### ISSUE THREAD

**Issue by ghiron** [elastic/elasticsearch#9352]
Hi, 

is there a way to add a custom score mode in FiltersFunctionScoreQuery (branch 1.4) ?

Currently Es supports First, Avg, Max, Sum, Min, Multiply score mode and I'd like to have a "custom" one (in my case average score mode but with only positive scores).

eg : 

function 1 score : 20  
weight 1   : 10

function 2 score :  -1  
weight 2   :  20

Avg function returns : (20-1)/(20+10) ~ 0.63
I'd like my custom function score returns 20/10 =  2 

Score mode are hard coded in FiltersFunctionScoreQuery and FunctionScoreQueryParser. It looks like not so trivial to had a generic implementation / interface for a custom score mode ...

Any idea ?

Thanks

**Comment by clintongormley** [comment]
There has been no further support shown for this ticket in almost a year.  Rereading it it feels like an edge case that would introduce a lot of complexity to an already complex query, so I'm going to close it.

**Comment by aadmathijssen** [comment]
I needed this feature as well, in my case to combine a negative score with a positive score. The way they should be combined is that the resulting score is between the negative score and 1; the higher the positive score, the more it should approach 1.

A function that can be used for this is the following, where `ns` represents the negative score and `ps` the positive score:

```
ns^2 / (ns^2 + (1/ps) - 1)
```

The only way I can see how this could be added to the Elasticsearch instances, is by adding a server-side script. The downside of this is that the function score queries for obtaining the negative and positive scores should also be encoded inside the script. Also, this introduces the problem of deploying this script to each Elasticsearch instance and updating it whenever the logic changes. 

As a workaround, I have moved the calculation, and the logic to determine whether the negative and/or positive score applies as well, to the application code. The result of the calculation is then added as a  separate field to each document, and field value factor is used to apply the factor in this field to the score. This is not ideal situation, because it requires a full reindex whenever the negative or positive score is changed.
