### ISSUE TITLE
I use the SLM policy, and the start time of the snapshot name is 1 second earlier than the scheduled time of the snapshot policy

### ISSUE THREAD

**Issue by lijianzhi** [elastic/elasticsearch#93679]
### Elasticsearch Version

7.14

### Java Version

openjdk 17.0.5 2022-10-18 LTS

### OS Version

Linux master 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

sunch as I use slm policy to create a snapshot policy plan 0 0 * * *?, The next plan is 12:00, but the actual start time of the snapshot is 11:59:59, one second ahead of schedule. Or 12:00:01, delay 1 second. There are three replicas of esmaster and three data nodes.

### Steps to Reproduce

I use slm policy to create a snapshot policy plan 0 0 * * *?, The next plan is 12:00, but the actual start time of the snapshot is 11:59:59, one second ahead of schedule. Or 12:00:01, delay 1 second. There are three replicas of esmaster and three data nodes.

my server does time synchronization, and I deployed a single node verification, which also caused this problem. The start timestamp of the snapshot is also inconsistent with the scheduling timestamp of the policy

**Comment by dakrone** [comment]
@lijianzhi is this actually causing problems anywhere? Snapshots are invoked in a manner in which they may not always be exactly on the schedule, but I would not expect one second of difference to cause any ill effects?

**Comment by lijianzhi** [comment]
Yes, I have verified a variety of scenarios, all of which are 1 second ahead of time. Then I raised a question to discuss.elastic.co and thanked them for replying that it was caused by the following methods.


 org.elasticsearch.xpack.core.scheduler.SchedulerEngine#clock is the (accurate) java.time.Clock#systemUTC, whereas the snapshot timestamp comes from org.elasticsearch.threadpool.ThreadPool#absoluteTimeInMillis which is updated by org.elasticsearch.threadpool.ThreadPool.CachedTimeThread and therefore by default can be slow by 200ms or more:

`[elastic/elasticsearch/blob/8584d0ee4fd6fc400fbb652560bbda8246e23491/server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java#L411](https://github.com/elastic/elasticsearch/blob/8584d0ee4fd6fc400fbb652560bbda8246e23491/server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java#L411)

        }
        newEntry = SnapshotsInProgress.startedEntry(
            snapshot,
            request.includeGlobalState(),
            request.partial(),
            indexIds,
            CollectionUtils.concatLists(
                indexNameExpressionResolver.dataStreamNames(currentState, request.indicesOptions(), request.indices()),
                systemDataStreamNames
            ),
            **threadPool.absoluteTimeInMillis(),**
            repositoryData.getGenId(),
            shards,
            request.userMetadata(),
            version,
            List.copyOf(featureStates)
        );
        return ClusterState.builder(currentState).putCustom(SnapshotsInProgress.TYPE, snapshots.withAddedEntry(newEntry)).build();
    }

              
    @Override`

**Comment by jbaiera** [comment]
@lijianzhi 

The snapshot process uses the threadpool cached time to avoid excessive querying of system time. I've checked through the usages of the start time on snapshots and have not found any features that depend on its accuracy.

Is the start time for the snapshot being off by +/- 1 second causing functional problems in Elasticsearch? Are you building something where the start time needs to be accurate to the millisecond?

**Comment by lijianzhi** [comment]
@jbaiera
Thank you very much.

**Comment by DaveCTurner** [comment]
@jbaiera FWIW I do kind of think this is a bit of a usability problem. Say you schedule your snapshots at midnight, you would think that you can just look at the date part of the snapshot start time to manage them with simple tools like `curl` and `jq`, but in fact you have to look at the time so as to round to the _nearest_ midnight, which is much harder with simple tools. A similar problem happens if you schedule them every hour on the hour: truncating the time doesn't work, you have to round-to-nearest.

I don't know who owns `SchedulerEngine` but maybe we can consider this a bug in that?

**Comment by dakrone** [comment]
> I don't know who owns `SchedulerEngine` but maybe we can consider this a bug in that?

`SchedulerEngine` was originally part of Watcher until it was extracted and made more generic for use elsewhere, so I think that means we (Data Management) own it.

**Comment by dakrone** [comment]
@DaveCTurner with the scheduler, I think it wouldn't affect this, because the `SnapshotsInProgress.startedEntry(...)` passes in the cached `threadPool.absoluteTimeInMillis()`, which is what could be 200ms off.

Considering that this isn't hot code, could it be changed to be `System.currentTimeMillis()` without tripping an assertion about it being monotonically increasing? I'm not sure if we rely on the snapshot entries using the relative (nano) time or whether "real" time would be okay.

**Comment by jbaiera** [comment]
Should we instead consider setting the timestamp in the snapshot name to be the start time that returns from the schedule calculation instead of the actual time that the snapshot executes on? That way if you schedule a snapshot to run at `00:00:00` the date on it will actually contain `00:00:00` instead of a possible `23:59:59` or `00:00:01`?

**Comment by DaveCTurner** [comment]
> Considering that this isn't hot code, could it be changed to be `System.currentTimeMillis()` without tripping an assertion about it being monotonically increasing? I'm not sure if we rely on the snapshot entries using the relative (nano) time or whether "real" time would be okay.

`threadPool.absoluteTimeInMillis()` is about as non-monotonic as `System.currentTimeMillis()` so that's not a concern, but we do have quite a few tests which run snapshots on a fake threadpool via which we inject a fake time so I wouldn't want to lose this indirection. I suppose we could introduce `ThreadPool#rawAbsoluteTimeInMillis` (cf. ThreadPool#rawRelativeTimeInMillis`), but I'd prefer that we consider migrating `SchedulerEngine` to use the time (and scheduling) facilities on `ThreadPool` instead.
