### ISSUE TITLE
`elastic / elasticsearch # main - unix compatibility » amazon-2&&immutable #654` results in 404

### ISSUE THREAD

**Issue by n1v0lg** [elastic/elasticsearch#93683]
### CI Link

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+main+multijob+platform-support-unix/os=amazon-2&amp;&amp;immutable/654/

### Repro line

Go to https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+main+multijob+platform-support-unix/os=amazon-2&amp;&amp;immutable/654/ 

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

It isn't a test failure per se; the issue is that the URL to the failure is malformed. It looks like we included `;` in the job name which is not allowed.

To reproduce, simply visit the CI link, and you'll get:

`HTTP ERROR 400 Semicolons are not allowed in the request URI`

**Comment by mark-vieira** [comment]
The issue here is Slack is changing these URLs and reencoding `&` as `&amp;`. I've tried every method of encoding available it still does the same thing and Jenkins simply doesn't like it. One option I've thought of is changing these jenkins agent labels to avoid the `&`s so we simply never have links with that character.

**Comment by n1v0lg** [comment]
For anyone who lands on this in the future: *to get the correct URL just replace all `&amp;` with `&`.
