### ISSUE TITLE
Type qualification within children aggregations

### ISSUE THREAD

**Issue by perryn** [elastic/elasticsearch#9393]
Hi there,

I'm working with child aggregations and have found some points of confusion

1) The documentation isn't clear on when and if you need to qualify references to fields within a children aggregation with the type of the child documents. It is shown being done in the guide: ("field": "employee.hobby") 

http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/children-agg.html

but not in the reference ("field": "owner.display_name")

http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-aggregations-bucket-children-aggregation.html

It would be good if the documentation were clearer on this point.

2) In my case, I apparently needed to put the type qualification in. If I don't, I get an error that is not particularly helpful in diagnosing the problem:

    org.elasticsearch.ElasticsearchIllegalStateException: Invalid context - aggregation must use addResults() to collect child results

It would be good if the error were more 'user facing'

3) Lastly the need for type qualification lead me to suspect that I could sub-aggregate (below the children aggregation) based of fields from the parent. This doesn't seem to be the case, so perhaps it would be less confusing all round to not require type qualification at all (since it can only be one type anyway)

Happy to help out with pull requests if someone can give me some guidance

cheers

**Comment by clintongormley** [comment]
Hi @perryn 

The answer is: it depends :(

If you include the type name in the URL, then yes you do need to specify the type name in the field path.  Otherwise you don't.  This ambiguity will be cleaned up by #8870.

In the meantime I agree that that error should be made friendlier.  /cc @martijnvg

**Comment by martijnvg** [comment]
@perryn The use of type qualification is needed in the case the type is set on the search request. Basically the type sets the scope the search request operates in. I guess you set this to the parent type, so when not specifying the child type it couldn't a field you would like to use because it doesn't exist in the context of the parent type.

You should be able the create sub aggregations under the children aggregations that operates on buckets that come from the parent space. This is what the `children` aggregator does, it pushed buckets from the parent space into the children space.

**Comment by perryn** [comment]
Hi @martijnvg 

You are right I was performing a search on the parent type.  That explains why I need to qualify fields from the child type, but it also implies to me that I *can* use fields from the parent type. What I am seeing is that I can only use fields from the child type *and* I must qualify them too.

I am not sure if your second paragraph is saying this is expected or not?

 To be clear, what I am trying to do is

- children aggregation
  - date_histogram agg using timestamp field from child type
    - terms agg using string field from parent type 
      - sum agg using number field from child type

What I am seeing is that the terms aggregation creates 0 buckets.

**Comment by martijnvg** [comment]
@perryn What you're seeing is expected. The aggregations wrapped in the `children` aggregations can't refer to any parent type field. I was referring to how fields are resolved in general from the mappings. So in your case with the correct type prefix the correct field was resolved, but no documents would pass through the `terms` agg, because child docs don't have the defined field.

However buckets created on the parent level can be pushed in the child space. For example if you define something like this:
- `terms` agg using string field from parent type
   - `children` agg
      - `date_histogram` agg using timestamp field from child type
         - `sum` agg using number field from child type
 
Then `terms` agg buckets can connect to the buckets created by the `date_histogram` via the `children` aggregation. 

The example you shared would be possible if there was a `parent` aggregation:
- `children` aggregation
  - `date_histogram` agg using timestamp field from child type
    - `parent` aggregation
      - `terms` agg using string field from parent type 
        - `sum` agg using number field from child type

The parent aggregation doesn't exist yet.

**Comment by perryn** [comment]
Hi @martijnvg,

Thanks for taking the time to clear that up :).

 I think this issue can be reduced to 'provide a more illuminating error message' . I am happy to have a crack at it if you would like - I presume there is more to it than changing the error string in AggregatorFactory?

**Comment by clintongormley** [comment]
This ambiguity has been cleared up by #8870, and I've opened https://github.com/elastic/elasticsearch-definitive-guide/issues/449 to fix the guide docs

**Comment by tj** [comment]
woah confusing error message. I just had a typo in the field name for date_histogram and got the "aggregation must use addResults() to collect child" bit
