### ISSUE TITLE
Refactor security uses of Version.transportVersion

### ISSUE THREAD

**Issue by thecoop** [elastic/elasticsearch#93963]
Refactor security-related uses of `Version.transportVersion` for serialisation to not use that.

Affected classes:
* ClientHelper
* TokenMetadata
* TokenService

**Comment by thecoop** [comment]
For `ClientHelper`, this is using `transportVersion` for `maybeRewriteAuthenticationHeadersForVersion`, based on the node minversion. This is not a safe thing to do.

**Comment by thecoop** [comment]
Tokens have an associated transportversion - what's this for?

**Comment by gwbrown** [comment]
> Tokens have an associated transportversion - what's this for?

I started looking for the answer to this question and found that the code was originally written to use `Version` and changed to use `TransportVersion` in [this PR](https://github.com/elastic/elasticsearch/pull/93089/files#diff-3b282099019ee86ee408291eee2fae37e2ba2942256c3e57bfdbe310e18626fd) by @pgomulka without review from the Security team. So I don't actually know why tokens are using `TransportVersion` instead of `Version` - maybe @pgomulka can comment? 

The same is true of ClientHelper - it was [changed in the same PR](https://github.com/elastic/elasticsearch/pull/93089/files#diff-7ca17eb13b5b2211392c3a872d86328fabc8f78e4dd0ce25e8023f2e5e47a878), it appears without input from the Security team.

**Comment by pgomulka** [comment]
#93089 was part of bigger refactoring https://github.com/elastic/elasticsearch/issues/93098 where simple use cases of Version being used for de/serialisation can be replaced with a TransportVersion. There is no change of behaviour as Version have an asossiated TransportVersion. We also discussed this offline with @albertzaharovits (cc)

@thecop is now working on a split between Version and TransportVersion, so it is easier to upgrade versions.

I suspect @thecoop is asking if these affected classes could be rewriten without the Version/TransportVersion at all? Can you confirm/clarify?

**Comment by gwbrown** [comment]
Thanks for the clarification @pgomulka, I appear to have misinterpreted the ask pretty badly here, my apologies. That said, it is still unclear to me exactly what the request here is, though the suggestion above sounds like a reasonable interpretation to me.

Assuming that's true, what are our specific goals in getting rid of the TransportVersion usage? While I'm not extensively familiar with the tokens code, from some internal discussions and poking through the code it looks like this version is primarily used to translate authentication objects between versions. If not `Version` or `TransportVersion`, how should we be varying behavior based on e.g. creation version of an object or the mixed cluster version?

It's also stored in documents (though not serialized as in `writeTo`, just as an integer field in a JSON doc), so we'll need some way to translate from old school integer version IDs to whatever we should be using.

> For ClientHelper, this is using transportVersion for maybeRewriteAuthenticationHeadersForVersion, based on the node minversion. This is not a safe thing to do.

Could you expand on that please?

**Comment by thecoop** [comment]
So the aim here is that we are separating `Version` and `TransportVersion`, to make the transport version (aiming specifically at upcoming cloud deployments) completely separate to on-prem node versions. The `Version.transportVersion` field is a link between those two classes, which makes upgrading/modifying `Version` or `TransportVersion` on version upgrades & new transport versions much more complicated than it should be.

We are aiming to remove the `transportVersion` field. It is used in various places in the security code to go from 'minimum active node version' to 'serialisation version'. The question here is, is there a way to completely separate the serialisation version & node version in this code, to remove the `transportVersion` field?

**Comment by thecoop** [comment]
>>For ClientHelper, this is using transportVersion for maybeRewriteAuthenticationHeadersForVersion, based on the node minversion. This is not a safe thing to do.

>Could you expand on that please?

Apologies, this was a misunderstanding on my part. I've edited it.

**Comment by tvernum** [comment]
Let's restrict ourselves to 1 example for now so that we can talk specific rather than making general statements. Once we've work out that 1 example we can see if the answer applies to the other case.

I've picked [ClientHelper](https://github.com/elastic/elasticsearch/blob/da01691a994da5c814cedc20884a70940331e781/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ClientHelper.java#L92-L98), since it's been mentioned frequently in this issue. 
 
> The question here is, is there a way to completely separate the serialisation version & node version in this code, to remove the transportVersion field?

The code is attempting to determine _What is the maximum `TransportVersion` that can be safely understood by all nodes in the cluster_? so that it can (if necessary) re-serialize a piece of data (the `Authentication` object) into a backwards compatible format.

If we are removing the `transportVersion` field from the node Version, then how do we know what `TransportVersion` the cluster (as a whole) can work in?

**Comment by pgomulka** [comment]
to add an extra bit of colour - the idea of removing `TransportVersion` (and `Version`) from Node comes from https://github.com/elastic/elasticsearch/pull/93822 
The `TransportVersion` which is meant ot replace `Version` in the transport protocol contexts. 
However `Version` is also used in non transport protocol use cases, like https://github.com/elastic/elasticsearch/blob/da01691a994da5c814cedc20884a70940331e781/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ClientHelper.java#L160 I like to think about those as 'version specific feature flags'
The initial idea was simply replace `Version` with `TransportVersion` on DiscoveryNode https://github.com/elastic/elasticsearch/pull/93818 but during the review it was concluded that `TransportVersion` should be a property of a transport connection and limited to the transport protocol use case. I wonder if @DaveCTurner could give us more context?

I personally wouldn't mind keep on using `TransportVersion` for those 'version specific feature flags' as well as for transport protocol serialisation. The **Transport**Version name might be a bit unfortunate in this case

some more context on /ES-5599

**Comment by thecoop** [comment]
So I think there's a couple of ways we could go about this.

1. Leave as-is, inferring the transport version from node version. This is not great, especially since transport version is going to become separate to node version. This will cause more and more problems in the future.
2. Introduce the concept of 'min/max transport version supported by all known connections' in the infrastructure somewhere, that we then need to plumb through to places like this
3. Refactor this & other uses to use their own serialisation mechanism, independent of transport & stream input/output

**Comment by tvernum** [comment]
> There is no need for us to find the maximum here. Any universally-understood version will do.

I don't follow why that would be true.  
If we serialize into an older-than-current version, we are likely lose something - `TransportVersion` moves forward because new fields are added. If there are three transport versions `S` < `T` < `U` then, there is something that is serialized in `T` that is not in `S` and something that is serialized in `U` that is not in `S` or `T`. If we pick one of those versions at random, and use it as a serialization format, then we risk transporting less information than we could have, and that has consequences.  
Those consequences are acceptable - they must be because we have declared that the cluster is willing to operate on `S` - but they still exist.

And, in this particular case there's a performance impact. We only re-serialize if we know we need to support an older transport-version. In normal operation we skip that work altogether.

I supposed we could always write the header using the barrier version, but then we're accepting that it takes many releases before we can pass new fields between nodes - we need the barrier-version to reach the oldest transport-version that supports the field which will be several releases after the field was added. We don't seem to do that for transport connections, so I don't think we should force that restriction onto other cross-node data.

**Comment by tvernum** [comment]
> If we did, we would need to implement a version barrier based on the transport version, preventing from joining any nodes that speak transport versions older than the barrier version.

Surely we do need such a thing. It is not reasonable for a 3 year old node to join a cluster with the current transport version. If there is no barrier, then the set of possible versions that need to be tested and supported together becomes unreasonably large.

**Comment by tvernum** [comment]
> Refactor this & other uses to use their own serialisation mechanism, independent of transport & stream input/output

This may be reasonable, but it won't solve the problem. You still need a mechanism to know which nodes are in the cluster and how to serialize into a format that they accept. It might not be `TransportVersion` anymore, but it's something.

The problem we are trying to solve is that a version of ES released on day X needs to be compatible with every unversioned (serverless) build that might be deployed (roughly, anything built in the last month) plus every versioned (downloadable) build within the same major (which could be 2 years old). We're trying to implement a protocol that makes that feasible. 

In the `ClientHelper` case, the issue is that an `Authentication` object is passed between nodes using a header. It must be passed in a format that the receiving node can understand. Whether that uses `TransportVersion` or `SomeOtherVersion`, it still needs to pick a format based on the cluster membership. The only other alternative I can come up with, is that we never change serialization formats, never add new fields, and `Authentication` is stuck with the current format forever.

**Comment by DaveCTurner** [comment]
> Those consequences are acceptable - they must be because we have declared that the cluster is willing to operate on S - but they still exist.

I agree there are consequences, but this seems to be agreeing with my claim that any universally-understood version will suffice.

> Surely we do need such a thing [i.e. implement a version barrier]

I think we do not want a barrier in today's sense: a lower bound on version _determined dynamically by observing the current set of nodes in the cluster_. It's awfully fragile. But yes we do need to be able to impose some bounds on the transport versions we consider to be acceptable (i.e. this is built into the "universally-understood" qualifier in my claim). IMO those bounds should be determined statically based on some to-be-determined policy on the retirement of older versions.

**Comment by DaveCTurner** [comment]
> I supposed we could always write the header using the barrier version, but then we're accepting that it takes many releases before we can pass new fields between nodes - we need the barrier-version to reach the oldest transport-version that supports the field which will be several releases after the field was added. We don't seem to do that for transport connections, so I don't think we should force that restriction onto other cross-node data.

The difference is that transport traffic is completely ephemeral, so we can negotiate the protocol version prior to transmission. `ClientHelper` is persisting data for deserialization by some as-yet-unknown version in future. This is kind of an abuse of the transport protocol because of exactly this difficulty. In most places we use XContent for this, and XContent is much more appropriate because it is version-independent and permits a format which evolves independently of the transport protocol.

**Comment by tvernum** [comment]
I had missed that this was the code that was storing headers for the future (there's another version that re-writes the headers for transmission within the cluster).

The whole model of persisting the threadcontext (or in fact, a subset of it) so that tasks can be run in the future is incredible fragile and ought be to replaced, but that would be a massive yak to shave.

> I think we do not want a barrier in today's sense: a lower bound on version determined dynamically by observing the current set of nodes in the cluster. It's awfully fragile.

It's certainly fragile, but seems unrelated to the task at hand - nothing about the work to break out `TransportVersion` changes the premise that a cluster always moves forward and never supports adding in an older version.  
The issue that we're introducing is that we have to be more precise about what sort of "version" we mean when we talk about an older version, but the core assumption of _versions always move forwards_ isn't changed.

**Comment by DaveCTurner** [comment]
> It's certainly fragile, but seems unrelated to the task at hand

We will need to do some development work to adjust the dynamic barrier to work in terms of `TransportVersion`.

> The issue that we're introducing is that we have to be more precise about what sort of "version" we mean when we talk about an older version, but the core assumption of _versions always move forwards isn't changed_.

I'm not sure this is true - we have discussed a need for some (limited) support for downgrades, and a strict version barrier on transport versions would prevent that. This needs some wider discussion.

**Comment by thecoop** [comment]
In lieu of having those wider discussions and to fix the immediate problem, I've created https://github.com/elastic/elasticsearch/pull/94157 that creates a Connection/TransportVersion counterpart to DiscoveryNodes.getMinNodeVersion, that will allow core infra to make progress on the immediate blocker here.

**Comment by thecoop** [comment]
However, this will not aid with `TokenMetadata`, which is based on compatible index versions:

`Version.CURRENT.minimumIndexCompatibilityVersion().transportVersion`

What are the requirements around compatible versions for `TokenMetadata`? Why does it use the index version? Looks like this was first introduced in a3aacc359f98953f444719a50522fc217cbf014a

**Comment by ywangd** [comment]
I am fairly sure `TokenMetadata` should use `Version.CURRENT.minimumCompatibilityVersion()` just like most other custom metadata classes and be replaced with `TransportVersion.MINIMUM_COMPATIBLE`. It is dead code so it was not updated in the first place.

**Comment by thecoop** [comment]
Created #94454 to change use in TokenMetadata

**Comment by thecoop** [comment]
Created #94860 to migrate to the new getMinTransportVersion cluster state method
