### ISSUE TITLE
[Ingest][Processor] Add ability to decode base64 encoded data. 

### ISSUE THREAD

**Issue by vinit-chauhan** [elastic/elasticsearch#94007]
### Description

In Some of the APIs, It has been seen that the data is encoded in base64 format. And there's no straightforward way to decode the value.  

`{"data": "eyJzZWNyZXRfdXNlciI6ImFkbWluIiwgImhvd190b19nb190b19zZWNyZXRfcHJvdGFsIjoiaHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1kUXc0dzlXZ1hjUSJ9"}`

This Issue here is to request an enhancement in the ingest processor list to make it more streamlined to decode such responses.

**Comment by HiDAl** [comment]
Hello @vinit-chauhan 

First, thanks for reporting this issue. 

Well, I have reviewed your requirement and I can say that we do have support for handling base64 strings. In the following snippet you can see how to use the already available APIs:

```
POST _ingest/pipeline/_simulate
{
  "pipeline": {
    "processors": [
      {
        "script": {
          "source": """
          ctx.decoded_field = ctx.base64_encoded.decodeBase64();
          """
        }
      },
      {
        "script": {
          "source": """
          ctx.reencoded_field = ctx.decoded_field.encodeBase64();
          """
        }
      }
    ]
  },
  "docs": [
    {
      "_source": {
        "base64_encoded": "SGVsbG8gdGhpcyBpcyBhIHRlc3Qgb2YgYmFzZTY0Cg=="
      }
    }
    ]
}

{
  "docs": [
    {
      "doc": {
        "_index": "_index",
        "_id": "_id",
        "_version": "-3",
        "_source": {
          "base64_encoded": "SGVsbG8gdGhpcyBpcyBhIHRlc3Qgb2YgYmFzZTY0Cg==",
          "decoded_field": """Hello this is a test of base64
""",
          "reencoded_field": "SGVsbG8gdGhpcyBpcyBhIHRlc3Qgb2YgYmFzZTY0Cg=="
        },
        "_ingest": {
          "timestamp": "2023-02-24T14:36:14.829635026Z"
        }
      }
    }
  ]
}
```

As you could see using `ctx.<field>.(encode|decode)Base64()` methods you can easily convert any string in your documents. Here is available [the documentation for these methods from ingest processors perspective](https://www.elastic.co/guide/en/elasticsearch/painless/current/painless-api-reference-ingest-java-lang.html) and [here](https://www.elastic.co/guide/en/elasticsearch/painless/current/painless-api-reference-shared-java-util.html#painless-api-reference-shared-Base64) a more generic documentation about Painless scripting APIs.

We have internally discussed the option of having a specific processor to convert base64 strings (just like you coded in #94008, Thank you so much for it!), and we agreed that having a custom processor is a bit cumbersome, because there's already a one-line option of making this transformation. On the other hand, we have agreed on improving our documentation with examples of common use cases like this one (issue #94125). 

Again, thank you so much for reporting this issue and creating the PR.

Cheers

**Comment by vinit-chauhan** [comment]
Thanks @HiDAl - for the explanation. Couldn't agree with you more. And Thanks for creating another issue for the docs. 
Have a good one, Cheers! 🥂 😄
