### ISSUE TITLE
Error while building from source

### ISSUE THREAD

**Issue by ruthwik3690** [elastic/elasticsearch#94446]
The command : `./gradlew :distribution:archives:linux-tar:assemble` gave out the following error
```
Could not determine the dependencies of task ':x-pack:plugin:ml:bundlePlugin'.
> Could not resolve all task dependencies for configuration ':x-pack:plugin:ml:nativeBundle'.
   > Could not find org.elasticsearch.ml:ml-cpp:7.17.9-SNAPSHOT.
     Searched in the following locations:
       - https://artifacts-snapshot.elastic.co/ml-cpp/7.17.9-SNAPSHOT/downloads/ml-cpp/ml-cpp-7.17.9-SNAPSHOT.zip
     Required by:
         project :x-pack:plugin:ml
```

Please help me out with the solution/workaround for this issue, I want to build this particular 7.17.9 version only.

**Comment by droberts195** [comment]
The ML artifacts are stored on GCS for 30 days and on S3 forever. You are trying to build a version that hasn't been supported for more than 30 days, hence the artifacts are no longer on GCS.

To get the ML artifacts from S3 instead of GCS you would need to create a branch off of the `v7.17.9` tag and backport https://github.com/elastic/elasticsearch/pull/92381 onto that branch. Then build off the branch and you should end up with the 7.17.9 product build using a very slightly altered build system.

I don't think the backport will be a simple clean cherry-pick, because the automation on the original PR attempted that and it didn't work. Hopefully it won't be too hard to resolve the conflicts though. However, since you are working on an unsupported version we're unable to help you more than giving this high level advice.

**Comment by ruthwik3690** [comment]
for anyone who wants to build an older version of elastic search it isn't smooth you say 😐

FYI, i just want to build the latest version (8.6.2) but there's a condition which is put up by your team itself : https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html
i.e to upgrade to 8.6.2, we need to upgrade to 7.17 version first, then we can move on to 8.6.2.
due to which i wanted to upgrade to version 7.17.9.

**Comment by droberts195** [comment]
The version under development on the 7.17 branch is 7.17.10. Most people building the 7.17 branch from source would just build the latest code, which would give them a 7.17.10 build.

It should be possible to upgrade from older 7.x through 7.17.10 to 8.x. Once 7.17.10 is released that will be the recommended approach. It _should_ work now, but obviously there are no guarantees until 7.17.10 is officially released.

Going via 7.17.9 is the supported route for people who are running the released software.

You seem to be in the rare situation of wanting to build from source, yet follow the guidance for downloaded releases.

**Comment by ruthwik3690** [comment]
do you have a rough estimate on when 7.17.10 gonna be released?

**Comment by ruthwik3690** [comment]
please let me know if there is any proposed/expected date for 7.17.10.
Thanks

**Comment by mark-vieira** [comment]
Closing this as 7.17.10 is now released and we aren't supporting building older, unmaintained versions from source.
