### ISSUE TITLE
/_aliases remove action ignores must_exist when alias is missing

### ISSUE THREAD

**Issue by lastnico** [elastic/elasticsearch#94478]
### Elasticsearch Version

8.6.0

### Java Version

_bundled_

### OS Version

Linux 5.19.0-35-generic #36-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 3 18:36:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

If I try to perform a single "remove" action with "must_exist": false on the /_aliases endpoint, I still receive an HTTP 404 response with "type": "aliases_not_found_exception".

This seems to contradict documentation of the [/aliases](https://www.elastic.co/guide/en/elasticsearch/reference/8.6/indices-aliases.html) API 

>  must_exist
>     (Optional, Boolean) If true, the alias must exist to perform the action. Defaults to false. Only the remove action supports this parameter. 

### Steps to Reproduce

[ ] Create index new_index

```
PUT /new_index
{}
```

[ ] Try to remove a missing some_alias on new_index index

```
POST _aliases
{
  "actions": [
    {
      "remove": {
        "index": "new_index",
        "alias": "some_alias",
        "must_exist": false
      }
    }
  ]
}
```

[ ] This will lead to the following error:
```
{
  "error": {
    "root_cause": [
      {
        "type": "aliases_not_found_exception",
        "reason": "aliases [some_alias] missing",
        "resource.type": "aliases",
        "resource.id": "some_alias"
      }
    ],
    "type": "aliases_not_found_exception",
    "reason": "aliases [some_alias] missing",
    "resource.type": "aliases",
    "resource.id": "some_alias"
  },
  "status": 404
}
```

**Comment by parkertimmins** [comment]
After some thought, I think we should continue to return 404 on removal on non-existing aliases if `must_exist==false`. Rather than making the change in this ticket, the docs should be updated to indicate that the `must_exist` argument affects the atomicity of applying a list of actions. Additionally, the phrase "single atomic operation" in the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html), should probably be updated to clarify that the option is only atomic if `must_exist==true`.

This is my reasoning: 

- `DELETE /some_index/_alias/non_existing_alias` returns 404, as it should.
- The following list of actions with a single remove should be expected to behave the same as the above DELETE . More pragmatically, these share the same removal code, and it would be better to keep them as the same code.
```
POST _aliases
{
  "actions": [
    {
      "remove": {
        "index": "some_index",
        "alias": "non_existing_alias"
      }
    }
  ]
}
```

- Though it might make sense to return 200 if `must_exist==false`, this is the default case, so returning 200 for `must_exist==false` also requires returning 200 in the above case where the `must_exist` argument is absent.
- Silently failing in the default case seems undesired.
