### ISSUE TITLE
Documentation about file realm is confusing

### ISSUE THREAD

**Issue by lhirlimann** [elastic/elasticsearch#94658]
### Elasticsearch Version

8.6

### Java Version

_bundled_

### OS Version

Linux

### Problem Description

Documentation at https://www.elastic.co/guide/en/elasticsearch/reference/8.6/file-realm.html#file-realm-configuration is a bit confusing on how to use the file realm it says both : 
- `To use the file realm you must explicitly include it in the realm chain`
- `The file realm is added to the realm chain by default. You don't need to explicitly configure a file realm.`

Can we clarify which one is correct?

### Steps to Reproduce

Read the documentation and try to figure out how to add a file realm.

**Comment by tailorzed** [comment]
May we add the content from [here](https://medium.com/@stefnestor/elasticsearch-file-based-realm-2508ff0e5de2)?

**Comment by abdonpijpelink** [comment]
Thanks for sharing @gemaliano ! I can make the necessary changes to the 8.x docs (file realm is added by default) and 7.x docs (file realm needs to be explicitly added).

**Comment by ywangd** [comment]
Thanks for spotting this inconsistency. I can confirm @gemaliano is right. To recapture, for both file and native realms
**8.x** 
* They are always added to the realm chain unless explicitly disabled
* User can configure the `order` for these realms. Otherwise they are always added to the beginning of the realm chain (file then native)

**7.x**
* They are added to the realm chain only when no effective realms are configured at all
* Effective realm means the realm is explicitly configured, enabled and allowed by the cluster's license
* If any effective realm is configured, to use `file` or `native` realm, the user must explicilty configure them.

**Comment by abdonpijpelink** [comment]
This has been fixed in https://github.com/elastic/elasticsearch/pull/94778 and https://github.com/elastic/elasticsearch/pull/94777
