### ISSUE TITLE
JDK 20 upgrade has broken APM tracing

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#94689]
In PR #94600, we upgraded the bundled JDK to 20. However, it now appears that running ES with JDK 20 breaks APM tracing. JVM metrics are still reported, but no spans appear.

   * @jamesspi reported that he couldn't see traces in Kibana after configuring APM on a branch.
   * I tried configuring APM using the 8.6.2 distribution from the website, and it worked as expected
   * I then tried the branch above, and no spans were reported
   * I tried `main`, same thing.
   * I tried the `8.7` branch, same thing
   * I reverted commit 3b79a4fd3b62a27a84cf18cc5846a10145ce87b0 locally, to downgrade to JDK 19, and now spans were show in Kibana.

**Comment by pugnascotia** [comment]
I'm not aware of any particular reliance internally. We've only recently reached the point of full distributed tracing in QA, and the capability is not trivially accessed. It's not a disaster if it isn't available for a period of time, though it's concerning that the JDK upgrade had such an impact that went unnoticed.

**Comment by mark-vieira** [comment]
> It's not a disaster if it isn't available for a period of time, though it's concerning that the JDK upgrade had such an impact that went unnoticed.

For now we are going to revert while we assess the actual impact of this. It's not obvious to me that the APM agent supports Java 20. The docs only show support for LTS versions up to 17 so the fact it worked on Java 19 might very well have been coincidence.

APM integration in ES just frankly isn't a first-class citizen and we need to figure out what the future support for it is gonna be.

**Comment by JonasKunz** [comment]
Hi from @elastic/apm-agent-java ,

Though not officially stated on the supported technologies page, we always run our agent test suite against the currently latest JDK version as well. However, because JDK 20 was just released three days ago, we didn't upgrade our setup from 19 to 20 yet. Turns out this will take a bit more time to setup, because JDK 20 does not support compiling to Java 7 bytecode anymore, which we still have to support.

Nonetheless, I was able to successfully run our test suite with a few tricks locally using JDK 20, so the agent should actually support JDK 20. I also tried locally with a small test application and was able to receive traces without problems.

I think the best way to progress would be if you could provide us with [debug logs](https://www.elastic.co/guide/en/apm/agent/java/current/trouble-shooting.html#trouble-shooting-logging-procedure) from the agent running in your JDK 20 setup, so that we can maybe spot there why exactly you are not receiving any traces. It is especially strange that metrics are reported while traces are note.

**Comment by pugnascotia** [comment]
I did observe that metrics were being reported successfully to the APM server, but not spans. We use the OTel API in Elasticsearch, so maybe the way in which the agent installs itself over the OTel API's default no-op span collector broken somehow?

**Comment by JonasKunz** [comment]
The Otel usecase is also covered by our test suite. In addition I just did some manual testing with Otel and our agent on JDK 20, works fine there as well. I think we really need the logs, otherwise it's hard to narrow down the root cause.

**Comment by AlexanderWert** [comment]
@pugnascotia We found the problem, @SylvainJuge will summarize the findings in more detail. In short: we need to update to APM Agent version 1.36.0.

**Comment by SylvainJuge** [comment]
I've just opened a draft PR to update the agent : https://github.com/elastic/elasticsearch/pull/94716

**Comment by mark-vieira** [comment]
> Though not officially stated on the supported technologies page, we always run our agent test suite against the currently latest JDK version as well. However, because JDK 20 was just released three days ago, we didn't upgrade our setup from 19 to 20 yet. Turns out this will take a bit more time to setup, because JDK 20 does not support compiling to Java 7 bytecode anymore, which we still have to support.

Thanks @JonasKunz. On the ES side we always ship with the latest available JDK. We start testing on early access builds as soon as they're available so as soon as a new Java release goes GA we bump the bundled JDK in Elasticsearch. This is necessary since with non-LTS releases the old version go EOL as soon as a new one goes GA.

We may want to considering doing some proactive testing with APM as well given we now bundle it in ES. We're also looking to get our own APM integration test suite running again. It started failing awhile back and has been muted ever since 😢

**Comment by JonasKunz** [comment]
> We start testing on early access builds as soon as they're available so as soon as a new Java release goes GA we bump the bundled JDK in Elasticsearch. This is necessary since with non-LTS releases the old version go EOL as soon as a new one goes GA.

I think this would be a good strategy for us to test the APM Agent too and to avoid future potential problems. I'll take it to the team for discussion.
