### ISSUE TITLE
Upgrade forbiddenapis Gradle plugin to 3.5.1

### ISSUE THREAD

**Issue by uschindler** [elastic/elasticsearch#94773]
### Description

The new version was released a minute ago: https://github.com/policeman-tools/forbidden-apis/wiki/Changes#version-35-released-2023-03-27

Summary of relevant changes for Elasticsearch:
- Faster startup time as Gradle plugin initialization was compiled statically and is part of JAR file
- Support for Java 20 signatures and bytecode of Java 21

I have no time to submit PR (and don't want to due to legal reasons => no open source license). So this is for informative purposes only.

**Comment by mark-vieira** [comment]
@uschindler we do this so that ignoring missing classes is explicit. Essentially, if someone adds a new dependency which references missing classes we want that to be known and either a) add them as exclusions (for example of those classes are only needed by a feature we don't use) or b) fix our dependencies to bring in the dependency that provides those missing classes.

I think parsing the summary at the end is fine. As long as each missing class is logged at least once that satisfies our use case. I'll see about updating our parsing logic to support the new format.

**Comment by uschindler** [comment]
If you want me to add DEBUG logging to the CLI tool, just open an issue on forbiddenapis referring to my above description. I can quickly release a bugfix version 3.5.1, so you won't have to wait till Java 21.

**Comment by mark-vieira** [comment]
> So to me it looks like you are misusing forbiddenapis

That is accurate 😉 



> An alternative would be to create your own ASM parser scanning class files (actually thats not too much work, you just need to add a listener that triggers at right places for class names). Or even better scan through the constant pool of classes with another library (there are some) to collect all references from it.

That's certainly possible, but this class parsing is expensive, especially with large classpaths, so since forbidden APIs already has to do this for it's purposes are simply taking advantage of this.

> If you want me to add DEBUG logging to the CLI tool, just open an issue on forbiddenapis referring to my above description. I can quickly release a bugfix version 3.5.1, so you won't have to wait till Java 21.

Thanks, @uschindler! I've opened https://github.com/policeman-tools/forbidden-apis/issues/226.

**Comment by uschindler** [comment]
Hi,
version 3.5.1 was released to work around your problem. Basically adding the `--debug` option to the CLI script and adapting the regular expression a bit should be enough to restore previous behaviour.

https://github.com/policeman-tools/forbidden-apis/wiki/Changes#version-351-released-2023-03-30
