### ISSUE TITLE
Aggregations for long and date values

### ISSUE THREAD

**Issue by Hocdoc** [elastic/elasticsearch#9545]
I store 64-Bit-Twitter-IDs in a long field in Elasticsearch documents:

```
"tweetId": {
  "type": "long"
}
```

I want to use Max aggregation to get the maximum id. Unfortunately I only get Double values (f.ex. 5.6253962514387763E17) instead of my Long Id and I loose the last digits.

It would be perfect when I can also get the max value as `Long` instead of `Double`.

See also my [Stackoverflow question](http://stackoverflow.com/questions/28295400/elasticsearch-max-long-value-aggregation) about this issue.

**Comment by rjernst** [comment]
@Hocdoc Are you passing your long values as json numbers? These have precision problems for large integers.  Instead, you can pass them as strings and Elasticsearch will coerce the string into the type (long in this case) of the field.

**Comment by Hocdoc** [comment]
No, the values are stored correctly (but thanks for the JSON hint). 
I use the Java client, not a Javascript client. I think the problem is the [Max interface](https://github.com/elasticsearch/elasticsearch/blob/master/src/main/java/org/elasticsearch/search/aggregations/metrics/max/Max.java)  which only define the `getValue()` method with return type double instead of f.ex. `Number`.

**Comment by rjernst** [comment]
Thanks @Hocdoc, your findings look like the probable cause. @jpountz is going to take a look.

**Comment by jpountz** [comment]
Not only the interface is an issue but also the internal implementation: for simplicity we handle everything as doubles. We could potentially fix the min and max aggs, but I don't think eg. the sum aggregation is fixable since you can easily overflow a long while a double gracefully loses accuracy as the sum increases.

I don't know how many users are affected by this issue. It is only an issue in practice when values grow larger than 2^53 so maybe the right thing to do is just to document this limitation?

**Comment by Norelius** [comment]
I think there would be value in implementing min and max aggregations for long fields even if the sum aggregation is left out. The reasoning being that you might want to store a unix timestamp as a long instead of using the date option and find min or max timestamps within a search result.

**Comment by Noia** [comment]
I'd suggest making the Max interface become generic <T extends Number> and then the Sum interface does the same but retains a doubleValue method with comments regarding precision. Alternatively you can add a tag to the Sum requests regarding how to handle overflow scenarios. Also, you can fit more in by using an unsigned long (from Guava) but that's probably beyond the scope of this.

**Comment by clintongormley** [comment]
@jpountz what's your feeling about this one after 18 months of reflection?

**Comment by jpountz** [comment]
I think this is only really an issue for the `min` and `max` aggregations, which return a value from the dataset rather than an aggregate from multiple values. There would also be the `percentiles` aggregation in that case, but it is already documented as being approximate.

I would like to fix it, but it is not straightforward and also looks impossible to do without breaking all users of the Java transport client. So I am tempted to close it and document the behaviour. Maybe we can reconsider when all clients talk to Elasticsearch using the REST layer.
