### ISSUE TITLE
API_key roles

### ISSUE THREAD

**Issue by XEMYJIb** [elastic/elasticsearch#95484]
### Elasticsearch Version

8.7.0

### Java Version

_bundled_

### OS Version

MacOS

### Problem Description

The behavior was seen on the Docker version. The trial and security are enabled.
Multiple roles affect DSL queries.

<img src="https://user-images.githubusercontent.com/5957810/233905901-df597207-152c-4a5d-8382-d6fc375218a1.png" width="300" height="300">
<img src="https://user-images.githubusercontent.com/5957810/233906101-f0719edb-631b-46a5-92a4-45c193dd8b2e.png" width="300" height="100">
---------------------------
<img src="https://user-images.githubusercontent.com/5957810/233906236-cfcfa159-ad54-4bb8-a847-2f75512ab644.png" width="300" height="400">
<img src="https://user-images.githubusercontent.com/5957810/233906307-6d61a1c4-e33c-48c9-8f6b-48b928512999.png" width="300" height="200">

### Steps to Reproduce

- Create document
- Create API_key with one role. The role contains
two privileges -  and "read" and DSL query that restricts search(read) documents by a field.
- Make a search with the API_key. Expected result - "found": false. Actual result - "found": false.
- Create a similar API_key but with two roles. The first role contains "read" privilege and 
DSL query that restricts search(read) documents by a field. The second role contains "create" privilege.
- Make a search with the new API_key. Expected result - "found": false. Actual result - "found": true.

**Comment by slobodanadamovic** [comment]
@XEMYJIb This is an expected behavior which is described here: 

- https://www.elastic.co/guide/en/elasticsearch/reference/current/field-and-document-access-control.html#multiple-roles-dls-fls

> Document level security takes into account each role held by the user and combines each document level security query for a given data stream or index with an "OR". This means that only one of the role queries must match for a document to be returned.

In this particular case `role2` did not provide any DLS query which automatically means it grants access to all document. 

Hope this helps clarify it. If you have further questions I suggest you raise it on our [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by XEMYJIb** [comment]
@slobodanadamovic thank you for the reply. As for the forum, I did not get the answer there.
