### ISSUE TITLE
Visibility into contents of filter cache

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#9558]
Would be nice to provide something similar to fielddata memory breakdown in the node stats so we can see the top consumers of the filter cache (eg. list the type of filter in the cache, and for each type, list the field names and count + size info) without having to log and review queries or examine a heap dump.

**Comment by jpountz** [comment]
Breaking down by field would be complicated since queries may apply to several fields (eg. bool) and other queries don't apply to the field that you think they do (eg. the exists filter which queries the _field_names field instead of the field that documents should have).

Breaking down by query type would be easier but I'm afraid the output could be misleading since we cache the rewritten queries (on purpose). So for instance if you use bounding box filters, you might only see boolean queries and range queries in the cache.

I'm not totally against it, just wanted to give more information about the trade-offs / challenges. :)

Currently the tracking of the statistics of the filter cache is a bit hack-ish due to the fact that this cache is per-node while elasticsearch allows to report per-shard statistics. So we have a map between shard ids and the segments that they have and use this information to break down stats per shard. If we want to add more stats to the filter cache, I think we should first try to clean up the way we do reporting of the filter cache usage, which might require us to stop breaking down statistics by shard first.

**Comment by ppf2** [comment]
Thanks for the perspective!  When I hear about this requirement in the field, they are often related to figuring out what makes sense to cache so I think this auto cache PR will help (https://github.com/elastic/elasticsearch/pull/8573).  Though some users are also trying to figure out in similar way what makes sense to add to the warmers based on the field accessed in the cache.

**Comment by clintongormley** [comment]
I think that if the shard is node level, then the stats should also be node level, especially if implementing them at shard level involves lots of hackery.

@ppf2 regarding warmers - I think we can do a better job there: we should be auto-warming the N most popular and expensive filters, or something like that.  Warmers have pretty much been replaced by field level options like `eager_global_ordinals`. With a bit more work we can make all warming either configurable or automatic without requiring the user to figure it out for themselves.

This seems a better investment of time to me.

**Comment by ppf2** [comment]
@clintongormley Agreed :+1:

**Comment by ycombinator** [comment]
Also requested by @icedfish. He is also interested in a related feature: to be able to automatically warm up the top X queries (same as Clint's comment above), but I could not find a separate public issue for this related feature request so mentioning it here.

**Comment by clintongormley** [comment]
I think that exposing the contents of the filter cache these days is nothing more than a debug tool.  The use case of using it to find filters to warm is something that should be done automatically by elasticsearch, not by the user. Given the complexity of exposing this API, I'm going to close this issue in favour of improving warmers (https://github.com/elastic/elasticsearch/issues/9331)
