### ISSUE TITLE
Newly added cluster and index privileges should be handled to ensure BWC

### ISSUE THREAD

**Issue by slobodanadamovic** [elastic/elasticsearch#95771]
### Elasticsearch Version

8.X, 7.X

### Java Version

_bundled_

### OS Version

not relevant

### Problem Description

Creating a role against a new version node, with a newly introduced named index or cluster privilege, in a mixed version cluster will cause authentication to fail against old version node. Although, arguably the mixed cluster should be temporary state, I still think we should handle this.

Note: This issue does not only affect users but also API keys. 

### Steps to Reproduce

1. Create a role with cluster or index privilege against new version node (e.g. 8.8.0)
```
POST _security/role/my-role
{
    "cluster": ["manage_search_application"], // This cluster privilege was introduced in 8.8.0
    "indices": [
        {
            "names": ["*"],
            "privileges": ["read", "new_manage_privilege"] // The is a fictive privilege, but let's imagine it's only known to 8.8.0 node
        }
    ]
}
```
2. Create a user and assign new role against new version node
```
PUT _security/user/my-user
{
    "password": "secret",
    "roles": ["my-role"]
}
```
3. Send authenticate request to old version node (e.g. 8.7.1) `POST /_security/_authenticate`

**Comment by ywangd** [comment]
It might be useful to handle this. But I think it is also OK in its current state. BWC handling's main focus is:
1. Not breaking existing workflows - A typical example is adding a new field to an existing Request class. Since there maybe existing workflows using this Request, we want to ensure a minor version upgrade does not break them.
2. Not silently do the wrong thing for existing workflows - A recent example is that we prevent creating role or API keys with `remote_indices` if there are old nodes. RoleDescriptor parsing is lenient and it skips unknown fields. This means a role with `remote_indices` will be loaded by an old node as if it does not have a `remote_indices` section. This may result into obsecure failure scenarios or sliently giving out wrong results. 

If end-user actively uses a new feature (e.g. the new privilege) and the new feature always explicitly errors on an old node, it does not break existing workflows and does not siliently do the wrong thing. Since the mix-version cluster should be considered temporary, I don't feel strongly the need to fix it.
