### ISSUE TITLE
[DOCS] Improve Install Elasticsearch with Docker documentation

### ISSUE THREAD

**Issue by abdonpijpelink** [elastic/elasticsearch#95791]
There have been a few complaints about the [Install Elasticsearch with Docker](https://github.com/elastic/elasticsearch/blob/main/docs/reference/setup/install/docker.asciidoc) documentation. We should review those docs to ensure the guidance is still correct and follows best practices.

Specific feedback provided via the feedback form:

- breaks enrollment ERROR: [xpack.security.enrollment.enabled] must be set to `true` to create an enrollment token (Apparently regarding [Always bind data volumes](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_always_bind_data_volumes))
- step 5 doesnt work for me it is not possible to enter any key for a password
- The example does not work, as it did not create a user at the setup service, it tries to change a password for non existing user.
- Version 7 crashes on start on windows and linux, same for version 8. 
- setup fails with security_exception: unable to authenticate user [kibana_system] for REST request

Additional issues:

- [JVM heap error](https://github.com/elastic/elasticsearch/pull/96054)

**Comment by mark-vieira** [comment]
Can you elaborate on these two points?

> Version 7 crashes on start on windows and linux, same for version 8.
> setup fails with security_exception: unable to authenticate user [kibana_system] for REST request

**Comment by abdonpijpelink** [comment]
This is raw feedback that folks entered in the feedback form. We have no more information.

I think it would be good if someone with Docker knowledge verifies the documentation to ensure all the steps still work and follow best practices.

**Comment by abdonpijpelink** [comment]
Feedback from @TimBosman : The [Kibana docker instructions](https://www.elastic.co/guide/en/kibana/current/docker.html) are better. And more useful, because they show how to spin up Elasticsearch **and** Kibana. We could consider (partly) copying those instructions to the ES docs.

**Comment by TimBosman** [comment]
I think this documentation page is too long and unstructured. I think we should not have the full docker compose example on the page, but have it linked to a repository. There is repetition in the subjects (setting JVM heap). I have made a start below to restructure

# Install Docker

# Pull the Docker image
## Optional: Verify the image signature
# Create an Elasticsearch cluster
## Start first node
The following commands start a single-node Elasticsearch cluster for development or testing.
1. Create a new docker network for Elasticsearch
`docker network create elastic`

2. Start an Elasticsearch container in Docker. This command will print the elastic user password and an enrollment token for Kibana on the terminal.
`docker run --name es01 --net elastic -p 9200:9200 -it -m 1GB docker.elastic.co/elasticsearch/elasticsearch:8.9.0`
> Note: It is recommended to set a container memory limit for Elasticsearch container, since Elastic will configure the JVM size to half of the available memory, which is the full Docker node memory by default.

3. Copy the generated elastic password and enrollment token. These values are only shown at start-up, but can be regenerated using the following commands
`docker exec -it es01 /usr/share/elasticsearch/bin/elasticsearch-reset-password`
`docker exec -it es01 /usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana`

4. Curl the container to ensure that the container is running. By copying the http_ca.crt from the Elasticsearch container to your local machine. 
`docker cp es01:/usr/share/elasticsearch/config/certs/http_ca.crt .`
`curl --cacert http_ca.crt -u elastic https://localhost:9200`
This can also be done without verifying the Elasticsearch certificate.
`curl -k -u elastic https://localhost:9200`

## Add more nodes
To add more nodes to our cluster we should take the following steps:
1. Generate a enrollment token for a new Elasticsearch node
`docker exec -it es01 /usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s node`

2. Run a new Elasticsearch container with the enrollment token as an environment variable
`docker run -e ENROLLMENT_TOKEN="<token>" --name es02 --net elastic -it -m 1GB docker.elastic.co/elasticsearch/elasticsearch:8.9.0`

3. Check if the node is added to the node list
`curl --cacert http_ca.crt -u elastic https://localhost:9200/_cat/nodes`

## Configure Elasticsearch containers
When Elasticsearch is run in a Docker container, the [configuration files](https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html#config-files-location) can be found in 
 `/usr/share/elasticsearch/config`. In order to change these files, we can mount a local configuration file over the default one in the container. This can be done by adding `-v full_path_to/custom_elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml` to your `docker run` command. 
Alterternatively, we can set individual Elasticsearch configurations, using the container environment variables. This can be done by using the setting name directly as the environment variable name. If you cannot do this, for example because your orchestration platform forbids periods in environment variable names, then you can use an alternative style by converting the setting name as follows.
1. Change the setting name to uppercase
2. Prefix it with ES_SETTING_
3. Escape any underscores (_) by duplicating them
4. Convert all periods (.) to underscores (_)
For example, `-e bootstrap.memory_lock=true` becomes `-e ES_SETTING_BOOTSTRAP_MEMORY__LOCK=true`.
You can use the contents of a file to set the value of the `ELASTIC_PASSWORD` or `KEYSTORE_PASSWORD` environment variables, by suffixing the environment variable name with `_FILE`. This is useful for passing secrets such as passwords to Elasticsearch without specifying them directly.

For example, to set the Elasticsearch bootstrap password from a file, you can bind mount the file and set the `ELASTIC_PASSWORD_FILE` environment variable to the mount location. If you mount the password file to `/run/secrets/bootstrapPassword.txt, specify`:

`-e ELASTIC_PASSWORD_FILE=/run/secrets/bootstrapPassword.txt`
You can override the default command for the image to pass Elasticsearch configuration parameters as command line options. For example:

`docker run <various parameters> bin/elasticsearch -Ecluster.name=mynewclustername`
### JVM heap size
# Elasticsearch on Docker in production
# Elasticsearch cluster with Docker compose
# Common issues

**Comment by jrodewig** [comment]
Thanks for raising this @abdonpijpelink. And thanks for the additional feedback @TimBosman.

I've opened https://github.com/elastic/elasticsearch/pull/98886 to include most of @TimBosman's restructuring suggestions. I'm going to close this issue with that PR, but I'll continue iterating on these docs as part of https://github.com/elastic/platform-docs-team/issues/183.

## Feedback
Tackling some of the feedback outlined in the root comment:

### Enrollment

> - breaks enrollment ERROR: [xpack.security.enrollment.enabled] must be set to `true` to create an enrollment token (Apparently regarding [Always bind data volumes](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_always_bind_data_volumes))

This setting is `true` by default. To disable it, the user must explicitly disable security autoconfig (`xpack.security.autoconfiguration.enabled`) or the specific enrollment setting (`xpack.security.enrollment.enabled`).

I don't think this will happen accidentally, and I feel like the settings are covered well enough in the [security settings docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html). I don't think we should crowd the Docker docs with a related note.

It's not clear to me how this relates to binding data volumes.

### Password feedback
> - step 5 doesnt work for me it is not possible to enter any key for a password

This should be fixed with https://github.com/elastic/elasticsearch/pull/98886. We now explicitly pass a password in the curl command rather than waiting for a prompt.

> - The example does not work, as it did not create a user at the setup service, it tries to change a password for non existing user.

Not sure what may have caused this. However, I tested the single-node and Docker compose instructions in https://github.com/elastic/elasticsearch/pull/98886 on Mac, Windows, and Linux (Ubuntu) — They work now.

### Crashes on Linux and Windows
> - Version 7 crashes on start on windows and linux, same for version 8. 

My guess is that this is a Linux or WSL user that didn't set `vm.max_map_count` to `262144` or higher. I'm going to move this content up as part of https://github.com/elastic/platform-docs-team/issues/185

### Kibana authentication failures
> - setup fails with security_exception: unable to authenticate user [kibana_system] for REST request

Dunno what may have caused this. It could be that the user ignored [this note indicating that passwords must be alphanumeric](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-compose-file:~:text=Your%20passwords%20must%20be%20alphanumeric) if you're using the Docker Compose example.

### JVM heap error

> Additional issues:
>
> - [JVM heap error](https://github.com/elastic/elasticsearch/pull/96054)

There could be multiple things going on here. As Mark mentioned in the issue, setting `-e "discovery.type=single-node"` isn't the right solution. However, I think we should maybe incorporate our [JVM heap setting recommendations](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_setting_jvm_heap_size) into the default single-node instructions: https://github.com/elastic/platform-docs-team/issues/184
