### ISSUE TITLE
unknown setting [archived.cluster.routing.allocation.disk.include_relocations] please check that any required plugins are installed, or check the breaking changes documentation for removed settings

### ISSUE THREAD

**Issue by liyale123** [elastic/elasticsearch#95851]
### Elasticsearch Version

8.7.0

### Java Version

_bundled_

### OS Version

8.7.0

### Problem Description

elasticseasch-7.15.1升级到7.17.0，再升级到8.7.0后集群有些参数无法使用，一直报错unknown setting [archived.cluster.routing.allocation.disk.include_relocations] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"。

Some parameters of the cluster are unavailable after elasticseasch-7.15.1 was upgraded to 7.17.0 and then to 8.7.0. An error persists “unknown setting [archived.cluster.routing.allocation.disk.include_relocations] please check that any required plugins are installed, or check the breaking changes documentation for removed settings""

### Steps to Reproduce

PUT _cluster/settings
{
  "persistent": {
    "cluster.routing.allocation.disk.watermark.low": "89%",
    "cluster.routing.allocation.disk.watermark.high": "94%"
  }
}

### Logs (if relevant)

{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "unknown setting [archived.cluster.routing.allocation.disk.include_relocations] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "unknown setting [archived.cluster.routing.allocation.disk.include_relocations] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"
  },
  "status": 400
}

**Comment by dliappis** [comment]
The setting [cluster.routing.allocation.disk.include_relocations](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/modules-cluster.html) is deprecated since `7.5.0`. In [breaking changes](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/breaking-changes-7.5.html#deprecate-cluster-routing-allocation-disk-include-relocations-setting) we can see:

> The cluster.routing.allocation.disk.include_relocations cluster setting is now deprecated. In future versions, Elasticsearch will account for the sizes of relocating shards when making allocation decisions based on the disk usage of nodes in the cluster.
> Currently, you can set cluster.routing.allocation.disk.include_relocations to false to disable this accounting. This can result in poor allocation decisions that might overshoot watermarks and require significant work to correct.
> To avoid deprecation warnings, discontinue use of the setting.

In the [migration guide for 8.0](https://www.elastic.co/guide/en/elasticsearch/reference/8.7/migrating-8.0.html) you can see a guidance section for this setting:

> cluster.routing.allocation.disk.include_relocations has been removed.
> Details
> Elasticsearch now always accounts for the sizes of relocating shards when making allocation decisions based on the disk usage of the nodes in the cluster. In earlier versions, you could disable this by setting cluster.routing.allocation.disk.include_relocations to false. That could result in poor allocation decisions that could overshoot watermarks and require significant extra work to correct. The cluster.routing.allocation.disk.include_relocations setting has been removed.

> Impact
> Remove the cluster.routing.allocation.disk.include_relocations setting. Specifying this setting in elasticsearch.yml will result in an error on startup.

So you should remove this setting now that you're on 8.x.

Additionally, this appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
