### ISSUE TITLE
Allow comments inside mapping

### ISSUE THREAD

**Issue by drorata** [elastic/elasticsearch#9649]
Currently, when invoking `GET indexname/_mapping` one gets a long list of the fields that can be expected in the index. All these have the form:

```
"feed": {
            "type": "string",
            "index": "not_analyzed"
}
```

For an end user, who normally cannot see the configuration, the name of the field and its properties might not be enough to understand what the field actually holds. Therefore, it would be very helpful to allow a comment field inside the object above. Here is an example:

```
"feed": {
            "type": "string",
            "index": "not_analyzed"
            "comment": "feed holds the name of the feed as provided by the client side"
}
```

**Comment by colings86** [comment]
We would need to be careful here that the comments don't explode the cluster state size. In a large cluster with a lot of indices/fields the comments could grow the cluster state size by a lot causing issues. Maybe we should have a character limit on the comments to help with this?

**Comment by drorata** [comment]
I don't understand. I though these comments should be stored in the config files, and when the user invokes `_mapping` it will extract them from there. But apparently I am wrong.

**Comment by colings86** [comment]
@drorata the mapping lives within the cluster state which is given to every node in the cluster and published to all nodes when the cluster state changes (such as changing mapping, adding a node to the cluster, reallocating shard). To be able to keep all the comments in the mapping in sync we would want to store them in the mapping since coordinating this with another mechanism (such as storing the comments in a file on disc) would add more complexity and the potential for cluster state bugs.

**Comment by drorata** [comment]
@colings86: You're the expert. I can only say that as a user this kind of information could be helpful.

**Comment by colings86** [comment]
@drorata Yes, I think it's useful too, thanks for raising the issue. I've labelled it `adoptme` so it should get picked up and implemented

**Comment by dadoonet** [comment]
See also #1394. Though it was closed, I guess it was not really fixed? :)

**Comment by synhershko** [comment]
@dadoonet it was fixed in https://github.com/elasticsearch/elasticsearch/commit/6f7253c5242e7fb94d959ce291c88f93887e3bde -- comments are supported when passed in source, they just don't get persisted to store hence aren't retrieved.

I'm on the fence on this one. Commenting using proper comments on code seems to be enough, and the fact they are being stripped by the deserializer on ES's end so never persisted seems to only affect edge cases where you want to read mappings from the cluster and don't have access to SCM. I think I can live with that.

**Comment by drorata** [comment]
@synhershko I disagree with you. Having under the hood access is not always granted to the "user" and it could be very helpful to be able to have easy access to what the developers had in mind. It is not terribly important, and there are loads of workarounds, but it is still nice to have integrated into the ES.

**Comment by synhershko** [comment]
@drorata fwiw this is supported in Elasticsearch since it doesn't validate the input http://fadefade.com/json-comments.html

**Comment by drorata** [comment]
I'm afraid I didn't understand your comment.

**Comment by synhershko** [comment]
@drorata you can still "have comments", sorta, by duplicating the field in the input like demonstrated in the link I provided. The first instance of the field will be ignored.

**Comment by drorata** [comment]
@synhershko and will this pseudo-comment be returned when executing `_mapping`?

**Comment by synhershko** [comment]
Actually I'm not sure, good point

**Comment by pquentin** [comment]
No, it won't, that's the whole point of the hack.

**Comment by clintongormley** [comment]
Fields can already be documented in the `_meta` field if really necessary.  While not quite as convenient as having a comment on every field, I think it is sufficient to support this use case and more efficient than having to add an optional field to every field mapping.  I'm going to close this issue
