### ISSUE TITLE
Time Range for Snapshot Restore 

### ISSUE THREAD

**Issue by AravindhStanley** [elastic/elasticsearch#97034]
### Description

I would like to propose a feature that allows restoring snapshots for specified time range. Assume the data stream's backing indices are around 50 GB and has multiple days worth of data and user need only a specific data's log. It would save lots of time and space if we can have this feature during the restore.

Right now, the only option is to restore the entire data stream, at least allowing certain backing indices would help solve this to an extent?

**Comment by DaveCTurner** [comment]
This is effectively what [partially-mounted searchable snapshots](https://www.elastic.co/guide/en/elasticsearch/reference/current/searchable-snapshots.html) do: the data is held in a snapshot and only retrieved into the cluster when accessed by a search. The advantages of searchable snapshots include that (a) you don't even need to take action to restore the data, the on-demand retrieval is automatic, and (b) you don't even need space for the whole index in the cluster, the on-demand retrieval is much more granular.

Since this use-case is already supported today, I'm closing this.
