### ISSUE TITLE
Geoshape query returns incorrect results

### ISSUE THREAD

**Issue by j0r0** [elastic/elasticsearch#9716]
With version 1.4.1 we had this issue: #8467
https://github.com/elasticsearch/elasticsearch/issues/8467

With 1.4.1 the workaround returns completely wrong results.
Example;
```
{
  "size" : 0,
  "query" : {
    "bool" : {
      "must" : [ {
        "range" : {
          "ts" : {
            "from" : "2015-02-13T00:00:00.0Z",
            "to" : "2015-02-13T23:59:58.0Z",
            "include_lower" : true,
            "include_upper" : true
          }
        }
      }, {
        "geo_shape" : {
          "loc" : {
            "shape" : {
              "type" : "polygon",
              "coordinates" : [ [ [ -179.999, 89.999 ], [ 179.999, 89.999 ], [ 179.999, -89.999 ], [ -179.999, -89.999 ], [ -179.999, 89.999 ] ] ]
            },
            "relation": "within"
          }
        }
      } ]
    }
  }
}
```

This returns 4360 results, which is clearly wrong.

Another query (only polygon changed a bit)
```
GET track_201502/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "geo_shape": {
      "loc": {
        "shape": {
          "type": "polygon",
          "coordinates": [[[-180,90],[180,90],[180,-90],[-180,-90],[-180,90]]]
        },
        "relation": "within"
      }
    }
        },
        {
          "range": {
            "ts": {
              "from" : "2015-02-13T00:00:00.0Z",
            "to" : "2015-02-13T23:59:58.0Z",
            "include_lower" : true,
            "include_upper" : true
            }
          }
        }
      ]
    }
  }
  ,
  "size": 0
}
```
This returns 6678451 results which is more likely .
As you can see the only difference between the 2 queries is the polygon .
Instead of 180/90 we have 179.999/89.999
This was workaround for  #8467

**Comment by nknize** [comment]
Can you post your field mappings?

**Comment by j0r0** [comment]
Sure. I am posting only the relevant fields
```
"ts": {
  "format": "dateOptionalTime",
  "type": "date"
},
"loc": {
  "tree": "quadtree",
  "type": "geo_shape"
}
```

**Comment by j0r0** [comment]
I just noticed something which can eventually help you.
The direction of polygon I am describing is clockwise.
So : topleft , topright,bottomright,bottomleft,repeatfirst

If i change the direction to ccw, it is returning correct results.

**Comment by nknize** [comment]
@j0r0 Thanks for the feedback.

If I understand the behavior you're describing then its working as expected.  We switched the ShapeBuilder winding order to comply with the OGC right-hand rule.  While geojson does not care, this indifference becomes problematic for ambiguous polygons such as yours (e.g., no way of knowing whether the specified poly crosses the dateline or spans the globe).  By complying with the right-hand rule we impose deterministic ordering in the ShapeBuilder to remove these ambiguities.  When you specified your coordinates in clockwise order, the builder interpreted them in counter-clockwise - thus the poly crosses the dateline instead of spanning the globe.  The one exception is a global spanning polygon - which is unambiguous.  

There's also another issue at play here (which affects the results for large filters).  If you increase the ```tree_level``` and reduce the ```distance_error_pct``` values in your mapping, you will (should) see different results.  That behavior is related to issues #2361, #9691, #9680 and has to do with the accuracy of the quad cells.  By accepting defaults you're using a ```tree_level``` of 12 which maps to a cell coverage area of ~0.022/0.044 degrees lat/lon.  The ```distance_error_pct``` adds another fuzzy factor (default of 2.5% the length of the shape's bounding box diagonal)  So for large polygons this error factor will increase.  This is an issue thats currently being worked and should be fixed very soon.  For now, the best approach is to find a balance between the precision you really need and performance requirements.  Post filtering results in the application layer is a good way of weeding out the false matches (which you won't need to do once these issues are corrected).

I hope this helps

**Comment by clintongormley** [comment]
@nknize can this issue be closed, or do you want to keep it open for now?

**Comment by nknize** [comment]
Unless @j0r0 has an outstanding issue I consider this resolved.  Lets give a day or so for further feedback.

**Comment by nknize** [comment]
Closing as non-issue
