### ISSUE TITLE
[CI] DataStreamLifecycleServiceTests

### ISSUE THREAD

**Issue by albertzaharovits** [elastic/elasticsearch#97570]
### CI Link

[Build Scan™ for 'elasticsearch' today at 09:10:21 EEST | Gradle Enterprise](https://gradle-enterprise.elastic.co/s/cv3sgpbwgaowe/tests/:modules:data-streams:test/org.elasticsearch.datastreams.lifecycle.DataStreamLifecycleServiceTests/testDataStreamsWithoutLifecycleAreSkipped?top-execution=1)

### Repro line

./gradlew ':modules:data-streams:test' --tests "org.elasticsearch.datastreams.lifecycle.DataStreamLifecycleServiceTests.testForceMergeDedup" -Dtests.seed=D8A4B58C934EFB56 -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=zh-CN -Dtests.timezone=America/Havana -Druntime.java=20

### Does it reproduce?

Yes

### Applicable branches

main 

### Failure history

https://gradle-enterprise.elastic.co/scans/tests?search.startTimeMax=1689081987180&search.startTimeMin=1688418000000&search.timeZoneId=Europe/Bucharest&tests.container=org.elasticsearch.datastreams.lifecycle.DataStreamLifecycleServiceTests

### Failure excerpt

From what I can tell the error trace for all the tests in `DataStreamLifecycleServiceTests` is:
```
  2> java.lang.IllegalArgumentException: setting cluster.lifecycle.default.rollover has not been registered
        at org.elasticsearch.common.settings.AbstractScopedSettings.get(AbstractScopedSettings.java:743)
        at org.elasticsearch.datastreams.lifecycle.DataStreamLifecycleService.<init>(DataStreamLifecycleService.java:167)
        at org.elasticsearch.datastreams.lifecycle.DataStreamLifecycleServiceTests.setupServices(DataStreamLifecycleServiceTests.java:114)
```

**Comment by masseyke** [comment]
@gmarouli I took a look at this one because I thought it might be yet another problem with forcemerge. But it looks like the problem is the `-Dbuild.snapshot=false` argument -- that results in DataStreamLifecycle.isEnabled() being false, which breaks all the tests. I assume we'll want to add `assumeTrue` lines to all these tests? But I'm not sure if you had something else in mind there so I'll leave it up to you.

**Comment by gmarouli** [comment]
You are right @masseyke , the cause is `-Dbuild.snapshot=false`. The approach we took in the past to fix this is to enable the flag in release builds, something I forgot when I move the data stream lifecycle code from the `dlm` module to the `data-streams` (https://github.com/elastic/elasticsearch/pull/97345/files#diff-ae6caffc7a2ab209609293083f2fef0e80c453c21556bb7a703cb7013a4bdda4). Fix is coming!
