### ISSUE TITLE
Debian packaging: JAVA_HOME detection in init script defeats update-alternatives

### ISSUE THREAD

**Issue by grantr** [elastic/elasticsearch#9774]
We are using update-alternatives to manage java versions, so we'd like elasticsearch to always use `which java` to select a java version. Unfortunately this doesn't work by default because the elasticsearch init script tries to autodetect `JAVA_HOME` and use that instead of the java in the path: https://github.com/elasticsearch/elasticsearch/blob/544ef8cb17014efb72abb2932d227e4f327b1dcb/src/deb/init.d/elasticsearch#L47

We can override the detected `JAVA_HOME`  in `/etc/default/elasticsearch`, causing the script to fall back to `which java` as desired. Before committing to this approach, we'd like to confirm that this behavior won't accidentally or intentionally change without warning in the future. Can we count on an empty `JAVA_HOME` being respected in future versions?

I'd also like to suggest removing the code that autodetects `JAVA_HOME`, especially for distributions that use update-alternatives. I prefer the behavior of the default elasticsearch binaries: use `JAVA_HOME` if present but don't try to set it.

/cc @spinscale

**Comment by clintongormley** [comment]
@spinscale @tlrx any thoughts?

**Comment by tlrx** [comment]
@grantr thanks to share your thoughts.

I agree with you and I also think that the automatic JAVA_HOME detection is maybe not a such good idea. We are currently modifying the scripts to make them more uniform and we will remove this detection loop from the init script. If really needed, one could add it in the `/etc/default/elasticsearch` to set JAVA_HOME.

To me, the right behavior is: use `JAVA_HOME` if defined (in `/etc/default/elasticsearch` or anywhere else) otherwise `which java` will do the job.

> Can we count on an empty JAVA_HOME being respected in future versions?

Yes.

> I prefer the behavior of the default elasticsearch binaries: use JAVA_HOME if present but don't try to set it.

I agree :)

**Comment by grantr** [comment]
Great, thanks @tlrx! I'll follow the release notes to see when I can remove the `JAVA_HOME` override from our `/etc/default/elasticsearch`.

**Comment by tlrx** [comment]
@grantr it should be fixed by #13514
