### ISSUE TITLE
Missing quotes breaks stuff

### ISSUE THREAD

**Issue by jimmyjones2** [elastic/elasticsearch#9800]
The following is allowed:
```
curl -XPUT localhost:9200/test9/test9/1 -d '{ test: 0 }'
```
However it upsets downstream systems as it's not quite JSON, eg. the Perl Search::Elasticsearch module, Kibana, and possibly others. Should the _source be rewritten to make it proper JSON (like when you submit YAML), or should this be banned entirely, maybe in 2.0?

**Comment by clintongormley** [comment]
yeah, i'm torn about it.  i think the idea of relaxed parsing was to make it less onerous to try things out from the command line with curl.  That said, with autocomplete tools like Sense available, it is much easier to type correct JSON.

We're certainly leaning towards being stricter, because it avoids silent errors.

**Comment by GlenRSmith** [comment]
Maybe there should be a configuration to enforce strict json. If so, I think it would make most sense for the default behavior to be "strict", and have it over-ridden in es.yml in the distros. This would make it a little more likely, I think, that people would remember to change the config before deploying to production.
Even with that modification, maybe in "relaxed" mode, ES should do what @jimmyjones2 suggests. There would be some performance overhead, but, if implemented properly, removing the "json relaxed" config would eliminate that.
So, where does the setting belong?
Maybe something on "index." which can be set on index creation. Or, come to think of it, something in the mapping, analogous to "dynamic". I'm hesitant to suggest something really literal, like "require_quoted_keys", because maybe there would be a future case for including other relaxations, like tolerating missing commas between key/value pairs.

**Comment by clintongormley** [comment]
Really this is just a setting in Jackson: https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/common/xcontent/json/JsonXContent.java#L46

Should we allow this to be changed via settings, or even just require quoted field names?

**Comment by jimmyjones2** [comment]
I'd vote for quoted by default, for one this behaviour wasted an hour of my life plus Elasticsearch sends the HTTP header ``Content-Type: application/json`` in the response, which is incorrect if quotes are missing.

**Comment by rjernst** [comment]
I dont think we should make it configurable or possible, given that it is not part of the json spec, and it would tie us to a particular json library (jackson).

**Comment by clintongormley** [comment]
Actually, the JSON spec requires double quotes around field names.  http://www.json.org/

**Comment by rjernst** [comment]
Exactly, my comment was meant to say the json spec does not allow the absence of quotes.

**Comment by clintongormley** [comment]
But currently we accept JSON without quotes around field names, so changing this would be a breaking change.

**Comment by clintongormley** [comment]
Honestly, i think the only thing it would break is JSON entered on the command line.  Any clients will be quoting fields correctly already.

**Comment by jimmyjones2** [comment]
Would you accept a patch for 3.0 to change ALLOW_UNQUOTED_FIELD_NAMES to false?

**Comment by dakrone** [comment]
I'm +1 on changing Jackson to be strict (the `ALLOW_UNQUOTED_FIELD_NAMES` change), what do you think @clintongormley?

**Comment by nik9000** [comment]
> Would you accept a patch for 3.0 to change ALLOW_UNQUOTED_FIELD_NAMES to false?

Yes please. Make sure to put it in the breaking changes list in "migrate_3_0.asciidoc". I'm working on reindex now which we could use to ease the pain of anyone who has invalid json in their index.

**Comment by clintongormley** [comment]
Closed by #15351
