### ISSUE TITLE
Add default dynamic mapping for sparse_vector

### ISSUE THREAD

**Issue by ioanatia** [elastic/elasticsearch#98094]
### Description

similar to https://github.com/elastic/elasticsearch/issues/97532

It would be great if dynamic mappings can automatically map `sparse_vector` fields.
This way the `text_expansion` query could work without needing a prerequisite setup of the mapping.

**Comment by benwtrent** [comment]
While `dense_vector` has a natural heuristic (N number of floats), `sparse_vector` (e.g. `rank_features`) does not. 

These are tokens, terms, or numbers pointing to a `float`. It will be difficult to make sure the heuristic we build wouldn't break the typical metric usage of:
```
{
"foo": 2,
"bar": 4,
"baz": 6
}
```

**Comment by kderusso** [comment]
@benwtrent I think we might be able to use heuristics here when the maps of values to float underneath an object exceed some large cutoff, maybe something like 1024? What are your thoughts?

**Comment by kderusso** [comment]
Thanks for the explanation. I think that leaves a couple of options here: 

I wonder if this should be controlled via property? Like, have people opt in to this type of dynamic mapping if they want to? Then we could set the bar very low - Maybe even 50 - and it would be OK. We'd probably want to also be rather aggressive about documentation here to make sure users know the option is there and when to use it. 

The other option is to walk back on this and require mappings. 

WDYT?

**Comment by Mikep86** [comment]
@benwtrent

@mayya-sharipova, @giladgal, @kderusso, and I discussed this at the Search Area Daily and came to a general consensus that a heuristic based on number of map entries was a reasonable way to implement this. The exact threshold value is TBD, but we thought a value between 50-100 could work reasonably well.

If our initial threshold value proves to be disruptive, we could first adjust it and then if it's still problematic, make it configurable by the user.

Thoughts?

**Comment by benwtrent** [comment]
I think this might be ok, but I just don't see how the need for dynamic mapping sparse vector support is similar to dense vector.

I would venture to say nearly all our sparse vector usage is because of elser. The models as an analyzer should address the mapping issue there.

If we add dynamic mapping here, we are making a judgment call on typical sparse model output. Of which, I only know about two (ELSER and SPLADE).

Overall, I am hesitant about this change. It seems like it would never be used once we have a "semantic_text" type. It feels like a hack.

The dense_vector support seemed simpler and more useful to me as there is a plethora of models and folks commonly use inference out of the stack. Additionally, the logic for dense vectors is simple (the model always outputs the same vector dims, sparse models can vary even in themselves).

**Comment by Mikep86** [comment]
@benwtrent 

I see your point about this effort becoming redundant after the introduction of the `semantic_text` type. But looking forward a bit, we may still have the same dynamic mapping problem with the `semantic_text` type. Do we want to support dynamic mapping for the `semantic_text` type? If so, what logic should we use for it?

**Comment by benwtrent** [comment]
> Do we want to support dynamic mapping for the semantic_text type? If so, what logic should we use for it?

Not currently. The only input to `semantic_text` is literal text. I don't see us ever switching that to be something other than `text` and `text.keyword`.

**Comment by Mikep86** [comment]
Closing this issue with no changes applied. The consensus seems to be that this mapping is primarily to support a simpler ELSER workflow in Kibana, which can be achieved with fewer trade-offs via the `semantic_text` field type.
