### ISSUE TITLE
Define good heuristics to use `collect_mode: breadth_first`

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#9825]
`breadth_first` does not work when sub aggregations require scores, which is why we never use it by default today. However, we recently added the ability to know whether an aggregator requires scores or not (for now it just assumes that if a script is used then scripts are needed but we can improve it in the future, for instance I think we could have the information with lucene-expressions at least).

This means that we could now use `breadth_first` by default, we just need to figure out a good heuristic of when this is going to make the terms agg faster and/or more memory-efficient.

**Comment by speedplane** [comment]
It would be fantastic if the `breadth_first` / `depth_first` choice could be handled on the ES side. 

Short of that, it would be nice to have some insight into whether one should be using `breadth_first` instead of `depth_first`. Right now, it's hard to know which one you should use other than testing them both and seeing which is faster. For example, if a counter returned how many temporary buckets were created in order to build the aggregation, one could get some insight into the internals of the aggregation and better optimize it.
