### ISSUE TITLE
Separate reporting for memory usage of ordinals?

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#9838]
Currently, memory usage for global ordinal maps are reported under the fielddata section.  This can be confusing to end users esp. when they have switched from fielddata to doc values.  Have we considered reporting ordinal maps usage in a separate category?

**Comment by jpountz** [comment]
My problem with that is that ordinal maps are really an implementation detail of how we implement some operations. So either we want to have a stable format of our reporting APIs so that tools like kopf or marvel can use it, or we can add more information but then it needs to be only for human consumption as it might break every time that we change the way that some things are implemented.

**Comment by clintongormley** [comment]
@jpountz++  ordinals are an implementation detail. I prefer the option of stable reporting APIs 

closing
