### ISSUE TITLE
Get API has wrong description for `stored_fields` parameter

### ISSUE THREAD

**Issue by sabi0** [elastic/elasticsearch#98385]
Both [7.17](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/docs-get.html#docs-get-api-query-params) and [8.9](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-get.html#docs-get-api-query-params) (current) "Get API" page describe the `stored_fields` parameter as
>  `stored_fields`
>  (Optional, Boolean) If `true`, retrieves the document fields stored in the index rather than the document `_source`. Defaults to `false`.

But in fact it accepts a comma-separated list of stored fields to retrieve, as described in the "[Get stored fields](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-get.html#get-stored-fields)" section at the bottom of the page:

> Use the `stored_fields` parameter to specify the set of stored fields you want to retrieve.
> ...
> `GET my-index-000001/_doc/1?stored_fields=tags,counter`

**Comment by abdonpijpelink** [comment]
Thanks for reporting this @sabi0 . I've transferred your issue to the `elasticsearch` repo.

I think you're right, [looking at the API spec](https://github.com/elastic/elasticsearch-specification/blob/main/specification/_global/get/GetRequest.ts#L76): `stored_fields` accepts a list of fields, instead of a boolean value. I'll let someone from @elastic/es-distributed confirm.
