### ISSUE TITLE
For a given list of indices - consecutively iterating thru and setting index.routing.allocation.require gets progressively slower

### ISSUE THREAD

**Issue by petecheslock** [elastic/elasticsearch#9853]
Using the curator tool (or a bash like `for i in list of indices`;do blah;done) rolling thru 1000 indexes the api calls get progressively slower and slower.

The scenario is to set all the indexes to a certain class as we move towards a tiered storage strategy.
we set `class:ssd`

I don't have 1st run logs - but on a 2nd run it looks like
```
curator allocation --older-than 0 --prefix globallogs. --timestring '%Y%m%d' --rule class=ssd
2015-02-24 15:54:29,318 INFO      Job starting...
2015-02-24 15:54:29,320 INFO      Applying allocation/routing tags to indices...
2015-02-24 15:54:29,394 INFO      Updating index setting index.routing.allocation.require.class=ssd
2015-02-24 15:54:33,407 INFO      apply_allocation_rule operation succeeded on globallogs.20110812
2015-02-24 15:54:33,409 INFO      Updating index setting index.routing.allocation.require.class=ssd
2015-02-24 15:54:37,430 INFO      apply_allocation_rule operation succeeded on globallogs.20110813

<snip>

2015-02-24 17:30:46,229 INFO      apply_allocation_rule operation succeeded on globallogs.20141104
2015-02-24 17:30:46,231 INFO      Updating index setting index.routing.allocation.require.class=ssd
2015-02-24 17:30:55,402 INFO      apply_allocation_rule operation succeeded on globallogs.20141105
2015-02-24 17:30:55,403 INFO      Updating index setting index.routing.allocation.require.class=ssd
```

I've tried to do a single shard like `curl -XPUT localhost:9200/globallogs.20150223/_settings -d '{"index.routing.allocation.require.class" : "ssd"}'` and it took the same amount of time to respond.

Querying Hot threads from /_nodes/hot_threads - gives https://gist.github.com/petecheslock/9d27dba1afe6fe0578e4

We are running v1.4.3

**Comment by dakrone** [comment]
Okay, I spent some time looking into this, here is my theory - 

Every time an index's settings are updated, Elasticsearch first applies the new
settings to the index, and attempts to re-route the cluster (in case settings
like `number_of_replicas` have changed). See this line in
[MetaDataUpdateSettingsService](https://github.com/elasticsearch/elasticsearch/blob/1816951b6b0320e7a011436c7c7519ec2bfabc6e/src/main/java/org/elasticsearch/cluster/metadata/MetaDataUpdateSettingsService.java#L313-L315)

So here's what is happening, the first index is having the
`index.routing.allocation.require.class: ssd` setting added to it, so the
setting is added, and then the master nodes reroutes all of the shards. This
means the `BalancedShardsAllocator` will run through shards checking if they can
remain, in your case none of the nodes have the `node.class: ssd` setting, so
the shard for the index can not remain on the current node. The allocator
attempts to move it to any other node, which it can't, because none of the nodes
have that tag yet. Eventually, it fails because there is nowhere to move the
shards for this index and it gives up.

The cluster state in incremented and sent out to all nodes.

Now, the second index has the `index.routing.allocation.require.class: ssd`
setting applied. Again, the master node adds the setting and attempts another
reroute. This time the balanced shards allocator tries to move the second index
away, and it also tries to move all the shards for the first index away. Again,
there are no nodes with the "ssd" tag, so it eventually gives up.

The cluster state is incremented and sent out to all nodes.

This repeats for every index that you have, so you end up with:

`n * (n + 1) / 2` total moving-an-index-away attempts.

For 1000 indices, this means 500500 attempted rebalances for a particular index,
assuming you are applying the setting incrementally.

Fortunately, there is a way to make this better -

Currently, Curator issues requests on an index-by-index basis after resolving
the indices that need to have settings changed, however, after every request, a
new reroute is performed and a new cluster state issued. To prevent this, we can
change:

    curl -XPUT 'localhost:9200/index1/_settings' -d'{...}'
    curl -XPUT 'localhost:9200/index2/_settings' -d'{...}'
    curl -XPUT 'localhost:9200/index3/_settings' -d'{...}'
    curl -XPUT 'localhost:9200/index4/_settings' -d'{...}'
    curl -XPUT 'localhost:9200/index5/_settings' -d'{...}'

Into a single call:

    curl -XPUT 'localhost:9200/index1,index2,index3,index4,index5/_settings' -d'{...}'
    
    ... or ...
    
    curl -XPUT 'localhost:9200/index*/_settings' -d'{...}'

By doing it in a single request, only a single reroute is attempted after
applying the settings to all the indices.

I've spoken with @untergeek about making this change in Curator, and I think we
both agreed that it should be added. Until it is, as a workaround, you can
manually apply the setting to multiple indices at once, which should prevent so
much churn in the cluster with regard to rerouting and new cluster states.

**Comment by petecheslock** [comment]
I think you're on the right track. For another datapoint - after restarting the cluster to pick up the new node class tags set.  We ran (running) curator again on indices older than x days and seeing a similar things happen even with there being nodes in the cluster with the proper class assigned.   Maybe just due to the sheer number of indices and nodes?  We don't see it on a dev cluster of 100 indices and like 6 systems (yet).  But the workaround can work for me in the meantime.   

Thanks!

**Comment by petecheslock** [comment]
Actually - i take that back - after restarting the cluster - with the tags set, it's cranking thru the indexes at a rate of one a second (which is far better than before) and does not show likes it's slowing down.  So i think mostly related to when you don't have the node applied with that tag yet that may exacerbate the problem.

**Comment by dakrone** [comment]
@petecheslock okay, curator [3.0.0](https://github.com/elastic/curator/releases) was released, which batches these requests instead of sending them one-at-a-time. This should fix this for the case when the tag is not set on a node and it keeps taking longer and longer, because it will only cause a single cluster state update.

I'm going to close this for now, feel free to re-open or open a new issue!

**Comment by petecheslock** [comment]
Thanks @dakrone 👍
