### ISSUE TITLE
[GEO] Update parameters and defaults for geo_point mapping

### ISSUE THREAD

**Issue by nknize** [elastic/elasticsearch#9859]
```geo_point``` mapping currently has 11 parameters (http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-geo-point-type.html) most of which are causing mass confusion for 90% of the elasticsearch user base.

Additionally, for most use-cases, the defaults are consuming large amounts of resources leading to scaling problems over time (unless the user really understands what is going on under the covers - which most don't).  This enhancement will update the default ```geo_point``` parameter mappings and rework the geohash logic to reduce resource consumption and improve the overall performance for ```geo_point```.  

```geo_shape``` mapping will be worked as a separate issue (which has a large set of its own issues)

**Comment by colings86** [comment]
Maybe it's worth also combining the normalise and validate options? Especially since they don't work together. We could have, for example, just the `validate`, `validate_lat` and `validate_lon` options and have the accepted values as `error`, `normalise`, `no`.

Also do we need three settings for validate? Are there really use cases where people need to validate or normalise latitudes and not longitudes? Could we have just a single `validate` option which works on  both lat and lon?

**Comment by clintongormley** [comment]
Is there ever a reason why you would want to accept invalid geopoints?

**Comment by RolphH** [comment]
Is geopoint [null, null] considered to be invalid, then yes, there is a reason. In some occasions we don't have a geopoint (for example when your geoip database is not up-to-date and you cannot resolve an IP to a geopoint ). Result is [null, null]
