### ISSUE TITLE
Stable master health indicator reports problems even on planned master failovers 

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#98636]
Today the stable-master health indicator reports `yellow` health if it sees the elected master change 4 times in 30 minutes. However, this could be caused by planned activity such as a rolling restart, and in that case we should not consider a sequence of master failovers as a sign of ill health.

I think we can solve this by refining this check to disregard master nodes that have restarted since they were master, or are no longer in the cluster at all. Restarting the master will always trigger a failover, and the stable-master indicator need not worry about whether the node restart was planned or not; separately, unplanned node restarts are definitely a sign of ill health, but that applies whether the node was the elected master or not. Similarly, if a node is no longer in the cluster then either it is no longer running (again, whether that's planned or not is irrelevant to the stable-master indicator) or else it is running and failing to join the cluster (and hence reporting its own ill health).

**Comment by masseyke** [comment]
We probably ought to have an indicator reporting unplanned node restarts. We don't currently have that. Do we have any way in the elasticsearch code to know if a restart was planned though?
Thinking through how to do this one, on a master change seen in `MasterHistory::clusterChanged`. I'm assuming in a containerized environment nodes don't actually keep the same id across restarts (since to elasticsearch it appears to be an entirely new machine). So we need to make the assumption that two nodes with the same name are intended to be the same node. I assume we'd need to:

1. Check if previousMaster is gone from the cluster. This is the case if no node in ` event.state().nodes()` has the same name as previousMaster. In this case, we'll remove previousMaster from the master history and add the new one.
2. Check if previousMaster has been restarted and has been replaced as master. This is the case if there is a node in the cluster state that has the same value for `getName` but a different one for `getEphemeralId`. In the case, we'll also remove previousMaster from the master history and add the new one.
3. Check if the new master is already in the master history but has been restarted. This is the case if any node is already in the history that has the same name but different ephemeral id. In that case, we'd remove the old one and add the new one.

**Comment by DaveCTurner** [comment]
> We probably ought to have an indicator reporting unplanned node restarts. We don't currently have that. Do we have any way in the elasticsearch code to know if a restart was planned though?

We could for instance disregard node departures after the node was marked for shutdown in the shutdown API.

> So we need to make the assumption that two nodes with the same name are intended to be the same node.

For the master-stability thing I don't think we need to care about the node name, we can just compare the ephemeral IDs of past masters with the ephemeral IDs of the nodes currently in the cluster.
