### ISSUE TITLE
ESQL: replace Float/Double NaN with null

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#98698]
### Description

Floating number (Float and Double) provide a special, out of band value - NaN, Not-a-Number.

This occurs typically when dividing a number by zero; integer numbers don't have one and instead thrown an error.
To make things consistent, I propose we treat and convert NaN internally to null so it never reaches the user.
Several arguments to support this:
- JSON doesn't allow NaN (nor -Inf or +Inf for that matter)
- ES doesn't allow ingestion of non-finite double or float (regardless of whether JSON is used or not) - see NumberFieldMapper for [floats](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java#L584)  and [doubles](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java#L714).

**Comment by not-napoleon** [comment]
As I said at the meeting yesterday, I think it's less important which option we pick, so long as we pick one and do it consistently in all functions. 

This has an advantage that it's easier to test - if nothing should return `NaN`, we can just add an assert to the unit tests that we never get back a `NaN`, rather than having to think about each case and if it should be `NaN` or `null`.

Would we also collapse the infinities into `null`?

**Comment by bpintea** [comment]
Just noting this for future lookups:

> Would we also collapse the infinities into null?

We practically have: https://github.com/elastic/elasticsearch/blob/722853e2530e5c8b052cab77298955c959cfe00f/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/math/Pow.java#L77-L83

**Comment by nik9000** [comment]
Save for a few bugs, I believe we've done this work.
