### ISSUE TITLE
Cosine similarity is not calculated correctly

### ISSUE THREAD

**Issue by IvankoPo** [elastic/elasticsearch#99140]
### Elasticsearch Version

8.9.1

### Java Version

_bundled_

### OS Version

elastic docker image

### Problem Description

Cosine similarity is calculated incorrectly, the score is highly inflated for completely irrelevant results the score is always higher than 0.9

I use knn search
```
dims: 1536 (OpenAI), 
index: True
```

My search query is for example "My name is Jonh".
The results come up 

"Hello check" _score: 0.91840607
"Hi mark" _score: 0.917526

But if I calculate the cosine similarity itself the results are as follows 
between "My name is Jonh" and "Hi mark" 0.5824739317690164.
between "My name is Jonh" and "Hello check" 0.581567532224248749.

According to the documentation, elastik considers cosine similarity as follows
(1 + cosine(query, vector)) / 2

My similarity calculation function looks like this

```
from scipy import spatial

def calc_distance(em1, em2):
    return (1 + spatial.distance.cosine(em1, em2)) / 2
```

### Steps to Reproduce

```
 {
  "properties": {
    "message_text": {
      "type": "text"
    },
    "message_vector": {
      "type": "dense_vector",
      "dims": 1536,
      "index": true,
      "similarity": "cosine"
    }
  }
}
```

Inserting data
```
POST _doc
{
    "message_text":  "Hi mark",
    "message_vector": [...]
}

{
    "message_text":  "Hello check",
    "message_vector": [...]
}
```

Search
```
q = {
    "field": "message_vector",
    "query_vector": get_openai_embedding("My name is Jonh"),
    "k": 3,
    "num_candidates": 10

}

client.knn_search(index="chat_test", knn=q, fields=["message_text"], source=False)
```

**Comment by pmpailis** [comment]
Hello 👋 

Thank you so much for your interest in Elasticsearch & for reporting this potential issue!

As you mentioned Elasticsearch computes a normalized cosine similarity instead, based on the formula below, so that the resulting values are bound to [0, 1]:
```
normalized_cosine_similarity = (1 + cosine_similarity(em1, em2)) / 2
```
For reference, the discussion/implementation for these changes can be found in these Lucene tickets: [original implementation](https://github.com/apache/lucene/issues/11183) & [normalization added](https://github.com/apache/lucene/issues/11184).

I was able to replicate the case you provided with much smaller vectors as well:
```
query_vector = [1, 1, 1]
doc_vectors = [  [1, 1, 1], [1, 1, 2], [2, 1, 1], [2, 0, 2]  ]
```
where the computed cosine similarities from Elasticsearch are respectively: `[1, 0.9714, 0.9714, 0.9082]`, the exact (non-normalized) cosine similarities are: `[1, 0.9428, 0.9428, 0.8164]` & the results from the formula you provided are `[0.5, 0.5285, 0.5285, 0.5917]`

On the code snippet you provided it seems that you're using scipy's **cosine distance** instead of **cosine similarity**. Based on [scipy's documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cosine.html) this is defined as the complement of cosine similarity, i.e.  1 - cosine_similarity(em1, em2) - hence why the score for the same vector is the smallest one, 0.5).

If you adjust the provided script to account for that (i.e.` (1 - cosine_distance) ` or if you experiment directly with `numpy`'s implementation the numbers match those reported in the `_score` attribute on your Elasticsearch results.  E.g.:
```
import numpy as np
def np_cosine_similarity(em1, em2):
    return np.dot(em1, em2) / (np.linalg.norm(em1) * np.linalg.norm(em2))

from scipy import spatial
def scipy_cosine_similarity(em1, em2):
    return 1 - spatial.distance.cosine(em1, em2))
```
then using any of the above with Elastic's normalization formula should yield the same results:
```
((1 + scipy_cosine_similarity) / 2) == ((1 + np_cosine_similarity) / 2)
```
Overall, we can directly compare Elasticsearch's cosine similarity scores, but when trying to interpret them or use them as reference for external comparisons, please be aware of this added normalization step. (you can revert/remove the normalization factor if needed using something like: `2 x score - 1`
