### ISSUE TITLE
ML service should auto launch another ML allocation process when one of the ML allocation process is   crashed 

### ISSUE THREAD

**Issue by wjp719** [elastic/elasticsearch#99419]
### Description

in 8.9.1， when I kill one of ML allocation process, I found it was marked as failed in kibana, but no other ML allocation process starts

![image](https://github.com/elastic/elasticsearch/assets/9303466/44b7bbf4-ad04-4df7-9bc8-4a0a7deba637)

I think ML service should auto launch another ML allocation process when one of the ML allocation process is   crashed

**Comment by dennywu2966** [comment]
The background is that we hope to make ML node more robust in real production environments, like how we handle normal ES node: we have an ES controller which will monitor and resume an ES node if it crashes. 

We may use a similar way with the controller, but it might be better to solve it inside ES itself, as we think pytorch processes are internal entities of the node and thus the ES cluster, which may be a better place to maintain its internal states.

**Comment by droberts195** [comment]
Thank you for opening this issue.

The behaviour is different depending on whether the whole node leaves the cluster or if the process crashes. If a whole node leaves the cluster, for example due to hardware failure or machine shutdown, then we rebalance the model allocations on that node to a different node.

But you are correct that if a `pytorch_inference` process crashes on one node then we just mark it as failed and don't attempt to rebalance the lost allocations to another node or the same node. The reasoning for this was that a crash would indicate some fatal problem in the inference model that would make the process crash over and over again. We want to avoid the situation where a `pytorch_inference` process crashes and restarts indefinitely, because transferring the multi-hundred megabyte model out of an Elasticsearch index and into the separate process is expensive and doing it repeatedly would place an unnecessary burden on the cluster.

However, I think you are right that we should retry starting the process at least a few times if it crashes, just in case the crash was due to some external event (like a user killing the process) or a really rare bug that only causes a crash very occasionally.

We will change the behaviour in a future version of Elasticsearch to either simply restart the process on the same machine or rebalance the cluster with the number of allocations that were lost by the crash. We'll need to look more deeply into the code to decide which is best given the way allocations are balanced across nodes, but we'll do _something_ to make it more robust to rare crashes.

**Comment by davidkyle** [comment]
#104433 added automatic restarts of the `pytorch_inference` process after a crash up to 3 times in a 24 hour period. Notification messages are create for each restart. If the process crashes more than 3 times in 24 hours it is considered a pathological case will not be restarted, again a notification will be created for this case. This enhancement is in 8.13.0.
