### ISSUE TITLE
Add option for nGram tokenizer to always tokenize whole word

### ISSUE THREAD

**Issue by BHSPitMonkey** [elastic/elasticsearch#9971]
It would be great if the nGram tokenizer came with an option to force creation of a whole-word token for cases when the word length falls outside the min-gram/max-gram range. Currently, we have to resort to a dual-mapping approach to make sure these tokens get created, which limits how we can construct per-field queries.

**Comment by clintongormley** [comment]
Hi @BHSPitMonkey 

I think you mean the edge-ngram tokenizer, rather than the ngram tokenizer.  When using `token_chars' to break up the string into words, you can just make the max_ngram as big as you need, which will serve your purpose.

**Comment by BHSPitMonkey** [comment]
1. Actually, no; I meant the ngram tokenizer.
2. Raising the `max_gram` (and/or lowering the `min_gram`) setting is outside the question. The problem is that, once you've decided on a min/max which suit your needs (a decision based on the specific partial-matching needs and taking storage complexity into account), you still want words outside of this window to match in their entirety.

For example: Let's say we've decided to decided to restrict partial text searching to substrings from 3 to 10 characters in length. (Going below 3 would add a considerable amount of additional tokens, and we've decided it's not very useful below that threshold.)

* You want to search for a title with the (whole) word `Me`, but you can't; `Me` won't produce any token at all, despite being a full word (which the standard tokenizer would pick up).
* You want to search for `incandescent`, but you can't; However, you can search for `candescent`, or any other substring of length [3,10]. But what good does that do if the user provided the whole word in their query?

So, in order to accommodate these two seemingly reasonable scenarios, we currently have to index our text into two separate (identical) fields, using a standard tokenizer on the other one. This is a hack that comes with added storage/bandwidth costs, makes filtering on these fields harder, and adds complexity to queries (for instance, now you can't easily query by field anymore without transforming the query and introducing an `OR` subquery). An option like the one I'm describing would be really helpful to have.

**Comment by clintongormley** [comment]
Hi @BHSPitMonkey

**Comment by clintongormley** [comment]
Hi @BHSPitMonkey 

OK - I understand the requirement to include whole terms which are shorter than the `min_gram` (which are currently dropped from the token stream) but the same doesn't apply to words that are longer, because they will have ngrams applied anyway, for instance:

    DELETE t
    
    PUT t
    {
      "settings": {
        "analysis": {
          "tokenizer": {
            "my_ngrams": {
              "type": "ngram",
              "min_gram": 3,
              "max_gram": 4,
              "token_chars": [
                "letter"
              ]
            }
          },
          "analyzer": {
            "my_ngrams": {
              "tokenizer": "my_ngrams"
            }
          }
        }
      }
    }
    
    GET /t/_analyze?text=my tests&analyzer=my_ngrams
    
The above returns:

    {
       "tokens": [
          {
             "token": "tes",
             "start_offset": 3,
             "end_offset": 6,
             "type": "word",
             "position": 1
          },
          {
             "token": "test",
             "start_offset": 3,
             "end_offset": 7,
             "type": "word",
             "position": 2
          },
          {
             "token": "est",
             "start_offset": 4,
             "end_offset": 7,
             "type": "word",
             "position": 3
          },
          {
             "token": "ests",
             "start_offset": 4,
             "end_offset": 8,
             "type": "word",
             "position": 4
          },
          {
             "token": "sts",
             "start_offset": 5,
             "end_offset": 8,
             "type": "word",
             "position": 5
          }
       ]
    }


So yes, the word `my` has just been dropped, but `tests` still produces all of the tokens you need.

I agree that we should probably add an option to include the whole token if it is shorter than `min_gram`

**Comment by clintongormley** [comment]
Oh I think I've just got your point about including the whole token if it is above `max_gram`.   

Hmm, the typical approach to this would be just to index the field twice: once with standard analyzer and once with ngrams, then to use a `multi_match` query in `most_fields` mode to query both fields at once.

@rmuir what's your take on this?

**Comment by rmuir** [comment]
I don't understand the aversion to multi fields approach here. with n=3/4 you already have two analysis fields stuck inside of one IMO (one at n=3, one at n=4). If you have another field with standardanalyzer, you have a lot of flexibility, e.g. you can query both at the same time, or just the standardanalyzer field for a more 'exact' query (e.g., user puts term in quotes).

Of course, this thing seems to be complicated by a few issues. First of all, IMO n-grams shouldnt really pre-tokenize much at all. This doesn't make a lot of sense to me since n-grams is a different tokenization technique, just let it be different than tokenizing on words (so don't do it in n-grams!). 

If we try to be too fancy and handle everything just within n-grams, i'm afraid the code will become super-complicated and stagnate and become unmaintainable. For a real example of this, look at CJKBigramFilter.java in lucene (it has some of the logic proposed here, in its miniature world of n=1/n=2). I wrote it from scratch and really tried to make it simple and easy. Its hairy as hell :(

**Comment by clintongormley** [comment]
@rmuir many thanks.  Closing
