### ISSUE TITLE
Ability to restore specific shard(s) from snapshot

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#9984]
Shard corruption is not common but it can happen and we have seen situations where both primary and replica shards got corrupted.  When this occurs, it will be nice to be able to restore specific shard(s) or a single shard via snapshot restore without having to restore the entire index which can take a long time esp. for indices that are TBs in size (eg. 20+ TB)

**Comment by gmenegatti** [comment]
+1

**Comment by ChrisRimondi** [comment]
+1

**Comment by iostat** [comment]
Hi! I'd love to take this task on, however, I'm stuck at a bit of a crossroads when it comes the actual implementation.

Here's a rundown of my understanding of the situation and work involved in this feature. I'd love some feedback on whether I'm right or wrong on some points, completely talking out of my ass, etc.; as well as some guidance on the preferred approach:

When a snapshot of an index is taken, it dumps blobs of the data of each shard, along with the entirety of an index's metadata (mappings, aliases, etc.).

The current snapshot restoration logic effectively:
1. If the index that's being restored exists, replaces its metadata with that which is in the snapshot; if not, it creates a new index with the same name and metadata in the snapshot.
2. Allocates new shards, and fills them with the data in the snapshot's blobs, and updates index<->shard routing entries to the newly restored shards.

This means that fundamentally, to restore specific shards, I just need to update the routing for the shards I want to restore instead of basically creating a whole new index.

Now, inside [o.e.s.RestoreService.restoreSnapshot$ClusterStateUpdateTask.execute (at line 249)](https://github.com/elastic/elasticsearch/blob/4ea19995cff603ce8472e985c902dd2f8fadebee/core/src/main/java/org/elasticsearch/snapshots/RestoreService.java#L249-L249), there's an `ignoredShards` set that gets generated during the restore operation which is used in conjunction with the `partial` option for when a snapshot has shards in it that are corrupt or otherwise unrestoreable... more on this in a sec.

The RestoreService is currently very intimately coupled with all of the other conveniences that the snapshot restore feature gives you (such as renaming the index, changing the number of replicas, etc.) that (IMO) do not apply to the operation of restoring specific shards. In the scenarios that I can imagine for restoring specific shards, one would just want a no-bullshit, replacement of (a) corrupt shard(s), ASAP, without affecting the rest of the index properties.

Going back to the `partial` option. Because the snapshot restore is basically creating a brand new index, it doesn't care about the shards which already exist, regardless if they're healthy/unchanged/etc. If the copy of the shard in the snapshot is corrupt, ES will just initialize an empty shard for that data. This means that I am left with two choices:

A) Modify RestoreService, RestoreRequest, RestoreSnapshotRequest, TransportRestoreSnapshotAction, and probably others to take a "onlyRestoreShards" field. If this field is given, it disables all the conveniences like changing replica counts, renaming, etc (after giving the operator a stern warning if they try to combine them, of course). as well as somehow short circuiting the "create an empty shard" logic, instead redirecting the existing/unaffected shards to point to the "new" index.

The drawback to this is that, due to the previously mentioned intimate coupling, this will make the RestoreService even more complicated than it already is, not to mention all the additional validations and potential edge cases that will need to be considered inside the Requests and their builders.

*HOWEVER*, it may potentially open up the additional possibility of keeping existing shards (assuming they're healthy) when doing a snapshot restore with `partial` enabled instead of just blanking them out if the snapshot is useless. Furthermore, it means less boilerplate written, and a simpler API (in terms of less endpoints to be aware of) for the administrator.

b) Create a RestoreShardsService/RestoreShardsRequest/etc./etc./etc. along with a new REST endpoint such as /_snapshots/etc/etc/_restore_shards as well as a corresponding Transport operation.

This has the benefit of a simpler API for the end user, a cleaner separation of concerns, much simpler code for the restoration logic (no short circuits or retrofits) BUT it does add a significant quantity of boilerplate. Also going with this option means that the possibility of smarter restores of invalid shard snapshots is out of the question.

Thanks for taking the time to read this wall of text!

**Comment by clintongormley** [comment]
Closing in favour of #15653
