### ISSUE TITLE
Add timeouts to refresh, flush and optimize apis

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#9997]
At the moment when the refresh, flush and optimize apis are executed and there is a cluster block (for example no master block) then these apis fail immediately. It would be nicer if those apis would wait for a defined timeout period and see if the cluster block is resolved within that period. This should be similar in how deal with cluster blocks in the index, update and delete apis (which have a timeout parameter).

**Comment by clintongormley** [comment]
These requests do now wait instead of failing immediately, but the timeout is not configurable.

**Comment by hub-cap** [comment]
This feature request is an interesting idea but since its opening we have not seen enough feedback that it is a feature we should pursue. We prefer to close this issue as a clear indication that we are not going to work on this at this time. We are always open to reconsidering this in the future based on compelling feedback; despite this issue being closed please feel free to leave feedback on the proposal (including +1s).
